### ISSUE TITLE
ID is shown as an object when fetching models with nested relationships

### ISSUE THREAD

**Issue by alhill** [strapi/strapi#4118] opened 2019-09-27 08:28 UTC
**Describe the bug**
If you create a group and one of the fields is a relationship with a model which have inside more relationships, when you fetch this data, it shows the id of the nested relationship as a object with the order of the character as key and the character as a value, in the same way as if you do {..."idString"}

**Steps to reproduce the behavior**
1. Create a group with a relation to a model with more relationships
2. Add the group to a model

**Expected behavior**
The nested relationship should show the id of the related content as a normal string

**Postman response**
```
[
    {
        "_id": "5d8db9bf0dc976285007b04d",
        "items": [
            {
                "_id": "5d8db9bf0dc976285007b04e",
                "notes": "qwe",
                "qty": 2,
                "createdAt": "2019-09-27T07:26:55.574Z",
                "updatedAt": "2019-09-27T07:26:55.601Z",
                "__v": 0,
                "product": {
                    "_id": "5d6fbbe94e7c9554792b22b4",
                    "name": "product11",
                    "description": "tggyyfff77",
                    "createdAt": "2019-09-04T13:28:09.311Z",
                    "updatedAt": "2019-09-17T13:02:42.835Z",
                    "__v": 0,
                    "organization": {
                        "0": "5",
                        "1": "d",
                        "2": "6",
                        "3": "e",
                        "4": "2",
                        "5": "f",
                        "6": "e",
                        "7": "2",
                        "8": "8",
                        "9": "e",
                        "10": "6",
                        "11": "7",
                        "12": "5",
                        "13": "7",
                        "14": "3",
                        "15": "8",
                        "16": "7",
                        "17": "a",
                        "18": "c",
                        "19": "7",
                        "20": "6",
                        "21": "0",
                        "22": "3",
                        "23": "7"
                    },
                    "productgroup": {
                        "0": "5",
                        "1": "d",
                        "2": "6",
                        "3": "f",
                        "4": "b",
                        "5": "b",
                        "6": "d",
                        "7": "7",
                        "8": "4",
                        "9": "e",
                        "10": "7",
                        "11": "c",
                        "12": "9",
                        "13": "5",
                        "14": "5",
                        "15": "4",
                        "16": "7",
                        "17": "9",
                        "18": "2",
                        "19": "b",
                        "20": "2",
                        "21": "2",
                        "22": "b",
                        "23": "2"
                    },
                    "factory": {
                        "0": "5",
                        "1": "d",
                        "2": "6",
                        "3": "e",
                        "4": "4",
                        "5": "5",
                        "6": "7",
                        "7": "c",
                        "8": "7",
                        "9": "6",
                        "10": "2",
                        "11": "f",
                        "12": "2",
                        "13": "d",
                        "14": "4",
                        "15": "8",
                        "16": "f",
                        "17": "0",
                        "18": "6",
                        "19": "8",
                        "20": "8",
                        "21": "8",
                        "22": "6",
                        "23": "d"
                    },
                    "client": {
                        "0": "5",
                        "1": "d",
                        "2": "6",
                        "3": "e",
                        "4": "4",
                        "5": "2",
                        "6": "4",
                        "7": "0",
                        "8": "2",
                        "9": "8",
                        "10": "8",
                        "11": "e",
                        "12": "d",
                        "13": "e",
                        "14": "4",
                        "15": "7",
                        "16": "1",
                        "17": "e",
                        "18": "7",
                        "19": "2",
                        "20": "6",
                        "21": "1",
                        "22": "0",
                        "23": "3"
                    },
                    "sku": "12345",
                    "id": "5d6fbbe94e7c9554792b22b4"
                },
                "id": "5d8db9bf0dc976285007b04e"
            }
]```

**System**
- Node.js version: v10.5
- NPM version: v6.7
- Strapi version: Beta 16.6
- Database: MongoDB
- Operating system: Windows 10

**Possible solution**
Now the id recovers its normal form with Object.values(strangeObjectID).reduce((a,b) => a+b, ""), maybe it lacks this in some point of the code. Or maybe there's a playful spread operator messing the string ID

**Comment by sunsgs** [comment] 2019-09-27 17:59
this is happening also if you do not use groups.

**Comment by nameszian** [comment] 2019-09-29 23:14
It is also happening with relationships, it seems to be a problem of Strapi with MongoDb when it comes to resolving references / relationships, since everything seems correct in the database.

Can be tested by following the getting started tutorial (relationship between `Restaurant` and `Category`) with `strapi beta 3.0.0-beta.16.6`:

Example of a response of a request to `find - GET /restaurants` (restaurants it's incorrect, each element of the array is one character of the referenced _id):
```
{
    "_id": "5d91008856252d9b995ae553",
    "id": "5d91008856252d9b995ae553",
    "name": "name here",
    "description": "description here",
    "restaurant_hours": [],
    "createdAt": "2019-09-29T19:05:44.483Z",
    "updatedAt": "2019-09-29T19:06:12.921Z",
    "__v": 1,
    "image": { ... },
    "categories": [
    {
        "restaurants": [
            {
                "0": "5",
                "1": "d",
                "2": "9",
                "3": "0",
                "4": "f",
                "5": "b",
                "6": "4",
                "7": "8",
                "8": "5",
                "9": "6",
                "10": "2",
                "11": "5",
                "12": "2",
                "13": "d",
                "14": "9",
                "15": "b",
                "16": "9",
                "17": "9",
                "18": "5",
                "19": "a",
                "20": "e",
                "21": "5",
                "22": "4",
                "23": "8"
            }
         ],
    "_id": "5d90fdc656252d9b995ae552",
    "name": "French food",
    "createdAt": "2019-09-29T18:53:58.399Z",
    "updatedAt": "2019-09-29T19:06:12.871Z",
    "__v": 0,
    "id": "5d90fdc656252d9b995ae552"
}
```

**Comment by alhill** [comment] 2019-09-30 12:54
After testing it in other endpoints, I have seen the same problem too, not only in groups. I have edited the title to make it more generic.

**Comment by nameszian** [comment] 2019-10-01 22:13
Yes like I said, the problem is in the process of resolving a relationship, I didn't test it with groups, but with simple relationships (ref in mongo) the problem is there :(

**Comment by lauriejim** [comment] 2019-10-03 10:04
Hello @alhill and @nameszian !
Can I have your model definition, please. I need to know the type of relations you have between your models.
And I also need to know you you created your entries. Via the admin panel or via an HTTP request to the generated API.
If vias HTTP request, I need to know the request you did (how you formated your body)

**Comment by alhill** [comment] 2019-10-03 11:07
I think it happens in one to one and one to many, unidirectional or bidirectional.
In my case, almost every entry is created via HTTP request, sending a fetch with post method with a application/json body, with the relation defined passing the id to relate as value of the related field.

The place where fails is sanitize-entity.js, in strapi-utils/lib. Writing `if (typeof plainData === 'string'){ return data }` in line 7 of this file seems to fix the problem. I have been trying it in this way and everything seems to work flawlessly but I don't know if it breaks any feature somewhere.

**Comment by nameszian** [comment] 2019-10-03 12:29
@lauriejim In my case I found the problem following the [tutorial](https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start-tutorial.html#_4-create-a-new-content-type-called-category): 
`You are now ready to add the second field, a Relation field for creating a Many to Many relationship between the Category and Restaurant Content Types.`

And I created everything from the Admin panel. 

*The only difference to the tutorial is that I used MongoDb and the tutorial uses SQLLite (--quickstart).

**Comment by lauriejim** [comment] 2019-10-03 12:42
Okay thank you! I will reproduce the tutorial and see what happens.

**Comment by lauriejim** [comment] 2019-10-03 12:55
Okay thank you. I successfully reproduced the issue.
If you fetch the data from the category it works.
I think it's if you fetch data that have `"dominant": true,` it fail.
I will ping @alexandrebodin  on this issue.
Thank you for reporting it. Appreciate.

**Comment by nameszian** [comment] 2019-10-03 17:10
Thank you for the awesome system!

**Closed** 2019-10-04 09:56 UTC
Labels: priority: high, status: confirmed, type: bug 🐛
