### ISSUE TITLE
Filters disabled when filtering for invalid / non existing input

### ISSUE THREAD

**Issue by Eventyret** [strapi/strapi#20155] opened 2024-04-19 08:54 UTC
### Required System information

- Node.js version: 20.x
- Strapi version: v5.0.0-beta.4
- Database: Postgres
- Operating system: MacOS
- Is your project Javascript or Typescript: TS

### Describe the bug

500 error when filtering on relation column where other side has no entries in the database yet

`function lower(integer) does not exist` seems to be the root of the error. Looks like the generated query is trying to call `lower` on an `id` field which is an int type

### Steps to reproduce the behavior

1. Blog content-type
2. Tags content-type
3. Add many2many relation between
4. Have some blogs, no tags yet
5. Try to add tag filter, `contains (insensitive)`

You will now see that filters are disabled, so you would have to go back 

![image](https://github.com/strapi/strapi/assets/977232/e684e526-3351-48c4-b845-c65516b6ff9c)
### Expected behavior

I would expect to have filtered enabled to change filters again.
Screenshot of the same search but for something that does exist
![image](https://github.com/strapi/strapi/assets/977232/43e21103-079e-49d6-bea7-02a500fffa52)

**Comment by Feranchz** [comment] 2024-07-05 08:21
@Eventyret I couldn't reproduce this on latest version. We fix some bugs on the filters in the last weeks so maybe this was fixed too, can you double check?

In case is still happening to you, can you share with me the shape of your tag content type?

**Comment by Feranchz** [comment] 2024-08-19 15:52
Hey @derrickmehaffy, We are trying to replicate this issue and we can't. I think we fixed this on #20548. Can we have the support team confirmation so we can close this issue? 🤔

**Comment by derrickmehaffy** [comment] 2024-08-19 16:00
Yup I'll try and reproduce it after the Monday meeting

**Comment by derrickmehaffy** [comment] 2024-08-19 16:28
Yup looks like it's working on rc.10, I'll go ahead and close this.

**Closed by derrickmehaffy** 2024-08-19 16:28 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-manager, version: 5
