### ISSUE TITLE
[Review Workflows] Super Admin users can't modify an entry's stage for non-default workflows

### ISSUE THREAD

**Issue by remidej** [strapi/strapi#20881] opened 2024-07-25 15:17 UTC
As a Super Admin, I shouldn't see "you don't have permissions to update the stage" on an entry's stage.

This problem does not occur when using the default review workflow created by Strapi, but only when using workflows I created myself.

https://github.com/user-attachments/assets/a57d667a-1b8e-4456-9982-8eefc543065b

At the same time we could add this[ tiny UX refinement](https://www.figma.com/design/HIxlFS0OIItVtBUhKzMGZw/Review-Workflows-(v5)?node-id=1-2&t=Y3JSJN3jNyAijzyE-0)

**Comment by Marc-Roig** [comment] 2024-08-19 07:54
I am not able to reproduce this issue on the latest v5 version, so closing this issue for now!

**Closed by Marc-Roig** 2024-08-19 07:54 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:review-workflows, version: 5
