### ISSUE TITLE
User password can be seen

### ISSUE THREAD

**Issue by deebov** [strapi/strapi#4432] opened 2019-11-02 17:07 UTC
**Describe the topic**
Currently, admins can see and change users password. That is not secure, of course. I'd like to know if there's any way to hide users password so nobody can see or change them.

**Comment by pouyamiralayi** [comment] 2019-11-02 17:17
> admins can see

admin sees the hash version of password, not the plain text.

there is an open discussion about this [here](https://github.com/strapi/strapi/issues/4341).
cheers!

**Comment by derrickmehaffy** [comment] 2019-11-02 17:17
closing as duplicate of https://github.com/strapi/strapi/issues/4341

**Closed by derrickmehaffy** 2019-11-02 17:17 UTC

**Comment by deebov** [comment] 2019-11-02 17:40
> > admins can see
> 
> admin sees the hashed version of password, not the plain text.
> 
> there is an open discussion about this [here](https://github.com/strapi/strapi/issues/4341).
> cheers!

Thanks for the reply. But showing hashed password won't solve the problem at all. Because admins can still change it and replace with a different hash or plain text

**Comment by derrickmehaffy** [comment] 2019-11-02 17:41
The issue linked goes into detail about this, it's not intended and it will be removed eventually.
