### ISSUE TITLE
mongodb: unique constraint not updated in production deployment

### ISSUE THREAD

**Issue by RileyMShea** [strapi/strapi#7386] opened 2020-08-08 22:31 UTC
**Describe the bug**
Adding a unique constraint to an existing field, via admin panel or models, is updated in development, but is not applied when deployed to production server via docker(as part of docker-compose stack).  

**Steps to reproduce the behavior**

From dev server:

1. create a collection with a text field, no constraints.
2. add an entry to this collection
3. build into  production docker image:
```Dockerfile
FROM strapi/strapi:3.1.1-node12

WORKDIR /some-path

COPY ./package.json ./
COPY ./yarn.lock ./

ENV NODE_ENV production

RUN yarn install --prod

COPY . .

RUN yarn build --clean

EXPOSE 1337

CMD ["yarn", "start"]
```
4. push and deploy to production server
5. still on dev server, update the field to be unique and required directly on model or via admin panel
6. verify unique constraint works in development
7. commit and rebuild with updated unique setting in models
8. re-deploy new image to production
9. unique constraint is not reflected in production despite new api/models having the unique constraint

**Expected behavior**
I would expect adding unique and required constraints to be reflected when pushed to production.  This is not the case. 

There is no conflicts for the constraint(existing duplicate of field that should be getting a unique index applied)

**Code snippets**

Development successfully applies unique constraint:
```json
[
        {
                "v" : 2,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "strapi.projects"
        },
        {
                "v" : 2,
                "unique" : true,
                "key" : {
                        "name" : 1
                },
                "name" : "name_1",
                "ns" : "strapi.projects",
                "background" : true
        }
]
```

Production failing to get constraint upon update
```json
> db.projects.getIndexes()
[
        {
                "v" : 2,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "strapi.projects"
        },
        {
                "v" : 2,
                "key" : {
                        "name" : 1
                },
                "name" : "name_1",
                "ns" : "strapi.projects",
                "background" : true
        }
]
```
**System**

- Node.js version: LTS v12 via official strapi/strapi 3.1.1-node12 image
- NPM version: 6
- Strapi version: 3.1.1-node12
- Database: mongo:4.2.7-bionic as part of Docker-compose stack
- Operating system: Ubuntu 18.04

**Additional context**
A separate MongoDB instance is used for each environment.

similar or same as issue #5863

**Comment by derrickmehaffy** [comment] 2020-08-10 13:45
Closing as duplicate of: https://github.com/strapi/strapi/issues/5863
And also likely related: https://github.com/strapi/strapi/issues/1114

**Closed by derrickmehaffy** 2020-08-10 13:45 UTC
