### ISSUE TITLE
Maximum length error in content manager

### ISSUE THREAD

**Issue by MechJosh0** [strapi/strapi#1694] opened 2018-08-03 19:15 UTC
**Informations**
- **Node.js version**: 9.11.2
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.13.0.1
- **Database**: MySQL
- **Operating system**: Ubuntu

**What is the current behavior?**
When you try to edit an item which has a field with a maximum length with a blank entry it errors due to the length of the items value is blank/null/undefined.

Console error:
```
Uncaught TypeError: Cannot read property 'length' of null
    at :1337/admin/content-manager/main.js:52
    at :1337/admin/content-manager/main.js:18
    at :1337/admin/content-manager/main.js:18
    at cr (:1337/admin/content-manager/main.js:18)
    at Ll (:1337/admin/content-manager/main.js:18)
    at i (:1337/admin/content-manager/main.js:52)
    at :1337/admin/content-manager/main.js:52
    at :1337/admin/content-manager/main.js:18
    at cr (:1337/admin/content-manager/main.js:18)
    at :1337/admin/content-manager/main.js:18
```

**Steps to reproduce the problem**
1. Create a new content type with various fields, one of them must be a `string` with a maximum length - the field can be blank therefore it is not required.
2. Create a new item in this content type, but do not enter anything inside our field which has a maximum length.
3. Open to edit the item you just created, click save -> **This will create the error**
4. If you go the textarea which has our maximum length requirement, you can enter a character and then remove it, click save and this will save.

Note - Using the step 4 hack solution, you can now open and edit freely. The bug will keep on occurring until you do step 4, but from that point onwards it's perfectly fine.

**What is the expected behavior?**
Step 3 should save the item.

**Suggested solutions**
Do not check the length of a value if it is blank and not required.

**Comment by soupette** [comment] 2018-08-06 11:06
Hi @MechJosh0 I wasn't able to reproduce your issue by following your steps

**Comment by MechJosh0** [comment] 2018-08-07 19:14
@soupette Here is a video of me reproducing the bug from a fresh install -> https://youtu.be/pTxsFWbQUnU

Sorry for the lag in the video.

**Comment by derrickmehaffy** [comment] 2018-08-08 02:11
@MechJosh0 two things related to your video:

1) Can't use spaces in modelname
2) Can't use spaces in field name

**Comment by MechJosh0** [comment] 2018-08-08 06:27
@derrickmehaffy this is just an example, when you save it fixes the spaces. The bug is still there when you try to use spaces or not.

**Comment by soupette** [comment] 2018-08-10 11:17
Hi @MechJosh0 I can't reproduce your issue. I have followed your steps and it works correctly on my side.

Can you check if this still occurs?

**Comment by lauriejim** [comment] 2018-09-17 09:02
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.

**Closed by lauriejim** 2018-09-17 09:02 UTC
Labels: priority: medium, status: can't reproduce, type: bug 🐛

**Comment by echappen** [comment] 2018-11-28 17:09
I am also seeing this behavior in one of our models. Below is the current model schema.

Node.js version: 8.11.1
npm version: 5.6.0
Strapi version: 3.0.0-alpha.14.5
Database: Postgres
Operating system: Darwin 17.7.0

```
{
  "connection": "default",
  "collectionName": "topics",
  "info": {
    "name": "topic",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "title": {
      "default": "",
      "type": "string",
      "maxLength": 1000
    },
    "body": {
      "default": "",
      "type": "text",
      "maxLength": 15000
    },
    "slug": {
      "default": "",
      "unique": true,
      "type": "string",
      "required": true,
      "maxLength": 1000
    },
    "a9_id": {
      "default": "",
      "unique": true,
      "type": "integer",
      "required": true
    },
    "content_id": {
      "default": "",
      "type": "integer"
    },
    "old_id": {
      "default": "",
      "unique": true,
      "type": "integer",
      "required": true
    },
    "description": {
      "default": "",
      "type": "text",
      "maxLength": 15000
    },
    "banner_image_url": {
      "default": "",
      "maxLength": 1000,
      "type": "string"
    },
    "tags": {
      "collection": "tag",
      "via": "topics",
      "dominant": true
    },
    "related_topics": {
      "collection": "topic",
      "via": "topics"
    },
    "topics": {
      "model": "topic",
      "via": "related_topics"
    },
    "alternate_slugs": {
      "collection": "alternateslugs",
      "via": "topic"
    },
    "call_to_action": {
      "default": "",
      "maxLength": 500,
      "type": "string"
    },
    "fact": {
      "default": "",
      "maxLength": 1000,
      "type": "string"
    }
  }
}

**Comment by derrickmehaffy** [comment] 2018-11-28 17:11
@echappen `Node.js version: 8.11.1`

Please test with Node 10, node 8 is no longer supported and is EOL

**Comment by echappen** [comment] 2018-11-28 17:35
@derrickmehaffy Re-ran the Strapi server using node v10.14.0 and got the same result.
