### ISSUE TITLE
Entity navigation breaking for recursive relationship

### ISSUE THREAD

**Issue by sarvesh-globant** [strapi/strapi#16405] opened 2023-04-14 18:08 UTC
### Required System information

- Node.js version: 18.14.1
- NPM version: 9.3.1
- Strapi version: 4.6.2
- Database: pgSQL
- Operating system: Ubuntu 20.04 LTS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

If a collection A entity have a relation with the same type of collection (recursive relationship One-to-One (A to A)). Pagination in `node_modules/@strapi/admin/admin/src/content-manager/components/RelationInputDataManager/RelationInputDataManager.js` 
its breaking, when we navigate to the related entity (of the same collectionType), the related entity is showing the same relations of parent entity.

### Steps to reproduce the behavior

1. Go to 'Parent' collection detailed page.
2. Click on related-entity (with same type of collection)
3. See error - Related entity is showing the same relative content as parent.

### Expected behavior

Related entity should show its own relevant content.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by Boegie19** [comment] 2023-04-17 16:59
duplicate of https://github.com/strapi/strapi/issues/16260

**Closed by Boegie19** 2023-04-17 16:59 UTC
Labels: status: duplicate
