### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined 

### ISSUE THREAD

**Issue by qaynam** [strapi/strapi#9915] opened 2021-03-31 12:17 UTC
### Describe the bug

i upload 2 images in media library page, and then I created custom content type , when i select those images in [ create an entry] page it get errors like this ↓

i cant remove those image from media library page , it got same errors ↓

```text
Something went wrong.
詳細
TypeError: Cannot read property 'toString' of undefined

    in InputModalStepperProvider
    in Unknown
    in InputModal
    in div
    in styled.div
    in InputMedia
    in D
    in Inputs
    in Inputs
    in Unknown
    in div
    in div
    in div
    in styled.div
    in div
    in div
    in div
    in styled.div
    in form
    in EditViewDataManagerProvider
    in CollectionTypeFormWrapper
    in CollectionTypeFormWrapper
    in EditView
    in EditView
    in e
    in e
    in CollectionTypeRecursivePath
    in e
    in e
    in Unknown
    in Main
    in ConnectFunction
    in ErrorBoundary
    in div
    in PluginDispatcher
    in PluginDispatcher
    in e
    in e
    in div
    in styled.div
    in div
    in div
    in styled.div
    in UserProvider
    in GlobalContextProvider
    in Admin
    in ConnectFunction
    in injectIntl(Connect(Admin))
    in e
    in PrivateRoute
    in e
    in div
    in styled.div
    in div
    in styled.div
    in Unknown
    in Theme
    in App
    in ConnectFunction
    in t
    in e
    in IntlProvider
    in LanguageProvider
    in ConnectFunction
```

__server log__

```text
[2021-03-31T11:47:53.469Z] debug GET /upload/files?_limit=10&_start=0&_sort=updated_at:DESC (67 ms) 200

[2021-03-31T11:47:53.495Z] debug GET /uploads/small_Web_d99214958e.png?129029.24500009976 (3 ms) 200

[2021-03-31T11:47:53.496Z] debug GET /uploads/small_youtube_end_card_78144df155.png?129028.17500010133 (3 ms) 200

[2021-03-31T11:47:54.167Z] debug GET /uploads/youtube_end_card_78144df155.png?129691.6650000494 (4 ms) 200

[2021-03-31T11:47:58.937Z] error error: select distinct "upload_file".* from "upload_file" where "upload_file"."id" = $1 limit $2 - invalid input syntax for type integer: "undefined"

at Parser.parseErrorMessage (/srv/app/node_modules/pg-protocol/dist/parser.js:278:15)

at Parser.handlePacket (/srv/app/node_modules/pg-protocol/dist/parser.js:126:29)

at Parser.parse (/srv/app/node_modules/pg-protocol/dist/parser.js:39:38)

at Socket.<anonymous> (/srv/app/node_modules/pg-protocol/dist/index.js:10:42)

at Socket.emit (events.js:314:20)

at addChunk (_stream_readable.js:297:12)

at readableAddChunk (_stream_readable.js:272:9)

at Socket.Readable.push (_stream_readable.js:213:10)

at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

From previous event:

at processImmediate (internal/timers.js:461:21)

From previous event:

at Sync.<anonymous> (/srv/app/node_modules/bookshelf/lib/sync.js:204:8)

From previous event:

at Child.<anonymous> (/srv/app/node_modules/bookshelf/lib/collection.js:160:12)

From previous event:

at Child.fetchAll (/srv/app/node_modules/bookshelf/lib/model.js:878:10)

at find (/srv/app/node_modules/strapi-connector-bookshelf/lib/queries.js:79:8)

at Object.findOne (/srv/app/node_modules/strapi-connector-bookshelf/lib/queries.js:66:27)

at fn (/srv/app/node_modules/strapi-database/lib/queries/helpers.js:31:54)

at Object.findOne (/srv/app/node_modules/strapi-database/lib/queries/helpers.js:15:24)

at async findEntityAndCheckPermissions (/srv/app/node_modules/strapi-plugin-upload/controllers/upload/admin.js:194:16)

at async destroy (/srv/app/node_modules/strapi-plugin-upload/controllers/upload/admin.js:86:26)

at async /srv/app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22

[2021-03-31T11:47:58.937Z] debug DELETE /upload/files/undefined (21 ms) 500
```

### Screenshots

![image](https://user-images.githubusercontent.com/33139713/113141183-5bd4f500-9264-11eb-8a5a-8c1c64670c88.png)
![image](https://user-images.githubusercontent.com/33139713/113142813-4bbe1500-9266-11eb-8216-1fbf16bdab31.png)

### System

- Node.js version: stripe docker image
- NPM version: stripe docker image
- Strapi version: 3.5.3 
- Database: postgres:12.0-alpine docker image
- Operating system: windows10 
- docker version: v20.10.5

**Comment by derrickmehaffy** [comment] 2021-04-01 20:29
@qaynam can you please provide more information to reproduce the issue?

**Comment by derrickmehaffy** [comment] 2021-07-22 21:46
No new information added, closing as unable to reproduce with existing information

**Closed by derrickmehaffy** 2021-07-22 21:46 UTC
Labels: source: plugin:content-manager, status: can't reproduce, type: help wanted

**Comment by AleksejDomash** [comment] 2021-09-21 21:04
Just got the same issue. It's possible to upload an asset, it's shown in media library, but each time I'm trying to add it to the collection item as Image, that error appears:
Something went wrong.
Details
TypeError: Cannot read property 'toString' of undefined

    in S
    in Unknown
    in m
    in div
    in styled.div
    in A
    in I
    in C
    in C
    in Unknown
    in div
    in div
    in div
    in styled.div
    in div
    in div
    in div
    in styled.div
    in form
    in b
    in y
    in y
    in T
    in T
    in t
    in t
    in b
    in t
    in t
    in Unknown
    in k
    in w
    in n
    in div
    in m
    in m
    in t
    in t
    in div
    in styled.div
    in div
    in div
    in styled.div
    in Cl
    in fe
    in n
    in w
    in injectIntl(Connect(n))
    in t
    in d
    in t
    in div
    in styled.div
    in div
    in styled.div
    in Unknown
    in s
    in P
    in w
    in t
    in t
    in IntlProvider
    in n
    in w
    in Js
    in s

**Comment by derrickmehaffy** [comment] 2021-10-04 22:08
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
