### ISSUE TITLE
Specifying "false" `srv` option for the mongo database during yarn setup enables srv option

### ISSUE THREAD

**Issue by mcrmonkey** [strapi/strapi#9283] opened 2021-02-01 14:55 UTC
### Describe the bug

When following the prompts for setting up the mongo database while using `yarn create` the user is asked if they want to use the SRV record to fill out the port number etc.

If the user types in `false` the option is enabled and the setup will fail ( because there's no SRV record in place for this setup )

### Steps to reproduce the behavior

1. Run `yarn create strapi-app test`
2. Select `Custom` for custom databases settings
3. Select `mongo` as the database type
4. Follow prompts providing input as requested
5. Enter `false` in the `+srv` field
6. complete setup and wait for error

### Expected behavior

If a user enters `false` the srv option shouldn't be enabled.

### System

- Node.js version: v12.20.1 
- NPM version: 6.14.10
- Strapi version: v3.4.5
- Database: mongo
- Operating system: debian buster - docker and bare metal / macos  

### Additional context

I think the question type needs to be changed so it doesn't accept free text - should either be a `yes` or `no` option

**Comment by derrickmehaffy** [comment] 2021-02-01 15:03
Can't reproduce on v3.4.5:

![image](https://user-images.githubusercontent.com/8593673/106475924-b9ff7a80-6463-11eb-8e10-a4f0fcdd7a75.png)

Generated database.js:

![image](https://user-images.githubusercontent.com/8593673/106475959-c257b580-6463-11eb-83b5-8895789c9bb6.png)

Default template always sets the `srv` as `srv: env.bool('DATABASE_SRV', false),` and the connection test during the creation is the only time this key is used (follows what is set).

---

Can you please provide more information on how to test this?

**Comment by mcrmonkey** [comment] 2021-02-01 15:29
thats odd...


Here's a docker example:

```shell
docker run -it --rm --entrypoint bash node:12.20.1-buster
```

Then inside the container do:

```shell
yarn create strapi-app test
```

Specify the values:

* custom (manual settings)
* Database client - select `mongo`
* database name: ( press enter to accept default value of `test` )
* Host: ( press enter to accept default value of `127.0.0.1` )
* +srv connection type in `false` and press enter
* Port ( press enter to accept default ) 
* Username ( press enter to accept default)
* Password ( press enter to accept default)
* Authentication database ( press enter to accept default)
* Enable SSL connection ( press enter to accept default )

After entering these values the following error is returned:

```
  connection test failed: querySrv ENOTFOUND _mongodb._tcp.127.0.0.1 

```

If you repeat the test but press enter to accept the default value for the +srv option it doesn't make any attempts to lookup the SRV record and attempts to connect directly to 127.0.0.1 

*Note*: This connection attempt to 127.0.0.1 will fail in this container as there's no mongo server up but that's ok - the point is the SRV stuff isn't activated

**Comment by derrickmehaffy** [comment] 2021-02-02 20:56
this may be a docker specific issue, if so then we need to transfer the issue over to the docker repo: https://github.com/strapi/strapi-docker

**Comment by derrickmehaffy** [comment] 2021-02-05 20:34
```
dmehaffy@DM-Desktop-LM:~$ dig srv _mongo._tcp.127.0.0.1

; <<>> DiG 9.16.1-Ubuntu <<>> srv _mongo._tcp.127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 58482
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;_mongo._tcp.127.0.0.1.		IN	SRV

;; Query time: 24 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Feb 05 13:33:46 MST 2021
;; MSG SIZE  rcvd: 50
```

(I'm a Linux User)

**Comment by derrickmehaffy** [comment] 2021-04-15 18:16
Closing as we can't reproduce and no new information has been provided

**Closed by derrickmehaffy** 2021-04-15 18:16 UTC
Labels: severity: low, source: core:database, status: can't reproduce
