### ISSUE TITLE
[V4] GraphQL Hangs with beta.7

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#11417] opened 2021-10-31 10:18 UTC
## Bug report

http://localhost:1337/graphql hands with beta.7

### Describe the bug

When upgrading to `beta.7` (I believe `--quickstart` yields same result), graphql playground hangs.
The issue disappears when downgrading to beta.6 or lower.

### Screenshots

![2021-10-31 12 07 28](https://user-images.githubusercontent.com/11737572/139577943-5978da77-8a89-4377-8b21-1aa729f7d3cf.gif)

### System

- Node.js version: `v14.17.6`
- Strapi version: `4.0.0-beta.7`
- Database: PG
- Operating system: macOS

**Comment by derrickmehaffy** [comment] 2021-11-01 16:48
Issue is caused by the change in the CSP security config: https://github.com/strapi/strapi/pull/11362

Modifying the CSP config to disable it will allow GraphQL playground to load the external CDN options.

**Comment by ScottAgirs** [comment] 2021-11-01 16:57
> Issue is caused by the change in the CSP security config: #11362
> 
> Modifying the CSP config to disable it will allow GraphQL playground to load the external CDN options.

I see, thank you for that 🙌🏼 

@derrickmehaffy, @kasonde  I'm low-key confused about the "status: pending reproduction" tag :D 

I see it from time to time - does it mean that Strapi team is expecting an app reproduction with the issue?

**Comment by derrickmehaffy** [comment] 2021-11-01 18:25
> > Issue is caused by the change in the CSP security config: #11362
> > 
> > Modifying the CSP config to disable it will allow GraphQL playground to load the external CDN options.
> 
> I see, thank you for that 🙌🏼 
> 
> @derrickmehaffy, @kasonde  I'm low-key confused about the "status: pending reproduction" tag :D 
> 
> I see it from time to time - does it mean that Strapi team is expecting an app reproduction with the issue?

It means someone from the team needs to reproduce it locally from a fresh project. Those with the tag for a while just means it is low on our priority list and no one from the team has actually tested the problem yet.

**Comment by ScottAgirs** [comment] 2021-11-01 19:16
> > > Issue is caused by the change in the CSP security config: #11362
> > > 
> > > Modifying the CSP config to disable it will allow GraphQL playground to load the external CDN options.
> > 
> > I see, thank you for that 🙌🏼 
> > 
> > @derrickmehaffy, @kasonde  I'm low-key confused about the "status: pending reproduction" tag :D 
> > 
> > I see it from time to time - does it mean that Strapi team is expecting an app reproduction with the issue?
> 
> It means someone from the team needs to reproduce it locally from a fresh project. Those with the tag for a while just means it is low on our priority list and no one from the team has actually tested the problem yet.

Toit, thanks for clarifying 🤓

**Comment by derrickmehaffy** [comment] 2021-11-02 18:33
Fixed in Beta.8

**Closed by derrickmehaffy** 2021-11-02 18:33 UTC
Labels: type: bug, severity: medium, status: confirmed, source: core:framework, version: v4-Alpha/Beta
