### ISSUE TITLE
Strapi 3.0.5 is too slow when loaded for the first time

### ISSUE THREAD

**Issue by Moizsohail** [strapi/strapi#7950] opened 2020-09-18 13:54 UTC
**Performance issue**
When I deployed the production server on digital ocean it started taking around 1 - 2 minutes to fully load up. After further analysis I found that the source of the problem is the http://128.199.25.147:1337/admin/main.be9bc0d5.chunk.js which is taking about 1.9 minutes to fully download. The whole chunk is about 7mb.

As you can see the content download of the following js file is taking too much time and causing unnecessary delay. 
![image](https://user-images.githubusercontent.com/32095770/93605359-16478d80-f9e0-11ea-9e7e-ea73fe8da659.png)

 

**Steps to reproduce the behavior**

Access the http://128.199.25.147:1337/admin link

**System**
- Network speed - 2mbps average
- Digital Ocean Droplet - $10 with 2gb ram as recommended
- Node.js version: 14.11.0
- NPM version: 6.14.8
- Strapi version: 3.0.5
- Database: Monogodb
- Operating system: Ubuntu 18.04

PS: I have tried and tested this on multiple devices and the problem still exists.

**Comment by derrickmehaffy** [comment] 2020-09-18 15:50
I believe in your case the connection isn't very good =/ If the issue is due to the size of the admin we already have an open issue here: https://github.com/strapi/strapi/issues/7439

**Comment by Moizsohail** [comment] 2020-09-18 17:06
How much time did the above link take to load for you?

I corrected the network speed. It's 2mbps not 200kbps. 

Also the mentioned issue does not resolve the problem. Any other suggestions?

**Comment by derrickmehaffy** [comment] 2020-09-18 17:19
For the moment there is no suggestions to decrease the payload time (mine downloads in about 700ms, but I'm also in the US where the DO servers are located). For now I'm going to mark this as closed as a duplicate of #7439.

**Closed by derrickmehaffy** 2020-09-18 17:19 UTC
Labels: status: can't reproduce

**Comment by pedromagalhaes** [comment] 2021-03-21 17:31
I have exactly the same problem, also in Digital Ocean. The Strapi CMS login screen, in production mode, takes me minutes to load because of these big sized chunks. Im on Strapi 3.4.6 and im on 200MB internet speed connection. It looks to me that these chunks are being slowely loaded from Digital Ocean for some reason.

**Comment by Mierenga** [comment] 2021-04-17 02:50
A solution to this problem (I've verified it for my case) is in the other issue thread: https://github.com/strapi/strapi/issues/7439#issuecomment-706242075

I think this is the most likely cause of this issue for anyone who has reasonable internet speeds.
