### ISSUE TITLE
Response time during login step

### ISSUE THREAD

**Issue by ronny35** [strapi/strapi#9836] opened 2021-03-25 12:20 UTC
### Describe the bug

I follow this [link](https://strapi.io/documentation/developer-docs/latest/guides/auth-request.html#login-as-a-reader) in order to log in and obtain token.
The first post is very slow :
```
[2021-03-25T12:12:25.179Z] debug POST /auth/local (50058 ms) 200
[2021-03-25T12:12:34.387Z] debug POST /auth/local (280 ms) 200
```

### Steps to reproduce the behavior

Following this [link](https://strapi.io/documentation/developer-docs/latest/guides/auth-request.html#login-as-a-reader)

### Expected behavior

Response time must be improved.

### System

Docker :
- Strapi version: strapi/strapi:3.3.3-alpine
- Database: mongo:4.4.1-bionic

**Comment by derrickmehaffy** [comment] 2021-03-29 21:36
Closing as I can't reproduce this and not enough information was provided to reproduce

**Closed by derrickmehaffy** 2021-03-29 21:36 UTC
Labels: status: can't reproduce

**Comment by ronny35** [comment] 2021-03-31 06:53
What kind of information do you need? I reproduce it every time and often during the first log in.

**Comment by derrickmehaffy** [comment] 2021-04-01 20:19
Sample code repo that can be run with a sample code that can be used to reproduce the issue.
