### ISSUE TITLE
Media library crashes with blank screen due to relative server url config

### ISSUE THREAD

**Issue by segovia** [strapi/strapi#18163] opened 2023-09-26 07:27 UTC
### Required System information

Environment: development
OS: linux-x64
Strapi Version: 4.13.7
Node/Yarn Version: yarn/3.6.3 npm/? node/v16.20.0 linux x64
Edition: Community
Database: postgres

### Steps to reproduce the behavior

1. Configure your server with a relative url (in server.ts), like: /my-url
2. Go to the Media Library in the admin via clicking the left panel nav link
3. You will see a blank screen and the browser console will log

```
main.21a86957.js:1285 TypeError: Failed to construct 'URL': Invalid base URL
    at a (main.21a86957.js:1232:8369)
    at ue (main.21a86957.js:945:666)
    at F (main.21a86957.js:1283:20696)
    at Ao (main.21a86957.js:1285:45914)
    at Xn (main.21a86957.js:1285:41496)
    at rt (main.21a86957.js:1285:41424)
    at xn (main.21a86957.js:1285:41275)
    at qd (main.21a86957.js:1285:37489)
    at hh (main.21a86957.js:1285:36385)
```

### Expected behavior

I would expect the Media Library not to crash

### Additional context

I believe the issue is related to the code here: https://github.com/strapi/strapi/blob/4d6918a3fca8bb44d5c1a69f0e5ae9728833aac8/packages/core/upload/admin/src/utils/appendSearchParamsToUrl.js#L13
This line was recently changed and it assumes that the backend url is a full url (not a relative one). Since Url expects a full url as the second argument, it crashes.

According to documentation, a relative url is allowed: https://docs.strapi.io/dev-docs/configurations/server

**Comment by pgsfredda** [comment] 2023-09-27 06:43
Hi everyone.
I'm facing the same issue with admin.

When I try to load one or more images (size: 5kb) Strapi Admin get an error message:
`Woops! Something went wrong. Please, try again.`

The error in the browser console is:

![immagine](https://github.com/strapi/strapi/assets/7228819/5d3e8220-8390-4b45-a790-745c7966b4ae)

No error messages on server log.

**System information:**

* Strapi Version: 4.13.7
* Operating System: Ubuntu 20.04.6 LTS
* Database: mySQL 8.0.34 (using mysql2 as driver)
* Node Version: 18.18.0
* NPM Version: 9.8.1
* Yarn Version: none

My `config/server.ts`:

~~~js
export default ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('STRAPI_URL', '/strapi'),
  app: {
    keys: env.array('APP_KEYS'),
  },
  webhooks: {
    populateRelations: env.bool('WEBHOOKS_POPULATE_RELATIONS', false),
  },
});
~~~

My `config/admin.ts`:
~~~js
export default ({ env }) => ({
  url: env('STRAPI_ADMIN_URL', '/strapi/admin'),
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT'),
  },
  transfer: {
    token: {
      salt: env('TRANSFER_TOKEN_SALT'),
    },
  },
});
~~~

Admin build command:
`NODE_ENV=production STRAPI_URL=/strapi STRAPI_ADMIN_URL=/strapi/admin npm run build`

My apache proxy config:
~~~code
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName mydomain
        ServerAlias mydomain
        ServerAdmin myemail
        DocumentRoot /var/www/mydomain/html

        <Directory /var/www/mydomain/html>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <IfModule mod_dir.c>
            DirectoryIndex index.php index.pl index.cgi index.html index.xhtml index.htm
        </IfModule>

	ProxyPreserveHost On
  	ProxyRequests Off
	ProxyPass /strapi http://localhost:1337
	ProxyPassReverse /strapi http://localhost:1337
</VirtualHost>
</IfModule>
~~~

When I make the same test on local machine, without server url field definition, strapi admin works fine.
Can someone help me? Thank you in advance

**Comment by pgsfredda** [comment] 2023-09-28 07:35
# UPDATE

I made some tests with the file `appendSearchParamsToUrl.js` adding some rows to modify the `url` and `window.strapi.backendURL` parameters.
The solution is not good because the problem is the composition of those parameters  elsewhere but with this change I can use media now. 

I'm waiting for a correct patch. **This is a blocking issue**.
Thank you

### Temporary patch for `appendSearchParamsToUrl.js`
~~~js
/**
 * Append the given search params to the given URL.
 *
 * @param {String} url The URL string to append the search params to
 * @param {Object} params The object of search params to append to the URL
 * @returns {String} A string representing the URL with the search params appended
 */
const appendSearchParamsToUrl = ({ url, params }) => {
  if (url === undefined || typeof params !== 'object') {
    return url;
  }

  var blob = url.split(':')[0] === 'blob'? 'blob:': '';
  if(blob) url = url.replace('blob:', '');
  url = url.replace(window.origin, '').replace(window.strapi.backendURL, '');
  if(!window.strapi.backendURL.startsWith(window.origin)) window.strapi.backendURL = window.origin + window.strapi.backendURL;
  if(!url.startsWith(window.strapi.backendURL)) url = blob + window.strapi.backendURL + url;
  
  console.log('*** STRAPI *** append', {url, params, origin: window.origin, backendURL: window.strapi.backendURL});
  const urlObj = new URL(url, window.strapi.backendURL);

  Object.entries(params).forEach(([key, value]) => {
    if (value !== undefined) {
      urlObj.searchParams.append(key, value);
    }
  });

  return urlObj.toString();
};

export { appendSearchParamsToUrl };

~~~

**Comment by joshuaellis** [comment] 2023-09-28 08:23
Closing in favour of #18175 which has been written clearer overall.

**Closed by joshuaellis** 2023-09-28 08:23 UTC
