### ISSUE TITLE
url parameter in config/server.ts not working

### ISSUE THREAD

**Issue by Matb85** [strapi/strapi#21452] opened 2024-09-24 21:07 UTC
### Required System information

- Node.js version: v20.11.0
- NPM version: yarn 1.22.2 npm 10.2.4
- Strapi version: 5.0.0
- Database: postgres
- Operating system: MacOS Sonoma 14.5
- Is your project Javascript or Typescript: Typescript

### Describe the bug

After building for production, the frontend has incorrect urls for script files

### Steps to reproduce the behavior

1. Go to set a custom url with a subpath (e.g. https:/example.com/api)in config/server.ts
2. Build and deploy the project
3. See error - the admin panel does not load, paths to scripts in the generated index.html file does not start with /api 

<img width="414" alt="Screenshot 2024-08-20 at 12 40 20" src="https://github.com/user-attachments/assets/710ca975-13a6-4d98-b606-3a7346896a25">
ff5">

### Expected behavior

The admin login view should show up

### Screenshots

<img width="414" alt="Screenshot 2024-08-20 at 12 40 20" src="https://github.com/user-attachments/assets/710ca975-13a6-4d98-b606-3a7346896a25">
ff5">

### Code snippets

config/server.ts

<img width="513" alt="Screenshot 2024-09-24 at 23 05 05" src="https://github.com/user-attachments/assets/28b87f9a-453e-4b0d-9604-2bbd128c5d64">

### Additional context

probably something to do with Vite's config

the error:

<img width="1470" alt="1" src="https://github.com/user-attachments/assets/75a1c04a-0a9d-4228-9520-9a1d2c61da3d">
<img width="402" alt="2" src="https://github.com/user-attachments/assets/0b91be7a-3851-46b3-acfb-e960d868d64c">

the path should be /api/admin instead of /admin

**Comment by raphaelbadawi** [comment] 2024-09-25 11:55
I had a similar issue after migrating to v5, but after [digging in to the documentation, it seems that you can fill your admin subpath directly in ./config/admin.ts](https://docs.strapi.io/dev-docs/admin-panel-customization/host-port-path). It seems the admin path is built on the host rather than on the server url, which makes you having to fill the subpath directly there.

**Comment by raphaelbadawi** [comment] 2024-09-25 16:27
I reproduced the same issue. The thing is, to workaround this, I added a nginx rewrite rule so all requests to /admin are redirected to to /api/admin. After this, the .js files end up being loaded properly, but the react app will still not load. No JS error nor network failure.

**Comment by wladyslawczyzewski** [comment] 2024-09-26 12:47
I think the issue is here:

https://github.com/strapi/strapi/blob/4052765aa209dd4f3d92b81baee295fc0213c04c/packages/core/core/src/configuration/urls.ts#L57

Up until this `adminPath` variable set the urls are building ok, for example:

`http://domain.com/cms` & `http://domain.com/cms/admin`

because we replace the common parts of these two values, we get only `/admin` but should be `/cms/admin`. Probably we should not do the replace here or replace only origin of the url?

**Comment by raphaelbadawi** [comment] 2024-09-26 15:53
Well I test patching this line and it seems this line is actually doing what it is supposed to do. adminPath is not adminUrl, if you have adminUrl to /api/admin and adminPath to /api/admin, then to access your admin page you will have to go to /api/api/admin, so adminPath should be just /admin in this case.

**Comment by wladyslawczyzewski** [comment] 2024-09-27 08:06
`adminPath` later is used to build the URL for the resources like this JS file in the screenshots. I also tried to fix this issue by changing this line and had some progress but another issue come up, so I decided to deploy the strapi with subdomain instead of subfolder of the website.

Spent two days trying to run it as subdomain... 😭

**Comment by wladyslawczyzewski** [comment] 2024-09-27 14:35
update on this issue:

I managed to run the strapi in subfolder (`https://domain.com/cms`) – the reverse proxy configuration where you rewrite the request uri to remove the subfolder's prefix (`/cms`) is incorrect, you need just to pass the request to api with custom setting for the `server.url` and `admin.url` parameters (I used `https://domain.com/cms` and `https://domain.com/cms/admin`). Also, I needed to apply the patch for the if branch I mentioned above and replace it with `adminPath = new URL(adminUrl).pathname;` (see attachment).

Now all the requests are being processed by the strapi instance correctly, however, I got another issue where the call to `/admin/init` endpoint return the html for admin panel instead of <put what should be there as idk>. See screenshot attachment.

[@strapi+core+5.0.1.patch](https://github.com/user-attachments/files/17165676/%40strapi%2Bcore%2B5.0.1.patch)
<img width="1045" alt="Screenshot 2024-09-27 at 16 34 30" src="https://github.com/user-attachments/assets/4fee453b-2dad-43c1-ac59-95a1fd01bf53">

**Comment by wladyslawczyzewski** [comment] 2024-09-27 22:43
further update: create a PR with the fix for this issue

**Comment by adminceovision** [comment] 2024-09-28 08:17
It didn't fix it for me, weirdly when following the steps detailed above, I end up with a /api/api/admin URL for the admin panel :/

**Comment by wladyslawczyzewski** [comment] 2024-09-28 08:30
@adminceovision sorry, there's few more changes required (see the PR). attaching the patch file I use right now and it seems to be working fine.

also, please remember to not rewrite the request uri on reverse proxy, just pass it to the strapi instance.

[@strapi+core+5.0.1.patch](https://github.com/user-attachments/files/17173756/%40strapi%2Bcore%2B5.0.1.patch)

**Comment by raphaelbadawi** [comment] 2024-09-28 09:50
Hey you're right the request rewrite was still there in our nginx config, sorry for the confusion.

Deployed the changes to configuration/urls.ts, configuration/index.ts and admin-api.ts and it just works, thank you! For now I will just add to my Dockerfile some lines to copy the patched files, until this is merged ;-)

**Comment by alexandrebodin** [comment] 2024-10-09 10:36
Hello, we are investigate this. closing as duplicate of https://github.com/strapi/strapi/issues/21184 so we have a single issue to reference

**Closed by alexandrebodin** 2024-10-09 10:36 UTC
