### ISSUE TITLE
Multiple Image Uploads result in memory leak

### ISSUE THREAD

**Issue by iserko** [strapi/strapi#6432] opened 2020-05-29 12:53 UTC
**Describe the bug**
Memory leak due to image uploading both with and without `responsiveDimensions` and `sizeOptimization` disabled via Media Library settings.

If you upload multiple images at the same, the memory consumption increases according to the number of images you're uploading.

Tested with:
- `strapi-provider-upload-local` `3.0.1` 
- `strapi-provider-upload-aws-s3` `3.0.0`

**Steps to reproduce the behavior**
I run Strapi inside Docker, so I monitor memory usage by running `docker stats`

Have made a video:

1. Start a fresh Strapi server ... memory usage `93 MB`
2. turn off Image optimization and Responsive Dimensions via `/admin/settings/media-library` 3. go to the Media Library and upload an image `490 kB` in size ... memory usage now `122 MB`
4. upload another image `149 kB` in size ... memory usage now `135 MB`
5. enable Image optimization and Responsive Dimension via `/admin/settings/media-library`
6. upload another image `325 kB` in size ... memory usage now `257 MB`

**Expected behavior**
I would expect the additional memory usage to be much lower and stable.

**Screenshots**
Video: https://drive.google.com/file/d/1wNVkRLKagVQuRp8Vuld6FADrilfmS00n/view?usp=sharing

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.4
- Strapi version: 3.0.1
- Database: PostgreSQL
- Operating system: Debian Buster running inside Docker

**Comment by derrickmehaffy** [comment] 2020-05-29 13:33
@soupette @alexandrebodin ? 

On the flip side I will try to see if I can reproduce this outside of docker.

**Comment by iserko** [comment] 2020-05-29 14:00
before [`enhanceFile`](https://github.com/strapi/strapi/blob/719430a81dcde943b01c996bb76d09e5b6f1d49b/packages/strapi-plugin-upload/services/Upload.js#L81) - `145 MB`
after [`enhanceFile`](https://github.com/strapi/strapi/blob/719430a81dcde943b01c996bb76d09e5b6f1d49b/packages/strapi-plugin-upload/services/Upload.js#L81) - `154 MB`

no change in memory until we get to thumb creation.

after [`generateThumbnail`](https://github.com/strapi/strapi/blob/719430a81dcde943b01c996bb76d09e5b6f1d49b/packages/strapi-plugin-upload/services/image-manipulation.js#L31) - `164 MB`

after [`generateResponsiveFormats`](https://github.com/strapi/strapi/blob/719430a81dcde943b01c996bb76d09e5b6f1d49b/packages/strapi-plugin-upload/services/image-manipulation.js#L88) - `199 MB`

**Comment by iserko** [comment] 2020-05-29 16:02
I wrote a simple test script https://gist.github.com/iserko/ff497e0c9b91b10166dcc1d45d3811a5
```
# using streams with a minimal memory footprint
root@f93240de99bd:/srv/app# DEBUG=* yarn exec plugins/test.js
yarn exec v1.22.4
  test-sharp at start - 44.6640625 MB +0ms
  test-sharp after initializing the streams - 45.12890625 MB +3ms
  test-sharp after initializing sharp - 45.12890625 MB +2ms
  test-sharp after resizing - 45.12890625 MB +0ms
Image height is 119
Done in 0.24s.

# using buffer adds 6 MB
root@f93240de99bd:/srv/app# DEBUG=* yarn exec plugins/test.js
yarn exec v1.22.4
  test-sharp at start - 44.90234375 MB +0ms
  test-sharp after reading file - 45.6796875 MB +11ms
  test-sharp after resizing - 49.87109375 MB +42ms
  test-sharp after deleting content - 49.87109375 MB +2ms
  test-sharp after deleting newBuffer - 50.19921875 MB +0ms
Done in 0.21s.
```

**Comment by lauriejim** [comment] 2020-06-15 10:29
Thank you @iserko for reporting this issue.
I ping @alexandrebodin about this issue.

The team is quite busy on other topic, can you please try to have a look in the code source to find a potential reason of this issue.
I will appreciate your help on this issue resolution.
Thank you.

**Comment by iserko** [comment] 2020-06-15 10:41
@lauriejim as my test from the test script shows, if you use buffers (as Strapi does), you get memory leaks. If you write the code so that it streams all the way through, then there's almost no memory overhead.

**Comment by alexandrebodin** [comment] 2020-06-15 12:01
Hi @iserko Would you be interested in making a PR ?

**Comment by iserko** [comment] 2020-06-15 14:07
@alexandrebodin can't commit, so it's free for anyone to take it. If I do get time to do it though, can take a stab at it.

**Comment by vinod77** [comment] 2020-07-13 16:34
Hi..
Looks this memory leak issue is causing due to the Buffer.

https://github.com/strapi/strapi/blob/v3.0.0-beta.20.3/packages/strapi-plugin-upload/services/Upload.js#L82 

The default Strapi code uses `fs.readFile()`  which uses Buffer, leads to memory leak.. So I wrote my own code, using `fs.createReadStream()` which reads/streams the file all the way from the file Storage (S3) itself, in this case there won't be any memory leak issues.

`fs.readFile()` uses Buffer that holds/leaks the memory to read the files but `fs.createReadStream()` doesn't.

And i have also removed `generateThumbnail`: https://github.com/strapi/strapi/blob/v3.0.0-beta.20.3/packages/strapi-plugin-upload/services/Upload.js#L125 which takes huge time to generate thumb.

**Comment by markjlaney** [comment] 2020-07-15 18:51
@lauriejim this is blocking us from upgrading to the new version. This is a high priority bug. Is there any way you can re-prioritize? It causes our server to crash any time multiple users upload videos.

**Comment by lynndylanhurley** [comment] 2020-09-03 15:21
Agree with @markjlaney . We just built a site with strapi that cannot be released until this issue is resolved

**Comment by alexandrebodin** [comment] 2020-09-03 15:25
Hi, FYI this is in our backlog for this month :)

**Comment by petersg83** [comment] 2020-09-24 13:18
Hi :)
I investigatted in it and I see the increase of the RSS memory but it may not be a memory leak. Here is what I understood:
- When you upload a file, it is stored in a buffer and the memory usage increases
- Once the upload is done, the buffer is deleted and the memory is freed BUT Node doesn't directly return the memory to the OS (source: https://github.com/lovell/sharp/issues/890), which why you don't see the memory usage decrease. From what I observed, the RSS decreases from times to times.

So it looks like it is inherent to the way Node works.

I you continue to play with the media library by adding new files, does the memory usage always and only increase ? Or do it decrease sometimes ? Would be good to see all the info of the `process.memoryUsage` function to better understand.

(Also, even if there are no memory leaks, the increase of the memory usage is problematic and it would be good to see if we can use streams instead of buffers, but that would be for another time)

**Comment by derrickmehaffy** [comment] 2020-09-24 20:08
I agree with Streams as well @petersg83 as that should cut out the issues related to very large files as well as we wouldn't need to buffer the file into memory :thinking: I remember an issue that Alex and I looked at some time ago dealing with extremely large files (say larger than 4 to 10 GB)

**Comment by petersg83** [comment] 2020-09-25 08:13
Yes, but I'm not sure it would be possible since we manipulate the files to transform them. It's possible that some libraries we use only accept buffers

**Comment by blixth** [comment] 2020-10-29 08:42
> I agree with Streams as well @petersg83 as that should cut out the issues related to very large files as well as we wouldn't need to buffer the file into memory  I remember an issue that Alex and I looked at some time ago dealing with extremely large files (say larger than 4 to 10 GB)

+1 for Streams. We too have the need to upload large files:
`error RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3270935831) is greater than possible Buffer: 2147483647 bytes
    at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:282:11)`

**Comment by vietlongn** [comment] 2020-11-18 09:02
I also did some investigation and it turned out that the memory allocator in strapi base image (debian) take responsibility to this "leak". Switching to Alpine variant should solve the problem.

FYI you can also replace memory allocator in base variant with another one. [Read here](https://github.com/lovell/sharp/issues/955#issuecomment-475532037)

**Comment by derrickmehaffy** [comment] 2020-12-03 10:21
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/heroku-memory-leak/1443/1

**Comment by derrickmehaffy** [comment] 2020-12-03 19:50
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/heroku-memory-leak/1443/5

**Comment by derrickmehaffy** [comment] 2020-12-04 13:26
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/heroku-memory-leak/1443/7

**Comment by theomjones** [comment] 2021-03-02 13:34
What's the status of this issue? Is anyone looking into this yet?

**Comment by theomjones** [comment] 2021-03-02 13:45
> I also did some investigation and it turned out that the memory allocator in strapi base image (debian) take responsibility to this "leak". Switching to Alpine variant should solve the problem.
> 
> FYI you can also replace memory allocator in base variant with another one. [Read here](https://github.com/lovell/sharp/issues/955#issuecomment-475532037)

This solution didn't work for me

**Comment by pescoboza** [comment] 2021-08-12 07:11
Have a nice product catalog. Can't deploy though. Anyone found a fix?

**Comment by nimarion** [comment] 2021-11-04 21:20
Is there an ETA for this issue?

**Comment by derrickmehaffy** [comment] 2021-11-08 21:26
> Is there an ETA for this issue?

Not at the moment sorry, I believe the team is looking into this after the first v4 stable release (fixing this in v4 won't be a breaking change)

**Comment by YannickMol** [comment] 2021-11-30 20:08
It looks like this is fixed in v4. I have been able to successfully upload over 500 images without any error or memory leak.

**Comment by pedrosimao** [comment] 2021-11-30 20:20
@YannickMol That's good news! Do v4 uses Streams instead of Buffers?

**Comment by YannickMol** [comment] 2021-11-30 20:35
@pedrosimao I have no idea - I leave that to someone from the core team to answer. They are far more experienced 😉

**Comment by petersg83** [comment] 2021-12-01 08:54
We didn't try to fix it for V4 :p 
We will need to have a deeper look into it

**Comment by derrickmehaffy** [comment] 2021-12-21 20:01
Update (provided on behalf of the engineering and product team).

This issue is currently being looked at and confirmed in v4 to see how best to fix it or even where the source of the problem is. Once we have more information we will let you know.

**Closed** 2022-02-23 12:43 UTC
Labels: issue-type: bug, severity: medium, source: core:upload, status: pending reproduction, version: v4
