### ISSUE TITLE
Strapi with GraphQL crashes if a field in any content type contains a space

### ISSUE THREAD

**Issue by keahie** [strapi/strapi#3035] opened 2019-03-27 15:10 UTC
**Informations**
- **Node.js version**: v11.12.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: MongoDB
- **Operating system**: Mac OS 10.14.4 Mojave

**What is the current behavior?**
If any field in a content type contains a space and the GraphQL plugin is active the server crashes every time you try to start him.

**Steps to reproduce the problem**
Just name a field in any content type to, for example, "Foo Bar" and install the GraphQL plugin.

**What is the expected behaviour?**
The server should not allow whitespaces if the GraphQL plugin is installed.

**Suggested solutions**
It should not be possible to install the GraphQL plugin if any whitespaces exists in and field. If the GraphQL plugin is installed and you try to rename or create a new field with a whitespace, the user should get a warning message. So he or she can fix the naming before the server crashes at the start.
Or you just don't allow whitespaces in any field. It doesn't matter if GraphQL is installed or not. Spaces just cause troubles in many API's so it would be a good idea to forbid them or at least replace them with %20 or an underscore (_)

**Comment by derrickmehaffy** [comment] 2019-03-27 15:15
https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#model--field-naming-schemes

@keahie spaces, symbols and special cases are not supported with or without the graphQL plugin.

given yes there should be some validation so the user can't enter them to begin with but they do plan to be supported in the future hence why this hasn't been added. I'm marking this as closed as the issue is will documented and not currently supported.

**Closed by derrickmehaffy** 2019-03-27 15:15 UTC
