### ISSUE TITLE
Icons alignment issues in the left menu Firefox

### ISSUE THREAD

**Issue by fabio-nettis** [strapi/strapi#4060] opened 2019-09-20 05:41 UTC
**Describe the bug**
Since updating to version *v3.0.0-beta.16.4* I somehow expirience an issue where the different Icons in front of the Content-Type name are not aligned perfectly centered. This is a totally astethic issue and does not effect functionality in any way, matter of fact it's unpleasant.

**Steps to reproduce the behavior**
1. Update to version v3.0.0-beta.16.4 or higher.
2. Take a look at the side-nav.

**Expected behavior**
The icons should be centered like in previous versions.

**Screenshots**

![sidenav-strapi](https://user-images.githubusercontent.com/36916632/65301250-e9675d00-db76-11e9-8e08-45183d60015e.PNG)

**Code snippets**
Not applicable.

**System**
- Node.js version: 12.10.0
- NPM version: 6.11.3
- Strapi version: v3.0.0-beta.16.5
- Database: MongoDB
- Operating system: Windows Server 2002 R2

**Comment by websocket98765** [comment] 2019-09-25 21:42
Related to this line: https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/components/LeftMenuLink/styles.scss#L89

But the difficulty is that updating it to `top: calc(50% - 0.7rem);` is vertically centered in FF, `top: calc(50% - 0.5rem);` is vertically centered in Safari and Chrome.

(Strapi v3.0.0-beta.16.5)

**Comment by fabio-nettis** [comment] 2019-09-26 10:18
Related to this line: https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/components/LeftMenuLink/styles.scss#L89


Updating it to
```
top: calc(50% - 1.2rem)
```

Fixes the issue in Chrome for me.

**Comment by veitbjarsch** [comment] 2019-10-01 12:50
The values shouldn't set with a top calculation. Just use the line-height property and set the icon and span tag to the same line-height (update the top to 0.9rem, and remove the height of the <i> tag). 

After lining the icons correctly there could be done some cleanup and in the style code. For example you should use flexbox instead of an absolute position.

**Comment by xstable** [comment] 2019-10-04 09:36
I'll take this one. You can assign me to this ticket.

**Comment by lauriejim** [comment] 2019-12-02 21:12
This issue is fixed in the last version of Strapi - at least the beta.17.8

**Comment by websocket98765** [comment] 2019-12-06 17:50
@lauriejim Are you sure this made it into beta.17.8? I'm seeing same misalignment in all browsers. I've run `npm run build` and tried both `npm run develop` and `npm run start` with same result. FireFox is most prevalent:

(note footer says 17.8)
![ff](https://user-images.githubusercontent.com/41795874/70343983-853c6700-1850-11ea-8988-6da90ea21261.png)

**Comment by fabio-nettis** [comment] 2019-12-09 10:21
> @lauriejim Are you sure this made it into beta.17.8? I'm seeing same misalignment in all browsers. I've run `npm run build` and tried both `npm run develop` and `npm run start` with same result. FireFox is most prevalent:
> 
> (note footer says 17.8)
> ![ff](https://user-images.githubusercontent.com/41795874/70343983-853c6700-1850-11ea-8988-6da90ea21261.png)

He is absolutly right! Seems as if this hasn't made it into the current version. Somebody should definitly reopen the issue.

**Comment by lauriejim** [comment] 2019-12-15 19:33
<img width="239" alt="Screenshot 2019-12-15 at 8 32 44 PM" src="https://user-images.githubusercontent.com/5716596/70867826-16f75300-1f7a-11ea-9855-b31f88bf0e28.png">
With Google Chrome. What is your browser?

**Comment by websocket98765** [comment] 2019-12-16 01:21
@lauriejim screenshot is FireFox for MacOS.

Confirmed again using the current version of FireFox (71.0) for MacOS; identical result so not reposting screenshot.

**Comment by lauriejim** [comment] 2019-12-17 15:53
We just published the `beta.18` the icon was replaced and the css reviewed.
<img width="868" alt="Screenshot 2019-12-17 at 4 53 19 PM" src="https://user-images.githubusercontent.com/5716596/71011485-c0ab2100-20ed-11ea-9801-a0f1592fa40f.png">
Looking good on the last vesionb of strapi on firefox.

**Comment by websocket98765** [comment] 2019-12-20 02:57
@lauriejim The Content Type bullets look well positioned 👍 , but it appears the other icons for Plugins and Configuration are lower than they should be. (The screenshot below is FireFox 71 on macOS. It appears in your screenshot too.)

![strapi 18 2](https://user-images.githubusercontent.com/41795874/71226548-180ae600-22d4-11ea-959b-6fa55246b60a.png)

**Comment by lauriejim** [comment] 2019-12-24 12:36
Ping @virginieky  😇

**Comment by soupette** [comment] 2020-03-27 06:13
@lauriejim can we close this issue?

**Comment by soupette** [comment] 2020-04-02 16:08
I am closing this issue as it seems to be fixed.

**Closed by soupette** 2020-04-02 16:08 UTC
Labels: good first issue, priority: low, source: admin, type: enhancement
