### ISSUE TITLE
[3.4.0] HEAD http://localhost:1337/_health net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by endrehegyi** [strapi/strapi#8941] opened 2020-12-18 15:52 UTC
I created a brand new application using thee command 

`npx create-strapi-app@latest my-project --quickstart`

Strapi was then launched in chrome and I Created my account.

I then created a new collection type called 'Page' with a 'Text' field. 

On clicking the save button the following the error is shown twice in Chrome Dev Tool Console:

`VM21:1 HEAD http://localhost:1337/_health net::ERR_CONNECTION_REFUSED`

The application restarts fine and my new collection type is visible; so it all looks functional however I am not sure why that error is shown every time a new collection type is created.

**Comment by soupette** [comment] 2020-12-18 16:07
When you create a content type it generates a new folder under the api one. In order for all these files to be loaded in the backend the back-end  server needs to restart. So in order for the admin to stop showing the text the server is restarting, we ping the `/_heath` endpoint until the server is live again. This is why you see a bunch of errors it's completely intended.

I am closing the issue as it is an intended behaviour.

**Closed by soupette** 2020-12-18 16:07 UTC
