### ISSUE TITLE
error: relation core_store does not exist

### ISSUE THREAD

**Issue by aditya-mitra** [strapi/strapi#9471] opened 2021-02-21 17:20 UTC
### Describe the bug

I am running strapi in a docker container attached to a postgres db.
The strapi container would always fail to start.

Neither `strapi start` nor `strapi develop` would work.

### Steps to reproduce the behavior

1. Run a strapi docker container with postgres docker container also.

### Expected behavior

Strapi would start without fail

### Screenshots

Even **`strapi develop`** would not work.

![image](https://user-images.githubusercontent.com/55396651/108632153-6cd75d00-7493-11eb-8a45-b48e2c3d8103.png)

Log of operations in the postgres database

![image](https://user-images.githubusercontent.com/55396651/108632593-cf315d00-7495-11eb-9743-98a88a588825.png)

### Code snippets

I can produce more code snippets if asked to.

**docker-compose.yml**
```yml
version: "3"

services:
    db:
        container_name: pgdb
        image: postgres:12-alpine
        restart: on-failure
        environment:
            POSTGRES_DB: strapi_db
            POSTGRES_USER: strapi_user
            POSTGRES_PASSWORD: strapi_webdev
        volumes:
            - ./pgdocker:/var/lib/postgresql/data
        ports:
            - 5432:5432
        network_mode: host

    cms:
        container_name: cmsbackend
        build: ./cms
        environment:
            DATABASE_NAME: strapi_db
            DATABASE_HOST: localhost
            DATABASE_USERNAME: strapi_user
            DATABASE_PASSWORD: strapi_webdev
            DATABASE_PORT: 5432
        depends_on:
            - db
        ports:
            - 9000:9000
        network_mode: host
        restart: on-failure
```

I am also pasting the code of `database.js` file:
```js
const productionConfig = ({ env }) => {

	return {
		defaultConnection: 'default',
		connections: {
			default: {
				connector: 'bookshelf',
				settings: {
					client: 'postgres',
					host: env('DATABASE_HOST', 'localhost'),
					database: env('DATABASE_NAME', 'strapi_db'),
					port: env.int('DATABASE_PORT', 5432),
					username: env('DATABASE_USERNAME', 'strapi_user'),
					password: env('DATABASE_PASSWORD', 'strapi_webdev'),
					ssl: false
				},
			},
		},
	};
};
export default productionConfig;
```

### System

- Node.js version:  v12
- NPM version: v6
- Strapi version:  3.4.2
- Database: postgres-12
- Operating system: node:12-alpine (docker container)

### Additional context

I have tried this on several virtual machines but still it ain't resolving.

**Comment by derrickmehaffy** [comment] 2021-02-22 19:02
> Strapi version: 3.4.2

Can you please test with v3.4.6 (there is a known docker issue on v3.5.0)

Also you may need to adjust your database.js options with some Knex tarn pool config changes if your docker network is too slow: https://strapi.io/documentation/developer-docs/latest/concepts/configurations.html#database

See the pool config object and tweak your connection min/max + timeouts

**Comment by cortopy** [comment] 2021-02-22 23:45
I'm experiencing the same issue. I'm not using strapi in a container but I can reproduce like this:

1. Start postgres container in docker-compose
2. Create strapi project. 
3. Run `strapi develop`. All works fine
3. Create admin user, etc.
4. Stop server
5. Run `strapi develop`. All works fine again
6. Stop server
4. Run `docker-compose down -v` to remove all docker volumes and start again
5. Run `docker-compose up`. An empty postgres database is ready for connections
6. Run `strapi develop`. I get the error `relation core_store does not exist`

It's as if strapi doesn't realise that it has to create all tables from scratch when they are not there

**Comment by aditya-mitra** [comment] 2021-02-23 06:19
Thanks for the reply everyone!

I resolved it using **`autoMigration: true`** in the *database.js* in config folder.


Full config here - 

**database.js**
```js
const productionConfig = ({ env }) => {
	return {
		defaultConnection: 'default',
		connections: {
			default: {
				connector: 'bookshelf',
				settings: {
					client: 'postgres',
					host: env('DATABASE_HOST', 'localhost'),
					database: env('DATABASE_NAME'),
					port: env.int('DATABASE_PORT', 5432),
					username: env('DATABASE_USERNAME'),
					password: env('DATABASE_PASSWORD'),
					ssl: false,
				},
				options: {
					autoMigration: true, // this option is required in dbs other than sqlite so that tables can be created autuomatically
				},
			},
		},
	};
};
module.exports = productionConfig;
```

**Comment by cortopy** [comment] 2021-02-23 10:11
Sadly that didn't work for me. I have two connections: default and my own as the entity tables are managed externally.

```js
{
    defaultConnection: "default",
    connections: {
      default: {
        connector: "bookshelf",
        settings: {...},
        options: {
          autoMigration: true,
        },
      },
      cms: {
        connector: "bookshelf",
        settings: {...},
        options: {
          autoMigration: false,
        },
      },
    },
  };
```

It seems that ALL connections have to be `autoMigration` true, but this is not right. I have to rename my api directory and comment all connections except `default`for strapi to start. And then, I can restore all my files

**Comment by derrickmehaffy** [comment] 2021-02-23 10:50
> autoMigration: true

I have never seen this used with docker to fix an issue, it's typically used for scaling instances....

**Comment by aditya-mitra** [comment] 2021-02-23 12:42
If I use sqlite3 as the database, the application would start without any failure.

I think `autoMigration: true` is used for creating, updating and dropping tables. Without that option enabled, `knex` would not automatically create the tables. This happens for schemas which are already declared, not the new ones. Please correct me if I am wrong.

**Comment by derrickmehaffy** [comment] 2021-02-26 19:40
You are correct @aditya-mitra the setting is so that say you are working on a cluster of Strapi instances (horizontal) you can have one "master" node run any database migrations and the other nodes won't try to make the same modifications.

Or if you have an external system that does migration modifications on the database, you can stop Strapi from doing it entirely.

**Comment by derrickmehaffy** [comment] 2021-04-15 18:18
Closing as the tables weren't created due to the setting

**Closed by derrickmehaffy** 2021-04-15 18:18 UTC
Labels: status: can't reproduce, type: help wanted

**Comment by bastianhilton** [comment] 2021-05-02 02:16
> Thanks for the reply everyone!
> 
> I resolved it using **`autoMigration: true`** in the _database.js_ in config folder.
> 
> Full config here -
> 
> **database.js**
> 
> ```js
> const productionConfig = ({ env }) => {
> 	return {
> 		defaultConnection: 'default',
> 		connections: {
> 			default: {
> 				connector: 'bookshelf',
> 				settings: {
> 					client: 'postgres',
> 					host: env('DATABASE_HOST', 'localhost'),
> 					database: env('DATABASE_NAME'),
> 					port: env.int('DATABASE_PORT', 5432),
> 					username: env('DATABASE_USERNAME'),
> 					password: env('DATABASE_PASSWORD'),
> 					ssl: false,
> 				},
> 				options: {
> 					autoMigration: true, // this option is required in dbs other than sqlite so that tables can be created autuomatically
> 				},
> 			},
> 		},
> 	};
> };
> module.exports = productionConfig;
> ```

Finally, thank you so much this fixed my issue i was having

**Comment by theCompanyDream** [comment] 2021-09-24 14:59
> Sadly that didn't work for me. I have two connections: default and my own as the entity tables are managed externally.
> 
> ```js
> {
>     defaultConnection: "default",
>     connections: {
>       default: {
>         connector: "bookshelf",
>         settings: {...},
>         options: {
>           autoMigration: true,
>         },
>       },
>       cms: {
>         connector: "bookshelf",
>         settings: {...},
>         options: {
>           autoMigration: false,
>         },
>       },
>     },
>   };
> ```
> 
> It seems that ALL connections have to be `autoMigration` true, but this is not right. I have to rename my api directory and comment all connections except `default`for strapi to start. And then, I can restore all my files

Same here I've been wrestling so long with getting the database to play nice with strapi. Nothing has worked and I've been using sqlite3 because I can't get a connection.
