### ISSUE TITLE
Incorrect URL display in Strapi Content Manager when clicking on parent URL

### ISSUE THREAD

**Issue by ericrisco** [strapi/strapi#16314] opened 2023-04-06 09:34 UTC
- Node.js version: 18.13.0
- NPM version: 8.19.3
- Strapi version: 4.7.1
- Database: MySql
- Operating system: Windows 10
- Is your project Javascript or Typescript: Javascript

# **Description:**

I have encountered an issue in Strapi while working with a collection type called "Url" that has a self-relation to create a hierarchical structure of URLs for a web tree. Each "Url" element is also linked to a "Page" element to have the corresponding URL for each page. The API is functioning correctly, and the created structure is accurate.

However, I am experiencing a visual issue within the Strapi Content Manager view of the "Url" collection type. When clicking on the parent "Url", it navigates to the parent "Url" as expected, but on the "Url" still appears the parent "Url" page. This visual issue can be resolved by refreshing the page (pressing F5), but it should not require a page refresh to display the correct information.

# **Steps to reproduce:**

- Create a collection type called "Url" with a self-relation (parent) and a relation to a "Page" element.
- Add some "Url" elements and set up the parent-child relationships.
- Navigate to the Content Manager and open the "Url" collection type.
- Click on a parent "Url" element.

# **Expected behavior:**

The parent "Url" page should display without showing the his own"Url".

# **Actual behavior:**

The parent "Url" page is displayed with his own "Url" still visible. Refreshing the page (F5) resolves the issue, but the correct display should be available without a refresh.

# **Child**
![srate](https://user-images.githubusercontent.com/20164590/230336457-4048922e-e02e-4758-8420-e86926489660.PNG)

# **Father:**
![contract](https://user-images.githubusercontent.com/20164590/230336454-dd9e1094-7ea1-4bed-a1b1-51a5473e5966.PNG)

# **Father after F5**
![afterf5](https://user-images.githubusercontent.com/20164590/230336450-bf306355-8ccf-40f7-ab74-a93c624997db.PNG)

**Comment by Boegie19** [comment] 2023-04-13 18:18
Duplicate of https://github.com/strapi/strapi/issues/16260

**Closed by Boegie19** 2023-04-13 18:18 UTC
Labels: status: duplicate
