### ISSUE TITLE
Strapi should allow keeping track of user's who created/updated any content

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#6403] opened 2020-05-28 06:37 UTC
**Please describe your feature request:**
Strapi should allow keeping track of user's who created/updated any content.

I want to know user who created & updated any record, but currently Strapi doesn't provides this feature or if i am wrong, please let me know how do i know about this.

Currently i can only see CreatedAt & UpdatedAt attributes by default which are working good.

**It will be great to have CreatedBy & UpdatedBy as well. This feature is really important for us.**

**Expected behavior**
Should be able to see & keep track of User who created & updated any record.

**System**

- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.20.3
- Database: Mongo & S3 File storage for File uploads
- Operating system: MAC

**Comment by derrickmehaffy** [comment] 2020-05-28 06:46
Closing as duplicate of https://github.com/strapi/strapi/discussions/6402

**Closed by derrickmehaffy** 2020-05-28 06:46 UTC
