### ISSUE TITLE
Users Permissions jwt verifier bug

### ISSUE THREAD

**Issue by Eli-Nathan** [strapi/strapi#12354] opened 2022-01-30 23:03 UTC
### Describe the bug

When writing custom jwt validation policies, I'm able to use:

```
strapi.service("plugin::users-permissions.jwt").getToken(ctx);
```

However, when debugging and stepping through the code, it appears that the verify function _always_ fails because there is no `algorithms` array provided in the options passed to the jwt [verify function](https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/jwt.js#L40).

If I manually update the node module and add an algorithms array into those options then it clears that error but gives me a new one related to the jwtSecret: `ERR_OSSL_PEM_NO_START_LINE`.

More info on the invalid algorithms error here https://stackoverflow.com/questions/47119043/verifying-auth0-jwt-throws-invalid-algorigthm

### Steps to reproduce the behavior

1. Create project with custom jwt validation from auth0
2. Authenticate within the app with auth0
3. Using token from Auth0, make an authenticated request to Strapi
4. Place breakpoint or `console.log(err)` [here](https://github.com/strapi/strapi/blob/master/packages/plugins/users-permissions/server/services/jwt.js#L47)
5. See the error

### Expected behavior
jwt verifier library should be passed the options it needs to verify a token.

### System
- Node.js version: V12
- Strapi version: V4.0.5 (Also tried on v3 and it's an issue there too)

**Comment by derrickmehaffy** [comment] 2022-02-04 22:48
Get token just pulls it out of the headers: https://github.com/strapi/strapi/blob/6343ce509ce166ad855c918bbccb0d50c842eb98/packages/plugins/users-permissions/server/services/jwt.js#L13-L29

But yes it is passed to the verify function: https://github.com/strapi/strapi/blob/6343ce509ce166ad855c918bbccb0d50c842eb98/packages/plugins/users-permissions/server/services/jwt.js#L40-L52

We use: https://www.npmjs.com/package/jsonwebtoken and this service was only designed to validate our tokens, not external ones. You should probably build your own services to verify external tokens. I can't reproduce this logic using our own so going to set this as closed as it's not a bug but an issue with customization.

**Closed by derrickmehaffy** 2022-02-04 22:48 UTC

**Comment by TechQuery** [comment] 2025-05-17 04:48
> We use: https://www.npmjs.com/package/jsonwebtoken and this service was only designed to validate our tokens, not external ones. You should probably build your own services to verify external tokens. I can't reproduce this logic using our own so going to set this as closed as it's not a bug but an issue with customization.

@derrickmehaffy I find a similar bug in `strapi@5.13.0`:

```js
import { verify } from 'jsonwebtoken';

const signedJWT = strapi.service("plugin::users-permissions.jwt").issue({ id: 1 });

const payload1 = verify(signedJWT, strapi.config.get('plugin.users-permissions.jwtSecret'));

console.assert(payload1 != null, "JWT decoded nothing");  // passed

const payload2 = strapi.service("plugin::users-permissions.jwt").getToken(ctx);

console.assert(payload2 != null, "JWT decoded nothing");  // thrown
```
