### ISSUE TITLE
strapi-provider-upload-* is out of date on npm

### ISSUE THREAD

**Issue by ryanchuah** [strapi/strapi#3764] opened 2019-08-11 04:04 UTC
Related issue [#2768](https://github.com/strapi/strapi/issues/2768)

**Describe the bug**
All strapi-provider-upload-* on your github refers to version 3.0.0-beta.14. However, when I npm install an upload provider such as strapi-provider-upload-cloudinary, I get version 3.0.0-alpha.15. I had to manually change strapi-provider-upload-cloudinary version in my package.json to get the latest version.

**Steps to reproduce the behavior**
1. npm install strapi-provider-upload-cloudinary
2. View version of strapi-provider-upload-cloudinary in package.json

**Expected behavior**
npm install strapi-provider-upload-* should install latest version as per Strapi's github repo

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.2
- Strapi version: 3.0.0-beta.14
- Operating system: Windows 10

**Additional context**
The outdated install of strapi-provider-upload-cloudinary caused me quite a bit of trouble because this version did not set cloudinary.uploader.upload_stream() resource_type to auto. It took me quite a while to realize that my uploads were failing because of this, and some more time to realize that the npm install was outdated.

**Comment by derrickmehaffy** [comment] 2019-08-11 09:59
@ryanchuah you have to add the `@beta` to it, until strapi goes into a stable release there won't be any updated packages on `@latest`

Marking as closed as this is not a bug.

**Closed by derrickmehaffy** 2019-08-11 09:59 UTC
