### ISSUE TITLE
Mobile Authentication using firebase

### ISSUE THREAD

**Issue by spss20** [strapi/strapi#10435] opened 2021-06-04 05:13 UTC
### Can you guys please add a feature to use mobile authentication as an option in authentication providers, I will suggest if you can do firebase integration.

- [ No] **I have created my request on the Product Board before I submitted this issue**
- [ No] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Why is it needed?

It is necessary because majority of modern applications uses mobile authentication for login instead of remembering email and password.

**Comment by kasonde** [comment] 2021-06-04 18:42
Duplicate of #4719

**Closed by kasonde** 2021-06-04 18:42 UTC
