### ISSUE TITLE
Adding new content type breaking the strapi server

### ISSUE THREAD

**Issue by Hemant-yadav** [strapi/strapi#4755] opened 2019-12-18 15:33 UTC
**System Info**
Environment: development
Version: 3.0.0-beta.18.1 (node v12.4.0)
uname: Darwin
sw_vers -productVersion: 10.14.6
Strapi: 3.0.0-beta.18.1

**Issue**
After upgrading from beta.17 to beta.18 when trying to register new content type it breaking the strapi server.

**Observation**
The new auto generated `model.setting.json` has timestamps as true (**Boolean**) in options field. The older version had it as **Array** with values createdAt and updatedAt.

**Comment by alexandrebodin** [comment] 2019-12-18 15:58
Can you share the steps to reproduce ? Options you use, name of the content type...

**Comment by alexandrebodin** [comment] 2019-12-18 15:58
Alos can you share the error you can in your terminal

**Comment by Hemant-yadav** [comment] 2019-12-18 16:03
**Update**
I **changed** my **node version** as **10.18.0** but the error was still present.

`
error Bootstrap function in plugin "content-manager" failed
error TypeError: _.get is not a function or its return value is not iterable
    at createTimestampsSchema (/path/node_modules/strapi-plugin-content-manager/services/ContentTypes.js:113:54)
    at formatContentTypeSchema (/path/node_modules/strapi-plugin-content-manager/services/ContentTypes.js:103:10)
    at createDefaultConfiguration (/path/node_modules/strapi-plugin-content-manager/services/utils/configuration/index.js:26:18)
    at generateNewConfiguration (/path/node_modules/strapi-plugin-content-manager/config/functions/bootstrap.js:49:13)
    at Promise.all.contentTypesToAdd.map.uid (/path/node_modules/strapi-plugin-content-manager/config/functions/bootstrap.js:67:34)
    at Array.map (<anonymous>)
    at updateContentTypes (/path/node_modules/strapi-plugin-content-manager/config/functions/bootstrap.js:67:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.`

content type name was irrelevant as I think the problem is in the model.setting.json -> options -> timestamps

**Comment by alexandrebodin** [comment] 2019-12-18 16:24
Setting timestamps to true doesn't create a bug. it is equivalent to setting the default create at and updated at fields.

Can you share the model file so I can try it locally with your exact config.

Can you provide the database you are using too plz

**Comment by Hemant-yadav** [comment] 2019-12-18 17:09
The database.json was incorrect.
The defaultConnection wasn't present in connections in `database.json` file.
Model was referring to the invalid default connection.
Strapi should have thrown error if the defaultConnection isn't present.
And after changing the `timestamps` in `model.setting.json` file it worked

**Comment by alexandrebodin** [comment] 2019-12-19 07:22
It sure should throw. I'm closing this issue as the problem is coming not coming from content type creation

**Closed by alexandrebodin** 2019-12-19 07:22 UTC
