### ISSUE TITLE
The email configuration cannot be adjusted

### ISSUE THREAD

**Issue by tobiasbenkner** [strapi/strapi#17949] opened 2023-09-06 08:21 UTC
### Required System information
- Node.js version: v18.12.1
- NPM version: 9.8.0
- Strapi version: 4.13.2
- Database: doesn't matter
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug
I cannot adjust the email configuration. The configuration will be ignored from Strapi.

I was follwing the docs from Strapi
- https://docs.strapi.io/dev-docs/plugins/email
- https://docs.strapi.io/dev-docs/providers
- https://www.npmjs.com/package/@strapi/provider-email-nodemailer

I was trying to place the plugins.ts into two different folders. It doesn't work:
- config/plugins.ts
- config/env/development/plugins.ts

Also i was changing the provider name to:
- nodemailer
- strapi-provider-email-nodemailer

both doesn't work.

### Steps to reproduce the behavior

1. Checkout https://github.com/tobiasbenkner/strapi-bug-nodemailer
2. yarn
3. yarn develop
4. Go to http://localhost:1337/admin/settings/email

### Expected behavior
you will see that the email provider is still sendmail instead of nodemailer

### Code snippets
./config/plugins.ts
```
export default ({ env }) => {
  return {
    email: {
      // provider: 'nodemailer',
      provider: 'strapi-provider-email-nodemailer',
      providerOptions: {
        host: 'localhost',
        port: 1025,
        ignoreTLS: true,
      },
    },
  };
};
```

./package.json
```
"@strapi/provider-email-nodemailer": "^4.13.2",
"nodemailer": "^6.9.5"
```

### Additional context
./docker-compose.yml for mocking an smtp server
```
version: '3.1'

volumes:
  mail:
  
services:

  mail:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - mail:/home/mailhog
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog
```

**Comment by TomJamesDuffy** [comment] 2023-09-08 14:07
Spent a few hours on this myself today, the documentation is incorrect.

To get it to work
1.) Remove your details from plugins.js
2.) Add them into src/index.js

For me that looked like this:

`"use strict";

module.exports = {
  /**
   * An asynchronous register function that runs before
   * your application is initialized.
   *
   * This gives you an opportunity to extend code.
   */

  register({ strapi }) {
    console.log(process.env.EMAIL_SMTP_USERNAME);
    console.log(process.env.EMAIL_SMTP_PASSWORD);
    strapi.config.set("plugin.email", {
      provider: "nodemailer",
      providerOptions: {
        host: process.env.EMAIL_SMTP_HOST, //SMTP Host
        port: process.env.EMAIL_SMTP_PORT, //SMTP Port
        secure: true,
        auth: {
          user: process.env.EMAIL_SMTP_USERNAME,
          pass: process.env.EMAIL_SMTP_PASSWORD,
        },
        rejectUnauthorized: true,
        requireTLS: true,
      },
      settings: {
        defaultFrom: "tom@swimplan.co.uk",
        defaultReplyTo: "tom@swimplan.co.uk",
      },
    });
  },

  /**
   * An asynchronous bootstrap function that runs before
   * your application gets started.
   *
   * This gives you an opportunity to set up your data model,
   * run jobs, or perform some special logic.
   */
  bootstrap(/*{ strapi }*/) {},
};
`

**Comment by derrickmehaffy** [comment] 2023-09-08 14:12
> Spent a few hours on this myself today, the documentation is incorrect.
> 
> To get it to work
> 1.) Remove your details from plugins.js
> 2.) Add them into src/index.js
> 3.) Make sure you have both @strapi/plugin-email & @strapi/provider-email-nodemailer installed.
> 
> For me that looked like this:
> 
> ```
> module.exports = {
>   register({ strapi }) {
>     strapi.config.set("plugin.email", {
>       provider: "nodemailer",
>       providerOptions: {
>         host: process.env.EMAIL_SMTP_HOST, //SMTP Host
>         port: process.env.EMAIL_SMTP_PORT, //SMTP Port
>         secure: true,
>         auth: {
>           user: process.env.EMAIL_SMTP_USERNAME,
>           pass: process.env.EMAIL_SMTP_PASSWORD,
>         },
>         rejectUnauthorized: true,
>         requireTLS: true,
>       },
>       settings: {
>         defaultFrom: process.env.EMAIL_SMTP_USERNAME,
>         defaultReplyTo: process.env.EMAIL_SMTP_USERNAME,
>       },
>     });
>   },
>   bootstrap(/*{ strapi }*/) {},
> };
> ```
> 
> I would also recommend logging out your environment variables to make sure that they are coming through as you would expect.
> 
> I'm running Strapi on 18.17.1 and my package.json looks like the below:
> 
> ```{
>   "name": "top-secret-private-project",
>   "private": true,
>   "version": "0.1.0",
>   "description": "A Strapi application",
>   "scripts": {
>     "develop": "strapi develop",
>     "start": "strapi start",
>     "build": "strapi build",
>     "strapi": "strapi"
>   },
>   "dependencies": {
>     "@strapi/plugin-email": "4.13.3",
>     "@strapi/plugin-i18n": "4.13.3",
>     "@strapi/plugin-users-permissions": "4.13.3",
>     "@strapi/provider-email-nodemailer": "^4.14.0-alpha.0",
>     "@strapi/strapi": "4.13.3",
>     "better-sqlite3": "8.0.1",
>     "openai": "^3.3.0",
>     "pg": "^8.11.0",
>     "pg-connection-string": "^2.6.0"
>   },
>   "author": {
>     "name": "A Strapi developer"
>   },
>   "strapi": {
>     "uuid": "4508fd3f-419e-412a-b3b5-d9174c07ed7a"
>   },
>   "engines": {
>     "node": ">=14.19.1 <=18.x.x",
>     "npm": "<=6.x.x"
>   },
>   "license": "MIT"
> }
> ```

This is absolutely 100% the wrong way to configure this. It may work but this is not the correct way to do it.

**Comment by TomJamesDuffy** [comment] 2023-09-08 14:13
Happy for you to show me the correct way :-)

**Comment by derrickmehaffy** [comment] 2023-09-08 14:17
Under the email object you need to wrap the rest of the stuff in a config object. See one of our default providers: https://www.npmjs.com/package/@strapi/provider-email-nodemailer

It looks like you were using the old V3 package not the V4 one.

**Comment by derrickmehaffy** [comment] 2023-09-08 14:18
Marking this is closed as it's not a bug

**Closed by derrickmehaffy** 2023-09-08 14:18 UTC
Labels: issue: bug, severity: medium, source: core:email, status: pending reproduction

**Comment by TomJamesDuffy** [comment] 2023-09-08 14:25
Thanks!

**Comment by tobiasbenkner** [comment] 2023-09-08 18:55
thanks! now it works

./config/plugins.ts. the config attribute was missing.
```
module.exports = ({ env }) => ({
  email: {
    config: {
      provider: 'nodemailer',
      providerOptions: {
        host: 'localhost',
        port: 1025,
        ignoreTLS: true,
      },
    },
  },
});
```

and installed the package _@strapi/plugin-email_
