### ISSUE TITLE
Date value decreases by one day every time entity is saved

### ISSUE THREAD

**Issue by cullylarson** [strapi/strapi#9576] opened 2021-03-02 21:30 UTC
### Describe the bug

I'm in the PST timezone. I have a content type with a Date field (i.e. just the date). When you create a new entity of this type and you select a date, then click Save, the date goes back one day. I assume this is a timezone issue. I've seen other open issues on this. However, I've noticed some unique behavior for date-only fields. If you create the entity, set the date, hit save, you'll see the date go back one day. If you then edit the entity and change a field other than the date and hit save, the date will go back one day again, even though you didn't modify the date. Basically any time the entity is saved, the date will go back a day. This doesn't happen for Datetime fields.

### Steps to reproduce the behavior

1. Set your local timezone to PST (not sure if this is necessary but it might be).
2. Create a content type with a Date field (just the date, not a datetime) and at least one other field.
3. Create a new entity, set the date, save it. Notice that the date goes back one day.
4. Edit the entity and change the field other than the Date. Hit save.
5. You'll notice that the date goes back one day even though it wasn't modified.

### Expected behavior

The date should remain the same on each update.

### Code snippets

Looking at the request from the frontend and response from the server, when an entity is saved, the request date is e.g. `2021-02-22`. The response is `2021-02-21`. Hit save again, the request is `2021-02-21` and the response is `2021-02-20`. Etc.

### System

- Node.js version: 12
- NPM version: 6
- Strapi version: 3.5.2
- Database: SQLite
- Operating system: Macos

**Comment by nihey** [comment] 2021-04-01 01:28
I reproduced it following the same steps, it seems this issue does not happen when using `datetime` type.
We are handling this on our end for now by using `datetime` instead of `date`.

If it helps: as I've debugged this and it seems strapi sends the correct date to Bookshelf on `strapi-connector-bookshelf/lib/queries.js` file, maybe this conversion error is happening on Bookshelf or Knex.

**Comment by anmol5varma** [comment] 2021-04-02 16:32
@cullylarson You can try passing `TZ=UTC` with your start script. 
Something like `TZ=UTC strapi develop`

**Comment by derrickmehaffy** [comment] 2021-04-09 16:49
It appears the `date` field is being passed through moment when it shouldn't be. The reference I found is here:

https://github.com/strapi/strapi/blob/86e0cf0f55d58e714a67cf4daee2e59e39974dd9/packages/strapi-plugin-content-manager/admin/src/containers/ListView/Filter.js#L28-L43

@strapi/maintainers Do we have another area where the date is passed through moment for conversion? For datetime / timestamp it makes sense since there is a time component to it, but for just standard dates I don't think we should pass it through.

**Comment by derrickmehaffy** [comment] 2021-04-09 17:32
**Note to those trying to reproduce**, moment uses your browsers timezone so if you are only a few hours in front of UTC you won't see the problem, it generally will only happen to those BEHIND UTC because the Admin takes into account the timezone and converts backwards so the date also goes backwards.

**Comment by derrickmehaffy** [comment] 2021-04-13 20:28
Video reproducing the issue: 

https://www.loom.com/share/7a9174be12874717ad343ede17dab636

**Comment by petersg83** [comment] 2021-04-28 14:35
Thank you for the issue. I dug into it and was able to reproduce it.
It appears the problem is quite complex and larger than this specific issue. We need to refactor all the way we handle dates (disable timezone in pg for instance) and it would be more of a breaking change than a bug fix. So we won't fix everything now but it will be fixed in V4 (should come in beta ~summer and released before the end of the year).

However, we did a small change in the admin (in #10033). It may fix your issue, it seems to work on my side. Are you able to test the PR on your side?

**Closed** 2021-05-11 07:26 UTC
Labels: source: core:database, status: confirmed, type: bug

**Comment by zarpilla** [comment] 2022-01-14 13:45
I think this bug is hapening again in strapi v4.0.4

**Comment by derrickmehaffy** [comment] 2022-01-18 21:54
> I think this bug is hapening again in strapi v4.0.4 i CET timezone

There is a new bug report for this here for v4: https://github.com/strapi/strapi/issues/11509
