### ISSUE TITLE
Send email validation error 500

### ISSUE THREAD

**Issue by Giildo** [strapi/strapi#9951] opened 2021-04-04 20:27 UTC
### Describe the bug

If I would like to send a request to send a new email validation, if the email is invalid, response is a error 500.
In the sendEmailConfirmation method, there is no check if the user is null.

### Steps to reproduce the behavior

I request a new email validation, if my email is not in the database, I get a error 500.

### Expected behavior

The method could check if the user is null, and return a generic code like the callback method and the "Auth.form.error.invalid".

### Screenshots

![Capture d’écran de 2021-04-04 22-22-15](https://user-images.githubusercontent.com/34237011/113520617-93a9a880-9594-11eb-9492-f9cbef6547d6.png)

### System

- Node.js version: 14.15.5
- NPM version: 7.6.3
- Yarn version: 1.22.5
- Strapi version: 3.5.4
- Database: PostgreSQL
- Operating system: Linux / Debian 10

**Comment by derrickmehaffy** [comment] 2021-04-05 15:05
Can you please provide reproduction steps for this as I was not able to reproduce.

Marking as closed until we get reproduction steps, if this is a custom implementation then please ask the question on our forum: https://forum.strapi.io

**Comment by Giildo** [comment] 2021-04-05 15:39
Is no a custom implementation, in your method `sendEmailConfirmation` in the Auth.js file in the `users-permissions` plugin you are this code (line 578) : 
```javascript
const user = await strapi.query('user', 'users-permissions').findOne({
  email: params.email,
});

if (user.confirmed) {
  return ctx.badRequest('already.confirmed');
}
```

But if the `email` is wrong, the `user` constant is `null` and when the method check if the user is confirmed, `user` being is `null` the app crash with an error 500 !

**Comment by derrickmehaffy** [comment] 2021-04-05 16:58
Email is required: https://github.com/strapi/strapi/blob/912cf44c4cee3a75dd3f0b603b8f7ddb60740588/packages/strapi-plugin-users-permissions/models/User.settings.json#L23

So what I'm confused on is how can the email be "wrong" or missing?

**Comment by Giildo** [comment] 2021-04-05 17:32
> Email is required:
> 
> https://github.com/strapi/strapi/blob/912cf44c4cee3a75dd3f0b603b8f7ddb60740588/packages/strapi-plugin-users-permissions/models/User.settings.json#L23
> 
> So what I'm confused on is how can the email be "wrong" or missing?

Yes I know!

If email is required and if is missing your are this condition:
```javascript
if (!params.email) {
  return ctx.badRequest('missing.email');
}
```
e.g.: if in my database I have one user with the email: `john@doe.fr` and he would like resend a email validation, he write in the text field: `john@doe.com`. When app load the user with this email, with this code:
```javascript
const user = await strapi.query('user', 'users-permissions').findOne({
  email: params.email,
});

if (user.confirmed) {
  return ctx.badRequest('already.confirmed');
}
```
It doesn't find a user with this email because no user has this email in the database. The `const user` will be null, and when app check `user.confirmed` a error thrown because, it doesn't read a property of null.

**Comment by derrickmehaffy** [comment] 2021-04-09 17:57
I see now, for reproduction, you need to send the wrong email to the resend confirmation endpoint which returns a 500 error and not a 400 error with the proper error message.

**Comment by alexandrebodin** [comment] 2022-06-05 15:23
Hi this was fixed in v4. 

FYI it will just return send:true even if the email is invalid to avoid leaking email info :)

**Closed by alexandrebodin** 2022-06-05 15:23 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: plugin:users-permissions
