### ISSUE TITLE
UID Regenerate new id

### ISSUE THREAD

**Issue by michael-proulx** [strapi/strapi#7681] opened 2020-09-01 19:44 UTC
**Describe the bug**
I use UID for slug field on my blog Articles, work perfectly when creating a new article, re-write the title, but on editing existing Article it regenerate the existing one, **lorem-ipsum** to **lorem-ipsum-1**, you can't delete **-1** because it mention that its already exist, but if my contributors save the article, the slug update to the new one... 

**Steps to reproduce the behavior**
1. Add UID to your Model
2. Create a new article
3. Edit the newly created article

**Expected behavior**
The UID field should only update when the associated field is modified, should not mention that the UID already exist if it attach to it.

**Screenshots**
![image](https://user-images.githubusercontent.com/23478544/91898844-5a116780-ec6a-11ea-9ac5-72a82b353b31.png)
![image](https://user-images.githubusercontent.com/23478544/91898996-8af19c80-ec6a-11ea-9cfc-6cb30dfdadd3.png)

**System**
- Strapi version: 3.1.4
- Database: MySQL

**Comment by michael-proulx** [comment] 2020-09-01 20:47
I found my issue, I had set `"timestamps": false` in my model, because I didn't want it when I was getting my data, but instead we are using GraphQL with Gatsby, so I can set it back to true, and it fix my issue.

![image](https://user-images.githubusercontent.com/23478544/91904275-a95b9600-ec72-11ea-9e22-efca5daa4558.png)

So I will let you chose if you close it or not for future improvement.

**Comment by lauriejim** [comment] 2020-09-07 15:35
Hello! Can you please give us more information about the fields related to your UID field please?

**Comment by michael-proulx** [comment] 2020-09-08 13:05
Hello,

The related field of my UID is 
```
"title": {
  "type": "string",
  "required": true,
  "unique": true
},
"slug": {
  "type": "uid",
  "targetField": "title",
  "required": true
},
```

So if timestamps is set to false, `"timestamps": false`, the UID have difficulty to retrieve his old value, I'm guessing it is looking for the update_at and/or create_at to regenerate the UID

**Comment by derrickmehaffy** [comment] 2020-09-08 15:01
:thinking: The UID should have no dependency on the timestamps

**Comment by derrickmehaffy** [comment] 2020-11-17 21:44
> Same for me, with models without a timestamp I have the problem with the UID.
> Note: Strapi 3.2.5

Can you please test on the latest version v3.3.3?

**Comment by nicolashmln** [comment] 2020-11-18 15:32
Still happening for me with v3.3.3

**Comment by derrickmehaffy** [comment] 2020-11-18 19:37
I can confirm this on v3.3.3 (timestamps disabled)

![image](https://user-images.githubusercontent.com/8593673/99578950-c6af1f00-299a-11eb-8b0c-52292d1817cb.png)

**Comment by rserafim** [comment] 2021-07-22 01:43
For me to v3.6.5!

**Comment by mashupmark** [comment] 2021-08-03 10:13
Im also having this issue running Strapi 3.6.5 and mongoDB.
It would be great if it could be resolved.

**Comment by rserafim** [comment] 2021-08-03 12:48
> Im also having this issue running Strapi 3.6.5 and mongoDB.
> It would be great if it could be resolved.

As I understand it, you need to keep the created and updated fields, which will work correctly again.
Unfortunately it gives up using Mongo, because in the next versions Strapi will not be supported.

**Comment by mashupmark** [comment] 2021-08-04 08:35
> > Im also having this issue running Strapi 3.6.5 and mongoDB.
> > It would be great if it could be resolved.
> 
> As I understand it, you need to keep the created and updated fields, which will work correctly again.
> Unfortunately it gives up using Mongo, because in the next versions Strapi will not be supported.

Yeah I know support for MongoDB will be dropped, but changing the DB is not an option for now.
I tested it with create and update Fields enabled and it kinda worked.
I need to use the uid without localization, meaning all languages of one page should share one uid. (Might be an edge case)
So for now I’m just using an text field which could be swapped out later.

But thanks for your help ;)

**Comment by derrickmehaffy** [comment] 2022-07-13 20:40
Fixed in v4 (you still need to hit the regen button but you shouldn't hit the issues described in this issue)

We don't plan to automatically regenerate the UID when you change the linked field if there is already a value as this would likely be a breaking change for users who don't want that logic. Since we can't have it both ways (easily at least) for the moment we are gonna keep the manual logic.

**Closed by derrickmehaffy** 2022-07-13 20:40 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-manager
