### ISSUE TITLE
Add nested components from content builder

### ISSUE THREAD

**Issue by Juliovazquezc** [strapi/strapi#12600] opened 2022-02-20 00:03 UTC
### Description
From the content builder, I can't add a nested component when a component has already been added to another component.

The only way to get this behavior is by modifying the component source code to add it.

### Steps to reproduce the behavior

1. Create three components
2. Add the second component to the first component
3. Add the third component to the first component into the nested second component, you won't be able to see the button component.

### Expected behavior
The possibility to add the component that has already been added to another component from the content builder

### Screenshots
![Strapi_1](https://user-images.githubusercontent.com/43428762/154823213-3d79f967-31c2-48ee-999f-9edd59744066.PNG)
![Strapi_2](https://user-images.githubusercontent.com/43428762/154823216-027e3f29-88e5-49a9-a7b6-efa502db0edf.PNG)

### System

- Node.js version: v14.15.4
- NPM version: 6.14.10
- Strapi version: 4.1.0
- Database: SQLite
- Operating system: Windows 10

**Comment by RemyMachado** [comment] 2022-02-21 10:12
This is a long time know issue.
There is already an open ticket here :  [here](https://github.com/strapi/strapi/issues/11319)

**Comment by kasonde** [comment] 2022-02-22 07:12
Closing this issue for the conversation to continue on #11319. (The issue is valid, there currently is a restriction on how far your nesting can go in the Content Type builder :) )

**Closed by kasonde** 2022-02-22 07:12 UTC
