### ISSUE TITLE
Import: imports will not terminate on first try

### ISSUE THREAD

**Issue by sirtobey** [strapi/strapi#16046] opened 2023-03-10 16:32 UTC
### Required System information

- Node.js version: v16.19.1
- Yarn version: 1.22.19
- Strapi version: 4.7.1
- Database: postgresql in Docker (14.6)
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When exporting data and then reimporting it, the process will run without being terminated. When importing only the config and then the files, it will fail. In the next try importing everything, it will then succeed.

### Steps to reproduce the behavior

1. run `yarn strapi export --no-encrypt`
2. run `yarn strapi import my.tar.gz` ➡️ process will not terminate
3. terminate the process
4. run `yarn strapi import my.tar.gz --only config` ➡️  will succeed
5. run `yarn strapi import my.tar.gz --only files` ➡️  will fail (see appendix 1)
6. run `yarn strapi import my.tar.gz` ➡️ this will succeed

### Expected behavior

Import succeeds and terminates process on first run.

### Additional context

Appendix 1:
```bash
$ strapi import -f export_20230310164153.tar.gz --only files
? The import will delete all data in your database and media files. Are you sure you want to proceed? Yes
Starting the compilation for TypeScript files in /Users/sirtobey/zeilenwerk/zw-website/cms
Starting import...
✔ assets: 2 transfered (size: 39.8 KB) (elapsed: 3 ms)
⠋ links: 0 transfered (size: 0) (elapsed: 0 ms) [2023-03-10 17:22:28.288] error: [ERROR] insert into "files_related_morphs" ("field", "file_id", "order", "related_id", "related_type") values ($1, $2, $3, $4, $5) - insert or update on table "files_related_morphs" violates foreign key constraint "files_related_morphs_fk"
⠋ links: 32 transfered (size: 6.4 KB) (elapsed: 1 ms) (6.2 MB/s)Import process failed.
error Command failed with exit code 1.
```

**Comment by sirtobey** [comment] 2023-03-10 20:16
New info what also works:
`yarn strapi import -f my.tar.gz --only config`
`yarn strapi import -f my.tar.gz`

**Comment by JWandscheer** [comment] 2023-03-13 13:02
Maybe related to this bug:
I'm trying to export my Strapi instance based on mysql and re-import it on a PostgreSQL instance.
The import fails with an error message very similar to the above:

`error: [ERROR] insert into "events_team_member_links" ("event_id", "team_member_id") values ($1, $2) - insert or update on table "events_team_member_links" violates foreign key constraint "events_team_member_links_inv_fk"`

**Required System information**

Node.js version: v18.15.0
Yarn version: 1.22.19
Strapi version: 4.7.1
Database: postgresql in Docker (15.1) / mariadb in Docker (10.6.8)
Operating system: macOS
Is your project Javascript or Typescript: Javascript

**Comment by niklasfjeldberg** [comment] 2023-03-19 20:49
@JWandscheer I am trying to do the same, and I get a similar error. Have you solved the issue?

`[ERROR] insert into "components_food_ingredients_ingredient_links" ("ingredient_id", "inv_ingredient_id") values ($1, $2) - insert or update on table "components_food_ingredients_ingredient_links" violates foreign key constraint "components_food_ingredients_ingredient_links_fk"`

**Required System information**
Node.js version: v18.14.2
NPM version: 9.5.0
Strapi version: 4.8.2
Database: to postgresql from sqlite
Operating system: Windows 11 using WSL Ubuntu
Is your project Javascript or Typescript: Javascript

**Comment by marcoautiero** [comment] 2023-03-20 10:30
@sirtobey I can't reproduce your issue, you could share with me your database or your export archive (if you don't have problems with it) 

same for you @JWandscheer and @niklasfjeldberg , if there are no sensistive information, you could sand me a backup of your database or the export archive by email marco.autiero@strapi.io

**Comment by niklasfjeldberg** [comment] 2023-03-20 10:53
@marcoautiero done. I could also add that this happens at different places. I have tried several times, and at one time I managed to get to Links, although it mostly stops at Entities.

**Comment by waterzhong2023** [comment] 2023-04-04 09:26
> 

Hi, I had the same error as '**violates foreign key constraint**', is there any solution available?

the command i ran is:
 **yarn  strapi import --file /app/my-strapi-export.tar.gz --force**

**Comment by niklasfjeldberg** [comment] 2023-04-07 19:13
@marcoautiero any update on the issue, have you managed to reproduce it?

**Comment by hpmax00** [comment] 2023-04-10 06:21
I also got the 'violates foreign key constraint' error, when use data transfer

**Comment by waterzhong2023** [comment] 2023-04-10 06:27
> I also got the 'violates foreign key constraint' error, when use data transfer

me too, I tried to compare the strapi import with pg-restore cli, I think the problems is that , 
  for pg-restore, it can solve  the constraint problem with a way as creating the constraint  at the last of the process;
  but for strapi import, I think it will create the constraint  at the same time as table. 

In my imagination, May be we need to re-arrange the sql steps in strapi import just likes the pg-restore does. 
What do you think ?

Regards,
Water

**Comment by derrickmehaffy** [comment] 2023-04-12 16:40
merged into https://github.com/strapi/strapi/issues/16363

**Closed as completed by derrickmehaffy** 2023-04-12 16:40 UTC
Labels: issue: bug, severity: medium, status: pending reproduction, source: core:data-transfer
