### ISSUE TITLE
Renaming a field with content-types builder make the server unable to restart

### ISSUE THREAD

**Issue by klys** [strapi/strapi#6765] opened 2020-06-22 15:27 UTC
**Describe the bug**

Just renaming a field which was before with capital uppercase to lowercase make this bug happen

**Steps to reproduce the behavior**

1. Create a new content-type and add one or more fields with capital letter uppercase and save it
2. Edit the previus content-type and change the uppercase to lowercase of field(s) and save
3. Server will not be able to restart again

**Expected behavior**

The strapi server should work as normally.

**Screenshots**
N/A

**Code snippets**
N/A

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.4
- Strapi version:  Strapi v3.0.0-beta.20.3
- Database: SQLite
- Operating system: Linux/Debian 4.9.210

**Additional context**

I just solved the problem by manually editing the SQLite database by deleting the field giving the error.

**Comment by derrickmehaffy** [comment] 2020-06-22 15:39
Closing as duplicate of https://github.com/strapi/strapi/issues/1114

**Closed by derrickmehaffy** 2020-06-22 15:39 UTC
