### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by GRajaram-ETV** [strapi/strapi#20650] opened 2024-06-27 16:03 UTC
### Required System information
- Node.js version: v20.11.1
- NPM version: 10.7.0
- yarn version: v1.22.21
- Strapi version:v5.0.0-rc.0
- Database: sqlite
- Operating system: Win32 x64
- Is your project Javascript or Typescript:

### Describe the bug

When I created the project and run yarn install & yarn build & yarn develop, the strapi admin page loads correctly. 

When I try to create a component , the yarn develop fails with the below error message

When I create even a very simple component and develo (yarn develop) get this error.

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined                                                 
at validateString (node:internal/validators:162:11)                                                                                          
at Object.join (node:path:433:7)                                                                                                             
at C:\Data\Development\strapi5\CMDB\node_modules\@strapi\core\dist\loaders\components.js:17:31                                   
at Array.forEach (<anonymous>)                                                                                                               
at C:\Data\Development\strapi5\CMDB\node_modules\@strapi\core\dist\loaders\components.js:14:32                                   
at Array.reduce (<anonymous>)                                                                                                                
at loadComponents (C:\Data\Development\strapi5\CMDB\node_modules\@strapi\core\dist\loaders\components.js:13:39)                  
at async Promise.all (index 5)                                                                                                               
at async Module.loadApplicationContext (C:\Data\Development\strapi5\CMDB\node_modules\@strapi\core\dist\loaders\index.js:12:3)   
at async Object.register (C:\Data\Development\strapi5\CMDB\node_modules\@strapi\core\dist\providers\registries.js:26:5)
```

Removing the component removes this error.

### Steps to reproduce the behavior

1. Run yarn develop
2. Crete a component and save
3. See error

### Expected behavior

Must be able to continue using the Strapi CMS with the created component

**Comment by derrickmehaffy** [comment] 2024-06-27 21:28
Confirmed by Webbist in the community

**Comment by Webbist-dev** [comment] 2024-06-27 21:29
Also experiencing this. 

On fresh install, created a new component in a collection, breaks then on reboot as reported. 

```
│       TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined                            
│       at Object.join (node:path:433:7)                                                                                        
│       at D:\personal\website\api\node_modules\@strapi\core\dist\loaders\components.js:17:31                                   
│       at Array.forEach (<anonymous>)                                                                                          
│       at D:\personal\website\api\node_modules\@strapi\core\dist\loaders\components.js:14:32                                   
│       at Array.reduce (<anonymous>)                                                                                           
│       at loadComponents (D:\personal\website\api\node_modules\@strapi\core\dist\loaders\components.js:13:39)                  
│       at async Promise.all (index 5)                                                                                          
│       at async Module.loadApplicationContext (D:\personal\website\api\node_modules\@strapi\core\dist\loaders\index.js:12:3)   │
│       at async Object.register (D:\personal\website\api\node_modules\@strapi\core\dist\providers\registries.js:26:5)          
│       at async Strapi.register (D:\personal\website\api\node_modules\@strapi\core\dist\Strapi.js:322:7)```

**Comment by derrickmehaffy** [comment] 2024-06-27 21:29
actually gonna close this as a duplicate of: https://github.com/strapi/strapi/issues/20057

**Closed** 2024-06-27 21:29 UTC
Labels: issue: bug, severity: high, status: confirmed, version: 5, source: core:core
