### ISSUE TITLE
Cannot filter by "users_permissions_user" after 4.14.6

### ISSUE THREAD

**Issue by abaksha-sc** [strapi/strapi#19304] opened 2024-01-23 13:13 UTC
### Required System information

- Node.js version: 18.13.0
- Yarn version: 1.22.21
- Strapi version: 4.17.1
- Database: 10.5.23-MariaDB-1:10.5.23+maria~ubu2004
- Operating system: Windows 10
- Is your project Javascript or Typescript: Typescript

### Describe the bug

After upgrade from 4.11 to 4.14.6 filtering by `users_permissions_user` doesn't work.

### Steps to reproduce the behavior

1. Create any collection with relation "manyToOne" to "users_permission_user"
2. Try to request items of this collection by URL: `/api/collection-items?filters[users_permissions_user][id]=123`

![image](https://github.com/strapi/strapi/assets/37663273/aa1bfc4f-2a02-44c1-9255-93af26e8a501)

### Expected behavior

Should return items filtered by user (as in version 4.11.5)

![image](https://github.com/strapi/strapi/assets/37663273/665e00d4-83aa-44b0-9d00-e36e0f57fc2f)

### Screenshots

![image](https://github.com/strapi/strapi/assets/37663273/6753269b-a4e8-4646-a0e9-1bab87caad82)

Or I even copied filter from admin URL after filter was added through UI:

![image](https://github.com/strapi/strapi/assets/37663273/5033ef73-e349-438a-9702-bc3646eb84ab)

### Additional context

Maybe I use incorrect filter but it works for version 4.11.5. So how to filter some collection by user ?

**Comment by abaksha-sc** [comment] 2024-01-23 14:09
Oh, after debugging of strapi server I found that now it's required to allow action "find" for "Users Permission" model. It was unclear and I would expect error 403 in this case instead of 400

![image](https://github.com/strapi/strapi/assets/37663273/f4c3c3ad-cd05-429b-8530-67ec9f210a95)

**Comment by derrickmehaffy** [comment] 2024-01-23 17:44
Indeed we plan (I believe) to throw 403s in Strapi v5 but couldn't do it in v4.

Note that by enabling that permission without a route middleware could leak user information on that route.

**Comment by abaksha-sc** [comment] 2024-01-23 17:49
> Note that by enabling that permission without a route middleware could leak user information on that route.

Yes, I understand and we decided to not enable action "find" and to implement some custom routes like `/api/my-transactions` and so on. But it seems we need manually get parameters (filters, sort, paging and so on) and then process them into `strapi.entityService.findMany(options)`. Or maybe you know easier ways?

**Comment by kasonde** [comment] 2024-01-24 14:47
> Or maybe you know easier ways?

If you're using the entity service in your solution, pass query params into the entity service so you don' have to construct those objects each time.

**Comment by abaksha-sc** [comment] 2024-01-25 07:58
Wow, I found that in version 4.11.5 filter like `filters[users_permissions_user][id]=123` just do nothing. It's absolutely not clear

**Comment by derrickmehaffy** [comment] 2024-02-09 17:05
We plan on changing this in v5 if you try to populate something without permissions it will throw a proper 403 error instead of just silently removing it: https://github.com/strapi/strapi/pull/19372

For now I'll close this as intended in v4 to be fixed in v5

**Closed by derrickmehaffy** 2024-02-09 17:05 UTC
