### ISSUE TITLE
Fail upgrade 4.5.0 with alter table unique constraint

### ISSUE THREAD

**Issue by pcriadoperez** [strapi/strapi#14824] opened 2022-11-09 21:31 UTC
### Required System information

- Node.js version: 16
- NPM version: 8
- Strapi version: 4.5.0
- Database: Postgres
- Operating system: Ubuntu

### Describe the bug

A get the following error when deploying the upgraded version.

### Expected behavior

I upgraded from 4.4.3 to 4.5.0 and I get the following error when trying to deploy and sever starts.
```
error: alter table "answers_question_links" add constraint "answers_question_links_unique" unique ("answer_id", "question_id") - could not create unique index "answers_question_links_unique"
```

PS. All I did was upgrade the version, I did not add any unique constraints

**Comment by Alex01d** [comment] 2022-11-09 23:47
I had the same issue. The problem was that I had duplicate relation records in {entity1}_{entity2}_links table.

**Comment by eucciferri** [comment] 2022-11-10 02:09
I had the same issue and I was able to solve it by removing duplicate relations as @Alex01d said before. Thanks!

**Comment by Marc-Roig** [comment] 2022-11-10 10:51
Thank you all for raising this issue! We are working on it.

From 4.5 we introduced ordering in the relations table, adding a unique constraint to prevent duplicates that could break the ordering.

 I will update you as soon as we decide how to proceed. A workaround now would be to manually remove duplicates in the relation `{entity1}_{entity2}_links` table

**Comment by Marc-Roig** [comment] 2022-11-11 15:16
⚠️ At your own discretion ⚠️ 
**This is a preliminary migration file** in case anyone is interested. It deletes duplicated rows of the tables in the `tablesToUpdate` variable.

This is not validated by the team, so use it knowing it can break things.

```js
'use strict';
​
// path: database/migrations
// filename: 2022.11.11T00.00.00.unique-relations.js
​
// Place here the tables with duplicated rows. The migration will delete the duplicated rows.
const tablesToUpdate = ['YOUR_TABLE_NAME']; // e.g. answers_question_links
​
async function up(trx) {
​
  for (const table of tablesToUpdate) {
    // Get relationship table column names
    const attributes = await trx.from(table).columnInfo();
​
    // Get the ones that end with `_id`
    const columns = Object.keys(attributes).filter((key) => key.endsWith('_id'));
​
    // There should only be two columns
    if (columns.length !== 2) {
      throw new Error(`Expected two columns to end with _id, got ${columns.length} instead`);
    }
​
    // Delete repeated rows
    await trx
      .from(`${table} as k1`)
      .where(
        'id',
        '>',
        trx
          .from(`${table} as k2`)
          .min('id')
          .where(`k2.${columns[0]}`, '=', trx.ref(`k1.${columns[0]}`))
          .where(`k2.${columns[1]}`, '=', trx.ref(`k1.${columns[1]}`))
      )
      .del();
  }
}
​
async function down() {}
​
module.exports = { up, down };
```

If you don't want to create a migration file, the query to execute is:

```sql
DELETE FROM {tableName} as T1
WHERE id > (
  SELECT MIN(id) FROM {tableName} T2
  WHERE T2.{entity1}_id = T1.{entity1}_id AND T2.{entity2}_id = T1.{entity2}_id
)
```

**Comment by ntarandek** [comment] 2022-11-12 08:48
After upgrading from 4.4.7 to 4.5.0 and cleaning up duplicates in some tables, everything went OK except one important detail.

My custom tsvector fields (using postgres) were removed from 3 tables that have them. I have the script ready to go so it was quick fix after I detected what happened.

Maybe this info helps someone else with suddenly missing custom fields.

**Comment by petersg83** [comment] 2022-11-14 09:30
@ntarandek Thank you for pointing this out! Can you open a new issue for it? I tried to reproduce with a simple color-picker custom field but it was correctly kept.

**Comment by petersg83** [comment] 2022-11-14 10:48
Thank you!

**Comment by willempie96** [comment] 2022-11-14 14:11
I tried to use the provided preliminary migration script but ran into a problem when trying to clean up my mariaDB. Apparently this syntax of the delete query wasn't working for my database. I had to rewrite it to: 

`
async function up(trx) {
  console.log('perform database migration');
  for (const table of tablesToUpdate) {
    console.log(`removed duplicates in ${table}`);

    // Get relationship table column names
    const attributes = await trx.from(table).columnInfo();

    // Get the ones that end with `_id`
    const columns = Object.keys(attributes).filter((key) => key.endsWith('_id'));

    // There should only be two columns
    if (columns.length !== 2) {
      throw new Error(`Expected two columns to end with _id, got ${columns.length} instead`);
    }

    // Delete repeated rows
    await trx
      .from(`${table}`)
      .where(
        'id',
        'in',
        trx
          .select('id')
          .from(`${table} as k1`)
          .where(
            'id',
            '>',
            trx
              .from(`${table} as k2`)
              .min('id')
              .where(`k2.${columns[0]}`, '=', trx.ref(`k1.${columns[0]}`))
              .where(`k2.${columns[1]}`, '=', trx.ref(`k1.${columns[1]}`))
          )
      )
      .del();
  }
}
`

Maybe this is useful for somebody else or when releasing the final migration.

**Comment by smoothdvd** [comment] 2022-11-17 06:23
Same issue when I upgrade from 4.5.0 to 4.5.1

**Comment by petersg83** [comment] 2022-11-17 08:19
Hello all :)
A migration script to help clean the duplicated relationships was created : https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.4.5-to-4.5.1.html

How does it work for you?

**Comment by pentcle** [comment] 2022-11-17 08:31
> Hello all :) A migration script to help clean the duplicated relationships was created : https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides/v4/migration-guide-4.4.5-to-4.5.1.html
> 
> How does it work for you?

i used it and it ran fine the first time i added the migration, ran `yarn build`, `yarn develop`, but have just sat down to work today, started the back-end, and am getting the same error again now 

``` error: alter table "globals_components" add constraint "globals_unique" unique ("entity_id", "component_id", "field", "component_type") - relation "globals_unique" already exists
error: alter table "globals_components" add constraint "globals_unique" unique ("entity_id", "component_id", "field", "component_type") - relation "globals_unique" already exists
```

**Comment by Marc-Roig** [comment] 2022-11-17 09:05
we moved the relations in to the main view, and that config is stored in the db. My guess is, if you try to downgrade, you have to edit the model here 
![image](https://user-images.githubusercontent.com/20578351/202403059-c5b00d98-60c0-4554-8f94-1ebfd5676b1e.png)

Just in case, Could you look if there is an index in your database called globals_unique in your globals_components table?

**Comment by pentcle** [comment] 2022-11-17 09:06
<img width="814" alt="image" src="https://user-images.githubusercontent.com/80323528/202403416-5fd9ed7d-fa25-4963-8c1c-4acf5b437c35.png">

**Comment by Marc-Roig** [comment] 2022-11-17 09:12
Using version 4.4.7, I created a globals components and it should not have the index 
![image](https://user-images.githubusercontent.com/20578351/202404590-f330870a-2793-4ee2-81f0-f8abaa991522.png)

I think that is what is causing the issue. I understand you are on  a version smaller than <4.5.0, right?

**Comment by pentcle** [comment] 2022-11-17 09:14
yes was using 4.1.11. Have I forgotten to run a migration here... better go and look at the migration guides :)

**Comment by Marc-Roig** [comment] 2022-11-17 09:17
I will try following the same process starting from 4.1.11 this afternoon. I will keep you updated during the day :)

**Comment by pentcle** [comment] 2022-11-17 09:38
i went through and individually upgraded through the versions from 4.1.1, one by one
- ran no migrations (including the one for 4.5) and it worked perfectly! 

4.2.x to 4.3.x
4.3.6 to 4.3.8
4.4.3 to 4.4.5

**Comment by Marc-Roig** [comment] 2022-11-17 09:55
So when you upgrade the first time it work ok, it is only when you restart de server that you have the problem?

**Comment by pentcle** [comment] 2022-11-17 09:57
yes, exactly, upon restarting server i get that error. 

i've downgraded to 4.4.7 and checked the indexes: 
<img width="263" alt="image" src="https://user-images.githubusercontent.com/80323528/202415508-033e23b0-eb5b-4dd4-821d-373056027bb6.png">

**Comment by Marc-Roig** [comment] 2022-11-17 10:00
alright, I will check with postgress later and see what can cause this 🤔 Can you create another issue for it? So we can close this one

**Comment by pentcle** [comment] 2022-11-17 10:16
done https://github.com/strapi/strapi/issues/14912

**Comment by Marc-Roig** [comment] 2022-11-17 10:42
Thank you! I will close this issue now.

**Closed by Marc-Roig** 2022-11-17 10:42 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-manager
