### ISSUE TITLE
Any relation to User Model crashes the server

### ISSUE THREAD

**Issue by enricobuehler** [strapi/strapi#4861] opened 2019-12-31 07:23 UTC
**Describe the bug**

When creating any relation with the `user` Content-Type the server crashes and isn't able to start.

After removing the relation from both settings files for the given models the server is able start again.
(e.g. `/api/user-data/models/user-data.settings.json` removing the `user` relation under `attributes`)

**Steps to reproduce the behavior**

1. Create a new model in the admin UI
2. Edit the `user` model to be related to the newly created model, also in the admin ui

**Expected behavior**

The relation is created and works.

**Screenshots**
-

**Code snippets**
The Terminal log:

```
Starting your app...
[2019-12-31T07:12:30.491Z] error Something went wrong in the model `User-data` with the attribute `user`
[2019-12-31T07:12:30.492Z] error TypeError: Cannot read property 'attributes' of undefined
  at Object.getNature (/srv/app/node_modules/strapi-utils/lib/models.js:150:33)
  at /srv/app/node_modules/strapi-connector-bookshelf/lib/mount-models.js:156:21
  at Array.forEach (<anonymous>)
  at /srv/app/node_modules/strapi-connector-bookshelf/lib/mount-models.js:149:40
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async Promise.all (index 2)
  at async Promise.all (index 1)
  at async Promise.all (index 0)
  at async DatabaseManager.initialize (/srv/app/node_modules/strapi-database/lib/database-manager.js:39:7)
  at async Strapi.load (/srv/app/node_modules/strapi/lib/Strapi.js:362:5)
  at async Strapi.start (/srv/app/node_modules/strapi/lib/Strapi.js:196:7)
```

**System**
- Node.js version: v12.13.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.3
- Database: mongoDB
- Operating system: Ubuntu 18.04.3 LTS

**Additional context**
- Using strapi docker

**Comment by derrickmehaffy** [comment] 2019-12-31 07:44
Can you please provide examples of the relations you are trying to make and the $model.settings.json files for your model and the users model.

I just tested locally making some relations to the user model and didn't hit any issues, so I need more information to reproduce this.

**Comment by enricobuehler** [comment] 2019-12-31 08:25
I just tried it on a new strapi installation, and was able to reproduce the error. Although in this case it only happened with a has and belongs to one relation.

My initial use-case for the relation was a userData model which is related to the user model and contains information about users like adresses etc. (would be protected by a owner policy). 

`User.settings.json`:

{
  "connection": "default",
  "collectionName": "users-permissions_user",
  "info": {
    "name": "user",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "confirmed": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions",
      "configurable": false
    },
    "project": {
      "model": "project",
      "via": "user"
    }
  }

`project.settings.json`:


{
  "connection": "default",
  "collectionName": "projects",
  "info": {
    "name": "project"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "banner": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    },
    "thumbnail": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    },
    "content": {
      "type": "dynamiczone",
      "components": [
        "project-components.gallery",
        "project-components.text",
        "project-components.gallery-item",
        "project-components.paragraph"
      ]
    },
    "clients": {
      "via": "projects",
      "collection": "customer",
      "dominant": true
    },
    "user": {
      "via": "project",
      "model": "user"
    }
  }
}

**Comment by enricobuehler** [comment] 2019-12-31 08:59
Creating a relation between 2 models that arent user models works as expected. Just happening with the `user` model.

**Comment by enricobuehler** [comment] 2019-12-31 09:14
Just tested it in a different environment, new installation, same error. (Windows 10, create-strapi-app, quickstart)

`[2019-12-31T09:03:45.628Z] debug GET /content-manager/content-types (20 ms) 200
[2019-12-31T09:03:45.692Z] debug GET /content-type-builder/components (9 ms) 200
[2019-12-31T09:03:45.693Z] debug GET /content-type-builder/content-types (7 ms) 200
[2019-12-31T09:10:46.224Z] info File changed: C:\Users\enric\Documents\strapi\api\user-data\models\user-data.settings.json
[2019-12-31T09:10:46.228Z] debug PUT /content-type-builder/content-types/plugins::users-permissions.user (44 ms) 201
[2019-12-31T09:10:46.229Z] info The server is restarting

[2019-12-31T09:10:46.236Z] info File created: C:\Users\enric\Documents\strapi\extensions\users-permissions\models\User.settings.json
[2019-12-31T09:10:48.558Z] error Something went wrong in the model `User-data` with the attribute `user`
[2019-12-31T09:10:48.559Z] error TypeError: Cannot read property 'attributes' of undefined
    at Object.getNature (C:\Users\enric\Documents\strapi\node_modules\strapi-utils\lib\models.js:150:33)
    at Object.keys.forEach.name (C:\Users\enric\Documents\strapi\node_modules\strapi-connector-bookshelf\lib\mount-models.js:156:21)
    at Array.forEach (<anonymous>)
    at Object.keys.map (C:\Users\enric\Documents\strapi\node_modules\strapi-connector-bookshelf\lib\mount-models.js:149:40)      at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by lauriejim** [comment] 2019-12-31 16:24
I set this issue as confirmed - many people have issues about relations with **User** model.

**Comment by ralphchristianeclipse** [comment] 2020-01-02 19:17
The issue is about

the plugin field is missing when created.

    "user": {
      "plugin": "users-permissions",
      "via": "memberships",
      "model": "user"
    },

try to add plugin field with the value users-permissions

**Comment by red-sight** [comment] 2020-01-05 14:38
I

> The issue is about
> 
> the plugin field is missing when created.
> 
> ```
> "user": {
>   "plugin": "users-permissions",
>   "via": "memberships",
>   "model": "user"
> },
> ```
> 
> try to add plugin field with the value users-permissions

I've got this error. After any adding or editing fields with user model, the server crashes after restart.
And, yes, adding the plugin field manually fixes the problem. But after any editing user fileds, I have to fix it again.

**Comment by alexandrebodin** [comment] 2020-01-08 13:42
Hi, This has been fixed in beta.18.4.

Closing for now. Will reopen if you still have issues once you upgrade

**Closed by alexandrebodin** 2020-01-08 13:42 UTC
Labels: priority: medium, status: confirmed, type: bug 🐛
