### ISSUE TITLE
Media Library gets error 500

### ISSUE THREAD

**Issue by lodisy** [strapi/strapi#6973] opened 2020-07-10 21:49 UTC
The upload / media works fine until today, I found it generated error 500 when try adding new images.

**Describe the bug**

Media Library is unavailable, it shows no pics which uploaded before.

**Steps to reproduce the behavior**

1. Go to media library / click to upload media(as fields or in the editor) in the post page
2. Click on upload
3. See an error(500) occurs / if in the post upload, will see "an error occured, there is no assets in the library"

**Expected behavior**
`[2020-07-10T21:37:26.325Z] debug GET /upload/files?_limit=10&_start=0&_sort=updated_at%3ADESC (18 ms) 500`

**Screenshots**

![Screenshot 2020-07-10 at 23.44.12.jpg](https://i.loli.net/2020/07/11/jI8ON4eb7KRBGUg.jpg)
![Screenshot 2020-07-10 at 23.43.18.jpg](https://i.loli.net/2020/07/11/6bFUtcQJ8kCLGrw.jpg)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: V14.4.0
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: SQLite
- Operating system: macOS Catalina 10.15.5

**Comment by derrickmehaffy** [comment] 2020-07-11 00:44
Can you please provide any additional logs you see in the Strapi terminal

**Comment by lodisy** [comment] 2020-07-11 06:44
`Error: The target polymorphic type "categories" is not one of the defined target types`

Seems the same with the issue #6347 

Solved by re add image field for categories and delete all the images.

**Comment by derrickmehaffy** [comment] 2020-11-23 15:46
duplicate of: https://github.com/strapi/strapi/issues/6347

**Closed by derrickmehaffy** 2020-11-23 15:46 UTC
Labels: status: pending reproduction
