### ISSUE TITLE
strapi start error

### ISSUE THREAD

**Issue by soccer99** [strapi/strapi#199] opened 2017-04-12 00:23 UTC
**Node.js version**: v7.5.0
**npm version**: 4.1.2
"strapi": "~1.5.6"
Mac osx 10.12.4

Brand new strapi project.  Set it up and tried to run it.  Got this error

```
/usr/local/lib/node_modules/strapi/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: 4.x
    at new SemVer (/usr/local/lib/node_modules/strapi/node_modules/semver/semver.js:293:11)
    at SemVer.compare (/usr/local/lib/node_modules/strapi/node_modules/semver/semver.js:342:13)
    at compare (/usr/local/lib/node_modules/strapi/node_modules/semver/semver.js:566:31)
    at Function.gt (/usr/local/lib/node_modules/strapi/node_modules/semver/semver.js:595:10)
    at Strapi.isLocalStrapiValid (/usr/local/lib/node_modules/strapi/lib/private/isLocalStrapiValid.js:75:14)
    at Command.module.exports (/usr/local/lib/node_modules/strapi/bin/strapi-start.js:49:14)
    at Command.listener (/usr/local/lib/node_modules/strapi/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:192:7)
    at Command.parseArgs (/usr/local/lib/node_modules/strapi/node_modules/commander/index.js:615:12)
```

**Comment by Aurelsicoko** [comment] 2017-04-12 14:16
Sorry, it should be fixed, we just published a patch on npm. It was caused by changes that we made  yesterday.

**Closed by Aurelsicoko** 2017-04-12 14:16 UTC
