### ISSUE TITLE
403 Forbidden error on GET /users-permissions/init

### ISSUE THREAD

**Issue by nightire** [strapi/strapi#3284] opened 2019-05-17 08:14 UTC
**Informations**
- **Node.js version**: v10.5.3
- **NPM version**: v6.9.0
- **Strapi version**: v3.0.0-alpha.26 ~~.2~~
- **Database**: PG v11.3
- **Operating system**: macOS v10.14.4
- **(Optional) Link to your Project**: private

**What is the current behavior?**

Access `/admin`, there's a request of `GET /users-permissions/init` will get a `403 Forbidden` error.

**Steps to reproduce the problem**

The service was working normally, however, after clearing the localStorage, you can not access `/admin` anymore.

**What is the expected behavior?**

It should work even if you clear the localStorage, like request user to log in again.

**Suggested solutions**

There's a manual way to solve this issue temporarily:

1. open `plugins/users-permissions/middlewares/users-permissions/defaults.json` file
2. set `user-permissions/enabled` to `false`, wait for the service restart, then refresh `/admin` page
3. now it will ask for admin login, do it as usual
4. once sign in successfully, change `user-permissions/enabled` to `true` again, otherwise, you will encounter errors related with lack of authorization header after another refreshing.

Nevertheless, this is still a bug needs to be fixed, I don't have free time to dig in further, the solution above is all I can give ATM.

**Comment by lauriejim** [comment] 2019-05-21 09:54
Hello!

Can you please give me exact steps I have to do to reproduce your issue please.
(with a list of steps from the `strapi new`)

I juste tried to delete my session and local storage and all works well.
I think I miss something.

**Comment by nightire** [comment] 2019-05-21 10:37
I'm sorry, I can't reproduce this issue with a new strapi project either. I only encounter this on an existing one uses strapi v3.0.0-alpha.26 (not v3.0.0-alpha.26.2, I made a typo in the main post).

We're in developing now, I'll double check this after we upgrade strapi to the latest version.

**Comment by lauriejim** [comment] 2019-05-23 12:53
Ho okay setup has failed on this version of Strapi I think. 
I close this issue, will reopen it if needed.

**Closed by lauriejim** 2019-05-23 12:53 UTC
Labels: type: help wanted 🤷‍♂️

**Comment by georgezouq** [comment] 2019-05-28 05:09
I have the same issues just after `strapi new`...  Is this fixed?

**Comment by nightire** [comment] 2019-05-28 10:05
> I have the same issues just after `strapi new`... Is this fixed?

What's your version of strapi? I can only reproduce this issue in my own project uses an older version.

**Comment by anguspiv** [comment] 2019-07-01 00:12
I am getting this same issue:
Node.js version: v10.16.0
NPM version: v6.9.0
Strapi version: v3.0.0-beta.8
Database: sqlite 3.26.0
Operating system: macOS v10.14.5

This is following the quick start guide: https://strapi.io/documentation/3.0.0-beta.x/getting-started/quick-start.html

**Comment by nightire** [comment] 2019-07-01 03:02
@georgezouq @anguspiv 

Please check your permission setting at:

`Roles & Permissions -> Public -> User Permissions -> init`

make sure this one is checked, otherwise, you will encounter the same issue again.

If you can not enter admin UI, please refer to [the suggested solution above](https://github.com/strapi/strapi/issues/3284#issue-445319771).

**Comment by anguspiv** [comment] 2019-07-01 03:49
I originally could not access the admin UI. I had tried to follow the solution mentioned above, but could not find the files mentioned. 

I created a new project with `strapi new <project-title> --quickstart` and was suddenly able to access the admin as described. 

Seems I had a bad install the first time. Thank you for your help

**Comment by nightire** [comment] 2019-07-01 04:16
@anguspiv Because in beta, that file was removed to a dedicated npm package, you can find it in `node_modules` folder. For more information, you can refer to the beta migration document.

**Comment by forethoughtde** [comment] 2019-09-24 14:56
This issue still exists. Is there any fix for this?

**Comment by truongnguyen1912** [comment] 2019-12-30 17:32
Following is working for me:

Open table users-permissions_role
Find record with "action" column = "init"
Update role column from 1 to 2
That means Public user has ability to init the UserPermission plugin.

**Comment by onexdata** [comment] 2020-01-01 00:39
@truongnguyen1912 I think you meant the users-permissions_permission table, and also, make sure the "enabled" column is set to 1 as well

**Comment by mswaidan** [comment] 2020-01-23 20:19
I'm getting the same issue using Strapi 3.0.0-beta.18.6, with a remote mysql db.
on the initial run, I get the following error:
```
[2020-01-23T20:02:39.463Z] error Bootstrap function in plugin "users-permissions" failed
[2020-01-23T20:02:39.464Z] error TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
```
I can run `strapi dev` a second time, strapi starts but I get the `403` on `GET /users-permissions/init`
This workaround allowed me to get going: https://github.com/strapi/strapi/issues/3284#issuecomment-570010174

**Comment by steffens1** [comment] 2020-01-28 22:51
**Informations**

**Node.js version:** v10.8.0
**NPM version:** v6.10.2
**Strapi version:** Strapi v3.0.0-beta.18.6

What is the current behavior?
Access /admin, there's a request of GET /users-permissions/init will get a 403 Forbidden error.

Suggested solutions
There's a manual way to solve this issue:

> open plugins/users-permissions/middlewares/users-permissions/defaults.json file
> set user-permissions/enabled to false, wait for the service restart, then refresh /admin page
> now it will ask for admin login

> **enable  role "public"  user-permission **init**,  that's all**

**Comment by nightire** [comment] 2020-01-29 02:27
> **enable role "public" user-permission **init**, that's all**

If you can't access the `/admin`, how do you enable the role "public" for user-permission init?

**Comment by carljustineoyales** [comment] 2020-01-29 17:22
im getting this same issue after deploying to heroku

**Comment by carljustineoyales** [comment] 2020-01-29 17:22
how to fix when it is deployed to heroku?

**Comment by steffens1** [comment] 2020-01-29 21:52
> > **enable role "public" user-permission **init**, that's all**
> 
> If you can't access the `/admin`, how do you enable the role "public" for user-permission init?


open node_modules/strapi-plugin-users-permissions/middlewares/users-permissions/defaults.json file
set user-permissions/enabled to false, wait for the service restart, then refresh /admin page
now it will ask for admin login

**Comment by carljustineoyales** [comment] 2020-01-30 01:48
ok, I just fixed my issue by editing the MySQL database. I'm using an add on called JawsDB and edited the users-permissions_permission table using the MySQL Workbench, search the 'init' under action column then changing the role column to 2 because the id of the public role in the users-permissions_role is 2. after applying the changes, reload <heroku-site>/admin then it works

**Comment by nightire** [comment] 2020-01-30 02:07
> open node_modules/strapi-plugin-users-permissions/middlewares/users-permissions/defaults.json file
> set user-permissions/enabled to false, wait for the service restart, then refresh /admin page
> now it will ask for admin login

This is exactly how I did for a temporary solution in the original post, so I don't know what's the point of your reply, sorry.

**Comment by raygerrard** [comment] 2020-02-10 02:35
I am getting this error connecting to a remote mysql db on aws. changing init role to 2 did let me create the first user. Why does this work? should this be changed back to 1 after first login?

**Comment by bhall2001** [comment] 2020-02-19 12:12
I'm evaluating strapi again for use in projects. Not a good first impression. I ran into this same bug setting up a new project with remote maria db on aws.  

https://github.com/strapi/strapi/issues/3284#issuecomment-579505619 fixed it for me. I presume the original setting should be reset but would like to hear from someone in the know..

**Comment by allealdine** [comment] 2020-07-28 12:01
I fixed my issue by removing node_modules and yarn.lock.
