### ISSUE TITLE
sendgrid plugin causing error in typescript production build - 2

### ISSUE THREAD

**Issue by dsfaccini** [strapi/strapi#15698] opened 2023-02-02 23:28 UTC
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
## Bug report

The bug prevents "npm run build" to run without just cause and comes from the sendgrid plugin

Note: Sorry I seem to have posted this issue on my work account. Also I forgot to delete the start of an html comment that rendered the issue void

### Required System information

- Node.js version: v18.13.0
- NPM version: 8.19.3
- Strapi version: 4.5.6
- Database: pg
- Operating system: Ubuntu 20.04.5 LTS (GNU/Linux 5.15.79.1-microsoft-standard-WSL2 x86_64)

### Describe the bug

`Building your admin UI with production configuration...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
node_modules/@strapi/admin/utils/create-cache-dir.js:82:33`

### Steps to reproduce the behavior

run following commands
`nvm use 18`
`npx create-strapi-app my-app --ts`
`cd my-app`
`echo NODE_ENV=development >> .env`
`yarn add @strapi/provider-email-sendgrid`
`yarn build`

This should build the admin panel with dev configuration, it should work as is

now run the following commands

`cp -r config production`
`mkdir config/env`
`mv production config/env/production`
`touch config/env/production/plugins.ts`

this will mimic the dev configuration for a production environment with the exception that it'll include a plugins file
now go to [the sendgrid plugin url](https://market.strapi.io/providers/@strapi-provider-email-sendgrid) and copy the content of the plugins.js file into Your plugins.ts file

last but not least open Your .env file and replace NODE_ENV=development with NODE_ENV=production
try the `yarn build` command again

### Expected behavior

It should build normally, but it throws an error because the sendgrid plugin apparently doesn't have a plugin file

### Code snippets

the code snippet on the file `node_modules/@strapi/admin/utils/create-cache-dir.js:82:33` looks like this
```js
const pluginsWithFront = Object.keys(plugins)
    .filter((pluginName) => {
      const pluginInfo = plugins[pluginName];
      console.log({pathToPlugin: pluginInfo.pathToPlugin}) // I added this
      return fs.existsSync(path.resolve(pluginInfo.pathToPlugin, 'strapi-admin.js'));
    })
    .map((name) => ({ name, ...plugins[name] }));
```

### Screenshots

on the screenshot You can see the logged plugins (I added a try so that the loop continues, if You don't add the try it only logs until the plugin that doesn't have a path attribute
![image](https://user-images.githubusercontent.com/105485043/212431318-1fe72334-38ff-4544-912f-80f0fefa1577.png)

### Additional context

[package.json](https://github.com/strapi/strapi/files/10415856/package.-.Copy.txt)

**Comment by derrickmehaffy** [comment] 2023-02-03 04:02
Can you please provide the plugins.ts file?

Also as a sub note you absolutely do not need to copy the entire config directory over to production. Strapi will read the base config and will merge the keys for you if there any changes but you should not and do not need to copy the whole directory.

**Comment by dsfaccini** [comment] 2023-02-03 15:07
Sure

```typescript
// config/env/production/plugins.ts
// https://www.npmjs.com/package/@strapi/provider-upload-aws-s3

module.exports = ({ env }: {env: any}) => ({
        email: {
                config: {
                        provider: 'sendgrid',
                        providerOptions: {
                                apiKey: env('SENDGRID_API_KEY')
                        },
                        settings: {
                                defaultFrom: 'strapi@dsfaccini.com'
                        }
                }
        }
});
```

**Comment by StrapiShaun** [comment] 2023-02-07 05:19
Hello @dsfaccini, for a TypeScript project, try using `export default` in place of `module.exports =` . You can see more details about the plugins config file in the [documentation](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/plugins.html).

**Comment by dsfaccini** [comment] 2023-02-07 19:59
thank You for the tip, the same error appears when I change the syntax though

**Comment by derrickmehaffy** [comment] 2023-02-07 22:33
> Sure
> 
> ```ts
> // config/env/production/plugins.ts
> // https://www.npmjs.com/package/@strapi/provider-upload-aws-s3
> 
> module.exports = ({ env }: {env: any}) => ({
>         email: {
>                 config: {
>                         provider: 'sendgrid',
>                         providerOptions: {
>                                 apiKey: env('SENDGRID_API_KEY')
>                         },
>                         settings: {
>                                 defaultFrom: 'strapi@dsfaccini.com'
>                         }
>                 }
>         }
> });
> ```

Can you provide your root plugins file should be inside of `./config/plugins.ts` not just your production one

**Comment by dsfaccini** [comment] 2023-02-07 23:24
I don't have one under root, just under production
Shouldn't be relevant though, right? Strapi is using the production one to build. The development build is building fine

**Comment by derrickmehaffy** [comment] 2023-02-13 15:56
Based on the error you are getting there is some plugin that is trying to be loaded that shouldn't (given the name is undefined)

**Comment by derrickmehaffy** [comment] 2023-02-16 17:48
> One specific plugin really, probably the one I put on the title

Sendgrid itself isn't a plugin, it's just a provider that the upload plugin loads, there seems to be an additional plugin that is trying to be loaded (hence the undefined).

Could you possibly share your entire codebase? I was testing with a v4.6.1 TS project using sendgrid and could not reproduce the issue you are seeing.

**Comment by derrickmehaffy** [comment] 2023-02-27 22:20
I tested on both v4.6.2 and v4.7.0 with sendgrid and could not reproduce this, as it's been a while since we have an update from the user, I'm marking this as closed until we have more information.

**Closed by derrickmehaffy** 2023-02-27 22:20 UTC
Labels: issue: bug, severity: medium, status: pending reproduction
