### ISSUE TITLE
Strapi hard crashes when labeling field name ID or id_ or some variation of id

### ISSUE THREAD

**Issue by dogunbound** [strapi/strapi#13269] opened 2022-05-08 23:16 UTC
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.1.8
- Database: pg
- Operating system: linux

### Describe the bug

```error: alter table "coins" alter column "id" drop not null - column "id" is in a primary key
error: alter table "coins" alter column "id" drop not null - column "id" is in a primary key
    at Parser.parseErrorMessage (/home/dogunbound/work/DigitalHumanities/pgSyriosv4/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/dogunbound/work/DigitalHumanities/pgSyriosv4/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/dogunbound/work/DigitalHumanities/pgSyriosv4/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/dogunbound/work/DigitalHumanities/pgSyriosv4/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

Labeling field names as ID, or id_ (possibly others) hard crashes strapi.
### Steps to reproduce the behavior

1. Create single type / collection
2. add field with field name ID, id_, possibly other variations
3. save

### Expected behavior

Warning for invalid field names.

### Screenshots

Should be easily reproducible.

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

Not a huge problem because I can just label my field name as <collection_name>_id (coin_id in my case) as a workaround.

**Comment by bolg55** [comment] 2022-05-09 15:03
Duplicate of #1198

**Closed by bolg55** 2022-05-09 15:03 UTC
Labels: status: duplicate
