### ISSUE TITLE
_locale filter completely fails using REST

### ISSUE THREAD

**Issue by wintercounter** [strapi/strapi#10714] opened 2021-08-09 22:23 UTC
### Describe the bug

I'm having some issues with locales. Localizations are simply not returned by default (using Graphql, it is). If I add `_locale=all`, I'll get a 400 error:

```
Your filters contain a field 'locale' that doesn't appear on your model definition nor its relations.
```

My GET query is simply:
```
/settings?_locale=all
```

`settings` is a single type (the same is happening with collection types).

Using this GQL query, it's all good, I get the `localizations` field with all of my translations:

```
settings {
    translations {
        word
        localizations {
            word
        }
    }
}

Without `_locale` in REST I don't get the `localizations` field at all.
```

### Steps to reproduce the behavior

Not sure if it's reproducible on a clean install, I'm updating/migrating since 3.2, never had issues that weren't reproducible.

However, I don't know where to start debugging, some help/guidance would be great. It seems weird that such a basic feature is failing for me, feels like there was an issue with my upgrade at some point.

### Expected behavior

`_locale` doesn't fail with 400 error.

### System

- Node.js version: v14
- Strapi version:  3.6.6
- Database: MariaDB

**Comment by derrickmehaffy** [comment] 2022-01-05 21:41
Can't reproduce on v4, marking as closed

**Closed by derrickmehaffy** 2022-01-05 21:41 UTC
Labels: status: pending reproduction, source: plugin:i18n
