### ISSUE TITLE
Problem creating strapi application

### ISSUE THREAD

**Issue by Tansito** [strapi/strapi#4512] opened 2019-11-12 13:56 UTC
**Describe the bug**
Creating a project with `npx create-strapi-app` and `yarn create strapi-app` generates the next error while installing dependencies:
```
✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: autoreconf: command not found
```

**Steps to reproduce the behavior**
1. Execute `npx create-strapi-app my-project`
2. Setup Custom with all the values by default and mongo as db

**Expected behavior**
Create the project correctly.

**System**
- Node.js version: v12.12.0
- NPM version: v6.11.3
- Operating system: macOS Catalina 10.15.1

**Comment by izzuddinnatsir** [comment] 2019-11-12 14:18
That error told you that autoreconf executable is not install in your system, install autoreconf first then try again

**Comment by abdonrd** [comment] 2019-11-12 14:35
I can reproduce the issue!

**Comment by Tansito** [comment] 2019-11-12 14:40
Installing the next packages do the trick:
```
brew install libtool automake autoconf nasm
```
The problem that I see is that without that libraries two days ago I could create projects without problems but now the process breaks following the steps that the documentation has. My assumption is that one of the dependencies of the project changed probably (and I don't know if this should be documented too).

**Comment by derrickmehaffy** [comment] 2019-11-12 15:57
Marking as closed as not a strapi issue but user environment.

Do feel free to continue the discussion.

**Closed by derrickmehaffy** 2019-11-12 15:57 UTC

**Comment by abdonrd** [comment] 2019-11-12 15:58
It's a little strange, because a couple of days ago this didn't happen to me.

**Comment by abdonrd** [comment] 2019-11-14 17:12
@Tansito you had previously been able to create applications? Or was it the first time?

**Comment by Tansito** [comment] 2019-11-14 20:15
Yeah, I have created various applications before, even recently. That's why I opened the issue because it was a weird behaviour that I didn't expect after creating a good couple of apps.

**Comment by abdonrd** [comment] 2019-11-19 11:11
For me works with:

```
brew install autoconf automake libtool libpng nasm pkg-config
```
