### ISSUE TITLE
Hierarchical collection

### ISSUE THREAD

**Issue by arichard-info** [strapi/strapi#6329] opened 2020-05-23 14:10 UTC
- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

Hello everyone!

It would be really interesting to easily manage hierarchical content.
Currently, with the "**has many**" relationship, you can easily set up a parent/child link between two entries of the same collection, here is an example for a page collection : 

![relation](https://user-images.githubusercontent.com/56544866/82732285-91d44f00-9d0c-11ea-8fe8-13a0321ec5ed.PNG)

An item can have one parent, and several children. This can be useful when you want to set up a page tree system for example, it allows to manage urls thanks to the hierarchy.

But it would be much more convenient, if it was possible to look and manage these relationships directly from the list view of the collection. For example, the WordPress [Nested Pages](https://fr.wordpress.org/plugins/wp-nested-pages/) extension, offers an interface and drag & drop for this : 

![nested_pages_wordpress](https://user-images.githubusercontent.com/56544866/82732395-3bb3db80-9d0d-11ea-8ad0-2f75506659fb.gif)

Come to think of it, on Strapi's side, it might look something like this : 

<img width="1689" alt="sort" src="https://user-images.githubusercontent.com/56544866/82732425-6d2ca700-9d0d-11ea-87b0-1661ca96341d.png">

Parent/child relationships could be managed by drag & drop, as well as the order of entries (linked with this feature request : https://github.com/strapi/strapi/issues/3946). We could also fold the groups of entries. 

To do this, one could imagine that additional options would be available to make a collection hierarchical and sortable. This could create implicit fields: parent / children / order, which would be updated when dragging & dropping.

![collection_advanced_options](https://user-images.githubusercontent.com/56544866/82732568-4b7fef80-9d0e-11ea-9dd7-6e966aa88bb4.PNG)

This offers several possibilities at the API level: retrieving children of an element, retrieving an element according to its parent etc...

It also gives the possibility to generate fields thanks to the hierarchy, here is a basic example : 

```javascript
// page.js
module.exports = {
  beforeSave: async (model, attrs, options) => {
    let fullSlug = "";
   // here we update the field "full_slug",  by concatenating the parent's one
    if (model.relations && model.relations.parent) {
      const parent = model.relations.parent;
      const parentSlug = parent.attributes && parent.attributes.full_slug;
      fullSlug = `${parentSlug}/${attrs.slug}`;
    } else {
      fullSlug = attrs.slug;
    }

    if (options.method === "insert") {
      model.set("full_slug", fullSlug);
    } else if (options.method === "update") {
      attrs.full_slug = fullSlug;
    }
  },
};

``` 

the most common case, would obviously be the management of page trees, but also, for example, the hierarchy of documents, a list of employees, etc.

**Comment by derrickmehaffy** [comment] 2020-05-23 15:50
While this would be nice, I don't think it should be the default at all. Strapi is not just designed for your typical "wordpress" website. Relations are not as cut and dry as wordpress does it. There is a lot of thought that needs to be put into what type of relation and the structure of the data being returned.

Personally I quite like Strapi's solution over your normal "drag and drop" methods simply because it's easy to define in the backend setting files.

**Comment by arichard-info** [comment] 2020-05-23 18:48
I have no doubt that there are many different use cases, and Strapi is not a new WordPress backoffice. But I think a lot of people are interested in it to manage editorial content, often hierarchical for the site tree structure and SEO.  

As I said, it is already technically possible to implement such relationships. You can get out of it with a relationship, and some lifecycle functions to generate the fields you need (as long as you set it up for each collection you want). I just propose to make the parent/child relationship more visible in the list view, and allow a more visual and logical management. 

The drag & drop is only an abstraction for the "order" or "parent" fields of a model, in the list view. This is something that already exists in the strapi backoffice (management of the order of fields in a template for example). This would allow a non-technical user to manage it more easily. It might still be possible to modify these fields individually for each entry.

I didn't talk about making it a default feature. Besides I think it's a perfect reason for an extension, which would enrich the management of collections on the list view, by possibly adding new fields in the concerned models (it comes together with this request: https://github.com/strapi/strapi/issues/3946). I think it's rather logical that an extension can add fields in some models, as long as it doesn't alter the model and its basic functionalities.

I'll be happy to contribute to this kind of extension, when possible 😉

**Comment by virgil9306** [comment] 2020-05-25 20:35
@arichard-info 

How are you planning on implementing this?

I also need this functionality, and was planning on just using the "one-to-many" and having my app interpret that as a hierarchy. At least until something better comes along.

But it doesn't _look_ like a hierarchy in Strapi, which would be hard for my non-technical users to configure/wrap their heads around a "one-to-many" relationship.

I have not written a Strapi extension before, but could it literally just slapping a nice front-end on top of a "one-to-many" relationship underlying? If so, that might be worth giving a shot...

**Comment by cyp3rius** [comment] 2020-05-26 09:43
@arichard-info we've got a similar case on RnD now but more from view perspective than collection advanced options. In short:

1. Work with collections as-is now
2. If collection has a relation field based on which a hierarchy might be created than in **Configure the view** under View section there should be a toggle for **Enable hierarchy view** with possibility to choose a field over which it should be the view being created

We're working on an extension to Content Manager plugin. Hope to get some PoC soon :)

**Comment by jankallewulf** [comment] 2020-06-12 12:14
@cyp3rius is there already an update on the work you have mentioned in regards to the Content Manager plugin? Would be amazing!

**Comment by cyp3rius** [comment] 2020-06-12 13:31
@jankallewulf hope to get something till end of next week :) The PoC is working, now doing the alignments to make it more generic. 
We are going to publish it as an extension to Content Manager Plugin, maybe some time in the future it will become part of it :)

**Comment by Aurelsicoko** [comment] 2020-06-12 13:35
Wow, it seems to be an amazing work done here! First, I would say congratulations. It makes sense to me to let everyone customize Strapi and extend the interface to fit your needs.

I wouldn't implement it by default, but it could be a great plugin to develop. However, we need to develop the internal API to be able to do that, or maybe not. @soupette & @alexandrebodin do you have any thoughts?

**Comment by cyp3rius** [comment] 2020-06-12 13:39
@Aurelsicoko we're operating on existing default APIs and relations to not customize it a lot. Just give possibility to switch to hierarchical view based on exact relation field (selected in view settings). 

The core problem here is that there is no guard over cyclic relations between entities, so it's a bit tricky. Now the proposal is to validate the cycles on the list view and show which entities should be fixed. Ideally the special 'one-direction non-cyclic' relation might be introduced to strapi and it will resolve most of corner cases.

**Comment by ahrherrera** [comment] 2020-06-15 01:25
Upvote for reorder records in a content-type. Hope add this feature soon

**Comment by cyp3rius** [comment] 2020-06-19 12:45
For interested in, extension is currently in review: https://github.com/VirtusLab/strapi-plugin-content-manager-extension-hierarchical/pull/2

You might pull the branch and test it, anyway recommend to do this on fresh strapi instance as we didn't check it yet within a complex project :)

**Comment by dmilioniw** [comment] 2020-09-18 11:07
Can you please check the extension for version 3.1.5???Or help me fix the issue??thank you in advance !!!

**Comment by cyp3rius** [comment] 2020-09-22 18:56
@dmilioniw happy to help, provide please more details in the opened issue on the repo.

**Comment by dmilioniw** [comment] 2020-09-23 06:49
> @dmilioniw happy to help, provide please more details in the opened issue on the repo.
I upgradeted to version 3.1.5 of strapi and the extension doesn't work properly as it concerns the UI .When i fix a new collection type in order to use the extension as you describe i het an error "Something went wrong" and i see this in the console main.c45b4e81.chunk.js:1 TypeError: Cannot read property 'split' of undefined
    at c (6.d3c6a264.chunk.js:1)
    at Za (main.c45b4e81.chunk.js:1)
    at vc (main.c45b4e81.chunk.js:1)
    at sl (main.c45b4e81.chunk.js:1)
    at cl (main.c45b4e81.chunk.js:1)
    at $c (main.c45b4e81.chunk.js:1)
    at main.c45b4e81.chunk.js:1
    at t.unstable_runWithPriority (main.c45b4e81.chunk.js:1)
    at Bo (main.c45b4e81.chunk.js:1)
    at Yo (main.c45b4e81.chunk.js:1)
ec @ main.c45b4e81.chunk.js:1.

Can you please upgrade the strapi to 3.1.5 and get the latest updates???
You will reproduce it as well.

Thank you in advance

**Comment by kanchansrivastava** [comment] 2021-04-27 01:55
> @arichard-info we've got a similar case on RnD now but more from view perspective than collection advanced options. In short:
> 
> 1. Work with collections as-is now
> 2. If collection has a relation field based on which a hierarchy might be created than in **Configure the view** under **View section** there should be a toggle for **Enable hierarchy view** with possibility to choose a field over which it should be the view being created
> 3. Focus on presentation layer, than something more like D&D, etc.
> 
> We're working on an extension to Content Manager plugin. Hope to get some PoC soon :)

Couldn't find this option?

**Comment by cawoodm** [comment] 2021-08-12 09:14
Is this now generally available in Strapi? If so, from which version and how to use it?

**Comment by webdelin** [comment] 2021-09-22 19:26
Hi guys. I want to create hierarchy in collection type. but in the end I get data that I can not use. can please help jemad and write an instruction or recommend video where this is shown.

**i want to have this**
<pre>
[
    {
        "id": 18,
        "title": "category",
        "slug": "category",
        "published_at": "2021-09-22T19:17:52.000Z",
        "created_at": "2021-09-22T19:17:48.000Z",
        "updated_at": "2021-09-22T19:17:52.000Z",
        "parent": null,
        "page": null,
        "parentId": null,
        "child": null,
        "category": null,
        "children": [
            {
                "id": 19,
                "title": "subcategory",
                "slug": "subcategory",
                "published_at": "2021-09-22T19:18:19.000Z",
                "created_at": "2021-09-22T19:18:11.000Z",
                "updated_at": "2021-09-22T19:18:19.000Z",
                "parent": 18,
                "page": null,
                "parentId": null,
                "child": null,
                "category": null
            }
        ]
    },
    {
        "id": 20,
        "title": "category1",
        "slug": "category1",
        "published_at": "2021-09-22T19:18:35.000Z",
        "created_at": "2021-09-22T19:18:32.000Z",
        "updated_at": "2021-09-22T19:18:35.000Z",
        "parent": null,
        "page": null,
        "parentId": null,
        "child": null,
        "category": null,
        "children": [
            {
                "id": 21,
                "title": "subcategory1",
                "slug": "subcategory1",
                "published_at": "2021-09-22T19:18:57.000Z",
                "created_at": "2021-09-22T19:18:55.000Z",
                "updated_at": "2021-09-22T19:18:58.000Z",
                "parent": 20,
                "page": null,
                "parentId": null,
                "child": null,
                "category": null
            }
        ]
    }
  ]
</pre>

**not this**

<pre>
[
    {
        "id": 18,
        "title": "category",
        "slug": "category",
        "published_at": "2021-09-22T19:17:52.000Z",
        "created_at": "2021-09-22T19:17:48.000Z",
        "updated_at": "2021-09-22T19:17:52.000Z",
        "parent": null,
        "page": null,
        "parentId": null,
        "child": null,
        "category": null,
        "children": [
            {
                "id": 19,
                "title": "subcategory",
                "slug": "subcategory",
                "published_at": "2021-09-22T19:18:19.000Z",
                "created_at": "2021-09-22T19:18:11.000Z",
                "updated_at": "2021-09-22T19:18:19.000Z",
                "parent": 18,
                "page": null,
                "parentId": null,
                "child": null,
                "category": null
            }
        ]
    },
    {
        "id": 19,
        "title": "subcategory",
        "slug": "subcategory",
        "published_at": "2021-09-22T19:18:19.000Z",
        "created_at": "2021-09-22T19:18:11.000Z",
        "updated_at": "2021-09-22T19:18:19.000Z",
        "parent": {
            "id": 18,
            "title": "category",
            "slug": "category",
            "published_at": "2021-09-22T19:17:52.000Z",
            "created_at": "2021-09-22T19:17:48.000Z",
            "updated_at": "2021-09-22T19:17:52.000Z",
            "parent": null,
            "page": null,
            "parentId": null,
            "child": null,
            "category": null
        },
        "page": null,
        "parentId": null,
        "child": null,
        "category": null,
        "children": []
    },
    {
        "id": 20,
        "title": "category1",
        "slug": "category1",
        "published_at": "2021-09-22T19:18:35.000Z",
        "created_at": "2021-09-22T19:18:32.000Z",
        "updated_at": "2021-09-22T19:18:35.000Z",
        "parent": null,
        "page": null,
        "parentId": null,
        "child": null,
        "category": null,
        "children": [
            {
                "id": 21,
                "title": "subcategory1",
                "slug": "subcategory1",
                "published_at": "2021-09-22T19:18:57.000Z",
                "created_at": "2021-09-22T19:18:55.000Z",
                "updated_at": "2021-09-22T19:18:58.000Z",
                "parent": 20,
                "page": null,
                "parentId": null,
                "child": null,
                "category": null
            }
        ]
    },
    {
        "id": 21,
        "title": "subcategory1",
        "slug": "subcategory1",
        "published_at": "2021-09-22T19:18:57.000Z",
        "created_at": "2021-09-22T19:18:55.000Z",
        "updated_at": "2021-09-22T19:18:58.000Z",
        "parent": {
            "id": 20,
            "title": "category1",
            "slug": "category1",
            "published_at": "2021-09-22T19:18:35.000Z",
            "created_at": "2021-09-22T19:18:32.000Z",
            "updated_at": "2021-09-22T19:18:35.000Z",
            "parent": null,
            "page": null,
            "parentId": null,
            "child": null,
            "category": null
        },
        "page": null,
        "parentId": null,
        "child": null,
        "category": null,
        "children": []
    }
]
</pre>

**Comment by kwissem1** [comment] 2021-09-22 21:56
@webdelin Try this in categories controllers file !

async find(ctx) {
    const categories = await strapi.services.categories.find(
      {
        id: 1,
      },
      ["children", "children.children"]
    );

    return sanitizeEntity(categories, { model: strapi.models.categories });
  }

**Comment by kwissem1** [comment] 2021-09-22 21:58
@webdelin Try this on categories controllers file:

const { sanitizeEntity } = require("strapi-utils");

module.exports = {
  async find(ctx) {
    const categories = await strapi.services.categories.find(
      {
        id: 1,
      },
      ["children", "children.children"]
    );

    return sanitizeEntity(categories, { model: strapi.models.categories });
  },
};

**Comment by webdelin** [comment] 2021-09-23 07:13
it doesn't work. why do I have to pass id? I want to get a clean hierarchical structured json

**Comment by webdelin** [comment] 2021-09-23 07:22
![Firefox_Screenshot_2021-09-23T07-21-39 134Z](https://user-images.githubusercontent.com/21138899/134468656-02ee73e6-9619-4e14-89cb-fd19adc53ca1.png)

**Comment by Rar9** [comment] 2021-12-17 13:54
A video on how to implenpt this hierarchy in strapi would be much appriciated.

**Comment by KrisKnez** [comment] 2022-01-29 17:24
We need this in the latest version of Strapi

**Comment by derrickmehaffy** [comment] 2022-03-24 21:12
We currently do not plan to add native support for this at this time.

Marking as closed as discussed with @Aurelsicoko

**Closed by derrickmehaffy** 2022-03-24 21:12 UTC
Labels: issue: feature request, severity: low

**Comment by kentarohorie** [comment] 2022-04-04 06:10
I want to know reason why you don't plan to support this.
I feel there are many people expect this feature, so I am doubtfut.

**Comment by derrickmehaffy** [comment] 2022-04-04 22:53
> 

It doesn't follow the project vision that we have for how Strapi will function in the near, mid, and long term future. Something like this is more inline with document databases and not with relational ones.

This complex model structure is one we are looking to avoid and instead will be relying on modifying the edit interface to make it easier to manage relational content there.

Alternatively, very purposeful interfaces such as the example gif shown in the original posting would instead likely be better built as a plugin and not native to the core code-base. Much like what was already done in this community plugin: https://market.strapi.io/plugins/strapi-plugin-menus

Excluded from examples like menus it doesn't really fit the content-modelling structure that we are trying to build within Strapi for many use-cases.

---

As something to point out, just because we reject the feature now doesn't mean that won't change in the future or if someone comes up with a detailed [RFC](https://github.com/strapi/rfcs). This rejection is simply stating that at this moment, with the data/team/time/vision we currently have it's not planned and the initial request has been rejected.

If you feel strongly about the feature please feel free to post on our feedback/feature request site: https://feedback.strapi.io, feel free to submit an RFC, or in a case like this feel free to build a plugin that builds in the feature :) 

We just need to take things as they come and consider hundreads (literally) of different feature requests and sadly not all of them will be possible.

I'm going to go ahead and lock this issue but if you would like to reopen a new request on the feedback site, please feel free (you can also link to this issue)
