### ISSUE TITLE
Table column not delete after deleting collection field

### ISSUE THREAD

**Issue by Sakkhor909** [strapi/strapi#11593] opened 2021-11-16 13:29 UTC
### Describe the bug

When I create Strapi with custom configuration (MySQL in my Linux(ubuntu) localhost server) it will ask me for a database. I choose a database same name as my project name. Strapi creates some default tables in that database. when I create a collection Strapi adds a table to that database. When I add a field to that new collection Strapi adds a column according to that. But If I delete that field, it does not delete the column in the database.  Even if delete the collection the table stays there. It creates unnecessary data in the database. it should be deleted right?

- Node.js version:  v14.0.0
- NPM version: 6.14.4
- Strapi version: 3.6.8
- Database: mysql
- Operating system: linux (ubuntu)

**Comment by willnode** [comment] 2021-11-18 15:25
I think it is difficult to actually do that. Even if Strapi could delete/update columns in the database, we only doing it in our localhost development. How would Strapi remember the thing we do locally to a different (eg. production) database server? AFAIK Strapi doesn't have any database migration system.

**Comment by derrickmehaffy** [comment] 2021-11-18 18:51
Duplicate of #1114 will be "fixed" in v4 (it's already the case in the v4-beta)

**Closed by derrickmehaffy** 2021-11-18 18:51 UTC
Labels: status: duplicate
