### ISSUE TITLE
Creating a new entry on the admin panel that has a required relation has incomplete error message and feedback.

### ISSUE THREAD

**Issue by jaakidup** [strapi/strapi#7763] opened 2020-09-07 12:18 UTC
When creating a new entry, one of the fields is a relation to another type. 
This relationship is required, but the admin panel doesn't give adequate feedback to the user.

It currently Toasts "Validation Error".
Other fields that are required are highlighted with red, but not the relationship field.
Can this be added?

**Comment by derrickmehaffy** [comment] 2020-09-07 13:47
Closing as duplicate of https://github.com/strapi/strapi/issues/557

**Closed by derrickmehaffy** 2020-09-07 13:47 UTC
Labels: status: duplicate
