### ISSUE TITLE
[v4] Improve the Rich text preview

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#12164] opened 2022-01-10 18:16 UTC
### Describe the bug

Right now the Rich text looks like this:

| <img width="724" alt="Screenshot 2022-01-10 at 19 09 55" src="https://user-images.githubusercontent.com/1007051/148817268-36e9de30-f869-4f96-98bf-4e9eda327658.png"> | <img width="725" alt="Screenshot 2022-01-10 at 19 10 07" src="https://user-images.githubusercontent.com/1007051/148817316-1c243774-04fb-4476-aa96-5f51c9271294.png"> |
|---------|-------------|

Also if you use the Expand option:

<img width="961" alt="Screenshot 2022-01-10 at 19 10 22" src="https://user-images.githubusercontent.com/1007051/148817503-7d64b088-7663-475c-90d7-fbcfcae1f2f3.png">

As you can see, there is no break lines in the preview.

### Expected behavior

See the break lines in the preview.

### System

- Node.js version: v14
- NPM version: v8
- Strapi version: v4.0.4
- Database: SQLite
- Operating system: macOS

**Comment by soupette** [comment] 2022-01-11 08:20
This issue is also a duplicate of #12121

**Comment by derrickmehaffy** [comment] 2022-01-11 22:17
closing duplicate: https://github.com/strapi/strapi/issues/12121

**Closed by derrickmehaffy** 2022-01-11 22:17 UTC
Labels: issue-type: enhancement, source: core:content-manager
