### ISSUE TITLE
Unexpected notification in Settings -> Overview 

### ISSUE THREAD

**Issue by Striffly** [strapi/strapi#20376] opened 2024-05-27 12:06 UTC
### Required System information

- Node.js version: 20.x
- NPM version: 10.5.2
- Strapi version: 4.24.3
- Database: SQLite
- Operating system: Linux
- Is your project Javascript or Typescript: ?

### Describe the bug

With a fresly created project, a notification is associated with the Settings -> Overview tab, likely indicating that I need to upgrade Strapi. However, I am already on the latest version. Could this be because the beta of 5.0.0 is also present as a Release on GitHub?

### Steps to reproduce the behavior

1. Go to Admin

### Expected behavior

I am not supposed to have any notifications displayed.

### Screenshots

![image](https://github.com/strapi/strapi/assets/13284087/57d0af6d-90f5-42da-8136-09b649fe959f)

**Comment by vincentkipchoge** [comment] 2024-05-29 19:48
Reproduced the following issue across all supported operation systems and can acknowledge the same result is present based on the following condition. Provided is a [refrence](https://github.com/strapi/strapi/blob/develop/packages/core/admin/admin/src/pages/Settings/pages/ApplicationInfo/ApplicationInfoPage.tsx#L165-L186) to the issues potential location.
<img width="742" alt="code snippet" src="https://github.com/strapi/strapi/assets/100973751/0cb1a123-faec-4f68-afc3-25e055dd52cd">

Whenever a release is deployed the [tag ](https://github.com/strapi/strapi/tags) associated with it is used as a reference in comparison with your local machines version. If your local machine contains an outdated version it recommends an update to the most recent repository release tag. Problem is when the betas are released there is also generated tags which clashes with the standard releases and thus recommending updates even when on current release. 
<img width="953" alt="tag snippet" src="https://github.com/strapi/strapi/assets/100973751/220a6e16-8f1f-41e7-b49d-ef6bcf0d3d58">

As of 5/29 there is a [v4.24.4](https://github.com/strapi/strapi/releases/tag/v4.24.4) so after [updating](https://docs.strapi.io/dev-docs/update-version) the issue will go away. The problem doesn't alter the application function and is a minor blemish. 

Possible solution would be to make sure the tag reference isn't a beta version release.

**Comment by derrickmehaffy** [comment] 2024-05-29 20:48
Closing as duplicate of https://github.com/strapi/strapi/issues/19199

**Closed by derrickmehaffy** 2024-05-29 20:48 UTC
Labels: status: duplicate
