### ISSUE TITLE
UID with attached fields does not show up in API or view

### ISSUE THREAD

**Issue by vnguyen42** [strapi/strapi#17633] opened 2023-08-09 20:55 UTC
**Required System information**

    Node.js version: 16.15.1
    NPM version: 8.11.0
    Strapi version: 4.7.0
    Database: PostgreSQL
    Operating system: Windows
    Is your project Javascript or Typescript: Javascript

**Describe the bug**

When creating a new UID field attached to another field (of type text fpr exaù^me), the new field's value is not visible from the list collection (it shows "-" and the field is not working when using the API (whenever it's QS, GraphQL). It's also not working when filtering the field from the back office itself (eq ==), it always returns no result even if the UID is correct. Inside every item in the back office, we can properly see the UID set for all items, but for some reasons it's not working properly.

However, it's working if we re-save one of the item from the back-office.

**Comment by derrickmehaffy** [comment] 2023-08-15 21:21
tested on a fresh v4.12.4 and cannot reproduce

**Comment by derrickmehaffy** [comment] 2023-08-15 21:34
Ah I think I see what is meant here, it's a duplicate of https://github.com/strapi/strapi/issues/12589

**Closed by derrickmehaffy** 2023-08-15 21:34 UTC
Labels: issue: bug, severity: low, status: can not reproduce, source: core:content-manager
