### ISSUE TITLE
Cannot upload images using API

### ISSUE THREAD

**Issue by hansemannn** [strapi/strapi#1919] opened 2018-09-08 19:58 UTC
Node 8.11.4
npm 5.6.0
Strapi 3.0@alpha

**What is the current behavior?**
We are unable to upload images with Strapi. There are some docs on uploading a single file, but for schemes that have multiple file/image fields, there is no working case on how to use it.

**Steps to reproduce the problem**
1. Create a new model "photo"
2. Add twi image-based fields "photo1" and "photo2"
3. Try to do a POST request on it:
```json
{
  "files": "BASE64_ENCODED_VERSION",
  "path": "photo/photo1",
  "refId": "my_user_id",
  "ref": "photo",
  "source": "users-permissions",
  "field": "photo1"
}
```

I also tried sending it as multiform-data, but that also did not succeed.

**What is the expected behavior?**
The images should be handled properly and linked to the identity.

**Suggested solutions**
Provide a working example or hint on how to upload photos.

**Comment by tombunn** [comment] 2018-09-11 19:48
@hansemannn I had a hard time with this the other week and figured it out eventually. The documentation and examples need improving in my opinion as it was not clear at all. This example below might help you and I can confirm it does work for my React project. There are some dispatch actions for redux which you can ignore but I hope this helps.

I'm not sure if you are trying this but you cannot add the images when you add or update your item. You must upload the image first using the /upload endpoint. When the upload is successful the response can be then used for sending a POST or a PUT request to add or update the item with the files.

```export const uploadImages = (refId, files, setSubmitting, history) => (dispatch) => {
  const bodyFormData = new FormData();
  const token = localStorage.getItem('token');

  bodyFormData.append('refId', refId);
  bodyFormData.append('field', 'images');
  bodyFormData.append('ref', 'product');

  // Add each file upload to the form data
  files.forEach((file) => {
    bodyFormData.append('files', file, file.name);
  });

  dispatch(addImagesLoading(true));

  axios({
    async: true,
    crossDomain: true,
    processData: false,
    contentType: false,
    mimeType: 'multipart/form-data',
    method: 'POST',
    url: `${process.env.REACT_APP_ENDPOINT}/upload`,
    headers: {
      Authorization: `Bearer ${token}`,
    },
    data: bodyFormData,
    onUploadProgress: (progressEvent) => {
      dispatch(uploadProgress(getUploadPercentage(progressEvent)));
    },
  })
    .then((response) => {
      if (response.status === 200) {
        dispatch(addImagesSuccess(response.data));

        dispatch(addImagesLoading(false));

        // Check if form is submitting
        if (setSubmitting) {
          setSubmitting(false);
        }

        // Check if redirect needed
        if (history) {
          history.push('/products');
        }
      }
    })
    .catch((error) => {
      dispatch(addImagesFailed(error.response));
      dispatch(addImagesLoading(false));
    });
};
```

Hope this helps but if you need any more help with this let me know

**Comment by lauriejim** [comment] 2018-09-13 09:17
Can you update your issue by given the correct name of the strapi version you use please.

**Comment by lauriejim** [comment] 2018-10-10 10:28
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.

**Comment by hansemannn** [comment] 2018-10-10 18:09
It happens with all versions of Strapi (including latest alpha 14.3)

**Comment by lauriejim** [comment] 2018-10-17 12:12
@hansemannn Did you follow the documentation ?

**Comment by lauriejim** [comment] 2018-11-11 22:06
I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.

**Closed by lauriejim** 2018-11-11 22:06 UTC
Labels: type: help wanted 🤷‍♂️

**Comment by cpres** [comment] 2019-08-16 23:06
I couldn't find a way to successfully send with axios, but with request it ended up being fairly simple to upload the image to the api in node:

```var formData = {
                files: [fs.createReadStream(image_path)],
                path: 'upload_folder',
                refId: viewId
            }
request.post({url:`${strapiUrl}/upload`, formData: formData}, ()=>{});```

**Comment by mohanen** [comment] 2019-08-31 17:58
When I upload files this is what I get, 

> error Error: ER_BAD_FIELD_ERROR: Unknown column 'fields' in 'field list'

Tried with postman, axios, XMLHttpRequest

Stuck with this for almost a day, Help me out

```
  const formElement = document.querySelector('#myform form');
  const bodyFormData = new FormData();
  const token = localStorage.getItem('token');

  var fields = ['name', 'info', 'price']
  var files = ['thumbnail', 'img1', 'img2', 'img3']

  console.log(formElement);

  fields.forEach(function(element) {
    console.log(element, " - ", formElement.querySelector(`[name=${element}]`).value);
    bodyFormData.append(element, formElement.querySelector(`[name=${element}]`).value );
  });

  // Add each file upload to the form data
  files.forEach((file) => {
    bodyFormData.append(file, formElement.querySelector(`[name=${file}]`).files[0], formElement.querySelector(`input[name=${file}]`).files[0].name);
    console.log(file, " - ", formElement.querySelector(`[name=${file}]`).files[0].name);

  });

  axios({
    async: true,
    crossDomain: true,
    processData: false,
    contentType: false,
    mimeType: 'multipart/form-data',
    method: 'POST',
    url: url,
    headers: {
      Authorization: `Bearer ${token}`,
    },
    data: bodyFormData,
    onUploadProgress: (progressEvent) => {
    },
  })
    .then((response) => {
      // Handle success.
      console.log('Well done!', response);
    })
    .catch((error) => {
      console.log('An error occurred:', error);
    });
```

my ctx body printed with the help of a policy

```
{ fields: { name: 'axios', info: 'Initial Test', price: '500' },
  files:
   { thumbnail:
      File {
        domain: null,
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        size: 3639,
        path: '/tmp/upload_fa81289651fee40c74bbb8f32a529425',
        name: 'index.jpeg',
        type: 'image/jpeg',
        hash: null,
        lastModifiedDate: 2019-08-31T17:53:54.677Z,
        _writeStream: [WriteStream] },
     img1:
      File {
        domain: null,
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        size: 5695,
        path: '/tmp/upload_ddf8a4d422f88fd8116e06ea4d9498d9',
        name: 'index2.jpeg',
        type: 'image/jpeg',
        hash: null,
        lastModifiedDate: 2019-08-31T17:53:54.677Z,
        _writeStream: [WriteStream] },
     img2:
      File {
        domain: null,
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        size: 5392,
        path: '/tmp/upload_4cf930df8d7b0ea7e3abc6b17e517666',
        name: 'index3.jpeg',
        type: 'image/jpeg',
        hash: null,
        lastModifiedDate: 2019-08-31T17:53:54.729Z,
        _writeStream: [WriteStream] },
     img3:
      File {
        domain: null,
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        size: 4932,
        path: '/tmp/upload_ec5c1b88f1d42327ec3a770a2ffe1eff',
        name: 'index4.jpeg',
        type: 'image/jpeg',
        hash: null,
        lastModifiedDate: 2019-08-31T17:53:54.729Z,
        _writeStream: [WriteStream] } },
  owner: undefined }
```

My package.json

```
{
  "name": "Test",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "lint": "eslint ."
  },
  "devDependencies": {
    "babel-eslint": "^10.0.0",
    "eslint": "^6.0.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.18.0",
    "eslint-plugin-react": "^7.14.0"
  },
  "dependencies": {
    "knex": "^0.19.3",
    "lodash": "^4.17.5",
    "mysql": "latest",
    "strapi": "3.0.0-beta.15",
    "strapi-admin": "3.0.0-beta.15",
    "strapi-hook-bookshelf": "3.0.0-beta.15",
    "strapi-hook-knex": "3.0.0-beta.15",
    "strapi-plugin-content-manager": "3.0.0-beta.15",
    "strapi-plugin-content-type-builder": "3.0.0-beta.15",
    "strapi-plugin-email": "3.0.0-beta.15",
    "strapi-plugin-settings-manager": "3.0.0-beta.15",
    "strapi-plugin-upload": "3.0.0-beta.15",
    "strapi-plugin-users-permissions": "3.0.0-beta.15",
    "strapi-provider-upload-aws-s3": "^3.0.0-beta.15",
    "strapi-utils": "3.0.0-beta.15"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "d6d7b508-14b1-4c11-9c77-1a82f6ce5613"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by fortydegrees** [comment] 2019-12-12 11:47
Any update on this? I had it working on my strapi install before (that used SQLite)

Now using MySQL and I get: 
```
error Error: ER_BAD_FIELD_ERROR: Unknown column 'fields' in 'field list'
    at Query.Sequence._packetToError (/Users/david/coding/sw/strapi-server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
```

**Comment by fortydegrees** [comment] 2019-12-12 12:12
Okay, I have a workaround for this: POST upload via the /content-manager/explorer/ route and it will go through okay. You have to change files.imgLogo to just imgLogo and provide the field names manually instead of via a 'data' JSON but it works.

That said, I would definitely consider this a bug with strapi and MySQL, as like I said I had it working fine before with SQLite, but moving to MySQL broke it with the aforementioned error.

**Comment by fortydegrees** [comment] 2019-12-12 13:48
I've also realised that in doing it this way, constraints like uniqueness aren't adhered to

**Comment by impactcolor** [comment] 2021-01-22 23:16
@tombunn in your example where do you get refId from?
` bodyFormData.append('refId', refId);`
You have it is a variable so wondering where it's coming from
