### ISSUE TITLE
Add New Field display error. Component field has 100% height and overlaying other fields. (Safari)

### ISSUE THREAD

**Issue by cjboco** [strapi/strapi#17642] opened 2023-08-10 22:54 UTC
### Required System information
- Node.js version: 
- 18.16.0
- NPM version:
- 9.8.0
- Strapi version:
- 4.12.4
- Database:
- Operating system:
- macOS
- Is your project Javascript or Typescript:
- JavaScript
- Browser
- Safari, it works fine in Chrome and FireFox
- OS
- macOS 13.5

### Describe the bug
When I click on "Add another field to this component", the field pop-up displays, but the "Component" field has a height of 100% and is floating over "Boolean", and "Relation".

This appears to be a Safari and/or CSS bug.

### Steps to reproduce the behavior

1. Go to 'Content Type Builder' (using Safari)
2. Click on 'Add another field to this component'
3. Scroll down to 'Component'
4. See display error

### Expected behavior
The component field should not be floating over the other fields.

This has been happening with Strapi for a few updates, but it didn't use to. (Maybe since Strapi 4)

### Screenshots
<img width="1589" alt="Screenshot 2023-08-10 at 3 41 18 PM" src="https://github.com/strapi/strapi/assets/351122/41142408-0e93-4834-9cf2-1c0383f42a14">

**Comment by gu-stav** [comment] 2023-08-11 10:14
Closing as duplicate of https://github.com/strapi/strapi/issues/17591

**Closed by gu-stav** 2023-08-11 10:14 UTC
