### ISSUE TITLE
Content Types are missing metadata 

### ISSUE THREAD

**Issue by cupofnestor** [strapi/strapi#2304] opened 2018-11-13 21:05 UTC
**Informations**
- **Node.js version**: 
v10.1.0
- **npm version**: 
- **Strapi version**: 
3.0.0-alpha.14.5
- **Database**: 
mongo
- **Operating system**: 
OSX/Linux

**What is the current behavior?**
Content Types are missing metadata (labels, placeholders, ...)   when checked out from a repository.

**Steps to reproduce the problem**

1. Joe creates default strapi project using a local `mongo` instance.
2. Joe adds models and fields in Content Type Builder or using strapi cli
3. Joe commits changes to external repository.
4. Jane checks out Joe's strapi project on her machine with a local `mongo` instance
5. Jane runs Joe's project with `strapi start` in order to populate a dev or production database.

**What is the expected behavior?**
Jane sees what Joe sees including all metadata (labels, placeholders, ...) 

**Suggested solutions**

- Option 1 (not likely) 

Don't store metadata in the database

- Option 2
Additional dump/restore workflow to flat-file that supports selective migration of users and metadata, respecting the agnostic nature of strapi's database support.

**Comment by derrickmehaffy** [comment] 2018-11-14 06:19
This isn't really a bug... its more of a feature request and has been suggested. See: https://portal.productboard.com/strapi/c/23-import-export-data

The "metadata" your talking about is stored in the database. I do manual exports in my project as "seed files" for other developers, however I use MySQL.

@lauriejim I recommend closing this issue as there is no bug to reproduce and is a duplicate.

**Comment by cupofnestor** [comment] 2018-11-14 14:29
> more of a feature request and has been suggested
Can it be labelled as such? I don't think that this is a duplicate as we don't actually _want_ to export the data, just the metadata.  I can easily import/export **data** using mongodump and have developed a solution that only exports the collections (core_store, users-permissions_permission, users-permissions_role, users-permissions_use) but it is platform-dependant.

**Comment by cupofnestor** [comment] 2018-11-14 14:31
I should add that I am happy to work on it, but might need to be pointed in the right direction as I am not up-to-speed on the ecosystem/src.

**Comment by derrickmehaffy** [comment] 2018-11-14 15:02
@cupofnestor your talking about basically migrating strapi only data between environments which @Aurelsicoko has covered on the product board. (There is a closed issue somewhere on here about it)

**Comment by derrickmehaffy** [comment] 2018-11-14 15:03
Given you could also use this to "migrate" between developers as well. I understand your point but I do believe this is a duplicate

**Comment by derrickmehaffy** [comment] 2018-11-14 15:04
Here we go:

https://github.com/strapi/strapi/issues/672

https://portal.productboard.com/strapi/c/12-migrate-across-environments

**Comment by lauriejim** [comment] 2018-11-14 15:12
Thank you for this feedback. Send your feedback in productboard please.

**Closed by lauriejim** 2018-11-14 15:12 UTC
Labels: status: duplicate

**Comment by Aurelsicoko** [comment] 2018-11-15 14:40
@cupofnestor We will provide an easy way to switch between environment. We know that currently, it's a real pain. However, we will continue to store the metadata in the database because these metadata can be changed on the fly without restarting the server. This is the only reason why we're storing them in the database instead of local JSON files. It avoids server restart.
