### ISSUE TITLE
"Invalid input syntax for integer" when using a custom Relation on a built-in colleciton type

### ISSUE THREAD

**Issue by odnamrataizem** [strapi/strapi#6259] opened 2020-05-19 02:42 UTC
**Describe the bug**
There seems to be a bug on some Strapi auth routines when there are custom Relation fields on the (built-in) User collection type.

**Steps to reproduce the behavior**

1. Go to "Content-Types Builder";
2. Click on "User";
3. Add a one-to-one Relation field to any other collection type, let's say XYZ;
4. Create a User and a XYZ that the User relates to;
4.1. You may have to set up your emailing to something other than Sendmail before the next steps;
5. Hit the `/auth/forgot-password` endpoint with that User's `email`;
6. The console spits out `error: invalid input syntax for integer` followed by the XYZ data, JSON-formatted.

**Expected behavior**
It should have returned `200 OK`. I did receive an e-mail with the reset password token (which doesn't work), though.

**System**

- Node.js version: v12.16.3
- NPM version: v6.14.4
- Strapi version: v3.0.0-rc.1
- Database: PostgreSQL 10.11
- Operating system: macOS Catalina

**Additional context**
I think this _might_ relate to #3682, even though I didn't name anything as `value` when testing this.

Oh, and thanks for such an awesome product!

**Comment by lauriejim** [comment] 2020-05-23 09:15
Hello this issue issue is a duplicate of this one - https://github.com/strapi/strapi/issues/5249
The error is different due to the database MongoDB or PG.
But the issue is the same.
Thank you for reporting this issue, and thank you for your support.

**Closed by lauriejim** 2020-05-23 09:15 UTC
