### ISSUE TITLE
Strapi gets stuck on loading screen after creating a Collection Type. Need to reload for the project to run.

### ISSUE THREAD

**Issue by adamtzur1996** [strapi/strapi#20149] opened 2024-04-18 11:36 UTC
### Required System information

- Node.js version: v20.6.1
- NPM version: 9.8.1
- Strapi version: 5.0.0-beta.3
- Database: sqlite
- Operating system: Ubuntu 22.04.4 LTS
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

Created a very basic collection type called "Products" with 3 texts (1 long description and 2 short), one media single image, a "price" simple integer number and a custom field containing: 1 boolean, two short description texts.

### Steps to reproduce the behavior
Create a collection type "Product".

Add the following fields: 
- name -> text (short)
- sku -> text (short)
- description -> text (long)
- Image -> Media (Single media)
- price -> Number (integer {ex:10})
- Repeatable Component:
- customFields -> Component (repeatable)
-  name -> text (short)
-  required -> Boolean
-  options -> Text (short)

Click "save" and the project doesn't reload.

### Expected behavior

Once the above steps are implemented, the moment you click save it should get stuck on restarting. After which it will state that the project is taking longer than expected to reload.
Right click on the screen -> click on "Inspect" -> Go to "Console". You will find it.

### Screenshots

![image](https://github.com/strapi/strapi/assets/48216791/36d042c3-1f2a-4762-a6d5-5335fe294018)

### Code snippets

For the entire code error follow the below link:
https://drive.google.com/file/d/17akpjhH4Q_yLy5Ica0CJwIWokFdzcu3B/view?usp=sharing

**Comment by derrickmehaffy** [comment] 2024-04-24 17:25
Can't reproduce on beta.5

**Comment by SalahAdDin** [comment] 2024-04-26 07:13
@derrickmehaffy I don't know if my issue is related to this one, but after saving any entity, Strapi admin does not refresh itself, and we have to manually refresh the browser to get the admin working back:
![StrapiDoesNotRefreshAfterSavingEntities](https://github.com/strapi/strapi/assets/5034215/502cfadf-9ee3-48d3-aa99-d66059699ecf)

**Comment by joshuaellis** [comment] 2024-04-26 07:25
> @derrickmehaffy I don't know if my issue is related to this one, but after saving any entity, Strapi admin does not refresh itself, and we have to manually refresh the browser to get the admin working back: ![StrapiDoesNotRefreshAfterSavingEntities](https://private-user-images.githubusercontent.com/5034215/325881532-502cfadf-9ee3-48d3-aa99-d66059699ecf.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTY1ODIsIm5iZiI6MTcxNDExNjI4MiwicGF0aCI6Ii81MDM0MjE1LzMyNTg4MTUzMi01MDJjZmFkZi05ZWUzLTQ4ZDMtYWE5OS1kNjYwNTk2OTllY2YuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMDcyNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY1ZTg2NTE2NmJlZjJjNjc3NzhkZDBlZGZiOTQ5ZWMwNWM2YjIyN2EyYWJiM2NmM2Y3ZDU4NDNjZDE5ZDc4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e7p0C7hOXht-N-4_MXdfgjgyxikCe5CC-MiRplZ5_U4) [ ![StrapiDoesNotRefreshAfterSavingEntities](https://private-user-images.githubusercontent.com/5034215/325881532-502cfadf-9ee3-48d3-aa99-d66059699ecf.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTY1ODIsIm5iZiI6MTcxNDExNjI4MiwicGF0aCI6Ii81MDM0MjE1LzMyNTg4MTUzMi01MDJjZmFkZi05ZWUzLTQ4ZDMtYWE5OS1kNjYwNTk2OTllY2YuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMDcyNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY1ZTg2NTE2NmJlZjJjNjc3NzhkZDBlZGZiOTQ5ZWMwNWM2YjIyN2EyYWJiM2NmM2Y3ZDU4NDNjZDE5ZDc4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e7p0C7hOXht-N-4_MXdfgjgyxikCe5CC-MiRplZ5_U4) ](https://private-user-images.githubusercontent.com/5034215/325881532-502cfadf-9ee3-48d3-aa99-d66059699ecf.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTY1ODIsIm5iZiI6MTcxNDExNjI4MiwicGF0aCI6Ii81MDM0MjE1LzMyNTg4MTUzMi01MDJjZmFkZi05ZWUzLTQ4ZDMtYWE5OS1kNjYwNTk2OTllY2YuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMDcyNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY1ZTg2NTE2NmJlZjJjNjc3NzhkZDBlZGZiOTQ5ZWMwNWM2YjIyN2EyYWJiM2NmM2Y3ZDU4NDNjZDE5ZDc4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e7p0C7hOXht-N-4_MXdfgjgyxikCe5CC-MiRplZ5_U4) [ ](https://private-user-images.githubusercontent.com/5034215/325881532-502cfadf-9ee3-48d3-aa99-d66059699ecf.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTY1ODIsIm5iZiI6MTcxNDExNjI4MiwicGF0aCI6Ii81MDM0MjE1LzMyNTg4MTUzMi01MDJjZmFkZi05ZWUzLTQ4ZDMtYWE5OS1kNjYwNTk2OTllY2YuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMDcyNDQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWY1ZTg2NTE2NmJlZjJjNjc3NzhkZDBlZGZiOTQ5ZWMwNWM2YjIyN2EyYWJiM2NmM2Y3ZDU4NDNjZDE5ZDc4NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e7p0C7hOXht-N-4_MXdfgjgyxikCe5CC-MiRplZ5_U4)
> 
> It happens on the latest beta version.

please open a new issue.

**Comment by derrickmehaffy** [comment] 2024-04-29 20:40
Closing this one since we can't reproduce and the other problem has an issue

**Closed by derrickmehaffy** 2024-04-29 20:40 UTC
Labels: issue: bug, severity: high, source: core:content-type-builder, status: pending reproduction, version: 5
