### ISSUE TITLE
Crash on large file upload to S3 (Linode)

### ISSUE THREAD

**Issue by derek-maurer** [strapi/strapi#19126] opened 2023-12-28 19:24 UTC
### Required System information

- Node.js version: 18.17
- NPM version: 
- Strapi version: 14.16.2
- Database: MySQL
- Operating system: Docker - Node 18 Alpine
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

When uploading larger file (usually 1.5gb or larger) the upload the the Strapi server itself will work, but the entire server will crash or timeout when attempting to then upload to S3 (Linode object storage in my case). Running my docker image locally on my machine it works fine, but when running in on my actual server it throws either a 504 or a 502. The server completely shuts down and the strapi instance restarts. There are no logs in my docker logs beyond just showing the request to the /upload endpoint. I've tried doing several things including increasing the sizeLimit in my middlewares.js file, increasing the size limit in my plugins.js config for my S3 plugin, increasing the request timeout to 60minutes in my server.js. None of this works and unfortunately I'm at a loss. Any ideas on what could be causing this? My guess is it could be related to the fact that I'm uploading to linode and not S3 itself because I also ran into another issue with configuring it to work with linode. 

### Steps to reproduce the behavior

1. Setup the S3 file upload plugin
2. Connect to Linode (or possibly AWS)
3. Try uploading a file 1.5GB - 4GB

### Expected behavior

File should upload and appears in the media library 

### Screenshots

<img width="1735" alt="Screenshot 2023-12-28 at 1 11 45 PM" src="https://github.com/strapi/strapi/assets/792292/9fab965e-f879-417a-a3d6-ae1bbc65d348">
<img width="1373" alt="Screenshot 2023-12-28 at 12 01 35 PM" src="https://github.com/strapi/strapi/assets/792292/1a3b3ee1-1a11-4fd9-ba87-6be7f3af9085">
<img width="695" alt="Screenshot 2023-12-28 at 1 23 09 PM" src="https://github.com/strapi/strapi/assets/792292/e4c73159-b5e3-44b5-8d02-cba976dd8a73">
<img width="686" alt="Screenshot 2023-12-28 at 1 22 25 PM" src="https://github.com/strapi/strapi/assets/792292/f7329760-3bdc-455b-b925-6666081af06c">
<img width="540" alt="Screenshot 2023-12-28 at 1 22 31 PM" src="https://github.com/strapi/strapi/assets/792292/7c4148f0-3fc6-4d42-9e27-172249c08ea4">
<img width="891" alt="Screenshot 2023-12-28 at 1 22 52 PM" src="https://github.com/strapi/strapi/assets/792292/83419d1e-3224-45df-8a60-bf15420a184e">
<img width="450" alt="Screenshot 2023-12-28 at 1 22 40 PM" src="https://github.com/strapi/strapi/assets/792292/72a7e8bf-d4f7-4f68-994f-3bbee9a39b45">

**Comment by derek-maurer** [comment] 2023-12-28 23:43
Looks like here are some other people with the exact same issue: https://forum.strapi.io/t/error-uploading-to-cloudinary-request-timeout/19947

**Comment by pierpo** [comment] 2024-01-11 16:44
Same issue when using Strapi Cloud with the default media provider. A file of size 350MB is enough to make the whole server crash and restart the Strapi instance.

With the default provider, I don't even get the image to be uploaded though. It is totally cancelled.

**Comment by derek-maurer** [comment] 2024-01-17 21:53
FYI, I fixed the issue by upgrading my linode VPS. I was running a pretty small shared box. I changed it to a dedicated box and that fixed it. My guess is that Linode itself was killing the requests to the server because of how long it was taking to execute the request.

**Comment by Eventyret** [comment] 2024-02-23 10:23
Duplicate of #14417

**Closed by Eventyret** 2024-02-23 10:23 UTC
Labels: status: pending reproduction
