### ISSUE TITLE
Cannot Get the specific entry

### ISSUE THREAD

**Issue by Mateussmo** [strapi/strapi#3302] opened 2019-05-20 18:04 UTC
**Informations**
- **Node.js version**:  10.15.3
- **NPM version**:  6.4.1
- **Strapi version**:  3.0.0-alpha.26.2
- **Database**:  MongoDB
- **Operating system**: 
- **(Optional) Link to your Project**: 

**What is the current behavior?**
I just can get the results using findone when I pass the ID, but I can't get the results if I pass another field.
On my MongoDb, I have something like this: { "id":"0e0e30e03k", "email": "somethig@asd.com"}. 
So in URL I acess: "http://localhost:1337/some/0e0e30e03k"  and I get the results, but if I pass "http://localhost:1337/some/somethig@asd.com".
How can I resolve this ?

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by derrickmehaffy** [comment] 2019-05-20 18:13
@Mateussmo Use filters: https://strapi.io/documentation/3.x.x/guides/filters.html

`http://localhost:1337/some?email=something@asd.com`

Marking as closed as not a bug

**Closed by derrickmehaffy** 2019-05-20 18:13 UTC

**Comment by Mateussmo** [comment] 2019-05-20 18:19
Thank you so Much @derrickmehaffy !

**Comment by derrickmehaffy** [comment] 2019-05-20 18:19
np

**Comment by Mateussmo** [comment] 2019-05-20 18:26
@derrickmehaffy Can I use count with this filter?

**Comment by derrickmehaffy** [comment] 2019-05-20 18:30
Yes the only filter that count doesn't work with is `_q`

`http://localhost:1337/some/count?email=something@asd.com`

**Comment by Mateussmo** [comment] 2019-05-20 18:32
It Works!! Thank You again.
