### ISSUE TITLE
Forgot password ONLY works for admin user

### ISSUE THREAD

**Issue by justinriggio** [strapi/strapi#2977] opened 2019-03-14 16:45 UTC
**Informations**
- **Node.js version**: v10.8.0
- **NPM version**: 6.5.0
- **Strapi version**: v19 but this bug was tested on v25
- **Database**: mongoDB
- **Operating system**: macOS, ubuntu 18.04
- **(Optional) Link to your Project**: 

**What is the current behavior?**
Forgotten password does not work for any user but the admin user.

**Steps to reproduce the problem**
Use the guide here:
https://strapi.io/documentation/3.x.x/guides/authentication.html#forgotten-password
OR
use the login for the admin panel and click forgot password
OR use Strapi SDK
https://github.com/strapi/strapi-sdk-javascript

**What is the expected behavior?**
Forgotten password should work for any registered user.

**Suggested solutions**

**Comment by derrickmehaffy** [comment] 2019-03-14 16:46
Can confirm this on Strapi v25:

![Selection_630](https://user-images.githubusercontent.com/8593673/54375320-0f4afc80-463e-11e9-994a-fd207862fcb1.png)

![Selection_629](https://user-images.githubusercontent.com/8593673/54375327-11ad5680-463e-11e9-8e4d-c479453e71cb.png)

**Comment by derrickmehaffy** [comment] 2019-03-14 16:48
This appears to work with an admin User, but not with a normal user

**Comment by bykclk** [comment] 2019-03-30 10:01
I think problem is with the email sender. In this line: https://github.com/strapi/strapi/blob/master/packages/strapi-provider-email-sendmail/lib/index.js#L47
```
            if (err) {
              reject([{ messages: [{ id: 'Auth.form.error.email.invalid' }] }]);
            } else {
              resolve();
            }
```
Here, api returns `Auth.form.error.email.invalid` on any error but the real error on the console is this:
```
send gmail.com>
send gmail.com>.
recv gmail.com>550-5.7.1 This message does not have authentication information or fails to pass
recv gmail.com>550-5.7.1 authentication checks. To best protect our users from spam, the
recv gmail.com>550-5.7.1 message has been blocked. Please visit
recv gmail.com>550-5.7.1  https://support.google.com/mail/answer/81126#authentication for more
recv gmail.com>550 5.7.1 information. c12si4165188pgk.202 - gsmtp
SMTP responds error code 550
Error: SMTP code:550 msg:550-5.7.1 This message does not have authentication information or fails to pass
550-5.7.1 authentication checks. To best protect our users from spam, the
550-5.7.1 message has been blocked. Please visit
550-5.7.1  https://support.google.com/mail/answer/81126#authentication for more
550 5.7.1 information. c12si4165188pgk.202 - gsmtp

    at response (/home/omer/strapi/packages/strapi-provider-email-sendmail/node_modules/sendmail/sendmail.js:217:24)
    at onLine (/home/omer/strapi/packages/strapi-provider-email-sendmail/node_modules/sendmail/sendmail.js:233:11)
    at Socket.<anonymous> (/home/omer/strapi/packages/strapi-provider-email-sendmail/node_modules/sendmail/sendmail.js:141:11)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:261:13)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by lauriejim** [comment] 2019-04-05 09:03
Hello, I just install Strapi and use the forgot password process with a non admin user and it works.
I think your issue is related to this article http://help.strapi.io/customize/email/error-when-send-email

**Comment by lauriejim** [comment] 2019-04-23 08:40
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.

**Closed by lauriejim** 2019-04-23 08:40 UTC
Labels: priority: medium, status: can't reproduce, type: bug 🐛

**Comment by nezzard** [comment] 2019-08-06 16:33
I installed sendgrid provider, email recieved, but when i try to change password, i get an eror 'Wrong code'

**Comment by kalanyuz** [comment] 2019-09-29 11:29
I'm having the same problem too.

**Comment by elirodrigues** [comment] 2020-05-04 00:41
Find out all the details to reproduce in this discussion topic : 
https://github.com/strapi/strapi/discussions/6034

**Comment by coderdix** [comment] 2020-06-14 10:05
having same issue with sendgrid - email confirmation works but forgotten password giving me "Auth.form.error.email.invalid"

**Comment by Thomas13702** [comment] 2021-06-16 16:43
I am having the same issue, forgot password email only gets sent to Admin email and not just users
