### ISSUE TITLE
TypeError: ht?.toDate is not a function when adding a datetime field in Strapi admin

### ISSUE THREAD

**Issue by schuif** [strapi/strapi#18353] opened 2023-10-08 15:30 UTC
**Description**

I encountered an issue when attempting to add a datetime field to my new content type in the Strapi admin. The error message I received is as follows:

```
_**TypeError: ht?.toDate is not a function**_'
```

**Environment**

- Strapi version: v4.14.3
- Database: SQLite
- Node.js version: v18.18.0
- Operating system: windows 11
- Browser: Edge

**Steps to Reproduce**

1. Log in to the Strapi dashboard.
2. Navigate to Content Types Builder
3. Create a new cellection type
4. Attempt to add a datetime field and navigate to advanced
5. Observe the error message.

**Expected Behavior**

I expected to be able to add a datetime field without encountering any errors.

**Actual Behavior**

I received the "TypeError: ht?.toDate is not a function" error and white screen when trying to add a datetime field.

**Screenshots**

![Capture d'écran 2023-10-08 151249](https://github.com/strapi/strapi/assets/35401312/4e945135-e938-486d-b0b3-a25f1767af7c)

**Comment by gaurab-khanal** [comment] 2023-10-08 16:15
Can I work on this issue?

**Comment by Boegie19** [comment] 2023-10-08 19:05
@gaurab-khanal Please read the pinned issue! https://github.com/strapi/strapi/issues/18298

**Comment by gaurab-khanal** [comment] 2023-10-10 10:50
@Boegie19 
```
yarn install // command execution got stucked at 
```
![image](https://github.com/strapi/strapi/assets/40165867/95e4750f-3743-4169-9ca0-62f979fed83d)

**Comment by gaurab-khanal** [comment] 2023-10-10 10:51
@Boegie19 is there any other guide on how to setup this project for development?

**Comment by Boegie19** [comment] 2023-10-10 10:52
follow the staps in https://github.com/strapi/strapi/blob/main/CONTRIBUTING.md

**Comment by gaurab-khanal** [comment] 2023-10-10 11:03
> follow the staps in https://github.com/strapi/strapi/blob/main/CONTRIBUTING.md

```
yarn install
```
is taking too much time. Is this normal?

**Comment by Melak12** [comment] 2023-10-10 13:25
The same issue happening to me as well. The error occurs when tapping the "Advanced Settings" of the Date Field.

**Comment by akd-io** [comment] 2023-10-10 16:16
@Melak12 Same for me

**Comment by Boegie19** [comment] 2023-10-18 16:36
Duplicate of https://github.com/strapi/strapi/issues/18123

**Closed** 2023-10-18 16:36 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-type-builder

**Comment by faceless49** [comment] 2023-10-26 17:19
strapi last version Same for me
