### ISSUE TITLE
Draft entries are still available if they are related to other Content-type's

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#9558] opened 2021-03-01 17:04 UTC
### Describe the bug
Unpublished/Draft entries are still available if they are related to other Content-type's Published records

### Steps to reproduce the behavior

Implement Draft system, use this Strapi Doc: https://strapi.io/documentation/developer-docs/latest/guides/draft.html#introduction 

Create a Draft entry on any content-type & check it's own API: This API doesn't returns Unpublished/Draft entries (This is working good)

But now relate this Draft entry to a Published record of any other content-type & check other content-type's API now: One content-type's Draft entries are still visible on other content-type's API (This is the issue).

**Steps to reproduce:**
1. Implement Draft System, following this doc: https://strapi.io/documentation/developer-docs/latest/guides/draft.html#introduction 
2. Create a Cars collection, create a Draft entry & Published entry
3. Create a Trucks collection, create a draft entry & Published entry
4. relate both these collections as many to many
5. Now relate Draft entry on Cars collection to Published entry on Trucks
6. Now check Trucks API
7. Bug: Trucks API returns Cars Draft

### Expected behavior

**Drafts entries should not be available even if they are related to other content-type's/API's** 

### System

- Node.js version: v14.8.0
- NPM version: 6.14.7
- Strapi version: v3.0.6
- Database: Mongo
- Operating system: MAC

**Comment by vinod77** [comment] 2021-03-02 18:20
Hi @sam-pires Thank you for looking into it. I have updated the issue.

**Below are the steps to reproduce this issue on Strapi v`3.0.6`**

1. Implement Draft System, following this doc: https://strapi.io/documentation/developer-docs/latest/guides/draft.html#introduction 
2. Create a Cars collection, create a Draft entry & Published entry
3. Create a Trucks collection, create a draft entry & Published entry
4. relate both these collections as many to many
5. Now relate Draft entry on Cars collection to Published entry on Trucks
6. Now check Trucks API
7. Bug: Trucks API returns Cars Draft

Please lmk if you have any questions to reproduce it. 
Thanks!

**Comment by JabStrapi** [comment] 2021-03-04 13:29
Hi @vinod77, thanks for your report. I tried to reproduce this issue following the steps you mentioned but I could not. 
The Strapi version you are using (3.0.6) is older than the release of the Draft system feature, it could explain the issue (as it is mentioned in the doc you quoted), could you try with a more recent version?

**Comment by derrickmehaffy** [comment] 2021-03-05 21:13
@vinod77 I also was not able to reproduce this on the latest release. Please note you are using quite an old version and the current version is v3.5.2.

In order to fix the bug (or prove it exists) we need to be able to reproduce it on the latest release.

**Comment by derrickmehaffy** [comment] 2021-04-15 18:18
closing as no new information

**Closed by derrickmehaffy** 2021-04-15 18:18 UTC
Labels: status: can't reproduce
