### ISSUE TITLE
Database Migration/Change Versioning

### ISSUE THREAD

**Issue by benramsay** [strapi/strapi#18660] opened 2023-11-03 11:16 UTC
Hello Strapi Team,

I've recently started using Strapi and I'm **having a great time with it**, and I've managed to convince several developpers to give it a try as well. However, as I'm working on my first **production integration** and made slight **changes to the database schema**, I've encountered a challenge related to **database migrations**. 

I noticed that Strapi uses Knex under the hood, and I expected that Knex migration files would be generated automatically (for example when adding new collections through the admin dashboard,...).

It seems like this process isn't as automated as I thought. I want to avoid reinventing the wheel, so I wanted to reach out to clarify if I might have missed a detail in the setup or if there's a recommended **strategy for handling database migrations** and **versioning** within the **Strapi development cycle**.

Sorry if I reached out here concerning this need (or question). But I couldn't find any information on this topic anywhere, and I consider it a crucial aspect of our development cycle. Also nobody is answering on your forum or on Stackoverflow... :(

I appreciate your assistance and any guidance you can provide on this topic. I'm excited to continue using Strapi and want to ensure that I'm following best practices for database schema migration/changes in my projects.

Thank you for your time and support.

**Comment by derrickmehaffy** [comment] 2023-11-03 13:49
Duplicate of https://feedback.strapi.io/developer-experience/p/gracefully-handle-renaming-of-content-types-and-fields-in-the-ctb

We don't handle certain changes automatically and you'll need to write some manual migrations for now: https://docs.strapi.io/dev-docs/database-migrations

**Closed** 2023-11-03 13:49 UTC
Labels: flag: question
