### ISSUE TITLE
v4 (4.23.0): "strapi export" command doesn't accept any arguments

### ISSUE THREAD

**Issue by ztxone** [strapi/strapi#20130] opened 2024-04-16 16:38 UTC
### Required System information

- Node.js version: 20.9.0
- NPM version: 10.5.2
- Strapi version: 4.23.0
- Database: mysql 8.0
- Operating system: CentOs 8 Stream (VPS) | Sonoma 14.4.1 (Local)
- Is your project Javascript or Typescript: ts

### Describe the bug

Can't run strapi export with arguments. Followed by "error: too many arguments for 'export'. Expected 0 arguments but got 2."

### Steps to reproduce the behavior

1. Install fresh strapi latest
2. Try to run "npm run strapi export -f export_name"
3. See screenshot
 
![Screenshot 2024-04-16 at 18 20 57](https://github.com/strapi/strapi/assets/39146381/4610450f-8622-4608-896a-b8bf78d79229)

### Expected behavior

Up to documentation:

Examples of strapi export:
___
export your data with the default options and the filename myData, which results in a file named myData.tar.gz.enc.
 $ strapi export -f myData

export your data without encryption.
 $ strapi export --no-encrypt
___

### Additional context

Have tried with different DB: sqlite, mysql -  same stuff
Without arguments "strapi export" works fine

**Comment by Convly** [comment] 2024-04-16 16:57
Use `npm run strapi export -- -f export_name` instead

[`npm run <script>` expect script's arguments to be placed after `--`](https://docs.npmjs.com/cli/v8/commands/npm-run-script#description)

Closing as it's not a bug with Strapi.

**Closed by Convly** 2024-04-16 16:57 UTC

**Comment by ztxone** [comment] 2024-04-16 18:09
> Use `npm run strapi export -- -f export_name` instead
> 
> [`npm run <script>` expect script's arguments to be placed after `--`](https://docs.npmjs.com/cli/v8/commands/npm-run-script#description)
> 
> Closing as it's not a bug with Strapi.

Ty for answer. I supposed this have to be fixed in docs thow
![Screenshot 2024-04-16 at 20 08 59](https://github.com/strapi/strapi/assets/39146381/e1b37461-8da7-4797-9770-4821500bab89)

**Comment by Convly** [comment] 2024-04-17 08:25
Not really, `yarn` doesn't need `--`, only `npm`.

In this example, the documentation uses the generic strapi CLI format to define the generic commands.

However, we usually detail what command to use for both npm and yarn in the command's respective documentation.

- [Export](https://docs.strapi.io/dev-docs/data-management/export#example-export-data-with-a-custom-filename)
- [Import](https://docs.strapi.io/dev-docs/data-management/import#example-minimum-command-to-import-data-from-a-file-in-the-strapi-project-root)
- [Transfer](https://docs.strapi.io/dev-docs/data-management/transfer#setup-and-run-the-data-transfer)

**Comment by abhijithkmpixel** [comment] 2024-08-12 08:28
No matter what arguement i give its givimg me error
strapi ver: 4.25.4

npm run strapi export -- -f export_name
error: too many arguments for 'export'. Expected 0 arguments but got 1.
 
 also npm run strapi export --only content this command is not properly working
 as when i run this its exporting the assets too

**Comment by philipAthanasopoulos** [comment] 2025-07-09 09:20
> No matter what arguement i give its givimg me error strapi ver: 4.25.4
> 
> npm run strapi export -- -f export_name error: too many arguments for 'export'. Expected 0 arguments but got 1.
> 
> also npm run strapi export --only content this command is not properly working as when i run this its exporting the assets too
> 
> but worked with yarn

I'm also facing the same issue right now with Strapi v5
