### ISSUE TITLE
Facebook provider stores user's non unique name as strapi unique username

### ISSUE THREAD

**Issue by negati-ve** [strapi/strapi#6014] opened 2020-04-30 18:22 UTC
**Describe the bug**
After going through the facebook provider auth flow via /connect/facebook
the callback stores the user's facebook non unique name as the user's unique strapi username

In strapi-plugin-users-permissions/services/Providers.js > getProfile
line 174
```
facebook
        .query()
        .get('me?fields=name,email')
        .auth(access_token)
        .request((err, res, body) => {
          if (err) {
            callback(err);
          } else {
            callback(null, {
              username: body.name,
              email: body.email,
            });
          }
        });
```

There seem to be many Jim Laurie on facebook
This would mean that only one Jim Laurie could ever sign up on the site via facebook
**Steps to reproduce the behavior**

1. login through facebook provider with 2 accounts with the same name

**Expected behavior**
username should be unique in case user logs in through facebook
Ideally, the user's profile url/handle would be the perfect fit for username
Although, this isn't available through graph api. 

So the best bet is to use the user's facebook user id as his/her username 

**Code snippets**
quick fix by dropping a customization in extensions/users-permissions/services/Providers.js
```
facebook
        .query()
        .get('me?fields=id,email')
        .auth(access_token)
        .request((err, res, body) => {
          if (err) {
            callback(err);
          } else {
            callback(null, {
              username: body.id,
              email: body.email,
            });
          }
        });
```

**Comment by lauriejim** [comment] 2020-05-07 13:13
Thank you for reporting this issue.
I ping @Aurelsicoko and @alexandrebodin about this issue.

There is a workaround for this issue.

DO NOT update the `extensions/users-permissions/models/User.settings.json` to update the `require: false` of the username field.
This field could be used for the auth.

BUT you can create a new field `name` for example.
And the use the [customization concept](https://strapi.io/documentation/3.0.0-beta.x/concepts/customization.html) to update this function as you did in your **Code snippets
** section.

**Comment by Dannymx** [comment] 2020-07-10 20:56
I agree, as I tested the registration I found users when they register they could easily find their username was already taken. An option to make this non-unique or have another field as the username would be nice to have.

**Comment by alexandrebodin** [comment] 2020-07-15 09:08
We already discussed this in another issue (can't find it) I think we should use the email as unique identifier and let the username be whatever the user wants.

**Comment by Aurelioolive** [comment] 2020-12-10 10:03
I think that email could be the unique identifier. It would even be interesting if, when registering a user via Facebook (or other provider), he checked if the same email address already exists in the registered database to associate Facebook Login with the already registered user.

**Comment by dotamir** [comment] 2021-04-23 08:58
Is anyone up to this issue? If not, I can work on this issue if that's okay?

**Comment by Aurelioolive** [comment] 2021-04-23 13:12
> Is anyone up to this issue? If not, I can work on this issue if that's okay?

Do a PR =]

**Comment by MrMossevig** [comment] 2021-05-28 09:03
I added a PR for this. In short itis an added check in Providers.js that checks if the username is taken. If it is taken it adds a random suffix to the username.
I opted for tilde (~) as the separator as that works best with "real" usernames. Facebook names would look better with a psce and a hash(#) but facebook is not using the "real" username atm, I think it would be better to use the username (the one in the title bar on a profile page) for username from Facebook, but there might be  a problem with this?

Anyway if anyone ends up here and want the quick fix:
Create a file: extensions/users-permissions/services/Providers.js
Add this to the top:
```
const crypto = require('crypto');

// Same random suffix as used in upload
const randomSuffix = () => crypto.randomBytes(3).toString('hex');
```
And  this between "Retrieve default role" and "Create the new user":

```
        // Check if a user with the username exists
        var usernames = await strapi.query('user', 'users-permissions').find({
            username: profile.username,
          });

        // Add a new #randomsuffix to the username till we find one that is not taken
        var newUsername;
        while(!_.isEmpty(usernames)) {
            newUsername = `${profile.username}~${randomSuffix()}`;
            usernames = await strapi.query('user', 'users-permissions').find({
                username: newUsername,
              });
        }

        // Set the updated username
        profile.username = newUsername;
```

**Comment by omkarg01** [comment] 2022-02-09 18:26
@derrickmehaffy I would like to work on this issue.

**Comment by derrickmehaffy** [comment] 2022-08-17 18:34
I'm going to close this one as a duplicate of https://github.com/strapi/strapi/issues/8807

**Closed by derrickmehaffy** 2022-08-17 18:34 UTC
Labels: severity: low, good first issue, status: confirmed, source: plugin:users-permissions
