### ISSUE TITLE
TypeError: Promise.defer is not a function & Bootstrap encountered an error.

### ISSUE THREAD

**Issue by iocron** [strapi/strapi#146] opened 2016-09-22 23:17 UTC
Hello,
I've just made a fresh strapi installation with the help of your documentation (http://strapi.io/documentation), but I just get the following errors after starting it (OS X 10.10.5, Node v6.4.0):

```
strapi start
info: Server started in /....../projects/strapi
info: Your server is running at http://localhost:1337
info: Your admin panel is available at http://localhost:1337/admin/
debug: Time: Fri Sep 23 2016 00:54:33 GMT+0200 (CEST)
debug: Environment: development
debug: Process PID: 75531
debug: Cluster: master
info: To shut down your server, press <CTRL> + C at any time

error:  TypeError: Promise.defer is not a function
    at Object.exports.create (/....../projects/strapi/api/user/config/fixtures/route.js:18:28)
    at /....../projects/strapi/config/functions/bootstrap.js:16:29
error: Bootstrap encountered an error.
error:  TypeError: Promise.defer is not a function
    at Object.exports.create (/....../projects/strapi/api/user/config/fixtures/route.js:18:28)
    at /....../projects/strapi/config/functions/bootstrap.js:16:29
```

And also this one after going through the admin panel:

```
debug: GET /admin/routes (1ms)

  Error: Route not found
      at Error (native)
      at Object.isUserAuthorized (/....../projects/strapi/api/user/services/user.js:91:13)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/strapi/node_modules/co/index.js:65:19)
      at tryCatcher (/usr/local/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
      at Promise._settlePromiseAt (/usr/local/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
      at Promise._settlePromises (/usr/local/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
      at Async._drainQueue (/usr/local/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
      at Async._drainQueues (/usr/local/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
      at Immediate.Async.drainQueues (/usr/local/lib/node_modules/strapi/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
      at runCallback (timers.js:574:20)
      at tryOnImmediate (timers.js:554:5)
      at processImmediate [as _immediateCallback] (timers.js:533:5)
```

By the way, if I may ask, do I have to run "strapi login" to be able to use strapi? (this wasn't exactly clear in the docs, even if I've followed every single instruction step including this one)

Kind regards,
ioCron

**Comment by Aurelsicoko** [comment] 2016-09-23 10:29
Hi @iocron! This issue is caused by your node.js version. Strapi (v1.5.4) is not compatible with Node v6. This is a known issue, and this will be fixed on the v3.

You don't have to run `$ strapi login` to use Strapi. This command will be necessary if you want to use the Studio, our set of online tools to create an API without write a single line of code.

**Comment by gabrielperales** [comment] 2016-09-24 18:39
I had the same issue, and I fixed it changing `Promise.defer` by a ES6 `Promise`.  I can share my code or make a pull request if you are happy with that.

**Comment by iocron** [comment] 2016-09-25 01:20
Hi @Aurelsicoko Thanks a lot for the quick information, I am able to switch between all nodejs versions freely / independently so it's not a problem for me. I'll be using 4.5.x while I am working with strapi for now.

Can't wait to see Strapi v3, I've just read the latest blog announcements about it, keep up the good work, maybe I am able to help on some features or plugins as well / in the future (pull-requests) once I find a bit more time.

**Comment by Aurelsicoko** [comment] 2016-09-25 13:10
@gabrielperales This is a great alternative too. The v3 will use the native Promise object to fix this. Thanks for your help!

@iocron I'm glad that you found a way to make Strapi work! Thanks for your kind words about the v3. I hope you will like it! Can you (or I) close the issue?

**Closed** 2016-09-25 13:16 UTC
Labels: bug, v1.0

**Comment by laclance** [comment] 2016-11-12 10:57
@gabrielperales please would you share your code if you dont mind. Im still new to ES6.

**Comment by Aurelsicoko** [comment] 2016-11-12 13:24
@laclance What's your Node version? Do you have the exact same issue?

**Comment by laclance** [comment] 2016-11-12 13:49
I do. 6.5.0

**Comment by pierreburgy** [comment] 2017-04-18 15:52
@iocron @gabrielperales @laclance Strapi v1 is now compatible with every Node versions, including 7.x. Feel free to upgrade: `npm i strapi -g`. More information here: http://blog.strapi.io/release-v1-6.
