### ISSUE TITLE
local plugin - public route

### ISSUE THREAD

**Issue by jsaguiar** [strapi/strapi#5775] opened 2020-04-12 21:01 UTC
**Describe the bug**
when create a new local plugin. all routes are authenticated despite no policy is defined. (or no way to define it has public) 

**Steps to reproduce the behavior**
just follow the documentation. 
https://strapi.io/documentation/3.0.0-beta.x/plugin-development/backend-development.html#controllers), 

**Expected behavior**
When policy array is empty, route should be public. 

```json {
  "routes": [
    {
      "method": "GET",
      "path": "/",
      "handler": "my-plugin.index",
      "config": {
        "policies": []
      }
    }
  ]
```
**System**
- Node.js version: v13.11.0
- NPM version: 6.13.7
- Strapi version: 3.0.0-beta.19.5
- Database: Postgres
- Operating system: MacOS 10.15.3

**Comment by derrickmehaffy** [comment] 2020-04-13 04:19
This is not a bug.

Policy != Permissions. Policies are executed after the user is allowed via permissions (it lets you run logic between auth/noauth and the controller)

Marking as closed as not a bug, you need to enable permissions for your plugin routes in the admin.

**Closed by derrickmehaffy** 2020-04-13 04:19 UTC

**Comment by alexgalkin** [comment] 2020-11-05 16:26
> This is not a bug.
> 
> Policy != Permissions. Policies are executed after the user is allowed via permissions (it lets you run logic between auth/noauth and the controller)
> 
> Marking as closed as not a bug, you need to enable permissions for your plugin routes in the admin.

Honestly, it sounds like a bullshit. It is definitely a bug. Policies should be exactly for that purpose. I do not understand why I need to go and click on hundreds of checkboxes to allow public access and do that on EVERY environment where I deploy the application instead of configuring that in policy. Can you please explain your desire to click on tons of the checkboxes instead of creating proper policies logic? Thanks.

**Comment by derrickmehaffy** [comment] 2020-11-05 21:32
> > This is not a bug.
> > Policy != Permissions. Policies are executed after the user is allowed via permissions (it lets you run logic between auth/noauth and the controller)
> > Marking as closed as not a bug, you need to enable permissions for your plugin routes in the admin.
> 
> Honestly, it sounds like a bullshit. It is definitely a bug. Policies should be exactly for that purpose. I do not understand why I need to go and click on hundreds of checkboxes to allow public access and do that on EVERY environment where I deploy the application instead of configuring that in policy. Can you please explain your desire to click on tons of the checkboxes instead of creating proper policies logic? Thanks.

We have a temporary workaround (though largely unintended, and will be changed in the future to something more defined)

```json
  "routes": [
    {
      "method": "GET",
      "path": "/",
      "handler": "my-plugin.index"
    }
  ]
```

The above example will skip the users-permissions check all together and make the route public. But to define it in context of my previous reply, we put a strong focus on security meaning every route is protected by default. The permissions options are very basic in nature and simply define if the user has access to the handler (controller) or not. The default for that is not.

Policies in the context of the users-permissions plugin are actually Koa.js middlewares that are scoped to that specific route (they function exactly like a middleware but are not ran on every request). Their purpose is also not narrowly scoped to just restricting access but are for any custom logic that runs **-before-** the handler (controller). This means you could instead use a policy to strictly define some query parameters if the user doesn't.

Take for example a policy that sets the default `_sort` filter if the user doesn't define one.

**Path:** `./config/policies/somepolicy.js`

```js
module.exports = async (ctx, next) => {
  console.log(ctx.query)
  if (!ctx.query['_sort']) {
    // If SQL
    ctx.query['_sort'] = 'created_at:desc'

    // If Mongo
    //ctx.query['_sort'] = 'createdAt:desc'
  }
  await next()
};
```

**Path:** `./api/somemodel/config/routes.json`

```json
{
  "routes": [
    {
      "method": "GET",
      "path": "/clients",
      "handler": "client.find",
      "config": {
        "policies": ["global::somepolicy"]
      }
    },
  ]
}
```

In the above context and example if the user requests `GET localhost:1337/clients` without the `?_sort=somefield:desc` then the policy automatically sets it for you. Yes you can do more custom validation of the incoming request and do something like a `return ctx.badRequest('some error message')` but that isn't the only purpose of a policy.

I hope that's more clear and I apologize if my previous response came off wrong, it was not intended.

**Comment by derrickmehaffy** [comment] 2020-11-05 21:33
Also if you don't want to check the boxes to preset permissions there are alternatives: https://github.com/strapi/strapi/discussions/6294#discussioncomment-16719

**Comment by alexgalkin** [comment] 2020-11-06 06:42
@derrickmehaffy thanks for the quick reply. I see what you mean though it still looks a bit weird that policies are not related to permissions.

Thank you for pointing out the workaround. We will try that.

**Comment by derrickmehaffy** [comment] 2020-11-06 14:08
> bit weird that policies are not related to permissions.

The key thing is that policies function at a global Koa.js level (part of the framework) and the users-permissions is just a plugin, one that we intend to make optional and not installed by default in the future when we the [native API tokens](https://portal.productboard.com/strapi/1-roadmap/c/40-api-token-with-permissions).

There are various uses for Policies that aren't just restrictive in nature, they are simply a course or principle of actionable logic ran between the standard permissions check and the controller (which parses through the request context to execute the services which then trigger the queries to talk to the database).

You could very easily scope a policy to forward data to a logging platform, or fetch additional remote data to inject into the response, the possibilities are endless.

**Comment by pianomansam** [comment] 2021-02-02 16:28
> Also if you don't want to check the boxes to preset permissions there are alternatives: https://github.com/strapi/strapi/discussions/6294#discussioncomment-16719

Link it dead. I would really like to know what was in that conversation.

**Comment by derrickmehaffy** [comment] 2021-02-02 17:14
> > Also if you don't want to check the boxes to preset permissions there are alternatives: https://github.com/strapi/strapi/discussions/6294#discussioncomment-16719
> 
> Link is dead. I would really like to know what was in that conversation.

https://forum.strapi.io/t/set-permissions-programmatically-6294/1774
