### ISSUE TITLE
strapi server shutsdown unexpectedly

### ISSUE THREAD

**Issue by harshchaudhari9** [strapi/strapi#20638] opened 2024-06-26 12:15 UTC
Whenever I try to create a component in Strapi content builder the server of strapi shuts down unexpectedly and if I delete that component (eg:" dummycompo.json ) from the files which is in my machine then it starts perfectly

"⠦ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐│                                                                                                                                  ││   TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined                               ││   at Object.join (node:path:433:7)                                                                                               ││   at C:\vscodefiles\backend strapi\ai-resume\node_modules\@strapi\core\dist\loaders\components.js:17:31                          ││   at Array.forEach (<anonymous>)                                                                                                 ││   at C:\vscodefiles\backend strapi\ai-resume\node_modules\@strapi\core\dist\loaders\components.js:14:32                          ││   at Array.reduce (<anonymous>)                                                                                                  ││   at loadComponents (C:\vscodefiles\backend strapi\ai-resume\node_modules\@strapi\core\dist\loaders\components.js:13:39)         ││   at async Promise.all (index 5)                                                                                                 ││   at async Module.loadApplicationContext (C:\vscodefiles\backend                                                                 ││   strapi\ai-resume\node_modules\@strapi\core\dist\loaders\index.js:12:3)                                                         ││   at async Object.register (C:\vscodefiles\backend                                                                               ││   strapi\ai-resume\node_modules\@strapi\core\dist\providers\registries.js:26:5)                                                  ││   at async Strapi.register (C:\vscodefiles\backend strapi\ai-resume\node_modules\@strapi\core\dist\Strapi.js:322:7)              ││                                                                                                                                  │└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by Convly** [comment] 2024-06-26 12:30
Closing as duplicate of https://github.com/strapi/strapi/issues/20057

If you can provide more reproduction steps (e.g. your windows config). That would be awesome.

**Closed by Convly** 2024-06-26 12:30 UTC

**Comment by harshchaudhari9** [comment] 2024-06-26 14:07
my windows is 11
and npm 10.7.0 
and node version is 20 lts

**Comment by harshchaudhari9** [comment] 2024-06-26 14:08
can this issue be solve and if its solved pls provide links etc would great help
