### ISSUE TITLE
Broken Peer dependency: graphql plugin

### ISSUE THREAD

**Issue by LidiaSecchi** [strapi/strapi#19895] opened 2024-03-22 09:28 UTC
### Required System information

- Node.js version: 20.5.1
- NPM version: 9.8.0
- Strapi version: 5.0.0-beta.0
- Database: 
- Operating system: Linux Manjaro
- Is your project Javascript or Typescript: js

### Describe the bug

create a repo using npx create-strapi-app@5.0.0-beta.0 strapi5-myqpp --quickstart .
running npm install, no graphql plugin is downloaded.
forced npm i @strapi/plugin-graphql

### Steps to reproduce the behavior

1. create a repo using npx create-strapi-app@5.0.0-beta.0 strapi5-myqpp --quickstart .
2. run npm install, no graphql plugin is downloaded.
3. forced installation for plugin graphql ``` npm i @strapi/plugin-graphql ```
4. 
```npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: strapi-v-5@0.1.0
npm ERR! Found: @strapi/strapi@5.0.0-beta.0
npm ERR! node_modules/@strapi/strapi
npm ERR!   @strapi/strapi@"5.0.0-beta.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @strapi/strapi@"^4.0.0" from @strapi/plugin-graphql@5.0.0-beta.0
npm ERR! node_modules/@strapi/plugin-graphql
npm ERR!   @strapi/plugin-graphql@"5.0.0-beta.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.```

### Expected behavior

npm install successfully

### Screenshots

--

### Code snippets

--

### Additional context

--

**Comment by derrickmehaffy** [comment] 2024-03-22 15:43
@Boegie19 confirmed it, mentioned on Discord

**Comment by Boegie19** [comment] 2024-03-22 19:05
closing it since it is npm i fully broken made a new issue for it https://github.com/strapi/strapi/issues/19903

**Closed by Boegie19** 2024-03-22 19:05 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: plugin:graphql, version: 5
