### ISSUE TITLE
Decimal/float fields only stores 2 numbers after the decimal point

### ISSUE THREAD

**Issue by Thyvo** [strapi/strapi#909] opened 2018-04-06 12:37 UTC
**Informations**
- **Node.js version**: v9.10.0
- **npm version**: 5.8.0
- **Strapi version**: 3.0.0-alpha.11.3
- **Database**: MongoDB
- **Operating system**: Win10pro

**What is the current behavior?**
I'm trying to store some coordinates in the database using the admin panel, after saving only the first 2 numbers after the decimal point are stored

**Steps to reproduce the problem**
Create a new content type with a number(float or decimal) field.
Populate the fields with numbers with decimals (50.159740 and 10.355469 for example)

**What is the expected behavior?**
The values to be stored correctly in the database

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment] 2018-04-10 20:38
The issue is caused by the `type` detection. Generate `Double` instead of `Float` and I think it can come from here https://github.com/strapi/strapi/blob/master/packages/strapi-mongoose/lib/utils/index.js

Can you try to debug it please an submit a PR :) will appreciate your help !

**Comment by derrickmehaffy** [comment] 2018-04-23 13:37
Just wanted to note that previously a change was made on the Decimal and Float types (I think V10?) that might be causing this. https://github.com/strapi/strapi/pull/589

Decimal type previously before this change did store more than 2 decimal points until it was removed and replaced with float.

**Comment by Aurelsicoko** [comment] 2018-04-23 17:02
@derrickmehaffy I remember it but it seems that the support of decimal in MongoDB is still complicated. I would love to know how we could fix it definitely because the previous implementation allowed us to remove the `mongoose-double` plugin.

**Comment by derrickmehaffy** [comment] 2018-04-24 05:54
I agree @Aurelsicoko I think this might have something to do with defining the accuracy of the float option. I know in MySQL you can define the integer accuracy before and after the decimal.

If I understand mongo's method for storing floats its using IEEE 754 and really the only good suggestion is to store them as stringified decimals (which is a super ugly solution)

**Comment by Aurelsicoko** [comment] 2018-04-24 09:25
After some readings, it seems that the decimal supports was improved from MongoDB 3.4. Mongoose seems to support the Decimal128 type (http://mongoosejs.com/docs/schematypes.html). I've already tried to implement it but it wasn't working as expected. I should give another try...

**Comment by Aurelsicoko** [comment] 2018-04-24 13:28
Woohoo, I made it! The PR is open https://github.com/strapi/strapi/pull/1019, it should be working 👍

**Comment by derrickmehaffy** [comment] 2018-04-24 13:47
Nice job @Aurelsicoko this was a huge killer for the project I was working on, can't wait for it to go live :grin:

**Comment by Aurelsicoko** [comment] 2018-04-24 15:58
Already merged by the awesome @lauriejim! I'm closing the issue...

**Closed by Aurelsicoko** 2018-04-24 15:58 UTC
Labels: priority: medium, status: confirmed 👍, type: bug 🐛
