### ISSUE TITLE
Implementing Postgres Heroku DATABASE_URL needed in multiple places

### ISSUE THREAD

**Issue by fredrivett** [strapi/strapi#3520] opened 2019-06-24 15:22 UTC
I'm not sure where exactly to put this, as it's an issue with a feature that isn't yet supported but is quite needed.

That issue is using a postgres DB hosted with Heroku. [There's already some chat about this here](https://github.com/strapi/strapi/issues/3094), but wanted to elaborate on the issue having looked into it.

I started doing some work to get this feature in, and [put a commit together](https://github.com/octopuswealth/strapi/commit/c1650ed8c4e88578640c658b456f0aba3b71d60c) that seemed to do the job. We could login with that setup but things didn't work as expected (it was a week or so ago we hit the issue, from memory I think things like viewing specific content types (e.g. `Article`) threw errors).

[We found a temporary hacky solution](https://github.com/strapi/strapi/issues/3245), by running this in our production DB after a deploy:
`delete from core_store where key = 'plugin_content-manager_schema';`

The issue seems to be that `strapi-hook-bookshelf` also directly references the database. I hoped there was one source of truth for the database connection (the one I edited in the commit above in `strapi-hook-knex`) but it seems that's not the case. [The `dbName` here outputs as `undefined` and therefore fails to connect](https://github.com/strapi/strapi/blob/master/packages/strapi-hook-bookshelf/lib/index.js#L27).

**Ideally there'd be one source of truth that handles the DB connection, but with two different packages needing this info, I'm not sure how best to go about that? Another package that they both reference?**

As I'm new to Strapi I'd appreciate guidance about how best to go about this.

**Comment by alexandrebodin** [comment] 2019-07-03 15:23
Hi,

I'm going to close this issue as a duplicate of #3094 and give you more info there ;)

**Closed by alexandrebodin** 2019-07-03 15:23 UTC
Labels: type: help wanted 🤷‍♂️
