### ISSUE TITLE
strapi-hook-mongoose not found [ Never Resolved ]

### ISSUE THREAD

**Issue by Skullyfox** [strapi/strapi#4828] opened 2019-12-26 10:55 UTC
**Description of the bug**

When i try to deploy on Heroku, i have this error : 
![image](https://user-images.githubusercontent.com/28902701/71473193-5aea2380-27d6-11ea-8096-5ccf2ce40379.png)

This issue was never be resolved, i try a lot of issue here, and nobody work .... 

**config > environnement > production > database.json**

![image](https://user-images.githubusercontent.com/28902701/71473336-d9df5c00-27d6-11ea-8e53-30f0996c28d1.png)

**my package.json**

![image](https://user-images.githubusercontent.com/28902701/71473397-2034bb00-27d7-11ea-8f68-0de1744ff8c9.png)

**System**
- Node.js version: lastest
- NPM version: lastest
- Strapi version: 3.0.0-beta.18.3
- Database: Mongo
- Operating system: Heroku

**Comment by derrickmehaffy** [comment] 2019-12-26 11:29
As the migration guide states (https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html#upgrading-your-dependencies)

The name has changed from strapi-hook-mongoose to strapi-connector-mongoose, also in your package.json you need to change `strapi-hook-mongoose` to just `mongoose`

Not a bug, user error, marking as closed.

**Closed by derrickmehaffy** 2019-12-26 11:29 UTC

**Comment by Skullyfox** [comment] 2019-12-26 14:20
> As the migration guide states (https://strapi.io/documentation/3.0.0-beta.x/migration-guide/migration-guide-beta.17-to-beta.18.html#upgrading-your-dependencies)
> 
> The name has changed from strapi-hook-mongoose to strapi-connector-mongoose, also in your package.json you need to change `strapi-hook-mongoose` to just `mongoose`
> 
> Not a bug, user error, marking as closed.

With mongoose, Strapi don't connect to mLab, i've timeout, so i tried strapi-connector-mongoose
