### ISSUE TITLE
DB column not dropped when collection type field is removed

### ISSUE THREAD

**Issue by cappe** [strapi/strapi#9129] opened 2021-01-14 18:43 UTC
### Describe the bug

When a column is removed, it's not dropped from the db. If the column was required (it had NOT NULL constraint), updating existing records fail due to NOT NULL constraint is not met.

### Steps to reproduce the behavior

1. Create a collection type "Articles" from Content-Types Builder
2. Add a Text field called "title"
3. Set the field as "Required field" from the field's Advanced Settings
4. Create an article with a title, save
5. Go back to Content-Types Builder and remove the required "title" field, save
6. Update the article's title, save
7. Save fails due to NOT NULL constraint still present in the db
8. Log into the db and "SELECT * FROM articles;" and confirm that the required field "title" is still present

### Expected behavior

Removing a field from the collection type should drop the related column from the db.

### Screenshots

N/A

### Code snippets

N/A

### System

- Node.js version: 12.20.1
- NPM version: 6.14.10
- Strapi version: 3.4.3
- Database: PostgreSQL v12.1
- Operating system: Using the Docker image strapi/strapi:3.4.3-node12-alpine so Alpine?

### Additional context

I'm happy to contribute if and when this issue is confirmed.

**Comment by derrickmehaffy** [comment] 2021-01-14 20:03
Closing as duplicate of #1114

**Closed by derrickmehaffy** 2021-01-14 20:03 UTC
Labels: status: duplicate
