### ISSUE TITLE
Error in Single Type Controller Documentation

### ISSUE THREAD

**Issue by gfritzdev** [strapi/strapi#7747] opened 2020-09-06 01:21 UTC
**Describe the bug**
`const { sanitizeEntity } = require('strapi-utils');
module.exports = {
  /**
   * Retrieve the record.
   *
   * @return {Array}
   */
  async find(ctx) {
    const entity = await strapi.services.restaurant.findOne();
    return sanitizeEntity(entity, { model: strapi.models.restaurant });
  },
};
`
**Steps to reproduce the behavior**

1. Go to https://strapi.io/documentation/v3.x/concepts/controllers.html#single-type
2. Click on find
3. Scroll down to the code example 

**Expected behavior**
The example should use the .find() method instead of findOne.  findOne() does not exist for single types.

`async find(ctx) {
    const entity = await strapi.services.restaurant.findOne();
    return sanitizeEntity(entity, { model: strapi.models.restaurant });
  },
`
**should be:**

`async find(ctx) {
    const entity = await strapi.services.restaurant.find();
    return sanitizeEntity(entity, { model: strapi.models.restaurant });
  },
`

**System**

- Node.js version: v12.18.3
- NPM version: 6.14.7
- Strapi version: 3.1.4
- Database: mySql
- Operating system: OSX

**Comment by MattieBelt** [comment] 2020-09-07 06:41
Duplicate of #7718, fixed in #7721.

**Comment by derrickmehaffy** [comment] 2020-09-07 13:35
Closing as duplicate of https://github.com/strapi/strapi/issues/7718

**Closed by derrickmehaffy** 2020-09-07 13:35 UTC
Labels: status: duplicate
