### ISSUE TITLE
strapi.config.currentEnvironment is undefined inside services file

### ISSUE THREAD

**Issue by jiv-e** [strapi/strapi#5602] opened 2020-03-25 17:16 UTC
**Describe the bug**
Global strapi.config.currentEnvironment is undefined inside API services file.

**Steps to reproduce the behavior**
1. Create a custom services file inside api/ folder. See: https://strapi.io/documentation/3.0.0-beta.x/cli/CLI.html#strapi-generate-service
2. Write console.log(strapi.config) on top of the services file, outside the method calls.
3. Run _npm run develop_ and check the output.

**Expected behavior**
Global property strapi.config.currentEnvironment should be defined.

**System**
- Node.js version: 12.14.1
- NPM version: 6.13.6
- Strapi version: v3.0.0-beta.19.3

**Additional context**
I wan't to access env specific configs for instantiating some third party API clients.

**Comment by derrickmehaffy** [comment] 2020-03-25 18:04
@jiv-e can you describe where you plan on saving certain things in the config. The way I understand it is you plan on storing the information somewhere in the config directory but might be useful to know where specifically you are looking to do so.

@alexandrebodin when you get a minute can you briefly run down what is the proper way to store custom config stuff (maybe other than the `config/environments/*/custom.json` ).

If someone where to make a `config/environments/*/myconfig.json` would that be accessible from `strapi.config.myconfig` ?

**Comment by alexandrebodin** [comment] 2020-03-25 18:20
Hi @jiv-e you aren't supposed to be using strapi.config in the modele declaration. Strapi is requireing the files in your app at the same time as the configuration. If you add a function and using strapi.config.currentEnvorionment inside of that function it will be available. 

I'm going to close this issue as this is the intended behaviour.

**Closed by alexandrebodin** 2020-03-25 18:20 UTC
Labels: type: discussion

**Comment by derrickmehaffy** [comment] 2020-03-25 18:23
Maybe here would be better? https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#functions

Create a function and call that?

**Comment by alexandrebodin** [comment] 2020-03-25 18:26
You should either create a custom hook or simply use the bootstrapi function :)

**Comment by jiv-e** [comment] 2020-03-25 22:15
Ok! Thanks for the information. I'm still wondering is there some reason environment configs are not required before other stuff? Is it technically impossible or difficult?

Being able to use these config files globally would give a nice cohesive way for adding env configs. Otherwise some configs need to be placed somewhere else. I find this confusing, at least for other developers trying to figure out the codebase.

If for some reason the current situation cannot be changed, this restriction could be documented with recommendations what to store in environment configs and what not. At least I got an impression that all the configs could be added in this great flexible folder structure provided by Strapi.

My current need is to add MailChimp API-keys to the config.

/config/environments/development/mailchimp.json
```
{
  "mailChimpApiKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx-us15",
  "mailChimpListId": "xxxxxxxxxxxx"
}
```

I want to use this inside /api/mailchimp/services/MailChimp.js like this. Once in the beginning of the file:
```
const Mailchimp = require("mailchimp-api-v3");
const mailchimp = new Mailchimp(strapi.config.currentEnvironment.mailChimpApiKey);
...
```

Currently I'm doing this:
```
const getMailChimpClient = () => (
  this.mailchimp =
    this.mailchimp ||
    new Mailchimp(strapi.config.currentEnvironment.mailChimpApiKey)
);
```

Then I call getMailChimpClient() inside the service method. CurrentEnvironment property is already defined in that stagem so it works, but feels hacky.

**Comment by alexandrebodin** [comment] 2020-03-26 08:59
Hi, This is planned to be improved in the futur. 

In anycase I want to remove the need for a global variable as much as possible to provide better dev experience among other things. So you will probably only have access to the variable in a function call in the future. Example:

`api/blog/services/newsletter.js
```js
module.exports = (strapi) => {
  return new MailChimp(strapi.config.get('mailChimp')
}
```

**Comment by jiv-e** [comment] 2020-03-26 12:21
Nice idea!
I'm still wondering how this would solve the current problem?
Calling that newsletter function would create new MailChimp object every time, right? Or is the idea to run that exported function automatically by Strapi and make that result available inside controllers somehow?

```
module.exports = (strapi) => {
  return new MailChimp(strapi.config.get('mailChimp') // Will this be run only once when Strapi bootstraps?
}
```

**Comment by alexandrebodin** [comment] 2020-03-26 13:11
This is a simple dependency injection example. When strapi loads the file it calls the function once and exposes the result. IT would be the same as exporting a class and strapi instantiating it :)

So called only once ;)

**Comment by jiv-e** [comment] 2020-03-26 13:58
Nice!
