### ISSUE TITLE
Problem with database selection

### ISSUE THREAD

**Issue by adverterio** [strapi/strapi#2129] opened 2018-10-11 21:44 UTC
**Informations**
- **Node.js version**:10.12.0 
- **npm version**: 6.4.1
- **Strapi version**:  3.0.0-alpha.14.3
- **Database**: MongoBD
- **Operating system**: Windows 10 x64

**What is the current behavior?**
During creating new Strapi project on the step "Choose your main database:" I choose MongoBD and after that choice of the name of the database is not offered, and no errors are displayed. MongoBD is installed and launched with mongod and mongo in cmd. Same situation with other BDs.
![default](https://user-images.githubusercontent.com/20576120/46835146-01a2f980-cdb6-11e8-91d5-9fd08eddf24d.png)

**Comment by derrickmehaffy** [comment] 2018-10-12 06:09
@adverterio there are multiple issues related to windows. Please use WSL or a linux VM, current windows support is minimal and has many documented issues.

**Comment by dannydtk** [comment] 2018-10-12 09:53
Try with PowerShell instead of CMD.

**Comment by derrickmehaffy** [comment] 2018-10-12 13:28
@lauriejim duplicate of https://github.com/strapi/strapi/issues/1281

Recommend closing issue.

**Closed** 2018-10-16 12:49 UTC
Labels: status: duplicate

**Comment by msarfaraz** [comment] 2018-12-19 06:19
Its not working bro.I tried with powershell also??
