### ISSUE TITLE
Rename a field of a collection duplicates the field in API response

### ISSUE THREAD

**Issue by Guillaume-succubus** [strapi/strapi#5941] opened 2020-04-24 14:33 UTC
**Describe the bug**

When ever I rename a field in a collection (or single type) The previous name of the field stays in my API response(JSON) with the latest content.

**Steps to reproduce the behavior**
- create a single type with a field "name".
- go to your created single type and fill the name with "myName". Then click save
- request your api to get this single type you created and you'll see your member with a field "name" with "myName" as value.
- go to the builder and edit the field "name" of your single type (rename it "newName").
- go to your single type, in the value of your field "newName" put "myNewName" then save.
- request your API for that single type : you'll see a field name with value "myName" AND a field "newName" with value "myNewName".

**Expected behavior**

When you modify a field, the API removes the last on and keep only the new one (same in the DB)

**System**

- Node.js version: 12.13.1
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20
- Database: mongo
- Operating system: debian

**Comment by derrickmehaffy** [comment] 2020-04-24 14:36
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10/v12) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by Guillaume-succubus** [comment] 2020-04-24 15:01
Done

**Comment by alexandrebodin** [comment] 2020-04-24 16:39
Hello, @Guillaume-succubus To avoid deleting data strapi does not delete content in your mongo documents when changing names. The renaming simply recreates a new column to avoid issues with type casting / indexes / unique constraints and so on. When you will deploy your finalized scheam you will only have the right fields. In development you might want to reset your db or something. 

We will work on this in the future for sure be we would rather people have too much fields than break stuff until we have enough devs to work on this properly :)

**Comment by Guillaume-succubus** [comment] 2020-04-27 08:36
Ok that's fine, I guess I'll have to go directly in my db and removes the useless field as I was already in deployment when I discover I needed to change the name of the field (to allow translation between english and french). It still would be nice to have a settings to choose between only renaming or deleting :)

**Comment by lauriejim** [comment] 2020-04-27 15:53
This high-level topic is explained in this issue https://github.com/strapi/strapi/issues/1114

**Comment by etienneburdet** [comment] 2020-09-01 13:13
Same issue here. To elaborate on the topic, here my expected behavior : 
* API result fields matches exactly those displayed in the content type builder at any point, no matter what extra columns/tables are in the DB. Espacially no fields that are not in the model anymore.
* If I revert my Strapi codebase to a previous commit or switch a different branch etc. the API results fields should reflect this change as well.
* If some fields of certain records are not appearing anymore because they don't match the schema anymore, they should appear again if I revert to a previous commit.

It is more about querying than deleting data (although I have no idea how hard it is to implement 😛 )

**Comment by ortonomy** [comment] 2021-02-10 10:00
Low severity that hasn't been fixed since April 2020? This is, as far as I'm concerned, a deal breaker. How can something as basic as changing case on a field name cause the whole app to crash? Just because I chose to use MySQL as a database? Either don't support the database or fix it. This is insane?!

**Comment by finex** [comment] 2021-02-11 23:30
Hi, I'm also experiencing this bug. If a simple field rename action needs a manual migration it should be a big warning on the UI. 

I've just started to evaluate Strapi, but now, with this type of bug I'm quite afraid to know what else I could found. Is this project ready for production projects?

**Comment by derrickmehaffy** [comment] 2021-02-22 14:51
> Low severity that hasn't been fixed since April 2020? This is, as far as I'm concerned, a deal breaker. How can something as basic as changing case on a field name cause the whole app to crash? Just because I chose to use MySQL as a database? Either don't support the database or fix it. This is insane?!

This is the same on all databases, as mentioned above see: #1114 and it's a topic we plan to address in Q3 of 2021

**Comment by SalahAdDin** [comment] 2021-05-13 22:20
Mine is related to this workflow but with a different result: renaming a collection field does delete the previous content, is it normal?

**Comment by derrickmehaffy** [comment] 2021-05-17 18:10
Closing as duplicate of #1114

**Closed by derrickmehaffy** 2021-05-17 18:10 UTC
Labels: status: duplicate
