### ISSUE TITLE
MediaLibrary Content Is genrating New Auto Folders and save images there automatic while Upload from postman or App 

### ISSUE THREAD

**Issue by MohamedSonata** [strapi/strapi#13999] opened 2022-08-05 16:05 UTC
- Node.js version:16
- NPM version:6
- Strapi version:4.3.2

- Operating system:windows

### Describe the bug
I've tried a lot of methods to skip this but there's no way Every Time i upload and media images to Media Library Content Is generating new folder is (API Upload) and save only one Image for each upload and save other's out the folder in assets ....
can some one help ;
https://user-images.githubusercontent.com/96669613/183116817-3f9c25db-eca6-4a57-99e3-b3a7be71a64d.png

**Comment by petersg83** [comment] 2022-08-05 16:21
Hello @MohamedSonata!
Is there multiple `API Upload` folders created? Or just one where all the uploaded file go to?

If it is just one, then it is intended in order to keep the root level of the Media Library clean and not mixing files coming from the API and files uploaded by the admin users.

Do you prefer files uploaded to the root level?

**Comment by MohamedSonata** [comment] 2022-08-05 16:30
hello @petersg83 
no I'm Not Prefer upload to the root level ..
But the problem while u select multiple  files and upload it u find MediaLibrary save one file in (API Upload) Folder and save else files to the root Level...

how i can select a folder to upload files From Api Requests Like Post Man

**Comment by petersg83** [comment] 2022-08-05 16:37
Oh so when you upload several files within the same request, only one goes to the `API upload` folder and the others go to the root level. Is that correct? If yes, it is a bug indeed and it should be fixed.

You cannot select a specific folder to upload the files. However, you can rename the folder and change its location if you want. Files will keep being uploaded to this folder.

**Comment by MohamedSonata** [comment] 2022-08-05 16:42
Oh so when you upload several files within the same request, only one goes to the API upload folder and the others go to the root level. Is that correct? If yes, it is a bug indeed and it should be fixed. 

yes It's Correct i hope The Team Fix It Soon..

Thanks Bro.

**Comment by derrickmehaffy** [comment] 2022-08-05 17:09
Reproduction loom video: https://www.loom.com/share/3a3d144462f340e29af571e70e90b12d

**Comment by petersg83** [comment] 2022-08-08 16:39
Will be released Wednesday :) thank you @WalkingPizza and @MohamedSonata!

**Closed** 2022-08-08 16:38 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:upload

**Comment by MohamedSonata** [comment] 2022-08-09 18:31
You're Welcome Bro @petersg83 We want Strapi to be in constant development for the better and without errors because it is one of the best open-source headless CMS back End  that has been built
