### ISSUE TITLE
[Design] Dynamic Zones disappear in the published tab

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20790] opened 2024-07-16 19:59 UTC
https://www.notion.so/strapi/Dynamic-Zones-disappear-in-the-published-tab-603467d37ae34c6c9fbe8de365102a87?pvs=4

https://github.com/user-attachments/assets/f9b69701-151b-460f-8231-1d991a51938f

**Comment by yanniskadiri** [comment] 2024-07-29 09:07
Could not reproduce in rc.7

**Comment by Feranchz** [comment] 2024-09-05 08:57
Closing this after QAed, everything looks fine

**Closed by Feranchz** 2024-09-05 08:57 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-manager, version: 5
