### ISSUE TITLE
Mongo, populate nested field only from collection

### ISSUE THREAD

**Issue by borm** [strapi/strapi#9078] opened 2021-01-10 03:33 UTC
### Related [issue](https://github.com/strapi/strapi/issues/5520), no answer, 
@lauriejim why u did close it?

### Model
```
"attributes": {
  "admin": {
    "plugin": "users-permissions",
    "model": "user",
    "via": "restaurant"
  },
  "users": {
    "plugin": "users-permissions",
    "collection": "user",
    "via": "restaurant"
  }
}
```

### Original query
```
strapi.query('restaurant').findOne({ id: params.id }, populate);
```

### Query 1
```
populate = [];
```

#### Actual result
```
{
  admin: USER.ID,
  users: []
}
```

### Query 2
```
populate = ['users'];
```

#### Actual result
```
{
  admin: USER.ID,
  users: [USER, USER, USER]
}
```

### Query 3
```
populate = ['users.id'];
```

#### Actual result
```
 error MissingSchemaError: Schema hasn't been registered for model "restaurant".
```

#### Expected result
```
{
  admin: USER.ID,
  users: [USER.ID, USER.ID, ...], // not user model, only id
}
```

- **Strapi Version**: 3.4.0
- **Operating System**: MacOS
- **Database**: MongoDB
- **Node Version**: v14.15.3

**Comment by derrickmehaffy** [comment] 2021-01-11 23:36
Alright so going to break this down in steps:

Regarding the closed issue, it was done so because it was attempting to do something we don't support (and had extremely poor formatting, which our [rules](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue) are quite clear about and you did very well on in this issue)

---

> Query 1

The first one is a limitation of our population and how we handle relations, though this issue says components it also applies to certain relations. So duplicate of: https://github.com/strapi/strapi/issues/7360

---

> Query 2

Functions as intended

---

> Query 3

The population array only works on relational fields, so if you had some other relations on the user model, say users had a "comments" and "likes" relations (don't care which type) and you only wanted to populate the "likes"; Your population array would look like: `[ "user", "user.like" ]`, this would leave comments un-populated.

Also in your case I'm guessing you forgot to change the default controller from our docs example (swap out the restaurant for the actual model name)

examples: 
![image](https://user-images.githubusercontent.com/8593673/104250124-29b4b380-542a-11eb-9c77-30d72a6a3202.png)
![image](https://user-images.githubusercontent.com/8593673/104250163-3e914700-542a-11eb-8ee9-0a8f68c10f73.png)

---

At the moment we don't support dynamic population of fields themselves, only relational ones. We do plan to make a change I believe in Q3 which will make default population as none, and let users pick the fields (not just relational) they want to show.

Marking this as closed, as aside from the duplicate issue I linked, it's working as intended. If you need more advanced population you will have to build a custom query: https://strapi.io/documentation/developer-docs/latest/concepts/queries.html#mongoose

**Closed** 2021-01-11 23:36 UTC
Labels: status: duplicate

**Comment by derrickmehaffy** [comment] 2021-07-10 16:32
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/how-to-populate-component-that-comes-from-a-deep-nested-relation/3018/8

**Comment by MotaZor94** [comment] 2021-07-21 12:56
Hi @derrickmehaffy,


I have tried your solution above and it worked perfectly. The only issue then is that all the repeatable components get deleted from the object. Is there a solution to this maybe?

**Comment by derrickmehaffy** [comment] 2021-07-21 13:38
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/populate-deleted-components-and-repeatable-components/7459/1
