### ISSUE TITLE
[Bug] Unable to start strapi using docker-compose with local custom providers

### ISSUE THREAD

**Issue by tom555my** [strapi/strapi#10767] opened 2021-08-20 01:40 UTC
### Describe the bug

Unable to start strapi using docker-compose with local custom providers. The logs from the container said that `error Error: Cannot find module 'strapi-provider-upload-pcl-minio'`.

### Steps to reproduce the behavior

1. Create a custom provider, following this [guide](https://strapi.io/documentation/developer-docs/latest/development/plugins/upload.html#create-providers)
2. Start strapi using docker-compose
3. To see the log, `docker-compose logs -f strapi`

### Expected behavior

Strapi is up and running with my custom providers.

### Screenshots

*Logs from container*
![image](https://user-images.githubusercontent.com/19559068/130165472-ad038411-14ae-4cf8-adcb-7170ff3567d5.png)

*Project structure*
![image](https://user-images.githubusercontent.com/19559068/130165813-1304aae0-af09-48f2-a98e-33327ddd2184.png)

### Code snippets

*package.json*
```json
{
  "name": "app",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "0.21.18",
    "minio": "^7.0.18",
    "mysql": "2.18.1",
    "strapi": "3.6.3",
    "strapi-admin": "3.6.3",
    "strapi-connector-bookshelf": "3.6.3",
    "strapi-plugin-content-manager": "3.6.3",
    "strapi-plugin-content-type-builder": "3.6.3",
    "strapi-plugin-email": "3.6.3",
    "strapi-plugin-i18n": "3.6.3",
    "strapi-plugin-upload": "3.6.3",
    "strapi-plugin-users-permissions": "3.6.3",
    "strapi-provider-upload-pcl-minio": "file:./providers/strapi-provider-upload-pcl-minio",
    "strapi-utils": "3.6.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "xxxxxxxx"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": "^6.0.0"
  },
  "license": "MIT"
}
```

*strapi-provider-upload-pcl-minio/index.js*
Not sure if it is useful for this bug report
```js
const Minio = require('minio');
const { promisify } = require('util');

let Client = Minio.Client;

Client.prototype.bucketExists = promisify(Client.prototype.bucketExists);
Client.prototype.makeBucket = promisify(Client.prototype.makeBucket);
Client.prototype.putObject = promisify(Client.prototype.putObject);
Client.prototype.removeObject = promisify(Client.prototype.removeObject);
Client.prototype.presignedGetObject = promisify(
  Client.prototype.presignedGetObject
);

module.exports = {
  init(providerOptions) {
    // init your provider if necessary
    const {
      url,
      port,
      accessKey,
      secretKey,
      bucketName
    } = providerOptions;

    const client = new Client({
      endPoint: url,
      port,
      useSSL: false,
      accessKey,
      secretKey
    });

    return {
      upload: async (file) => {
        const newObject = await client.putObject(
          bucketName,
          `${file.hash}${file.ext}`,
          Buffer.from(file.buffer, 'binary'),
          {
            'Content-Type': file.mime,
          }
        );
        return newObject;
        // upload the file in the provider
      },
      delete: async (file) => {
        // delete the file in the provider
        await client.removeObject(
          bucketName,
          `${file.hash}${file.ext}`,
        );
      },
    };
  },
};
```

### System

- Node.js version: v14
- NPM version: 6.14.13
- Strapi version: 3.6.3
- Database: MySQL 8.0
- Operating system: Ubuntu

**Comment by derrickmehaffy** [comment] 2021-08-20 15:33
> error Error: Cannot find module 'strapi-provider-upload-pcl-minio'.
> "strapi-provider-upload-pcl-minio": "file:./providers/strapi-provider-upload-pcl-minio",

You need to run an `npm install` or `yarn install` in cases like this, unlikely this is an issue with Strapi itself (I regularly test with custom providers such as https://github.com/derrickmehaffy/strapi-test-clamav

Setting this as closed as I can't reproduce as is, please test my suggestion and if you still have issues we can do some more testing together.

**Closed by derrickmehaffy** 2021-08-20 15:33 UTC

**Comment by tom555my** [comment] 2021-08-23 07:53
Thanks for answering @derrickmehaffy. 

After studying the [docker-entrypoint.sh](https://github.com/strapi/strapi-docker/blob/master/strapi/docker-entrypoint.sh) of the docker image. I found that the way to handle this case is not running `npm install` or `yarn install` manually, as i am using Docker to serve the service. Having different OS in container and host machine will cause incompatible issue. Instead, we should
1. Kill and remove the container
2. Remove node_module
3. Start the container again

Hope this help others!
