### ISSUE TITLE
[gatsby-source-strapi] only return 100 data

### ISSUE THREAD

**Issue by Dogtiti** [strapi/strapi#2601] opened 2019-01-09 10:28 UTC
```
  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 71.0.3578.98
    Safari: 12.0.2
  npmGlobalPackages:
    gatsby-cli: 2.4.8
```
In fact , I have more than 1000 data in my database,but it only return 100 .In `strapi dashboard`also have all data.
![image](https://user-images.githubusercontent.com/38354472/50893180-43861f00-143b-11e9-9a1d-e698a7a48c52.png)
![image](https://user-images.githubusercontent.com/38354472/50893201-526cd180-143b-11e9-9f24-b71f7ed009d4.png)

And I also use `postman` to `GET` the data ,it also returns 100 data:

**Comment by derrickmehaffy** [comment] 2019-01-09 12:35
@Dogtiti This is intended you will need to use the filters to loop through and get more data.

https://strapi.io/documentation/3.x.x/guides/filters.html

Marking this as closed as it is not a bug

**Closed by derrickmehaffy** 2019-01-09 12:35 UTC
