### ISSUE TITLE
Missing add another field to this content type post GCP App Engine deployment

### ISSUE THREAD

**Issue by shivaping** [strapi/strapi#5078] opened 2020-01-23 17:52 UTC
**Describe the bug**

**Steps to reproduce the behavior**
1. Go to /admin and login to strapi admin dash board
2. Click on content type builder after deploying to GCP 
3. Scroll down : Missing : Add ANOTHER FIELD TO THIS CONTENT-TYPE Link

**Expected behavior**
![Capture](https://user-images.githubusercontent.com/13598222/73009986-7c6f1700-3e37-11ea-88a4-83bb908d3cb4.PNG)

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by alexandrebodin** [comment] 2020-01-23 18:00
Hi @shivaping,

When strapi is deployed to production you cannot edit the content types nor the components schemas. The worklow is : build schemas -> deploy -> manage content. And repeat :)

You need to edit in development mode commit and then re deploy ;)

Closing as this is the intended behaviour.

**Closed by alexandrebodin** 2020-01-23 18:00 UTC

**Comment by ViVa98** [comment] 2021-05-03 09:40
I ran into the same problem of not able to add a new collection, a new field when in development mode locally.

![Frame 4](https://user-images.githubusercontent.com/35100223/116861793-55e68100-ac21-11eb-822a-a42173bb7ef6.jpg)

![Screenshot (139)](https://user-images.githubusercontent.com/35100223/116861918-89291000-ac21-11eb-9592-d3f05699c6df.png)
