### ISSUE TITLE
Filters not working on the users-persmission plugin

### ISSUE THREAD

**Issue by kamal-choudhary** [strapi/strapi#12303] opened 2022-01-26 07:33 UTC
## Bug report

When we try to filter on the **/users** endpoint, it does not work.

### Steps to reproduce the behavior
1. Create 2,3 random users in the Users-Permissions
2. Create a user with username: "John"
3. Send a GET request to the /users like **http://localhost:1337/api/users?filters[username][$eq]=John**
4. Response contains all the users

### Expected behavior

The response should contain only the user with username: "John"

### System

- Node.js version: 14.15.3
- NPM version: 6.14.9
- Strapi version: 4.0.5
- Database: MariaDB
- Operating system: MacOS

### Additional context

Previously, I included the changes of PR #11795 manually in my project. I think Strapi 4.0.1 wasn't released at that time. Now, my Strapi is 4.0.5, so, I guess those changes are automatically overridden. The PR I mentioned was merged in 4.0.1.

**Comment by kasonde** [comment] 2022-01-26 18:40
Hi @kamal-choudhary , I'm unable to reproduce this issue on v4.0.5. Filtering seems to be working fine. See image attached.
![image](https://user-images.githubusercontent.com/13610895/151225975-e09c1c42-35cd-4586-8601-9c22b38cb732.png)

**Comment by kamal-choudhary** [comment] 2022-01-27 19:22
HI @kasonde  thanks for looking into it.

I checked and found that I have a file src\extensions\users-permissions\strapi-server.js

When I delete this file, the filter works fine.

but this file actually helps to make the population working on **/users** route.

Deleting this file makes the population functionality stop working.

I added this file to my project after seeing a reply on this Github issue: [https://github.com/strapi/strapi/issues/11957](https://github.com/strapi/strapi/issues/11957)

```
// path: src/extensions/users-permissions/strapi-server.js
module.exports = plugin => {
  const sanitizeOutput = (user) => {
    const {
      password, resetPasswordToken, confirmationToken, ...sanitizedUser
    } = user; // be careful, you need to omit other private attributes yourself
    return sanitizedUser;
  };

  plugin.controllers.user.me = async (ctx) => {
    if (!ctx.state.user) {
      return ctx.unauthorized();
    }
    const user = await strapi.entityService.findOne(
      'plugin::users-permissions.user',
      ctx.state.user.id,
      { populate: ['role'] }
    );

    ctx.body = sanitizeOutput(user);
  };

  plugin.controllers.user.find = async (ctx) => {
    const users = await strapi.entityService.findMany(
      'plugin::users-permissions.user',
      { ...ctx.params, populate: ['role'] }
    );

    ctx.body = users.map(user => sanitizeOutput(user));
  };

  return plugin;
};
```

PS: I am not the original author of this code. It was originally written by: @iicdii

**Comment by cnaum** [comment] 2022-01-27 20:48
I also had this issue - created a temporary work around by editing line 136... of node_modules\@strapi\plugin-users-permissions\server\controllers\user.js

async find(ctx, next, { populate } = {}) {
const populate1 = ["role"]
    const users = await getService('user').fetchAll(ctx.query.filters, populate1);

**Comment by kamal-choudhary** [comment] 2022-02-02 11:39
@cnaum I actually tried this - but it didn't work in my case. I also found that even if I just try to console.log something here, it doesn't get printed to the console.

**Comment by kamal-choudhary** [comment] 2022-02-07 08:46
The method @cnaum suggested works. However, I found that only the `role` field is not being populated. Although, other relational fields are being populated.

```
async find(ctx, next, { populate } = {}) {
const populate1 = ["someOtherRelationalProperty", "role"];
const users = await getService('user').fetchAll(ctx.query.filters, populate1);
```
`someOtherRelationalProperty` is being populated, but `role` is not being populated.

**Comment by kasonde** [comment] 2022-02-07 16:59
Hi @kamal-choudhary just a quick follow-up, after a crazy couple weeks it slipped my schedule to update you on this. I did verify this issue a while ago we were able to track down the problem being within the users-permissions plugin. It's because the permission name used to populate roles is called getRoles while the one you set in the admin is called something completely different. This mismatch tells Strapi (specifically the sanitize function) that you're actually not allowed to populate roles at all. The fix for this is to change line 3 in this file: [node_modules/@strapi/utils/lib/sanitize/visitors/remove-restricted-relations.js](https://github.com/strapi/strapi/blob/59a7fb31958010a190f6550fa5da17e12c456d5f/packages/core/utils/lib/sanitize/visitors/remove-restricted-relations.js#L3) to instead say: `const ACTIONS_TO_VERIFY = ['find', 'getRole', 'getRoles'];` and it should work.

Let me know if this works for you (minus the custom controller you wrote)!

**Comment by kamal-choudhary** [comment] 2022-02-08 09:56
Hi @kasonde thank you for looking into this issue. For some reason, the solution you suggested didn't work for me. I added that line in the file you mentioned, but `role` is still not getting populated.

PS: I'm not using the `strapi-server.js` code anymore. However, I'm using the patch suggested by @cnaum.

**Comment by marinalvdgs** [comment] 2022-04-12 08:03
Hi, solution suggested by @cnaum works fine for me (for me there are no need to get user role). But relations returns only with `/users` and `/users/me` requests and do not returns with `/users/:id` request. I tried to do same way with `findOne` method but it didn't work. Maybe someone faced with this issue and fixed it? 

Sorry if my question is silly, I'm very new in Strapi.

**Closed** 2022-06-01 18:38 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: plugin:users-permissions
