### ISSUE TITLE
Incorrect text search behavior with a PostgreSQL database

### ISSUE THREAD

**Issue by johannpinson** [strapi/strapi#5707] opened 2020-04-03 16:49 UTC
**Describe the bug**
Hey guys 👋 

I'm looking to work with the "search" service for a datatable react component.
But the search behavior seems to work only if I type an exact world (it's work with the "leader" word but not with "leade" for example).

I didn't test it with mysql or mongo, and it seems to be a problem specifically with postgres database (because it depends directly how the query raw is built).

I have the same "bug" with the filter in the admin search for the content.

Let's me know if you want that I create a PR directly.

Thanks,

PS : it may be related about the issue #5303, but not directly (and depends of the database type)

<br>
<br>

**Expected behavior**
I expected an autocomplete-style search, to avoid to type the exact term that i maybe not have/know

**Code snippets**
https://github.com/strapi/strapi/blob/c0ec9a54ec1ccfa5d9a7538b9f607fc47f96f2cf/packages/strapi-connector-bookshelf/lib/queries.js#L701-L707

At the line 707, the `query` variable must be change by `'${query}:*'`.
It will allow to use startwith query style when using :*.

```ts
qb.orWhereRaw(`${searchQuery.join(' || ')} @@ plainto_tsquery(?)`, `${query}:*`);
```

This is an example of a postgres query which working in the API (or the admin) if I search the term "leader", but only type "leade":
```sql
select "projects".*
from "projects"
where to_tsvector(coalesce(name, '')) || to_tsvector(coalesce(description, ''))
@@ to_tsquery('leade:*')
limit 100
```

**System**
- Node.js version: 13.12
- NPM version: 6.14.4
- Strapi version: @3.0.0-beta.19.4
- Database: PostegreSQL 10
- Operating system: MacOS 10.14.6

**Comment by derrickmehaffy** [comment] 2020-04-03 18:05
@johannpinson Welcome back! And yes if you could please create a pull request.

Thank you!

**Comment by lauriejim** [comment] 2020-04-09 13:53
Hello @johannpinson !
Thank you for reporting this issue, can you please provide steps to reproduce the issue you have please.
This will help to "see" the issue, and validate that the issue is well fixed.
Thank you.

**Comment by johannpinson** [comment] 2020-04-09 14:03
Hello @lauriejim !

Yes of course, it just need to create a new project with a PostgreSQL database.
Then, create a content type "Post" with a "name" string field.
Add some content with "nameA", "nameB", etc.

Then, directly from the administration, you can use the search input to test if you type "na", you may have some results.

Actually, it needs to write the exact name to get some results.

**Comment by johannpinson** [comment] 2020-04-09 14:14
Ok i made another commit, because I forget to change the `plainto_tsquery` to `to_tsquery` during my edit.

If we keep the `plainto_tsquery`, it will not work, event with the `${query}:*`, as indicated from the pg doc : 

> 12.3.2. Parsing Queries [...] [to_tsquery offers access to more features than either plainto_tsquery or phraseto_tsquery, but it is less forgiving about its input](https://www.postgresql.org/docs/10/textsearch-controls.html)

**Comment by derrickmehaffy** [comment] 2020-04-09 14:16
MySQL/MariaDB have similar search problems

**Comment by lauriejim** [comment] 2020-04-13 15:12
Thanks for the process, it will help @alexandrebodin to validate/approve it.

**Comment by alexandrebodin** [comment] 2020-04-14 07:48
Hi, We are reviewing the global search issues soon. I will add this to list of issues so we have good references to all issues and ideas. Thanks !

**Comment by derrickmehaffy** [comment] 2021-12-22 20:02
should be fixed in v4

**Closed by derrickmehaffy** 2021-12-22 20:02 UTC
Labels: issue-type: discussion
