### ISSUE TITLE
Post request API，Insert error on timestamp fields using MySQL

### ISSUE THREAD

**Issue by imxinz** [strapi/strapi#3825] opened 2019-08-22 19:01 UTC
hi guys, this is error screenshot. pls check it.

![image](https://user-images.githubusercontent.com/1137255/63541729-51635d00-c551-11e9-8883-6c143ff5413d.png)

* node version：v10.11.0
* npm version：6.4.1
* mysql version：v5.7.25
* strapi dependencies
`{
    "knex": "latest",
    "lodash": "^4.17.5",
    "mysql": "^2.17.1",
    "sqlite3": "latest",
    "strapi": "3.0.0-beta.15",
    "strapi-admin": "3.0.0-beta.15",
    "strapi-hook-bookshelf": "3.0.0-beta.15",
    "strapi-hook-knex": "3.0.0-beta.15",
    "strapi-plugin-content-manager": "3.0.0-beta.15",
    "strapi-plugin-content-type-builder": "3.0.0-beta.15",
    "strapi-plugin-email": "3.0.0-beta.15",
    "strapi-plugin-settings-manager": "3.0.0-beta.15",
    "strapi-plugin-upload": "3.0.0-beta.15",
    "strapi-plugin-users-permissions": "3.0.0-beta.15",
    "strapi-utils": "3.0.0-beta.15"
  }`

I can execute successfully with the original SQL：
`insert into `shicis` (created_at, pinglunCount, updated_at ) values ('2019-08-23 02:12:04', 0, '2019-08-23 02:12:04')`

**Comment by derrickmehaffy** [comment] 2019-08-23 11:58
If you are trying to update the `created_at` or `updated_at` fields manually via a Post request it will fail, as you shouldn't be updating those (the db server handles that).

Else this bug is a duplicate of https://github.com/strapi/strapi/issues/3031 and as such marking as closed

**Closed by derrickmehaffy** 2019-08-23 11:58 UTC
