### ISSUE TITLE
Renaming a component doesn't adjust schema

### ISSUE THREAD

**Issue by oriooctopus** [strapi/strapi#12083] opened 2022-01-03 15:53 UTC
## Bug report

Renaming a component adjusts the display name but does not adjust the name in the graphql schema, and as far as I know there is no other way to adjust it.

### Steps to reproduce the behavior

https://user-images.githubusercontent.com/20331238/147951351-fc288a80-2054-41a0-88cc-9815a2536648.mp4

### Expected behavior

There needs to be someway to adjust the name at the data level, not just the display level

### System

- Strapi version: 4.0.2

**Comment by derrickmehaffy** [comment] 2022-01-03 16:41
This isn't just components, it's everything. The only way to rename the component from the UI is to delete it and recreate it.

To actually just rename it requires you to modify it manually on the filesystem and handle the database migration using an undocumented custom migration script system.

Adding as a feature request, not a bug.

**Comment by petersg83** [comment] 2022-01-18 09:41
However I agree that the UI is misleading. I would be in favor of removing the rename feature or to show a message explaining that it doesn't migrate the data etc.

**Comment by aukgit** [comment] 2022-02-14 07:35
> ## Bug report
> Renaming a component adjusts the display name but does not adjust the name in the graphql schema, and as far as I know there is no other way to adjust it.
> 
> ### Steps to reproduce the behavior
>  untitled-jan-3-2022-12-44-pm_9DmQ5O2y.mp4 
> ### Expected behavior
> There needs to be someway to adjust the name at the data level, not just the display level
> 
> ### System
> * Strapi version: 4.0.2

Happened to me as well, kind of misleading

**Comment by aukgit** [comment] 2022-02-14 07:35
> This isn't just components, it's everything. The only way to rename the component from the UI is to delete it and recreate it.
> 
> To actually just rename it requires you to modify it manually on the filesystem and handle the database migration using an undocumented custom migration script system.
> 
> Adding as a feature request, not a bug.

Happened to me as well, kind of misleading

**Comment by oriooctopus** [comment] 2022-03-25 11:32
> it requires you to modify it manually on the filesystem and handle the database migration using an undocumented custom migration script system

@derrickmehaffy can you elaborate on what that migration script system might be?

**Comment by derrickmehaffy** [comment] 2022-03-28 20:42
> > it requires you to modify it manually on the filesystem and handle the database migration using an undocumented custom migration script system
> 
> @derrickmehaffy can you elaborate on what that migration script system might be?

https://github.com/derrickmehaffy/strapi-example-v4-custom-db

**Comment by derrickmehaffy** [comment] 2022-05-06 16:01
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/gracefully-handle-renaming-of-content-types-and-fields-in-the-ctb
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!

**Closed by derrickmehaffy** 2022-05-06 16:01 UTC
Labels: issue: feature request, source: core:content-type-builder
