### ISSUE TITLE
[CM] Date picker issue

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20464] opened 2024-06-07 08:33 UTC
### Required System information

Node.js version: v20.9.0
Strapi version: v5.0.0-beta.9
Operating system: Windows WSL

### Describe the bug

It is impossible to select the right date in a Date field (format date), right after selected, there's one day prior to the selected date, then when you click outside the Date field, there's one day prior to the selected date again, making it impossible to have the wanted date (or by selecting a date 2 days after the date you want ^^)

### Steps to reproduce the behavior

https://app.dashcam.io/replay/6662c417628a620077d12f21?share=2KBfrZY2L31VJ0Jha2eKLA

1.  Create a CT with Date field, format date
2. Go to CM
3. Create an entry for this CT
4. Try to fill in the date field with the date of your choice
5. Click outside
6. Save

I checked with Date + Time format : it works properly (no date changing) but there is a weird behaviour when you update the Date field : first the time is erased (I think it shouldn't), and second when you save, the previous date is briefly displayed.

### Expected behavior

When you select a date on the Date field, it remains the same date !
When you select a date and a time, then erase the date, time is not erased.

**Comment by joshuaellis** [comment] 2024-06-07 11:49
duplicate of #20321

**Closed by joshuaellis** 2024-06-07 11:49 UTC
Labels: version: 5
