### ISSUE TITLE
development server restart for no reason and no error-log

### ISSUE THREAD

**Issue by tudislei** [strapi/strapi#9288] opened 2021-02-02 03:31 UTC
Sorry that I can't reproduce this bug , but it happened twice already.
It only happens during a function that calls the 'google-spreadsheet' module is fired ,
May I know if there is any similar known bug and what may causes it?
Thank you so much.

There is no error-log , just seems like a 'normal' restart 
```
> strapi develop

 Project information

[90m┌────────────────────[39m[90m┬──────────────────────────────────────────────────┐[39m
[90m│[39m Time               [90m│[39m ...… [90m│[39m
[90m│[39m Launched in        [90m│[39m 7165 ms                                          [90m│[39m
[90m│[39m Environment        [90m│[39m development                                      [90m│[39m
[90m│[39m Process PID        [90m│[39m .........                                          [90m│[39m
[90m│[39m Version            [90m│[39m 3.0.0 (node v14.14.0)                            [90m│[39m
[90m└────────────────────[39m[90m┴──────────────────────────────────────────────────┘[39m

 Actions available

Welcome back!
To manage your project 🚀, go to the administration panel at:
http://localhost:[port]/admin

To access the server ⚡️, go to:
http://localhost:[port]

```

- Node.js version: 14.14.0
- NPM version: 6.14.8
- Strapi version: 3.0.0
- Database: postgresql
- Operating system: CentOS Linux release 8.2.2004 (Core)

**Comment by derrickmehaffy** [comment] 2021-02-02 03:47
> It only happens during a function that calls the 'google-spreadsheet' module is fired ,

Is this file calling a spreadsheet and downloading a file into the project directory somewhere? If so the development environment will auto-restart if a new file is detected.

**Comment by tudislei** [comment] 2021-02-02 03:48
> > It only happens during a function that calls the 'google-spreadsheet' module is fired ,
> 
> Is this file calling a spreadsheet and downloading a file into the project directory somewhere? If so the development environment will auto-restart if a new file is detected.

Hello . No , I am sure these are not the reason.

**Comment by derrickmehaffy** [comment] 2021-02-02 15:17
> [2021-02-02T03:26:12.601Z] info File changed: /usr/....../....js

What is this file?

**Comment by tudislei** [comment] 2021-02-02 15:18
> > [2021-02-02T03:26:12.601Z] info File changed: /usr/....../....js
> 
> What is this file?

no , I used that for an example. 

Was trying to say such log doesn't exist in this case.

**Comment by derrickmehaffy** [comment] 2021-02-02 21:06
I've tried to reproduce this but am unable to and need more information.

**Comment by andriichern** [comment] 2021-02-03 07:57
Not sure this is related to this specific issue, but I am not able to run `strapi develop` due to restarting.

My system:
 - OS: Linux Manjaro
 - Node: v14.15.3,
 - Strapi: v3.4.5 Community,
 - DB: Mongo 4.4.1.

Description of an issue: Every time I run `strapi develop` CLI command locally on my computer Strapi can not start. It seems that it automatically creates and edits files inside `data` folder, then it recognizes file changes due to watching mechanism and restarts.

My mongo is run inside Docker container and it works as expected.

I tried to add `data` folder to `watchIgnoreFiles` but it does not help. My teammate also can not run strapi this way, he is on Ubuntu 20.

Interesting fact: although I can not run `strapi develop` locally it works when I run it with Docker container. But this terribly uncomfortable to develop Strapi through container as I have to connect to the container and copy needed files from console. Moreover I have to manually restart container every time I change my logic inside model/controller/service files.

![console](https://user-images.githubusercontent.com/35733665/106715799-392cb400-6606-11eb-9680-b9a4a180c839.jpg)

Any ideas?

**Comment by derrickmehaffy** [comment] 2021-04-15 18:17
closing as no new information

**Closed by derrickmehaffy** 2021-04-15 18:17 UTC
Labels: status: can't reproduce
