### ISSUE TITLE
Enumeration component doesn't allow true/false values

### ISSUE THREAD

**Issue by alebog** [strapi/strapi#13013] opened 2022-03-30 17:32 UTC
### Required System information

- Node.js version: 14.19.1
- NPM version: 7.11.1
- Strapi version: 4.16
- Database: postgres
- Operating system: windows 11

### Describe the bug

When you insert an enumeration component and you set as possible values 'true' and 'false' strapi crashes
### Steps to reproduce the behavior

1. Go to 'Content-type builder'
2. Click on 'create new component'
3. Choose a display name, a category and an icon and click "continue"
4. Click on Enumeration
5. Insert a Name and in Values insert 
     true
     false
6. Click on Finish
7. Click on Save
8. See the error: "The restart is taking longer than expected"

### Expected behavior

It should create an Enumeration component with values true and false

### Screenshots
![image](https://user-images.githubusercontent.com/3062899/160896231-328b2a8f-2642-49d2-be1e-333b5610d23a.png)

### Additional context

Console log:
[2022-03-30 18:57:44.965] debug: ⛔️ Server wasn't able to start properly.
[2022-03-30 18:57:44.967] error: Enum type ENUM_COMPONENTCHALLENGETRUEFALSEQUESTION_CORRECTANSWER cannot include value: true.

Enum type ENUM_COMPONENTCHALLENGETRUEFALSEQUESTION_CORRECTANSWER cannot include value: false.
Error: Enum type ENUM_COMPONENTCHALLENGETRUEFALSEQUESTION_CORRECTANSWER cannot include value: true.      

Enum type ENUM_COMPONENTCHALLENGETRUEFALSEQUESTION_CORRECTANSWER cannot include value: false.
    at assertValidSchema (C:\dev\strapi\node_modules\graphql\type\validate.js:69:11)
    at assertValidExecutionArguments (C:\dev\strapi\node_modules\graphql\execution\execute.js:150:35)    
    at executeImpl (C:\dev\strapi\node_modules\graphql\execution\execute.js:98:3)
    at Object.execute (C:\dev\strapi\node_modules\graphql\execution\execute.js:60:63)
    at Object.generateSchemaHash (C:\dev\strapi\node_modules\apollo-server-core\dist\utils\schemaHash.js:15:32)
    at ApolloServer.generateSchemaDerivedData (C:\dev\strapi\node_modules\apollo-server-core\dist\ApolloServer.js:320:41)
    at Object.schemaDerivedDataProvider (C:\dev\strapi\node_modules\apollo-server-core\dist\ApolloServer.js:139:65)
    at new SchemaManager (C:\dev\strapi\node_modules\apollo-server-core\dist\utils\schemaManager.js:22:21)
    at new ApolloServerBase (C:\dev\strapi\node_modules\apollo-server-core\dist\ApolloServer.js:137:32)  
    at new ApolloServer (C:\dev\strapi\node_modules\apollo-server-koa\dist\ApolloServer.js:20:1)
    at Object.module.exports [as bootstrap] (C:\dev\strapi\node_modules\@strapi\plugin-graphql\server\bootstrap.js:87:18)
    at Object.bootstrap (C:\dev\strapi\node_modules\@strapi\strapi\lib\core\domain\module\index.js:40:47)
    at Object.bootstrap (C:\dev\strapi\node_modules\@strapi\strapi\lib\core\registries\modules.js:28:19) 
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Strapi.runLifecyclesFunctions (C:\dev\strapi\node_modules\@strapi\strapi\lib\Strapi.js:468:5)
    at async Strapi.bootstrap (C:\dev\strapi\node_modules\@strapi\strapi\lib\Strapi.js:406:5)
PS C:\dev\strapi> npm run develop

> strapi@0.1.0 develop
> strapi develop

[2022-03-30 18:59:59.132] debug: ⛔️ Server wasn't able to start properly.
    at new ApolloServerBase (C:\dev\strapi\node_modules\apollo-server-core\dist\ApolloServer.js:137:32)      at new ApolloServer (C:\dev\strapi\node_modules\apollo-server-koa\dist\ApolloServer.js:20:1)
    at Object.module.exports [as bootstrap] (C:\dev\strapi\node_modules\@strapi\plugin-graphql\server\bootstrap.js:87:18)
    at Object.bootstrap (C:\dev\strapi\node_modules\@strapi\strapi\lib\core\domain\module\index.js:40:47)    at Object.bootstrap (C:\dev\strapi\node_modules\@strapi\strapi\lib\core\registries\modules.js:28:19) 
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Strapi.runLifecyclesFunctions (C:\dev\strapi\node_modules\@strapi\strapi\lib\Strapi.js:468:5)
    at async Strapi.bootstrap (C:\dev\strapi\node_modules\@strapi\strapi\lib\Strapi.js:406:5)

**Comment by derrickmehaffy** [comment] 2022-04-11 19:39
The issue is valid but we can't fix this within GraphQL thus we just need to add a check in the CTB to see if a value provided is true or false and throw a warning to the user.

These are GraphQL internal type checks we can't bypass without getting rid of enums in the graphql schema which we won't do (we just added them back a few versions ago)

**Comment by derrickmehaffy** [comment] 2022-04-18 17:24
Closing as we won't fix this

**Closed by derrickmehaffy** 2022-04-18 17:24 UTC
Labels: issue: bug, severity: low, status: confirmed, source: plugin:graphql, status: will not fix
