### ISSUE TITLE
Error: Component in a collection does not show up in the JSON

### ISSUE THREAD

**Issue by Kinbaum** [strapi/strapi#11542] opened 2021-11-10 12:49 UTC
# v4 Beta Reproduction

I'm trying out the new v4 beta and have come across an issue. When you have a component type in the model of a collection, the data does not show up. 

To reproduce this:

1. Create a card collection with the model below
1. Create a link component with the model below
1. Enable `find` and `findOne` permission on the card collection 
1. Populate the card with some information 
1. Visit http://localhost:1337/api/cards

<details>
    <summary>Card Collection</summary>

```json
{
    "kind": "collectionType",
    "collectionName": "cards",
    "info": {
        "singularName": "card",
        "pluralName": "cards",
        "displayName": "Card"
    },
    "options": {
        "draftAndPublish": true
    },
    "pluginOptions": {
        "i18n": {
            "localized": true
        }
    },
    "attributes": {
        "title": {
            "pluginOptions": {
                "i18n": {
                    "localized": true
                }
            },
            "type": "string"
        },
        "description": {
            "pluginOptions": {
                "i18n": {
                    "localized": true
                }
            },
            "type": "text"
        },
        "ctas": {
            "type": "component",
            "repeatable": true,
            "pluginOptions": {
                "i18n": {
                    "localized": true
                }
            },
            "component": "generic.link"
        }
    }
}
```
</details>

<details>
    <summary>Link Component</summary>

```json
{
    "collectionName": "components_generic_links",
    "info": {
        "displayName": "Link",
        "icon": "link"
    },
    "options": {},
    "attributes": {
        "children": {
            "type": "string"
        },
        "href": {
            "type": "string"
        },
        "target": {
            "type": "enumeration",
            "enum": [
                "_blank",
                "_self",
                "_parent",
                "_top"
            ]
        }
    }
}
```
</details>

### Expected behavior

I would expect to see the all of the data show up  in the JSON when I visit http://localhost:1337/api/cards. However I do not see the `ctas` key in my JSON response. Here is the output:

```json
{
    "data": [
        {
            "id": 1,
            "attributes": {
                "title": "Testing",
                "description": "Lorem ipsum",
                "createdAt": "2021-11-10T12:35:21.977Z",
                "updatedAt": "2021-11-10T12:38:45.189Z",
                "publishedAt": "2021-11-10T12:35:32.484Z",
                "locale": "en"
            }
        }
    ],
    "meta": {
        "pagination": {
            "page": 1,
            "pageSize": 25,
            "pageCount": 1,
            "total": 1
        }
    }
}
```

# v3 Similar Issue

I have a similar problem in v3, but it's one that deals with dynamic zones. Have a look at the following models:

<details>
    <summary>Member Collection</summary>

```json
{
    "kind": "collectionType",
    "collectionName": "members",
    "info": {
        "name": "Member",
        "description": ""
    },
    "options": {
        "increments": true,
        "timestamps": true,
        "draftAndPublish": true
    },
    "pluginOptions": {
        "i18n": {
            "localized": true
        }
    },
    "attributes": {
        "slug": {
            "pluginOptions": {
                "i18n": {
                    "localized": true
                }
            },
            "type": "string"
        },
        "zone": {
            "pluginOptions": {
                "i18n": {
                    "localized": true
                }
            },
            "type": "dynamiczone",
            "components": [
                "generic.cards"
            ]
        }
    }
}
```
</details>

<details>
    <summary>Card Component</summary>

```json
{
    "collectionName": "components_generic_cards",
    "info": {
        "name": "Cards",
        "icon": "th-list",
        "description": ""
    },
    "options": {},
    "attributes": {
        "header": {
            "type": "string"
        },
        "cards": {
            "collection": "card"
        }
    }
}
```
</details>

<details>
    <summary>Card Collection</summary>

```json
{
    "kind": "collectionType",
    "collectionName": "cards",
    "info": {
        "name": "Card",
        "description": ""
    },
    "options": {
        "increments": true,
        "timestamps": true,
        "draftAndPublish": true
    },
    "pluginOptions": {
        "i18n": {
            "localized": true
        }
    },
    "attributes": {
        "title": {
            "pluginOptions": {
                "i18n": {
                    "localized": true
                }
            },
            "type": "string"
        },
        "description": {
            "pluginOptions": {
                "i18n": {
                    "localized": true
                }
            },
            "type": "text"
        },
        "ctas": {
            "type": "component",
            "repeatable": true,
            "pluginOptions": {
                "i18n": {
                    "localized": true
                }
            },
            "component": "generic.link"
        }
    }
}
```
</details>

<details>
    <summary>Link Component</summary>

```json
{
    "collectionName": "components_generic_links",
    "info": {
        "name": "Link",
        "icon": "link",
        "description": ""
    },
    "options": {},
    "attributes": {
        "children": {
            "type": "string",
            "required": true
        },
        "href": {
            "type": "string",
            "required": true
        },
        "target": {
            "type": "enumeration",
            "enum": [
                "_blank",
                "_self",
                "_parent",
                "_top"
            ]
        }
    }
}  
```
</details>

After I fill out some information in the both the card collection and member collection, then visit http://localhost:1337/members I do not see the `ctas` key below the `cards` in my JSON response. Here is the output:

```json
[
    {
        "id": 1,
        "slug": "/member",
        "locale": "en",
        "published_at": "2021-11-09T21:25:51.000Z",
        "created_at": "2021-11-09T19:12:22.000Z",
        "updated_at": "2021-11-09T21:25:52.000Z",
        "zone": [
            {
                "__component": "generic.cards",
                "id": 5,
                "header": "My Header",
                "cards": [
                    {
                        "id": 3,
                        "title": "Testing",
                        "description": "Lorem ipsum",
                        "locale": "en",
                        "published_at": "2021-11-08T20:07:26.000Z",
                        "created_at": "2021-11-08T13:50:14.000Z",
                        "updated_at": "2021-11-09T23:45:39.000Z"
                    }
                ]
            }
        ],
        "localizations": []
    }
]
```

### System

- Node.js version: v14.16.1
- NPM version: v6.14.12
- Strapi version: v4.0.0-beta.12 && v3.6.8
- Database: v4 (sqlite3) v3 (MySQL)
- Operating system: Mac

**Comment by LucaNerlich** [comment] 2021-11-10 13:04
Please follow the bug report template and provide some kind of reproduction steps. Thanks :)

**Comment by LucaNerlich** [comment] 2021-11-10 13:19
Have you tried `http://localhost:1337/api/cards?populate=*`?

**Comment by Kinbaum** [comment] 2021-11-10 13:24
Awesome, that was an easy fix for the v4 case. But that does not work in the v3 scenario I described. This is the response I get when trying to do http://localhost:1337/members?populate=*

```json
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Your filters contain a field 'populate' that doesn't appear on your model definition nor its relations"
}
```

**Comment by LucaNerlich** [comment] 2021-11-10 13:26
?populate is a new addition for v4, since all content population is off by default - (which I disagree with btw, it does not feel 'natural' and by experience, other REST Apis do not work like this).

For v3 however, it should work. Did you allow the public role to 'find'?

![image](https://user-images.githubusercontent.com/5942270/141121442-e686d2ce-af21-4237-b7ee-10dd7c477435.png)

**Comment by Kinbaum** [comment] 2021-11-10 13:30
Yes I did, and I agree with you as well. Even though I have `find` and `findOne` enabled throughout, the data doesn't show up in v3. If I access the cards directly via [http://localhost:1337/cards](http://localhost:1337/cards), then I can see the `ctas` key show up. 

But when I access [http://localhost:1337/members](http://localhost:1337/members), which has a `dynamic zone` that includes a `card component`, with a relation to the `cards collection`, the `ctas` key does not show up.

**Comment by Kinbaum** [comment] 2021-11-10 13:38
It's strange. If I use the GraphQL query below, then I can see the `ctas` being returned in the JSON. But accessing the REST endpoint, or doing a simple `console.log` of the entity in the member controller will show the data with the `ctas` key omitted.

```gql
{
    members {
        zone {
            ... on ComponentGenericCards {
                cards {
                    ctas {
                        children
                        href
                        target
                    }
                }
            }
        }
    }
}
```

**Comment by LucaNerlich** [comment] 2021-11-10 13:42
ive only ever queried data via graphql aswell. No clue here, sorry.

**Comment by Kinbaum** [comment] 2021-11-10 14:13
Going back to the v4 example, if I try to use [http://localhost:1337/api/members?populate=*](http://localhost:1337/api/members?populate=*) that also seems to have limits in depth. Recreated my v3 example in the beta. The component within the dynamic zone does not populate it's information

```json
{
    "data": [
        {
            "id": 1,
            "attributes": {
                "createdAt": "2021-11-10T12:36:07.189Z",
                "updatedAt": "2021-11-10T12:36:08.830Z",
                "publishedAt": "2021-11-10T12:36:08.827Z",
                "locale": "en",
                "zone": [
                    {
                        "id": 1,
                        "__component": "generic.card"
                    }
                ],
                "localizations": {
                    "data": []
                }
            }
        }
    ],
    "meta": {
        "pagination": {
            "page": 1,
            "pageSize": 25,
            "pageCount": 1,
            "total": 1
        }
    }
}
```

**Comment by derrickmehaffy** [comment] 2021-11-10 20:27
As this bug report was created for v4, what you are describing is intended in line with the new population logic: 

(this says relations but it applies to components too): https://docs-next.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#relations-population

v3 has no population logic at the query level (other than with GraphQL) unless you modify the services:  https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#collection-type-2

> populate (array): the data to populate ["author", "author.name", "comment", "comment.content"]

But component and nested component population is a problem in v3 and likely not something we are gonna fix since v4 is just around the corner.

---

The v3 side of this is more so a duplicate of: https://github.com/strapi/strapi/issues/7454
For the v4 side as I mentioned this is intended so gonna set this as closed.

**Closed by derrickmehaffy** 2021-11-10 20:27 UTC

**Comment by Kinbaum** [comment] 2021-11-10 21:31
@derrickmehaffy thank you for the clarification

**Comment by tomservice1030** [comment] 2022-02-26 07:26
> Yes I did, and I agree with you as well. Even though I have `find` and `findOne` enabled throughout, the data doesn't show up in v3. If I access the cards directly via http://localhost:1337/cards, then I can see the `ctas` key show up.
> 
> But when I access http://localhost:1337/members, which has a `dynamic zone` that includes a `card component`, with a relation to the `cards collection`, the `ctas` key does not show up.

I have a same isssue now

**Comment by Badlapje** [comment] 2025-05-12 14:27
FYi for those who run into this: you need to have saved the single type at least once before the api gives a result.  Until then it returns a 404 not found 🤷
