### ISSUE TITLE
Localization: Flags and languages are a bad couple

### ISSUE THREAD

**Issue by vicesalles** [strapi/strapi#8561] opened 2020-11-03 13:27 UTC
# Summary

I'd like the flags to be removed from the locale dropdown menu as they are misleading. 

Mixing flags and languages is a bad idea. I'd like you to remove the flags from the locale dropdown menu. It's colorful and even cute but useless and misleading. In Belgium for instance, they speak dutch and french but nor the France or the Netherlands flags has nothing to do with them. Why an austrian needs the german flag? Further This dropdown is bassed on flags-icon-css library that has some hilarious conflicts between the language code ISO-639 and his own idea of flag codes.

This colorful addon to the dropdown menu is misleading.

### Why is it needed?

The current flags addon in the dropdown menu is colorful but useless and misleading.

### Suggested solution(s)

Remove the flags.

**Comment by MattieBelt** [comment] 2020-11-04 09:58
Duplicate of #7102

@vicesalles could you specify you Strapi version, because flags aren't shown in `v3.1.5` or above.

**Comment by derrickmehaffy** [comment] 2020-11-04 16:23
Thank you @MattieBelt Marking as closed as your right they were removed (I tried finding that issue, didn't even check the PRs)

**Closed by derrickmehaffy** 2020-11-04 16:23 UTC
Labels: status: duplicate

**Comment by vicesalles** [comment] 2020-11-04 17:22
> Duplicate of #7102
> 
> @vicesalles could you specify you Strapi version, because flags aren't shown in `v3.1.5` or above.

3.1.3 , thanks guys
