### ISSUE TITLE
Null filter returns empty array instead of skipping value.

### ISSUE THREAD

**Issue by Onxi95** [strapi/strapi#10390] opened 2021-05-26 18:18 UTC
### Description

Referring to https://github.com/strapi/strapi/pull/3562.
I wanted to fetch only those posts, that have "category" set.
There is a filter called "_null" in docs: https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#query-api

Unfortunately, it seems that it does not work with my setup. Query properly sorts results but also returns records with empty "categories" array.
 

### Steps to reproduce the behavior

1. Install GraphQL Plugin

2. Create a new collection named "post" with fields:

![image](https://user-images.githubusercontent.com/48386403/119708036-24498a00-be5c-11eb-9317-206d6b8ed147.png)

3. Create a new collection named "category" with fields:

![image](https://user-images.githubusercontent.com/48386403/119708304-50fda180-be5c-11eb-8138-6349a03d793e.png)

4. Relation setup:

![image](https://user-images.githubusercontent.com/48386403/119708581-9621d380-be5c-11eb-8cb7-a5f9b53e7845.png)

5. Create some dummy data

6. Go to [http://localhost:1337/graphql](url) and run a query:

```graphql
query {
	posts(start: 0,limit: 9, 
	sort: "created_at:DESC", 
	where: {categories_null: false}) {
    title,
    categories(where: {name_contains: "cat1"}) {
      name
    },
    date,
  }
}
```

replacing "cat1" by a category name.

### Expected behavior

Query returns only these values that have a valid category name (in that case "cat1") without unnecessary records with empty "categories" arrays. 

### Screenshots

my first approach:
![image](https://user-images.githubusercontent.com/48386403/119709554-a25a6080-be5d-11eb-8ca6-b01b337d6d6a.png)

my second approach (same result):
![image](https://user-images.githubusercontent.com/48386403/119709642-bb631180-be5d-11eb-9c96-63af27370375.png)

### System

- Node.js version: v12.18.3
- Yarn version: 1.22.5
- Strapi version: 3.6.2
- Database: MySQL
- Operating system: GNU/Linux (Manjaro)

Useful dependencies:

 

-  "knex": "0.21.18",

 - "mysql": "2.18.1",
-  "strapi": "3.6.2",
 - "strapi-admin": "3.6.2",
 - "strapi-connector-bookshelf": "3.6.2",

**Comment by ssoftwares** [comment] 2021-08-30 08:32
Please resolve this as soon as possible  , its a crucial feature for strapi without which strapi can't be called a cms.

**Comment by Onxi95** [comment] 2021-08-30 08:42
@ssoftwares I found a workaround in GraphQL, I need to change my query a bit, unfortunately I haven't used REST in this project so it's hard for me to help with this topic.


```
query Posts($start: Int, $category: String) {
  posts(
    where: { categories: { name_null: false, name_contains: $category } }
    start: $start
    limit: 9
    sort: "created_at:DESC"
  ) {
      title
      date
      slug
      image {
          formats
      }
  }
}
```

Even though the code above works, it would be nice if the filters on the screenshots above would also work :)

**Comment by ssoftwares** [comment] 2021-08-30 15:10
@Onxi95 what about rest api?

**Comment by derrickmehaffy** [comment] 2021-08-30 21:41
> @Onxi95 what about rest api?

Yes this also impacts the REST layer as it's not a bug with just GraphQL but is a problem at the query level. See my comment on the duplicate issue here: https://github.com/strapi/strapi/issues/10813#issuecomment-908719221

**Comment by derrickmehaffy** [comment] 2021-08-30 21:43
Closing this in favor of https://github.com/strapi/strapi/issues/5414

**Closed by derrickmehaffy** 2021-08-30 21:43 UTC
Labels: type: bug, severity: low, status: confirmed, source: core:database, source: plugin:graphql
