### ISSUE TITLE
Disable “Draft and publish” confirmation modal doesn’t close automatically when clicking “Confirm”

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#20510] opened 2024-06-13 14:09 UTC
Spotted by Simone during the Releases Blitz session

https://github.com/strapi/strapi/assets/47896922/45c6eeea-f317-4a11-ab76-a9dcb3b95d68

**Comment by simotae14** [comment] 2024-07-04 13:31
I am gonna close it because the issue is already fixed in the v5 release candidate

**Closed by simotae14** 2024-07-04 13:31 UTC
