### ISSUE TITLE
Filter by locale in entity service API

### ISSUE THREAD

**Issue by Charlesdoiron** [strapi/strapi#13507] opened 2022-06-08 14:56 UTC
Hello !
I'm not sure it's a bug, but i can't find anything on it on the documention ...

I’m making a custom graphQl query.
I have create a controller to get my contentType and make some logic on it.
Everything work.

I use `strapi.entityService.findMany` with a filter (slug coming from the param).
I want to find the french version of my contentType but i don’t manage.
I get only the contentType with default language data.

Ps: The two contentType have the same slug

Here is my code

```
 const menus = await strapi.entityService.findMany("api::menu.menu", {
          filters: {
            slug: {
              $eq: param.slug,
            },
          },
          populate: [  ...  ],
        });
```
        
I’v tried :
```

 const menus = await strapi.entityService.findMany("api::menu.menu", {
          filters: {
            locale:"fr",   // or //  _locale:"fr
            slug: {
              $eq: param.slug,
            },
          },
          populate: [],
        });
```
But it’s not the good solution : (
Is there a way to filter by locale using the entity service ?
Thanks a lot !

**Comment by derrickmehaffy** [comment] 2022-06-08 15:04
Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Comment by Charlesdoiron** [comment] 2022-06-08 15:06
Hi @derrickmehaffy , i'm not sure if it's a question or a bug, so i post it here and on the forum.
Thanks

**Comment by Charlesdoiron** [comment] 2022-06-17 11:17
It work like this ...

```
 const menus = await strapi.entityService.findMany("api::menu.menu", {
          filters: {
            slug: {
              $eq: param.slug,
            },
          },
         locale:"fr", 
          populate: [],
        });
```

**Comment by goodpixels** [comment] 2022-07-23 16:18
I think I have the same problem - I am using entity service API to pre-populate some fields for my request, but this causes the locale query param to be completely ignored. None of the above solutions worked. The following code gives me always the default locale results:

`async findOne(ctx) {
    // TODO This returns all data ignoring the locale!
    ctx.query = {
      ...ctx.query,
      fields: ["publishedAt"],
      populate: "*"
    };
    return super.findOne(ctx);
  },`
  
The endpoint is being called like so: `http://localhost:1337/api/articles/16?locale=pl-PL`, but instead of a localised version, I get the default english locale one.

**Comment by Jae-Kae** [comment] 2022-08-23 19:30
I'm having the same issue

**Comment by derrickmehaffy** [comment] 2022-08-29 18:28
Marking as confirmed due to number of users and moving to medium as no good workaround exists

**Comment by Marc-Roig** [comment] 2022-10-19 13:45
As for the first question I think it has been answered. The locale query parameter has to at the root of query params:
```
 const menus = await strapi.entityService.findMany("api::menu.menu", {
          filters: {
            slug: {
              $eq: param.slug,
            },
          },
         locale:"fr",  <=== here
          populate: [],
        });
```

For the second one, It is the intended behavior to omit the locale or any other filter when asking for an id.

> Now I know that localized versions are just separate entries in the database, but I think there should be an option to enforce stricter locale checking then interacting with the API.

As you correctly guessed, the localized versions are different entities in the database. As you are asking for an specific id, the service will only return the one you are asking.

You are right we should enforce a stricter locale checking. And this is exactly what we will be working on .
**In future versions, localized versions will share the same `document_id` , so it will be possible to ask for an entity by id filtering by the locale.**


I am closing this issue again as it is more of a feature request (and we are working on it)

**Closed by Marc-Roig** 2022-10-19 13:45 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: plugin:i18n
