### ISSUE TITLE
Switching to required field if field exists with no value stops server restart

### ISSUE THREAD

**Issue by samOpenforce** [strapi/strapi#6861] opened 2020-06-30 08:30 UTC
**Describe the bug**
Enabling 'required field' if field exists but has no value stops server restart

**Steps to reproduce the behavior**

1. Create collection-type
2. Add field eg. (not required)
3. Create content for collection type
4. Do not add value to field
5. Edit collection-type
6. Make field required
7. Server attempts restart and fails

**Expected behavior**
Warning that fields may not contain values? Enabling 'required field' disabled if null values present?

**Screenshots**
Not applicable

**Code snippets**
```
[2020-06-29T14:05:24.415Z] debug ⛔ Server wasn't able to start properly.
[2020-06-29T14:05:24.416Z] error error: column "secondary_header" contains null values
at Parser.parseErrorMessage (/srv/app/node_modules/pg-protocol/dist/parser.js:241:15)
at Parser.handlePacket (/srv/app/node_modules/pg-protocol/dist/parser.js:89:29)
at Parser.parse (/srv/app/node_modules/pg-protocol/dist/parser.js:41:38)
at Socket.<anonymous> (/srv/app/node_modules/pg-protocol/dist/index.js:8:42)
at Socket.emit (events.js:315:20)
at addChunk (_stream_readable.js:295:12)
at readableAddChunk (_stream_readable.js:271:9)
at Socket.Readable.push (_stream_readable.js:212:10)
at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
From previous event:
at Client_PG._query (/srv/app/node_modules/knex/lib/dialects/postgres/index.js:234:12)
at Client_PG.query (/srv/app/node_modules/knex/lib/client.js:158:17)
at Runner.query (/srv/app/node_modules/knex/lib/runner.js:135:36)
at Runner.queryArray (/srv/app/node_modules/knex/lib/runner.js:224:14)
at /srv/app/node_modules/knex/lib/runner.js:37:25
From previous event:
at Runner.run (/srv/app/node_modules/knex/lib/runner.js:25:16)
at SchemaBuilder.Target.then (/srv/app/node_modules/knex/lib/interface.js:14:43)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**System**
Official Strapi Docker container

**Comment by lauriejim** [comment] 2020-07-07 09:39
Hello this is a duplicate of this issue - https://github.com/strapi/strapi/issues/6292

**Closed by lauriejim** 2020-07-07 09:39 UTC
