### ISSUE TITLE
Long text fields are uneditable after upgrading to 4.10.6

### ISSUE THREAD

**Issue by eruiz-impact** [strapi/strapi#16830] opened 2023-05-24 20:33 UTC
### Required System information

- Node.js version: 16.19.1
- NPM version: 8.19.3
- Strapi version: 4.10.6
- Database: Postgres
- Operating system: macOS Venture
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After upgrading to 4.10.6, all long text fields are uneditable.

**Comment by gu-stav** [comment] 2023-05-25 11:22
I'm sorry for the bug - I didn't think it would do that :/ We will create a new DS release this afternoon (1.7.8) which will fix the styling regression introduced. After that we well update the monorepo and I'll provide you an experimental release you can use until next Wednesday (which is when 4.10.7 will be released).

In case it turns out many users are running into that problem we can also consider to do 4.10.7 a bit earlier than planned.

Hope that works for you?

**Comment by Shrikantpaliwal** [comment] 2023-05-25 16:15
Yes, Please My team is facing the same issue with long text fields - link to forum- https://forum.strapi.io/t/text-description-field-is-not-taking-input-in-production-for-some-reason-locally-everything-works-in-both-development-and-production-configuration/28705

**Comment by gustbul** [comment] 2023-05-25 19:32
This has seriously affected normal use.

**Comment by gustbul** [comment] 2023-05-25 19:33
This has seriously affected normal use. I hope to post it soon. @gu-stav

**Comment by pradeepvish1213** [comment] 2023-05-26 02:43
> I'm sorry for the bug - I didn't think it would do that :/ We will create a new DS release this afternoon (1.7.8) which will fix the styling regression introduced. After that we well update the monorepo and I'll provide you an experimental release you can use until next Wednesday (which is when 4.10.7 will be released).
> 
> In case it turns out many users are running into that problem we can also consider to do 4.10.7 a bit earlier than planned.
> 
> Hope that works for you?

Can you please provide any experimental release?

**Comment by GregorSondermeier** [comment] 2023-05-26 07:32
Which Strapi version did this bug first appear in? v4.10.6 or earlier?

**Comment by marcowuethrich** [comment] 2023-05-26 07:37
> Which Strapi version did this bug first appear in? v4.10.6 or earlier?

Yes in 4.10.6, 4.10.5 works for me.

**Comment by gu-stav** [comment] 2023-05-26 07:44
I will link you an experimental release with the fix later today. Again: apologies for the bug :/

**Comment by jdbenn** [comment] 2023-05-26 16:10
the experimental release didd not help.  I am still unable to edit textarea inputs on the admin app in both dev and production.

```json
"scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {
    "yarn-upgrade-all": "^0.7.2"
  },
  "dependencies": {
    "@strapi/admin": "0.0.0-experimental.943497a7d92d1d147604c631ce5c58737af841da",
    "@strapi/plugin-graphql": "4.10.6",
    "@strapi/plugin-i18n": "4.10.6",
    "@strapi/plugin-users-permissions": "4.10.6",
    "@strapi/strapi": "4.10.6",
    "mysql": "2.18.1",
    "strapi-provider-upload-aws-s3-plus-cdn": "4.0.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "34ddde67-df53-4b44-8ed4-4e6eb4b723d5"
  },
  "engines": {
    "node": ">=14.19.1 <=18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by eruiz-impact** [comment] 2023-05-26 16:12
Downgrading to 4.10.5 is a temp work around until 4.10.7 is released next week.

**Comment by ifightcrime** [comment] 2023-05-26 17:02
> the experimental release did not help. I am still unable to edit textarea inputs on the admin app in both dev and production.
> 
> ```json
> "scripts": {
>     "develop": "strapi develop",
>     "start": "strapi start",
>     "build": "strapi build",
>     "strapi": "strapi"
>   },
>   "devDependencies": {
>     "yarn-upgrade-all": "^0.7.2"
>   },
>   "dependencies": {
>     "@strapi/admin": "0.0.0-experimental.943497a7d92d1d147604c631ce5c58737af841da",
>     "@strapi/plugin-graphql": "4.10.6",
>     "@strapi/plugin-i18n": "4.10.6",
>     "@strapi/plugin-users-permissions": "4.10.6",
>     "@strapi/strapi": "4.10.6",
>     "mysql": "2.18.1",
>     "strapi-provider-upload-aws-s3-plus-cdn": "4.0.0"
>   },
>   "author": {
>     "name": "A Strapi developer"
>   },
>   "strapi": {
>     "uuid": "34ddde67-df53-4b44-8ed4-4e6eb4b723d5"
>   },
>   "engines": {
>     "node": ">=14.19.1 <=18.x.x",
>     "npm": ">=6.0.0"
>   }
> ```

@jdbenn see my [quick fix above](https://github.com/strapi/strapi/issues/16830#issuecomment-1562116181). All you have to do is downgrade strapi-design.

**Comment by IlirEdis** [comment] 2023-05-29 12:26
> I'm sorry for the bug - I didn't think it would do that :/ We will create a new DS release this afternoon (1.7.8) which will fix the styling regression introduced. After that we well update the monorepo and I'll provide you an experimental release you can use until next Wednesday (which is when 4.10.7 will be released).
> 
> In case it turns out many users are running into that problem we can also consider to do 4.10.7 a bit earlier than planned.
> 
> Hope that works for you?

Same issue here after updating to 4.10.6 . Please do 4.10.7

**Comment by GregorSondermeier** [comment] 2023-05-30 12:55
> I'm sorry for the bug - I didn't think it would do that :/

We're all just human and shit can and will happen.

I mentioned this before on the Discourse and in the Forum, I will mention it again: It would be great if Strapi could stick to [semantic versioning](https://semver.org/). Use patch updates to fix bugs only. It's totally unexpected to include a under-the-hood-refactoring in a patch update. Why not wait for v4.11.0 to include the refactoring? As a developer working with Strapi almost on a daily basis I'm **very** nervous for every Strapi dependency upgrade given Strapi's track record for breaking things. Mostly unintentional, but still.

**Comment by hrenaud** [comment] 2023-05-31 16:00
Hello,

it's 05/31, the bug was labeled as such on 05/24. It's blocking contributions and there may be workarounds, but why on earth hasn't the buggy version been removed from NPM and why aren't you talking about it in the Discord announcement channel? We all make mistakes, but it would be cool, not necessarily to fix them, but at least to inform people and prevent them from installing the buggy version.

**Comment by gu-stav** [comment] 2023-05-31 16:12
Hello. `strapi@4.10.7` was released today, which contains a fix for the issue.

**Closed by gu-stav** 2023-05-31 16:12 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:helper-plugin

**Comment by aamuhammadi** [comment] 2023-05-31 22:17
Experiencing the same issue in version 4.10.7, any updates or workarounds available?

**Comment by GregorSondermeier** [comment] 2023-06-01 04:54
> Experiencing the same issue in version 4.10.7, any updates or workarounds available?

Did you run `strapi build` after having upgraded?

Otherwise the workaround is downgrading to v4.10.5.

**Comment by gu-stav** [comment] 2023-06-01 06:37
Thanks @GregorSondermeier. `rm -rf .cache build && strapi build` will give you a clean build and the issue should be gone. I've setup a new instance yesterday and didn't see the problem any longer.

**Comment by aamuhammadi** [comment] 2023-06-01 11:08
Yes, it's working fine now after removing and rebuilding the .cache and build folders.

Thank you
