### ISSUE TITLE
after installation and build the strapi admin does not start

### ISSUE THREAD

**Issue by rafaumeu** [strapi/strapi#10944] opened 2021-09-12 23:36 UTC
### Bug description

after installation and build strapi exits run with exit 0
### Steps to reproduce the behavior

1. yarn create strapi-app my-project --quickstart 
2. wait instalation done
3. cd my-project 
4. yarn develop

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.17.6
- NPM version: 6.14.15
- Strapi version: 3.6.8
- Database: tests quick install 
- Operating System: Linux Mint 20.1
            Kernel: Linux 5.4.0-84-generic
      Architecture: x86-64

### Additional context

the strapi doesn't work with either docker or npm, same error

https://user-images.githubusercontent.com/30784471/133006279-576097d8-2fdd-4291-96e4-849cc4756e16.mp4

https://user-images.githubusercontent.com/30784471/133006290-28a937c9-ebdc-4230-8ec7-45430e87c0c8.mp4

docker

https://user-images.githubusercontent.com/30784471/133007042-95fceee8-c616-4f40-ac82-6c9a3991d066.mp4

docker-compose.yaml
```

version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data

```

**Comment by gastonfl** [comment] 2021-09-13 01:35
After update from 3.6.6 or 3.6.7 to 3.6.8 doesnt start, yarn install OK, yarn build --clean exit code 1, yarn develop start build same error exit code 1

**Comment by kasonde** [comment] 2021-09-13 13:16
Hi @rafaumeu, from the videos sent, this appears to be an issue with your environment and not Strapi per se. I have attempted to reproduce this on a fresh installation of Ubuntu 20.1 and the version of Node specified to no avail. Is there anymore information you'd like to share concerning this? Is this the first time you've run a Strapi project on this environment without any significant change to it?

**Comment by derrickmehaffy** [comment] 2021-09-13 17:42
This is a duplicate of: https://forum.strapi.io/t/strapi-dont-starts/11189

@rafaumeu can you try using bash and not zsh?

in your terminal use `/bin/bash` and try to use npx that way to create a fresh project. My best guess is your zsh config is blocking something.

**Comment by rafaumeu** [comment] 2021-09-13 21:30
> This is a duplicate of: https://forum.strapi.io/t/strapi-dont-starts/11189
> 
> @rafaumeu can you try using bash and not zsh?
> 
> in your terminal use `/bin/bash` and try to use npx that way to create a fresh project. My best guess is your zsh config is blocking something.

i tried npx on a virtual machine with a fresh installation, but the error was the same.

**Comment by rafaumeu** [comment] 2021-09-13 21:37
> Hi @rafaumeu, from the videos sent, this appears to be an issue with your environment and not Strapi per se. I have attempted to reproduce this on a fresh installation of Ubuntu 20.1 and the version of Node specified to no avail. Is there anymore information you'd like to share concerning this? Is this the first time you've run a Strapi project on this environment without any significant change to it?

if there is any relevant information of course to provide. Well the installation of node was done with npx. The yarn strapi has error code 1 not specified.
I ran the yarn info command
yarn info v1.22.11
error Received invalid response from npm.
Done in 1.12s.
It's been a few days since I've been trying to use the strapi for the first time, but without success.

**Comment by derrickmehaffy** [comment] 2021-09-14 18:01
> node test/create-test-app.js

Where did you get this command?

It appears like you are downloading our monorepo and trying to run it as an application. This repo is the source code of all of our packages, you can't just clone it and run it (that's not what it's designed for).

To run a strapi application to either need to use `npx create-strapi-app@latest your-project` or `yarn create strapi-app your-project`

I've tested this just today about 9 times on different virtual machines all in different clouds and on my host and I cannot reproduce your issue at all. Please try to do the follow and record a video of it using loom or something.

-  Open a terminal
- Type this: `/bin/bash` + enter key (this will temporarily change your terminal to using bash instead of zsh)
- Type this: `npx create-strapi-app@latest test-project --quickstart` + enter key
- Wait for it to start up the project

I have a strong feeling either your network is extremely slow or you have heavily modified your bash profile when you installed zsh and broke something as I've been using linux mint for about 6 years and Strapi about 4.5 years and I've never seen that issue you are hitting on my own systems or anyone elses.

**Comment by rafaumeu** [comment] 2021-09-16 00:06
> > node test/create-test-app.js
> 
> Where did you get this command?
Hi @derrickmehaffy A person in the node group suggested this test claiming that I had seen it in the documentation, I did it to see if it returned an error or something that could help with the problem, even without understanding.
 
> It appears like you are downloading our monorepo and trying to run it as an application. This repo is the source code of all of our packages, you can't just clone it and run it (that's not what it's designed for).
> 
> To run a strapi application to either need to use `npx create-strapi-app@latest your-project` or `yarn create strapi-app your-project`
> 
> I've tested this just today about 9 times on different virtual machines all in different clouds and on my host and I cannot reproduce your issue at all. Please try to do the follow and record a video of it using loom or something.
> 
> * Open a terminal
> * Type this: `/bin/bash` + enter key (this will temporarily change your terminal to using bash instead of zsh)
> * Type this: `npx create-strapi-app@latest test-project --quickstart` + enter key
> * Wait for it to start up the project
> 
> I have a strong feeling either your network is extremely slow or you have heavily modified your bash profile when you installed zsh and broke something as I've been using linux mint for about 6 years and Strapi about 4.5 years and I've never seen that issue you are hitting on my own systems or anyone elses.
Procedure performed follows the video of the attempt.

https://user-images.githubusercontent.com/30784471/133528634-233639ec-0f54-471d-9eec-f7c3c6f53f71.mp4

**Comment by derrickmehaffy** [comment] 2021-09-16 21:09
I'm downloading the latest linux mint iso and am going to spool up a virtual machine to test your post-install script to see if that is the root cause.

**Comment by derrickmehaffy** [comment] 2021-09-16 21:41
Alright, spun up a fresh Linux Mint 20.2 and ran your postinstall script (after troubleshooting some problems) and still couldn't reproduce the issue. There has to be something else going on here.

**Comment by rafaumeu** [comment] 2021-09-19 13:28
> Alright, spun up a fresh Linux Mint 20.2 and ran your postinstall script (after troubleshooting some problems) and still couldn't reproduce the issue. There has to be something else going on here.
> 
> At this point, I'd recommend booting into a live linux CD (like Linux mint) and install nvm + node 14 and test in that live environment to see if you still hit the same issue.

@derrickmehaffy procedure done. however it presents the same problem. But I tried to record with Kazam but it didn't save the video in the videos directory.

**Comment by derrickmehaffy** [comment] 2021-10-04 21:56
Honestly @rafaumeu I have no idea, I cannot under any environment reproduce what you are hitting.

**Comment by derrickmehaffy** [comment] 2021-11-01 16:32
@rafaumeu I'm sorry but there is just nothing else we can offer you:

Multiple people (myself and others on the team) have tested various configurations of different operating systems and hardware and none of us can reproduce what you are seeing. There is no question this is an environment issue and not a bug within Strapi. I'm out of ideas and thus going to set this issue as closed.

I'm sorry we can't be of more help.

**Closed by derrickmehaffy** 2021-11-01 16:32 UTC
Labels: status: can't reproduce
