### ISSUE TITLE
does not support multiple database

### ISSUE THREAD

**Issue by enginespot** [strapi/strapi#9057] opened 2021-01-07 14:20 UTC
### Describe the bug

does not support multiple database

### Steps to reproduce the behavior

1. install the latest strapi version with docker-compose https://strapi.io/documentation/developer-docs/latest/installation/docker.html

2.change database configuration
```
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'sqlite',
        filename: env('DATABASE_FILENAME', 'data/api.db'),
      },
      options: {
        useNullAsDefault: true,
      },
    },
    model: {
      connector: 'bookshelf',
      settings: {
        client: 'sqlite',
        filename: env('DATABASE_FILENAME', 'data/model.db'),
      },
      options: {
        useNullAsDefault: true,
      },
    }
  },
});
```
3. change some model setting
```
{
  "connection": "**model**",
  "kind": "collectionType",
  "collectionName": "devices",
  "info": {
    "name": "device",
    "description": ""
  }
....
}
```
4. there is error occur when create device
```
 error Error: SQLITE_ERROR: no such table: strapi_administrator
    at Client_SQLite3._query (./api/node_modules/knex/lib/dialects/sqlite3/index.js:99:12)
    at Client_SQLite3.query (./api/node_modules/knex/lib/client.js:158:17)
    at ./api/node_modules/knex/lib/transaction.js:331:24
From previous event:
    at Client_SQLite3.trxClient.query (./api/node_modules/knex/lib/transaction.js:326:12)
    at Runner.query (./api/node_modules/knex/lib/runner.js:135:36)
    at ./api/node_modules/knex/lib/runner.js:39:23
```

### Expected behavior

when create entity table, there should be database selection option
when insert entity data , there should be no error

### System
- Strapi version: v3.4.1

**Comment by derrickmehaffy** [comment] 2021-01-11 20:29
You most likely have a relation setup between a model and the admin user model. Bookshelf currently doesn't support relations on different databases.

IE: You can use multiple databases, but those databases cannot have relations to models on the other database. This is a limitation of the upstream ORMs.

Marking as closed as multi-database support is working as currently intended.

**Closed by derrickmehaffy** 2021-01-11 20:29 UTC

**Comment by enginespot** [comment] 2021-01-12 01:12
@derrickmehaffy , the model has no relationship with user model . it is only entity model

**Comment by derrickmehaffy** [comment] 2021-01-13 08:45
Can you provide a test project (without docker) that I can use for testing? As I tested locally and could not reproduce the issue.
