### ISSUE TITLE
MySQL - update user in admin UI  leads to ER_TRUNCATED_WRONG_VALUE

### ISSUE THREAD

**Issue by akalitenya** [strapi/strapi#3706] opened 2019-08-01 05:22 UTC
**Describe the bug**
MySQL - update User in admin UI  leads to ER_TRUNCATED_WRONG_VALUE

**Steps to reproduce the behavior**
1. make new project with Strapi beta 14
2. create user in admin UI
3. try to update user in admin UI
4. see error

**Expected behavior**
User should be updated with no issue

**System**
- Node.js version: 10.15.0
- Strapi version: beta 14
- Database: MySQL 5.7.25

**Additional context**
data of created user using admin UI:
Username: "John"
Email: "john@example.com"
role: Authenticated

then try to change Username to "John2" and click Save
got error:

Response:
{"statusCode":400,
"error":"Bad Request",
"message":[
{"messages":[
{
"id":"update `users-permissions_user` set 
`created_at` = '2019-08-01T05:15:10.000Z', 
`blocked` = false, 
`resetPasswordToken` = NULL, 
`provider` = 'local', 
`role` = 1, 
`username` = 'john2', 
`updated_at` = '2019-08-01T05:15:10.000Z', 
`email` = 'john@example.com', 
`confirmed` = false where `id` = 1 - ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2019-08-01T05:15:10.000Z' for column 'created_at' at row 1"
}]}]}

**Comment by lauriejim** [comment] 2019-08-07 14:30
Hello @akalitenya!
Can you please provide the data of your user when you created it.
And also the update you did to update your user.

Can you also provide a readable response object. It will help us a lot to read it easily.
I'm pretty sure you can read it clearly yourself.

**Comment by razvanilin** [comment] 2019-08-08 07:46
@lauriejim I have the same issue as the OP. The easiest way to replicate it is to:

* create a new strapi beta14 project
* have a default mysql connection
* complete setup
* create a new user from the Admin UI
* go to that user in the Admin UI and press Save to update it
* Error

It works fine through the API, but through the Admin UI it complains about the format of the `created_at` date that is passed through. My guess is that `created_at` shouldn't even be passed when updating the user, since that always stays the same and it can't be edited from the Admin UI anyway. I also noticed that MySql connections complain about ISO datetime formats and the date fields require a `YYYY-MM-DD h:mm:ss` format.

System

Node.js version: v10.16.0
Strapi version: beta 14
Database: MySQL 5.7.19

**Comment by akalitenya** [comment] 2019-08-08 08:09
@lauriejim i have updated issue decription

**Comment by razvanilin** [comment] 2019-08-08 08:33
As a temporary fix, you could add the following to `node_modules/strapi-plugin-users-permissions/controllers/User.js`

```
const moment = require('moment');

// ---- 

// then at line 154, before the edit function

// delete the created_at field as it doesn't need updating
if (ctx.request.body.created_at) delete ctx.request.body.created_at;
if (ctx.request.body.updated_at) {
  ctx.request.body.updated_at = moment(ctx.request.body.updated_at).format('YYYY-MM-DD h:mm:ss');
}
```

**Comment by lauriejim** [comment] 2019-08-08 16:02
Okay! this is a duplicate of this issue https://github.com/strapi/strapi/issues/3031
I close this one.

**Closed by lauriejim** 2019-08-08 16:02 UTC
Labels: type: help wanted 🤷‍♂️
