### ISSUE TITLE
Cannot throw custom ApplicationError message when deleting an entity (lifecycles)

### ISSUE THREAD

**Issue by LukaszUrb** [strapi/strapi#12607] opened 2022-02-21 10:11 UTC
### Describe the bug

Cannot throw custom ApplicationError (with message) when deleting an entity (lifecycles)

### Steps to reproduce the behavior

1. Go to an entity's lifecycles.js in the code
2. Create beforeDelete hook
3. Throw custom ApplicationError in the hook

### Expected behavior

UI displays a custom message passed to ApplicationError when deleting

### Current behavior

UI always displays the same error: "Warning: An error occurred during record deletion."

BTW Throwing a custom errors in any other hook e.g. beforeCreate works correctly.

### Code snippets

```
  beforeDelete() {
     throw new ApplicationError('You cannot do this')
  }
```

### System

- Node.js version: v14.18.0
- NPM version: 6.14.15
- Strapi version: 4.0.1
- Database: Postgres
- Operating system: Windows

**Comment by kasonde** [comment] 2022-02-21 13:17
Please share where your ApplicationError class is imported from. I'm not able to reproduce the issue without it

**Comment by LukaszUrb** [comment] 2022-02-21 13:29
`const { ApplicationError  } = require('@strapi/utils').errors;`

**Comment by kasonde** [comment] 2022-02-22 06:44
Yeah, quite odd that it doesn't. The error is actually returned to the UI like all the other hooks:
```json
{
    "data": null,
    "error": {
        "status": 400,
        "name": "ApplicationError",
        "message": "wow, no thanks",
        "details": {}
    }
}
```

**Comment by dirbacke** [comment] 2022-09-20 09:38
I have tested this with Strapi 4.3.8 and the error message is not shown to the user in lifecycle `beforeDelete` nor in the `beforeDeleteMany` lifecycle. 

`
const { ApplicationError } = require('@strapi/utils').errors;
`

```
async beforeDeleteMany(events) {
    const ids = events.params.where.$and[0].id.$in
    const items = await strapi.entityService.findMany('api::shop-product.shop-product', 
    {
      fields: ['id', 'inStock', 'publishedAt'],
      filters: { id: ids }
    })
    items.forEach(item => {
      if (item.inStock && item.publishedAt !== null) {
        throw new ApplicationError('Product is still in stock.');
      }
    })
  }
```

**Comment by specialblend** [comment] 2022-09-22 19:02
Seeing same issue on strapi `4.3.2` after `npm install @strapi/utils` which installed `^4.3.9`. 

Installing `@strapi/utils` same version as `@strapi/strapi`  seems to resolve issue.

Are breaking changes expected on patch version changes or patch version mismatch between core and utils? 

If not, do we track here or should I open new issue?

**Comment by derrickmehaffy** [comment] 2022-10-31 20:17
> Seeing same issue on strapi `4.3.2` after `npm install @strapi/utils` which installed `^4.3.9`.
> 
> Installing `@strapi/utils` same version as `@strapi/strapi` seems to resolve issue.
> 
> Are breaking changes expected on patch version changes or patch version mismatch between core and utils?
> 
> If not, do we track here or should I open new issue?

Generally speaking there should not be breaking changes in patch versions but we do expect that all `@strapi/*` packages are the same version when you upgrade. We do not currently version/release our packages independently.

**Comment by appanchor** [comment] 2022-11-06 20:13
I have verified that this bug exists in version 4.4.5; the ApplicationError message prop is not displayed. Any hopes this could be elevated to a higher severity? It's a terrible UX without this feature.

**Comment by derrickmehaffy** [comment] 2022-11-09 20:51
Reproduction video on v4.5.0: https://www.loom.com/share/b6b9cc9087f448239d62ec4a393c339e

**Comment by Burningnewm** [comment] 2022-12-06 20:49
Same issue here. Custom messages appear to be working correctly in other hooks but when using  beforeDelete it shows same message as above.

**Comment by joshuaellis** [comment] 2023-02-07 17:08
@gu-stav assigning to you because of your PR in progress.

**Closed** 2023-02-10 13:03 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:admin

**Comment by PatchLord** [comment] 2025-02-28 09:12
i am using strapi v5.5.1, and it doesn't show any custom message on UI, it only show in terminal.

`// Check if page_template_name is being set to null or undefined
    if (event.result?.page_template_name?.count < 1) {
      throw new errors.ApplicationError('Page Template not added');
    }`
