### ISSUE TITLE
Collection-Type field deleted, in the GET req is still visible

### ISSUE THREAD

**Issue by danielcurcione** [strapi/strapi#10424] opened 2021-06-02 16:27 UTC
### Describe the bug

After having deleted a field of a collection-type, if I try to make a GET request that field remains visible anyway, set to null.
**This problem does not appear in localhost, but only in production system** (host in _heroku_)

### Steps to reproduce the behavior

1. Create entries in a collection-type
2. Go to collection-type builder and delete on field
3. Make a GET request to read all entries about that collection-type
4. See error: the field you had deleted is still visible
5. Create a new entries without deleted field
6. Remake a GET request
7. See another error: the field you had deleted in a new entries is visible, but is value is null

### Expected behavior

After having deleted a field of the collection-type, I expect not to see it anymore in the GET requests

### Screenshots

My collection-type, after deleted 'price' field
<img width="495" alt="Schermata 2021-06-02 alle 23 41 36" src="https://user-images.githubusercontent.com/65120616/120556197-752d2580-c3fc-11eb-925e-45e90a69ce6f.png">

The results of GET request, field 'price' is still here
<img width="216" alt="Schermata 2021-06-02 alle 23 41 56" src="https://user-images.githubusercontent.com/65120616/120556344-a7d71e00-c3fc-11eb-8e55-34c9f0c347a3.png">

### System

- Node.js version: v12.16.3
- NPM version: v7.6.0
- Yarn version: v1.22.10
- Strapi version: v3.6.2
- Database: --quickstart default DB 
- Operating system: macOS

### Additional context

This issue is happen only in Heroku (prod env), not in localhost

**Comment by derrickmehaffy** [comment] 2021-06-02 20:49
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by danielcurcione** [comment] 2021-06-02 21:53
Hi, I updated my issue.

**Comment by derrickmehaffy** [comment] 2021-06-16 22:22
Hi @danielcurcione I believe this is a duplicate of http://github.com/strapi/strapi/issues/1114 but I'll let you reply and confirm.

We plan to have some massive changes to how we handle schema changes and migrations in our v4 to handle it automatically. There will be a database RFC available soon to detail those changes.

**Closed by derrickmehaffy** 2021-06-16 22:22 UTC
