### ISSUE TITLE
Date picker not displaying the right date when selecting one

### ISSUE THREAD

**Issue by yanniskadiri** [strapi/strapi#20412] opened 2024-05-31 14:28 UTC
**Required System information**
Node.js version: 20
NPM version: 10
Strapi version: 5.0.0
Database: sqlite
Operating system: Mac
Is your project Javascript or Typescript: Javascript

**Describe the bug**
The datetime field does not display the date that has been selected
Here is a recording showing the bug: https://app.dashcam.io/replay/6655ee1f3de8b20078726d25?share=RVVMxvGPkeBbJ9DESWrLNQ

**Steps to reproduce the behavior**
edit a content type
add a datetime field
click save
go to the content-type in the content manager
create an entry with the datetime field
add a date
check the displayed date

**Expected behavior**
The date displayed should be the one that has been selected in the date picker

**Comment by alexandrebodin** [comment] 2024-06-06 09:09
FYI, 

The Datetime field works correctly but it's Date field that is broken. @joshuaellis @madhurisandbhor  is this a DS issue ?

**Comment by joshuaellis** [comment] 2024-06-07 08:35
If thats the case, it's probably in the app and perhaps something to do with timezones and times since Date implicitly has time on it.

**Comment by joshuaellis** [comment] 2024-06-07 11:48
duplicate of #20321

**Closed by joshuaellis** 2024-06-07 11:48 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-manager, version: 5
