### ISSUE TITLE
Installing using Docker fails : Error: Cannot find module

### ISSUE THREAD

**Issue by jbeckton** [strapi/strapi#10043] opened 2021-04-14 22:16 UTC
### Describe the bug

while following the getting started guide [here](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/docker.html) the process fails when it tries to start the strapi app.

### Steps to reproduce the behavior

1. Go to [https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/docker.html](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/installation/docker.html)
2. On step 1 choose the Mongodb option 
3. Continue with steps 2 and 3 
4. See error in terminal

### Expected behavior

strapi app should start up in docker container and allow for access to the /admin

### Error

````
Starting your app...
internal/modules/cjs/loader.js:818

  throw err;
  ^

Error: Cannot find module './_lib/formatDistance/index.js'
Require stack:
- /srv/app/node_modules/date-fns/locale/en-US/index.js
- /srv/app/node_modules/date-fns/format/index.js
- /srv/app/node_modules/date-fns/index.js
- /srv/app/node_modules/strapi-utils/lib/parse-type.js
- /srv/app/node_modules/strapi-utils/lib/build-query.js
- /srv/app/node_modules/strapi-utils/lib/index.js
- /srv/app/node_modules/strapi/lib/commands/develop.js
- /usr/local/share/.config/yarn/global/node_modules/strapi/bin/strapi.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/srv/app/node_modules/date-fns/locale/en-US/index.js:8:37)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/srv/app/node_modules/date-fns/locale/en-US/index.js',
    '/srv/app/node_modules/date-fns/format/index.js',
    '/srv/app/node_modules/date-fns/index.js',
    '/srv/app/node_modules/strapi-utils/lib/parse-type.js',
    '/srv/app/node_modules/strapi-utils/lib/build-query.js',
    '/srv/app/node_modules/strapi-utils/lib/index.js',
    '/srv/app/node_modules/strapi/lib/commands/develop.js',
    '/usr/local/share/.config/yarn/global/node_modules/strapi/bin/strapi.js'
  ]
}
`````

### System

- Node.js version: 14.8
- NPM version: 7.9.0
- Strapi version: 3.5.4
- Database: Mongo
- Operating system: macOS 11.2.3

### Additional context

After the first attempt failed I deleted all the containers I have stored locally just to make sure I am getting a fresh build.

**Comment by derrickmehaffy** [comment] 2021-04-15 14:52
Can't reproduce (not using daemon) following documentation steps:

![image](https://user-images.githubusercontent.com/8593673/114889903-655f7080-9dbf-11eb-8654-d87980672070.png)

![image](https://user-images.githubusercontent.com/8593673/114889998-7c05c780-9dbf-11eb-9b6a-d06e87c2785b.png)

@jbeckton the issue is likely your npm version: 7.9.0 which isn't currently supported.

Marking issue as closed as can't reproduce

**Closed by derrickmehaffy** 2021-04-15 14:52 UTC
Labels: status: can't reproduce
