### ISSUE TITLE
Cannot install Plugins "@strapi/plugin-graphql"

### ISSUE THREAD

**Issue by anthoai97** [strapi/strapi#14048] opened 2022-08-10 06:04 UTC
## Mod Edit - Workaround

Please see this comment for a temporary work around until we have a fix: https://github.com/strapi/strapi/issues/14048#issuecomment-1210290065 or https://github.com/strapi/strapi/issues/14048#issuecomment-1210445438

---

### Required System information

- Node.js version: v16.15.0
- NPM version: 8.5.5
- Strapi version: "4.3.2"
- Database:
- Operating system:

### Steps to reproduce the behavior

Cannot run project after install Graphql Plugin.
Error return: 
[2022-08-10 12:58:07.468] debug: ⛔️ Server wasn't able to start properly.
[2022-08-10 12:58:07.469] error: merge.extractExtensionsFromSchema is not a function

### Screenshots

<img width="739" alt="Screen Shot 2022-08-10 at 13 03 59" src="https://user-images.githubusercontent.com/85854989/183827100-010422a9-a0c9-4b24-9120-b4a7354134b0.png">

**Comment by LabatJordan** [comment] 2022-08-10 07:04
Same for me when migrating to strapi "4.3.2"
<img width="617" alt="Capture d’écran 2022-08-10 à 09 03 11" src="https://user-images.githubusercontent.com/16118515/183836617-0b249e64-c9be-400c-bcd0-f071d81b9b96.png">

**Comment by SujayPrabhu96** [comment] 2022-08-10 07:08
+1

**Comment by MikuZZZ** [comment] 2022-08-10 07:19
Same error here

**Comment by Sunny-Pirate** [comment] 2022-08-10 07:40
+1

**Comment by MikuZZZ** [comment] 2022-08-10 07:45
Add the resolution filed to lock `@graphql-tools/merge` package version to 8.3.0 can solve this problem temporarily.

```
"resolutions": {
    "**/@graphql-tools/merge": "8.3.0"
  },
```

**Comment by anthoai97** [comment] 2022-08-10 08:03
> Add the resolution filed to lock `@graphql-tools/merge` package version to 8.3.0 can solve this problem temporarily.
> 
> ```
> "resolutions": {
>     "**/@graphql-tools/merge": "8.3.0"
>   },
> ```

It work !!!

**Comment by plcdnl** [comment] 2022-08-10 08:22
> Add the resolution filed to lock `@graphql-tools/merge` package version to 8.3.0 can solve this problem temporarily.
> 
> ```
> "resolutions": {
>     "**/@graphql-tools/merge": "8.3.0"
>   },
> ```

Same here. Thank you so much for this temporary fix!

**Comment by JanKoll** [comment] 2022-08-10 09:59
If you are using npm you can add the following to your `package.json` until its fixed:
```
...
  "overrides": {
    "@graphql-tools/merge": "8.3.0"
  },
...
```

**Comment by bouncydragon** [comment] 2022-08-10 10:08
> Add the resolution filed to lock `@graphql-tools/merge` package version to 8.3.0 can solve this problem temporarily.
> 
> ```
> "resolutions": {
>     "**/@graphql-tools/merge": "8.3.0"
>   },
> ```

I followed the [setup for deploying strapi using heroku](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/heroku.html#_5-create-your-strapi-server-config-for-production) with graphql plugin, running it locally works fine, but after deploying it to heroku, the issue still exist.

![image](https://user-images.githubusercontent.com/9712523/183875547-3ae842ce-9ddc-4d72-b12e-37cfe8056f6d.png)

**Comment by richardweaver** [comment] 2022-08-10 12:09
I'm still getting this on Strapi 4.2.3. I've tried applying both `resolutions` and `overrides`, and for completeness added `@graphql-tools/schema` to the overrides, but I still get the issue. Any suggestions?

```
  "dependencies": {
    "@mattie-bundle/strapi-plugin-search": "1.0.0-alpha.3",
    "@mattie-bundle/strapi-provider-search-algolia": "1.0.0-alpha.3",
    "@strapi/plugin-graphql": "4.2.3",
    "@strapi/plugin-i18n": "4.2.3",
    "@strapi/plugin-users-permissions": "4.2.3",
    "@strapi/provider-upload-cloudinary": "4.2.3",
    "@strapi/strapi": "4.2.3",
    "bullmq": "^1.86.5",
    "node-bigcommerce": "^4.1.0",
    "pg": "^8.7.3",
    "sqlite3": "^5.0.5",
    "strapi-plugin-preview-button": "^0.3.4"
  },
  "devDependencies": {
    "@types/node": "16",
    "babel-eslint": "^10.1.0"
  },
  "resolutions": {
    "**/@graphql-tools/merge": "8.3.0",
    "**/@graphql-tools/schema": "8.3.0"
  },
  "overrides": {
    "@graphql-tools/merge": "8.3.0",
    "@graphql-tools/schema": "8.3.0"
  }
```

**Comment by sinamoradi1375** [comment] 2022-08-10 12:10
Same error here. I've tried installing it on both `v4.2.2` and `v4.3.2`.

**Comment by plcdnl** [comment] 2022-08-10 12:21
> I'm still getting this on Strapi 4.2.3. I've tried applying both `resolutions` and `overrides`, and for completeness added `@graphql-tools/schema` to the overrides, but I still get the issue. Any suggestions?
> 
> ```
>   "dependencies": {
>     "@mattie-bundle/strapi-plugin-search": "1.0.0-alpha.3",
>     "@mattie-bundle/strapi-provider-search-algolia": "1.0.0-alpha.3",
>     "@strapi/plugin-graphql": "4.2.3",
>     "@strapi/plugin-i18n": "4.2.3",
>     "@strapi/plugin-users-permissions": "4.2.3",
>     "@strapi/provider-upload-cloudinary": "4.2.3",
>     "@strapi/strapi": "4.2.3",
>     "bullmq": "^1.86.5",
>     "node-bigcommerce": "^4.1.0",
>     "pg": "^8.7.3",
>     "sqlite3": "^5.0.5",
>     "strapi-plugin-preview-button": "^0.3.4"
>   },
>   "devDependencies": {
>     "@types/node": "16",
>     "babel-eslint": "^10.1.0"
>   },
>   "resolutions": {
>     "**/@graphql-tools/merge": "8.3.0",
>     "**/@graphql-tools/schema": "8.3.0"
>   },
>   "overrides": {
>     "@graphql-tools/merge": "8.3.0",
>     "@graphql-tools/schema": "8.3.0"
>   }
> ```

Wich version of node are you using ? With v14 i had the same problem but not with v16

**Comment by pepijn-vanvlaanderen** [comment] 2022-08-10 12:43
+1

**Comment by richardweaver** [comment] 2022-08-10 14:44
I've resolved this, for anyone searching: if you are using yarn workspaces with hoisting your `resolutions` declaration needs to be in your root `package.json`.

**Comment by derrickmehaffy** [comment] 2022-08-10 14:51
Marking as confirmed due to volume of confirmations.

**Comment by derrickmehaffy** [comment] 2022-08-10 15:29
Just as an update to this issue, we are currently deploying an experimental release to check the fix above works and once we confirm that we will release a hotfix.

**Comment by derrickmehaffy** [comment] 2022-08-10 15:38
Could I have a few of you do us a favor and test using the experimental tag:

`npx create-strapi-app@experimental testHotfix --quickstart --no-run`
Or you can move your package versions to: `0.0.0-8581854cb3`

```json
{
  "name": "test-hotfix",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/plugin-graphql": "^0.0.0-8581854cb3",
    "@strapi/plugin-i18n": "0.0.0-8581854cb3",
    "@strapi/plugin-users-permissions": "0.0.0-8581854cb3",
    "@strapi/strapi": "0.0.0-8581854cb3",
    "better-sqlite3": "7.4.6"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "e6de134e-c98c-4ac8-a9fd-3ec53af2bfed"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by plcdnl** [comment] 2022-08-10 15:45
Works for me!

**Comment by derrickmehaffy** [comment] 2022-08-10 16:01
> Works for me!

Can you confirm your node-version as we noticed that some users on node 16 still get the same error

**Comment by plcdnl** [comment] 2022-08-10 16:07
> > Works for me!
> 
> Can you confirm your node-version as we noticed that some users on node 16 still get the same error

Tried on v14 and v16. Works on both for me

**Comment by DerMambo** [comment] 2022-08-10 16:09
looks good to me as well 👍  `v16.14.2`

**Comment by derrickmehaffy** [comment] 2022-08-10 16:52
It looks like we have determined this isn't an issue that was caused by a change we made but we think there is some other work arounds.

**Comment by alexandrebodin** [comment] 2022-08-10 17:34
This problem has been fixed on @graphql-tools repo. Thank you to [ardatan](https://github.com/ardatan) for the quick fix :)

**Comment by derrickmehaffy** [comment] 2022-08-10 17:35
To fix, just make sure you delete your `package-lock.json` and/or `yarn.lock` and reinstall node_modules, no Strapi version upgrade needed.

TY everyone for reporting this!

**Closed by alexandrebodin** 2022-08-10 17:34 UTC
Labels: issue: bug, severity: high, status: confirmed, source: plugin:graphql
