### ISSUE TITLE
Filter on datetime field is not working in GraphQL API

### ISSUE THREAD

**Issue by luanorlandi** [strapi/strapi#12706] opened 2022-03-01 22:30 UTC
### Describe the bug

Queries with a filter in a field of type date are not working for the GraphQL API plugin in Strapi. I was also able to reproduce the following scenarios:

- The REST API is working
- The  filter for `date`, `datetime` and `createdAt` (managed by Strapi) are affected
- Changing operators (like `gte` or `eq`) give the same result, the data is not filtered
- Applying operators in other field types like `number` does filter the data as expected

Tests were done in the SQLite database only.

I found this issue that seems to be related: [Filter on date not working on SQLite #3996](https://github.com/strapi/strapi/issues/3996)

### Steps to reproduce the behavior

1. Bootstrap Strapi with option quickstart
2. Add the GraphQL plugin of Strapi
4. Start the server in localhost
5. Build a new content type
6. Create an entity for that content type
7. Add `find` permission for Public role
8. Query entities with GraphQL playground using a filter for `createdAt` and operator `gte`, with a value greater than the date in the entity created

### Expected behavior

The entity is filtered and the list returned by the query is empty.

### Code snippets

```graphql
query {
  entities(filters: { createdAt: { gte: "2022-02-28T03:00:00.000Z" } }) {
    data {
      id
    }
  }
}
```

Equivalent REST API:

```javascript
fetch('http://localhost:1337/api/entities?filters[createdAt][$gte]=2022-02-28T03:00:00.000Z');
```

### System

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version: 4.1.0
- Database: SQLite
- Operating system: MacOS

**Comment by tpimh** [comment] 2022-03-02 09:44
Just upgraded from 4.0.6 to 4.1.1 and is also hit by this bug.

**Comment by tpimh** [comment] 2022-03-02 10:25
I can confirm that filtering works correctly on 4.0.7 and is broken on 4.0.8. Hope this helps to find the commit that caused this. [A lot of changes between the two versions, though](https://github.com/strapi/strapi/compare/v4.0.7...v4.0.8).

**Comment by ZakariasBW** [comment] 2022-03-02 16:39
Same issue here
 - Strapi version: 4.1.1
 - Database: Postgres

**Comment by luanorlandi** [comment] 2022-03-03 02:37
Thank you @tpimh and @ZakariasBW for the input.

I've tracked down the issue and submitted a PR to fix it: https://github.com/strapi/strapi/pull/12725

**Comment by Brianggalvez** [comment] 2022-03-03 10:02
> Thank you @tpimh and @ZakariasBW for the input.
> 
> The bug was introduced in this PR: #11917
> 
> I've tracked down the issue and submitted a PR to fix it: #12725

for Date type it's still not working because after parsing the query params, '1992-12-12' turns into { '$gt': 1992-12-12T00:00:00.000Z }

**Comment by petersg83** [comment] 2022-03-03 14:54
Hello :)
Does the bug still exist in `4.1.2`? It was released yesterday and I believe it fixed the issue

**Comment by tpimh** [comment] 2022-03-03 15:09
@petersg83 As https://github.com/strapi/strapi/pull/12725 is still open, 4.1.2 should be affected as well.

**Comment by tpimh** [comment] 2022-03-03 15:16
@petersg83 Just tested with 4.1.2, it works! Now this issue and https://github.com/strapi/strapi/pull/12725 can be closed! Thank you all very much!

**Comment by petersg83** [comment] 2022-03-03 15:28
Thank you all very much too! It's very nice to be quickly aware of a bug in order to fix it as soon as possible :) Have a good day!

**Comment by luanorlandi** [comment] 2022-03-04 00:56
@petersg83 The issue is still happening for datetime fields. See the sections below for details and double-check the solution provided in PR #12725.

I tested in v4.1.2 with the GraphQL API, the date type is working, datetime type is not (including `createdAt` managed by Strapi).

I believe the issue remains for the way that the parser mentioned in PR https://github.com/strapi/strapi/pull/12725 is treating datetime types as objects of type `Date`. But date types as strings, since they don't include time, thus are strings with just day, month and year.

I tested the queries with the `eq` operator and changed 1 day to check if the filter applies (with values 2022-03-01 and 2022-03-02).

# Entity created in admin

![image](https://user-images.githubusercontent.com/6919329/156676046-ebe49836-9c6b-4d16-9a72-762b265777ae.png)

# Master in v4.1.2

App `examples/getstarted` running in master branch in v4.1.2

![image](https://user-images.githubusercontent.com/6919329/156675167-fd2825c7-bfac-44e0-8ab7-0f3298555a98.png)

Git log:

![image](https://user-images.githubusercontent.com/6919329/156677618-8b75817c-3e3a-4aae-952b-7d9244c22d33.png)

## Datetime field (not working)

![image](https://user-images.githubusercontent.com/6919329/156675652-d68f7c67-3875-4bbb-8c0b-07ee6a65f7b7.png)

This one failed to filter:

![image](https://user-images.githubusercontent.com/6919329/156675694-c430c11f-b0ef-4303-bcfd-eb96a8a3e050.png)

With `createdAt` filter, the result is the same.

## Date field (working as expected)

![image](https://user-images.githubusercontent.com/6919329/156675803-3c6bd521-8aa3-41a6-a094-071ac19c9be5.png)

![image](https://user-images.githubusercontent.com/6919329/156675838-89c3c144-adb1-44c3-a7b3-ecfde8b66739.png)

# fix/sanitize-date-query-param branch from PR #12725

App `examples/getstarted` running in fix/sanitize-date-query-param branch from PR #12725

![image](https://user-images.githubusercontent.com/6919329/156677534-aff98bf6-dee5-4ea3-9bb6-ecc86954d23b.png)

## Datetime field (working as expected)

![image](https://user-images.githubusercontent.com/6919329/156676576-a5e786ad-4be9-4ea8-9320-7dcc91955e57.png)

![image](https://user-images.githubusercontent.com/6919329/156676604-96fb8f58-5ed0-448e-aa82-d36e4f9235cd.png)

## Date field (working as expected)

![image](https://user-images.githubusercontent.com/6919329/156677376-8ab421a5-f9d3-4dd1-bd19-2a6dbf725438.png)

![image](https://user-images.githubusercontent.com/6919329/156677399-02c5199e-8c87-4a92-855a-3fc9c837fb09.png)

**Comment by petersg83** [comment] 2022-03-04 13:15
Thank you ! Indeed the datetime filter is not working correctly. I'm looking at your PR

**Comment by tpimh** [comment] 2022-03-04 13:57
Turns out I spoke too soon. I only checked with date, not datetime.

**Comment by gu-stav** [comment] 2022-03-11 11:09
@luanorlandi Thanks again for Pr and the great tests. The PR was merged to today and will be included in the next release. If you encounter any other issues, feel free to ping @petersg83 and me directly and we'll re-open this issue.

**Comment by FarhangQ** [comment] 2022-07-28 08:52
same here
graphQL = 4.3.0
strapi = 4.2.3
SQLite


![Screenshot 2022-07-28 132057](https://user-images.githubusercontent.com/11559624/181464209-74d37690-fdee-4e6d-85d5-00c700972dd0.jpg)

**Comment by gu-stav** [comment] 2022-07-28 08:55
@petersg83 I think we need to look at this again ...

**Comment by Convly** [comment] 2022-07-28 09:04
@FarhangQ is there only one story for this user in the returned data?

**Comment by FarhangQ** [comment] 2022-07-28 09:08
> @FarhangQ is there only one story for this user in the returned data?
no, it return any stories till that date

![image](https://user-images.githubusercontent.com/11559624/181467312-5fd44ea7-fce6-44b4-87b7-196f32d2eb93.png)

**Comment by Convly** [comment] 2022-07-28 09:20
Your story ID: 127 matches the filter, so the user is returned.
If you want to filter the stories for each user to only keep a subsection, you must apply the filter on the child resolver directly (`sorties(filters: {})`)
![image](https://user-images.githubusercontent.com/25851739/181470152-62b1efc1-abd5-47b9-b76c-2d9a94ae8211.png)

**Comment by Convly** [comment] 2022-07-28 09:26
Basically something similar to this

```graphql
query {
  usersPermissionsUsers(
    # Get users who have at least one stories that match this filter
    filters: { stories: { hide_date: { gt: "2022-07-30T08:31:57.000Z" } } }
  ) {
    data {
      attributes {
        stories(
          # Get user's stories that match this filter
          filters: { stories: { gt: "2022-07-30T08:31:57.000Z" } }
        ) {
          data {
            id
            attributes {
              hide_date
            }
          }
        }
      }
    }
  }
}
```

**Comment by FarhangQ** [comment] 2022-07-28 09:27
> Your story ID: 127 matches the filter, so the user is returned. If you want to filter the stories for each user to only keep a subsection, you must apply the filter on the child resolver directly (`stories(filters: {})`) ![image](https://user-images.githubusercontent.com/25851739/181470152-62b1efc1-abd5-47b9-b76c-2d9a94ae8211.png)

thanks, but there is another issue, bunch of useless data (as many as stories exists). is it normal?
![image](https://user-images.githubusercontent.com/11559624/181471365-3b872fa7-208d-4082-8ba6-8432da23c3f7.png)

**Comment by Convly** [comment] 2022-07-28 09:28
> > Your story ID: 127 matches the filter, so the user is returned. If you want to filter the stories for each user to only keep a subsection, you must apply the filter on the child resolver directly (`stories(filters: {})`) ![image](https://user-images.githubusercontent.com/25851739/181470152-62b1efc1-abd5-47b9-b76c-2d9a94ae8211.png)
> 
> thanks, but there is another issue, bunch of useless data (as many as stories exists). is it normal? ![image](https://user-images.githubusercontent.com/11559624/181471365-3b872fa7-208d-4082-8ba6-8432da23c3f7.png)

See my message above with the example provided :slightly_smiling_face:

**Comment by FarhangQ** [comment] 2022-07-28 09:38
> See my message above with the example provided 🙂

could you please write correct code to get rid of useless data?

(I tried following code but results are same)

![image](https://user-images.githubusercontent.com/11559624/181474188-d8522b11-c082-4ddd-a512-bae256bec16e.png)

**Comment by Convly** [comment] 2022-07-28 09:47
I'll close this as it works as intended. Feel free to open a new issue if you encounter troubles.
Have a nice day & good luck!

**Closed by Convly** 2022-07-28 09:47 UTC
Labels: issue: bug, severity: medium, source: plugin:graphql, status: pending reproduction
