### ISSUE TITLE
Typescript: entityService.findMany, findOne, ... should accept Common.UID.Schema instead of Common.UID.ContentType

### ISSUE THREAD

**Issue by mateon1** [strapi/strapi#18725] opened 2023-11-10 00:49 UTC
### Required System information

Environment: development
OS: linux-x64
Strapi Version: 4.15.2
Node/Yarn Version: yarn/1.22.19 npm/? node/v18.18.0 linux x64
Edition: Community
Database: sqlite

### Describe the bug

Trying to use entityService methods to find and modify components currently causes a type error, despite entityService methods working with components.

### Steps to reproduce the behavior

Create any component, write code trying to access the component via the entityService, for example:
```js
let test = await strapi.entityService.findMany("test.test")
```
Notice the Typescript type error, and that the query succeeds at runtime.

### Expected behavior

No type error is emitted.

### Additional context

I encountered this issue while writing some code for working around #17654. Deeply populating zones doesn't work, but you can query the zone components directly and deeply populate starting from those components.

**Comment by hussain-mustafa990** [comment] 2024-01-11 14:33
i have also experienced this issue in version v4.17.0

**Comment by Convly** [comment] 2024-01-23 14:04
Hi, thanks for taking the time to open this issue.

The entity service was never intended to be used with components in the first place.

Components are entities that depend entirely on a content type entry and shouldn't be queried on their own.

The fact that the entity service was OK with returning components is at best a flaw in its implementation, and it shouldn't be used as it's considered 100% unstable.

The goal of adding types to our most used APIs is to enforce good practices and usage of our APIs. Restricting the UID param of the entity service's methods to be a content type UID is thus the intended behavior and won't be changed.

Thanks for your comprehension. I'll close this as this is not a bug.

Have a nice day!

_ps: You should be able to deeply populate dynamic zones using [populate fragments](https://docs.strapi.io/dev-docs/api/entity-service/populate#populate-fragments)_

**Closed by Convly** 2024-01-23 14:04 UTC
Labels: issue: bug, severity: medium, status: pending reproduction, source: typescript
