### ISSUE TITLE
In Production Mode, Admin Panel ist not accessible. 

### ISSUE THREAD

**Issue by exotexot** [strapi/strapi#17966] opened 2023-09-07 10:42 UTC
### Required System information

- Node.js version: 18.17.1 (using latest node:18-alpine version)
- NPM version: 9.6.7
- Strapi version: 4.13.1
- Database: Postgres 14.5
- Operating system: Ubuntu 22
- Is your project Javascript or Typescript: JS

### Describe the bug

I'm using Strapi in a Docker, using the docker configuration described here: https://docs.strapi.io/dev-docs/installation/docker
I'm using nginx to server strapi via 0.0.0.0/strapi

When running a production build, I cannot access the admin panel: 0.0.0.0/strapi/admin shows blank screen.

### Steps to reproduce the behavior

1. Run Dockerised Strapi
2. Make production build
3. setup nginx 
4. Try to access Admin Panel

### Expected behavior

Admin Panel should be available.

### Screenshots

![Screenshot 2023-09-07 at 12 39 01](https://github.com/strapi/strapi/assets/10153413/98b9522c-bfa4-45ba-8f6c-13cc12f06a1a)

### Code snippets

Dockerfile
```
# Creating multi-stage build for production
FROM node:18-alpine as build
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev > /dev/null 2>&1
ARG NODE_ENV=production
ENV NODE_ENV=production

WORKDIR /server/
COPY package.json package-lock.json ./
RUN npm config set network-timeout 600000 -g && npm install --only=production
ENV PATH /server/node_modules/.bin:$PATH
WORKDIR /server/app
COPY . .
RUN npm run build

# Creating final production image
FROM node:18-alpine
RUN apk add --no-cache vips-dev
ARG NODE_ENV=production
ENV NODE_ENV=production
WORKDIR /server/
COPY --from=build /server/node_modules ./node_modules
WORKDIR /server/app
COPY --from=build /server/app ./
ENV PATH /server/node_modules/.bin:$PATH

RUN chown -R node:node /server/app
USER node
EXPOSE 1337
CMD ["npm", "run", "start"]
```

NGINX Config
```
server {
  listen 80;
  server_name 192.168.1.228;

  # Redirect HTTP to HTTPS
  location / {
    return 301 https://$host$request_uri;
  }
}


server {
  listen 443 ssl;
  server_name 192.168.1.228;

  ssl_certificate /etc/nginx/ssl/cert.pem;   # Path to SSL certificate in the bind volume
  ssl_certificate_key /etc/nginx/ssl/key.pem;  # Path to SSL private key in the bind volume

  location / {
    root /usr/share/nginx/html;
    index index.html;

    # Use try_files to handle client-side routing
    try_files $uri $uri/ /index.html;
  }

  location /strapi/ {
    proxy_pass http://abc-strapi:1337/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}

```

**Comment by vitalijalbu** [comment] 2023-09-07 12:11
i also had this issue on nginx server, seems impossible to deploy strapi in very few clicks. when don't do like php? you uplaod the code, connect to db and that's it!!! @strapi-cla

**Comment by derrickmehaffy** [comment] 2023-09-07 15:25
The server url needs to be set and likewise your nginx config is not stripping the prefix, we have documentation around this: https://docs.strapi.io/dev-docs/deployment/nginx-proxy

Yes to answer the question that comes with this every time, you do need to build separate containers for each environment if you intend on serving the admin panel in the same container, no the admin url is not dynamic, no we do not plan to do so anytime soon.

Marking this as closed as it's not a bug but more of a question

**Closed** 2023-09-07 15:26 UTC
Labels: flag: question

**Comment by vitalijalbu** [comment] 2023-09-07 15:28
> The server url needs to be set and likewise your nginx config is not stripping the prefix, we have documentation around this: https://docs.strapi.io/dev-docs/deployment/nginx-proxy
> 
> Yes to answer the question that comes with this every time, you do need to build separate containers for each environment if you intend on serving the admin panel in the same container, no the admin url is not dynamic, no we do not plan to do so anytime soon.
> 
> Marking this as closed as it's not a bug but more of a question

Hi, I can't understand. Server configuration needs only Upstream ? Or also Proxy?
I'm not a techical server :D

**Comment by derrickmehaffy** [comment] 2023-09-07 15:57
You are missing this: `rewrite ^/test/?(.*)$ /$1 break;` and your server URL doesn't appear to be set and/or the ENV var isn't being passed when the admin panel is built.

**Comment by derrickmehaffy** [comment] 2023-09-07 15:57
In your case the path would be /strapi not /test
