### ISSUE TITLE
Users permissions disappearance

### ISSUE THREAD

**Issue by TheWebsDoor** [strapi/strapi#842] opened 2018-03-25 17:58 UTC
**Node.js version:**
8.9.3
**npm version:**
5.5.1
**Strapi version:**
3.0.0-alpha.11.1
**Operating system:**
MacOS 10.13.3

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Sometimes, users permissions disappear for no reason. All checkboxes are unchecked and we have to start to do the configuration all over again. And sometimes, even when we recheck all the boxes, nothing happen when we save new permissions.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
I have to admit that I didn't understand yet why this behaviour is happening but you are already aware of this issue. Maybe someone could give us more details in this thread.

**What is the expected behavior?**
We should keep users permissions

**Comment by lauriejim** [comment] 2018-03-27 16:44
Hi @TheWebsDoor .

The checkbox `select all` is a little bit buggy so try to don't use it.

And about this issue, we have to found steps to reproduce it ...

**Comment by nurikabe** [comment] 2018-03-27 17:49
I've experienced loss of user permissions as well.  It seems to occur somewhat routinely in the following case:

1.  Work on a model with "auto server reload" active
2.  If there is a crash while editing a model, the server fails to auto reload
3.  Forcibly reload the server and in many cases user permissions have been lost

My *guess* is that Strapi may be (needlessly?) cascade re-persisting user permissions when models for other data types are changed.  Perhaps permissions get wiped out when the there is a problem saving the data that triggered user permissions to also update.

**Comment by lauriejim** [comment] 2018-03-27 18:02
I close this issue, it' a duplicate of this one: https://github.com/strapi/strapi/issues/736

**Closed by lauriejim** 2018-03-27 18:02 UTC
Labels: priority: high, status: need more informations 🤔, type: bug 🐛
