### ISSUE TITLE
Unable to set order for new relation

### ISSUE THREAD

**Issue by monolithed** [strapi/strapi#22263] opened 2024-11-25 08:24 UTC
### Required System information

Launched In: 228 ms
Environment: development
OS: darwin-arm64
Strapi Version: 5.3.0
Node/Yarn Version: npm/10.1.0 node/v20.9.0 darwin arm64 workspaces/false
Edition: Community
Database: postgres
TypeScript

### Describe the bug

Currently, to add a relation, you first need to save the entry, reload the page, and only then set its order. If you try to set the order right away, you get an error.

### Steps to reproduce the behavior

1. Go to 'Collection Types.'
2. Click on 'Entry'
3. Add 'Relation'
4. Try setting the order for your new relation
5. Press 'Publish'

### Expected behavior

No errors

### Screenshots

<img width="753" alt="Screenshot 2024-11-25 at 15 19 39" src="https://github.com/user-attachments/assets/93a377f9-151e-4435-8a75-7a56f0b716aa">

**Comment by derrickmehaffy** [comment] 2024-12-09 18:03
Duplicate of: https://github.com/strapi/strapi/issues/22228

**Closed** 2024-12-09 18:15 UTC
Labels: status: duplicate
