### ISSUE TITLE
How to understand Strapi.serives.[modelname].find Output

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4097] opened 2019-09-25 09:58 UTC
**Describe the topic**
How to understand Strapi.serives.[modelname].find Output

How to get the db output ?

Query {
  _mongooseOptions: { populate: { category_name: [PopulateOptions] } },
  _transforms: [],
  _hooks: Kareem { _pres: Map {}, _posts: Map {} },
  _executionCount: 0,
  mongooseCollection:
   NativeCollection {
     collection: Collection { s: [Object] },
     Promise: [Function: Promise],
     opts:
      { bufferCommands: true,
        capped: false,
        Promise: [Function: Promise],
        '$wasForceClosed': undefined },
     name: 'article',
     collectionName: 'article',
     conn:
      NativeConnection {
        base: [Mongoose],
        collections: [Object],
        models: [Object],
        config: [Object],
        replica: false,
        options: null,
        otherDbs: [],
        relatedDbs: {},
        states: [Object],
        _readyState: 1,
        _closeCalled: false,
        _hasOpened: true,
        plugins: [],
        _listening: false,
        _connectionOptions: [Object],
        '$dbName': 'bawarchi',
        name: 'bawarchi',
        host: '127.0.0.1',
        port: 27017,
        user: undefined,
        pass: undefined,
        client: [MongoClient],
        '$initialConnection': [Promise],
        db: [Db] },
     queue: [],
     buffer: false,
     emitter:
      EventEmitter {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined } },
  model: Model { Article },
  schema:
   Schema {
     base:
      Mongoose {
        connections: [Array],
        models: [Object],
        modelSchemas: [Object],
        options: [Object],
        _pluralize: [Function: pluralize],
        Schema: [Function],
        plugins: [Array] },
     obj:
      { Description: [Object],
        IsActive: [Object],
        Channel: [Object],
        Source: [Object],
        SeoUrl: [Object],
        ShowCaseArea: [Object],
        Category: [Object],
        Title: [Object],
        Section: [Object],
        EntityType: [Object],
        category_name: [Object] },
     paths:
      { Description: [SchemaString],
        IsActive: [SchemaBoolean],
        Channel: [SchemaString],
        Source: [SchemaString],
        SeoUrl: [SchemaString],
        ShowCaseArea: [SchemaString],
        Category: [SchemaString],
        Title: [SchemaString],
        Section: [SchemaString],
        EntityType: [SchemaString],
        category_name: [ObjectId],
        _id: [ObjectId],
        updatedAt: [SchemaDate],
        createdAt: [SchemaDate],
        __v: [SchemaNumber] },
     aliases: {},
     subpaths: {},
     virtuals: { id: [VirtualType] },
     singleNestedPaths: {},
     nested: {},
     inherits: {},
     callQueue: [],
     _indexes: [],
     methods: { initializeTimestamps: [Function] },
     methodOptions: {},
     statics: {},
     tree:
      { Description: [Object],
        IsActive: [Object],
        Channel: [Object],
        Source: [Object],
        SeoUrl: [Object],
        ShowCaseArea: [Object],
        Category: [Object],
        Title: [Object],
        Section: [Object],
        EntityType: [Object],
        category_name: [Object],
        _id: [Object],
        updatedAt: [Function: Date],
        createdAt: [Function: Date],
        __v: [Function: Number],
        id: [VirtualType] },
     query: {},
     childSchemas: [],
     plugins: [ [Object], [Object], [Object], [Object], [Object] ],
     '$id': 1,
     s: { hooks: [Kareem] },
     _userProvidedOptions: { timestamps: [Object], minimize: false },
     options:
      { typeKey: 'type',
        id: true,
        noVirtualId: false,
        _id: true,
        noId: false,
        validateBeforeSave: true,
        read: null,
        shardKey: null,
        autoIndex: null,
        minimize: false,
        discriminatorKey: '__t',
        versionKey: '__v',
        capped: false,
        bufferCommands: true,
        strict: true,
        timestamps: [Object],
        toJSON: [Object],
        toObject: [Object],
        pluralization: true },
     '$timestamps': { createdAt: 'createdAt', updatedAt: 'updatedAt' },
     '$globalPluginsApplied': true },
  op: 'find',
  options: { skip: 0, limit: 100 },
  _conditions: {},
  _fields: undefined,
  _update: undefined,
  _path: undefined,
  _distinct: undefined,
  _collection:
   NodeCollection {
     collection:
      NativeCollection {
        collection: [Collection],
        Promise: [Function: Promise],
        opts: [Object],
        name: 'article',
        collectionName: 'article',
        conn: [NativeConnection],
        queue: [],
        buffer: false,
        emitter: [EventEmitter] },
     collectionName: 'article' },
  _traceFunction: undefined,
  '$useProjection': true,
  count: [Function: count] }

**Comment by derrickmehaffy** [comment] 2019-09-25 10:02
closing as duplicate of https://github.com/strapi/strapi/issues/4095.

@sunithakarthikeyan please update your first issue with the proper template and please don't open multiple issues related to the same topic

**Closed by derrickmehaffy** 2019-09-25 10:02 UTC
