### ISSUE TITLE
Content Type Just Disappeared

### ISSUE THREAD

**Issue by Nivek92** [strapi/strapi#2948] opened 2019-03-08 08:05 UTC
**Informations**
- **Node.js version**: v10.8.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: Postgres
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
I created a content type via the content type builder and as I wanted to change it's name "An error occured" the content type isn't available in the content type builder anymore but the folder under /api is still there and it is shown under Content Types as one can see in the screenshot
![screenshot from 2019-03-08 08-56-32](https://user-images.githubusercontent.com/5087400/54015769-feebdb00-4180-11e9-9d06-6206ef3c0a97.png)

On a side note, only 2 of the Content Types under Content Types actually exist. Some of them have been deleted but still show for some reason (**another bug**)

**Steps to reproduce the problem**
I actually don't know

**What is the expected behavior?**
Well there shouldn't be any problems creating, editing and removing Content Types

**Comment by derrickmehaffy** [comment] 2019-03-08 08:09
@Nivek92 Strapi doesn't rename columns, you will need to manually rename it in your database.

Shutdown strapi, use the postgres CLI (or a client) to rename the column in the table.

**Comment by Nivek92** [comment] 2019-03-08 08:59
@derrickmehaffy I wanted to rename the content type.

There is an input field for it so I expect it to work from the dashboard. If it actually is not an option, the input field has to be removed.

![screenshot from 2019-03-08 09-55-32](https://user-images.githubusercontent.com/5087400/54018280-8852db80-4188-11e9-9d74-4c97755ac715.png)

Oh and about the listen Content Types, that have already been deleted:
I did some digging and found that they are still in the Postgres DB under public.core_store -> plugin_content-manager_schema
They have not been removed from there for some reason.

**Comment by derrickmehaffy** [comment] 2019-03-08 09:09
@Nivek92 https://github.com/strapi/strapi/issues/1114

Also yes the content manager does have a few issues that the Strapi team are aware of, you can just drop that entry in the database and restart strapi.

**Comment by derrickmehaffy** [comment] 2019-03-08 09:11
For now marking this issue as closed as it is a duplicate of #1114 and the content manager bugs are well documented and are being worked on.

**Closed by derrickmehaffy** 2019-03-08 09:11 UTC
