### ISSUE TITLE
Strapi v4 trying to run  (npm run develop) 

### ISSUE THREAD

**Issue by baliram123giri** [strapi/strapi#12153] opened 2022-01-10 09:21 UTC
Hi there!
I am getting an issue with strapi, when I am trying to run  (npm run develop). last time I hade no problem, but now it's issue hasn't solved!

**Comment by EzraEn1** [comment] 2022-01-10 09:22
Please follow the issue template, and please confirm that the issue you're having is not a duplicate of #12142.

**Comment by EzraEn1** [comment] 2022-01-10 09:25
If it is a duplicate, you may close this issue. A PR has already been submitted.

**Comment by RolfVeinoeSorensen** [comment] 2022-01-10 10:20
@EzraEn1 
Is the strapi 4.0.3 npm package fixed by your PR or should we do something else in order to be able to build strapi again?

**Comment by EzraEn1** [comment] 2022-01-10 11:04
@RolfVeinoeSorensen Unfortunately no, it's been moved over to the 4.0.4 milestone. However, it has been merged into the main branch.

**Comment by kasonde** [comment] 2022-01-10 14:25
Duplicate of #12142

**Closed by kasonde** 2022-01-10 14:25 UTC
