### ISSUE TITLE
Using the `useLibrary` hook throws a TypeError

### ISSUE THREAD

**Issue by lvegerano** [strapi/strapi#12072] opened 2022-01-02 17:18 UTC
### Describe the bug

Trying to implement a different WYSIWYG editor I want to use the Strapi media gallery. Based on the source code to use the medial library the `useLibrary` hook is needed for this. Doing so causes a `TypeError`.

### Steps to reproduce the behavior

1. Go to `src/plugins`
2. Generate a plugin with the CLI tool
3. Go to `<plugin>/src/admin/index.js`
4. Add field `app.addFields({ type: 'wysiwyg', Component: <TestComponent>  });`
5. In your component import `useLibrary` from `@strapi/helper-plugin`
6. In your code add `const { components } = useLibrary();`
7. BOOM!

### Expected behavior

Not to throw an Error

### System

- Node.js version: v16.13.0
- NPM version: v8.1.0
- Strapi version: v4
- Database: Postgres
- Operating system: Mac OS

**Comment by lvegerano** [comment] 2022-01-04 22:57
Hi @soupette I will try to put a reproduction repo later today.

**Comment by soupette** [comment] 2022-01-05 08:29
Thanks!

**Comment by lvegerano** [comment] 2022-01-05 15:22
Hi @soupette, [here](https://github.com/lvegerano/strapi-plugin-error) is my reproduction.  Sounds like I maybe doing something wrong.

**Comment by soupette** [comment] 2022-01-06 08:58
I am closing this issue as it is a duplicate of #12106.

Here is an [example repo](https://github.com/soupette/example-strapi-wysiwyg) where you can find the implementation of the Media library component

**Closed by soupette** 2022-01-06 08:58 UTC
Labels: severity: low, issue-type: help wanted
