### ISSUE TITLE
Duplicating resources does not populate relation inputs

### ISSUE THREAD

**Issue by samturrell** [strapi/strapi#15093] opened 2022-12-06 12:08 UTC
### Required System information

- Node.js version: v14.19.3
- NPM version: 6.14.17
- Strapi version: 4.5.3
- Database: mysql
- Operating system: macOS

### Describe the bug

When duplicating a page, relation inputs aren't populated.

### Steps to reproduce the behavior

1. Create a resource with a linked relation
2. Go to the collection listing page
3. Click to duplicate an item
4. Observe that the relations are not pulled through

See the recording below:

https://www.loom.com/share/816a4bb8b0db4d3a8c242c6ac5e07969

### Expected behavior

Relations should be pulled through from the resource being duplicated.

### Screenshots

https://www.loom.com/share/816a4bb8b0db4d3a8c242c6ac5e07969

### Code snippets

N/A

### Additional context

N/A

**Comment by petersg83** [comment] 2022-12-08 11:27
Indeed there is a regression here.

The way it was working before was that : when clicking on the duplicate button it was only opening the edit view with the form pre-filled (including relations). As we don’t load all relations anymore in the front because of performance issues, we need to rethink the duplicate feature and the user’s path to achieve a full duplicate.
Loading all the relations to fix this issue would just re-create the performance issues (not able to save when there are more than 1000 relations of instance etc.), so it would not be the way to go.

**Comment by joshuaellis** [comment] 2022-12-08 11:42
@petersg83 i've wondered this for a while actually, how come we clone browser side? And not server-side? If we were to do it server-side, this would _probably_ remove this issue?

**Comment by petersg83** [comment] 2022-12-08 11:56
There are several reasons :
  - so the user can edit it before
  - because the duplicate action can be destructive on relations, like a one-to-x relation. It would remove the relation from the original entry. So it's best if the user can edit it before saving, it becomes their responsibility.

Side note :
  - I wonder what happens with i18n

**Comment by gu-stav** [comment] 2022-12-12 13:54
We have discussed this issue today and will work on fixing this, but it will take a bit longer because the current way of cloning is broken with the refactoring of relations. We agreed that we need to explore how we will handle cloning in the future and keep you posted.

**Comment by JulienHe** [comment] 2022-12-15 13:21
I don't know if that's related, but when you `Fill in from another locale` the issue is similar, even worst the relations from the original page are going away.

**Comment by derrickmehaffy** [comment] 2022-12-27 20:57
I'll go ahead and close this issue since it's more so a feature request as Gustav pointed out

**Comment by gu-stav** [comment] 2023-01-02 11:24
@derrickmehaffy I'd like to reopen this issue if you don't mind because the comments above mix two issues:

- we will work on duplicating an entity from the CM list view, because this is simply broken for now, but the solution is not easy
- we won't work on relational fields when filling from another locale, because this part works as intended (relations are always localized) for now

**Comment by derrickmehaffy** [comment] 2023-01-03 06:31
> @derrickmehaffy I'd like to reopen this issue if you don't mind because the comments above mix two issues:
> 
> - we will work on duplicating an entity from the CM list view, because this is simply broken for now, but the solution is not easy
> - we won't work on relational fields when filling from another locale, because this part works as intended (relations are always localized) for now

Can you update the title?

**Closed** 2023-06-22 10:05 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-manager
