### ISSUE TITLE
Content type won't save

### ISSUE THREAD

**Issue by coolemur** [strapi/strapi#1300] opened 2018-05-30 13:26 UTC
**Informations**
- **Node.js version**: v8.11.2
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: Mongodb 3.6.5
- **Operating system**: ubuntu 16.04

**What is the current behavior?**

Content type wont save unless I restart my strapi node server.
(same issue here https://github.com/strapi/strapi/issues/487 but it was closed ??)

**Steps to reproduce the problem**

Try to create content type add some fields and press "save".

**What is the expected behavior?**

Created content type with fields.

**Suggested solutions**

Have no suggestions... maybe somehow automatically restart server or at least inform user with "restart your server" instead of "error occured".

**Comment by derrickmehaffy** [comment] 2018-05-30 13:34
@coolemur can you try and update your node version to node 9 or node 10 and try with a fresh project? Also include any errors dumped into the console.

**Comment by coolemur** [comment] 2018-05-30 13:54
@derrickmehaffy I can confirm that this issue doesn't occur with node v10.3.0 . Thank you. 

P.s. You might want to fix it on older version or just document that version x.x.x+ is needed for strapi.

**Comment by derrickmehaffy** [comment] 2018-05-30 13:55
@coolemur I believe as of late the required version of node >9 is documented but yeah I think right now its best to just move to node 10

**Comment by coolemur** [comment] 2018-05-30 13:56
@derrickmehaffy wrong call.... data dissapeared after page refresh... :/

**Comment by coolemur** [comment] 2018-05-30 13:56
So it doesn't work with v10 either...

**Comment by derrickmehaffy** [comment] 2018-05-30 13:57
@coolemur is Strapi automatically restarting when you save a content type? Or is this for data being entered in the content manager?

**Comment by coolemur** [comment] 2018-05-30 13:59
@derrickmehaffy 

1) I create content type and press save.
2) Content tipe appears in list and success message is shown.
3) I refresh page - content type is gone from the list.
4) I restart node server - content type appears in list.

**Comment by derrickmehaffy** [comment] 2018-05-30 14:02
@coolemur in your console are you seeing any errors being generated (not the browser console, the console where you ran `strapi start`)

Also is your model being shown in the `api/-modelname-/models/-Modelname-.settings.json` ?

**Comment by coolemur** [comment] 2018-05-30 14:07
@derrickmehaffy 

Model appears at api/-modelname-/models/-Modelname-.settings.json  but not in web application .
No errors is generated when I start api.

I think I found the problem.

When I run it with Forever (daemon library)
```forever start server.js``` Then it won't work.

When I run command 
```strapi start``` it works

Is it possible to run strapi as a daemon process  (I need daemon for production)?

**Comment by yummyelin** [comment] 2018-05-30 19:01
I used `strapi start`, the issue reproduced.

Steps:
1. Select "content type builder" in admin panel, click on "add content type", save
2. Click on "add new field", save. 
1)Success message pop up.
2)The new content type appears in left side bar.
3. Click on the new content type, shows: there are no fields yet, which make sense.
4. Click back on "content type builder", **the new content type disappears in the table, and still appears in left side bar**.
5. Refresh page, **the new content type disappears in left side bar**.

After I restart strapi server, the new content type reappears. 

I guess this kind of change would not be automatically applied to strapi server, even the change is saved in code.

The same as "Delete A Content Type". It won't be applied until restart strapi server.

**Comment by soupette** [comment] 2018-05-31 08:10
@yummyelin do you have the graphql plugin installed?

**Comment by lauriejim** [comment] 2018-05-31 16:55
Hi @coolemur an @yummyelin .
I reproduce your steps @yummyelin and it looks working on my side. @soupette did you successfully reproduce the issue ?

**Comment by yummyelin** [comment] 2018-05-31 21:38
@soupette no, I didn't install graphql plugin.

**Comment by johannpinson** [comment] 2018-06-05 16:57
I also had this bug some time and it's when I run as usual the `npm start` command instead of `strapi start`.

@yummyelin Do you see this kind of message when you save a field?
![capture d ecran 2018-06-05 a 18 55 59](https://user-images.githubusercontent.com/2202989/40990832-5493efec-68f2-11e8-8fba-417bf9060ac1.png)

**Comment by lauriejim** [comment] 2018-06-05 18:16
@yummyelin What is the browser you use ? Do you have an error log in your browser and in your terminal. Definitively not able to reproduce this issue.

**Comment by yummyelin** [comment] 2018-06-05 21:20
@johannpinson Yes, I saw this message. I can't reproduce now..

**Comment by yummyelin** [comment] 2018-06-05 21:20
@lauriejim I am using Chrome. I think we can close the issue, I can't reproduce now.

**Closed** 2018-06-06 10:49 UTC
Labels: priority: medium, status: can't reproduce 🙃, type: bug 🐛

**Comment by matejukmar** [comment] 2018-06-10 07:47
I was able to reproduce this issue with strapi **3.0.0-alpha.12.3**:
- started server as service with pm2 on custom port
`NODE_ENV=production PORT=2005 sudo pm2 start server.js --name myapi`
- access was via nginx proxy to 2005 port

1. New content type is 'successfully' created and fields added
2. When trying to create an instance of newly created type, page displays:
'There are no fields yet', 'Add your first field to your Content Type'

There is no error in Chrome console and I'm unable to see any errors in server logs.

**Comment by lauriejim** [comment] 2018-06-11 12:24
If you want to create content type, please use `strapi start` command.

**Comment by matejukmar** [comment] 2018-06-11 20:15
Is there a simple way to run `strapi start` as service?

**Comment by lauriejim** [comment] 2018-06-11 20:24
You can run `npm run strapi start`

**Comment by coolemur** [comment] 2018-06-11 23:02
@matejukmar 

You can use [forever](https://www.npmjs.com/package/forever) to run any command as service.
For example: ```forever start -c "strapi start" ./``` This will execute "strapi start" command in current directory.

**Comment by derrickmehaffy** [comment] 2018-06-12 09:43
You can also modify the package.json to run strapi with pm2. If you look at this guide: https://blog.strapi.io/how-to-deploy-a-strapi-application/

**Comment by dreaddymck** [comment] 2018-11-08 15:16
I am using pm2  with watch and useFsEvents enabled. The setup should automatically reload the application if change detected.

My ecosystem.config

```
module.exports = {
  /**
   * Application configuration section
   * http://pm2.keymetrics.io/docs/usage/application-declaration/
   */
  apps: [

    // First application
    {
      name: 'strapi',
      script: 'server.js',
      watch: true,
      watch_options: {
        "useFsEvents": true
      },
      // env: {
      //   "PORT": 9001,
      //   "NODE_ENV": "production"
      // },
    }
  ],
};
```
command:
`pm2 start ecosystem.config`
