### ISSUE TITLE
Error during creation of collection in Content-Types builder 

### ISSUE THREAD

**Issue by FlacorLopes** [strapi/strapi#9266] opened 2021-01-29 23:12 UTC
### Describe the bug

Content-Types builder displays a generic error alert when saving a collection with a specific name. 

### Steps to reproduce the behavior

1. Go to admin panel
2. Click on Content-Types builder
3. Click on Create new collection type
4. Type Music in Display Name
5. Click the button Continue
6. Select a text field and give it any name
7. Click finish, then click Save
8. See error

### Expected behavior

The content type should be created/saved or a descriptive error message should be displayed on the screen.

### Screenshots

![tempsnip](https://user-images.githubusercontent.com/1523957/106336481-c1f5c980-626d-11eb-90a5-d00f281fec67.png)

### System

- Node.js version: 14.10.0 
- NPM version: 6.14.8
- Strapi version: 3.4.5 
- Database: MongoDB 4.4.3 or SQLite from quickstart strapi app
- Operating system: Windows 10 - 10.0.19041.746

### Additional context

The error payload says that Music cannot be pluralized.
Similar issue was closed before https://github.com/strapi/strapi/issues/7508

**Comment by FlacorLopes** [comment] 2021-01-29 23:52
I think the appropriate way of handle this is showing up the pluralization error message, cause the pluralize package has 'music' as an uncountable word.

https://github.com/strapi/strapi/blob/be4d5556936cf923aa3e23d5da82a6c60a5a42bc/packages/strapi-plugin-content-type-
builder/controllers/validation/content-type.js

https://github.com/plurals/pluralize/blob/cba2fef5aacec60dc1ff4c780d01b16bcb8a03b3/pluralize.js

**Comment by budlight** [comment] 2021-03-28 03:10
I suspect this is a duplicate of #1198

**Comment by derrickmehaffy** [comment] 2021-03-29 19:06
closing as duplicate of https://github.com/strapi/strapi/issues/1198 (ty again @budlight)

**Closed by derrickmehaffy** 2021-03-29 19:06 UTC
Labels: severity: low, source: plugin:content-type-builder, status: pending reproduction, type: bug
