### ISSUE TITLE
Provider is not set when create User from content manager

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1213] opened 2018-05-17 04:36 UTC
**Informations**
- **Node.js version**:v10.1.0
- **npm version**:5.6.0
- **Strapi version**:3.0.0-alpha.12.1.3
- **Database**:Mongo
- **Operating system**:Linux

**What is the current behavior?**
Role shows wrong.

**Steps to reproduce the problem**
I have one admin user and one normal user but in "Users" page in content manager my users role shows wrong. See this image:
![strapi1](https://user-images.githubusercontent.com/25859075/40156906-5f3d0abe-59b1-11e8-8409-c07293089baf.png)
It's show **local** for my admin and **admin** for my user1. :thinking: 

**What is the expected behavior?**
We need see user role in Users page

**Suggested solutions**
---

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment] 2018-06-04 13:11
Hello @mnlbox ! 

How do you register this new user ? Did you use the content manager ?

Because `provider` is different than `role`. Provider is `local`, `facebook`, `twitter` ....

**Comment by mnlbox** [comment] 2018-06-12 07:14
@lauriejim Yes I create this user from content manager.
What is the meaning of "Admin" as a `provider`. :thinking:

**Comment by lauriejim** [comment] 2018-06-12 08:30
I don't know... That is the problem!

Can you send me params send in your request please.

**Comment by mnlbox** [comment] 2018-06-12 08:50
I just create new user from my admin panel. I don't send any custom params in my request. :thinking:

**Comment by lauriejim** [comment] 2018-07-01 15:19
The admin panel send a request with params, I have to know what are params value.
Still have no issue on this point. Did you customize your user controllers/services ?

**Comment by mnlbox** [comment] 2018-07-11 08:48
@lauriejim no I use default user model,...

**Comment by lauriejim** [comment] 2018-07-13 09:37
Can you please answer to my first sentence cause I still without information.

**Comment by lauriejim** [comment] 2018-07-19 15:05
If no body is able to reproduce this issue I will close it. Probably coming from your app and update you did in.

**Comment by derrickmehaffy** [comment] 2018-07-19 15:06
@lauriejim let me test to see if I can reproduce it, I think it has something to do with registering a new user.

**Comment by derrickmehaffy** [comment] 2018-07-19 15:11
@lauriejim creating a new user from the AdminUI doesn't show the correct provider (Using MySQL):

![image](https://user-images.githubusercontent.com/8593673/42951535-3e02faba-8b2b-11e8-92fc-d6058d94b9c6.png)

![image](https://user-images.githubusercontent.com/8593673/42951545-45da8fe6-8b2b-11e8-8fa7-c6354db478e5.png)

Note that the provider should local not -

**Comment by derrickmehaffy** [comment] 2018-07-19 15:15
Using a post request:

![image](https://user-images.githubusercontent.com/8593673/42951786-db4cbbe4-8b2b-11e8-8a62-5e36e6649fe6.png)

![image](https://user-images.githubusercontent.com/8593673/42951808-e95ac7e4-8b2b-11e8-861a-4b692a6cc9b1.png)

Works as intended

**Comment by mnlbox** [comment] 2018-07-22 09:00
@lauriejim as me and @derrickmehaffy said this issue happens when we create user from admin UI.

**Comment by lauriejim** [comment] 2018-07-23 09:10
@derrickmehaffy for `-` as provider, I'm OK.
But @mnlbox `admin` as provider, I don't know why you have this issue.

**Comment by mnlbox** [comment] 2018-07-25 10:18
@lauriejim I don't know but maybe it's because of that I create that user from admin UI with **admin** username. :thinking:

**Comment by lauriejim** [comment] 2018-08-22 13:14
Definitively impossible to reproduce @mnlbox issue (I close this issue).
@derrickmehaffy about the provider `-` can you create an issue for this point please.

**Comment by derrickmehaffy** [comment] 2018-08-22 13:26
@lauriejim Done: https://github.com/strapi/strapi/issues/1787

**Closed** 2018-08-22 13:27 UTC
Labels: priority: low, status: confirmed, type: enhancement 💅
