### ISSUE TITLE
Can't access Media Libray on the admin panel

### ISSUE THREAD

**Issue by bis0072** [strapi/strapi#17959] opened 2023-09-06 19:43 UTC
### Required System information

- Node.js version: v18.17.1
- NPM version: 9.3.1
- Strapi version: 4.13.3
- Database: "better-sqlite3": "^8.6.0"
- Operating system: win 11
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Can't access Media Libray on the admin panel
main.659737ec.js:1161 TypeError: Failed to construct 'URL': Invalid URL
    at a (main.659737ec.js:1126:8419)
    at fe (main.659737ec.js:839:664)
    at $s (main.659737ec.js:1159:20472)
    at Xe (main.659737ec.js:1161:45148)
    at of (main.659737ec.js:1161:40770)
    at Tf (main.659737ec.js:1161:40698)
    at zc (main.659737ec.js:1161:40552)
    at Td (main.659737ec.js:1161:36807)
    at nf (main.659737ec.js:1161:35746)
    at B (main.659737ec.js:1232:1633)

### Additional context

[Add any other context about the problem here.](http://localhost:1337/dashboard/plugins/upload?sort=createdAt:DESC&page=1&pageSize=10)

**Comment by esarymsakov** [comment] 2023-09-07 04:47
https://github.com/strapi/strapi/assets/95041686/a519471f-6658-4db7-a8f1-3b3fdae47d1c

I have a problem with uploading media files too. I attached a video about that problem.

**Comment by esarymsakov** [comment] 2023-09-07 05:19
UPD: I updated up Strapi to 4.13.3. Same problem

**Comment by agentx3** [comment] 2023-09-07 05:29
This should be the same issue as https://github.com/strapi/strapi/issues/17931

**Comment by joshuaellis** [comment] 2023-09-07 07:05
duplicate of https://github.com/strapi/strapi/issues/17931

**Closed by joshuaellis** 2023-09-07 07:05 UTC

**Comment by MWaseem739** [comment] 2023-09-07 07:15
I'm also facing the same issue. How I can resolve this issue?
