### ISSUE TITLE
TypeError: property.map is not a function

### ISSUE THREAD

**Issue by arutr** [strapi/strapi#3789] opened 2019-08-15 21:34 UTC
**Describe the bug**
Attempting to update a record through the Admin UI for models with a one-to-many or many-to-many relationship throws:
```
TypeError: property.map is not a function
    at params.parseRelationships.Object.keys.reduce (/home/artur/p20-backend/node_modules/strapi-hook-mongoose/lib/relations.js:97:49)
    at Array.reduce (<anonymous>)
    at Function.update [as updateRelations] (/home/artur/p20-backend/node_modules/strapi-hook-mongoose/lib/relations.js:30:122)
```
This happens if `property` is a string. In this instance, `property` is equal to an array with a single populated record, which seems to be interpreted as a string.

**UPDATE**: @albatrocity posted the potential fix for this below.

**Steps to reproduce the behavior**
1. Create a model with a many-to-many relationship field.
2. Add a record of the model.
3. Update a value in the new model.

**System**
- Node.js version: 10.16
- NPM version: 6.9
- Strapi version: beta 15
- Database: mongoDB
- Operating system: Ubuntu 18.04

**Additional context**
The affected model and record has been created in beta 7.

**Comment by arutr** [comment] 2019-08-15 23:11
A temporary workaround is to check whether `property.map` exists in [`relations.js`](https://github.com/strapi/strapi/blob/master/packages/strapi-hook-mongoose/lib/relations.js), but I don't think that solves the problem...

**Comment by albatrocity** [comment] 2019-08-19 17:52
`property` is a string [here](https://github.com/albatrocity/strapi/blob/master/packages/strapi-hook-mongoose/lib/relations.js#L84). If you replace line 84 with 
```js
$in: (Array.isArray(property) ? property : JSON.parse(property)).map(val => new mongoose.Types.ObjectId(val[assocModel.primaryKey]||val))
```
it works as expected. Could this be a bigger issue with the `strapi-plugin-content-manager` package and how it saves values?

**Comment by alexandrebodin** [comment] 2019-08-22 14:19
Hi @arutr, can you share the model.settings files of your schema so I can reproduce the bug locally plz :)

**Comment by arutr** [comment] 2019-08-22 15:16
@alexandrebodin https://github.com/poland20/p20-backend/tree/master/api
Anything in relation with Edition (e.g. Teammember) causes this bug.

**Comment by alexandrebodin** [comment] 2019-08-23 09:51
@arutr can you try for me to unselect the teamember and reselect and save ?

**Comment by alexandrebodin** [comment] 2019-08-23 09:57
@arutr Did you rebuild your admin panel after upgrading ?

**Comment by arutr** [comment] 2019-08-23 10:00
@alexandrebodin this issue doesn't just occur with Teammember, it also happens if you try to edit a field within an Edition
it also occurs even after rebuilding the admin panel
could this be an issue with what's stored in the database?

**Comment by alexandrebodin** [comment] 2019-08-23 11:35
@arutr

I'm just talking about teammembers and edition as an example :)
The issue is coming from the admin panel not sending the right data somehow. 

I have multiple ideas I need to verify so can you send me the data your receive and send when in the admin panel (looking into your inspector network tab) ?

**Comment by arutr** [comment] 2019-08-23 12:12
In Teammember, I receive:
```
{"_id":"5d1253a454b4ab001c190f30","name":"Bartłomiej Możdżeń","position":"Project Leader","organisation":"King's College London","email":"bartlomiej.mozdzen@poland20.com","createdAt":"2019-06-25T17:02:28.579Z","updatedAt":"2019-08-21T19:35:38.745Z","__v":0,"id":"5d1253a454b4ab001c190f30","linkedin":"https://www.linkedin.com/in/bartlomiej-mozdzen/","photo":{"_id":"5d1fa4fdf1da96001c67a7d1","name":"Photo from B.jpg","sha256":"Qzpy_5e5eokN-lj6LoYo1LHBAmxsd2S4V+kVIFQNEX0","hash":"8fbde669dd0c435199835577ecfdcffb","ext":".jpg","mime":"image/jpeg","size":"133.25","public_id":"grsipkkgywbqbdft2evg","url":"https://res.cloudinary.com/dg1royeho/image/upload/v1562354940/grsipkkgywbqbdft2evg.jpg","provider":"cloudinary","related":["5d1253a454b4ab001c190f30"],"createdAt":"2019-07-05T19:29:01.088Z","updatedAt":"2019-07-05T19:29:01.097Z","__v":0,"id":"5d1fa4fdf1da96001c67a7d1"},"editions":[{"teamMembers":["5d123dde779623001ce3ccbb","5d1253a454b4ab001c190f30","5d123eca779623001ce3ccbe","5d12545454b4ab001c190f33","5d123fbb779623001ce3ccc1","5d2635e2f1da96001c67a7da","5d21d276f1da96001c67a7d5","5d165d06f1da96001c67a7cb","5d12413554b4ab001c190f24","5d1c9b8af1da96001c67a7ce","5d123ccce63d1d001c07f802","5d136f52f1da96001c67a755","5d12427754b4ab001c190f2a","5d2639ddf1da96001c67a7dd","5d1242f054b4ab001c190f2d","5d014320ad5b943400cd8ed7","5d1241ed54b4ab001c190f27"],"sponsors":[],"speakers":[],"sponsorCategories":[],"_id":"5d02c48edaae307f03bbb2d2","year":2019,"description":"An annual conference for professionals and students that aims to present how innovation and technological progress are transforming the future of life, business, and public policy; placing a special emphasis on the role of Poland as a promising player in this field.","startDate":"2019-10-25T15:00:00.000Z","endDate":"2019-10-26T18:00:00.000Z","current":true,"createdAt":"2019-06-13T21:47:58.994Z","updatedAt":"2019-08-21T19:35:53.924Z","__v":0,"id":"5d02c48edaae307f03bbb2d2","venue":"5d0bfc0ffecc5f27dc4cc41b","name":"21st Century Nomad","coverPhoto":{"_id":"5d3b14537b6506001b9dfbfd","name":"Square 5_final landing.mp4","sha256":"9m1ixBQLm0guVK3KCaQ2ChE6ilRdrWyI9R0XbbtPyDQ","hash":"e337b7b472234199a1fd7598e2184da2","ext":".mp4","mime":"video/mp4","size":"5188.60","public_id":"bop6i4qy2piukmmc8y8o","url":"https://res.cloudinary.com/dg1royeho/video/upload/v1564152912/bop6i4qy2piukmmc8y8o.mp4","provider":"cloudinary","related":["5d02c48edaae307f03bbb2d2"],"createdAt":"2019-07-26T14:55:15.140Z","updatedAt":"2019-07-26T14:55:15.148Z","__v":0,"id":"5d3b14537b6506001b9dfbfd"}}]}
```

Updating field `linkedin` sends (in raw format):
```
------WebKitFormBoundaryhq66cepwfbJwcDKG
Content-Disposition: form-data; name="position"

Project Leader
------WebKitFormBoundaryhq66cepwfbJwcDKG
Content-Disposition: form-data; name="name"

Bartłomiej Możdżeń
------WebKitFormBoundaryhq66cepwfbJwcDKG
Content-Disposition: form-data; name="photo"

5d1fa4fdf1da96001c67a7d1
------WebKitFormBoundaryhq66cepwfbJwcDKG
Content-Disposition: form-data; name="editions"

[{"endDate":"2019-10-26T18:00:00.000Z","name":"21st Century Nomad","updatedAt":"2019-08-21T19:35:53.924Z","venue":"5d0bfc0ffecc5f27dc4cc41b","startDate":"2019-10-25T15:00:00.000Z","speakers":[],"__v":0,"sponsorCategories":[],"sponsors":[],"current":true,"_id":"5d02c48edaae307f03bbb2d2","coverPhoto":{"size":"5188.60","ext":".mp4","sha256":"9m1ixBQLm0guVK3KCaQ2ChE6ilRdrWyI9R0XbbtPyDQ","related":["5d02c48edaae307f03bbb2d2"],"name":"Square 5_final landing.mp4","hash":"e337b7b472234199a1fd7598e2184da2","updatedAt":"2019-07-26T14:55:15.148Z","url":"https://res.cloudinary.com/dg1royeho/video/upload/v1564152912/bop6i4qy2piukmmc8y8o.mp4","provider":"cloudinary","public_id":"bop6i4qy2piukmmc8y8o","mime":"video/mp4","__v":0,"_id":"5d3b14537b6506001b9dfbfd","id":"5d3b14537b6506001b9dfbfd","createdAt":"2019-07-26T14:55:15.140Z"},"id":"5d02c48edaae307f03bbb2d2","createdAt":"2019-06-13T21:47:58.994Z","description":"An annual conference for professionals and students that aims to present how innovation and technological progress are transforming the future of life, business, and public policy; placing a special emphasis on the role of Poland as a promising player in this field.","teamMembers":["5d123dde779623001ce3ccbb","5d1253a454b4ab001c190f30","5d123eca779623001ce3ccbe","5d12545454b4ab001c190f33","5d123fbb779623001ce3ccc1","5d2635e2f1da96001c67a7da","5d21d276f1da96001c67a7d5","5d165d06f1da96001c67a7cb","5d12413554b4ab001c190f24","5d1c9b8af1da96001c67a7ce","5d123ccce63d1d001c07f802","5d136f52f1da96001c67a755","5d12427754b4ab001c190f2a","5d2639ddf1da96001c67a7dd","5d1242f054b4ab001c190f2d","5d014320ad5b943400cd8ed7","5d1241ed54b4ab001c190f27"],"year":2019}]
------WebKitFormBoundaryhq66cepwfbJwcDKG
Content-Disposition: form-data; name="__v"

0
------WebKitFormBoundaryhq66cepwfbJwcDKG
Content-Disposition: form-data; name="organisation"

King's College London
------WebKitFormBoundaryhq66cepwfbJwcDKG
Content-Disposition: form-data; name="_id"

5d1253a454b4ab001c190f30
------WebKitFormBoundaryhq66cepwfbJwcDKG
Content-Disposition: form-data; name="id"

5d1253a454b4ab001c190f30
------WebKitFormBoundaryhq66cepwfbJwcDKG
Content-Disposition: form-data; name="email"

bartlomiej.mozdzen@poland20.com
------WebKitFormBoundaryhq66cepwfbJwcDKG
Content-Disposition: form-data; name="linkedin"

https://www.linkedin.com/in/bartlomiej-mozdzen
------WebKitFormBoundaryhq66cepwfbJwcDKG--
```

**Comment by alexandrebodin** [comment] 2019-08-23 12:50
Ok I have tried your app the issue is comin from :your package.json config.

You have locked koa-body on a version that just doesn't work with strapi

The current release of strapi uses koa-body v2.5. 
If you remove this it works just fine
```json
{
  "resolutions": {
    "strapi/**/koa-body": "~4.1.0"
  }
}
```

Just so you know the next release will have koa-body 4.1 so you won't need this resolution anymore ;)

In the meantime if you really need this version of koa-body you can look into sth like: https://stackoverflow.com/questions/43770328/two-versions-of-same-npm-package-in-node-application


I'm closing this issue as it is not strapi related.

**Closed by alexandrebodin** 2019-08-23 12:50 UTC
Labels: priority: high, status: have to reproduce
