### ISSUE TITLE
Can't generate controller

### ISSUE THREAD

**Issue by jezperp** [strapi/strapi#1050] opened 2018-04-26 15:10 UTC
Hello!

I'm trying to generate a controller but it doesn't seem to work, I've tested and successfully generated a api though...

I'm trying to do:
strapi generate:controller hello

It gives me:
error No generator called `controller` found.

**Informations**
- **Node.js version**: v10.0.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.0.1
- **Database**: MySQL
- **Operating system**: macOS High Sierra (10.13.3)

- [x] I'm sure that this issue hasn't already been referenced

**Comment by lauriejim** [comment] 2018-04-26 15:12
Hello @jezperp it's a duplicate of this issue https://github.com/strapi/strapi/issues/644 
You don't take time to check it

**Closed** 2018-04-26 15:12 UTC
Labels: status: duplicate
