### ISSUE TITLE
peer @strapi/strapi@"4.0.0" from @strapi/plugin-users-permissions@4.15.2

### ISSUE THREAD

**Issue by asermoon** [strapi/strapi#18726] opened 2023-11-10 03:07 UTC
### Required System information

- Node.js version: 18
- NPM version: 9
- Strapi version: 4.15.2

<img width="599" alt="截屏2023-11-10 11 05 20" src="https://github.com/strapi/strapi/assets/7497051/8188499d-8b87-4450-9d84-6cb6321c4958">

### Describe the bug

NPM error:
peer @strapi/strapi@"4.0.0" from @strapi/plugin-users-permissions@4.15.2

code: 
https://www.npmjs.com/package/@strapi/plugin-users-permissions?activeTab=code
<img width="488" alt="截屏2023-11-10 11 11 25" src="https://github.com/strapi/strapi/assets/7497051/b096c8c1-bc95-44d6-bdda-a28a98289b8c">

**Comment by asermoon** [comment] 2023-11-10 03:13
Please fix it.

**Comment by joshuaellis** [comment] 2023-11-10 08:50
duplicate of #18706

**Closed by joshuaellis** 2023-11-10 08:50 UTC

**Comment by LucaNerlich** [comment] 2023-11-28 08:02
We are still facing this issue, even on 4.15.5-alpha.6.
The problematic library is `@strapi/plugin-users-permissions` now.
