### ISSUE TITLE
Can't filter by id on MongodDB

### ISSUE THREAD

**Issue by bouhendfaycal** [strapi/strapi#4569] opened 2019-11-21 15:21 UTC
**Describe the bug**
using api filter gives an error :
`Your filters contain a field 'id' that doesn't appear on your model definition nor it's relations`
fo instance something like this url (replacing `id`by `_id` works fine  : 
 - `https://strapiexample.foo/foos?state=active&id=dd664b531e57c0006ea9972`

or via the admin dashboard when using filters :
 - id [is] dd664b531e57c0006ea9972

**Steps to reproduce the behavior**
1. create a fresh installation with mongodb as database
2. create some content type
3. add some data to the content type
4. try using the filter on the dashboard, or give `find` permission to the public user and try the api filter

**System**
- Node.js version: node:10.13.0-alpine
- NPM version: node:10.13.0-alpine
- Strapi version: 17.4
- Database: mongo:latest
- Operating system: docker (gcp VM)

**Comment by n8tb1t** [comment] 2019-11-29 00:05
this is a critical bug!

**Comment by filipinyo** [comment] 2019-12-02 10:59
same problem here!

**Comment by bouhendfaycal** [comment] 2019-12-02 11:03
I had to replace all my API calls with _id for it to work

**Comment by filipinyo** [comment] 2019-12-02 11:08
@bouhendfaycal thank you! It seems to be working this way 👍

**Comment by alexandrebodin** [comment] 2020-01-07 10:36
Hi,

I cannot reproduce with the latest version (beta.18.4). Can you try this again ? 

I'll close it until then. Thanks

**Closed by alexandrebodin** 2020-01-07 10:36 UTC
Labels: priority: low, status: confirmed, type: bug 🐛

**Comment by derrickmehaffy** [comment] 2020-01-07 10:38
> Hi,
> 
> I cannot reproduce with the latest version (beta.18.4). Can you try this again ?
> 
> I'll close it until then. Thanks

Think you mean beta.18.3 :stuck_out_tongue_closed_eyes:
