### ISSUE TITLE
Videos can't be selected

### ISSUE THREAD

**Issue by paddotk** [strapi/strapi#15041] opened 2022-11-30 09:30 UTC
### Required System information
- Node.js version: not relevant
- NPM version: not relevant
- Strapi version: 4.4.3
- Database: not relevant
- Operating system: Windows 10

### Describe the bug
Videos (from the media library) can't be selected to be used anywhere in the Content Manager. The 'thumbnail' is the actual video, and this overlays the checkbox that you need to click.

### Steps to reproduce the behavior
1. Upload a video to the media library
2. Have a component somewhere where a file can be selected (in the Content Manager)
3. Try to select the video. You'll enter edit mode for the file instead of selecting it.

**Notes:**
- This issue does not occur in development mode (locally)
- This issue does not occur with images
- If you open the prompt to select a file and then choose 'Add more assets', then upload the file, it gets selected after uploading automatically, therefore it's possible to use it. But only then and there.
- If you go to the media library from the menu, you can also select the video (it's positioned _under_ the checkbox)

### Expected behavior
I should be able to select the video to use.

**Comment by paddotk** [comment] 2022-12-16 09:49
@gu-stav Here's one:
https://user-images.githubusercontent.com/11683974/208071081-924e30b2-b4ac-41ac-9e85-db32754d227b.mp4

PS in this video, I added a white overlay to the images in the main folder (for privacy reasons), so that's not a bug.

**Comment by joshuaellis** [comment] 2022-12-16 10:07
hey @paddotk, i've just checked this out in the same way but I can't seem to reproduce it. How did you upload the video? It seems weird that it's not got a preview or duration – have you tried deleting that asset and re-uploading? 🤔

**Comment by derrickmehaffy** [comment] 2022-12-27 20:55
I'm going to close this in favor of https://github.com/strapi/strapi/issues/15275 since there is more reproduction information here.

CC @joshuaellis

**Closed by derrickmehaffy** 2022-12-27 20:55 UTC
Labels: issue: bug, severity: low, status: can not reproduce, source: core:upload

**Comment by paddotk** [comment] 2023-01-10 10:22
@joshuaellis Sorry, I've missed your response it seems.
I tried both uploading directly in the Media Library as well as in the Content Manager (add asset > 'Add more assets' > select video), and when deleting and re-uploading it doesn't work either.
This happens on different videos (though I think I only tried with .mp4).
