### ISSUE TITLE
Deleting and Creating a new field with different expected type causes issues

### ISSUE THREAD

**Issue by jaszczw** [strapi/strapi#9324] opened 2021-02-05 13:20 UTC
### Describe the bug

Once you have a text field in a 'content-type' for example 'category' and you have had already put some data in it,  a change to a data structure that removes it and replaces it with a relation with the same name to a new content type (for example categories), will cause the whole content-type to fail.

### Steps to reproduce the behavior

1. Create Content-Type "Articles" with text field "category"
2. Create some articles that have 'category' filled
3. Create Content-Type "Categories"
4. Replace text field "category" in "Articles" with a relation to "categories"
5. All request to "Articles" begin to fail as a type of column mismatch

#### Best case
Ask user if the column should be replaced

#### Good Enough
At least a warning that column like that exists and it may cause issues

### Screenshots

![image](https://user-images.githubusercontent.com/1790627/107038254-8783b380-67bc-11eb-8c34-3cbc4aee1943.png)
![image](https://user-images.githubusercontent.com/1790627/107038310-9b2f1a00-67bc-11eb-9856-fd410a46cb89.png)

### Error outputs

```
"select distinct \"categories\".* from \"categories\" where (\"categories\".\"published_at\" is not null) and \"categories\".\"id\" in ($1, $2) - invalid input syntax for type integer: \"recipies\"",
```

```
error error: invalid input syntax for type integer: "recipes"
```

### System

- Node.js version: v12.20.1
- NPM version: 6.14.10
- Strapi version: 3.4.5
- Database: PostgreSQL
- Operating system: Ubuntu/Docker image (strapi/strapi)

**Comment by derrickmehaffy** [comment] 2021-02-05 19:58
Duplicate of: #1114

**Closed by derrickmehaffy** 2021-02-05 19:58 UTC
Labels: status: duplicate
