### ISSUE TITLE
yarn/npx create-strapi-app not working with Mongo

### ISSUE THREAD

**Issue by GeFeSTTS** [strapi/strapi#8243] opened 2020-10-08 11:44 UTC
**Describe the bug**
yarn/npx create-app project-name is not working with Mongo.

**Steps to reproduce the behavior**

Try to create a fresh install with Mongo

**Expected behavior**
⛔️ Connection test failed: Command failed: yarnpkg --cwd /tmp/strapi98374ae1d282 add strapi-connector-mongoose@3.2.1
error An unexpected error occurred: "https/strapi-connector-mongoose: Invalid URI \"https/strapi-connector-mongoose\"".

**Screenshots**
![Screenshot from 2020-10-08 14-34-10](https://user-images.githubusercontent.com/43075229/95454126-b2780b00-0974-11eb-831b-e2b27a4e080b.png)

**System**

- Node.js version: 12.10.0
- NPM version: 6.10.3
- Database: Mongo
- Operating system: Ubuntu 18.04.5

**Additional context**

**Comment by lemarcgagnon** [comment] 2020-10-08 12:29
I exactly have the same issues, I tried every otpions mysql, postgree, mongo and still I get :

Cannot find module '/tmp/strapi4927787ad3b3/node_modules/strapi-connector-mongoose/lib/utils/connectivity.js'
Require stack:
- /usr/local/share/.config/yarn/global/node_modules/strapi-generate-new/lib/create-customized-project.js
- /usr/local/share/.config/yarn/global/node_modules/strapi-generate-new/lib/generate-new.js
- /usr/local/share/.config/yarn/global/node_modules/strapi-generate-new/lib/index.js
- /usr/local/share/.config/yarn/global/node_modules/create-strapi-app/create-strapi-app.js
- /usr/local/share/.config/yarn/global/node_modules/create-strapi-app/index.js

I have strapi-connector-mongoose installed a few places in the computer for npx and yarn, updated, upgrade everything.. still!

node -v : 12.13.1
npm -v : 6.14.5
Database: every one bugs but Sqlite
linux Mint 19.3


I yarned it, npxed it, researched a lot, tried all sort of things but this still comes back : Cannot find module '/tmp/strapi4927787ad3b3/node_modules/strapi-connector-mongoose/lib/utils/connectivity.js'

tried on 2 mint linux computer, still no success

**Comment by derrickmehaffy** [comment] 2020-10-08 14:30
Do you have the `strapi` package installed globally? try a `which strapi`

(I can't reproduce this on Linux Mint 20)

**Comment by GeFeSTTS** [comment] 2020-10-08 14:32
> Do you have the `strapi` package installed globally? try a `which strapi`
> 
> (I can't reproduce this on Linux Mint 20)

don't have installed globally

**Comment by GeFeSTTS** [comment] 2020-10-08 14:54
Installed strapi globally (version: 3.2.1), but issue still reproducing

**Comment by derrickmehaffy** [comment] 2020-10-08 15:04
Sorry I should of clarified, you should not have it installed globally. Based on your logs there is something coming from the yarn global node_modules.

In your case I'm guessing there is a conflict in your package cache :thinking: can you try `npx create-strapi-app@latest test-project` (key part being the `@latest` as that will force npx to check and regrab the package)

**Comment by GeFeSTTS** [comment] 2020-10-08 15:21
Tried to use `npx create-strapi-app@latest test-project` but it didn't help to me. Also tried to reinstall yarn.

**Comment by derrickmehaffy** [comment] 2020-10-08 17:49
We will need more information to attempt to reproduce @GeFeSTTS 

I don't think this is an issue with Strapi directly but is likely within your user environment.

**Comment by lemarcgagnon** [comment] 2020-10-08 19:48
Question:  I would like to verify the chmod rights... where exactly is this comment happening?

Command failed: yarnpkg --cwd /tmp/strapi1bc6ec512d6b add strapi-connector-mongoose@3.2.1
error Could not write file

in which directory is this strapi  /tmp/ happening?

**Comment by lemarcgagnon** [comment] 2020-10-08 20:06
I see that the rights for my /tmp are
drwxrwxrwt  27 root root       620 Oct  8 21:59 tmp

and I also see that Yarn tries to write in that directory for creating mongo setup
drwxrwxr-x  2 marc marc   80 Oct  8 21:59  yarn--1602187187277-0.3407319777476321

Could that be causing erros in building mongodb based strapi? since I always get that error:

Connection test failed: Command failed: yarnpkg --cwd /tmp/strapi559004466d69 add strapi-connector-mongoose@3.2.1
error Could not write file "/yarn-error.log": "EACCES: permission denied, open '/yarn-error.log'"
error An unexpected error occurred: "EACCES: permission denied, unlink '/node_modules/.yarn-integrity'".

**Comment by derrickmehaffy** [comment] 2020-10-08 20:18
Uhhhh `/tmp` should be writable by everyone, it's a global temporary directory that is flushed on a reboot used to temp store any kind of cache. That issue isn't a Strapi one but more so a yarn one / bad permissions on your `/tmp`

https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/tmp.html

https://superuser.com/questions/153716/should-tmp-be-owned-by-root#:~:text=It%20should%20be%20owned%20by,remove%20or%20rename%20the%20file.

**Comment by derrickmehaffy** [comment] 2020-10-08 20:19
(I should clarify about the sticky bit on that directory, it should be writable by anyone creating a new file, but only writable on a file inside of it by the user who created said file)

**Comment by GeFeSTTS** [comment] 2020-10-08 20:45
Found that my issue is related to yarn, but i don't know why it's comming when i using npmx (not yarn).
![Screenshot from 2020-10-08 23-43-47](https://user-images.githubusercontent.com/43075229/95511612-5c30b980-09c0-11eb-8c1c-81f3543d1043.png)

**Comment by GeFeSTTS** [comment] 2020-10-08 21:01
Ok, guys, i solved my problem. It's not related to strapi and other problems. Some times ago for publishing package to github i changed npm registri config and set it to 'http'. So fix of this problem is `npm config set registry '""`. Sorry for u'r time and thanks at all

**Comment by derrickmehaffy** [comment] 2020-10-08 21:29
Ah no problem @GeFeSTTS thank you for confirming, marking as closed.

**Closed by derrickmehaffy** 2020-10-08 21:29 UTC
Labels: status: can't reproduce, type: help wanted

**Comment by lemarcgagnon** [comment] 2020-10-09 07:21
what does bookshelf do that the others don't.  Because creating an app in Sqlite works every times but all the others don't.  what do they all require - common factor - that creates a problem on my platform?

Yours,

Marc

**Comment by derrickmehaffy** [comment] 2020-10-09 16:08
@lemarcgagnon SQLite is just a file, there is no service it's connecting to, the entire database is just being read and written to as a single file. Other options require a service to be installed and running that operate on a higher level and are more complex (require auth, ect)

**Comment by lemarcgagnon** [comment] 2020-10-12 08:18
Hello!  So I finally decided to rebuild my linux Mint 20 system rather than spend another day on this issue.  Thanks for the support and help.

now it works perfectly fine.

Marc

**Comment by derrickmehaffy** [comment] 2020-10-13 17:42
Awesome glad to hear @lemarcgagnon
