### ISSUE TITLE
Database migration does not recreate user roles correctly

### ISSUE THREAD

**Issue by halfsoft** [strapi/strapi#5733] opened 2020-04-07 14:23 UTC
**Describe the bug**
After moving from sqlite to a mysql database (an empty one), the tables are recreated correctly, however the default user roles are not created correctly, the public role permission list is empty (no models in Application, unless you create a new content type, which gets added).

**Steps to reproduce the behavior**
1. Create a new strapi instance, create 2-3 content types
2. delete the database tables completely and rerun the application
3. create a new admin account and enter the admin area, in the roles tab the public user doesn't have any permissions available to set

**Expected behavior**
Populating the empty DB should recreate the controller permissions correctly.

**Screenshots**
N/A

**Code snippets**
N/A

**System**
- Node.js version: 13.12.0
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.19.5
- Database: mysql
- Operating system: linux(ubuntu)

**Additional context**
Had to enter the db and run manual queries to recreate the missing controller permissions in *users-permissions_permission*

**Comment by alexandrebodin** [comment] 2020-04-07 14:25
Hi, this issue is clearly a duplicate of https://github.com/strapi/strapi/issues/4045. Closing this one so we can keep track of it in one single issue.

**Closed by alexandrebodin** 2020-04-07 14:25 UTC

**Comment by halfsoft** [comment] 2020-04-07 14:31
In the referenced issue people are reporting that the issue is fixed after a restart of the instance (and they have to set again the permissions).
In my case the permissions were never recreated after restart or rebuild (both in development and in production mode)

**Comment by alexandrebodin** [comment] 2020-04-07 14:34
You can comment in this issue so we have the info there ot fix it once.
