### ISSUE TITLE
Error executing DELETE

### ISSUE THREAD

**Issue by junioreuripedes** [strapi/strapi#3120] opened 2019-04-12 13:33 UTC
**What is the current behavior?**
Executando o metodo DELETE esta aparecendo erro com a coluna "id" que não existe no MySQL.

In MySQL the column "id" is represented by the column "CO_VENDA_MESA".

The Strapi (version v3.0.0-alpha.25.2) by what I understood is trying to consult this column id that does not exist not my base, this made all the changes to change that column as I found in the documentation.

**Steps to reproduce the problem**
> [2019-04-11T13:56:21.138Z] debug GET /mesas (73 ms)
> Error: Undefined binding(s) detected when compiling SELECT query: select tb_venda_mesa.* from tb_venda_mesa where tb_venda_mesa.id = ? limit ?
> at QueryCompiler_MySQL.toSQL (/Applications/MAMP/htdocs/esysconsultoria/esyscloud/strapi/node_modules/knex/lib/query/compiler.js:85:13)
> at Builder.toSQL (/Applications/MAMP/htdocs/esysconsultoria/esyscloud/strapi/node_modules/knex/lib/query/builder.js:72:44)
> at /Applications/MAMP/htdocs/esysconsultoria/esyscloud/strapi/node_modules/knex/lib/runner.js:37:34
> From previous event:
> at Runner.run (/Applications/MAMP/htdocs/esysconsultoria/esyscloud/strapi/node_modules/knex/lib/runner.js:33:30)
> at Builder.Target.then (/Applications/MAMP/htdocs/esysconsultoria/esyscloud/strapi/node_modules/knex/lib/interface.js:23:43)
> at processImmediate (timers.js:638:19)
> at process.topLevelDomainCallback (domain.js:136:23)
> [2019-04-11T13:56:29.089Z] debug DELETE /mesas/15 (10 ms)

**What is the expected behavior?**
**[Archive Mesa.settings.json]**
> {
> "connection": "teste",
> "collectionName": "tb_venda_mesa",
> "info": {
> "name": "mesa",
> "description": "Tabela de Venda Mesa."
> },
> "options": {
> "increments": true,
> "timestamps": false,
> "comment": "",
> "idAttribute": "CO_VENDA_MESA",
> "idAttributeType": "integer"
> },
> "attributes": {
> "CO_VENDA_MESA": {
> "default": "",
> "unique": true,
> "type": "integer",
> "required": true
> },
> "DT_CADAS": {
> "default": "",
> "type": "date",
> "required": true
> },
> "NU_MESA": {
> "default": "",
> "maxLength": 20,
> "unique": true,
> "type": "string",
> "required": true
> },
> "ST_MESA": {
> "default": "",
> "maxLength": 1,
> "type": "string",
> "required": true
> }
> }
> }

**[Archive routes.json]**
> {
> "routes": [
> {
> "method": "GET",
> "path": "/mesas",
> "handler": "Mesa.find",
> "config": {
> "policies": []
> }
> },
> {
> "method": "GET",
> "path": "/mesas/count",
> "handler": "Mesa.count",
> "config": {
> "policies": []
> }
> },
> {
> "method": "GET",
> "path": "/mesas/:CO_VENDA_MESA",
> "handler": "Mesa.findOne",
> "config": {
> "policies": []
> }
> },
> {
> "method": "POST",
> "path": "/mesas",
> "handler": "Mesa.create",
> "config": {
> "policies": []
> }
> },
> {
> "method": "PUT",
> "path": "/mesas/:CO_VENDA_MESA",
> "handler": "Mesa.update",
> "config": {
> "policies": []
> }
> },
> {
> "method": "DELETE",
> "path": "/mesas/:CO_VENDA_MESA",
> "handler": "Mesa.destroy",
> "config": {
> "policies": []
> }
> }
> ]
> }

**Comment by derrickmehaffy** [comment] 2019-04-12 13:36
Please do not create duplicate issues, update your existing one with the proper template and it can be reopened.

Closing as duplicate of: https://github.com/strapi/strapi/issues/3117

**Closed by derrickmehaffy** 2019-04-12 13:36 UTC

**Comment by derrickmehaffy** [comment] 2019-04-12 13:37
Por favor, não crie problemas duplicados. Atualize seu existente seguindo o modelo de relatório de bug apropriado e ele pode ser reaberto
