### ISSUE TITLE
Plugin - Content Internalization

### ISSUE THREAD

**Issue by BroTrue** [strapi/strapi#1507] opened 2018-07-02 17:23 UTC
Hello everyone, in Strapi Road Map found this Feature "Plugin - Content Internalization". And I got question and when it will be developed? Maybe someone already started?

Expected behavior:

Translate the content of your API in any language, from the admin panel.

**Comment by maru3l** [comment] 2018-07-02 17:44
I'm actually working on something. The way a see it's to make a entry of the same content type for each language and link them together with a relation.

**Comment by BroTrue** [comment] 2018-07-02 18:16
@maru3l can I take a look? some exaples etc.? it will be great if you can :)

**Comment by maru3l** [comment] 2018-07-02 18:45
The test I've made is only to create a relation and a select field in the entry. I use the select to select the language and the relation to relate the article. It's working perfectly.

What I'm working on, it's to make a plugin who automatically create they's field, make it invisible and add a widget in the creation page to make the link between the post easier.

**Comment by BroTrue** [comment] 2018-07-03 16:29
Maybe Strapi Team can tell us ,when it will be developed?  ;)

**Comment by lauriejim** [comment] 2018-07-04 09:03
There is no date for this feature. We will not work on it for next months.

**Comment by maru3l** [comment] 2018-07-06 18:51
@Aurelsicoko I've already spoke to Pierre a weeks ago to explain my idea, but I'm still open to get more information or giving help to make this feature append. It's a must have for my client and I can't make them use Strapi if this feature is not available.

The only thing blocking me right now it's because I have to edit the content-manager package for adding my widget. But I know it's not a good adea to write directly in it if someone change the package after.

**Comment by joonashak** [comment] 2018-07-27 09:37
I'm currently developing a bilingual website using Strapi as my backend. I'm using a similar approach, namely storing two entries, one for each language and linking them with a one-to-one relation. However, the content type builder forces me to define two relational fields when linking a Page item to another Page item. I didn't want to file a bug report straight away, but currently I'm thinking that this is incorrect behaviour. As one-to-one links one and only one document to another, wouldn't it be simpler and more elegant to have only one field?

Example:

Say we have a Page document called A in English and want to create a corresponding document B in Finnish.

Expected behaviour:

Create a one-to-one relation that links two Page entries. Only one field should suffice for this type of linking, thus it is expected that one would be able to create the relation and express it in a single field called translation (in the example case). A.translation would then contain B and B.translation would contain A.

Current behaviour:

Content type builder forces me to create two fields with unique names when creating the Page-to-Page relation. E.g., I could have fields translation and translationLink, both of which express the exact same relation. The result is that unnecessary code is required to check both fields where one would be enough (or have the user or another piece of code populate both "directions", i.e., all four fields).

Is my reasoning correct, and if so, should I file a separate bug report or feature request?

**Comment by MartinMuzatko** [comment] 2018-08-15 22:03
To point out the elephant in the room: Did somebody try the paid i18n plugin?
Does it do what it claims?
There is an item on the roadmap marked as not done and there is the plugin in the [marketplace](https://strapi.io/marketplace/internationalization).
I personally think it is a must for a good CMF to have open source I18n.

**Comment by Aurelsicoko** [comment] 2018-08-17 12:31
@MartinMuzatko The i18n plugin is available on the marketplace but you won't be charged for it because it's not developed yet. It helps us to know if the plugin is requested or not.

As I already said, we can't offer all the features for free. We have to find a way to make the OSS sustainable. If we offer everything for free, the project is going in the wrong direction and it'll certainly die in a few years. A lot of enterprises, web-agencies or startups are using Strapi and they are able to pay for some features. We're trying to do our best to build a smart business model. As an OSS it's complicated for us to charge based on the usage (requests/s for example) so we have an approach based on the features offered for now. Everything can change, we're listening to the feedback to find the perfect match between the community version and the paid version of Strapi.

**Comment by MartinMuzatko** [comment] 2018-08-17 20:03
@Aurelsicoko I'm not saying charging for plugins is wrong. I just wanted to know what the exact difference is, because there is the (not yet) paid version which claims to "translate everything instantly" which is a bit unclear. it sounds like it would do like the community plugin for i18n. So you can imagine there is some confusion. Thanks anyway, I'm sure you will find a good way to monetize strapi :) just keep your nice community and your healthy way of getting in touch with your userbase.

**Comment by Aurelsicoko** [comment] 2018-09-07 14:08
I'm talking about the exact same plugin. There will be only one i18n plugin which will be available through the Premium plan for now. This is our goal to keep our nice community (<3) and stay accessible to everyone. 

We're trying to educate everyone that "open-source" doesn't mean "free". There is always a cost behind each feature (hours of design, development, communication, maintenance, etc). If something is free for you, someone paid for it.

**Comment by derrickmehaffy** [comment] 2018-09-07 16:29
*Sarcasm* Wait you mean not all "Open-Source" projects are FOSS? (Free & Open Source Software)

Jokes aside I agree that the plugins should be monetized @Aurelsicoko but at the same time I do like the road that RedHat takes with their software. Obviously at this stage that isn't really an option for Strapi as you don't really have a "Commercial"  business model yet to provide "support" for. Maybe one day.

However the problem I do see right now is after Strapi has built the plugins and released them, no one can help contribute to them unless they have already paid for them. And that is of course if we are given the source code at that point. If the plugins are packaged in such a way that we can't see the source, then the only way bugs or improvements can be made is by the Strapi team themselves.

Chicken or Egg problem :stuck_out_tongue:

**Comment by z-ax** [comment] 2018-09-07 17:07
I did this kind of Internalization for my CMS in a very simple way.
1. In field's meta boolean flag if there is one.
2. If there is, it's content is a JSON where key is a locale (in my case ISO 639-1 code) and value is a string. If there is no value by some locale - use main locale (which is required).
3. Where JSON type of fields is not supported, JSON is stringified (not the best performance then, but still works great and easy to maintain).

**Comment by Aurelsicoko** [comment] 2018-11-08 14:11
I'm closing this issue to keep the repository as clear as possible. We're moving the feature request on Product Board. Please refers to this card (https://portal.productboard.com/strapi/c/19-content-internationalization) about the content internationalization. Feel free to give us more insights and examples using Product Board.

**Closed by Aurelsicoko** 2018-11-08 14:11 UTC
Labels: priority: medium, type: feature request 🙏

**Comment by kgrosvenor** [comment] 2019-10-24 11:43
Suppose it's just a simple where query on a list of locales, and then if user adds locale in the URL it should filter the content like any other filter does, it's just that locale should be added automatically on the backend and then we can select which locale it belongs too, in essence you can kind of already do this, it's just that the filter UI is not intuitive and does not load the select options, you have to type them in everytime

**Comment by sheinzle** [comment] 2020-08-11 11:26
What is the status on content internationalization? We're currently evaluating different CMS'es, and i18n for content is a crucial component.

As a side note: we're a software development agency and would be more than happy to pay to use that feature.

**Comment by derrickmehaffy** [comment] 2020-08-11 14:35
From @Aurelsicoko on the slack:

Hey everyone, I hope you are all doing well :pray:
We've started working on the Internationalization feature to easily translate your content in multiple languages (locales). As you might know to make sure we will develop the right feature that fits your needs, we are used to run a survey.
Could you please take 3 minutes of your time to fill in it?

https://strapi.typeform.com/to/kJRitLiK

Thank you very much!

**Comment by lauriejim** [comment] 2020-09-29 07:20
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/internationalization/169/2
