### ISSUE TITLE
Strapi fails to save models with not null attribute on foreign key columns

### ISSUE THREAD

**Issue by harshilsharma63** [strapi/strapi#556] opened 2018-02-01 12:51 UTC
**Node.js version**: 8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.9

**Operating system**: Ubuntu 16.04 x64

Additional details -

 **Database being used**: PostgreSQL 9.5.10

**Do you want to request a *feature* or report a *bug*?**
Bug

Consider a table `pet` with column `name` and `owner_id` referencing `owner.id`. On creating a new pet, strapi makes two database queries - first, to insert `pet.name` (and other non-referential columns if they exist), second, to insert foreign key ids.

See logs below -
```
2018-02-01 17:57:39 IST [31111-6] harshilsharma@strapi LOG:  execute <unnamed>: insert into "pet" ("name") values ($1) returning "id"
2018-02-01 17:57:39 IST [31111-7] harshilsharma@strapi DETAIL:  parameters: $1 = 'pet1'
2018-02-01 17:57:39 IST [31111-8] harshilsharma@strapi LOG:  execute <unnamed>: select "pet".* from "pet" where "pet"."id" = $1 limit $2
2018-02-01 17:57:39 IST [31111-9] harshilsharma@strapi DETAIL:  parameters: $1 = '3', $2 = '1'
2018-02-01 17:57:39 IST [31111-10] harshilsharma@strapi LOG:  execute <unnamed>: update "pet" set "id" = $1, "name" = $2, "owner_id" = $3 where "id" = $4
2018-02-01 17:57:39 IST [31111-11] harshilsharma@strapi DETAIL:  parameters: $1 = '3', $2 = 'pet1', $3 = '1', $4 = '3'
```

However if we have `not null` constraint on a foreign key column, the first query fails due to not null constraint. See logs below -
```
2018-02-01 18:13:04 IST [31845-79] harshilsharma@strapi LOG:  execute <unnamed>: insert into "pet" ("name") values ($1) returning "id"
2018-02-01 18:13:04 IST [31845-80] harshilsharma@strapi DETAIL:  parameters: $1 = 'pet4'
2018-02-01 18:13:04 IST [31845-81] harshilsharma@strapi ERROR:  null value in column "owner_id" violates not-null constraint
2018-02-01 18:13:04 IST [31845-82] harshilsharma@strapi DETAIL:  Failing row contains (6, pet4, null).
2018-02-01 18:13:04 IST [31845-83] harshilsharma@strapi STATEMENT:  insert into "pet" ("name") values ($1) returning "id"
```

**If the current behavior is a bug, please provide the steps to reproduce the problem**
1. Create two tables - I'll call them `pet` and `owner`; with `pet.owner_id` referencing `owner.id`.
1. Add `not null` constraint on `pet.owner_id`.
1. Add `pet` and `owner` to Strapi.
1. Create an `owner`.
1. Create a new `pet` and try saving it.

**What is the current behavior?**
Newly created pet fails to be saved.

**What is the expected behavior?**
Newly created pet is successfully saved.

**Comment by Aurelsicoko** [comment] 2018-02-06 09:55
@harshilsharma63 Thank you for raising this issue! Right now, the only solution is to remove this `NOT NULL` condition.

**Comment by harshilsharma63** [comment] 2018-02-06 10:59
@Aurelsicoko  yeah, that's what I've done right now.

**Comment by lauriejim** [comment] 2018-07-01 13:51
@harshilsharma63 can you tell me if this issue still happen with last version of Strapi ?

**Comment by lauriejim** [comment] 2018-07-19 14:09
I am closing this issue because we don’t have any update/needed informations about it.

**Closed by lauriejim** 2018-07-19 14:09 UTC
Labels: priority: low, status: need informations, type: bug 🐛

**Comment by ikesler-tenengroup** [comment] 2019-09-18 07:30
It is still an issue in 3.0.0-beta.11

**Comment by derrickmehaffy** [comment] 2019-09-18 07:32
@ikesler-tenengroup please test with the latest strapi version (beta.16.4)

**Comment by ikesler-tenengroup** [comment] 2019-09-18 09:03
> @ikesler-tenengroup please test with the latest strapi version (beta.16.4)

the same: `null value in column "category_type" violates not-null constraint` in my specific case

**Comment by cadavre** [comment] 2019-12-11 07:59
Confirmed that it still happens in 3.0.0-beta.17. Used with Postgres.

**Comment by bwsalmon** [comment] 2019-12-14 07:42
I'm seeing this as well.

**Comment by yulafezmesi** [comment] 2020-07-18 11:48
Is there any solution for this case. I couldn't find any answer.

**Comment by alexey-yunoshev** [comment] 2020-08-04 21:16
This is the line that causes the error for me:
https://github.com/strapi/strapi/blob/ab77f264ae08c4862205113eafcac452f766d4b6/packages/strapi-connector-bookshelf/lib/relations.js#L398
@alexandrebodin Could you please explain why `deleteRelations` is important? I removed it and eveything seemed to work fine. If my company decides to use Strapi, I migth try and help fix it.

**Comment by derrickmehaffy** [comment] 2020-08-04 22:46
@yulafezmesi can you please open up a new bug report and follow the template, this bug report is quite old and the information from previous responses no longer applies.
