### ISSUE TITLE
filling from another locale doesn't copy relational fields and keep them empty

### ISSUE THREAD

**Issue by Rabih-Alhousein** [strapi/strapi#14499] opened 2022-09-29 20:02 UTC
### Describe the bug:
I am using the "fill from another locale" feature to duplicate the content of the pages in different locales and to make small changes to the content of the other locale, it is working well except for relational fields, it keeps them empty even if the content of the relation field has content in the new locale.

**for example :** 
In Products collection type, we have two relations: 
one to one with tab( category) collection
and  one-to-many with sub-products collection
and this is an example from Products Collection:

![image](https://user-images.githubusercontent.com/93277394/193128977-097faeb8-5e41-4abf-8e5e-2a07e9fdb994.png)

now if we switch to English-Egypt(en-EG) locale and fill from another locale English(en) it will copy everything except for relational fields (tab and sub-products), they will stay empty: 
![image](https://user-images.githubusercontent.com/93277394/193129213-27be49bb-ed0c-417e-84ab-a4b90424f7c2.png)

even if we have them created before in English-Egypt(en-EG) locale 

**expected behaviour:** 
it should copy all the content from the other locale, even for relational fields  but from the new locale (selected locale), only if the content is created before in the new locale:

![image](https://user-images.githubusercontent.com/93277394/193129593-d918ba5a-53ad-4faf-bbee-aae564a7dd52.png)

 and it should keep it empty only if the relation doesn't have content in the new locale 

### Required System information: 
Node.js version: 14.17.2
NPM version: 6.14.13
Strapi version: 4.1.12
Database: MariaDB
Operating system: Windows 11

**Comment by gu-stav** [comment] 2022-10-18 08:16
Closing as duplicate of https://github.com/strapi/strapi/issues/14337

**Closed by gu-stav** 2022-10-18 08:16 UTC
