### ISSUE TITLE
Many peer dependencies umet versions in 4.15.2 release, such as @strapi/plugin-users-permissions

### ISSUE THREAD

**Issue by smoothdvd** [strapi/strapi#18712] opened 2023-11-09 00:55 UTC
### Required System information

- Node.js version: 20.x
- NPM version:
- Strapi version: 4.15.2
- Database: PostgreSQL 
- Operating system: macOS / Linux
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Many peer dependencies umet versions in 4.15.2 release, such as @strapi/plugin-users-permissions.

in the source code, package.json file:

```
"devDependencies": {
    "@strapi/pack-up": "workspace:*",
    "@strapi/strapi": "4.15.1",
    "@testing-library/dom": "9.2.0",
    "@testing-library/react": "14.0.0",
    "@testing-library/user-event": "14.4.3",
    "msw": "1.3.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3"
  },
  "peerDependencies": {
    "@strapi/strapi": "4.0.0",
    "react": "^17.0.0 || ^18.0.0",
    "react-dom": "^17.0.0 || ^18.0.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3"
  },
```

### Steps to reproduce the behavior

1. Check file: packages/plugins/users-permissions/package.json

### Expected behavior

Resolve umet warning

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by dgrebb** [comment] 2023-11-09 03:05
@smoothdvd discussion in #18706 as well.

**Comment by kevinblanco** [comment] 2023-11-09 03:18
Same issue here, it seems it will be fixed on next release, for now we need to use -`-legacy-peer-deps` to bypass the issue.

**Comment by joshuaellis** [comment] 2023-11-09 06:57
Duplicate of #18706

**Closed** 2023-11-09 06:57 UTC
Labels: status: duplicate
