### ISSUE TITLE
v4.0.1 u. v4.0.2 Webpack Error when running npm run build --clean after upgrade

### ISSUE THREAD

**Issue by ThunderAnimal** [strapi/strapi#12000] opened 2021-12-22 17:55 UTC
### Describe the bug 
Can't _npm run build --clean_ after upgrade to strapi **4.0.1 or 4.0.2**.

Error: TypeError: The 'compilation' argument must be an instance of Compilation
Stacktrace
```
at Function.getCompilationHooks (E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\webpack\lib\javascript\JavascriptModulesPlugin.js:141:10)
    at E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\terser-webpack-plugin\dist\index.js:566:67
    at _next33 (eval at create (E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:44:1)
    at _next11 (eval at create (E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:123:1)
    at Hook.CALL_DELEGATE [as _call] (E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\@strapi\admin\node_modules\webpack\lib\Compiler.js:1031:26)
    at E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\@strapi\admin\node_modules\webpack\lib\Compiler.js:1073:29
    at Hook.eval [as callAsync] (eval at create (E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\@strapi\admin\node_modules\webpack\lib\Compiler.js:1068:28)
    at E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\@strapi\admin\node_modules\webpack\lib\Compiler.js:496:12
    at Compiler.readRecords (E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\@strapi\admin\node_modules\webpack\lib\Compiler.js:908:11)
    at E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\@strapi\admin\node_modules\webpack\lib\Compiler.js:493:11
    at Hook.eval [as callAsync] (eval at create (E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\Entwickl\wedding-elli-stefan\wedding-elli-stefan_server\node_modules\tapable\lib\Hook.js:18:14)
```

### Steps to reproduce the behavior

1. Change Strapi Version in the package.json to 4.0.1 or. 4.0.2
2. Delete the *lock and node_modules folder
3. run npm i 
4. run npm run build --clean

### Screenshots

![image](https://user-images.githubusercontent.com/6366929/147134714-eb261631-8f04-46af-a1b4-abfe567838e7.png)

### System

- Node.js version: v16.13.1
- NPM version: 8.1.2
- Operating system: Windows [Version 10.0.19043.1415]

**Comment by Webbist-dev** [comment] 2021-12-22 17:56
Use Yarn instead, shouldn't, I know this isn't helpful to npm specific users but yarn worked fine for me.

**Comment by ThunderAnimal** [comment] 2021-12-22 18:03
@Webbist-dev , wow thx for the fast help.
Indeed, with yarn it works fine now.

I'm so used to run npm i, that i totally forgot thee yarn alternative.

**Comment by Pablo-Aldana** [comment] 2021-12-29 20:36
I have the same issue using yarn build

**Comment by kwiat1990** [comment] 2021-12-30 11:38
Is there any fix for this? I have also got this error while updating from 4.0.0 to 4.0.2.

**Comment by soupette** [comment] 2021-12-30 11:57
I can confirm the issue, we are looking into it but I am not sure where it is coming from.

**Comment by kbertalan** [comment] 2021-12-30 14:36
@soupette As I remember a colleague of mine saw this issue before and he said that adding terser-webpack-plugin to the depdencies will produce a more meaningful error message. I hope this is still true and helps the troubleshooting.

**Comment by dp50mm** [comment] 2021-12-30 16:07
Was getting the same build errors as well from a fresh create-strapi-app install on M1 mac, intel mac and on DigitalOcean app service. Tried with both npm & yarn which gave the same error.
Was able to resolve them by adding terser-webpack-plugin:

`npm install terser-webpack-plugin`

and then had to install missing depencency for @strapi/design-system

`@strapi/design-system`

After this was able to successfully build with npm.
Ideally a build command from a fresh boilerplate install should work out of the box.

Hope this information helps resolve the issue!

**Comment by kwiat1990** [comment] 2022-01-01 14:59
> I can confirm the issue, we are looking into it but I am not sure where it is coming from.
> 
> @kwiat1990 can you try using yarn it works on my side.

There is already an issue for this very error: [The 'compilation' argument must be an instance of Compilation - Upgrade from 4.0.0 to 4.0.2](https://github.com/strapi/strapi/issues/12030) and it seems like using `yarn` one also can't build the admin panel.

I have tried the solution from @dp50mm and after installing both packages (`terser-webpack-plugin` and `@strapi/design-system`) I was able to build the admin panel but I don't think it's the right way of doing things to make strapi work.

**Comment by derrickmehaffy** [comment] 2022-01-03 11:45
> > I can confirm the issue, we are looking into it but I am not sure where it is coming from.
> > @kwiat1990 can you try using yarn it works on my side.
> 
> There is already an issue for this very error: [The 'compilation' argument must be an instance of Compilation - Upgrade from 4.0.0 to 4.0.2](https://github.com/strapi/strapi/issues/12030) and it seems like using `yarn` one also can't build the admin panel.
> 
> I have tried the solution from @dp50mm and after installing both packages (`terser-webpack-plugin` and `@strapi/design-system`) I was able to build the admin panel but I don't think it's the right way of doing things to make strapi work.

Yes you are correct, the issue is the missing @strapi/design-system package. We are looking into it.

**Comment by soupette** [comment] 2022-01-03 13:42
Well the packages are installed but not in the correct folder when using npm, I still don't know why...

I managed to get it to work by installing the latest version of the `terser-webpack-plugin` and by modifying the webpack config.

Here's what I did:

**Path: ./src/admin/webpack.config.js**

```js
"use strict";

const path = require("path");

/* eslint-disable no-unused-vars */
module.exports = (config, webpack) => {
  config.resolve.modules = [
    "node_modules",
    path.resolve(
      process.cwd(),
      "node_modules",
      "@strapi/admin",
      "node_modules"
    ),
  ];

  return config;
};
```

This is a temporary fix, I have already made a PR to upgrade all the dependencies used in the webpack configuration (see #12078 and I am checking for a fix in order to have the correct module resolution in a generated app.

**Closed** 2022-01-05 08:14 UTC
Labels: issue-type: bug, severity: medium, status: confirmed, source: core:admin

**Comment by ZeldOcarina** [comment] 2022-01-05 15:17
Hi so how do I get the updated version with this fix in place?

**Comment by soupette** [comment] 2022-01-06 09:25
@ZeldOcarina you need to upgrade your app to the v4.0.3

**Comment by ZeldOcarina** [comment] 2022-01-06 11:39
Thank you I managed using the migration guide! :)
