### ISSUE TITLE
MySQL using UUID doesn't generate a random UUID

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1826] opened 2018-08-28 12:04 UTC
**Informations**
- **Node.js version**: v10.9.0
- **npm version**: 6.4.0
- **Strapi version**: 3.0.0-alpha.14
- **Database**: 10.2.17-MariaDB
- **Operating system**: Linux Mint 19 (Ubuntu 18.04)

**What is the current behavior?**

When using the option added in this PR: https://github.com/strapi/strapi/pull/1682 like so:

```
  "options": {
    "increments": true,
    "idAttributeType": "uuid",
    "timestamps": true,
    "comment": ""
  },
```

When attempting to add an entry I am getting the following error:

```
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1, 1 ],
  __knexQueryUid: 'fd42edd8-c275-4735-a7f6-5680da517022',
  sql:
   'select `users-permissions_user`.* from `users-permissions_user` where `users-permissions_user`.`id` = ? limit ?' }
{ method: 'select',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 1 ],
  __knexQueryUid: '52805595-42c7-497b-8481-e67e109a3de1',
  sql:
   'select `users-permissions_role`.* from `users-permissions_role` where `users-permissions_role`.`id` in (?)' }
{ method: 'insert',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings:
   [ 'test', 2018-08-28T12:02:22.753Z, 2018-08-28T12:02:22.753Z ],
  __knexQueryUid: '75b69ce8-a7eb-4b1b-a556-3248f74826fd',
  sql:
   'insert into `cmdrs` (`cmdrName`, `created_at`, `updated_at`) values (?, ?, ?)' }
[2018-08-28T12:02:22.758Z] error insert into `cmdrs` (`cmdrName`, `created_at`, `updated_at`) values ('test', '2018-08-28 05:02:22.753', '2018-08-28 05:02:22.753') - ER_NO_DEFAULT_FOR_FIELD: Field 'id' doesn't have a default value
[2018-08-28T12:02:22.759Z] debug POST /content-manager/explorer/cmdr/?source=content-manager (33 ms)
```

**Steps to reproduce the problem**

Create a model and set the `idAttributeType` to any of the string based fields like `uuid` and attempt to save an entry. There is currently no function to generate a random uuid on MySQL.

**What is the expected behavior?**

Strapi should generate a random uuid value to send to the database as MySQL / Postgres does not have a function built in to do this.

**Suggested solutions**

@kuongknight can you modify your code to generate a random string for bookshelf

**Comment by kuongknight** [comment] 2018-09-20 09:45
@derrickmehaffy ok, I will handle it

**Comment by derrickmehaffy** [comment] 2018-09-20 09:48
@kuongknight I would check with @maturanomx as he is also working modifying bookshelf

**Comment by caoer** [comment] 2018-10-08 09:46
yeah, confirmed too that mysql with uuid column does not work.

**Comment by lauriejim** [comment] 2018-10-09 19:00
Add informations, probably have to create the commande to handle it for MySQL https://github.com/strapi/strapi/blob/master/packages/strapi-hook-bookshelf/lib/index.js#L529

**Comment by MaSydJun** [comment] 2019-03-01 14:33
Not sure if my following comment is qualified for this issue, if not feel free to delete it.

Since I wanted to use UUIDs as primary key for all my tables in strapi as well, I was able to achieve this as follows:

1. Tell your model to use uuid type for the pk column:
file "_ModelName.settings.json_":
```
...
  "options": {
    "idAttributeType": "uuid"
  },
...
```

2. Use the _beforeCreate_ hook to generate a random uuid to use as pk:
file "_ModelName.json_":
```
'use strict';

const uuid = require('uuid');

module.exports = {
  beforeCreate: async (model) => {
    model.set('id', uuid());
  }
};
```

Now this works for me using a plain and simple SQLite database. However it would be 100 times more comfortable if setting  `idAttributeType` to `uuid` would be already enough to tell strapi to generate a uuid for each new record by it self.

I'm pretty sure you guys already know there's a plugin for bookshelf called [bookshelf-uuid](https://www.npmjs.com/package/bookshelf-uuid).
If I'm right, this should be pretty easy to integrate into strapi. For example, load the plugin in [this line](https://github.com/strapi/strapi/blob/master/packages/strapi-hook-bookshelf/lib/index.js#L72).
It is still necessary to enable the `uuid` property in the bookshelf model however. But this shouldn't be too tricky to do.
In my opinion it would be a great idea to ask the user whether to use numeric ID's or UUID's as part of the strapi project setup.

Just a couple ideas I'm throwing out there.

**Comment by fancyoung** [comment] 2019-04-01 09:19
In sqlite3, after config set `"idAttributeType": "uuid"`,
try update table config or delete old table to regenerate table id column attribute, 
then set `model.set('id', uuid());` in beforeCreate as @MaSydJun 's code.
Works for me.

I tried config `bookshelf-uuid` in `config/functions/bookshelf.js`, but need change `strapi-hook-bookshelf` code.

**Comment by lauriejim** [comment] 2019-04-21 14:18
By default on PG use `uuid_generate_v4()` and you have to manually install `CREATE EXTENSION IF NOT EXISTS "uuid-ossp";` to make it works.
So for MySQL and others DB it's the same think.

This option is to let you configure the type of your id type, it's not here to manage the logic behind.

It's an advanced settings, I don't think Strapi have to have all this case.

@Aurelsicoko and @alexandrebodin what do you think about that ?

**Comment by Aurelsicoko** [comment] 2019-04-22 08:51
I'm not sure it should be natively handled by strapi... I think that using lifecycle `beforeCreate` is the best choice in that case (like @MaSydJun did).

**Comment by derrickmehaffy** [comment] 2019-04-22 10:06
@lauriejim @Aurelsicoko MySQL doesn't support auto id based defaults for a UUID, it either needs to be done by a trigger or by the client (strapi): https://stackoverflow.com/questions/46134550/mysql-set-default-id-uuid

Default values cannot be functions such as `UUID()` https://dev.mysql.com/doc/refman/5.7/en/data-type-defaults.html

**Comment by lauriejim** [comment] 2019-04-22 10:08
So we can close this issue right ?

**Comment by derrickmehaffy** [comment] 2019-04-22 10:10
I mean it still needs some sort of UUID generation.... Best option would be to look at bookshelf or knex to see if it has any built in functions or build one.

UUIDs are a common security measure for anonymous data that you don't want someone to be able to just lookup an ID in sequential order

**Closed** 2019-08-14 10:11 UTC
Labels: priority: low, status: confirmed, type: bug 🐛
