### ISSUE TITLE
v3.0: missing files on install, after git clone project

### ISSUE THREAD

**Issue by MartinBucko** [strapi/strapi#370] opened 2017-12-12 21:42 UTC
**Node.js version**: v8.9.3
**npm version**: 5.5.1
**Strapi version**:
```
tcapi master 4d ▲ ➜ npm run strapi -v
5.5.1
tcapi master 4d ▲ ➜ strapi -v
3.0.0-alpha.6.7

``` 
**Operating system**:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.10
DISTRIB_CODENAME=artful
DISTRIB_DESCRIPTION="Ubuntu 17.10"
NAME="Ubuntu"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 17.10"
VERSION_ID="17.10"

````

If i move to another computer and i pull my project based on strapi, its give me errors on install packages:
```
 npm i
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/chalk-ecd4f3ca/package.json'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/ansi-styles-2c70c142/package.json'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/supports-color-6cc48eb0/package.json'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/chalk-ecd4f3ca/index.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/find-up-9363e06b/package.json'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/ansi-styles-2c70c142/index.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/supports-color-6cc48eb0/index.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/path-exists-4900b8b3/package.json'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/pinkie-promise-0a2de6c5/package.json'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/pinkie-0c3a0e88/package.json'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/chalk-ecd4f3ca/license'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/find-up-9363e06b/index.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/ansi-styles-2c70c142/license'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/supports-color-6cc48eb0/browser.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/path-exists-4900b8b3/index.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/pinkie-promise-0a2de6c5/index.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/pinkie-0c3a0e88/index.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/chalk-ecd4f3ca/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/find-up-9363e06b/license'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/ansi-styles-2c70c142/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/supports-color-6cc48eb0/license'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/path-exists-4900b8b3/license'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/pinkie-promise-0a2de6c5/license'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/pinkie-0c3a0e88/license'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/chalk-ecd4f3ca/templates.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/find-up-9363e06b/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/supports-color-6cc48eb0/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/path-exists-4900b8b3/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/pinkie-promise-0a2de6c5/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/pinkie-0c3a0e88/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mquery-55736ffb/lib/permissions.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mquery-55736ffb/lib/utils.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/browserDocument.js'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mquery-55736ffb/lib/collection'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/queryhelpers.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/browser.js'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mquery-55736ffb/lib/collection'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/querystream.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/ajv-97657dc9/dist/regenerator.min.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/core-js-97b1cc92/client/library.min.js.map'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/statemachine.js'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mquery-55736ffb/lib/collection'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/virtualtype.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/internal.js'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mquery-55736ffb/History.md'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, open '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/moment-0582811f/min/moment.min.js'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/schema'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/plugins'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/plugins'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/plugins'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/plugins'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/error'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/services'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/drivers'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/drivers'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/drivers'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/drivers'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/drivers'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/drivers'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/drivers'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/drivers'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/drivers'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/drivers'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/drivers'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/drivers'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/drivers'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/types'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/types'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/types'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/types'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/types'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/types'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/types'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/types'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/cursor'
npm WARN tar ENOENT: no such file or directory, lstat '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/mongoose-c27ecfce/lib/cursor'
npm ERR! path /media/martinez/data/www/tcbot/tcapi/node_modules/.staging/strapi-e9677b5e/node_modules/@sailshq/lodash
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/strapi-e9677b5e/node_modules/@sailshq/lodash' -> '/media/martinez/data/www/tcbot/tcapi/node_modules/.staging/@sailshq/lodash-25e2b2be'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/martinez/.npm/_logs/2017-12-12T21_30_21_432Z-debug.log

```

**Comment by Aurelsicoko** [comment] 2017-12-13 11:35
We are working on it, this is a known issue on our side. It's mainly due to the postInstall script which is in charge to install the node_modules of the plugins.

**Comment by lauriejim** [comment] 2017-12-18 10:01
It looks like it not coming from the`post install` script.
Can you remove your `node_modules` folder and try again your `npm install`.

**Comment by Aurelsicoko** [comment] 2018-01-05 15:39
It should be fixed with the [latest release](https://github.com/strapi/strapi/releases/tag/v3.0.0-alpha.7.3).

**Comment by lkostrowski** [comment] 2018-01-05 21:55
@Aurelsicoko 
Hi, I just found this issue, because I met exactly the same error. I have built via CLI on my OSX env, then deployed to prod Debian, tried `npm install` and `npm run setup`, both failed with the same errors.
I made it running by creating a new app with CLI on server and copying files.
Can I provide some data to help?

BTW great job, I love strapi and will try to contribute if I meet the challenge

**Comment by Aurelsicoko** [comment] 2018-01-08 09:51
@lkostrowski Sure, it could be interested to share your logs to understand what happened in your case. Thank you for your kind words!

**Comment by franzos** [comment] 2018-01-09 09:47
@lkostrowski I've encountered the same issues as you, but noticed something odd manually copying the files: Previously Strapi created db collection names using plural (article**s**, user**s**), however after copying over the config (api) to production, Strapi tries to access collections using the singular (article, user), hence it can't find the data. I had to manually rename the collection. Did you encounter a similar issue?

**Comment by lkostrowski** [comment] 2018-01-09 09:52
I finally had another issue  (#423) so haven't dig deeper. 
I will try next time and to share something, this issue is a blocker for me

**Comment by Aurelsicoko** [comment] 2018-01-10 16:42
@franzos Yes, it was a mistake on our side. The collection names were pluralized without any reasons. We are now using singular table/collection names. You can force the collection/table name using the `collectionName` attribute in your models or rename your collections/tables.

**Comment by franzos** [comment] 2018-01-10 23:01
@Aurelsicoko good to know, thanks. I simply renamed the collection.

**Closed** 2018-01-22 09:52 UTC
Labels: os: linux, priority: critical, status: need more information, version: 3.x

**Comment by daominhsangvn** [comment] 2018-03-03 08:36
Hello, i'm facing this issue in 3.0.0-alpha.10.3.
```
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-ansi-54dd844b/package.json'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-flag-41bb82ff/package.json'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-symbols-aa157099/package.json'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-3ec69323/package.json'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/hosted-git-info-7718a819/package.json'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-ansi-54dd844b/index.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-flag-41bb82ff/index.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-symbols-aa157099/.npmignore'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/graceful-fs-000e3ace/package.json'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-3ec69323/.npmignore'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/globals-cd57d2f0/package.json'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/generic-pool-ac4d3ae8/package.json'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/hosted-git-info-7718a819/README.md'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-ansi-54dd844b/license'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-flag-41bb82ff/license'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-symbols-aa157099/README.md'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/graceful-fs-000e3ace/README.md'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-3ec69323/.jshintrc'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/globals-cd57d2f0/index.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/generic-pool-ac4d3ae8/.npmignore'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/hosted-git-info-7718a819/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-ansi-54dd844b/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-flag-41bb82ff/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-symbols-aa157099/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/graceful-fs-000e3ace/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-3ec69323/LICENSE-MIT'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/globals-cd57d2f0/license'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/generic-pool-ac4d3ae8/README.md'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/hosted-git-info-7718a819/git-host-info.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-symbols-aa157099/index.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/graceful-fs-000e3ace/polyfills.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-3ec69323/README.mkd'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/globals-cd57d2f0/readme.md'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/generic-pool-ac4d3ae8/.eslintrc.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/hosted-git-info-7718a819/git-host.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-symbols-aa157099/shams.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/graceful-fs-000e3ace/legacy-streams.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/globals-cd57d2f0/globals.json'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/generic-pool-ac4d3ae8/CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/hosted-git-info-7718a819/index.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-symbols-aa157099/.travis.yml'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/graceful-fs-000e3ace/graceful-fs.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/generic-pool-ac4d3ae8/Makefile'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-symbols-aa157099/CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/graceful-fs-000e3ace/fs.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/has-symbols-aa157099/.eslintrc'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/ajv-4c48af73/dist/regenerator.min.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/async-7ecbc6ad/dist/async.min.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/async-7ecbc6ad/bower.json'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/async-7ecbc6ad/CHANGELOG.md'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/core-js-840b5d0a/client/shim.min.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/eslint-47655d56/lib/rules/operator-assignment.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/eslint-47655d56/lib/rules/key-spacing.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/eslint-47655d56/lib/rules/operator-linebreak.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/eslint-47655d56/lib/rules/jsx-quotes.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/eslint-47655d56/lib/rules/padded-blocks.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/eslint-47655d56/lib/rules/init-declarations.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/eslint-47655d56/lib/rules/prefer-arrow-callback.js'
npm WARN tar ENOENT: no such file or directory, open '/root/node-myportfolio/node_modules/.staging/eslint-47655d56/lib/rules/indent.js'
```

**Comment by nicroto** [comment] 2018-07-03 22:07
Had the same issue. Indeed, removing package-lock.json worked. But it kind of makes the locking useless. I don't know why the issue was closed, this happened to me with `3.0.0-alpha.12.6` ...

**Comment by maturano** [comment] 2018-07-05 16:00
Same issue with `3.0.0-alpha.12.6`. @Aurelsicoko reopen or new issue?

**Comment by Aurelsicoko** [comment] 2018-07-05 16:24
@nicroto @maturano We can reopen it to investigate again but it seems more related to npm than Strapi. The package.lock never worked for me whatever the project I'm building. I'm constantly adding it in the .gitignore file to avoid this kind of issue.

**Comment by emahuni** [comment] 2018-07-09 17:45
Was having a similar issue: 

```
npm WARN tar ENOENT: no such file or directory, lstat '/sdcard/app/node_modules/.staging/faker...'
```

i just removed the package-lock.json file and it installed nicely.

**Comment by nicroto** [comment] 2018-07-10 07:30
@Aurelsicoko Thanks for the reply and sorry for my late response. (I've missed the notification)

I am on the opposite spectrum of impressions with `package-lock.json`. I have projects that are years-old, and they keep on installing properly, only because of package-lock.json (well they use the older npm-shrinkwrap which is, for the purposes of this conversation - the same thing).

I think you should reopen the issue until someone tracks that the problem is **not** strapi-related. If this is the case, we will then submit it to npm, so it can be resolved at the root.

I believe this is an important feature for many developers and I definitely want (need) to use it myself.

I hope this makes sense.
