### ISSUE TITLE
Re-ordering of repeatable components that contain repeatable components

### ISSUE THREAD

**Issue by raygerrard** [strapi/strapi#5215] opened 2020-02-10 05:19 UTC
**Describe the bug**
When authoring a content type item that has a dynamic zone with a component that contains a repeatable component itself there is an issue when clicking on the up / down arrow to re-order. The re-ordering on the UI changes the order of the wrong list of components.

**Steps to reproduce the behavior**
1. Create content type "Quiz" that has a field "Questions" of dynamic zone (Multiple Choice Question)
2. Create a new component (Multiple Choice Question) that has a field "Questions) of repeatable component (Multiple Choice Answer) and a question field of type text
3. Create a new component (Multiple Choice Answer) with answer field of type text
4. Create content item of type "Quiz" and add two multiple choice questions with multiple choice answers
5. Click up or down arrow and observe the list of questions moving but the question text field stays in the current position.

**Expected behavior**
When clicking up or down it should move the component at the highest level that the up / down icon is attached too, not the components at the lowest level.

**System**
- Node.js version: v10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.7
- Database: MySQL
- Operating system: MAC OS 10.14.6

**Comment by derrickmehaffy** [comment] 2020-02-10 05:23
@raygerrard Please completely fill out the bug report template the below part of the template **is required**:

```
**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:
```

After you have updated your issue with this part I will reopen it.

**Comment by raygerrard** [comment] 2020-02-11 03:54
Added additional details

**Comment by raygerrard** [comment] 2020-02-12 18:36
@derrickmehaffy can you re-open this?

**Comment by lauriejim** [comment] 2020-02-13 16:35
Hello! I tried to reproduce without success.
Here is what I did - let me know if I missed something - https://www.loom.com/share/b3d2e52c080b4677b215ea5ecaaaecdf

**Comment by raygerrard** [comment] 2020-02-13 21:07
Thanks for trying to reproduce. The only thing you missed was the text field on the Multiple Choice Question component so you weren't able to see the issue as the child questions do get moved up / down. If you add a text field to Multiple Choice Questions and populate each question with a different name you will see the children (Multiple Choice Answers) get moved up / down but the question text stays in the current order.

**Comment by lauriejim** [comment] 2020-02-14 11:17
Can you please share your API and Components please.
This will help me to be sure to have the right data structure.

**Comment by soupette** [comment] 2020-03-27 07:14
@lauriejim should we close this issue due to both inactivity and since we cannot reproduce it?

**Comment by derrickmehaffy** [comment] 2020-03-27 12:38
Marking as closed as user hasn't responding to requests for additional information. This can be reopened when user has replied.

**Closed by derrickmehaffy** 2020-03-27 12:38 UTC
Labels: priority: medium, source: plugin:content-manager, status: can't reproduce, type: bug
