### ISSUE TITLE
Creating collection entry yields error: "strapi `Protect` must be used within `Auth`"

### ISSUE THREAD

**Issue by soudis** [strapi/strapi#22382] opened 2024-12-10 14:01 UTC
### Required System information

- Node.js version: v20.18.1
- NPM version: using pnpm 9.9.0
- Strapi version: 5.5.0
- Database: mariadb:11.3
- Operating system: alpine
- Is your project Javascript or Typescript: TS

### Describe the bug

After dropping the database and recreating the admin user everything works fine, but if I go to any collection and try to create a new entry a frontend error is shown: 

`strapi Protect must be used within Auth`

The setup was working just fine before resetting the database. I assume that recreating the admin user did something wrong. 

There are a couple of similiar issues that did not pass the bugreport requirements, so there seems to be a problem: 
- https://github.com/strapi/strapi/issues/22185
- https://github.com/strapi/strapi/issues/22198
- https://github.com/strapi/strapi/issues/22224

### Steps to reproduce the behavior

1. Drop database
2. Restart strapi
3. Create admin user
4. got to any collection => create entry

### Expected behavior

No error is shown

### Screenshots

![grafik](https://github.com/user-attachments/assets/a2711a24-4d64-4fb1-b88c-5a8d1e256f1c)

### Code snippets

none

### Additional context

Stacktrace from browser console:

```
The above error occurred in the <Protect> component:

Protect@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-BT26MBRR.js?v=1dcf76b2:1638:15
InjectedImportExportSingleType@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2AWURZ5M.js?v=1dcf76b2:66300:45
InjectionZone@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-TA2NL7HV.js?v=1dcf76b2:135:21
div
O2@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-AKSCLQJA.js?v=1dcf76b2:1267:6
Box<@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-OAJ7Z6LW.js?v=1dcf76b2:4869:7
O2@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-AKSCLQJA.js?v=1dcf76b2:1267:6
Flex<@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-OAJ7Z6LW.js?v=1dcf76b2:4976:92
ActionsPanelContent@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-TA2NL7HV.js?v=1dcf76b2:3091:29
aside
O2@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-AKSCLQJA.js?v…
react-dom.development.js:18704:14
```

```
React Router caught the following error during render Error: `Protect` must be used within `Auth`
    useContext2 Context.tsx:33
    h index.ts:169
    useContext2 Context.tsx:30
    Protect PageHelpers.tsx:182
    React 9
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
 
Object { componentStack: "\nProtect@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-BT26MBRR.js?v=1dcf76b2:1638:15\nInjectedImportExportSingleType@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2AWURZ5M.js?v=1dcf76b2:66300:45\nInjectionZone@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-TA2NL7HV.js?v=1dcf76b2:135:21\ndiv\nO2@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-AKSCLQJA.js?v=1dcf76b2:1267:6\nBox<@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-OAJ7Z6LW.js?v=1dcf76b2:4869:7\nO2@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-AKSCLQJA.js?v=1dcf76b2:1267:6\nFlex<@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-OAJ7Z6LW.js?v=1dcf76b2:4976:92\nActionsPanelContent@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-TA2NL7HV.js?v=1dcf76b2:3091:29\naside\nO2@https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-AKSCLQJA.js?v=1dcf76b2:1267:6\nBox<@https://cms.klink.localhost/nod…" }
hooks.tsx:631:12
    componentDidCatch https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-WBAU2NZA.js?v=1dcf76b2:4071
    callback https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:14104
    callCallback https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:11268
    commitUpdateQueue https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:11285
    commitLayoutEffectOnFiber https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:17097
    commitLayoutMountEffects_complete https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:18008
    commitLayoutEffects_begin https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:17997
    commitLayoutEffects https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:17948
    commitRootImpl https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:19381
    commitRoot https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:19305
    finishConcurrentRender https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:18788
    performConcurrentWorkOnRoot https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:18746
    workLoop https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:197
    flushWork https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:176
    performWorkUntilDeadline https://cms.klink.localhost/node_modules/.strapi/vite/deps/chunk-2UE3WFCV.js?v=1dcf76b2:384


```

**Comment by Boegie19** [comment] 2024-12-11 17:39
@soudis Can I ask for a list of all dependencies of your strapi instance.

**Comment by derrickmehaffy** [comment] 2024-12-12 19:22
duplicate of https://github.com/strapi/strapi/issues/21151

**Closed by derrickmehaffy** 2024-12-12 19:22 UTC
Labels: status: duplicate

**Comment by soudis** [comment] 2024-12-16 12:46
@Boegie19 

```
  "dependencies": {
    "@babel/core": "^7.0.0-0",
    "@babel/runtime": "^7.26.0",
    "@codemirror/autocomplete": "^6.18.3",
    "@codemirror/language": "^6.10.4",
    "@codemirror/lint": "^6.8.3",
    "@codemirror/search": "^6.5.8",
    "@codemirror/state": "^6.4.1",
    "@codemirror/theme-one-dark": "^6.1.2",
    "@codemirror/view": "^6.35.0",
    "@lezer/common": "^1.2.3",
    "@strapi/admin": "^5.5.0",
    "@strapi/data-transfer": "^5.5.0",
    "@strapi/plugin-graphql": "^5.5.0",
    "@strapi/plugin-users-permissions": "^5.4.1",
    "@strapi/strapi": "^5.5.0",
    "codemirror": "^6.0.1",
    "koa": "2.15.3",
    "mysql2": "3.10.1",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-router-dom": "^6.28.0",
    "strapi-import-export": "^0.0.1",
    "strapi-plugin-config-sync": "^3.0.4",
    "strapi-v5-plugin-populate-deep": "^4.0.4",
    "styled-components": "^6.1.13"
  },
  "devDependencies": {
    "@graphql-codegen/cli": "5.0.3",
    "@graphql-codegen/client-preset": "4.5.1",
    "@graphql-codegen/introspection": "4.0.3",
    "@graphql-codegen/typescript": "^4.1.2",
    "@graphql-codegen/typescript-resolvers": "^4.4.1",
    "graphql": "^16.9.0"
  }
``

**Comment by Boegie19** [comment] 2024-12-16 13:28
@soudis multiple plugins you have installed are v4 and not v5 plugins so will make the page crash

**Comment by Boegie19** [comment] 2024-12-18 14:30
No problem please open a issue with the plugin do

**Comment by Boegie19** [comment] 2024-12-18 18:50
I was wrong is not a issue with the plugin is a issue with your strapi project that you have 2 diffrent versions of strapi installed
