### ISSUE TITLE
Update notifier stuck after update to v4.17.0

### ISSUE THREAD

**Issue by fabio-nettis** [strapi/strapi#19199] opened 2024-01-11 09:26 UTC
### Required System information

- Node.js version: 21.5.0
- Yarn version: 4.0.2
- Strapi version: 4.17.0
- Database: PostgreSQL
- Operating system: darwin-x64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Since updating to version 4.17.0 the update notifier has been stuck on the previous version and still displays that an update is available. The contents of the `.strapi-updater.json` file look like this:

```json
{
  "latest": "4.17.0",
  "lastUpdateCheck": 1704881324810,
  "lastNotification": 1703146687905
}
```

Interestingly the last check has been performed recently and the version really is 4.17.0, nevertheless the admin panel still tells me there is an update, I have removed the `build` and `.cache` folder and rebuild multiple times since.

### Steps to reproduce the behavior

1. Update to the latest version
2. Rebuild the admin panel
3. Go to Settings > Overview

### Expected behavior

There should not be a update notification.

### Screenshots

![screenshot-strapi-updater](https://github.com/strapi/strapi/assets/36916632/5d9c174e-fd7c-4a2a-a0db-27b1edbcef22)

### Code snippets

N/A

### Additional context

N/A

**Comment by derrickmehaffy** [comment] 2024-01-11 19:49
@fabio-nettis the admin build now is in a `.strapi` folder, can you make sure you rebuild the admin panel manually and does it still show that?

**Comment by fabio-nettis** [comment] 2024-01-11 19:54
@derrickmehaffy Already did that earlier today. Issue still persists in development and production builds.

**Comment by derrickmehaffy** [comment] 2024-01-11 19:56
Alright I'll try taking a look tomorrow morning to see if I can reproduce it, I'm guessing the issue is for some reason it's probably still looking for the `build` folder and not `.strapi`

**Comment by derrickmehaffy** [comment] 2024-01-11 19:56
Just to double check though can you try deleting the build folder in case it's trying to parse something out of it?

**Comment by fabio-nettis** [comment] 2024-01-11 19:58
@derrickmehaffy Yeah sure! Will check it out by tomorrow. 🤘🏻

**Comment by fabio-nettis** [comment] 2024-01-12 15:29
@derrickmehaffy Alright, can confirm now that the issue still persists for me after running `rm -rf .strapi build && yarn build && yarn dev`. Hope you were able to reproduce the error.

**Comment by exneval** [comment] 2024-01-15 04:36
also experience the same thing just to clarify

**Comment by monzonj** [comment] 2024-01-15 12:00
Issue is there for me for a fresh install of Strapi 4.17.0

**Comment by Adaphath** [comment] 2024-01-16 09:02
It might come from this error I got after updating from 4.15.5 to 4.16.2:
```
WARNING in ./node_modules/@palmabit/strapi-app-version/admin/src/pages/App/index.js 10:44-52
export 'NotFound' (imported as 'NotFound') was not found in '@strapi/helper-plugin' (possible exports: AnErrorOccurred, AppInfoContext, AppInfoProvider, AppInfosContext, AppInfosProvider, AutoReloadOverlayBlockerContext, AutoReloadOverlayBlockerProvider, Body, CheckPagePermissions, CheckPermissions, ConfirmDialog, ContentBox, ContentManagerEditViewDataManagerContext, CustomFieldsContext, CustomFieldsProvider, DateTimePicker, DynamicTable, EmptyBodyTable, EmptyStateLayout, FilterListURLQuery, FilterPopoverURLQuery, Form, GenericInput, GuidedTourContext, GuidedTourProvider, InjectionZone, LibraryContext, LibraryProvider, Link, LinkButton, LoadingIndicatorPage, NoContent, NoMedia, NoPermissions, NotAllowedInput, NotificationsContext, NotificationsProvider, OverlayBlockerContext, OverlayBlockerProvider, PageSizeURLQuery, PaginationURLQuery, RBACContext, RBACProviderContext, ReactSelect, RelativeTime, RemoveRoundedButton, Root, SearchURLQuery, SettingsPageTitle, SortIcon, Status, StopPropagation, StrapiAppContext, StrapiAppProvider, Table, TrackingContext, TrackingProvider, auth, contentManagementUtilRemoveFieldsFromData, difference, findMatchingPermissions, formatContentTypeData, formatPermissionsForRequest, getAPIInnerErrors, getFetchClient, getFileExtension, getOtherInfos, getType, getYupInnerErrors, hasPermissions, normalizeAPIError, onRowClick, prefixFileUrlWithBackendUrl, prefixPluginTranslations, pxToRem, request, setHexOpacity, shouldCheckPermissions, stopPropagation, to, translatedErrors, useAPIErrorHandler, useAppInfo, useAppInfos, useAutoReloadOverlayBlocker, useCMEditViewDataManager, useCallbackRef, useClipboard, useCollator, useCustomFields, useFetchClient, useFilter, useFocusInputField, useFocusWhenNavigate, useGuidedTour, useLibrary, useLockScroll, useNotification, useOverlayBlocker, usePersistentState, useQuery, useQueryParams, useRBAC, useRBACProvider, useSelectionState, useStrapiApp, useTableContext, useTracking, wrapAxiosInstance)
 @ ./node_modules/@palmabit/strapi-app-version/admin/src/index.js
 @ ./node_modules/@palmabit/strapi-app-version/strapi-admin.js
 @ ./.strapi/client/app.js 1:0-73 18:26-42

```

**Comment by JulienRamel** [comment] 2024-01-29 09:18
The issue is still here on 4.19.0...

**Comment by saintcore** [comment] 2024-01-30 15:07
> The issue is still here on 4.19.0...

same here for me

**Comment by derrickmehaffy** [comment] 2024-02-09 17:46
Confirmed

Steps:

- Create a project on 4.19.0
- Start project on 4.19.0 (`yarn develop`)
- See both CLI and admin notification that 4.20.0 is there
- Update package.json for 4.20.0
- Run project on 4.20.0 (`yarn develop`)
- See that CLI warning is gone but admin one remains

**Comment by derrickmehaffy** [comment] 2024-03-12 05:53
Locking this, we know, it will get fixed but is probably the lowest priority bug we have right now.

When it's fixed you'll see a linked pull request

**Comment by derrickmehaffy** [comment] 2024-12-12 19:08
duplicate of https://github.com/strapi/strapi/issues/21356

**Closed by derrickmehaffy** 2024-12-12 19:08 UTC
Labels: status: duplicate
