### ISSUE TITLE
strapi quickstart installation problem in windows

### ISSUE THREAD

**Issue by RameshTechouts** [strapi/strapi#8786] opened 2020-12-03 07:08 UTC
### Describe the bug

create new project with npx : npx create-strapi-app my-project --quickstart
but getting errors.
### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version:   12
- NPM version: 6
- Strapi version: 
- Database:
- Operating system: windows 10

### Additional context

D:\Strapi\project>npx create-strapi-app my-project --quickstart
Creating a new Strapi application at D:\Strapi\project\my-project.

Creating a quickstart project.
Creating files.
Error while installing dependencies:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-project@0.1.0
npm ERR! Found: knex@0.19.5
npm ERR! node_modules/knex
npm ERR!   knex@"<0.20.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"^0.20.0" from strapi-connector-bookshelf@3.3.4
npm ERR! node_modules/strapi-connector-bookshelf
npm ERR!   strapi-connector-bookshelf@"3.3.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\dell\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Local\npm-cache\_logs\2020-12-03T06_53_11_334Z-debug.log

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentionned in the installation errors and try to run the following command:

cd D:\Strapi\project\my-project && npm install

npm ERR! code 1
npm ERR! path D:\Strapi\project
npm ERR! command failed
npm ERR! command C:\Windows\System32\cmd.exe /d /s /c create-strapi-app my-project --quickstart

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Local\npm-cache\_logs\2020-12-03T06_53_17_438Z-debug.log

D:\Strapi\project>

After trying cd D:\Strapi\project\my-project && npm install
getting this error:

D:\Strapi\project\my-project>cd D:\Strapi\project\my-project && npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-project@0.1.0
npm ERR! Found: knex@0.19.5
npm ERR! node_modules/knex
npm ERR!   knex@"<0.20.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"^0.20.0" from strapi-connector-bookshelf@3.3.4
npm ERR! node_modules/strapi-connector-bookshelf
npm ERR!   strapi-connector-bookshelf@"3.3.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\dell\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dell\AppData\Local\npm-cache\_logs\2020-12-03T06_55_36_437Z-debug.log

**Comment by derrickmehaffy** [comment] 2020-12-03 14:18
@RameshTechouts I just tested on my own Windows 10 system and could not reproduce your issue. It appears you have some very aggressive npm cache, or your npm registry is set to something that is pulling old packages (or is missing packages).

**Comment by Dr-Nio** [comment] 2020-12-04 15:47
So what could be the possible solution, because am experiencing the same issue too

**Comment by tipmisle** [comment] 2020-12-06 13:01
I have the same issue.

**Comment by eliasmuniz** [comment] 2020-12-06 17:57
Same here!

**Comment by Deltids** [comment] 2020-12-06 22:19
Same here

**Comment by RameshTechouts** [comment] 2020-12-08 11:12
I followed the below points , Then it will worked for me.

1.rm -r node_modules
2.npm cach clean --force
3.npm install


Thanks&Regards
Ramesh D

**Comment by jorrit** [comment] 2020-12-10 13:51
By default, `create-strapi-app` adds the dependency `"knex": "<0.20.0"` to your package.json. However, since 4f5a0e76799b2186e7e45b62cf76d78599a8d7f7 the actual dependency that strapi has on knex was changed to `^0.20.`, so they don't match anymore. NPM 7 stopped accepting this inconsistency. I think you can update package.json to `>=0.15.0 <0.22.0`, which is the version range used by the `bookshelf` dependency.

**Comment by BraydenGirard** [comment] 2020-12-29 17:50
I am having the same issue using Node 15. Unfortunately I can't use an earlier version of Node as I am on Apple Silicon and Node 15 is the only version that will compile natively.

**Comment by derrickmehaffy** [comment] 2020-12-29 18:19
Those of you on Node 15, we have no plans to support Node 15 (or any "odd" node release) the next supported version will be Node 16 in October of 2021.

**Comment by BraydenGirard** [comment] 2020-12-29 18:42
Any suggestions for running Strapi locally on Apple Silicon?

**Comment by derrickmehaffy** [comment] 2020-12-30 15:03
> Any suggestions for running Strapi locally on Apple Silicon?
> 
> Update:
> 
> Great resource here - [nodejs/build#2474 (comment)](https://github.com/nodejs/build/issues/2474#issuecomment-752213589)

None of us in the core Strapi team have M1 Macs to even test with, so for the moment we can't validate any support on them.

**Comment by larrybird1** [comment] 2021-01-13 04:24
this error while trying to install in windows 10

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: bienesraices@0.1.0
npm ERR! Found: knex@0.19.5
npm ERR! node_modules/knex
npm ERR!   knex@"<0.20.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"^0.20.0" from strapi-connector-bookshelf@3.4.1
npm ERR! node_modules/strapi-connector-bookshelf
npm ERR!   strapi-connector-bookshelf@"3.4.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\fraustro\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\fraustro\AppData\Local\npm-cache\_logs\2021-01-13T04_21_11_512Z-debug.log

**Comment by derrickmehaffy** [comment] 2021-01-13 08:25
@BraydenGirard a few in our team now have m1 macs, see this PR: https://github.com/strapi/strapi/pull/9106

**Comment by derrickmehaffy** [comment] 2021-01-13 08:26
@larrybird1 what node/npm version do you have and can you check your npm registry setting with: `npm config get registry`

**Comment by gokturkenez** [comment] 2021-01-25 16:07
I'm experiencing the same issue as well. Looks like using the latest npm and node version is the main reason of this error. Does anyone manage to fix the above issue somehow?

**Comment by derrickmehaffy** [comment] 2021-01-25 20:56
> I'm experiencing the same issue as well. Looks like using the latest npm and node version is the main reason of this error. Does anyone manage to fix the above issue somehow?

We don't support Node v15 and/or any "odd version" of node as they are not LTS. We support up to v14 and will eventually support v16 in October of 2021.

**Comment by lbell** [comment] 2021-02-02 13:44
> We don't support Node v15 and/or any "odd version" of node as they are not LTS. We support up to v14 and will eventually support v16 in October of 2021.

Thanks. You might make that more clear in the docs, which currently state: "The current _recommended_ version to run Strapi is Node v14." ( https://strapi.io/documentation/developer-docs/latest/installation/cli.html ).

**Comment by pesinasiller** [comment] 2021-02-02 21:54
I had the same problem on heroku and I fixed it by changing npm from >=6.0.0 to 6.14.9 in package.json
```
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": "6.14.9"
  },
```

**Comment by derrickmehaffy** [comment] 2021-02-05 18:00
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/build-error-dependency-problem-while-deploying-to-heroku/2661/2

**Comment by PabloPap** [comment] 2021-02-05 18:03
@derrickmehaffy 
I just posted the solution by @pesinasiller on the Strapi forum. it also worked for me

**Closed** 2021-02-10 16:35 UTC
Labels: status: can't reproduce

**Comment by sheikware** [comment] 2021-02-25 04:09
Just an FYI - I also ran into this issue on a mac m1 (npm@7.3.0, node@v15.5.1) as there are multiple dependency contradictions with strapi-connector-bookshelf in the npm package (they look fixed in master, knex version and sqlite version need to be ^0.21.0 and ^5.0.0, respectively). 

But you can just run `npm update --legacy-peer-deps` manually after the `create-strapi-api` fails and everything seems to work just fine.
