### ISSUE TITLE
Content Manager cannot open created Content Types

### ISSUE THREAD

**Issue by djbingham** [strapi/strapi#1912] opened 2018-09-06 16:21 UTC
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.14

- **Database**: MongoDB 4.1
- **Operating system**: Alpine Linux (inside a Docker container using the `strapi/strapi` image)

**What is the current behavior?**
The Strapi admin UI crashes with the following console errors when opening a content type in the Content Manager.

Console log:
```
main.js:16 TypeError: Cannot read property 'getIn' of undefined
    at e.value (main.js:46)
    at main.js:46
    at We.__iterate (main.js:6)
    at We.forEach (main.js:6)
    at e.value (main.js:46)
    at new e (main.js:46)
    at main.js:40
    at Me (main.js:6)
    at Me (main.js:6)
    at Me (main.js:6)
Io @ main.js:16
Uo.o.callback @ main.js:16
to @ main.js:16
oo @ main.js:16
mn @ main.js:16
cn @ main.js:16
un @ main.js:16
ln @ main.js:16
bn @ main.js:16
We @ main.js:16
main.js:16 Uncaught TypeError: Cannot read property 'getIn' of undefined
    at e.value (main.js:46)
    at main.js:46
    at We.__iterate (main.js:6)
    at We.forEach (main.js:6)
    at e.value (main.js:46)
    at new e (main.js:46)
    at main.js:40
    at Me (main.js:6)
    at Me (main.js:6)
    at Me (main.js:6)
```

**Steps to reproduce the problem**
1. Create a new content type `Article` with string field `title` and text field `content`.
2. Wait for the UI to refresh and indicate that the update has been applied (Docker logs indicate the app restarted successfully).
3. Navigate to Content Manager and select `Article`.
4. See that settings for the `Article` type are displayed.
5. Return to the Content Type Editor and add a relation field `author` which related `Article` to `User`. The relation type `User has many Articles`.
6. Return to Content Manager and select `Article` again.
7. See the page flicker (presumably loading the intended page) and then go blank. Check the console log for errors.

**What is the expected behavior?**
Options to modify settings for the selected content type should be displayed.

**Suggested solutions**
In the reproduction steps, I describe exactly what I did to reproduce this error after seeing it the first time. I've experimented a bit and I believe the error does not occur unless a relation has been added to a user-defined content type. However, once a relation has been added to any one content type, it seems to cause this error for all other content types as well.

**Comment by lauriejim** [comment] 2018-09-12 17:44
Can you guys test again with last version of Strapi please (just published new version and I think it's fixed)

**Comment by gianniskarmas** [comment] 2018-09-14 23:40
That happens in a new 14.1.1 project.
Copied apis from previous one and only these give this error when I try to edit them in Content manager. Any newly created behave correctly.
Is there something else that should be created for content management to work?

**Comment by derrickmehaffy** [comment] 2018-09-15 03:08
@hansemannn you can't create stuff on heroku because the storage isn't persistent. You will need to create new models locally then push to heroku.

**Comment by ChrisSargent** [comment] 2018-09-15 23:28
I am also experiencing this issue - if I can provide any information to help with debugging, please let me know.

**Comment by hansemannn** [comment] 2018-09-15 23:40
@derrickmehaffy That's a good point! But actually this happens with a locally-deployed instance where all content-types have been created earlier.

**Comment by gianniskarmas** [comment] 2018-09-16 01:37
Also to mention I can't edit at all these copied apis and can't add new fields any more. @lauriejim can you please give us any hints of where to look? This is urgent if it is a bug

**Comment by ChrisSargent** [comment] 2018-09-16 10:59
I've been doing a little bit of debugging on this this morning. In the constructor of `Manager.js` in content-type-builder/utils, when it is throwing an error, the variable with name `layout` is coming through as `undefined`.

**Comment by hansemannn** [comment] 2018-09-16 11:42
@ChrisSargent This is huge progress! Do you know a way to clean this up? I am searching through both the model settings and the MongoDB itself, but cannot find any old references to camel-cased fields, except Strapi's own ones (updatedAt, createdAt & resetPasswordToken).

**Comment by ChrisSargent** [comment] 2018-09-16 11:46
@hansemannn, well when I first ran in to this problem I couldn't get back to a working / clean state either. So, I setup a new repo with these changes to that I could track exactly what was being changed in the code. I also committed a working .json file from the `core_store` collection that Strapi creates. There is an entry there with a key called `plugin_content-manager_schema` and it seems to control the menu items and available content types for editing.

However, looking at the original issue it doesn't seem that they were using any casing in their models.

**Comment by gianniskarmas** [comment] 2018-09-16 13:10
After your reply @ChrisSargent looked into db's core_store and realised that is the root of these problems, at least in my case.

In the [migration guide](https://github.com/strapi/strapi/wiki/migration-guide-alpha.14-to-alpha.14.1) it does not mention anywhere that you need to copy core_store from previous db or nothing works. I assumed this entry gets automatically created when it reads what's inside the /api/ folder but it seems it doesn't. So the schema of the content-manager plugin does not have any info about these apis, thus the errors.

The question: Is there anyway to force core_store creation correctly from available apis?

**Comment by hansemannn** [comment] 2018-09-16 14:33
Thanks to both of you! In my case, a field was appended twice in the core_store, resulting in the blank page. Cleaning it up manually fixed the issue.

**Comment by ChrisSargent** [comment] 2018-09-16 19:18
I’m not sure. It seems that maybe this dB entry is created from scratch every time a model type is edited through the UI. Or maybe it updates it. Either way, it seems it would be better if it always recreated the entry based on data in the code.

**Closed** 2018-09-17 11:46 UTC
Labels: type: help wanted 🤷‍♂️

**Comment by derrickmehaffy** [comment] 2018-09-17 11:49
@lauriejim I think this is still an on-going issue. Had another user report something similar on slack. May want to keep this open to make sure there is no existing issue to be fixed.

**Comment by derrickmehaffy** [comment] 2018-09-17 13:28
@gianniskarmas the content manager plugin (customizing the look of the edit/list views) is very new.

The project as a whole is currently in alpha thus I would expect a lot of changes to happen, at this point everything is pretty much subject to change.

That being said the Strapi team is small, and they get a lot of duplicate tickets. I spoke with him on the slack and in this case the issue is with the core_store entry and you needed to delete the entry after the update due to a change in how the schema is created. I've spoken with @soupette on this issue and I'm not a huge fan of it is currently being stored.

**Comment by gianniskarmas** [comment] 2018-09-17 14:31
@derrickmehaffy Thank you for all the hard work all of you put on this project.
Unfortunately that is not the only problem but also a part of a bigger one .

It looses any access and track to the old apis and does not recreate the schema.
- **Can't create any new fields in Content Type**. When I try to I get the infinite spinning wheel.
- **Can't edit with Content Manager**. PUT http://localhost:1337/content-type-builder/models/materials 500 (Internal Server Error)
- **Can't edit with Content Type Builder**. TypeError: Cannot read property 'getIn' of undefined

The api and graphql works in all crud operations but the admin, which is the best part of strapi, becomes corrupted very easily.

The way I see it (and while I've had to learn these limitations after destroy days of work) this is a core problem and something to consider fixing urgently.

**Comment by derrickmehaffy** [comment] 2018-09-17 14:39
@gianniskarmas yeah as I said it was related to how the content manager plugin (what changes those views on the admin panel) stores the data. Right now all that information is stored in one very deeply nested json on a single db entry (good luck breaking that down by hand).

There was a change in how that schema is built, thus it couldn't parse the json from the previous version, hence why it had to be deleted to get the content manager to work again.

Trust me I know it is frustrating for you, your talking to someone who has roughly 75 models that I had to rebuild one by one. But I expect this in an alpha project and I've been talking with the Strapi team to help them with some of these "quality of life" improvements, in this case it was a needed change. I won't lie and say who knows if something like this will be needed again, like I said before Alpha = everything is subject to change.

I understand that you are trying to use this and develop for a production application. I use strapi in production (or well getting close to) so trust me when I say I feel your pain, however the Strapi team right now are solely focused on getting a stable release out by the end of the year and aren't focused on those of us that are currently using it. In this case it was a bug with updating and not creating a new project.

I am not a Strapi team member, but I have been around here for some time now and am very focused on helping them where I can with the skills I have. I always suggest to everyone here that if there is something you don't like or something you think should change, fork the code, fix it, and submit a PR. :smile: 

My javascript skills unfortunately are not very strong and I have basically zero frontend development skills, thus I usually try and poke around where I can. In this case, I recommend you backup your core_store table, delete it, and restart the server. That should get you access again to the adminUI

**Comment by signorekai** [comment] 2018-09-17 16:30
For what it's worth, I've encountered this as well, and figured it's the content-manager plugin's config. I've basically just used https://jsonformatter.org/ to format the string @derrickmehaffy mentioned, inside `core_store` under `plugin_content-manager__schema`. The site lets me collapse nodes, and generally has good formatting (to me anyway).

Just keep a look out for duplicate keys and any keys that you may have removed. These will cause the content-manager page on your admin to not work properly.

**Comment by derrickmehaffy** [comment] 2018-09-17 16:39
Good hint @signorekai I was trying to break it down manually. Exporting as CSV from MySQL and trying to manually modify the CSV. Most programs won't even open a CSV that big (a good 75 models worth) :laughing:

**Comment by signorekai** [comment] 2018-09-17 16:46
Yeah was a massive pain to deal with. Hopefully this will get better in the
future. Until then!

**Comment by devaublanc** [comment] 2018-09-24 16:46
Same problem here after migrate and deploy the 3.0.0-alpha.14.1.1 release

**Comment by mandaputtra** [comment] 2018-09-28 08:05
3.0.0-alpha.14.2 still problem, if i can help, where I should start?

**Comment by lauriejim** [comment] 2018-09-28 14:36
Warning to this migration https://github.com/strapi/strapi/wiki/migration-guide-alpha.13.1-to-alpha.14#reset-your-content-manager-settings

**Comment by anderson916** [comment] 2018-10-08 15:14
same problem here.

**Comment by derrickmehaffy** [comment] 2018-10-08 15:19
@anderson916 see the comment above yours, there is an incompatibility from older strapi versions with the content manager plugin, you need to purge the content-manager schema entry from your DB in the `core_store` table (or collection in mongo)

**Comment by anderson916** [comment] 2018-10-08 16:40
Yes, it works. 

When I use "straps generate:api" to create a model, one field has a name of "averageFrequency", the field will be changed to "average frequency" in the Admin UI. After I change the name back to "averageFrequency", the Content Manager doesn't work. But as you suggested to remove the content-manager schema entry from your DB in the core_store table (or collection in mongo), and restart Strapi manually, everything is working now.

Thanks. You save my time.

**Comment by derrickmehaffy** [comment] 2018-10-08 17:15
No problem :wink:

**Comment by fsc7** [comment] 2018-10-23 08:58
> @anderson916 see the comment above yours, there is an incompatibility from older strapi versions with the content manager plugin, you need to purge the content-manager schema entry from your DB in the `core_store` table (or collection in mongo)

That did the trick. Thanks for the information.

**Comment by Matildahermansson** [comment] 2018-10-23 10:20
Hi, 

I'm working with a React + Strapi project and when I ran strapi start in my terminal I get to my admin page. However, when I press Content Manager I am met by Content Manager
Configure the default settings for all your Content types where I can either Save or Cancel. Whichever one I choose sends me to a blank page called http://localhost:1337/admin/plugins/content-manager/ctm-configurations
I cannot see any of my products or pics i uploaded a few weeks ago. 
What can i do? 
![screen shot 2018-10-23 at 12 19 53](https://user-images.githubusercontent.com/31923706/47354043-fad18c00-d6bd-11e8-96cc-ecfa7623a682.png)

**Comment by kenn44** [comment] 2018-11-04 00:37
I have the same problem in a fresh project

**Comment by avirankatzsofi** [comment] 2018-11-15 10:39
I still experience this bug in alpha 14.5 - but only on my server (on my local machine everything is fine). On my server, this bug occurs on a fresh project as well.

**Comment by T-Zahil** [comment] 2018-11-30 14:14
Same error here, only on my server too.

**Comment by kenn44** [comment] 2018-11-30 17:49
@avirankatzsofi @T-Zahil  I solved it by running

`npm run setup`

**Comment by rahimimo** [comment] 2018-12-01 10:11
I have also this spinng wheel when I want to add a post and production but not development. Nothing seem to help.

**Comment by javialon26** [comment] 2018-12-03 23:13
Same here with alpha 15. In my local development environment everything works well but in the staging environment, the content manager plugins break. This happens for example when I want to add a new user or edit one.

`TypeError: Cannot read property 'type' of undefined
    at r.renderAttr (main.js:48)
    at Array.map (<anonymous>)
    at t.value (main.js:48)
    at Mo (main.js:16)
    at So (main.js:16)
    at Fo (main.js:16)
    at Jo (main.js:16)
    at Zo (main.js:16)
    at gn (main.js:16)
    at fn (main.js:16)
Ro @ main.js:16
Wo.o.callback @ main.js:16
Jt @ main.js:16
$t @ main.js:16
yn @ main.js:16
gn @ main.js:16
fn @ main.js:16
dn @ main.js:16
on @ main.js:16
enqueueSetState @ main.js:24
i.setState @ main.js:40
d.onStateChange @ main.js:72
l @ main.js:72
(anonymous) @ main.js:72
(anonymous) @ main.js:72
dispatch @ main.js:72
(anonymous) @ main.js:72
(anonymous) @ main.js:72
r @ main.js:72
a @ main.js:72
o @ main.js:72
S @ main.js:72
b @ main.js:72
m @ main.js:72
n @ main.js:72
Promise.then (async)
w @ main.js:72
k @ main.js:72
b @ main.js:72
m @ main.js:72
a @ main.js:72
C @ main.js:72
b @ main.js:72
m @ main.js:72
n @ main.js:72
s @ main.js:72
t @ main.js:72
(anonymous) @ main.js:72
(anonymous) @ main.js:72
r @ main.js:72
a @ main.js:72
o @ main.js:72
(anonymous) @ main.js:72
t @ main.js:72
(anonymous) @ main.js:72
(anonymous) @ main.js:72
value @ main.js:48
yn @ main.js:16
gn @ main.js:16
fn @ main.js:16
dn @ main.js:16
on @ main.js:16
enqueueSetState @ main.js:24
i.setState @ main.js:40
t @ main.js:72
(anonymous) @ main.js:72
Promise.then (async)
s._loadModule @ main.js:72
s.componentWillMount @ main.js:72
fo @ main.js:16
So @ main.js:16
Fo @ main.js:16
Jo @ main.js:16
Zo @ main.js:16
gn @ main.js:16
fn @ main.js:16
dn @ main.js:16
on @ main.js:16
enqueueSetState @ main.js:24
a.setState @ main.js:45
p.onStateChange @ main.js:37
notify @ main.js:37
t.notifyNestedSubs @ main.js:37
p.onStateChange @ main.js:37
notify @ main.js:37
t.notifyNestedSubs @ main.js:37
p.onStateChange @ main.js:37
l @ main.js:45
(anonymous) @ main.js:37
(anonymous) @ main.js:45
dispatch @ main.js:45
(anonymous) @ main.js:45
(anonymous) @ main.js:45
n @ main.js:45
s @ main.js:45
r @ main.js:45
k @ main.js:45
b @ main.js:45
f @ main.js:45
o @ main.js:45
n @ main.js:45
t @ main.js:45
o @ main.js:45
Promise.then (async)
j @ main.js:45
T @ main.js:45
b @ main.js:45
(anonymous) @ main.js:45
S @ main.js:45
b @ main.js:45
f @ main.js:45
o @ main.js:45
Promise.then (async)
j @ main.js:45
T @ main.js:45
b @ main.js:45
f @ main.js:45
o @ main.js:45
C @ main.js:45
b @ main.js:45
f @ main.js:45
s @ main.js:45
P @ main.js:45
b @ main.js:45
f @ main.js:45
o @ main.js:45
i @ main.js:45
t @ main.js:45
(anonymous) @ main.js:45
(anonymous) @ main.js:45
n @ main.js:45
s @ main.js:45
r @ main.js:45
(anonymous) @ main.js:45
t @ main.js:45
(anonymous) @ main.js:45
(anonymous) @ main.js:45
value @ main.js:1
yn @ main.js:16
gn @ main.js:16
fn @ main.js:16
dn @ main.js:16
on @ main.js:16
enqueueSetState @ main.js:24
a.setState @ main.js:45
p.onStateChange @ main.js:37
notify @ main.js:37
t.notifyNestedSubs @ main.js:37
p.onStateChange @ main.js:37
l @ main.js:45
(anonymous) @ main.js:37
(anonymous) @ main.js:45
(anonymous) @ main.js:1
Promise.then (async)
u @ main.js:1
./node_modules/strapi-helper-plugin/lib/src/app.js @ main.js:45
a @ main.js:1
(anonymous) @ main.js:1
(anonymous) @ main.js:1
main.js:72 uncaught at o TypeError: Cannot read property 'type' of undefined
    at r.renderAttr (https://zoopharmapi.mwe.cloud/admin/content-manager/main.js:48:311414)
    at Array.map (<anonymous>)
    at t.value (https://zoopharmapi.mwe.cloud/admin/content-manager/main.js:48:312330)
    at Mo (https://zoopharmapi.mwe.cloud/admin/main.js:16:42968)
    at So (https://zoopharmapi.mwe.cloud/admin/main.js:16:42763)
    at Fo (https://zoopharmapi.mwe.cloud/admin/main.js:16:46086)
    at Jo (https://zoopharmapi.mwe.cloud/admin/main.js:16:59256)
    at Zo (https://zoopharmapi.mwe.cloud/admin/main.js:16:59637)
    at gn (https://zoopharmapi.mwe.cloud/admin/main.js:16:65916)
    at fn (https://zoopharmapi.mwe.cloud/admin/main.js:16:65296)`

The only difference between my environments is the URL (host) and the Nginx reverse proxy for the staging environment.

**Comment by Vishal062** [comment] 2024-09-10 07:32
> For what it's worth, I've encountered this as well, and figured it's the content-manager plugin's config. I've basically just used https://jsonformatter.org/ to format the string @derrickmehaffy mentioned, inside `core_store` under `plugin_content-manager__schema`. The site lets me collapse nodes, and generally has good formatting (to me anyway).
> 
> Just keep a look out for duplicate keys and any keys that you may have removed. These will cause the content-manager page on your admin to not work properly.

Hi When I am update my strapi project from 4.3.9 to 4.4.5 Neither the core_store table were present in old db or new Db
So how to resolve this issue
Getting blank screen on content manager and while adding any new entry
