### ISSUE TITLE
Jwt expiry

### ISSUE THREAD

**Issue by gowthamik14** [strapi/strapi#14482] opened 2022-09-28 09:59 UTC
### Required System information

- Node.js version: 
- NPM version:
- Strapi version: 4.3.8
- Database: mysql
- Operating system:

### Describe the bug
 This is one of the pen test observation where the user left the system for 40 hours  and still able to send Curl request with the jwt token and get response back successfully.

I would like to change the jwt expiry time on admin from 30 d to 3 hrs. However i was testing few scenarios with short duration time using 3m.
Noticed that after 3 min even though i am actively editing the content, when i press Save it is logging me out of the system and taking to login screen.
Is this valid behavior ? 
I would expect that strapi should allow the user to continue using the system instead of logging out (like Sliding expiry time) 
and send a refresh token request by itself

Please let us know how to proceed. 

### Steps to reproduce the behavior
Change the config/admin.js  to below.

auth: {
    secret: env('ADMIN_JWT_SECRET'),
    options: {
      expiresIn: "3m"
    }
  },

**Comment by derrickmehaffy** [comment] 2022-09-28 21:28
Yes this is intended behavior as it's the nature of how JWT's work and the fact our admin panel is CSR not SSR. Every action is an API call to the backend while the admin panel is loaded in the users web browser. 

In the future for security related concerns please forward these requests to security@strapi.io and not the github unless asked by us to open an issue.

For now I'll mark this as closed as the behavior mentioned is intended for now.

**Closed by derrickmehaffy** 2022-09-28 21:28 UTC
