### ISSUE TITLE
GraphQL limit > 100 or limit: -1 is not respected

### ISSUE THREAD

**Issue by kliakos** [strapi/strapi#9959] opened 2021-04-05 15:21 UTC
### Describe the bug

When querying a collection with GraphqQL, specifying a limit greater than 100 query does not return more that 100 records. The same works fine on the REST API, either by specifying `_limit=-1` or a number greater than 100.

### Steps to reproduce the behavior

1. Create a collection and add more than 100 records.
2. Query the records with GQL and limit > 100

### Expected behavior

Either max records for up to the `limit` value should be returned, or all records if `limit: -1`.

### System

- Node.js version: node v14.16.0
- NPM version: 6.14.11
- Strapi version: 3.5.4
- Database: MySQL 8
- Operating system: Ubuntu 20.04

**Comment by derrickmehaffy** [comment] 2021-04-05 16:13
GraphQL has it's own limit option: https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#configurations

Specifically: `amountLimit: 100,`

Marking as closed, as not a bug

**Closed by derrickmehaffy** 2021-04-05 16:13 UTC

**Comment by kliakos** [comment] 2021-04-05 16:14
This is a global option for all GQL queries. We should be able to define this per query, like we can on REST APIs.

**Comment by derrickmehaffy** [comment] 2021-04-05 16:46
> This is a global option for all GQL queries. We should be able to define this per query, like we can on REST APIs.

Submit a feature request please :)

**Comment by kliakos** [comment] 2021-04-05 16:58
No problem, I will do.

However, and no offence by that, in my opinion respecting the limit parameter is the expected behavior, thus not working this way should be considered a bug of the current behavior. But I understand, it's a feature not a bug 😃.
