### ISSUE TITLE
afterCreate - component data not shown in event result when using REST api

### ISSUE THREAD

**Issue by pcriadoperez** [strapi/strapi#14740] opened 2022-10-28 21:28 UTC
### Required System information

- Node.js version: 16
- NPM version: 8.3.1
- Strapi version: 4.4.3
- Database: Postgresql
- Operating system: linux

### Describe the bug

When using a POST API request to create an entity, the component fields are not shown in the event.result

### Steps to reproduce the behavior

1. Create an entity with a relational field
2. Use POST API request to create entity
3. console.log (event.result)

### Expected behavior

- event.result contains component data. Just as it happens when using the admin panel.

**Comment by derrickmehaffy** [comment] 2022-10-31 21:20
Duplicate of the following:
https://github.com/strapi/strapi/issues/3329
https://github.com/strapi/strapi/issues/9178

Lifecycles wrap database entries and relations are not part of that database entry (because there are several database entries). Components at the data query layer are just relations.

**Closed by derrickmehaffy** 2022-10-31 21:20 UTC
Labels: status: duplicate
