### ISSUE TITLE
Yarn V2 build error

### ISSUE THREAD

**Issue by aleccool213** [strapi/strapi#9109] opened 2021-01-12 21:34 UTC
### Describe the bug

When building Strapi with Yarn V2, `yarn build` fails. [Here](https://github.com/aleccool213/strapi-yarn-v2-bug) is a repo where I reproduce the steps taken to produce the bug.

### Steps to reproduce the behavior

1. run `git clone git@github.com:aleccool213/strapi-yarn-v2-bug.git`
2. run `yarn create strapi-app strapi-yarn-v2-bug --quickstart`
3. run `yarn`
4. run `yarn build`
5. See error

```
Error: Module not found: Error: Can't resolve 'strapi-helper-plugin' in '/Users/REDACTED/strapi/.cache/admin/src'
    at /Users/REDACTED/.yarn/cache/strapi-admin-npm-3.4.1-c3c70887db-0c7329154e.zip/node_modules/strapi-admin/index.js:71:23
    at finalCallback (/Users/REDACTED/.yarn/$$virtual/webpack-virtual-c15c32d42a/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/Users/REDACTED/.yarn/$$virtual/webpack-virtual-c15c32d42a/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compiler.js:265:20)
    at /Users/REDACTED/.yarn/$$virtual/webpack-virtual-c15c32d42a/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/Users/REDACTED/.yarn/cache/tapable-npm-1.1.3-f1c2843426-b2c2ab2026.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
    at /Users/REDACTED/.yarn/$$virtual/webpack-virtual-c15c32d42a/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compilation.js:1173:13
    at /Users/REDACTED/.yarn/$$virtual/webpack-virtual-c15c32d42a/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compilation.js:1096:25
    at /Users/REDACTED/.yarn/$$virtual/webpack-virtual-c15c32d42a/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compilation.js:1017:13
    at /Users/REDACTED/.yarn/cache/neo-async-npm-2.6.2-75d6902586-34a8f53091.zip/node_modules/neo-async/async.js:2830:7
    at /Users/REDACTED/.yarn/cache/neo-async-npm-2.6.2-75d6902586-34a8f53091.zip/node_modules/neo-async/async.js:2830:7
    at done (/Users/REDACTED/.yarn/cache/neo-async-npm-2.6.2-75d6902586-34a8f53091.zip/node_modules/neo-async/async.js:2863:11)
    at /Users/REDACTED/.yarn/cache/neo-async-npm-2.6.2-75d6902586-34a8f53091.zip/node_modules/neo-async/async.js:2818:7
    at errorAndCallback (/Users/REDACTED/.yarn/$$virtual/webpack-virtual-c15c32d42a/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compilation.js:883:7)
    at errorOrWarningAndCallback (/Users/REDACTED/.yarn/$$virtual/webpack-virtual-c15c32d42a/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compilation.js:918:17)
    at /Users/REDACTED/.yarn/$$virtual/webpack-virtual-c15c32d42a/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compilation.js:924:16
    at /Users/REDACTED/.yarn/$$virtual/webpack-virtual-c15c32d42a/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/NormalModuleFactory.js:401:22
```

### Expected behavior

Builds and runs.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Comment by derrickmehaffy** [comment] 2021-01-12 23:27
We don't currently support yarn v2 as it's more scoped towards npm v7+ which is only shipped with Node v15+ (We don't support development versions of node).

We plan to look at Node v16 and Yarn v2 later in 2021 closer towards the standard Node LTS release date of october.

**Comment by seniorquico** [comment] 2021-01-13 05:40
@derrickmehaffy What does Yarn v2 have to do with Node v15 or npm v7? We migrated most of our projects to Yarn v2, and we're still on Node v12 LTS. I think this issue was more about Yarn v2's custom Node module resolver (Plug'n'Play) and their stricter approach to dependencies.

> We plan to look at ... Yarn v2 later in 2021

👍

**Comment by alexandrebodin** [comment] 2021-01-13 08:10
I'm actually having the same issue without using yarn v2 in some cases. We are investigating the issue right now it might fix yours at the same time :)

**Comment by aleccool213** [comment] 2021-01-13 14:19
@seniorquico 

After installing `strapi-helper-plugin` explicitly, it still breaks with the same error. Its mostly likely how webpack is resolving modules :/ This likely will be solved in the interim with a custom webpack config.

**Comment by aleccool213** [comment] 2021-02-08 19:36
An update on this issue, I got module resolution working with this custom webpack config:

```javascript

# admin/admin.config.js
const PnpWebpackPlugin = require(`pnp-webpack-plugin`);

module.exports = {
  webpack: (config, webpack) => {
    // Note: we provide webpack above so you should not `require` it
    // Perform customizations to webpack config

    config.resolve = {
      ...config.resolve,
      plugins: [PnpWebpackPlugin],
    };

    config.resolveLoader = {
      ...config.resolveLoader,
      plugins: [PnpWebpackPlugin.moduleLoader(module)],
    };

    // Important: return the modified config
    config.plugins.push(new webpack.IgnorePlugin(/\/__tests__\//));

    return config;
  },
};
```

But not its complaining none of the required modules are installed in the .cache folder when running strapi:

```
 yarn build                                                                                                                                                                                                       11:31:33

● Webpack █████████████████████████ building (13%) 31/53 modules 22 active
 ../../.yarn/cache/regenerator-runtime-npm-0.13.7-41bcbe64ea-6ef567c662.zip/node_modules/regenerator-runtime/runtime.js

Error: Module not found: Error: Your application tried to access lodash, but it isn't declared in your dependencies; this makes the require call ambiguous and unsound.

Required package: lodash (via "lodash")
Required by: /Users/alecbrunelle/Github/live-platform/services/strapi/.cache/admin/src/app.js

    at /Users/alecbrunelle/Github/live-platform/.yarn/$$virtual/strapi-admin-virtual-10ab5cd6ac/0/cache/strapi-admin-npm-3.4.6-937808a04d-b348fb6829.zip/node_modules/strapi-admin/index.js:71:23
    at finalCallback (/Users/alecbrunelle/Github/live-platform/.yarn/$$virtual/webpack-virtual-8a5e2fc3a9/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/Users/alecbrunelle/Github/live-platform/.yarn/$$virtual/webpack-virtual-8a5e2fc3a9/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compiler.js:265:20)
    at /Users/alecbrunelle/Github/live-platform/.yarn/$$virtual/webpack-virtual-8a5e2fc3a9/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/Users/alecbrunelle/Github/live-platform/.yarn/cache/tapable-npm-1.1.3-f1c2843426-b2c2ab2026.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
    at /Users/alecbrunelle/Github/live-platform/.yarn/$$virtual/webpack-virtual-8a5e2fc3a9/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compilation.js:1173:13
    at /Users/alecbrunelle/Github/live-platform/.yarn/$$virtual/webpack-virtual-8a5e2fc3a9/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compilation.js:1096:25
    at /Users/alecbrunelle/Github/live-platform/.yarn/$$virtual/webpack-virtual-8a5e2fc3a9/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compilation.js:1017:13
    at /Users/alecbrunelle/Github/live-platform/.yarn/cache/neo-async-npm-2.6.2-75d6902586-34a8f53091.zip/node_modules/neo-async/async.js:2830:7
    at /Users/alecbrunelle/Github/live-platform/.yarn/cache/neo-async-npm-2.6.2-75d6902586-34a8f53091.zip/node_modules/neo-async/async.js:2830:7
    at done (/Users/alecbrunelle/Github/live-platform/.yarn/cache/neo-async-npm-2.6.2-75d6902586-34a8f53091.zip/node_modules/neo-async/async.js:2863:11)
    at /Users/alecbrunelle/Github/live-platform/.yarn/cache/neo-async-npm-2.6.2-75d6902586-34a8f53091.zip/node_modules/neo-async/async.js:2818:7
    at errorAndCallback (/Users/alecbrunelle/Github/live-platform/.yarn/$$virtual/webpack-virtual-8a5e2fc3a9/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compilation.js:883:7)
    at errorOrWarningAndCallback (/Users/alecbrunelle/Github/live-platform/.yarn/$$virtual/webpack-virtual-8a5e2fc3a9/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compilation.js:918:17)
    at /Users/alecbrunelle/Github/live-platform/.yarn/$$virtual/webpack-virtual-8a5e2fc3a9/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/Compilation.js:924:16
    at /Users/alecbrunelle/Github/live-platform/.yarn/$$virtual/webpack-virtual-8a5e2fc3a9/0/cache/webpack-npm-4.46.0-a8158cfa7f-1e3bc97c01.zip/node_modules/webpack/lib/NormalModuleFactory.js:401:22
```

This makes sense as the .cache package.json npm modules have not been installed yet. Suggestions on what to do next?

**Comment by aleccool213** [comment] 2021-02-08 20:34
Note, webpack v5 supports pnp natively

**Comment by budlight** [comment] 2021-03-26 16:14
still currently breaking for me with 3.5.4 

```
Error: strapi tried to access strapi-admin, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

**Comment by lodisy** [comment] 2021-06-23 17:37
same here, any idea on how to use monorepo with strapi?

**Comment by crubier** [comment] 2021-06-28 11:36
Same kind of problem here (Same problem as @budlight ). 

I really wanted to use (and pay for) Strapi (and I managed to make it work at some point by luck) in our monorepo with yarn v2, but it is broken, will have to use DatoCMS instead...

**Comment by MattieBelt** [comment] 2021-06-28 11:57
> same here, any idea on how to use monorepo with strapi?

You could use yarn (v1) workspaces / lerna for it.

**Comment by vip3rousmango** [comment] 2021-07-19 01:35
I'm also running up against this issue. Has anyone figured out a workaround without having to revert back to yarn v1 workspaces?

**Comment by erald14** [comment] 2021-07-21 07:12
same issue for me. Waiting for a solution

**Comment by erald14** [comment] 2021-07-21 07:36
adding :
pnpMode: loose
in .yarnrc.yml file.
worked for me

https://yarnpkg.com/features/pnp#pnp-loose-mode

**Comment by erald14** [comment] 2021-07-22 12:46
@MattieBelt the issue is not just to use in monorepo. True we could use lerna. Strapi developers need to define their dependencies so that yarn2 PNP works. Until then strapi is unusable, and considering the number of new projects using yarn 2 this really worries me. 
The only way to use this is to go back to nodeLinker: node-modules . not a good solution 😔

**Comment by crubier** [comment] 2021-07-22 13:34
> The only way to use this is to go back to nodeLinker: node-modules . not a good solution 😔

Even with `nodeLinker: node-modules` I ended up with inextricable problems later in the process (using postgres db connector)

No problem with NPM, but now all strapi stuff is in a separate folder in my repo...

**Comment by m-torin** [comment] 2021-11-02 21:29
Strapi v4 Beta 8 is working for me with Yarn 3.10.

**Comment by derrickmehaffy** [comment] 2021-11-02 23:16
Setting as closed/fixed in v4 beta.8 :) Thanks @m-torin

**Closed by derrickmehaffy** 2021-11-02 23:16 UTC
Labels: type: feature request, severity: low, source: core:framework, version: v4-Alpha/Beta

**Comment by diegolameira** [comment] 2022-04-17 05:16
got same error with yarn@3.2.0 and strapi@4.1.8


```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: @strapi/admin tried to access object-assign, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: object-assign
Required by: @strapi/admin@npm:4.1.8 (via ~/workspaces/yarn2/.yarn/cache/@strapi-admin-npm-4.1.8-bb91175257-840c431e85.zip/node_modules/@strapi/admin/)

Require stack:
- ~/workspaces/yarn2/.yarn/cache/@strapi-admin-npm-4.1.8-bb91175257-840c431e85.zip/node_modules/@strapi/admin/webpack.alias.js
- ~/workspaces/yarn2/.yarn/cache/@strapi-admin-npm-4.1.8-bb91175257-840c431e85.zip/node_modules/@strapi/admin/webpack.config.js
- ~/workspaces/yarn2/.yarn/cache/@strapi-admin-npm-4.1.8-bb91175257-840c431e85.zip/node_modules/@strapi/admin/index.js
- ~/workspaces/yarn2/.yarn/unplugged/@strapi-strapi-npm-4.1.8-aa208aeb77/node_modules/@strapi/strapi/lib/commands/build.js
- ~/workspaces/yarn2/.yarn/unplugged/@strapi-strapi-npm-4.1.8-aa208aeb77/node_modules/@strapi/strapi/lib/commands/develop.js
- ~/workspaces/yarn2/.yarn/unplugged/@strapi-strapi-npm-4.1.8-aa208aeb77/node_modules/@strapi/strapi/bin/strapi.js
    at Function.require$$0.Module._resolveFilename (~/workspaces/yarn2/.pnp.cjs:25912:13)
    at Function.resolve (internal/modules/cjs/helpers.js:99:19)
    at ~/workspaces/yarn2/.yarn/cache/@strapi-admin-npm-4.1.8-bb91175257-840c431e85.zip/node_modules/@strapi/admin/webpack.alias.js:40:31
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (~/workspaces/yarn2/.yarn/cache/@strapi-admin-npm-4.1.8-bb91175257-840c431e85.zip/node_modules/@strapi/admin/webpack.alias.js:38:24)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require$$0.Module._extensions..js (~/workspaces/yarn2/.pnp.cjs:25956:33)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.require$$0.Module._load (~/workspaces/yarn2/.pnp.cjs:25796:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (~/workspaces/yarn2/.yarn/cache/@strapi-admin-npm-4.1.8-bb91175257-840c431e85.zip/node_modules/@strapi/admin/webpack.config.js:11:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.require$$0.Module._extensions..js (~/workspaces/yarn2/.pnp.cjs:25956:33)
 ```

**Comment by MrChrisRodriguez** [comment] 2022-04-28 18:25
Yeah, this is not working in yarn@3.2.0 and strapi@4.1.8 or strapi@4.1.9.

A lot of dependencies just aren't strictly defined (and they should be -- it's caused me problems in other places unrelated to yarn pnp)
