### ISSUE TITLE
Adding properties to entities named "<entity name>Id" cause issues when nesting relationship fields

### ISSUE THREAD

**Issue by cody-fjorge** [strapi/strapi#18085] opened 2023-09-15 18:44 UTC
### Required System information

- Node.js version: 16.6.1
- NPM version: 8.2.0
- Strapi version: 4.9.2
- Database: Mysql 2.18.1
- Operating system: mac/windows/linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug
Adding a property to an entity with the name of "<entity name>Id" that also has a relationship property to the same entity, when getting results from the api if you try to read the value of <entity name>Id of the parent from inside the child the value will be the row ID of the child.

### Steps to reproduce the behavior

- Create an entity named 'shirt'
- Add a text prop named 'shirtId'
- Save
- Add a one to many relational field to shirt named variants for the many and variantOf for the one.
- Create a shirt with a shirtId = 'abc'
- Create a shirt with a shirtId = 'xyz'
- Add the second shirt as a variant of the first shirt

 When pulling results from the api:
- The parent shirt's shirtId = "abc" and ID of 1 
- The parent has a variant shirt with a shirtId of "xyz" and ID of 2
- The variant shirt has a variantOf property to reference it's parent 
- The variant shirt's variantOf shirt will have a shirtId of "2" (the ID of the variant) and an ID of 1

### Expected behavior
The <entity name>Id field should be correct when looking at the parent data from the child

### Additional context

If this shirtId property is changed to something like "shirtUid" the bug does not happen.

**Comment by NmN03jain** [comment] 2023-10-02 21:14
can you pls suggest the path or files in which i have to make changes ?

**Comment by Boegie19** [comment] 2023-10-03 19:41
Tryed to reproduce the issue but I got the output like I expected

```
{
   "data":[
      {
         "id":1,
         "attributes":{
            "A":"A",
            "createdAt":"2023-10-03T17:58:22.854Z",
            "updatedAt":"2023-10-03T17:58:37.884Z",
            "publishedAt":"2023-10-03T17:58:37.880Z",
            "Parent":{
               "data":[
                  
               ]
            },
            "Child":{
               "data":[
                  {
                     "id":2,
                     "attributes":{
                        "A":"B",
                        "createdAt":"2023-10-03T17:58:29.948Z",
                        "updatedAt":"2023-10-03T17:58:40.387Z",
                        "publishedAt":"2023-10-03T17:58:40.385Z"
                     }
                  }
               ]
            }
         }
      },
      {
         "id":2,
         "attributes":{
            "A":"B",
            "createdAt":"2023-10-03T17:58:29.948Z",
            "updatedAt":"2023-10-03T17:58:40.387Z",
            "publishedAt":"2023-10-03T17:58:40.385Z",
            "Parent":{
               "data":[
                  {
                     "id":1,
                     "attributes":{
                        "A":"A",
                        "createdAt":"2023-10-03T17:58:22.854Z",
                        "updatedAt":"2023-10-03T17:58:37.884Z",
                        "publishedAt":"2023-10-03T17:58:37.880Z"
                     }
                  }
               ]
            },
            "Child":{
               "data":[
                  
               ]
            }
         }
      }
   ],
   "meta":{
      "pagination":{
         "page":1,
         "pageSize":25,
         "pageCount":1,
         "total":2
      }
   }
}
```

**Comment by jason-Impress** [comment] 2023-10-04 04:50
Getting this issue too. My attribute is "formId" and the REST API only ever returns "1" for the value when it's retrieved through a relationship in a dynamic zone component.

**Comment by Boegie19** [comment] 2023-10-04 09:04
> Getting this issue too. My attribute is "formId" and the REST API only ever returns "1" for the value when it's retrieved through a relationship in a dynamic zone component.

Mind giving me the content type like you use it with replication staps?

**Comment by Boegie19** [comment] 2023-10-04 09:04
> Getting this issue too. My attribute is "formId" and the REST API only ever returns "1" for the value when it's retrieved through a relationship in a dynamic zone component.

Mind giving me the content type like you use it with replication staps?

**Comment by cody-fjorge** [comment] 2023-10-04 19:36
> Tryed to reproduce the issue but I got the output like I expected
> 
> ```
> {
>    "data":[
>       {
>          "id":1,
>          "attributes":{
>             "A":"A",
>             "createdAt":"2023-10-03T17:58:22.854Z",
>             "updatedAt":"2023-10-03T17:58:37.884Z",
>             "publishedAt":"2023-10-03T17:58:37.880Z",
>             "Parent":{
>                "data":[
>                   
>                ]
>             },
>             "Child":{
>                "data":[
>                   {
>                      "id":2,
>                      "attributes":{
>                         "A":"B",
>                         "createdAt":"2023-10-03T17:58:29.948Z",
>                         "updatedAt":"2023-10-03T17:58:40.387Z",
>                         "publishedAt":"2023-10-03T17:58:40.385Z"
>                      }
>                   }
>                ]
>             }
>          }
>       },
>       {
>          "id":2,
>          "attributes":{
>             "A":"B",
>             "createdAt":"2023-10-03T17:58:29.948Z",
>             "updatedAt":"2023-10-03T17:58:40.387Z",
>             "publishedAt":"2023-10-03T17:58:40.385Z",
>             "Parent":{
>                "data":[
>                   {
>                      "id":1,
>                      "attributes":{
>                         "A":"A",
>                         "createdAt":"2023-10-03T17:58:22.854Z",
>                         "updatedAt":"2023-10-03T17:58:37.884Z",
>                         "publishedAt":"2023-10-03T17:58:37.880Z"
>                      }
>                   }
>                ]
>             },
>             "Child":{
>                "data":[
>                   
>                ]
>             }
>          }
>       }
>    ],
>    "meta":{
>       "pagination":{
>          "page":1,
>          "pageSize":25,
>          "pageCount":1,
>          "total":2
>       }
>    }
> }
> ```

This looks like you didn't setup the fields correctly from my reproduction steps since there is no field named <entityName>Id (ex. shirtId if the entity is named shirt).

**Comment by Boegie19** [comment] 2023-10-04 20:16
I see now I am closing it since there is a tracking issue for this. https://github.com/strapi/strapi/issues/18085

**Comment by derrickmehaffy** [comment] 2024-03-12 18:04
I'm able to reproduce it on v4.20.4.

Here is the content-type schema I used:

```json
{
  "kind": "collectionType",
  "collectionName": "shirts",
  "info": {
    "singularName": "shirt",
    "pluralName": "shirts",
    "displayName": "shirt",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "shirtId": {
      "type": "string"
    },
    "variants": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::shirt.shirt",
      "mappedBy": "variantOf"
    },
    "variantOf": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::shirt.shirt",
      "inversedBy": "variants"
    }
  }
}
```

You need two entries with the relation set on one of them:

![image](https://github.com/strapi/strapi/assets/8593673/3e01e9de-5d68-47d3-911b-96b9b5a366d8)
![image](https://github.com/strapi/strapi/assets/8593673/54752715-78be-4b1b-a817-6b86556117cc)

Here is the request you need to make: `localhost:1337/api/shirts?populate[variants][populate]=*`

Response payload:

![image](https://github.com/strapi/strapi/assets/8593673/4a9ab131-9897-45f7-901f-eba66dd1c0bc)

**Comment by derrickmehaffy** [comment] 2024-03-22 14:57
Tested on 5.0.0-beta.0 and the issue is still there but the odd thing is it only appears at a deeper than 1 nesting level.

![image](https://github.com/strapi/strapi/assets/8593673/27143704-a56a-42e3-ace3-48a6ac5e9fd6)

**Closed** 2024-04-17 13:14 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:strapi, version: 5, version: 4
