### ISSUE TITLE
[v4] - Strapi can't handle many records.

### ISSUE THREAD

**Issue by rserafim** [strapi/strapi#12004] opened 2021-12-23 00:35 UTC
### Describe the bug
Error accessing a record in admin.

Strapi can't handle working with too many records. I only have 1 million and he is crying. I still need to go up another 5 million.

This error only happens when I click on a record that is related to a city that has hundreds of companies.

If I click on a record, in which the city has dozens of companies, the error doesn't happen.

That's because it's running on localhost.

### Steps to reproduce the behavior

1. Go to /content-manager/collection-types
2. Click on any register
3. See error

### INFO REGISTER COMPANY ID = 1314737
total companies same city = 235611
total companies same category = 272

### Expected behavior

Show the data like the example below.

INFO REGISTER COMPANY ID = 2
total companies same city = 1
total companies same category = 2
![image](https://user-images.githubusercontent.com/48859044/147245570-0439a4a4-c094-451b-836e-2d7eb166b4a4.png)

### Screenshots
INFO REGISTER COMPANY ID = 1314737
![image](https://user-images.githubusercontent.com/48859044/147169579-0bd42b2a-51fe-4e95-aee1-5a397256df84.png)
![image](https://user-images.githubusercontent.com/48859044/147169898-cd3f08c8-83be-4f27-93ef-fb4cdd67aee6.png)

Searching via Graphql the result comes correctly.
![image](https://user-images.githubusercontent.com/48859044/147170164-a1c9fba4-22f1-41f3-b39c-546fa7abdbd0.png)

### Code snippets

`[2021-12-22 21:10:46.340] error: select distinct "t0".*, "t1"."company_id" from "categories" as "t0" left join "companies_category_links" as "t1" on "t0"."id" = "t1"."category_id" where ("t1"."company_id" in ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, ....)) - bind message has 39003 parameter formats but 0 parameters
    at Parser.parseErrorMessage (/Volumes/SSD Externo/_PROJETOS/XXX/XXX/api-portalfull-v2/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Volumes/SSD Externo/_PROJETOS/XXX/XXX/api-portalfull-v2/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Volumes/SSD Externo/_PROJETOS/XXX/XXX/api-portalfull-v2/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Volumes/SSD Externo/_PROJETOS/XXX/XXX/api-portalfull-v2/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)`

And if it keeps trying to show the registration data (blank screen print), some time later this error will appear.
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`
### System

- Node.js version: v14.16.0
- YARN version: 1.22.17
- Strapi version: v4
- Database: DOCKER/POSTGRES
- Operating system: macos

### Content-Type COMPANY
![image](https://user-images.githubusercontent.com/48859044/147243172-67b3b73f-2e2b-4c79-8cad-9d7de715d3cc.png)
![image](https://user-images.githubusercontent.com/48859044/147243208-d32e4162-7158-4e2a-b429-ae820c080e63.png)

### DATA INFOS
total companies = 1.229.134
total cities = 10.186
total categories = 2.351

**Comment by qant** [comment] 2021-12-23 10:11
Imo you should try get less data, its seems not strapi error, its your error because of to many data in one query.
So try to avoid is some how, its your app, you need to think how to organize data, for example separate the queries or put some limits etc. I hope it helps

**Comment by rserafim** [comment] 2021-12-23 12:13
> Imo you should try get less data, its seems not strapi error, its your error because of to many data in one query. So try to avoid is some how, its your app, you need to think how to organize data, for example separate the queries or put some limits etc. I hope it helps

I'm not fetching lots of data. It is only 1 record with a relation of 1 city and 1 category. Just it!

**Comment by derrickmehaffy** [comment] 2021-12-23 18:42
Can you please test with v4.0.2 (also in the future please specify your exact version not just `v4`)

We modified the logic in the list and edit views for population.

**Comment by rserafim** [comment] 2021-12-23 23:10
> Can you please test with v4.0.2 (also in the future please specify your exact version not just `v4`)
> 
> We modified the logic in the list and edit views for population.
I upgraded and rebuilt the dashboard. But nothing has changed, the error continues.

![image](https://user-images.githubusercontent.com/48859044/147298179-dd0c5ae6-c6e3-4950-85bf-57eda035576f.png)

![image](https://user-images.githubusercontent.com/48859044/147298507-e2a468da-c626-4c2f-9bd5-18d5c17db4c4.png)

**Comment by derrickmehaffy** [comment] 2021-12-27 16:12
Even trying to remotely create the number of entities you have I can't reproduce this at all.

**Comment by rserafim** [comment] 2021-12-28 02:07
> derrickmehaffy

I created a new repository and a new database with fake data. I sent the invitation and you can reproduce the same error.
Thank's for your time.

**Comment by derrickmehaffy** [comment] 2021-12-28 16:46
You didn't link to the repo? :confused:

**Comment by derrickmehaffy** [comment] 2021-12-28 16:53
It doesn't appear your repo has the database though

**Comment by rserafim** [comment] 2021-12-28 18:42
> It doesn't appear your repo has the database though

is configured directly in database.js

**Comment by derrickmehaffy** [comment] 2021-12-28 19:04
> > It doesn't appear your repo has the database though
> 
> is configured directly in database.js

I mean.... Using a PostgreSQL database over the internet is obviously not a good idea, the latency alone would trigger basically every warning in the tarn.js pooling system and probably just kill the connections.

Are you attempting to use a remote database also?

**Comment by rserafim** [comment] 2021-12-29 00:07
> > > It doesn't appear your repo has the database though
> > 
> > 
> > is configured directly in database.js
> 
> I mean.... Using a PostgreSQL database over the internet is obviously not a good idea, the latency alone would trigger basically every warning in the tarn.js pooling system and probably just kill the connections.
> 
> Are you attempting to use a remote database also?
> 
> Edit: I'm grabbing a DB backup of this remote database so I can test locally. If you are trying to use this remotely that is almost certainly going to be a problem.

No. I'm using localhost (Docker).

It's just for you to access and download.

**Comment by supryantowp** [comment] 2022-01-03 10:08
same issue

**Comment by signly-projects** [comment] 2022-01-12 17:16
I have a very similar issue, if not the same.

### System

OS: Ubuntu 20.04
Env: local / dev (not docker)
Strapi v4.0.4
Node v16.13.2
Yarn v1.22.17
Database: PostgreSQL v14.1

### Scenario

Content type Words
**Words** _has and belongs to many_ **Paragraphs** 

Content type Paragraphs
**Paragraphs** _has and belongs to many_ **Words** 
**Page** _has many_ **Paragraphs**

Content type Page
**Paragraphs** belongs to many **Pages**
**Book** _has many_ **Pages**

Content type Book
**Book** _belongs to many_ **Pages**

If I try to view a single word/paragraph/page, in the Admin Panel -> Content Management, and if the amount of **words** is highish (~1000) the operation takes ages (~30 secons) to complete (CPU usage increases, Memory usage increases too).

If the amount of **words** is around 100k I get a JavaScript memory leak.

**Comment by appanchor** [comment] 2022-01-18 16:13
Hello. I had a similar issue. It was taking ~5 seconds to load one record with 200 relations in Content Manager.

The issue is with the [getDeepPopulate](https://github.com/strapi/strapi/blob/b6061783326542a5fbf9ad673d42fc32daba39d1/packages/core/content-manager/server/services/entity-manager.js#L43) function in the content-manager entity-manager service. The populate object that it generates is 3 levels deep, which results in a very large response because of duplicated data. [Here](https://gist.github.com/appanchor/2f6eefbb04f45d97bda7f90699b37453) is an example of the response coming back from /content-manager/collection-types/api::employee.employee/1. You'll see that each hoursRecord contains employee data that also includes all hoursRecords. The example has just 2 hoursRecords, but you can imagine how large this response gets with 200.

I resolved this issue by changing [this line](https://github.com/strapi/strapi/blob/b6061783326542a5fbf9ad673d42fc32daba39d1/packages/core/content-manager/server/services/entity-manager.js#L59) to the following: 

59   `? { populate: getDeepPopulate(attribute.target, null, 3) }`

Setting depth to 3 here forces populate to one level for relations, which prevents the large deeply-nested response from Content Manager. I'm not sure if this is the best approach to resolve this issue, but it's working for me. I have no need for a deeply-nested response with relationships, and Content Manager doesn't seem to require this either. Hope this helps!

**Comment by petersg83** [comment] 2022-01-18 16:50
I could reproduce the bug. Thank you, we will work on it

**Comment by margani** [comment] 2022-02-02 09:32
Why does it populate when the top filter in content manager UI doesn't support fields from relations? Shouldn't it populate only when in API, the user is setting the populate query string?

**Comment by derrickmehaffy** [comment] 2022-02-03 17:58
That is a good question, and yes you are correct. It shouldn't be populating that deep and/or only selecting the stuff it needs.

**Comment by GraemeFulton** [comment] 2022-02-18 11:03
I too am having this issue, just by having 12k+ posts with simple tags and authors relations as shown in below screenshot.

The Tags and Author relation, I copied from [this tutorial](https://strapi.io/blog/building-a-css-tricks-website-clone-with-strapi-next-js).

* Tags has and belongs to many Articles 
* Author has many articles

After removing both relations, my admin dashboard can load all posts, but leaving them in causes it to crash. I can't use the dashboard until there is some solution - is there any time estimate on when this might be fixed? thanks a lot!

<img width="533" alt="Screenshot of strapi content type, showing tags and author relation" src="https://user-images.githubusercontent.com/4354786/154670242-5847dba5-f3ae-40f9-9608-ddc0950c06c7.png">

**Comment by ScyDev** [comment] 2022-03-01 08:44
I have the same problem. We have a hierarchy of categories that can have thousands of products. The Strapi admin backend becomes unusable. It worked fine with Strapi v3, where it was possible to prevent populating of a relation with just one line of code.

This is preventing us from launching production. Can we have an ETA please?

**Comment by DanielSusanu** [comment] 2022-03-02 12:00
Hey guys, I have the same problem as @GraemeFulton and @appanchor. There is no need to deep populated the relations in the content-manager when viewing a content type. You could just get and display the top 10 items from each relation, for each relation entity get the entity title because thats what you actually display and the id to link to that entity if needed. Show a count for each relation and load more button to load more data if needed. You could also exlude the relation from the query if the relation is disabled from the view.

I think that the above will improve the performance of the content-manager, right now is quite unusable when having large data and relations between them.

Since many of us have the same issue could you please prioritize this issue and let us know about an ETA please?

Kind Regards,

**Comment by petersg83** [comment] 2022-03-02 12:57
Hi everyone! Sorry for the inconvenience, we know it is an important problem. I will work on it in the coming days, limiting the population to 20 entries or so. The fix would probably be out in the next release, in 2 weeks then :)

**Comment by DanielSusanu** [comment] 2022-03-02 13:11
Hey @petersg83, could you please also limit the deep population to 2 or 3 at most. 
Thanks a lot, really appreciate your hard work. 
Kind Regards

**Comment by sjoukedv** [comment] 2022-03-04 10:25
@petersg83 Maybe this helps locate the issue: my issue was originally with the `up_users` collection. Whenever the role is not populated the entries load instantly like they should.

**Comment by petersg83** [comment] 2022-03-04 10:35
Hi @DanielSusanu :) in which part of the app ? The deep population is already limited to 2 levels in the admin panel

Thanks @sjoukedv the problem is well identified

Actually, I started to look at the code and it's more complicated than I thought. Sorry for the false hope but I don't think it will be fixed for the next release. I cannot give an ETA. But do know that we have planned to rework how we handle the relations in the admin panel. So the issue will be addressed there if not before. (In the meantime we will implement folders in the ML)

**Comment by DanielSusanu** [comment] 2022-03-04 13:52
Hey @petersg83, thanks for the reply. 
Thats when editing a collection type. Right now the downloaded data for a collection type is 19.6MB and I was very surprised because I expected  to be < 10KB.

Example of my collection type.

Collection for a smarphone model.

This smartphone has 
manufacturer: 1
device_type: 1
services: 24
colors: 6
storages: 3 

The schema for the attributes with a type of relation 
"manufacturer": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::manufacturer.manufacturer",
      "inversedBy": "models"
    },
    "device_type": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::device-type.device-type"
    },
    "services": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::service-type.service-type",
      "inversedBy": "models"
    },
    "colors": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::model-color.model-color"
    },
    "storages": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::model-storage.model-storage"
    }

Now imagine that I might have all of the smarphone models that exist for all manufacturers. 
When you get the data to show in the page If you deep populate the service-type that would also get all of the models that exist (that can be 1000+ models).


Let me know if you need more details and I'll be happy to help.

Kind Regards,

**Comment by petersg83** [comment] 2022-03-04 14:26
Ok thank you. I think what you describe is not really related to populating deep but just that we populate without a limit. We populate the first level of relations but don't have for the moment a limit on the population so if you have 1000 relations for one entity, it will fetch them all, which should not be the case. The long term idea is to put a pagination on the relations

**Comment by DanielSusanu** [comment] 2022-03-04 14:35
Yea that would improve the performace a lot. You could also limit the attributes that you get for the entities, I don't think that you need more than the entity title and the entity id, unless you are doing something else in the background.

**Comment by petersg83** [comment] 2022-03-04 15:56
@DanielSusanu You were actually right for the deep populate. I thought it was limited to 2 but it is limited to 3 and it changes everything ^^ I set it to 1 for the relations (need to keep deepPopulate for components). The fix should be released in 2 weeks then :) It's a emotional roller-coaster :p

**Comment by DanielSusanu** [comment] 2022-03-04 16:16
Hey @petersg83 thanks for find the issue and the fix. Just make sure you limit the deepPopulate for the components to 2 otherwise I imagin that you will have the same issue.

Will let you know how it performes once you release it. 
Many thanks.

**Closed** 2022-03-08 09:04 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:database

**Comment by DanielSusanu** [comment] 2022-03-12 10:39
Hey @petersg83 thanks for sorting this out. A huge load time improvement, day and night difference.  
Kind Regards,

**Comment by ScyDev** [comment] 2022-04-22 10:30
Unfortunately I still have the same issue on Strapi 4.1.8.
A category that has 5000 products will take upwards of 30 seconds to load in the content manager.
That's on a very powerful dev machine.

Do I need to configure something to make this have an effect? From what I gathered, in Strapi 4 we can't configure the populating behavior of a model, correct?

**Comment by petersg83** [comment] 2022-04-25 09:49
@ScyDev Would you be able to share the response content of the request for this category? Taken from the browser developer console?

I don't think there are more quick fixes for the moment, however it is planned that we rework the relation management in the next months and the loading problem will be gone

**Comment by ScyDev** [comment] 2022-04-26 09:33
@petersg83 Yes, here it is: 
[Strapi Content Manager Category Response.zip](https://github.com/strapi/strapi/files/8561808/Strapi.Content.Manager.Category.Response.zip)


Is there another issue I can track for progress on that rework?

**Comment by Keith-Hon** [comment] 2022-05-04 10:12
Experiencing performance issues when i have about 200k entities on a collection. Only the first 10 records shown should populate. But it takes ~8s to load the first page.

**Comment by petersg83** [comment] 2022-05-05 21:56
Thank you @ScyDev! From what you sent I confirm it doesn't look like a quick fix can be made. 
@Keith-Hon What do you mean by "Only the first 10 records shown should populate." ? Do you think about and infinite scroll ?

**Comment by Keith-Hon** [comment] 2022-05-06 03:56
> Thank you @ScyDev! From what you sent I confirm it doesn't look like a quick fix can be made. @Keith-Hon What do you mean by "Only the first 10 records shown should populate." ? Do you think about an infinite scroll ?

Hi @petersg83, im not thinking about infinite scroll. I was wondering what caused the slowness in loading only the first 10 records from a collection. 

![image](https://user-images.githubusercontent.com/23226987/167064203-e3c9491d-b479-4555-87dd-6ef9724d7ff1.png)

When there are 10 records per page, only these 10 records, and the count of the total number of records in such table should be selected from the database in order to load the page. But it takes too much time to load currently, so i wonder what went wrong in terms of implementation.

**Comment by ScyDev** [comment] 2022-05-06 06:55
@petersg83 Is there another issue we can track for progress on that rework, so we can be updated? Btw. this was not a problem in Strapi v3, really strange that v4 performs that much worse.

**Comment by petersg83** [comment] 2022-05-06 07:47
oh ok @Keith-Hon. So you are talking about the `list view` and @ScyDev is talking about the `edit view`. Is it correct?
@Keith-Hon Can you share the schema of your collection please? If it has relations, could you estimate the average number of entities for each xToMany entity? So I can try to reproduce with your usecase.

@ScyDev I think you can follow this feature on Canny https://strapi.canny.io/customization/p/move-relations-into-the-main-view to receive an email when the feature is out :)

**Comment by ScyDev** [comment] 2022-05-06 07:51
@petersg83 Yes, I'm talking about the `edit view` of an entity that has a relation with thousands of child entries. Thanks, I'll check that issue.

**Comment by petersg83** [comment] 2022-05-06 07:59
@ScyDev Yes we will more likely add pagination on the relation so the performance will be impacted to :)
