### ISSUE TITLE
[BUG] Drag and Drop is not working on View editing

### ISSUE THREAD

**Issue by SalahAdDin** [strapi/strapi#20222] opened 2024-04-28 00:49 UTC
### Required System information

- Environment: development
- OS: Linux-x64
- Strapi Version: 5.0.0-beta.5
- Node/Yarn Version: yarn/4.1.1 npm/? node/v20.12.2 linux x64
- Edition: Community
- Database: SQLite
- Typescript

### Describe the bug

When we try to change the List View columns order using drag and drow, the items are not reordered at all; we have to remove all columns and add them again in the wanted order.

### Steps to reproduce the behavior

1. Go to the **Content Manager**.
2. Click on the Collection Type you will work with.
3. Click on the cog icon on the right side.
4. Click on Edit view.
5. Choose a column to reorder and drag and drop it.
6. See the error.

### Expected behavior

Dragging and dropping a column should update the column order on the database and render it on the admin panel as well.

### Screenshots

![DragAndDrawNotWorkingStrapi5-2](https://github.com/strapi/strapi/assets/5034215/2a345f01-fd64-4ad4-95b9-88651e209022)

**Comment by SalahAdDin** [comment] 2024-06-07 03:30
UPDATE: 

I checked it and It is also failing in Edit Entity View:

![Drag DropEditView](https://github.com/strapi/strapi/assets/5034215/31f40a9d-d253-4cef-9614-bd81d4b3426c)

**Comment by AlcaYezzz** [comment] 2024-06-25 11:21
Could this be linked also to https://github.com/strapi/strapi/issues/17489 ?

**Comment by SalahAdDin** [comment] 2024-06-27 19:32
It is still happening in the release candidate version:
```sh
Launched In: 385 ms
Environment: development
OS: linux-x64
Strapi Version: 5.0.0-rc.0
Node/Yarn Version: yarn/4.3.1 npm/? node/v20.12.2 linux x64
Edition: Community
Database: sqlite
[2024-06-27 14:32:19.647] info: Shutting down Strapi
[2024-06-27 14:32:19.649] info: Strapi has been shut down
```

**Comment by alexandrebodin** [comment] 2024-08-28 15:39
Hi, I cannot reproduce this issue in the latest release candidates. Going to close this. Let us know if you still have some issue in the latest versions :)

**Closed by alexandrebodin** 2024-08-28 15:39 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-manager, version: 5

**Comment by SalahAdDin** [comment] 2025-01-23 02:48
@alexandrebodin 
I checked it and it is still happening, it seems the right way to reorder the fields is moving over the fields, and it is not intuitive.

https://github.com/user-attachments/assets/c88c8e68-5658-4677-9e1d-f27029f8cba4
https://github.com/user-attachments/assets/5110d817-37d9-4097-99b1-1052b3379e6d

It goes even more complex:

https://github.com/user-attachments/assets/58aa6c2b-eafb-48eb-acf0-8e6fc2063b03


# Required System information
 pnpm strapi report                                                           ✔ 

> strapi-template@1.0.1 strapi /media/Storage/Projects/Experiments/strapi-template
> strapi "report"

Launched In: 662 ms
Environment: development
OS: linux-x64
Strapi Version: 5.8.0
Node/Yarn Version: pnpm/9.14.4 npm/? node/v22.13.1 linux x64
Edition: Community
Database: sqlite
[2025-01-22 21:46:03.905] info: Shutting down Strapi
[2025-01-22 21:46:03.906] info: Strapi has been shut down

**Comment by ZZXCOIN** [comment] 2025-01-23 09:50
The bug is still present in the latest version!

**Comment by SalahAdDin** [comment] 2025-01-23 22:38
> The bug is still present in the latest version!

@alexandrebodin  up!

**Comment by Kyle772** [comment] 2025-04-09 21:29
Still running into this issue on 5.12.4 @derrickmehaffy @alexandrebodin 

I searched the error here in the project issues and it seems like all ~12 of these tickets have been closed without any proper followup or investigation. I recently updated from v4 so it's possible it's only triggered on a migrated project?

**Comment by SalahAdDin** [comment] 2025-04-10 04:08
> Still running into this issue on 5.12.4 [@derrickmehaffy](https://github.com/derrickmehaffy) [@alexandrebodin](https://github.com/alexandrebodin)
> 
> I searched the error here in the project issues and it seems like all ~12 of these tickets have been closed without any proper followup or investigation. I recently updated from v4 so it's possible it's only triggered on a migrated project?

We have to open as many as issues required till the issue is fixed.

**Comment by alexandrebodin** [comment] 2025-04-10 05:57
We have someone actively working on this issue, we are using a new lib and need to refactor quite a few things to fix it.

**Comment by Kyle772** [comment] 2025-04-10 20:41
> We have someone actively working on this issue, we are using a new lib and need to refactor quite a few things to fix it.

What was the last stable version before react dnd got added? I downgraded several versions and am running into the same issue on all of them. I can't access the content manager at all, not even just when adjusting the view. :/

**Comment by Kyle772** [comment] 2025-04-11 01:13
I was able to fix the drag and drop context missing by removing "@strapi/icons": "^1.8.2". Not sure why this worked but I have isolated it to being this dependency that was breaking things.

**Comment by SalahAdDin** [comment] 2025-04-11 14:26
> I was able to fix the drag and drop context missing by removing "@strapi/icons": "^1.8.2". Not sure why this worked but I have isolated it to being this dependency that was breaking things.

Crazy, maybe that library is overriding another one...
