### ISSUE TITLE
Collection Type not getting displayed after creation in sidebar

### ISSUE THREAD

**Issue by xcorman** [strapi/strapi#10253] opened 2021-05-06 10:31 UTC
### Describe the bug

I created few collection type in content builder but after creation they dont show in the sidebar. This was the fresh Strapi installation.. By default when I installed Strapi, v3.4.4 came with that. I thought it was version issue to I tried to upgrade latest 3.6.1 but same issue there as well. 

### Steps to reproduce the behavior

1. Created new `Collection Type` in `Content Builder`
2. It waited for restart.
3. Soon after, in sidebar `Collection Type` not displayed.

To fix I tried:  `npm run build --clean`, also tried to reinstall all modules and rebuild everything

### Screenshots

![image](https://user-images.githubusercontent.com/63841969/117283244-39e21a00-ae83-11eb-9f84-0073849ee735.png)

### System

- Node.js version: 14.15
- NPM version: 6.14.8
- Strapi version: 3.4.4/3.6.1
- Database: MongoDB
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment] 2021-05-06 18:16
@xcorman is your project code somewhere public like in a GitHub repo that I can look at?

**Comment by xcorman** [comment] 2021-05-06 18:18
No, this is private currently

**Comment by derrickmehaffy** [comment] 2021-05-07 17:57
Are you able to reproduce this in a fresh project as I can't reproduce this with the current information.

**Comment by xcorman** [comment] 2021-05-08 12:45
Yes, this is only happening with MongoDB, every other DB is working. just moved to MySQL instead

**Comment by derrickmehaffy** [comment] 2021-05-10 19:34
Sounds good, marking as closed

**Closed by derrickmehaffy** 2021-05-10 19:34 UTC
Labels: status: can't reproduce
