### ISSUE TITLE
File field private option not working in admin

### ISSUE THREAD

**Issue by mikaoelitiana** [strapi/strapi#10105] opened 2021-04-22 17:55 UTC
### Describe the bug

I have created a `FIle` field on admin that I want to make private in API so I check the option but it cannot be save from admin panel. Everytime I set it there and save, the value is reset.

<img width="957" alt="Screenshot 2021-04-22 at 19 47 31" src="https://user-images.githubusercontent.com/674667/115762626-f6c47900-a3a3-11eb-8aa0-f7777e5721b5.png">

I am able to set the value directly in the model setting file and result works as expected on the API response : 

<img width="293" alt="Screenshot 2021-04-22 at 19 47 59" src="https://user-images.githubusercontent.com/674667/115762734-1196ed80-a3a4-11eb-985b-95725d0566f5.png">

### Steps to reproduce the behavior

1. Go to 'Admin > Content-Types Builder'
2. Create or edit a content type having a file field 
3. Go to 'Advanced Settings'
4. Check 'Private field' option
5. Save the content type
6. Reopen the field setting and see unchecked option

### Expected behavior

Private option should be set and model setting file updated

### Screenshots

See descriptions above

### System

- Node.js version: 14.15.1
- NPM version:
- Strapi version: 3.6.0
- Database: Postgres
- Operating system: OSX

**Comment by TheSeally** [comment] 2021-04-28 21:29
Hello. Can I take this issue?

**Comment by marcoautiero** [comment] 2023-03-05 21:54
Closing because the issue doesn't exist in v4

**Comment by joshuaellis** [comment] 2023-03-13 16:24
@gu-stav was able to reproduce this, however @Marc-Roig has made a PR fix 👍🏼

**Closed** 2023-03-13 17:25 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-type-builder
