### ISSUE TITLE
Users can't sign up with social authentication

### ISSUE THREAD

**Issue by bahdcoder** [strapi/strapi#1521] opened 2018-07-05 10:49 UTC
**Informations**
- **Node.js version**:
9.10.1
- **npm version**:
5.6.0
- **Strapi version**:
 v3.0.0-alpha.12.6
- **Database**:
mongodb
- **Operating system**:
macosHighSierra

**What is the current behavior?**

When users try to sign up with provider authentication, even if it's their first time, api responds with `Auth.form.

This issue is exactly what is described in #1358. 

**Steps to reproduce the problem**

- Create new strapi app
- Enable a new provider
- Create a simple client side application and pass token to strapi api for registration.
- This action always returns Email already taken.

**What is the expected behavior?**

- Users can register by social auth

**Suggested solutions**

The problem was pointed out in the issue i linked above. In the user-permissions/services/Providers.js file, the connect function has this line of code:

```js
if (!_.isEmpty(_.find(users, user => user.provider !== provider)) && advanced.unique_email) {
          return resolve([null, [{ messages: [{ id: 'Auth.form.error.email.taken' }] }], 'Email is already taken.']);
        }
```

This code has a problem, and I think it's supposed to check if the email is duplicated 🤔? cc @lauriejim .
I can raise a fix, but please let's understand what exactly the problem is.

**Comment by derrickmehaffy** [comment] 2018-07-05 10:53
I've seen some other issues related to providers, I think more than just this part probably needs a double check to make sure everything is working as intended.

**Comment by soupette** [comment] 2018-07-05 17:39
@bahdcoder while working on this [boilerplate](https://github.com/strapi/strapi-examples/tree/update-boilerplate/create-react-app-sdk) I have tested the providers again and it was working.

Can you try again? If you registered to strapi with the same email address that you use when you try to register with per say 'Facebook' you need to disable the `unique email address` option.

**Comment by bahdcoder** [comment] 2018-07-06 02:05
@soupette I have tried again, and the problem is not having duplicate email addresses. I made sure the email wasn't duplicated and spent a long time trying to find out what's wrong. I really think there's a problem here. I had to modify the code in my project just to get it to work. Could you please check again with the latest version of strapi?
thanks.

**Comment by daqst** [comment] 2018-07-09 14:31
I have been able to reproduce what I am confident is the same bug.  @soupette it doesn't matter if using the boilerplate or not, the boilerplate code is just calling `localhost:1337/connect/<provider>`.  So using the boilerplate to call it, or just starting a Strapi instance and navigating to connect/provider manually has the same effect.

Steps to reproduce:
- Install new Strapi instance (alpha 12.6, though I've had this problem since 12.4). `strapi new strapi-test`.  Database doesn't matter, I tested with both MongoDB and mySQL.
- Start the Strapi instance `cd strapi-test && strapi start`
- Create a new admin user (`user: admin   pass: admin   email: admin@domain.com`)
- Enable Google auth provider.
- Navigate to `localhost:1337/connect/google` in a browser
- Log in with Google account (email will not be the same as the admin user (it can't be)...
- Strapi returns `Auth.form.error.email.taken` error.

So this has been addressed in an earlier issues.  The most relevant is #908.  In that issue, after making a PR, what looks to be the real bug was found and addressed but never fixed and the issue was closed.

The problem seems to be at [https://github.com/strapi/strapi/blob/5cba57f91dee81e625a7824318f9963c2526dd5d/packages/strapi-plugin-users-permissions/services/Providers.js#L49](url).

The call here is to find all users that have the same email as the one provided by the provider. `email: profile.email`  However, looking at the Bookshelf and Mongoose `find` functions you will see that they are both expecting `params.where`.  Since this is never provided, both functions will return a list of ALL users.  In the case above this is the admin user with the email `admin@domain.com` and the provider `local`.

This should be fixed, as suggested in #908 by changing line 49.  The problem here is `mongoose.js` - 
[https://github.com/strapi/strapi/blob/5cba57f91dee81e625a7824318f9963c2526dd5d/packages/strapi-plugin-users-permissions/config/queries/mongoose.js#L6](url) and `bookshelf.js`  - [https://github.com/strapi/strapi/blob/5cba57f91dee81e625a7824318f9963c2526dd5d/packages/strapi-plugin-users-permissions/config/queries/bookshelf.js#L9](url) expect different syntax.  Mongoose looks for params.where while bookshelf uses `params.where` with sub-parameters `symbol` and `value`.

This means if line 49 in `Providers.js` is changed, to work with bookshelf, the it needs to be:
`where: { email: { symbol: '=', value: profile.email }}` while to make it work with mongoose, it needs to be `where: { email: profile.email }`.

This is obviously a pretty big problem.

What's more, the syntax for the `findOne` function of both bookshelf and mongoose just look at the `params` passed in.  There are large inconsistencies here in how query parameters are handled and that is probably what should be changed.

**Comment by derrickmehaffy** [comment] 2018-07-09 14:43
@daqst Very nice explanation. I'm going to test this myself shortly to confirm your findings. @lauriejim might be worth taking a second look? I've seen a lot of issues relating to the providers plugin.

**Comment by lauriejim** [comment] 2018-07-19 16:38
Hello guys ! 

@bahdcoder and @daqst I think it's related to this comment https://github.com/strapi/strapi/pull/1485#issuecomment-405296037

If you confirm, please can you open a PR to share your fix with the community. Will appreciate your help on this point.

**Comment by bahdcoder** [comment] 2018-07-19 17:33
@lauriejim i will raise a PR asap to fix this.

**Closed** 2018-07-23 07:47 UTC
Labels: priority: medium, status: confirmed, type: bug 🐛
