### ISSUE TITLE
Duplicating entry with i18n enabled when not in the default locale created an inconsistent state

### ISSUE THREAD

**Issue by ls-ramos** [strapi/strapi#19798] opened 2024-03-15 17:13 UTC
### Required System information

- Node.js version: 20.11.0
- NPM version: 10.2.4
- YARN version: 1.22.21
- Strapi version: 4.20.5
- Database: SQLite
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: TS

### Describe the bug

Duplicating an entry that has a locale that is not the default locale, creates an entry on the default locale, but it displays the incorrect locale while creating it.

As an example: You have an entry with locale DE on the content type Test, you click the duplicate button, you go to the page of the newly created entry, and you are shown on the frontend the locale DE, even though the entry is actually on locale EN. Switching the locales fixed the inconsistence situation.

This is very confusion for non-technical people that might be handling strapi.

### Steps to reproduce the behavior

Here is a video of the situation:

https://github.com/strapi/strapi/assets/29318376/57cc957c-4f68-402d-b9a2-fc8a3c833194

1. Go to an entry in a locale that is not the default, for example DE.
2. Click on the duplicate button
3. You will see a screen with the data duplicated and the locale shown will be the one you were in, for example DE. But the entry is actually created in the default locale, for example EN.
4. If before you save you go back and forth on the locales, meaning you switch to the default locale (for example EN) and then back to the previous locale (for example DE), then you will be in a consistent state where the locale shown is the actual locale where the duplicated entry was created.

### Expected behavior

I know that strapi does not currently support duplicating an entry that is not in default locale, there is a feature request for this: https://feedback.strapi.io/customization/p/duplicate-item-does-not-copy-translations

But even though this is not supported, it is expected that the fronted displays consistent information. So following the setup of the video with EN as the default locale and DE an additional locale: 
1. When I am in an entry on the DE locale and I click in duplicate
2. I expect to at least end up in a newly created entry that is shown to be in the EN locale right away. 
3.So I can bring the data to DE locale if I wish, and remove it from the EN locale if I don't want it there.

### Additional context

I believe this is related to others i18n issue, for example to the comment I left on this bug: https://github.com/strapi/strapi/issues/18550#issuecomment-2000038037

**Comment by derrickmehaffy** [comment] 2024-03-28 20:59
Not a complete duplicate of https://github.com/strapi/strapi/issues/17498 but most likely caused by the same issue which is lacking the local query parameter

**Closed by derrickmehaffy** 2024-03-28 20:59 UTC
Labels: status: duplicate
