### ISSUE TITLE
Arrow keys don't move the caret inside Text fields when nested inside repeatable component fields

### ISSUE THREAD

**Issue by frances-guest** [strapi/strapi#14770] opened 2022-11-02 22:55 UTC
### Required System information

- Node.js version: 16.17.1
- NPM version: 8.15.0
- Strapi version: 4.4.1
- Database: PostgresQL
- Operating system: Debian GNU/Linux 10

### Describe the bug

Arrow keys do not work in text inputs appearing inside **repeatable** component fields. Pressing arrow keys while focused on a text input _should_ move the caret but in this case it does not. This makes it difficult to enter/edit content as moving the caret (the text cursor) via keyboard is an expected function of all text inputs.

This bug only appears in repeatable component fields. The bug does not appear inside single components fields and dynamic zones.

### Steps to reproduce the behavior

1. Set up the required content types. In the `Content-type Builder` or via code:
    1. Create a new `Component Type` with a single `Text field`.
    2. Create a `Single Type` or `Collection Type`. The `name`, `required`, etc. options can be set to anything
    3. Add a `Component field` with the "Use an existing Component" option
    4. Select the previously created component and set the `Type` of the `Component field` to be `Repeatable Component`
    5. Save your changes
2. Navigate within the `Content Manager` to your newly created content type
3. Within the repeatable component field click the `add a new entry` button
4. Type into the text input
5. Attempt to use the arrow keys within the text input. The caret will not move when the keys are pressed. **This is the bug.** The caret can still be moved with a mouse.

### Expected behavior

Pressing arrow keys while focused on a text input should move the caret in the corresponding direction ie. left arrow key should move the caret one character to the left if it is not already at the start of the input.

### Screenshots

_not applicable_

### Code snippets

_not applicable_

### Additional context

No further context to add

**Comment by derrickmehaffy** [comment] 2022-11-03 19:05
Cannot reproduce in v4.4.6, most likely fixed in https://github.com/strapi/design-system/pull/702

**Closed by derrickmehaffy** 2022-11-03 19:05 UTC
Labels: status: can not reproduce
