### ISSUE TITLE
[enhancement]: Admin Modals close without warning when forms have unsaved data in

### ISSUE THREAD

**Issue by stafyniaksacha** [strapi/strapi#13044] opened 2022-04-01 17:44 UTC
### Describe the bug

When performing a lot of action on the admin, it's often happening that a miss click occurs while fulfilling forms inside modals, thus resetting the form and losing data.

### Expected behavior

I think that modal containing any form can be only explicitly closed (click on cancel button, the `X` button or `esc` key)
Modals that contain only text content (info or confirm modals) can be safely closable by also clicking on the overlay.

**Comment by derrickmehaffy** [comment] 2022-04-18 20:04
Confirmed on v4.1.8, pretty annoying honestly >.<

**Comment by gu-stav** [comment] 2022-06-21 12:00
Hi there. Thanks for raising the issue.

My personal opinion on that is, that we should keep the current behavior, because clicking outside modals/ popovers etc. is something that is expected by users.

However - I do understand your issue and I'm wondering, if we could improve the situation if we e.g. show a confirmation dialog, once you entered some data and then clicked outside the modal, to confirm/ raise awareness that you are loosing your input. This could prevent at least the data loss. Downside could be, that some users might find this behavior annoying, because it includes another step.

Also pinging @maevalienard for her opinion here.

**Comment by AdrianoCahete** [comment] 2022-08-23 15:45
> My personal opinion on that is, that we should keep the current behavior, because clicking outside modals/ popovers etc. is something that is expected by users.
> 
> However - I do understand your issue and I'm wondering, if we could improve the situation if we e.g. show a confirmation dialog, once you entered some data and then clicked outside the modal, to confirm/ raise awareness that you are loosing your input. This could prevent at least the data loss. Downside could be, that some users might find this behavior annoying, because it includes another step.

As primary a UX, it is best for user to may have an annoying behavior IF they blur/change something and want to dispose the entered data, than users who make big/long changes and see their content go away because of a miss click and the UI does not warn/keep the user away from the error.

Comparing the learning curve from users, who will need to understand that the modal is only warning you when you have some change, vs the happiness of the user that you prevented the loss of their data, the answer is pretty straightforward.

Links for people of links :D :
https://www.nngroup.com/articles/user-mistakes/
https://www.nngroup.com/articles/confirmation-dialog/
https://www.nngroup.com/videos/slips-vs-mistakes/

**Comment by codymx** [comment] 2022-09-30 15:27
> News: The problem not only occurs when you click outside modal, it's happen when you click and hold inside modal (cleaning a field, for example), drag on the input to select, but releases the click with mouse positioned **outside** the modal.

Going to second this. It's odd that this is set to happen on the `mouseup` event, and I've lost quite a bit of data due to this behaviour.

While I generally agree that the "default" behaviour of a modal is that it should close when the overlay is clicked, I think there are severities that need to be taken into account. For instance, a simple message modal should be closable by clicking the overlay, but when a user is required to enter a lot of data it makes sense to disable this behaviour and instead use a "Close" or "Cancel" button to avoid annoyances like this. I think this is why a lot of UI libraries have this feature.

Other than that I'm loving Strapi thus far, but after making this mistake many times while trying to create a large backend API I felt this aspect could use improvement from an end-user perspective.

**Comment by joshuaellis** [comment] 2022-10-05 13:44
So there's a PR to fix the issue with the modal dismissing accidentally in cases like this:

> it's happen when you click and hold inside modal (cleaning a field, for example), drag on the input to select, but releases the click with mouse positioned outside the modal.

And regarding the behaviour, we want to look into firing a confirmation alert in these situations to avoid accidental closures.

**Comment by derrickmehaffy** [comment] 2022-10-07 19:04
I'm also not a huge fan of the current behavior, especially when clicking and dragging to select text. If you accidentally move outside the modal when you release the mouse button and it closes is super annoying.

**Comment by joshuaellis** [comment] 2022-10-07 20:07
> I'm also not a huge fan of the current behavior, especially when clicking and dragging to select text. If you accidentally move outside the modal when you release the mouse button and it closes is super annoying.

Hi @derrickmehaffy The PR referenced above will fix this when we've finished it and it's merged into the design system. The issue is the result of incorrect implementation previously.

**Closed** 2023-01-09 13:58 UTC
Labels: issue: enhancement, severity: medium, status: confirmed, source: core:content-type-builder
