### ISSUE TITLE
 error MissingSchemaError: Schema hasn't been registered for model "inventory".

### ISSUE THREAD

**Issue by ningacoding** [strapi/strapi#7485] opened 2020-08-15 20:28 UTC
**Describe the bug**
We have an **Inventory** model, the Strapi Admin Panel lists successfully the collection data (see screenshots), but when adding a custom code into controller using `strapi.services.inventory.find()`, Strapi throwing  error MissingSchemaError: Schema hasn't been registered for model "inventory".

**Steps to reproduce the behavior**
1. create a Model - Content Type "Inventory" for example, from the Strapi panel using version **3.0.0-beta.19.5**
2. follow the migration Guide until version **3.1.1**
3. Access to Strapi panel and list your collection (this should work)
4. Access to collection data in a controller using: `strapi.services.inventory.find({});` (this has the error)

**Expected behavior**
Both, panel and custom controller code, should to access to the strapi->inventory api/database without errors.

**Screenshots**
Strapi panel lists the data successfully
![image](https://user-images.githubusercontent.com/17342546/90320963-25cc4600-df0b-11ea-9342-a198cfd75a0d.png)

Strapi panel shows Content-Type OK
![image](https://user-images.githubusercontent.com/17342546/90320688-e997e600-df08-11ea-9672-652f00db07a8.png)

![image](https://user-images.githubusercontent.com/17342546/90320797-b9047c00-df09-11ea-8a05-3e4afe42265d.png)

Strapi controller throws error
![image](https://user-images.githubusercontent.com/17342546/90320712-2b289100-df09-11ea-826c-60ec767f376f.png)

Current collection schema
![image](https://user-images.githubusercontent.com/17342546/90321103-55c81900-df0c-11ea-830b-306f8566d691.png)

**Code snippets**

**models/inventory.js**
`module.exports = {};`

**models/inventory.settings.json**
``` javascript
{
  "kind": "collectionType", // tried with and without this
  "connection": "default", // tried with and without this
  "collectionName": "inventories", // tried with "inventory" but runtime is not consistent
  "info": {
    "name": "Inventory"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
    "location": {
      "type": "text"
    },
    "user": {
      "plugin": "users-permissions",
      "model": "user"
    },
    "containers": {
      "collection": "container",
      "via": "inventory"
    }
  }
}
```
**controllers/inventory.js**
``` javascript
module.exports = {
  me: async ({state: {user}}) => {
    return await strapi.services.inventory.find({
      user: user.id
    }, 'id name location');
  }
};
```
**config/routes.json**
``` json
{
  "routes": [
    {
      "method": "GET",
      "path": "/inventories/me",
      "handler": "inventory.me",
      "config": {
        "policies": []
      }
    }
  ]
}
```

**System**

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.1
- Database: MongoDB 4.2.8
- Operating system: Linux Ubuntu

**Additional context**
As additional info, this project was migrated from **3.0.0-beta.19.5** to **3.1.1** following every step for MongoDB instructions.

**Comment by lauriejim** [comment] 2020-08-17 13:34
Hello! did you follow each migration guides one by one?

**Comment by ningacoding** [comment] 2020-08-17 14:01
> Hello! did you follow each migration guides one by one?
> Beta.18 to beta.20 then beta.20 to stable and finally 3.0.0 to 3.1.0?

yes

**Comment by derrickmehaffy** [comment] 2020-08-17 17:25
I was unable to reproduce this. I created a beta.18 project, created the model structure, and followed the migration all the way up to v3.1.4 and didn't notice any issues.

**Comment by ningacoding** [comment] 2020-08-18 14:02
> I was unable to reproduce this. I created a beta.18 project, created the model structure, and followed the migration all the way up to v3.1.4 and didn't notice any issues.

the versions on the reproduce steps are different.

**Comment by derrickmehaffy** [comment] 2020-08-18 17:18
@ningacoding even starting a beta.19.5 I wasn't able to reproduce this :thinking:

**Comment by ahmed-ahmed** [comment] 2020-08-31 02:15
I'm seeing the same issue

**Comment by derrickmehaffy** [comment] 2020-08-31 13:21
@ningacoding @ahmed-ahmed we will need more information to be able to reproduce this and help you.

Usually with these types of errors it relates to a broken relation, can either of you provide your project code via something like Github?

**Comment by ningacoding** [comment] 2020-08-31 18:43
@derrickmehaffy which information do you need?, in addition to the provided one.

**Comment by derrickmehaffy** [comment] 2020-10-15 14:30
Closing as user has provided no new information

**Comment by Arcktosh** [comment] 2020-11-05 13:13
I have the same type of problem: MissingSchemaError: Schema hasn't been registered for model "UploadFile"
Replicate problem steps:
Go to Globals
Upload an image for the favicon
Save

Github repo:
https://github.com/Arcktosh/Strapi-Website

**Comment by derrickmehaffy** [comment] 2020-11-18 16:30
> I have the same type of problem: MissingSchemaError: Schema hasn't been registered for model "UploadFile"
> Replicate problem steps:
> Go to Globals
> Upload an image for the favicon
> Save
> 
> Github repo:
> https://github.com/Arcktosh/Strapi-Website

@Arcktosh I pulled your code and updated it to v3.3.3 and hit no issue: 
![image](https://user-images.githubusercontent.com/8593673/99558095-9bb7d180-2980-11eb-8d46-0b522686751f.png)

Going to mark as closed as I can't reproduce this issue locally.

**Closed by derrickmehaffy** 2020-11-18 16:30 UTC
Labels: status: can't reproduce
