### ISSUE TITLE
`created_by` , `updated_by` not set with authenticated POST (post new collection member)

### ISSUE THREAD

**Issue by virgil9306** [strapi/strapi#7635] opened 2020-08-28 09:27 UTC
**Describe the bug**

I created a new collection type called `hierarchy-members`

This endpoint is set to full permissions on authenticated requests only, ELSE no permissions.

I tried an authenticated POST to `hierarchy-members` endpoint (using Postman) and the API endpoint works and the new object is created BUT `created_by` and `updated_by` is null.

I also checked using the `controller`: this information is never available, even before or after `sanitizeEntity`.

**Steps to reproduce the behavior**

1. Create a new Collection Type that only allows authenticated requests
2. POST to it using an authenticated request
3. Response is incorrect: everything is OK **EXCEPT** there is no `created_by` or `updated_by`

**Expected behavior**

Creating the new `hierarchy-member` using admin panel, the `created_by` and `updated_by` fields are populated correctly. So I expected authenticated requests to be recognized by Strapi and populate these fields correctly.

**Screenshots**
n/a

**Code snippets**
n/a

**System**

- Node.js version: 12.18.2
- NPM version: 6.13.1
- Strapi version: 3.1.4
- Database: postgres
- Operating system: OSX

**Additional context**

- There is this old tutorial about how to deal with this issue, this is here from since beta so I don't know if it is still valid because now we have `created_by` and `updated_by`: https://strapi.io/documentation/v3.x/guides/is-owner.html#introduction -- I don't want to do it this way since we already have a field that is meant for this, so now it is redundant But, do you still recommend it?

**Comment by alexandrebodin** [comment] 2020-08-31 13:00
Hello, 

The created_by and updated_by fields are only used inside the admin panel and only refer to administrators (admin model) not authenticated users (user-permissions user model). This is the intended behaviour. If you want to create a relation to the user-permission user model and automate the link you can do so with some customization of course :)

Closing as it is the expected behaviour

**Closed by alexandrebodin** 2020-08-31 13:00 UTC
