### ISSUE TITLE
[V4] Strapi is successfully installed shows errors after running develop command with postgres

### ISSUE THREAD

**Issue by amjadniazi48** [strapi/strapi#11144] opened 2021-09-29 19:07 UTC
### Describe the bug

I installed the strapi V4 successfully but got following error after running develop command 

### Steps to reproduce the behavior

1. Go to 'strapi beta v4 installtion command'
2. After successful installtion run  npm  run develop  and you will see the following behaviour
### Expected Behaviour
It should create and start new strapi app
### Code snippets

`ModuleNotFoundError: Module not found: Error: Can't resolve '......
ode_modules@strapiplugin-email/strapi-admin.js' in 'E:\nodeprojects\newstrapi\.cache\admin\src'
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\Compilation.js:1765:28
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:730:13
    at eval (eval at create (E:\nodeprojects\newstrapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:273:22
    at eval (eval at create (E:\nodeprojects\newstrapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:402:22
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:117:11
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:646:24
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:800:8
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:920:5
    at E:\nodeprojects\newstrapi\node_modules\neo-async\async.js:6883:13
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:903:45
    at finishWithoutResolve (E:\nodeprojects\newstrapi\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at E:\nodeprojects\newstrapi\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at E:\nodeprojects\newstrapi\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (E:\nodeprojects\newstrapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '......
ode_modules@strapiplugin-email/strapi-admin.js' in 'E:\nodeprojects\newstrapi\.cache\admin\src'
  Parsed request is a module
  using description file: E:\nodeprojects\newstrapi\.cache\package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      E:\nodeprojects\newstrapi\.cache\admin\src\node_modules doesn't exist or is not a directory
      E:\nodeprojects\newstrapi\.cache\admin\node_modules doesn't exist or is not a directory
      E:\nodeprojects\newstrapi\.cache\node_modules doesn't exist or is not a directory
      looking for modules in E:\nodeprojects\newstrapi\node_modules
        E:\nodeprojects\newstrapi\node_modules\......
ode_modules@strapiplugin-email doesn't exist
      E:\nodeprojects\node_modules doesn't exist or is not a directory
      E:\node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve '......
ode_modules@strapiplugin-email/strapi-admin.js' in 'E:\nodeprojects\newstrapi\.cache\admin\src'
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\Compilation.js:1765:28
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:730:13
    at eval (eval at create (E:\nodeprojects\newstrapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:273:22
    at eval (eval at create (E:\nodeprojects\newstrapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:402:22
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:117:11
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:646:24
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:800:8
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:920:5
    at E:\nodeprojects\newstrapi\node_modules\neo-async\async.js:6883:13
    at E:\nodeprojects\newstrapi\node_modules\webpack\lib\NormalModuleFactory.js:903:45
    at finishWithoutResolve (E:\nodeprojects\newstrapi\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at E:\nodeprojects\newstrapi\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at E:\nodeprojects\newstrapi\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (E:\nodeprojects\newstrapi\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '......
ode_modules@strapiplugin-email/strapi-admin.js' in 'E:\nodeprojects\newstrapi\.cache\admin\src'
  Parsed request is a module
  using description file: E:\nodeprojects\newstrapi\.cache\package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      E:\nodeprojects\newstrapi\.cache\admin\src\node_modules doesn't exist or is not a directory
      E:\nodeprojects\newstrapi\.cache\admin\node_modules doesn't exist or is not a directory
      E:\nodeprojects\newstrapi\.cache\node_modules doesn't exist or is not a directory
      looking for modules in E:\nodeprojects\newstrapi\node_modules
        E:\nodeprojects\newstrapi\node_modules\......
ode_modules@strapiplugin-email doesn't exist
      E:\nodeprojects\node_modules doesn't exist or is not a directory
      E:\node_modules doesn't exist or is not a directory`

### System

- Node.js version:  4.18.0
- NPM version: 7.5.2
- Strapi version:  v4
- Database: postgres
- Operating system: windows 10

**Comment by MattieBelt** [comment] 2021-09-29 19:35
Duplicate of #11137

**Closed by MattieBelt** 2021-09-29 19:35 UTC
