### ISSUE TITLE
Relationship issues migrating mySQL project from alpha to beta

### ISSUE THREAD

**Issue by TheRealBarenziah** [strapi/strapi#4325] opened 2019-10-22 16:00 UTC
I am in the process of migrating a mySQL project from alpha to beta. I followed the migration guide and it solved most of my issues but not all of them. Afaik those come from the ORM and the way relations are established.
I have two separate problems that I'll gather to avoid spamming. **If you prefer that I post two separate issues please tell me & I will edit**. But as they both concern the migration process & mySQL, it seemed ok to pack them.

In both cases, things worked fine on alpha version (theproject was initialized in April 2019)

# 1/ `Error: ER_FT_MATCHING_KEY_NOT_FOUND: Can't find FULLTEXT index matching the column list`

**Describe the bug**
I have two contents created with the plugin, Action and Contentaction (see models below). Before, I could first create an action, then I could go create a Contentaction and select the action I just created in the "Action" dropdown. Now, when I create the action, it is properly added in the database (I use mySQL Workbench to visualize), but it's not available in my Contentaction dropdown (yet the actions that existed prior to the migration are available - this behavior feels like a big clue, but I still failed to resolve it). 
There is another clue: every time I type a character in the dropdown "search bar", the UI makes a request to the server that returns 500 (sample output below)
```
[2019-10-22T09:31:17.703Z] debug GET /content-manager/explorer/action?_limit=20&_start=0&source=content-manager&_q=aaa (43 ms) 500
[2019-10-22T09:31:17.748Z] error Error: ER_FT_MATCHING_KEY_NOT_FOUND: Can't find FULLTEXT index matching the column list
```

**Steps to reproduce the behavior**
1. Get [my repo](https://github.com/TheRealBarenziah/strapi-demo)
2. Create new SQL database and link it through ./config/environment/development/database.json (sorry I can't share the OC)
3. First create a new Action
4. Then create a new Contentaction
5. The action is in your database but it's not appearing in the Action dropdown of the "new Contentaction" interface; also you get an error 500 `ER_FT_MATCHING_KEY_NOT_FOUND: Can't find FULLTEXT index matching the column list` for each stroke in the search bar.

**Expected behavior**
It should work like it used to, considering I followed the migration guide and it's supposed to be using the same model/controller etc.

**Code snippets**
Action model:
```
{
  "connection": "default",
  "collectionName": "actions",
  "info": {
    "name": "action",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "Name": {
      "default": "",
      "type": "string"
    },
    "function": {
      "default": "",
      "type": "string"
    }
  }
}
```
Contentaction model:
```
{
  "connection": "default",
  "collectionName": "contentactions",
  "info": {
    "name": "contentaction",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "Type": {
      "default": "",
      "type": "enumeration",
      "enum": [
        "None",
        "ContentButton",
        "ContentVideo",
        "ContentThumbnail",
        "ContentScene",
        "ContentHotspot",
        "ContentEmpty",
        "ContentMenuCurved",
        "ContentOnBoarding",
        "ContentText",
        "ContentAudio",
        "ContentStartButton",
        "ContentLookAround",
        "ContentStJoGame",
        "ContentHotspotMouvant",
        "ContentPhotoCatch",
        "ContentTuto",
        "ContentBlend"
      ]
    },
    "ContentID": {
      "default": "",
      "type": "integer"
    },
    "action": {
      "model": "action"
    },
    "Name": {
      "default": "",
      "type": "string"
    },
    "contentbutton_activate": {
      "model": "contentbutton",
      "via": "onActivate"
    },
    "contentbutton_deactivate": {
      "model": "contentbutton",
      "via": "onDeactivate"
    },
    "contentvideo_OnActivate": {
      "model": "contentvideo",
      "via": "OnActivate"
    },
    "contentvideo_OnDeactivate": {
      "model": "contentvideo",
      "via": "OnDeactivate"
    },
    "contentvideo": {
      "model": "contentvideo",
      "via": "OnVideoEnd"
    },
    "contentscene": {
      "model": "contentscene",
      "via": "OnSceneLoad"
    },
    "contentthumbnail_gazeenter": {
      "model": "contentthumbnail",
      "via": "OnGazeEnter"
    },
    "contentthumbnail_gazeexit": {
      "model": "contentthumbnail",
      "via": "OnGazeExit"
    },
    "contentbutton_onFilled": {
      "model": "contentbutton",
      "via": "onFilled"
    },
    "contentscene_VideoEnd": {
      "model": "contentscene",
      "via": "OnVideoEnd"
    },
    "contentonboarding_ondeactivate": {
      "model": "contentonboarding",
      "via": "OnDeactivate"
    },
    "contentaudio_onaudioend": {
      "model": "contentaudio",
      "via": "OnAudioEnd"
    },
    "contentonboarding_onactivate": {
      "model": "contentonboarding",
      "via": "OnActivate"
    },
    "contentstartbutton_onfilled": {
      "model": "contentstartbutton",
      "via": "onFilled"
    },
    "contentstjogame_ongameend": {
      "model": "contentstjogame",
      "via": "onGameEnd"
    },
    "contenttuto_ontutoend": {
      "model": "contenttuto",
      "via": "OnTutoEnd"
    },
    "contentscene_ondeactivate": {
      "model": "contentscene",
      "via": "OnDeactivate"
    },
    "contentphotocatch_ondeactivate": {
      "model": "contentphotocatch",
      "via": "OnDeactivate"
    },
    "contentblend_oncontinue": {
      "model": "contentblend",
      "via": "onContinue"
    }
  }
}
```
Action "controller" (same as Contentaction):
```
'use strict';

/**
 * Action.js controller
 *
 * @description: A set of functions called "actions" for managing `Action`.
 */

module.exports = {};

```
**System**
- Node.js version: 10.0.0
- NPM version: 5.6.0
- Yarn version: 1.19.1
- Strapi version: 3.0.0-beta.17.2
- Database: mySQL
- Operating system: Linux Mint (local), RedHat Enterprise Linux (AWS)

**Additional context**
When googling this problem, it appears that the error message is related to mySQL, and the mainstream fix is some SQL `ALTER TABLE `foo` ADD FULLTEXT ...`, but handcrafting SQL feels wrong when the ORM should work.
I also ran into [this interesting Strapi issue](https://github.com/strapi/strapi/issues/1382), interesting because it learned me a couple relevant things but afaik it's status is "Fixed by #2049". So either it is not fixed, or I missed something on my end (which I believe).

A more experienced developer suggested me it looked like the node_modules/strapi-hook-bookshelf/lib/buildDatabaseSchema.js did not ran when it was expected. He suggested me to run SQL commands to create FULLTEXT index for each field of each table to fix this. I will do that and keep you informed of my progresses.

_____

# 2/ Polymorphism w/ Upload plugin, or `TypeError: Cannot destructure property `refId` of 'undefined' or 'null'.`

**Describe the bug**
When I try to upload a file through the GUI, it returns an error 500 and the message `TypeError: Cannot destructure property `refId` of 'undefined' or 'null'.` Same behavior if the request is made with Postman or C#.

**Steps to reproduce the behavior**
1. Get [my repo](https://github.com/TheRealBarenziah/strapi-demo) (note the custom Upload controller & File model, I did this following the migration guide but there's a fair chance the problem lies here)
2. Create new SQL database and link it through ./config/environment/development/database.json (sorry I can't share the OC)
3. Try to upload a file in GUI (through Upload tab, so with no relation)
4. Watch it fail because cannot destructure property refId of null (he's expecting a relation, I kinda get that)
5 Upload a file through another tab (f.e create a new Contentphotocatches, it takes a media file in the PositionInfo field)
6. Watch the POST and the upload succeed (you have the file in your database, and the link is made with the "related" field (cf snippet below). However the link is not made through the `upload_file_morph` table).

**Expected behavior**
Either polymorphism by default for Uploads have been dropped and I should have no error asking me for `ref` `refId` etc. Or it's not dropped, and the plugin should increment `upload_file_morph` table like it used to.

**Code snippets**
Upload controller: 
```
'use strict';

/**
 * Upload.js controller
 *
 * @description: A set of functions called "actions" of the `upload` plugin.
 */

const _ = require('lodash');

module.exports = {
  upload: async (ctx) => {
    // Retrieve provider configuration.
    const config = await strapi.store({
      environment: strapi.config.environment,
      type: 'plugin',
      name: 'upload'
    }).get({ key: 'provider' });

    // Verify if the file upload is enable.
    if (config.enabled === false) {
      return ctx.badRequest(null, ctx.request.admin ? [{ messages: [{ id: 'Upload.status.disabled' }] }] : 'File upload is disabled');
    }

    // Extract optional relational data.
    const { refId, ref, source, field, path } = ctx.request.body.fields;
    const { files = {} } = ctx.request.body.files;

    if (_.isEmpty(files)) {
      return ctx.badRequest(null, ctx.request.admin ? [{ messages: [{ id: 'Upload.status.empty' }] }] : 'Files are empty');
    }

    // Transform stream files to buffer
    const buffers = await strapi.plugins.upload.services.upload.bufferize(ctx.request.body.files.files);
    const enhancedFiles = buffers.map(file => {
      if (file.size > config.sizeLimit) {
        return ctx.badRequest(null, ctx.request.admin ? [{ messages: [{ id: 'Upload.status.sizeLimit', values: {file: file.name} }] }] : `${file.name} file is bigger than limit size!`);
      }

      // Add details to the file to be able to create the relationships.
      if (refId && ref && field) {
        Object.assign(file, {
          related: [{
            refId,
            ref,
            source,
            field
          }]
        });
      }

      // Update uploading folder path for the file.
      if (path) {
        Object.assign(file, {
          path
        });
      }

      return file;
    });

    // Something is wrong (size limit)...
    if (ctx.status === 400) {
      return;
    }

    const uploadedFiles = await strapi.plugins.upload.services.upload.upload(enhancedFiles, config);

    // Send 200 `ok`
    ctx.send(uploadedFiles.map((file) => {
      // If is local server upload, add backend host as prefix
      if (file.url && file.url[0] === '/') {
        file.url = strapi.config.url + file.url;
      }

      if (_.isArray(file.related)) {
        file.related = file.related.map(obj => obj.ref || obj);
      }

      return file;
    }));
  },

  getEnvironments: async (ctx) => {
    const environments =  _.map(_.keys(strapi.config.environments), environment => {
      return {
        name: environment,
        active: (strapi.config.environment === environment)
      };
    });

    ctx.send({ environments });
  },

  getSettings: async (ctx) => {
    const config = await strapi.store({
      environment: ctx.params.environment,
      type: 'plugin',
      name: 'upload'
    }).get({key: 'provider'});

    ctx.send({
      providers: strapi.plugins.upload.config.providers,
      config
    });
  },

  updateSettings: async (ctx) => {
    await strapi.store({
      environment: ctx.params.environment,
      type: 'plugin',
      name: 'upload'
    }).set({key: 'provider', value: ctx.request.body});

    ctx.send({ok: true});
  },

  find: async (ctx) => {
    const data = await strapi.plugins['upload'].services.upload.fetchAll(ctx.query);

    // Send 200 `ok`
    ctx.send(data
      // .map((file) => {
      // // if is local server upload, add backend host as prefix
      //   if (file.url[0] === '/') {
      //     file.url = strapi.config.url + file.url;
      //   }

      //   return file;
      // })
    );
  },

  findOne: async (ctx) => {
    const data = await strapi.plugins['upload'].services.upload.fetch(ctx.params);

    data.url = strapi.config.url + data.url;

    // Send 200 `ok`
    ctx.send(data);
  },

  count: async (ctx) => {
    const data = await strapi.plugins['upload'].services.upload.count(ctx.query);

    // Send 200 `ok`
    ctx.send({
      count: data
    });
  },

  destroy: async (ctx) => {
    const config = await strapi.store({
      environment: strapi.config.environment,
      type: 'plugin',
      name: 'upload'
    }).get({key: 'provider'});

    const data = await strapi.plugins['upload'].services.upload.remove(ctx.params, config);

    // Send 200 `ok`
    ctx.send(data);
  },

  search: async (ctx) => {
    const data = await strapi.query('file', 'upload').search(ctx.params);

    ctx.send(data);
  },
};

```
File model (File.settings.json)
```
{
  "connection": "default",
  "info": {
    "name": "file",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string",
      "configurable": false,
      "required": true
    },
    "hash": {
      "type": "string",
      "configurable": false,
      "required": true
    },
    "sha256": {
      "type": "string",
      "configurable": false
    },
    "ext": {
      "type": "string",
      "configurable": false
    },
    "mime": {
      "type": "string",
      "configurable": false,
      "required": true
    },
    "size": {
      "type": "string",
      "configurable": false,
      "required": true
    },
    "url": {
      "type": "string",
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false,
      "required": true
    },
    "public_id": {
      "type": "string",
      "configurable": false
    },
    "related": {
      "collection": "*",
      "filter": "field",
      "configurable": false
    }
  }
}
```
**System**
Same as above.

**Additional context**
I'm novice with mySQL; didn't even knew the polymorphism before running into it. Now I'm a bit more documented, as far as I understand it's a sort of join table but more flexible (having not only a pair of FKs but also other fields like `related_type` and `field` to allow FK reference of many different tables). I still know very little thing about it, only that it used to work and now it doesn't.
I giggled when I stumbled upon this quote in an issue below: "If you need to use the polymorphic associations is that you're a confirmed developer and you can easily edit the models manually."
Because I'm definitely a novice developer, but had to learn about polymorphic associations in order to solve this problem. 

The clue I have for this problem is, some people mentioned strange behavior when polymorphism was used in conjunction with  `"model": "*"` or `"collection": "*"` (link 2 / issue 750), and I have this related.collection field. Another clue is simply the differences in the way Upload plugin manages the relations between alpha & beta.

Again, I will update as soon as I make progress

[Somewhat related issue 1](https://github.com/strapi/strapi/issues/788)
[Somewhat related issue 2](https://github.com/strapi/strapi/issues/750)
[Somewhat related issue 3](https://github.com/strapi/strapi/issues/3173)
[Somewhat related gitlab](https://www.gitmemory.com/issue/strapi/strapi/3173/511174968)

**Comment by lauriejim** [comment] 2019-10-25 06:33
Hello @TheRealBarenziah !

About your first issue, I haven't be able to reproduce. I cloned your repo and it works.
Maybe I missed something.

*Here is what I did:*
https://www.loom.com/share/9c38611c37c14d70a2b89e97eee15312

And for the second issue, It's due to your `extension`.
The controller code of the **Upload** plugin changed. You are using the alpha one I suppose.
So by deleting it, it will work. If you did some customization, I suggest you to re-apply it based on the new controller code.

*Here is what I did:*
https://www.loom.com/share/dbfc6f81b66741339221434f1118c355

**Comment by TheRealBarenziah** [comment] 2019-10-25 14:01
Hello lauriejim. Thanks for taking the time to go through this, it's much appreciated !

## About issue 1
I've been able to fix the `Code 500; ER_FT_MATCHING_KEY_NOT_FOUND: Can't find FULLTEXT index matching the column list` simply by [applying this advice](https://stackoverflow.com/a/21551787/11894221) (`ALTER TABLE x ADD FULLTEXT INDEX y (z)`) for each column of actions, upload_file & upload_file_morph tables. I didn't expect the fix to be that simple. Still don't know what caused this in the first place, but it looks like at one point `node_modules/strapi-hook-bookshelf/lib/buildDatabaseSchema.js` should have run and did not.

About the action not appearing in dropdown tho, thank you for making me look deeper. 
There's a difference in our environment as I have more than 20 action objects in my database (I've got ~50). The value of "20" is significant because of the dropdown button behavior (you may know it already but I've just found out thanks to devtools/Network tab): when you first click it, it'll fetch the first 20 items of said model (for me, the query looks like `/content-manager/explorer/action?_limit=20&_start=0&source=content-manager`). Then when you scroll down and approach the end of the list, it will do another fetch.
The second fetch seems to be where the problem lies: on my old server, it hits `/content-manager/explorer/action/?_limit=20&_start=20&source=content-manager`; I can see the logic here, it went through the 20 first entries so now it'll fetch the 20 next ones. If I scroll down again, it will fetch again with `_start=40` and so on.
But on the new server (beta version), the dropdown fetch n°2 is hitting `http://15.188.66.181:1337/content-manager/explorer/action?_limit=20&_start=1&source=content-manager` as if I had only 21 actions ! (in fact I have 49 of them + the one I create to test)

Further testing with Postman confirmed that the action was properly created (I can see it as the last entry on the `content-manager/explorer/action` endpoint), and that I could indeed create the relation properly (f.e. POST on `/contentactions`, body : { Type : ContentScene , ContentID : 3 , action : 75 }, 75 being the id of the action I created prior)

Do you know what could cause this? Because I have this exact behavior on several other "relationship dropdowns"). It seems like the "start=x" param in the dropdown fetch is not incrementing as it should. Also it seems the problem is limited to the front, as I can establish relations properly using Postman. 



## About issue 2
On my end I fixed it "by accident" by removing irrelevant & obsolete entries from my upload_file_morph table; when knex complained about refId of this or that, I just deleted those entries. Then it complained again about another one; I made this a few times and after a deletion it suddenly worked fine.

As I'm not the one who initialized this project, seems that I've wrongly assumed that my Upload plugin had been customized during alpha; so I "migrated" it in ./extension as advised by the Migration guide. But if it wasn't customized afterall, I kinda see how it could create problems. Thanks for having looked into it.

**Comment by lauriejim** [comment] 2019-10-27 13:12
Okay, thank you for these details.
I will close this big issue.

Can you please open a new one that only explains your issue with the dropdown entries load.
Thankk you for your time

**Closed by lauriejim** 2019-10-27 13:12 UTC
Labels: type: help wanted 🤷‍♂️
