### ISSUE TITLE
413 (Request Entity Too Large) 

### ISSUE THREAD

**Issue by ddy-ddy** [strapi/strapi#13743] opened 2022-07-11 16:07 UTC
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.11.0
- Strapi version: v4.1.12
- Database: sqlite3
- Operating system: Linux 5.4 Ubuntu 20.04.4 LTS

### Describe the bug

1. When i upload an image which the sizes is bigger than 1MB. I get an error called `413 (Request Entity Too Large) `. 
2. I found a solution in strapi v4 doc [strapi doc](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/middlewares.html#internal-middlewares-configuration-reference). I followed the guide to edit the `./config/middlewares.js` file. so the edited file is:
```shell
module.exports = [
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  // 'strapi::body',
  {
    name: "strapi::body",
    config: {
      formLimit: "256mb", // modify form body
      jsonLimit: "256mb", // modify JSON body
      textLimit: "256mb", // modify text body
      formidable: {
        maxFileSize: 200 * 1024 * 1024, // multipart data, modify here limit of uploaded file size
      },
    },
  },
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
``` 
3. I restart the strapi. but unfortunately, I got a error called `413 (Request Entity Too Large)` again when I upload a big size image.

### Expected behavior

I want to upload a big size image by strapi.

### Screenshots
![](https://tva1.sinaimg.cn/large/e6c9d24egy1h43folwr1vj21qj0u0agb.jpg)

**Comment by derrickmehaffy** [comment] 2022-07-13 20:16
You also need to adjust the max file size of the upload plugin too: https://docs.strapi.io/developer-docs/latest/plugins/upload.html#max-file-size

Marking as closed as it's not a bug.

**Closed by derrickmehaffy** 2022-07-13 20:16 UTC

**Comment by ddy-ddy** [comment] 2022-07-14 00:43
> You also need to adjust the max file size of the upload plugin too: https://docs.strapi.io/developer-docs/latest/plugins/upload.html#max-file-size
> 
> 
> 
> Marking as closed as it's not a bug.

Yeah, I follow the guide. But it does not function.

**Comment by derrickmehaffy** [comment] 2022-07-14 13:49
You only edited the middleware, you need to modify the plugin config too

**Comment by ddy-ddy** [comment] 2022-07-14 15:13
> You only edited the middleware, you need to modify the plugin config too

Thank you so much. I followed the suggestions you gave to me. Unfortunately, it still doesn't work. But I found the reason. There is an upload size limitation of Nginx. So it works when I edit the params `client_max_body_size` in the config file of Nginx
![](https://tva1.sinaimg.cn/large/e6c9d24egy1h46v18k83nj20sa0l2jua.jpg)

**Comment by ddy-ddy** [comment] 2022-07-14 17:56
> Ahhh yeah sorry I was gonna mention that one next, we should probably include that info in the docs. I'll make a pull request

Great 👍

**Comment by derrickmehaffy** [comment] 2022-07-14 18:20
If anyone stumbles upon this issue in the future, see: https://github.com/strapi/documentation/pull/998
