### ISSUE TITLE
Set SHOW_TUTORIALS to false causes FE error

### ISSUE THREAD

**Issue by kuka-radovan** [strapi/strapi#8558] opened 2020-11-03 09:25 UTC
### Describe the bug

Set `SHOW_TUTORIALS` option to `false` inside `./admin/src/config.js` causes FE error and inability to render admin UI.

### Steps to reproduce the behavior

1. Create `./admin/src/config.js` file
2. Add `export const SHOW_TUTORIALS = false;`
3. Rebuild strapi
4. Browse `http://localhost:1337/admin/`

### Expected behavior

As described in [documentation](https://strapi.io/documentation/v3.x/admin-panel/customization.html#development-mode), it should disable the information box containing the tutorial videos.

### Screenshots

![image](https://user-images.githubusercontent.com/5869729/97968184-95412b80-1dbe-11eb-974a-c3f000a1b3ab.png)

### System

- Node.js version: `v14.11.0`
- NPM version: `6.14.8`
- Strapi version:`3.2.5`
- Database: `SQLite`
- Operating system: `Mac OS (10.15.7)`

**Comment by derrickmehaffy** [comment] 2020-11-03 13:28
Unable to reproduce on v3.2.5 using the following override:

**Path:** `./admin/src/config.js`
```js
export const LOGIN_LOGO = null;
export const SHOW_TUTORIALS = false;
export const SETTINGS_BASE_URL = '/settings';
```

Can you please test with the example I used here and rebuild your admin.

**Comment by schafer14** [comment] 2020-11-04 23:14
It looks to me as if you have `SHOW_TUTORIALS` set without setting `SETTINGS_BASE_URL` the admin page will not render. Does this help reproduce the issue for you @derrickmehaffy ?

**Comment by derrickmehaffy** [comment] 2020-11-04 23:30
> It looks to me as if you have `SHOW_TUTORIALS` set without setting `SETTINGS_BASE_URL` the admin page will not render. Does this help reproduce the issue for you @derrickmehaffy ?

When setting this override you need all of the options or it will break yes.

**Comment by kuka-radovan** [comment] 2020-11-05 09:19
@derrickmehaffy I am sorry but it does not make sense to me. If I want to change one config value, I have to override all settings? I think, this is complicating migration to newer version in case it will introduce new configuration option. And it brings fragility in this way.

**Comment by derrickmehaffy** [comment] 2020-11-05 13:54
> @derrickmehaffy I am sorry but it does not make sense to me. If I want to change one config value, I have to override all settings? I think, this is complicating migration to newer version in case it will introduce new configuration option. And it brings fragility in this way.

I didn't design the system myself so I can't speak to it being the better or worse option, I'm only informing how it currently works and is the intended requirement on the current versions.

**Comment by kuka-radovan** [comment] 2020-11-10 08:18
This is exactly what I was talking about. https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.2.5-to-3.3.0.html#migration

**Comment by derrickmehaffy** [comment] 2020-11-10 14:54
@soupette do you want to weight in here as to the reason for needing all the values to modify only one of them?

**Comment by kuka-radovan** [comment] 2020-11-10 18:49
If it would be considered as a acceptable feature request I could send a PR with this feature...

**Comment by derrickmehaffy** [comment] 2020-11-10 20:39
> If it would be considered as a acceptable feature request I could send a PR.

I wouldn't see why not @kuka-radovan if it helps makes everyone's life easier I think that would be considered acceptable. I think the reason it was built the way it was, it just didn't seem important to split them.

Please do feel free :smiley:

**Comment by soupette** [comment] 2021-11-30 09:06
Is this issue still happening?

**Comment by derrickmehaffy** [comment] 2021-12-02 21:24
Doubtful on v4, marking as closed since we couldn't reproduce it on v3

**Closed by derrickmehaffy** 2021-12-02 21:24 UTC
Labels: type: enhancement, severity: low, source: admin
