### ISSUE TITLE
GraphQL filter parameters on nested query does not work

### ISSUE THREAD

**Issue by laportem** [strapi/strapi#5608] opened 2020-03-26 10:45 UTC
**Describe the bug**
According to the documentations, filters on nested queries should be possible with graphql.
But none of the filter parameters, “**limit**”, “**start**”, “**sort**” and “**where**” seems to work.

For example,
```
query {
	stocks {
		id
		name
		sku,
		quantity
		images (limit: 3) {
			id
			url
		}
	}
}
```

**Expected behavior**
I would have expected only 3 images per stock to be returned but instead it is returning all images (7 of them to be exact)

**System**
- Node.js version: v10.15.3
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.19.3
- Database: PostgreSQL v11.3
- Operating system: Ubuntu 1404 (via vagrant vbox)

**Comment by derrickmehaffy** [comment] 2020-03-26 11:14
@alexandrebodin correct me if I'm wrong but query params shouldn't work on nested relational data right? (Especially on polymorphic like upload until the media lib is added, was fairly certain the upload plugin didn't support filtering in general)

**Comment by laportem** [comment] 2020-03-26 11:46
Shouldn't work with Strapi-Graphql or Graphql in general?

I have not tested others but i know nested query params work perfectly on hasura

**Comment by alexandrebodin** [comment] 2020-03-26 13:08
There clearly is an issue here. the params are ignored. I'm putting this issue as confirmed

**Comment by hashinteractive** [comment] 2020-07-22 19:06
Has there been any updates to this? The `limit`, `sort` and filter `where` query params do not work as well.

**Comment by Philine** [comment] 2020-08-04 16:56
I ran into a similar issue.
From what I've experienced, the query params work if the filtered field is another collection with a relation to the 1st one, but not if it's a field with multiple entries defined on the 1st queried content type. I hope it helps to solve the issue or as a workaround for others in the meantime

**Comment by alexandrebodin** [comment] 2020-08-04 21:41
Hi @Philine thanks for the details, would you mind sharing example model settings json files so we can reproduce more easily ?

**Comment by Philine** [comment] 2020-08-05 08:32
I created a basic "Example" type
```
{
  "kind": "singleType",
  "collectionName": "examples",
  "info": {
    "name": "example"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string"
    },
    "multiple_media_field": {
      "collection": "file",
      "via": "related",
      "allowedTypes": [
        "images",
        "files",
        "videos"
      ],
      "plugin": "upload",
      "required": false
    },
    "media_collection_types": {
      "collection": "media-collection-type"
    }
  }
}
```
And so this query:
```
query Example {
  example {
    id
    multiple_media_field (limit: 1) {
      id
    }
    media_collection_types (limit: 1) {
      id
    }
  }  
}
```

Will return something like
```
{
  "data": {
    "example": {
      "id": "1",
      "multiple_media_field": [
        {
          "id": "21"
        },
        {
          "id": "20"
        },
        {
          "id": "22"
        }
      ],
      "media_collection_types": [
        {
          "id": "1"
        }
      ]
    }
  }
}
```

**Comment by machiaveli88** [comment] 2020-10-03 22:14
The bug came with version 3.1.6! In version 3.1.5 everything still worked as it should!

**Comment by GermainPereira** [comment] 2020-10-16 17:24
I'm having the a similar issue here querying Strapi v. 3.2.0 through React.js/Gatsby.
Any updates on this? Thank you!

**Comment by hackonhari** [comment] 2020-12-01 10:19
For this issue, I am using nested arguments at the root query argument
like 

```
posts(where:{topics:{slug_containss:"wordpress"}},limit:3,sort:"date:desc"){
slug
title
topics{
id
slug
}
}
```

it's working and my post & topics have a relation between them.

**Comment by blefevre** [comment] 2020-12-29 14:48
This was caused by https://github.com/strapi/strapi/pull/7959, reverting that change fixes the issue.

As a workaround you can overwrite that change via extensions:
Copy https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/type-definitions.js
and place it in `extensions/graphql/services/type-definitions.js`, then edit line 185 to remove `case 'manyWay':`

**Comment by blefevre** [comment] 2020-12-29 18:51
I was able to do some more investigation and have opened a PR with a possible solution.
Copy the files from [here](https://github.com/blefevre/strapi/tree/fix-graphql-nested-query/packages/strapi-plugin-graphql) instead for (hopefully) a better solution while we wait for the PR.

**Comment by alexandrebodin** [comment] 2020-12-30 14:13
Hi @blefevre There is a refactor in progress on this part of the code here https://github.com/strapi/strapi/pull/9020 Would you mind checking if it fixes your issues ?

**Comment by jacargentina** [comment] 2020-12-31 15:59
@alexandrebodin  as I'm interested too in a solution for this bug; I've tested #9020 (simply copied all your PR files from strap-plugin-graphql over my own project node_modules/strapi-plugin-graphql.

Dont seem to fix the nested query.

**Comment by alexandrebodin** [comment] 2020-12-31 16:18
Hi @jacargentina, could you please share the structure (models) you are using so we can reproduce ? just to confirm you are using mongo right ?

**Comment by jacargentina** [comment] 2020-12-31 16:23
Yes, is mongo

```api/product/models/Product.settings.json```

```json
{
  "connection": "default",
  "collectionName": "product",
  "info": {
    "name": "product",
    "description": "Describe un producto"
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
    "shortname": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "slogan": {
      "type": "text",
      "required": true
    },
    "description": {
      "type": "text",
      "required": true
    },
    "slug": {
      "type": "string",
      "unique": true,
      "required": true
    },
    "icon": {
      "model": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    },
    "color": {
      "type": "string"
    },
    "faq": {
      "type": "text"
    },
    "twitterHashtag": {
      "type": "string"
    },
    "twitterWidgetId": {
      "type": "string"
    },
    "discontinued": {
      "type": "boolean",
      "required": true
    },
    "quotes": {
      "collection": "quote",
      "via": "product"
    },
    "releases": {
      "collection": "release",
      "via": "product"
    },
    "features": {
      "collection": "feature",
      "via": "product"
    },
    "book": {
      "model": "book"
    }
  }
}
```

```api/release/models/Release.settings.json```

```json
{
  "connection": "default",
  "collectionName": "release",
  "info": {
    "name": "release",
    "description": "El lanzamiento de un producto, con detalle de los cambios y archivos instaladores"
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
    "published": {
      "type": "boolean",
      "required": true
    },
    "slug": {
      "type": "string",
      "required": true
    },
    "version": {
      "type": "string",
      "required": true
    },
    "sortableVersion": {
      "type": "string",
      "configurable": false
    },
    "changelog": {
      "type": "text"
    },
    "product": {
      "model": "product",
      "via": "releases"
    },
    "files": {
      "collection": "file",
      "via": "related",
      "plugin": "upload",
      "required": false
    }
  }
}
```

**Comment by alexandrebodin** [comment] 2020-12-31 16:54
I can't seem to reproduce @jacargentina, do you have any specific code in the controller or service for the `release.find` action ?

**Comment by jacargentina** [comment] 2020-12-31 17:31
Not at all. I'm interested on trying to help fixing this. I'll try to use your PR against my db to debug somehow.

**Comment by jacargentina** [comment] 2020-12-31 18:37
Integration with your PR done, now i''
ve tried some queries, and found that when using "sort", it screws all.

That works.
<img width="1362" alt="Captura de Pantalla 2020-12-31 a la(s) 15 29 05" src="https://user-images.githubusercontent.com/517228/103421978-f21e4f80-4b7d-11eb-8558-c716c8f2a307.png">


But this is not.

<img width="1182" alt="Captura de Pantalla 2020-12-31 a la(s) 15 28 34" src="https://user-images.githubusercontent.com/517228/103421997-0cf0c400-4b7e-11eb-8ed5-a0d9a70b4653.png">

**Comment by alexandrebodin** [comment] 2021-01-04 08:31
Hey, I still can't reproduce with the sorting. Let's move to DM on slack. Can you send me a test db dump ?

**Comment by jacargentina** [comment] 2021-01-04 16:02
@alexandrebodin I've tested the updated PR with my data; the nulls are fixed, but the query results still are wrong.

"Give me all releases from newest to oldest" (createdAt: desc)

<img width="1247" alt="Captura de Pantalla 2021-01-04 a la(s) 12 58 55" src="https://user-images.githubusercontent.com/517228/103553836-c4dae580-4e8c-11eb-999e-c741519307dd.png">

It says **_newest_** 2020-01-27

"Give me only the latest release" (createdAt: desc limit:1)

<img width="1294" alt="Captura de Pantalla 2021-01-04 a la(s) 12 59 11" src="https://user-images.githubusercontent.com/517228/103553932-eb991c00-4e8c-11eb-946c-462bd4d31098.png">

It should be the very same result, ie 2020-01-27; but tells me all wrong!

**Comment by alexandrebodin** [comment] 2021-01-04 21:05
Yep this is not a graphQL bug but a mongo one. @Convly when deep filtering the sort is not applied on the second query which means the limit passes first and breaks the query. we need to review this

**Comment by Convly** [comment] 2021-01-11 13:35
Reopening this issue since the linked pr was fixing a bug listed in the comment and not the problem reported by the author.

**Comment by TheManFromEarth1** [comment] 2021-04-05 14:01
I seem to have this problem with postgresql aswell

The limit under Links doesn't work 

Error: Unknown argument \"limit\" on field \"Collection.Links\".",

```
query Collections ($ListIDs: [String!] ) {
  collections (where: { id: $ListIDs} )  {
   id
   Links  (limit: 5)  {
    id
    Index
      }
    }
  }
}
```
Strapi 3.5.4

**Comment by derrickmehaffy** [comment] 2021-12-22 20:05
should be fixed in v4, closing

**Closed by derrickmehaffy** 2021-12-22 20:05 UTC
Labels: issue-type: bug, severity: high, status: confirmed, source: plugin:graphql
