### ISSUE TITLE
Transfer pull not working with DigitalOcean App platform

### ISSUE THREAD

**Issue by Brianggalvez** [strapi/strapi#16296] opened 2023-04-04 15:12 UTC
### Required System information

- Node.js version: v18.13.0
- NPM version: 8.19.3
- Strapi version: 4.9.0
- Database: PostgreSQL
- Operating system: DO AppPlatform
- Is your project Javascript or Typescript: Js

### Describe the bug
After configuring transfer token and run the command yarn strapi transfer --from ... the CLI outputs the following:

 error: [FATAL] Failed to initialize the connection: Unexpected server response 504
Transfer process failed.

**Comment by Pavan-Sai-Grandhi** [comment] 2023-04-13 07:10
System information
Node.js version: v18.12.1
NPM version: 9.2.0
Strapi version: 4.9.0
Database: PostgreSQL

Got a similar error on running this command (it is an example):
`npm run strapi transfer -- --from remoteURL --from-token remoteToken`

error: [FATAL] Failed to initialize the connection: Unexpected server response 500
Transfer process failed.

Error log in remote instance:

```
2023-04-13 12:27:30 | [2023-04-13 06:57:30.221] error: Invalid Header
-- | --
  |   | 2023-04-13 12:25:03 | at async policiesMiddleware (/opt/app/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
  |   | 2023-04-13 12:25:03 | at async returnBodyMiddleware (/opt/app/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
  |   | 2023-04-13 12:25:03 | at async serve (/opt/app/node_modules/koa-static/index.js:59:5)
  |   | 2023-04-13 12:25:03 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
  |   | 2023-04-13 12:25:03 | at runMicrotasks (<anonymous>)
  |   | 2023-04-13 12:25:03 | at /opt/app/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:33:12
  |   | 2023-04-13 12:25:03 | at dispatch (/opt/app/node_modules/koa-compose/index.js:42:32)
  |   | 2023-04-13 12:25:03 | at policiesMiddleware (/opt/app/node_modules/@strapi/strapi/lib/services/server/policy.js:24:11)
  |   | 2023-04-13 12:25:03 | at dispatch (/opt/app/node_modules/koa-compose/index.js:42:32)
  |   | 2023-04-13 12:25:03 | at /opt/app/node_modules/@strapi/admin/server/middlewares/data-transfer.js:11:12
  |   | 2023-04-13 12:25:03 | at dispatch (/opt/app/node_modules/koa-compose/index.js:42:32)
  |   | 2023-04-13 12:25:03 | at returnBodyMiddleware (/opt/app/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:24)
  |   | 2023-04-13 12:25:03 | at dispatch (/opt/app/node_modules/koa-compose/index.js:42:32)
  |   | 2023-04-13 12:25:03 | at Object.runner-pull (/opt/app/node_modules/@strapi/data-transfer/dist/strapi/remote/handlers/utils.js:55:37)
  |   | 2023-04-13 12:25:03 | at handleWSUpgrade (/opt/app/node_modules/@strapi/data-transfer/dist/strapi/remote/handlers/utils.js:40:35)
  |   | 2023-04-13 12:25:03 | at assertValidHeader (/opt/app/node_modules/@strapi/data-transfer/dist/strapi/remote/handlers/utils.js:18:15)
  |   | 2023-04-13 12:25:03 | Error: Invalid Header
```

**Comment by arpadgabor** [comment] 2023-05-24 07:51
Same here, but I get no logs, just an error 500. Trying to pull data from remote.

**Comment by exdeniz** [comment] 2023-05-25 06:14
Node.js version: v16.19.0
NPM version: 8.19.3
Strapi version: 4.10.6
Database: mysql

```
1|strapi  | [2023-05-25 06:09:53.963] error: Invalid Header
1|strapi  | Error: Invalid Header
1|strapi  |     at assertValidHeader (/home/user/frontend/garantex/node_modules/@strapi/data-transfer/dist/strapi/remote/handlers/utils.js:18:15)
1|strapi  |     at handleWSUpgrade (/home/user/frontend/garantex/node_modules/@strapi/data-transfer/dist/strapi/remote/handlers/utils.js:40:35)
1|strapi  |     at Object.runner-pull (/home/user/frontend/garantex/node_modules/@strapi/data-transfer/dist/strapi/remote/handlers/utils.js:55:37)
1|strapi  |     at dispatch (/home/user/frontend/garantex/node_modules/koa-compose/index.js:42:32)
1|strapi  |     at returnBodyMiddleware (/home/user/frontend/garantex/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:24)
1|strapi  |     at dispatch (/home/user/frontend/garantex/node_modules/koa-compose/index.js:42:32)
1|strapi  |     at /home/user/frontend/garantex/node_modules/@strapi/admin/server/middlewares/data-transfer.js:11:12
1|strapi  |     at dispatch (/home/user/frontend/garantex/node_modules/koa-compose/index.js:42:32)
1|strapi  |     at policiesMiddleware (/home/user/frontend/garantex/node_modules/@strapi/strapi/lib/services/server/policy.js:24:11)
1|strapi  |     at dispatch (/home/user/frontend/garantex/node_modules/koa-compose/index.js:42:32)
```
on server and client:
```
npm run strapi transfer --from remoteURL --from-token remoteToken
[2023-05-25 09:09:53.938] error: [FATAL] Failed to initialize the connection: Unexpected server response 500
Transfer process failed.
error Command failed with exit code 1.
```

**Comment by exdeniz** [comment] 2023-06-12 08:27
The problem was nginx header processing. If you connect directly to strapi, the transfer works.

**Comment by Brianggalvez** [comment] 2023-06-28 08:05
I see this in from server logs:
`upstream prematurely closed connection while reading response header from upstream, client:**, server: , request: "GET /admin/transfer/runner/pull HTTP/1.1", upstream: "http://127.0.0.1:1337/admin/transfer/runner/pull", host: ""

==> /var/log/nginx/access.log <==
********** - - [28/Jun/2023:10:01:45 +0200] "GET /admin/transfer/runner/pull HTTP/1.1" 502 166 "-" "-"
`

**Comment by marcoautiero** [comment] 2023-07-05 13:49
Hey there, we're sorry for the issues you're encountering, we appreciate you reporting them because it helps us to identify possible improvements to the data transfer feature. But, I need to invite you to open a dedicated issue if it strongly differs from the one raised by the author of this issue. Your error codes and descriptions seem slightly different from the main issue, and it could be hard to discuss all of them in a single one.

@Pavan-Sai-Grandh, @arpadgabor, and @exdeniz, is there any particular reason you consider this issue similar to the ones that you're mentioning in your comments? Are they all happening in a DigitalOcean App?

**Comment by innerdvations** [comment] 2023-08-01 08:27
We are closing this issue involving the 504 status (gateway timeout) because we are unable to reproduce on DO and it appears to be a server or proxy configuration error. If anyone is able to provide additional information we can reopen and investigate further.

Regarding the similar but different 500 status with Strapi error invalid header: this is a server/proxy configuration issue and not something Strapi can fix. We have improved the error messaging which will hopefully lead people to the solution quicker.

**Closed by innerdvations** 2023-08-01 08:27 UTC
Labels: issue: bug, severity: medium, status: can not reproduce, source: core:data-transfer
