### ISSUE TITLE
Documentation links broken in live site

### ISSUE THREAD

**Issue by Salman2301** [strapi/strapi#6368] opened 2020-05-26 22:46 UTC
**404 Error in documentation (nginx is not redirecting?)**
  When i try to open the link in a new tab. instead of redirecting me to url with .html attached at the end, it throws 404 error
.
When you navigate to 
https://strapi.io/documentation/v3.x/getting-started/installation

It should redirect to
https://strapi.io/documentation/v3.x/getting-started/installation.html

I run the documentation in my local machine <br>
It looks like vuepress is working
when you goto
https://strapi.io/documentation/v3.x/getting-started/installation
it will redirect to url with the .html at the end

So, i think the **nginx** is the issue

**Steps to reproduce the behavior**

1. Go to 'https://strapi.io/documentation/v3.x/getting-started/installation.html'
2.  Right Click on 'CLI' link
3.  Click on "Open in New Tab"
4. Goto the tab it will show 404 error => https://strapi.io/documentation/v3.x/installation/cli

**Expected behavior**
It should redirect me to the url with a prefix of ".html"
https://strapi.io/documentation/v3.x/installation/cli.html

**Screenshots**
-

**Code snippets**
-

**System**

- Node.js version: -
- NPM version:
- Strapi version:  v3.x
- Database: -
- Operating system: -

**Additional context**
I am using Window, Chrome browser. I think the nginx is receiving the url but throws 404 error

**Comment by derrickmehaffy** [comment] 2020-05-27 00:38
@alexandrebodin @lauriejim

**Comment by alexandrebodin** [comment] 2020-05-27 09:03
Hi @Salman2301  thank you for the report, 
Can you share where you are getting those links from ? There is no reasons you should get such a link without the .html att the end :)

**Comment by Salman2301** [comment] 2020-05-27 10:44
![bug](https://user-images.githubusercontent.com/40920317/83009668-b5f99e00-a034-11ea-9926-a41a9c68a439.jpg)

**Added a screenshot**

All the links in the document, don't have .html at the end
When u click on it, it works fine 
But you open the link in new tab or copy the link address you are gonna get
link without .html at the end

**Comment by Salman2301** [comment] 2020-05-27 11:07
@alexandrebodin I tagged you in slack in feedback channel, to explain the issue
it shows the vuepress redirect /cli to /cli.html

But not the live one

**Comment by derrickmehaffy** [comment] 2020-05-27 11:36
I can't reproduce this on the live documentation.
![Peek 2020-05-27 04-35](https://user-images.githubusercontent.com/8593673/83014441-93836880-9fd3-11ea-8210-9f1835afa016.gif)

**Comment by Salman2301** [comment] 2020-05-27 11:48
@derrickmehaffy i have said it couple of times
once again
 it works when u click on it
**now try to right click and open the link in new tab**
or copy the link

**Comment by derrickmehaffy** [comment] 2020-05-27 11:52
> @derrickmehaffy i have said it couple of times
> once again
> it works when u click on it
> **now try to right click and open the link in new tab**
> or copy the link

Ah sorry missed that, that is odd :thinking: 

Those links are relative inside of viewpress:

```
<div>
	<InstallLink link="../installation/cli">
		<template #icon>
			<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 256 271"><g><path d="M116.553,0 L0,67.953 L0,98.096 L49.665,127.882 L91.366,105.163 L91.366,78.74 L179.665,28.034 L241.711,63.77 L241.637,135.222 L156.567,184.231 L128.082,173.694 L90.165,197.882 L91.128,255.785 L117.233,270.858 L234.743,203.897 L234.743,163.65 L221.531,170.761 L221.531,196.347 L117.267,255.461 L104.352,248.005 L103.644,205.48 L128.114,189.128 L157.607,199.658 L256,142.912 L255.065,55.656 L179.678,12.633 L78.016,71.009 L78.016,97.419 L49.824,112.41 L13.35,90.536 L13.35,75.622 L116.243,15.636 L137.841,29.399 L150.89,21.886 L116.553,0 Z M186.0696,71.0918 L164.1876,84.3678 L164.7436,109.9558 L187.1816,122.2678 L209.0636,108.9918 L208.5076,83.4048 L186.0696,71.0918 Z M186.3206,82.6508 L198.6226,89.4018 L198.9276,103.4308 L186.9306,110.7088 L174.6286,103.9588 L174.3236,89.9298 L186.3206,82.6508 Z M73.701,141.0235 L70.738,135.4095 C70.086,134.1755 68.558,133.7035 67.324,134.3545 L47.931,144.5855 C46.697,145.2365 46.224,146.7655 46.876,148.0005 L49.84,153.6175 C50.491,154.8515 52.02,155.3245 53.254,154.6725 L72.645,144.4385 C73.88,143.7865 74.352,142.2575 73.701,141.0235 M84.9168,158.0703 L81.9548,152.4543 C81.2838,151.1813 79.6868,150.7253 78.4438,151.4513 L45.7398,170.5723 C44.5718,171.2563 44.1488,172.7373 44.7798,173.9333 L47.7418,179.5493 C48.4138,180.8223 50.0108,181.2783 51.2528,180.5523 L83.9578,161.4313 C85.1248,160.7483 85.5478,159.2673 84.9168,158.0703 M87.9705,169.6055 L49.5225,191.7065 C48.3435,192.3835 47.9115,193.8735 48.5475,195.0765 L51.5105,200.6915 C52.1785,201.9575 53.7635,202.4165 55.0045,201.7035 L93.4525,179.6025 C94.6325,178.9245 95.0635,177.4345 94.4285,176.2315 L91.4645,170.6165 C90.7965,169.3515 89.2115,168.8925 87.9705,169.6055" fill="#FFF"/></g></svg>
		</template>
		<template #title>CLI</template>
		<template #description>
			Create a project in your local machine using the CLI.
		</template>
	</InstallLink>
</div>
```

And if it's handling the redirection on a click, why not in a new tab. That shouldn't have anything to do with Nginx.

**Comment by Salman2301** [comment] 2020-05-27 12:18
I am not that much of an experience to share this
but anyway to answer your question
if you click on it
The page don't do a full redirect, cause VUE is a SPA (It's just show and hide the page and change the URL)
but when u go to that link specifically without .html
NGINX need allow it.
So VUE can redirect to .html, and reder the page

If you run the local DOC as i share the video in slack
the redirects works but in live site
i assume there is a restriction somewhere that's cause this error

It's just a wild guess

**Comment by Salman2301** [comment] 2020-05-27 12:37
I think it's better to rewrite all the Intallation Link with .html at the end 
Instead of configuring the NGINX

**Comment by EtienneR** [comment] 2020-05-27 14:36
> Hi @Salman2301 thank you for the report,
> Can you share where you are getting those links from ? There is no reasons you should get such a link without the .html att the end :)

Hello,

It's look a familiar problem.
I am using Strapi 3 and when I go in the "Maketplaces" and I click to "Documentation" plugin for the installation, the modale appear with a link with "Read to the documentation" but this link is not good : https://strapi.io/documentation/v3.x/configurations/configurations.html#server returns a 404 error

**Comment by derrickmehaffy** [comment] 2020-05-28 06:55
> I think it's better to rewrite all the Intallation Link with .html at the end
> Instead of configuring the NGINX

This specifically goes against Vuepress's documentation and best practices, if anything we should be using `.md` links to pages. I'm playing around with different options locally on my machine (with the docs and nginx to see if I can find a good solution) but hard coding .html is not an option in the docs.

**Comment by Salman2301** [comment] 2020-05-28 08:28
@derrickmehaffy 
I will leave that upto you guys. Just want to let you guys know of this issue

**Comment by lauriejim** [comment] 2020-07-01 10:10
Fixed in my docs review

**Closed** 2020-07-01 10:10 UTC
Labels: priority: medium, source: documentation, status: confirmed, type: bug
