### ISSUE TITLE
Strapi is not able to create a new project

### ISSUE THREAD

**Issue by AnizZen** [strapi/strapi#2476] opened 2018-12-13 01:54 UTC
**Informations**
- **Node.js version**: 10.14.2
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.16
- **Database**: MongoDB v3.4.6
- **Operating system**: Windows10

**What is the current behavior?**
I am unable to create a new project with strapi. I ran "strapi new project-name" command. Next thing I am asked to pick a database and I selected MongoDB. Then I wait for several minutes (15 minutes plus) and nothing happens.

I am on Strapi v3.0.0-alpha.16, MongoDB v3.4.6, Node.js v10.14.2 , NPM v6.4.1, Windows 10

Can you please help to resolve?

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by webgururobin** [comment] 2018-12-13 03:04
Not sure, but it looks like the problem is because of MongoDB deprecated functions, hopefully, this is resolved.

**Comment by derrickmehaffy** [comment] 2018-12-13 16:33
@AnizZen @webgururobin Please see: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#windows

I am marking this issue as closed as there are many duplicate issues related to create new projects on windows. Please see that FAQ for work arounds if you are on windows 10.

**Closed by derrickmehaffy** 2018-12-13 16:33 UTC
