### ISSUE TITLE
JSON fields are ordered differently when exceeding 8 fields per object

### ISSUE THREAD

**Issue by kamal-choudhary** [strapi/strapi#10699] opened 2021-08-06 07:34 UTC
### Describe the bug

I have a JSON data field in one of my content types. It works perfectly fine until the number of fields inside the JSON object is either 8 or less than 8. As soon as I introduce field number 9, the order of JSON fields gets changed.

### Steps to reproduce the behavior

1. Add a JSON data field in your content type
2. Go to your content type and create an entry
3. Add some valid JSON for the JSON field, it works fine until the number of fields inside the JSON object is either 8 or less than 8
4. Added field number 9 and the ordering of fields will get changed.

### Expected behavior

The ordering of fields should not change. Items should be ordered as entered.

### Code snippets

Let’s say I have a Person type JSON-LD object and I add only 8 fields in this format:
```
{
  "@context": "https://schema.org",
  "@type": "Person",
  "name": "Jane Doe",
  "url": "http://www.janedoe.com",
  "sameAs": "sdfsdfsdf",
  "jobTitle": "CEO",
  "image": "janedoe.jpg",
  "description": "jane doe description"
}
```
Until this moment, it is perfectly fine.

But if I add a new field like “memberOf”, then the ordering of the fields gets changed.

```
{
  "name": "Jane Doe",
  "url": "http://www.janedoe.com",
  "@context": "https://schema.org",
  "memberOf": "janedoewebsite.com",
  "sameAs": "sdfsdfsdf",
  "@type": "Person",
  "jobTitle": "CEO",
  "image": "janedoe.jpg",
  "description": "jane doe description"
}
```

The whole ordering of fields has been changed by introducing field 9.
### System

- Node.js version: 14.15.3
- NPM version: 6.14.9
- Strapi version: 3.6.3
- Database: SQLite locally, postgreSQL on Production
- Operating system: macOS Big Sur

**Comment by derrickmehaffy** [comment] 2021-08-12 21:25
Tested on v3.6.6 using Linux Mint 20.2 and SQLite (Node v14) and it works fine:

![image](https://user-images.githubusercontent.com/8593673/129272049-be4a2d32-279b-44b3-be54-db3138a601c1.png)
![image](https://user-images.githubusercontent.com/8593673/129272078-cceb2527-440d-4c5f-95fc-626afaaf5889.png)

**Comment by derrickmehaffy** [comment] 2021-08-12 21:27
Unsure of source, it could be something the Content-Manager is doing or it could have something to do with the backend. :thinking:

**Comment by rowild** [comment] 2022-01-25 19:18
I observe a similar problem. This is what the json data looks like in the JSON field:

```json
{
  "pilot": {
    "route": "/pilot",
    "btn_txt": "To Pilot Experiment",
    "btn_type": "success"
  },
  "experiment": {
    ...
  },
  "playground": {
    ...
  },
  "introduction": {
    ...
  }
}
```

If I want to change to order and put `introduction` as the first object:

```json
{
  "introduction": {
    "route": "/Introduction",
    "btn_txt": "Introduction",
    "btn_type": "success"
  }
  "pilot": {
     ...
  },
  "experiment": {
    ...
  },
  "playground": {
    ...
  }
}
```

strapi does not accept this and instead saves the old version again.

This only happens in production mode, not in development. (And currently I only tested Strapi v3.)

**Comment by derrickmehaffy** [comment] 2022-01-27 22:14
> I observe a similar problem. This is what the json data looks like in the JSON field:
> 
> ```json
> {
>   "pilot": {
>     "route": "/pilot",
>     "btn_txt": "To Pilot Experiment",
>     "btn_type": "success"
>   },
>   "experiment": {
>     ...
>   },
>   "playground": {
>     ...
>   },
>   "introduction": {
>     ...
>   }
> }
> ```
> 
> If I want to change to order and put `introduction` as the first object:
> 
> ```json
> {
>   "introduction": {
>     "route": "/Introduction",
>     "btn_txt": "Introduction",
>     "btn_type": "success"
>   }
>   "pilot": {
>      ...
>   },
>   "experiment": {
>     ...
>   },
>   "playground": {
>     ...
>   }
> }
> ```
> 
> strapi does not accept this and instead saves the old version again.
> 
> This only happens in production mode, not in development. (And currently I only tested Strapi v3.) I would recommend to NOT set severity to low, because this does influence frontend output.

Can you please test this on v4, we won't be fixing issues on v3 anymore unless they are critical or security related

**Comment by nolliebigspin** [comment] 2022-01-27 23:11
> Can you please test this on v4, we won't be fixing issues on v3 anymore unless they are critical or security related

I'm using `strapi@4.0.5` right now and had the same issue as @rowild yesterday. After saving JSON file, the order of objects is completly messed up.

**Comment by rowild** [comment] 2022-01-28 00:16
I've just tested my issue in strapi v4, too, and the problem is the same. To sum up:

- JSON can be reorganised / restructured in development mode
- JSON cannot be restructured in production mode; there it will always jump back to the first form it had in initial save

**Comment by rylax** [comment] 2022-02-18 21:37
Facing the same issue.

**Comment by pandeyprafull** [comment] 2022-04-13 06:42
Facing the same as well

**Comment by derrickmehaffy** [comment] 2022-04-18 20:02
Can't reproduce on v4.1.8 using SQLite. Marking as closed until additional information is given to reproduce

**Closed by derrickmehaffy** 2022-04-18 20:02 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:content-manager

**Comment by zaychoer** [comment] 2022-09-15 05:45
I'm using strapi@4.3.2 right now, default type for JSON field on postgres for strapi is jsonb, so i update the field json to json . After saving JSON file, the order of objects was ordered as entered.

If you want your keys order not to change, you can use the json type that does not change the order of the keys when storing the data in the database.

Hope it helps.

**Comment by chakraskun** [comment] 2022-09-24 10:31
> I'm using strapi@4.3.2 right now, default type for JSON field on postgres for strapi is jsonb, so i update the field json to json . After saving JSON file, the order of objects was ordered as entered.
> 
> If you want your keys order not to change, you can use the json type that does not change the order of the keys when storing the data in the database.
> 
> Hope it helps.

works like a charm 👍

**Comment by marianolop** [comment] 2023-10-10 14:46
I have strapi 3, so I can't change from jsonb to json, did anybody find a solution. This is real important, I have to show some properties in certain order

**Comment by igotDiamonds** [comment] 2023-10-11 13:07
Facing this issue on Strapi v4.10.4

**Comment by LostAnurag** [comment] 2024-04-26 04:35
> I have strapi 3, so I can't change from jsonb to json, did anybody find a solution. This is real important, I have to show some properties in certain order

Did you resolve that issue?

**Comment by LostAnurag** [comment] 2024-04-26 04:36
> Facing this issue on Strapi v4.10.4

m facing same issue, do you have any solution to fix it?

**Comment by LostAnurag** [comment] 2024-04-26 18:37
> you can use the json type that does not change the order of the keys when storing the data in the database.

what you did to reslve it bro?
m facing that issue
