### ISSUE TITLE
Strapi mongo, findOne({ id: null }) returns first created record

### ISSUE THREAD

**Issue by borm** [strapi/strapi#9077] opened 2021-01-09 19:21 UTC
### Steps to reproduce the behavior

1. Create a custom collection
2. Add a two records to collection
3. Override the collection api controller `--->(FIND)<---` method like bellow
```js
const { sanitizeEntity } = require('strapi-utils');

module.exports = {
  /**
   * Retrieve a record.
   *
   * @return {Object}
   */

  async find(ctx) {
    // reproduced also with id: undefined
    const entity = await strapi.services.restaurant.findOne({ id: null });
    return sanitizeEntity(entity, { model: strapi.models.restaurant });
  },
};
```
4. Send request to api
```
fetch('/restaurants') // Get all, not single query
```
### Actual behavior
Strapi returns a first created record

### Expected behavior
Should return 404 or some error like original REST `findOne`
`fetch('/restaurants/null')`
```
[2021-01-09T19:36:11.349Z] error CastError: Cast to ObjectId failed for value "null" at path "_id" for model "restaurant"
    at model.Query.exec (node_modules/mongoose/lib/query.js:4371:21)
```

### System

- Node.js version: v14.15.3
- Strapi version: 3.4.0
- Database: mongo v4.4.1
- Operating system: MacOS

### Screenshots
![image](https://user-images.githubusercontent.com/4027842/104106911-821c7180-52c1-11eb-9b34-c8246067eb6f.png)
![image](https://user-images.githubusercontent.com/4027842/104106900-6dd87480-52c1-11eb-92c6-b340e466ff80.png)
![image](https://user-images.githubusercontent.com/4027842/104106913-88125280-52c1-11eb-8dfa-5f70bc45bf27.png)

**Comment by borm** [comment] 2021-01-09 19:45
Update,
Change the `findOne` to `find` with the same params 
```js
async find(ctx) {
  const entity = await strapi.services.restaurant.find({ id: null });
  return sanitizeEntity(entity, { model: strapi.models.restaurant });
},
```

![image](https://user-images.githubusercontent.com/4027842/104107311-dd4f6380-52c3-11eb-9145-ca6c285892e7.png)

**Comment by derrickmehaffy** [comment] 2021-01-10 07:42
I'm not sure exactly what you are trying to do here?

**Comment by borm** [comment] 2021-01-10 14:55
What is not clear?
im trying get record with id: null
normally that record can`t be exists, so should not be any response, why returns first record instead of error?

**Comment by derrickmehaffy** [comment] 2021-01-11 18:03
For `findOne`, you are accessing the service (which hits the query) and forcefully passing a null objectID hence the error.

Queries directly interface with the Mongoose ORM, so it would be the same as trying to pass a query directly into MongoDB with an `ObjectID: null` which would throw an error.

For `find` you are doing a filter on the ID, MongoDB (for the same reason as above) treats this as an empty filter and returns the default response.

---

Any time you are interacting with the service/query you will want to expect like you are asking the database directly, if you want to return an error if the response from Database isn't correct you must check it inside the controller and do something like `return ctx.badRequest('some error message')`

I think you might have some confusion how the internal API works, and that's okay, why not open up a thread on our [forum](https://forum.strapi.io) and I'd be happy to show you around the API.

Going to mark this as closed as it's not a bug within Strapi.

**Closed by derrickmehaffy** 2021-01-11 18:03 UTC
Labels: type: help wanted
