### ISSUE TITLE
SQLite error when adding required field with blank default 

### ISSUE THREAD

**Issue by tiberiuana** [strapi/strapi#2941] opened 2019-03-06 12:08 UTC
**Information**
- **Node.js version**: 10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: SQLite (using default settings, unconfigured)
- **Operating system**: Ubuntu 18.04.2
- **(Optional) Link to your Project**: --

**Steps to reproduce the problem**

- quickstart new project
- define new content type
- add new string field
  - check *Required field*
  - leave *Default value* blank
- save

**What is the expected behavior?**

New required field gets added.

**What is the current behavior?**

```
(node:16263) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: Cannot add a NOT NULL column with default value NULL
    at Client_SQLite3._query (/home/tga/tmp/test1/node_modules/knex/lib/dialects/sqlite3/index.js:108:12)
    at Client_SQLite3.query (/home/tga/tmp/test1/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/home/tga/tmp/test1/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /home/tga/tmp/test1/node_modules/knex/lib/runner.js:47:21
    at processImmediate (timers.js:637:19)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Runner.run (/home/tga/tmp/test1/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/home/tga/tmp/test1/node_modules/knex/lib/interface.js:23:43)
(node:16263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16263) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-03-06T12:02:16.740Z] debug ⛔️ Server wasn't able to start properly.

```

**Comment by derrickmehaffy** [comment] 2019-03-06 12:20
@tiberiuana Do you already have data in that table?

**Comment by tiberiuana** [comment] 2019-03-06 12:38
No, I just reproduced it in a brand new project.

**Comment by chielorenz** [comment] 2019-03-10 10:55
For anyone who is stuck here a workaround is to create the field as not required and then set it as required.

**Comment by ralphMevision** [comment] 2019-03-10 20:07
I had the exact same issue. I had to go in the 

> project folder 

on my local drive, open the 

>api folder, 

select the folder of the content type that was crashing the server then open the 

> models folder

then open the 

>xxxxx.settings.json file

 and remove all the `required: true` lines in the json file, save it and restart the project with the command line `strapi start`. I could then just use the admin UI to put all the required fields like mentioned by @chielorenz 

I just hope this will big fixed asap.

**Comment by lauriejim** [comment] 2019-03-12 14:50
Hello!

I follow your steps and was not able to reproduce.

1. Click on add `+Add Content Type`
2. Name it `article`
3. Click on `+ Add New Field`
4. Choose `String`
5. Name it `title`
6. Set `required` in advanced settings
7. Click on `Save` button

All works ... I may be miss something.

**Comment by sdecourcel** [comment] 2019-03-21 12:20
Hi, 
I just got the same issue : 
1. Add un enumerable field « event_type » with a list of values in « event » model - NB : NOT required at first, and NO default value 
2. Create several events (with http://localhost:1337/admin/plugins/content-manager) : one of these events was created with the first value of that enum list without having to select it (because first value of the enum list is displayed by default)
=> Issue n°1:  http://localhost:1337/events  returned NULL for that enum field for the event I created with the first value of the enum list.
It's not really an issue : when I click on « update » for any event, the content-manager displays all the time the first value of the enum list event if the value stored in database is different => it is confusing (when I created the event with the first value of the enum list without selecting it, in fact the value stored in the database was NULL)

3. Add « Required » on that enum field :
=>Issue n°2 : UnhandledPromiseRejectionWarning: error: column "event_type" contains null values

To fix that, I had to :
- Remove « required : true » in events.settings.json file in order to restart strapi
- Set Default value with the first value of the enum list
=>now when I create an event with the first value of the enum list (without having to select it), everything works fine

**Comment by lauriejim** [comment] 2019-03-21 15:46
Hello @sdecourcel your issue is related to this one https://github.com/strapi/strapi/issues/2471

**Comment by ArjanRoos96** [comment] 2019-04-16 12:38
The problem also occures when you add a field of the type text and set it as required. See the following error statement:

```
error ALTER TABLE `restaurants` ADD `description` longtext NOT NULL ; - SQLITE_ERROR: Cannot add a NOT NULL column with default value NULL
{ Error: SQLITE_ERROR: Cannot add a NOT NULL column with default value NULL
    at Client_SQLite3._query (/Users/arjanroos/Documents/Prive/cms/node_modules/knex/lib/dialects/sqlite3/index.js:108:12)
    at Client_SQLite3.query (/Users/arjanroos/Documents/Prive/cms/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/Users/arjanroos/Documents/Prive/cms/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /Users/arjanroos/Documents/Prive/cms/node_modules/knex/lib/runner.js:47:21
    at processImmediate (timers.js:637:19)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Runner.run (/Users/arjanroos/Documents/Prive/cms/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/Users/arjanroos/Documents/Prive/cms/node_modules/knex/lib/interface.js:23:43) errno: 1, code: 'SQLITE_ERROR' }
```

**Comment by lauriejim** [comment] 2019-04-16 19:24
Your issue @ArjanRoos96 is related to an other issue.
You can't apply a contraint like that if you already have data in your database (not related to Strapi but to the database)

So since I han't new about this issue I close it.

**Closed by lauriejim** 2019-04-16 19:24 UTC
Labels: priority: medium, status: can't reproduce, type: bug 🐛

**Comment by bcgilliom** [comment] 2019-04-17 15:25
I just got this on `3.0.0-alpha.26` when I added a number field, marked as required, left default value blank, saved. Server crashed, won't restart until manually removing required prop from xxx.settings.json.

**Comment by sparticvs** [comment] 2019-04-18 15:50
I am having a similar issue with 'boolean'. The only default option is "Set to true". I want them to be false by default and required. I expect that the default value is false, not null.

**Comment by gnimmelf** [comment] 2019-04-22 23:42
...and another variant: Added a required string-field to the `user` model;

First error is
```
error ALTER TABLE `users-permissions_user` ADD `name` varchar(255) NOT NULL ; - SQLITE_ERROR: Cannot add a NOT NULL column with default value NULL
```
Then errors on subsequent restarts are:
```
SQLITE_ERROR: table `tmp_users-permissions_role` already exists
```

Fix is 1) Fix up the model `plugins/users-permissions/models/User.settings.json`, then 2) manually drop the corresponding table that "already exists".

Above all, thanks for an amazing job with Strapi!

**Comment by renenjovalente-ubidy** [comment] 2019-04-28 14:25
i am encountering the same issue if i add a field with required but no default value

```bash
NOT NULL ; - SQLITE_ERROR: Cannot add a NOT NULL column with default value NULL
```

**Comment by ssotomayor** [comment] 2020-08-25 06:51
Just got this error, solution from @ralphMevision worked for me.

**Comment by J-hash-code** [comment] 2020-10-13 03:44
if you got the error : UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: Cannot add a NOT NULL, it sound like you already got the table  with  a data value of NULL  which should not be NULL. In my case just DROP TABLE IF EXISTS table_name, and then create a new one instead.
