### ISSUE TITLE
Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

### ISSUE THREAD

**Issue by SkinnyMonk** [strapi/strapi#12321] opened 2022-01-26 17:40 UTC
Informations

Node.js version:  v16+

NPM version: 8+

Strapi version: * 4.0.4

Database: postgresql for production, default one for local

Operating system: Ubuntu 20.04

(Optional) Link to your Project:

What is the current behavior?
On deploying on heroku, i found this error in logs Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call? After trying out some solutions i figured out, if i role back to previous working fine heroku version, the app works fine. But when i try to pull the code and make a empty push. I get same knex error. Also the rolled back version has a database which is not in the code i get from heroku pull. Since i can't delete the collection type on production. I don't know how to delete it. 

Steps to reproduce the problem

Have 3 collection types.. db1, db2, db3
Db1 can have multiple db2. 
Db2 can have multiple db3. 
Initially by mistake i added as db1 have multiple db3. Nd db2 has multiple db3. 
Thn change it to the correct order
Db1 can have multiple db2. 
Db2 can have multiple db3.
What is the expected behavior?
Whatever is showing in heroku production environment should reflect back exactly in local environment . 

Suggested solutions

**Comment by SkinnyMonk** [comment] 2022-01-30 19:30
So far I've understood it happens when i try to delete an existing content types. Does anyone have any idea how can I delete content types safely after production?

**Comment by kasonde** [comment] 2022-01-31 12:50
We do not recommend deleting content types in production. Strapi has to restart each time to update the schema definitions stored on the file system to match the database. Technically the first thing to get changed is the files in the file system and then Strapi syncs the database based on those files. Failure to update the filesystem in production, for example, could cause your database to be out of sync with your schema definition. Also your server does not get automatically restarted in production mode. 

We recommend making all changes in a development environment with the app running in development mode, checking your app into version control and pulling the changed application in the production environment.

**Comment by kasonde** [comment] 2022-01-31 12:51
I'll go ahead and close the issue in light of the new information, if you have any more info/disagree, we can always keep the conversation going and I can always reopen if the new information indicates an issue with Strapi

**Closed by kasonde** 2022-01-31 12:51 UTC
Labels: status: cant reproduce

**Comment by fabio-nettis** [comment] 2022-02-04 11:58
I'm having the same issue with Strapi V4.0.6. Randomly started receiving following error on startup, Strapi instance is **completely unusable** now.

```
[2022-02-04 12:40:54.410] error: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_SQLite3.acquireConnection (/Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/knex/lib/client.js:295:26)
    at async Runner.ensureConnection (/Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/knex/lib/execution/runner.js:259:28)
    at async Runner.run (/Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/knex/lib/execution/runner.js:30:19)
    at async Object.execute (/Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/@strapi/database/lib/query/query-builder.js:354:22)
    at async Object.findOne (/Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/@strapi/database/lib/entity-manager.js:118:22)
    at async Object.authenticate (/Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/@strapi/admin/server/strategies/api-token.js:32:20)
    at async Object.authenticate (/Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/@strapi/strapi/lib/services/auth/index.js:48:24)
    at async returnBodyMiddleware (/Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
    at async policiesMiddleware (/Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
    at async /Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/@strapi/strapi/lib/middlewares/logger.js:22:5
    at async /Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/@strapi/strapi/lib/middlewares/powered-by.js:16:5
    at async cors (/Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/@koa/cors/index.js:56:32)
    at async /Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/@strapi/strapi/lib/middlewares/errors.js:13:7
    at async session (/Users/fabio_nettis/github/bucan-labs/commerce-backend-v2/node_modules/koa-session/index.js:41:7)
```

Followed by:

```
[2022-02-04 12:52:10.082] error: update `strapi_core_store_settings` set `value` =
...
SQLITE_BUSY: database is locked
```

**Comment by Webbist-dev** [comment] 2022-02-04 12:06
Your resource is too limited for the app to spin up. Depending on where you're hosting this up the resources for the box. 
We had a similar issue hosting as a webapp in azure. Increasing the timeout might also help. 

You can add this in config/database.js 

`pool: {
  acquireTimeoutMillis: env.int('DATABASE_POOL_ACQUIRE_TIMEOUT_MILLIS', 60000),
}`

**Comment by fabio-nettis** [comment] 2022-02-04 12:11
> Your resource is too limited for the app to spin up. Depending on where you're hosting this up the resources for the box. We had a similar issue hosting as a webapp in azure. Increasing the timeout might also help.
> 
> You can add this in config/database.js
> 
> `pool: { acquireTimeoutMillis: env.int('DATABASE_POOL_ACQUIRE_TIMEOUT_MILLIS', 60000), }`

Thanks @Webbist-dev Alright. Will definitely give that a try.

**Comment by quornik** [comment] 2022-04-16 16:31
# SOLUTION PROPOSITION
I found a pretty specific way of handling such error.

It worked for me, since I had error / duplicates it postgres tables containing API model information, and this was the reason my app did not start. I wanted my database back, with posts / pages and rest of the content, and decided that I can restore the API fields naming and sizes just by editing it manually. 

If you are in  the same situation, you might try this solution.


## PREREQUISITES
Heroku CLI installed and logged in.
Make sure you have made backup for the database, on your not working app. Just in case.

## SOLUTION STEP BY STEP
- Create another app on Heroku, from the same repository as the one that stopped working.
- Attach fresh postgres database to this second app.
- On Heroku, databases can be attached to multiple apps. Use this functionality, and attach this new database as SECOND to the app that stopped working. Heroku distinguish those databases with specific names on every app. In my case, the same database on working app was attached as DATABASE and on not working app was attached as ROSE.
- Start the new app. With clean database it should start flawlessly. If not, the problem is elsewhere. If it does, you can do next steps.
- Do not log in to the Strapi admin on the new app. Check if it's running and if it does, leave it that way untouched.
- Use the Heroku CLI and execute command `heroku pg:copy OLDBASENAME SECONDBASENAME --app not-working-appname` - make sure that you have the databeses names in right order. The command will try to copy data from the old database to the new one, so you need to put the old database name first.
- Wait till the process end. It will end with errors, unable to copy some data. That is desired.
- You should now have SECOND app with data migrated from the first app.

Here's the trick: Strapi running on server, blocks the ability to write into tables responsible for holding API model information. Therefore, while you try to copy the data from one base to another, and the second one is attached to running strapi app, it will only be able to copy the tables which contains everything but API model. 

- Restart the new app's dynos, to make sure it will boot without problem.

#### OPTIONAL STEPS
- After you make sure that the second app is working, and the data that has been copied is sufficient, you might run the cli command but revert the database order. This way you should have the first app working again.

Hope it helps.
