### ISSUE TITLE
An error when trying to reorder components in dynamic zone with relation

### ISSUE THREAD

**Issue by romanslonov** [strapi/strapi#15259] opened 2022-12-23 09:25 UTC
### Required System information

- Node.js version: v18.12.1
- NPM version: 8.19.2
- Strapi version: 4.5.4
- Database: postgresql latest
- Operating system: macos 13.1

### Describe the bug

Got an error when trying to reorder dynamic zone components including component which has `has_many` relation.

```
TypeError: i is not iterable
    at content-manager.f9630c3b.chunk.js:1010:19282
    at Y.produce (main.71f24343.js:482:85735)
    at Ph (content-manager.f9630c3b.chunk.js:1010:18026)
    at Object.Co [as useReducer] (main.71f24343.js:541:55850)
    at t.useReducer (main.71f24343.js:573:5891)
    at Br (content-manager.f9630c3b.chunk.js:1010:23250)
    at tl (main.71f24343.js:541:54583)
    at Eo (main.71f24343.js:541:64349)
    at ot (main.71f24343.js:545:10106)
    at no (main.71f24343.js:545:990)
```

### Steps to reproduce the behavior

1. Create a collection-type for example Page with dynamic zone
2. Create a collection-type for example Car
3. Create a component which has relation `has_many` to Car collection-type for example CardsGrid
4. Go to content manager and create a Page and add some components to dynamic zone including CardsGrid and select some Car relations
5. Try to reorder that components inside dynamic zone
6. See an error in console

### Screenshots

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/10784316/209309137-69f638e4-7bd8-4279-bae7-87d629b03d30.png">

### Minimal reproduction repository
https://github.com/romanslonov/strapi-issue

**Comment by gu-stav** [comment] 2022-12-23 09:32
@romanslonov Thank you for opening this issue. Would it be possible for you to run Strapi in development mode, so that we are able to see the un-minified code?

**Comment by romanslonov** [comment] 2022-12-23 09:36
@gu-stav how? I ran it locally `npm run develop`, is there is another way?

**Comment by gu-stav** [comment] 2022-12-23 09:39
@romanslonov Does it work if you run `NODE_ENV=development npm run develop`? It not, nevermind - I'll have a look at the reproduction (thanks for this!).

**Comment by romanslonov** [comment] 2022-12-23 09:41
@gu-stav yes it's same, the code of admin ui is built and minified.

**Comment by yulafezmesi** [comment] 2023-01-02 09:56
same here.

**Comment by ibrahimdemir92** [comment] 2023-01-03 09:06
same here

**Comment by joshuaellis** [comment] 2023-01-03 12:26
I think this is a duplicate of #14908

**Closed by joshuaellis** 2023-01-03 12:26 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-manager
