### ISSUE TITLE
Videos are not visualized in preview mode at Rich Text Field

### ISSUE THREAD

**Issue by SalahAdDin** [strapi/strapi#8339] opened 2020-10-15 07:38 UTC
Hi, when we are creating content in a rich text field and we introduce a video (like we introduce images), we can't see the video in the preview mode.

**Steps to reproduce the behavior**

1. Create a type.
2. Add a rich-text field.
3. Go to the type and create a new instance.
4. Embed a video(media), in the content.
5. Go to the preview mode.

**Expected behavior**
We should see the embedded video too.

**Screenshots**
We have the next:
![Screen Capture_select-area_20201015002831](https://user-images.githubusercontent.com/5034215/96105431-b232bf00-0ee2-11eb-8ebc-df6ba2443465.png)

**System**

- Node.js Version: v14.12.0
- NPM version: 6.14.7
- Strapi version: 3.1.3
- Database: SQLite
- Operating system: Manjaro Linux

**Comment by soupette** [comment] 2020-10-15 12:42
I am closing this issue as it is a duplicate of #8004

Videos are not really supported in markdown, however, you can use the html version:

```
<video controls="controls" width="100%">
<source src="LINK FROM THE ML" type="video/mp4"></source>
</video>
```

**Closed by soupette** 2020-10-15 12:42 UTC
