### ISSUE TITLE
Internationalization tab missing in global settings after installing i18n plugin

### ISSUE THREAD

**Issue by dondurivan** [strapi/strapi#10252] opened 2021-05-06 10:16 UTC
### Describe the bug

After updating Strapi to version 3.6.1 and installing i18n plugin, I can't enable localization since the Internationalization tab is missing in Global Settings.

### Steps to reproduce the behavior

1. Update Strapi to version `3.6.1`
2. Install i18n plugin with `npm run strapi install i18n`
3. Run `npm run build --clean`
4. Run `npx strapi start`

### Expected behavior

i18n Plugin appears in Plugins page
Internationalization tab appears in Global settings

### Screenshots

![Screenshot from 2021-05-06 12-08-04](https://user-images.githubusercontent.com/3501560/117282222-c7624180-ae64-11eb-9c0b-4d69eaac42da.png)
![Screenshot from 2021-05-06 12-15-01](https://user-images.githubusercontent.com/3501560/117282255-d0531300-ae64-11eb-9b46-e0717ce654bc.png)

**Comment by kasonde** [comment] 2021-05-06 12:57
I'm unable to reproduce this behavior. If you can, please share your system information (in the same format on the issue template), your `package.json`, as well as the initial Strapi version that you upgraded from.

**Comment by derrickmehaffy** [comment] 2021-05-10 19:54
Closing as I also can't reproduce the issue and no new information has been provided.

If you have additional steps to reproduce let us know and we can reopen this.

**Closed by derrickmehaffy** 2021-05-10 19:54 UTC
Labels: status: can't reproduce
