### ISSUE TITLE
Bad request (400)when trying to authenticate with Nuxt Auth

### ISSUE THREAD

**Issue by c3as3** [strapi/strapi#4727] opened 2019-12-14 16:20 UTC
**Describe the bug**
When setting up a local strategy using Nuxt/auth I get a 400 error when passing the email and password hash. Using Axios, Strapi and Nuxt/auth

**Steps to reproduce the behavior**

**Expected behavior**
It should be able to login or at least provide a token in dev tools. 

**Screenshots**
### Strapi Public Permissions
<img width="609" alt="Screen Shot 2019-12-14 at 10 55 16 AM" src="https://user-images.githubusercontent.com/11511154/70851199-52056380-1e60-11ea-97ee-9faaeb757840.png">

**Code snippets**
### nuxt.config.js
```
modules: [
    '@nuxtjs/apollo',
    '@nuxtjs/axios',
    '@nuxtjs/auth'
  ],
  apollo:{
    clientConfigs: {
      default: {
        httpEndpoint: 'http://localhost:1337/graphql',
      }
    }
  },
  axios: {
    baseURL: 'http://localhost:1337'
  },

  /*
  ** Build configuration
  */
  build: {
    /*
    ** You can extend webpack config here
    */
    extend (config, ctx) {
    }
  },

  auth: {
    strategies: {
      local: {
        endpoints: {
          login: { url: '/auth/local/', method: 'post', propertyName: 'token' },
          logout: { url: '/api/auth/logout', method: 'post' },
          user: { url: '/users/me', method: 'get', propertyName: 'user' }
        },
        // tokenRequired: true,
        tokenType: ''
      }
    }
  }, 
```
### /login/index.vue LOGIN PAGE
```
<template>
    <v-container>
        <h1>Login</h1>

        <UserAuthForm buttonText="Login" :submitForm="loginUser"/>

        </v-container>
</template>>

<script>
import UserAuthForm from '@/components/UserAuthForm'

export default {
    components:{
        UserAuthForm
    },
    methods: {
        loginUser(loginInfo){
            this.$auth.loginWith('local', {
                data: loginInfo
            })
            
        }
    }
}
</script>
```

**System**
- 10.17.0 
- NPM version: 6.12.1
- Strapi v3.0.0-beta.17.8 
- Database: Mongo
- Operating system: MAC OS

**Additional context**
### DEV Tools results
Says the email or username is not provided
<img width="1343" alt="Screen Shot 2019-12-14 at 12 10 23 PM" src="https://user-images.githubusercontent.com/11511154/70852048-ca712200-1e6a-11ea-9edc-9b094d237a5b.png">

### BUT
Here is the data that is passed with variable "loginInfo"
<img width="1345" alt="Screen Shot 2019-12-14 at 12 13 10 PM" src="https://user-images.githubusercontent.com/11511154/70852077-41a6b600-1e6b-11ea-977f-950b15f4005a.png">

**Comment by derrickmehaffy** [comment] 2019-12-14 18:17
you need `identifier` and not `email`. The auth/local route only accepts:

```
{
  "identifier": "Email or Username",
  "password": "your password"
}
```

Also Strapi has no logout funcation yet, for that you just delete the stored JWT on your client.

**Comment by derrickmehaffy** [comment] 2019-12-14 18:18
I'm marking this as closed as the bug is not with strapi but user code, should this need to be reopened just reply back and it can be looked at for reopening.

**Closed by derrickmehaffy** 2019-12-14 18:18 UTC

**Comment by rodrigosebastiao** [comment] 2020-05-29 02:51
The problem is how can we extract the error (from this object), to show for the user? 
After all there is: _Email not confirmed by email_, _Wrong password_, _Identifier or password invalid_.
Tried to solve with Graphql React.
