### ISSUE TITLE
strapi index page works, /admin is blank (vendor.dll.js and main.js not found)

### ISSUE THREAD

**Issue by AndreiGuk** [strapi/strapi#3377] opened 2019-06-05 10:09 UTC
**Describe the bug**
I've successfully installed strapi on remote digital ocean server using the provided tutorial on medium. I use subdomain, nginx is set to serve localhost:1337 on location /

**Steps to reproduce the behavior**
Strapi welcome page opens without any issues. However, when I try to go to admin page I see a blank page.

**Expected behavior**
Admin page should be available

**Screenshots**
![strapi](https://user-images.githubusercontent.com/48508646/58948501-efd1f480-8792-11e9-88d2-25b0f9142b4f.png)

**Code snippets**
If I curl on the server I get
`curl http://localhost:1337/dashboard
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="mobile-web-app-capable" content="yes"><title>Strapi Admin</title></head><body><div id="app"></div><script type="text/javascript" src="vendor.dll.js"></script><script type="text/javascript" src="main.js"></script></body></html>`

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-alpha.26.2
- Database: MongoDB
- Operating system: Ubuntu 18.04.

**Additional context**
No

**Comment by davidkartuzinski** [comment] 2019-06-05 17:25
This happened to me as well. I don't remember the exact cause, but it's fixed if you follow these just released instructions from our docs regarding Ubuntu 18.04 / Digital Ocean:

http://localhost:8080/documentation/3.0.0-beta.x/guides/deployment.html#digital-ocean

Please note: We are going to revise these docs to remove the practice of adding the database configuration to the database.json but adding it to the env variables.

Please try these instructions, and see if this resolves for you.

-DK

**Comment by soupette** [comment] 2019-06-12 10:02
@AndreiGuk can you upgrade your application and check if the bug is still happening?

Here is the [documentation](https://strapi.io/documentation/3.0.0-beta.x/advanced/customize-admin.html#customization) regarding changing the administration panel path.

**Comment by juniorsdj** [comment] 2019-06-17 14:46
try `npm run build` before run `npm start`

**Comment by cpres** [comment] 2019-08-08 22:54
@AndreiGuk any luck on finding your solution? @soupette I'm on the latest strapi and bug is still happening with nginx reverse proxying

**Comment by cpres** [comment] 2019-08-09 00:46
Interestingly for me going to /admin/admin worked, but not admin

**Comment by soupette** [comment] 2019-08-09 09:04
Have you changed the path of your admin?

**Comment by cpres** [comment] 2019-08-10 15:28
I have not, but I did realize there was an easy work around for my issue, which was my admin path needed to be "/admin/" for the javascript files to be discovered. Probably something funky with the nginx reverse proxy.

**Comment by razvan-soare** [comment] 2019-08-11 21:28
I got the same error with nginx and reverse proxy. i followed this tutorial: https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#digital-ocean
But still cannot access /admin. But i can see without a problem the welcome page. Im not sure what the problem is here.

@cpres would you mind giving a hand ? im kinda stuck rn

**Comment by razvan-soare** [comment] 2019-08-12 06:16
I tried to change from /admin to /dashboard but it cannot find the route. Im getting 404 Not Found page from nginx.

**Comment by davidkartuzinski** [comment] 2019-08-12 08:27
@razvan-soare - Did you do step #6 https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#setup-production-server-and-install-node-js - particularly the instructions referred from https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally.

**Comment by razvan-soare** [comment] 2019-08-12 08:30
@davidkartuzinski Yes i did. This error is not from a global install from what i can see.

And i tested installing some global modules and is working just fine.

**Comment by davidkartuzinski** [comment] 2019-08-12 08:33
@razvan-soare Can you confirm that your install works as expected until the https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#further-steps-to-take-2 section?

And please also confirm that you are following the instructions linked to in that section of "Further Steps to Take"?

**Comment by razvan-soare** [comment] 2019-08-12 08:47
Installed nginx as instructed in Further Steps. 
I did not Set-up Nginx with HTTP/2 Support yet. i dont think this should be the problem.

webhook - working as expected
pm2 - running and config saved and restarting after reboot too all good here
PostgreSQL - installed added database and user to the config should be fine 


During deploy from github might be something odd.
It says to 
cd ./my-project/
npm install
NODE_ENV=production npm run build

But i dont have any build script by default ?  This is what i have.
`"setup": "cd admin && npm run setup",
    "start": "node server.js",
    "strapi": "node_modules/strapi/bin/strapi.js",
    "lint": "node_modules/.bin/eslint api/**/*.js config/**/*.js plugins/**/*.js",
    "postinstall": "node node_modules/strapi/lib/utils/post-install.js"`

The only build script is inside admin folder.

**Comment by razvan-soare** [comment] 2019-08-12 08:59
I double checked and indeed i had alpha version. I will test again using the beta and see if the problem is resolved and report back

**Comment by razvan-soare** [comment] 2019-08-14 06:44
Hey i tested with the beta version but still not working,
<img width="349" alt="Screenshot 2019-08-14 at 09 42 06" src="https://user-images.githubusercontent.com/39434481/62999660-cced4c00-be77-11e9-8cc2-dc9126e0f6db.png">

The problem is in production is looking for /admin/main but from what i see the files exist in /build folder.

Also i tried to Change access URL to /dashboard. 
- in dev is working as expected
- in prod is not. It doesn.t even find the route not sure if is a nginx problem or not :?? (switched back to admin and is finding the route and giving the error)

Thank you

**Comment by lauriejim** [comment] 2019-08-16 13:19
Hello! I close this issue.
Here is an issue about the documentation you read.
You are using `alpha` version of strapi and try `beta` documentation stuff.

**Closed by lauriejim** 2019-08-16 13:19 UTC
Labels: type: help wanted 🤷‍♂️

**Comment by coderdix** [comment] 2020-05-10 14:06
> Hey i tested with the beta version but still not working,
> <img alt="Screenshot 2019-08-14 at 09 42 06" width="349" src="https://user-images.githubusercontent.com/39434481/62999660-cced4c00-be77-11e9-8cc2-dc9126e0f6db.png">
> 
> The problem is in production is looking for /admin/main but from what i see the files exist in /build folder.
> 
> Also i tried to Change access URL to /dashboard.
> 
>     * in dev is working as expected
> 
>     * in prod is not. It doesn.t even find the route not sure if is a nginx problem or not :?? (switched back to admin and is finding the route and giving the error)
> 
> 
> Thank you

Did you ever find a solution to this?

**Comment by Pablo-Aldana** [comment] 2020-06-23 13:11
Hi I have stable version 3.0.4 and have same issue with PROD. Is there any solution for this? 

![image](https://user-images.githubusercontent.com/9969839/85407340-6474fe00-b563-11ea-8ad4-aca909c88447.png)

**Comment by pooja1425** [comment] 2020-07-01 07:12
I am getting blank /admin page after migrating to strapi stable version.
Error in console window: TypeError: currentPluginFn is not a function

Not able to create a strapi admin user also.

**Comment by FiNEk** [comment] 2020-07-23 09:22
> Hi I have stable version 3.0.4 and have same issue with PROD. Is there any solution for this?
> But surprisly if i tpy in the broswer myURL/admin/runtime~main.c50d6d3f.js it returns the file content... so doesn't seems to be an NGNIX issue

Im having exact same problem, but im using stable 3.0.6 and Apache for proxy. Problem here seems to be scripts src doesnt respect host variable. index.html get downloaded no problem, but scripts for that page are pointing to default host value.

**Comment by Bilal-io** [comment] 2020-07-28 03:51
I have attempted deploying to Vercel and Netlify, both result to blank pages.
This file doesn't exist `...netlify.app/admin/runtime~main.c82d5749.js` while `...netlify.app/runtime~main.c82d5749.js` exists. 

I have not made any changes to the default settings generated by `npx create-strapi-app my-project`

**Comment by felipepatricio** [comment] 2020-08-02 15:16
> try `npm run build` before run `npm start`

This work to me. Thanks @juniorsdj

**Comment by sergiooak** [comment] 2020-08-03 22:45
> I have attempted deploying to Vercel and Netlify, both result to blank pages.
> This file doesn't exist `...netlify.app/admin/runtime~main.c82d5749.js` while `...netlify.app/runtime~main.c82d5749.js` exists.
> 
> I have not made any changes to the default settings generated by `npx create-strapi-app my-project`

Vercel and Netlify are static hosting, not node hosting.
On the [official docs](https://strapi.io/documentation/3.0.0-beta.x/getting-started/deployment.html) have all major node hosting companies
