### ISSUE TITLE
Strapi with Mysql unique setting in model is not creating unique in DB for fields

### ISSUE THREAD

**Issue by srinair80** [strapi/strapi#4466] opened 2019-11-06 19:20 UTC
**Describe the bug**
As an admin when I am creating a new document and added a filed as unique it creates unique setting in model but its actually not unique in mysql DB.

**Steps to reproduce the behavior**
1. Go to 'content type builder'
2. Click on 'add content type finish the wizard to go to create fields'
3. Click on add field as string and in advanced mark the field as unique 
4. Save and check the corresponding model settings and verify the unique setting ""unique": true,"
5. save and restart server 
6. go to content type and add same data twice .

**Expected behavior**
An exception should say duplicate
**Actual**
No error but it save two records and in mysql unique is not marked for the field

**System**
- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: v3.0.0-alpha.26.2
- Database: Mysql
- Operating system: ubuntu 16.04 -- AWS EC2
- Mysql Version : mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper

**Comment by derrickmehaffy** [comment] 2019-11-06 19:46
@srinair80 Alpha versions are no longer supported only beta. The issue is known with beta and will be addressed. For now you would need to manually add the unique constraints.

Marking as closed as this was opened as an Alpha issue

**Closed by derrickmehaffy** 2019-11-06 19:46 UTC
