### ISSUE TITLE
Can not see all app pages on the first server load 

### ISSUE THREAD

**Issue by Marc-Roig** [strapi/strapi#20448] opened 2024-06-06 09:13 UTC
### Required System information

- Node.js version: v20.12.2
- NPM version: 10.5.0
- Strapi version: 5.0.0-beta.9
- Database: SQLite
- Operating system: N/A
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After creating a new strapi app, I am only seeing the following navbar links:
<img src="https://github.com/strapi/strapi/assets/20578351/461a7a83-547d-48f4-84f9-6e23306d48f1" height="200"> 

Content Type Builder, Media Builder, and Marketplace are not available in the navbar.

Only when I restart the server and reload the admin, I do see the rest of links available:

<img src="https://github.com/strapi/strapi/assets/20578351/4acb1c10-ac9d-4b6a-a6b5-86b8dfb730d6" height="400">

### Steps to reproduce the behavior

1. Create a new strapi app
2. Open localhost:1337/admin and see missing navbar links
3. Restart the terminal app
4. Open localhost:1337/admin and see the missing links appear again.

**Comment by Eventyret** [comment] 2024-06-07 11:18
Unable to confirm this in when creating a new v5 beta-9
I get this


![Image](https://github.com/strapi/strapi/assets/977232/f85e628c-732e-4f52-8959-638cb2d8e8b0)


Tested in:
- incognito mode
- Normal browser

But I think it is possible to replicate if you login with a user that does not have all privileges, then out again then in with an admin

**Comment by Marc-Roig** [comment] 2024-06-10 08:24
I was testing this using the internal strapi monorepo examples, so maybe it's only an issue there

**Comment by Simran-B** [comment] 2024-06-14 10:13
Seems like a duplicate of #20332

**Closed** 2024-06-20 08:32 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:admin, version: 5
