### ISSUE TITLE
Media library images not showing - possible CORS issue?

### ISSUE THREAD

**Issue by Solero007** [strapi/strapi#11867] opened 2021-12-10 01:17 UTC
## Bug report
Media images not showing in admin area, media library 

### Describe the bug
I'm using Digital Ocean spaces for a cdn, but the images aren't showing in the library after save. It's committing them to the DO and is viewable in the front end app.   

### Screenshots
![image](https://user-images.githubusercontent.com/26302508/145500954-8d2d0e77-59b5-4505-a717-17ff3473717c.png)
![image](https://user-images.githubusercontent.com/26302508/145500733-220c35bd-787e-4e84-bfed-bb79177b1bde.png)
![image](https://user-images.githubusercontent.com/26302508/145500624-d084037f-5478-4f7b-9683-d20a3ed1ee9f.png)
![image](https://user-images.githubusercontent.com/26302508/145500828-0cb67540-99fe-4ef5-a6f5-6abb235a0554.png)

UPDATE
it's possble it's to do with the "self" security policy on external providers. how do you allow it?

**Comment by ihmpavel** [comment] 2021-12-10 04:25
Hi, that looks same as https://github.com/strapi/strapi/issues/11837

You should check new [documentation](https://github.com/strapi/strapi/blob/master/packages/providers/upload-aws-s3/README.md#security-middleware-configuration) to allow CSP.

**Comment by derrickmehaffy** [comment] 2021-12-10 04:34
Exactly as @ihmpavel stated, it's in the docs and in the READMEs of the providers in the repo (npm readmes will be updated when we release v4.0.1)

Closing as intended

**Closed by derrickmehaffy** 2021-12-10 04:34 UTC

**Comment by Solero007** [comment] 2021-12-10 07:45
thank you!
