### ISSUE TITLE
GraphQL abstract type polymorphic relations

### ISSUE THREAD

**Issue by ThomasMcFarlane** [strapi/strapi#4145] opened 2019-09-30 15:20 UTC
**Describe the bug**
The following error occurs when attempting to query a polymorphic field in GraphQL:

```graphql
Abstract type Morph must resolve to an Object type at runtime for field Page.blocks with value { inputs: [[ObjectID]], _id: { _bsontype: \"ObjectID\", id: <Buffer 5d 91 c4 9f 81 3b 4b 0b 8e 76 f1 4d> }, createdAt: {}, updatedAt: {}, meta: { event_id: \"my_id\" }, action: \"event_registration\", _type: \"\", id: \"5d91c49f813b4b0b8e76f14d\" }, received \"undefined\". Either the Morph type should provide a \"resolveType\" function or each possible type should provide an \"isTypeOf\" function.
```

**Steps to reproduce the behavior**
1. Setup a polymorphic relationship
```json
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "page",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "title": {
      "type": "string"
    },
    "blocks": {
      "collection": "*"
    }
  }
}
```
2. Go to 'http://localhost:1337/graphql'
3. Run... 
```graphql
query {
  pages{
    blocks {
      ... on Form{
        _id
      }
    }
  }
}
```

**Expected behavior**
The response should show the associated Form record with the Id field.

**Screenshots**
![image](https://user-images.githubusercontent.com/7033707/65891791-0da81280-e39d-11e9-928d-e1d0ccea1d90.png)
Data comes back in REST:
![image](https://user-images.githubusercontent.com/7033707/65891817-1993d480-e39d-11e9-9ea6-12cad84d6025.png)

**System**
- Node.js version: 10.16.3
- NPM version:6.9.0
- Strapi version:3.0.0-beta.16.5
- Database: MongoDB
- Operating system: macOS Mojave

**Additional context**
The issue appears to be due to the "kind" field not existing on the record. The workaround for this is to save the kind field on the Header/Form in the DB which isn't ideal.
This should, really, come from the already populated "kind" property on the reference field.

**Comment by lauriejim** [comment] 2019-10-02 16:18
Hello @ThomasMcFarlane !
Can you also give me another model you have related to the Page model.

**Comment by ThomasMcFarlane** [comment] 2019-10-02 18:05
Hey @lauriejim 
This is an example of the Form model:
```json
{
  "connection": "default",
  "collectionName": "form",
  "info": {
    "name": "form",
    "description": ""
  },
  "options": {
    "timestamps": [
      "createdAt",
      "updatedAt"
    ]
  },
  "attributes": {
    "action": {
      "required": true,
      "enum": [
        "event_registration",
        "portal_submission"
      ],
      "type": "enumeration"
    },
    "meta": {
      "type": "json"
    },
    "inputs": {
      "collection": "input"
    }
  }
}
```

**Comment by lauriejim** [comment] 2019-10-03 11:38
In your **Form** model, you don't have relations with **Page**.
It looks weird for me 🤔

Can you make sure you followed [this example](https://strapi.io/documentation/3.0.0-beta.x/guides/models.html#relations) to have a correct relation model definition.

Thank you.

**Comment by ThomasMcFarlane** [comment] 2019-10-08 09:01
@lauriejim how do you store data in the `blocks` field on the Page in this instance?
I cannot create any records like this due to this error: https://github.com/strapi/strapi/issues/4147

**Comment by derrickmehaffy** [comment] 2019-10-08 09:19
@lauriejim it looks like a manyWay morph relationship? which I don't think is possible?

**Comment by emahuni** [comment] 2019-10-15 16:16
I once asked about this on Slack if you remember @derrickmehaffy. I bumped into the same issue again today.

In this case it is a model defined by Strapi Upload Plugin itself. 
```graphql
query morphQ {
  files {
    id
    related {
      ...on UsersPermissionsMe {
        id
      }
    }
  }
}

```

So maybe @lauriejim you can use that info to understand what's going on since you understand that model better.

**Comment by emahuni** [comment] 2019-10-15 16:32
If you look at the schema you should quickly see that it is morphing to all possible types in the system using one union type: `Morph`;
```graphql
union Morph = Account | Address | Call | Campaign...
```

and then, per instance, the `UploadFile` type does this: 

```graphql
type UploadFile {
  created_at: DateTime!
  ext: String
  hash: String!
  id: ID!
  mime: String!
  name: String!
  provider: String!
  public_id: String
  related(limit: Int, sort: String, start: Int, where: JSON): [Morph]
  sha256: String
  size: String!
  updated_at: DateTime!
  url: String!
}
```

So now, the problem that's happening here seems to be that the Graphql system is unable to infer the correct type to morph to when trying to cast the data against the correct model/type because of missing type resolving function according to that error:

```js
 Either the Morph type should provide a "resolveType" function or each possible type should provide an "isTypeOf" function
```

I have no idea where that is supposed to be done, but it is missing. IMO it's somewhere during model -> type resolvers definition somewhere... take this with a grain of salt, I am trying to understand something I have no idea of using the above info. 

I have searched the web about this and it seems unions are something that are not fully covered yet and that info might be scarce. I am sure someone here should be able to figure this out though. This is critical coz Strapi offers polymorphic relations that are actually unusable with Graphql becoz of this.

**Comment by emahuni** [comment] 2019-10-15 16:49
Ok I was searching wrong I guess

https://stackoverflow.com/questions/53078554/how-to-implement-istypeof-method

this is the solution to that problem

**Comment by darron1217** [comment] 2020-11-22 09:49
Is there any progress on this issue?
Currently strapi's schema accepts only `ID` type on polymorphic relation. Which should accept `refId`,`ref`,`source`,`field`.

**Comment by derrickmehaffy** [comment] 2020-11-23 14:28
@darron1217 neither our REST nor GraphQL support filtering on polymorphic relations, it's something we are looking at for v4.

No movement yet.

**Comment by derrickmehaffy** [comment] 2020-11-23 14:31
Closing this in favor of: https://github.com/strapi/strapi/issues/8651

**Closed by derrickmehaffy** 2020-11-23 14:31 UTC
Labels: severity: low, source: plugin:graphql, type: enhancement

**Comment by darron1217** [comment] 2020-11-24 02:02
@derrickmehaffy 
Just to be clear, I wasn't talking about filtering polymorphic relationships.
I also think filtering would be difficult. Just mutation(create/update/delete) support would be nice.

**Comment by derrickmehaffy** [comment] 2020-11-24 02:42
@darron1217 we are planning a massive rework of the entire graphql plugin so I would imagine this would like be part of it. Just trying to cut down on the total number issues about a specific topic. Most likely I'll be closing out all of the GraphQL issues and merging them into our global tracking issue for GraphQL as they will be part of the refactoring.

**Comment by emahuni** [comment] 2020-11-24 12:03
Hey Derrick, Pliz share the ref here. Want to contribute to the issue too.

**Comment by derrickmehaffy** [comment] 2020-11-24 15:31
@emahuni right now the issue is only about performance, but when we fix the performance issues, it will also likely trigger a refactoring of the entire plugin.

This is the tracking issue: https://github.com/strapi/strapi/issues/8552
