### ISSUE TITLE
Unable to access admin panel  with user with Custom Role.

### ISSUE THREAD

**Issue by aynomjb** [strapi/strapi#5036] opened 2020-01-21 07:13 UTC
**Describe the bug**
Created an author role, created an user assigned author role. Unable to login via admin panel.
While logging in showing  "Identifier or password invalid."

**System**
- Node.js version: v10.15.3
- NPM version:6.4.1
- Strapi version:  Strapi v3.0.0-beta.18.3
- Database: SQLite
- Operating system:

**Additional context**

**Comment by derrickmehaffy** [comment] 2020-01-21 07:42
@aynomjb Normal users cannot access the the AdminUI no matter what role they have. API users (REST/GraphQL) and Admin users are split.  You can see more in this blog post: https://strapi.io/blog/why-we-split-the-management-of-the-admin-users-and-end-users?redirectPage=3

Eventually there will be a feature to have different role types for the adminUI but the ETA isn't until Q2 2020 and this may be a paid feature. You can see this feature on the product board: https://portal.productboard.com/strapi/1-public-roadmap/c/8-administrators-roles-permissions

Source for possible paid (this isn't confirmed yet): https://strapi.io/blog/top-10-questions-to-strapi-ceo?redirectPage=1

```
How do you plan to build a sustainable business if Strapi is Open Source?
Strapi is and will always be open-source and free. That being said, we’re currently looking at different business models including a SaaS offering hosted by Strapi and a Self-Managed Enterprise version for customers who would like to host their own instances on-premises or in the cloud.

Our enterprise version will include features that are specifically tied to enterprise use-cases such as internationalization, Single Sign-On, Role-Based Access Control, etc.
```

Marking as closed as this is not a bug and is intended.

**Closed by derrickmehaffy** 2020-01-21 07:42 UTC

**Comment by mizvyt** [comment] 2020-07-08 09:21
@derrickmehaffy, sorry for pulling an old issue to the daylight, but it's already almost Q3 2020 and we don't have any admin panel user roles. I am particularly interested in the predefined "author" or "editor" role in the CE of Strapi as planned. Do you have an updated roadmap for this? Can we expect it to be issued any time soon? It's a pretty important issue given that the only way to easily edit content for content managers right now is by logging in as administrators, and they have full control over the dashboard, meaning they may break the actual API :-)

**Comment by derrickmehaffy** [comment] 2020-07-08 13:07
It's currently in testing, I believe they plan to release it very soon.
