### ISSUE TITLE
content-manger, i18n other plugins, don't respect admin.url setting, witch results unusable unified routing

### ISSUE THREAD

**Issue by antokhio** [strapi/strapi#14621] opened 2022-10-13 14:19 UTC
## Bug report
Hi, i've been digging around the Subfolder-Unified routing, and came across issue preventing, admin panel to work in such scenario 
so: 
/config/admin.ts
```ts
export default ({ env }) => ({
  auth: {
    ...
  },
  url: env("PUBLIC_ADMIN_URL", "/admin/admin"),
});
```
/config/server.ts
```ts
export default ({ env }) => ({
  host: env("HOST", "0.0.0.0"),
  port: env.int("PORT", 1337),
  app: {
    keys: env.array("APP_KEYS"),
  },
  url: env("URL", "example.com"),
});
```
nginx block: (inrelevant)
```nginx
    location /admin/ {
        proxy_pass http://strapi/admin/;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_pass_request_headers on;
    }
```
Browser Network/XHR
![image](https://user-images.githubusercontent.com/1254168/195622016-2280fc87-6702-4c3e-9142-d0290b7e835a.png)

the list of requested routes: 
```python
admin/project-type
admin/renew-token
admin/init
admin/telemetry-properties
admin/users/me/permissions
admin/users/me

// and then, ops' we don't respect admin url:
i18n/locales
content-manager/components
content-manager/content-types
```

### Required System information
- Strapi version: 4.4.x

full list `strapi routes:list`

**Comment by gu-stav** [comment] 2022-10-18 11:21
Closing this as duplicate of https://github.com/strapi/strapi/issues/13889

**Closed by gu-stav** 2022-10-18 11:21 UTC
