### ISSUE TITLE
"required field" is not enforced on REST API

### ISSUE THREAD

**Issue by thematrixdev** [strapi/strapi#17912] opened 2023-09-04 06:30 UTC
### Required System information

- Node.js version: 18.17.1
- NPM version:
- Strapi version: 4.13.1
- Database: MySQL 8
- Operating system: Ubuntu 22.04
- Is your project Javascript or Typescript: Typescript

### Steps to reproduce the behavior

1. In "Content-Type Builder", create a collection with a "Media" field marked as "required field"
2. Save and restart
3. POST to the REST API with empty data. It returned HTTP 200. A record was saved.
(It works when creating a new record on UI)

### Expected behavior

Expecting to show an error prompting to upload a file. Do not save a new record.

### Screenshots

![image](https://github.com/strapi/strapi/assets/19472561/ac971e51-e520-4346-bf36-3c0dfffa88cb)
![image](https://github.com/strapi/strapi/assets/19472561/8a708aec-a84f-4180-a450-ff22223a6a30)
![image](https://github.com/strapi/strapi/assets/19472561/178e5dd2-9e4c-4ea2-bbc8-dff2391d20d5)
![image](https://github.com/strapi/strapi/assets/19472561/da3c4efc-a39b-47ce-895d-c08d21a38587)
![image](https://github.com/strapi/strapi/assets/19472561/5b5eadf6-fc91-4441-98f9-3df5cf753882)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment] 2023-09-05 16:47
Since media fields are relations this is a duplicate of: https://feedback.strapi.io/customization/p/specify-relation-column-as-required

**Closed by derrickmehaffy** 2023-09-05 16:47 UTC
