### ISSUE TITLE
Strapi 5.1.0 - After each login, the system remains stuck on the loading screen indefinitely until the browser cache is cleared or the page is refreshed multiple times using F5.

### ISSUE THREAD

**Issue by hoqkhanh** [strapi/strapi#21945] opened 2024-10-23 07:02 UTC
### Required System information

- Node.js version: 18
- NPM version: 10.7
- Strapi version: 5.1.0 
- Database: Mysql
- Operating system: Ubuntu
- Is your project Javascript or Typescript: JS

### Describe the bug

After each login, we are unable to access the CMS as it remains stuck on the loading screen indefinitely. This issue persists until we either clear the browser cache or repeatedly refresh the page using F5.
### Steps to reproduce the behavior

1. Go to the login page
2. Login with the CMS account
3. Loading is forerver
4. Have to clear the browser cache and hard reload to access the CMS

### Expected behavior

We can access the cms and don't have to clear the browser cache each login

### Screenshots

<img width="1707" alt="Screenshot 2024-10-23 at 13 51 30" src="https://github.com/user-attachments/assets/e1af4a9a-2e43-46a8-9d77-ea465954886f">

Online video: https://jumpshare.com/s/gWzBFMjIO6KabjlU3hwd

Video https://github.com/user-attachments/assets/3e221cd9-2846-4477-b274-cb1a31501ae3

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by eruiz-impact** [comment] 2024-10-24 15:49
I am getting the same issue

**Comment by zmdavis15** [comment] 2024-10-25 21:01
Same issue on Strapi 5.1.1 on Ubuntu 24.04.1 LTS using Sqlite database

**Comment by bolg55** [comment] 2024-10-31 16:51
Related to #21811

**Comment by artsiompeshko** [comment] 2024-11-18 20:29
+1 here.

**Comment by derrickmehaffy** [comment] 2024-11-22 05:02
Fairly certain this is a duplicate of https://github.com/strapi/strapi/issues/21811

**Closed** 2024-11-22 05:03 UTC
Labels: issue: bug, severity: high, status: duplicate, flag: EE, version: 5
