### ISSUE TITLE
Issue with dynamic zone.

### ISSUE THREAD

**Issue by toxicity1985** [strapi/strapi#14968] opened 2022-11-23 07:50 UTC
### Required System information

- Node.js version: v16.14.0
- NPM version: 8.3.1
- Strapi version: 5.4.2
- Database: MariaDB
- Operating system: Debian

### Describe the bug

Impossible to edit a single-type with dynamic zone and content inside

### Steps to reproduce the behavior

-> Create a dynamic zone in a single-type. 
-> Add content in it. 
-> Save and then reopen the content and it does not appear. But i can see the content through the debug bar( the api call).

### Screenshots

![image](https://user-images.githubusercontent.com/708329/203495210-7e3e82c9-a4b0-4f50-9bcb-38957370d219.png)µ

**Comment by toxicity1985** [comment] 2022-11-28 15:15
Hello. 

I'm trying to debug myself to find what's wrong. I just found that the componentPath are not ok.  Do you know where that value is set ?

![image](https://user-images.githubusercontent.com/708329/204313095-f7a2bade-80a3-4bb1-a6f1-931d394942b3.png)

**Comment by joshuaellis** [comment] 2022-11-28 15:40
can you share your schemas and component schemas? This will help debug when someone is available.

**Comment by toxicity1985** [comment] 2022-11-28 17:07
Hi,

It's difficult to share some schema but I think i undestand the issue. We have some component who have relations with field name "content". The relation is not the same between the components. In the screenshot, you can see what happens.

![image](https://user-images.githubusercontent.com/708329/204338501-28fba680-4970-4a7e-98cf-a98a452cb8ef.png)

**Comment by toxicity1985** [comment] 2022-12-02 13:55
I update strapi to the last version and issue is there. I can send you in private the component, type and single type defined.

**Comment by joshuaellis** [comment] 2022-12-08 17:11
Hey @toxicity1985, we're still unable to reproduce your error, we've edited our functions to remove this `undefined` in the paths issue, but are currently unable to make the page "blank".

I didn't fully understand this comment:

> We have some component who have relations with field name "content". The relation is not the same between the components. In the screenshot, you can see what happens.

Can you try to re-explain this? potentially which schema examples? Otherwise to address this issue we would need you to supply a reproducible example, this might be quicker tbf.

**Comment by mirkods** [comment] 2022-12-13 13:44
Hi all, I'm experiencing the same issue so I add some information to help you all in debugging this problem.

I have the following schema called learning unit

<img width="1385" alt="Screenshot 2022-12-13 at 14 32 41" src="https://user-images.githubusercontent.com/2368194/207336017-3e03ab49-cccd-4625-bea9-d3570c25c927.png">

Then I have a component Unit that has a one to many relation with my learning unit schema

<img width="1411" alt="Screenshot 2022-12-13 at 14 33 02" src="https://user-images.githubusercontent.com/2368194/207336528-d54259f3-9dc0-4893-81b4-b6a383283a99.png">

At the end I have another schema called learning module that has Unit as a repeatable component

<img width="1363" alt="Screenshot 2022-12-13 at 14 36 24" src="https://user-images.githubusercontent.com/2368194/207337519-77e99e74-14b2-4f84-93b1-fb675e106253.png">

The problem mentioned in this issue is present is in the learning module objects. Basically when I create a new entry I correctly populate the relations in the repeatable component and I save it but when I refresh the page the relations are not visible anymore in the entry page while I can see them in main table of the schema.

Here a quick video:


https://user-images.githubusercontent.com/2368194/207341568-00d44b71-0d1b-4d39-85ac-cbe6732f0ee5.mov


Please, let me know if the problem is clear or if you need more information.

Best,
Mirko

**Comment by ronronscelestes** [comment] 2022-12-14 13:36
hi @mirkods thank you for sharing this, I will try to replicate this issue
I have some questions: 
- with what Strapi version are you experiencing this issue?
- did you create those CT/components with another Strapi versions?
- could you add a screenshot of the network `GET` request of your entity to make sure the front receives well your rep component data? example in the screenshot :
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/71838159/207609459-2ff69147-973e-4eb6-b3bf-f54def769b40.png">


in the meantime, #15139 is included in today's release, when the new version is out could you try updating your project to see if you're still experiencing this issue? 🙏

**Comment by mirkods** [comment] 2022-12-14 14:58
Hi @ronronscelestes,

- Strapi version 4.5.3
- Yes, probably with some version 4.4.x. I also tried to rename this component in order to force model update on the new verision
- Here the screenshot. As you can see the frontend receives the data correctly

<img width="1799" alt="Screenshot 2022-12-14 at 15 53 03" src="https://user-images.githubusercontent.com/2368194/207628893-b655b289-6043-4c11-9968-763d4a380f20.png">

**I confirm that with the version 4.5.4 I'm still having this problem.**

Mirko

**Comment by ronronscelestes** [comment] 2022-12-14 17:11
hi again @mirkods 
I spent some time trying to reproduce this issue locally with the provided information you gave but I'm not not running into any issues:

![image](https://user-images.githubusercontent.com/71838159/207660725-da8552ce-825e-4a5c-b8a7-0b23bf275c8e.png)
![image](https://user-images.githubusercontent.com/71838159/207660777-b9423f07-0b90-4b3d-a5f4-0ab683b39f28.png)
 
could any of you share a minimal viable reproduction of the issue, so we could reproduce it and find a solution? 
[this](https://github.com/strapi/strapi/issues/14993) could help you to find the best approach 😊

**Comment by mirkods** [comment] 2022-12-20 21:07
Hi @ronronscelestes,

### Bug report

Schemas that use repeatable components that has a relation inside are saved correctly but the dashboard doesn't show the relations anymore after saving the entry.

### System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.5.4
- Database: pg/ postgresql dev database locally
- Operating system: Mac

### Steps to reproduce the behavior

1. Download the zip file here (https://github.com/strapi/strapi/files/10272584/bug.zip)
2. Create locally a postgres db called `strapi_bug` with a schema inside it called `strapi`
3. Create a full access user for this database with username `user` and password `password` (we are reproducing locally the ./config/database.js setup)
4. Unzip the file and run `npm i` inside the folder and the `npm run develop`
5. With the content manager create one or more entry in the collection `unit`
6. Now create an entry in the collection module and in the units field add a relation with one of the unit created before
7. Save the module entry
8. Now if you refresh the page the relation disappear while it will be visible in the main collation table 

### Screen Recording

Here a screen recording of the steps described above 
https://user-images.githubusercontent.com/2368194/208766481-668bb02d-ffc7-46c5-83fd-ea370a13c5e5.mov

Hope that now you guys are able to reproduce the bug correctly.

Best,
Mirko

**Comment by marcosantonocito** [comment] 2022-12-21 05:04
Hello @ronronscelestes,

I tried reproducing this issue on Strapi Demo (https://strapi.io/demo), and it's also not working there.

### Steps to reproduce the behavior
1. Create a new live demo on [Strapi Demo](https://strapi.io/demo) and log into it
2. Create a new collection called "ingredient" and add a short text field called "name". Save it.
3. Create a new component called "relation" and add it to one category. Add two fields inside this component: a short text field called "name" and a one-to-many relation field to the collection "ingredient". Save it.
4. Create a new collection called "recipe, add a short field called "name" and a repeatable component named "ingredients". The repeatable component has to be the one created in point 3. Save it.
5. Enter the Content Manager section and create some ingredients. Save and publish each of them. 
6. Create a recipe in the Content Manager section and add some ingredients. Save. 

After saving, you will not see any of the ingredients added on point 6, but if you return to the recipes list, you will see the number of added ingredients.

**Comment by ronronscelestes** [comment] 2022-12-22 18:29
thank you @marcosantonocito and @mirkods for the very helpful indications - we found the issue, you can read more about it in the PR that I have opened and linked to this issue!

**Comment by mirkods** [comment] 2022-12-23 08:06
Thanks @ronronscelestes.

Are you able to provide us an estimate time for the release of this fix?

Mirko

**Comment by ronronscelestes** [comment] 2022-12-23 10:59
@mirkods I think it should be merged for the next release on 28th of December 🙂

**Closed** 2022-12-27 08:29 UTC
Labels: issue: bug, severity: medium, source: core:content-manager, status: pending reproduction
