### ISSUE TITLE
 'find' API returns empty data.

### ISSUE THREAD

**Issue by huamurui** [strapi/strapi#15582] opened 2023-01-26 03:05 UTC
### Required System information

- Node.js version: 16.13
- NPM version: yarn1.22
- Strapi version: 4.6.0
- Database: sqlite3
- Operating system: windows

### Describe the bug

The 'find' does not work, it returns  empty data.
![图片](https://user-images.githubusercontent.com/60086749/214747318-61cf6fe1-8346-44f2-bae0-b40d7a734b98.png)

I have added the content, and 'findOne' is ok. 
![图片](https://user-images.githubusercontent.com/60086749/214747406-75e46669-a86f-4c84-8666-d2da3a45bd69.png)

![图片](https://user-images.githubusercontent.com/60086749/214747585-aca546ec-97b5-43ab-b0a7-3e8ca767f671.png)

### Steps to reproduce the behavior

I am following the [tutorial](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#get-entries) to learn to use strapi, but can't get the same result in the tutorial.

### Expected behavior

I am not sure if this is a bug...

I want to know if there's a step in the docs I'm missing? How to get the same result in the tutorial?
![图片](https://user-images.githubusercontent.com/60086749/214749760-3de819cb-105f-4fc2-835a-9407ee1a0ab7.png)

### Code snippets

here is a reop I met the problem, but I'm not sure if this will help...
https://github.com/huamurui/strapi-0126

**Comment by Convly** [comment] 2023-01-26 09:29
Hi. Your entry is in draft mode and thus won't appear without adding a `publicationState` filter or publishing it.
You can see it as in your `findOne` request, `publishedAt` is `null`.

Closing as it's not a bug.

**Closed by Convly** 2023-01-26 09:29 UTC
