### ISSUE TITLE
Error Viewing Last Page of Media Gallery

### ISSUE THREAD

**Issue by MakingStuffs** [strapi/strapi#7160] opened 2020-07-24 13:28 UTC
**Describe the bug**
When I am browsing the media gallery for a component clicking the last pagination button causes the empty gallery screen to pop up and an error. For example: There are 10 pages and I click the button for page 10.

It also logs the following errors in the console: 

```
main.f62cb3ef.chunk.js:1 GET http://localhost:1337/upload/files?_limit=10&_start=120&_sort=updated_at%3ADESC 500 (Internal Server Error)

react_devtools_backend.js:2273 Error: Internal Server Error
    at main.f62cb3ef.chunk.js:1
```

**Steps to reproduce the behavior**

1. Make a component with a media field with the following settings:
Single or Multiple: Multiple Media
Media Types: Images
Required: True
2. Add an entry and populate the media field with enough images to have multiple pages (there are 13 in mine)
3. Save the entry
4. Refresh the page
5. Click the pencil to edit the media field
6. Click the back button in the top left corner of the modal which appears
7. Scroll to the bottom and click the last pagination button which is visible -- the highest number

**Expected behavior**
Display the images on the page otherwise only show pagination buttons for pages which exist.

**Screenshots**
<img width="1280" alt="Screenshot 2020-07-24 at 13 19 06" src="https://user-images.githubusercontent.com/33229318/88395837-97f0b580-cdb9-11ea-98cb-cd7f5e581d18.png">

**System**

- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.5
- Database: GraphQL
- Operating system: Mac OS Catalina 10.15.6
- Browser: Brave Version 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)

**Comment by soupette** [comment] 2020-07-28 12:40
Hi @MakingStuffs I am not able to reproduce your bug can you try to upgrade your app?

**Comment by MakingStuffs** [comment] 2020-07-29 07:04
Hi @soupette Do you mean run npm update?

**Comment by MakingStuffs** [comment] 2020-07-30 19:41
@soupette I can confirm that the issue is still present in the most up to date version of Strapi. 

I can add that it seems to happen with any media browser when adding content. So, if I go to set the thumbnail on, for example, an article, and I want to get an image which exists in my database but is on the last page of the pagination it will fail.

**Comment by soupette** [comment] 2020-08-03 06:55
Thanks @MakingStuffs I'll take a look at it

**Comment by soupette** [comment] 2020-08-04 09:22
@MakingStuffs can you show me the error you are receiving in the console and or server?

**Comment by MakingStuffs** [comment] 2020-08-04 10:45
@soupette Sure, the only error which is displayed on the UI is as above and the errors on the console are 500 errors, as follows: 

```
/upload/files?_limit=10&_start=30&_sort=updated_at%3ADESC:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Error: Internal Server Error
    at main.cc260c3d.chunk.js:1
```

**Comment by soupette** [comment] 2020-08-04 12:04
and what about your backend? Do you have any error in the terminal?

**Comment by MakingStuffs** [comment] 2020-08-04 16:10
Sorry mate I should have added that, heroku logs have the following: 
```
2020-08-04T10:41:32.497149+00:00 app[web.1]: [2020-08-04T10:41:32.497Z] error Error: The target polymorphic type "articles" is not one of the defined target types
2020-08-04T10:41:32.497165+00:00 app[web.1]: at Object.morphCandidate (/app/node_modules/bookshelf/lib/helpers.js:136:13)
2020-08-04T10:41:32.497167+00:00 app[web.1]: at /app/node_modules/bookshelf/lib/eager.js:52:15
2020-08-04T10:41:32.497168+00:00 app[web.1]: at /app/node_modules/lodash/lodash.js:13401:38
2020-08-04T10:41:32.497168+00:00 app[web.1]: at /app/node_modules/lodash/lodash.js:4905:15
2020-08-04T10:41:32.497169+00:00 app[web.1]: at baseForOwn (/app/node_modules/lodash/lodash.js:2990:24)
2020-08-04T10:41:32.497169+00:00 app[web.1]: at Function.mapValues (/app/node_modules/lodash/lodash.js:13400:7)
2020-08-04T10:41:32.497170+00:00 app[web.1]: at EagerRelation.morphToFetch (/app/node_modules/bookshelf/lib/eager.js:51:28)
2020-08-04T10:41:32.497170+00:00 app[web.1]: at EagerRelation.eagerFetch (/app/node_modules/bookshelf/lib/eager.js:25:19)
2020-08-04T10:41:32.497170+00:00 app[web.1]: at EagerRelation.<anonymous> (/app/node_modules/bookshelf/lib/base/eager.js:67:14)
2020-08-04T10:41:32.497171+00:00 app[web.1]: at EagerRelation.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2020-08-04T10:41:32.497171+00:00 app[web.1]: at EagerRelation.fetch (/app/node_modules/bluebird/js/release/method.js:15:34)
2020-08-04T10:41:32.497172+00:00 app[web.1]: at /app/node_modules/bookshelf/lib/eager.js:95:73
2020-08-04T10:41:32.497172+00:00 app[web.1]: at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2020-08-04T10:41:32.497173+00:00 app[web.1]: at Function.Promise.attempt.Promise.try (/app/node_modules/bluebird/js/release/method.js:39:29)
2020-08-04T10:41:32.497173+00:00 app[web.1]: at EagerRelation._eagerLoadHelper (/app/node_modules/bookshelf/lib/eager.js:82:23)
2020-08-04T10:41:32.497174+00:00 app[web.1]: at Sync.<anonymous> (/app/node_modules/bookshelf/lib/eager.js:31:31)
2020-08-04T10:41:32.497515+00:00 app[web.1]: [2020-08-04T10:41:32.497Z] debug GET /upload/files?_limit=10&_start=30&_sort=updated_at%3ADESC (93 ms) 500
2020-08-04T10:41:32.499963+00:00 heroku[router]: at=info method=GET path="/upload/files?_limit=10&_start=30&_sort=updated_at%3ADESC" host=resinfusion.herokuapp.com request_id=ef494514-5e2d-4b6e-b3f9-f5f00168a76f fwd="91.125.142.204" dyno=web.1 connect=1ms service=101ms status=500 bytes=387 protocol=https
```

**Comment by soupette** [comment] 2020-08-05 07:53
I see it's not a front-end bug then it's related to one of your file that is linked to a collection that seems to not be existing. I ping @alexandrebodin @petersg83 about it.

**Comment by MakingStuffs** [comment] 2020-08-06 06:12
> I see it's not a front-end bug then it's related to one of your file that is linked to a collection that seems to not be existing. I ping @alexandrebodin @petersg83 about it.

Very weird as I am not specifying the file. I am just clicking the button to view the last page of the library of files which were uploaded using the UI

**Comment by alexandrebodin** [comment] 2020-08-06 10:28
You have files in your db linked to content types you have deleted in the meantime. You will need to run a cleanup on your side as we do not provide theses utils yet :)

**Comment by MakingStuffs** [comment] 2020-08-13 09:48
@alexandrebodin Ok any idea why this might have happened? I have only ever deleted media through the UI. When you say run a cleanup can you elaborate a bit please? Thanks mate :)

**Comment by alexandrebodin** [comment] 2020-10-15 14:26
@MakingStuffs for example:

- you created a Content Type A with images.
- Then create some Content Type A entries with images.
- Then deleted the Content Type A.

Right now the data is not clear on Content Type deletion as you might have made a mistake or want to keep the data to migrate it for example. This means Images are still linked to a "ghost" Content Type that don't exist in anymore. The SQL lib we use throws erors when trying to populate the images relations because the Content Type is not decalred anymore. We are going to work on a fix soon

**Comment by derrickmehaffy** [comment] 2020-11-09 19:59
@gmourier can you provide any steps to reproduce this issue on a fresh project?

**Comment by gmourier** [comment] 2020-11-09 22:24
Yes, as i remember, i've got simple media field on a lot of model and i needed to change it to a more complex structure to be able to handle alt and caption for file in graphql since gatsby-source-strapi doesn't provide them. I've done that in a bulk task so i deleted media field on model instead of deleting media assets file before that and i've replaced it with a media component. On restart, i've got en error 500 on the assets media view. Thanks to @alexandrebodin, by digging the database, some rows related to the componens i've deleted were still here in upload_file_morph table.

**Comment by yuriduarte** [comment] 2020-12-01 13:48
I managed to solve this by accessing the database and clearing the **upload_file** table. This resolved the conflicts of the types of files that were excluded!

**Comment by derrickmehaffy** [comment] 2020-12-01 19:46
@alexandrebodin didn't we fix this in a recent release?

> deleted media fields on my models instead of deleting media assets file

**Comment by M-erb** [comment] 2020-12-14 23:38
I think this is the same thing happening to me. We are using GIT and switching to a branch where a content type does not exist yet will produce these same symptoms as described here.

Again its when in branch "A" you create a content type. Then switch to branch "B" you will see these same errors.

Makes using GIT with a common database between branches very difficult and therefore gets in the way of developing fast. I am having to create a new database and juggle them between branches.

**Comment by gasPoweredSticks** [comment] 2021-01-25 18:56
did anyone end up solving this? i'm currently having this issue but with the first page.

**Comment by lilaL** [comment] 2021-02-16 16:22
when using sqlite, this solved my issue!
`sqlite3 ./temp/data.db`
`sqlite> DELETE FROM upload_file_morph;`

**Comment by RyanMoreau** [comment] 2021-02-28 18:19
> when using sqlite, this solved my issue!
> `sqlite3 ./temp/data.db`
> `sqlite> DELETE FROM upload_file_morph;`

That worked, thank you!

**Comment by derrickmehaffy** [comment] 2021-12-22 20:08
should be fixed in v4

**Closed by derrickmehaffy** 2021-12-22 20:08 UTC
Labels: issue-type: bug, severity: low, status: confirmed, source: core:upload
