### ISSUE TITLE
Custom routing of method GET didn't work when place after route of findOne

### ISSUE THREAD

**Issue by ttpjb** [strapi/strapi#6961] opened 2020-07-10 04:35 UTC
**Describe the bug**
When place custom GET route after route of findOne, it return error 404

**Steps to reproduce the behavior**

1. Create a project with ```npx create-strapi-app my-project --quickstart```
2. Create a content-type by "Content-Type Builder" on admin page (eg. example)
3. Create a custom controller 
```javascript
  async test(ctx) {
    return ctx.send("OK");
  }
```
4. Add custom route with GET method after route of findOne
```json
    {
      "method": "GET",
      "path": "/examples/:id",
      "handler": "example.findOne",
      "config": {
        "policies": []
      }
    },
    {
      "method": "GET",
      "path": "/examples/test",
      "handler": "example.test",
      "config": {
        "policies": []
      }
    },
```
5. Enable route permission in admin page in public role
6. Send request ```GET localhost:1337/examples/test```

**Expected behavior**
It should return 
```
OK
```

**Screenshots of actual result**
![Image of error](https://i.ibb.co/kqQn133/bug.png)

**System**

- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.5
- Database: SQLite
- Operating system: Window10

**Additional context**
When change position of custom route to before ```/examples/:id```, it work fine.

**Comment by derrickmehaffy** [comment] 2020-07-10 05:09
This is intended, as each object within the routes array is executed in sequence, when it finds a match from the requested route and the routes array (matched via regex I believe) it will stop and run that controller.

When you passed `GET /examples/test` it believed that `test` was the ID. As you figured out moving that above the ID findOne it works, this is how you correctly add a new one.

Marking as closed as it's not a bug.

**Closed by derrickmehaffy** 2020-07-10 05:09 UTC
