### ISSUE TITLE
Cloned database create table statement error relation "strapi_migrations" already exists

### ISSUE THREAD

**Issue by sjoukedv** [strapi/strapi#13464] opened 2022-06-03 17:59 UTC
### Required System information

- Node.js version: v16
- NPM version: 6.14.16
- Strapi version: 4.1.12
- Database: Postgres 14
- Operating system: docker `node:16-alpine`

### Describe the bug

Server fails to start on `create table` statement, because relation already exists.

```
yarn run v1.22.18
$ strapi start
[2022-06-03 17:47:29.935] [34mdebug[39m: ⛔️ Server wasn't able to start properly.
[2022-06-03 17:47:29.940] [31merror[39m: create table "public"."strapi_migrations" ("id" serial primary key, "name" varchar(255), "time" timestamp) - relation "strapi_migrations" already exists
error: create table "public"."strapi_migrations" ("id" serial primary key, "name" varchar(255), "time" timestamp) - relation "strapi_migrations" already exists
at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
at TLSSocket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
at TLSSocket.emit (node:events:527:28)
at TLSSocket.emit (node:domain:475:12)
at addChunk (node:internal/streams/readable:315:12)
at readableAddChunk (node:internal/streams/readable:289:9)
at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Dropping the `strapi_migrations` table does not resolve the problem, but it gets thrown for another table.

### Steps to reproduce the behavior

1. Clone a database on a Postgres server, e.g. `create database <new-db> template <old-db>;`
2. Start Strapi instance pointing to the new database instead of the old one

This duplication is useful for e.g. staging environments.

### Expected behavior

Strapi to start properly and function the same using the new database.

### Code snippets

Tried the turning the creation/migration off with `settings.forceMigration: false`

```js
// path config/database.js
module.exports = ({ env }) => ({
    connection: {
      client: 'postgres',
      connection: {
        host: env('DATABASE_HOST', '127.0.0.1'),
        port: env.int('DATABASE_PORT', 5432),
        database: env('DATABASE_NAME', 'strapi'),
        user: env('DATABASE_USERNAME', 'strapi'),
        password: env('DATABASE_PASSWORD', 'strapi'),
        schema: env('DATABASE_SCHEMA', 'public'), // Not required
        ssl: false
      },
      debug: false,
    },
    settings: {
      forceMigration: false
    }
  });
   
```

**Comment by derrickmehaffy** [comment] 2022-06-03 18:16
I can't reproduce this exact bug but I've seen similar issues like this and I think we need to take a look at the "sanity check logic" to make sure it's actually using knex functions to check if a table and column exist first.

cc @alexandrebodin this is what I was talking about the last time we were chatting about the hash checking

**Comment by sjoukedv** [comment] 2022-06-04 15:03
> I can't reproduce this exact bug but I've seen similar issues like this and I think we need to take a look at the "sanity check logic" to make sure it's actually using knex functions to check if a table and column exist first.
> 
> cc @alexandrebodin this is what I was talking about the last time we were chatting about the hash checking

I just tried this with a fresh instance and there it does not occur. Let me know if I can provider further debug information. It's not possible to dump the database as it contains sensitive data.

**Comment by derrickmehaffy** [comment] 2022-06-04 17:32
> > I can't reproduce this exact bug but I've seen similar issues like this and I think we need to take a look at the "sanity check logic" to make sure it's actually using knex functions to check if a table and column exist first.
> > 
> > cc @alexandrebodin this is what I was talking about the last time we were chatting about the hash checking
> 
> I just tried this with a fresh instance and there it does not occur. Let me know if I can provider further debug information. It's not possible to dump the database as it contains sensitive data.

Can you try to dump the test db and import that and see if you get the same error?

**Comment by marcelorodcla** [comment] 2022-06-21 19:19
The same issue here

## Required System information
- Node.js version: v16.15.1
- NPM version: 8.12.2
- Strapi version: 4.2.0
- Database: PostgreSQL 12.11
- Operating system: Ubuntu 20.04.4 LTS

## Describe the bug
i had my db in google cloud, and i wanted my db running  in the same  server (vultr.com) where is strapi. After import my db (no issues) i have this error:
```
 npm run develop

> eratpedia@0.1.0 develop
> strapi develop

[2022-06-21 17:38:14.775] info: [slugify] graphql detected, registering queries
[
  {
    sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'strapi_core_store_settings' ],
    output: [Function: output]
  }
]
[
  {
    sql: 'select * from information_schema.tables where table_name = ? and table_schema = current_schema()',
    bindings: [ 'strapi_migrations' ],
    output: [Function: output]
  }
]
[
  {
    sql: 'create table "strapi_migrations" ("id" serial primary key, "name" varchar(255), "time" timestamp)',
    bindings: []
  }
]
[2022-06-21 17:38:14.882] debug: ⛔️ Server wasn't able to start properly.
[2022-06-21 17:38:14.882] error: create table "strapi_migrations" ("id" serial primary key, "name" varchar(255), "time" timestamp) - relation "strapi_migrations" already exists
error: create table "strapi_migrations" ("id" serial primary key, "name" varchar(255), "time" timestamp) - relation "strapi_migrations" already exists
    at Parser.parseErrorMessage (/var/www/ruarga/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/var/www/ruarga/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/var/www/ruarga/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/var/www/ruarga/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
 ```
i created a new db  instance in AWS and imported the same db and works. And in my local works well:
- Node.js version: v16.14.0
- NPM version: 8.3.1
- Strapi version: 4.2.0
- Database: PostgreSQL 12.9
- Operating system: Windows 10, WSL Ubuntu 20.04.4 LTS

**Comment by derrickmehaffy** [comment] 2022-06-30 16:33
Still unable to reproduce, I feel the issue here is likely a problem with the database dump. :thinking:

**Comment by derrickmehaffy** [comment] 2022-08-04 20:40
As no new information going to go ahead and close this but if someone can provide step by step instructions to reproduce from a fresh project please do let us know and we can reopen.

**Closed by derrickmehaffy** 2022-08-04 20:40 UTC
Labels: issue: bug, severity: low, status: can not reproduce, source: core:database

**Comment by greyaxis** [comment] 2022-08-09 09:56
still happening while deploying to google cloud

**Comment by tcherokee** [comment] 2022-08-15 04:06
I am also running into this error. I have tried dumping the DB using pg_dump and tableplus backup option neither worked. I don't mind sending over a copy of my db.

**Comment by tcherokee** [comment] 2022-08-15 05:28
Ok, so I noticed that the "strapi_migrations" table was empty, so I deleted it, just to see what would happen. Strapi recreated the "strapi_migrations" table and then moved on to try to create the "strapi_database_schema" and then complained about the relation already exisiting. I am not sure, but could it be trying to recreate the entire db? I am deploying using docker, so I have no idea if that has any bearing on it.

**Comment by tcherokee** [comment] 2022-08-16 18:49
Ok finally sorted this out. It seems to be a permission based problem. I was restoring the DB using postgres root user which seemed to be the problem even though the DB user had full permissions over the DB. Once I restored the DB using the db user account, the error went away.

**Comment by martywallace** [comment] 2023-03-27 05:51
Ran into this same issue and it was a table ownership problem as described above. I ran the import in DataGrip with the default user allocated by Digital Ocean and then tried connecting with a separate application-specific user. I need to manually change ownership of all the Strapi tables to the same user to fix the problem i.e.

```sql
alter table admin_permissions owner to my_user;
alter table admin_permissions_role_links owner to my_user;
...
```

**Comment by cgraf-spiria** [comment] 2023-12-12 01:52
Same issue, but I fixed with a single command:
```
REASSIGN OWNED BY "CurrentOwnerName" TO "NewOwnerName";
```
