### ISSUE TITLE
Enum error message using special character

### ISSUE THREAD

**Issue by humbertoT2** [strapi/strapi#4123] opened 2019-09-27 16:36 UTC
**Describe the bug**
When adding a value to an Enumuration field I got the following error: "Values should not start with a number or a special character."

Except, I am not using a special character. The values are just Text on new lines with no quotes or special characters. This Enum field was created prior to 16.3 beta. Enum fields created after do not seem to reproduce this error. 

**Steps to reproduce the behavior**
1. Go to Content Type Builder
2. Click on Enum Field
3. Add a new value in the text area - EX: General
4. Hit Save
5. Error: "Values should not start with a number or a special character."

**Expected behavior**
New value should be added without error as long as no special characters are used. 

**System**
- Node.js 10.14.2
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.16.3
- Database: Mongo
- Operating system: Mac OS Mojave

**Comment by lauriejim** [comment] 2019-10-01 09:24
Hello @humbertoT2 !
Can you send me the content of you textarea please.
You should have something like this:
```
value1
value2
```
If you wrote 
```
EX:value1
EX:value2
```
It's normal you have an issue.
You are using `:` that is a special character - and it's not allowed in an enum value.

**Comment by Humberto-Zayas** [comment] 2019-10-02 14:58
Hi @lauriejim 

So my values are: 

Uncategorized 
Rings 
Springs
Clamps

I am trying to add one more

Uncategorized
Rings
Springs
Clamps
General

Upon adding "General" and navigating to "Advanced Settings" to set the "Default Value"—General is reflected as an option but hitting save produces the error message about special characters.

**Comment by lauriejim** [comment] 2019-10-03 11:33
Hello! I just tested and it works well.
[Here](https://www.loom.com/share/75ec5bde7f774991be341cd1dd57af84) is a screen record.

**Comment by derrickmehaffy** [comment] 2019-10-09 11:29
I also just tested this on beta.16.8 and couldn't reproduce the issue. I'm marking this as closed for now @Humberto-Zayas if you can find a way to reproduce this and provide the exact steps to do so please provide it and this can be reopened. Thanks!

**Closed by derrickmehaffy** 2019-10-09 11:29 UTC
Labels: type: help wanted 🤷‍♂️
