### ISSUE TITLE
Manually setting default value on JSON field

### ISSUE THREAD

**Issue by tjterry** [strapi/strapi#8118] opened 2020-09-30 20:43 UTC
**Describe the bug**

Since there is no way of setting default values on JSON-type fields in the Strapi UI, my workaround has been to manually do so by adding a "default" property on a field in the /models/{content-type}.settings.json. Whenever that content type is edited in the Content-Types Builder, my "default" property gets removed. 

**Steps to reproduce the behavior**

1. Add and save "default" property to JSON-type field in /models/{content-type}.settings.json
2. Add/edit/delete a field to the content type in Content-Types Builder
3. Find missing "default" property on field in /models/{content-type}.settings.json

**Expected behavior**

After updating a content type in the Content-Types Builder, all JSON-type fields with a "default" property should remain as they were, prior to updating content type.

**Code snippets**

*Before:*
`"attributes": {
    "services": {
      "type": "json",
      "default": []
    },
    "memos": {
      "type": "json",
      "default": []
    }
  }`

*After:*
`"attributes": {
    "services": {
      "type": "json"
    },
    "memos": {
      "type": "json"
    },
     "description": {
      "type": "text"
    },
  }`

**System**

- Node.js version: 14.4.0
- NPM version: 6.14.4
- Strapi version: 3.1.0
- Database: MongoDB
- Operating system: Mac OS X

**Additional context**

Strapi and MongoDB are running inside their own Docker containers.

**Comment by derrickmehaffy** [comment] 2020-09-30 21:03
I was able to confirm this on v3.1.6, we need to read and append to the model settings file instead of just completely overwriting it on changes.

**Comment by mahmoodhosseini** [comment] 2020-10-08 23:39
I'd like to work on this.

**Comment by nathan-pichon** [comment] 2023-02-08 09:26
Hello,
Thanks for the issue. I’m sorry for the late response.
It looks like this issue has been solved in a previous version. I cannot reproduce in the latest version of Strapi (v4.5.6).
I am closing the issue.

Feel free to re-open a new one if the issue persists.

**Closed by nathan-pichon** 2023-02-08 09:26 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-type-builder
