### ISSUE TITLE
Relations do no longer appear in content manager (strapi 4.5.0)

### ISSUE THREAD

**Issue by willempie96** [strapi/strapi#14886] opened 2022-11-16 01:14 UTC
### Required System information

- Node.js version: v16
- NPM version: 8.1.2
- Strapi version: 4.5.0
- Database: mariaDB 10.6.8
- Operating system: Mac

### Describe the bug

After updating strapi to 4.5.0 the relations, when editing a collection entry, don't show up in the block on the right (as was the expected behavior before 4.5.0) nor in the main entry managing layout.
I can see in the request to retrieve the entry that there are count values for the relations but it isn't retrieving the relations themself to show in the content manager.

(Im all for lazy loading but this might be a bit much)

**Comment by gu-stav** [comment] 2022-11-16 08:47
Can you try two things:

1. check if the fields show up in the CTB (navigate to the content-type, click "Configure the view" in the top right corner and then add them)
2. did you rebuild the admin UI running `yarn build`? Please make sure you delete your `.cache`, `build` and `node_modules` in case that doesn't make a difference.

**Comment by z0lo13** [comment] 2022-11-16 20:27
@willempie96 
they are in the bottom of you document also, not on the right side

**Comment by gu-stav** [comment] 2022-11-16 20:53
@z0lo13 As of Strapi 4.5 this is the expected behavior. They can be moved around and organized like any other fields now.

**Comment by derrickmehaffy** [comment] 2022-11-16 21:05
As this is an intended change per the 4.5.0 change-log (https://github.com/strapi/strapi/releases/tag/v4.5.0)

> [core:content-manager] Move relations into the content-manager main-view and improve loading performance (https://github.com/strapi/strapi/pull/14401)

I'm marking this as closed, there is no information on reproducing an error thus this is not a bug until additional reproduction steps are provided.

**Closed by derrickmehaffy** 2022-11-16 21:05 UTC

**Comment by willempie96** [comment] 2022-11-17 08:11
> Can you try two things:
> 
> 1. check if the fields show up in the CTB (navigate to the content-type, click "Configure the view" in the top right corner and then add them)
> 2. did you rebuild the admin UI running `yarn build`? Please make sure you delete your `.cache`, `build` and `node_modules` in case that doesn't make a difference.

I did indeed need to add them back to the view, i'm not sure how i missed that. Thx!

**Comment by santoshideal** [comment] 2025-01-07 06:41
**Title**: Relations Not Appearing in Content Manager for Main Content

**Description**: I am experiencing an issue where related content no longer appears in the main content view of the Content Manager. As shown in the attached screenshot, while I can add a relation to the content, it does not display the related data within the main entry.

This issue happens when I create or edit an entry with relations. The relation seems to be saved correctly (it shows "Published"), but it does not reflect in the content view.

Can anyone help resolve this issue or guide me on how to debug it?

Thank you!
![Screenshot from 2025-01-07 12-07-19](https://github.com/user-attachments/assets/e991346c-18ee-42d8-a8eb-3a0d90bed5f8)
