### ISSUE TITLE
Unable to use quickstart command flag

### ISSUE THREAD

**Issue by koltenfluckiger** [strapi/strapi#15101] opened 2022-12-07 07:51 UTC
### Required System information

- Node.js version: v16.18.1
- NPM version: 9.1.3
- Strapi version: 4.5.3
- Database: N/A
- Operating system: Windows 11

### Describe the bug

Unable to use the quickstart flag when creating a project. Always asks for quickstart or custom.
After looking into the create-strapi-app it looks like the quickstart flag is not being set for some reason therefore prompts for said information.

### Steps to reproduce the behavior

```shell
create-strapi-app test --quickstart
```

### Screenshots

![image](https://user-images.githubusercontent.com/41795395/206119207-6fed6e70-9f4d-4197-8c23-d8c625edaa53.png)

### Additional context

Problem in the create-strapi-app. Also occurs with yarn, npm as well. I was able to edit it, and get it working however the create-strapi-app overwrites the changes.

**Comment by monzonj** [comment] 2022-12-07 13:22
It works properly in 4.5.2 (and older). It is broken in 4.5.3

It also ignores `--no-run` (doesn't start strapi after install) and `--typescript` (uses typescript). Actually it ignores all flags.



Works:
```
npx --quiet create-strapi-app@v4.5.2 strapi --quickstart --typescript --no-run
```

Broken:
```
npx --quiet create-strapi-app@v4.5.3 strapi --quickstart --typescript --no-run
```

**Comment by koltenfluckiger** [comment] 2022-12-07 13:54
> It works properly in 4.5.2 (and older). It is broken in 4.5.3
> 
> It also ignores `--no-run` (doesn't start strapi after install) and `--typescript` (uses typescript). Actually it ignores all flags.
> 
> Works:
> 
> ```
> npx --quiet create-strapi-app@v4.5.2 strapi --quickstart --typescript --no-run
> ```
> 
> Broken:
> 
> ```
> npx --quiet create-strapi-app@v4.5.3 strapi --quickstart --typescript --no-run
> ```

Thanks for the reply. A little frustrating to say the least as I wasted so much time to try and get it up and running with a makefile and docker. I'll try 4.5.2 for now, and hopefully they fix it shortly.

**Comment by rit001** [comment] 2022-12-07 14:55
Thanks for posting this as it means that I'm not making a total mess, while trying to look at strapi for the first time.

**Comment by Eventyret** [comment] 2022-12-07 16:51
Flagged here too 2 days ago.
https://github.com/strapi/strapi/issues/15074

**Comment by bolg55** [comment] 2022-12-23 22:25
duplicate of #15074

**Closed by bolg55** 2022-12-23 22:25 UTC
