### ISSUE TITLE
`update file field data` save failed.

### ISSUE THREAD

**Issue by zhuang17** [strapi/strapi#1015] opened 2018-04-24 08:30 UTC
**Informations**
- **Node.js version**:
v9.11.1

- **npm version**:
5.6.0

- **Strapi version**:
3.0.0-alpha.12

- **Database**:
MongoDb

- **Operating system**:
MacOS 10.12

**What is the current behavior?**
When I tried to edit the data of image `file field`, 
(try both `upload a new image`, or `delete the previous image then upload a new image`)
The UI show upload image file successfully, and when i click `Save`, the UI show save successfully as well.

but when i enter into the record again, the data  image field didn't change.

**What is the expected behavior?**
The image field data should change when it update successfully.

**Comment by zhuang17** [comment] 2018-04-24 08:31
screen for updating `headerImage` field of `Test` Model
![update-image-field](https://user-images.githubusercontent.com/6997095/39175396-c7ad8c5e-47dc-11e8-9a3a-32a521d0a04c.gif)

**Comment by zhuang17** [comment] 2018-04-24 08:33
screens for `remove and re-upload` the `headerImage`  field of `Test` Model.

![delete-and-reupload-image-field](https://user-images.githubusercontent.com/6997095/39175508-1e4d89ec-47dd-11e8-991c-2d6904134825.gif)

**Comment by soupette** [comment] 2018-04-24 08:44
Duplicate of https://github.com/strapi/strapi/issues/924. See https://github.com/strapi/strapi/pull/1001

**Comment by Aurelsicoko** [comment] 2018-04-24 09:28
@zhuang17 You're lucky! When I was fixing #924 I faced this issue too. It has been fixed with this PR https://github.com/strapi/strapi/pull/1001

**Closed by Aurelsicoko** 2018-04-24 09:28 UTC
