### ISSUE TITLE
Translations are not linked properly

### ISSUE THREAD

**Issue by vinda2401** [strapi/strapi#20940] opened 2024-08-05 12:42 UTC
After an upgrade of the admin panel, switching between translations for records stored in both English (EN) and Dutch (NL) throws an error. The linking between the translations appears to be improperly set.
Steps to reproduce the behavior

1.     Open the admin panel.
2.     Locate and open a record that has translations in both EN and NL.
3.     Attempt to switch between the EN and NL translations.
4.     Observe the error that occurs.

It should have switched between the recods without throwing an error

### Screenshots
![image](https://github.com/user-attachments/assets/1a9c2512-ce3c-46a1-abb2-05eb46dd1490)

### System

- Node.js version: 18+
- NPM version: 18.6
- Strapi version: 5.0.0-rc.8
- Plugin version: 
- Database: mysql
- Operating system: Ubuntu 22.04.4 LTS

**Comment by StrapiBartosh** [comment] 2024-08-07 15:17
I've also gotten this error. In list view, I can create content in various languages, but this issue appears specifically when switching locales in a content type.

**Comment by MarcelAtSmartshore** [comment] 2024-08-21 11:42
Looking forward to updates on this issue so we can migratie, as one of the first, to v5.

**Comment by yanniskadiri** [comment] 2024-11-15 14:05
I could not reproduce it, @MarionLemaire could you try to replicate it as well?

If we are not able to reproduce, we can close it.

**Comment by MarionLemaire** [comment] 2024-11-15 15:52
@yanniskadiri i've just tried to reproduce this issue on 5.4.0 using a dataset of a localized Collection type with 2 languages (ENG and NL), including text, media and relation fields. I've left some of the relations in Draft status (as in the example) and switched from both locales in Edit view and List view : everything worked fine. I guess we can close this one :)

**Comment by yanniskadiri** [comment] 2024-11-15 16:05
Okay thanks I'm closing it then!

**Closed by yanniskadiri** 2024-11-15 16:05 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: plugin:i18n, version: 5
