### ISSUE TITLE
Deleting a file, still received that it exists in the response

### ISSUE THREAD

**Issue by praisethemoon** [strapi/strapi#4916] opened 2020-01-07 02:52 UTC
**Describe the bug**
Hello team,

I have a situation when when a user removes a file (sending `DELETE` to `upload/files/:id`), in the response, I get the `related` object, which contains relevant information to whom the file belonged. But the deleted file is still present in the returned result.

**Steps to reproduce the behavior**
1. Add new type a user as a file (with multiple uploads in my case)
2. Give user permission to delete the file
3. Add some files
4. Send DELETE requests to one of the files
5. The delete response still contains the deleted object.
6. Query the files, the deleted object does not appear anymore (only present in the response for the delete request)

**Expected behavior**
I am still a strapi noob, and this is defintely going to change as a user can literally delete any upload :sob: 

Still trying figuring out how custom controllers work. While I am avoiding them at the moment, I will defintely get into them

Still, I think the issue might still be relevant.

**Screenshots**

<img width="384" alt="image" src="https://user-images.githubusercontent.com/22145460/71864668-b7b3db00-3100-11ea-8cc9-8c99713f1611.png">

**System**
- Node.js version: v12.14.0
- NPM version: v6.13.3
- Strapi version: 3.0.0-beta.18.3
- Database: MongoDB 4.2.2
- Operating system: Ubuntu 18.04

**Comment by derrickmehaffy** [comment] 2020-01-07 05:33
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by derrickmehaffy** [comment] 2020-01-07 05:50
I believe this kinda relates to Cascade delete? https://portal.productboard.com/strapi/1-public-roadmap/c/59-cascade-delete

I'll let @lauriejim or @alexandrebodin decide here.

**Comment by alexandrebodin** [comment] 2020-01-07 07:16
Hi @praisethemoon it is the intended behavior to return the entity you just deleted in the API response in case you need some info. But the data is correctly deleted from DB.

I’m closing this issue for now. If I miss understood your issue let me know ;)

**Closed by alexandrebodin** 2020-01-07 07:16 UTC

**Comment by praisethemoon** [comment] 2020-01-07 07:44
Apologies for the false report in that case. I opted for @derrickmehaffy solution to first remove the relation and after it send the actual delete request. Thanks everyone!

**Comment by jamesdesouza** [comment] 2020-04-08 11:59
> Hi @praisethemoon it is the intended behavior to return the entity you just deleted in the API response in case you need some info. But the data is correctly deleted from DB.
> 
> I’m closing this issue for now. If I miss understood your issue let me know ;)

when you trigger delete endpoint, it's not deleted the relation data from `upload_file_morph` and this causes the empty objects in model data!

I couldn't find any workaround in issues. 

`return strapi.query('file', 'upload').delete({ id: file.id });`

this code should delete the related data but just delete the file record instead

**Comment by lauriejim** [comment] 2020-04-13 14:29
Thank you for this code.
