### ISSUE TITLE
Server crashes when attemping to create a ManyToMany relationship that results in a very long table name

### ISSUE THREAD

**Issue by pierre-le** [strapi/strapi#7800] opened 2020-09-08 14:27 UTC
**Describe the bug**

I have two content types: "Article Extension" and "Article Extension - Item".

When attempting to create a Many-to-Many relationship between the two of them, Strapi crashes when attemting to save. The error seems related to a `article_extensions_article_extension_items__article_extension_items_article_extensions` table being created, which sounds odd as both tables are listed twice in that new table name (I'd expect `article_extensions__article_extension_items`).

```
strapi_1  | [2020-09-08T14:04:46.992Z] error A table name is too long. If it is the name of a join table automatically generated by Strapi, you can customise it by adding `collectionName: "customName"` in the corresponding model's attribute.
strapi_1  | When this happens on a manyToMany relation, make sure to set this parameter on the dominant side of the relation (e.g: where `dominant: true` is set)
strapi_1  | [2020-09-08T14:04:46.993Z] error Error: ER_TOO_LONG_IDENT: Identifier name 'article_extensions_article_extension_items__article_extension_items_article_extensions' is too long
strapi_1  |     at Query.Sequence._packetToError (/srv/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
strapi_1  |     at Query.ErrorPacket (/srv/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
strapi_1  |     at Protocol._parsePacket (/srv/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
strapi_1  |     at Parser._parsePacket (/srv/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
strapi_1  |     at Parser.write (/srv/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
strapi_1  |     at Protocol.write (/srv/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
strapi_1  |     at Socket.<anonymous> (/srv/app/node_modules/mysql/lib/Connection.js:88:28)
strapi_1  |     at Socket.<anonymous> (/srv/app/node_modules/mysql/lib/Connection.js:526:10)
strapi_1  |     at Socket.emit (events.js:315:20)
strapi_1  |     at addChunk (_stream_readable.js:295:12)
strapi_1  |     at readableAddChunk (_stream_readable.js:271:9)
strapi_1  |     at Socket.Readable.push (_stream_readable.js:212:10)
strapi_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
strapi_1  |     at Protocol._enqueue (/srv/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
strapi_1  |     at Connection.query (/srv/app/node_modules/mysql/lib/Connection.js:198:25)
strapi_1  |     at /srv/app/node_modules/knex/lib/dialects/mysql/index.js:130:18
strapi_1  | From previous event:
strapi_1  |     at Client_MySQL._query (/srv/app/node_modules/knex/lib/dialects/mysql/index.js:124:12)
strapi_1  |     at Client_MySQL.query (/srv/app/node_modules/knex/lib/client.js:158:17)
strapi_1  |     at Runner.query (/srv/app/node_modules/knex/lib/runner.js:135:36)
strapi_1  |     at Runner.queryArray (/srv/app/node_modules/knex/lib/runner.js:224:14)
strapi_1  |     at /srv/app/node_modules/knex/lib/runner.js:37:25
strapi_1  | From previous event:
strapi_1  |     at Runner.run (/srv/app/node_modules/knex/lib/runner.js:25:16)
strapi_1  |     at SchemaBuilder.Target.then (/srv/app/node_modules/knex/lib/interface.js:14:43)
```

**Steps to reproduce the behavior**

1. Setup a Strapi installation using MySQL 8 as the database.
1. Create two content types: "Article Extension" and "Article Extension Item".
2. Attempt to create a Many-to-Many relationship between them.
3. Save.
4. Server attempts to reload, then crashes.

**Expected behavior**

Strapi should neither crash or allow table names that exceed MySQL or Postgres maximum allowed length.
Format of Many-to-Many relationships might need to be changed (both table names being listed twice in the generated table name).

**System**

- Node.js version: v12.18.2
- NPM version:
- Strapi version: 3.1.4
- Database: MySQL 8
- Operating system: Ubuntu 20.04

**Additional context**

Used a docker-compose file to setup Strapi, as well as a hosted MySQL database on DigitalOcean.

**Comment by pierre-le** [comment] 2020-09-08 14:29
FYI I worked around that issue by removing the culprit field from `xxx.settings.json` files, then shortening both table names. But the core issue still stands.

**Comment by derrickmehaffy** [comment] 2020-09-08 15:06
@alexandrebodin @Convly @petersg83 something to note when we get to reworking the database, about making the naming system a bit more "future proof"

**Comment by alexandrebodin** [comment] 2020-09-09 12:55
Hi, This issue is a duplicate of https://github.com/strapi/strapi/issues/3409 :) 

You can check the doc https://strapi.io/documentation/v3.x/concepts/models.html#relations in the many-many tab :)

**Closed by alexandrebodin** 2020-09-09 12:55 UTC
Labels: priority: medium, source: core:database, status: confirmed, type: bug

**Comment by ralphsomeday** [comment] 2021-03-24 13:15
https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#models

**Comment by ralphsomeday** [comment] 2021-03-24 13:15
```
{
  "attributes": {
    "categories": {
      "collection": "category",
      "via": "products",
      "dominant": true,
      "collectionName": "products_categories__categories_products" // this is optional but this is how you can solve this issue
    }
  }
}
```
