### ISSUE TITLE
"Invalid Input Data Please Verify Unique Constraints " after migrating from OneClick to AWS

### ISSUE THREAD

**Issue by Tej-Bains** [strapi/strapi#9369] opened 2021-02-10 20:51 UTC
### Describe the bug

Moved my strapi build from digitaloceans one click service to aws self-installed strapi on ubuntu 18. with postgres rds. 

Database was migrated using aws datamigration service. Content was successfully migrated. There were some initial errors, but repeat of the process with truncate enabled allowed the database to be moved successfully.

Strapi is showing the data, but when trying to edit the migrated content you get met with the error "Invalid Input Data Please Verify Unique Constraints ".

### Steps to reproduce the behaviour

1. Open a digitalocean one click strapi app add some content.
2. Set up aws strapi server and database and s3 bucket and steps.
3. move database from digitalocean to aws.
4. try to change content after logging in.

### Expected behavior

No error and successful edit of the fields.

### System

- Node.js version: 10.19.0
- NPM version: 6.14.4
- Strapi version: 3.46
- Server: AWS EC2 Ubuntu 18
- Database: postgres on aws rds
- Operating system: windows os

### Additional context

from the backside the postgres database is giving a 400 error. But if i were to add a item to the collection content, then that item works fine. I just cant edit or change SOME fields in the cms for content that was migrated over.

Ive tried with node_env to both dev and production.

ive tried strapi development mode.

ive tried strapi production.

ive tried updating all the npm packages and updating to latest strapi build.

still getting the same error.

is this issue related to security groups on aws? or the s3 bucket for file uploads?

any help is appreciated.

**Comment by derrickmehaffy** [comment] 2021-02-10 21:00
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by Tej-Bains** [comment] 2021-02-10 21:07
> 
> 
> > This is a templated message
> 
> Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).
> 
> A proper issue submission let's us better understand the origin of your bug and therefore help you.
> 
> I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).
> 
> Please update the issue with the template and we can reopen this report.
> 
> Thank you.

fixed

**Comment by derrickmehaffy** [comment] 2021-02-22 14:34
@Tej-Bains 
> Strapi version: 3.46

We issued a release in v3.5.0 last week that should address this, can you try updating and see if that fixes your issue?

**Comment by mrmadhat** [comment] 2021-03-01 09:23
I was getting this error because of a mismatch in package versions. During my deploy I switched the upload provider from `strapi-provider-upload-aws-s3` to `strapi-provider-upload-cloudinary` but when I installed the new provider I didn't realise that the installed version of the upload provider was 3.5.1 and strapi packages were 3.4.6. Making sure the provider version matched the strapi version fixed the issue for me.

**Comment by brnpimentel** [comment] 2021-04-09 12:52
I updated to last version 3.5.x and fixed the issue

**Comment by derrickmehaffy** [comment] 2021-04-09 18:21
Marking as closed as two confirmations stated it's fixed.

**Closed by derrickmehaffy** 2021-04-09 18:21 UTC
Labels: severity: low, source: core:database, status: pending reproduction, type: bug

**Comment by gramsco** [comment] 2021-06-24 06:59
I have the same issue with 3.6.1.
My hypothesis is that bugs like in Strapi that occur when:

- you add a field to a collection
- you add data to the field for an object in said collection
- you remove the field 

because Strapi does not remove the data associated to the field. Which could be a good opt-in by the way: "do you want to remove the data associated to the field you're deleting?" 

 I will try to go directly into the DB to fix the issue (and update my post)

**Comment by shadracnicholas** [comment] 2021-06-26 14:53
This is a "by design" Postgress issue that occurs when you mass import. To solve it;

SELECT MAX(the_primary_key) FROM the_table;
SELECT nextval('the_primary_key_seq');
SELECT setval('the_primary_key_sequence', (SELECT MAX(the_primary_key) FROM the_table)+1);

Do this across all affected tables.

**Comment by gramsco** [comment] 2021-06-26 20:06
I should have mentioned it's a mongoDB project!

**Comment by sidsaxena0** [comment] 2021-08-12 08:16
I am still facing this issue on 3.6.6 in postgresql.

**Comment by sidsaxena0** [comment] 2021-08-12 08:26
> This is a "by design" Postgress issue that occurs when you mass import. To solve it;
> 
> SELECT MAX(the_primary_key) FROM the_table;
> SELECT nextval('the_primary_key_seq');
> SELECT setval('the_primary_key_sequence', (SELECT MAX(the_primary_key) FROM the_table)+1);
> 
> Do this across all affected tables.

Thanks it helped me!

**Comment by coderdix** [comment] 2021-09-16 16:57
> This is a "by design" Postgress issue that occurs when you mass import. To solve it;
> 
> SELECT MAX(the_primary_key) FROM the_table;
> SELECT nextval('the_primary_key_seq');
> SELECT setval('the_primary_key_sequence', (SELECT MAX(the_primary_key) FROM the_table)+1);
> 
> Do this across all affected tables.

I'm new to sequel and had this same error. I'm using TablePlus Query area to input this - could you maybe offer some explanation into what its doing & why it (could) work

**Comment by shadracnicholas** [comment] 2021-09-16 18:04
@coderdix When you import the database you need to reset the sequence for each table. What the above script does is increase the sequence id by 1 from the last record in your table. The next time you save, the updated sequence will be the id and auto increased by one. I hope I have not confused you even more. You can DM me on Twitter @shadracnicholas in case this explanation doesn't seem to make sense.

**Comment by ahmadjoya** [comment] 2021-10-03 04:59
today I faced this issue as well. 10/3/2021

**Comment by shadracnicholas** [comment] 2021-10-04 10:49
@ahmadjoya You are using Postgress as your database?

**Comment by lifedup** [comment] 2021-11-13 04:55
I also had this problem.  I was using an existing DB that had a UUID based primary key.  Strapi only supports integer primary keys for tables that are modified using Strapi.  If you don't ever use relations or image fields you won't have a problem.

If you add a relation or photo field - Strapi will automatically use an integer for the reference regardless of the actual PK field type.   I.e., if you have an article table with UUID PK and add an image field, the DB upload table will set the reference field to Int4, making it throw this error.  

To fix this – make sure all of your PK fields are Integers.

**Comment by i-bsd** [comment] 2021-11-26 04:44
> To fix this – make sure all of your PK fields are Integers.

Can you explain how to change this? I'm having the same issue and think this might be it.

**Comment by thiboot** [comment] 2021-12-05 22:04
> This is a "by design" Postgress issue that occurs when you mass import. To solve it;
> 
> SELECT MAX(the_primary_key) FROM the_table; SELECT nextval('the_primary_key_seq'); SELECT setval('the_primary_key_sequence', (SELECT MAX(the_primary_key) FROM the_table)+1);
> 
> Do this across all affected tables.

Resolved my problem, thx @shadracnicholas, further informations here: 
https://www.ankursheel.com/blog/reset-primary-key-sequence-out-of-sync-postgres

**Comment by Gabriel-Andy** [comment] 2022-03-04 10:08
I also have  a same issue.
I am trying to post image on strapi on production.
everything is ok on my development but on production, I have this issue.
I use mongodb

**Comment by ashokselva-js** [comment] 2022-05-19 05:40
> This is a "by design" Postgress issue that occurs when you mass import. To solve it;
> 
> SELECT MAX(the_primary_key) FROM the_table; SELECT nextval('the_primary_key_seq'); SELECT setval('the_primary_key_sequence', (SELECT MAX(the_primary_key) FROM the_table)+1);
> 
> Do this across all affected tables.

Works like a charm✌✌

**Comment by harshSinghCondenast** [comment] 2022-07-19 07:08
> This is a "by design" Postgress issue that occurs when you mass import. To solve it;
> 
> SELECT MAX(the_primary_key) FROM the_table; SELECT nextval('the_primary_key_seq'); SELECT setval('the_primary_key_sequence', (SELECT MAX(the_primary_key) FROM the_table)+1);
> 
> Do this across all affected tables.

I'm new to the postgres. So can any one tell me, "Where Should I execute this query ?" as in strapi we can't do this and if it has to be done in postgres (pgAdmin) in which section it has be done, as I'm trying to do this in query editor but It is not helping me in any way.😫😫
