### ISSUE TITLE
/config/env instead of /config/environments

### ISSUE THREAD

**Issue by andrewspode** [strapi/strapi#8821] opened 2020-12-07 16:36 UTC
### Describe the bug

(almost) All the documentation suggests that custom configuration should be /config/environments/environment-name but this fails to work, however /config/env/environment-name works. 

For example /config/env/development works, but /config/environments/development does not.

### Steps to reproduce the behavior

Do a quick start Strapi install. Move the config from the config folder root into /config/environments/development and the server won't start, complaining of undefined variables. Rename the "environments" folder to "env" and it works.

### Expected behavior

It should load the custom configuration.

Either the documentation needs to be updated so that it is /config/env/ (I found one reference to that) or the code needs updating to work with /config/environments/ (as suggested in most docs including file structure).

I think considering there are references to both, it might be safer to include both?

### System

- Node.js version: 14.15.1
- NPM version: 
- Strapi version: 3.3.4
- Database: Sqllite
- Operating system: Docker Linux

I have NODE_ENV set to "development" in my environment, and I am launching as "yarn develop"

**Comment by derrickmehaffy** [comment] 2020-12-07 17:23
I believe you are looking at the wrong documentation (beta) that we are planning to remove this month.

https://strapi.io/documentation/v3.x/concepts/configurations.html#environments

I'm going to mark this as closed as it's not a bug with the code. but please deep feel free to keep up the discussion.

**Closed by derrickmehaffy** 2020-12-07 17:23 UTC

**Comment by andrewspode** [comment] 2020-12-07 18:04
> I believe you are looking at the wrong documentation (beta) that we are planning to remove this month.
> 
> https://strapi.io/documentation/v3.x/concepts/configurations.html#environments
> 
> I'm going to mark this as closed as it's not a bug with the code. but please deep feel free to keep up the discussion.

You are 100% correct and now I feel silly. If I search for "strapi environment configuration" the beta stuff comes up first and it wasn't clear to me that this is what I was reading! Thanks for looking into it :)
