### ISSUE TITLE
"duplicate key value violates unique constraint" error when creating a new item

### ISSUE THREAD

**Issue by IvoNet** [strapi/strapi#17635] opened 2023-08-10 06:07 UTC
### Required System information

- Node.js version: 16.15.0
- NPM version: 8.5.5
- Strapi version: 4.12.0
- Database: PostgreSQL
- Operating system: Linux 
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After a Migration file was used for basic filling of a table we can not add new entries to the table anymore as the postgres sequencer seems not to have been updated and we get duplicate key errors

See also issue [here](https://github.com/strapi/strapi/issues/12493) that was IMHO wrongly closed.

### Steps to reproduce the behavior

1. I make anew item based on a Content-Type
2. I try to save it
3. Get an error message (see screenshot)
4. In log get a stacktrace (see further down)

### Expected behavior

The item should have been saved.

### Screenshots

![image](https://github.com/strapi/strapi/assets/741238/f0f5d3d6-dee5-4724-905a-75b0bc0fe6cf)

### Code snippets

Stacktrace

```text
[2023-08-10 05:52:15.576] error: insert into "public"."release_note_items_application_id_links" ("release_note_application_id_id", "release_note_item_id") values ($1, $2) on conflict ("release_note_item_id", "release_note_application_id_id") do nothing returning "id" - duplicate key value violates unique constraint "release_note_items_application_id_links_pkey"
error: insert into "public"."release_note_items_application_id_links" ("release_note_application_id_id", "release_note_item_id") values ($1, $2) on conflict ("release_note_item_id", "release_note_application_id_id") do nothing returning "id" - duplicate key value violates unique constraint "release_note_items_application_id_links_pkey"
    at Parser.parseErrorMessage (/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Additional context

I have done the "solution" as described in the other issue:

```sql
SELECT SETVAL(
               (SELECT PG_GET_SERIAL_SEQUENCE('"release_note_items"', 'id')),
               (SELECT MAX(id)
                FROM release_note_items) + 1, FALSE
           );
```

and that seemed to work but a few days later a "couple table" gave issues and we had to do it again

```sql
SELECT SETVAL(
               (SELECT PG_GET_SERIAL_SEQUENCE('"release_note_items_application_id_links"', 'id')),
               (SELECT MAX(id)
                FROM release_note_items_application_id_links) + 1, FALSE
           );
```

I do not think this is a Postgres Issue but a Strapi issue. Please reinvestigate.

**Comment by gu-stav** [comment] 2023-08-11 10:18
@IvoNet I have not checked yet: do you think this issue is a duplicate of https://github.com/strapi/strapi/issues/12493? If so, could we close this one - I have re-opened the previous issue, because it contains more context.

**Comment by IvoNet** [comment] 2023-08-14 11:11
I think it is the same issue yes

**Closed** 2023-08-14 11:11 UTC
