### ISSUE TITLE
API is response for any authorization header on GraphQL

### ISSUE THREAD

**Issue by davutkara** [strapi/strapi#1317] opened 2018-06-04 21:34 UTC
**Informations**
- **Node.js version**: 8.11.2
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0 alpha 12.2
- **Database**: mongodb
- **Operating system**: ubuntu 16.04

**What is the current behavior?**

Api is response for any authorization

**Steps to reproduce the problem**

I installed graphql and Chrome Modify Headers extension, I set authorization for dummy data, then it response for my request on the playground.

**What is the expected behavior?**
It could give error for authorization.

**Suggested solutions**

make jwt secure please

**Comment by davutkara** [comment] 2018-06-04 21:55
When I try restful api it gives error that is "invalid token."
But when using graphql, it did not give error.

**Comment by xeegi** [comment] 2018-06-20 09:10
Could not reproduce on Strapi version: 3.0.0 alpha 12.3
Instead of using Chrome Modify Header extension I used HTTP Headers tab built into the Playground.
Using dummy Authorization header gave response as:
```
{
  "error": "Response not successful: Received status code 401"
}
```
Did not test with: 3.0.0 alpha 12.2

Meanwhile using a correct token gave an expected result.

**Comment by Aurelsicoko** [comment] 2018-06-20 16:38
@Jehu I made a quick test on my side, it was working well. Can you give me the steps to reproduce?

**Comment by Jehu** [comment] 2018-06-20 17:35
@Aurelsicoko i think we must ask @davutkara here? I just watch this issue because i evaluate strapi for using in production

**Comment by davutkara** [comment] 2018-06-20 18:15
I tried on developer mode.

**Comment by lauriejim** [comment] 2018-07-01 16:06
I am closing this issue because we don’t have any update/needed informations about it.

**Comment by hachimihamza** [comment] 2018-09-19 20:30
![screenshot from 2018-09-19 20-26-16](https://user-images.githubusercontent.com/16524191/45779456-f47d6980-bc52-11e8-856c-da771cd7123b.png)
You can reproduce this 
version 3.0.0-alpha.14.1.1
node v8.12.0

**Comment by derrickmehaffy** [comment] 2018-09-20 15:29
@Aurelsicoko can confirm this issue:
![image](https://user-images.githubusercontent.com/8593673/45829220-45bb4680-bcaf-11e8-9cc0-2239eb3b9660.png)

This needs to be re-opened and made a very high priority. Basically allows anyone to bypass authentication to query the server.

**Comment by lauriejim** [comment] 2018-09-24 16:20
Have to check if one has not be opened about this issue.

**Comment by lauriejim** [comment] 2018-10-07 18:00
Fixed in last version of Strapi

**Comment by derrickmehaffy** [comment] 2018-10-07 19:51
@lauriejim can you link the commit this was fixed in? I was testing on 14.2 and could still bypass it.

**Comment by lauriejim** [comment] 2018-10-07 20:34
Sorry was testing with generated API no with user API

**Comment by derrickmehaffy** [comment] 2018-10-07 20:36
Just for an example on v14.2:

![image](https://user-images.githubusercontent.com/8593673/46586619-f22e5400-ca35-11e8-98fa-e00627ca511a.png)

**Comment by rpedroni** [comment] 2018-11-01 19:04
Hey guys, any update one this?
Just started using Strapi today (fresh alpha install) and can confirm GraphQL accepts anything for "Authorization" header.

![whatsapp image 2018-11-01 at 16 04 24](https://user-images.githubusercontent.com/759187/47873378-d4170200-ddef-11e8-92b1-660337754d50.jpeg)

**Comment by Aurelsicoko** [comment] 2018-11-02 17:14
I'll fix it next week, it's in my todo list 💪

**Comment by Aurelsicoko** [comment] 2018-11-06 15:41
Done 💪

**Closed** 2018-11-08 17:37 UTC
Labels: priority: high, status: confirmed, type: bug 🐛
