### ISSUE TITLE
[Bug] GET users/me doesn't return avatar

### ISSUE THREAD

**Issue by ssuvorov** [strapi/strapi#7491] opened 2020-08-16 19:44 UTC
**Describe the bug**
After using **POST /upload**
```
body <FormData> {
  files: (file),
  ref: user,
  refId: 46,
  field: avatar,
  source: 'users-permissions'
}
```
the response is the following: **(avatar is null! I don't know why)**
```js
[
    {
        "id": 52,
        "name": "Screenshot 2020-06-03 at 18.25.33.png",
        "alternativeText": null,
        "caption": null,
        "width": 722,
        "height": 990,
        "formats": {
            "small": {
                "ext": ".png",
                "url": "https://res.cloudinary.com/dy3jvbm3l/image/upload/v1597604855/small_Screenshot_2020_06_03_at_18_25_33_b555919390.png",
                "hash": "small_Screenshot_2020_06_03_at_18_25_33_b555919390",
                "mime": "image/png",
                "name": "small_Screenshot 2020-06-03 at 18.25.33.png",
                "path": null,
                "size": 111.67,
                "width": 365,
                "height": 500,
                "provider_metadata": {
                    "public_id": "small_Screenshot_2020_06_03_at_18_25_33_b555919390",
                    "resource_type": "image"
                }
            },
            "medium": {
                "ext": ".png",
                "url": "https://res.cloudinary.com/dy3jvbm3l/image/upload/v1597604854/medium_Screenshot_2020_06_03_at_18_25_33_b555919390.png",
                "hash": "medium_Screenshot_2020_06_03_at_18_25_33_b555919390",
                "mime": "image/png",
                "name": "medium_Screenshot 2020-06-03 at 18.25.33.png",
                "path": null,
                "size": 207.28,
                "width": 547,
                "height": 750,
                "provider_metadata": {
                    "public_id": "medium_Screenshot_2020_06_03_at_18_25_33_b555919390",
                    "resource_type": "image"
                }
            },
            "thumbnail": {
                "ext": ".png",
                "url": "https://res.cloudinary.com/dy3jvbm3l/image/upload/v1597604853/thumbnail_Screenshot_2020_06_03_at_18_25_33_b555919390.png",
                "hash": "thumbnail_Screenshot_2020_06_03_at_18_25_33_b555919390",
                "mime": "image/png",
                "name": "thumbnail_Screenshot 2020-06-03 at 18.25.33.png",
                "path": null,
                "size": 18.7,
                "width": 114,
                "height": 156,
                "provider_metadata": {
                    "public_id": "thumbnail_Screenshot_2020_06_03_at_18_25_33_b555919390",
                    "resource_type": "image"
                }
            }
        },
        "hash": "Screenshot_2020_06_03_at_18_25_33_b555919390",
        "ext": ".png",
        "mime": "image/png",
        "size": 124.32,
        "url": "https://res.cloudinary.com/dy3jvbm3l/image/upload/v1597604852/Screenshot_2020_06_03_at_18_25_33_b555919390.png",
        "previewUrl": null,
        "provider": "cloudinary",
        "provider_metadata": {
            "public_id": "Screenshot_2020_06_03_at_18_25_33_b555919390",
            "resource_type": "image"
        },
        "created_at": "2020-08-16T19:07:36.038Z",
        "updated_at": "2020-08-16T19:07:36.038Z",
        "created_by": null,
        "updated_by": null,
        "related": [
            {
                "__contentType": "UsersPermissionsUser",
                "id": 46,
                "username": "test@test.com",
                "email": "test@test.com",
                "provider": "local",
                "password": "-----hash-----",
                "resetPasswordToken": null,
                "confirmed": true,
                "blocked": null,
                "role": 1,
                "created_at": "2020-07-12T10:48:17.774Z",
                "updated_at": "2020-08-16T19:06:33.949Z",
                "first_name": "x",
                "last_name": "y",
                "created_by": null,
                "updated_by": 1,
                "avatar": null
            }
        ]
    }
]
```

**GET /users/:id** - returns avatar. This works fine. So if I request `/users/46` - avatar is an object.

**Current behavior**
**GET /users/me** - returns avatar: **null**

**Expected behavior**
**GET /users/me** - returns avatar: {object}

In Strapi admin, when I select the user (id = 46), avatar is displayed.

**Related**
```js
// package.json
"dependencies": {
    "editorjs-html": "^2.0.0",
    "knex": "^0.21.2",
    "pg": "^8.3.0",
    "strapi": "^3.1.1",
    "strapi-admin": "^3.1.1",
    "strapi-connector-bookshelf": "^3.1.1",
    "strapi-plugin-content-manager": "^3.1.1",
    "strapi-plugin-content-type-builder": "^3.1.1",
    "strapi-plugin-email": "^3.1.1",
    "strapi-plugin-upload": "^3.1.1",
    "strapi-plugin-users-permissions": "^3.1.1",
    "strapi-provider-upload-cloudinary": "^3.1.1",
    "strapi-utils": "^3.1.1"
  },
```

- Node.js: v13.11.0
- NPM version: 6.14.7
- Database: Postgresql

**Additional context**
```js
// User.settings
{
  "connection": "default",
  "kind": "collectionType",
  "collectionName": "users-permissions_user",
  "info": {
    "name": "user",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "confirmed": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions",
      "configurable": false
    },
    "first_name": {
      "type": "string",
      "minLength": 2,
      "maxLength": 100
    },
    "last_name": {
      "type": "string",
      "maxLength": 100,
      "minLength": 2
    },
    "avatar": {
      "model": "file",
      "via": "related",
      "plugin": "upload"
    }
  }
}

```

**Comment by derrickmehaffy** [comment] 2020-08-17 17:01
Hello!

A few things to note here
- Node v13 isn't support only "even" versions and the current Node LTS is supported (in this case v12 as v14 doesn't go LTS until October)
- You will want to update to the latest version v3.1.4 for Strapi packages to use the below suggestion.

By default only the `role` is populated for the `/users/me` you can custom this using the [extensions system](https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#how-do-i-customize-a-plugin) and extending this function to customize the populate array: https://github.com/strapi/strapi/blob/b39709a6edee136047260aefca34069e4cf8b0f8/packages/strapi-plugin-users-permissions/services/User.js#L68-L74

I'm going to mark this as closed as it's not a bug with Strapi but intended as populating many relations can cause quite a bit of latency for this specific endpoint.

**Closed by derrickmehaffy** 2020-08-17 17:01 UTC

**Comment by ssuvorov** [comment] 2020-08-18 07:50
@derrickmehaffy thanks! I created `extensions/users-permissions/services/User.js` with the following code
```js
module.exports = {
  async fetchAuthenticatedUser(id) {
    return strapi.query('user', 'users-permissions').findOne({ id }, ['role', 'avatar']);
  }
};
```

It works. However, it's a bit weird, that in the code I see only role selection `['role']`. I expected to see only role fields, but instead having an avatar too.

**Comment by derrickmehaffy** [comment] 2020-08-18 15:58
Indeed it does look strange, I am aware of the cause but it is much farther up the cascading code tree that requires a much larger fix, alternatively if you want to populate all the relations you can just remove that array and all fields will be populated up to one level deep.
