### ISSUE TITLE
[v4 & v3] - All text-based fields created by the user in the Content-Type Builder have the wrong autocomplete HTML parameter

### ISSUE THREAD

**Issue by kasonde** [strapi/strapi#11241] opened 2021-10-11 17:07 UTC
### Describe the bug

Currently, in both v4 and v3, all text-based input fields generated by the Content-Type Builder have their `autocomplete` HTML parameter set to `new-password` and not `off` for example. 

### Steps to reproduce the behavior

1. Create a new content type
2. Add a new field and save the content type
3. Inspect the element in the Dev tools when you try to add a new record
4. See wrong 

### Expected behavior

This should either not be set or specified to the correct parameter values

### Screenshots

![image](https://user-images.githubusercontent.com/13610895/136828849-cabd6b76-94cf-4082-96fb-6764ab22d4aa.png)

### System

- Node.js version: 14
- NPM version: 6
- Strapi version: v3 / v4
- Database: SQLite
- Operating system: MacOS BigSur

**Comment by derrickmehaffy** [comment] 2021-11-09 02:42
Confirmed in beta.11

**Comment by JabStrapi** [comment] 2021-11-25 13:45
Indeed, as @ChristianHeimke mentioned, this is intended to prevent the browser auto-completion. I'll close this issue until we get a chance to turn this into an option.

**Closed by JabStrapi** 2021-11-25 13:45 UTC
Labels: type: bug, severity: low, status: confirmed, source: admin, version: v4-Alpha/Beta
