### ISSUE TITLE
Many-to-Many relations creating table name too long

### ISSUE THREAD

**Issue by jsve** [strapi/strapi#3409] opened 2019-06-08 17:16 UTC
**Describe the bug**
When setting up a  many-to-many relation between to entities: A relation table is created (as expected) and the relation seems to work properly. If strapi reboots it will not start again, giving this error:
```
[2019-06-08T17:04:37.306Z] debug ⛔️ Server wasn't able to start properly.
[2019-06-08T17:04:37.307Z] error error: relation "entity1_entity2__entity2_entity1" already exists
```

**Steps to reproduce the behavior**
1. Create many-to-many relation between two entities (relation table is created as expected)
2. shut down strapi
3. start up strapi again
__error message from above__

If i remove the relation table,Ii am able to start up strapi again. The relations is then (of course) lost between the entities.

**Expected behavior**
strapi should start, even with relations defined.

**System**
Node.js version: v10.15.3
NPM version: 6.4.1
Strapi version: 3.0.0@beta.3
Database: postgres
Operating system: MacOS

**Additional context**
Not sure if related, but the relation table gets a name that exceeds postgres 63 byte name limit. The name is hence truncated upon creation.

**Comment by jsve** [comment] 2019-06-08 17:35
**Follow up**
I realised that it would be quite easy to test my theory in "additional context".

When I create two new entities "e1" and "e2" and set up many-to-many between them, the resulting relation table gets named `e_1_s_e_2_s__e_2_s_e_1_s` (24 characters). This does seem to work even between reboots.

This leads to the conclusion that postgres truncating of table names has something to do with the bug.

**Comment by alexandrebodin** [comment] 2019-06-11 18:46
Hi @jsve,

Can you please provide the `Model.settings.json` files to reproduce your bug ?

Thanks !

**Comment by jsve** [comment] 2019-06-11 21:38
## Component Price Card
```json
{
  "connection": "default",
  "collectionName": "Component Price Card",
  "info": {
    "name": "componentpricecard",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "cms_name": {
      "required": true,
      "default": "name to show in cms",
      "type": "string"
    },
    "price": {
      "type": "string",
      "required": true
    },
    "price_period": {
      "default": "",
      "required": true,
      "type": "string"
    },
    "feature_list_en": {
      "required": true,
      "default": "- feature 1\n - feature 2",
      "type": "text"
    },
    "cta": {
      "maxLength": 15,
      "default": "buy",
      "required": true,
      "type": "string"
    },
    "sectionprices": {
      "collection": "sectionprice",
      "via": "componentpricecards"
    }
  }
}
```

## sectionprice 
```json
{
  "connection": "default",
  "collectionName": "sectionprices",
  "info": {
    "name": "sectionprice",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "cms_name": {
      "default": "some name to show in cms",
      "type": "string"
    },
    "componentpricecards": {
      "collection": "componentpricecard",
      "via": "sectionprices",
      "dominant": true
    }
  }
}
```

**Comment by alexandrebodin** [comment] 2019-06-12 07:48
Hi @jsve,

Indeed postgres truncates the table on creation when the table name length is too long: https://til.hashrocket.com/posts/8f87c65a0a-postgresqls-max-identifier-length-is-63-bytes.

When checking if the table already exists it fails because it looks for the longer name.

I suggest you use short filenames for your entities for now until we can handle it.

**Comment by cns-dan** [comment] 2019-09-17 10:53
We are getting an equivalent error creating a many-to-many relation on MySQL:

error Impossible to register the 'longmodelnames' model.
error Error: ER_WRONG_TABLE_NAME: Incorrect table name 'longmodelnames_relatedmodelnames__relatedmodelnames_longmodelnames'

**Comment by eiskalteschatten** [comment] 2020-02-13 09:12
Is there any prospect of this bug being fixed soon? It is causing a lot of pain and costing me tremendous amount of time....

**Comment by matepaiva** [comment] 2020-03-02 16:48
@eiskalteschatten did you find any work around for this?

**Comment by eiskalteschatten** [comment] 2020-03-02 16:50
@matepaiva The only workaround I've found is to rename the content types with really short names which is, of course, not really possible if you have a lot of data already. :( Fortunately, our system is brand new, so we don't have any data in it and it's still possible.

**Comment by matepaiva** [comment] 2020-03-02 17:49
I found another workaround, I think. But you must create a new table. 

The workaround is to create a table with a short name, once the uid is obtained from the name. You can go to the advanced tab and set the real name as the name of the table, as this is not the issue. Save your new resource. 

After that, the uid will be generated. Now you can change the name for the real name, and everything would work as usual.

**Comment by matepaiva** [comment] 2020-03-02 17:53
@eiskalteschatten I think another workaround maybe is to change the folder name/filenames because the uid is generated based on that.

**Comment by eiskalteschatten** [comment] 2020-03-02 20:18
@matepaiva Thanks for the ideas! Next time I run into the problem, I will try them out!

**Comment by Djinnes** [comment] 2020-03-09 12:44
What about a solution of allowing the relationship tables to be renamed?

**Comment by derrickmehaffy** [comment] 2021-03-29 16:58
Reopening due to reproduction on PostgreSQL / MySQL / MariaDB on Strapi v3.5.x

Pinging @ScottAgirs for more information if he wants to provide it.

We need to find another solution as the startup process to validating the database schema isn't taking into account the truncation that the database does with the relation name so it throws an error on startup.

Default limits of table names in SQL databases:
- PostgreSQL = 63 bytes
- MySQL/MariaDB = 64 bytes
- SQLite = 128 bytes (not exclusive, it's limited on the length of the entire SQL statement which is 1000000 bytes. See: https://www.sqlite.org/limits.html )

**Comment by derrickmehaffy** [comment] 2021-03-29 16:59
Workaround provided by @alexandrebodin in https://github.com/strapi/strapi/issues/3409#issuecomment-501160074 still applies but the issue is not "fixed"

**Comment by derrickmehaffy** [comment] 2021-03-29 17:00
Note, changing the collectionName does not solve the issue, you must rename the entire model. @strapi/maintainers should we switch this to use the collection name instead? It would at least make it easier to modify instead of renaming the whole model which also means you have to fix the routes.json + major project code changes to properly rename.

**Comment by ScottAgirs** [comment] 2021-03-29 17:09
@derrickmehaffy thank you for your help w this. I think you already said it all, but I am currently working on trying out the steps you suggested, I'll follow up w my findings once done.

**Comment by ScottAgirs** [comment] 2021-03-29 17:45
**Update:** abbreviating model names (folders, files and collectionName), as well as relational fields, solved the issue with where Strapi app failed to start due to an error where ".. table already exists ..".

It is, however, confusing and a bit of a mystery on how to use this, and since this is defacto the core functionality of a CMS I would love to see this as a top priority item.

And if I may throw my 2 cents into the tips jar - even something like a max char limit info when creating relational fields or naming Collection Types would be great. For example, I noticed that in some cases the relational field names can be even longer than the one that caused an issue.

It turned out that the problem was the combination of factors - I believe (also based on what @derrickmehaffy explained to me) that the major contributing factor was the many-to-many relationship.

I wouldn't want to go to much more detail as I don't think I have enough context and knowledge about this, but hopefully this helps.

**Comment by alexandrebodin** [comment] 2021-03-29 18:35
We merged a PR that allows configure the join table name of a relation that's why the issue was closed a while back.

I thought it was also documented but could not find it so not sure about that.

Check this PR https://github.com/strapi/strapi/pull/5627. You simply can use the collectionName property inside a relation to define the join table name for many many & manyWay relations

**Comment by derrickmehaffy** [comment] 2021-03-29 18:42
@alexandrebodin it was expressly stated this was for NoSQL only, but this issue was happening on PostgreSQL.

```
**NOTE**:
(NoSQL databases only) The `collectionName` key defines the name of the join table. It has to be specified once, in the `dominant` attribute of the relation. If it is not specified, Strapi will use a generated default one. It is useful to define the name of the join table when the name generated by Strapi is too long for the database you use.
```

@petersg83 can you confirm it's on both SQL and NoSQL and I'll transfer this issue over to the documentation repo to build docs around it.

**Comment by petersg83** [comment] 2021-03-30 09:47
Alright, there is a problem with the documentation yes. Let me update it (it's SQL only, there are no table created for mongo)

**Comment by petersg83** [comment] 2021-03-30 10:02
Here is the PR : https://github.com/strapi/documentation/pull/215

**Comment by tobia** [comment] 2021-03-30 15:57
With the version I'm using (3.5.4) I can add the collectionName attribute in a relation to customize the relation table, but then if I ever use the Content-Types Builder on the same collection type, even by changing another field and hitting Save, it will remove the attribute and re-create the original named table.

Is this expected (eg. already fixed in master) or is it a bug?

**Comment by petersg83** [comment] 2021-03-30 16:22
Thanks for the feedback, it is a bug indeed. Can you please open an issue for that and tag me in?

**Closed** 2021-04-26 15:05 UTC
Labels: severity: medium, source: core:database, status: confirmed, type: bug

**Comment by frn-dawn** [comment] 2021-09-02 08:40
@alexandrebodin Can it really be right that this issue is closed because an advanced manual CMS configuration can "solve" the problem before it occurs? As @ScottAgirs mentioned, naming is a core feature of CMS development, and is essential for usability. Especially when dealing with many different content types, are long-ish names (3 words are not unusual) common and necessary. 
I don't see a case where it's natural for developers to remember to put shorter collection names in the Content-Types Builder's advanced tab. 

As long as it's possible to crash the system by typing a name in the UI, this should be considered a bug.

Any chance there is something on the roadmap to fix this properly? I'm hesitant to use Strapi for professional projects if this type of issue is not taken seriously.

I hope to see a reaction to this, as I think Strapi is filling a gap in the market, and I want to be able to recommend it on client projects.

**Comment by alexandrebodin** [comment] 2021-09-02 09:47
> @alexandrebodin Can it really be right that this issue is closed because an advanced manual CMS configuration can "solve" the problem before it occurs? As @ScottAgirs mentioned, naming is a core feature of CMS development, and is essential for usability. Especially when dealing with many different content types, are long-ish names (3 words are not unusual) common and necessary.
> I don't see a case where it's natural for developers to remember to put shorter collection names in the Content-Types Builder's advanced tab.
> 
> As long as it's possible to crash the system by typing a name in the UI, this should be considered a bug.
> 
> Any chance there is something on the roadmap to fix this properly? I'm hesitant to use Strapi for professional projects if this type of issue is not taken seriously.
> 
> I hope to see a reaction to this, as I think Strapi is filling a gap in the market, and I want to be able to recommend it on client projects.

Hi, This will not be changed in v3 as it will pass in maintenance mode. However this will be reviewed for v4 to see waht we can do about it

**Comment by frn-dawn** [comment] 2021-09-06 12:06
> Hi, This will not be changed in v3 as it will pass in maintenance mode. However this will be reviewed for v4 to see what we can do about it

Thanks for your reply @alexandrebodin 

When is v4 planned for? And If solving this issue becomes part of it, where can I follow the status?

**Comment by cupofnestor** [comment] 2022-03-10 19:21
This is still an issue in v4.  We're taking quite a lot of advantage of strapi components now and it'd be great to use semantic names -- however long they may be  -- for our content managers' sake.

**Comment by frn-dawn** [comment] 2022-03-11 08:49
> > @alexandrebodin Can it really be right that this issue is closed because an advanced manual CMS configuration can "solve" the problem before it occurs? As @ScottAgirs mentioned, naming is a core feature of CMS development, and is essential for usability. Especially when dealing with many different content types, are long-ish names (3 words are not unusual) common and necessary.
> > I don't see a case where it's natural for developers to remember to put shorter collection names in the Content-Types Builder's advanced tab.
> > As long as it's possible to crash the system by typing a name in the UI, this should be considered a bug.
> > Any chance there is something on the roadmap to fix this properly? I'm hesitant to use Strapi for professional projects if this type of issue is not taken seriously.
> > I hope to see a reaction to this, as I think Strapi is filling a gap in the market, and I want to be able to recommend it on client projects.
> 
> Hi, This will not be changed in v3 as it will pass in maintenance mode. However this will be reviewed for v4 to see what we can do about it

@alexandrebodin Any update here? Seems on the comment from @cupofnestor that the issue hasn't been addressed.

**Comment by derrickmehaffy** [comment] 2022-03-14 22:57
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
