### ISSUE TITLE
Tracking Issue: Relations/Media links lost when using transfer

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#17343] opened 2023-07-17 19:57 UTC
### Required System information

- Node.js version: v18
- NPM version: v8
- Strapi version: 0.0.0-experimental.e70c18d5ed73d87da88fe1cd5caaeebb863748b5 (based on https://github.com/strapi/strapi/tree/e70c18d5ed73d87da88fe1cd5caaeebb863748b5 but reproducible on all versions <=v4.11.5)
- Database: SQLite
- Operating system: Linux Mint 21.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When using the transfer option, file relationships and normal relations are not transfered for components, nested components, and dynamic zones.

### Steps to reproduce the behavior

Reproduction is complex, see this example code (contained is the media assets and database).

Example User on both applications:

```
email: test@test.com
pass: Test1234!
```

### Expected behavior

Relationships and media links should also be transfered

### Screenshots

Source application:
![image](https://github.com/strapi/strapi/assets/8593673/b1da3db4-8f97-412e-b376-b3f4ddb0b999)
![image](https://github.com/strapi/strapi/assets/8593673/4c1c8aae-ff60-4f1b-8247-136650ddacb7)

Destination application:
![image](https://github.com/strapi/strapi/assets/8593673/076bd901-181d-43a8-9f49-328d52fe49b3)
![image](https://github.com/strapi/strapi/assets/8593673/a08a4e39-e017-4cde-a564-8cdaa1b6ecae)

Logs from transfer (no errors)
![image](https://github.com/strapi/strapi/assets/8593673/2d4ec735-f085-4762-97eb-d191fdf04a2f)

Some snips of the destination database tables via dbeaver (relations were not transferred)
![image](https://github.com/strapi/strapi/assets/8593673/6fc18894-0c6f-4b22-99d9-ed4fcbb0ba2e)

Parent media relations were transferred but not components
![image](https://github.com/strapi/strapi/assets/8593673/0b0f6552-9018-4424-ae59-7ff66aa06df2)

Image from source project for example file_related_morphs
![image](https://github.com/strapi/strapi/assets/8593673/dd36c56e-5da9-44f6-bc61-b6a16a23d104)

### Code snippets

Example projects (both source and destination) including database and file uploads
[testDTS.zip](https://github.com/strapi/strapi/files/12073419/testDTS.zip)

### Additional context

This is a tracking issue combining all other data loss issues with the DTS , additional gh issues linked below that were closed during the making of this.

https://github.com/strapi/strapi/issues/16999
https://github.com/strapi/strapi/issues/16891
https://github.com/strapi/strapi/issues/16813
https://github.com/strapi/strapi/issues/16811

**Comment by derrickmehaffy** [comment] 2023-07-20 20:08
Raising severity per our internal escalation process for EE customers.

Related to internal TID4165

**Comment by 20x-dz** [comment] 2023-07-25 09:17
Happens also on transfers between postgres-backed instances as well as transfers from/to mac-based dev environments.
Exports are also affected and cannot be used after an import.

Last working export/import on v4.11.4 iirc (transfer was already broken in that version).

**Comment by erkandem** [comment] 2023-07-25 16:23
Also broken for strapicloud instances.

Have had relied on this export/import or transfer feature to follow the deployment workflow (develop locally -> push code and content & asset changes towards prod). Am very disapointed as to what V4.x means. Can't hide that. But still a thank you for developing this app, maintaining it and offering it us ... for free ❤️ !

Using Postgres as a DB, storing media "locally", MVP stage of the app.

I worked around this issue for now by: 
 - dropping the prod database ⚠️  and restoring it with local postgres dump (with all the caveats this has ☠️ )
 - copying the uploaded media files to the prod folder

Not sure though whether these  steps include all of which a export/import or transfer would include. 
Seemed to work. 🤷

**Comment by derrickmehaffy** [comment] 2023-07-25 22:28
Also related to internal TID3919 for an EE self-hosted customer

**Comment by derrickmehaffy** [comment] 2023-07-27 15:49
Experimental release: `0.0.0-experimental.b8add035057504e7feb472f8cc437c83b49e7268` for fix

**Comment by 20x-dz** [comment] 2023-07-27 21:58
Thx!

Tried to import a prod export (76,8MB).

Complained about schema integrity (which seems obvious, that's why an import is being run 😅 ) and the message is worded kind of weird imo:

> ? There are differences in schema between the source and destination, and the
data listed above will be lost. Are you sure you want to continue? (y/N)

Anyways, it failed to read metadata trying to import assets

```bash
⠼ assets: 0 transfered (size: 0) (elapsed: 0 ms)  Failed to read metadata for a_filename.svg, Strapi will try to fix this issue automatically
```

and lastly crashed with 

```bash
        convertedError = new KnexTimeoutError(
                         ^

KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Client_BetterSQLite3.acquireConnection (<redacted>/strapi-17343/transfer-test/node_modules/knex/lib/client.js:332:26)
    at async Runner.ensureConnection (<redacted>/strapi-17343/transfer-test/node_modules/knex/lib/execution/runner.js:305:28)
    at async Runner.run (<redacted>/strapi-17343/transfer-test/node_modules/knex/lib/execution/runner.js:30:19)
    at async Object.computeMetrics (<redacted>/strapi-17343/transfer-test/node_modules/@strapi/plugin-upload/server/services/metrics/weekly-metrics.js:50:7)
    at async Object.sendMetrics (<redacted>/strapi-17343/transfer-test/node_modules/@strapi/plugin-upload/server/services/metrics/weekly-metrics.js:93:21)
Emitted 'error' event on Job instance at:
    at <redacted>/strapi-17343/transfer-test/node_modules/node-schedule/lib/Invocation.js:277:17 {
  sql: undefined,
  bindings: undefined
}

Node.js v18.16.0
```

after 314324ms (~5 minutes).

Should we test transfer/import only between 2 instances on the same experimental version?

(and fwiw, `import --exclude` does not seem to work while `--only` does)

**Comment by derrickmehaffy** [comment] 2023-07-28 05:12
Yes for now only the experimental version will work

**Comment by Convly** [comment] 2023-07-28 08:50
> Complained about schema integrity (which seems obvious, that's why an import is being run 😅 ) and the message is worded kind of weird imo:
> 
> > ? There are differences in schema between the source and destination, and the
> > data listed above will be lost. Are you sure you want to continue? (y/N)

This message is about the fact that your production application apparently has a different structure compared to your local one (more content types maybe?) & some data won't be transferred since it cannot map it to your destination app's structure.
Interested in the feedback though, what do you think would be a better alternative in term of wording? :eyes: 

> 
> ```shell
> ⠼ assets: 0 transfered (size: 0) (elapsed: 0 ms)  Failed to read metadata for a_filename.svg, Strapi will try to fix this issue automatically
> ```

This one is only a warning. We made changes recently to support the transfer of assets between any upload providers (before it was only working for local files). This change contains a breaking change in the export file's structure, but we managed to find a way to handle old export files anyway so that old datasets are not lost. In order to provide as much information as possible, we decided to throw a warning anyway in case something breaks at this level.

> and lastly crashed with
> 
> ```shell
>         convertedError = new KnexTimeoutError(
>                          ^
> 
> KnexTimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
>     at Client_BetterSQLite3.acquireConnection (<redacted>/strapi-17343/transfer-test/node_modules/knex/lib/client.js:332:26)
>     at async Runner.ensureConnection (<redacted>/strapi-17343/transfer-test/node_modules/knex/lib/execution/runner.js:305:28)
>     at async Runner.run (<redacted>/strapi-17343/transfer-test/node_modules/knex/lib/execution/runner.js:30:19)
>     at async Object.computeMetrics (<redacted>/strapi-17343/transfer-test/node_modules/@strapi/plugin-upload/server/services/metrics/weekly-metrics.js:50:7)
>     at async Object.sendMetrics (<redacted>/strapi-17343/transfer-test/node_modules/@strapi/plugin-upload/server/services/metrics/weekly-metrics.js:93:21)
> Emitted 'error' event on Job instance at:
>     at <redacted>/strapi-17343/transfer-test/node_modules/node-schedule/lib/Invocation.js:277:17 {
>   sql: undefined,
>   bindings: undefined
> }
> 
> Node.js v18.16.0
> ```
> 
> after 314324ms (~5 minutes).

This one is annoying. If I remember correctly, SQLite doesn't handle 1 transaction + 1 external write/read concurrently (probably why the pool is full). From what I can read it could be due to another service executing a request at the same time. Does it happens again & again if you retry?
In any case, this alone should be a standalone issue :slightly_smiling_face: 

> Should we test transfer/import only between 2 instances on the same experimental version?

In theory, it _should_ work even from a previous version (even with warnings)
 
> (and fwiw, `import --exclude` does not seem to work while `--only` does)

Weird :thinking:, would you mind opening an issue with the faulty behavior you encountered?

**Closed** 2023-07-31 15:28 UTC
Labels: issue: bug, severity: critical, status: confirmed, flag: tracking issue, flag: EE, source: core:data-transfer

**Comment by DanielRoeven-Intunio** [comment] 2023-11-16 12:28
Sorry to comment on a closed issue, but I'm still able to reproduce this issue on `@strapi/strapi: 4.15.4`. 

If I read the [related pull request](https://github.com/strapi/strapi/pull/17475) correctly this has been fixed and released in version 4.12, so I'm stumped as to why this is still occurring. The behaviour we see matches _precisely_ with the bug described above.

**System information**
Node.js version: v18.16.1
NPM version: v9.5.1
Strapi version: 4.15.4
Database: SQLite OR Postgres, tested and reproduced on both.
Operating system: macOS
Is your project Javascript or Typescript: Typescript

Any clues on to how I might fix this? Are there any other experimental builds to try out?

**Comment by derrickmehaffy** [comment] 2023-11-16 13:38
> Sorry to comment on a closed issue, but I'm still able to reproduce this issue on `@strapi/strapi: 4.15.4`. 
> 
> If I read the [related pull request](https://github.com/strapi/strapi/pull/17475) correctly this has been fixed and released in version 4.12, so I'm stumped as to why this is still occurring. The behaviour we see matches _precisely_ with [this bug report](https://github.com/strapi/strapi/issues/16813). Since that thread is locked and this is the tracking issue, I thought I'd post here 🙂 
> 
> **System information**
> Node.js version: v18.16.1
> NPM version: v9.5.1
> Strapi version: 4.15.4
> Database: SQLite OR Postgres, tested and reproduced on both.
> Operating system: macOS
> Is your project Javascript or Typescript: Typescript
> 
> Any clues on to how I might fix this? Are there any other experimental builds to try out?
> 
> EDIT:
> 
> Might not be precisely the same cause, despite manifesting as the same behaviour / bug. It appears that running `npm run strapi import` _several times in a row_ solves the issue. Most often running the `npm run strapi import` command twice correctly populates media inside components. Sometimes twice is not enough and it needs to be run three times.
> 
> Regardless, it seems that the data is being exported to the `.tar.gz` archive at least. It's the importing step where it goes wrong. Reimporting several times solves the problem.
> 
> Let me know if I should open a new bug report for this @derrickmehaffy?

Please open a new bug report

**Comment by 20x-dz** [comment] 2023-11-16 17:38
@DanielRoeven-Intunio Yeah, transfer broke again somewhere in 4.13.x or 4.14.x (and didn't work at all in other cases see e.g. #17557).

**Comment by danielshawellis** [comment] 2024-01-10 19:24
I'm still seeing this issue when using `strapi transfer` on Strapi version **4.17.0** for file relationships (specifically image files in my case) within components. As an attempted work-around I tried running `strapi export` and `strapi import`, but that yielded the exact same problem behavior.

**Comment by mohammed-shameem** [comment] 2024-02-13 07:32
Can anyone mention which version have a fix for this ?

**Comment by TheBoltThrower** [comment] 2024-02-13 08:23
Have the same problem as @danielshawellis, can we get more information on how to fix it or some information when the bug will be resolved?
