### ISSUE TITLE
Strapi 5 (beta 17) creating a simple component breaks the server

### ISSUE THREAD

**Issue by AleksDrop** [strapi/strapi#20631] opened 2024-06-26 05:58 UTC
### Required System information

- Node.js version: 20.14
- NPM version: 10.7
- Strapi version: 5.0.0-beta.17
- Database: SQLite
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Creating a simple component with 2 text fields causes an error:
\ Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                         │
│   TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined                                      │
│       at Object.join (node:path:433:7)                                                                                                  │
│       at D:\Code\Droplet\Strapi\betalatest\node_modules\@strapi\core\dist\loaders\components.js:17:31                                   │
│       at Array.forEach (<anonymous>)                                                                                                    │
│       at D:\Code\Droplet\Strapi\betalatest\node_modules\@strapi\core\dist\loaders\components.js:14:32                                   │
│       at Array.reduce (<anonymous>)                                                                                                     │
│       at loadComponents (D:\Code\Droplet\Strapi\betalatest\node_modules\@strapi\core\dist\loaders\components.js:13:39)                  │
│       at async Promise.all (index 5)                                                                                                    │
│       at async Module.loadApplicationContext (D:\Code\Droplet\Strapi\betalatest\node_modules\@strapi\core\dist\loaders\index.js:12:3)   │
│       at async Object.register (D:\Code\Droplet\Strapi\betalatest\node_modules\@strapi\core\dist\providers\registries.js:26:5)          │
│       at async Strapi.register (D:\Code\Droplet\Strapi\betalatest\node_modules\@strapi\core\dist\Strapi.js:322:7)                       │
│                                                                                                                         

### Steps to reproduce the behavior

1. npx create-strapi-app@beta betalatest --quickstart
2. Start the admin panel
3. Create a simple component with 2 text fields
4. Get the error on reload (see above)

### Expected behavior

This is a super basic operation and should just work

**Comment by AleksDrop** [comment] 2024-06-26 12:19
This issue seems to be related or duplicate: [https://github.com/strapi/strapi/issues/20638](https://github.com/strapi/strapi/issues/20638)

**Comment by Convly** [comment] 2024-06-26 12:31
Closing as duplicate of https://github.com/strapi/strapi/issues/20057
Please add any relevant information regarding your setup there

**Closed by Convly** 2024-06-26 12:31 UTC
Labels: status: duplicate
