### ISSUE TITLE
SqliteError: unable to open database file (Strapi v5 beta)

### ISSUE THREAD

**Issue by boris-schwarz** [strapi/strapi#20530] opened 2024-06-16 13:55 UTC
## Bug report
Strapi v5 beta does not start after a fresh installation.

### Required System information
- Node.js version: v20.14.0
- NPM version: 10.4.0
- Strapi version: 5.0.0-beta.10
- Database: sqlite
- Operating system: win32-x64 - Microsoft Windows 11 Pro, 10.0.22631 Build 22631
- Is your project Javascript or Typescript: Typescript

<details>
  <summary>Strapi Report</summary>
  <ul>
  </ul>
    <li>Launched In: 415 ms</li>
    <li>Environment: development</li>
    <li>OS: win32-x64</li>
    <li>Strapi Version: 5.0.0-beta.10</li>
    <li>Node/Yarn Version: npm/10.4.0 node/v20.14.0 win32 x64 workspaces/false</li>
    <li>Edition: Community</li>
    <li>Database: sqlite</li>
</details>

### Describe the bug

The installation fails because `ajv/dist/core` could not be installed. 
Fixing this by running `npm install` results in a subsequent error:
```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                               │
│   SqliteError: unable to open database file                                                                   │
│   at new Database (C:\db\my-project-name-here\node_modules\better-sqlite3\lib\database.js:69:26)              │
│   at Client_BetterSQLite3.acquireRawConnection                                                                │
│   (C:\db\my-project-name-here\node_modules\knex\lib\dialects\better-sqlite3\index.js:14:12)                   │
│   at create (C:\db\my-project-name-here\node_modules\knex\lib\client.js:262:39)                               │
│                                                                                                               │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```
(tl;dr this is because `DATABASE_FILENAME` in the .env file is empty, see [Possible solutions](#possible-solutions))

### Steps to reproduce the behavior

1. Create new project with `npx create-strapi-app@beta my-project-name-here --quickstart`
2. The installation will not be successful because **ajv/dist/core** could not be installed:
```
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module 'ajv/dist/core'

[...]

- C:\db\my-project-name-here\node_modules\@strapi\strapi\bin\strapi.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\db\my-project-name-here\node_modules\ajv-draft-04\dist\index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19) {
  code: 'MODULE_NOT_FOUND',
```
3. Either run `npm install` or `npm i ajv-draft-04` to fix the missing dependency (both result in the same upcoming behaviour).
4. After that, either run `npm run development` or `npm run build`
5. Both ouput the following error (as mentioned above):
```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                               │
│   SqliteError: unable to open database file                                                                   │
│   at new Database (C:\db\my-project-name-here\node_modules\better-sqlite3\lib\database.js:69:26)              │
│   at Client_BetterSQLite3.acquireRawConnection                                                                │
│   (C:\db\my-project-name-here\node_modules\knex\lib\dialects\better-sqlite3\index.js:14:12)                   │
│   at create (C:\db\my-project-name-here\node_modules\knex\lib\client.js:262:39)                               │
│                                                                                                               │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

### Expected behavior

I expect Strapi to build and see the admin panel, where I can create the admin account.

### Additional context

1. This is the `database` part of my .env file, I have not tinkered with it and have never tinkered with it in previous versions:
```
# Database
DATABASE_CLIENT=sqlite
DATABASE_FILENAME=
```
2. I have tried to give full admin rights to my local windows account to C:\db\my-project-name-here\node_modules\better-sqlite3\lib\database.js

# Possible solutions
Make sure `DATABASE_FILENAME` in your .env file is not empty. You can set it to `your-project-name.sqlite`, it might be something the Strapi Installer would do by itself, if it didn't stop because of the `ajv/dist/core` error. This is also why I will submit this bug, for others to find and for the team to look into it, even if an `npm install` error happens.

Cheers, Boris

**Comment by reslear** [comment] 2024-07-02 05:17
Same problem:
node 18/20 
strapi 4.25.1

**Comment by derrickmehaffy** [comment] 2024-07-23 21:10
Can't reproduce in rc.6 closing

**Closed by derrickmehaffy** 2024-07-23 21:10 UTC
Labels: issue: bug, severity: high, source: core:database, status: pending reproduction, version: 5, source: core:core
