### ISSUE TITLE
Upgrade from 4.13 to 4.14, in typescript, fundamentally changed and breaks core features of data management

### ISSUE THREAD

**Issue by woodyjon** [strapi/strapi#18317] opened 2023-10-05 13:11 UTC
I have a big backend running on strapi. Was running fine on 4.13, in typescript. Upgrading to 4.14 creates a ton of errors because of the types.

I am working with interfaces that look like this:
```
export interface IBatchBase {
  id?: number;

  type: BatchType;

  batchNumber?: string;
  material: IMaterial;
  openedAt: string;
  closedAt?: string;
  openedBy?: IUser;
  closedBy?: IUser;

  batchLines: IBatchLine[];
  flags?: IFlag[];
}

export interface IBatchRework extends IBatchBase {
  type: BatchType.rework;
  reasonForMovement?: IReasonForMovement;
}
```
Those interfaces were compatible with the strapi api and I could find items or create and update items. But moving to 4.13, my types are incompatible with the types expected by strapi. I have a lot of errors like:
```
 error TS2339: Property 'material' does not exist on type 'GetValues<"api::batch.batch", GetNonPopulatableKeys<"api::batch.batch">>'.

548     if (batch.material.pkgType !== PkgType.SS) {
```
```
error TS2339: Property 'flags' does not exist on type 'GetValues<"api::batch.batch", GetNonPopulatableKeys<"api::batch.batch">>'.

490         batch.flags.push(flag);
```
```
error TS2322: Type '{ type?: BatchType.rework; reasonForMovement?: IReasonForMovement; id?: number; batchNumber?: string; material?: IMaterial; openedAt?: string; closedAt?: string; openedBy?: IUser; closedBy?: IUser; batchLines?: IBatchLine[]; flags?: IFlag[]; }' is not assignable to type 'Input<"api::batch.batch">'.
  Type '{ type?: BatchType.rework; reasonForMovement?: IReasonForMovement; id?: number; batchNumber?: string; material?: IMaterial; openedAt?: string; closedAt?: string; openedBy?: IUser; closedBy?: IUser; batchLines?: IBatchLine[]; flags?: IFlag[]; }' is not assignable to type 'OmitRelationWithoutTarget<"api::batch.batch", { material?: ID; type?: "regular" | "rework"; comment?: string; createdAt?: DateTimeValue; updatedAt?: DateTimeValue; createdBy?: ID; ... 11 more ...; flags?: ID[]; } & {}>'.
    Types of property 'material' are incompatible.
      Type 'IMaterial' is not assignable to type 'ID'.

444         data: {

const ret = await strapi.entityService
      .create("api::batch.batch", {
        data: {
          ...batch,
        },
        populate: strapi.service("api::batch.batch").getFullPopulateObject(),
      })
      .catch(console.error);
``` 
It seems Strapi was returning full hierarchy of objects, now it is just returning ids of linked objects.

**Comment by Convly** [comment] 2023-10-05 14:16
Hello, thanks for opening the issue, happy to try to help you with that.

It seems that populate doesn't understand what fields are returned by `getFullPopulateObject()` and thus doesn't add anything to the final object.

Out of curiosity what's the return type of this method?

ps: Previously they were compatible because they weren't typed at all (`any`)

**Comment by woodyjon** [comment] 2023-10-05 15:39
Hello.

Thanks.

This is my getFullPopulateObject() service:

```
getFullPopulateObject() {
    return {
      material: true,
      scaleReadings: {
        populate: strapi.service("api::scale-reading.scale-reading").getFullPopulateObject(),
      },
      flags: {
        populate: strapi.service("api::flag.flag").getFullPopulateObject(),
      },
      batchLines: {
        populate: strapi.service("api::batch-line.batch-line").getFullPopulateObject(),
      },
    };
  },
```

It is just using populate true and that normal kind of things. The normal format expected by populate.

**Comment by woodyjon** [comment] 2023-10-06 11:27
OK, I understand. But everything working fine, then many things not working anymore after an upgrade, I would love some explanation of what was changed and why. I am not the only one who will face those issues after the upgrade, I am guessing.

**Comment by Convly** [comment] 2023-10-06 11:51
I'm wondering what improvement could be done to fix things here.

Do you have access to the inferred return type of getFullPopulateObject? I'm trying to understand if it resolves to a wider type or if it keeps a literal object representation of your object.

Also, in the event where there is a value for the populate but it's not recognized by the type handler, I'm wondering if we should interpret that as either "all populatable keys" or "no populatable keys"

**Comment by woodyjon** [comment] 2023-10-06 12:04
Actually I don't think I have any issue with the populate. I am just using normal format and there is no issue there.
The issue is that it does not like my types, that are simpler than the one automatically generated by strapi, and that used to work perfectly before 4.14.

It seems the strapi api now expects types that are like:
```
{
    id: 
    attributes: {
        attribute1:
        attribute2:
    }
}
```
but it used to work with types like:
```
{
    id:
    attribute1:
    attribute2:
}
```

**Comment by Convly** [comment] 2023-10-06 12:25
```
 error TS2339: Property 'material' does not exist on type 'GetValues<"api::batch.batch", GetNonPopulatableKeys<"api::batch.batch">>'.

548     if (batch.material.pkgType !== PkgType.SS) {
```

```
error TS2339: Property 'flags' does not exist on type 'GetValues<"api::batch.batch", GetNonPopulatableKeys<"api::batch.batch">>'.

490         batch.flags.push(flag);
```

Tells you that the returned entities don't contain the `material` and `flags` attributes.

Based on the definition of you `getFullObjectPopulate`, it looks like those are populatable attributes (**relations**, **components**, **dynamic zones**, or **media**).

Those kinds of fields are dynamically added to the result entities based on your query (`populate`)

If you say `populate: 'material',` you should get the autocomplete for it in the returned entities, same for `flags`. Hence the questions about the return type of the getPopulate method, because based on the given definition, it should work as intended.

>It seems the strapi api now expects types that are like:
>```
>{
>    id: 
>    attributes: {
>        attribute1:
>        attribute2:
>    }
>}

I'm really not sure how you've come to encounter this, attributes shouldn't be part of any internal API, especially not around the entity service.

**Comment by woodyjon** [comment] 2023-10-06 15:08
I made a minimal project to illustrate a part of what does not work anymore in my code with versions above 4.13.6.

I have 2 collection types, CollectionA and CollectionB. Those are my types:
```
export interface CollectionA {
    id?: number;
  
    textFieldA?: string;
    collectionB?: CollectionB;
  }

export interface CollectionB {
    id?: number;
  
    textFieldB?: string;
  }
```

This is a simple controller example for CollectionA:
```
/**
 * collectiona controller
 */

import { factories } from '@strapi/strapi';
import { CollectionA, CollectionB } from '../../types';

export default factories.createCoreController('api::collectiona.collectiona', ({ strapi }) => ({
    async create(ctx) {
      // collectionB item with id 1 already exists in the database
      const collectionB: CollectionB = {
        id: 1,
      };
      const newCollectionA: CollectionA = {
        textFieldA: "Hey",
        collectionB: collectionB,
      }
      const createdItem = await strapi.entityService
      .create("api::collectiona.collectiona", {
        data: {
          ...newCollectionA,
        },
        populate: {
          collectionB: true,
        },
      })
      .catch(console.error);

      return createdItem;
    },
  }));
  ```

With v 4.13.6, this works fine. And when I call create, I get this returned value:
```
{
      "id": 2,
      "textFieldA": "Hey",
      "createdAt": "2023-10-06T15:00:33.718Z",
      "updatedAt": "2023-10-06T15:00:33.718Z",
      "collectionB": {
        "id": 1,
        "textFieldB": "hey1",
        "createdAt": "2023-10-06T14:54:08.339Z",
        "updatedAt": "2023-10-06T14:54:28.658Z"
      }
    }
```

But with 4.14, I have following error:
```
src/api/collectiona/controllers/collectiona.ts:19:9 - error TS2322: Type '{ id?: number; textFieldA?: string; collectionB?: CollectionB; }' is not assignable to type 'Input<"api::collectiona.collectiona">'.
  Type '{ id?: number; textFieldA?: string; collectionB?: CollectionB; }' is not assignable to type 'OmitRelationWithoutTarget<"api::collectiona.collectiona", { textFieldA?: string; collectionB?: ID; createdAt?: DateTimeValue; updatedAt?: DateTimeValue; createdBy?: ID; updatedBy?: ID; } & {}>'.
    Types of property 'collectionB' are incompatible.
      Type 'CollectionB' is not assignable to type 'ID'.

19         data: {
           ~~~~

  node_modules/@strapi/types/dist/modules/entity-service/params/index.d.ts:108:13
    108             data?: Data.Input<TSchemaUID>;
                    ~~~~
    The expected type comes from property 'data' which is declared here on type '{ fields?: Any<"api::collectiona.collectiona">; } & { populate?: Any<"api::collectiona.collectiona">; } & { data?: Input<"api::collectiona.collectiona">; } & { files?: Record<...>; }'

Found 1 error(s).
```

**Comment by Adaphath** [comment] 2023-10-09 07:24
Hey there,
I had my problems with 4.14 too but after a few hours I got the hang of it.

I also used custom types for my collections and tried to create data with it.
To ensure compatibility with the new types I extended my custom types with the Strapi entities:
```typescript
import { Entity } from '@strapi/types/dist/modules/entity-service/index';
export interface CollectionA extends Entity<'api::collectiona.collectiona'> {
  // my old interface definition for faster rollback and testing
}
```

You can now use it as a result type when using the entity service (find, findMany).
```typescript
const result = strapi.entityService.findMany('api::collectiona.collectiona', {});
```
`result` now has the same fields as `CollectionA` and you can use it as the type. I used it to only change my types and not change my whole code basis.


To use the types as Input for `entityService.create` you have to use the `Input<'api::collectiona.collectiona'>` type.
This allows the creation of objects with references to other collections by strings, etc.
In your example:
```typescript
import { Input } from '@strapi/types/dist/modules/entity-service/params/data';

const newCollectionA: Input<'api::collectiona.collectiona'>= {
  textFieldA: "Hey",
  collectionB: <id of collection B>,
}
const createdItem = await strapi.entityService
.create("api::collectiona.collectiona", {
  data: {
    ...newCollectionA,
  },
  populate: {
    collectionB: true,
  },
})
```

I didn't test it on my machine but this should work.
If you have any further questions you can drop me an email.

**Comment by woodyjon** [comment] 2023-10-09 07:59
Thanks. Will try that. Makes sense. The collection extending the Strapi entity is nice.
It still feels a bit a pity that we have to create a different object with a different type to input for create and update.
Cheers.

**Comment by OneTechSavvy** [comment] 2023-10-09 18:00
No guide for this?

**Comment by Adaphath** [comment] 2023-10-10 08:57
> No guide for this?

Atleast I could not find one. The developer docs do not cover this and the contributor docs just state 'Coming soon'.

@Convly I would like to help write some guides for the typescript topic. But I think I'm still missing your 'official' way of doing typescript things

**Comment by SimonStorlSchulke** [comment] 2023-10-27 13:50
> No guide for this?

Just wanted to bump this. Seing your whole strapi-codebase break like that (with a minor version upgrade) and not being able to find any information about it (despite now this thread) is not a pleasant experience. I't be better to only ship such breaking changes when there is a good documentaion and migration guide for it. Apart from that, it's actually nice to see to get better typescript support.

**Comment by Convly** [comment] 2023-11-15 07:49
> It seems like the data property is indeed missing the { id: ID } for regular relation (right now it only accepts a regular ID).

> We'll also need to handle object-shape for polymorphic links.

> I'll add that to our backlog.

This hasn't been forgotten.

> I would like to help write some guides for the typescript topic. But I think I'm still missing your 'official' way of doing typescript things

Hey, thank you for your interest, we should _soon_ start writing guides on how to work with Strapi types. We are just waiting a bit more to stabilize the APIs and make sure we won't introduce breaking changes after documenting the usage.

> Just wanted to bump this. Seing your whole strapi-codebase break like that (with a minor version upgrade) and not being able to find any information about it (despite now this thread) is not a pleasant experience

I know it can be (very) frustrating, but we had to make a decision at some point in order to move forward with the topic and start improving things. The lack of documentation for this is a serious issue that we have in our backlog. Even though I cannot guarantee a precise ETA, I wanted to guarantee that this is not a topic lost at the bottom of our priorities.

> Apart from that, it's actually nice to see strapi getting better typescript support.

Thanks, really appreciate it.

**Comment by blakerunyon09** [comment] 2023-11-21 20:12
Yea this actually sucks as a dev experience. Went to update from 4.11 to 4.15, and I'm met with over 300 errors. Spent a good majority of the day fixing all these. You shouldn't need to a typescript power user to be able to update a minor version of strapi.

**Comment by woodyjon** [comment] 2023-11-22 08:46
> Yea this actually sucks as a dev experience. Went to update from 4.11 to 4.15, and I'm met with over 300 errors. Spent a good majority of the day fixing all these. You shouldn't need to be a typescript power user to be able to update a minor version of strapi.

If you can share the approach you took to solve those issues, that would be nice.
I am postponing my upgrade of strapi until I have a lot of available time and a better vision on how to do it.

**Comment by OneTechSavvy** [comment] 2023-11-22 18:26
Don't worry.
I fixed that issue in 10mins manually.
A simple minor change leads to fixing dozens of errors.

**Comment by AdrianFahrbach** [comment] 2023-11-24 15:16
I'm currently working on updating to 4.14 as well and I agree with the others who say that this feels like a breaking change, a huge part of that is that we got our own types in place though. I still think that the types improved in this updated and are a bit more clearer then before. Once you get a hang of it, it kind of works.

However, I would like to add that I'm not a fan of your typescript implementation. It feels like going from one extreme (no types) to the other (super complicated types).
You have to be a typescript power user and worked with Strapi types before to fully get along with this. I mean just take a look at [the attributes utils file](https://github.com/strapi/strapi/blob/8811cfafd27e6318bde3951dadbe45dfe1acbce3/packages/core/types/src/types/core/attributes/utils.ts) (its minified in the package). How am I supposed to understand whats going on here?

It is cool that e.g. the entity service will check for population options, but if the trade off for stuff like that is that I can't let a junior dev make any type changes related to Strapi, then it is not the right way for me.

**Comment by Convly** [comment] 2023-12-21 13:10
Hey everyone, the relation's fix was released yesterday at part of https://github.com/strapi/strapi/releases/tag/v4.16.0.

I'm gonna close this as the original issue should be fixed now.

Thanks for all the opinions expressed in the thread, they've been shared internally :slightly_smiling_face:

**Closed by Convly** 2023-12-21 13:10 UTC
Labels: issue: bug, severity: low, status: confirmed, source: typescript

**Comment by OneTechSavvy** [comment] 2023-12-21 14:09
Thank you.
This would be beneficial for all Strapi developers.

The website develop.mystrapisite.com/admin is displaying a 502 error.
I dedicated a week to resolve this issue.
Could you please inform me about the cause of this error and provide
guidance on how to resolve it?
Thank you once again.
