### ISSUE TITLE
Rename column in SQLite prevents server start

### ISSUE THREAD

**Issue by shannonarcher** [strapi/strapi#2998] opened 2019-03-19 15:53 UTC
**Informations**
- **Node.js version**: 10.13.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: SQLite
- **Operating system**: Ubuntu 16.04

**What is the current behavior?**
Changing the case of the name of a content type property will cause migration and therefore server start up to fail.

**Steps to reproduce the problem**
1. Create a content type with property Title
2. Save
3. Rename property Title to title
4. Save
5. Restart the strapi server, error log will report Duplicate column name and bookshelf will timeout.

**What is the expected behavior?**
Changing the case of a content type property name should be migrated in the database successfully.

**Suggested solutions**
Use SQLite's `Rename Column` feature instead to rename the column instead of creating a new column with the same name.

OR

Create a check when editing content type properties that doesn't allow the user to edit a property name to a value that is case-insensitively identical to an existing property title.

**Comment by lauriejim** [comment] 2019-03-21 14:42
Hello @shannonarcher !
Thank you for this report!

Can you investigate on this issue please. Find the best way to manage this case. 
We will appreciate your contribution on this issue.

**Comment by tshelver** [comment] 2019-03-22 10:33
Sounds like the same thing I experienced,

**Comment by shannonarcher** [comment] 2019-03-22 20:51
Can do @lauriejim

**Comment by steveafrost** [comment] 2019-04-04 00:16
Possible this has to do with unique columns, as I just ran into a similar issue.

**Comment by maxcoffer** [comment] 2019-04-07 03:23
I meet the same issue just now using MongoDB: renamed field name from "Title" to "title", then Strapi server goes down and can't run anymore. Deployed at DigitalOcean on Ubuntu.

`(node:16191) UnhandledPromiseRejectionWarning: Error: SQLITE_ERROR: duplicate column name: title
    at Client_SQLite3._query (/root/strapi/cms/node_modules/knex/lib/dialects/sqlite3/index.js:108:12)
    at Client_SQLite3.query (/root/strapi/cms/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/root/strapi/cms/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /root/strapi/cms/node_modules/knex/lib/runner.js:47:21
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:120:23)
From previous event:
    at Runner.run (/root/strapi/cms/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/root/strapi/cms/node_modules/knex/lib/interface.js:23:43)
(node:16191) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16191) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-04-07T03:15:52.850Z] debug ⛔️ Server wasn't able to start properly.
[2019-04-07T03:15:52.852Z] error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load`

**Comment by lastavenka** [comment] 2019-04-20 12:32
Have the same issue

**Comment by Dzheky** [comment] 2019-04-20 15:30
had the same error
```[2019-04-20T15:25:49.917Z] debug ⛔️ Server wasn't able to start properly.
[2019-04-20T15:25:49.922Z] error
                        CREATE TABLE `tmp_games` (
                          id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
`id` varchar(255)  NULL ,
`name` varchar(255)  NULL ,
`url` varchar(255)  NULL ,
`created_at` timestamp DEFAULT CURRENT_TIMESTAMP  NULL ,
`updated_at` timestamp DEFAULT CURRENT_TIMESTAMP  NULL
                        )
                       - SQLITE_ERROR: duplicate column name: id
{ Error: SQLITE_ERROR: duplicate column name: id
    at Client_SQLite3._query (/root/dev/cms/node_modules/knex/lib/dialects/sqlite3/index.js:108:12)
    at Client_SQLite3.query (/root/dev/cms/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/root/dev/cms/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /root/dev/cms/node_modules/knex/lib/runner.js:47:21
    at processImmediate (internal/timers.js:443:21)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at Runner.run (/root/dev/cms/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/root/dev/cms/node_modules/knex/lib/interface.js:23:43) errno: 1, code: 'SQLITE_ERROR' }```

**Comment by leanderlindahl** [comment] 2019-04-21 14:54
I have the same issue when renaming "Title" to "title"...

**Comment by ca-miked** [comment] 2019-04-30 00:50
Experiencing same issue.

**Comment by ca-miked** [comment] 2019-04-30 17:46
Is there any know fix for this or do i have to nuke the entire thing and start over?

**Comment by ca-miked** [comment] 2019-04-30 17:46
Is it worth trying to go into mongodb directly to rename/remove the old column?

**Comment by derrickmehaffy** [comment] 2019-04-30 18:05
@ca-miked going from SQLite to Mongo you would have to completely regenerate all your models
The templates are different between Mongoose and Bookshelf.

SQLite to MySQL or Postgres works fine

**Comment by ca-miked** [comment] 2019-04-30 18:20
Apologies - that was a typo. I edited my message above to SQLite

**Comment by ca-miked** [comment] 2019-04-30 18:22
I'm looking at the SQLite directly and there are no duplicate columns. Was the rename operation cached so it attempts to re-run every time i fire up strapi

**Comment by mhowey-gr8** [comment] 2019-05-02 19:24
I also have run into this issue...I changed some column names, and tried to restart strapi and get...

[2019-05-02T19:24:12.161Z] debug ⛔️ Server wasn't able to start properly.
[2019-05-02T19:24:12.162Z] error ALTER TABLE `employers` ADD `CurrentEmployer` boolean  NULL ; - SQLITE_ERROR: duplicate column name: CurrentEmployer
{ Error: SQLITE_ERROR: duplicate column name: CurrentEmployer
    at Client_SQLite3._query (/Users/mhowey/projects/strapi-backend/node_modules/knex/lib/dialects/sqlite3/index.js:108:12)
    at Client_SQLite3.query (/Users/mhowey/projects/strapi-backend/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/Users/mhowey/projects/strapi-backend/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /Users/mhowey/projects/strapi-backend/node_modules/knex/lib/runner.js:47:21
    at processImmediate (internal/timers.js:443:21)
    at process.topLevelDomainCallback (domain.js:136:23)
From previous event:
    at Runner.run (/Users/mhowey/projects/strapi-backend/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/Users/mhowey/projects/strapi-backend/node_modules/knex/lib/interface.js:23:43) errno: 1, code: 'SQLITE_ERROR' }

**Comment by Carlows** [comment] 2019-05-13 23:41
Same issue, is there a workaround to get the database into a correct state?

Also, is this actively being worked on? Or is there any context to try fix it with a PR?

**Comment by rafamedina** [comment] 2019-05-14 21:13
Essentially, I modified the data table in sqlite by hand,
It is in <project folder>\.tmp
Removed the renamed column (with the old name) and run the project again and worked
Of course, in my case, I don't care about the data in that column

**Comment by guptasanchit90** [comment] 2019-06-27 13:46
If you are stuck after trying to change the filed name, try to change it back to the original name in api/<model>/models/<model>.setting.json
Then re-start your strapi server.

**Comment by michailb** [comment] 2019-06-29 09:21
Had the same issue and used the workaround below:

1. Open cms/.tmp/data.db and edit the column names (eg. "Title" to "title")
2. Open cms/api/models/Article.settings.json and edit the column name in "attributes" to match the above changes.

**Comment by Jeromche** [comment] 2019-08-01 18:33
Having the same issue when changing from uppercase to lowercase. Database used is Sqlite.

**Comment by barbgegrasse** [comment] 2019-08-30 14:21
I had the same issue...

**Closed** 2019-09-09 11:32 UTC
Labels: priority: high, status: confirmed, type: bug 🐛

**Comment by Pluto8195** [comment] 2019-11-28 06:45
> If you are stuck after trying to change the filed name, try to change it back to the original name in api//models/.setting.json
> Then re-start your strapi server.
> 
> You can do it twice to so that you can setup the desired column name.

This did it, answer thank you!

**Comment by fusepilot** [comment] 2020-01-25 02:14
Still an issue. I don't think this should have been closed.

**Comment by alexandrebodin** [comment] 2020-01-27 09:26
> Still an issue. I don't think this should have been closed.

This issue is outdated and was fixed in priori versions. If you are still having issue please open a new issue with your vonfiguration ifnromations :)

**Comment by pittersnider** [comment] 2020-03-27 21:20
I have the same issue.

**Comment by pittersnider** [comment] 2020-03-27 21:20
@alexandrebodin just downloaded this framework today with most recent version and this is still a problem. :/

**Comment by ledenis** [comment] 2020-03-29 19:38
Same issue reproduced today

**Comment by alexandrebodin** [comment] 2020-03-30 07:01
The issue is coming from knex implementation. We made a fix there that was merged in https://github.com/knex/knex/blob/master/CHANGELOG.md#0202---14-november-2019.

You can try upgrading the knex version you have in your package and verify it is fixed. We will upgrade the dependencies on project creation soon. We were waiting for bookshelf to upgrade first.

**Comment by shamim-42** [comment] 2020-03-30 10:09
Samething in mysql database
