### ISSUE TITLE
Class constructor ApolloError

### ISSUE THREAD

**Issue by XanderD99** [strapi/strapi#12622] opened 2022-02-22 11:07 UTC
### Describe the bug

When making a mutation using graphql an unexpected error occurs when the data is not valid. This error occurs using apollo client and with an axios post request.

### Steps to reproduce the behavior

1. Create number field with minimum validation (eg. sum field with minimum value 10)
2. Sent graphql mutation with invalid data (eg. sum field value 5)
3. Get error `Class constructor ApolloError cannot be invoked without 'new'`

### Expected behavior

The expected behavior is to get the same error message in my consumer that is logged in the Strapi backend being: `min_frequency must be greater than or equal to 10` 

### System

- Node.js version: v16.13.1
- NPM version: v8.1.2
- Strapi version: v4
- Database: postgres
- Operating system: linux

**Comment by Convly** [comment] 2022-02-22 11:24
Hi, thanks for opening the issue. I've spotted a missing `new` call in the error formatting. However, after fixing it I realized I wasn't able to reproduce your initial issue even without the fix I've made. Can you give me more information about the Strapi version you're on (4.x.x)?

**Comment by Convly** [comment] 2022-02-22 11:30
Tested on a brand new application (v4.1.0) and couldn't reproduce
![image](https://user-images.githubusercontent.com/25851739/155123456-b04e7bc8-a36b-445c-8551-23721c14d8e3.png)

**Comment by XanderD99** [comment] 2022-02-22 13:52
I am currently on strapi 4.0.7 and below is the output of my graphql

```js
 "dependencies": {
    "@strapi/plugin-documentation": "^4.0.7",
    "@strapi/plugin-graphql": "^4.0.7",
    "@strapi/plugin-i18n": "4.0.7",
    "@strapi/plugin-users-permissions": "4.0.7",
    "@strapi/strapi": "4.0.7",
    "pg": "^8.7.3",
    "strapi-plugin-transformer": "^1.0.3"
  },
```

![image](https://user-images.githubusercontent.com/36887752/155145767-92b0ecf5-ea48-456f-abd8-b7b867bad603.png)

**Comment by Convly** [comment] 2022-02-22 15:45
Alright, looks like v4.1.0 prevents the issue from happening by capturing it early and transforming it to a validation error. However, the issue is still valid & should be fixed by the PR mentioned above.

Thanks for your inputs :slightly_smiling_face:

**Closed** 2022-02-23 11:02 UTC
Labels: issue-type: bug, severity: low, source: plugin:graphql, status: pending reproduction
