### ISSUE TITLE
Controller and Services overriding capabilities do not work anymore

### ISSUE THREAD

**Issue by jmchza** [strapi/strapi#4855] opened 2019-12-30 06:32 UTC
**Describe the bug**
Following the guide for overriding a controller or service by copying and paste the examples from the documentation does not override the default ones from ContentManager plugin.

Guys this is a very old feature and it we break things like this one, people will loose credibility in what Strapi is doing.
I hope this is something stupid and not a major one. 

**Steps to reproduce the behavior**
1. creata a new content type though the content type builder on the admin console
2. copy and paste the controller example like update from documentation page and restart the server
3. set a break point if debugging and it always lands on the ContentManager instead.

**Expected behavior**
Use my own controller and service instead.

**Code snippets**
```async update(ctx) {
        let entity;
        if (ctx.is('multipart')) {
          const { data, files } = parseMultipartData(ctx);
          entity = await strapi.services.restaurant.update(ctx.params, data, {
            files,
          });
        } else {
          entity = await strapi.services.restaurant.update(
            ctx.params,
            ctx.request.body
          );
        }
    
        return sanitizeEntity(entity, { model: strapi.models.restaurant });
      },
```

**System**
- Node.js version: 12.3.1  
- NPM version: 6.12.1
- Strapi version: 3.0.0-beta.18.2 
- Database: mysql
- Operating system: Windows 10

**Additional context**

**Comment by derrickmehaffy** [comment] 2019-12-30 06:42
@jmchza the adminUI has it's own internal API that doesn't use the generated controllers that you see in the API folder (It has been this way for the better part of the past 2 years)

**Comment by derrickmehaffy** [comment] 2019-12-30 06:43
CTM Controllers: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/controllers/ContentManager.js

CTM Services: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/services/ContentManager.js

**Comment by jmchza** [comment] 2019-12-30 06:53
hi @derrickmehaffy thanks for your prompt response.

I was about to update this with the discovery that only the admin console is the one that deos not trigger the overrides. at which point I realized the admin uses its own controllers as you well did point out here.
So if I want to use the admin console but the back-end is quite customized. i.e things like id not being integer instead varchar in the DB.
Would I be able to override this internal behavior of the admin console ? 
Or this is condition enough for me to write my own admin console ?  

Thanks.

**Comment by derrickmehaffy** [comment] 2019-12-30 07:16
There are parts that can be done like that sure it would likely require quite a bit of customization for the moment (speaking directly about a UUID instead of a typical ID) The separation between the admin and the generated routes is very much intended as your users may need something entirely different than say your admins or content-creators (this was the reasoning behind it)

Honestly it's up to you on if you needed to build your own admin panel, in my mind it depends on the use-case and intended purpose.

On a side note, I'm going to go ahead and close this since we both agree it's not a bug, but we can continue the discussion.

**Closed by derrickmehaffy** 2019-12-30 07:16 UTC

**Comment by jmchza** [comment] 2019-12-30 10:30
Yes I was about to close it myself @derrickmehaffy 

Thanks for your feedback. Yes it is just that analysis that you either spend so much time in customising something versus building it from scratch which in my personal opinion are 2 different arts. 

Cheers.

**Comment by Zedonboy** [comment] 2021-02-27 22:57
I really need to change the controller, that affects the admin controller

**Comment by Zedonboy** [comment] 2021-02-27 23:07
Please @derrickmehaffy  any work around to this.

I want to trigger a web-push notification when notication object is created.

**Comment by derrickmehaffy** [comment] 2021-03-01 23:01
@Zedonboy please open a question thread on our forum: https://forum.strapi.io
