### ISSUE TITLE
Graphql Plugin Crashes Server

### ISSUE THREAD

**Issue by moshemo** [strapi/strapi#4837] opened 2019-12-27 07:31 UTC
**Describe the bug**
Installing the `strapi-plugin-graphql` on an installation of strapi that already has a custom post type crashes the strapi server.

**Steps to reproduce the behavior**
1. Installed strapi.  
1. Setup custom post types with fields.  
1. Tried to install the `strapi-plugin-graphql` via the admin panel.
1. Received the following error message:

> The restart takes longer than expected
> The server should have restarted, please check your logs in the terminal

1. Checked my terminal log:  

```
[2019-12-27T07:47:12.612Z] debug GET /admin/plugins (5 ms) 200
[2019-12-27T07:47:15.882Z] info Installing graphql...
[2019-12-27T07:48:59.105Z] info File changed: C:\code\tutorials\react\Gatsby\strapi\startup-reporter\package.json[2019-12-27T07:48:59.279Z] debug POST /admin/plugins/install (103411 ms) 200
[2019-12-27T07:48:59.281Z] info The server is restarting

[2019-12-27T07:49:14.672Z] debug ⛔️ Server wasn't able to start properly.
[2019-12-27T07:49:14.674Z] error Error: Field "Query.news" can only be defined once.
    at assertValidSDL (C:\code\tutorials\react\Gatsby\strapi\startup-reporter\node_modules\graphql\validation\validate.js:108:11)
    at Object.buildASTSchema (C:\code\tutorials\react\Gatsby\strapi\startup-reporter\node_modules\graphql\utilities\buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (C:\code\tutorials\react\Gatsby\strapi\startup-reporter\node_modules\graphql-tools\dist\generate\buildSchemaFromTypeDefinitions.js:23:28)
    at makeExecutableSchema (C:\code\tutorials\react\Gatsby\strapi\startup-reporter\node_modules\graphql-tools\dist\makeExecutableSchema.js:26:29)
    at Object.generateSchema (C:\code\tutorials\react\Gatsby\strapi\startup-reporter\node_modules\strapi-plugin-graphql\services\Schema.js:300:22)
    at Object.initialize (C:\code\tutorials\react\Gatsby\strapi\startup-reporter\node_modules\strapi-plugin-graphql\hooks\graphql\index.js:59:50)
    at Promise.resolve.then (C:\code\tutorials\react\Gatsby\strapi\startup-reporter\node_modules\strapi\lib\hooks\index.js:37:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! startup-reporter@0.1.0 dev: `strapi develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the startup-reporter@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\moshe\AppData\Roaming\npm-cache\_logs\2019-12-27T07_49_14_697Z-debug.log
```

1. Checked the `2019-12-27T07_49_14_697Z-debug.log` logfile.  Here are the contents:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\moshe\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\moshe\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle startup-reporter@0.1.0~predev: startup-reporter@0.1.0
6 info lifecycle startup-reporter@0.1.0~dev: startup-reporter@0.1.0
7 verbose lifecycle startup-reporter@0.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle startup-reporter@0.1.0~dev: PATH: C:\Users\moshe\scoop\persist\nvm\nodejs\v10.16.3\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\code\tutorials\react\Gatsby\strapi\startup-reporter\node_modules\.bin;C:\Users\moshe\scoop\apps\cmder-full\current\bin;C:\Users\moshe\scoop\apps\cmder-full\current\vendor\bin;C:\Users\moshe\scoop\apps\cmder-full\current\vendor\conemu-maximus5\ConEmu\Scripts;C:\Users\moshe\scoop\apps\cmder-full\current\vendor\conemu-maximus5;C:\Users\moshe\scoop\apps\cmder-full\current\vendor\conemu-maximus5\ConEmu;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Microsoft VS Code\bin;C:\Users\moshe\scoop\apps\yarn\current\Yarn\bin;C:\Users\moshe\scoop\apps\yarn\current\global\node_modules\.bin;C:\Users\moshe\scoop\apps\nvm\current\nodejs\nodejs;C:\Users\moshe\scoop\shims;C:\Users\moshe\AppData\Local\Microsoft\WindowsApps;C:\code\src\flutter\bin;C:\Program Files\heroku\bin;C:\Users\moshe\scoop\apps\cmder-full\current\vendor\git-for-windows\cmd;C:\Users\moshe\scoop\apps\cmder-full\current\vendor\git-for-windows\mingw64\bin;C:\Users\moshe\scoop\apps\cmder-full\current\vendor\git-for-windows\usr\bin;C:\Users\moshe\scoop\apps\cmder-full\current
9 verbose lifecycle startup-reporter@0.1.0~dev: CWD: C:\code\tutorials\react\Gatsby\strapi\startup-reporter
10 silly lifecycle startup-reporter@0.1.0~dev: Args: [ '/d /s /c', 'strapi develop' ]
11 silly lifecycle startup-reporter@0.1.0~dev: Returned: code: 1  signal: null
12 info lifecycle startup-reporter@0.1.0~dev: Failed to exec dev script
13 verbose stack Error: startup-reporter@0.1.0 dev: `strapi develop`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\moshe\scoop\persist\nvm\nodejs\v10.16.3\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\moshe\scoop\persist\nvm\nodejs\v10.16.3\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid startup-reporter@0.1.0
15 verbose cwd C:\code\tutorials\react\Gatsby\strapi\startup-reporter
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Users\\moshe\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\node.exe" "C:\\Users\\moshe\\scoop\\apps\\nvm\\current\\nodejs\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error startup-reporter@0.1.0 dev: `strapi develop`
22 error Exit status 1
23 error Failed at the startup-reporter@0.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

1. Did a fresh install strapi (without setting up any custom post types)
1. Was able to successfully install the graphql plugin.  

**Code Snippets**

```
// package.json
{
  "name": "startup-reporter",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "dev": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "sqlite3": "latest",
    "strapi": "3.0.0-beta.18.3",
    "strapi-admin": "3.0.0-beta.18.3",
    "strapi-connector-bookshelf": "3.0.0-beta.18.3",
    "strapi-plugin-content-manager": "3.0.0-beta.18.3",
    "strapi-plugin-content-type-builder": "3.0.0-beta.18.3",
    "strapi-plugin-email": "3.0.0-beta.18.3",
    "strapi-plugin-upload": "3.0.0-beta.18.3",
    "strapi-plugin-users-permissions": "3.0.0-beta.18.3",
    "strapi-utils": "3.0.0-beta.18.3"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "a9021e9b-cff8-4449-8173-478b5840669d"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**SYSTEM**
* **Node version:**  v10.16.3
* **Strapi version:** 3.0.0-beta.18.3
* **Database:**  I believe SQLite (I installed using the quickstart option)
* **Operating System:**  Windows 10

**Comment by derrickmehaffy** [comment] 2019-12-27 07:53
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by moshemo** [comment] 2019-12-27 08:14
@derrickmehaffy I have updated the question in the format of the template.

**Comment by derrickmehaffy** [comment] 2019-12-27 08:17
please post in your package.json file (or at least just the depends section)

**Comment by moshemo** [comment] 2019-12-27 08:28
@derrickmehaffy I updated my initial post with the package.json file.  Note, this is the file **after** I deleted `strapi-plugin-graphql`.   In the fresh install with the graphql plugin, this is the version of that plugin:

```
"strapi-plugin-graphql": "3.0.0-beta.18.3",
```

Thanks, by the way, for helping with this.

**Comment by derrickmehaffy** [comment] 2019-12-27 08:42
Everything else looks fine in the package.json 🤔 Can you upload your project to a github repo so I can clone it and take a deep dive? (Remove any private information like the db settings in the `config/environments/development/database.json`

**Comment by moshemo** [comment] 2019-12-27 09:42
Yes -- but it may have to wait until the beginning of next week.  If I get time later today, I'll upload it.

**Comment by moshemo** [comment] 2019-12-27 09:49
Here is a link to the repository: https://github.com/moshemo/strapi-graphql-question

**Comment by lauriejim** [comment] 2019-12-27 16:03
Hello, this issue is a duplicate of this one https://github.com/strapi/strapi/issues/1198#issuecomment-522337991

**Closed by lauriejim** 2019-12-27 16:03 UTC
