### ISSUE TITLE
Import/Transfer fails with "FOREIGN KEY constraint failed" on links

### ISSUE THREAD

**Issue by 20x-dz** [strapi/strapi#18269] opened 2023-10-03 20:33 UTC
### Required System information

- Node.js version: v18.18.0
- NPM version: 9.8.1 
- Strapi version: 4.14.2
- Database: sqlite <> mariadb 10.4
- Operating system: macOS <> Ubuntu Server 22.04
- Is your project Javascript or Typescript: TS

### Describe the bug

Running a transfer between v4.14.2 instances (staging (ubuntu server, mariadb) to dev (macOS, sqlite)) fails on links with the following error message:

```bash
Starting transfer...
✔ entities: 951 transfered (size: 1.3 MB) (elapsed: 2350 ms)
✖ links: 1421 transfered (size: 281.4 KB) (elapsed: 100 ms)
[2023-10-03 22:13:20.774] error: [ERROR] insert into `c_blck_customer_logos_customer_logos_links` (`customer_logo_id`, `customer_logo_order`, `customer_logos_id`) values (42, 5, 19) - FOREIGN KEY constraint failed
Transfer process failed.
```

### Steps to reproduce the behavior

1. Be on latest strapi version (v4.14.0 or v4.14.2)
2. run `npm run strapi transfer -- --from https://example.com/admin/ --from-token $TOKEN`
3. See error

### Expected behavior

Transfer should succeed

### Additional context

Reverting to v4.13.7 works as a workaround.

Looking through the changelog no apparent (big) changes seem to be related to DTS.

In the [comparison](https://github.com/strapi/strapi/compare/v4.13.7...v4.14.2) only the following commits seem to be related (according to their commit messages):
 * https://github.com/strapi/strapi/commit/75b4aa5226c8de2eee0f85b1425637ced5ce4869 (doubtful)
 * https://github.com/strapi/strapi/commit/ad9def07c2bac6e7039684e217eb17b776e0bc0d (probably not)
 * https://github.com/strapi/strapi/commit/49e0c08fca8b0c8f72e2be1aedac0d2582d082d2 (beats me, but probably not)

Maybe related to #16363 as well?

Hope this helps.

**Comment by derrickmehaffy** [comment] 2023-10-04 18:30
duplicate of https://github.com/strapi/strapi/issues/17578

**Closed by derrickmehaffy** 2023-10-04 18:30 UTC
