### ISSUE TITLE
Unable to access array fields of a component in a dynamic zone

### ISSUE THREAD

**Issue by jsjohann** [strapi/strapi#7454] opened 2020-08-13 11:07 UTC
**Describe the bug**
We have got a single type `Home` with a dynamic zone field `Content` where it is possible to add custom components like displaying several `projects` (set up as a relation). These projects do have some array fields like `MetaData`, `MetaTags` or `TeaserImages` (see first screenshot), but these are not showing in the response for the `Home` query (see second screenshot). 
 
**Expected behavior**
It is possible to see and access the array fields.

**Screenshots**
`/projects` request
![image](https://user-images.githubusercontent.com/3832460/90126942-b74d8380-dd64-11ea-95c6-dddd419ec3f8.png)
`/home` request
![image](https://user-images.githubusercontent.com/3832460/90127204-17dcc080-dd65-11ea-9c5d-2d1c6f119036.png)

**System**

- Node.js version: v13.7.0
- NPM version: 6.13.7
- Strapi version: 3.1.3
- Database: postgres
- Operating system: MacOS 10.15.6

**Comment by derrickmehaffy** [comment] 2020-08-13 22:11
@jsjohann I'm not sure I understand the problem here, can you please provide some more context?

**Comment by jsjohann** [comment] 2020-08-14 08:24
@derrickmehaffy We use the single type `home` for our landing page. The content of this page is organized as a dynamic zone to display several components. One of these components is for displaying references to some of our projects. So, this component basically is a relation to a certain project. If we now send a http request from our frontend to Strapi to fetch these components of the dynamic zone (via a general get `home`request), the array fields of a project are missing (like displayed in the screenshots above). But we need these additional fields to display the images and so on of a project at our landing page.

**Comment by lauriejim** [comment] 2020-08-15 09:50
Ho okay, I got it.
By default, Strapi gets data only with 2 levels of relations.
Here, in your case, your dynamic zone, and then your projects.

Can you please share your data structure to let us reproduce and make sure that's the reason.
If you want more data, you will have to customize the `population` attribute.
Here is a video about how to do that: https://www.youtube.com/watch?v=VBNjCgUokLk&list=PL7Q0DQYATmvhlHxHqfKHsr-zFls2mIVTi&index=17&t=0s

**Comment by jsjohann** [comment] 2020-08-17 09:07
Thanks for your response!

The model of the homepage/landing page is like that:
![image](https://user-images.githubusercontent.com/3832460/90377977-14a14780-e079-11ea-9a0d-f94f277b6fd7.png)

A component looks like that:
![image](https://user-images.githubusercontent.com/3832460/90378304-7792de80-e079-11ea-9ad3-5b8cc1082635.png)

And the project type is defined like this:
![image](https://user-images.githubusercontent.com/3832460/90378443-a90baa00-e079-11ea-932d-5b8ab6cd4e9a.png)
![image](https://user-images.githubusercontent.com/3832460/90378482-b5900280-e079-11ea-8001-ef7d82163f66.png)

**Comment by lauriejim** [comment] 2020-08-18 07:54
Can you please update your message by using the code in code blocks instead of images.
I can copy/past the content of images. This will save my time to have to code directly.
Thanks.

**Comment by jsjohann** [comment] 2020-08-18 09:03
'Startseite' single type
```
{
  "kind": "singleType",
  "connection": "default",
  "collectionName": "startseites",
  "info": {
    "name": "Startseite"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "MetaTags": {
      "type": "component",
      "repeatable": true,
      "component": "content.meta-tags"
    },
    "TeaserSlider": {
      "type": "component",
      "repeatable": true,
      "component": "content.teaser-slider"
    },
    "TeaserText": {
      "type": "text"
    },
    "Content": {
      "type": "dynamiczone",
      "components": [
        "homepage.random-projects",
        "homepage.newest-post",
        "homepage.featured-project",
        "homepage.featured-content"
      ]
    }
  }
}
```

Project collection type
```

{
  "kind": "collectionType",
  "connection": "default",
  "collectionName": "projects",
  "info": {
    "name": "project",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "Title": {
      "type": "string"
    },
    "PublishingDate": {
      "type": "date"
    },
    "posts": {
      "collection": "post",
      "via": "projects"
    },
    "Slug": {
      "type": "uid",
      "targetField": "Title"
    },
    "MetaTags": {
      "type": "component",
      "repeatable": true,
      "component": "content.meta-tags"
    },
    "MetaData": {
      "type": "component",
      "repeatable": true,
      "component": "content.meta-data"
    },
    "TeaserTitle": {
      "type": "string"
    },
    "Content": {
      "type": "dynamiczone",
      "components": [
        "layout.text",
        "layout.heading"
      ]
    },
    "isVisible": {
      "type": "boolean",
      "default": true
    },
    "projects": {
      "collection": "project"
    },
    "TeaserImages": {
      "type": "component",
      "repeatable": true,
      "component": "content.teaser-image"
    }
  }
}
```
'Meta Data' component as an example of an array field missing in the result
```
{
  "connection": "default",
  "collectionName": "components_content_meta_data",
  "info": {
    "name": "MetaData",
    "icon": "table"
  },
  "options": {},
  "attributes": {
    "Title": {
      "type": "string"
    },
    "Content": {
      "type": "text"
    }
  }
}
```

'Random projects' component

```
{
  "collectionName": "components_homepage_random_projects",
  "info": {
    "name": "RandomProjects",
    "icon": "random"
  },
  "options": {},
  "attributes": {
    "projects": {
      "collection": "project"
    }
  }
}
```

**Comment by derrickmehaffy** [comment] 2020-08-19 13:24
@jsjohann if possible can you link to your github repo that contains these models? Based on the structure you gave above these are quite complex and will be difficult to properly reproduce (it appears you are missing some structure for some components that weren't shown above).

**Comment by jsjohann** [comment] 2020-08-20 15:20
@derrickmehaffy Thanks for your effort! I've setup a test project with a reduced data structure but I got the same problem. It basically consists of following three types:

homepage
```
{
  "kind": "singleType",
  "collectionName": "homepages",
  "info": {
    "name": "Homepage"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "Headline": {
      "type": "string"
    },
    "Content": {
      "type": "dynamiczone",
      "components": [
        "homepage.featured-projects"
      ]
    }
  }
}

```
component FeaturedProjects
```
{
  "collectionName": "components_homepage_featured_projects",
  "info": {
    "name": "FeaturedProjects",
    "icon": "address-card"
  },
  "options": {},
  "attributes": {
    "projects": {
      "collection": "project"
    }
  }
}
```

projects
```
{
  "kind": "collectionType",
  "collectionName": "projects",
  "info": {
    "name": "Project"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "Title": {
      "type": "string"
    },
    "MetaTags": {
      "type": "component",
      "repeatable": true,
      "component": "content.meta-tags"
    }
  }
}
```

component MetaTag
```
{
  "collectionName": "components_content_meta_tags",
  "info": {
    "name": "MetaTags",
    "icon": "ad"
  },
  "options": {},
  "attributes": {
    "Type": {
      "type": "enumeration",
      "enum": [
        "Title",
        "Content"
      ]
    },
    "Value": {
      "type": "string"
    }
  }
}
```

**Comment by lodisy** [comment] 2020-08-20 15:35
> @derrickmehaffy Thanks for your effort! I've setup a test project with a reduced data structure but I got the same problem. It basically consists of following three types:
> 
> homepage
> 
> ```
> {
>   "kind": "singleType",
>   "collectionName": "homepages",
>   "info": {
>     "name": "Homepage"
>   },
>   "options": {
>     "increments": true,
>     "timestamps": true
>   },
>   "attributes": {
>     "Headline": {
>       "type": "string"
>     },
>     "Content": {
>       "type": "dynamiczone",
>       "components": [
>         "homepage.featured-projects"
>       ]
>     }
>   }
> }
> ```
> 
> component FeaturedProjects
> 
> ```
> {
>   "collectionName": "components_homepage_featured_projects",
>   "info": {
>     "name": "FeaturedProjects",
>     "icon": "address-card"
>   },
>   "options": {},
>   "attributes": {
>     "projects": {
>       "collection": "project"
>     }
>   }
> }
> ```
> 
> projects
> 
> ```
> {
>   "kind": "collectionType",
>   "collectionName": "projects",
>   "info": {
>     "name": "Project"
>   },
>   "options": {
>     "increments": true,
>     "timestamps": true
>   },
>   "attributes": {
>     "Title": {
>       "type": "string"
>     },
>     "MetaTags": {
>       "type": "component",
>       "repeatable": true,
>       "component": "content.meta-tags"
>     }
>   }
> }
> ```
> 
> component MetaTag
> 
> ```
> {
>   "collectionName": "components_content_meta_tags",
>   "info": {
>     "name": "MetaTags",
>     "icon": "ad"
>   },
>   "options": {},
>   "attributes": {
>     "Type": {
>       "type": "enumeration",
>       "enum": [
>         "Title",
>         "Content"
>       ]
>     },
>     "Value": {
>       "type": "string"
>     }
>   }
> }
> ```
> 
> I've setup a repo here: https://github.com/jsjohann/strapi-test

query like this:

` content {
                ... on ComponentTextParagraph {
                    __typename
                    id
                    paragraph
                }
...etc...
}`

**Comment by derrickmehaffy** [comment] 2020-08-20 15:37
Thank you @jsjohann let me take a look :)

**Comment by jsjohann** [comment] 2020-08-20 15:49
@derrickmehaffy Thanks for checking! Is there anything I can do on my side or is this an issue on Strapi's side?

**Comment by lauriejim** [comment] 2020-08-20 16:14
@derrickmehaffy did you try the customization of the `populate` in the controller to see if you are able to populate the data with that?

**Comment by derrickmehaffy** [comment] 2020-08-20 16:20
Yeah building on what @jsjohann had in the linked project

```js
module.exports = {
  async find(ctx) {
    const entity = await strapi.services.homepage.find(['Content', 'Content.projects', 'Content.projects.MetaTags']);
    return sanitizeEntity(entity, { model: strapi.models.homepage });
  },
};
```

**Comment by derrickmehaffy** [comment] 2020-08-20 16:40
@jsjohann at the moment I'm not sure, let me engage with the backend engineering team. as a side point I'm adding this to my list of topics we need to better document.

**Comment by kantan-florian** [comment] 2020-12-11 19:32
Is there already any info or possible workaround for this issue? As soon as you need more than 2 populate-levels and specify population paths in the find method, the components disappear. Can I not reference the components somehow to also get them populated?

**Comment by felixhagspiel** [comment] 2021-02-26 12:17
@kantan-florian a (bit ugly) workaround would be to just get the IDs of the relations and do additional queries for each component (or collect all ids and include them in one single query). Of course this can impact performance depending on how many items there are.

**Comment by davidmgrana** [comment] 2021-05-12 00:21
hi there, any news? having this issue as well

**Comment by SatadruBhattacharjee** [comment] 2021-05-16 12:18
+1

**Comment by pozh** [comment] 2021-05-20 17:18
+1

**Comment by fadhilx** [comment] 2021-05-21 10:33
Hi, i have the same issue, hope this will fix soon, really need this feature.

**Comment by karlmoubarak** [comment] 2021-06-30 08:20
any update on this?

**Comment by derrickmehaffy** [comment] 2021-07-01 22:10
This will be possible in our v4 coming later this year.

**Comment by mergims** [comment] 2021-11-09 19:34
Bump 🤡

**Comment by derrickmehaffy** [comment] 2021-11-10 00:03
Locking, this will be in the v4 (and is already in the v4 beta).

This "fix" won't be backported to v3

**Comment by derrickmehaffy** [comment] 2021-11-30 14:17
Fixed in v4, marking as closed

**Closed by derrickmehaffy** 2021-11-30 14:17 UTC
Labels: type: bug, severity: low, status: confirmed, source: core:framework
