### ISSUE TITLE
Boolean fields cannot be filtered in strapi admin or custom route

### ISSUE THREAD

**Issue by apodaka** [strapi/strapi#9154] opened 2021-01-18 03:52 UTC
### Describe the bug

Boolean fields cannot be filtered in strapi admin or custom route. When i try to filter records with strapi admin, it allways returns 0 records.

### Steps to reproduce the behavior

1. Go to strapi admin and create a contet type called "Profile" (as example) with an attribute named "related" (set true as default value).
2. Create content for the type "Profile"
3. Use the filter form in strapi admin for filter cities by is attribute "related" setted as true.
4. List 0 records of cities

### Screenshots

![Captura de pantalla 2021-01-17 a la(s) 20 45 23](https://user-images.githubusercontent.com/18412209/104870214-2f683880-5905-11eb-89de-e7e881ba4a83.png)

![Captura de pantalla 2021-01-17 a la(s) 20 46 01](https://user-images.githubusercontent.com/18412209/104870209-2e370b80-5905-11eb-9668-ea96b7e3fb5a.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v10.21.0 
- NPM version: 6.14.8
- Strapi version: 3.3.3 
- Database: MongoDB 4.2.8
- Operating system: MacOS High Sierra

**Comment by derrickmehaffy** [comment] 2021-01-18 07:53
> Strapi version: 3.3.3

Can you test on a fresh project in the latest release please?

**Comment by derrickmehaffy** [comment] 2021-01-22 20:32
Tested on v3.4.4 and couldn't reproduce. Marking as closed

![image](https://user-images.githubusercontent.com/8593673/105542215-351f9e80-5cb6-11eb-843a-423196a8c9a0.png)

![image](https://user-images.githubusercontent.com/8593673/105542225-394bbc00-5cb6-11eb-8689-3ad1862fe7d7.png)

![image](https://user-images.githubusercontent.com/8593673/105542235-3c46ac80-5cb6-11eb-8f4f-0e1e7cdde832.png)

![image](https://user-images.githubusercontent.com/8593673/105542246-3fda3380-5cb6-11eb-8535-437b4ca05545.png)

**Closed by derrickmehaffy** 2021-01-22 20:32 UTC
Labels: status: pending reproduction
