### ISSUE TITLE
Error adding data field to an existing Content Type

### ISSUE THREAD

**Issue by brnmtt** [strapi/strapi#3434] opened 2019-06-12 14:28 UTC
**Describe the bug**
After crating a new Data field I get this error on the terminal and Strapi stop working:
debug ⛔️ Server wasn't able to start properly.
error Error: SQLITE_ERROR: Cannot add a column with non-constant default

**Steps to reproduce the behavior**
1. Go to content type builder
2. Click on any already existing Content Type
3. Click on Add New Field
4. Select Data type, insert name and default value
5. Save

**Expected behavior**
It create a new field

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.3
- Database: Mongo

**Comment by alexandrebodin** [comment] 2019-06-12 18:30
Duplicate of https://github.com/strapi/strapi/issues/2930
CLosing is it is fixed in beta.4

**Closed by alexandrebodin** 2019-06-12 18:30 UTC

**Comment by lauriejim** [comment] 2019-06-17 16:19
But there is something weird. Why did you get this `SQLite` error if you are using MongoDB database.

**Comment by derrickmehaffy** [comment] 2019-06-17 16:28
@brnmtt FYI `--quickstart` does not use MongoDB, it uses SQLite hence the `.tmp/` directory which holds the SQLite data file.

However it is a duplicate as @alexandrebodin said
