### ISSUE TITLE
Error Preventing Strapi From Running in Development Mode

### ISSUE THREAD

**Issue by MattHarr1s** [strapi/strapi#13369] opened 2022-05-20 17:19 UTC
### Required System information

- Node.js version: 14.19.3
- NPM version: 6.14.17
- Strapi version: 4.1.11
- Database: sqlite
- Operating system:  Pop_os Linux

### Describe the bug
 When trying to run strapi in development mode the script fails and the following error message is displayed:  
 
Building your admin UI with development configuration ...
Error: For the selected environment is no default script chunk format available:
JSONP Array push can be chosen when 'document' or 'importScripts' is available.
CommonJs exports can be chosen when 'require' or node builtins are available.
Make sure that your 'browserslist' includes only platforms that support these features or select an appropriate 'target' to allow selecting a chunk format by default. Alternatively specify the 'output.chunkFormat' directly.
    at /home/matt/Documents/fun/strapi-4/node_modules/webpack/lib/config/defaults.js:735:11
    at F (/home/matt/Documents/fun/strapi-4/node_modules/webpack/lib/config/defaults.js:72:15)
    at applyOutputDefaults (/home/matt/Documents/fun/strapi-4/node_modules/webpack/lib/config/defaults.js:716:2)
    at applyWebpackOptionsDefaults (/home/matt/Documents/fun/strapi-4/node_modules/webpack/lib/config/defaults.js:190:2)
    at createCompiler (/home/matt/Documents/fun/strapi-4/node_modules/webpack/lib/webpack.js:77:2)
    at create (/home/matt/Documents/fun/strapi-4/node_modules/webpack/lib/webpack.js:134:16)
    at webpack (/home/matt/Documents/fun/strapi-4/node_modules/webpack/lib/webpack.js:158:32)
    at f (/home/matt/Documents/fun/strapi-4/node_modules/webpack/lib/index.js:58:16)
    at Object.build (/home/matt/Documents/fun/strapi-4/node_modules/@strapi/admin/index.js:84:20)
    at async module.exports (/home/matt/Documents/fun/strapi-4/node_modules/@strapi/strapi/lib/commands/develop.js:33:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Steps to reproduce the behavior

1. Create new project using NPX.
2.  Run npm install or yarn. 
3. Run Yarn Develop or NPM Develop.
4. See error in terminal when trying to build admin ui.

### Expected behavior

The develop command should work to start strapi in development mode. 

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment] 2022-05-20 21:22
The error doesn't provide any context to the problem (it doesn't even look like an error that would crash the application or cause it not to run). And there is no steps to reproduce as I couldn't reproduce on v4.1.11.

Closing this until the user provides more detailed reproduction steps or clearer information on the error.

**Closed by derrickmehaffy** 2022-05-20 21:22 UTC

**Comment by MattHarr1s** [comment] 2022-05-21 17:19
I tested more and realized this happens only after installing the documentation plugin. Removing the documentation plugin allows strapi to run in development mode again.
