### ISSUE TITLE
In Content Type List view, columns with boolean values shows hyphen in rows

### ISSUE THREAD

**Issue by shumiyao** [strapi/strapi#13074] opened 2022-04-06 15:03 UTC
### Required System information

- Node.js version: v14.19.0
- NPM version: 6.14.16
- Strapi version: 4.1.7
- Database: postgres
- Operating system: MacOS 12.3.1

### Describe the bug

Since the Strapi version 4.1.7, columns in Content Type List view with boolean values started showing hyphen in rows, instead of false or true

### Steps to reproduce the behavior

1. Upgrade to Strapi 4.1.7
1. Do `npm run build`
1. Go to 'http://localhost:1337/admin/content-manager/collectionType/plugin::users-permissions.user'

### Expected behavior

The value should be shown as `true` or `false`.

### Screenshots

<img width="1361" alt="ScreenShot 2022-04-06 at 3 59 33 PM" src="https://user-images.githubusercontent.com/50849841/162005642-fde5dc6f-18c6-491d-b723-42c2ad1d1bec.png">

**Comment by gu-stav** [comment] 2022-04-06 18:57
Duplicate of https://github.com/strapi/strapi/issues/13066

**Closed by gu-stav** 2022-04-06 18:57 UTC
