### ISSUE TITLE
Still unable to use Strapi in pnpm monorepo

### ISSUE THREAD

**Issue by elliason** [strapi/strapi#16133] opened 2023-03-18 14:30 UTC
2 weeks ago, I have opened issue https://github.com/strapi/strapi/issues/15992 about not being able to use Strapi inside pnpm monorepo. Issue was closed, but should not have been. The problem is still there in 4.8.2. Build task is still failing on missing modules.

**Comment by Eventyret** [comment] 2023-03-20 09:48
Closing this as it's a duplicate of https://github.com/strapi/strapi/issues/16133
I will try re-produce it in the original issue

**Closed by Eventyret** 2023-03-20 09:48 UTC
