### ISSUE TITLE
Updating relation field with ID of unexisting entry not handled

### ISSUE THREAD

**Issue by Aleksandar1932** [strapi/strapi#10971] opened 2021-09-15 07:48 UTC
### Describe the bug

Updating an entry's relation field with ID of an entry which does not exist in the collection of the other side of the relation is not handled and will put empty object for that field. 

### Steps to reproduce the behavior
1. Create two collections with arbitrary names (ex. `File` and `Folder`)
2. In the `File` collection add `1:N` relation to the `Folder` collection (`File has one Folder`). 
3. Create one Folder entry. 
4. Create one File entry and add in the folder field add the ID of the previously created folder in 3. (`POST`)
![image](https://user-images.githubusercontent.com/29300910/133391991-99579241-0e94-4e3a-a2da-ef75aadeef01.png)
5. Update the folder field in the previously created file in 4, with an ID of a folder which does not exist. 
![image](https://user-images.githubusercontent.com/29300910/133391880-dc4b8f0d-6bdc-400d-91fb-dbb149f6d29b.png)

### Expected behavior

An error should be thrown, or folder should be set to null, since there isn't a way to make that field required. 

### Screenshots

Provided in the repro steps above. 

### System

- Node.js version: v14.17.5
- NPM version: 6.14.14
- Strapi version: 3.6.8
- Database: PostgreSQL
- Operating system: macOS Big Sur Version 11.5.2 (20G95)

**Comment by MattieBelt** [comment] 2021-09-15 11:15
Duplicate of #10871

**Closed** 2021-09-17 21:43 UTC
Labels: status: duplicate
