### ISSUE TITLE
Wrong URLs in email templates

### ISSUE THREAD

**Issue by spiff-radio** [strapi/strapi#17091] opened 2023-06-24 10:17 UTC
## Bug report

The emails sent by Strapi have incorrect URLs.

eg

> We heard that you lost your password. Sorry about that!
> 
> But donâ€™t worry! You can use the following link to reset your password:
> 
> ?code=XXX
> 
> Thanks.

I first thought that it was because I didn't define the APP_URL, but now that it's done, it still does not work.
Changing `<%= URL %>?code=<%= TOKEN %>` to `<%= APP_URL %>?code=<%= TOKEN %>` doesn't work either (error 500)

`ValidationError: Invalid template`

PS: + encoding error !  `donâ€™t`

### Required System information

- Node.js version: v16.20.1
- Strapi version:4.11.1
- Database:postgres
- Is your project Javascript or Typescript:JS

**Comment by ajayxverma** [comment] 2023-06-26 15:51
Please assign this issue to me

**Comment by ashutoshdhande** [comment] 2023-06-27 04:43
Hi @spiff-radio,

**Can you provide the following information for better analysis?**

- How to reproduce this exact same issue as plain emails will work fine mostly?
- What email provider is used, like SendGrid or a custom one?
- Also, please provide the `afterCreate ` lifecycle code snippet.

**Comment by spiff-radio** [comment] 2023-06-27 06:28
Hello,
I use the default settings and didn't customize the email stuff.
The emails are sent, it just don't have an URL within.

Le mar. 27 juin 2023 à 06:44, ashutoshdhande ***@***.***> a
écrit :

**Comment by ashutoshdhande** [comment] 2023-06-27 07:03
@spiff-radio A dummy email screenshot and email template (text or html whatever you've done) object would be better for fuether analysis. Btw this ` But donâ€™t worry! ` may be due to lack of escape character.

**Closed** 2023-06-27 07:14 UTC
Labels: flag: invalid template
