### ISSUE TITLE
Strapi console binds to a port

### ISSUE THREAD

**Issue by goodhoko** [strapi/strapi#14652] opened 2022-10-18 09:35 UTC
### Required System information
- Node.js version: 16.16.0
- Yarn version: 1.22.19
- Strapi version: 4.3.9
- Database: Postgres:12.0
- Operating system: node:16 [Docker image](https://hub.docker.com/_/node).### Describe the bug

### Describe the bug
When `strapi console` is run it tries to bind to the configured port. If the port is already taken the console crashes. This makes it impossible to run the console alongside other instance of the app.

### Steps to reproduce the behavior

1. Run `strapi develop` or `strapi start`
2. Open another terminal session and run `strapi console`
3. The console crashes with `error: The port 8080 is already used by another application.`

### Expected behavior
The console starts and doesn't try to bind to a port because it has no reason to do that.

### Additional context

The ability to run the console alongside a running app is quite useful when one wants to try out strapi construct (eg. EntityService API) in environments where the other app cannot be easily paused. Think remote production/staging servers, docker containers or even local machine with a long-running `strapi dev` instance.

There is a workaround where you can just configure the console to bind to some other free port. Eg. `PORT=6666 strapi console`.

**Comment by derrickmehaffy** [comment] 2022-10-23 19:35
Our implementation of the console is not to be used in production/staging environments, it's designed to be used for development purposes only. Simply changing the port as a workaround does not connect you to the running server but spin up it's own.

The console starts the server in node interactive mode (AKA REPL): https://nodejs.org/en/knowledge/REPL/how-to-use-nodejs-repl/

We don't plan to change this. Marking as closed.

**Closed by derrickmehaffy** 2022-10-23 19:35 UTC
Labels: status: will not fix

**Comment by goodhoko** [comment] 2022-10-24 09:41
@derrickmehaffy Thanks for your answer.

> console is not to be used in production/staging environments, it's designed to be used for development purposes only.

I don't think this is limited to non-dev environments in any way. A development console binding to a port is weird on its own. There is no reason for the console to require this system resource. Doing so hinders its usage in *any* environment. Eg. we can't open multiple strapi consoles side by side. We can't open strapi console inside a docker container with a running strapi server.

What does it mean, practically, for the console to "not be designed" for non-dev environments? Is there any reason for not wanting the console to be designed to run in *any* environment?

There is quite an utility from running console in non-dev environments. For example:
- Debugging environement-specific bugs.
- Exporting and/or importing data leveraging the Entity Service API.
- Running migration scripts that cannot be run using the db migrations API.

The list is virtually endless just as the possibilities of the console itself.

If we really want to prevent using the console in non-dev environments shouldn't we actually check for the environment and exit with a *descriptive* error message?

Also, looking at consoles of other frameworks like, for instance, [Ruby on Rails'](https://guides.rubyonrails.org/command_line.html#bin-rails-console) they don't bind to a port.

btw: I'd be up for submitting a PR that fixes this.

**Comment by derrickmehaffy** [comment] 2022-10-28 18:04
> @derrickmehaffy Thanks for your answer.
> 
> > console is not to be used in production/staging environments, it's designed to be used for development purposes only.
> 
> I don't think this is limited to non-dev environments in any way. A development console binding to a port is weird on its own. There is no reason for the console to require this system resource. Doing so hinders its usage in _any_ environment. Eg. we can't open multiple strapi consoles side by side. We can't open strapi console inside a docker container with a running strapi server.
> 
> What does it mean, practically, for the console to "not be designed" for non-dev environments? Is there any reason for not wanting the console to be designed to run in _any_ environment?
> 
> There is quite an utility from running console in non-dev environments. For example:
> 
> * Debugging environement-specific bugs.
> * Exporting and/or importing data leveraging the Entity Service API.
> * Running migration scripts that cannot be run using the db migrations API.
> 
> The list is virtually endless just as the possibilities of the console itself.
> 
> If we really want to prevent using the console in non-dev environments shouldn't we actually check for the environment and exit with a _descriptive_ error message?
> 
> Also, looking at consoles of other frameworks like, for instance, [Ruby on Rails'](https://guides.rubyonrails.org/command_line.html#bin-rails-console) they don't bind to a port.
> 
> btw: I'd be up for submitting a PR that fixes this.

Originally the console was designed for our internal use (navigating the internal API easily for debugging reasons) and thus we never intended for, designed it for any other purpose. We aren't implementing anything special, it's literally just using Node's repl implementation.

https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/commands/console.js

There is nothing special here, no plan to build on this any further. It's for debugging only, not for exporting/importing stuff (we are building a feature for that in the CLI right now called DEITs), and migration scripts will be handled by DEITS as well.

We only want to implement features like this via the CLI not through a console because in a console like this you pretty much can't automate it's usage, CLI commands should ideally be constructed in a way that can be automated through say CI/CD pipelines which our console cannot do.

**Comment by userlond** [comment] 2024-02-16 07:35
> There is a workaround where you can just configure the console to bind to some other free port. Eg. PORT=6666 strapi console.

For Windows users:
`set "PORT=6666" && yarn strapi console`
