### ISSUE TITLE
Components are inserted on database even thought the validation on `beforeCreate` fails when I throw an error

### ISSUE THREAD

**Issue by RafaelMarinho96** [strapi/strapi#15481] opened 2023-01-17 19:55 UTC
### Required System information

- Node.js version: 14.19.1
- NPM version: 6.14.16
- Strapi version: 4.5.0
- Database: Mysql
- Operating system: Linux Ubuntu

### Describe the bug

Hello guys, i've been using strapi with custom graphql resolvers and lifecycles hooks to validate what are being filled in a content-type. I notice that the components are inserted on database even thought the validation on `beforeCreate` fails when I throw an error. 

 I'd like to prevent this components being inserted in database when I throw an error, is it possible? Is it a bug or it was planned?

### Steps to reproduce the behavior

1. Create a content type with a normal field and a component
2. Create a rule on `beforeCreate` hook to throw an error
3. Fill the content type (normal field and the compoennt)
4. Click to save and wait for an error
5. Check database on component table (verify the component was inserted even thought the validation on `beforeCreate` fails)

### Expected behavior

Components are inserted on database even thought the validation on `beforeCreate` fails when I throw an error.

### Screenshots

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/20724574/213003466-4466abe7-70d2-4878-aebb-9c4907e77a58.gif)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by LukaszFuchs** [comment] 2023-01-20 15:47
any workaround?

**Comment by KamilLisM** [comment] 2023-01-21 14:33
Is it planned to be fixed in near future? Urgently looking for some kind of workaround..

**Comment by RafaelMarinho96** [comment] 2023-01-23 18:15
Another example, when a component field has the attribute `unique` i can't save and publish correctly, because the save button insert the component on database and when I click on `publish` the application will try to check if the field has a unique value but because of the before insertion this validation will always fail.

**Comment by brunosilvafreitas** [comment] 2023-01-24 15:15
Guys, without a solution for this point we will not be able to move our project to Strapi V4, please help us!

**Comment by derrickmehaffy** [comment] 2023-01-24 22:49
Related to: https://feedback.strapi.io/feature-requests/p/lifecycle-hooks-for-components

For now this is intended as Components don't have lifecycles, at that layer components aren't components they are their own content-type and modification of components happen before the parent so by the time the parent beforeCreate is called the component modifications are already done

**Comment by derrickmehaffy** [comment] 2023-01-24 22:49
Closing this in favor of the feature request as it's not a bug but the logic doesn't exist.

**Closed by derrickmehaffy** 2023-01-24 22:49 UTC
