### ISSUE TITLE
Review life cycles

### ISSUE THREAD

**Issue by MattAurich** [strapi/strapi#1443] opened 2018-06-21 15:14 UTC
# Edited by @derrickmehaffy as of March 8th 2020

Lifecycle Callbacks from generated APIs and plugins are currently very broken (different levels depending on the database) and the Strapi team do plan to fix these over the next few weeks (likely before the stable release in Q2 2020).

Usage of them right now is not recommended, some will work, others will not. There is currently ongoing work to finish up some pre-requisites that will be needed to fix the Lifecycles.

This issue will serve as a central place for all the issues to be linked to and discussed for when they are ready to be worked on.

---

**Informations**
- **Node.js version**: 9.11.2
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.5
- **Database**: MongoDB
- **Operating system**: macOS High Sierra v10.13.4

**What is the current behavior?**
When updating an existing entry, the before/afterSave lifecycle callbacks are not being called. Which is contrary to the comment/description of the function which states that it should be called on an 'insert' and an 'update'. The before/afterUpdate is also getting called for not only on 'update', but also on 'insert' queries.

**Steps to reproduce the problem**
1. Install strapi.
2. Create a new content-type.
3. Create log for before/afterSave and before/afterUpdate (ex: console.log('beforeUpdate'))
4. Create new entry (using either the Content Manager or a curl request) and update an entry to see the behavior.
    * as an aside, when using curl to make an update, the before/afterUpdate are each getting fired twice ( curl localhost:1337/brandy/5b2bbed25a78eb20f953f6dd \
  --data '{"Title":"bluess","content":"about-ussss"}' \
  -X PUT -H "Content-Type: application/json" ) 

**What is the expected behavior?**

// After saving a value.
// Fired after an `insert` or **`update`** query.

**Suggested solutions**

Still digging into a solution, but having gone far enough into the code to get into what triggers the model lifecycle callbacks.

**Comment by derrickmehaffy** [comment] 2018-06-22 06:45
@MattAurich can you test this with MySQL and/or Postgres as well. I'm wondering if there is an issue with mongoose or bookshelf

**Comment by lauriejim** [comment] 2018-07-01 17:58
Hello @MattAurich I just tried with laster version of Strapi and It works.

![screen shot 2018-07-01 at 19 55 24](https://user-images.githubusercontent.com/5716596/42137230-077da564-7d69-11e8-808d-d0a7d322a12c.png)
![screen shot 2018-07-01 at 19 56 50](https://user-images.githubusercontent.com/5716596/42137231-07954142-7d69-11e8-90b9-4f9ae850a552.png)

What look like you model please ?

**Comment by MattAurich** [comment] 2018-07-02 14:57
![image](https://user-images.githubusercontent.com/5571444/42171164-336f6d68-7dde-11e8-9a84-cb94f3b32fd5.png)

**Comment by MattAurich** [comment] 2018-07-02 14:59
My model, though it is freshly generated with just some console logs. I updated strapi to the latest version (3.0.0-alpha.12.6) to generate the above response.
```
'use strict';

/**
 * Lifecycle callbacks for the `Stuff` model.
 */

module.exports = {
  // Before saving a value.
  // Fired before an `insert` or `update` query.
  beforeSave: async (model) => {
    console.log('beforeSave: ');
  },
  

  // After saving a value.
  // Fired after an `insert` or `update` query.
  afterSave: async (model, result) => {
    console.log('afterSave: ');
  },
  

  // Before fetching all values.
  // Fired before a `fetchAll` operation.
  beforeFetchAll: async (model) => {
    console.log('beforeFetchAll: ');

  },

  // After fetching all values.
  // Fired after a `fetchAll` operation.
  afterFetchAll: async (model, results) => {
    console.log('afterFetchAll: ');
  },
  

  // Fired before a `fetch` operation.
  beforeFetch: async (model) => {
    console.log('beforeFetch: ');

  },

  // After fetching a value.
  // Fired after a `fetch` operation.
  afterFetch: async (model, result) => {
    console.log('afterFetch: ');
  },

  // Before creating a value.
  // Fired before an `insert` query.
  beforeCreate: async (model) => {
    console.log('beforeCreate: ');
  },

  // After creating a value.
  // Fired after an `insert` query.
  afterCreate: async (model, result) => {
    console.log('afterCreate: ');
  },

  // Before updating a value.
  // Fired before an `update` query.
  beforeUpdate: async (model) => {
    console.log('beforeUpdate: ');
  },

  // After updating a value.
  // Fired after an `update` query.
  afterUpdate: async (model, result) => {
    console.log('afterUpdate: ');
  },

  // Before destroying a value.
  // Fired before a `delete` query.
  beforeDestroy: async (model) => {
    console.log('beforeDestroy: ');
  },

  // After destroying a value.
  // Fired after a `delete` query.
  afterDestroy: async (model, result) => {
    console.log('afterDestroy: ');
  }
};
```

**Comment by MattAurich** [comment] 2018-07-02 15:03
From my understanding of the comments in the model file, the generated output for an 'update' should be:
```
beforeSave:
afterSave:
beforeFetch: 
afterFetch: 
beforeUpdate: 
afterUpdate: 
beforeFetch: 
afterFetch: 
beforeFetch: 
afterFetch: 
```
And the generated output for a create should be:
```
beforeCreate: 
afterCreate: 
beforeSave: 
afterSave: 
beforeFetch: 
afterFetch:  
beforeFetch: 
afterFetch: 
beforeFetch: 
afterFetch:
```

**Comment by lauriejim** [comment] 2018-07-03 10:33
Please update to `alpha.12.6` to have `save` fire on `update`.

About `update` on `create` action, it's because the content manager `create` then entry data and then `update` for relations data.

**Comment by MattAurich** [comment] 2018-07-03 14:35
I did a fresh install of ```alpha.12.6``` after doing an uninstall of strapi, then created a brand new project for the above example. You've tried it with a PUT request?

Interesting, about the update action being how strapi works for relations data, so does it run across every object in the model? (Just for clarity, it can't be the actual 'Content Manager' plugin, as it still does it on curl request or if the plugin is removed.)

**Comment by henrych4** [comment] 2018-07-20 03:48
I just come across with similar problem and I have updated strapi to `alpha.12.6` but neither `beforeSave` nor `afterSave` is fired. 

**Informations**
- **Node.js version**: 9.0.0
- **npm version**: 5.5.1
- **Strapi version**: 3.0.0-alpha.12.6
- **Database**: MongoDB
- **Operating system**: macOS High Sierra Version 10.13.1

**Steps to reproduce the problem**
* create a content type with a text field
* add code to log event message in model file
* create a record on cms and then save it
log result:
<img width="159" alt="screen shot 2018-07-20 at 11 40 15 am" src="https://user-images.githubusercontent.com/19466940/42982024-e4c87906-8c11-11e8-8779-694dd8ab6ea6.png">

* click on just created record, update text field and save it
<img width="160" alt="screen shot 2018-07-20 at 11 43 25 am" src="https://user-images.githubusercontent.com/19466940/42982067-2599598c-8c12-11e8-878b-3d5b5f724f81.png">

**Comment by lauriejim** [comment] 2018-10-07 18:49
It's not related to Strapi. Please check https://github.com/Automattic/mongoose/issues/419

**Comment by g-div** [comment] 2018-10-25 09:14
If `beforeSave`/`afterSave` aren't fired on *update* but only on *insert* then means that using `beforeSave`/`afterSave` is the same as using `beforeCreate`/`afterCreate`. In this case I don't really understand why do we need both.
Otherwise means that the following comment it's wrong or at least misleading:
>  // Fired before an `insert` or **`update`** query.

this is somehow related to Strapi.

**Comment by duurland** [comment] 2018-11-14 18:11
Just installed my 1st strapi app to test it out and was quite confused about the callbacks.

- When creating an entry `*Update` is triggered.
- When updating `*Save` is not triggered.
- When deleting a single entry `*Destroy` is not triggered.
- When deleting multiple/all `*Destroy` is not triggered, however `*Update` is. 

Surely this can't be intended?

![https://i.imgur.com/sMoBw9H.png](https://i.imgur.com/sMoBw9H.png)

Node.js version: 10.11.0
npm version: 5.7.1
Strapi version: 3.0.0-alpha.14.5
Database: MongoDB
Operating system: Windows 10 Pro x64 v1803

---

> @lauriejim : About `update` on `create` action, it's because the content manager `create` then entry data and then `update` for relations data.

Guess that answers by first questions, however, what's the use for `save`, if `update` is always ran?

**Comment by henrych4** [comment] 2018-12-04 16:12
Would you mind to check _update object inside model? You may something useful.

**Comment by krsnaa** [comment] 2018-12-05 10:36
@henrych4 - thanks for your comment. I did come across the _update object, and while it does contain the atomic properties changed, it does not seem to contain any of the identifiers (like the id attribute) that I can use to grab the entire object.

**Comment by henrych4** [comment] 2018-12-05 14:02
The id can be found in _conditions object.

**Comment by krsnaa** [comment] 2019-02-07 05:29
In 3.0.0-alpha.22, before/afterUpdate lifecycle methods do not fire when updating a value using the content manager or using a PUT request. 

before/afterDestroy do not fire when deleting using the UI, but they work when sending a DELETE request.

Very frustrating when trying to implement a websocket model to sync with downstream systems as there is no data consistency anymore.

**Comment by krsnaa** [comment] 2019-02-07 05:36
https://github.com/strapi/strapi/issues/2779

**Comment by genu** [comment] 2019-03-06 13:14
I can confirm that this is still an issue in `3.0.0-alpha.24.1`

**Comment by csotiriou** [comment] 2019-03-18 15:12
I think that we have identified the issue here.

This pull request here is what broke this functionality:
https://github.com/strapi/strapi/pull/2682

So, now in the connector, in here:

```
                const preLifecycle = {
                  validate: 'beforeCreate',
                  findOneAndUpdate: 'beforeUpdate',
                  findOneAndRemove: 'beforeDestroy',
                  remove: 'beforeDestroy',
                  update: 'beforeUpdate',
                  find: 'beforeFetchAll',
                  findOne: 'beforeFetch',
                  save: 'beforeSave'
                };
```
There should also be a `updateOne` there, because after this pull request the mongoose hook slightly changes!!

**Comment by henrych4** [comment] 2019-03-19 02:05
beforeUpdate/afterUpdate should be triggered after the fix in #2905. Upgrade strapi to latest version and it should work as expected.

However, lifecycle methods related to save and destroy are not fired. The problem exists since very earlier version of strapi.

**Comment by jacargentina** [comment] 2019-06-18 20:07
Are lifecicle events working on 3.0.0-beta.5/6 ??

When i call in a given controller this code:

```javascript
const release = await strapi.services.release.create(relParams);
``` 

code on `api/release/models/Release.js, method beforeSave` is not being called; what i'm missing ?

**Comment by Gribbs** [comment] 2019-06-21 12:08
I'm finding beforeSave is not firing for me either. I'm using "3.0.0-beta.6"

`  // Before saving a value.
  // Fired before an `insert` or `update` query.
  beforeSave: async (model, attrs, options) => {
    console.log(attrs,options);
  },`
I'm never seeing the console.log

**Comment by lauriejim** [comment] 2019-06-22 13:46
Hello! I just tried to implement your service call in a custom controller function.
And the `Release` lifeCycle function is called.

I don't know how you implement it but it works.

**Comment by jacargentina** [comment] 2019-06-24 16:25
@lauriejim i've found `beforeSave` is broken! I've replaced with `beforeCreate` and `beforeUpdate`

**Comment by jacargentina** [comment] 2019-06-27 23:00
@lauriejim also i 've found `beforeUpdate`is called twice, first call `model` has a `Query` with a `_update` field containing new values; later second call the `_update` field contains an empty object

**Comment by dominikg** [comment] 2019-07-11 12:17
this is still an issue in beta.11.

beforeSave/afterSave don't fire for PUT requests and beforeUpdate/afterUpdate fire twice

**Comment by lauriejim** [comment] 2019-08-14 09:50
We have to plug life cycle functions to the `core queries` instead of native Models life cycle functions.

**Comment by Palgie** [comment] 2019-09-09 08:05
Would love for this to get improved. Have enjoyed utilising the lifecycle methods but as everyone's saying here, it's really difficult to make use of them properly if the lifecycle can only cover half of the CRUD operations.

In my case the beforeUpdate and afterUpdate fired twice. Found a little bit of hope in the save lifecycle as a way to bypass the update firing but haven't been able to correctly trigger the destroy hooks. In my case I'm using hooks to mirror product changes into Stripe and lack of delete leaves a lot of junk that has to be manually cleaned up whenever the dataset changes a whole bunch.

**Comment by AntoninBeaufort** [comment] 2019-09-13 10:37
For me afterUpdate fired twice too on beta.16.1

**Comment by websocket98765** [comment] 2019-09-26 22:01
**Additional bug related to lifecycles:**

When using `model.set()` to modify a model, the altered model is not stored in the databse during **updated**-related callbacks, but is stored successfully during insert-related callbacks.

**Examples:**

```js
// Works as expected and the modified model is stored in the DB.
beforeCreate: async (model, attrs, options) => {
  console.log('model before:', model);
  model.set('foo', 'modifying on insert sets the value successfully!');
  console.log('model after:', model); // this is stored in DB
},

// BROKEN: The modified model logs successfully, but is not stored in the DB;
// the UNmodified model is stored in the DB.
beforeUpdate: async (model, attrs, options) => {
  console.log('model before:', model); // Stored in DB
  model.set('foo', 'does not update this value');
  console.log('model after:', model); // Not stored in DB, but should be. Bug!
},
```

Note that when using the `beforeSave()` callback, similar behavior occurs--i.e. if it's an insert, the modified model is stored in the DB; if it's an update, the modified model is NOT stored and the UNmodified model is stored.

**Comment by mcaulirealt** [comment] 2019-09-30 11:04
> **Additional bug related to lifecycles:**
> 
> When using `model.set()` to modify a model, the altered model is not stored in the databse during **updated**-related callbacks, but is stored successfully during insert-related callbacks.
> 
> **Examples:**
> 
> ```js
> // Works as expected and the modified model is stored in the DB.
> beforeCreate: async (model, attrs, options) => {
>   console.log('model before:', model);
>   model.set('foo', 'modifying on insert sets the value successfully!');
>   console.log('model after:', model); // this is stored in DB
> },
> 
> // BROKEN: The modified model logs successfully, but is not stored in the DB;
> // the UNmodified model is stored in the DB.
> beforeUpdate: async (model, attrs, options) => {
>   console.log('model before:', model); // Stored in DB
>   model.set('foo', 'does not update this value');
>   console.log('model after:', model); // Not stored in DB, but should be. Bug!
> },
> ```
> 
> Note that when using the `beforeSave()` callback, similar behavior occurs--i.e. if it's an insert, the modified model is stored in the DB; if it's an update, the modified model is NOT stored and the UNmodified model is stored.

i have the same problem and need to save the modified model, any solutions?

**Comment by derrickmehaffy** [comment] 2019-09-30 11:10
@mcaulirealt for now I wouldn't recommend using Lifecycle callbacks as they are effectively broken until the new DBAL layer is done.

**Comment by websocket98765** [comment] 2019-09-30 17:22
@mcaulirealt No solution yet until lifecycles callbacks are fixed.

**Comment by AlexanderYW** [comment] 2019-10-23 11:09
@websocket98765 have you tried using setTimeout inside the function with a 100 or 1000 ms before executing the code?

That worked for me in the `afterCreate` function on Strapi 3.0.0-beta.16.8

**Comment by slashvortal** [comment] 2019-10-24 17:15
Any updates on this topic or a temporary alternative to **model.set** with beforeUpdate or beforeSave?
_(Using PUT method)_

**Comment by derrickmehaffy** [comment] 2019-10-25 10:12
I have updated the original post and am linking all other lifecycle callback issues here.

**Comment by lauriejim** [comment] 2019-10-27 09:01
Thank you for that @derrickmehaffy.

**Comment by abdonrd** [comment] 2019-10-28 10:09
There are any ETA to fix this? Thanks in advance!

**Comment by derrickmehaffy** [comment] 2019-10-28 14:13
@abdonrd no updated ETA yet. I think the DBAL layer is coming here soon (beta.18 I think?) but it's just the core stuff. However after it initially gets added I think @alexandrebodin will likely start poking at this a bit more. It's a fairly complex fix that almost needs a rewrite since the callbacks will change from being dependent on the upstream hook packages (mongoose/bookshelf) to the dbal layer.

**Comment by RicardsRikmanis** [comment] 2019-11-13 11:09
Is there any WIP available? Would be useful since we are thinking of fixing the missing relations on beforeSave actions while waiting for full rework.

**Comment by emukans** [comment] 2019-11-22 15:05
As temporary workaround of not working `model.set()` in beforeSave method, I define a callback outside of beforeSave scope and execute it asynchronously in afterSave. And then I reset the callback.

E.g.
```
let postProcessAction = null;

module.exports = {
    beforeSave: async (model) => {
        let fieldToUpdate = {};

        if (checkIfPostProcessIsNeeded(model)) {
            fieldToUpdate = { foo: 'Bar' };
        }

        if (Object.keys(fieldToUpdate).length !== 0) {
            postProcessAction = () => strapi.query('model').update({ id: model.attributes.id }, fieldToUpdate);
        }
    },
    afterSave: async () => {
        if (postProcessAction) {
            postProcessAction().catch((error) => {
                console.log('Error', error);
            });
            postProcessAction = null;
        }
    }
};
```

**Note:**
You can't execute `postProcessAction` with `await` since an entity is in a transaction and is locked for an update in afterSave event

**Comment by jc111t** [comment] 2019-12-03 17:46
@emukans with your temporary workaround were you able to have the response update within the same query.  For example, I used your workaround and it'll save the points value and update the score (updated in the beforeUpdate lifecycle) in an updateUser query like:

```graphql
mutation updateUser ($id: ID! ) {
  updateUser(input: {
    where: {
      id: $id
    },
    data: {
      points: 1383
    }
  }), {
    user {
      id
      email
      score
      points
    }
  }
}
```

The score in the response is the old score (but the score is updated in the db as the new score).

**Comment by emukans** [comment] 2019-12-03 22:51
Hi @jc111t,
No with the workaround above you won't see updates in the same query since the actual update happens asynchronously after the update. In my case, the update query returns just success/fail and error message if there some. Maybe you can revise your logic to something similar until life cycle events are reviewed.

**Comment by therobster121** [comment] 2019-12-21 06:26
Can anyone suggest a workaround to:
afterCreate() being called twice when using Groups Field #4166.
#4166 was closed but no update on when new webhooks  feature  will be delivered

**Comment by derrickmehaffy** [comment] 2019-12-21 06:45
@therobster121 

https://portal.productboard.com/strapi/1-public-roadmap/c/27-webhooks

ETA is Q4 2019 though it might be pushed to Q1 2020

**Comment by MaffooBristol** [comment] 2020-01-06 17:10
Thanks @emukans - your solution is definitely helpful but I think the whole splitting before/after is unnecessary unless I am missing something?

This worked for me:
```javascript
// api/blog/models/Blog.js

const slug = require('slug');

module.exports = {
  afterSave: async (model, attrs, options) => {
    const title = model.attributes.Title || model.attributes.title || null;
    if (title) {
      strapi.query('blog').update({ id: model.attributes.id }, { slug: slug(title, { lower: true }) });
    }
  },
};
```

**Comment by wysher** [comment] 2020-01-22 12:45
@lauriejim Webhooks has arrived and I assume that for now this is the way to handle changes (requires adding webhook and controller). Which is fine, and working properly like `after` Create/Update/Delete callbacks, which handles most cases, but what with `before`?

Do you plan review of callbacks any time soon?

I'm asking because have a deadline comming and wonder if I should go with webhooks or wait for callbacks.

**Comment by sarneeh** [comment] 2020-01-22 13:02
> @lauriejim Webhooks has arrived and I assume that for now this is the way to handle changes (requires adding webhook and controller). Which is fine (...)

I don't agree. Using webhooks to call ourselves just to do something after creating/updating/deleting an entry is a real overkill. It would probably work, but it's a dirty hack.

**Comment by alexandrebodin** [comment] 2020-01-22 13:05
We want to do this before april 2020 but no exact deadline for it right now :/

**Comment by wysher** [comment] 2020-01-22 13:10
@sarneeh You're right. It's hacky, it's dirty. But work need to be done so I need to use something that works, unlike lifecycle methods.

@alexandrebodin thanks. Looking forward for that :)

**Comment by alexandrebodin** [comment] 2020-01-22 13:28
BTW, if someone wants to contribute and help us work on that please let me know on slack ;)

**Comment by sarneeh** [comment] 2020-01-22 13:30
> @sarneeh You're right. It's hacky, it's dirty. But work need to be done so I need to use something that works, unlike lifecycle methods.

You can override the content-manager plugin and hook into `create/update/delete/...` there 😃 Like this:

**extensions/content-manager/services/ContentManager.js**
```
const OriginalContentManager = require('strapi-plugin-content-manager/services/ContentManager')

module.exports = {
  async create(...args) {
    // ...your logic
    return OriginalContentManager.create(...args)
  },

  async edit(...args) {
    // ...your logic
    return OriginalContentManager.edit(...args)
  },

  async delete(...args) {
    // ...your logic
    return OriginalContentManager.delete(...args)
  }
}
```

**Comment by DekiGk** [comment] 2020-01-24 23:29
Thank you for giving us Webhooks within Strapi.

Does someone know if webhooks between Strapi and Gatsby work locally? If so, is there some payload I should pass through? Does anyone have a link of how to do this?

I am following this guide: https://strapi.io/documentation/3.0.0-beta.x/concepts/webhooks.html#what-is-a-webhook and I am having trouble updating (rebuilding) my Gatsby data once I update some entry in Strapi.

P.S. I am working locally using Postgres DB

**Comment by sarneeh** [comment] 2020-01-25 07:54
> Thank you for giving us Webhooks within Strapi.
> 
> Does someone know if webhooks between Strapi and Gatsby work locally? If so, is there some payload I should pass through? Does anyone have a link of how to do this?
> 
> I am following this guide: https://strapi.io/documentation/3.0.0-beta.x/concepts/webhooks.html#what-is-a-webhook and I am having trouble updating (rebuilding) my Gatsby data once I update some entry in Strapi.
> 
> P.S. I am working locally using Postgres DB

Webhooks are HTTP requests, you'd need a server locally which has an endpoint that triggers a rebuild for your Gatsby website. Then you can attach this into a Strapi webhook.

**Comment by DekiGk** [comment] 2020-01-26 01:23
> @DekiGk Webhooks are HTTP requests, you'd need a server locally which has an endpoint that triggers a rebuild for your Gatsby website. Then you can attach this into a Strapi webhook.

I know this as I have seen the previous workaround. 

Unfortunately it took a bit more of digging until I made it work and I am putting this here for whoever stumbles upon the same issue. For `Gatsby` there is an `ENV` variable you can add to expose the endpoint that is needed to update GraphQL data. `ENABLE_GATSBY_REFRESH_ENDPOINT=1` should be added to your `.env file` and then you should just trigger a `POST` request to `http://localhost:8000/__refresh` and that should work.

More details can be found here:
https://github.com/gatsbyjs/gatsby/issues/14395#issuecomment-496977070
https://www.gatsbyjs.org/docs/environment-variables/#reserved-environment-variables

**Comment by sarneeh** [comment] 2020-01-26 04:35
@DekiGk Please read the comments in the [issue you've mentioned](https://github.com/gatsbyjs/gatsby/issues/14395#issuecomment-496977070). This method apparently does not work in Gatsby.

**Comment by DekiGk** [comment] 2020-01-26 21:32
@sarneeh It works locally for me. Haven't tested staging and production yet, but seems to work as expected.

**Comment by alexandrebodin** [comment] 2020-01-27 09:29
Hi, for staging and production the rebuild will need to be triggger via your deploy tool (e.g netlify, gitlab etc)

**Comment by dominikg** [comment] 2020-01-27 09:56
I am subscribed here in anticipation of lifecycle calkbacks getting fixed. I don't think webhooks provide an adequate workaround and would appreciate if you move discussions unrelated to lifecycle callbacks to separate issues or slack.

**Comment by Elementrat** [comment] 2020-02-06 21:49
Is there an item where we can track the progress on this issue in ProductBoard? 
This is a big one for us too, really looking forward to resolution.

**Comment by emaddoma** [comment] 2020-02-06 23:24
Unfortunately for us, this is a dealbreaker.  We need to geocode address data, so we initially set out to create a custom field type that used Google Places Autocomplete.  That approach turned out to be a dead end because there are no front end customization hooks.  Then we looked at these lifecycle hooks in hopes of using Google Maps API.  Such a bummer.

**Comment by derrickmehaffy** [comment] 2020-02-13 08:40
@Elementrat no it's not on the product board as there is for features. This issue is the tracking one.

**Comment by mik3lov3st3ch** [comment] 2020-02-13 10:40
It looks like that M2M relations are not respected in the args passed to the callbacks.

**model settings:**
![image](https://user-images.githubusercontent.com/60316761/74426334-73310300-4e55-11ea-96f9-bc92438ec8c5.png)

**callback on that model:**
![image](https://user-images.githubusercontent.com/60316761/74426373-89d75a00-4e55-11ea-9db2-ed5fea908dca.png)

**log output -> "products" is missing:**
![image](https://user-images.githubusercontent.com/60316761/74426428-a4113800-4e55-11ea-87fe-ab37916fe57d.png)

**Comment by vietlongn** [comment] 2020-02-17 08:05
There is an inconsistency in the life cycle callbacks.
`beforeCreate`, `afterCreate`, `beforeSave` and `afterSave` return a Model object while others return a Query object.
`beforeSave: async (model) => {
    console.log('beforeSave: ', model.constructor.name);
  }`
Result:
![image](https://user-images.githubusercontent.com/6986991/74634623-d3e27780-5196-11ea-9502-ffedfe47bdc3.png)

**Comment by aksdevac** [comment] 2020-03-11 12:42
@derrickmehaffy  as Usage of this right now is not recommended, so how can I customise update method that is called from strapi admin entity service, it seems it is generalized service(strapi.entityService) & if we write custom update service in Model's service it won't get called from admin UI, I want create password hash before saving my custom User model, is it possible to do without using this life cycle method?

**Comment by derrickmehaffy** [comment] 2020-04-02 18:41
> @derrickmehaffy as Usage of this right now is not recommended, so how can I customise update method that is called from strapi admin entity service, it seems it is generalized service(strapi.entityService) & if we write custom update service in Model's service it won't get called from admin UI, I want create password hash before saving my custom User model, is it possible to do without using this life cycle method?

For now, you will need to override the controllers in the content-manager plugin:

https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/controllers/ContentManager.js

**Comment by ayhid** [comment] 2020-04-11 22:08
Hello I am new to strapi, and I stumbled upon this issue while trying to implement  `afterSave` hook to send my saved model to algolia search. the `afterSave`hook is fired 3 times and only id 's are fetched on my related models.

@derrickmehaffy I am interested in your solution is there any documentation about overriding plugins ?

**Comment by derrickmehaffy** [comment] 2020-04-14 05:57
> Hello I am new to strapi, and I stumbled upon this issue while trying to implement `afterSave` hook to send my saved model to algolia search. the `afterSave`hook is fired 3 times and only id 's are fetched on my related models.
> 
> @derrickmehaffy I am interested in your solution is there any documentation about overriding plugins ?

@ayhid 
https://strapi.io/documentation/3.0.0-beta.x/getting-started/troubleshooting.html#how-do-i-customize-a-plugin

**Comment by ayhid** [comment] 2020-04-14 21:20
@derrickmehaffy  thanks a lot I managed to override the plugin & do things as I want. It's a little bit clunky but It will do for now.

**Comment by ashbuilds** [comment] 2020-04-16 05:06
Hi, Any updates on this issue: https://github.com/strapi/strapi/issues/3863

**Comment by derrickmehaffy** [comment] 2020-04-16 06:14
> Hi, Any updates on this issue: #3863

As this issue suggests @ashbuilds LC callbacks are currently broken so the above workarounds should be used instead. For the moment there is no news other than this issue will be fixed before stable.

It's not an easy issue to fix directly as previously these callbacks were based on the ORMs themselves, in which they are failing because those ORMs have removed many options so the LC CBs have to be moved to Strapi logic instead. After the few remaining features are added, I believe the Strapi team plan to dedicate quite a bit of time into "bug fixes" (they have already been doing that for critical/high priority ones, this not being either) before stable.

**Comment by ashbuilds** [comment] 2020-04-16 17:03
@derrickmehaffy I totally understand, Thanks for your quick response. Could you please tell me the possible release date for stable version? 
And thanks again. I appreciate what Strapi has done ❤️

**Comment by derrickmehaffy** [comment] 2020-04-17 00:03
> @derrickmehaffy I totally understand, Thanks for your quick response. Could you please tell me the possible release date for stable version? 
> And thanks again. I appreciate what Strapi has done ❤️

There is no set date for that yet

**Comment by ashbuilds** [comment] 2020-04-17 08:28
Thanks 🙂
For now I'm just using some extra fields to solve this issue specially for `beforeSave`. Later refactor the code to use LC once this is fixed. 
Have a nice day. 

<img width="558" alt="Screenshot 2020-04-17 at 3 25 48 PM" src="https://user-images.githubusercontent.com/2686288/79548491-ba3ead00-80bf-11ea-859b-3ec9a4b4cd93.png">

**Comment by abdonrd** [comment] 2020-04-23 16:11
New draft PR! https://github.com/strapi/strapi/pull/5927

**Comment by derrickmehaffy** [comment] 2020-05-14 19:07
This has been fixed in rc.0 and there is currently no plans to backport it to the beta versions. Migration to the rc tagged releases is not currently recommended but the stable release is expected by the end of this month (may 2020).

For now I am marking this as closed.

**Closed by derrickmehaffy** 2020-05-14 19:07 UTC
Labels: priority: high, priority: medium, source: core:database, status: confirmed

**Comment by TheHelias** [comment] 2020-06-05 17:22
Life cycle callbacks are still not working in stable version 3.0.1

**Comment by wysher** [comment] 2020-06-05 17:29
@TheHelias There was some breaking changes in lifecycle methods. I tested them and all works fine.

Remember that new lifecycle methods must me inside `lifecycles` object inside model file, like so:

```js
module.exports = {
  lifecycles: {
    async beforeCreate(data) {
        // do sth with data
    },
  },
};
```

Here's more examples: https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks

If you encountered some problems with lifecycle methods, could You please provide more information?

**Comment by TheHelias** [comment] 2020-06-05 19:02
It works now. Didn't notice this (Remember that new lifecycle methods must me inside lifecycles object inside model file, like so:) earlier. Good job!

**Comment by gtamas** [comment] 2020-06-07 12:02
@derrickmehaffy 
@TheHelias 
or anyone :)

How do you call a lifecycle hook manually (using Mongo)?

strapi.query(modelName).model.lifecycles is undefined, so the Bookshelf way doesn't work.

**Comment by derrickmehaffy** [comment] 2020-06-07 12:09
> @derrickmehaffy 
> @TheHelias 
> or anyone :)
> 
> How do you call a lifecycle hook manually (using Mongo)?
> 
> strapi.query(modelName).model.lifecycles is undefined, so the Bookshelf way doesn't work.
> 

You can't directly call it manually (as of yet). But if you call the normal `strapi.query('model').action()` such as find, findOne, create, update, or delete. The lifecycles will trigger. Lifecycles are attached to those actions.

**Comment by derrickmehaffy** [comment] 2020-06-07 12:11
I'm going to lock this thread as the lifecycles have been fixed and any further discussion will be off topic. Any questions should be directed towards the [discussions](https://github.com/strapi/strapi/discussions)
