### ISSUE TITLE
Rename the users-permissions tables to conform the GraphQL and SQL naming standard.

### ISSUE THREAD

**Issue by EAdeveloper** [strapi/strapi#7447] opened 2020-08-12 16:54 UTC
Hello 👋 Strapi  team,
 
Please rename the following tables to conform the GraphQL and SQL naming standard.

1. **users-permissions_permission** should be rename to **users_permissions_permission**
2. **users-permissions_role** should be rename to **users_permissions_role**
2. **users-permissions_user** should be rename to **users_permissions_user**

![image](https://user-images.githubusercontent.com/21114220/90042137-4345a980-dc98-11ea-85de-ada80bbded65.png)

![image](https://user-images.githubusercontent.com/21114220/90042781-21005b80-dc99-11ea-8857-f28072b99369.png)

`{
  "kind": "collectionType",
  "collectionName": "users_permissions_user",
  "info": {
    "name": "user",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
}`

**Comment by derrickmehaffy** [comment] 2020-08-12 17:11
Duplicate of: https://github.com/strapi/strapi/issues/7446

@EAdeveloper please follow our bug report template.

**Closed by derrickmehaffy** 2020-08-12 17:11 UTC
