### ISSUE TITLE
Number field doesn't accept periods for decimal/floats. Not able to save Content Type entry that has number fields

### ISSUE THREAD

**Issue by jeanmaried** [strapi/strapi#1697] opened 2018-08-05 13:48 UTC
**Informations**
- **Node.js version**: v10.8.0
- **npm version**: 6.2.0
- **Strapi version**: 3.0.0-alpha.13.0.1
- **Database**: mongodb
- **Operating system**: macOS High Sierra

**What is the current behavior?**
When entering a period in a number field inside a Content Type for any of the three available number formats, any number that was already entered is removed and replaced by a 0. The 0 cannot be removed after. It can only be changed with the up/down arrows. A coma for decimal separation seems to work which is no good for me.

**Steps to reproduce the problem**
Create a Content Type, add any of the available number fields to it. Go to make a new entry in your new Content Type. Type a few numbers in a number field and then try typing a period.

**What is the expected behavior?**
Being able to have a period for decimal separation. Not having to refresh to remove the 0 that gets stuck in the field.

**Suggestions**
Maybe remove the up down arrows? Seems pointless to me for a simple number input.

**Comment by derrickmehaffy** [comment] 2018-08-06 06:11
AdminUI related issue with zero in number fields: https://github.com/strapi/strapi/issues/1077

As for not being able to use decimals @jeanmaried I cannot replicate this. What browser are you using?

**Comment by derrickmehaffy** [comment] 2018-08-06 06:11
@soupette is the zero thing a limitation of react?

**Comment by jeanmaried** [comment] 2018-08-06 09:05
@derrickmehaffy I am using the latest version of Chrome. I am located in France but have my browser and strapi are set to US english. I know in France comas are used for decimals so maybe this has something to do with it.

**Comment by derrickmehaffy** [comment] 2018-08-06 09:28
@jeanmaried that is likely, to confirm you are trying to type:

`1234.567` and not `1234,5678`

(side note how do you guys comma-eliminate large values O_o like `123,456,678.1234`)

**Comment by jeanmaried** [comment] 2018-08-06 09:42
Correct. I am trying to type `1234.567` as I would be using this field for a USD$ price in my project.

As far as I remember, in France the coma and period are the opposite of the US. So `123,456,678.1234` in the US would be `123.456.678,1234` in France (or just spaces instead of the periods, not sure what is most common).

**Comment by derrickmehaffy** [comment] 2018-08-06 09:53
(Incoming typical pig-headed american comment, you were warned)

That is just backa**wards :stuck_out_tongue_winking_eye: Anyway, if you try changing your Strapi AdminUI to French do you also have this issue?

Also, can't remember where, but I believe there is a setting chrome that also changes to a different language. If you try setting that to either US/UK English does it still show up? What I find odd is that the Strapi team is based in France and don't seem to have hit this issue (and I know @lauriejim does a ton of testing)

**Comment by jeanmaried** [comment] 2018-08-06 10:29
I will check it out when i get home tonight! Thank you @derrickmehaffy

**Comment by soupette** [comment] 2018-08-06 13:31
@jeanmaried Well I think that we should keep the ISO standard for the numbers and have configuration in the admin so they can be displayed as 1.222,65 instead of 1222,65.

You can easily fix the bug that returns 0 when you add a period by changing the line 217 in `content-manager/admin/src/containers/EditPage/index.js` to `parseFloat(e.target.value)` however after trying it it happens that it returns NaN, so I wouldn't recommend it.

**Comment by jeanmaried** [comment] 2018-08-06 14:38
@soupette I think you misunderstood me. I just want to be able to use periods for decimal separation. I'm not looking to do this `1.222,65`. I want this: `1222.65` where `.` is the decimal separator.

Currently I can only use a coma to separate decimals. When I hit the period it replaces everything with 0. Shouldn't the period be the standard for decimals separation?

**Comment by jeanmaried** [comment] 2018-08-06 19:13
@derrickmehaffy When I change Strapi Admin UI to french it still does it. I have my browser language set to US english.

**Comment by jeanmaried** [comment] 2018-08-07 06:26
@derrickmehaffy @soupette I feel like something might be wrong with my install. I noticed that when saving a new Content Type I get the error `HEAD http://localhost:1337/_health 0 ()` 50 times and then it saves. I've tried reinstalling strapi and that doesn't seem to do anything. Any ideas?

**Comment by derrickmehaffy** [comment] 2018-08-07 06:39
@jeanmaried I don't have another Mac handy to try and recreate your environment but can you give exact versions of everything you can think of to see if we can find the root cause?

I'm not a mongo user myself but that shouldn't be causing an issue with the frontend, I've done quite a bit of testing between different browsers and OSes and am not able to reproduce this issue at all.

Have you made any changes to the admin? (Like creating a project with --dev)?

**Comment by jeanmaried** [comment] 2018-08-07 06:49
I haven’t made any changes to the admin. I’m going to attempt another install on my work Mac in a little bit.

I found this which seems to describe my issue as being a problem with React/Chrome:

https://github.com/facebook/react/issues/7253

**Comment by derrickmehaffy** [comment] 2018-08-07 07:07
Hmmm good catch @jeanmaried not sure which version of react Strapi uses but based on how old that issue thread is. :thinking:

**Comment by jeanmaried** [comment] 2018-08-07 08:42
I just did a fresh install of Strapi and mongoDB on my work Mac. Same exact problem...

Here are the exact steps I followed:
1) started mongodb with `mongod`
2) installed strapi `npm install strapi@alpha -g`
3) created project `strapi new strapi-test`
4) `cd strapi-test`
5) `strapi start`
6) create user and login
7) click on Content Type Builder and create new Content Type `stuff`
8) add 3 number fields (integer, float, decimal)
9) save and click on my new Content Type `stuff`
10) add new `stuff` entry
11) type 123 in any of the number fields then type `.` and bug persists

**Comment by jeanmaried** [comment] 2018-08-07 09:06
Ah... i figured out. I had to change my country settings in my Mac, not my browser. That's why both my personal and work Mac had the same behavior. The really buggy behavior when typing a period with my region set to France really threw me off!

**Comment by derrickmehaffy** [comment] 2018-08-07 09:07
I would keep this open as a workaround will still need to be implemented if it affects other users. @soupette have you come across this (assuming the teams Macs are set to french)

**Comment by derrickmehaffy** [comment] 2018-08-07 09:10
@maturano can you test with your browser/system set to Spanish (AFAIR you are also running a mac)

**Comment by maturano** [comment] 2018-08-07 20:30
@derrickmehaffy I wish! 😅 ... I have Windows and I'm working on WSL.

I barely test the case and I can tell you I experienced the same behavior trying to use `,` as decimal separator (here, we use `.`); all is replaced by a `0`.

If you want to test more deeply, let me know ;)

**Comment by byoungd** [comment] 2018-09-26 03:49
I have the same issue.
Node :  v8.9.4
Mac OS: 10.14
Mac Language: Chinese
Strapi: v3@alpha.14

---

When I use the Number with Float field, typed in number like 123.12 or 123, it throw a alert 
`
This not,a,valid,Decimal,128,string is already taken
`

**Comment by JZFLei** [comment] 2018-09-26 05:44
@byoungd That's fixed in the next release. Referencing #1924 for your information.

**Comment by soupette** [comment] 2018-09-26 16:29
Thanks all!
I'm closing the issue then.

**Closed by soupette** 2018-09-26 16:29 UTC
Labels: priority: low, type: enhancement 💅

**Comment by generalMashuka** [comment] 2023-06-08 13:04
Hi everyone! 
Experiencing same issue when trying to enter lat/lng in a float number field. Strapi doesn't let me put a dot as a separator (-99.15543410014578), but when I enter it with a comma (-99,15543410014578) and save - it is saved with a dot. this is a strange behaviour that will affect the work of my content manager team.
Node.js version: v16.19.0
npm version: 8.19.3
Strapi version: 4.10.2
Database: postgresql
Operating system: macOS 13.1
