### ISSUE TITLE
Strapi doesn't work with Cyrillic text - throws ER_TRUNCATED_WRONG_VALUE_FOR_FIELD error

### ISSUE THREAD

**Issue by r007** [strapi/strapi#2699] opened 2019-01-28 12:22 UTC
**Informations**
- **Node.js version**:  11.1.0
- **NPM version**: 6.4.1
- **Strapi version**:  3.0.0-alpha.16
- **Database**: MySQL 5.7.24-0ubuntu0.18.04.1
- **Operating system**: Ubuntu 18.04
- **(Optional) Link to your Project**:  Local project

**What is the current behavior?**

Any cyrillic text, for example "новая запись в блоге" entered in any field will cause an error during saving. A popup with error message saying:

```update `posts` set `Title` = 'Новая запись', `id` = 4, `categories` = 1, `updated_at` = '2019-01-28 14:54:45.120' where `id` = 4```

*ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xD0\x9D\xD0\xBE\xD0\xB2...' for column 'Title' at row 1*

Current DB character encoding set: latin1. Should be utf8mb4 instead.

**Steps to reproduce the problem**

1. Use MySQL as the database.
2. Enter "новая запись" in any field.

**Suggested solutions**

Convert the character encoding set to UTF-8.

**Comment by derrickmehaffy** [comment] 2019-01-28 12:43
@r007 Strapi doesn't handle the database local setting, that is something you will need to change (it would have been set when you created the database)

**Comment by derrickmehaffy** [comment] 2019-02-04 12:35
Just tested this on my dev system. pasted the user reported string into a text field and it stored it just fine:

![image](https://user-images.githubusercontent.com/8593673/52208600-71922f80-283e-11e9-9d3b-cb123980dd67.png)

@r007 you will need to set the proper utf8 properties on your database yourself, strapi doesn't control that:
![image](https://user-images.githubusercontent.com/8593673/52208651-971f3900-283e-11e9-90de-464d29688b90.png)

Marking as closed as this is not a strapi related issue

**Closed by derrickmehaffy** 2019-02-04 12:35 UTC
Labels: type: help wanted 🤷‍♂️

**Comment by jaime8111** [comment] 2019-07-03 06:31
In my case it was not enough to set database charset and collation. I also have to **set charset on strapi database configuration to set charset on MySQL connection driver**.

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mysql",
        "host": "127.0.0.1",
        "port": 3306,
        "database": "name",
        "username": "user",
        "password": "password",
        "charset": "utf8mb4_unicode_ci"
      },
      "options": {
        "charset": "utf8mb4_unicode_ci"
      }
    }
  }
}
```

**Comment by LaughingApe** [comment] 2020-01-24 12:27
> In my case it was not enough to set database charset and collation. I also have to **set charset on strapi database configuration to set charset on MySQL connection driver**.
> 
> ```
> {
>   "defaultConnection": "default",
>   "connections": {
>     "default": {
>       "connector": "strapi-hook-bookshelf",
>       "settings": {
>         "client": "mysql",
>         "host": "127.0.0.1",
>         "port": 3306,
>         "database": "name",
>         "username": "user",
>         "password": "password",
>         "charset": "utf8mb4_unicode_ci"
>       },
>       "options": {
>         "charset": "utf8mb4_unicode_ci"
>       }
>     }
>   }
> }
> ```

Yes, this worked, except that I also had to change collation for the specific table (not just the databasea) in MySQL, because it was already created with the previous (wrong) collation before.

**Comment by maxoyed** [comment] 2020-07-22 18:25
> In my case it was not enough to set database charset and collation. I also have to **set charset on strapi database configuration to set charset on MySQL connection driver**.
> 
> ```
> {
>   "defaultConnection": "default",
>   "connections": {
>     "default": {
>       "connector": "strapi-hook-bookshelf",
>       "settings": {
>         "client": "mysql",
>         "host": "127.0.0.1",
>         "port": 3306,
>         "database": "name",
>         "username": "user",
>         "password": "password",
>         "charset": "utf8mb4_unicode_ci"
>       },
>       "options": {
>         "charset": "utf8mb4_unicode_ci"
>       }
>     }
>   }
> }
> ```

Thx, that works for me !
![image](https://user-images.githubusercontent.com/25519245/88213747-b9ec1a00-cc8b-11ea-894f-f6ece37c092b.png)

**Comment by dneckel** [comment] 2020-08-13 16:58
I tried the solution provided by **jaime8111** and **maxoyed**. It pointed me in the right direction however I ran into a Knex error:
`Error: ER_UNKNOWN_CHARACTER_SET: Unknown character set: 'utf8mb4_unicode_ci'`

I had a table creation pending and the server was not able to start back up.

In order to get it back to work i had to set the charset to:
`"charset": "utf8mb4"`

After I manually changed all existing column, tables and fields to charset `utf8mb4` and collation `utf8mb4_unicode_ci` I noticed that I did not need the configuration after all. Knex picks up the database and table config automatically and creates new tables and fields in existing tables with the correct charset and collation.

Hope this helps in case somebody else runs into the same problem and finds this issue.

**Comment by jaladh-singhal** [comment] 2021-07-28 11:33
> I tried the solution provided by **jaime8111** and **maxoyed**. It pointed me in the right direction however I ran into a Knex error:
> `Error: ER_UNKNOWN_CHARACTER_SET: Unknown character set: 'utf8mb4_unicode_ci'`
> 
> I had a table creation pending and the server was not able to start back up.
> 
> In order to get it back to work i had to set the charset to:
> `"charset": "utf8mb4"`
> 
> After I manually changed all existing column, tables and fields to charset `utf8mb4` and collation `utf8mb4_unicode_ci` I noticed that I did not need the configuration after all. Knex picks up the database and table config automatically and creates new tables and fields in existing tables with the correct charset and collation.

I was recieving same error @dneckel and removing the configuration options mentioned by @jaime8111 made it work (ofc after manually changing databse & its all tables to charset `utf8mb4` and collation `utf8mb4_unicode_ci`). Now when I try saving a characters like `новая` everything works fine but when I try saving an emoji `😃` I receive the issue author's error: `ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value` 

I checked charset and collation of table & its columns, they are `utf8mb4` and `utf8mb4_unicode_ci` respectively as expected. Any ideas what is the cause?

**Comment by crushy26** [comment] 2021-09-17 08:09
@jaladh-singhal were you able to solve it? I still couldn't save emoji even after saving characters, rest works propely.

**Comment by jaladh-singhal** [comment] 2021-09-17 13:15
> @jaladh-singhal were you able to solve it? I still couldn't save emoji even after changing charset, the rest works properly.

@crushy26 Unfortunately, no (I just gave up on this atm). Please let me know if/when you find a solution.

**Comment by crushy26** [comment] 2021-09-17 14:13
Yes, I found the issue, you need to add the charset at both places in the
database config file.

In the options key and also in the settings key

**Comment by jaladh-singhal** [comment] 2021-10-20 18:42
> Yes, I found the issue, you need to add the charset at both places in the database config file. In the options key and also in the settings key

I tried that, it still didn't work for me. I don't know if it's related to MySQL version - I'm using v5.7 what version you tried it with @crushy26 ?
