### ISSUE TITLE
Admin doesn't work after rebuild

### ISSUE THREAD

**Issue by kuzn-ilya** [strapi/strapi#2989] opened 2019-03-17 10:36 UTC
**Informations**
- **Node.js version**: v10.15.3
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: psql (PostgreSQL) 10.7
- **Operating system**: Windows 10
- **(Optional) Link to your Project**: 

**What is the current behavior?**

strapi admin doesn't start

**Steps to reproduce the problem**
```
strapi new project
rem ...walk through new project's setup process...
cd project
npm run start
```
At this point always is working fine, login screen turns up.
But I want not to store **/build folders in my git repo, so I executed the following cmds to emulate a fresh start:
```
rimraf **/node_modules/
rimraf **/build/
```
After that the following commands was executed:
```
npm install
npm run setup --plugins
npm run start
```
When I try to open admin panel on http://localhost:1337/admin it reditect me into http://localhost:1337/admin/plugins/users-permissions/auth/register, but I see a blank screen.

In the browser console I see the following:
![image](https://user-images.githubusercontent.com/7905573/54489041-424cf480-48b9-11e9-8ea3-55913760877a.png)

**What is the expected behavior?**
The register screen appears

**Suggested solutions**
It seems like a user-permissions plugin is broken.

**Comment by pnl107** [comment] 2019-03-18 07:40
I think it can help you
https://strapi.io/documentation/3.x.x/migration-guide/migration-guide-alpha.24-to-alpha.25.html

**Comment by kuzn-ilya** [comment] 2019-03-18 08:06
> I think it can help you
> https://strapi.io/documentation/3.x.x/migration-guide/migration-guide-alpha.24-to-alpha.25.html

@pnl107 , thank you for suggestion, but I bootstrapped a strapi from scratch, so I cannot apply migration steps described by a link you provided. Could you please drop me a hint, if you meant something different from migration 24->25.

**Comment by kuzn-ilya** [comment] 2019-03-19 11:45
@lauriejim , @soupette , Let me know if you need help to reproduce this bug or any additional info from my side

**Comment by abdonrd** [comment] 2019-03-19 23:26
I can not do the build process either:

```
➜  my-secret-project git:(strapi) ✗ npm run setup --plugins

> my-secret-project@0.1.0 setup /Users/abdonrd/my-secret-project
> cd admin && npm run setup


> strapi-admin@3.0.0-alpha.25.2 presetup /Users/abdonrd/my-secret-project/admin
> node ./scripts/preSetup.js


🕓  The setup process can take few minutes.

🔸  Administration Panel
📦  Installing packages...

Packages installed successfully

> strapi-admin@3.0.0-alpha.25.2 setup /Users/abdonrd/my-secret-project/admin
> node ./scripts/setup.js

🏗  Building the admin...
✅  Success

ls: no such file or directory: * -d
🔸  Plugin - Content-manager
📦  Installing packages...
🏗  Building...
✅  Success

🔸  Plugin - Content-type-builder
📦  Installing packages...
🏗  Building...
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module './'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/abdonrd/my-secret-project/node_modules/.bin/rimraf:3:14)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-plugin-content-type-builder@3.0.0-alpha.25.2 build:clean: `cross-env rimraf admin/build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-plugin-content-type-builder@3.0.0-alpha.25.2 build:clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abdonrd/.npm/_logs/2019-03-19T23_23_06_218Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-plugin-content-type-builder@3.0.0-alpha.25.2 prebuild: `npm run build:clean`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-plugin-content-type-builder@3.0.0-alpha.25.2 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abdonrd/.npm/_logs/2019-03-19T23_23_06_250Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.25.2 setup: `node ./scripts/setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-admin@3.0.0-alpha.25.2 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abdonrd/.npm/_logs/2019-03-19T23_23_06_291Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-secret-project@0.1.0 setup: `cd admin && npm run setup`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-secret-project@0.1.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abdonrd/.npm/_logs/2019-03-19T23_23_06_366Z-debug.log
```

**Comment by kuzn-ilya** [comment] 2019-03-20 07:57
@abdonrd , do you use a proper version of nodejs? I got a similar error on I used node 8 which is currently not supported by strapi

**Comment by abdonrd** [comment] 2019-03-20 07:59
@kuzn-ilya I use Node v11.6.0.

**Comment by kuzn-ilya** [comment] 2019-03-22 08:25
@abdonrd , I tried to perform the same steps as described by me using node v11.6.0 but it got stuck two times on installing admin packages.

**Comment by abdonrd** [comment] 2019-03-22 08:31
It does not work for me either... 😞

**Comment by abdonrd** [comment] 2019-03-25 17:02
@soupette I'm on macOS.

**Comment by kuzn-ilya** [comment] 2019-03-25 17:03
I am on Windows 10

**Comment by soupette** [comment] 2019-03-27 20:16
Well I have just tried using the master branch and it's working.

**Comment by friendofdog** [comment] 2019-03-27 23:43
I'm experiencing the exact same problem as originally posted, except I got there by upgrading from alpha.24.1. After opening the Strapi admin, navigating to _anywhere_ from the home page – except Marketplace – results a blank page with the exact same `invariant failed` console error.

Even after rolling back to alpha.24.1, the issue persists.

There are no issues with the build process, which is working just fine.

**Comment by doublesharp** [comment] 2019-03-30 18:40
@abdonrd @friendofdog I had this same issue and was able to resolve it by fixing a bug in `admin/scripts/setup.js`. The error `ls: no such file or directory: * -d` is being triggered by [this line](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/scripts/setup.js#L29) in the admin setup script. The call to `ls * -d PLUGINS_DIR` is not valid, so I changed it to the following to get a listing of just the plugins directories and was able to run `npm run setup --plugins`.

_Original_
```
  const plugins = path.resolve(appPath, 'plugins');

  // TODO: build plugins in async
  shell.ls('* -d', plugins)
    .filter(x => {
          // the filter code
    })
```

_Fixed_
```
  const plugins = path.resolve(appPath, 'plugins');

  shell.cd(path.resolve(plugins));
  const pluginsDirs = shell.ls('-d', '*')
  // now filter and forEach on pluginDirs
  pluginsDirs
    .filter(x => {
          // the filter code
    })
```

The above will fix it, but I actually went ahead and made it async as well...

_Updated_
```
  const plugins = path.resolve(appPath, 'plugins');

  (async function() {
    // change to the plugins directory
    shell.cd(path.resolve(plugins));
    // run `ls -d *` to get plugins
    const pluginsDirs = shell.ls('-d', '*')
    await Promise.all(
      pluginsDirs
        .filter(x => {
          // the filter code
        })
        .map(async function (plugin) {
          shell.echo(`🔸  Plugin - ${_.upperFirst(plugin)}`);
          // rest of the install code
        })
    );
  })();

**Comment by friendofdog** [comment] 2019-04-02 04:27
@doublesharp Great idea building plugins asynchronously, especially since there's a note in the code to do so. But this did not resolve the issue when I ran setup with your code.

It was pointed out to me that the error pertains to React. If you look in the many package.json files involved in the build process, some dependency versions use carets. So my guess is that one or some of the packages got updated and are now causing the error.

**Comment by doublesharp** [comment] 2019-04-02 04:32
The script actually deletes the package-lock.json files too so it's definitely going to pull the latest :(

FWIW I was just able to regenerate all the `build` folders using this Dockerfile and the change I posted above to `setup.js`.

```
FROM node:11.13.0-stretch-slim

WORKDIR /app

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y libgl1-mesa-glx
RUN echo "unsafe-perm = true" >> ~/.npmrc

COPY package*.json /app/
COPY admin/package*.json /app/admin/
COPY plugins/content-manager/package*.json /app/plugins/content-manager/
COPY plugins/content-type-builder/package*.json /app/plugins/content-type-builder/
COPY plugins/email/package*.json /app/plugins/email/
COPY plugins/settings-manager/package*.json /app/plugins/settings-manager/
COPY plugins/upload/package*.json /app/plugins/upload/
COPY plugins/users-permissions/package*.json /app/plugins/users-permissions/

RUN npm install

COPY plugins/ /app/plugins/
COPY admin/ /app/admin/
COPY config/environments/ /app/config/environments/

RUN npm run setup --plugins

COPY . /app

CMD ["node", "server.js"]

```

**Comment by SMR39** [comment] 2019-04-02 07:19
@doublesharp can you paste the whole file here please. `setup.js`

**Comment by johnnyshields** [comment] 2019-04-02 08:43
If the `package-lock.json` files are deleted, how are we supposed to ensure reliable/stable builds in productions? This is madness...

**Comment by derrickmehaffy** [comment] 2019-04-02 08:44
@johnnyshields the lock files create problems during the build process, it's been a known issue for over a year hence why they are removed or not generated at all.

**Comment by johnnyshields** [comment] 2019-04-02 08:47
Is someone fixing the build process to properly work with lock files?

**Comment by derrickmehaffy** [comment] 2019-04-02 09:08
@johnnyshields not yet, at least not that I am aware of. You are more than welcome to work on it and submit a PR

**Comment by johnnyshields** [comment] 2019-04-02 14:08
Is there an issue raised? I will post a $1000 bounty for it.

**Comment by doublesharp** [comment] 2019-04-02 15:22
@derrickmehaffy Can you let me know what the problem is with the package-lock.json files? I can't think of a reason that they would cause a problem since they just lock the version of the dependencies from the package.json.

@johnnyshields I'm testing my setup again to make sure it works without deleting the package-lock.json files, if it does I'll let you know where to send the money :P

@SMR39 I had to modify `preSetup.js` (uncomment deleting of package-lock.json) and `setup.js` (path fixes, async, etc). Will post here if it works.

**Comment by derrickmehaffy** [comment] 2019-04-02 15:30
@doublesharp I can't remember the exact issue off the top of my head but I think it had something to do with how the helper plugin works. It would fail to grab some dependents if you pulled a project from a repo and ran `npm i`. (I'm well aware of what it does, and understand why some believe it to be important)

Honestly not sure if any major debugging went into it, magically if you delete the lock file it works :man_shrugging:

**Comment by doublesharp** [comment] 2019-04-02 15:51
I just rebuilt the admin twice, once with the package-lock.json being imported in the Dockerfile and the other omitting it, then checked the CRC32. When I imported the lock the CRC32 matched, when I did not and regenerated it did not, but it was successful both times so it seems to be working for me to regenerate the build files. The only place I saw them being deleted was `preSetup.js` so if I've missed somewhere let me know (I also updated my .gitignore).

Below are the files I'm using, there are a few other fixes too like using `sh.test()` to check for a directory instead of a try/catch block.

**admin/scripts/preSetup.js**
```
const shell = require('shelljs');
const path = require('path');

shell.echo(`
🕓  The setup process can take few minutes.

🔸  Administration Panel
📦  Installing packages...
`);

const pwd = shell.pwd();

const silent = process.env.npm_config_debug !== 'true';
const isDevelopmentMode = path.resolve(pwd.stdout).indexOf('strapi-admin') !== -1;
const appPath = isDevelopmentMode ? path.resolve(process.env.PWD, '..') : path.resolve(pwd.stdout, '..');

// We just install the admin's dependencies here

// Install the project dependencies.
shell.cd(appPath);
shell.exec('npm install --ignore-scripts', {silent});

// Install the administration dependencies.
shell.cd(path.resolve(appPath, 'admin'));
shell.exec('npm install', {silent});

if (isDevelopmentMode) {
  shell.cd(path.resolve(appPath, 'admin'));
  shell.exec('npm link strapi-helper-plugin && npm link strapi-utils', {silent});
} else {
  shell.cd(path.resolve(appPath, 'admin', 'node_modules', 'strapi-helper-plugin'));
  shell.exec('npm install', {silent});
}

shell.echo('Packages installed successfully');
```

**admin/scripts/setup.js**
```
const fs = require('fs');
const shell = require('shelljs');
const path = require('path');
const _ = require('lodash');

const pwd = shell.pwd();

const silent = process.env.npm_config_debug !== 'true';
const isDevelopmentMode = path.resolve(pwd.stdout).indexOf('strapi-admin') !== -1;
const appPath = isDevelopmentMode ? path.resolve(process.env.PWD, '..') : path.resolve(pwd.stdout, '..');

shell.echo('🏗  Building the admin...');

shell.cd(path.resolve(appPath, 'admin'));
const build = shell.exec(`cross-env APP_PATH="${appPath}" npm run build`, {silent});

if (build.stderr && build.code !== 0) {
  console.error(build.stderr);
  process.exit(1);
}

shell.echo('✅  Success');
shell.echo('');

if (process.env.npm_config_plugins === 'true') {
  const plugins = path.resolve(appPath, 'plugins');

  (async function() {
    // change to plugins path
    shell.cd(path.resolve(plugins));
    // list all directories in plugins
    const pluginsDirs = shell.ls('-d', '*');
    await Promise.all(
      pluginsDirs
        // filter for plugins with admin path
        .filter(x =>
          sh.test('-d', path.resolve(appPath, 'plugins', x, 'admin', 'src', 'containers', 'App'))
        )
        .map(async function (plugin) {
          shell.echo(`🔸  Plugin - ${_.upperFirst(plugin)}`);
          shell.echo('📦  Installing packages...');
          shell.cd(path.resolve(plugins, plugin));
          shell.exec('npm install', {silent});
    
          if (isDevelopmentMode) {
            shell.cd(path.resolve(plugins, plugin));
            shell.exec('npm link strapi-helper-plugin', {silent});
          } else {
            shell.cd(path.resolve(plugins, plugin, 'node_modules', 'strapi-helper-plugin'));
            shell.exec('npm install', {silent});
          }
    
          shell.echo('🏗  Building...');
          shell.cd(path.resolve(plugins, plugin));
          const build = shell.exec(`cross-env APP_PATH="${appPath}" npm run build`, {silent});
    
          if (build.stderr && build.code !== 0) {
            console.error(build.stderr);
            process.exit(1);
          }
    
          shell.echo('✅  Success');
          shell.echo('');
        })
    );
  })();
}
```

**Dockerfile**
```
FROM node:11.13.0-stretch-slim

WORKDIR /app

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y libgl1-mesa-glx
RUN echo "unsafe-perm = true" >> ~/.npmrc

COPY package*.json /app/
COPY admin/package*.json /app/admin/
COPY plugins/content-manager/package*.json /app/plugins/content-manager/
COPY plugins/content-type-builder/package*.json /app/plugins/content-type-builder/
COPY plugins/email/package*.json /app/plugins/email/
COPY plugins/settings-manager/package*.json /app/plugins/settings-manager/
COPY plugins/upload/package*.json /app/plugins/upload/
COPY plugins/users-permissions/package*.json /app/plugins/users-permissions/

RUN npm install

COPY plugins/ /app/plugins/
COPY admin/ /app/admin/
COPY config/environments/ /app/config/environments/

RUN npm run setup --plugins

# Check CRC32 of the package-lock.json
#RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libarchive-zip-perl
#RUN crc32 /app/package-lock.json

COPY . /app

CMD ["node", "server.js"]
```
**.dockerignore**
```
**/node_modules
**/npm-debug.log
**/Dockerfile
**/docker-compose.yml
**/build
**/docker
**/test
**/tmp
docker
.dockerignore
.git
.gitignore
.vscode
.env
*.log
README.md
LICENSE
```

**Comment by johnnyshields** [comment] 2019-04-02 17:53
@doublesharp if you get the fix merged to master--and presumably fix whatever issue was causing the project authors to delete the lock files in the first place--the bounty is yours.

**Comment by doublesharp** [comment] 2019-04-02 19:19
I've gone a bit deeper and might have bastardized it for my own purposes, so I'm not sure if it's something mergeable or not.

I realized that making the plugin install async didn't make it faster since it `shelljs` blocked so instead I converted it to using a `Worker` and can see it using 6 cores to install, but I also have to start with `--experimental-worker`. I also modified a lot of the install script to use `npm ci` which is much faster than `npm install` but requires a `package-lock.json`. 

It gets a little bit more hack-y because I wanted to be able to use `npm ci` on `strapi-helper-plugin` but it doesn't have a package-lock.json either - so in the `Worker` for each plugin installer I just copy the one that was generated for the one in `./admin/node_modules` like this:

```
  build = shell.exec(`\
cd "${path.resolve(plugins, plugin)}" && \
npm ci && \
cd "${path.resolve(plugins, plugin, 'node_modules', 'strapi-helper-plugin')}" && \
cp "${path.resolve(appPath, 'admin', 'node_modules', 'strapi-helper-plugin', 'package-lock.json')}" . && \
npm ci && \
cd "${path.resolve(plugins, plugin)}" && \
cross-env APP_PATH="${appPath}" npm run build`, {silent});
```

Not sure if this works with "dev mode" as I have never started that way.

**Comment by doublesharp** [comment] 2019-04-02 20:50
I can reliably rebuilding the admin and plugins (*mostly because `strapi-helper-plugin` does get installed without  a package lock) using the `package-lock.json` and multithreaded the install with `Workers`. Installing with `npm ci` where available helps a lot as well. It takes about 8 mins to get to "Plugin workers finished!" then Docker does some things for a while caching the image before it continues, about 10.5 mins total, which is faster than it was originally for me. I have a 2013 Macbook Pro.

```
> date && docker-compose -f docker/environments/development/docker-compose.yml build && date
Tue Apr  2 13:27:27 PDT 2019

strapi_db uses an image, skipping
Building strapi
Step 1/20 : FROM node:11.13.0-stretch-slim
 ---> e52c23bbdd87
Step 2/20 : WORKDIR /app
 ---> Using cache
 ---> 800d123849b4
Step 3/20 : RUN DEBIAN_FRONTEND=noninteractive apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install -y libgl1-mesa-glx libxi6
 ---> Using cache
 ---> 2ff8beb55419
Step 4/20 : RUN echo "unsafe-perm = true" >> ~/.npmrc
 ---> Using cache
 ---> 5abb2a1349de
Step 5/20 : COPY package*.json /app/
 ---> Using cache
 ---> 41367c7c32f5
Step 6/20 : COPY admin/package*.json /app/admin/
 ---> Using cache
 ---> 903e52a6556b
Step 7/20 : COPY plugins/content-manager/package*.json /app/plugins/content-manager/
 ---> Using cache
 ---> f7f0c82b43f7
Step 8/20 : COPY plugins/content-type-builder/package*.json /app/plugins/content-type-builder/
 ---> Using cache
 ---> 05b811925b28
Step 9/20 : COPY plugins/email/package*.json /app/plugins/email/
 ---> Using cache
 ---> 03ca54c02c1b
Step 10/20 : COPY plugins/settings-manager/package*.json /app/plugins/settings-manager/
 ---> Using cache
 ---> a3ee482838e2
Step 11/20 : COPY plugins/upload/package*.json /app/plugins/upload/
 ---> Using cache
 ---> 02b5c92308a5
Step 12/20 : COPY plugins/users-permissions/package*.json /app/plugins/users-permissions/
 ---> Using cache
 ---> fcfe82cb02b0
Step 13/20 : RUN npm ci
 ---> Using cache
 ---> 9c6e6e4f0752
Step 14/20 : COPY admin/ /app/admin/
 ---> Using cache
 ---> 3e14b2e8ec40
Step 15/20 : COPY plugins/ /app/plugins/
 ---> Using cache
 ---> fb53ce402657
Step 16/20 : COPY config/environments/ /app/config/environments/
 ---> Using cache
 ---> 93ce438d65e9
Step 17/20 : COPY custom/ /app/admin/scripts
 ---> 3ca2d7c5b708
Step 18/20 : RUN npm run setup --plugins
 ---> Running in 320b8a87da7a

> cms@0.1.0 setup /app
> cd admin && npm run setup


> strapi-admin@3.0.0-alpha.25.2 presetup /app/admin
> node ./scripts/preSetup.js


🕓  The setup process can take few minutes.

🔸  Administration Panel
📦  Installing packages via 'npm ci'...
🔨  Installing strapi-helper-plugin packages via 'npm install'...
✅  Packages installed successfully!


> strapi-admin@3.0.0-alpha.25.2 setup /app/admin
> node --experimental-worker ./scripts/setup.js

🏗  Building the admin...
✅  Success

🐇  Starting Plugin Workers
📦  Email - Installing packages via 'npm ci'...
📦  Content-type-builder - Installing packages via 'npm ci'...
📦  Settings-manager - Installing packages via 'npm ci'...
📦  Users-permissions - Installing packages via 'npm ci'...
📦  Upload - Installing packages via 'npm ci'...
📦  Content-manager - Installing packages via 'npm ci'...
🔨  Upload - Installing strapi-helper-plugin packages via 'npm ci'...
🔨  Email - Installing strapi-helper-plugin packages via 'npm ci'...
🔨  Settings-manager - Installing strapi-helper-plugin packages via 'npm ci'...
🔨  Content-manager - Installing strapi-helper-plugin packages via 'npm ci'...
🔨  Content-type-builder - Installing strapi-helper-plugin packages via 'npm ci'...
🔨  Users-permissions - Installing strapi-helper-plugin packages via 'npm ci'...
🏗  Content-type-builder - Building...
🏗  Settings-manager - Building...
🏗  Upload - Building...
🏗  Content-manager - Building...
🏗  Users-permissions - Building...
🏗  Email - Building...
✅  Email - Success!
✅  Settings-manager - Success!
✅  Upload - Success!
✅  Users-permissions - Success!
✅  Content-type-builder - Success!
✅  Content-manager - Success!
💥  Plugin workers finished!

Removing intermediate container 320b8a87da7a
 ---> 1a749099d77d
Step 19/20 : COPY . /app
 ---> 6ff3c5940dea
Step 20/20 : CMD ["node", "server.js"]
 ---> Running in 8102865b4ce2
Removing intermediate container 8102865b4ce2
 ---> a4dbb612e9a1

Successfully built a4dbb612e9a1
Successfully tagged development_strapi:latest

Tue Apr  2 13:38:07 PDT 2019
```

**preSetup.js**
```javascript
const shell = require('shelljs');
const path = require('path');

shell.echo(`
🕓  The setup process can take few minutes.

🔸  Administration Panel`);

const pwd = shell.pwd();

const silent = process.env.npm_config_debug !== 'true';
const isDevelopmentMode = path.resolve(pwd.stdout).indexOf('strapi-admin') !== -1;
const appPath = isDevelopmentMode ? path.resolve(process.env.PWD, '..') : path.resolve(pwd.stdout, '..');

// Install the administration dependencies.
shell.cd(path.resolve(appPath, 'admin'));

const adminCmd = shell.test('-f', './package-lock.json') ? 'ci' : 'install';
shell.echo(`📦  Installing packages via 'npm ${adminCmd}'...`);
shell.exec(`npm ${adminCmd}`, {silent});

if (isDevelopmentMode) {
  shell.echo('🔨  Linking strapi-helper-plugin and strapi-utils packages...');
  shell.cd(path.resolve(appPath, 'admin'));
  shell.exec('npm link strapi-helper-plugin && npm link strapi-utils', {silent});
} else {
  shell.cd(path.resolve(appPath, 'admin', 'node_modules', 'strapi-helper-plugin'));
  const helperCmd = shell.test('-f', './package-lock.json') ? 'ci' : 'install';
  shell.echo(`🔨  Installing strapi-helper-plugin packages via 'npm ${helperCmd}'...`);
  shell.exec(`npm ${helperCmd}`, {silent});
}

shell.echo('✅  Packages installed successfully!');
shell.echo('');
```

**setup.js**
```javascript
const shell = require('shelljs');
const path = require('path');
const {
  Worker
} = require('worker_threads');

const pwd = shell.pwd();

const silent = process.env.npm_config_debug !== 'true';
const isDevelopmentMode = path.resolve(pwd.stdout).indexOf('strapi-admin') !== -1;
const appPath = isDevelopmentMode ? path.resolve(process.env.PWD, '..') : path.resolve(pwd.stdout, '..');

shell.echo('🏗  Building the admin...');

shell.cd(path.resolve(appPath, 'admin'));
const build = shell.exec(`cross-env APP_PATH="${appPath}" npm run build`, {silent});

if (build.stderr && build.code !== 0) {
  console.error(build.stderr);
  process.exit(1);
}

shell.echo('✅  Success');
shell.echo('');

if (process.env.npm_config_plugins === 'true') {
  process.setMaxListeners(0);
  const plugins = path.resolve(appPath, 'plugins');

  shell.echo('🐇  Starting Plugin Workers');
  (async function() {
    // change to plugins path
    shell.cd(path.resolve(plugins));
    // list all directories in plugins
    const pluginsDirs = shell.ls('-d', '*');
    await Promise.all(
      pluginsDirs
        // filter for plugins with admin path
        .filter(x =>
          shell.test('-d', path.resolve(appPath, 'plugins', x, 'admin', 'src', 'containers', 'App'))
        )
        .map(function (plugin) {
          return new Promise((resolve, reject) => {
            const workerPath = path.resolve(appPath, 'admin', 'scripts', 'lib', 'pluginInstaller.js');
            const worker = new Worker(workerPath, {
              workerData: {
                appPath, plugin, plugins, isDevelopmentMode, silent,
              },
            });
            worker.on('error', (err) => reject(err));
            worker.on('message', (message) => resolve(message));
          });
        })
    );
    shell.echo('💥  Plugin workers finished!');
    shell.echo('');

    // exit success
    process.exit(0);
  })();
}
```

**lib/pluginInstaller**
```javascript
const shell = require('shelljs');
const path = require('path');
const _ = require('lodash');
const {
  workerData, parentPort
} = require('worker_threads');

const { appPath, plugin, plugins, isDevelopmentMode, silent } = workerData;

let build;

const hasPluginPackageLock = shell.test('-f', path.resolve(plugins, plugin, 'package-lock.json'));
const pluginInstallCmd = hasPluginPackageLock ? 'ci' : 'install';

if (isDevelopmentMode) {
  // this is untested and probably doesn't work
  build = shell.exec(`\
cd "${path.resolve(plugins, plugin)}" && \
npm ci && \
cross-env APP_PATH="${appPath}" npm run build`, {silent});
  /* 
  shell.cd(path.resolve(plugins, plugin));
  shell.exec('npm link strapi-helper-plugin', {silent});
   
  end isDevelopmentMode */
} else {
  const quiet = silent ? ' >/dev/null 2>&1' : '';
  build = shell.exec(`\
cd "${path.resolve(plugins, plugin)}" ${quiet} && \
echo "📦  ${_.upperFirst(plugin)} - Installing packages via 'npm ${pluginInstallCmd}'..." && \
npm ${pluginInstallCmd} ${quiet} && \
cd "${path.resolve(plugins, plugin, 'node_modules', 'strapi-helper-plugin')}" ${quiet} && \
cp "${path.resolve(appPath, 'admin', 'node_modules', 'strapi-helper-plugin', 'package-lock.json')}" . ${quiet} && \
echo "🔨  ${_.upperFirst(plugin)} - Installing strapi-helper-plugin packages via 'npm ci'..." && \
npm ci ${quiet} && \
cd "${path.resolve(plugins, plugin)}" ${quiet} && \
echo "🏗  ${_.upperFirst(plugin)} - Building..." && \
cross-env APP_PATH="${appPath}" npm run build ${quiet}`);
  /* end !isDevelopmentMode */
}

if (build.stderr && build.code !== 0) {
  console.error(build.stderr);
  process.exit(1);
}

shell.echo(`✅  ${_.upperFirst(plugin)} - Success!`);

// tell the parent thread that we are done
parentPort.postMessage(`installed ${plugin}`);

```

**Comment by doublesharp** [comment] 2019-04-02 20:53
You also need to update the `setup` script in `admin/package.json` to be `node --experimental-worker ./scripts/setup.js`.

**Comment by johnnyshields** [comment] 2019-04-03 05:56
May I kindly suggest we stop pasting code into this Github issue and do the following:
1. Open a new issue which concisely describes the problem. I will post a $1000 bounty for that issue.
2. Open PR(s) to address the issue, with a goal of making a permanent fix on Strapi.

**Comment by derrickmehaffy** [comment] 2019-04-03 06:02
@johnnyshields PR acceptation is frozen until after the framework rewrite is merged

![image](https://user-images.githubusercontent.com/8593673/55456214-5a03c880-559b-11e9-8e82-3ac978be8f95.png)

https://github.com/strapi/strapi/pull/3079

**Comment by doublesharp** [comment] 2019-04-03 17:33
@johnnyshields it looks like PRs are closed (and maybe this will be improved in the new release anyway) but I'm also too busy right now to get the above code into proper shape to be merged into the project though it works for my purposes. I was mostly posting it in case it was helpful to anyone else as I am able to regenerate the build files for my project inside a Docker container using it, which is what I need for my project. Hopefully it can help you too, but if not good luck on yours as well!

**Comment by johnnyshields** [comment] 2019-04-04 06:58
@doublesharp understood. Well let's see if this "new architecture" rationalizes the build process.

**Comment by derrickmehaffy** [comment] 2019-04-04 07:00
@johnnyshields I wouldn't bet on that short term. It's possible but highly unlikely.

**Comment by johnnyshields** [comment] 2019-04-04 08:19
Confucius say: application built without locked dependencies like house built on quicksand. ☯️

**Comment by lauriejim** [comment] 2019-05-09 15:26
Close this issue, the process will be easier in next version (beta) - information will come in next weeks about this version.

**Closed by lauriejim** 2019-05-09 15:26 UTC
Labels: type: help wanted 🤷‍♂️
