### ISSUE TITLE
Invite link not working

### ISSUE THREAD

**Issue by zainullinramil** [strapi/strapi#13300] opened 2022-05-12 12:36 UTC
### Required System information

- Node.js version: v16.15.0
- Yarn version: v1.22.18
- Strapi version: v4.1.10
- Database: PostgreSQL
- Operating system: aws t3a.medium

### Describe the bug

When adding a new user, the registrationToken is not substituted into the registration link

### Steps to reproduce the behavior

1. Go to '/admin/settings/users'
2. Click on 'Invite new user'
3. Enter new user details
4. Click on 'Invite user'
5. Copy invite link
6.Invitation link does not contain registrationToken value 'https://yourdomain.com/admin/auth/register?registrationToken='

### Expected behavior

Invitation link does contain registrationToken

**Comment by derrickmehaffy** [comment] 2022-05-12 17:04
can't reproduce on v4.1.10, need more information. Will mark as closed until additional information can be provided.

**Comment by derrickmehaffy** [comment] 2022-05-12 19:43
Ah I see it now, reopening

**Comment by Convly** [comment] 2022-05-13 10:19
Hey, thanks a lot for reporting this issue. I've submitted a fix and it should be reviewed, merged & released in the next version (4.1.11).

**Comment by zainullinramil** [comment] 2022-05-13 10:21
thank! this is great news!

> Hey, thanks a lot for reporting this issue. I've submitted a fix and it should be reviewed, merged & released in the next version (4.1.11).

**Comment by MatthiasDunker** [comment] 2022-08-26 06:25
Hey @Convly ,
Has this also been fixed for version 3?
It is a bug there, too.
Thanks in advance.

**Comment by derrickmehaffy** [comment] 2022-08-29 18:43
> Hey @Convly , Has this also been fixed for version 3? It is a bug there, too. Thanks in advance.

We are not currently patching bugs in v3, see: https://github.com/strapi/strapi/security/policy

**Comment by MatthiasDunker** [comment] 2022-08-30 12:47
I see, thanks.

For those who need an updated version 3, here is what I did:

1. Add the following to `/packages/strapi-admin/controllers/user.js` into the `create` controller before the line `// Send 201 created` (around row 40).

```js

    // Note: We need to assign manually the registrationToken to the
    // final user payload so that it's not removed in the sanitation process.
    Object.assign(userInfo, { registrationToken: createdUser.registrationToken });

```

2. Run patch-package. The description is in the Readme: https://github.com/ds300/patch-package

That’s it. From now on, invite links will have a token

**Comment by GregorSondermeier** [comment] 2022-09-07 09:48
Before blindly using patch-package, be aware that this is a quite hacky workaround that I would not say is a sustainable, scalable solution. Use at own risk.

**Closed** 2023-04-07 18:00 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:admin
