### ISSUE TITLE
Cannot move cursor in input fields of repeatable components

### ISSUE THREAD

**Issue by kjoscha** [strapi/strapi#13342] opened 2022-05-17 12:03 UTC
### Required System information

- Node.js version: v16
- NPM version: 8.5.5
- Strapi version: 4.1.7
- Database: sqlite
- Operating system: Ubuntu

### Describe the bug

If I use a repeatable component in a collection or a singular type, inside all inputs the arrow keys do not move the cursor. Nevrtheless, with the mouse the cursor can be moved to all positions.

### Steps to reproduce the behavior

1. Content-Type builder: Create a singular type and add a repeatable component with a text input 
2. Content Manager: Add a component, type anything in the input field and try to move the cursor with the arrow keys.

### Screenshots

![Bildschirmfoto von 2022-05-17 13-59-02](https://user-images.githubusercontent.com/3657707/168806446-9ce92524-9b22-4978-aa8c-77cb29841f17.png)

**Comment by kjoscha** [comment] 2022-05-19 13:11
Thank you for trying!

Meanwhile, I found out that it does only appear if I use any wysiwyg replacement as "tiptap" or "editor.js" from the official market (https://market.strapi.io/plugins/strapi-tiptap-editor).

**Comment by derrickmehaffy** [comment] 2022-05-19 19:34
> Thank you for trying!
> 
> Meanwhile, I found out that it does only appear if I use any wysiwyg replacement as "tiptap" or "editor.js" from the official market (https://market.strapi.io/plugins/strapi-tiptap-editor). 

Ah in that case you'll need to open an issue with those authors

**Comment by jcberquist** [comment] 2022-05-27 21:12
Hi @derrickmehaffy, we are trying out Strapi and are encountering this issue as well. It looked to me in your reproduction video that you used a single component type instead of repeatable. I believe this issue only arises with the repeatable type. Specifically, with a little digging, it looks to me like the [KeyboardNavigable](https://github.com/strapi/design-system/blob/main/packages/strapi-design-system/src/KeyboardNavigable/KeyboardNavigable.js) component (which is used by `RepeatableComponent` via `AccordionGroupCustom`) is listening for arrow key events and always calls `preventDefault()` whether the `isValidFocusedElement()` check passes or not. It doesn't look to me like that is intended behavior, as `preventDefault()` gets called again if that check passes. Perhaps there is something I am missing.

(Interestingly, while the issue does show up in basic text fields, the arrow keys will stick work in the default rich text editor - presumably because CodeMirror doesn't care that `preventDefault` has been set on the key events.)

**Comment by derrickmehaffy** [comment] 2022-05-28 00:19
Sure I'll reopen this and take another look on Tuesday

**Comment by derrickmehaffy** [comment] 2022-05-31 22:05
Good catch :) confirmed reproduction on v4.1.12 using repeat compos

Appears it only happens in the string and longtext fields as Rich Text seems to work fine

https://www.loom.com/share/12bddede77f740a8a0f7cfdaf25b633a

**Comment by derrickmehaffy** [comment] 2022-06-02 04:06
I just realized this is a duplicate of https://github.com/strapi/strapi/issues/12432

Gonna close this one in favor of the older issue. Sorry about that :see_no_evil:

**Closed by derrickmehaffy** 2022-06-02 04:06 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-manager
