### ISSUE TITLE
null value in column violates not-null constraint when saving a content-type

### ISSUE THREAD

**Issue by txbrown** [strapi/strapi#7393] opened 2020-08-09 20:40 UTC
**Describe the bug**
 When saving a content-type an error is shown. A summary of that is - "_null value in column "latitude" violates not-null constraint_".

**Steps to reproduce the behaviour**

1. Create a content-type called venue (or something else)
2. Create a a component called location with fields `latitude` and `longitude` and set them to be of type number (float), with required as true and default value as 0.
3. Set the location component as a field of venue - `venue.location`.
3. Create a new venue and save.
4. Create another venue and save

An error is now showing and not allowing to create a new venue.

**Expected behaviour**
I can create a new content-type item (in this case a venue).

**System**

- Node.js version: 12
- NPM version: >= 6
- Strapi version: 3.1.2
- Database: postgres
- Operating system: linux

**Comment by txbrown** [comment] 2020-08-09 20:44
There is already an issue that was closed a couple days ago #556

**Comment by derrickmehaffy** [comment] 2020-08-13 13:31
hi @txbrown I've tested this on the current latest release (v3.1.3) and could not reproduce it: 
![image](https://user-images.githubusercontent.com/8593673/90140423-98cc9580-dd2e-11ea-99a7-6d6969161ad2.png)

**Comment by lauriejim** [comment] 2020-08-15 09:00
Hello, I also tried on my side and everything is working fine using a fresh new app with 3.1.3 version of Strapi.
Your issue is probably related to this one - https://github.com/strapi/strapi/issues/6292
I'm closing the issue for now.

**Closed by lauriejim** 2020-08-15 09:00 UTC
