### ISSUE TITLE
v4 Public role endpoint 403 - get /api/pages/:id

### ISSUE THREAD

**Issue by MartinN3** [strapi/strapi#11161] opened 2021-09-30 17:35 UTC
## Bug report

error 403 after making GET request to /api/pages/1 after setting public permissions to allow findOne

### Steps to reproduce the behavior

1. Go to USERS & PERMISSIONS PLUGIN -> Roles
2. Select 'Public' roles
3. Click on content type -> Pages
4. check 'findOne'
5. See error 403 after making GET request to /api/pages/1 

### Expected behavior

As in previous version, get data for page with selected ID

### Code snippets

```json
{
  "kind": "collectionType",
  "collectionName": "pages",
  "info": {
    "singularName": "page",
    "pluralName": "pages",
    "displayName": "page",
    "name": "page"
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "test": {
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      },
      "type": "string"
    }
  }
}
````

### System

- Node.js version: v14.17.6
- NPM version: 6.14.15
- Strapi version: 4.0.0-beta.0
- Database: sqLite
- Operating system: WSL - linux on windows

**Comment by MattieBelt** [comment] 2021-09-30 19:16
Duplicate of #11141

**Closed by MattieBelt** 2021-09-30 19:16 UTC
