### ISSUE TITLE
error: create table "strapi_core_store_settings" already exists

### ISSUE THREAD

**Issue by kevinmamaqi** [strapi/strapi#13143] opened 2022-04-17 16:16 UTC
## Bug report
Strapi throws create table error always after updating a content-type or using a database backup that contains data:
```
[2022-04-17 17:51:26.005] http: HEAD /_health (0 ms) 204
[2022-04-17 17:51:26.003] info: The server is restarting

[2022-04-17 17:51:27.681] debug: ⛔️ Server wasn't able to start properly.
[2022-04-17 17:51:27.682] error: create table "strapi_core_store_settings" ("id" serial primary key, "key" varchar(255) null, "value" text null, "type" varchar(255) null, "environment" varchar(255) null, "tag" varchar(255) null) - relation "strapi_core_store_settings" already exists
error: create table "strapi_core_store_settings" ("id" serial primary key, "key" varchar(255) null, "value" text null, "type" varchar(255) null, "environment" varchar(255) null, "tag" varchar(255) null) - relation "strapi_core_store_settings" already exists
```

### Required System information

- Node.js version: 14.17.1
- NPM version: 8.1.4
- Strapi version: 4.1.8
- Database: Postgresql 14.1:alpine
- Operating system: Macos 12.2.1

### Describe the bug

Each time a modify a content type or use a previously saved database dump Strapi throws the error above about not being able to create the table "strapi_core_store_settings". If I delete the table, another table is the problem.

### Expected behavior

Don't run create the table if it is already created.

### Additional context

I updated from 4.1.11 to 4.1.18.

**Comment by derrickmehaffy** [comment] 2022-04-18 20:58
Cannot reproduce on v4.1.8 with information provided, closing until better/more reproduction steps are provided

**Closed by derrickmehaffy** 2022-04-18 20:58 UTC
Labels: status: can not reproduce

**Comment by kevinmamaqi** [comment] 2022-04-19 11:33
@derrickmehaffy I understand it is not easily reproducible, but any idea or guidance of why strapi tries to recreate that specific table?

**Comment by derrickmehaffy** [comment] 2022-04-19 19:48
> @derrickmehaffy I understand it is not easily reproducible, but any idea or guidance of why strapi tries to recreate that specific table?

Generally it means Strapi doesn't see that the table exists. You can try purging the core_store table and rebooting the app but that will flush all plugin configs too, or you can dive into the core_store and delete all the db schema keys

**Comment by gfsd3v** [comment] 2022-07-20 00:14
Was having the same problem, I wasn't using the `schema` key on the DB config for Postgres, I set it to `public` and the tables worked as expected, give it a try @kevinmamaqi .

**Comment by derrickmehaffy** [comment] 2022-09-02 16:17
> I confirm that this happens due to schema mismatch if the schema setting is not configured.
> 
> To reproduce it you can start a containerized PostgreSQL database and add this initialization script to the `/docker-entrypoint-initdb.d` folder:
> 
> ```
> #!/bin/bash
> set -e
> 
> psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
> 	CREATE SCHEMA strapi;
> 	SET search_path TO strapi;
> EOSQL
> ```
> In this way the default PostgreSQL schema is set to `strapi`.
> 
> Then, when Strapi is initialized the first time, it consider that `search_path` and creates the tables inside the `strapi` schema.
> 
> However, when a new content type is created and the service restarts it will not consider that setting anymore and the error about attempting to create a table that already exists will be thrown.
> 
> To fix this make sure that you have added this to the connection properties (file `config/database.js`):
> 
> ```
> schema: env('DATABASE_SCHEMA', 'public'),
> ```
> 
> And when you start the service set your environment variable `DATABASE_SCHEMA` to the correct name (`strapi` in this example).

Good catch! Indeed for most users that schema setting isn't needed but if your PG DB differs from the default that may be required.

**Comment by 595682** [comment] 2022-10-13 11:11
I am having the same issue with mySQL. I was on Strapi@4.2.3, upgraded to 4.3.6, and the issue persisted. After I change an enetity's schema (remove a field from an api element) and try to redeploy the app to staging, i get this error when running strapi start.

````
sql: 'create table `strapi`.`strapi_core_store_settings` (`id` int unsigned not null auto_increment primary key, `key` varchar(255) null, `value` longtext null, `type` varchar(255) null, `environment` varchar(255) null, `tag` varchar(255) null)',
bindings: []
}
]
[2022-10-13 13:02:19.247] debug: ⛔️ Server wasn't able to start properly.
[2022-10-13 13:02:19.250] error: create table `strapi`.`strapi_core_store_settings` (`id` int unsigned not null auto_increment primary key, `key` varchar(255) null, `value` longtext null, `type` varchar(255) null, `environment` varchar(255) null, `tag` varchar(255) null) - ER_TABLE_EXISTS_ERROR: Table 'strapi_core_store_settings' already exists
Error: ER_TABLE_EXISTS_ERROR: Table 'strapi_core_store_settings' already exists
````

If I drop the table it works, but that's not a solution. 

Any guesses where should I start digging to find a viable solution?

**Comment by Drakenwolf** [comment] 2022-11-15 21:26
i aa having the same issue with slq lite 3

**Comment by MohamedSonata** [comment] 2022-12-09 23:42
The best Solution for this problem you should add (.env) file in gitignore while you're  override  the Application  Environments to the cloud you're chosen  ..  this fixing my problem

**Comment by RolandaDev** [comment] 2024-01-11 08:53
How I solved this:
I got the same error as you:
` Error: DB table "components_sections_features" already exists. Change      ││   the collectionName` 
 
 I've deleted the table in the database but the problem was still there
 
 Then I've searched for "components_sections_features" in my code and there was a file in
 components/sections/features.js
 I've removed and that solved the problem
