### ISSUE TITLE
The flag --no-run is being ignored on Windows platform

### ISSUE THREAD

**Issue by adriatic** [strapi/strapi#7119] opened 2020-07-22 17:23 UTC
**Describe the bug**

The very first Strapi invocation (`yarn create strapi-app backend --quickstart --no-run `) fails to return control back to the terminal window. This problem manifests itself when using either CMD, [cmder](https://cmder.net/), or Powershell console. 

**Steps to reproduce the behavior**

1. Start the console and go to any windows directory (I used `c:/work/test`)
2. Run the command `yarn create strapi-app backend --quickstart --no-run `
3. Observe that the control is never returned to the console window

**System**

- Node.js version: v12.18.2
- NPM version: 6.14.5
- Strapi version:  3.0.6 
- Database:
- Operating system: Windows 10 PRO version 1903

**Additional context**

**Comment by derrickmehaffy** [comment] 2020-07-22 17:26
To add some additional context here, as I tested on the 2004 release of Windows 10 Pro in powershell. When the command is run, Strapi's process isn't terminated and doesn't return the user back to the shell and you need to forcefully kill the process with `ctrl + c` to return to the shell. 

Doing so within WSL or WSL2 I didn't notice the issue.

**Comment by adriatic** [comment] 2020-07-22 17:34
This man @derrickmehaffy is really incredible: I did not even finish my bug report - and he reacted with his (very relevant observation).

I believe that I exchanged a few messages with Pierre about this same issue a couple of months ago, when he tried it and could not reproduce it. Then I asked what computer does he use - and it was a Mac, of course.

**Comment by lauriejim** [comment] 2020-08-14 10:21
Hello! I'm closing this issue because it's a duplicate of your own issue there - https://github.com/strapi/strapi/issues/5759

**Closed by lauriejim** 2020-08-14 10:21 UTC
Labels: status: duplicate
