### ISSUE TITLE
GraphQL not working for already existing content types

### ISSUE THREAD

**Issue by tjvanderende** [strapi/strapi#1610] opened 2018-07-21 17:42 UTC
- **Node.js version**: 9.11.2
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.7.1
- **Database**: MySQL
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
Getting the error: Website.find is not a function when I apply a query on the whole collection from the local playground or JSON api. When applying a query for one record I get the following error: Cannot read property 'match' of undefined .
**Note:** , Querying build-in types like "User" , " Role"  works. Couldn't find anything different than I did.
**Note:**, The weird part is. The content-builder plugin can access my API (As it works without problem).

**Steps to reproduce the problem**
- Running a localhost:4000/admin besides a " strapi new [app] --dev" created project.
- Created content-types (created using the /admin environment).
- Added graph SQL plugin support. 
- Try to get data from the JSON api or GraphQL playground.

**What is the expected behavior?**
Querying data with GraphQL / traditional JSON api without any problems.

**Suggested solutions**
- I tryed this: " https://strapi.io/documentation/3.x.x/guides/graphql.html" but the documentation is not clear about what has to be customized and what is supported " out-oft-the-box" to solve the issue with GraphQL.
- Tryed to find the source of the .find functions, but can't find the issue (All looks well).

So the question (related to a bug or not) is: How can I use my JSON API / GraphQL?

**Comment by tjvanderende** [comment] 2018-07-25 06:30
UPDATE: Also doesn't work with the normal JSON api! (So probably priority: High). 
Same errors when requesting the normal JSON API.
Any updates on this? :(

**Comment by lauriejim** [comment] 2018-07-26 09:07
Hello @tjvanderende can you update your issue description and give us the Strapi version you user please.

**Comment by tjvanderende** [comment] 2018-07-27 07:42
I just did edit my original question and added the Strapi version.

**Comment by tjvanderende** [comment] 2018-08-01 09:52
Any news on this?

**Comment by derrickmehaffy** [comment] 2018-08-01 09:59
@tjvanderende For the RestAPI part on Strapi v13.0.1 I can confirm it works fine on MySQL. I'll test graphQL right now and let you know, but last time I looked it was functioning fine?

**Comment by derrickmehaffy** [comment] 2018-08-01 10:03
@johannpinson 

@tjvanderende may be onto something here, lookups are acting odd, it doesn't seem to be pulling the correct data and is only grabbing the first entry

Left -> Rest // Right -> GraphQL Playground

![image](https://user-images.githubusercontent.com/8593673/43515460-6bfca900-9537-11e8-9b05-f6062dc1bf57.png)

**Comment by derrickmehaffy** [comment] 2018-08-01 10:05
Getting a bunch of errors about bookshelf in console

```
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:187:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:187:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:187:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:187:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:187:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:187:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:187:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:187:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:187:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:187:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:187:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by lauriejim** [comment] 2018-08-01 15:04
Hello @tjvanderende I'm not able to reproduce your issue. It work fine on my side

@derrickmehaffy I have not your logs on my side. 
Can you give me logs of `params` param line 178
and logs of `record` line 187 please.

**Comment by derrickmehaffy** [comment] 2018-08-01 15:28
[strapi.log](https://github.com/strapi/strapi/files/2250089/strapi.log)

Also this dumped to console:

```
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:189:25)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:189:25)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:189:25)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:189:25)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:189:25)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:189:25)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:189:25)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:189:25)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:189:25)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:189:25)
TypeError: Cannot read property 'toJSON' of null
    at Function.findOne (/mnt/nixstorage/Github/Canonn/CAPIv2-Strapi/plugins/content-manager/config/queries/bookshelf.js:189:25)
```

**Comment by lauriejim** [comment] 2018-09-17 08:34
@derrickmehaffy @tjvanderende Can you give us an update about this issue. Still exist with last version of Strapi ?

**Comment by derrickmehaffy** [comment] 2018-09-17 08:35
@lauriejim it now working more or less, I am getting some additional errors but it isn't related to this issue anymore. You should be able to close this one.

**Closed** 2018-09-17 10:04 UTC
Labels: priority: medium, status: can't reproduce, type: bug 🐛
