### ISSUE TITLE
Media Library Broken After Deleting Content-Type

### ISSUE THREAD

**Issue by zurfluh** [strapi/strapi#8049] opened 2020-09-25 12:10 UTC
**Describe the bug**

**When** I delete a content-type that has Media entries which reference files
**then**
1. the media library does not show any files and displays an error
2. File upload for remaining content-types fail with error

**Steps to reproduce the behavior**

1. Create a content-type "Old" with a Media field "OldFile"
1. Create an "Old" entry, upload a file, and link the file to the "OldFile" field
1. Delete the "Old" content-type. (succeeds)
1. Media library shows an error popup and file uploads are not possible. Log:

```
error Error: The target polymorphic type "media_tests" is not one of the defined target types
    at Object.morphCandidate (/home/stefan/src/strapi/src/node_modules/bookshelf/lib/helpers.js:140:13)
    at /home/stefan/src/strapi/src/node_modules/bookshelf/lib/eager.js:52:15
    at /home/stefan/src/strapi/src/node_modules/bookshelf/node_modules/lodash/lodash.js:13427:38
    at /home/stefan/src/strapi/src/node_modules/bookshelf/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/home/stefan/src/strapi/src/node_modules/bookshelf/node_modules/lodash/lodash.js:2990:24)
    at Function.mapValues (/home/stefan/src/strapi/src/node_modules/bookshelf/node_modules/lodash/lodash.js:13426:7)
    at EagerRelation.morphToFetch (/home/stefan/src/strapi/src/node_modules/bookshelf/lib/eager.js:51:28)
    at EagerRelation.eagerFetch (/home/stefan/src/strapi/src/node_modules/bookshelf/lib/eager.js:25:19)
    at EagerRelation.<anonymous> (/home/stefan/src/strapi/src/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at /home/stefan/src/strapi/src/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper (/home/stefan/src/strapi/src/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> (/home/stefan/src/strapi/src/node_modules/bookshelf/lib/eager.js:31:31)
From previous event:
    at EagerRelation.eagerFetch (/home/stefan/src/strapi/src/node_modules/bookshelf/lib/eager.js:31:8)
    at EagerRelation.<anonymous> (/home/stefan/src/strapi/src/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at Child._handleEager (/home/stefan/src/strapi/src/node_modules/bookshelf/lib/collection.js:527:73)
    at Child.<anonymous> (/home/stefan/src/strapi/src/node_modules/bookshelf/lib/collection.js:179:27)
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Child.<anonymous> (/home/stefan/src/strapi/src/node_modules/bookshelf/lib/collection.js:177:12)
From previous event:
    at Child.fetchAll (/home/stefan/src/strapi/src/node_modules/bookshelf/lib/model.js:878:10)
    at Object.find (/home/stefan/src/strapi/src/node_modules/strapi-connector-bookshelf/lib/queries.js:62:8)
    at fn (/home/stefan/src/strapi/src/node_modules/strapi-database/lib/queries/helpers.js:31:54)
    at Object.find (/home/stefan/src/strapi/src/node_modules/strapi-database/lib/queries/helpers.js:15:24)
    at async find (/home/stefan/src/strapi/src/node_modules/strapi-plugin-upload/controllers/upload/admin.js:37:20)
    at async /home/stefan/src/strapi/src/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
```

**Expected behavior**
Media library keeps working after removing a content-type.

**Possibly related issues**
https://github.com/strapi/strapi/issues/7160, https://github.com/strapi/strapi/issues/7012, https://github.com/strapi/strapi/issues/7242

**System**

- Node.js version: v12
- NPM version: v6
- Strapi version: v3.1.3
- Database: PostgreSQL
- Operating system: Linux

**Comment by derrickmehaffy** [comment] 2020-09-28 17:32
I can confirm the bug on the latest release `v3.1.6` 

After deleting the content-type, the media library shows an error and the media file is not shown in the UI

**Comment by lauriejim** [comment] 2020-09-29 08:15
Probably also related to this issue - https://github.com/strapi/strapi/issues/6347

**Comment by derrickmehaffy** [comment] 2020-09-29 13:58
Ah yup you are right @lauriejim closing as duplicate of https://github.com/strapi/strapi/issues/6347

**Closed by derrickmehaffy** 2020-09-29 13:58 UTC
Labels: status: duplicate
