### ISSUE TITLE
[Blocker] error TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by EloB** [strapi/strapi#3936] opened 2019-09-09 21:26 UTC
**Describe the bug**
A newly created strapi with postgres won't start develop. I've got it running on sqlite

**Steps to reproduce the behavior**
```bash
strapi new myapp
# Choose postgres and valid settings
# I saw people in Slack reported the same issue on mysql but can't confirm it

cd myapp/
strapi develop

[2019-09-09T21:20:05.018Z] error Bootstrap function in plugin "users-permissions" failed
[2019-09-09T21:20:05.019Z] error TypeError: Cannot read property 'id' of null
```

It crashes here.
https://github.com/strapi/strapi/blob/v3.0.0-beta.16/packages/strapi-plugin-users-permissions/services/UsersPermissions.js#L437

When I outputed the `permission` information these are the broken part.
```js
{ id: 1,
  type: 'settings-manager',
  controller: 'settingsmanager',
  action: 'menu',
  enabled: false,
  policy: '',
  role: null }
{ id: 1,
  type: 'settings-manager',
  controller: 'settingsmanager',
  action: 'menu',
  enabled: false,
  policy: '',
  role: null }
```

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: Latest 16 beta
- Database: postgres
- Operating system: Windows 10

**Comment by alexandrebodin** [comment] 2019-09-09 22:07
Duplicate of #https://github.com/strapi/strapi/issues/3927

**Closed by alexandrebodin** 2019-09-09 22:07 UTC
