### ISSUE TITLE
Content-Types Builder: Cannot edit admin users collection

### ISSUE THREAD

**Issue by amrnn90** [strapi/strapi#8992] opened 2020-12-24 12:47 UTC
### Describe the bug

I want to add a field to the admin users collection type, but when I go to the Content-Types Builder page, it only shows:  User 
(from: users-permissions), but it doesn't show the other users collection which contains the admins.

### Steps to reproduce the behavior

1. Go to the Content-Types Builder.
2. Try looking for the admin users collection to edit it.

### Expected behavior

You should find two user collections:
1. User (from: users-permissions)
2. User (from: admin)

(the same issue also applies for the roles collection)

### System

- Node.js version: v14.15.1
- NPM version: 6.14.8
- Strapi version: v3.4.1
- Database: sqlite
- Operating system: Ubuntu 18.04.3 LTS

**Comment by soupette** [comment] 2020-12-24 14:00
Hello @amrnn90 thank you for opening this issue. The Admin collection type is not editable by design, the only way you can edit this model is by forking the strapi-admin plugin.
I am closing this issue as it is an intended behaviour.

**Closed by soupette** 2020-12-24 14:00 UTC

**Comment by amrnn90** [comment] 2020-12-24 14:15
Hi @soupette ,
Since this is an intended behaviour then maybe there's a better way to achieve the simple requirement that I have.

I have a typical posts collection, I need each post to to be associated with its original author, so I made a relation between the posts collection and the admin users (since these are the users who have access to the admin and can write the posts).

Now I need to display some information about each author by allowing them to provide some images and maybe some social links, in order to do this I have to add some fields to the admin collection, am I right?

I hope there's a simple solution for this requirement other than having to fork a plugin and overriding its implementation.
