### ISSUE TITLE
Conversion of long integers

### ISSUE THREAD

**Issue by scipe** [strapi/strapi#995] opened 2018-04-22 17:44 UTC
**Informations**
- **Node.js version**: 9.8.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.11.3
- **Database**: MongoDB v.3.6.0
- **Operating system**: Mac OS X

**What is the current behavior?**
Problem with edit field. When i try put in (text field or number field, nevermind, same problem) 76561198009194284, after save strapi change it on 76561198009194230. 
Its not only on number type of field! In text type same problem. 

**What is the expected behavior?**
Just save what i put.
Via mongodb console all working right. 

- [x] I'm sure that this issue hasn't already been referenced

**Comment by piere129** [comment] 2018-04-23 07:52
I have the same problem with my User. Trying to edit its' username to a new value results in "an error occured during update". I'm using MySQL as a database. Other self-created content-types get updated, but editing fields of the user always results in an error when saving.

**Comment by soupette** [comment] 2018-04-23 08:26
Hi @scipe I'm having a hard time understanding your issue...

Can you provide the steps to reproduce it and the expected behavior?

**Comment by profjefferson** [comment] 2018-04-23 08:48
I have same problem here, when i try edit a number field occur this error: 
This field is not editable for the moment...😮, its a fresh install

**Comment by piere129** [comment] 2018-04-23 09:01
@soupette Is my comment related with this issue? Or should I create a new issue?

**Comment by lauriejim** [comment] 2018-04-23 09:48
@profjefferson what is you Strapi version ?

**Comment by scipe** [comment] 2018-04-23 13:59
@soupette hello.

Create field with string type.
Go add new item.
Put it in this field 765611980091942**84**
After you save entity, field autochange on 765611980091942**30**

**Comment by scipe** [comment] 2018-04-23 14:02
@piere129 i have same problem with integer strings. But i think its another issue.

**Comment by oeddyo** [comment] 2018-04-24 05:34
same problem +1

**Comment by scipe** [comment] 2018-04-24 08:12
@soupette hi mate! now clear? you understand the problem?

**Comment by soupette** [comment] 2018-04-24 08:31
Hi @scipe the error is coming the ContentManager services at `parser` function.

**Comment by scipe** [comment] 2018-04-24 08:37
@soupette with type "TEXT" same problem. 

Thanks you for your work!

**Comment by soupette** [comment] 2018-04-24 08:39
Yes apparently Json.parse can't work with long numbers. I found this link on [stackoverflow](https://stackoverflow.com/questions/15689790/parse-json-in-javascript-long-numbers-get-rounded).

**Comment by scipe** [comment] 2018-04-24 08:47
@soupette but its if field is number. Why its doesnt work if field is string or text?

**Comment by scipe** [comment] 2018-04-24 08:53
So my entity bigger when Number.MAX_SAFE_INTEGER

**Comment by soupette** [comment] 2018-04-24 09:03
A possible fix could be the following (if @lauriejim agrees):

```js
// Parse stringify JSON data.
values = Object.keys(values.fields).reduce((acc, current) => {
   acc[current] = !_.isNaN(_.toNumber(values.fields[current])) ?
     values.fields[current]
     : parser(values.fields[current]);

  return acc;
}, {});
```

**Comment by lauriejim** [comment] 2018-05-11 10:13
@scipe Can you please follow @soupette instruction and submit a PR to fix this issue please.
We’ll be glad to count you as one of our contributors! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by derrickmehaffy** [comment] 2018-06-18 04:46
@scipe Can you confirm this issue still exists in Strapi 12.4? (Trying to help the team close out old issues.)

**Comment by lauriejim** [comment] 2018-06-18 08:07
@derrickmehaffy I confirm this issue still exist.

**Comment by derrickmehaffy** [comment] 2018-06-18 09:00
@lauriejim I believe this is a database related issue, strapi itself isn't rounding these I don't think.

**Comment by derrickmehaffy** [comment] 2019-03-04 06:57
As a small update, it seems that Bigint is being merged into javascript proper: https://tc39.github.io/proposal-bigint/

**Comment by fouber** [comment] 2019-07-04 12:38
When can this bug be fixed?

**Comment by lauriejim** [comment] 2019-07-08 14:43
We don't have any date for this issue.

**Comment by soupette** [comment] 2019-07-31 12:18
@lauriejim I think that @alexandrebodin can confirm but since we have removed the formdata in the content manager this issue will be solved at least for the text field.

**Comment by alexandrebodin** [comment] 2019-07-31 14:38
It will indeed be fixed once we release the upcoming feature

**Closed** 2019-09-09 11:32 UTC
Labels: Good for new contributors, priority: low, status: confirmed, type: bug 🐛
