### ISSUE TITLE
Querying _id results in an error every time.

### ISSUE THREAD

**Issue by wsalazar-peakactivity** [strapi/strapi#2255] opened 2018-11-03 00:46 UTC
**Informations**
- **Node.js version**: v10.6.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: Mongo db version v4.0.0
- **Operating system**: OSX 10.13.4

**What is the current behavior?**
Any time I add _id to any of my queries, I get the following error:
ID cannot represent value: {_bsontype: \"ObjectID\", id: <Buffer 5b db 47 78 37 6c 1f 2b 60 8a d4 0a>}

**Steps to reproduce the problem**
add _id to any query for an object inside your database

**What is the expected behavior?**
An id is returned

**Suggested solutions**

**Comment by lauriejim** [comment] 2018-11-05 15:03
Can you check this issue please: https://github.com/strapi/strapi/issues/1911

**Comment by lauriejim** [comment] 2018-11-05 15:04
Duplicate of this one (https://github.com/strapi/strapi/issues/2260)
Created after but more documented.

**Closed by lauriejim** 2018-11-05 15:04 UTC

**Comment by wsalazar-peakactivity** [comment] 2018-11-07 03:38
Thanks @lauriejim Downgrading to 0.13.2 solved the problem.
