### ISSUE TITLE
[strapi-admin] Input Validation Error Without Highlighting Problematic Fields

### ISSUE THREAD

**Issue by roylee0704** [strapi/strapi#8938] opened 2020-12-18 11:03 UTC
### Describe the bug

I'm trying to publish a new entry with 2-5 required fields that are left empty. However, instead of highlighting the problematic fields with reasons. It prompts me a generic alert: "Validation Error".

#### Additional Context 
The following outputs were showing in the developer console (Chrome: v87.0.4280.88).

- output1:
```js
data:
errors: {locationName: Array(1), locationLatitude: Array(1), locationLongitude: Array(1), partyReceivingLegalThreat: Array(1), partyLegalCounsel: Array(1), …}
__proto__: Object
error: "Bad Request"
message: "ValidationError"
statusCode: 400
__proto__: Object
```

- output2:
```js
main.9b72d5b1.chunk.js:79934 Deprecated: Will be deleted.
Please use strapi.notification.toggle(config).
Docs : https://strapi.io/documentation/v3.x/plugin-development/frontend-development.html#strapi-notification
```

The problematic field/reason pairs were clearly returned however it wasn't showing on the UI. A data-entry clerk might not know how to debug to locate the error.

### Steps to reproduce the behavior

1. Go to 'Add New Entry' on any collection. This collection needs to have at least 3 required fields.
2. Click on 'Save'.
3. Click on 'Publish'.
4. [partially-correct behavior]: It highlights the first required field in red and outline the reason 'this is required' below the field.  
5. Fix the error by filling up value. (note: at this moment, you should have 2 required fields unfilled)
6. Click on 'Save'.
7. Click on 'Publish'.
8. [bug]: This time, it doesn't highlight the required fields and no reason was outlined. Instead, it shows an alert: 'Validation Error'.

### Expected behavior

I'm expecting that all problematic fields will be highlighted in red + reason. 

### Screenshots

![image](https://user-images.githubusercontent.com/3850661/102607589-1b40e800-415b-11eb-8cd3-775cc439a02b.png)

### System

- Node.js version: v14.15.0
- NPM version: v6.14.8
- Strapi version: v3.4.0
- Database: mongodb
- Operating system: macOs Catalina - v10.15.7

**Comment by sunnysonx** [comment] 2020-12-18 11:52
Reproduced the issue. 

Happens only with mongo, because these "required" fields do not exist at all in the mongo's document, so when you are hitting the publish button it tries to check if all the required fields have values, but they do not exist, as a result, it returns a message that these fields must be defined:
![image](https://user-images.githubusercontent.com/14160283/102611250-40236400-4137-11eb-806b-8bf26f6e2fdd.png)

If you add some content to these required fields and after that leave them empty, the validation will work ok, since the fields exist in the mongo document.

As a fast fix to this: when creating the document inside mongo, it should also create the required fields, with a **null** value.

**Comment by roylee0704** [comment] 2020-12-18 14:23
Hey @sunnysonx, thanks for the quick response!

In fact it's working as intended - I'm expecting it to catch the nullability error.  

However only 1 last step is missing, is to render the error message on the impacted fields instead of a generic alert 'Validation Error'. :)

**Comment by derrickmehaffy** [comment] 2021-01-25 15:20
This bug was also reported via a customer to happen on PostgreSQL as well in v3.4.x/v3.3.x

**Comment by soupette** [comment] 2021-03-03 11:11
I can't reproduce this issue with the latest version of strapi 3.5.2.
I am closing this issue feel free to reopen it.

**Comment by LucaNerlich** [comment] 2021-03-03 11:18
Hello, @soupette 
this issue is still present.

Strapi 3.5.2
MongoDB

Create Date Field, mark required, Save, Hit Publish. Results in "Generic Validation Error", NO red markings on the error field and only information in the browser console. Please see attached screenshots:

![strapi1](https://user-images.githubusercontent.com/5942270/109798091-97a37d00-7c1a-11eb-9d56-9d4648e9f60d.jpg)
![strapi2](https://user-images.githubusercontent.com/5942270/109798094-996d4080-7c1a-11eb-8ff7-1ddff9889248.jpg)

**Comment by soupette** [comment] 2021-03-03 11:25
It

**Comment by LucaNerlich** [comment] 2021-03-03 11:26
Are you running on mongodb?

**Comment by soupette** [comment] 2021-03-03 11:28
At this point, the required validations should be checked before the request is sent, so it is not related to the database.

**Comment by LucaNerlich** [comment] 2021-03-03 11:32
> in this case the issue might be coming from your side.

How? We are only using standard strapi components. Nothing special.
Im trying to recreated this in a public repo soon. But so far, something is definetly not working correctly - and has not been, since we are using strapi. This specific issue was always a pain.

**Comment by LucaNerlich** [comment] 2021-03-03 11:37
@soupette ive reproduced it with a brand new strapi project:

https://github.com/LucaNerlich/strapi-validation-error

**Comment by soupette** [comment] 2021-03-03 12:08
Ok I know where the issue is coming from, it's indeed due to the database you are using. 
With mongo, when you are creating an entry the database doesn't use null as default for the fields that have not been created and this causes the issue. 
In the admin panel due to the implementation of RBAC the validations can be skipped when a user does not have the right to see a field, in your case the admin panel considers that the missing field are valid since it matches the condition that a user does not have the right to read the required fields.

Right now, I don't have a proper solution for this however you can try to customise the content manager so it supports the errors sent from the back-end, or you can use another database.

Regarding the customisation here's what you can do:

1. Modify these [lines](https://github.com/strapi/strapi/blob/ebcfa07c338f3d1ac7fe29162fd9ab8edb4fba39/packages/strapi-plugin-content-manager/admin/src/containers/CollectionTypeFormWrapper/index.js#L150-L164) to something like the following:

```
const [formErrors, setFormErrors] = useState({});
const displayErrors= useCallback(err => {
  const errors = Object.entries(get(errorPayload, 'data.errors', {})).reduce((acc, current) => {
      acc[current[0]] = { id: current[1][0] };

      return acc;
  }, {});
  setFormErrors(errors)
},[]}
```

2. Modify the [EditView component](https://github.com/strapi/strapi/blob/ebcfa07c338f3d1ac7fe29162fd9ab8edb4fba39/packages/strapi-plugin-content-manager/admin/src/containers/EditView/index.js#L94) as follows

```
<DataManagerWrapper ...>
 {({..., status, formErrors}) => <EditViewDataManagerProvider ... errors={formErrors}></EditViewDataManagerProvider>}
```

3. In the [EditViewDataManagerProvider](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/admin/src/containers/EditViewDataManagerProvider/index.js) add the following

```
useEffect(() => {
  if (!isEmpty(error)) {
    dispatch({ type: 'SET_FORM_ERRORS', errors });
   }
}, [errors])
```

Then you will be able to display the response from the api

**Comment by LucaNerlich** [comment] 2021-03-03 12:13
I appreciate your response, however, in my opinion, this should be fixed internally in strapi. Having to create custom overlays / altering strapi core code cannot be the solution for this.

**Comment by derrickmehaffy** [comment] 2021-03-03 13:28
> I appreciate your response, however, in my opinion, this should be fixed internally in strapi. Having to create custom overlays / altering strapi core code cannot be the solution for this, since this **will** create issues while upgrading strapi in the future. This is an integral part of any cms / form editor and should need to be handeled by the user/developer - for built in components. At least the required/regex fields should always show some human understandable error.
> 
> Since this is not the first database specific issue, maybe it would be an idea to ditch all those database options (knex) and move to e.g postgres only, wikijs. is doing the same. Handling all those specific issues is an overhead, one could potentially avoid.
> 
> https://blog.js.wiki/news/2021/wiki-js-3-going-full-postgresql

It's a temporary workaround that @soupette provided as we have a much larger refactoring needed to modify the logic that shows validation errors

**Comment by LucaNerlich** [comment] 2021-03-03 13:40
To understand your comment correctly, this refactoring is indeed planned, right?

**Comment by derrickmehaffy** [comment] 2021-03-08 17:06
We don't have an ETA but it's on the "menu" @LucaNerlich

**Comment by brunomptavares** [comment] 2021-04-26 22:25
I'm using mongo and have the same issue, however it only shows on the models with the draft/publish feature on. On other models  where it's off, the missing fields are properly highlighted.

**Comment by lukesmmr** [comment] 2021-09-27 15:31
I can still reproduce this issue on Strapi `v3.8.6`. After reducing the amount of supported fields of an enum saving an item would not allow to submit just throwing "Validation Error" but without highlighting the errors in the UI (see screenshot attached). Running local dev version with sqlite.

![Strapi - Content Manager 2021-09-27 16-25-55](https://user-images.githubusercontent.com/4427047/134939013-8fa70c85-69b3-4765-87ec-d3be897ad007.png)

**Comment by derrickmehaffy** [comment] 2021-10-04 22:12
will be "fixed" in the v4

**Comment by Strapi-User** [comment] 2021-11-18 15:06
I'm still facing the same issue on Strapi v4 beta13, I have a custom validator in the lifecycle but the message in the ValidationError that is returned in the body of the "400 Bad Request" response message is not shown in the UI, only a generic "Bad Request" so the author has no idea why the update fails. Any ideas on how this can be fixed in v4?

**Comment by derrickmehaffy** [comment] 2021-11-19 20:28
> I'm still facing the same issue on Strapi v4 beta13, I have a custom validator in the lifecycle but the message in the ValidationError that is returned in the body of the "400 Bad Request" response message is not shown in the UI, only a generic "Bad Request" so the author has no idea why the update fails. Any ideas on how this can be fixed in v4?

It's not possible to pass DB validation errors into the frontend and highlight a field.

**Comment by derrickmehaffy** [comment] 2021-11-30 14:21
Fixed in v4, marking as closed

**Closed by derrickmehaffy** 2021-11-30 14:21 UTC
Labels: type: bug, severity: medium, status: confirmed, source: plugin:content-manager

**Comment by DonikaV** [comment] 2022-10-27 11:18
`{error: {name: "ValidationError", message: "displayName.required", details: {errors: [,…]}}}
error
: 
{name: "ValidationError", message: "displayName.required", details: {errors: [,…]}}
details
: 
{errors: [,…]}
errors
: 
[,…]
0
: 
{path: ["components", "0", "displayName"], message: "displayName.required", name: "ValidationError"}
message
: 
"displayName.required"
name
: 
"ValidationError"
path
: 
["components", "0", "displayName"]
message
: 
"displayName.required"
name
: 
"ValidationError"`
Version 4, trying to add another field
