### ISSUE TITLE
v4: Could not resolve dependency @strapi/plugin-upload@"^4.0.0"

### ISSUE THREAD

**Issue by xeon566** [strapi/strapi#11139] opened 2021-09-29 18:17 UTC
Strapi v4 Installation on Ubuntu stops at installation of @strapi/plugin-upload@"^4.0.0"

Happens with and without --quickstart option

### Steps to reproduce

1. Run npx create-strapi-app@beta beta
2. Select Custom
3. Select sqlite
4. agree to default database path

```
ubuntu@ubuntu:/dev/strapi$ npx create-strapi-app@beta beta
? Choose your installation type Custom (manual settings)
? Choose your default database client sqlite
? Filename: .tmp/data.db

Creating a project with custom database options.
Creating a new Strapi application at /dev/strapi/beta.
Creating files.
Error while installing dependencies:
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @strapi/provider-upload-local@4.0.0-beta.0
npm WARN Found: peer @strapi/plugin-upload@"^4.0.0" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @strapi/plugin-upload@"^4.0.0" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @strapi/plugin-upload@^4.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-09-29T16_40_53_460Z-debug.log

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following command:

cd /dev/strapi/beta && npm install

ubuntu@ubuntu:/dev/strapi$ npm install
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @strapi/provider-upload-local@4.0.0-beta.0
npm WARN Found: peer @strapi/plugin-upload@"^4.0.0" from the root project
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @strapi/plugin-upload@"^4.0.0" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @strapi/plugin-upload@^4.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2021-09-29T18_04_46_392Z-debug.log
```

### System

- Node.js version: v14.17.6
- Strapi version: 4.0.0-beta.0
- Database: sqlite
- Operating System: Ubuntu 20.04.3 LTS, Virtual Machine

**Comment by derrickmehaffy** [comment] 2021-09-29 18:20
```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @strapi/provider-upload-local@4.0.0-beta.0
npm WARN Found: peer @strapi/plugin-upload@"^4.0.0" from the root project
```

Are you using a custom npm proxy or have some kind of custom resolver system configured on your system? 

Can't reproduce on Linux Mint 20.2 using npm or yarn

**Comment by LucaNerlich** [comment] 2021-09-29 18:24
Most likely also due to windows. Has similar issues when trying around. 

#11137

**Comment by xeon566** [comment] 2021-09-29 18:37
> 
> 
> ```
> npm WARN ERESOLVE overriding peer dependency
> npm WARN While resolving: @strapi/provider-upload-local@4.0.0-beta.0
> npm WARN Found: peer @strapi/plugin-upload@"^4.0.0" from the root project
> ```
> 
> Are you using a custom npm proxy or have some kind of custom resolver system configured on your system?
> 
> Can't reproduce on Linux Mint 20.2 using npm or yarn

No, default global npm installation. 
The ubuntu vm on which i tried the installation is part of a server cluster using Proxmox.

Tried to reproduce it on Zorin OS too, installation worked fine tho.

Maybe it's an error on my side, sorry for that if that's the case.
Gonna test some more tomorrow.

**Comment by daveteu** [comment] 2021-09-30 08:47
I have the above issue when using node v16. 

Installation works when I use node 14.

I'm using macOs

**Comment by MattieBelt** [comment] 2021-09-30 08:54
> I have the above issue when using node v16.
> 
> Installation works when I use node 14.
> 
> I'm using macOs

Hey @daveteu any difference in NPM/Yarn version as well?

**Comment by josephfh** [comment] 2021-09-30 13:26
In case it helps anyone, I updated my Node version to the latest using nvm (MacOs)

Node v14.17.3 - same error as above 
**Node v14.18.0 - works 😄**

**Comment by freekvisser** [comment] 2021-10-01 11:01
Hey there! I faced the same issue. After this command fails, there is a package.json file in your beta folder. In this file I changed the following fields under `dependencies` from this:
```
"@strapi/strapi": "4.0.0-beta.0",
"@strapi/plugin-users-permissions": "4.0.0-beta.0",
"@strapi/plugin-i18n": "4.0.0-beta.0",
```
to this:
```
"@strapi/strapi": "4.0.0-next.0",
"@strapi/plugin-users-permissions": "4.0.0-next.0",
"@strapi/plugin-i18n": "4.0.0-next.0",
```

Hope this helps!

**Comment by LucaNerlich** [comment] 2021-10-01 12:03
@freekvisser next is the alpha, its older than beta.

**Comment by freekvisser** [comment] 2021-10-01 12:07
@LucaNerlich 
Thanks for the heads-up, when executing `npm view @strapi/plugin-upload`, the returned version is `@strapi/plugin-upload@4.0.0-next.0`, so I'm guessing the beta version is not yet published to npm?

**Comment by LucaNerlich** [comment] 2021-10-01 12:14
Possibly not for this plugin. MediaLibrary is also disabled in quickstart beta0 as of now.

**Comment by daveteu** [comment] 2021-10-01 14:37
> > I have the above issue when using node v16.
> > Installation works when I use node 14.
> > I'm using macOs
> 
> Hey @daveteu any difference in NPM/Yarn version as well?

It works when I use `node v14.17.4 (npm v6.14.14)`

Above error will occur when I use `node v16.5.0 (npm v7.19.1)`

**Comment by LucaNerlich** [comment] 2021-10-01 14:38
Node 16 is not supported atm.

**Comment by alserembani94** [comment] 2021-10-04 22:14
> 
> 
> > > I have the above issue when using node v16.
> > > Installation works when I use node 14.
> > > I'm using macOs
> > 
> > 
> > Hey @daveteu any difference in NPM/Yarn version as well?
> 
> It works when I use `node v14.17.4 (npm v6.14.14)`
> 
> Above error will occur when I use `node v16.5.0 (npm v7.19.1)`
> 
> Since @josephfh advised `v14.17.3` will cause the same error, I believe the min requirement is `node v14.17.4`

But the problem is, I use Node v14.18.0, and still didn't manage to successfully install `@strapi/plugin-upload@4.0.0-next.0`

**Comment by alserembani94** [comment] 2021-10-04 22:16
> 
> 
> > > > I have the above issue when using node v16.
> > > > Installation works when I use node 14.
> > > > I'm using macOs
> > > 
> > > 
> > > Hey @daveteu any difference in NPM/Yarn version as well?
> > 
> > 
> > It works when I use `node v14.17.4 (npm v6.14.14)`
> > Above error will occur when I use `node v16.5.0 (npm v7.19.1)`
> > Since @josephfh advised `v14.17.3` will cause the same error, I believe the min requirement is `node v14.17.4`
> 
> But the problem is, I use `node v14.18.0`, and still didn't manage to successfully install `@strapi/plugin-upload@4.0.0-next.0`

For more context, I am currently using WSL2 (Ubuntu). `node v14.18.0`, `npm v7.24.1`

**Comment by derrickmehaffy** [comment] 2021-10-04 22:19
you should be on the beta, not the next release.

Try to create a project with `npx create-strapi-app@beta testBeta --quickstart`

**Comment by derrickmehaffy** [comment] 2021-10-04 22:20
you do need to downgrade your npm version with node also. Node 14/NPM 6 is the max at the moment.

**Comment by derrickmehaffy** [comment] 2021-10-04 22:20
Closing for now as this is almost certainly related to npm v7 issue which we will tackle once we add in node 16 support.

**Closed by derrickmehaffy** 2021-10-04 22:20 UTC
Labels: type: bug, severity: medium, status: can't reproduce, flag: v4-Alpha/Beta

**Comment by derrickmehaffy** [comment] 2021-11-24 17:15
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/v4-beta-or-next-a-new-version-of-strapi-is-available-4-0-0-beta-0-4-0-0-next-0/11636/3
