### ISSUE TITLE
[strapi v5 Beta] Custom controller cannot get body

### ISSUE THREAD

**Issue by iamobj** [strapi/strapi#20430] opened 2024-06-04 16:01 UTC
### Required System information

- Node.js version: 20.11.1
- NPM version: pnpm/9.0.6
- Strapi version: 5.0.0-beta.8
- Database: sqlite
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Custom controller, cannot get the body of `POST` request in the controller, I use `ctx.request.body`, ts prompt type "Request" does not have attribute "body", use `ctx.body`, ts does not report an error, but what I get is undefined

### Code snippets

```js
createOrder(ctx) {
      console.log("body", ctx.body); // body undefined
      return {};
}
```
if use `ctx.request.body`, Program error and terminated, error message `Property 'body' does not exist on type 'Request'`

**Comment by iamobj** [comment] 2024-06-05 04:09
I tested on v4, `ctx.body` also has no value, the correct usage is `ctx.request.body`, but v5 will type error: error message `Property 'body' does not exist on type 'Request'`, I currently use the following way to get it normally
```js
createOrder(ctx) {
      console.log("body", (ctx.request as any).body);
}
```

**Comment by gregg-cbs** [comment] 2024-06-11 06:59
Somewhat related forum:
https://forum.strapi.io/t/how-to-type-the-context-object-in-strapi-api-with-typescript/28935/6

**Comment by Eventyret** [comment] 2024-06-11 12:47
Confirmed in `5.0.0-beta.9`

```bash
curl --location 'http://localhost:1337/api/test/createOrder' \
--header 'Content-Type: application/json' \
--data '{
    "hello": "World"
}'
```

```typescript
import { factories } from "@strapi/strapi";
import { Context } from "koa";

export default factories.createCoreController(
  "api::test.test",
  ({ strapi }) => ({
    async createOrder(ctx: Context) {
      console.log("ctx", ctx.request); // has no body
      console.log("body", ctx.body); // body undefined
      return {};
    },
  })
);

```

```json
ctx {
  method: 'POST',
  url: '/api/test/createOrder',
  header: {
    'content-type': 'application/json',
    'user-agent': 'PostmanRuntime/7.39.0',
    accept: '*/*',
    'postman-token': '666c3c50-ee4b-4841-8e30-4e54b59ad3d2',
    host: 'localhost:1337',
    'accept-encoding': 'gzip, deflate, br',
    connection: 'keep-alive',
    'content-length': '24'
  }
}
body undefined
```

body object does not exist in ctx.

**Comment by gfritzdev** [comment] 2024-07-05 20:51
I ran into this issue today.  There is no body found in the ctx.  I was trying to create a custom controller for creating records using the new Document Service API  because the lifecycle hooks no longer work on the default create method.

**Comment by kuizuo** [comment] 2024-08-17 18:40
There is still this problem in 5.0.0-beta.10 version.

**Comment by inkkonito** [comment] 2024-08-19 14:26
still seeing this as warning in VS, any way to fix it? thx

**Comment by alexandrebodin** [comment] 2024-09-03 12:23
Will be part of the next rc release

**Closed** 2024-09-03 12:23 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: typescript, version: 5, source: core:core

**Comment by James-dalsoft** [comment] 2024-10-01 01:31
The bug still happens at v5.0.1

**Comment by GerardPolloRebozado** [comment] 2024-10-22 11:36
I have the same bug at v5.1.0
