### ISSUE TITLE
Renaming field name in a component + MySQL

### ISSUE THREAD

**Issue by gilmarllen** [strapi/strapi#8138] opened 2020-10-01 21:05 UTC
**Describe the bug**
When renaming a field in a component, a new column is created in the database (MySQL in my case) and the old column is kept. The problem is that since Strapi doesn't set a default value for the columns in the MySQL, isn't possible to create entries on that table because the old field will be empty always.

**Steps to reproduce the behavior**

1. Create a component with a field
2. Rename that field name
3. Try to create a new entry in a collection that uses this component created.
4. See the error in the logs: ``Error: ER_NO_DEFAULT_FOR_FIELD: Field 'field_name' doesn't have a default value``

**Expected behavior**
Simply rename the column in the database as configured on Strapi.

**System**

- Strapi docker image (dev): 3.1.6 (node v12.18.2)
- Database: MySQL
- Operating system: Windows

**Comment by derrickmehaffy** [comment] 2020-10-01 21:09
Closing as duplicate of http://github.com/strapi/strapi/issues/1114

**Closed by derrickmehaffy** 2020-10-01 21:09 UTC
Labels: status: duplicate

**Comment by derrickmehaffy** [comment] 2020-10-01 21:10
For the moment @gilmarllen you will need to manually remove that old column from your database or handle the rename (deleting the new column) manually.

We know this is a massive pain point and are looking at our options

**Comment by gilmarllen** [comment] 2020-10-01 21:13
@derrickmehaffy No problem, I'm managing it in this way now. Glad to hear you are looking for this. Thanks!
