### ISSUE TITLE
DTS Import is failing on schema detection

### ISSUE THREAD

**Issue by PaulBratslavsky** [strapi/strapi#20388] opened 2024-05-28 19:19 UTC
### Required System information

- Environment: development
- OS: darwin-arm64
- Strapi Version: 5.0.0-beta.8
- Node/Yarn Version: npm/10.2.4 node/v20.11.1 darwin arm64 workspaces/false
- Edition: Community
- Database: sqlite
- Is your project Javascript or Typescript:

### Describe the bug

DTS Import  fails with warning messages after completing no files were imported.

### Steps to reproduce the behavior

See video

https://github.com/strapi/strapi/assets/6153188/254b49dd-d3af-4aeb-af43-4c489df1415b

### Expected behavior

Should import data.

### Screenshots

No data imported

![2024-05-28_14-17-31 (1)](https://github.com/strapi/strapi/assets/6153188/fb60c6b3-a35b-4fa1-b756-5cfd4ba6a508)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by Convly** [comment] 2024-05-29 07:21
Hey Paul, as mentioned in the CLI, since the transfer engine finds discrepancies between source (archive) and destination (app) schemas, it will ignore the related data and only import the rest (permissions, locales, etc...). So, this part is working as intended.

However, the fact that it finds such differences in the schema for the same app (on the `publishedAt.default`) is definitely a bug and is already listed in our internal DX backlog.

Thanks for sharing this, I'll add it to the internal ticket for the reproduction steps.

**Comment by PaulBratslavsky** [comment] 2024-05-29 16:01
@Convly thanks for the help, I may be a bit confused.  Why would there be discrepancies if the source was generated from the same app that I am trying to reimport the data too.  Is there a potential fix I can employ to be able to import my data.

**Comment by derrickmehaffy** [comment] 2024-05-29 18:01
@Convly here is a quick repo, just created the app, exported, and tried to import.

![image](https://github.com/strapi/strapi/assets/8593673/756ec85d-870e-43e3-b295-d3c8c19c1ef3)

**Comment by Convly** [comment] 2024-05-29 18:03
>Why would there be discrepancies if the source was generated from the same app that I am trying to reimport the data too

That's what I'm saying, there shouldn't be any, it's a known issue with known reproduction steps that we already have in our backlog :slightly_smiling_face:

**Comment by Convly** [comment] 2024-05-29 18:04
> Is there a potential fix I can employ to be able to import my data.

Not that I know of, maybe by deleting the schema files in the archive so that the detection isn't run? But I'm not sure it'll accept the source without the schema (you can always try) :thinking:

**Comment by PaulBratslavsky** [comment] 2024-05-30 15:31
@Convly thank you for the response.  Yep, I was confused. Now I am not.🙂

**Comment by Convly** [comment] 2024-06-06 13:54
Fixed by https://github.com/strapi/strapi/pull/20421

**Closed** 2024-06-06 13:54 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:data-transfer, version: 5
