### ISSUE TITLE
multifield search in where clause of graphql plugin

### ISSUE THREAD

**Issue by heavenkiller2018** [strapi/strapi#4902] opened 2020-01-05 23:29 UTC
**Describe the bug**
there is a defect that multifield search is not supported in graphql plugin .

**Steps to reproduce the behavior**
1. in mongodb shell:
`db.stores.insert(` [ { _id: 1, name: "Java Hut", description: "Coffee and cakes" }, { _id: 2, name: "Burger Buns", description: "Gourmet hamburgers" }, { _id: 3, name: "Coffee Shop", description: "Just coffee" }, { _id: 4, name: "Coffee Shop Clothes Clothes Clothes", description: "Discount clothing" }, { _id: 5, name: "Java Shopping", description: "Indonesian goods" } ] )`

2. if i want to get data that contain 'coffee' in 'description' field, the script could be like this:
`db.getCollection("stores").find( { "description" : { "$regex" : 'coffee', $options: 'i' } })`
results:
`{ "_id" : 1.0, "name" : "Java Hut", "description" : "Coffee and cakes" } { "_id" : 3.0, "name" : "Coffee Shop", "description" : "Just coffee" }`
the correspondent where clause in graphql plugin of strapi is following:
where: {"description_contains":"coffee"}

3. but if i want to fetch data that contain 'coffee' in 'description' or 'name' field, it could be realized in mongodb shell like this:
`
db.getCollection("stores").find( { "$or" : [ { "name" : { "$regex" : 'coffee', $options: 'i' } }, { "description" : { "$regex" : 'coffee', $options: 'i' } } ] } );`

results:
`{
"_id" : 1.0,
"name" : "Java Hut",
"description" : "Coffee and cakes"
}
{
"_id" : 3.0,
"name" : "Coffee Shop",
"description" : "Just coffee"
}
{
"_id" : 4.0,
"name" : "Coffee Shop Clothes Clothes Clothes",
"description" : "Discount clothing"
}`

4. but i'm suprised it can't be realized in graphql plugin of strapi because there is no correspondent syntax. or you can give me some advise to get it?

multifield search is very useful and extensive in absence of text index search!
I strongly recommend to improve it!

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v12.13.1
- NPM version:6.12.1
- Strapi version: 3.0.0-beta.15
- Database: mongodb
- Operating system:windows server 2019

**Additional context**

**Comment by derrickmehaffy** [comment] 2020-01-06 05:29
closing as duplicate of: https://github.com/strapi/strapi/issues/3194

**Closed by derrickmehaffy** 2020-01-06 05:29 UTC
