### ISSUE TITLE
Deployment in Heroku with PostGres : Error: self signed certificate

### ISSUE THREAD

**Issue by marieqg** [strapi/strapi#5671] opened 2020-04-01 05:29 UTC
**Describe the bug**
I'm trying to do a deployment of a new strapi project to heroku using PostGres. The deployment is succesfull but the application does not work. 

**Steps to reproduce the behavior**
1. I did a quick start of a strapi project and follow the official tutorial to deploy. 
2. See error: 

````
2020-04-01T05:27:32.733966+00:00 app[web.1]: [2020-04-01T05:27:32.733Z] debug ⛔️ Server wasn't able to start properly.
2020-04-01T05:27:32.734517+00:00 app[web.1]: [2020-04-01T05:27:32.734Z] error Error: self signed certificate
2020-04-01T05:27:32.734518+00:00 app[web.1]:     at TLSSocket.onConnectSecure (_tls_wrap.js:1492:34)
2020-04-01T05:27:32.734518+00:00 app[web.1]:     at TLSSocket.emit (events.js:315:20)
2020-04-01T05:27:32.734518+00:00 app[web.1]:     at TLSSocket._finishInit (_tls_wrap.js:935:8)
2020-04-01T05:27:32.734519+00:00 app[web.1]:     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:693:12)
2020-04-01T05:27:32.744466+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-04-01T05:27:32.744761+00:00 app[web.1]: npm ERR! errno 1
2020-04-01T05:27:32.745842+00:00 app[web.1]: npm ERR! my-project@0.1.0 start: `strapi start`
2020-04-01T05:27:32.745935+00:00 app[web.1]: npm ERR! Exit status 1
2020-04-01T05:27:32.746069+00:00 app[web.1]: npm ERR! 
2020-04-01T05:27:32.746142+00:00 app[web.1]: npm ERR! Failed at the my-project@0.1.0 start script.
2020-04-01T05:27:32.746238+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-04-01T05:27:32.753869+00:00 app[web.1]: 
2020-04-01T05:27:32.753997+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-04-01T05:27:32.754068+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-04-01T05_27_32_746Z-debug.log
````

**System**
- Node.js version: v10.16.0
- NPM version: 6.11.2
- Strapi version: "3.0.0-beta.19.4",
- Database: PostGres
- Operating system: macOS

**Additional context**
 My production database is like this : 
```{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "bookshelf",
      "settings": {
        "client": "postgres",
        "host": "${process.env.DATABASE_HOST }",
        "port": "${process.env.DATABASE_PORT }",
        "database": "${process.env.DATABASE_NAME }",
        "username": "${process.env.DATABASE_USERNAME }",
        "password": "${process.env.DATABASE_PASSWORD }",
        "ssl": true
      },
      "options": {}
    }
  }
}
```
Any idea on how to fix this thing? 
Thanks in advance, 
Marie

**Comment by derrickmehaffy** [comment] 2020-04-01 05:37
Per: https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain/45088585

This isn't directly an issue with Strapi, it's how node handles self-signed cert files:

```
From your question I'm guessing you are doing this in development as you are using a self signed certificate for SSL communication.

If that's the case, add NODE_TLS_REJECT_UNAUTHORIZED='0' as an environment variable wherever you are running node or running node directly with NODE_TLS_REJECT_UNAUTHORIZED='0' node app.js

This instructs Node to allow untrusted certificates (untrusted = not verified by a certificate authority)

I would not recommend setting this environment variable in production. Use a free SSL cert from a trusted provider like letsencrypt.org
```

Marking as closed as not a bug with Strapi but comes from node itself.

**Comment by marieqg** [comment] 2020-04-01 05:39
Thanks!

**Comment by tomastuser** [comment] 2020-04-02 14:15
Having exactly the same problem and can't seem to resolve it. I'm on Windows, otherwise I have the same specs as Marie. Any help would be appreciated.

**Comment by rovaniemi** [comment] 2020-04-02 18:18
I have the same problem. @derrickmehaffy are you sure the problem is not related to Strapi? At least Strapi has broken documentation because @marieqg tried to follow it and failed. 


I tried to go through the solution what this [chain suggests](https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain/45088585), but none of them worked.

**Comment by derrickmehaffy** [comment] 2020-04-02 18:24
> I have the same problem. @derrickmehaffy are you sure the problem is not related to Strapi? At least Strapi has broken documentation because @marieqg tried to follow it and failed.
> 
> I tried to go through the solution what this [chain suggests](https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain/45088585), but none of them worked.

I did not directly test with Heroku no, but considering that Strapi does not deal with SSL in any capacity (other than a database SSL cert, which is handled by Knex and is not "validated") It is unlikely that it's directly an issue with Strapi.

I'm not entirely sure where this SSL cert is coming from, but if it's on the request side, Strapi doesn't handle SSL at all and instead generally recommends you offload that to another service (for non-serverless users/heroku generally Nginx, Apache, HAProxy, or Traefik is suggested).

However Heroku handles SSL itself, which wouldn't even touch Strapi. So I'm confused as to where this cert is coming from.

**Comment by rovaniemi** [comment] 2020-04-02 18:52
> > I have the same problem. @derrickmehaffy are you sure the problem is not related to Strapi? At least Strapi has broken documentation because @marieqg tried to follow it and failed.
> > I tried to go through the solution what this [chain suggests](https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain/45088585), but none of them worked.
> 
> I did not directly test with Heroku no, but considering that Strapi does not deal with SSL in any capacity (other than a database SSL cert, which is handled by Knex and is not "validated") It is unlikely that it's directly an issue with Strapi.
> 
> I'm not entirely sure where this SSL cert is coming from, but if it's on the request side, Strapi doesn't handle SSL at all and instead generally recommends you offload that to another service (for non-serverless users/heroku generally Nginx, Apache, HAProxy, or Traefik is suggested).
> 
> However Heroku handles SSL itself, which wouldn't even touch Strapi. So I'm confused as to where this cert is coming from.

@derrickmehaffy Okay, I located this problem. When I downgrade `pg` from `8.0.0` to `7.4.3` it works. This issue is strongly related to [this](https://github.com/brianc/node-postgres/issues/2009). 

I don’t know what you’re going to do about it because it’s not directly related to Strapi, but your current Heroku with Postgres documentation/build is broken.

**Comment by derrickmehaffy** [comment] 2020-04-02 19:02
Reopening as we will need to ensure we have a way (maybe by default) to make sure the certs aren't validated.

@alexandrebodin might be something we need to look at.

**Comment by tomastuser** [comment] 2020-04-02 19:56
Finally I made it work by leaving out the line - "ssl": true  - when modifiying database.json in config/environments/production. The line was included in the deployment tutorial on strapi web, however when I followed the webinar on youtube about deploying strapi, the line wasn't included there.

**Comment by derrickmehaffy** [comment] 2020-04-03 08:28
Closing this again in favor a more clear description of the issue (as it's not directly related to Heroku, but is a PG issue): https://github.com/strapi/strapi/issues/5696

**Closed by derrickmehaffy** 2020-04-03 08:28 UTC
