### ISSUE TITLE
can't access to email plugin settings!

### ISSUE THREAD

**Issue by yaitmou** [strapi/strapi#6703] opened 2020-06-17 07:50 UTC
**Bug description**
email settings not accessible as per the [documentation](https://strapi.io/documentation/3.0.0-beta.x/plugins/email.html#programmatic-usage)
In the plugins, accessed via the left menu bar, I can see the email plugin among the installed plugins but it's missing the cog button to access email setting!
when I input the full path as described by the documentation [http://localhost:1337/admin/plugins/email/configurations/development](http://localhost:1337/admin/plugins/email/configurations/development) I still can't access the email setting.

when I manually enter the URL. The browser console says:
"react_devtools_backend.js:6 Error: Minified React error #130..."

since it appeared to be a react problem, I run the app using the `--watch-admin` flag. When trying the hit the same URL, through `port:8000`, the browser's console says: 
"Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: null."

**Steps to reproduce the behavior**

*Option 1*
1. install a **fresh strapi project** with `strapi new <project-nam> <dist>`
2. Click on 'Plugins' from the left menu bar
3. Under the list of installed plugins 
4. No cog button next to "EMAIL - Send emails" see the preview below 
![image](https://user-images.githubusercontent.com/31067870/84869514-ce366900-b086-11ea-801a-455dae010d70.png)

*Option 2*
1. Directly access the setting page through URL : [http://localhost:1337/admin/plugins/email/configurations/development](http://localhost:1337/admin/plugins/email/configurations/development)
2. Open the browser's console
3. Find the error shown in the screenshot below:
![Screen Shot 2020-06-17 at 10 44 23 AM](https://user-images.githubusercontent.com/31067870/84870111-8cf28900-b087-11ea-8bed-158eb787e7bf.png)

**Expected behavior**
Possibility to access the Email plugin setting through the cog button

**System**

- Node.js version: v12.6.0
- NPM version: 6.14.4
- Strapi version: 3.0.2
- Database: mongodb
- Operating system: MacOS Catalina v10.15.5

Any hint would be greatly appreciated as my love for strapi is expanding <3

**Comment by akhilmhdh** [comment] 2020-06-17 08:41
As your COG is missing, you must be using the latest stable version v3 of strapi. In v3 email plugin configurations has been changed to internally rather than in admin. That doc is for v3-beta.

Here you go the latest doc :
https://strapi.io/documentation/v3.x/plugins/email.html#configure-the-plugin

**Comment by derrickmehaffy** [comment] 2020-06-17 10:44
There have also been about 20 other issues that have been posted about this: https://github.com/strapi/strapi/issues?q=is%3Aissue+email+settings

Please be sure you read the contributing guide related to opening an issue: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue

Marking as closed as this is a duplicate of at least 20 other issues. And the user was looking at the beta documentation.

**Closed by derrickmehaffy** 2020-06-17 10:44 UTC

**Comment by yaitmou** [comment] 2020-06-17 11:05
my bad :s

**Comment by derrickmehaffy** [comment] 2020-06-24 09:56
> my bad :s

All good, your issue is what motivated me to make a notice issue about it: https://github.com/strapi/strapi/issues/6710

Hopefully other users that were in your position read that ;)

**Comment by mitul-srashtasoft** [comment] 2021-01-12 05:50
Nothing is working good, please help
