### ISSUE TITLE
Google sign in provider does not work for users created from dashboard

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [strapi/strapi#12421] opened 2022-02-06 19:17 UTC
### Describe the bug

A user created via Strapi dashboard when trying login using the same email via Google returns an error.

### Steps to reproduce the behavior

1. Create a new user from `http://localhost:1337/admin/content-manager/collectionType/plugin::users-permissions.user/create`. Make sure the email you are using is provided by Google/GSuite.
2. Now authenticate the same email with Google to get the user `accessToken` from Google.
3. Hit with the access token hit the endpoint `http://localhost:1337/api/auth/google/callback/?access_token=${accessToken}`
4. It returns an error.

### Expected behavior

It should return user with the access token.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version:
- Strapi version: v4.0.7
- Database: PostgreSQL
- Operating system:

**Comment by derrickmehaffy** [comment] 2022-02-07 21:01
No error information provided by user and most of the system information is missing, closing as we can't reproduce without more information from the issue author.

**Closed by derrickmehaffy** 2022-02-07 21:01 UTC
