### ISSUE TITLE
The date time value is decreasing by utc value.

### ISSUE THREAD

**Issue by Thanseem007** [strapi/strapi#3102] opened 2019-04-09 05:21 UTC
**Informations**
- **Node.js version**: v10.13.0
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**:  Mongo db
- **Operating system**: Windows
- **(Optional) Link to your Project**: 

**What is the current behavior?**
The date time is decreased by utc value.That change is directly reflecting on the  value in front side.

**Steps to reproduce the problem**

**What is the expected behavior?**
The local value should be visible on front side.Even if the date time value in mongo is utc.

**Suggested solutions**

**Comment by derrickmehaffy** [comment] 2019-04-09 06:58
Closing as duplicate of: https://github.com/strapi/strapi/issues/2811

**Closed by derrickmehaffy** 2019-04-09 06:58 UTC
