### ISSUE TITLE
Typescript error when using strapi.entityService.create with populate: localizations: select: string[]

### ISSUE THREAD

**Issue by seleckis** [strapi/strapi#18716] opened 2023-11-09 12:04 UTC
I'm registering custom graphql operations using `register` function and get typescript error.
```ts
const extensionService = strapi.service("plugin::graphql.extension");
extensionService.use(createPageWithAllLocales);
```

then function `createPageWithAllLocales` makes actions like:

```ts
const mainEntry = await strapi.entityService.create(modelUid, {
  data: {
    ...data,
    localizations,
  },
  populate: {
    localizations: {
      select: ["id"],
    },
  },
});
```
`strapi` is global and has type `Strapi`, but seems it is incomplete, because for the property `select` it shows an error:
```
Type '{ localizations: { select: string[]; }; }' is not assignable to type 'Any<CollectionTypes.pages>'.
  Types of property 'localizations' are incompatible.
    Type '{ select: string[]; }' is not assignable to type 'boolean | NestedParams<"api::page.page">'.
      Object literal may only specify known properties, and 'select' does not exist in type 'NestedParams<"api::page.page">'.ts(2322)
index.d.ts(64, 13): The expected type comes from property 'populate' which is declared here on type '{ fields?: Any<CollectionTypes.pages>; } & { populate?: Any<CollectionTypes.pages>; } & { data?: Input<CollectionTypes.pages>; } & { ...; }'
```
___

Environment: development
OS: darwin-x64
Strapi Version: 4.15.0
Node/Yarn Version: yarn/1.22.19 npm/? node/v18.12.1 darwin x64
Edition: Community
Database: sqlite

**Comment by derrickmehaffy** [comment] 2023-11-09 13:14
It's not select at this level, it's fields.

Gonna mark this as closed as it's not a bug but a question.

**Closed** 2023-11-09 13:15 UTC
Labels: flag: question
