### ISSUE TITLE
Bad JSON data breaks API and admin dashboard

### ISSUE THREAD

**Issue by nikita-fuchs** [strapi/strapi#15496] opened 2023-01-19 10:56 UTC
Hello, 

It is possible to remotely break APIs if the content type has a JSON field and the `create` operation is permitted. This also breaks the admin UI and prevents administrators from removing the malicious record, accessing the DB directly is the only way to fix the incident.

Reproduction steps:

1. Create a datatype with a JSON field
2. Create a new record via direct API call or using the entity service 
```
strapi.entityService.create(... { data: jsonField:{ "foo" }...
```
**with a string (!)** instead of an object for the JSON field.

This will lead to the string being stored directly in the DB table as strapi seemingly relies fully on the DB to perform validation. The problem is though that Postgres' JSONB type allows storing objects, **strings, and other data**. (see https://materialize.com/docs/sql/types/jsonb/#details )
Upon the call in step 2, the console will show a JSON parsing error, because Strapi is - for whatever reason - immediately reading the newly created record from the DB and expects the data to be a JSON object. 

Now Strapi is defacto broken, because every time somebody calls the API endpoint that includes such a malformatted JSON record, the parsing fails and there is an error response.

If an admin tries to investigate the issue, he is hit with the same error as the record(s) cannot be read because of the parsing error.

I recommend implementing a 'safe mode' view for the admin panel, so users aren't stuck with a broken strapi instance if issues like these occur in the future.

Node.js version: v18.12.1
NPM version: v9.2.0
Strapi version: 4.5.6
Database: postgres
Operating system: OSX

**Comment by Cpaczek** [comment] 2023-01-30 15:41
issue is here: https://github.com/strapi/strapi/blob/main/packages/core/database/lib/fields/json.js 

the issue is that the yup validation for the field doesn't require a JSON object and will accept a string and when strapi goes to pull that out of the database it will try and parse it and break everything. This could allow users to break the admin panel for anyone using a json field by just passing it a string.

**Comment by nikita-fuchs** [comment] 2023-01-30 16:07
I don't know how the yup validators exactly work, but all it needs is to check whether the passed data is actually an object, this should be doable pretty quickly, right?

**Comment by Cpaczek** [comment] 2023-01-30 16:26
Ya actually you would just need to validate the json in here: https://github.com/strapi/strapi/blob/main/packages/core/database/lib/fields/json.js also should probably do it on the yup end as this seems like its a last resort. 

You can see an example here: https://github.com/strapi/strapi/blob/main/packages/core/database/lib/fields/number.js

**Comment by derrickmehaffy** [comment] 2023-01-30 19:31
Marked as reproduced based on the evaluation of @Cpaczek

**Comment by derrickmehaffy** [comment] 2023-01-30 19:32
Notes:

Should only happen on PostgreSQL but possibly MySQL due to the native json functions in these databases.

**Comment by gu-stav** [comment] 2023-01-31 07:54
@derrickmehaffy Do you think it makes sense to create a separate FE task based on that? I haven't tested the issue, but if the admin app crashes on the field value I'd also consider this is a bug.

**Comment by joshuaellis** [comment] 2023-01-31 08:00
> @derrickmehaffy Do you think it makes sense to create a separate FE task based on that? I haven't tested the issue, but if the admin app crashes on the field value I'd also consider this is a bug.

I'm not Derrick, but yes. I think the FE shouldn't break from a bad value in the CMS instead it probably needs to show a warning

**Comment by derrickmehaffy** [comment] 2023-01-31 13:39
> > @derrickmehaffy Do you think it makes sense to create a separate FE task based on that? I haven't tested the issue, but if the admin app crashes on the field value I'd also consider this is a bug.
> 
> I'm not Derrick, but yes. I think the FE shouldn't break from a bad value in the CMS instead it probably needs to show a warning

Indeed I'd say that's a good idea

**Comment by Cpaczek** [comment] 2023-01-31 17:49
@joshuaellis @gu-stav @derrickmehaffy 

It seems like its not a FE error it's a 500 from the backend there's nothing to fix on the front end.

![image](https://user-images.githubusercontent.com/25715982/215841971-e0497692-fd0b-4995-8f76-95bfbd7363ab.png)

![image](https://user-images.githubusercontent.com/25715982/215842010-e8f612f9-e369-470e-9291-cd0fd014dccb.png)

**Comment by derrickmehaffy** [comment] 2023-01-31 17:50
> @joshuaellis @gu-stav @derrickmehaffy 
> 
> It seems like its not a FE error it's a 500 from the backend there's nothing to fix on the front end.
> 
> ![image](https://user-images.githubusercontent.com/25715982/215841971-e0497692-fd0b-4995-8f76-95bfbd7363ab.png)
> 
> ![image](https://user-images.githubusercontent.com/25715982/215842010-e8f612f9-e369-470e-9291-cd0fd014dccb.png)
> 

I think to their point we should return a sane error message on the frontend

**Comment by Cpaczek** [comment] 2023-01-31 17:54
I would agree but backend is returning a 500 which in theory should never happen. It does return this which is as much as it could return. 
![image](https://user-images.githubusercontent.com/25715982/215843236-3b24a8b1-e6f3-45f4-b9ba-8116e9792675.png)

**Comment by petersg83** [comment] 2023-02-08 17:20
Hello everybody :) It seems it happens only on Postgres. I've created a PR : #15752 could you test it and tell me if it fixes your issue ?

**Comment by cellmanguney** [comment] 2023-02-13 06:48
This issue not only creating through API, you can reproduce it on Admin as well.
<img width="962" alt="image" src="https://user-images.githubusercontent.com/6186950/218389779-be0c3f21-35af-42b3-a70a-c10c87e87e70.png">

**Closed** 2023-02-13 11:44 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:database
