### ISSUE TITLE
Can't login to my dashboard beacuase always show 'Email is already taken'

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1254] opened 2018-05-23 04:23 UTC
**Informations**
- **Node.js version**: v10.1.0
- **npm version**: v5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: MongoDB
- **Operating system**: Linux

**What is the current behavior?**
can't login to my app.
I login and work on my app yesterday but today when I want to login to my app I see setup page again.
I try to fill setup form again. but it's always return `Email is already taken`.
See below gif for more info:
![strapi 4](https://user-images.githubusercontent.com/25859075/40403350-b16b332e-5e66-11e8-98e3-05946fb08743.gif)

Can you help me?

**Steps to reproduce the problem**
I don't know :disappointed: 

**What is the expected behavior?**
I want to login or if any error happens please correct error message.

**Suggested solutions**

**Comment by jquequezana** [comment] 2018-05-23 04:36
Same issue, the first time register the admin when go to logout an relogin show again the register

**Comment by mnlbox** [comment] 2018-05-23 05:04
I also try to remove database completely and setup again but it's still return `Email is already taken` :thinking:

**Comment by derrickmehaffy** [comment] 2018-05-23 06:30
@mnlbox this is a duplicate of https://github.com/strapi/strapi/issues/1235. 

@lauriejim this issue should be closed and further troubleshooting should be done in the linked issue.

**Comment by mnlbox** [comment] 2018-05-23 08:45
OK, I think it's maybe related but why show `Email is already taken` error? In related issue you said that it's related to internet speed. :thinking:

**Comment by soupette** [comment] 2018-05-23 09:09
@mnlbox what browser are you using? Can you try using Chrome until we release this [patch}(https://github.com/strapi/strapi/pull/1222/files).


A  quick solution would be to add the code from the [PR](https://github.com/strapi/strapi/pull/1222/files) then run the following commands in your app (I can't guarantee that it will work if you're using an OS different from mac..., If you struggle DM me on slack).

```
// Create a new strapi app
$ strapi new my-app2
// We will need only the admin, so in order to prevent any bug from happening when trying to build the admin we're going to remove the plugins folder
$ cd my-app && rm -rf plugins
// Open the admin/admin/src/containers/AdminPage/index.js file and apply the modifications

// At the root of your app
$ npm run setup
```

The copy the admin folder into your existing app and it should be working fine.

**Comment by lauriejim** [comment] 2018-05-23 09:11
Hello @mnlbox , please follow the issue template so we can get a better understanding about the origin of your bug.
I will reopen your issue as soon as it follows the templating guidelines.
Thank you.

> Informations are missing

**Comment by mnlbox** [comment] 2018-05-23 09:17
@lauriejim excuse me man. I copy my node, npm, strapi, ... versions from another issue but I forget to paste it. I update my question, could you reopen this issue?
Please add latest version of Node, NPM, ... as a comment in issue template.

**Comment by mnlbox** [comment] 2018-05-23 09:27
@soupette I'm using Firefox.
I'm using strapi 12.2 and you merge PR #1222 so why this error happens? :thinking:

**Comment by soupette** [comment] 2018-05-23 09:30
@mnlbox good it's a good question!

The error is happening because I prevent the plugins from being loaded if the user is not logged in, therefore if the browser is slow the condition `hasAdminUser` is always false so you're always redirected to the register page.

**Comment by mnlbox** [comment] 2018-05-23 09:32
@soupette it's my Chromium experience:
![strapi 5](https://user-images.githubusercontent.com/25859075/40416174-dcd933aa-5e91-11e8-88ac-40de512a15c8.gif)

**Comment by derrickmehaffy** [comment] 2018-05-23 09:54
@soupette I don't think the browser is the main cause in this case, as I generally only use chrome and have noticed the same issue on both windows, linux, and mac.

**Comment by derrickmehaffy** [comment] 2018-05-23 09:55
@mnlbox the email error is normal as the email exists in the database, this is an issue with the redirect settings of the admin panel and not related to the information is being stored.

If you use something like Studio3T (Mongo) or HeidiSQL (MySQL) you'll see that your user is in fact in the database. Hence why that error is popping up.

**Comment by mnlbox** [comment] 2018-05-23 09:59
@derrickmehaffy I check and I haven't any user with that email.
I just randomly create tons of email and always it's return `Email is already taken`. I'm sure that it's message wrong.

**Comment by derrickmehaffy** [comment] 2018-05-23 10:01
@mnlbox Can you give me a screenshot of your mongoDB with the important bits blacked out (really would rather not see password hashes)

Given my testing has been on MySQL but I can see the users listed in my database. The issue is coming from the adminUI and its redirections

**Comment by mnlbox** [comment] 2018-05-23 10:06
@derrickmehaffy I try to completely drop and recreate my database with `db.dropDatabase()` but it's still return `Email is already taken`. I told that I'm sure that I haven't that users.

**Comment by derrickmehaffy** [comment] 2018-05-23 10:08
You dropped your entire database or just that `table` sorry I don't know what you call it in Mongo (can't stand the database personally :stuck_out_tongue: )

**Comment by derrickmehaffy** [comment] 2018-05-23 10:09
If you dropped the entire database you will need to restart strapi. As there is no database and there is likely a console error saying it can't connect.

**Comment by mnlbox** [comment] 2018-05-23 10:30
Yes I drop and restart Strapi but it's again return `Email is already taken`.

@lauriejim please reopen this issue until fix. Thanks man :wink:

**Comment by jquequezana** [comment] 2018-05-24 07:28
@soupette Thanks, that fix the issue

**Comment by soupette** [comment] 2018-05-24 07:39
@mnlbox can you show me your user model?

**Comment by mnlbox** [comment] 2018-05-24 08:13
@soupette This is my user model:
```
{
  "connection": "default",
  "info": {
    "name": "user",
    "description": ""
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true
    },
    "role": {
      "model": "role",
      "via": "users",
      "plugin": "users-permissions",
      "configurable": false
    },
    "firstname": {
      "type": "string",
      "required": true
    },
    "lastname": {
      "type": "string",
      "required": true
    }
  },
  "collectionName": "users-permissions_user"
}
```

**Comment by lauriejim** [comment] 2018-05-24 09:09
@soupette told me, @mnlbox you have to remove additional attributes (firstname and lastname) required.

**Comment by mnlbox** [comment] 2018-05-24 10:16
But I want this field as a required field :disappointed

**Comment by soupette** [comment] 2018-05-24 10:34
@mnlbox what about registering the first admin user and then set it back to true?

**Comment by soupette** [comment] 2018-05-24 10:34
The other options would be to modify the refister form so it displays firstname and lastname

**Comment by mig4ng** [comment] 2018-05-24 10:56
I am also having this issue both on firefox and chrome, it seems when I registered my admin yesterday it did make the change and now I am locked out of the application, what should I do?

**Comment by soupette** [comment] 2018-05-24 12:00
You'll need to make the modifications listed previously on the issue

**Comment by mig4ng** [comment] 2018-05-24 12:05
I read them but did not understand, do I have to generate a new project and copy the admin folder? Isn't it possible to fix directly my project instead?

**Comment by soupette** [comment] 2018-05-24 12:10
@mig4ng what is your OS?

**Comment by soupette** [comment] 2018-05-24 12:38
@mig4ng I think it will be easier if you take the admin folder from this [project](https://github.com/soupette/fix-strapi-login/tree/master/admin). It's an app that I pushed with the fix from above. So you don't have to rebuild the admin

**Comment by derrickmehaffy** [comment] 2018-05-24 17:33
@raulriera just as a quick test, use chrome and try and visit your site, if it redirects you to login, hit the back button twice. See if it drops you on the login page.

**Comment by raulriera** [comment] 2018-05-24 18:03
> @raulriera just as a quick test, use chrome and try and visit your site, if it redirects you to login, hit the back button twice. See if it drops you on the login page.

I'll try that the next time it happens, unable to reproduce it without "waiting a few days until admin starts doing that"

**Comment by israelroldan** [comment] 2018-05-25 10:18
This is caused by the analytics plugin, if you're not using it just disable it and voila!

**Comment by mig4ng** [comment] 2018-05-25 11:13
thanks @soupette! It worked for me, if anyone is having this issue too on any unix based OS just go to the directory above your project, clone the @soupette project, remove the admin/admin folder in your project and copy the admin/admin folder from the @soupette project to yours

**Step by step:**
1. Go to your project and `cd ..`
2. Clone @soupette project with `git clone https://github.com/soupette/fix-strapi-login.git`
3. Remove your admin/admin folder with `rm -rf {YOUR_PROJECT_PATH}/admin/admin`
4. Copy the @soupette admin/admin folder to your project with `cp -r fix-strapi-login/admin/admin {YOUR_PROJECT_PATH}/admin`

And you are done

**Comment by raulriera** [comment] 2018-05-27 15:56
@derrickmehaffy you are right, hitting the back button twice takes me to the login page. But I second the opinion I saw somewhere else that we should simply remove the redirect and link the two pages together... Being able to go from login to register anytime I want by having http links in them

**Comment by derrickmehaffy** [comment] 2018-05-27 23:51
@raulriera yeah thats what I thought, although it seems there might be other issues related to this as others have stated their admin user is not in the database (which I find odd, personally I think this is just related to this redirect issue and the user does exist there.) That being said, I don't use MongoDB and MySQL is far easier to check with. I still get the issue from time to time with @mig4ng and @soupette's fix but it's hard to pin down the cause. It has to be with some change between 12.1.3 and 12.2

**Comment by soupette** [comment] 2018-08-09 09:39
@sanchit-aneja Did you add some required field to the existing user model?

**Comment by soupette** [comment] 2018-08-09 09:41
What you can do is set some default value to your user model.

Anyway, I going to make this form more dynamic so it can take in account any added required field.

I'm reopening it.

**Comment by soupette** [comment] 2018-08-27 16:03
The other way would be to add a default value to the required fields.

**Closed by soupette** 2018-08-27 16:03 UTC
Labels: priority: medium, status: have to reproduce, type: bug 🐛
