### ISSUE TITLE
Webhooks not working with user-permissions.user

### ISSUE THREAD

**Issue by fabio-nettis** [strapi/strapi#6680] opened 2020-06-15 11:59 UTC
**Describe the bug**
As of version 3.0.1, it doesn't seem to be possible to listen to user creation, editing or deletion via webhook. The webhook simply never is called for the `user-permissions.user` model.

**Steps to reproduce the behavior**

1. Create a new webhook
2. Click create, edit and delete 
3. Try to see any results while performing actions on any user

**Expected behavior**
The webhook should also be called for the user-permissions.user entity.

**System**

- Node.js version: v12.13.0
- Yarn version: 1.12.3
- Strapi version: 3.0.1
- Database: SQLite
- Operating system: Windows 10, 2004 Update

**Additional context**

**Comment by alexandrebodin** [comment] 2020-06-15 12:07
Duplicate of https://github.com/strapi/strapi/issues/5324

**Closed by alexandrebodin** 2020-06-15 12:07 UTC
