### ISSUE TITLE
bootstrap function in admin failed, because of JSON Syntaxerror

### ISSUE THREAD

**Issue by jorgens** [strapi/strapi#10916] opened 2021-09-08 22:32 UTC
### Describe the bug

I cannot restart my strapi docker container. After running `docker compose up` I get the error message:
```
Starting your app...
[2021-09-08T22:17:51.585Z] error bootstrap function in admin failed
[2021-09-08T22:17:51.587Z] error SyntaxError: Unexpected number in JSON at position 1
SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.json (/srv/app/node_modules/strapi-connector-bookshelf/lib/formatter.js:24:17)
    at /srv/app/node_modules/strapi-connector-bookshelf/lib/formatter.js:15:27
    at /srv/app/node_modules/strapi-connector-bookshelf/lib/mount-models.js:630:37
    at Array.forEach (<anonymous>)
    at formatEntry (/srv/app/node_modules/strapi-connector-bookshelf/lib/mount-models.js:624:41)
    at /srv/app/node_modules/strapi-connector-bookshelf/lib/mount-models.js:636:46
    at Array.forEach (<anonymous>)
    at Child.<anonymous> (/srv/app/node_modules/strapi-connector-bookshelf/lib/mount-models.js:636:29)
    at /srv/app/node_modules/bookshelf/lib/base/events.js:101:64
    at tryCatcher (/srv/app/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/srv/app/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/srv/app/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/srv/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/srv/app/node_modules/bluebird/js/release/promise.js:604:18)
From previous event:
    at Child.triggerThen (/srv/app/node_modules/bookshelf/lib/base/events.js:101:20)
    at Child.<anonymous> (/srv/app/node_modules/bookshelf/lib/collection.js:196:25)
From previous event:
    at Child.<anonymous> (/srv/app/node_modules/bookshelf/lib/collection.js:182:12)
From previous event:
    at Child.fetchAll (/srv/app/node_modules/bookshelf/lib/model.js:878:10)
    at find (/srv/app/node_modules/strapi-connector-bookshelf/lib/queries.js:81:8)
    at /srv/app/node_modules/strapi-database/lib/queries/paginated-queries.js:10:25
    at async Object.findPage (/srv/app/node_modules/strapi-database/lib/queries/helpers.js:15:18)
    at async Object.cleanPermissionsInDatabase (/srv/app/node_modules/strapi-admin/services/permission/queries.js:138:37)
    at async module.exports (/srv/app/node_modules/strapi-admin/config/functions/bootstrap.js:55:3)
    at async Strapi.load (/srv/app/node_modules/strapi/lib/Strapi.js:379:5)
    at async Strapi.start (/srv/app/node_modules/strapi/lib/Strapi.js:196:9)
```

### Expected behavior

Starting the strapi server. It hints at a problem with the JSON description of one of the models, but they all seem OK.
How can I debug this further?

### System

- Node.js version: Standard Node version coming with the latest strapi/strapi image
- NPM version: Standard NPM version coming with the latest strapi/strapi image
- Strapi version: 3.6.8
- Database: sqlite3
- Operating system: Alpine

**Comment by kasonde** [comment] 2021-09-09 14:05
Could you please share the steps to reproduce the error? is there anything that was done before you got to this point?

**Comment by jorgens** [comment] 2021-09-09 15:30
Thanks for looking into this! 
I am sorry I cannot give you any concrete steps to reproduce. The docker container had been running for quite some time and was stopped and started with `docker-compose down` and `docker-compose up`, so it might have been some config I did a while ago causing the trouble, which makes it hard to pinpoint. 
Do you think the error is to be sought somewhere in the DB or in a config?

**Comment by derrickmehaffy** [comment] 2021-09-10 19:56
> Thanks for looking into this!
> I am sorry I cannot give you any concrete steps to reproduce. The docker container had been running for quite some time and was stopped and started with `docker-compose down` and `docker-compose up`, so it might have been some config I did a while ago causing the trouble, which makes it hard to pinpoint.
> Do you think the error is to be sought somewhere in the DB or in a config?

It would be in a config file, something isn't passing basic syntax validation.

**Comment by derrickmehaffy** [comment] 2021-09-10 19:57
I'm setting this as closed as it's most likely not a bug with Strapi but the user environment. In cases like this please move your question over to our forum: https://forum.strapi.io or our Discord: https://discord.strapi.io

**Closed by derrickmehaffy** 2021-09-10 19:57 UTC
