### ISSUE TITLE
Updating entry repeatable component object fails with Error: entry.notFound

### ISSUE THREAD

**Issue by petre2dor** [strapi/strapi#10375] opened 2021-05-24 18:21 UTC
### Describe the bug

When I try to update an entry with the repeatable component and I send it the component data that I get when I query the entry (find or findOne) it throws: `Error: entry.notFound` and replaces each entry from the component with `null`. 

### Steps to reproduce the behavior

1. Create new strapi project with Mongo
2. Create a new collection with a repeatable component:

Collection model:
```json
{
  "kind": "collectionType",
  "collectionName": "collections",
  "info": {
    "name": "collection"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string"
    },
    "component_repeateble": {
      "type": "component",
      "repeatable": true,
      "component": "component-category.component-repeateble"
    }
  }
}
```
Component model:
```JSON
{
  "collectionName": "components_component_category_component_repeatebles",
  "info": {
    "name": "component-repeateble",
    "icon": "ad"
  },
  "options": {},
  "attributes": {
    "enum": {
      "type": "enumeration",
      "enum": [
        "A",
        "B",
        "C"
      ]
    }
  }
}

```
3. Create a new test endpoint:
4. 
Entry in routes:
```JSON
    {
      "method": "GET",
      "path": "/collections/test",
      "handler": "collection.test",
      "config": {
        "policies": []
      }
    }
```
Method in controller:
```JS
async test(ctx) {
    const entity = await strapi.services.collection.findOne({ name: 'c' });
    console.log("🚀 ~ file: collection.js ~ line 19 ~ test ~ entity", entity)
    try {
      const res = await strapi.services.collection.update({id: entity.id}, entity);
      console.log("🚀 ~ file: collection.js ~ line 21 ~ test ~ res", res)
    } catch (error) {
      console.log("🚀 ~ file: collection.js ~ line 25 ~ test ~ error", error)

    }

    return res
  },
```
4. Error:
```JS
🚀 ~ file: collection.js ~ line 19 ~ test ~ entity {
  _id: 60abe8f1e0ac7f773d748f41,
  name: 'c',
  component_repeateble: [
    {
      enum: 'A',
      _id: 60abe8f1e0ac7f773d748f42,
      __v: 0,
      id: '60abe8f1e0ac7f773d748f42'
    },
    {
      enum: 'B',
      _id: 60abe8f1e0ac7f773d748f43,
      __v: 0,
      id: '60abe8f1e0ac7f773d748f43'
    }
  ],
  createdAt: 2021-05-24T17:57:05.074Z,
  updatedAt: 2021-05-24T17:57:05.095Z,
  __v: 1,
  created_by: {...},
  updated_by: {...},
  id: '60abe8f1e0ac7f773d748f41'
}
🚀 ~ file: collection.js ~ line 25 ~ test ~ error Error: entry.notFound
    at update (/home/user/strapi-bug/node_modules/strapi-connector-mongoose/lib/queries.js:493:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:434:9)
    at async Object.update (/home/user/strapi-bug/node_modules/strapi-connector-mongoose/lib/queries.js:74:14)
    at async Object.update (/home/user/strapi-bug/node_modules/strapi-database/lib/queries/helpers.js:15:18)
    at async Promise.all (index 0)
    at async updateComponents (/home/user/strapi-bug/node_modules/strapi-connector-mongoose/lib/queries.js:211:30)
    at async update (/home/user/strapi-bug/node_modules/strapi-connector-mongoose/lib/queries.js:503:5)
    at async Object.update (/home/user/strapi-bug/node_modules/strapi-connector-mongoose/lib/queries.js:74:14)
    at async Object.update (/home/user/strapi-bug/node_modules/strapi-database/lib/queries/helpers.js:15:18)
    at async Object.update (/home/user/strapi-bug/node_modules/strapi/lib/services/entity-service.js:175:17)
    at async Object.test (/home/user/strapi-bug/api/collection/controllers/collection.js:21:19)
    at async /home/user/strapi-bug/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
    at async module.exports (/home/user/strapi-bug/node_modules/strapi-plugin-users-permissions/config/policies/permissions.js:88:3)
    at async /home/user/strapi-bug/node_modules/strapi-utils/lib/policy.js:68:5 {
  status: 404
}
```
5. The entry is no longer visible in Admin, as the page is stuck in loading. Inspecting this XHR request: `http://localhost:1337/content-manager/collection-types/application::collection.collection/60abe8f1e0ac7f773d748f41` show that it returns: 
```JSON
{
  "_id": "60abe8f1e0ac7f773d748f41",
  "name": "c",
  "component_repeateble": [ null, null ],
  "createdAt": "2021-05-24T17:57:05.074Z",
  "updatedAt": "2021-05-24T17:57:05.095Z",
  "__v": 1,
  "created_by": {...},
  "updated_by": {...}
  },
  "id": "60abe8f1e0ac7f773d748f41"
}
```
Notice the ` "component_repeateble": [ null, null ]`

### Expected behavior
No error expected and the contents of the collection entry(including the component data) should remain unchanged.

### System

- Node.js version: v12.20.1
- NPM version: 6.14.10
- Strapi version: 3.6.2 (same problem occured on 3.5.3)
- Database: Mongo 4.4.6
- Operating system: Ubuntu

Thank you for your work!

**Comment by hksfho** [comment] 2021-11-24 02:27
hi, do you have any idea? I have a quick fix but don't think this is a good soluation.

```
const {map, pick, partialRight} = require('lodash');
entity['component_repeateble'] = map(entity['component_repeateble'], partialRight(pick, ['id']));
```

**Comment by derrickmehaffy** [comment] 2021-12-10 03:41
Closing as can't reproduce in v4

**Closed by derrickmehaffy** 2021-12-10 03:41 UTC
Labels: status: can't reproduce

**Comment by Grzanka99** [comment] 2022-07-04 17:40
> Closing as can't reproduce in v4

And that's why I will never use strapi again
