### ISSUE TITLE
Error: SQLITE_ERROR: duplicate column name: event

### ISSUE THREAD

**Issue by Gribbs** [strapi/strapi#3490] opened 2019-06-19 11:21 UTC
**Describe the bug**
I've been building out my content-types in the admin ui and somehow I've created a duplicate column and now ` strapi develop` command is not working. I get the Error:

```
strapi develop
{ Error: SQLITE_ERROR: duplicate column name: event errno: 1, code: 'SQLITE_ERROR' }
[2019-06-19T10:51:38.357Z] debug ⛔️ Server wasn't able to start properly.
[2019-06-19T10:51:38.357Z] error Error: SQLITE_ERROR: duplicate column name: event
```
I've seen in other issues it seems it can be fixed in the .tmp/data.db file but I'm not sure where and afraid to edit it in case I destroy hours of work. Is there an easier way to recover from this?

Any help will be appreciated.

**Expected behavior**
The server should start and let me correct any error.

**Screenshots**

**Code snippets**

**Snip** Removing DB file as it contains user private data -DMehaffy

**System**
- Node.js version: v10.0.0
- NPM version: 5.6.0
- Strapi version: 3.0.0-beta.6
- Database: default SQLite
- Operating system: 10.14.5 (18F132)

**Comment by derrickmehaffy** [comment] 2019-06-19 11:22
@Gribbs always make a backup, and short answer is no, you will need to go clean up the DB. I recommend getting a GUI client depending on your OS:

Linux: DBeaver
Windows: HeidiSQL
Mac: No idea

**Comment by derrickmehaffy** [comment] 2019-06-19 11:25
Also @Gribbs I removed a link to your DB file as it contains your email and an encrypted form of your password. Never a good idea to share that stuff on the internet as it allows for someone to offline try and crack the password.

**Comment by Gribbs** [comment] 2019-06-19 11:41
thanks @derrickmehaffy 
It worries me that a small mistake like changing the capitalization of a word in the admin ui completely destroys the application upon save and you have to go hunting in a wall of SQL to find the cause of the issue. I think a history should be built into the platform so you can revert to the last save or something?

**Comment by derrickmehaffy** [comment] 2019-06-19 11:45
It's a well known issue that only happens on SQLite which shouldn't even be used in production so it wasn't deemed as a priority fix. It stems from the fact that SQLite doesn't have a proper `ALTER TABLE` command which can cause conflicts on renaming columns (aka alterting them) when that table has data in it.

Basically what has to be done is it makes a copy of the model, copies the data with the rename change, deletes the old one and renames the table.

With data in the mix, it's possible to have a duplicate if the old table wasn't deleted first.

**Comment by derrickmehaffy** [comment] 2019-06-19 11:46
Your best bet is to preform the column rename yourself manually, or delete the table and let Strapi recreate it.

Either way marking this as closed for now, as the issue is well documented.

**Closed by derrickmehaffy** 2019-06-19 11:46 UTC

**Comment by Gribbs** [comment] 2019-06-19 12:42
thanks for the advice @derrickmehaffy  
Cleaned it up successfully using DB Browser for SQLite

**Comment by scottnorland** [comment] 2019-12-16 20:39
This can be solved locally by modifying the database settings file.  Ex: api/product/models/Product.settings.json

**Comment by jassehomar** [comment] 2020-01-24 13:10
Thanks :+1: @scottnorland this works, but it just takes you back to the original column name.

**Comment by chris-fran** [comment] 2020-03-09 23:11
Where is the SQLite file located?

**Comment by lauriejim** [comment] 2020-03-10 14:37
Hello @chris-fran , if you check your `config/environment/database.json` file you will find the location of the database.
in `.tmp/data.db`

**Comment by christopher4lis** [comment] 2020-06-19 14:29
Although this issue is well documented, I think it's good to re-open it. This is only providing a negative experience for those who just want to change the label of their field—a simple change like that shouldn't require the user to look up documentation and figure out what went wrong, it should just work.

**Comment by derrickmehaffy** [comment] 2020-06-21 08:49
@christopher4lis it all comes down to https://github.com/strapi/strapi/issues/1114 locking this as it's a duplicate
