### ISSUE TITLE
Change API prefix break admin / public files

### ISSUE THREAD

**Issue by demobo-com** [strapi/strapi#1323] opened 2018-06-06 02:36 UTC
**Informations**
- **Node.js version**: v9.10.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: mongodb
- **Operating system**: Mac

**What is the current behavior?**
changed config/environments/development/request.json
"router": {     "prefix": "v1"   }
this results /v1/xxx api not found
{
statusCode: 404,
error: "Not Found",
message: "Not Found"
}

**Steps to reproduce the problem**
Without prefix changes, /xxx api is working

**What is the expected behavior?**

**Suggested solutions**

**Comment by lauriejim** [comment] 2018-06-06 18:38
Hello @demobo-com !
If you follow the documentation exemple ([here](https://strapi.io/documentation/configurations/configurations.html)) we set `/v1`.

In your case you set `v1`. You have to add `/`.

**Comment by demobo-com** [comment] 2018-06-06 22:46
After changing the prefix to "/v1", the public folder is no longer accessible

**Comment by derrickmehaffy** [comment] 2018-07-05 18:03
I can confirm this issue still exist in 12.6 using the following in `config/environments/development/request.json`

```json
{
  "session": {
    "enabled": true,
    "client": "cookie",
    "key": "strapi.sid",
    "prefix": "strapi:sess:",
    "secretKeys": ["mySecretKey1", "mySecretKey2"],
    "httpOnly": true,
    "maxAge": 86400000,
    "overwrite": true,
    "signed": false,
    "rolling": false
  },
  "logger": {
    "level": "debug",
    "exposeInContext": true,
    "requests": true
  },
  "parser": {
    "enabled": true,
    "multipart": true
  },
  "router": {
    "prefix": "/v2"
  }
}
```

Results in the following:

localhost:1337/

![image](https://user-images.githubusercontent.com/8593673/42339700-9ba3fd48-8042-11e8-8689-431060448640.png)

localhost:1337/admin

![image](https://user-images.githubusercontent.com/8593673/42339721-a71dc74e-8042-11e8-9fec-7fef0b080633.png)

localhost:1337/v2/

Technically this is loading, but its loading in the wrong spot :stuck_out_tongue: hence the failed images and such
![image](https://user-images.githubusercontent.com/8593673/42339749-bc61396a-8042-11e8-9cb6-25f6a40f49ff.png)

localhost:1337/v2/admin

Based on the errors it seems its still trying to load the resources at `localhost:1337/admin/main.js` and `localhost:1337/admin/vendor.dll.js` so the admin index.html isn't being rebuilt.
![image](https://user-images.githubusercontent.com/8593673/42339792-e0d25b1c-8042-11e8-80a4-51337d4889eb.png)

**Comment by derrickmehaffy** [comment] 2018-07-05 18:05
Changing the prefix for requests should change the restAPI model requests, but the /public and /admin should remain the same. IE `localhost:1337/admin` and `localhost:1337/v2/modelTest`

**Comment by manishsg** [comment] 2018-07-09 05:20
I am facing the same issue. Please confirm if this will be fixed soon. We have changed the api prefix to /scs/. This breaks the public & admin panel.

Please help.

**Comment by storm1er** [comment] 2018-07-14 10:20
Same problem here.

@manishsg You can manually edit every route/path in `/api/*/config/routes.json` if you can't wait this issue to be resolved ;)

**Comment by manishsg** [comment] 2018-07-14 20:46
the api routes can be fixed by the change. But the admin panel and public path are major issue.

**Comment by Kinark** [comment] 2018-08-28 00:14
Still happening on the latest alpha version (3.0.0-alpha.14)

**Comment by Aurelsicoko** [comment] 2018-09-13 09:04
@nicroto You're right! The `prefix` should be used to prefix your API `http://localhost:1337/your-prefix/` instead of exposing the API at `http://localhost:1337/`. It shouldn't be used to manage the versioning of your API.

**Closed** 2018-10-02 14:52 UTC
Labels: priority: medium, status: confirmed, type: bug 🐛

**Comment by bel0v** [comment] 2019-01-04 22:06
so if I want to prefix my API, is the todays solution go and change all the api/**/config routes by hand?..

**Comment by derrickmehaffy** [comment] 2019-01-04 22:07
@bel0v you can try it and find out? right now there is no "solution" as it wasn't deemed critical for the moment. Versioning is on the roadmap https://portal.productboard.com/strapi/c/17-versioning

**Comment by x-yuri** [comment] 2019-09-23 07:23
Workaround:

`config/environments/production/custom.json`:
```json
{
  "api-prefix": {
    "enabled": true
  }
}
```

`config/middleware.json`:
```json
...
    "order": [
      "public", "api-prefix"
    ],
...
```

`middlewares/api-prefix/index.js`
```js
module.exports = strapi => {
  const composeEndpoint = require('strapi/lib/middlewares/router/utils/composeEndpoint')(strapi);
  return {
    initialize() {
      strapi.config.routes.forEach(value => {
        value.path = '/api' + value.path;
        composeEndpoint(value, null, strapi.router);
      });
    },
  };
};
```

**Comment by StevenWung** [comment] 2019-10-15 03:31
Is there any available official fix ?

**Comment by derrickmehaffy** [comment] 2019-10-15 05:21
@StevenWung Not not as of right now, Strapi themselves have removed the options for prefixing as it was causing issues with the adminUI. It will likely be looked into at a later date when versioning is added but no eta.

**Comment by jmchza** [comment] 2019-10-20 05:49
Hey @derrickmehaffy hold on on disabling the api prefix, I have an enhancement to be put into a PR today that will allow a bit more flexibility to play with when it comes to deploy the admin console.

for the rest, I would say the key is separating the admin console and deploying it into a NGINX or APACHE server. My suggestion is a NGINX.

I will do my best to write an article today for this, but basically you can build your admin console on a root level  as indicated here: 

> https://strapi.io/documentation/3.0.0-beta.x/admin-panel/deploy.html#deploy-the-entire-project-on-the-same-server

to be served by a NGINX

Example: 
"admin": {
    "path": "/" 
  } 

Once you've got that in place you have more alternatives to play with within NGINX re: paths configurations.
Watch for the next PR related to strapi-provider-upload-local plugin

Cheers.

**Comment by exlineo** [comment] 2020-02-07 12:17
In my case, I've found an ugly hack changing manualy builded files : 
- set up prefix > request.json, adding
```
"router": {
    "prefix": "/vinci/"
  }
```
- build admin files
- change index.html to add the prefix on js files (src="/myprefix/admin...")
- in runtime transpiled js file, add prefix before admin (a.p="/myprefix/admin/",)

Everything seems to be working find in admin...
A very bad hacking trip but it works.

**Comment by anmol5varma** [comment] 2021-01-06 06:40
Any updates on API versioning??
I have a lot of collection types, editing every endpoint might not be possible.
