### ISSUE TITLE
Endless unknown debug POST /graphql

### ISSUE THREAD

**Issue by laportem** [strapi/strapi#6420] opened 2020-05-28 18:37 UTC
**Describe the bug**
I may have missed a setting somewhere but I just installed to Strapi 3.0.0 using docker and I am seeing endless “debug POST /graphql” on the console.

There are no external app or services using the graphql
Looks like it something internally to strapi causing the endless POST

Are there any internal setting or job that could be make these graphql queries/mutations?

**Steps to reproduce the behavior**

1. Install and run the latest Strapi (3.0.0) using docker-compose

**Expected behavior**
Should not be seeing endless graphql queries/mutations made to strapi

**System**

- Node.js version: 12.13.0
- NPM version: (YARN) 1.19.1
- Strapi version: 3.0.0
- Database: Postgres:latest
- Operating system: Ubuntu 20.04 LTS (Focal Fossa)

**Comment by BowlingX** [comment] 2020-05-29 13:13
Hi :).
I would say this is not a bug. It's caused by the playground refetching the schema in the background periodically.
I just freshly installed the 3.0.1 strapi version and can reproduce it this way.

**Comment by alexandrebodin** [comment] 2020-05-29 13:39
Hi, indeed this is just the playground that pulls the schema regularly not a bug :) Closing

**Closed by alexandrebodin** 2020-05-29 13:39 UTC
