### ISSUE TITLE
[3.2.1] ReferenceError: describe is not defined 

### ISSUE THREAD

**Issue by periabyte** [strapi/strapi#8253] opened 2020-10-08 20:34 UTC
**Describe the bug**
My previous strapi version was 3.1.1 and I'm upgrading to 3.2.0, however when I tried to start the application after the update I get the error: `ReferenceError: describe is not defined`

I don't know why the test file `strapi-plugin-content-manager/config/policies/__tests__/has-draft-and-publish.test.js` affects the start up process

**Steps to reproduce the behavior**

1. Upgrade Strapi from 3.1.1. to 3.2.0
2. Run `strapi develop`

**Expected behavior**
Application should start properly

**Error**
```
ReferenceError: describe is not defined
    at Object.<anonymous> (project_folder/node_modules/strapi-plugin-content-manager/config/policies/__tests__/has-draft-and-publish.test.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at module.exports (project_folder/node_modules/strapi/lib/load/require-file-parse.js:12:10)
    at loadFiles (project_folder/node_modules/strapi/lib/load/load-files.js:31:17)
    at async loadPlugins (project_folder/node_modules/strapi/lib/core/load-plugins.js:55:38)
    at async module.exports (project_folder/node_modules/strapi/lib/core/load-plugins.js:12:19)
    at async Promise.all (index 2)
    at async module.exports (project_folder/node_modules/strapi/lib/core/load-modules.js:24:76)
    at async Strapi.load (project_folder/node_modules/strapi/lib/Strapi.js:267:21)
    at async Strapi.start (project_folder/node_modules/strapi/lib/Strapi.js:146:9)
```
**System**

- Node.js version: 12.16.1
- NPM version:
- Strapi version: 3.2.1
- Database: mongodb
- Operating system: MacOS

**Comment by derrickmehaffy** [comment] 2020-10-08 20:54
That should not be happening O_o though I am unable to reproduce this, can you give a link to your project code?

**Comment by periabyte** [comment] 2020-10-08 21:12
I'll try to recreate it in a public repo then link it again here

**Comment by derrickmehaffy** [comment] 2020-10-08 21:37
Thank you :hugs:

**Comment by derrickmehaffy** [comment] 2020-10-15 15:40
As we have received no new information, marking as closed
@periabyte if you are able to provide some reproduction steps we can reopen.

**Closed by derrickmehaffy** 2020-10-15 15:40 UTC
Labels: status: can't reproduce

**Comment by quitequinn** [comment] 2020-10-23 18:56
Were you able to solve this @periabyte ?

**Comment by jensvlierop** [comment] 2020-11-18 11:15
Is your database server running? That caused the same error for me.

**Comment by savyir** [comment] 2020-12-02 15:15
I had this problem 
I just removed node_modules, upgraded node version from 13 to 14 and reinstalled packages using yarn and now it works.

**Comment by portatlas** [comment] 2021-02-18 10:26
I had my test directory inside `/strapi/api/*` moving my tests to `/strapi/tests` appears to resolve the problem for me.
