### ISSUE TITLE
Custom Condition for Admin User Page 

### ISSUE THREAD

**Issue by raphaeldas** [strapi/strapi#16561] opened 2023-04-28 13:14 UTC
### Required System information

- Node.js version: 16.19.1
- NPM version: 9.6.4
- Strapi version: 4.9.1
- Database: Postgres 14.6
- Operating system: Alpine Linux Docker
- Is your project Javascript or Typescript: JS

### Describe the bug

As described in issue #16554 I am trying to define a custom codition for a role, that can manage only a subset of users with the same email domain. I have the use case were we mange the CMS for our client but the client has also accounts with lower permissions. They should add and manage their own set of users, so i want so filter out our own accounts.

### Code snippets
For testing I used the _$eq_ condition. Later it would be really cool to use the $regex condtion (or $endsWith / $containsi that i can use with content-types). This is my current custom condition:

``` javascript
  {
    displayName: 'Only Users with [Client] Mail Addresses',
    name: 'endress-email',
    handler: () => ({
      'email': {
        $eq: 'user@some-domain.com'
        }
      }
    )
  }
```
Unfortunetly this condition has no inpact when accessing the admin user page with the user with the specified role. 

### Expected behavior

Custom Conditions should also work on Admin Panels in general or at least on the User Page. 

### Screenshots

![image](https://user-images.githubusercontent.com/15084829/235156067-19671e10-8683-4c21-aef0-0ea991467f9f.png)

Thanks for your efforts!

**Comment by Boegie19** [comment] 2023-04-28 16:57
@raphaeldas is the same root cause as https://github.com/strapi/strapi/issues/16554 so I will close this ticket and keep the other one open 

this issue is most likely the filtering done on the api layer what would effect both issues

**Closed by Boegie19** 2023-04-28 16:57 UTC
