### ISSUE TITLE
Error deleting plugin from Admin Panel

### ISSUE THREAD

**Issue by Moomboh** [strapi/strapi#727] opened 2018-03-02 18:46 UTC
**Node.js version**: 8.9.4
**npm version**: 5.6.0
**Strapi version**: 3.0.0-alpha.10.3
**Operating system**: Ubuntu 17.10

**Do you want to request a *feature* or report a *bug*?**
Bug report.

**What is the current behavior?**
Deleting a plugin on `/admin/list-plugins` throws an error:
```
INFO (10577 on xxx-notebook): Uninstalling analytics...
module.js:540
    throw err;
    ^

Error: Cannot find module '/home/xxx/projects/strapi-bug-test/node_modules/strapi/bin/strapi'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
DEBUG (10577 on xxx-notebook): DELETE /admin/plugins/uninstall/analytics (130 ms)
```

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Install strapi via `npm install strapi@alpha -g`.
Create a new strapi project `strapi new project`.
Start strapi `cd project`, `strapi start`.
Visit http://localhost:1337/admin create admin user and visit http://localhost:1337/admin/list-plugins/.
Try to delete plugin by clicking the bin icon in the list.

**What is the expected behavior?**
Uninstall the plugin without throwing an error.

It seems that the `strapi new` command doesn't install the dependencies correctly in the project folder. Running `npm install` in the project solves the issue. 
Maybe related to #511?

**Comment by lauriejim** [comment] 2018-03-12 17:42
Are you in dev mode ?
I can't reproduce it on the last version of Strapi.

**Comment by forsetius** [comment] 2018-03-12 22:25
Same on:
Node.js version: 9.8.0
npm version: 5.6.0
Strapi version: 3.0.0-alpha.11.1
Operating system: Ubuntu 16.04

**Comment by lauriejim** [comment] 2018-03-13 10:31
Can you tell me if the plugin is successfully deleted ?
Hum both of you are on ubuntu, it's maybe coming from your OS.

Can you help me with try to find here https://github.com/strapi/strapi/blob/master/packages/strapi-admin/controllers/Admin.js#L54 where the function break on you computer.

**Comment by Moomboh** [comment] 2018-03-13 12:55
The problem is that the strapi package is not installed locally in the `node_modules` folder by `strapi new`. I think this is because of the way `strapi new` installes dependencies: [/strapi-generate-new/lib/after.js#L44](https://github.com/strapi/strapi/blob/master/packages/strapi-generate-new/lib/after.js#L44) here it checks if a dependency is already installed with [get-installed-path](https://www.npmjs.com/package/get-installed-path) since strapi is already installed globally it won't install it locally. 
So it crashes at [strapi-admin/controllers/Admin.js#L61](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/controllers/Admin.js#L61) because `strapiBin` is reffering to the local path in `node_modules` as of [Admin.js#L56](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/controllers/Admin.js#L56).
Note that `npm run strapi` and `npm run postinstall` will also fail since they also look in the `node_modules folder for the strapi bin.

**Comment by Moomboh** [comment] 2018-03-13 14:11
Just tried it out in a docker container based on the `node:alpine` image and everything worked as expexted. Probably a problem specific to ubuntu. I'll try to recreate the issue with docker.

**Comment by lauriejim** [comment] 2018-03-15 14:01
strapiBin is just require to execute `strapi uninstall ...` if strapi is not installed globally.
In your case can you test with a try catch the require of strapiBin and tell me what is the error in the catch.

**Comment by lauriejim** [comment] 2018-03-27 18:07
@Moomboh Can you give me an update about my last message please.

**Comment by lauriejim** [comment] 2018-04-08 13:14
I close this issue. This is the same issue as https://github.com/strapi/strapi/issues/785 but for uninstall plugin.

**Closed by lauriejim** 2018-04-08 13:14 UTC
Labels: priority: low, status: can't reproduce 🙃, type: bug 🐛
