### ISSUE TITLE
The document ID should have been the same for both translations

### ISSUE THREAD

**Issue by vinda2401** [strapi/strapi#21037] opened 2024-08-21 11:24 UTC
### Required System information

Node.js version: 18+
NPM version: 18.6
Strapi version: 5.0.0-rc.8
Plugin version:
Database: mysql
Operating system: Ubuntu 22.04.4 LTS

### Describe the bug

After following migration methods from v4 to v5, we discovered that the translations were not properly linked.

According to our understanding, the document id for both versions should be the same, yet the migrated records have different document ids for each entry. 
Thus, the translations are not correctly connected.

### Steps to reproduce the behavior

Prerequisite: Should have data in strapi v4 which is multilingual. Run though the migration process and upgrade to strapi v5. 

1. Open a collection containing multilingual data.
2. Click to open a record in editing mode. Attempt to swap between locales using the top right dropdown. You will notice an error.
3. Note down the document ID for this record.
4. Return to the collection’s listing page.
5. Filter data for another locale.
6. Choose the translated version of the record you opened before. Click to open it.
7. Write down the document ID.

In this scenario, the document IDs are different, hence the translations are not linked.

### Expected behavior

Both entries should have the same document ID, and switching between translations should be possible via a dropdown menu.

**Comment by derrickmehaffy** [comment] 2024-08-21 11:28
I've confirmed this issue and already informed our engineering team via Slack ([Internal Thread for Engineers](https://strapihq.slack.com/archives/C02CB44NJMV/p1724238274195689))

**Comment by derrickmehaffy** [comment] 2024-08-21 11:32
Source of the issue (I think) is here, since it's not finding the related IDs it's creating a new document ID:

https://github.com/strapi/strapi/blob/a2eac9d89132daee95ef7f194ed97e3b88b3650c/packages/core/database/src/migrations/internal-migrations/5.0.0-02-document-id.ts#L96-L116

**Comment by derrickmehaffy** [comment] 2024-08-21 11:33
I think the issue is simple in that the wrong table name is being used in the join it should be:

```js
identifiers.getJoinTableName(meta.tableName, `localization_links`),
```

![image](https://github.com/user-attachments/assets/edb303a2-886b-4469-a130-08368cfa2a56)

**Comment by derrickmehaffy** [comment] 2024-08-23 21:01
fixed by: https://github.com/strapi/strapi/pull/21050

**Closed by derrickmehaffy** 2024-08-23 21:01 UTC
Labels: issue: bug, severity: critical, status: confirmed, source: core:database, version: 5
