### ISSUE TITLE
Slug field association with sub component

### ISSUE THREAD

**Issue by robinComa** [strapi/strapi#7434] opened 2020-08-12 08:38 UTC
**Describe the bug**

Slug field association with sub component  doesn't work

**Steps to reproduce the behavior**

1. Create componant SEO with title as a String
2. Create a collection Blog
3. Add a field seo as Seo componant on Blog
4. Add a slug as UID field on Blog
5. Link the slug field with seo.title text to autogenerate the slug => doesn't work

**Expected behavior**
Associated field from component should be possible, ex slug <=> seo.title

**Screenshots**
![image](https://user-images.githubusercontent.com/2729768/89993917-b266d200-dc87-11ea-8727-c27ffe2b3419.png)
![image](https://user-images.githubusercontent.com/2729768/89993984-ca3e5600-dc87-11ea-9c4d-340c09194969.png)

**Code snippets**
n/a

**System**

- Node.js version: 12.4.0
- NPM version: 6.14.4
- Strapi version: 3.1.3
- Database: MongoDB
- Operating system: Mac OS

**Additional context**
n/a

**Comment by derrickmehaffy** [comment] 2020-08-12 15:52
@alexandrebodin correct me if I'm wrong but this isn't currently possible due to how components are handled in the backend right? This would be a feature request?

**Comment by alexandrebodin** [comment] 2020-08-12 17:50
Yes this isn't possible. components are separate in the db an have relation to their parent content types. There wouldn't be a good way to make the uid unique on the content type level inside a component. I don't think there is any way we will do that with component. I think we will need to introduce a new kind of fields (e.g nestedFields, that will have a component strucutre but be set inside the content type itself) at some point to handle this.

**Comment by derrickmehaffy** [comment] 2020-08-13 22:06
@robinComa as confirmed by Alex, I would suggest you find an alternative for this use-case such as using the [model lifecycle](https://strapi.io/documentation/v3.x/concepts/models.html#lifecycle-hooks) but you will likely want to move the title out of the component instead.

I'm going to mark this as closed as this isn't directly a bug with Strapi but simply that the feature doesn't exist with no real workaround to make what you are asking for possible at the moment.

**Comment by alexandrebodin** [comment] 2020-08-14 06:46
Actually I'm going to reopen as I think I misread the post. As long as the uid field is declared at the root of the content-type I think we could pretty easily allow the targetAttribute to be a component field.  @derrickmehaffy this should be made a feature request :)

**Comment by robinComa** [comment] 2020-08-19 13:10
Thanks :-)

**Comment by robinComa** [comment] 2020-08-19 13:10
Thanks :-)

**Comment by derrickmehaffy** [comment] 2022-05-19 22:44
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/customization/p/slug-field-association-with-sub-component
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!

**Closed by derrickmehaffy** 2022-05-19 22:44 UTC
Labels: issue: feature request, severity: low
