### ISSUE TITLE
Add Image into nested components

### ISSUE THREAD

**Issue by nisharg007** [strapi/strapi#10478] opened 2021-06-14 14:32 UTC
## Bug report

Hello, I am very new in `strapi` and I don't know, how strapi works internally in backend but I have one hosted strapi given by the client and I am working on it.

I have problem to upload image into components component

like

I have one collection called `order`, on that I have one component called `opc` and on that I have one component called `director` and on that I have one field called 'image', I want to upload my image on that and also want to link that.

```
order > opc > director ( want to upload here in image field )
```

![image](https://user-images.githubusercontent.com/56869722/121908544-bd2c4080-cd4a-11eb-9374-182a01c707ac.png)

## Code

```javascript
const fileData = new FormData();
fileData.append(
  `files`,
  value,
  `${new Date().getTime()}_${key}_${type[1]}`
);
// fileData.append("ref", "order");
fileData.append("ref", "order.opc.director");
// fileData.append(`refId`, order);
fileData.append(`refId`, order.opc.director.id);
fileData.append(`field`, 'image');
fileData.append(
  "fileInfo",
  JSON.stringify({ alternativeText: value.name })
);
const res = await axios({
  method: "POST",
  url: "https://api.example.com/upload",
  headers: {
    Authorization: `Bearer ${token}`,
    "Content-type": "multipart/form-data",
  },
  data: fileData,
});
```

is it right code? or I am doing something wrong here?

### System

- Node.js version: 14.17.0
- NPM version: 7.11.2
- Operating system:  Ubuntu 20.04

can someone please help me to add image on that component?

**Comment by kasonde** [comment] 2021-06-15 07:47
Hi @nisharg007 thanks for the question. I'm closing this here however since it's not an issue but a question that is absolutely perfect for our [Community Forum](https://forum.strapi.io). Once you post it there, I and other community members will be happy to share our ideas.

**Closed by kasonde** 2021-06-15 07:47 UTC

**Comment by NishargShah** [comment] 2021-06-15 16:56
@kasonde I know this is not an issue but can you please help me with that, so I can solve my problem.

**Comment by nisharg007** [comment] 2021-06-16 17:05
@kasonde I know this is not an issue but can you please help me with that, so I can solve my problem.

**Comment by derrickmehaffy** [comment] 2021-06-16 17:19
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/add-image-into-nested-components/5698/1

**Comment by nisharg007** [comment] 2021-06-18 06:46
@derrickmehaffy @kasonde No reply till now, can anyone answer?

**Comment by kasonde** [comment] 2021-06-18 07:35
Hi @nisharg007. I've just joined the conversation on the Forum regarding your issue now.

**Comment by nisharg007** [comment] 2021-06-18 17:34
@kasonde 

[quote="nisharg007, post:1, topic:5698"]
`order.opc.director`
[/quote]

I am getting these errors when performing the request

**Code**

```
fileData.append(
`files`,
value[i],
`${new Date().getTime()}_${key}_${type[1]}`
);
fileData.append("ref", "order.opc.director");
fileData.append(`refId`, order.opc.director.id);
fileData.append(`field`, 'image');
```

**Error**

```
12|strapi-dev  | [2021-06-18T17:27:22.003Z] error TypeError: Cannot read property 'associations' of undefined
```

If I am trying to follow the docs as suggested here https://strapi.io/documentation/developer-docs/latest/development/plugins/upload.html#upload-file-during-entry-creation

> TIP
>
>If you want to upload files for a component, you will have to specify the index of the item you want to add the file to. Example `files.my_component_name[the_index].attribute_name`

Is it required to specify index on **Single Component** ( files.opc[0].director[0].image )

**Code**

```
fileData.append(
`files.opc[0].director[0].image`,
value[i],
`${new Date().getTime()}_${key}_${type[1]}`
);
fileData.append("ref", "order.opc.director");
fileData.append(`refId`, order.opc.director.id);
fileData.append(`field`, 'image');
```

**Error**

```
{"statusCode":400,"error":"Bad Request","message":"Bad Request","data":{"errors":[{"id":"Upload.status.empty","message":"Files are empty"}]}}
```

Please help me on that, I do not understand how I figure this out

**Comment by derrickmehaffy** [comment] 2021-06-18 18:06
> @derrickmehaffy @kasonde No reply till now in forums, can anyone answer?

Replies on community help threads happen on a "best effort basis" we cannot always respond to every issue. If you require an SLA based help (time sensitive) we have enterprise plans that include those options starting from our Silver (limited) to our Gold (has SLAs).

If immediate help is what you need, I would suggest reviewing our Enterprising pricing: https://strapi.io/pricing-self-hosted

Locking thread as it was mentioned this is not a bug report or feature request, additional issues that violate our Code of Conduct or Contribution guide may result in a temporary ban from our GitHub repos.

Code of Conduct: https://forum.strapi.io/faq
Contribution Guide: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue
