### ISSUE TITLE
"contentType field cannot have keys not specified in the object shape" when deleting attribute in content builder

### ISSUE THREAD

**Issue by amitav13** [strapi/strapi#8324] opened 2020-10-14 03:24 UTC
**Describe the bug**
Can't delete a string attrribute from a collection type in the admin panel. 
For the request type `PUT /content-type-builder/content-types/application::product.product`, I'm getting back a `400` response with the error message body  as:
```json
error: {
    contentType: [
      'contentType field cannot have keys not specified in the object shape'
    ]
  }
```
The attribute I'm trying to delete is a simple string type:
```
"pattern": {
      "type": "string"
},
```
in my `product` collection type. What might be the source of error is the fact that I also already have a collection type called `pattern`.

***Update***: This error is actually more widespread than I thought. I can no longer perform updates to my `product` type (like adding a relation to another collection type), nor add in any new field at all through the admin panel, essentially bricking the entire plugin. Same error as above in both cases. I've also tried reverting to strapi `3.2.1`, my last working version, to no avail.

**Steps to reproduce the behavior**

1. Via the admin panel, navigate to the content-types builder and delete a `text` attribute in a collection type.
2. Click "save". "Error occurred" shows.

**Expected behavior**
The attribute to be deleted successfully.

**System**

- Node.js version: v12.16.3
- NPM version: 6.14.4
- Strapi version: 3.2.3
- Database: Postgres
- Operating system: mac OS 10.15.6

**Additional context**
~~I don't believe this bug existed in previous versions. I just updated from 3.2.1 today, might be related to that.~~

**Comment by alexandrebodin** [comment] 2020-10-14 12:10
Hi @amitav13 This error means you most likely have set a property in your json file manually and the content manager doesn't know about it :) Can you share your model.settings.json file please ?

**Comment by amitav13** [comment] 2020-10-14 12:16
`product.settings.json`:
```json
{
  "kind": "collectionType",
  "collectionName": "products",
  "info": {
    "name": "Product"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "populateCreatorFields": true
  },
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
    "short_description": {
      "type": "richtext"
    },
    "description": {
      "type": "richtext"
    },
    "deleted": {
      "type": "boolean",
      "default": false,
      "private": true,
      "required": true
    },
    "rubric_points": {
      "type": "decimal"
    },
    "size": {
      "model": "size"
    },
    "style": {
      "model": "style"
    },
    "colour": {
      "model": "colour"
    },
    "occasion": {
      "model": "occasion"
    },
    "user_segment": {
      "model": "user-segment"
    },
    "styling": {
      "model": "styling"
    },
    "brand": {
      "model": "brand"
    },
    "condition": {
      "model": "condition"
    },
    "made_in": {
      "model": "made-in"
    },
    "feels_like": {
      "model": "feels-like"
    },
    "category": {
      "model": "category",
      "via": "products"
    },
    "climate": {
      "type": "string"
    },
    "stretch": {
      "type": "string"
    },
    "evaluated_points": {
      "type": "decimal"
    },
    "measurements": {
      "type": "component",
      "repeatable": false,
      "component": "product.measurements"
    },
    "material": {
      "model": "material"
    },
    "seller": {
      "plugin": "users-permissions",
      "model": "user"
    },
    "garment_story": {
      "type": "component",
      "repeatable": false,
      "component": "product.garment-story"
    },
    "images": {
      "collection": "file",
      "via": "related",
      "allowedTypes": ["images"],
      "plugin": "upload",
      "required": false
    },
    "new_with_tag": {
      "type": "boolean",
      "default": false,
      "required": false
    },
    "ximilar_complete_tags": {
      "type": "json",
      "private": false
    },
    "tags": {
      "type": "json"
    }
  }
}
```

**Comment by amitav13** [comment] 2020-10-15 18:08
Nope doesn't work in either case.

**Comment by alexandrebodin** [comment] 2020-10-16 12:26
Ok So your model has really a lot of relation would you mind sharing your project or just one with the models copied so I can have the full structure to reproduce ? :)

**Comment by opllama-kun** [comment] 2020-10-21 15:08
not sure if this is the same situation as yours but just putting this out there, i had the same issue after updating Strapi from 3.1.4 to 3.2.4, i had the same error when creating fields for single/collection types but not for components, all i had to do was rebuild strapi and it was solved tho.

**Comment by alexandrebodin** [comment] 2020-10-21 16:27
@amitav13 @opllama-kun makes a good point, did you rebuild your admin panel after upgrading ?

**Comment by ivanji** [comment] 2020-10-30 20:51
I'm using the latest version 3.2.5 and I'm also getting this error. It's impossible now to edit the content type - I'm always getting the same error. I haven't manually updated the model.settings file but I do have a few relations with other models.

I'm regretting upgrading to these latest versions. I was on 3.1 and nothing like that was happening.

**Comment by ivanji** [comment] 2020-10-30 21:48
In case you need to see the models: https://codesandbox.io/s/bold-poincare-2guq4?file=/strapi-models/listing.settings.json - there all there under the same folder. Every time I try to save listing I fail - haven't tried with the rests as I dont need to modify those.

**Comment by alexandrebodin** [comment] 2020-11-02 09:39
Did you rebuild your admin panel ?

**Comment by ivanji** [comment] 2020-11-02 14:20
Yes, I did. Multiple times

**Comment by derrickmehaffy** [comment] 2020-11-10 08:17
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/does-anyone-know-what-this-error-means-when-saving-a-new-field-to-a-content-type/1041/4

**Comment by IPWright83** [comment] 2020-11-10 08:22
So I'm the author of the above thread in the forum, and am having the same error. I've got a denormalised type so I don't have any relationships in my model. I've tried a clean/build again which also doesn't fix the problem. 

I have however made a single direct change in my `model.settings.json` file because I needed a custom index so followed the instructions given https://forum.strapi.io/t/best-approaching-for-adding-custom-indexes/888/6. This is actually the field that is throwing an error underneath (though not one I'm editing).

> contentType.attributes.location: ["contentType.attributes.location field cannot have keys not specified in the object shape"]

**Comment by alexandrebodin** [comment] 2020-11-10 08:40
We have someone making a PR for this then but we asked for changes and no responses since then. https://github.com/strapi/strapi/pull/8022

**Comment by eighteenson** [comment] 2020-11-12 09:09
I also have the issue after updating the strapi from 3.1.3 to 3.2.5 or even 3.3.2
I can create a new content type with no issue. Until we want to add a new field for an existing content type and update it.
The error "contentType field cannot have keys not specified in the object shape" occurs.

The workaround for me is checking if there are two folders "content-manger" and "content-type-builder" under your project/extension/ folder. 
Delete both folder, and run "yarn build --clean" to rebuild the project..everything works fine for me

**Comment by burn-c** [comment] 2021-04-14 18:32
I have a project in v3.0.4, I was unable to solve it with the tip of @eighteenson .

Does anyone have any workaround for the problem ?
Can anyone tell me if this happens in v3.5.4 ?

**Comment by derrickmehaffy** [comment] 2022-07-13 20:50
Should be fixed in v4

**Closed by derrickmehaffy** 2022-07-13 20:50 UTC
Labels: issue: bug, source: core:content-type-builder
