### ISSUE TITLE
GraphQL query not working

### ISSUE THREAD

**Issue by laportem** [strapi/strapi#2816] opened 2019-02-12 12:14 UTC
**Informations**
- **Node.js version**: 10.1.0
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.23.1
- **Database**: mongodb v4.0.0
- **Operating system**:  Ubuntu 1404
- **(Optional) Link to your Project**: 

**What is the current behavior?**
I am test driving Strapi for a possible project. 
I have installed Strapi, add graphql plugin, create a content type enable public permissions and add some data.
If I query using REST I get the data as expected
`http://192.168.33.10:1337/topics`

However, when i tried the graphql query i received errors

`
http://192.168.33.10:1337/graphql
query {
  topics {
    name
    code
  }
}
`

I get the following error messages back

`
{
  "errors": [
    {
      "message": "Assignment to constant variable.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "topics"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Assignment to constant variable.",
            "    at getQueryParams (/home/vagrant/strapifrm/node_modules/strapi-hook-mongoose/lib/index.js:519:18)",
            "    at _.forEach (/home/vagrant/strapifrm/node_modules/strapi/node_modules/strapi-utils/lib/models.js:481:18)",
            "    at /home/vagrant/strapifrm/node_modules/lodash/lodash.js:4911:15",
            "    at baseForOwn (/home/vagrant/strapifrm/node_modules/lodash/lodash.js:2996:24)",
            "    at /home/vagrant/strapifrm/node_modules/lodash/lodash.js:4880:18",
            "    at Function.forEach (/home/vagrant/strapifrm/node_modules/lodash/lodash.js:9344:14)",
            "    at Object.convertParams (/home/vagrant/strapifrm/node_modules/strapi/node_modules/strapi-utils/lib/models.js:455:7)",
            "    at Object.fetchAll (/home/vagrant/strapifrm/api/topics/services/Topics.js:22:41)",
            "    at find (/home/vagrant/strapifrm/api/topics/controllers/Topics.js:21:37)",
            "    at /home/vagrant/strapifrm/plugins/graphql/services/Query.js:279:41"
          ]
        }
      }
    }
  ],
  "data": {
    "topics": null
  }
}
`

**Steps to reproduce the problem**
Use the playground to fire a graphql query

**What is the expected behavior?**

I should be able to use graphql query

**Suggested solutions**

**Comment by lauriejim** [comment] 2019-02-12 17:54
Hello @laportem !
Sorry for this trouble.

Can you give me your models please.

**Comment by laportem** [comment] 2019-02-12 21:36
I created the model using the admin UI. Very simple one. I have not manually touch the files. Here is one of them but i get the same problems for all models:
As i mentioned early, REST works; Graphql don't

`{
  "connection": "default",
  "collectionName": "topics",
  "info": {
    "name": "topics",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "code": {
      "default": "",
      "type": "string",
      "required": true,
      "unique": true
    },
    "name": {
      "default": "",
      "type": "string"
    },
    "slug": {
      "default": "",
      "type": "string"
    }
  }
}`

**Comment by kamalbennani** [comment] 2019-02-12 22:45
@lauriejim if I'm not mistaken this bug impact all the GraphQL queries without a filter, the problem is that we're using const in this line: https://github.com/strapi/strapi/blob/master/packages/strapi-hook-mongoose/lib/index.js#L511 but we're assigning it to undefined in this line: https://github.com/strapi/strapi/blob/master/packages/strapi-hook-mongoose/lib/index.js#L575.
The thing that I don't understand how the linter didn't catch this!

**Comment by lauriejim** [comment] 2019-02-13 18:23
Ho yes good catch! 

@kamalbennani Did you work on it in your PR ?

**Comment by kamalbennani** [comment] 2019-02-14 08:24
I can fix it in my PR but is it neccessary because we'll no longer be using convertParams, this has been said I think I need to add en an explicit warning message inside of this function so that we encourage developers to use the new Builder, what do you think?

**Comment by lauriejim** [comment] 2019-02-14 21:16
My question is. This issue still exist in the PR you did ?
If yes, can you fix it please.

**Comment by samantonis** [comment] 2019-02-15 11:54
got the same error when I tried to set up a test website with blogs and posts (using nextJS and Apollo in frontend)
http://localhost:1337/blogs give me a correct list of blogs i made , but running 
{
  blogs {
    _id
    title
	}
}
as a query on http://localhost:1337/graphql gives me the same error as mentioned by **[laportem](/laportem) **

is this expexted to be fixed soon or is this a non strapi issue and is using mongoDB not recommended for strapi projects ?

**Comment by lauriejim** [comment] 2019-02-16 12:09
@samantonis What is the database you use please.

**Comment by samantonis** [comment] 2019-02-16 12:26
I'm using mongodb locally

**Comment by samantonis** [comment] 2019-02-18 09:01
@lauriejim for more info , i was following this tutorial https://blog.strapi.io/strapi-next-cart/ but used blogs and posts instead of restaurants and dishes in the example. 
rest calls work , graphql does not (see error in previous posts by @laportem )
* **Node.js version**: 10.15.1

* **NPM version**:  6.4.1

* **Strapi version**: 3.0.0-alpha.23.1

* **Database**: mongodb v3.6.10

* **Operating system**:  Mac (Mojave 10.14.2)

**Comment by acarrera94** [comment] 2019-02-20 18:00
I fixed this issue by updating the mongoose dependency to the latest. In the package.json it now has: 
`"strapi-hook-mongoose": "3.0.0-alpha.24"`
the strapi version on mine is still alpha.23.

**Comment by samantonis** [comment] 2019-02-21 10:20
thanks @acarrera94 , that fixed it

**Closed** 2019-02-21 14:39 UTC
Labels: type: help wanted 🤷‍♂️

**Comment by laportem** [comment] 2019-02-22 12:14
indeed upgrading `strapi-hook-mongoose` fixed the issue
