### ISSUE TITLE
Problem with Heroku and MongoDB Atlas

### ISSUE THREAD

**Issue by rolandjmoritz** [strapi/strapi#3548] opened 2019-06-28 12:22 UTC
I am having trouble with deploying my Strapi App to Heroku while using MongoDB Atlas. I followed all the instructions in the "Getting Started"-Guide and got it to work with no problems locally. But when I deploy to Heroku, the App is unable to connect to my MongoDB Atlas DB. 

After deploying with git push, I execute "strapi start" I get this error according to the log:

```
error Make sure your MongoDB database is running...
Make sure your MongoDB database is running...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@0.1.0 start: "node server.js"
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Process exited with status 1
```

this same output is then repeated 3 times in a row in the log.

This is my database.json:

local version (development, connection to MongoDB Atlas works):

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "host": "cluster0-vj6uh.mongodb.net",
        "port": 27017,
        "database": "test",
        "username": "xxx",
        "password": "xxx",
        "srv": true
      },
      "options": {
        "authenticationDatabase": "admin",
        "ssl": true
      }
    }
  }
}

```

for Deployment (production, connection to MongoDB Atlas doesn't work):
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",       
        "host": "${process.env.DATABASE_HOST}",
        "port": "${process.env.DATABASE_PORT || 27017}",
        "database": "${process.env.DATABASE_NAME}",
        "username": "${process.env.DATABASE_USERNAME}",
        "password": "${process.env.DATABASE_PASSWORD}",
        "srv": true
      },
      "options": {
        "authenticationDatabase": "admin",
        "ssl": true
      }
    }
  }
}

```
I did set all the environment variables as explained in the Strapi Guide for deplyoment with Heroku.

**What is the current behavior?**
When deploying to Heroku - it gives me an application error.

**Steps to reproduce the problem**
Create new Strapi app Git init-> git add-> git commit-> create heroku app-> install MLab->push heroku master.

**What is the expected behavior?**
That the build page will show and /admin will redirect to login.

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-alpha.26.2
- Database: MongoDB Atlas Cluster
- Operating system: Windows 10

**Comment by dkarski** [comment] 2019-06-28 13:27
Are you sure that the following requirements are met?
1. Check is MongoDB instance is running
2. Check in the settings that host name is correct.

**Comment by rolandjmoritz** [comment] 2019-06-28 14:21
Ok, I used the Alpha.26.2 Version of Strapi originally. I deinstalled it and reinstalled the Beta Version. After rebuilding and deploying to a new Heroku App, it works! Seems like it might a problem with the Alpha?

**Comment by dkarski** [comment] 2019-06-28 16:38
@rolandjmoritz I'm not sure if it's supported. You can tried reapet the steps for alpha https://strapi.io/documentation/3.0.0-alpha.x/guides/databases.html#mongodb-installation

**Comment by davidkartuzinski** [comment] 2019-07-01 09:18
@rolandjmoritz - is this now resolved for you?

> After rebuilding and deploying to a new Heroku App, it works!

**Comment by monico-moreno** [comment] 2019-07-04 20:41
@rolandjmoritz I am getting the same error, and I am on strapi v3.0.0-beta.7 🤔 

I originally used the code snippet on [strapi's doc here](https://strapi.io/documentation/3.0.0-beta.x/guides/databases.html#mongodb-installation) but the page is a little out of date I think.  I had to add the `srv`, `ssl`, and `authenticationDatabase` keys from your example above.  but then I get other errors.  

I tried reaching out via the strapi slack channel, but it's slow in there.  😞 

Do you have any ideas, @rolandjmoritz  ?

**Comment by monico-moreno** [comment] 2019-07-04 20:49
Errors like this 👉 
```error { MongoWriteConcernError: No write concern mode named 'majority/' found in replica set configuration
    at Connection.<anonymous> (/Users/monico_a_moreno/source/celerity/rentpath-strapi-poc/node_modules/mongodb-core/lib/connection/pool.js:438:23)
    at Connection.emit (events.js:198:13)
    at processMessage (/Users/monico_a_moreno/source/celerity/rentpath-strapi-poc/node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at TLSSocket.<anonymous> (/Users/monico_a_moreno/source/celerity/rentpath-strapi-poc/node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)```

**Comment by monico-moreno** [comment] 2019-07-04 20:50
Errors like this 👉 
```error { MongoWriteConcernError: No write concern mode named 'majority/' found in replica set configuration
    at Connection.<anonymous> (/Users/monico_a_moreno/source/<a_folder>/<a_folder_2>-strapi-poc/node_modules/mongodb-core/lib/connection/pool.js:438:23)
    at Connection.emit (events.js:198:13)
    at processMessage (/Users/monico_a_moreno/source/<a_folder>/<a_folder_2>-strapi-poc/node_modules/mongodb-core/lib/connection/connection.js:364:10)
    at TLSSocket.<anonymous> (/Users/monico_a_moreno/source/<a_folder>/<a_folder_2>-strapi-poc/node_modules/mongodb-core/lib/connection/connection.js:533:15)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)```

**Comment by lauriejim** [comment] 2019-07-08 14:53
Hello @monico-moreno !

Your issue looks different, you are not using MongoAtlas?

**Comment by keshibat** [comment] 2019-07-19 00:49
**Describe the bug**

I am using 3.0.0-beta.13 and I got it work with MongoDB Atlas locally.
I am having trouble with deploying my Strapi App to Heroku while using MongoDB Atlas.

**Expected behavior**

I shold be able to New Entry and be able to save it.


**Steps to reproduce the behavior**

I got it to work with MongoDB Atlas locally.


Following this stephttps://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#heroku,
After deploying with git push, I execute "strapi start" I get this error according to the log:

```
2019-07-18T16:12:38.833397+00:00 app[web.1]: No hostname or hostnames provided in connection string
2019-07-18T16:12:38.838440+00:00 app[web.1]: [2019-07-18T16:12:38.837Z] error No hostname or hostnames provided in connection string
2019-07-18T16:12:38.857579+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-07-18T16:12:38.857941+00:00 app[web.1]: npm ERR! errno 1
2019-07-18T16:12:38.859371+00:00 app[web.1]: npm ERR! cms@0.1.0 start: `strapi start`
2019-07-18T16:12:38.859543+00:00 app[web.1]: npm ERR! Exit status 1
2019-07-18T16:12:38.859753+00:00 app[web.1]: npm ERR!
2019-07-18T16:12:38.859919+00:00 app[web.1]: npm ERR! Failed at the cms@0.1.0 start script.
2019-07-18T16:12:38.860089+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-07-18T16:12:38.879338+00:00 app[web.1]:
2019-07-18T16:12:38.879810+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-07-18T16:12:38.880186+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-07-18T16_12_38_861Z-debug.log
2019-07-18T16:12:39.128009+00:00 heroku[web.1]: State changed from starting to crashed
2019-07-18T16:12:39.104966+00:00 heroku[web.1]: Process exited with status 1
2019-07-18T19:04:59.935681+00:00 heroku[web.1]: State changed from crashed to starting
2019-07-18T19:05:11.996048+00:00 heroku[web.1]: Starting process with command `npm start`
2019-07-18T19:05:16.183717+00:00 app[web.1]:
2019-07-18T19:05:16.183736+00:00 app[web.1]: > cms@0.1.0 start /app
2019-07-18T19:05:16.183738+00:00 app[web.1]: > strapi start
2019-07-18T19:05:16.183740+00:00 app[web.1]:
2019-07-18T19:05:18.867056+00:00 app[web.1]: No hostname or hostnames provided in connection string
2019-07-18T19:05:18.871767+00:00 app[web.1]: [2019-07-18T19:05:18.870Z] error No hostname or hostnames provided in connection string
2019-07-18T19:05:18.897364+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-07-18T19:05:18.897791+00:00 app[web.1]: npm ERR! errno 1
2019-07-18T19:05:18.899351+00:00 app[web.1]: npm ERR! cms@0.1.0 start: `strapi start`
2019-07-18T19:05:18.899589+00:00 app[web.1]: npm ERR! Exit status 1
2019-07-18T19:05:18.899900+00:00 app[web.1]: npm ERR!
2019-07-18T19:05:18.900129+00:00 app[web.1]: npm ERR! Failed at the cms@0.1.0 start script.
2019-07-18T19:05:18.900373+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```



**Screenshots**
***Heroku Setup
I don't know if I'm doing correctly, I set up as follows and restart all dynos after I've saved.

![Imgur](https://i.imgur.com/jiB3Hau.png)


**Code snippets**

/Users/keshibat/dev/cms/config/environments/production

database.json
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "client": "mongo",
        "host": "${process.env.DATABASE_HOST}",
        "port": "${process.env.DATABASE_PORT}",
        "database": "${process.env.DATABASE_NAME}",
        "username": "${process.env.DATABASE_USERNAME}",
        "password": "${process.env.DATABASE_PASSWORD}"
      },
      "options": {
        "ssl": true
      }
    }
  }
}

```
**Code snippets**

/Users/keshibat/dev/cms/config/environments/development

database.json
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "host": "cluster1-shard-00-00-1cmhp.gcp.mongodb.net:27017,cluster1-shard-00-01-1cmhp.gcp.mongodb.net:27017,cluster1-shard-00-02-1cmhp.gcp.mongodb.net:27017/test?ssl=true&replicaSet=Cluster1-shard-0&authSource=admin&retryWrites=true",
        "port": 27017,
        "username": "XXX",
        "password": "XXX"
      },
      "options": {
        "ssl": true
      }
    }
  }
}

```

**Additional context**
Add any other context about the problem here.


**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.13
- Database: mongoDBAtlas
- Operating system: Mac 10.13.6

**Comment by davidkartuzinski** [comment] 2019-07-19 09:21
Here are some changes we made yesterday to the Heroku Config Documentation when using MongoDB Atlas. These have been tested and are simpler.  **NOTE: MongoDB Atlas has changed their UI a bit, but everything is still in there.**

The changes have not yet been merged - But try these.

## Don't forget to get the correct version of the URL! 

MongoDB Atlas automatically exposes the database credentials into a single environment variable accessible by your app. To locate it, follow these steps:

- Under `Atlas` in the left-hand, click on `Clusters`. This should take you to your `cluster`. Next, click `CONNECT` and then `Connect Your Application`.
- Under `1. Choose your driver version`, select **DRIVER** as `Node.js` and **VERSION** as `2.2.12 or later`. **IMPORTANT:** You **must** use `Version: 2.2.12 or later`.
- This should show a **Connection String Only**

## Delete any of your configs in Heroku and set these instead:

### Set up your config file like this

When you [set-up your MongoDB Atlas database](https://strapi.io/documentation/3.0.0-beta.x/guides/databases.html#install-on-atlas-mongodb-atlas) you noted a connection string. Similar to this:

```bash
mongodb://paulbocuse:<password>@strapidatabase-shard-00-00-fxxx6c.mongodb.net:27017,strapidatabase-shard-00-01-fxxxc.mongodb.net:27017,strapidatabase-shard-00-02-fxxxc.mongodb.net:27017/test?ssl=true&replicaSet=strapidatabase-shard-0&authSource=admin&retryWrites=true&w=majority

```

So, from **MongoDB Atlas**, you have to set two environment variables in the Heroku config (for **DATABASE_URI** and **DATABASE_NAME**). Set the environment variables using the following commands:

```bash
heroku config:set DATABASE_URI="mongodb://paulbocuse:<password>@strapidatabase-shard-00-00-fxxx6c.mongodb.net:27017,strapidatabase-shard-00-01-fxxxc.mongodb.net:27017,strapidatabase-shard-00-02-fxxxc.mongodb.net:27017/test?ssl=true&replicaSet=strapidatabase-shard-0&authSource=admin&retryWrites=true&w=majority"
heroku config:set DATABASE_NAME="my-database-name"
```

**Note:** Please replace the `<password>` and `my-database-name` values with the your actual values.

##### 2. Update your database config file

Replace the contents of `database.json` with the following:

`Path: ./config/environments/production/database.json`.

```json
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "uri": "${process.env.DATABASE_URI}",
        "database": "${process.env.DATABASE_NAME}"
      },
      "options": {
        "ssl": true
      }
    }
  }
}
```

The above instructions should work for you.  If you already got the database working and have data in there verify the collection name in the admin panel for MongoDB Atlas - and use that one. If you see "strapi" and you didn't set it, it's because that is the default Strapi collection name.

**Comment by keshibat** [comment] 2019-07-21 05:26
Still getting application error when I deploy to HEROKU with Atlas MongoDB.

Following this step(https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#heroku)


What I have changed.

1. Set two environment variables in the Heroku config
changed user and password for mine.
I confirmed that Config Vars was set on HEROKU GUI. 

```
heroku config:set DATABASE_URI="mongodb://dbuser:XXX@strapidatabase-shard-00-00-fxxx6c.mongodb.net:27017,strapidatabase-shard-00-01-fxxxc.mongodb.net:27017,strapidatabase-shard-00-02-fxxxc.mongodb.net:27017/test?ssl=true&replicaSet=strapidatabase-shard-0&authSource=admin&retryWrites=true&w=majority"
heroku config:set

DATABASE_NAME="test"
```

2.
**database.json**

/Users/keshibat/dev/cms/config/environments/production

```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "uri": "${process.env.DATABASE_URI}",
        "database": "${process.env.DATABASE_NAME}"
      },
      "options": {
        "ssl": true
      }
    }
  }
}

```



```
keshibat (master) cmstest $ heroku logs --tail
2019-07-21T04:53:56.404809+00:00 app[api]: Release v1 created by user kensukeshibata@gmail.com
2019-07-21T04:53:56.404809+00:00 app[api]: Initial release by user kensukeshibata@gmail.com
2019-07-21T04:53:56.576521+00:00 app[api]: Enable Logplex by user kensukeshibata@gmail.com
2019-07-21T04:53:56.576521+00:00 app[api]: Release v2 created by user kensukeshibata@gmail.com
2019-07-21T04:55:28.391792+00:00 app[api]: Set DATABASE_URI config vars by user kensukeshibata@gmail.com
2019-07-21T04:55:28.391792+00:00 app[api]: Release v3 created by user kensukeshibata@gmail.com
2019-07-21T04:56:44.924720+00:00 app[api]: Set DATABASE_NAME config vars by user kensukeshibata@gmail.com
2019-07-21T04:56:44.924720+00:00 app[api]: Release v4 created by user kensukeshibata@gmail.com
2019-07-21T05:00:17.000000+00:00 app[api]: Build started by user kensukeshibata@gmail.com
2019-07-21T05:04:29.833616+00:00 app[api]: Deploy 51febaba by user kensukeshibata@gmail.com
2019-07-21T05:04:29.833616+00:00 app[api]: Release v5 created by user kensukeshibata@gmail.com
2019-07-21T05:04:29.845913+00:00 app[api]: Scaled to web@1:Free by user kensukeshibata@gmail.com
2019-07-21T05:04:39.000000+00:00 app[api]: Build succeeded
2019-07-21T05:04:40.930350+00:00 heroku[web.1]: Starting process with command `npm start`
2019-07-21T05:04:43.780812+00:00 app[web.1]:
2019-07-21T05:04:43.780837+00:00 app[web.1]: > cmstest@0.1.0 start /app
2019-07-21T05:04:43.780839+00:00 app[web.1]: > strapi start
2019-07-21T05:04:43.780841+00:00 app[web.1]:
2019-07-21T05:04:45.894606+00:00 app[web.1]: Make sure your MongoDB database is running...
2019-07-21T05:04:45.897989+00:00 app[web.1]: [2019-07-21T05:04:45.897Z] error Make sure your MongoDB database is running...
2019-07-21T05:04:45.909945+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-07-21T05:04:45.910190+00:00 app[web.1]: npm ERR! errno 1
2019-07-21T05:04:45.911254+00:00 app[web.1]: npm ERR! cmstest@0.1.0 start: `strapi start`
2019-07-21T05:04:45.911353+00:00 app[web.1]: npm ERR! Exit status 1
2019-07-21T05:04:45.911507+00:00 app[web.1]: npm ERR!
2019-07-21T05:04:45.911625+00:00 app[web.1]: npm ERR! Failed at the cmstest@0.1.0 start script.
2019-07-21T05:04:45.911723+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-07-21T05:04:45.919195+00:00 app[web.1]:
2019-07-21T05:04:45.919431+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-07-21T05:04:45.919587+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-07-21T05_04_45_913Z-debug.log
2019-07-21T05:04:46.017240+00:00 heroku[web.1]: State changed from starting to crashed
2019-07-21T05:04:46.023537+00:00 heroku[web.1]: State changed from crashed to starting
2019-07-21T05:04:45.996525+00:00 heroku[web.1]: Process exited with status 1
2019-07-21T05:04:56.332073+00:00 app[web.1]:
2019-07-21T05:04:56.332099+00:00 app[web.1]: > cmstest@0.1.0 start /app
2019-07-21T05:04:56.332102+00:00 app[web.1]: > strapi start
2019-07-21T05:04:56.332103+00:00 app[web.1]:
2019-07-21T05:04:58.355193+00:00 app[web.1]: Make sure your MongoDB database is running...
2019-07-21T05:04:58.358415+00:00 app[web.1]: [2019-07-21T05:04:58.357Z] error Make sure your MongoDB database is running...
2019-07-21T05:04:58.369700+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-07-21T05:04:58.369889+00:00 app[web.1]: npm ERR! errno 1
2019-07-21T05:04:58.370780+00:00 app[web.1]: npm ERR! cmstest@0.1.0 start: `strapi start`
2019-07-21T05:04:58.370860+00:00 app[web.1]: npm ERR! Exit status 1
2019-07-21T05:04:58.371020+00:00 app[web.1]: npm ERR!
2019-07-21T05:04:58.371184+00:00 app[web.1]: npm ERR! Failed at the cmstest@0.1.0 start script.
2019-07-21T05:04:58.371360+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-07-21T05:04:58.379486+00:00 app[web.1]:
2019-07-21T05:04:58.379698+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-07-21T05:04:58.379794+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-07-21T05_04_58_372Z-debug.log
2019-07-21T05:04:58.454854+00:00 heroku[web.1]: State changed from starting to crashed
2019-07-21T05:04:58.436838+00:00 heroku[web.1]: Process exited with status 1
2019-07-21T05:05:15.378123+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cmsstrapi.herokuapp.com request_id=5d7b1122-4fcf-4506-9d31-46af198a69f2 fwd="220.233.93.208" dyno= connect= service= status=503 bytes= protocol=https
2019-07-21T05:07:01.742155+00:00 heroku[web.1]: State changed from crashed to starting
2019-07-21T05:07:01.503569+00:00 app[api]: Release v6 created by user kensukeshibata@gmail.com
2019-07-21T05:07:01.503569+00:00 app[api]: Set DATABASE_URI config vars by user kensukeshibata@gmail.com
2019-07-21T05:07:12.287629+00:00 heroku[web.1]: Starting process with command `npm start`
2019-07-21T05:07:14.299128+00:00 app[web.1]:
2019-07-21T05:07:14.299154+00:00 app[web.1]: > cmstest@0.1.0 start /app
2019-07-21T05:07:14.299156+00:00 app[web.1]: > strapi start
2019-07-21T05:07:14.299158+00:00 app[web.1]:
2019-07-21T05:07:16.710396+00:00 app[web.1]: Make sure your MongoDB database is running...
2019-07-21T05:07:16.713946+00:00 app[web.1]: [2019-07-21T05:07:16.713Z] error Make sure your MongoDB database is running...
2019-07-21T05:07:16.741218+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-07-21T05:07:16.745158+00:00 app[web.1]: npm ERR! errno 1
2019-07-21T05:07:16.747372+00:00 app[web.1]: npm ERR! cmstest@0.1.0 start: `strapi start`
2019-07-21T05:07:16.747578+00:00 app[web.1]: npm ERR! Exit status 1
2019-07-21T05:07:16.747825+00:00 app[web.1]: npm ERR!
2019-07-21T05:07:16.747989+00:00 app[web.1]: npm ERR! Failed at the cmstest@0.1.0 start script.
2019-07-21T05:07:16.748085+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-07-21T05:07:16.756543+00:00 app[web.1]:
2019-07-21T05:07:16.760217+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-07-21T05:07:16.760411+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-07-21T05_07_16_750Z-debug.log
2019-07-21T05:07:16.852882+00:00 heroku[web.1]: State changed from starting to crashed
2019-07-21T05:07:16.830507+00:00 heroku[web.1]: Process exited with status 1
2019-07-21T05:07:17.557991+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cmsstrapi.herokuapp.com request_id=8c83d4f7-7c21-460b-ad84-0b331beb80a3 fwd="220.233.93.208" dyno= connect= service= status=503 bytes= protocol=https
2019-07-21T05:11:56.618855+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cmsstrapi.herokuapp.com request_id=6ab93a51-3e72-4093-b060-0a6883ba6e51 fwd="220.233.93.208" dyno= connect= service= status=503 bytes= protocol=https
2019-07-21T05:13:53.761095+00:00 heroku[web.1]: State changed from crashed to starting
2019-07-21T05:14:05.323594+00:00 heroku[web.1]: Starting process with command `npm start`
2019-07-21T05:14:07.815037+00:00 app[web.1]:
2019-07-21T05:14:07.815068+00:00 app[web.1]: > cmstest@0.1.0 start /app
2019-07-21T05:14:07.815071+00:00 app[web.1]: > strapi start
2019-07-21T05:14:07.815073+00:00 app[web.1]:
2019-07-21T05:14:09.891814+00:00 app[web.1]: Make sure your MongoDB database is running...
2019-07-21T05:14:09.896220+00:00 app[web.1]: [2019-07-21T05:14:09.895Z] error Make sure your MongoDB database is running...
2019-07-21T05:14:09.922230+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-07-21T05:14:09.922466+00:00 app[web.1]: npm ERR! errno 1
2019-07-21T05:14:09.923887+00:00 app[web.1]: npm ERR! cmstest@0.1.0 start: `strapi start`
2019-07-21T05:14:09.923890+00:00 app[web.1]: npm ERR! Exit status 1
2019-07-21T05:14:09.924156+00:00 app[web.1]: npm ERR!
2019-07-21T05:14:09.924193+00:00 app[web.1]: npm ERR! Failed at the cmstest@0.1.0 start script.
2019-07-21T05:14:09.924354+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-07-21T05:14:09.935240+00:00 app[web.1]:
2019-07-21T05:14:09.935471+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-07-21T05:14:09.935714+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-07-21T05_14_09_925Z-debug.log
2019-07-21T05:14:10.037973+00:00 heroku[web.1]: State changed from starting to crashed
2019-07-21T05:14:10.014561+00:00 heroku[web.1]: Process exited with status 1
2019-07-21T05:14:11.016502+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=cmsstrapi.herokuapp.com request_id=fdbd66c4-a56c-458c-af29-9b5596e24057 fwd="220.233.93.208" dyno= connect= service= status=503 bytes= protocol=https
2019-07-21T05:16:03.585882+00:00 heroku[web.1]: State changed from crashed to starting
2019-07-21T05:16:12.574216+00:00 heroku[web.1]: Starting process with command `npm start`
2019-07-21T05:16:14.566041+00:00 app[web.1]:
2019-07-21T05:16:14.566059+00:00 app[web.1]: > cmstest@0.1.0 start /app
2019-07-21T05:16:14.566061+00:00 app[web.1]: > strapi start
2019-07-21T05:16:14.566062+00:00 app[web.1]:
2019-07-21T05:16:16.238350+00:00 app[web.1]: Make sure your MongoDB database is running...
2019-07-21T05:16:16.240795+00:00 app[web.1]: [2019-07-21T05:16:16.240Z] error Make sure your MongoDB database is running...
2019-07-21T05:16:16.252483+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-07-21T05:16:16.252666+00:00 app[web.1]: npm ERR! errno 1
2019-07-21T05:16:16.253542+00:00 app[web.1]: npm ERR! cmstest@0.1.0 start: `strapi start`
2019-07-21T05:16:16.253641+00:00 app[web.1]: npm ERR! Exit status 1
2019-07-21T05:16:16.253768+00:00 app[web.1]: npm ERR!
2019-07-21T05:16:16.253906+00:00 app[web.1]: npm ERR! Failed at the cmstest@0.1.0 start script.
2019-07-21T05:16:16.254003+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-07-21T05:16:16.261123+00:00 app[web.1]:
2019-07-21T05:16:16.261247+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-07-21T05:16:16.261316+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-07-21T05_16_16_255Z-debug.log
2019-07-21T05:16:16.331999+00:00 heroku[web.1]: State changed from starting to crashed
2019-07-21T05:16:16.311603+00:00 heroku[web.1]: Process exited with status 1
```




**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.13
- Database: mongoDBAtlas
- Operating system: Mac 10.13.6

**Comment by davidkartuzinski** [comment] 2019-07-22 09:04
Your settings look correct to me. 

Could you please verify your permission in MongoDB Atlas? Did you do Step 2 with the database user you created? https://strapi.io/documentation/3.0.0-beta.x/guides/databases.html#install-on-atlas-mongodb-atlas

Could you also verify your password under Security -> Database Access and edit in the User? 

Could you test with ACCESS Anywhere (Step 3) 0.0.0.0/0 in the Network Access Tab under Security?

If it still doesn't work, then please verify your connection string by clicking on ATLAS -> Clusters.  Then the CONNECT button. From there "Connect your Application" and next Select 2.2.12 or Later under Version.  Please reset (with your password) this in Heroku by deleting your existing value and trying again.

If that doesn't fix it, then please go to ATLAS -> Clusters and hit the COLLECTIONS button, you should see "test" in there. unless you named a different name in the database.json and the variable in Heroku.

Please let us know if this resolved it for you?

**Comment by keshibat** [comment] 2019-07-22 13:47
Finally got it to work. Thank you @davidkartuzinski 

I know what I did wrong.
I forgot to delete &w=majority in my DATABASE_URI:
```
heroku config:set DATABASE_URI="mongodb://dbuser:XXX@strapidatabase-shard-00-00-fxxx6c.mongodb.net:27017,strapidatabase-shard-00-01-fxxxc.mongodb.net:27017,strapidatabase-shard-00-02-fxxxc.mongodb.net:27017/test?ssl=true&replicaSet=strapidatabase-shard-0&authSource=admin&retryWrites=true"
heroku config:set DATABASE_NAME="test"

```


Besides that, 

=> I've added IP 0.0.0.0/0 in the Network Access (Previously, I only specify my home and school IP address)


=> It was originally set as "Altas admin". I changed to "Read and write to any database".


development 
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "host": "mongodb: //dbuser:Secret1.0@cluster1-shard-00-00-1cmhp.gcp.mongodb.net:27017,cluster1-shard-00-01-1cmhp.gcp.mongodb.net:27017,cluster1-shard-00-02-1cmhp.gcp.mongodb.net:27017/test?ssl=true&replicaSet=Cluster1-shard-0&authSource=admin&retryWrites=true",
        "port": 27017,
        "username": "dbuser",
        "password": "XXX(Password does not include capital letters)"
      },
      "options": {
        "ssl": true
      }
    }
  }
}
```

production
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-mongoose",
      "settings": {
        "uri": "${process.env.DATABASE_URI}",
        "database": "${process.env.DATABASE_NAME}"
      },
      "options": {
        "ssl": true
      }
    }
  }
}
```

**Comment by davidkartuzinski** [comment] 2019-07-22 14:48
@keshibat - I am happy you got your deployment to work using MongoDB Atlas.  Now that it is working, you shouldn't leave the 0.0.0.0/0 setting in the Network Access but use the IP address of the server holding Strapi.  Is that Heroku? If it is Heroku, unfortunately then, I understand the Heroku rotates IP Addresses so you have to use 0.0.0.0/0 but otherwise the IP Address from (for example EC2 with AWS or a Digital Ocean VPS) would go in there.

Again, good job on getting this to work and thank you for writing out what did it for you.

**Comment by keshibat** [comment] 2019-07-23 00:30
@davidkartuzinski 

I am using HEROKU.  Unfortunately, I need to use 0.0.0.0/0 in order to hook Strapi and Heroku. 
Otherwise, it won't work. So that was 0.0.0.0/0.

Now I am getting Infinite loading when I creating new entry.........
![Imgur](https://i.imgur.com/ps3lglE.png)

**Comment by derrickmehaffy** [comment] 2019-07-23 05:56
@keshibat as I mentioned on your other issue, you just need to delete the entry `plugin_content-manager_schema` in your `core_store` collection in Mongo. But yes I will go ahead and close this issue as you stated the original issue was solved.

**Closed by derrickmehaffy** 2019-07-23 05:56 UTC
Labels: type: help wanted 🤷‍♂️
