### ISSUE TITLE
Wrong results when filtering datetimes

### ISSUE THREAD

**Issue by finfa** [strapi/strapi#8298] opened 2020-10-12 16:27 UTC
**Describe the bug**

Wrong results when filtering datetimes

**Steps to reproduce the behavior**
1. Define a Model with a datetime field
2. Create an Instance of that Model with value '2020-10-01T00:00:00Z'
3. Query with a lower-than filter with value '2020-10-02T00:00:00Z'

The entity is not found.

**Expected behavior**
The entity is found because the datetime of the entity is smaller than the datetime given as a filter.

**Screenshots**
How the datetime is stored inside the SQLite database:
![image](https://user-images.githubusercontent.com/4535128/95765572-5eda2a00-0cb2-11eb-904e-20287f886233.png)

**Code snippets**
Model definition:
```
{
  "kind": "collectionType",
  "collectionName": "tests",
  "info": {
    "name": "test"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": false
  },
  "attributes": {
    "date": {
      "type": "datetime"
    }
  }
}
```

Functional test:
```
test('dateCheck', async done => {

  let {id} = await strapi.services.test.create({
    date: new Date('2020-10-01T00:00:00Z')
  });

  let entity = await strapi.query('test').findOne({
    id: id,
    date_lt: new Date('2020-10-02T00:00:00Z')
  })

  expect(entity).not.toBe(null)

  done()
});
```

Test output:
```

 ● functional tests › dateCheck

    expect(received).not.toBe(expected) // Object.is equality

    Expected: not null

      10 |   })
      11 | 
    > 12 |   expect(entity).not.toBe(null)
         |                      ^
      13 | 
      14 |   done()
      15 | });

      at Object.<anonymous> (tests/functional/publication.js:12:22)
```

**System**

- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: 3.2.0
- Database: Sqlite
- Operating system: Ubuntu 18.04

**Additional context**
I suspect the problem has to do with the format that Strapi uses to store datetimes in SQLite. Probably, an alphabetical comparison takes place, and fails to chronologically compare dates. If that's the issue, storing datetimes in an ISO- format should solve it.

Using SQLite-specific code cannot be a solution. We use Mysql in production. We find SQLite practical for running functional tests and feature-preview deployments.

**Comment by derrickmehaffy** [comment] 2020-10-13 19:45
Was able to confirm this on v3.2.3

**Comment by digitaljohn** [comment] 2021-04-23 23:40
Confirmed on v3.5.4

I agree with @finfa it's likely due to SQLites limited support of datetime fields.

**Comment by derrickmehaffy** [comment] 2022-07-13 20:48
Should be fixed in v4

**Closed by derrickmehaffy** 2022-07-13 20:48 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:database
