### ISSUE TITLE
In version 3.2.0 publish fails if non-repeateable component data is "null"

### ISSUE THREAD

**Issue by Stanko** [strapi/strapi#8221] opened 2020-10-07 11:57 UTC
**Describe the bug**

When trying to publish an entity that has non-repeateable component and component is not filled in, publish fails with an error.

﻿﻿I'll open a PR in a minute.

**Steps to reproduce the behavior**

In the Content-Types Builder:

* Create a component (I called it `publish-test-component`)
* Create a collection type (I called it `PublishTest`)
* Add two fields to it
  * `name` - text field
  * `component` - select the component we created `publish-test-component`, and for the "Type" select "Single Component"

Go and create a new `PublishTest`:

* Fill in the `name` field
* Click "Save"
* Click "Publish"
* You'll get this error in the console:
  ```
  Uncaught TypeError: can't convert null to object
    getDraftRelationsCount getDraftRelations.js:4
  ```

**Expected behavior**
Page is published with no errors.

**Screenshots**

Dummy collection type I created for this test, it is important that the component's type is set to "Single Component":
<img width="800" alt="Screen Shot 2020-10-07 at 1 47 41 PM" src="https://user-images.githubusercontent.com/776788/95327538-7bd2bf80-08a4-11eb-93bc-9abc1b3ec7ba.png">

When hitting publish, if component has no data, publish fails:
<img width="1200" alt="Screen Shot 2020-10-07 at 1 45 06 PM" src="https://user-images.githubusercontent.com/776788/95327550-7ecdb000-08a4-11eb-8d9e-27eb3232ae1d.png">

As you can see, data is `null` and `Object.keys(data)` on line 5 fails:
<img width="600" alt="Screen Shot 2020-10-07 at 1 46 13 PM" src="https://user-images.githubusercontent.com/776788/95327554-7ffedd00-08a4-11eb-8d63-73494b77e60e.png">

**System**

I don't think these matter, but still I filled it in:

- Node.js version: v12.16.1
- NPM version: 6.14.5
- Strapi version: 3.2.0
- Database: sqlite
- Operating system: macOS

**Comment by alexandrebodin** [comment] 2020-10-07 12:02
Hi, thanks for the notice.  This issue is a duplicate of https://github.com/strapi/strapi/issues/8220. I'm going to close this one :)

**Comment by Stanko** [comment] 2020-10-07 12:03
Sorry, I've searched through the issues, but missed that one 🙈

**Closed by alexandrebodin** 2020-10-07 12:02 UTC

**Comment by hadynz** [comment] 2020-10-07 17:51
Not related to the issue anymore since it has been resolved -

@Stanko i ran into the same issue last night and struggled a lot debugging it because strapi code is always minified. I couldn't even add `debugger` statements. 

I can see you didn't have the problem. Wondering how that was the case as it would help me in the future contributing more thoroughly to the project?

**Comment by Stanko** [comment] 2020-10-08 07:59
Hey @hadynz, code is minified, but strapi team provides source maps as well. When error happens, development tools (I use firefox) will show you exactly in which file it happened. Then you can edit it in the node modules, but this can be cumbersome as you need to restart the app. Or just copy the file to your project's folder, check the official documentation:

https://strapi.io/documentation/v3.x/admin-panel/customization.html#development-mode

Now strapi will use the local file instead of the one from the node modules, and you can patch the bug locally. Then I just take that patch and create a PR back to this repo.

Hope that helps, cheers!
