### ISSUE TITLE
Wrong directory with generate:model --plugin 

### ISSUE THREAD

**Issue by eddie11n** [strapi/strapi#3889] opened 2019-09-03 03:56 UTC
**Describe the bug**
Run command:  `strapi generate:model userinfo --plugin foo`
You get `project/plugins/foo/models/models/userinfo`

**Expected behavior**
Should be `project/plugins/foo/models/userinfo`

**System**
- Node.js version: 11.11.0
- NPM version: 6.11.1
- Strapi version: 3.0.0-beta.15
- Database: Mongo
- Operating system: macOS

**Comment by lauriejim** [comment] 2019-09-11 17:53
Hello @eddie11n ! Thank you for reporting this issue.
We already have a PR that fix the same kind of issue.
Please check [here 🛠](https://github.com/strapi/strapi/pull/3892)!
You will have to replace the path to the `./extensions` folder instead of `plugin` folder.
To match the [extension documentation 📚](https://strapi.io/documentation/3.0.0-beta.x/concepts/concepts.html#extensions)

**Comment by soupette** [comment] 2019-12-26 10:47
@lauriejim I have checked with the latest beta (**beta.18**) and the problem is not happening anymore. I am closing the issue.

**Comment by lauriejim** [comment] 2019-12-27 14:37
I reopen this issue. This still happen.
📺[here](https://www.loom.com/share/d83461606b9e466f8141372ce8114b42) is a record of what I did with a fresh new project `beta.18.3`

**Closed** 2020-03-23 18:02 UTC
Labels: good first issue, priority: low, source: core:framework, status: confirmed, type: bug
