### ISSUE TITLE
Cannot query single type by id GraphQL

### ISSUE THREAD

**Issue by giona69** [strapi/strapi#2771] opened 2019-02-06 13:22 UTC
**Informations**
- **Node.js version**: 10.14.1
- **NPM version**: 6.7.0
- **Strapi version**: alpha.22
- **Database**: tried with mysql 5.7 or SqlLite
- **Operating system**: macosx mojave

**What is the current behavior?**

this query will note execute, whatever the content type you have created

```
  module(id: "1") {
    name
  }
```
and this is the error:

"message": "Undefined binding(s) detected when compiling SELECT query: select `modules`.* from `modules` where `modules`.`id` = ? limit ?"

as a side note, maybe related, also this query doesn't work

```
  me {
    email
  }
```

**Steps to reproduce the problem**
install strapi version alpha.22
strapi new project
install graphql plugin
module (has one attribute "title") 
create two records in modules 
launch this query

```
 module(id: "1") {
    name
  }
```

**What is the expected behavior?**
should return the query as expected

**Suggested solutions**
must investigate
the most recent version to be working in this repsect is alpha.19 (also alpha.21 and alpha.20 do not work)

**Comment by derrickmehaffy** [comment] 2019-02-07 10:02
Can confirm this issue @lauriejim 
![image](https://user-images.githubusercontent.com/8593673/52403815-df2f9d00-2a84-11e9-981b-21ed0cfc37a7.png)

**Comment by derrickmehaffy** [comment] 2019-02-07 10:03
Both with or without the quotes `id: 1` or `id: "1"`

**Comment by giona69** [comment] 2019-02-07 10:14
@derrickmehaffy I tried both, with and without

**Comment by thomaskvael** [comment] 2019-02-07 10:30
There is another issue regarding this in strapi-examples
[https://github.com/strapi/strapi-examples/issues/70](https://github.com/strapi/strapi-examples/issues/70)

**Comment by scorpionking90** [comment] 2019-02-07 11:42
@derrickmehaffy can we have quick fix for this as it has stopped most of my development work. Thanks in advance.

**Comment by derrickmehaffy** [comment] 2019-02-07 11:48
@scorpionking90 no can do from me man. I am not on the Strapi team and have no idea what is going on here lol.

**Comment by scorpionking90** [comment] 2019-02-07 11:57
@derrickmehaffy , lol I saw you have pinned all striapi stuff so thought you have been contributing to it.
But I am trying this from few days, I am not able to get associates from teams.

This works
{
      teams{
            name
       }
}

**Comment by derrickmehaffy** [comment] 2019-02-07 12:11
@scorpionking90 sure I contribute :stuck_out_tongue: but I have not the slightest idea how the graphQL plugin works. :rofl:

**Comment by giona69** [comment] 2019-02-07 16:56
@derrickmehaffy going back to alpha.19 it still works ... just if you need to go on with your own stuff

**Comment by scorpionking90** [comment] 2019-02-08 05:49
@giona69 it is not working for me when i go back to alpha.19.

**Comment by lauriejim** [comment] 2019-02-09 15:20
Probably related to that https://github.com/strapi/strapi/issues/2244

**Comment by kenberkeley** [comment] 2019-02-14 08:43
any news?

**Comment by giona69** [comment] 2019-02-16 14:42
hey guys any news? this is a quite important feature ...

**Comment by pierreburgy** [comment] 2019-02-17 14:09
I submitted a new PR to fix this issue: https://github.com/strapi/strapi/pull/2839

**Closed** 2019-02-17 16:15 UTC
Labels: priority: high, status: confirmed, type: bug 🐛

**Comment by scorpionking90** [comment] 2019-02-19 18:29
I updated strapi to alpha.24, but still I have same issue

**Comment by derrickmehaffy** [comment] 2019-02-19 18:43
@scorpionking90 I couldn't reproduce this on 24.1 . Please check again on v24.1 (the hotfix)

![image](https://user-images.githubusercontent.com/8593673/53039113-9a6c1480-343b-11e9-833c-023533708590.png)

**Comment by vaskort** [comment] 2019-03-06 16:25
Any ideas in which version this got introduced? Thanks!

**Comment by puneetverma05** [comment] 2019-03-07 07:22
@derrickmehaffy  Error still persists in alpha.24.1 
Database: MySQL

**Comment by JonathanLehner** [comment] 2019-10-06 19:38
i get internal server error when selecting with iD. for me only works getting all the elements, which could give too much data

**Comment by derrickmehaffy** [comment] 2019-10-06 20:14
@JonathanLehner post your query here most likely you are trying to use where: {} with a single request and it doesn't support that.

**Comment by JonathanLehner** [comment] 2019-10-06 20:17
I used page(id : "1"){...} and page(id : 1){...} both didn't work

**Comment by derrickmehaffy** [comment] 2019-10-07 05:18
@JonathanLehner what database are you on? because mysql, postgres, and sqlite all work fine for me: 
![image](https://user-images.githubusercontent.com/8593673/66286628-2a55b600-e887-11e9-9090-2e4ebd590fcf.png)
