### ISSUE TITLE
Cannot install latest Strapi on Windows 10 space in profile path?

### ISSUE THREAD

**Issue by southside** [strapi/strapi#741] opened 2018-03-05 11:15 UTC
Node = 8.9.4
Npm = 5.6.0
Strapi = 3.0.0-alpha.10.3
Windows 10 1709
Report Bug installing on Windows 10 Pro

######

npm install strapi@alpha -g
seems to install fine no errors.

strapi new myProject
errors it looks like the dependencies are the issue maybe as I have a space in my profile path name ie C:\Users\Stewart Campbell\

See part of error below.

I see another reported bug with same issue saying it was fixed in Strapi Version 9 I am using a newer version.

Error: Cannot find module 'C:\Users\Stewart' at Function.Module._resolveFilename (module.js:538:15) at Function.Module._load (module.js:468:25) at Function.Module.runMain (module.js:684:10) at startup (bootstrap_node.js:187:16) at bootstrap_node.js:608:3

**Comment by lauriejim** [comment] 2018-03-05 14:05
hi @southside it's a duplicate of this issue https://github.com/strapi/strapi/issues/709
For the moment please use a path without space.

**Closed by lauriejim** 2018-03-05 14:05 UTC

**Comment by southside** [comment] 2018-03-05 14:14
When you say path without space I tried logging into pc as a new profile with username "test" so no space in profile path but when doing a strapi new project it still failed with same errors

Likely as the nodejs paths etc would still reference the profile nodejs etc were installed under

Would I need to reinstall nodejs, mongodb, npm etc under new profile to update environment paths?

Is there no other patch
