### ISSUE TITLE
Multiselect closes the whole modal

### ISSUE THREAD

**Issue by bogdaaamn** [strapi/strapi#18293] opened 2023-10-04 13:06 UTC
### Required System information

- Node.js version:  v18.17.1
- NPM version: 9.63
- Strapi version: 4.14.2
- Operating system: Sonoma 14.0
- Browser: Arc 1.10.1 (Chromium Engine Version 117.0.5938.132)
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

When selecting options inside a multiselect that is inside a modal, clicking outside of the multi box closes the modal altogether. No matter if I click inside of the modal to fill in other fields, this will close the modal. 

I also didn't figure out other ways to close the options list without closing the modal. Focusing back to the modal feels impossible. 

### Steps to reproduce the behavior

The place I found a modal is on the Users settings page, not sure where else are they.

1. Go to **Settings** > **Users**
2. Click on **Invite new user**
3. Select options in **User's roles**
4. Exit the options list

### Expected behavior

A click outside of the options list, inside the modal should close just the list. Esc key press as well, I believe (?)

### Screenshots

![Screen grab where the modal closes on any click outside of the multiselect](https://github.com/strapi/strapi/assets/22895284/5519dbc1-9d81-46d3-8173-973083775c4b)

### Code snippets

n/a

### Additional context

n/a

**Comment by shoaib-31** [comment] 2023-10-04 14:07
@derrickmehaffy @bogdaaamn Can I work on this issue? Maybe I can help as I have faced similar issues recently in my projects.

**Comment by Boegie19** [comment] 2023-10-04 14:44
@shoaib-31 If you want to work on something you would be looking for status: confirmed issues. take any you want that don't have an open PR for it since if somone is working on it they should open a PR for it.

@bogdaaamn Can you try and rebuild your admin and update to 4.14.3 since I can't replicate it on 4.14.3

**Comment by hamzapaskingakhtar1999** [comment] 2023-10-04 18:08
> @derrickmehaffy @bogdaaamn Can I work on this issue? Maybe I can help as I have faced similar issues recently in my projects.

I tried to reproduce and it seems to be working fine. Have you tried reproducing the issue yourself ?

**Comment by jainsuneet** [comment] 2023-10-05 08:33
I am also facing the same issue after updating to version 4.14.3

**Comment by bogdaaamn** [comment] 2023-10-05 10:05
Thank you @Boegie19! It's still happening on `4.14.3`.

I just ran `yarn create strapi-app my-project --quickstart` and I can't reproduce it on a fresh codebase. I will work back on my codebase see what the problem could be 🤔

**Comment by Boegie19** [comment] 2023-10-05 15:01
@bogdaaamn Do you get any errors in your console?

**Comment by afroraydude** [comment] 2023-10-05 19:21
I attempted this and found no errors in the console. I updated to 4.14.3 and rebuilt and still no errors.

**Comment by joshuaellis** [comment] 2023-10-06 09:25
Hi everyone, sorry to hear you're having some difficulties. With the help of @Boegie19, we're struggling to reproduce this issue and most of you are with a fresh project. 

Overall my advice would be to delete your node_modules and lockfile as per the usual upgrade paths – which _should_ make sure the design-system is up to date. Failing this, this issue will remain as "can not reproduce" unless someone is able to provide a github repo demonstrating the issue 👍🏼

**Comment by bogdaaamn** [comment] 2023-10-06 10:23
Thank you @joshuaellis @Boegie19!

Deleting and re-generating the lock file fixed the issue indeed. I thought it's weird to do it since I changed the lock file with the upgrade from 4.14.2 to 4.14.3 and issues persisted, so I didn't think this would do much. But it did wonders, thank you 🙌🏼 

@afroraydude @jainsuneet does this help?

**Comment by Boegie19** [comment] 2023-10-06 10:25
@bogdaaamn can you send us a diff of the old and new lock file of posible?

**Comment by bogdaaamn** [comment] 2023-10-06 10:37
@Boegie19 sure! The PR is in a private repo, but here is the git diff https://gist.github.com/bogdaaamn/2396679bf5bddde6ce4eab023259593a

Note that we also have a bunch of custom plugins, most of this might just be noise

**Comment by Boegie19** [comment] 2023-10-06 11:15
found the underlying issue. https://github.com/radix-ui/primitives/issues/1088

**Comment by jainsuneet** [comment] 2023-10-06 11:53
> Thank you @joshuaellis @Boegie19!
> 
> Deleting and re-generating the lock file fixed the issue indeed. I thought it's weird to do it since I changed the lock file with the upgrade from 4.14.2 to 4.14.3 and issues persisted, so I didn't think this would do much. But it did wonders, thank you 🙌🏼
> 
> @afroraydude @jainsuneet does this help?

@bogdaaamn Deleting the lock file and regenerating it did not help. Issue is still there.

**Comment by Boegie19** [comment] 2023-10-06 12:01
@jainsuneet can you send me your yarn lock file so I can confirm the issue?

**Comment by wgnahs** [comment] 2023-10-11 09:15
I encountered the same issue on v4.14.3. I removed my lock file and then ran `yarn build`, which resolved the problem.

**Comment by lukesmmr** [comment] 2023-10-11 20:16
Also happening to us after upgrading to `v4.12.5` to `v4.14.3` on one of our staging instances. Removing lock file and running `yarn build` was not the solution. Any updates on this?

**Comment by Boegie19** [comment] 2023-10-11 20:42
@lukesmmr issue is a miss meched dependency https://github.com/radix-ui/primitives/issues/1088 only solution would be to pin it properly pin it in your repo

**Comment by JustTB** [comment] 2023-10-27 11:46
This issue can be closed. It was fixed with v4.14.4

**Comment by Boegie19** [comment] 2023-10-27 17:24
@JustTB Don't think it is fixed since it depends on what dependency versions npm choses.

**Comment by nick-aj** [comment] 2023-11-14 10:01
Raising severity due to EE customer effected (5223).
Severity raised:
- Medium -> High.

**Comment by nick-aj** [comment] 2023-11-24 09:20
Additional instance of TID: 5315.

**Comment by Boegie19** [comment] 2023-11-24 09:47
@nick-aj Issue is fixable btw by pinning spesific dependencys like said in https://github.com/radix-ui/primitives/issues/1088

**Comment by nick-aj** [comment] 2023-11-29 07:21
Additional instance at TID 5374.

Thank you @Boegie19, I appreciate the pointer!

**Comment by Eventyret** [comment] 2023-12-19 08:59
Additional instance at TID 5548

**Comment by sdgroot** [comment] 2023-12-20 17:24
Any update on this issue? Also an Enterprise user here, and this bug is currently preventing us from inviting new users. Is there any known workaround until this is fixed?

Node.js version: v18.19.0
NPM version: v9.8.1
Strapi version: v4.15.5
Operating system: OSX Sonoma 14.2.1 (23C71)
Browser: Firefox 120.0.1 and Chrome 120.0.6099.109
Is your project Javascript or Typescript: JavaScript

**Comment by Boegie19** [comment] 2023-12-30 11:49
@sdgroot Like I said above.

Pinning 

    "@radix-ui/react-dismissable-layer": "^1.0.5",
    "@radix-ui/react-dialog": "^1.0.5"
    
  fixes the issue since it is a miss match in version one is above 1.0.5 and the other is bellow it

**Comment by derrickmehaffy** [comment] 2023-12-31 08:09
Locking this for now.

**Comment by derrickmehaffy** [comment] 2024-01-02 14:48
Raising this to critical as it's beginning to heavily impact many of our Cloud users who are completely unable to add new admin users.

While trying to reproduce it myself it appears this largely only impacts Mac users as I was not able to reproduce it on Chrome using Linux Mint (Strapi v4.16.2)

**Comment by derrickmehaffy** [comment] 2024-01-02 14:52
Additional TID5494

**Comment by derrickmehaffy** [comment] 2024-01-05 14:20
Hello all, 

We are trying to actively figure out the root cause of this and we need some information from everyone.

Can you please either attach your package.json and package-lock.json OR yarn.lock. Alternatively if you don't to send those publicly please email them to me directly derrick.mehaffy@strapi.io

Thank you

**Comment by derrickmehaffy** [comment] 2024-01-08 19:10
We believe we have determined the root cause of this based on information provided by community users and some of our Strapi Cloud users.

## For all Strapi projects, any package that starts with `@strapi/*` should be the same version, the only exception to this is `@strapi/plugin-seo`.

Thus if you have something like `@strapi/strapi` with the version of `4.16.2` then something like `@strapi/plugin-graphql`, `@strapi/plugin-users-permissions`, `@strapi/plugin-i18n` should all also be `4.16.2`

We also advise deleting your `package-lock.json` and/or `yarn.lock` and regenerating them. If you still encounter the issue after this, please share your package.json.

Thanks

**Comment by Agustin-BIDFTA** [comment] 2024-01-12 20:19
Howdy, I am experiencing the same issue. I've followed the thread from @derrickmehaffy and made sure every dependency with @strapi/* was the same, deleted yarn.lock and tried again. The issue persisted.

This is my package.json. 
```
{
  "name": "bidfta-strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/strapi": "4.16.2",
    "@strapi/plugin-users-permissions": "4.16.2",
    "@strapi/plugin-i18n": "4.16.2",
    "@strapi/plugin-cloud": "4.16.2",
    "better-sqlite3": "8.6.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3",
    "@strapi/plugin-color-picker": "4.16.2",
    "@strapi/provider-upload-aws-s3": "4.16.2",
    "knex": "^2.0.0",
    "mysql": "^2.18.1"
  },
  "author": {
    "name": "Agustin"
  },
  "strapi": {
    "uuid": "5bb5a797-4208-49af-aa6b-1756a59eeacc"
  },
  "engines": {
    "node": "18.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT",
  "devDependencies": {
    "prettier": "2.7.1"
  }
}
```

I can reproduce the issue both locally and on production with both windows and mac computer. I understand the pain of trying to fix something that isn't reproducible so if there's any further thing I can do to assist you, feel free to reach out.

**Comment by joshuaellis** [comment] 2024-01-12 20:31
Can you share your lock file please?

**Comment by Agustin-BIDFTA** [comment] 2024-01-12 20:47
Oops, there was an issue with my docker and it didn't load the latest dependencies when I updated my packages. This fixed my issue. Sorry for the extra hassle.

**Comment by certainlyakey** [comment] 2024-02-23 15:48
> @sdgroot Like I said above.
> 
> Pinning
> 
> ```
> "@radix-ui/react-dismissable-layer": "^1.0.5",
> "@radix-ui/react-dialog": "^1.0.5"
> ```
> 
> fixes the issue since it is a miss match in version one is above 1.0.5 and the other is bellow it

Didn't work for me.

**Comment by derrickmehaffy** [comment] 2024-02-23 17:53
Marking this as closed as it's been narrowed down to a specific dependency being cached for some users.

**Closed by derrickmehaffy** 2024-02-23 17:53 UTC
Labels: issue: bug, severity: high, status: confirmed, source: dependencies

**Comment by certainlyakey** [comment] 2024-02-27 14:50
We still need a working solution for this that would not require deleting `package-lock.json`. In a monorepo where Strapi is just one of the packages, deleting `package-lock.json` is too disruptive because it might potentially cause new issues in unrelated packages.

**Comment by derrickmehaffy** [comment] 2024-02-27 23:03
> We still need a working solution for this that would not require deleting `package-lock.json`. In a monorepo where Strapi is just one of the packages, deleting `package-lock.json` is too disruptive because it might potentially cause new issues in unrelated packages.

Sorry but we have no other solution as that's the word from our engineering team.

You could delete, regenerate, diff, restore, and manually fix your lock but that is far outside of our scope.

It has always been our policy to treat the lock file as something replaceable.
