### ISSUE TITLE
Serving Audio Assets.

### ISSUE THREAD

**Issue by yaldram** [strapi/strapi#5503] opened 2020-03-13 13:33 UTC
**Describe the bug**
Facing an unexpected error ``Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:111:27)`` while serving audio files m4a and mp3 from the public/uploads folder.

**Steps to reproduce the behavior**
1. Go to File Uploads in Strapi Admin.
2. Click on Upload a File and upload an mp3 file or m4a file.
3. Click on the eye Icon and Open the File just uploaded. The file will run in the browser but not on IOS and Android devices ( their respective media libraries not browser  ).
4. In the Console, you can see the error Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:111:27).
5. I tried serving these files from a simple express public folder surprisingly it worked there.

**Expected behavior**
When we view an uploaded mp3 or mp4 file we should be able to stream it without the TCP.onstream Error.

**Screenshots**
![image](https://user-images.githubusercontent.com/13429535/76624799-f7150280-655b-11ea-89d2-3a952aaac1a9.png).

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.7
- Database: MongoDB
- Operating system: Windows 10

**Additional context**
It is surprising that serving the same audio files works on a simple express app, but not with Strapi or is this a problem with Koa. Please Help Team. Thanks in advance.

**Comment by alexandrebodin** [comment] 2020-03-13 13:47
What express middleware are you using to serve the audio files ? 

Right now we just use koa static to serve the files. Which is missing some features like stream / range headers and such. We will change this soon

**Comment by yaldram** [comment] 2020-03-13 13:51
@alexandrebodin Thanks for your reply Sir. I am not using any middleware of my own. Everything is strapi's default. Do you think that stream / range is causing these issues and if yes then how should I solve it using strapi. Plus why is this working with a normal express server. I am just uploading some mp3 m4a files to public folder and then accessing them from the browser and my fellow developers from thier IOS and Android Libraries respectively and it worked.

**Comment by alexandrebodin** [comment] 2020-03-13 13:52
I was asking what express middleware you are using when testing with express. By default express doesn't serve files. You must be using a lib. The one we are using for koa just doesn't provide the same features :)

**Comment by yaldram** [comment] 2020-03-13 13:54
@alexandrebodin I am using the following code : -
```javascript 
 app.use(express.static(path.join(__dirname, "public/uploads")));
```

**Comment by yaldram** [comment] 2020-03-13 13:55
@alexandrebodin Sir what should I do in order for the streaming to work with strapi ? Please suggest some method I have a delivery on Monday. Thanks

**Comment by alexandrebodin** [comment] 2020-03-13 14:37
You should add a custom middleware before the public one using koa-range until we add it. 

Read more about this [here](https://strapi.io/documentation/3.0.0-beta.x/concepts/middlewares.html#custom-middlewares-structure)

This is a duplicate of https://github.com/strapi/strapi/issues/2246. I'm going to close the issue so the discussion stays in one unique issue.

**Closed by alexandrebodin** 2020-03-13 14:37 UTC
