### ISSUE TITLE
Content manager infinite load on relations

### ISSUE THREAD

**Issue by masteralb** [strapi/strapi#2415] opened 2018-12-01 17:59 UTC
**What is the current behavior?**
Loading too slow
Screen unresponsive

**Steps to reproduce the problem**
- Create 2 content types
- Create relation between content types ( has many )
- Seed with some items ( i'm trying with 10.000)
- Navigate in content manager, select an item, wait for the results.

**What is the expected behavior?**
Expected a fast loading of the section, in fact the query is loading all documents. Too long, 2-3 minutes.

**Suggested solutions**
Checked: content-manager/explorer/{content-type}/{id}?source=content-manager
It is loading all documents from db, why is needed ?

**Tested on**
Node: 10.13.0
Strapi: 3.0.0-alpha.14.5,15,16
Mongo: 3.6.3
Google Chrome: 70.0.3538.110

**Comment by soupette** [comment] 2018-12-03 10:34
I think this is related to #2413 because the view queries 20 items by default.

**Comment by lauriejim** [comment] 2018-12-03 13:18
@masteralb Can you please try with last version of Strapi (`alpha.15`).

And I'm not able to reproduce your issue. Can you give us more details.
When you seed your data, did you create relations? If yes how many by entry?

**Comment by masteralb** [comment] 2018-12-03 19:50
@lauriejim 
My seeds are very basic ( just for testing ):

`{
        title: 'Test item ', 
        source: '5bfac7dd4cd71677a752e3e3', 
        date_created: new Date()
    }`

Below the relation between:

![screen shot 2018-12-03 at 8 38 53 pm](https://user-images.githubusercontent.com/2469369/49397405-c4b30d80-f73b-11e8-8667-29369c84c051.png)
![screen shot 2018-12-03 at 8 38 35 pm](https://user-images.githubusercontent.com/2469369/49397406-c54ba400-f73b-11e8-8741-2329615eaf8d.png)

I think this is very important, i'm planning to migrate a large database 1M+ Record, but i'm stuck with only 10K.

Debugger:
![screen shot 2018-12-03 at 8 45 12 pm](https://user-images.githubusercontent.com/2469369/49397617-62a6d800-f73c-11e8-8962-843ff3c9c865.png)

** Tried with `alpha.15` same result
![screen shot 2018-12-03 at 8 46 33 pm](https://user-images.githubusercontent.com/2469369/49397673-908c1c80-f73c-11e8-80ed-44a5ffef6b3e.png)

**Comment by lauriejim** [comment] 2018-12-05 12:47
Can you try with `alpha.16` version please and tell me if it still happen ?

**Comment by masteralb** [comment] 2018-12-09 13:00
Hi, the issue is still present. 
Thanks for your time!

**Comment by kamalbennani** [comment] 2018-12-09 17:51
Nested Relation items are not paginated! Strapi is trying to load every single relation which of course takes a lot of time/memory/CPU

**Comment by masteralb** [comment] 2018-12-09 18:07
@kamalbennani any way to preven this? Why is needed to load every relation?

**Comment by lauriejim** [comment] 2018-12-10 11:01
Actually it's not possible in the content manager.

But if you have an application you can use GraphQL with filters on relations.
There is not syntax with Strapi REST API  for now.

```
{
  events{
    _id
    name
    registrations (limit: 3, start: 1) {
      _id
      name
    }
  }
}
```

And why relations are needed ? Cause we have to display them in the right panel to let you delete one if you want.

**Comment by wemod123** [comment] 2019-05-30 12:49
How do you think to fix this issue?

**plan-A:**  as said - have to display them in the right panel to let you delete one if you want;
- pros:  let you delete one if you want.
- cons:  will destroy the ui, and not possible to edit any other field since it's too slow and possiblly timeout, or exceed some limitation (NGINX default limit for example).

**plan-B:**  only show 100 items as default for example, or configurable ( have an option to show how many items, or show all )
- pros: if configurable, perfect, if not, at least the other field is editable.
- cons: if not configurable, not able to delete one if you want.


In the real situation, if you have a item relation more than 1000 items do you think you will delete a single item in the right panel?


For example, I reproduced it as below, and it destroy the UI, not possible to edit other field.
If you never access the strapi admin to edit these records, it's totally fine, otherwise:
I have to remove the relation, and rebuild all front-end application data queries way.


![image](https://user-images.githubusercontent.com/26819270/58633660-aeb58c80-831b-11e9-8e9a-6bd2a835f1c6.png)

**Comment by inoisy** [comment] 2019-06-24 21:20
I have 10+k items and page fully stuck on loading when save.

**Comment by monkibraum** [comment] 2019-07-12 11:12
If you guys are using strapi beta and mongo, I guess this can be resolved by these steps.

1.  Add `"autoPopulate" : false` to each or target attribute in your api model( APINAME.settings.json)
2.  add a filter to `find`, `findOne` function in `/node_modules/strapi-plugin-content-manager/config/queries/mongoose.js ` like this.
 `.populate(populate || model.associations.filter(x => x.autoPopulate).map(x => x.alias).join(' '));`

**Comment by jacargentina** [comment] 2019-07-17 17:27
I think i have similar problem when editing `Roles` and its permissions. Having the `Authenticated` Role with many many users... it seems it loads all Users (full).

But weird is sometimes it loads... takes long... but other times it fails (Not an error but amd infinite loading indicator)

Any clues ?

**Comment by quentingllmt** [comment] 2020-01-05 12:39
Hey, I have the same issue with 1900+ items.
Why don't you add a simple option of not displaying/loading this relation in the content Manager ?

**Comment by CharlyMartin** [comment] 2020-01-20 15:30
@masteralb I'm curious to know how you seeded the database with 10k records. Are you using Strapi services?

I'm new to Strapi and, although I know the concept of a seed, I struggle to implement it. Thanks for your help 🙂

**Comment by masteralb** [comment] 2020-01-20 20:17
@CharlyMartin nothing special, just a for loop using https://github.com/marak/Faker.js/ using Strapi services of course.

Thanks

**Closed** 2020-01-20 20:18 UTC
Labels: priority: medium, type: enhancement 💅

**Comment by copocaneta** [comment] 2022-02-02 01:17
All duplicates (#3782, #2764) to this issue were closed referencing this issue here and now this issue is closed. This still happens on v4. As asked before, why don't you add a simple option of not displaying/loading this relation in the content Manager ?

**Comment by derrickmehaffy** [comment] 2022-02-02 05:34
The new issue is here: https://github.com/strapi/strapi/issues/12004
