### ISSUE TITLE
[BUG] - Content manager crashing when reordering dynamic-zone components with relational fields

### ISSUE THREAD

**Issue by LeoJoly** [strapi/strapi#15218] opened 2022-12-20 10:54 UTC
### Required System information

- Node.js version: ```14.20.0```
- NPM version: ```6.14.17```
- Strapi version: ```4.5.4```
- Database: ```mysql 8.0.31```
- Operating system: ```macOS Ventura 13.0```

### Describe the bug

The content manager crashes when I reorder dynamic-zone components if one of them contains a relational field.
This bug may also occur in the same situation when switching locale.

### Steps to reproduce the behavior

1. Create two collection-types
2. Create multiple components, one of theme should contain a relational field to the first collection-type
3. In the second collection-type, add a dynamic zone with the created components
4. Add some content in the content-manager
5. try reordering the dynamic-zone
6. Content-manager should crash and display the following error : "Whoops ! An error has occurred. Try Again."

### Expected behavior

The content manager should not crash we we change the order of the components in a dynamic zone

### Screenshots

Here is the bug
[![the bug](https://i.gyazo.com/f732c915b12928a1a2e08bc6bcec8857.gif)](https://gyazo.com/f732c915b12928a1a2e08bc6bcec8857)

Error in the console
[![console error](https://i.gyazo.com/47d04d7d469831e5883dd8761f62bb53.png)](https://gyazo.com/47d04d7d469831e5883dd8761f62bb53)

**Comment by joshuaellis** [comment] 2022-12-20 11:10
This is a duplicate of #14908

**Closed by joshuaellis** 2022-12-20 11:10 UTC
Labels: status: duplicate
