### ISSUE TITLE
Creating new project fails due to alpha version

### ISSUE THREAD

**Issue by michaelbutler** [strapi/strapi#18247] opened 2023-10-02 17:56 UTC
## Workaround

From @derrickmehaffy I've alerted the Strapi engineering team to the issue, for now the workaround is to use the strict version and not the `@latest` tag.

eg: `npx create-strapi-app@4.14.0 yourApp`

---

### Required System information

- Node.js version:  v18.18.0
- NPM version:  9.8.1
- Strapi version:  `@latest` as of Oct 2, 2023
- Database: sqlite
- Operating system:  Manjaro Linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Run the command to start a new project:

```
npx create-strapi-app@latest mystrapi --quickstart
```

We get the following error output:

```
Creating a quickstart project.
Creating a new Strapi application at /run/media/mbutler/SsdHome/IdeaProjects/mystrapi.
Creating files.
Error while installing dependencies:
warning @strapi/strapi > koa-body > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
warning @strapi/strapi > @strapi/admin > fork-ts-checker-webpack-plugin > memfs@3.6.0: this will be v4
warning @strapi/strapi > @strapi/admin > webpack-dev-server > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning @strapi/strapi > @strapi/plugin-email > @strapi/provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
warning @strapi/strapi > @strapi/plugin-email > @strapi/provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
error Couldn't find any versions for "@strapi/data-transfer" that matches "4.15.0-alpha.0"
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
Error: Couldn't find any versions for "@strapi/data-transfer" that matches "4.15.0-alpha.0"
    at MessageError.ExtendableBuiltin (/home/mbutler/.volta/tools/image/yarn/1.22.19/lib/cli.js:721:66)
    at new MessageError (/home/mbutler/.volta/tools/image/yarn/1.22.19/lib/cli.js:750:123)
    at Function.<anonymous> (/home/mbutler/.volta/tools/image/yarn/1.22.19/lib/cli.js:50351:13)
    at Generator.next (<anonymous>)
    at step (/home/mbutler/.volta/tools/image/yarn/1.22.19/lib/cli.js:310:30)
    at /home/mbutler/.volta/tools/image/yarn/1.22.19/lib/cli.js:321:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
    at /home/mbutler/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:67:28
    at Array.forEach (<anonymous>)
    at captureStderr (/home/mbutler/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/utils/usage.js:66:14)
    at createProject (/home/mbutler/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-project.js:136:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createQuickStartProject (/home/mbutler/.npm/_npx/2d56dd13733e9da7/node_modules/@strapi/generate-new/dist/create-quickstart-project.js:21:5)
```

### Steps to reproduce the behavior

1. Explained above, just run the quickstart command in a fresh directory.

### Expected behavior

Expected the command not to fail.

### Screenshots

n/a

### Additional context

Using `volta` to manage which node/npm/yarn binary is active.

**Comment by michaelbutler** [comment] 2023-10-02 18:03
Also tried:

```
yarn cache clean
```

but it failed for the same reason afterwards.

**Comment by derrickmehaffy** [comment] 2023-10-02 18:42
Ignore my custom script which just basically runs the same `npx create-strapi-app@latest` blah blah

![image](https://github.com/strapi/strapi/assets/8593673/3858855c-838c-4269-b1d1-e3df18bfd115)

**Comment by derrickmehaffy** [comment] 2023-10-02 18:49
Found the root cause, an alpha release got pushed to the latest tag: 
![image](https://github.com/strapi/strapi/assets/8593673/75355a6c-a47e-43f1-b253-65cddfe1768a)

**Comment by michaelbutler** [comment] 2023-10-02 18:55
@derrickmehaffy thank you! I thought it was something odd indeed. is there any workaround (e.g. maybe I can pin an older version?)

**Comment by derrickmehaffy** [comment] 2023-10-02 18:55
Yeah you can work around it `npx create-strapi-app@4.14.1 yourApp`
you just specify the version instead of the tag

**Comment by derrickmehaffy** [comment] 2023-10-02 20:08
We published v4.14.2 to solve this issue, sorry for the interruption. I'll go ahead and close this one. Thank you for letting us know!

**Closed by derrickmehaffy** 2023-10-02 20:08 UTC
Labels: issue: bug, severity: critical, status: confirmed, source: dependencies

**Comment by glacierck** [comment] 2023-10-13 06:03
v4.14.4 creating new project fails

**Comment by YuhanYue** [comment] 2023-12-18 12:09
> v4.14.4 creating new project fails `TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')`

same
