### ISSUE TITLE
Aggregate count function does not return expected value

### ISSUE THREAD

**Issue by danielmaartens** [strapi/strapi#6782] opened 2020-06-23 13:01 UTC
***Updated Post***
*There are two issues*
1. One is the inability to execute "OR" queries within graphql. This is not a bug but rather I do not know whether there is in fact a way to do this. If there is then it is not obvious to me based on the documentation. If there isn't then I will have to log the appropriate feature request.
2. The other is - what I consider to be, at least - a bug. The details of which are described below as per your template.

**Describe the bug**
Aggregate count function does not return expect value

**Steps to reproduce the behavior**

1. Go to the graphql playground
2. Execute a query with `where` parameters to filter the data and retrieve the aggregate "count" and "totalCount" values. E.g.:
![image](https://user-images.githubusercontent.com/49619761/85405983-6d64d000-b561-11ea-8bcd-3adbfceea67e.png)
3. Compare these values with the total count of entries in the database for the table/collection you are querying.

**Expected behavior**
`count` should reflect the total number of entries in the database based on the filter parameters in the query.
`totalCount` should reflect the total number of entries in the databased irrespective of the filter parameters.

**System**

- Node.js version: 12.18.1
- NPM version: 6.14.5
- Strapi version: 3.0.1
- Database: Mongo
- Operating system: MacOs Mojave (10.14.5) 

***Previous Post***
When I request the "count" parameter I expect it to return the total number of entries that match my specific query. But it is not. Instead it is returning the total number of entries in the database.

This is making it difficult for me to apply any sort of pagination. 

What is also making pagination difficult is the fact that I cannot do "or" queries in graphql. 

For example, we have an e-commerce client that has 3 different stores. They would like to submit blog posts either specific to a store or specify the post as a default across the stores. 

Currently I have to do two graphql queries - one to retrieve the default entries and one to retrieve the store specific entries. How am I supposed execute pagination in a situation like this ?

Could you please help me with the above two issues as soon as you can because we have a critical deadline in two days' time and this relatively simple feature is blocking us from providing the proper functionality across our site.

**Comment by danielmaartens** [comment] 2020-06-23 13:03
I am using v3.0.1

**Comment by alexandrebodin** [comment] 2020-06-23 13:08
Hello, Please follow the issue template so we have enough information to reproduce and help you. Closing until the issue is updated

**Comment by derrickmehaffy** [comment] 2020-06-23 13:43
(also please don't mass ping 4 members of the team. I've edited your post to remove those)

**Comment by danielmaartens** [comment] 2020-06-23 14:03
@alexandrebodin please see updated issue.

**Comment by derrickmehaffy** [comment] 2020-06-24 07:30
> One is the inability to execute "OR" queries within graphql. This is not a bug but rather I do not know whether there is in fact a way to do this. If there is then it is not obvious to me based on the documentation. If there isn't then I will have to log the appropriate feature request.

For this one see: https://github.com/strapi/strapi/issues/3194 the only `or` filter supported currently by default is the same field **and** filter else they are all treated as `and`, beyond that you may need to create a custom route or override the existing service and tweak the query to use the backend ORM yourself. See: https://strapi.io/documentation/v3.x/concepts/queries.html#custom-queries

For more info on the discussion about filtering see: https://github.com/strapi/strapi/discussions/4906

**Comment by alexandrebodin** [comment] 2020-06-26 07:40
Hello, You aren't sharing the query nor the model you are running you query with so we cannot reproduce your issue.

**Comment by derrickmehaffy** [comment] 2020-10-15 14:16
As we have no updated information from the user, marking as closed.

**Closed by derrickmehaffy** 2020-10-15 14:16 UTC
Labels: type: help wanted
