### ISSUE TITLE
Dynamic zone: "This attribute must be unique" error on update

### ISSUE THREAD

**Issue by perostlin** [strapi/strapi#17649] opened 2023-08-11 12:55 UTC
### Required System information

- Node.js version: v16.15.1
- NPM version: 8.11.0
- Strapi version: 4.12.1
- Database: Postgres
- Operating system: macOS
- Is your project Javascript or Typescript: Javascript

### Describe the bug

"This attribute must be unique" error on update when having components with unique string field.

We have a content type called **Page** with a dynamic zone called **Blocks**, inside the **Blocks** we have a component called **CTA** which looks like below:
title: string
description: string
key: string, unique (**not a UID field**)

When we create a new **Page**, we can easily add different **Blocks**, in this case multiple **CTA** components with data like below:  

**First**
title: Home
description: Welcome to our homepage!
key: home

**Second**
title: About
description: About us
key: about

But when we try to update the title for one of the **CTA** components we get the following error:
<img width="458" alt="image" src="https://github.com/strapi/strapi/assets/20464832/0999d1e8-4c30-4b8b-b783-fa2260680320">

### Steps to reproduce the behavior

1. Setup a Strapi project.
2. Add a new content type called **Page**
3. Add a dynamic zone to the newly created content type called **Blocks**
4. Add a component to the newly created dynamic zone called **CTA**, with the following fields:
title: string
description: string
key: string, unique (**not a UID field**)
5. Create a new page called **Home**
6. Add two **CTA** components to the **Blocks** under the newly created page.
7. Save it.
8. Then try changing the title for one of the **CTA** components, then save it again.

### Expected behavior

We wish to be able to update the components which has unique string fields without getting this error.
This error indicates that there are already a component with that value for it's unique field.
Which is not the case since it's the only one, we are just trying to update it.

**Comment by alizaeda** [comment] 2023-09-10 21:22
I'm facing the same issue, any solution?

**Comment by mitchellhalliday** [comment] 2023-09-18 06:07
Same here - Specifically, it only seems to be an issue for me when this is set within a component.

**Comment by calvinrbnspiess** [comment] 2023-09-27 07:13
This also happens when trying to save repeated content types inside a dynamic zone, this means you cannot modify or add more items.

An easy workaround was it to remove the unique attribute. However, this means you can freely add items and this likely leads to duplicated entries. A real fix would be favourable.

**Comment by derrickmehaffy** [comment] 2023-10-10 14:04
elevating sev based on TID 4974

**Comment by derrickmehaffy** [comment] 2023-10-13 14:05
Duplicate of https://github.com/strapi/strapi/issues/12541

**Closed by derrickmehaffy** 2023-10-13 14:05 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:strapi, source: core:content-manager, flag: EE
