### ISSUE TITLE
Confusing character limit warning message

### ISSUE THREAD

**Issue by lgnov** [strapi/strapi#4932] opened 2020-01-08 04:16 UTC
**Describe the bug**
While putting content to a text field, if the input is longer than the maximum length limit, it shows an warning message of `This is too high` which I feel very confusing. Similar situation to go below minimum length limit where it shows `This is too small`.

**Steps to reproduce the behavior**
1. Create a text field with maximum/minimum length of 5 enabled.
2. Add content to the text field with more/less than 5 characters.
3. Click any empty space.
4. The warning shows as below in the screenshots.

**Expected behavior**
`too long` and `too short` are more appropriate.

**Screenshots**
![long](https://user-images.githubusercontent.com/47930782/71949738-93e8a780-3189-11ea-8668-75b640d2c741.PNG)
![short](https://user-images.githubusercontent.com/47930782/71949742-95b26b00-3189-11ea-8e42-c73d88ae9adf.PNG)

**Code snippets**
N/A

**System**
- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.3
- Database: PostgreSQL
- Operating system: Windows

**Additional context**
N/A

**Comment by soupette** [comment] 2020-01-08 09:28
Hi @lgnov I totally agree! But in fact, I have check and the issue is coming from [Buffet.js](https://buffetjs.io/) our new component library. So I will close this issue for now but do you mind reopening it on the other [repository](https://github.com/strapi/buffet)?

**Closed by soupette** 2020-01-08 09:28 UTC

**Comment by lgnov** [comment] 2020-01-08 21:01
Sure! A new issue was open to [#72](https://github.com/strapi/buffet/issues/72#issue-547096352). Thank you @soupette .
