### ISSUE TITLE
s3 upload provider private bucket does not work with s3-compatible storage

### ISSUE THREAD

**Issue by sjoukedv** [strapi/strapi#16331] opened 2023-04-08 08:11 UTC
### Required System information

- Node.js version: n.a.
- NPM version: n.a.
- Strapi version: 4.9.0
- Database: n.a.
- Operating system: n.a.
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I am using a private S3-compatible bucket hosted on DigitalOcean the host is in the form of `https://<bucket>.ams3.cdn.digitaloceanspaces.com` which does not match the predefined RegExp [`/^(.+\.)?s3[.-]([a-z0-9-]+)\./`](https://github.com/strapi/strapi/blob/main/packages/providers/upload-aws-s3/lib/utils.js#L3) as the URL does not contain `s3` and therefore it will skip the signing process:

```javascript
      getSignedUrl(file, customParams = {}) {
        // Do not sign the url if it does not come from the same bucket.
        const { bucket } = getBucketFromUrl(file.url);

        if (bucket !== config.params.Bucket) { <-- this will always be true because bucket is null
          return { url: file.url };
        }
        ....
      }
```

If I comment out this section it works as expected.

### Steps to reproduce the behavior

1. Example plugin configuration
```javascript
export default ({ env }) => ({
    upload: {
      config: {
        provider: 'aws-s3',
        providerOptions: {
          baseUrl: env('DO_AWS_CDN_URL'),
          rootPath: env('CDN_ROOT_PATH'),
          s3Options: {
            accessKeyId: env('DO_AWS_ACCESS_KEY_ID'),
            secretAccessKey: env('DO_AWS_ACCESS_SECRET'),
            region: env('DO_AWS_REGION'),
            endpoint: env('DO_AWS_ENDPOINT'),
            params: {    
              ACL: 'private',
              signedUrlExpires: 60 * 60 * 24 * 7,
              Bucket: env('DO_AWS_BUCKET'),
            }
          }
        },
      },
    },

```

2. Upload a media object
3. See broken link in `/admin/plugins/upload?sort=createdAt:DESC&page=1&pageSize=10`

### Expected behavior

Retrieve a signedUrl of every media object.

### Suggested solution(s)

- Change the RegExp to support S3-compatible urls OR remove the bucket check and handle error if you are trying to get a signed url for a different bucket.
- Add tests for this plugin with a S3-compatible provder

**Comment by sjoukedv** [comment] 2023-04-08 08:14
Related to #16245 and there is an open PR #16256

**Comment by Eventyret** [comment] 2023-04-11 09:35
Closing this issue as it's a duplicate of #16245 as @sjoukedv just said.

**Closed by Eventyret** 2023-04-11 09:35 UTC
