### ISSUE TITLE
Setting autoPopulate to false on relations does not return ids.

### ISSUE THREAD

**Issue by loongmxbt** [strapi/strapi#4630] opened 2019-11-30 06:06 UTC
**Describe the bug**
I need to add `autoPopulate: false` to relational fields (one-to-many), and later get the data.
E.g. Project has many Reports, when I add `"autoPopulate": false` to `reports`, then the whole reports field won't return. I hope to know the ids for further use.
```
"reports": {
      "collection": "report",
      "via": "project",
      "autoPopulate": false
    },
```
In N-1 relation, if set `autoPopulate: false`, it will return the id, e.g. `project: 1`.
This problem occurs when the field is 1-N and N-N relations. The field won't return.

**Steps to reproduce the behavior**
1. Go to a one-to-many relational fields, e.g. Project has many reports
2. Add `autoPopulation: false` to reports field
3. GET /projects/1
4. The report field doesn't return.

**Expected behavior**
I think it should behave the same, return `reports: [1, 2, 3]` or `reports: [{id: 1}, {id: 2}, {id: 3}]`

**Screenshots**

**Code snippets**
```
{
  "connection": "default",
  "collectionName": "projects",
  "info": {
    "name": "project",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": [
      "created_at",
      "updated_at"
    ],
    "comment": ""
  },
  "attributes": {
    "name": {
      "unique": true,
      "required": true,
      "type": "string"
    },
    "reports": {
      "collection": "report",
      "via": "project"
    },
    "comments": {
      "collection": "comment",
      "via": "project"
    }
  }
}
```

**System**
- Node.js version: 10.16.1
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.6
- Database: SQLite
- Operating system: Windows

**Additional context**

**Comment by derrickmehaffy** [comment] 2019-11-30 11:30
Please completely fill out the required template, including the versions. Once you have updated the issue and correctly followed the template this can be reopened.

**Comment by loongmxbt** [comment] 2019-11-30 13:52
@derrickmehaffy Sorry, I have modifed the issue.

**Comment by jonpalmisc** [comment] 2020-06-12 13:42
Any update or workaround on this? I'm having the same issue.

**Comment by jonpalmisc** [comment] 2020-06-13 14:56
I'm not familiar with the Strapi code base, but I would be more than happy to try to fix this myself if you could point me in the right direction! @derrickmehaffy

**Comment by mizvyt** [comment] 2020-07-02 01:42
I am facing the same issue on many-to-one relationship:
An Article has a Topic, but the Topic does not show up when editing this Article if "autoPopulate" on "topic" within "article" is set to false. 

![image](https://user-images.githubusercontent.com/43022287/86306951-1db09380-bc48-11ea-8ea6-d55d44b64e5e.png)

If we click "Details" on the above, we get a nasty error in the dashboard, as it's trying to navigate to `help-topic/undefined`.

This requires me to set the property to "private" instead, but then I don't get the ID of the Topic returned in REST of course...

**Comment by balmacefa** [comment] 2021-05-06 17:08
Any progress on this? Does anybody have a workaround?

**Comment by derrickmehaffy** [comment] 2021-05-07 17:47
@balmacefa this is something we are planning to look at in the Strapi v4 version along with the major database changes coming in Q3

**Comment by alightgoesout** [comment] 2021-05-13 15:34
My workaround was to let `autopopulate` as `true` but to replace the items by their ids using the `afterFind` lifecycle hook. It's not ideal since the whole item is still retrieved from the database, but the json response only contains the ids.

**Comment by derrickmehaffy** [comment] 2021-08-11 10:44
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/rest-api-retrieve-id-only-ids-of-relations/3399/5

**Comment by dasw3** [comment] 2021-08-11 10:53
> This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:
> 
> https://forum.strapi.io/t/rest-api-retrieve-id-only-ids-of-relations/3399/5

Derrick, I linked the Strapi community to this issue, there is no solution there. Now it is just circular references to the same issue in multiple areas.

**Comment by Convly** [comment] 2021-08-11 13:52
> > This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:
> > https://forum.strapi.io/t/rest-api-retrieve-id-only-ids-of-relations/3399/5
> 
> Derrick, I linked the Strapi community to this issue, there is no solution there. Now it is just circular references to the same issue in multiple areas.

This is an automated reply when an issue is mentioned on the forum :wink:

**Comment by Convly** [comment] 2021-08-11 13:54
I'll also link Alex's answer posted in a duplicate of this issue:
https://github.com/strapi/strapi/issues/7361#issuecomment-671358371

**Comment by derrickmehaffy** [comment] 2021-12-22 19:59
autopopulate doesn't exist anymore, closing

**Closed by derrickmehaffy** 2021-12-22 19:59 UTC
Labels: issue-type: bug, severity: medium, status: confirmed, source: core:strapi
