### ISSUE TITLE
The return type of findMany is incorrect

### ISSUE THREAD

**Issue by rktyt** [strapi/strapi#18516] opened 2023-10-20 01:46 UTC
### Required System information

- Node.js version: 18.18.2
- NPM version: 9
- Strapi version: 4.14.5
- Database: MySQL8
- Operating system: Debian12
- Is your project Javascript or Typescript: Typescript

### Describe the bug

```typescript
const items = await strapi.entityService.findMany(uid)
```

The type of items is as follows

```typescript
GetValues<"api::xxxx.xxxx", string> | GetValues<"api::xxxx.xxxx", string>[]
```

I think there never be a non-array result.

### Expected behavior

It should be of the following type
```typescript
GetValues<"api::xxxx.xxxx", string>[]
```

**Comment by Sohailsaifi** [comment] 2023-10-22 16:19
Can I attempt this?

**Comment by Eventyret** [comment] 2023-10-23 08:28
Thank you for submitting this. I'm unable to reproduce this.
Using the following

```typescript
  const items = await strapi.entityService.findMany("api::test.test")
```
I will get this type
```typescript
GetValues<"api::test.test", GetNonPopulatableKeys<"api::test.test">>[]
```

This would be helpful if you could provide more information on how you got a singular type or what your `uid` is.

Closing this for now, but if you have further information, please add more steps.

**Comment by rktyt** [comment] 2023-10-23 09:54
@Eventyret 
The `uid` is for collections already created before the update.
And the location of the code will be in the plugin.

I tried a new one with the following command
```
npx create-strapi-app@latest my-project --quickstart --typescript
npx strapi generate
```

I added the code to the following generated file
`src/plugins/dummy/server/services/my-service.ts`

The code is as follows
```typescript
const items = await strapi.entityService?.findMany('admin::user')
```

Then the type is as follows
```typescript
GetValues<"admin::user", string> | GetValues<"admin::user", string>[] | null | undefined
```

----

I was able to solve this by adding `types/generated` to the `tsconfig.json` of the plugin.

**Comment by innerdvations** [comment] 2023-11-02 11:48
It is possible for findMany to return a single item for Single Type content types.

So the problem is that without including the generated types, it's impossible to know if the requested uid is a single type or not. With the generated types, Strapi can see that that content type is not a single type, and can then be more precise in its types.

We're working on improving documentation for Typescript so hopefully this becomes more clear in the future!

**Closed by innerdvations** 2023-11-02 11:48 UTC
Labels: status: can not reproduce, source: typescript
