### ISSUE TITLE
3.5.2 breaks dynamic zone's relation population.

### ISSUE THREAD

**Issue by alaminut** [strapi/strapi#9578] opened 2021-03-02 23:27 UTC
### Describe the bug

When you have a component that has a relation to a model and if you use that component in another model's dynamic zone. Your rest and graphql queries do not populate dynamic zone's related model's properties. It only returns object id references (in rest) or null (in gql)

### Steps to reproduce the behavior

Please use this repository to reproduce this bug: https://github.com/alaminut/strapi-bug-repro

1. Create a "Product" with "name" and "description" components filled.
2. Create a "Celebrity" and add a "ProductDefinition" component to its dynamic zone.
3. Use REST or GQL endpoints to query "Celebrities" and see "LocalizedValue" and "Locale" fields are null in GQL, an array of ids in REST

Sample GQL query for reproduction

```
query {
  celebrities {
    id,
    Fullname,
    products {...prd}
  }
}

fragment prd on ComponentSalesProductDefinition {
  Price,
  product {
    id,
    systemName,
    name {
      LocalizedValue,
      Locale
    }
  }
}
```

### Expected behavior

Related model fields should be populated properly in the dynamic zone.

![image](https://user-images.githubusercontent.com/3727398/109728827-fee41180-7bc7-11eb-9c20-0d0b1349137d.png)

### System

- Node.js version: LTS
- Yarn version: 1.22.10
- Strapi version: 3.5.2
- Database: MongoDB (mongoose)
- Operating system: Windows

This problem did not exist in 4.6 which was the previous version I was using.

**Comment by shtelzerartem** [comment] 2021-03-03 14:23
It's likely to be same issue an described here #9451 broken by this PR #9464

Description and link to reproduction repo [here](https://github.com/strapi/strapi/issues/9451#issuecomment-785229133)

**Comment by alexandrebodin** [comment] 2021-03-03 14:26
Hello @alaminut this is indeed a duplicate of https://github.com/strapi/strapi/pull/9588. I'm going to close this one so everything is in the same place.

**Closed by alexandrebodin** 2021-03-03 14:26 UTC

**Comment by alaminut** [comment] 2021-03-03 16:53
Hello @aleksandryackovlev yeah this is the same issue thanks for mentioning. I'll follow the other issue and even try help solving it if I am able as this is kind of a road block for me at the moment.
