### ISSUE TITLE
[V4] Relation not showing up in API response

### ISSUE THREAD

**Issue by eliasto** [strapi/strapi#11765] opened 2021-12-02 13:38 UTC
### Describe the bug

When a relation is added in the user collection from users-permissions, the relation is not showed up in the API response.

### Steps to reproduce the behavior
- Create a collection
- Add it in the user collection
- Get the API response from any endpoint, like /users/me

### Expected behavior

- The flag collection should be there.

### Screenshots

![image](https://user-images.githubusercontent.com/55650958/144432542-0a9fb6c8-ab36-48a8-831a-f3ae659d83bf.png)

![image](https://user-images.githubusercontent.com/55650958/144432526-f1c4f8e0-2929-4996-8feb-45c249da57d4.png)

![image](https://user-images.githubusercontent.com/55650958/144432493-7a12e264-fcce-40ce-9da7-cf57c88a3cef.png)

![image](https://user-images.githubusercontent.com/55650958/144433062-fb61087d-fcf5-4b13-84a3-03ab54c14a9d.png)

### System

- Node.js version: 16.13.0
- NPM version: 8.1.0
- Strapi version: 4.0.0
- Database: default one
- Operating system: windows 11

**Comment by Convly** [comment] 2021-12-02 14:00
Hi, did you give access to flags & alumni content types to your role in the users-permissions plugin?
If you don't have the permission to find or findOne a flag or alumni, you won't be able to populate them as relations from another CT.

**Comment by eliasto** [comment] 2021-12-02 14:07
> Hi, did you give access to flags & alumni content types to your role in the users-permissions plugin? If you don't have the permission to find or findOne a flag or alumni, you won't be able to populate them as relations from another CT.

Hi, thanks for your answer! I checked. For testing purposes I selected everything:

![image](https://user-images.githubusercontent.com/55650958/144437544-4229dd3d-ca9d-4eda-8f15-ace5aff02f5b.png)

![image](https://user-images.githubusercontent.com/55650958/144437593-3f251625-bdeb-4a30-ae42-d614415bc583.png)

**Comment by Convly** [comment] 2021-12-02 14:56
Oh, I didn't notice your request was on the U&P `/me` route, my bad. The controller's method that handles the request is a custom one (not an auto-generated content-API route) and it doesn't handle filters, populate & co.

Two options are available:
- You can create a custom controller that makes use of the `ctx.state.user.id` to make a `findOne` request to the entity service with additional args (populate, fields & co)
- You can customize the service that fetches & set the `ctx.state.user` variable in the U&P authentication strategy.

If you think it would be better to directly allow passing arguments to the `/me` handler, please open a feature request. Note that it probably won't be a high priority though as we're a bit busy handling more urgent issues & bugs linked to the V4 release.

Hope it's clear for you, I'll close this issue as it's the intended behaviour, but feel free to comment and I'll do my best to answer you.

**Closed by Convly** 2021-12-02 14:56 UTC
