### ISSUE TITLE
Docker container crashes: The Strapi admin needs to install not required react and other packages

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#18648] opened 2023-11-02 14:41 UTC
```
 => ERROR [strapi 10/10] RUN ["yarn", "build"]                                                                             1.1s
------
 > [strapi 10/10] RUN ["yarn", "build"]:
0.227 yarn run v1.22.19
0.246 $ strapi build
1.076 [INFO] The Strapi admin needs to install the following dependencies:
1.076    - react@^18.0.0
1.076   - react-dom@^18.0.0
1.076   - react-router-dom@^5.0.0
1.076   - styled-components@^5.0.0
1.080 ? Would you like to install these dependencies now? These are not required but
1.080 are recommended, from V5 these will be required. (Y/n)                                                                   error Command failed with signal "SIGINT".
1.096 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: process "yarn build" did not complete successfully: exit code: 1
```

I can't build my container now.

My package.json for Strapi:

```
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "dev": "strapi dev",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-graphql": "^4.15.0",
    "@strapi/plugin-documentation": "^4.15.0",
    "@strapi/plugin-i18n": "^4.15.0",
    "@strapi/plugin-users-permissions": "^4.15.0",
    "@strapi/strapi": "^4.15.0",
    "pg": "^8.11.3"
  }
}

```

**Comment by joshuaellis** [comment] 2023-11-02 14:52
Thanks for the report! So you're trying to build strapi, what's your NODE_ENV?

**Comment by teinett** [comment] 2023-11-02 14:53
NODE_ENV: development

**Comment by teinett** [comment] 2023-11-02 14:56
I am not deploying. I do it on my local machine.

docker-compose.yml:
```
version: '3'

services:


  strapi:
    build: 
      context: .
      dockerfile: ./dockerfiles/strapi.dockerfile
    image: strapi:latest
    container_name: strapi_${PROJECT_NAME}
    ports:
      - "1337:1337"
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - database
      - redis
    environment:
      NODE_ENV: development
      DB_HOST: database
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    volumes:
      - ./strapi/config:/strapi/app/config
      - ./strapi/src:/strapi/app/src
      - ./strapi/package.json:/strapi/package.json
      - ./strapi/yarn.lock:/strapi/yarn.lock
      - ./.env:/strapi/app/.env
      - ./strapi/public:/strapi/app/public
      - ./strapi/public/uploads:/strapi/app/public/uploads
    networks:
      - strapi-astro-network

  database:
    image: postgres:14-alpine
    platform: linux/amd64 #for platform error on Apple M1 chips
    container_name: postgres_${PROJECT_NAME}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi-astro-network

networks:
  strapi-astro-network:
    driver: bridge

```

**Comment by teinett** [comment] 2023-11-02 14:57
strapi.dockerfile:

```
# Use an official Node runtime as the base image
FROM node:18-alpine AS runtime

# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Set the working directory in the container to /strapi
WORKDIR /strapi

# Copy package.json and package-lock.json into the directory /app in the container
# COPY strapi/package*.json ./
# COPY strapi/yarn.lock ./

COPY ./strapi/package*.json ./
COPY ./strapi/yarn.lock ./


# Add user node to /strapi ownership
RUN chown -R node:node /strapi
USER node

# Install dependencies
# RUN yarn config set network-timeout 600000 -g && yarn install
# Install dependencies and node-gyp
RUN yarn config set network-timeout 600000 -g && yarn global add node-gyp && yarn install


ENV PATH /strapi/node_modules/.bin:$PATH

WORKDIR /strapi/app

COPY --chown=node:node ./strapi/ .


RUN ["yarn", "build"]

EXPOSE 1337
CMD ["yarn", "develop"]
```

**Comment by joshuaellis** [comment] 2023-11-02 15:01
I would do what it asks you then, since you have the project locally incl. package.json add:

```json
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3"
```

to your project and run your install command to update the lock file, happy to hear how we could make this process better for development Docker users – we don't trigger the warning / request in Production but we do want it in dev to ease the transition from v4 -> v5 :)

**Comment by cooperwfloyd** [comment] 2023-11-02 15:08
getting a similar error right after 4.15.1 dropped
```
Building admin panel[ERROR] Module not found: Error: Package path ./admin/src/content-manager/utils is not exported from package ~/Documents/work-files/strapi/backend/node_modules/@strapi/admin (see exports field in ~/Documents/work-files/strapi/backend/node_modules/@strapi/admin/package.json)
```

**Comment by teinett** [comment] 2023-11-02 15:09
I truly appreciate the effort you and the team put into improving Strapi. However, the latest version has disrupted the functionality of my project. My primary concern is that I prefer not to invest time and resources preparing my project for elements that may or may not be included in future updates.

If Strapi requires certain dependencies, it would be immensely helpful if those dependencies could be integrated into the project, or if the instructions could be updated along with a migration document. Currently, the preparation for future updates is causing issues with my project's stability.

I believe we can find a solution that balances both the need for progress and the stability of existing projects like mine. Your assistance in addressing this matter would be greatly appreciated.

Thank you for your understanding and support.

**Comment by cooperwfloyd** [comment] 2023-11-02 15:16
getting a similar error right after 4.15.1 dropped. can't run an install anymore without getting this error and I'm not able to force `~14.5.0` anymore for some reason in my package.json. please revert `14.5.1` or correct the dependency issue, all of my strapi projects are unusable currently and this has happened many times where a non-breaking change version introduces breaking changes.
```
Building admin panel[ERROR] Module not found: Error: Package path ./admin/src/content-manager/utils is not exported from package ~/Documents/work-files/strapi/backend/node_modules/@strapi/admin (see exports field in ~/Documents/work-files/strapi/backend/node_modules/@strapi/admin/package.json)
```

**Comment by Yum1x** [comment] 2023-11-02 15:21
also getting error on this new release:
 ```
│ TypeError: Cannot destructure property 'env' of 'undefined' as it is undefined.                                                                                    │
│       at plugins_default (<SYSTEM_PATH>\config\plugins.ts:2:19)
...
```

**Comment by joshuaellis** [comment] 2023-11-02 15:24
> My primary concern is that I prefer not to invest time and resources preparing my project for elements that may or may not be included in future updates.

It will be included, they will be mandatory from V5, the reason we no longer want to include them is because we're not going to be aliasing dependencies from V5 – or when we introduce a new bundler e.g. vite, so you are investing time in what's going to happen. 

> I believe we can find a solution that balances both the need for progress and the stability of existing projects like mine.

Like I said, we don't run this in production & i'm opening to suggestions about handling Docker where this would be an issue in development only.

**Comment by joshuaellis** [comment] 2023-11-02 15:25
> getting a similar error right after 4.15.1 dropped. can't run an install and build anymore without getting this error and I'm not able to force `~14.5.0` anymore for some reason in my package.json. I've added the suggested react and styled components dependencies too. please revert `14.5.1` or correct the dependency issue, all of my strapi projects are unusable currently and this has happened many times where a non-breaking change version introduces breaking changes.
> 
> ```
> Building admin panel[ERROR] Module not found: Error: Package path ./admin/src/content-manager/utils is not exported from package ~/Documents/work-files/strapi/backend/node_modules/@strapi/admin (see exports field in ~/Documents/work-files/strapi/backend/node_modules/@strapi/admin/package.json)
> ```

You should open a new issue because your error message is unrelated to this issue.

**Comment by joshuaellis** [comment] 2023-11-02 15:25
> also getting error on this new release:
> 
> ```
> │ TypeError: Cannot destructure property 'env' of 'undefined' as it is undefined.                                                                                    │
> │       at plugins_default (<SYSTEM_PATH>\config\plugins.ts:2:19)
> ...
> ```

You should open a new issue because your error message is unrelated to this issue.

**Comment by joshuaellis** [comment] 2023-11-14 08:54
This was already fixed in the latest release by using the argument `ignorePrompts`.

**Closed by joshuaellis** 2023-11-14 08:54 UTC
Labels: issue: bug, severity: medium, source: core:admin, status: pending reproduction

**Comment by AdrianFahrbach** [comment] 2023-11-24 20:52
> This was already fixed in the latest release by using the argument `ignorePrompts`.

@joshuaellis Please completely remove the prompt and don't just automatically say no.
Going through the filesystem comparing package.json files is a bad idea. I had issues with this with [@phosphor/react](https://github.com/phosphor-icons/homepage) as well because it couldn't find the package.json and was stuck at an index.js, but I can't reproduce this now (and don't want to put anymore time into this). This also gets especially more difficult with monorepos.

In addition to that the `ignorePrompts` argument (which is actually `--ignore-prompts`) is documented nowhere. I was about to open a new issue for this until I found this one (and all the others).

I would also recommend to remove the custom error log window, since this cuts off file links and makes it difficult to open the files in VSCode. See screenshot below:
![screenshot 2023-11-24 at 21 33 19@2x](https://github.com/strapi/strapi/assets/45072099/ac21dc7d-b99b-40ae-8643-248c9600da5e)

I appreciate your effort and I see where this is coming from, since I've been there as well. It is fun to add prompts like this or custom error loggers, but this is not the right project for this. This just adds unnecessary complexity that breaks stuff for others. You should try to keep it as simple as possible and check how other large CMS/frameworks are doing stuff like that.

Again, I really appreciate your effort, but I have to add that it's crazy that stuff like that repeatedly makes it into production. I had broken projects because an icon got renamed from `image` to `picture`, dug hours through your source code to get what stuff does and to this day don't understand how your design system can be documented so badly. I randomly found docs about your hooks [here](https://contributor.strapi.io/) today (after 2 years of developing with Strapi!).
In my opinion, you got to change a lot about your DX fast if you don't want to get rolled over by Payload in a few years.

**Comment by teinett** [comment] 2023-11-24 23:36
> This was already fixed in the latest release by using the argument `ignorePrompts`.

@joshuaellis How exactly and where should I use this flag? Could you give us a link with documentation, please?

**Comment by psoleckimoj** [comment] 2023-12-12 20:28
We're now getting this, originally updating to 4.15.5, but now reverting makes no difference. If they're required and the project won't build without them then they need to be in dependencies.

**Comment by teinett** [comment] 2023-12-27 07:18
I changed my `strapi.dockerfile`:

```
# Use an official Node runtime as the base image
FROM node:18-alpine AS runtime

# Installing libvips-dev for sharp Compatibility
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Set the working directory in the container to /strapi
WORKDIR /strapi

# Copy package.json and package-lock.json into the directory /app in the container
# COPY strapi/package*.json ./
# COPY strapi/yarn.lock ./

COPY ./strapi/package*.json ./
COPY ./strapi/yarn.lock ./


# Add user node to /strapi ownership
RUN chown -R node:node /strapi
USER node

# Install dependencies
# RUN yarn config set network-timeout 600000 -g && yarn install
# Install dependencies and node-gyp
RUN yarn config set network-timeout 600000 -g && yarn global add node-gyp && yarn install


ENV PATH /strapi/node_modules/.bin:$PATH

WORKDIR /strapi/app

COPY --chown=node:node ./strapi/ .


RUN ["yarn", "build", "--ignore-prompts"]

EXPOSE 1337
CMD ["yarn", "develop"]

```

It was: `RUN ["yarn", "build"]`
Now: `RUN ["yarn", "build", "--ignore-prompts"]`

It didn't help. 
Docker constantly tried to work, but crashed: http://localhost:1337 didn't answer.

**The only solution now**: change `package.json` and add packages.

```
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "dev": "strapi dev",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-graphql": "^4.16.2",
    "@strapi/plugin-documentation": "^4.16.2",
    "@strapi/plugin-i18n": "^4.16.2",
    "@strapi/plugin-users-permissions": "^4.16.2",
    "@strapi/strapi": "^4.16.2",
    "pg": "^8.11.3",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^5.2.0",
    "styled-components": "^5.2.1"
  }
}
```

**Comment by suciueus** [comment] 2024-01-09 10:43
This is solved by adding the packages in package json:
```
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "5.3.4",
    "styled-components": "5.3.3"
```

 Is there an option to ignore these prompts or apply the changes automatically? This broke the pipeline which is not desirable.

**Comment by psoleckimoj** [comment] 2024-01-09 10:53
They're not even up-to-date versions of some of those modules either.

**Comment by rohankhudedev** [comment] 2024-01-12 19:05
![image](https://github.com/strapi/strapi/assets/17717700/9c6feca5-5b53-4434-85ef-05acd351be08)
Same here when pdating from 14.15.0 to 14.17.0

**Comment by suciueus** [comment] 2024-01-12 19:28
> 14.17.0. Even when upgrading to 14.16.2

Apply the fix above (add those dependencies manually in package.json for now)

**Comment by joshuaellis** [comment] 2024-01-12 19:34
You can also use '--ignore-prompts'

**Comment by suciueus** [comment] 2024-01-12 19:37
> You can also use '--ignore-prompts'

I don't think that works. The flag is not in Strapi docs either.

**Comment by falnos24865** [comment] 2024-01-27 06:32
I'm sad to see this closed. This issue caused our clients sites to break for hours since this message started appearing out of no where (we did not change versions on anything). This has been the final straw and will be switching away from Strapi. This message was a big mistake.

**Comment by teinett** [comment] 2024-01-27 20:07
> You can also use '--ignore-prompts'

This doesn't work. I tried it in many different forms.

**Comment by awesomedevv** [comment] 2024-01-29 16:48
I am currently in the process of upgrading from version 4.15.0 to 4.19.0. 
I encountered a similar issue as yours.
![image](https://github.com/strapi/strapi/assets/4244850/e2231801-6fdc-4162-bd9c-932df0a82dc5)

@joshuaellis, may I ask you a quick question? 
If it's alright with you, shouldn't we perform upgrades within the version 4 series? 
What I mean is, do we need to wait until version 5 is released before addressing this while NODE_ENV issue is not resolving?

> > NODE_ENV: development
> 
> but you're deploying strapi? so shouldn't it be `NODE_ENV=production`?

**Comment by web-admin** [comment] 2024-01-30 10:53
I use Docker & NX monorepo and had the same issue... I solved it by adding manually these modules to package.json as @suciueus mentioned.

**Comment by cisasmendi** [comment] 2024-02-13 02:23
también  estoy teniendo el mismo problema tenia andando los Docker en producción con la versión 4.6.1 y salieron los mismo errores.
