### ISSUE TITLE
plugin-color-picker not supported on version 4.5.3

### ISSUE THREAD

**Issue by flashcatz** [strapi/strapi#15089] opened 2022-12-06 07:17 UTC
### Required System information

- Node.js version: v16.14.2
- NPM version: 8.5.0
- Strapi version: 4.5.3
- Database: mysql
- Operating system: MacOS

### Describe the bug

Color picker plugin not working when updating strapi from 4.5.2 to 4.5.3.

### Steps to reproduce the behavior

1. After update to 4.5.3 from 4.5.2
2. Go to the Content Manager page and select the page where the color picker plugin is used.

### Expected behavior

The color picker UI is displayed.

### Screenshots

![plugin-color-picker-453-not-support](https://user-images.githubusercontent.com/16275137/205844847-0ee7ce0b-ce6d-48ff-bb31-741babd5f257.png)

**Comment by gu-stav** [comment] 2022-12-06 07:27
Duplicate of https://github.com/strapi/strapi/issues/15053 This issue will be fixed by the next version. Thank you for reporting it!

**Closed by gu-stav** 2022-12-06 07:27 UTC

**Comment by quyennt21** [comment] 2022-12-15 13:49
Plugin error when update strrapi 4.5.4

**Comment by gu-stav** [comment] 2022-12-15 16:38
@quyennt21 Did you re-build the admin app after the update?

**Comment by quyennt21** [comment] 2022-12-28 15:01
> @quyennt21 Did you re-build the admin app after the update?

yes, I build and run on docker
