### ISSUE TITLE
Component list does not show all components, when adding a component field

### ISSUE THREAD

**Issue by sl-env** [strapi/strapi#16003] opened 2023-03-06 12:58 UTC
### Required System information

- Node.js version: 18.13.0
- NPM version: 8.19.3
- Strapi version: 4.7.1
- Database: sqlite
- Operating system: WSL Debian on Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When adding a component field to another component the list provided in the UI does not show all components created. I already checked if all component types are fetched from the db, which seems to be the case. My guess is, that the React Portal for the dropdown is not styled correctly and hides it's overflow instead of scrolling the content. Or maybe a height property of a parent container is missing.

### Steps to reproduce the behavior

1. Go to 'Content-Type-Builder'
2. Click on 'Create new component'
3. Click on 'Add another field to this component'
4. Click on 'Component'
5. Click on 'Use an existing component'
6. Try to select a component from the list, that is not visible by default and needs scrolling to select it

Note: You should already have created more than 6 components to experience the bug.
Has been tested in firefox, chrome and edge.

### Expected behavior

The dropdown list of the form field should be scrollable, so that any component can be selected from the list.

**Comment by sl-env** [comment] 2023-03-13 13:53
In my opinion the issue should not be marked as medium severity, as there is no existing workaround for this problem. This issue stopped our whole development process. If there is any workaround that I am not aware of, please let me know.

**Comment by sl-env** [comment] 2023-03-13 13:55
In my opinion the issue should not be marked as medium severity as there is no existing workaround. The issue stopped our whole development process. If there are any workarounds that I am not aware of, please let me know.

**Comment by sl-env** [comment] 2023-03-13 18:54
> In my opinion the issue should not be marked as medium severity as there is no existing workaround. The issue stopped our whole development process. If there are any workarounds that I am not aware of, please let me know.

I now found an old forum post addressing the issue and mentioning a workaround by changing the json file. Sorry about that!

**Comment by derrickmehaffy** [comment] 2023-03-13 19:46
For context this issue of not showing components that go beyond the GUI limit of 2 in the CTB. This is confirmed but the questions are

- should we set the limits to 3 levels normally?
- should we show a warning why some components are listed (violating the level limit)
- should we write documentation around bypassing the limit manually
- should notification point to said documentation

**Comment by sl-env** [comment] 2023-03-14 08:46
I guess that this is a technical limitation resulting from the fact that the component relations should not be populated to infinity. If I am right, the limit should be preserved in any case. In which way a change is made now, depends on which target group you want to reach. If the target audience is purely developers, a note in the documentation with a link to the part of the documentation that shows how to create fields manually would be sufficient. If the target audience also includes people with less technical background, there should be a customization option and a note in the UI that customization can be done at your own risk and can lead to increased resource costs.

**Comment by sl-env** [comment] 2023-03-14 08:46
> For context this issue of not showing components that go beyond the GUI limit of 2 in the CTB. This is confirmed but the questions are
> 
>     * should we set the limits to 3 levels normally?
> 
>     * should we show a warning why some components are listed (violating the level limit)
> 
>     * should we write documentation around bypassing the limit manually
> 
>     * should notification point to said documentation

I guess that this is a technical limitation resulting from the fact that the component relations should not be populated to infinity. If I am right, the limit should be preserved in any case. In which way a change is made now, depends on which target group you want to reach. If the target audience is purely developers, a note in the documentation with a link to the part of the documentation that shows how to create fields manually would be sufficient. If the target audience also includes people with less technical background, there should be a customization option and a note in the UI that customization can be done at your own risk and can lead to increased resource costs.

**Comment by abdulazeezoj** [comment] 2023-07-13 01:54
I'm currently experiencing the same issue.

- Node.js - 18.16.1
- NPM - 9.8.0
- Strapi - 4.11.5
- Postgres (Docker) - 15.3-alpine
- Operating System - MacOS Ventura

![Screenshot 2023-07-13 at 02 50 18](https://github.com/strapi/strapi/assets/80918954/89293729-641e-4c95-8653-36c85fe695ee)

**Comment by felixnotermans** [comment] 2024-02-08 13:30
> I'm currently experiencing the same issue.
> 
> * Node.js - 18.16.1
> * NPM - 9.8.0
> * Strapi - 4.11.5
> * Postgres (Docker) - 15.3-alpine
> * Operating System - MacOS Ventura
> 
> ![Screenshot 2023-07-13 at 02 50 18](https://private-user-images.githubusercontent.com/80918954/253138204-89293729-641e-4c95-8653-36c85fe695ee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTkyOTgsIm5iZiI6MTcwNzM5ODk5OCwicGF0aCI6Ii84MDkxODk1NC8yNTMxMzgyMDQtODkyOTM3MjktNjQxZS00Yzk1LTg2NTMtMzZjODVmZTY5NWVlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEzMjk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjM2NjZWZmNjg0ZWEyYzZiMDgxNjQxZWY4MmE2NjBiYjA2MjU5YTcwZjFhOTc5MDZlYjI4MGQ3NzZmZjhhNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SFXWPxYjsLCO-sYxg6CrSrt1_sXepfp5bW1xHJHjvdY)

+1

**Comment by derrickmehaffy** [comment] 2024-02-09 18:04
Closing this as it's intended and related to this feature request: https://feedback.strapi.io/feature-requests/p/allow-nesting-of-components-more-than-2-levels-deep-in-ui

**Closed by derrickmehaffy** 2024-02-09 18:04 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-type-builder
