### ISSUE TITLE
Can't load admin panel in 4.12.4 on the public internet

### ISSUE THREAD

**Issue by exchgr** [strapi/strapi#17634] opened 2023-08-09 23:24 UTC
### Required System information

- Node.js version: v18.17.0
- NPM version: 9.6.7
- Strapi version: 4.12.4
- Database: aurora postgres 14.6
- Operating system: the docker container node:18-alpine, `Linux 30339f198cc4 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 aarch64 Linux`
- Is your project Javascript or Typescript: typescript

### Describe the bug

The Strapi admin panel won't load. It shows an error banner with the text:

> Warning: An error occurred while requesting the API

Looking in the browser console, the browser also tries to make several requests to http://localhost:1337, which makes no sense on the public internet. I haven't changed any configurations between 4.12.1 and 4.12.4.

### Steps to reproduce the behavior

1. Visit a strapi admin panel deployed to an environment other than localhost

### Expected behavior

The admin panel loads.

### Screenshots

(hostname of my server redacted for privacy)
<img width="1280" alt="Screenshot 2023-08-09 at 6 09 02 PM" src="https://github.com/strapi/strapi/assets/824678/035aaaa5-42a3-4af2-b45d-70234d5e881d">

### Code snippets

n/a

### Additional context

I tried setting `STRAPI_ADMIN_BACKEND_URL` manually to the domain where my strapi server is, but it didn't work.

**Comment by exneval** [comment] 2023-08-10 04:15
I have the same problem and same error, 4.12.4

**Comment by cannorin** [comment] 2023-08-10 04:20
We've encountered the same issue by *not* upgrading strapi to v4.12.4, but rather upgrading `@strapi/design-system` to v1.9.0. Downgrading `@strapi/design-system` to v1.8.2 fixed the problem.

(We've also upgraded `@strapi/icons` to v1.9.0 and also downgraded it to v1.8.2, but I guess this shouldn't matter as it only provides icons...)

**Comment by Cretezy** [comment] 2023-08-10 04:54
Can also confirm, after upgrading to 4.12.4 from 4.12.1.

```diff
-        "@strapi/plugin-graphql": "^4.12.1",
-        "@strapi/plugin-i18n": "4.12.1",
-        "@strapi/plugin-users-permissions": "4.12.1",
-        "@strapi/strapi": "4.12.1",
+        "@strapi/plugin-graphql": "^4.12.4",
+        "@strapi/plugin-i18n": "4.12.4",
+        "@strapi/plugin-users-permissions": "4.12.4",
+        "@strapi/strapi": "4.12.4",
```

**Comment by joshuaellis** [comment] 2023-08-10 07:14
I've just tried to create a new strapi-app with `npx create-strapi-app@latest` and did not run into this issue, i'll check the upgrade path now but can I confirm when you updated your strapi app you re-ran the build command to ensure the admin panel is rebuilt? :)

**Comment by gu-stav** [comment] 2023-08-10 07:17
I can confirm what ⬆️ @joshuaellis said. Could you please try and delete your `node_modules` directory and run `yarn build && yarn develop` again?

I was able to make `STRAPI_ADMIN_BACKEND_URL` work that way.

**Comment by cannorin** [comment] 2023-08-10 07:27
@joshuaellis @exchgr In our case, we always build a Docker image and push it to our server, which involves 1) `yarn install` and 2) `yarn build`.

Also, we don't set `STRAPI_ADMIN_BACKEND_URL`. We haven't encountered any problem on v4.12.1 and before.

**Comment by exneval** [comment] 2023-08-10 07:33
it's really unfortunate that in local environment everything is fine

it's only happened when you trying to host it in the server
I'm using strapi with dockerize container

**Comment by cannorin** [comment] 2023-08-10 07:35
Yes, you would have to deploy it to somewhere to reproduce it.

**Comment by gu-stav** [comment] 2023-08-10 07:37
I have tried running Strapi in Docker and mapped port 1337 to 1339, which is working well too:

<img width="985" alt="Screenshot 2023-08-10 at 09 36 30" src="https://github.com/strapi/strapi/assets/2244375/e7a1ba58-293e-4770-8830-a79f117c822f">

```yaml
version: '3'
services:
  strapi:
    container_name: strapi
    build: .
    image: strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock

      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1339:1337'
    networks:
      - strapi
    depends_on:
      - strapiDB
```

I think that should be sufficient to see the bug mentioned?

**Comment by exneval** [comment] 2023-08-10 07:39
@gu-stav can you try to self hosted the newest version somewhere? Local environment seems to be fine, no Content Security Policy happened

**Comment by joshuaellis** [comment] 2023-08-10 07:40
@exchgr, @exneval & @cannorin, can you please provide a reproduction? Without it we won't be able to debug the issue you're facing.

**Comment by exneval** [comment] 2023-08-10 07:53
> @exchgr, @exneval & @cannorin, can you please provide a reproduction? Without it we won't be able to debug the issue you're facing.

DMed you in discord

**Comment by gu-stav** [comment] 2023-08-10 07:57
I have deployed a new Strapi app on Strapi cloud and it is all working fine:

<img width="1240" alt="Screenshot 2023-08-10 at 09 55 55" src="https://github.com/strapi/strapi/assets/2244375/527157fd-92cc-422a-b999-2b2c75a34d94">

@exneval As Josh said: please make sure you deploy a clean Docker container, which does not cache `node_modules` and make sure you build the admin app beforehand.

We haven't done any major changes in this area and I can't recall any change that would break the overall behavior.

**Comment by exneval** [comment] 2023-08-10 07:59
> I have deployed a new Strapi app on Strapi cloud and it is all working fine:
> 
> <img alt="Screenshot 2023-08-10 at 09 55 55" width="1240" src="https://user-images.githubusercontent.com/2244375/259668098-527157fd-92cc-422a-b999-2b2c75a34d94.png">
> @exneval As Josh said: please make sure you deploy a clean Docker container, which does not cache `node_modules` and make sure you build the admin app beforehand.
> 
> We haven't done any major changes in this area and I can't recall any change that would break the overall behavior.

I'm using Dockerfile from the docs

**Comment by cannorin** [comment] 2023-08-10 08:00
Will try to create a reproduction. Note that we're using a yarn cache (which is a separate thing than `node_modules`) but we always create `node_modules` from the ground up.

**Comment by exneval** [comment] 2023-08-10 08:03
Additional information: I'm using Strapi from version 4.11.x to 4.12.1, using same environment, never faced an issue

It's just not feeling right 4.12.4 as patch have different behavior

**Comment by exneval** [comment] 2023-08-10 08:06
![image](https://github.com/strapi/strapi/assets/3431785/cdfe90aa-2e67-4e3b-9f20-c4541ab67b1f)
![image](https://github.com/strapi/strapi/assets/3431785/e5659dd5-31dd-4db5-8998-de879ebf4e47)

**Comment by gu-stav** [comment] 2023-08-10 08:32
As Josh said: at this stage we need working reproduction (e.g. a Dockerfile) for a fresh 4.12.4 instance, to make sure there aren't any side-effects caused e.g. by a cached node_modules directory.

**Comment by exneval** [comment] 2023-08-10 08:33
> As Josh said: at this stage we need working reproduction (e.g. a Dockerfile) for a fresh 4.12.4 instance, to make sure there aren't any side-effects caused e.g. by a cached node_modules directory.

Here it is

```
# Creating multi-stage build for production
FROM node:18-alpine as build
RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev > /dev/null 2>&1
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/
COPY package.json yarn.lock ./
RUN yarn config set network-timeout 600000 -g && yarn install --production
ENV PATH /opt/node_modules/.bin:$PATH
WORKDIR /opt/app
COPY . .
RUN yarn build

# Creating final production image
FROM node:18-alpine
RUN apk add --no-cache vips-dev
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/
COPY --from=build /opt/node_modules ./node_modules
WORKDIR /opt/app
COPY --from=build /opt/app ./
ENV PATH /opt/node_modules/.bin:$PATH

RUN chown -R node:node /opt/app
USER node
EXPOSE 1337
CMD ["yarn", "start"]
```

**Comment by exneval** [comment] 2023-08-10 08:47
Another Hint when observing behavior 4.12.1 and 4.12.4 in self hosted server

4.12.1: Trying to access `/admin/project-type` from my domain

4.12.4: Trying to access `/admin/project-type` from localhost:1337

**Comment by cannorin** [comment] 2023-08-10 10:50
I've tried exposing a local Strapi instance to the internet with ngrok, but the issue did not reproduce. I have a feeling that this would need far more complex setup to reproduce. Will continue to investigate tomorrow or later.

**Comment by omerkim** [comment] 2023-08-10 11:25
> Another Hint when observing behavior 4.12.1 and 4.12.4 in a self hosted server
> 
> 4.12.1: Trying to access `/admin/project-type` from my domain (200 OK request)
> 
> 4.12.4: Trying to access `/admin/project-type` from localhost:1337 (blocking request)

Same here.

**Comment by omerkim** [comment] 2023-08-10 11:34
> > Another Hint when observing behavior 4.12.1 and 4.12.4 in a self hosted server
> > 4.12.1: Trying to access `/admin/project-type` from my domain (200 OK request)
> > 4.12.4: Trying to access `/admin/project-type` from localhost:1337 (blocking request)
> 
> Same here.

It looks like something changed in some env variable that points the server to localhost:1337 instead our our server and those breaking the request and triggering csp

**Comment by Aliwahid17** [comment] 2023-08-10 14:37
I'm also facing the same issue in my strapi admin panel after upgrading

**Comment by ainusdev** [comment] 2023-08-10 18:39
I also have a problem with 4.12.4.

This issue disappeared after simply downgrading version to 4.12.1.

**Comment by exchgr** [comment] 2023-08-10 19:57
@joshuaellis https://github.com/strapi/strapi/issues/17634#issuecomment-1672684154:
> I've just tried to create a new strapi-app with `npx create-strapi-app@latest` and did not run into this issue, i'll check the upgrade path now but can I confirm when you updated your strapi app you re-ran the build command to ensure the admin panel is rebuilt? :)
> 
> Edit: i've just created an app at 4.12.1 and then upgraded to 4.12.4 and still do not receive this error, can you please provide a reproduction?

Just to clarify, this issue occurs for me in production. The issue doesn't occur on my development environment on localhost, or even if I connect using my computer's hostname, whether from the same computer or my phone. I've deployed Strapi to AWS EKS with Aurora Postgres, and as far as I know, everything is set up correctly there. I haven't had an issue like this in the few months it's been running, even having upgraded several times. 

I also rebuild the admin panel with every upgrade. In my `Dockerfile`, the command `yarn build` happens after `yarn`, which necessarily clears out the cached layer where `yarn build` happens. I confirmed this by looking in my CI/CD logs. However, I just noticed the following errors in that step, which I didn't notice yesterday until I checked the same build's log again today:
```
#19 [yarn-build 2/2] RUN yarn build
#19 3.522 Starting the compilation for TypeScript files in /app
#19 5.549 Building your admin UI with production configuration...
#19 6.222 ℹ Compiling Webpack
#19 23.84 ✔ Webpack: Compiled with some errors in 17.62s
#19 26.38 [
#19 26.38   {
#19 26.38     file: './src/admin/app.example.tsx:32:13',
#19 26.38     message: "TS7006: Parameter 'app' implicitly has an 'any' type.\n" +
#19 26.38       '    30 |     ],\n' +
#19 26.38       '    31 |   },\n' +
#19 26.38       '  > 32 |   bootstrap(app) {\n' +
#19 26.38       '       |             ^^^\n' +
#19 26.38       '    33 |     console.log(app);\n' +
#19 26.38       '    34 |   },\n' +
#19 26.38       '    35 | };',
#19 26.38     details: undefined,
#19 26.38     stack: "Error: TS7006: Parameter 'app' implicitly has an 'any' type.\n" +
#19 26.38       '    30 |     ],\n' +
#19 26.38       '    31 |   },\n' +
#19 26.38       '  > 32 |   bootstrap(app) {\n' +
#19 26.38       '       |             ^^^\n' +
#19 26.38       '    33 |     console.log(app);\n' +
#19 26.38       '    34 |   },\n' +
#19 26.38       '    35 | };\n' +
#19 26.38       '    at /app/node_modules/fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues.js:42:27\n' +
#19 26.38       '    at Array.forEach (<anonymous>)\n' +
#19 26.38       '    at /app/node_modules/fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues.js:41:16\n' +
#19 26.38       '    at Generator.next (<anonymous>)\n' +
#19 26.38       '    at fulfilled (/app/node_modules/fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues.js:5:58)'
#19 26.38   }
#19 26.38 ]
#19 26.39 Admin UI built successfully
#19 DONE 26.6s
```

The `#19`s and timestamps above are output from Docker, which you can ignore. I'm not sure whether these errors are related to this issue, but I thought I'd point them out. I don't see the errors in build logs for older versions of Strapi.

**Comment by exchgr** [comment] 2023-08-10 20:55
@gu-stav https://github.com/strapi/strapi/issues/17634#issuecomment-1672688438:
> I can confirm what ⬆️ @joshuaellis said. Could you please try and delete your `node_modules` directory and run `yarn && yarn build && yarn develop` again?
> 
> I was able to make `STRAPI_ADMIN_BACKEND_URL` work that way.

My `Dockerfile` doesn't cache `node_modules`, and that directory is also in my `.dockerignore`, so it doesn't get pulled in from anywhere outside the image builder. However, it does cache `/app/.yarn/cache`. (`/app` is the `WORKDIR`.) Do you think that could affect the build? I'm confused as to why that would be, since it's ostensibly using a completely different version of Strapi and associated plugins. And why would that affect the behavior of an environment variable? I'm very confused.

In any case, I tried removing the registry cache, where all these layers are stored, from the build step. It didn't fix the issue with or without `STRAPI_ADMIN_BACKEND_URL` set.

**Comment by exchgr** [comment] 2023-08-10 21:11
@gu-stav https://github.com/strapi/strapi/issues/17634#issuecomment-1672794522: 

> As Josh said: at this stage we need working reproduction (e.g. a Dockerfile) for a fresh 4.12.4 instance, to make sure there aren't any side-effects caused e.g. by a cached node_modules directory.

I can provide you and @joshuaellis access to my private github repo where this all lives, if that would help. (There's nothing really sensitive in there, I just have it private so any embarrassing mistakes don't show up on the public web or any LLM-based coding assistants 😅)

**Comment by creazy231** [comment] 2023-08-10 21:16
Got the same two errors 1. as the OP and 2. this one: https://github.com/strapi/strapi/issues/17634#issuecomment-1673827865

**Comment by matthewdenison** [comment] 2023-08-10 21:18
> @joshuaellis [#17634 (comment)](https://github.com/strapi/strapi/issues/17634#issuecomment-1672684154):
> 
> > I've just tried to create a new strapi-app with `npx create-strapi-app@latest` and did not run into this issue, i'll check the upgrade path now but can I confirm when you updated your strapi app you re-ran the build command to ensure the admin panel is rebuilt? :)
> > Edit: i've just created an app at 4.12.1 and then upgraded to 4.12.4 and still do not receive this error, can you please provide a reproduction?
> 
> Just to clarify, this issue occurs for me in production. The issue doesn't occur on my development environment on localhost, or even if I connect using my computer's hostname, whether from the same computer or my phone. I've deployed Strapi to AWS EKS with Aurora Postgres, and as far as I know, everything is set up correctly there. I haven't had an issue like this in the few months it's been running, even having upgraded several times.
> 
> I also rebuild the admin panel with every upgrade. In my `Dockerfile`, the command `yarn build` happens after `yarn`, which necessarily clears out the cached layer where `yarn build` happens. I confirmed this by looking in my CI/CD logs. However, I just noticed the following errors in that step, which I didn't notice yesterday until I checked the same build's log again today:
> 
> ```
> #19 [yarn-build 2/2] RUN yarn build
> #19 3.522 Starting the compilation for TypeScript files in /app
> #19 5.549 Building your admin UI with production configuration...
> #19 6.222 ℹ Compiling Webpack
> #19 23.84 ✔ Webpack: Compiled with some errors in 17.62s
> #19 26.38 [
> #19 26.38   {
> #19 26.38     file: './src/admin/app.example.tsx:32:13',
> #19 26.38     message: "TS7006: Parameter 'app' implicitly has an 'any' type.\n" +
> #19 26.38       '    30 |     ],\n' +
> #19 26.38       '    31 |   },\n' +
> #19 26.38       '  > 32 |   bootstrap(app) {\n' +
> #19 26.38       '       |             ^^^\n' +
> #19 26.38       '    33 |     console.log(app);\n' +
> #19 26.38       '    34 |   },\n' +
> #19 26.38       '    35 | };',
> #19 26.38     details: undefined,
> #19 26.38     stack: "Error: TS7006: Parameter 'app' implicitly has an 'any' type.\n" +
> #19 26.38       '    30 |     ],\n' +
> #19 26.38       '    31 |   },\n' +
> #19 26.38       '  > 32 |   bootstrap(app) {\n' +
> #19 26.38       '       |             ^^^\n' +
> #19 26.38       '    33 |     console.log(app);\n' +
> #19 26.38       '    34 |   },\n' +
> #19 26.38       '    35 | };\n' +
> #19 26.38       '    at /app/node_modules/fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues.js:42:27\n' +
> #19 26.38       '    at Array.forEach (<anonymous>)\n' +
> #19 26.38       '    at /app/node_modules/fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues.js:41:16\n' +
> #19 26.38       '    at Generator.next (<anonymous>)\n' +
> #19 26.38       '    at fulfilled (/app/node_modules/fork-ts-checker-webpack-plugin/lib/hooks/tap-after-compile-to-get-issues.js:5:58)'
> #19 26.38   }
> #19 26.38 ]
> #19 26.39 Admin UI built successfully
> #19 DONE 26.6s
> ```
> 
> The `#19`s and timestamps above are output from Docker, which you can ignore. I'm not sure whether these errors are related to this issue, but I thought I'd point them out. I don't see the errors in build logs for older versions of Strapi.

I had this same issue yesterday. If you go into the src/admin/app.exmple.tsx file, you can just add // @ts-ignore before the bootstrap(app) line. For some reason, webpack is reporting that it builds successfully but it is causing the environment variables to not get picked up. Once I did that small change it started working again.

**Comment by SvenWesterlaken** [comment] 2023-08-10 21:26
> While generating and then building a fresh plugin (no extra configuration) today in my project that I updated to `4.12.4`, I get a similar error to that of @exchgr (even after installing dependencies in the plugin directory), it also includes other errors such as :
> 
> `could not find a declaration file for module '@strapi/helper-plugin`.
> 
> It seems that something with the Typescript configuration has changed which fails the build and causes applications that update to `4.12.4` to crash after the build while it had silent errors. Because it does confirm the `Admin UI built successfully` at the end.

Downgrading `4.12.1` solved this problem. Looks like it's related in that case.

**Comment by creazy231** [comment] 2023-08-10 21:27
> I had this same issue yesterday. If you go into the src/admin/app.example.tsx file, you can just add // @ts-ignore before the bootstrap(app) line. For some reason, webpack is reporting that it builds successfully but it is causing the environment variables to not get picked up. Once I did that small change it started working again.

Thanks for the temp workaround! Works again ❤️

**Comment by exchgr** [comment] 2023-08-10 21:32
@ matthewdenison https://github.com/strapi/strapi/issues/17634#issuecomment-1673933442:
> I had this same issue yesterday. If you go into the src/admin/app.exmple.tsx file, you can just add // @ts-ignore before the bootstrap(app) line. For some reason, webpack is reporting that it builds successfully but it is causing the environment variables to not get picked up. Once I did that small change it started working again.

Incredible. This fixed my issue. Thank you very much!

I think a longer term fix is probably also necessary here, which won't require people to slap a `// @ts-ignore` in there. Perhaps adding a type annotation would work well. It looks like several possibly related dependencies were [upgraded](https://github.com/strapi/strapi/compare/v4.12.1...v4.12.4#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) between 4.12.1 and 4.12.4, which might have affected this.

**Comment by matthewdenison** [comment] 2023-08-10 21:36
> @matthewdenison [#17634 (comment)](https://github.com/strapi/strapi/issues/17634#issuecomment-1673933442):
> 
> > I had this same issue yesterday. If you go into the src/admin/app.exmple.tsx file, you can just add // @ts-ignore before the bootstrap(app) line. For some reason, webpack is reporting that it builds successfully but it is causing the environment variables to not get picked up. Once I did that small change it started working again.
> 
> Incredible. This fixed my issue. Thank you very much!
> 
> I think a longer term fix is probably also necessary here, which won't require people to slap a `// @ts-ignore` in there. Perhaps adding a type annotation would work well. It looks like several possibly related dependencies were [upgraded](https://github.com/strapi/strapi/compare/v4.12.1...v4.12.4#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) between 4.12.1 and 4.12.4, which might have affected this.

Glad it worked for you! :) They might need to do a migration guide on that. It is such a small issue but would have saved me some time yesterday.

**Comment by exchgr** [comment] 2023-08-10 21:46
Furthermore, I was able to reproduce this issue with a server running on localhost with these steps:

1. `yarn build`
2. `yarn start`
3. `ngrok http 1337`
4. open the ngrok url, with `/admin` on the end

**Comment by exneval** [comment] 2023-08-11 02:40
@matthewdenison thank you for the clue, that's answer my observation why strapi requesting to localhost for path `/project-type`

**Comment by cannorin** [comment] 2023-08-11 05:37
I've also obtained a reproduction thanks to @matthewdenison.

1. Run `yarn create strapi-app` to create a new Strapi project **with TypeScript as the project language**.
    - The Strapi version should be v4.12.4.
    - The issue does not reproduce if you set the project language to JavaScript.

2. Run `yarn build` and then `yarn develop` to start Strapi locally.
    - I can confirm that not only `yarn start` but `yarn develop` also fails in this setup. 
    - Here you would see the webpack error pointed out by @matthewdenison.
    ![image](https://github.com/strapi/strapi/assets/13620400/4a918d50-7df0-4e8b-8aaa-bf9bf19d7afd)

3. Use [ngrok](https://ngrok.com/) to expose it to the internet and open the public URL given by ngrok.
    - As @matthewdenison says, you can achieve this by `ngrok http 1337`.
    - Here you would see the error originally reported by @exchgr.
    ![image](https://github.com/strapi/strapi/assets/13620400/79b4709a-ea01-4e3b-b89b-e0492851419f)

Hope this helps! @joshuaellis @gu-stav

**Comment by gu-stav** [comment] 2023-08-11 07:41
Thank you for all of your clues and trying to find a reproduction 🙏🏼 - very helpful! I have informed the team that might have changed something around that and will keep you updated.

**Comment by gu-stav** [comment] 2023-08-11 08:55
I believe we have found the issue 🚀. Could you do me a favor and check if the experimental release `0.0.0-experimental.05ba949586582197048cb6fb1506057918ec9033` fixes the issue for you?

Instead of version `4.12.4` you can use the version string ⬆️ in your package.json files. Please don't forget to delete `.cache`, `build` and start with a fresh node_modules 🤞🏼

**Comment by cannorin** [comment] 2023-08-11 09:02
@gu-stav I can confirm that `0.0.0-experimental.05ba949586582197048cb6fb1506057918ec9033` does not cause the issue with the above steps of reproduction. Note that it was not necessary to clean `.cache`, `build`, and `node_modules`; it just worked by just replacing version strings and `yarn && yarn build && yarn develop`.

**Comment by gu-stav** [comment] 2023-08-11 10:07
Wonderful. I'll leave the issue open till the next release (4.12.5, next Wednesday) to avoid duplicates and close it then.

**Comment by exneval** [comment] 2023-08-11 11:57
thank you all

**Comment by thematrixdev** [comment] 2023-08-15 09:22
> @gu-stav I can confirm that `0.0.0-experimental.05ba949586582197048cb6fb1506057918ec9033` does not cause the issue with the above steps of reproduction. Note that it was not necessary to clean `.cache`, `build`, and `node_modules`; it just worked by just replacing version strings and `yarn && yarn build && yarn develop`.

Excuse me, what "version string" should be used instead of "4.12.4"?

**Comment by zvonimirr** [comment] 2023-08-17 02:41
Still facing this on 4.12.5 with Node 20.5.1

**Comment by thematrixdev** [comment] 2023-08-17 03:02
> Still facing this on 4.12.5 with Node 20.5.1

I have not tried 4.12.5 yet. But do you use Strapi with Docker? Try remove all cache and build again. It might help.

**Comment by zvonimirr** [comment] 2023-08-17 03:12
Hi @thematrixdev
I've managed to fix it in Docker:
```dockerfile
RUN STRAPI_ADMIN_BACKEND_URL=$STRAPI_ADMIN_BACKEND_URL HOST=$STRAPI_BACKEND_ADMIN_URL yarn build
CMD ["yarn", "start"]
```

**Comment by cannorin** [comment] 2023-08-17 03:21
I can confirm that `4.12.5` does not cause the issue with the steps of reproduction described in https://github.com/strapi/strapi/issues/17634#issuecomment-1674234368.

@zvonimirr make sure `@strapi/typescript-utils` is also updated to `4.12.5`. Setting `STRAPI_ADMIN_BACKEND_URL` should be unnecessary.

**Comment by zvonimirr** [comment] 2023-08-17 03:28
@cannorin I couldn't create a new app as I was updating an already existing app

**Comment by cannorin** [comment] 2023-08-17 03:31
@zvonimirr It shouldn't matter if you are creating a new app or updating an existing one. Try removing `package-lock.json` or `yarn.lock`, or try specifying the version in your `package.json`, I guess?

**Comment by thematrixdev** [comment] 2023-08-17 03:33
Checked. The issue should have been fixed on v4.12.5.
![image](https://github.com/strapi/strapi/assets/19472561/352b7502-38a2-4c6e-b9e4-8d5d768a06b0)

I have been using `yarn`, but during debug I suspect it was due to `yarn` so I have replaced it with `npm`...
My dockerfile:
```
FROM node:18-alpine

RUN apk update && apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

ARG PUBLIC_URL
ENV PUBLIC_URL=${PUBLIC_URL}

ENV PATH /opt/node_modules/.bin:$PATH
EXPOSE 1337
CMD ["npm", "run", "develop"]

WORKDIR /opt/
COPY ./strapi/package.json ./strapi/package-lock.json ./
RUN npm config set fetch-retry-maxtimeout 600000 -g && npm install

WORKDIR /opt/app/
COPY ./strapi ./
RUN ["npm", "run", "build"]
```

**Closed** 2023-08-17 05:47 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:admin

**Comment by jnolascob** [comment] 2023-10-12 17:57
> I also have a problem with 4.12.4.
> 
> This issue disappeared after simply downgrading version to 4.12.1.

Thanks bro, that fixed the issue in my case.

**Comment by y-nk** [comment] 2023-12-07 03:51
i'm having this bug now on 4.14.6 - all my files are TS, is it related?

**Comment by y-nk** [comment] 2023-12-07 05:59
For the people coming here. I don't know why,  and honestly i don't want to know. I had deleted `src/admin/*` files since i thought i didn't need them and it actually created this issue.

Bringing back those files (named `src/admin/*.example.js`) **fixed it**.

v4.14.6

**Comment by Unanimad** [comment] 2024-11-01 02:27
for me, I needed to change from 0.0.0.0 (on my `HOST' .env) to my internal IP (172.18.0.1).
