### ISSUE TITLE
Losing Data more than 8 hours and new field added go back null

### ISSUE THREAD

**Issue by Gypsy-147** [strapi/strapi#13914] opened 2022-07-30 20:45 UTC
### Required System information

- Node.js version: 16.15.1
- Strapi version: v4.3.0
- Database: postgresql
- Operating system: ubuntu 16

### Describe the bug

Everyday when i open the Strapi and check table Products Content Manager inside i have new field "is_hot", "is_discount" Boolean Type and discount_price is number and sub_title is text. Then i add new content everything ok but when i come back more than 8 hours this and go for check table Products Content Manager When Click Product Table page error and show this error and then i go check with postman in route problem return data not have new key im add it. Then im go to development mode for check but everything can do noproblem but inside product table in new field i fill go null and empty data. Im trying to fill again in production mode can save no error but more than 8 hours go back issue again 

### Steps to reproduce the behavior

1. Go to 'Content Manager'
2. Click on 'Product Table '

### Screenshots

![unknown](https://user-images.githubusercontent.com/60289811/181995520-fc2ef5fd-9a98-4523-af83-3f5bf58c2f06.png)

**Comment by derrickmehaffy** [comment] 2022-08-01 01:59
You are most likely hosting your application on something like Heroku and you aren't actually using PG (it's likely loading with SQLite, meaning your PG configuration isn't being used).

Double check your config and ensure if you set the NODE_ENV properly.

I'm closing this as it's practically impossible that a big within Strapi is deleting your entire database on a cron.

---

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Closed by derrickmehaffy** 2022-08-01 01:59 UTC

**Comment by Gypsy-147** [comment] 2022-08-01 06:15
Yes im hosting application on digital ocean and created PG with one-click droplet and i check everything on my env i dont know why strapi not save new field

**Comment by derrickmehaffy** [comment] 2022-08-04 16:56
We don't have one-click options anymore meaning that come from somewhere else.

I would validate you are actually using the PG database because by default Strapi uses SQLite and most PaaS hosts like DO's app engine will automatically shutdown the app and redeploy when it receives traffic this destroying your database because it's saved on the filesystem.

Either way I couldn't reproduce this given the information provided and a proper deployment on DOAE
