### ISSUE TITLE
[V5]: Cancel and Save buttons missing in Add new locale dialog in Safari

### ISSUE THREAD

**Issue by smoothdvd** [strapi/strapi#20660] opened 2024-07-01 04:22 UTC
### Required System information

- Node.js version: 20
- NPM version: 
- Strapi version: 5.0.0-rc.0
- Database: PostgreSQL 
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

 Cancel and Save buttons missing in Add new locale dialog  in Safari.

BTW: This issue affects all dialogs in Safari

### Steps to reproduce the behavior

1. Go to 'Admin Settings'
2. Click on 'Internationalization'
3. Click on 'Add new locale'

### Expected behavior

Show Cancel and Save buttons in Add new locale dialog

### Screenshots

<img width="832" alt="Screenshot 2024-07-01 at 12 16 51 PM" src="https://github.com/strapi/strapi/assets/22420/f4655fa1-a677-4f93-932a-99aa6277fb11">

**Comment by MSchmidt** [comment] 2024-08-10 07:44
Just came across the same while trying `5.0.0-rc.9`. For the 9th RC quite a bug I'd say :)

**Comment by alexandrebodin** [comment] 2024-09-03 12:05
Hi, I just tested with the latest rc.12 and I cannot reproduce this on Safari 🤔  @MSchmidt could you try on the new version ?

**Comment by alexandrebodin** [comment] 2024-09-03 13:29
Perfect :) Closing then

**Closed by alexandrebodin** 2024-09-03 13:29 UTC
Labels: issue: bug, severity: medium, status: pending reproduction, source: plugin:i18n, version: 5
