### ISSUE TITLE
"An internal server error occurred" after creating initial admin user.

### ISSUE THREAD

**Issue by CedricKnapp** [strapi/strapi#7145] opened 2020-07-23 16:32 UTC
**Describe the bug**
I have just finished deploying the strapi droplet on digital ocean, but I am unable to login as an administrator into the admin panel.

**Steps to reproduce the behavior**
I followed this documentation here: https://strapi.io/documentation/3.0.0-beta.x/installation/digitalocean-one-click.html

I am greeted with the error message "An internal server error occurred" after trying to log into the Admin user I created.

JSON return on POST request to log in.
statusCode | 500
error | "Internal Server Error"
message | "An internal server error occurred"

I have tried redeploying the droplet to see if that would resolve the issue but that had no effect.

**Expected behavior**
I expect the login to successfully take me to the admin page :)

**Screenshots**
![image](https://user-images.githubusercontent.com/36387919/88312031-a5d20800-ccdf-11ea-881a-e44ff4ed416a.png)

**System**
![image](https://user-images.githubusercontent.com/36387919/88312544-40cae200-cce0-11ea-9abb-1e6ccc54cb0f.png)

**Comment by derrickmehaffy** [comment] 2020-07-23 16:46
In your `config/server.js` did you set the Admin JWT secret?

**Comment by derrickmehaffy** [comment] 2020-07-23 16:53
Ah this is for the DO one-click, I have created an updated package and have sent it off to DigitalOcean to review and publish.

**Comment by derrickmehaffy** [comment] 2020-07-23 16:54
Closing as duplicate of: https://github.com/strapi/strapi/issues/7135

**Closed by derrickmehaffy** 2020-07-23 16:54 UTC
