### ISSUE TITLE
Different behavior of graphql policies than rest

### ISSUE THREAD

**Issue by marefati110** [strapi/strapi#7210] opened 2020-07-27 14:26 UTC
**Describe the bug**

I need access to the output data for authentication and to control the output data
Unlike policies for functions inside the controller, they do not behave the same way.
It is also expected to access the selected columns used in the graph before execute query on database
In the project I am working on, the graphql is widely used and it is not possible to change it, and this feature is very much needed.

related [discussions](https://github.com/strapi/strapi/discussions/6692)

**Steps to reproduce the behavior**
1-create new policy
```bash
yarn strapi generate:policy check --api article
```
```javascript
module.exports = async (ctx, next) => {
  console.log(ctx.body, 'req');
  await next();
  console.log(ctx.body, 'res');
};
```
2-create new reolver
```javascript
module.exports = {
  resolver: {
    Query: {
      articles: {
        resolver: 'application::article.article.find',
        policies: ['check'],
      },
    },
  },
};
```
3- graphql query
```graphql
{
  articles(limit:1){
    id
  }
}
```
finaly happen
```bash
undefined req
undefined res
```

**Expected behavior**
REST and GraphQL should behave similarly for requests.

**System**

- Node.js version: 12
- NPM version: 6
- Strapi version: 3.1.1
- Database: mysql
- Operating system:centos7

**Comment by alexandrebodin** [comment] 2020-07-27 14:30
Hi @marefati110 thanks for reporting. This is a duplicate of https://github.com/strapi/strapi/issues/7202. Closing

**Closed by alexandrebodin** 2020-07-27 14:30 UTC
