### ISSUE TITLE
Filter on date not working on SQLite

### ISSUE THREAD

**Issue by AntoninBeaufort** [strapi/strapi#3996] opened 2019-09-14 17:16 UTC
Hi, sorry for my english I'm french :/

**Describe the bug**
When I use filter on date there is no result  with Sqlite but with same data and MariaDB this is working.

**Steps to reproduce the behavior**
1. Go to model file
2. Create a afterCreate hook
3. Try a find with this param : 
`.find({created_at_gt: "2019-09-11T05:57:55.175Z"})`
4. Check result

**Expected behavior**
An array of entries that match

**System**
- Node.js version: 12.10.0
- NPM version: 6.10.3
- Strapi version: 3.0.0-beta.16.3
- Database: Sqlite
- Operating system: Debian

**Additional context**
This is working on MariaDB

**Comment by ceefour** [comment] 2019-09-15 06:09
I also get this problem. The result seems to be "somewhat random" / inconsistent. What's weird is changing it to `_lt` or `_lte` will return pretty much all results.

In GraphQL, this is compounded bug because running multiple queries with relations will return "null" relations when this `created_at_gt` here is present. (another bug)

**Comment by loongmxbt** [comment] 2019-11-14 15:20
Same issue. `date_lt` returns all results. `date_gt` returns empty list []
https://api.ergystar.com/reports?date_gt=2019-09-19%2000:00:00
returns []
https://touzi-api.ergystar.com/reports?date_lt=2019-09-19%2000:00:00
returns all reports

**Comment by BjoernRave** [comment] 2019-11-25 12:58
any news when this is going to be fixed? Don't want to sound needy, I know this is an open source project, just need it for what I am developing right now...

**Comment by derrickmehaffy** [comment] 2019-11-25 13:24
This is not something that can be fixed simply. SQLite is a file based storage that was designed to mimic an actual SQL database. Problem is a real DB stores indexes in memory to make them easily (and quickly) searchable. SQLite has no memory based index.

**Comment by BjoernRave** [comment] 2019-11-25 13:42
that means this is working with postgresql?

**Comment by AntoninBeaufort** [comment] 2019-11-25 13:43
At less, this is working on MariaDB, but I think it's also working on postgresql yes.

**Comment by derrickmehaffy** [comment] 2019-11-25 13:48
Yes it should work with any other database than SQLite

**Comment by BjoernRave** [comment] 2019-11-25 14:46
can confirm it is working with postgres. All the time I spent thinking about how to make it work, just to find out that it was working in prod all along...

**Comment by loongmxbt** [comment] 2019-11-26 03:16
BTW, mysql works fine.

But this means in both my development and production I should use mysql.
This makes sense, dev and prod database should be the same.

**Comment by petersg83** [comment] 2020-03-30 13:19
It seems to have been already fixed (works on my side too). I close the issue but you can reopen it if the problems still exists.

**Closed by petersg83** 2020-03-30 13:19 UTC
Labels: priority: medium, source: core:database, status: confirmed, type: bug
