### ISSUE TITLE
RBAC - declaring new conditions with category breaks the admin ui

### ISSUE THREAD

**Issue by aschalund** [strapi/strapi#14763] opened 2022-11-02 14:31 UTC
### Required System information

- Node.js version: v18.12.0
- NPM version: 8.19.2
- Strapi version: 4.4.5 & 4.4.6
- Database: PG
- Operating system: MacOS

### Describe the bug

When declaring a new condition for RBAC (Role-Based Access Control), per the documentation [Strapi Docs](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/rbac.html#declaring-new-conditions),
and setting a category it will properly display in the UI but it breaks selecting any other condition from any other category.

### Steps to reproduce the behavior

1. Declare a new condition
2. Go into the admin->settings->roles
3. Select a role
4. Click on the settings button for a specific permission to see the Define conditions
5. Attempt to click on conditions from multiple categories

### Expected behavior

All options should be selectable

### Screenshots

![image](https://user-images.githubusercontent.com/4872455/199516010-c109f5c2-7ad3-4b54-b3b3-706d95a66635.png)

### Code snippets

```
await strapi.admin.services.permission.conditionProvider.register({
            displayName: "Test",
            category: 'crazy-tests',
            name: "test",
            async handler(user) {
                return user.email.includes('example@weirdtest.com');
            },
        });
```

If you remove the category everything functions as normal

```
await strapi.admin.services.permission.conditionProvider.register({
            displayName: "Test",
            name: "test",
            async handler(user) {
                return user.email.includes('example@weirdtest.com');
            },
        });
```

**Comment by derrickmehaffy** [comment] 2022-11-03 18:48
Was able to reproduce this on v4.4.6, considered it high since it's related to EE feature.

**Comment by gu-stav** [comment] 2022-11-04 12:38
The issue will be fixed by https://github.com/strapi/strapi/pull/14784. We will release the next version next Wed (Nov 9th), and I believe it will be part of it.

**Closed** 2022-11-04 16:56 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:admin
