### ISSUE TITLE
Character like the matrix source code in the logs

### ISSUE THREAD

**Issue by sebastienthibaud** [strapi/strapi#12161] opened 2022-01-10 15:36 UTC
### Describe the bug

After installed the default project with the command yarn create strapi-app my-project --quickstart when Strapi run the command strapi develop, I have got the source code of the Matrix on my terminal.

### Steps to reproduce the behavior

1. Go to terminal
2. Run the command yarn create strapi-app my-project --quickstart or npx create-strapi-app@latest my-project --quickstart
3. See error

### Expected behavior

After Strapi run the command strapi develop, I'm supposed to see the Strapi admin page to registre the admin account.

### Screenshots

![Capture d’écran 2022-01-10 à 16 12 17](https://user-images.githubusercontent.com/4547111/148791816-c0e821a3-5cb4-4491-978a-2736bff6713e.png)

### System

- Node.js version: v14.17.0
- NPM version: v6.14.13
- Strapi version: 4.0.3
- Operating system: macOS Big Sur 11.6.1

### Additional context

I have tested on Terminal, iTerm, Visual Studio Code terminal in zsh and bash mode.

Thank you in advance for your help, Strapi is a great project.

**Comment by kasonde** [comment] 2022-01-10 15:37
Duplicate of #12142

**Closed by kasonde** 2022-01-10 15:37 UTC
