### ISSUE TITLE
Connector for DynamoDb AWS

### ISSUE THREAD

**Issue by tonihauptcc** [strapi/strapi#747] opened 2018-03-06 10:59 UTC
I want to achieve connecting to a dynamoDB from AWS, is there some quick woprkaround or some instructions how to make this possible?

**Comment by lauriejim** [comment] 2018-03-06 15:40
Hi @tonihauptcc .

It's actually not possible. We don't developed connector for this database.

If you want to checkout how connectors works, look `strapi-bookshelf` and `strapi-mongoose` (and good luck !)

**Comment by tonihauptcc** [comment] 2018-03-07 13:39
how can we hook into the install process?

**Comment by lauriejim** [comment] 2018-03-08 10:21
You will have to create duplicate of `strapi-mongoose` node module (you call it `strapi-dynamodb` for example) then you update your `config/environments/.../database.json` and update the connector.

Then you have to write your connector for DynamoDB

**Comment by zfedoran** [comment] 2018-03-13 21:25
Has anyone looked into how much `mongoose` the `strapi-mongoose` needs? I wonder if `dynamoose` would work as a drop in replacement. 

Might be worth looking into..

**Comment by tonihauptcc** [comment] 2018-03-14 21:23
Sounds like a good way. Will deep dive into it

**Closed** 2018-04-25 16:27 UTC
Labels: status: wontfix, type: help wanted 🤷‍♂️

**Comment by santiagopampillo** [comment] 2018-06-05 11:08
Did you succesfully connect Starpi to dynamo?

**Comment by Vadorequest** [comment] 2018-11-09 15:55
Also interested

**Comment by ericbharding** [comment] 2018-11-15 20:34
Also interested in a Dynamo connector

**Comment by dylan-westbury** [comment] 2018-11-28 04:47
Also would be interested in dynamo connected

**Comment by pbn04001** [comment] 2019-08-05 15:27
Want to keep this thread alive, any news on a dynamoDB connector?

Side Note: always working towards a fully serverless solution, would love exposed its logic in such a way I could plug it into lambda functions that the ui would hook into.

**Comment by derrickmehaffy** [comment] 2019-08-05 15:55
@pbn04001 it's unlikely that Strapi themselves will take up this database, it will likely be up to the community to build and publish a hook for this.

**Comment by albertpak** [comment] 2019-08-12 21:21
👍

**Comment by santhosh34** [comment] 2019-10-27 08:41
Also interested....

**Comment by jpmayorga** [comment] 2019-12-02 16:31
Any news about this?

**Comment by derrickmehaffy** [comment] 2019-12-02 17:43
Nothing new from Strapi on this that I am aware of, someone in the community will likely need to build, publish, and manage it

**Comment by dmportella** [comment] 2020-01-28 16:20
i would consider building this is it basically just mimicking the moongoose plugin and replacing it with aws dynamodb specific things?

**Comment by pedreviljoen** [comment] 2020-04-24 09:50
@dmportella 
Have you made progress on this?

**Comment by derrickmehaffy** [comment] 2020-05-10 14:42
> i would consider building this is it basically just mimicking the moongoose plugin and replacing it with aws dynamodb specific things? If i were to do this, i would like to push to main line not interested on running a public repo myself.

Right now @dmportella Strapi is not entertaining additional DB connectors in the main repo, as they don't want to maintain them.

**Comment by rvigneshw** [comment] 2020-10-06 14:57
> i would consider building this is it basically just mimicking the moongoose plugin and replacing it with aws dynamodb specific things? If i were to do this, i would like to push to main line not interested on running a public repo myself.

Have you made any progress in developing that?

**Comment by pupubird** [comment] 2020-10-21 15:34
Interested!

**Comment by jeanlescure** [comment] 2020-10-23 15:56
Really interested

**Comment by truancylounge** [comment] 2020-11-14 05:16
Anyone interested in developing a dynamo connector or if anyone has started working on the connector let me know I can help out with the development.

**Comment by ajoslin103** [comment] 2020-12-11 14:09
I'd be interested in collaboration, but I'm new to strapi so I'd not be able to lead.

**Comment by jaqsparow** [comment] 2020-12-28 01:38
Any update?

I am also interested in dynamodb as strapi backend.

**Comment by derrickmehaffy** [comment] 2020-12-28 07:50
Locking thread, please move discussion to our forum: https://forum.strapi.io
