### ISSUE TITLE
outdated dependency

### ISSUE THREAD

**Issue by y-nk** [strapi/strapi#18094] opened 2023-09-18 08:47 UTC
### Required System information

- Node.js version: 18.x
- NPM version: 8x
- Strapi version: latest (4.13.6)
- Database: sqlite
- Operating system: doesnt matter
- Is your project Javascript or Typescript: TS

### Describe the bug

Fresh install from `create strapi-app` produces:

```
@strapi/strapi > koa-body > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
```

### Steps to reproduce the behavior

1. `npm create strapi-app foo`
2. wait for the dep install

### Expected behavior

Dependencies should be up to date

**Comment by derrickmehaffy** [comment] 2023-09-19 04:24
Please feel free to open a PR

**Comment by sahillangoo** [comment] 2023-09-19 18:34
Here is the list:
`npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau`

**Comment by rktyt** [comment] 2023-09-21 01:36
The essence of the issue is the same as #17109.

**Comment by derrickmehaffy** [comment] 2023-09-21 02:51
> The essence of the issue is the same as #17109.

Thank you.

Closing as duplicate of https://github.com/strapi/strapi/issues/17109

**Closed by derrickmehaffy** 2023-09-21 02:51 UTC
Labels: issue: enhancement, severity: low, good first issue, status: confirmed, source: dependencies
