### ISSUE TITLE
Image variants - resizing API

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1999] opened 2018-09-21 09:23 UTC
**What is the expected behavior?**

Heavily inspired by http://processwire.com/api/fieldtypes/images/

As longtime user of Processwire, there is one feature I miss in Strapi.
Which is dynamically allocating and resizing images to tailor to the different needs of responsive web design.

Images/uploads could have variants, depending on different sizes. In processwire, you were able to request a specific size of an image and the backend would create it for you, if it didn't already exist.

I'll look how it is possible to create a plugin for this. Right now I'm not sure how the concept of image variants fits into the concept of strapi. Any feedback is welcome.

**Comment by colinmeinke** [comment] 2018-10-08 13:30
There's definitely a need for this if Strapi is to compete with other popular CMS's. For example, Craft has _Image Transforms_ built in https://docs.craftcms.com/v3/image-transforms.html.

**Comment by Froelund** [comment] 2018-10-21 12:46
I needed this as well, and I've started making a plugin. There's still a lot of optimisations and testing to be done, so please don't use it in production just yet.

Any feedback is welcome :)

https://github.com/Froelund/strapi-plugin-images

**Comment by Aurelsicoko** [comment] 2018-11-01 11:18
I've added a new card on our public roadmap. Feel free to upvote the feature and give us insights (https://portal.productboard.com/strapi/c/28-media-library-with-edit-crop-resize-capabilities).

**Comment by Aurelsicoko** [comment] 2018-11-06 17:19
To keep the repository as clear as possible, I'm closing this issue. Feel free to continue the discussion on it or on Product Board.

**Closed by Aurelsicoko** 2018-11-06 17:19 UTC
Labels: priority: low, type: feature request 🙏

**Comment by EternalBlack** [comment] 2020-02-22 15:27
I don't like to be a necromancer but I'd really like to know about the progress for this given the fact that this ticket got posted over a year ago and it's essentially the only thing that keeps me from chosing Strapi for my task (Image board forum). :s (I do see that is it "In Progress (Design)"). Unfortunately I don't get @Froelund plugin to work with my current installation.

**Comment by Aurelsicoko** [comment] 2020-03-10 08:10
Hey @EternalBlack, I write every month a Monthly Update blog post to almost exclusively speak about the product and our progress. I shared a video of the Media Library prototype in the last one. You should take a look https://strapi.io/blog/monthly-update-february-2020 ;)

We are currently actively developing the Media Library, we plan to release it in the next two or three weeks!

**Comment by EternalBlack** [comment] 2020-03-10 08:25
@Aurelsicoko Thanks for the reply and heads up! Will definitely check it out! I'm really excited for the release😊
Other than that: Is there a Discord Server next to the Slack  too? Would prefer this one as it's easier to join for me🙈

**Comment by alexkharech** [comment] 2020-03-16 01:11
this temporary hack.
file `extensions/upload/models/File.js`
```js
'use strict';

const path = require('path');
const fs = require('fs');
const sharp = require('sharp');
const publicPath = path.join(__dirname, '../../../public');
/**
 * Lifecycle callbacks for the `File` model.
 */

const getFileName = attrs => {
  return path.join(publicPath, 'uploads', `${attrs.hash}-thumb${attrs.ext}`);
};

module.exports = {
  afterSave: async model => {
    if (!model.attributes.mime.startsWith('image/')) return;

    const from = path.join(publicPath, model.attributes.url);
    const fileName = getFileName(model.attributes);
    try {
      await sharp(from)
        .resize(640)
        .toFile(fileName);
    } catch (err) {
      strapi.log.error(err);
    }
  }
}
```

**Comment by tommyboylab** [comment] 2020-04-08 07:38
@alexkharech Thank you above for your example, I've successfully implemented it in my own project. Now that I have.. how do you apply it?

 I'm having problems calling  an image component from within my models. I use the component feature in Strapi so that it supplies both an img and a placeholder for all my other models. Problem is, I can't seem to update the component from within the model.

Here's my example in models/Article.js
This is the example given in the Docs for creating a  slug 
```
const slugify = require('slugify');
module.exports = {
  beforeSave: async (model, attrs, options) => {
    if (options.method === 'insert' && attrs.title) {
      model.set('slug', slugify(attrs.title, {lower: true,}));
    } else if (options.method === 'update' && attrs.title) {
      attrs.slug = slugify(attrs.title, {lower: true,});
    }
}
```
Using the same logic, I should be able to call the image I've created in upload, and set the placeholder using the images' hash. The problem is I'm unable to update the placeholder upon image upload and I believe it's because of the component model. 

In the example below the image successfully uploads, but placeholder is not updated
```
    if (options.method === 'insert' && attrs.img) {
      model.set(attrs.placeholder, `${attrs.img.hash}-thumb.svg`);
    } else if (options.method === 'update' && attrs.img) {
      attrs.placeholder = `${attrs.img.hash}-thumb.svg`
    }
  },
```


In this example, I cannot upload the image as I'm given an error on the FE of img being undefined
```
    if (options.method === 'insert' && attrs.cover.img) {
      model.set(attrs.cover.placeholder, `${attrs.cover.img.hash}-thumb.svg`);
    } else if (options.method === 'update' && attrs.cover.img) {
      attrs.cover.placeholder = `${attrs.cover.img.hash}-thumb.svg`
    }
  },
```

**Comment by robots4life** [comment] 2020-10-24 13:59
https://sarpisik.com/blog/how-to-generate-different-image-formats-with-strapi-plugin-upload and this https://github.com/sarpisik/strapi-customize-image-formats/issues/1 has helped me get the sizes and naming pattern I want.

Perhaps this can be helpful to other people as well.
Bottom line, the core plugin `upload` needs to be changed with a plugin extension. https://strapi.io/documentation/v3.x/concepts/customization.html#plugin-extensions
