### ISSUE TITLE
Issue with Collection types names containing dash 

### ISSUE THREAD

**Issue by Jbmanllr** [strapi/strapi#8766] opened 2020-11-29 15:22 UTC
### Describe the bug

When a collection type name contains a dash, i can't refer to it via 'strapi.services.collection-type' (or 'strapi.services.collection_type') and strapi.models.collection-type or (strapi.models.collection_type).

### Steps to reproduce the behavior

1. Go to 'create collection type'
2. Creat a collection type containing two or more words ex: product-category
3. Now try refering to it for example when modifying the route to find by slug instead of id:
   async findOne(ctx) {
    const { slug } = ctx.params;

    const entity = await strapi.services.product_category.findOne({ slug });
    return sanitizeEntity(entity, { model: strapi.models.product_category });
  },
};
(or another try with - dash between words)
it throws:

error TypeError: Cannot read property 'findOne' of undefined
    at Object.findOne etc...

### Expected behavior

It should recognize the collection type name and not be undefined

- Node.js version: v14.15.1
- NPM version: 6.14.9
- Strapi version: v3.3.3
- Database: postgres
- Operating system: macos Catalina

**Comment by derrickmehaffy** [comment] 2020-11-30 03:18
You need to use `strapi.services['collection-type']` or `strapi.services'[collection_type']`

Marking as closed as it's functioning as intended.

**Closed by derrickmehaffy** 2020-11-30 03:18 UTC

**Comment by regisin** [comment] 2021-07-13 16:26
To complement the answer (in my case I have "Publication-Type"), the `models` part should also change:

    const entity = await strapi.services['publication-type'].findOne({ slug });
    return sanitizeEntity(entity, { model: strapi.models['publication-type'] });
