### ISSUE TITLE
AWS S3 upload issues using Dockerized version

### ISSUE THREAD

**Issue by Timester** [strapi/strapi#9620] opened 2021-03-05 13:49 UTC
### Describe the bug

I have a Strapi instance running on Amazon ECS based on the strapi/base:14 image. I have added the aws-s3 upload plugin to be able to use S3 as the storage for images uploaded for the content. The plugin and upload works as expected when I run this STrapi project locally, but on ECS there is some kind of an issue. I get back 200 OK for the upload and a corrupted (just a small square, not the original image) version of the image shows up on s3 (no thumbnails generated though). The MySQL DB record for the image misses the dimension information and the thumbnail data. There is nothing indicating an issue in the logs.

The S3 permissions, access keys etc must be OK, since a "corrupted" version of the image shows up in S3 and if I delete it from the Media Library it removes it as expected. Also from locally, running it without docker with ```npm run develop``` it runs okay and the uploads work as expected.

Do you have any idea what can cause this?

Thank You!

### Steps to reproduce the behavior

1. Create a Strapi project, with aws-s3 upload plugin enabled
2. Create a docker image from it using strapi/base:14 image as base 
3. Run the instance in ECS, set up the AWS account credentials as environment variables
4. Try to upload a picture in the media library

### Expected behavior

The picture uploads as expected, on the S3 side the original image and generated thumbnails show up.

### Screenshots

<img width="939" alt="Screen Shot 2021-03-05 at 14 34 56" src="https://user-images.githubusercontent.com/6758515/110122992-a5930280-7dc0-11eb-8025-067483e02214.png">

<img width="1890" alt="Screen Shot 2021-03-05 at 14 48 34" src="https://user-images.githubusercontent.com/6758515/110124010-dfb0d400-7dc1-11eb-83c1-347802f2a519.png">

### Code snippets

Dockerfile:

```
FROM strapi/base:14

WORKDIR /my-path

COPY ./strapi-plugin-wysiwyg-toastui ./strapi-plugin-wysiwyg-toastui
COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

ENV NODE_ENV production
ENV STRAPI_TELEMETRY_DISABLED true

RUN yarn build

EXPOSE 1337

CMD ["yarn", "start"]
```

config/plugins.js

```
module.exports = ({ env }) => ({
  upload: {
    provider: 'aws-s3',
    providerOptions: {
      accessKeyId: env('AWS_ACCESS_KEY_ID'),
      secretAccessKey: env('AWS_SECRET_ACCESS_KEY'),
      region: env('AWS_REGION', 'eu-central-1'),
      params: {
        Bucket: env('AWS_S3_BUCKET_NAME', 'thebestbucket'),
      },
    },
  },
});
```

### System

- Node.js version: Node.js LTS 14.15.3 the issue is present with v12 as well
- NPM version: 
- Strapi version: 3.5.2
- Database: MySQL
- Operating system: MacOS Catalina, Docker version 20.10.2, build 2291f61, Amazon ECS Fargate

**Comment by Zn4rK** [comment] 2021-03-06 15:08
My guess is that you are overriding the node_modules from your system. The upload plugin requires sharp, which in turn requires specific binaries to be built on the machine. When you are doing `COPY . .` (which I get is from the `strapi/strapi-docker` example), you are essentially using the `node_modules` installed on your system instead.

Easiest fix is to place a `.dockerignore` that contains `node_modules`.

**Comment by Timester** [comment] 2021-03-08 07:19
> My guess is that you are overriding the node_modules from your system. The upload plugin requires sharp, which in turn requires specific binaries to be built on the machine. When you are doing `COPY . .` (which I get is from the `strapi/strapi-docker` example), you are essentially using the `node_modules` installed on your system instead.
> 
> Easiest fix is to place a `.dockerignore` that contains `node_modules` next to your Dockerfile.

Thanks for the tip, but unfortunately this won't be it, the node_modules is in the .dockerignore file:

```
node_modules
build
.cache
.vscode
```

**Comment by derrickmehaffy** [comment] 2021-03-08 19:14
Can you please provide a link to your project code as I am not able to reproduce this with a standard install.

**Comment by Timester** [comment] 2021-03-26 08:02
Sorry for being this late with my follow-up, I had other things to work on. I can't publish any URLs or concrete details of this project. However, after many hours of debugging and trying out various configurations, it seems that the problem is with the proxy or URL settings of Strapi.

I have used an AWS API Gateway in front of the Strapi instance running in ECS, this Gateway does some URL path-based routing, the Strapi admin is visible under domain.com/cms/dashboard. For setting this up I have used the Strapi proxy guidelines from the documentation. With this setup, the image upload has the issue described above, but if I revert these URL configs in the server.js file and access the admin UI directly without a proxy, image upload works just fine. I have tried out many config variations to try to narrow down the possible source of the issue and this seems to be it.

The proxy setup guide I have followed is this:
https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/deployment/optional-software/nginx-proxy.html

(subfolder split version)


The AWS API Gateway config is like this:
<img width="202" alt="Screen Shot 2021-03-26 at 8 57 01" src="https://user-images.githubusercontent.com/6758515/112600529-9c221680-8e11-11eb-8d1f-a33b447f34f8.png">

And the server.js looks like this:

```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('URL', 'https://mydomain.com/cms/api'),
  proxy: true,
  cron: {
    enabled: true
  },
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', '123456'),
    },
    url: env('ADMIN_URL', 'https://mydomain.com/cms/dashboard')
    }
  },
});
```


Setting up this proxy to work was quite difficult in the first place but it also seems to break image upload (at least with the s3 plugin)

**Comment by derrickmehaffy** [comment] 2021-03-29 18:57
Can you share a trimmed down version of your nginx config?

**Comment by derrickmehaffy** [comment] 2021-07-22 21:46
No new information added, closing as unable to reproduce with existing information

**Closed by derrickmehaffy** 2021-07-22 21:46 UTC
Labels: status: can't reproduce

**Comment by rubfergor** [comment] 2021-10-05 00:30
For those facing this, the solution lies [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html).

> To handle binary payloads for AWS Lambda proxy integrations, you must base64-encode your function's response. You must also configure the binaryMediaTypes for your API. Your API's binaryMediaTypes configuration is a list of content types that your API treats as binary data. Example binary media types include image/png or application/octet-stream. You can use the wildcard character (*) to cover multiple media types. For example, */* includes all content types. 

Addind a simple rule (don't add this on prod, as it accept any binary! you'll have to limit to only the ones you want) in the API Gateway (settings section of your app) you should be able to solve it:
<img width="1196" alt="Captura de pantalla 2021-10-05 a las 2 28 42" src="https://user-images.githubusercontent.com/7360184/135942054-d07514c8-5d96-4f0d-9a75-bae651ee3412.png">

Hope it helps you too @Timester

**Comment by Akhil-udchalo** [comment] 2023-12-06 06:12
I have a same issue,

Our strapi container runs on ECS fargate with alb. This alb is directly pointed to the domain.

In this case what are the necessary changes I need to do to let the image upload as it is without breaking.

**Comment by anil1712** [comment] 2024-05-14 06:01
@jeaveme I my case I am able to upload the files successfully with 300MBs, but when it goes beyond that then the ECS task gets restarted. Do you guys have idea if I increase the ECS Task memory will it work?

**Comment by mgla178b** [comment] 2025-03-05 13:08
@jeaveme have you solved this issue? I stuck with the exact same result(
