### ISSUE TITLE
[V4] Specific environment configuration not taken into account

### ISSUE THREAD

**Issue by Stun3R** [strapi/strapi#11399] opened 2021-10-28 20:43 UTC
### Describe the bug

It seems that even if we create configuration per environments as per example `database.js` with the following path:`env/production/database.js`, it will never read and execute this file & will always take the development one.

I discovered this bug while I was trying to deploy my Strapi v4 app to Heroku (locally using SQLite and production PG).
As talked with @derrickmehaffy, we tried to have a workaround using conditionnal configuration in the development one thanks process.env.NODE_ENV but it didn't work too

### Steps to reproduce the behavior

1. Create a `env/production/database.js` file
2. Launch strapi with `NODE_ENV=production`
3. Strapi will tell you it runs in `production` environment but nothing is taken into account

### Expected behavior

Use configuration file per environment as said in the documentation

### System

- Node.js version: v14.18.1
- Strapi version: 4.0.0-beta.6
- Database: PG
- Operating system: MacOS Big Sur

### Additional context

This is an extremely annoying bug for me because this project must be released quickly (@derrickmehaffy  will tell you 👀)

**Comment by derrickmehaffy** [comment] 2021-10-29 21:37
Closing this as it's not a bug in the code, but a bug in the docs: https://github.com/strapi/documentation/pull/468

**Closed by derrickmehaffy** 2021-10-29 21:37 UTC
Labels: type: bug, severity: high, status: confirmed, source: core:database, version: v4-Alpha/Beta

**Comment by zentavr** [comment] 2023-02-01 20:19
I have my override file in `config/env/production/database.js` and seems like it is not caught up. Using strapi 4.6.0

**Comment by arilanto** [comment] 2023-02-03 05:51
Same issue here :

Strapi 4.6.0 (node 18.13.0)
I put ./config/env/development/plugins.js  to try to make nodemailer up in my localhost:1337
but no chance, it doesnt work, my strapi email configuration always show "sendmail" as provider (should be "nodemailer")
and I cant send mail (test mail via strapi back nor via api)

**Comment by zentavr** [comment] 2023-02-03 13:38
@arilanto is your database.js a file or a symlink?
