### ISSUE TITLE
WYSIWYG editor stuck prompting file uploads after user uses drag and drop with text

### ISSUE THREAD

**Issue by sezze** [strapi/strapi#2878] opened 2019-02-23 21:24 UTC
**Informations**
- **Node.js version**: 10.13.0 
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.24.1 
- **Database**: MongoDB
- **Operating system**: Windows 10

**What is the current behavior?**
The WYSIWYG editor gets stuck prompting me to select a file to upload after using drag and drop functionality with text, ie. selecting text and dragging it into the text area. The text area gets grayed out and when clicked prompts the user to upload a file. When aborted nothing changes, when the text area is clicked you get prompted again. When a file is selected the same thing happens, the file does not get uploaded. This makes it impossible to continue writing until the page has been reloaded (potentially making you lose progress).

**Steps to reproduce the problem**

1. Select text anywhere on the web page (even selecting text within the text editor works)
2. Click on the text and drag it into the text editor
3. The text editor is now grayed out and you can no longer edit text.

**What is the expected behavior?**
Drag and drop with text should either paste in the text or do nothing at all. Should work similarly to native text inputs.

**Suggested solutions**
Fixing the bug. If there is a temporary workaround, such as disabling the drag and drop functionality, I would appreciate it.

**Comment by lauriejim** [comment] 2019-02-25 13:23
Thank you for this report.
It's not a high priority for us so it will not be fixe soon as we can.

**Comment by lauriejim** [comment] 2019-08-14 15:46
I can't reproduce this issue - We updated the WYSIWYG since the issue creation.
Until we have no news about it and I close the issue. Will reopen it if needed.

**Closed by lauriejim** 2019-08-14 15:46 UTC
Labels: priority: low, status: can't reproduce, type: bug 🐛
