### ISSUE TITLE
Can't override plugin's lifeCycle functions

### ISSUE THREAD

**Issue by dannycoulombe** [strapi/strapi#3835] opened 2019-08-24 16:43 UTC
**Describe the bug**
I'm kind of reopening this closed issue: https://github.com/strapi/strapi/issues/3693

@lauriejim explanations doesn't seem to apply to the current version of Strapi _(surely, I am confused here?)_ since when updating the user model, it doesn't create the User.js file as mentionned. Moreover, the keys of User.settings.json aren't part of User.js either.

**Steps to reproduce the behavior**
Create a User.js file in extensions/users-permissions/models/. and add the following code snippet. Then go in the interface and create or update a user.

**Expected behavior**
Based on my code snippet, I am expecting the model to print in the console.

**Code snippets**
```
module.exports = {
	afterSave: async (model, response, options) => {
		console.log(model);
	},
}
```

**System**
- Node.js version: 10.15.0
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.15
- Database: MySQL 5.7.26
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment] 2019-09-15 12:42
Closing as duplicate of: https://github.com/strapi/strapi/issues/3693

**Closed by derrickmehaffy** 2019-09-15 12:42 UTC

**Comment by dannycoulombe** [comment] 2019-09-15 14:26
@derrickmehaffy This issue is relevant and should not be closed. Explanations provided by @lauriejim in #3693 doesn't solve the issue. Moreover #3693 is locked, which is why I created this post mentioning it.

**Comment by derrickmehaffy** [comment] 2019-09-15 14:29
@dannycoulombe the issue is well documented and plans to be worked on but for now the recommendation is to not use the lifecycle callbacks. The reason for the issue is due to upstream ORM changes in mongoose, bookshelf, and knex. Until the lc callbacks are moved to core queries there is no workarounds. Hence the reason the source issue is locked.

**Comment by derrickmehaffy** [comment] 2019-09-15 14:31
Alternative is to write custom services, controllers to handle your pre/post actions

**Comment by dannycoulombe** [comment] 2019-09-15 14:32
@derrickmehaffy I see. Then you can close this issue. We are no more in the unknown! :-)
