### ISSUE TITLE
Strapi crash - ERR_INTERNAL_ASSERTION: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.

### ISSUE THREAD

**Issue by Cretezy** [strapi/strapi#18084] opened 2023-09-15 16:47 UTC
### Required System information

- Node.js version: v20.5.1
- NPM version: 9.8.0
- Strapi version: 4.13.6, seems to also happen on 4.12
- Database: SQLite
- Operating system: Linux, Unraid 6.12.4, Docker `node:20.5.1-alpine`
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

Strapi crashes. Seems to only be happening when hitting `/graphql`.

Have not been able to find which query is causing this, will be able to this weekend.

Here are the logs:

```ts
...
[2023-09-15 09:32:33.822] http: POST /graphql (7 ms) 200
[2023-09-15 09:32:33.832] http: POST /graphql (6 ms) 200
[2023-09-15 09:32:33.844] http: POST /graphql (6 ms) 200
[2023-09-15 09:32:33.855] http: POST /graphql (8 ms) 200
[2023-09-15 09:32:34.718] http: POST /graphql (860 ms) 200
node:internal/assert:14
    throw new ERR_INTERNAL_ASSERTION(message);
    ^

Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at new NodeError (node:internal/errors:405:5)
    at assert (node:internal/assert:14:11)
    at internalConnectMultiple (node:net:1118:3)
    at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ERR_INTERNAL_ASSERTION'
}

Node.js v20.5.1
npm notice 
npm notice New major version of npm available! 9.8.0 -> 10.1.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.1.0>
npm notice Run `npm install -g npm@10.1.0` to update!
npm notice 
```

### Steps to reproduce the behavior

TBD, unsure yet. Will post this weekend.

### Expected behavior

Strapi does not crash.

**Comment by Cretezy** [comment] 2023-09-15 18:22
I couldn't figure out which query was causing this, or why it started happening.

We wanted to switch to Postgres recently, and switching fixed this issue. Closing as it's no longer a problem and not able to reproduce it consistently.

**Comment by dohoangtung** [comment] 2023-10-25 03:44
![image](https://github.com/strapi/strapi/assets/40049759/3eb16e8f-b979-418d-8e30-ceb893c282a3)

Same issue -

**Comment by nicolasjuan** [comment] 2023-10-25 13:24
Same here (using SQLite)

**Comment by 89224747505** [comment] 2023-11-11 09:47
Same here . I use Postgres. It happens when the server restarts to save changes in collections.

**Comment by nicolasjuan** [comment] 2023-11-11 13:58
I think that's because node v20. I go back to version 18 and works fine, as expected.

**Comment by klonwar** [comment] 2023-12-05 08:33
Still reproducing on Node 20.8.1 with Strapi 4.15.5
Works fine on Node 18.17.0

**Comment by sawden** [comment] 2023-12-22 04:41
Still an Issue with:
Node 20.10.0
Strapi 4.16.0 with sqlite

![image](https://github.com/strapi/strapi/assets/36924392/b5d4f77c-190d-4587-8d30-2945b4275e0a)

**Comment by Cretezy** [comment] 2023-12-22 04:42
Reopening as others have the issues.

**Comment by ancashoria** [comment] 2023-12-24 06:06
Same here, Strapi 4.16.2 (node v20.10.0)

**Comment by pashioz** [comment] 2023-12-25 18:41
I had the issue as well, was on Node.js v20.10.0, reverted to Node.18.19.0, seems to working ok now.

**Comment by dxps** [comment] 2024-01-02 15:37
Same here, using Strapi `v4.16.2` on Node.js `v20.10.0` on Linux (Pop!_OS 21.04 LTS).

It happened right after playing a bit with an initial content type, while learning it. Sample available [here](https://github.com/dxps/react-playground/tree/master/var_x/backend).

```shell
…/backend on  master [?] ❯ npm run develop

> backend@0.1.0 develop
> strapi develop

✔ Cleaning dist dir (10ms)
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (50ms)
✔ Creating admin (13698ms)
✔ Loading Strapi (844ms)
✔ Generating types (359ms)
✔ Cleaning dist dir (6ms)
✔ Compiling TS (1428ms)
node:internal/assert:14
    throw new ERR_INTERNAL_ASSERTION(message);
    ^

Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at assert (node:internal/assert:14:11)
    at internalConnectMultiple (node:net:1118:3)
    at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ERR_INTERNAL_ASSERTION'
}

Node.js v20.10.0
…/backend on  master [?] took 21s❯
```

**Comment by edoardo-bluframe** [comment] 2024-01-08 15:57
Same here on Postgres and Node v20.9.0!

**Comment by pashioz** [comment] 2024-01-11 14:37
I have just upgraded to Strapi v4.17.0, seems to work without error with Node 20.10.0 so far.

**Comment by derrickmehaffy** [comment] 2024-01-11 14:52
So far we haven't been able to reproduce this at all on any version. If someone could provide exact reproduction steps that we be awesome 👍

**Comment by pashioz** [comment] 2024-01-11 16:27
@derrickmehaffy it's pretty much just running _strapi develop_ whilst using node v20.10.0 in my case, node v20.11.0 produces the same error.

Ubuntu 23.04

```
➜  backend git:(develop) nvm use 20.10.0 
Now using node v20.10.0 (npm v10.2.5)
➜  backend git:(develop) yarn run develop
yarn run v1.22.21
$ strapi develop
✔ Cleaning dist dir (14ms)
⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (41ms)
✔ Creating admin (12172ms)
✔ Loading Strapi (680ms)
✔ Generating types (395ms)
✔ Cleaning dist dir (7ms)
✔ Compiling TS (1708ms)
node:internal/assert:14
    throw new ERR_INTERNAL_ASSERTION(message);
    ^

Error [ERR_INTERNAL_ASSERTION]: This is caused by either a bug in Node.js or incorrect usage of Node.js internals.
Please open an issue with this stack trace at https://github.com/nodejs/node/issues

    at assert (node:internal/assert:14:11)
    at internalConnectMultiple (node:net:1118:3)
    at Timeout.internalConnectMultipleTimeout (node:net:1687:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ERR_INTERNAL_ASSERTION'
}

Node.js v20.10.0
Done in 19.66s.
```

**Comment by derrickmehaffy** [comment] 2024-01-11 16:42
In that case then I can 100% confirm that isn't reproducable accurately because my default node version I use regularly is Node 20 on Linux Mint 21.2 (based on Ubuntu 22.04) and I spin up at least 10 to 15 projects a day and have never seen it.

Meaning there is some other environmental factor at play here that we need to identify. If we can't accurately reproduce the issue we can't fix it and validate our fix.

**Comment by karabo-betika** [comment] 2024-01-11 17:40
I running the project in a MacBook Pro Apple M1 Pro with

- Node v20.0.0
- NPM 9.6.4
- Strapi 4.17.0
- Database: MySQL
- Operating system: macOS Sonoma 14.2.1

hope it helps

**Comment by derrickmehaffy** [comment] 2024-01-11 19:54
In the process of testing another bug I still was unable to confirm this, brand new project on node 20 using our latest version (with SQLite) and I don't hit the issue (even after creating a new content-type)

![image](https://github.com/strapi/strapi/assets/8593673/4e05a575-d7df-422c-858c-56b9fbe26515)

**Comment by edoardo-bluframe** [comment] 2024-01-11 21:19
I downgraded to Node 18.19.0 now **all good**. For the record in my case it was happening in _production_ on Node 20.9.0, and in a K8 container

**Comment by derrickmehaffy** [comment] 2024-01-12 00:06
Anyone else here using docker or other containers and running in production?

**Comment by karabo-betika** [comment] 2024-01-12 06:28
> I downgraded to Node 18.19.0 now **all good**. For the record in my case it was happening in _production_ on Node 20.9.0, and in a K8 container

Yes downgrading seems to be the only solution at the moment. As I downgraded to Node v18.17.0 and didn't get the issue anymore.

**Comment by edoardo-bluframe** [comment] 2024-01-12 19:22
@derrickmehaffy Actually **seems** to be a bug in Node https://github.com/nodejs/node/issues/47644

Already merged in. I dug more when it started appearing for me not just in Strapi but in a GraphQL deployment!

**Comment by derrickmehaffy** [comment] 2024-01-12 20:47
Ahh seems to be an issue in Node's network stack, should be fixed by this when it's released: https://github.com/nodejs/node/pull/51045

I'll tag this correctly and close it for now since it's out of our hands but good find!

**Closed** 2024-01-12 20:47 UTC
Labels: issue: bug, severity: low, status: confirmed, source: dependencies

**Comment by jafaruddeen** [comment] 2024-01-16 01:29
Using Node v20.0.1 and getting the same issue while installing the Strapi v4.17.0

<img width="1086" alt="Screenshot 2024-01-16 at 6 51 11 AM" src="https://github.com/strapi/strapi/assets/7066982/e3265fd3-3bb2-454e-b66f-97db521b2590">

But downgraded the version of Node v18.18.0 and installed Strapi v4.17.0 without any issues.

**Comment by derrickmehaffy** [comment] 2024-01-16 02:26
> Using Node v20.0.1 and getting the same issue while installing the Strapi v4.17.0
> 
> <img width="1086" alt="Screenshot 2024-01-16 at 6 51 11 AM" src="https://github.com/strapi/strapi/assets/7066982/e3265fd3-3bb2-454e-b66f-97db521b2590">
> 
> But downgraded the version of Node v18.18.0 and installed Strapi v4.17.0 without any issues.
> 

As mentioned before this isn't us and there is quite literally nothing we can do about it, this issue happens with entirely different projects and boils down to a bug within node itself.

Locking this thread.
