### ISSUE TITLE
Permissions are reseting to default after open Permissions tab in Admin panel

### ISSUE THREAD

**Issue by dulgeoion** [strapi/strapi#1553] opened 2018-07-11 14:41 UTC
**Informations**
- **Node.js version**: 10.5.0
- **npm version**: 5.6.0
- **Strapi version**: 12.7.1
- **Database**: pg
- **Operating system**: Mac

**What is the current behavior?**
For example you set up permissions for each role in `User & Permissions` tab in Admin panel, after you saved it and went to develop your new API! After developing, you want to set up permissions for that api, but when you open permissions tab again, you find that all your previous permissions where reset. And you need to put all those ticks again. I found this occures when tab is opening, cause after saving permissions are saving and everything works correct.

**Steps to reproduce the problem**
I found this issue on 12.5, on 12.7 it is still occurs for me. Just try to create new project with bookshelf hook.

**What is the expected behavior?**
I would like to make my previous permissions not reseting.

**Suggested solutions**
Don't have.

**Comment by derrickmehaffy** [comment] 2018-07-11 16:46
@dulgeoion when you save permissions do you see them in the database at all? My guess is there might be a permissions issue on your postgres database that isn't allowing writes.

If you enable the debug option in your `database.json` file you can see if there is any errors.

See the following doc to enable it: https://strapi.io/documentation/configurations/configurations.html#database

**Comment by dulgeoion** [comment] 2018-07-11 17:46
@derrickmehaffy I cannot check right now if they are saving into database at all, but if I click save button and after will do some work, even if I will restart server, my permissions will be saved, but in the moment I open permissions tab, they are reseting, so I don't think that problem is in database...

**Comment by derrickmehaffy** [comment] 2018-07-11 18:09
Hmmm, that seems strange. I wasn't able to reproduce it on MySQL but I'll have to test with Postgres.

**Comment by derrickmehaffy** [comment] 2018-07-11 20:40
Hmmm, @printeastwoodcz what are you env settings (The `information` bit in the issue)

**Comment by printeastwoodcz** [comment] 2018-07-11 21:11
@derrickmehaffy 
Node.js version: 10.5.0
npm version: 5.6.0
Strapi version: 12.7.1
Database: mongo
Operating system: Ubuntu 16.04.4 LTS Server

**Comment by printeastwoodcz** [comment] 2018-07-11 21:47
@derrickmehaffy yesterdays fresh installation. 
modifications are only new api collections with theirs data and user objected was extended with one text field.

**Comment by lauriejim** [comment] 2018-07-13 08:07
Hello guys ! @dulgeoion @derrickmehaffy @printeastwoodcz 

I'm not able to reproduce your issue. I will need precise steps to be able to reproduce and fix this issue.

@printeastwoodcz PR and issues you link don't have an impact on this issue I think.

**Comment by lauriejim** [comment] 2018-08-22 14:46
I am closing this issue because we don’t have any update/needed informations about it.

**Closed by lauriejim** 2018-08-22 14:46 UTC
Labels: priority: medium, status: can't reproduce, status: need informations, type: bug 🐛
