### ISSUE TITLE
Strapi Plugin Docummentation Error on GCP

### ISSUE THREAD

**Issue by iiibnuadam** [strapi/strapi#16035] opened 2023-03-09 00:32 UTC
### **Bug report**

**Describe the bug**
When accessing the /documentation page from the Strapi admin panel on a GCP App Engine (Standard) instance, I am seeing the below errors in GCP logs and Page not found with a 404 error.

`EROFS: read-only file system, open '/workspace/src/api/alumnus/documentation/1.0.0/alumnus.json'`

The documentation plugin was installed in my LOCAL development environment and docs compiled before deploying to GCP App Engine. Locally it works fine.

**Steps to reproduce the behavior**

1. launch your Strapi project
2. active the Swagger documentation plugin
3. request the documentation locally (it will work)
4. upload the Strapi project to Google App Engine (gcloud command or whatever)
5. visit the documentation ( https://yourgoogleproject.appspot.com/documentation/v1.0.0 )

**System**
- Node.js version: v16.14.2
- NPM version: 8.5.0
- Strapi version: v4.7.1
- Database: Mysql

**Additional context**
Other users are facing the same problem: https://github.com/strapi/strapi/issues/11308

**Comment by richardweaver** [comment] 2023-08-09 11:11
The same happens on deployment to other services where the app is deployed as a package, including Azure when `WEBSITE_RUN_FROM_PACKAGE` is set.

The reason this happens is almost by design: on application startup documentation is [always re-generated](https://github.com/strapi/strapi/blob/main/packages/plugins/documentation/server/bootstrap.js).

What is needed is graceful handling where documentation generation can be turned off with an environment variable, or catch the read-only error and run with the pre-generated documentation. I will try and do something with `patch-package` and if it works do a pull request.

**Comment by derrickmehaffy** [comment] 2023-08-15 20:54
This is something we can't fix as the documentation plugin needs us to dump the schema to the filesystem which is auto-regenerated on boot.

Closing as it's something we won't fix.

**Closed by derrickmehaffy** 2023-08-15 20:54 UTC
Labels: issue: bug, severity: low, source: plugin:documentation, status: will not fix

**Comment by richardweaver** [comment] 2023-08-18 17:41
Hi Derrick, it's a legitimate use-case to want to bypass the generation but still serve pre-built documentation that's checked in to source control. I have a patch working which I would be happy to turn in to a PR?

**Comment by derrickmehaffy** [comment] 2023-08-21 17:44
> Hi Derrick, it's a legitimate use-case to want to bypass the generation but still serve pre-built documentation that's checked in to source control. I have a patch working which I would be happy to turn in to a PR?

Do feel free to open a PR but just wanted to let you know ahead of time we have a WIP plan to decricate that package in the future as we will probably build something else that isn't swagger/openAPI related since Strapi does not follow the openAPI standard (we use the json API standard)

**Comment by richardweaver** [comment] 2023-08-22 09:21
Thanks for the heads up Derrick and understood on JSON:API. In the meantime, I'll do the PR when I can.

**Comment by michalkos** [comment] 2023-12-11 10:09
Any update on this?

**Comment by commandodev** [comment] 2024-01-20 16:04
I've just run into the same issue. Usecase is that I'm trying to package a strapi project in nix and nix packages are immutable.

Any ideas how I could change the behaviour of wanting to write files in `/src/api/XXX/documentation/`?

**Comment by PaulRichez** [comment] 2024-06-25 20:02
Hello, you can override the generate documentation like this:

./src/index.js|ts
```
 register(/*{ strapi }*/) {
    const intialFuntionGenerateFullDoc = strapi.plugins.documentation.services.documentation.generateFullDoc.bind(strapi.plugins.documentation.services.documentation);
    strapi.plugins.documentation.services.documentation.generateFullDoc = (version = strapi.plugins.documentation.services.documentation.getDocumentationVersion()) => {
      // some code here
      const environment = strapi.config.environment;
      if (environment !== 'development') {
        // cancel the generation of the documentation
        return;
      }
      intialFuntionGenerateFullDoc(version);
    };
  },

```

**Comment by farunurisonmez** [comment] 2024-09-02 11:21
> Hello, you can override the generate documentation like this:
> 
> ```js
> // ./src/index.js|ts
>  register(/*{ strapi }*/) {
>     const intialFuntionGenerateFullDoc = strapi.plugins.documentation.services.documentation.generateFullDoc.bind(strapi.plugins.documentation.services.documentation);
>     strapi.plugins.documentation.services.documentation.generateFullDoc = (version = strapi.plugins.documentation.services.documentation.getDocumentationVersion()) => {
>       // some code here
>       const environment = strapi.config.environment;
>       if (environment !== 'development') {
>         // cancel the generation of the documentation
>         return;
>       }
>       intialFuntionGenerateFullDoc(version);
>     };
>   },
> ```

If strapi is disabled in production environment the issue is resolved.
