### ISSUE TITLE
MySQL tossing errors about FULLTEXT Search

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#1382] opened 2018-06-13 18:22 UTC
**Informations**
- **Node.js version**: v10.4.1
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.12.4
- **Database**: 10.2.15-MariaDB
- **Operating system**: Ubuntu 16.04 LTS

**What is the current behavior?**

MySQL tossing errors about creating indexes:
```
[2018-06-13T18:15:10.194Z] warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
{ method: 'raw',
  sql: 'CREATE FULLTEXT INDEX SEARCH_LOCATIONS ON `locations` ()',
  bindings: [],
  options: {},
  __knexQueryUid: 'dcf93b3a-24de-4c89-8e1d-1cc38716d882' }
{ method: 'raw',
  sql: 'CREATE FULLTEXT INDEX SEARCH_LSSITES ON `lssites` (`type`)',
  bindings: [],
  options: {},
  __knexQueryUid: '46f6d833-ac38-473a-9e39-4d1764ddeb84' }
{ method: 'raw',
  sql: 'CREATE FULLTEXT INDEX SEARCH_MATERIALS ON `materials` ()',
  bindings: [],
  options: {},
  __knexQueryUid: '18a9fed1-5201-482a-b9f6-dff1fccab1c7' }
```

Not sure where the `Create Fulltext Index` came from but based on these two docs I don't think that's being generated correctly 😛 @soupette @lauriejim @Aurelsicoko 

https://dev.mysql.com/doc/refman/8.0/en/fulltext-search.html

https://mariadb.com/kb/en/library/full-text-index-overview/

**Steps to reproduce the problem**

Created a project and enabled debug on the database.json. Created a few models, and restarted server. 

**What is the expected behavior?**

N/A - Error Message

**Suggested solutions**

**Comment by derrickmehaffy** [comment] 2018-06-19 10:10
No which means it has something to do with my very large project likely a specific field type or something.

**Comment by derrickmehaffy** [comment] 2018-06-19 10:11
I'll have to test it again when I update to 12.5 on my project.

**Comment by lauriejim** [comment] 2018-07-01 17:00
@derrickmehaffy Have you some news about this issue ?

**Comment by Aurelsicoko** [comment] 2018-07-20 09:30
@derrickmehaffy You're right, we are trying to create a FULLTEXT index for every model. If there is no relations or TEXT columns, we shouldn't create one. However, it means that the search query won't work at all and the best solution would be to disable the search for this specific models...

**Comment by derrickmehaffy** [comment] 2018-09-07 12:43
@Aurelsicoko is there some alternative to this? You should still be able to search numerical columns and after doing some testing today I noticed my search isn't working at all on any model....

**Comment by Aurelsicoko** [comment] 2018-09-07 14:28
That's bad... It was working before. Did you try with MySQL or with Mongo too?

**Comment by derrickmehaffy** [comment] 2018-09-07 16:30
@Aurelsicoko I'll be doing more testing here soon to provide better feedback on the Error. I just recently noticed it.

**Comment by marcellovetro** [comment] 2018-09-09 07:01
A PR is already open for this: #1845

**Comment by derrickmehaffy** [comment] 2018-09-14 06:35
Still an issue on v14.1.1

**Comment by maturanomx** [comment] 2018-09-21 21:39
@derrickmehaffy Is this still an issue now with #1950 merged??

> Side note as well, Search function does not work with the enum type. @Aurelsicoko

Have a ticket for this?

**Comment by derrickmehaffy** [comment] 2018-09-25 11:42
Still seeing this error on the current master branch:

```
{ Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
    at Query.Sequence._packetToError (/srv/test/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/srv/test/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/srv/test/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/srv/test/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/srv/test/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/srv/test/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/srv/test/node_modules/mysql/lib/Connection.js:502:10)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Protocol._enqueue (/srv/test/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/srv/test/node_modules/mysql/lib/Connection.js:200:25)
    at /srv/test/node_modules/knex/lib/dialects/mysql/index.js:154:18
From previous event:
    at Client_MySQL._query (/srv/test/node_modules/knex/lib/dialects/mysql/index.js:148:12)
    at Client_MySQL.query (/srv/test/node_modules/knex/lib/client.js:202:17)
    at Runner.<anonymous> (/srv/test/node_modules/knex/lib/runner.js:146:36)
From previous event:
    at /srv/test/node_modules/knex/lib/runner.js:48:21
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Runner.run (/srv/test/node_modules/knex/lib/runner.js:34:31)
    at Raw.Target.then (/srv/test/node_modules/knex/lib/interface.js:20:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage:
   'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \')\' at line 1',
  sqlState: '42000',
  index: 0,
  sql: 'CREATE FULLTEXT INDEX SEARCH_TEST_1_S ON `test1S` ()' }
[2018-09-25T11:40:21.090Z] warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.

```

PR 1950 did not fix the issue.

**Comment by derrickmehaffy** [comment] 2018-09-25 11:42
Used the following model:
```
{
  "connection": "default",
  "collectionName": "test1S",
  "info": {
    "name": "test1",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "comment": ""
  },
  "attributes": {
    "testint": {
      "default": "",
      "type": "integer"
    },
    "testbool": {
      "default": false,
      "type": "boolean"
    },
    "testenum": {
      "default": "",
      "type": "enumeration",
      "enum": [
        "test1",
        "test2",
        "test3"
      ]
    }
  }
}
```

**Comment by maturanomx** [comment] 2018-09-30 17:33
I confirmed the issue is still present in `master`. I create a new PR to fix this. Hope you can test it.

**Closed** 2018-10-01 15:01 UTC
Labels: priority: medium, status: confirmed, type: bug 🐛

**Comment by derrickmehaffy** [comment] 2018-10-01 15:03
@lauriejim this issue still exists on the master FYI. Prob best to leave it open until it is solved.

**Comment by derrickmehaffy** [comment] 2018-10-01 15:27
Nevermind on previous comment, just tested with PR 2049 and no fulltext errors are generated. 

:+1:

**Comment by maturanomx** [comment] 2018-10-01 15:31
You scare me man!
