### ISSUE TITLE
Photo crop tool scales images down to thumbnail size

### ISSUE THREAD

**Issue by JonasGruenwald** [strapi/strapi#12599] opened 2022-02-19 22:57 UTC
### Describe the bug

The photo crop tool only allows cropping while scaling down images to a tiny thumbnail size, making the tool basically useless for any regular kind of media.

### Steps to reproduce the behavior

1. Go to the media library
2. Upload an image asset to the library
3. Click the pencil icon to edit the image details
4. Click the crop icon in the top right of the image
5. Crop the image to a different aspect ratio
6. The dimensions displayed in the bottom right while cropping already indicate that the image is going to be cropped to a tiny size instead of the original one

### Expected behavior

I would expect the crop tool to crop the image relative to to its source size, and not change the resolution at all.

### Screenshots

<img width="892" alt="Screenshot 2022-02-19 at 22 45 08" src="https://user-images.githubusercontent.com/26603037/154821818-bc0c1fc9-1816-4237-84a9-4a434c736278.png">

You can see here the dimensions of the image are 2000x1600, but the crop tool is going to scale it down to the dimensions 156x126

### System
- Browser: Firefox on macOS
- Node.js version: v14.18.1
- NPM version: 6.14.15
- Strapi version: 4.0.7
- Database: PostgreSQL
- Operating system: macOS / Ubuntu

**Comment by kasonde** [comment] 2022-02-22 07:18
duplicate of #12568

**Closed by kasonde** 2022-02-22 07:18 UTC
Labels: issue-type: bug, severity: medium, status: confirmed, source: core:upload
