### ISSUE TITLE
Cascade delete for relations

### ISSUE THREAD

**Issue by sseypt** [strapi/strapi#3193] opened 2019-04-26 12:43 UTC
Hello.

- [x] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

I'd like to avoid orphan contens by using a `cascade` attribute to the `relation` field type.

Cheers,
Steve

**Comment by derrickmehaffy** [comment] 2019-04-26 12:44
In the case of `cascade` to clarify the users request, in this context he means cascade delete, so if a parent is deleted it will delete all children entries as well.

**Comment by Aurelsicoko** [comment] 2019-05-09 08:32
I've just created a new card on our public roadmap, please share your insights even if this feature is pretty easy to understand (https://portal.productboard.com/strapi/c/59-cascade-delete).

**Comment by luixal** [comment] 2021-09-01 13:58
Any news on this?

Now that Strapi has removed support for mongodb, supporting pure relational feature should be a priority.

**Comment by lnikell** [comment] 2021-12-29 12:09
@ludi81 no changes there, you have to manually declare cascade logic writing a code in lifecycles.js

**Comment by derrickmehaffy** [comment] 2022-01-03 11:41
> How does the cascade delete work in v4? I found nothing in the documentation.

In the future you'll be able to tweak the foreign key logic to handle cascade delete at the database layer. It's not supported yet nor documented but it's something we are working on.

**Comment by JonasJW** [comment] 2022-02-24 20:55
@derrickmehaffy any updates on this?

@lnikell any tips how to do this in v4? I used to do it with the `afterDelete` lifecycle in v3, the problem is, in v4, there are no relations populated (before the 1st relation layer was), so I can't delete the entries of these relations.

**Comment by derrickmehaffy** [comment] 2022-02-24 21:32
> @derrickmehaffy any updates on this?
> 
> @lnikell any tips how to do this in v4? I used to do it with the `afterDelete` lifecycle in v3, the problem is, in v4, there are no relations populated (before the 1st relation layer was), so I can't delete the entries of these relations.

Not at this time, we will need to add some advanced custom support to allow modification of the foreign keys which we don't currently have yet.

I'll reopen the feature request though

**Comment by M1CK431** [comment] 2022-02-24 22:02
Same need here, especially since there is no way to filter on components (so forced to switch on a dedicated collection with the drawback of orphan in database while deleting the parent).

Personally, I will **not** do it at code level because it's a database feature/responsibility.

Despite a proper implementation in strapi could take time, writing a simple documentation to achieve the same effect by modifying the foreign key looks like a good workaround. wdyt @derrickmehaffy ?

**Comment by derrickmehaffy** [comment] 2022-02-24 23:21
> Same need here, especially since there is no way to filter on components (so forced to switch on a dedicated collection with the drawback of orphan in database while deleting the parent).
> 
> Personally, I will **not** do it at code level because it's a database feature/responsibility.
> 
> Despite a proper implementation in strapi could take time, writing a simple documentation to achieve the same effect by modifying the foreign key looks like a good workaround. wdyt @derrickmehaffy ?
> 
> EDIT: something like this for example: https://stackoverflow.com/a/14381227

In the v4 you can filter on components just not dynamic zones

**Comment by M1CK431** [comment] 2022-02-24 23:37
> > Same need here, especially since there is no way to filter on components (so forced to switch on a dedicated collection with the drawback of orphan in database while deleting the parent).
> > Personally, I will **not** do it at code level because it's a database feature/responsibility.
> > Despite a proper implementation in strapi could take time, writing a simple documentation to achieve the same effect by modifying the foreign key looks like a good workaround. wdyt @derrickmehaffy ?
> > EDIT: something like this for example: https://stackoverflow.com/a/14381227
> 
> In the v4 you can filter on components just not dynamic zones

Even using graphql? :thinking: 
I'm not seeing any filter available in the schema for components...

**Comment by M1CK431** [comment] 2022-02-24 23:48
For anyone else trying to achieve that, I finally use a mysql trigger like this:
```sql
CREATE DEFINER=`somedatabase`@`%` TRIGGER delete_orphan_contacts_details
BEFORE DELETE 
ON prospects FOR EACH ROW
BEGIN 
	SET @contact_details_ids := (SELECT GROUP_CONCAT(contact_details_id) FROM prospects_contacts_details_links WHERE prospect_id = OLD.id);
	DELETE FROM prospects_contacts_details_links WHERE FIND_IN_SET(contact_details_id, @contact_details_ids);
	DELETE FROM contacts_details WHERE FIND_IN_SET(id, @contact_details_ids);
END
```

In my case the relationship is "prospect has many contactDetails".

**Comment by M1CK431** [comment] 2022-02-24 23:48
For anyone else trying to achieve that, I finally use a mysql trigger like this:
```sql
CREATE DEFINER=`somedatabase`@`%` TRIGGER delete_orphan_contacts_details
BEFORE DELETE 
ON prospects FOR EACH ROW
BEGIN 
	SET @contact_details_ids := (SELECT GROUP_CONCAT(contact_details_id) FROM prospects_contacts_details_links WHERE prospect_id = OLD.id);
	DELETE FROM prospects_contacts_details_links WHERE FIND_IN_SET(contact_details_id, @contact_details_ids);
	DELETE FROM contacts_details WHERE FIND_IN_SET(id, @contact_details_ids);
END
```

In my case the relationship is "prospect has many contactDetails".

**Comment by derrickmehaffy** [comment] 2022-03-25 18:06
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/feature-requests/p/allow-customization-of-foreign-keys-for-options-like-cascade-delete
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!

**Closed by derrickmehaffy** 2022-03-25 18:06 UTC
Labels: issue: feature request, source: core:database
