### ISSUE TITLE
Unique and empty rules not working

### ISSUE THREAD

**Issue by fabiojansenbr** [strapi/strapi#3778] opened 2019-08-13 15:17 UTC
Informations

Node.js version: v10
npm version: 6.0.0
Strapi version: 3.0.0-beta.15
Database: Postgresql
Heroku
What is the current behavior?

When setting a field as unique or not null, users are able to add data bypassing this rules

Steps to reproduce the problem

Using postgresql:
Create a field in the content builder and assign the option unique, not null then attempt to save a value multiple times. Strapi will write multiple entries without throwing an error. Or let insert values without data.

What is the expected behavior?

Strapi should create and assign a UNIQUE key value to the specified field and not let insert empty values

Suggested solutions: Maybe correct this

**Comment by lauriejim** [comment] 2019-08-13 15:31
Hello! This issue is a duplicate of this one https://github.com/strapi/strapi/issues/1189

**Closed by lauriejim** 2019-08-13 15:31 UTC
