### ISSUE TITLE
I can't edit the role permissions

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#8270] opened 2020-10-10 07:47 UTC
**Describe the bug**

I can't edit the role permissions

**Steps to reproduce the behavior**

I have tried to remove the delete permission in the Battle collection type, but I can't

**Expected behavior**

Allow to edit it.

**Screenshots**

<img width="1255" alt="Screenshot 2020-10-10 at 09 44 34" src="https://user-images.githubusercontent.com/1007051/95649341-5aa8e380-0add-11eb-847c-a8e3ca655fda.png">

**System**

- Node.js version: v12
- NPM version: v6
- Strapi version: v3.2.3
- Database: MongoDB
- Operating system: macOS

**Comment by jlsjonas** [comment] 2020-10-11 08:56
Noticing the same behavior, but for adding more user-role permissions.
It saves, PUT gets sent correctly and comes back with a 200 OK; there must be something off in the backend.

In my case, it's one of my single types, and one of my collection types; so it seems unrelated to that.

**Comment by soupette** [comment] 2020-10-12 07:12
@abdonrd are you using the community edition?

In community edition you cannot set the permission on a field level, this is a feature that only entreprise edition can have.

**Comment by abdonrd** [comment] 2020-10-12 07:45
Yeah, community edition.

But I don't say at the field level, but at the collection type level.
For example in the screenshoot, remove the `Delete` permission in the `Battle` collection type.

**Comment by 8byr0** [comment] 2020-10-12 08:40
Agree with @abdonrd, the behaviour is not clear for that module. 
If it's not possible to delete or edit a predefined role then:
- buttons should be disabled / styled in a different way (for delete button in roles list)
- a notice should be available on edit page "You're using strapi CE which does not allow to edit fields, *link to EE* to learn more"

If it sounds relevant to you, I can make a PR

**Comment by abdonrd** [comment] 2020-10-12 08:54
Anyway, I had understood that the limitation of the community version is to have only 3 roles. But being able to edit those 3 roles as we want.

**Comment by jlsjonas** [comment] 2020-10-12 10:14
@abdonrd Can you modify permissions for other types? If so, I suspect that the underlying issue will be the same for the Users & Permissions plugin. I duplicated the type that was _stuck_ and it is working as expected now (combination of certain names/renames causing unexpected behavior?)

**Comment by JabStrapi** [comment] 2020-10-12 13:42
The 3 roles in Community Edition are indeed predefined and cannot be edited @abdonrd.
Yet at a Content-Type and (to some extent) at a field level, one can choose to grant Author and Editor roles access or not to some content. 

This means that you can choose which Content-Type is available to which role (author/editor, because Super Admin has every permission by default) but as soon as you give permission on a content (Content-type or field) to one role, then this role will be granted all the permissions (CRUD) on it (in the limit of the predefined conditions applied. For example an author cannot publish content). 

This has been made for consistency matters since we wanted both to provide default roles that could be useful for most of our users and to maintain them predefined so that they can welcome all our features. In other words, the default roles permission settings view in Community Edition works "inline" but you are right, it would worth further explanation in-app as you suggested @8byr0. We'll make a PR soon for that (because it needs a design).

**Comment by lauriejim** [comment] 2020-10-13 20:39
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/rbac-role-based-access-control-feature-discussion/433/1

**Comment by derrickmehaffy** [comment] 2020-10-13 20:40
Closing / Locking thread in favor of the above forum thread ^^

**Closed** 2020-10-13 20:40 UTC
Labels: type: discussion
