### ISSUE TITLE
Sharp -  Media Upload Memory Leak

### ISSUE THREAD

**Issue by kasonde** [strapi/strapi#14417] opened 2022-09-14 09:17 UTC
### Required System information

- Node.js version: 14.19.1
- NPM version: 6.14.16
- Strapi version: 4.3.8
- Database: PostgreSQL
- Operating system: Linux (Heroku)

### Describe the bug

We have a website that depends a lot on media for each product and some products may have a lot of media types like videos audio and images and each one of them may reach 10 to 20 MB. When I try to upload them to Strapi, sometimes due to the size of the media, it not only doesn't upload but also crashes the application itself. We can't upload those files one by one because it affects the user experience a lot so we need to upload them in parallel. This is using the S3 Provider.

### Steps to reproduce the behavior

1. Deploy a Strapi app to Heroku 
2. Attempt to upload a 10MB file
3. Wait 
4. See error in logs

### Error logs

```bash
2022-09-03T13:28:13.740126+00:00 heroku[web.1]: Process running mem=1280M(249.9%)
2022-09-03T13:28:13.783638+00:00 heroku[web.1]: Error R15 (Memory quota vastly exceeded)
2022-09-03T13:28:13.791665+00:00 heroku[web.1]: Stopping process with SIGKILL
```

### Additional context

If you have noticed in the message they say 1280 megabytes are used and that's for one person, for one upload operation. Let's say there are 10 people uploading at the same time, do we need 10 gigabytes of ram memory?

Internal TID: 1828

**Comment by kasonde** [comment] 2022-09-14 09:17
We believe this is related to #12601

**Comment by coolista** [comment] 2022-09-14 23:01
thank you, @kasonde Richard.

**Comment by Marc-Roig** [comment] 2022-09-28 13:42
@kasonde 
I have made a quick investigation about this, I will leave some of my thoughts.

I am am uploading multiple images at the same time (10 of 5MB each) and my heroku dyno Ram gets to 400MB (starting from 200MB). I get a similar behaviour with Railway.

What I am not able to reproduce is that big spike you are reporting. **In that project do you use a Dockerfile you could share**? Or a Procfile configuration.

The only suspect here is the `sharp` library. There are many [reports](https://sharp.pixelplumbing.com/install#heroku) of sharp not being "responsible" with memory allocation in Linux machines. They encourage to use jemalloc for memory allocation, but I got spikes of 2GB when trying to install it 😓  Maybe you could try installing the [heroku-buildpack-jemalloc](https://github.com/gaffneyc/heroku-buildpack-jemalloc) and see if there is luck.

**Comment by Marc-Roig** [comment] 2022-09-28 13:46
One other thing that could improve the spike of memory is disabling any image optimizations in settings.
<img width="891" alt="image" src="https://user-images.githubusercontent.com/20578351/192795621-5b8ef237-76f8-4d7c-892a-c4bec193c7ae.png">

**Comment by DzymFardreamer** [comment] 2022-11-02 07:30
Have the same issue. After restart the server uses 280 mb. For each single 2 mb image uploaded, the memory usage increases by 30 mb. At some point, the server runs out of memory and crashes. Memory does not look like it is freed over time.

**Comment by Antoine-lb** [comment] 2022-12-06 14:52
Same problem here, my two cents:
- Started happening when I migrated to v4
- I use AWS S3 provider
- I do resize images (the default settings)

Maybe is keeping them in memory even when is sending them to a provider (the way it does when you don't have a provider) ?

Hope this gets fixed soon because my app is constantly crashing because of it, I keep a close eye on Heroku memory usage all the time

**Comment by andreyluchianic** [comment] 2022-12-16 13:49
Same here, 
- Cloud Run 
- strapi v4
- google-provider-strapi-upload

from 100mb RAM to 1.5Gb on uploading image 5mb

**Comment by AlbertoCalvoRubio** [comment] 2022-12-17 19:13
One thing you can do is disable the functionalities you don't want via extensions.
```javascript
function disableImageManipulation(plugin) {
  const imageServices = plugin.services['image-manipulation']();
  plugin.services['image-manipulation'] = () => ({
    ...imageServices,
    generateThumbnail: () => null,
    optimize: () => null,
    isSupportedImage: () => null,
    getDimensions: () => null,
    generateResponsiveFormats: () => null,
    isOptimizableImage: () => false,
    isImage: () => false
  });
}
```
This works for me. We don't need Strapi to work with the images. We use an external provider to manipulate them

**Comment by PeteJStewart** [comment] 2022-12-17 21:19
Thanks for the function example. Which file did you put this function in?

This seems like quite a critical bug in Strapi.  Does anyone know if it's planned to get resolved?

**Comment by AlbertoCalvoRubio** [comment] 2022-12-18 11:36
> Thanks for the function example. Which file did you put this function in?
> 
> This seems like quite a critical bug in Strapi. Does anyone know if it's planned to get resolved?

You can call the function from src/extensions/upload/strapi-server.js.
```javascript
module.exports = (plugin) => {
    disableImageManipulation(plugin);
}
```

The bug looks like is part of Sharp.js depending on the docker image you are using, so I don't think the Strapi team is going to change something

**Comment by Marc-Roig** [comment] 2022-12-19 13:49
@AlbertoCalvoRubio Thank you a lot for sharing that function 🚀 That would fix the problem and would disable all operations related to sharp.

And indeed, the bug is caused by sharp and having troubles with linux memory allocators (see 
 https://sharp.pixelplumbing.com/install#linux-memory-allocator)

What we are trying to find are alternatives to sharp to let users with this issue keep image optimizations and not have these annoying memory leaks. If anyone knows a good alternative it could help us speed up the process.

**Comment by p-mylecharane** [comment] 2023-02-16 00:26
> One thing you can do is disable the functionalities you don't want via extensions.
> 
> ```js
> function disableImageManipulation(plugin) {
>   const imageServices = plugin.services['image-manipulation']();
>   plugin.services['image-manipulation'] = () => ({
>     ...imageServices,
>     generateThumbnail: () => null,
>     optimize: () => null,
>     isSupportedImage: () => null,
>     getDimensions: () => null,
>     generateResponsiveFormats: () => null,
>     isOptimizableImage: () => false,
>     isImage: () => false
>   });
> }
> ```
> 
> This works for me. We don't need Strapi to work with the images. We use an external provider to manipulate them

Hi @AlbertoCalvoRubio thanks for this (for now until Strapi fixes the issue). I had to change this slightly for it to work for me. This may help some others? It is added to `/src/extensions/upload/strapi-server.js`

`module.exports = (plugin) => {
  
  const imageServices = plugin.services['image-manipulation']();
  plugin.services['image-manipulation'] = () => ({
    ...imageServices,
    generateThumbnail: () => null,
    optimize: () => null,
    isSupportedImage: () => null,
    getDimensions: () => null,
    generateResponsiveFormats: () => null,
    isOptimizableImage: () => false,
    isImage: () => false
  });

  return plugin;
};`

**Comment by DzymFardreamer** [comment] 2023-03-25 14:47
Thanks @p-mylecharane I can confirm the fix also works for me :) You are a life saver.

**Comment by nikita-fuchs** [comment] 2023-10-16 15:16
Sorry for not having any useful solutions to add but I'm wondering if this issue can be fixed by strapi at all? Usually, uploads are pipes / streamed to their destinations so memory leaks don't occur, but apparently the library in place here needs a full reference to the file it's supposed to process / transform. Even if nodejs does support running transformative logic on streams of binary data, some of the functionalities I see like `isImage` probably requires reading the full file first ? But that depends on the implementation of the corresponding logic of course, one might also just read the file header ;)

**Comment by derrickmehaffy** [comment] 2023-10-21 05:55
> Sorry for not having any useful solutions to add but I'm wondering if this issue can be fixed by strapi at all? Usually, uploads are pipes / streamed to their destinations so memory leaks don't occur, but apparently the library in place here needs a full reference to the file it's supposed to process / transform. Even if nodejs does support running transformative logic on streams of binary data, some of the functionalities I see like `isImage` probably requires reading the full file first ? But that depends on the implementation of the corresponding logic of course, one might also just read the file header ;)

Honestly that is a really good question, personally I'd love to get rid of Sharp entirely myself as it has always been a huge headache for us in various ways (nothing against Sharp or it's maintainer) but finding a suitable alternative certainly isn't an easy task.

Honestly at some point it would be good to also omit any "in-app" transformations if a specific provider (eg. Cloudinary) already does it.

**Comment by Marc-Roig** [comment] 2023-10-23 07:20
>Even if nodejs does support running transformative logic on streams of binary data, some of the functionalities I see like isImage probably requires reading the full file first 

As far as I was able to test, all image operations run by sharp do not require loading the entire image into memory, even for operations like isImage, where it only needs to read the first metadata bytes.

Having said that, I saw koa body parser does actually load everything into memory, before turning it into a stream. And that might be something else to improve.

>Honestly at some point it would be good to also omit any "in-app" transformations if a specific provider (eg. Cloudinary) already does it.
And also what you are proposing derrick was specifically the idea behind this work ,  be able to remove the sharp transformers, and handle the url transformations in providers such as cloudinary.

**Comment by nikita-fuchs** [comment] 2023-10-23 09:00
>  I saw koa body parser does actually load everything into memory

😨 that makes sense! and it opens up a full can of problems in and of itself. 

1. As I don't have experience in processing streams, how would one pass data to, say, sharp, before parsing the request body?
2. If it goes by somehow saying "Don't parse, just pass it on and let sharp decide if the data is fine", strapi would somehow allow to set some flag some flag to ignore body parsing on some route / some file size / some other condition?
3. If 2 would be implemented, how would one handle multiple file uploads without some sort of body parsing? Or would the solution then be to upload only 1 file per request, making it some sort of "high performance file upload endpoint" in strap?
4. any other issues I might not have thought of?

**Comment by alexandrebodin** [comment] 2024-04-11 10:06
Hey all 👋  

We have an experiemental version that aims at fixing a set of the issues mentionned here, if some of you want to take it for a spin the version is `0.0.0-experimental.a6060b60559b7e4e36fe81fe1ff8936b53a3808e`

**Closed** 2024-04-17 14:27 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:upload
