### ISSUE TITLE
Typing is incorrect for several Query Engine methods

### ISSUE THREAD

**Issue by maurice-ellis** [strapi/strapi#15999] opened 2023-03-05 15:53 UTC
### Required System information

- Node.js version: 18.14.2
- NPM version: 9.5.0
- Strapi version: 4.7.1
- Database: SQLite
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The current typing for `findMany` does not allow for the populate options mentioned in the [documentation](https://docs.strapi.io/dev-docs/api/query-engine/populating). I suspect it might be the case for `findOne`, `findWithCount`, `findPage`, `create`, and `createMany`.

![image](https://user-images.githubusercontent.com/7678232/222969868-6e55bb62-aa69-4a58-a656-3545ff8f64be.png)

The current typing is expecting`populate` to be an array of strings, numbers, or symbols and does not allow for objects.

![image](https://user-images.githubusercontent.com/7678232/222970662-b843ce89-78ab-4abf-a1e9-a5847c187930.png)

### Steps to reproduce the behavior

1. Add an object to populate
2. Recieve a Typescript error `Type '{ Parent: true; Children: true; }' is not assignable to type '(string | number | symbol)[]'.`

### Expected behavior

I'm expecting to be able to add an object to populate without a Typescript error and not having to cast the object as any.

### Code snippets

```
const children = await strapi.db.query(CONTENT_TYPE_UID).findMany({
    where: {
        Parent: {
            id: {
                $eq: result.id,
            },
        },
    },
    populate: { 
        Parent: true,
        Children: true
    },
});
```

**Comment by Eventyret** [comment] 2023-03-20 11:31
Thank you for your report @maurice-ellis.
To be able to try to reproduce the issue could you please provide me with the `schema` that you are using for this?
That clearly shows the `content-types` and `relations`.

This would speed up the way I can try to reproduce the issue.

**Comment by Eventyret** [comment] 2023-03-20 11:43
Closing as duplicate of https://github.com/strapi/strapi/issues/15225

**Closed by Eventyret** 2023-03-20 11:43 UTC
Labels: severity: low, status: pending reproduction, source: typescript
