### ISSUE TITLE
Error after server restart w/ AWS RDS Postgresql

### ISSUE THREAD

**Issue by bram-abe** [strapi/strapi#10630] opened 2021-07-20 18:33 UTC
### Describe the bug
The first start and creation of database run smoothly. the problem exist when server restart after every first start creation.

```
Got an error : create table "XYZ" ("someField" serial primary key, "someField2" integer null) - relation "XYZ" already exists
```
### Steps to reproduce the behavior

1. Create AWS RDS Postgreql 10.15
2. Create ECS Fargate for running Strapi
2. Start Strapi 
3. Shut down / stop Strapi 
4. Start Strapi again

### Expected behavior

It should be no DB error after restart and bookshelf can handle if

### System

- Node.js version: 14.17.3
- Strapi version: 3.6.5
- Database: AWS RDS Postgreql 10.15
- ECS Fargate: 1.4.0

**Comment by bram-abe** [comment] 2021-07-21 13:56
I change the title because to emphasis the error happen both on RDS Aurora serverless w/ postgresql compatibility and RDS Postgresql ( using postgresql 10.15 engine ).

Please advice

**Comment by kasonde** [comment] 2021-07-21 14:55
Hi @bram-abe Did you at any point create a content type that was deleted? Or was this a fresh install and restart occurrence?

**Comment by kasonde** [comment] 2021-07-21 14:57
I ask because Strapi will not delete tables on your behalf after you edit your content types. You need to manually manage the migrations with something like Knex. There's an on going conversation here #1114

**Comment by bram-abe** [comment] 2021-07-21 15:41
> Hi @bram-abe Did you at any point create a content type that was deleted? Or was this a fresh install and restart occurrence?

Hi @kasonde thx for reply. 

As I remember I was changing a couple of modifying and deleting of content-type. 
but as this is still in development environtment so after error I could delete all table and reconnect Strapi to DB with fresh table and it works well ( a new table was written according to current content-type ). But, the error I mention above will happen again after I disconnecting and connecting Strapi to DB even I wasn't doing any changed to content-type.

**Comment by derrickmehaffy** [comment] 2021-07-22 20:44
Unable to reproduce on v3.6.5 without more information on exact steps to reproduce the error.

**Comment by bram-abe** [comment] 2021-07-23 07:43
UPDATE:

I tried another DB with mySql with same content-type then got an different error said that `someTable name` is too long. the error refer to table with many to many relation where both original table have a long table name. 
So I  modified the name of the two table and all is good both on postgreSql and mySql.

Such error not occur on Sqlite during local DEV and still confused why it came up with different error messages between mySql and postgreSql if the error was caused by same problem with same fixed.

**Comment by kasonde** [comment] 2021-07-23 08:27
Similarly unable to reproduce the error on v3.6.5

**Comment by marcelshields** [comment] 2021-11-19 03:39
I have the same error on v3.6.8 using RDS Aurora serverless postgresql. Another dev deleted a single type locally and then pushed code. The development environment server then threw this error.

**Comment by derrickmehaffy** [comment] 2021-11-19 13:30
The issue here deals with a cloud native "compatible" PostgreSQL option being used that we don't support instead of the actual RDS type.

Marking as closed as this error is specific to a database we don't support.

**Closed by derrickmehaffy** 2021-11-19 13:30 UTC
Labels: status: can't reproduce
