### ISSUE TITLE
Getting error ModuleNotFoundError for strapiplugin-email/strapi-admin.js

### ISSUE THREAD

**Issue by sabahallah** [strapi/strapi#11149] opened 2021-09-30 07:34 UTC
## Bug report

Getting error ModuleNotFoundError: Module not found: Error: Can't resolve '......
ode_modules**@strapiplugin-email/strapi-admin.js**' in '\git\learning-and-experimental-projects\beta\.cache\admin\src'

### Describe the bug

Getting below error when executing `npx create-strapi-app@beta beta --quickstart`

### Steps to reproduce the behavior

* Run `>npx create-strapi-app@beta beta --quickstart`

### Complete Error Logs

```
D:\work\git\learning-and-experimental-projects>npx create-strapi-app@beta beta --quickstart
npx: installed 152 in 27.962s
Creating a quickstart project.
Creating a new Strapi application at D:\work\git\learning-and-experimental-projects\beta.
Creating files.
Dependencies installed successfully.

Your application was created at D:\work\git\learning-and-experimental-projects\beta.

Available commands in your project:

  npm run develop
  Start Strapi in watch mode.

  npm run start
  Start Strapi without watch mode.

  npm run build
  Build Strapi admin panel.

  npm run strapi
  Display all available commands.

You can start by doing:

  cd D:\work\git\learning-and-experimental-projects\beta
  npm run develop


> beta@0.1.0 build D:\work\git\learning-and-experimental-projects\beta
> strapi build "--no-optimization"

Building your admin UI with development configuration ...

* Webpack █████████████████████████ building (10%) 0/1 entries 54/115 dependencies 7/33 modules 18 active
 babel-loader » .cache\admin\src\content-manager\pages\App\reducer.js

ModuleNotFoundError: Module not found: Error: Can't resolve '......
ode_modules@strapiplugin-email/strapi-admin.js' in 'D:\work\git\learning-and-experimental-projects\beta\.cache\admin\src'
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\Compilation.js:1765:28
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:730:13
    at eval (eval at create (D:\work\git\learning-and-experimental-projects\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:273:22
    at eval (eval at create (D:\work\git\learning-and-experimental-projects\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:402:22
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:117:11
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:646:24
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:800:8
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:920:5
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\neo-async\async.js:6883:13
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:903:45
    at finishWithoutResolve (D:\work\git\learning-and-experimental-projects\beta\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (D:\work\git\learning-and-experimental-projects\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '......
ode_modules@strapiplugin-email/strapi-admin.js' in 'D:\work\git\learning-and-experimental-projects\beta\.cache\admin\src'
  Parsed request is a module
  using description file: D:\work\git\learning-and-experimental-projects\beta\.cache\package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      D:\work\git\learning-and-experimental-projects\beta\.cache\admin\src\node_modules doesn't exist or is not a directory
      D:\work\git\learning-and-experimental-projects\beta\.cache\admin\node_modules doesn't exist or is not a directory
      D:\work\git\learning-and-experimental-projects\beta\.cache\node_modules doesn't exist or is not a directory
      looking for modules in D:\work\git\learning-and-experimental-projects\beta\node_modules
        D:\work\git\learning-and-experimental-projects\beta\node_modules\......
ode_modules@strapiplugin-email doesn't exist
      D:\work\git\learning-and-experimental-projects\node_modules doesn't exist or is not a directory
      D:\work\git\node_modules doesn't exist or is not a directory
      D:\work\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve '......
ode_modules@strapiplugin-email/strapi-admin.js' in 'D:\work\git\learning-and-experimental-projects\beta\.cache\admin\src'
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\Compilation.js:1765:28
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:730:13
    at eval (eval at create (D:\work\git\learning-and-experimental-projects\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:273:22
    at eval (eval at create (D:\work\git\learning-and-experimental-projects\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:402:22
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:117:11
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:646:24
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:800:8
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:920:5
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\neo-async\async.js:6883:13
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\webpack\lib\NormalModuleFactory.js:903:45
    at finishWithoutResolve (D:\work\git\learning-and-experimental-projects\beta\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at D:\work\git\learning-and-experimental-projects\beta\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (D:\work\git\learning-and-experimental-projects\beta\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
resolve '......
ode_modules@strapiplugin-email/strapi-admin.js' in 'D:\work\git\learning-and-experimental-projects\beta\.cache\admin\src'
  Parsed request is a module
  using description file: D:\work\git\learning-and-experimental-projects\beta\.cache\package.json (relative path: ./admin/src)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      D:\work\git\learning-and-experimental-projects\beta\.cache\admin\src\node_modules doesn't exist or is not a directory
      D:\work\git\learning-and-experimental-projects\beta\.cache\admin\node_modules doesn't exist or is not a directory
      D:\work\git\learning-and-experimental-projects\beta\.cache\node_modules doesn't exist or is not a directory
      looking for modules in D:\work\git\learning-and-experimental-projects\beta\node_modules
        D:\work\git\learning-and-experimental-projects\beta\node_modules\......
ode_modules@strapiplugin-email doesn't exist
      D:\work\git\learning-and-experimental-projects\node_modules doesn't exist or is not a directory
      D:\work\git\node_modules doesn't exist or is not a directory
      D:\work\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! beta@0.1.0 build: `strapi build "--no-optimization"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the beta@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mahmo\AppData\Roaming\npm-cache\_logs\2021-09-30T07_14_36_045Z-debug.log
```

### System

- Node.js version: v14.15.4
- NPM version: 6.14.10
- Strapi version: Beta
- Database:
- Operating system: Windows

**Comment by LucaNerlich** [comment] 2021-09-30 08:05
Windows is not supported for v4 atm.

**Comment by MattieBelt** [comment] 2021-09-30 08:25
Duplicate of #11137

**Closed by MattieBelt** 2021-09-30 08:25 UTC
