### ISSUE TITLE
cannot create new Collection Types

### ISSUE THREAD

**Issue by juliensl** [strapi/strapi#5631] opened 2020-03-27 21:51 UTC
Hi everybody

**Describe the bug**
The button "Create new collection type" does not appear on my strapi app :'(

**Expected behavior**
Can create new collection type

**Screenshots**
![strapi](https://user-images.githubusercontent.com/43228020/77802762-dc727b80-707b-11ea-9258-0ab6aa075fff.png)

**System**
- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.19.3
- Database: mongo 3.6.12 on mlab
- Operating system: 18.04

**Additional context**
I deployed strapi manualy, with the strapi CLI, connected to an external mongoDB on mlab, launched in in the production mode with this command : `NODE_ENV=production npm start`
It does not work on firefox and chromium.
I restarted it but not work.
I searched `plugin_content-manager_schema` in my db, according with this comment https://github.com/strapi/strapi/issues/2213#issuecomment-459180434 but I did not found it.
When I try to directly got to `http://myurl:1337/admin/plugins/content-type-builder/content-types/article`
it redirects to `http://myurl:1337/admin/plugins/content-type-builder/content-types/plugins::users-permissions.permission` and it does not work :'( 

It looks like I did not use the good command to start the server, but I am lost to know wich one I have to use :/

Thank you !

**Comment by benediktgrether** [comment] 2020-03-27 22:47
Hey,
i run in the same issue a few minutes ago. 
After i see the image  

> The autoReload feature is required to use this plugin. Start your server with `strapi develop`  

i decided to start the Server with 
`strapi develop` 
and the isseu was fixed for me.

I hope it works for you, too.

**Comment by juliensl** [comment] 2020-03-27 23:17
Hi @benediktgrether, thank you for your answer.

I does not work with `strapi develop`, but I found the problem ! 
That's the NODE_ENV variable, when I set it to "production", it does not work, but it works without :) 

I Think it's not a normal behavior :/

**Comment by christianguevara** [comment] 2020-03-28 05:47
It's intended, check: https://github.com/strapi/strapi/pull/5615/commits/a52a2eae43c0491d25aaa37c475d7f3887578083 for reasons :)

**Comment by derrickmehaffy** [comment] 2020-03-28 08:40
Closing, waiting for pr to be merged for answer in FAQ.

This is intended see the above linked answer in the pr

**Closed by derrickmehaffy** 2020-03-28 08:40 UTC

**Comment by lauriejim** [comment] 2020-04-02 18:20
Here is the FAQ - https://strapi.io/documentation/3.0.0-beta.x/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging

**Comment by shrutisahatpure** [comment] 2020-07-03 07:18
hi @benediktgrether  i tried to use 'strapi develop' command but i got "'strapi' is not recognized as an internal or external command,
operable program or batch file." Can you please help with this?

**Comment by iamakshatjain** [comment] 2020-07-26 21:18
I am facing this same issue with heroku deployment with mongoDB

**Comment by lauriejim** [comment] 2020-07-27 09:09
Please try to run `yarn Strapi develop` or `nom run strapi develop`

**Comment by iamakshatjain** [comment] 2020-07-27 09:32
Resolved the issue, It was existing because I had to deploy after creating content types locally. Don't you think that strapi should read content types directly from the database and not depend on extra files or change in the code, I think it would really enhance the capabilities of the product ? I was confused and involved into this for quite long before I accidentally found about this in a random YouTube video!

**Comment by lauriejim** [comment] 2020-07-27 09:47
Ho okay, yes that the way you have to develop with Strapi.
We will have to improve the documentation about that point.
I understand you point, Database to API could be a great feature (as many others) but we have to prioritize with resources we have in the team 🙃 But thank you for your feedback.

**Comment by iamakshatjain** [comment] 2020-07-27 09:51
Yeah, Let me know if I can help. Would love to contribute to such a great product 🙂!

**Comment by lauriejim** [comment] 2020-07-27 15:13
We need a bite of re-structuration to include these info.
Waiting for our new Tech Writer to work on that :)

**Comment by iksent** [comment] 2020-11-10 05:04
Also I have the similar problem after upgrading strapi packages to the newest version with `yarn install` and **without** `yarn build`.

![2020-11-10_10-01-42](https://user-images.githubusercontent.com/32956521/98629992-f2e3f380-233b-11eb-98a1-0dd73407a67f.png)

Maybe we need to add some version mismatch notification to help developers avoid such situations?

**Comment by jalal246** [comment] 2020-11-13 00:31
> Also I have the similar problem after upgrading strapi packages to the newest version with `yarn install` and **without** `yarn build`.
> 
> ![2020-11-10_10-01-42](https://user-images.githubusercontent.com/32956521/98629992-f2e3f380-233b-11eb-98a1-0dd73407a67f.png)
> 
> Maybe we need to add some version mismatch notification to help developers avoid such situations?

 I have the same issue as well

**Comment by derrickmehaffy** [comment] 2020-11-13 16:31
@iksent @jalal246 

Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.

**Comment by iksent** [comment] 2020-11-15 09:48
@derrickmehaffy, yes, I'll create a new issue, but please take a look at this problem then ;)

Really important for me:
https://github.com/strapi/strapi/issues/7547#issuecomment-726717533

**Comment by rojcyk** [comment] 2020-11-15 20:51
I have the very same problem.

**Comment by jalal246** [comment] 2020-11-16 15:03
@rojcyk which version do you use?

**Comment by alexleone** [comment] 2020-11-16 18:20
this is happening to me on 3.3.2 and 3.3.3, downgraded to 3.2.4

**Comment by derrickmehaffy** [comment] 2020-11-16 19:07
Please create a new issue if you are having this problem and provide steps to reproduce.

The original issue likely has nothing to do with any current one. Locking.

**Comment by derrickmehaffy** [comment] 2020-11-18 18:27
Info from @baermathias

```
Some people (including me) had the problem that the couldn't create new collection types after upgrading to 3.3.3 (see #5631).

This can be resolved by running

strapi build

and I think it would be helpful to add this information within the issue.

Buuut, since the issue is locked, I cannot add it. Not sure if this is the right channel to request that, but could you, @derrickmehaffy add that info?

Thanks!
```

Please note with regards to updating versions, see this part of our update/migration documents:
https://strapi.io/documentation/v3.x/migration-guide/
https://strapi.io/documentation/v3.x/guides/update-version.html#rebuild-your-administration-panel

**Every version update, even minor** you should be rebuilding your Admin panel.
