### ISSUE TITLE
File extension ignored on loading routing files

### ISSUE THREAD

**Issue by danieldormann** [strapi/strapi#13478] opened 2022-06-06 10:20 UTC
### Required System information

- Node.js version: v16.14.0

- NPM version: 8.3.1
- Strapi version: 4.1.8
- Database: MySQL
- Operating system: Ubuntu 20.04

### Describe the bug

I noticed strapi doesn't seem to check on file extensions when loading files in src/api/*/routes. Practically speaking:

When editing files with vim, it creates a temporary swap file in the same folder. For instance editing example.js will create .example.js.swp for the time editing. Now while working in the routes directory in development mode will lead to reloading the strapi instance and then crashing, with a random exception, because obviously the format is not expected.

At least for controller files this doesn't seem to be the case. 

### Steps to reproduce the behavior

Just create any non js format file in a routes directory:

`echo "foo" > src/api/hello-world/routes/whatever.foo`

After reload strapi will crash.

**Comment by derrickmehaffy** [comment] 2022-06-06 11:38
kinda duplicate of: https://github.com/strapi/strapi/issues/13478

**Comment by derrickmehaffy** [comment] 2022-06-06 11:39
shoot wrong issue

**Closed by derrickmehaffy** 2022-06-06 11:38 UTC
Labels: status: duplicate

**Comment by derrickmehaffy** [comment] 2022-06-06 11:40
duplicate: https://github.com/strapi/strapi/issues/13317
