### ISSUE TITLE
GraphQL Version mismatch when using monorepos

### ISSUE THREAD

**Issue by guyathomas** [strapi/strapi#11865] opened 2021-12-09 23:56 UTC
## Bug report
When using a monorepo, with a client using its own version of graphql there ends up two versions of graphql and this causes packages like `apollo` to fail install, and also causes runtime errors ( workarounds exist by using the `resolutions` key in the package.json.

## The fix
It seems to me that this would be fixed by unpinning the `graphql` version that is set in the package.json. Can we unpin that? Raised a PR here for reference. https://github.com/strapi/strapi/pull/11866

Errors below
```
modules cannot be used at the same time since different
    versions may have different capabilities and behavior. The data from one
    version used in the function from another could produce confusing and
    spurious results.
            Error: Cannot use GraphQLObjectType "Error" from another module or realm.

    Ensure that there is only one instance of "graphql" in the node_modules
    directory. If different versions of "graphql" are the dependencies of other
    relied on modules, use "resolutions" to ensure only one version is installed.

    https://yarnpkg.com/en/docs/selective-version-resolutions

    Duplicate "graphql" modules cannot be used at the same time since different
    versions may have different capabilities and behavior. The data from one
    version used in the function from another could produce confusing and
    spurious results.
    
```

**Comment by derrickmehaffy** [comment] 2021-12-10 04:33
I'll let this issue slide this time @guyathomas but next time please completely follow our bug report template. Without at least the system block and a means to reproduce we normally have to close all issues (period).

Since you have already created a PR I'll leave this open.

**Comment by alexandrebodin** [comment] 2023-07-10 16:44
Fix was merged a while back

**Closed by alexandrebodin** 2023-07-10 16:44 UTC
Labels: issue: bug, severity: low, status: confirmed, source: plugin:graphql
