### ISSUE TITLE
(Providers/Cognito): Getting "ApplicationError::Invalid URL" after login via Cognito hosted ui

### ISSUE THREAD

**Issue by ibf-iurii-kucherov** [strapi/strapi#17705] opened 2023-08-19 19:55 UTC
### Required System information

- Node.js version: v20.3.1
- NPM version: 9.6.7
- Strapi version: 4.12.5
- Database: sqllite
- Operating system: MacOs
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I've been following [Setting up the provider - examples](https://docs.strapi.io/dev-docs/plugins/users-permissions#setting-up-the-provider---examples) but getting following error when Cognito redirects back to Strapi

```json
{"data":null,"error":{"status":400,"name":"ApplicationError","message":"Invalid URL","details":{}}}
```

#### Here are my Cognito provider settings on Strapi

<img width="835" alt="Screenshot 2023-08-19 at 9 37 19 PM" src="https://github.com/strapi/strapi/assets/123653004/0a3bc85a-a486-420f-8829-f06b81cda511">

#### Here are Cognito App client settings on AWS

<img width="1329" alt="Screenshot 2023-08-19 at 9 38 30 PM" src="https://github.com/strapi/strapi/assets/123653004/d1ed9571-5ae1-4565-bbc1-fc0c39039431">

<img width="1329" alt="Screenshot 2023-08-19 at 9 38 39 PM" src="https://github.com/strapi/strapi/assets/123653004/cc8d6532-2fc5-4205-84ec-c776be278c19">

### Steps to reproduce the behavior

1. Go to <http://localhost:1337/api/connect/cognito> it redirects me to Cognito hosted ui
<img width="1177" alt="Screenshot 2023-08-19 at 9 40 26 PM" src="https://github.com/strapi/strapi/assets/123653004/ee26dd11-d21a-43cb-b07a-6e03cc9eb84d">
2. I fill in username / password and Cognito redirects me back to http://localhost:1337/api/auth/cognito/callback?id_token=XXXXXXX
3. I see the following error 

```json
{"data":null,"error":{"status":400,"name":"ApplicationError","message":"Invalid URL","details":{}}}
```

<img width="1458" alt="Screenshot 2023-08-19 at 9 42 03 PM" src="https://github.com/strapi/strapi/assets/123653004/22403dc8-6dc4-4e9c-8ea4-bba064f48b56">

### Code snippets

```ts
// config/server.ts

export default ({ env }) => ({
  url: env('', 'http://localhost:1337'),
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  app: {
    keys: env.array('APP_KEYS'),
  },
  webhooks: {
    populateRelations: env.bool('WEBHOOKS_POPULATE_RELATIONS', false),
  },
});
```

I've been debugging this issue for quiet some time but cannot find answer so far.

Would appreciate any suggestions / help on this.

Thank you!

**Comment by derrickmehaffy** [comment] 2023-08-23 21:26
You are missing the jwks URL based on your screenshot but marking this as closed as it's not a bug but more of a question.

**Closed** 2023-08-23 21:26 UTC
Labels: flag: question
