### ISSUE TITLE
Database SSL Config not working in Production mode

### ISSUE THREAD

**Issue by sbeyeler** [strapi/strapi#4467] opened 2019-11-06 21:17 UTC
**Describe the bug**
When running strapi in production mode, the configuration value for `connections.default.settings.ssl` is ignored, and strapi is forced into SSL mode

**Steps to reproduce the behavior**
1. Set up a base strapi project
2. Create a production and dev environment with settings in database.json
3. Set up postgres settings with `connections.default.settings.ssl` = `false`
4. Run `npm start`
5. Server will start normally
6. Set env to production - `export NODE_ENV="production"`
7. Run `npm start`

**Expected behavior**
Server will start up and connect to the database with the provided settings in `config/environments/production/database.json`

**Actual behavior**
Server errors out because it tried to connect to a database with SSL that doesn't support SSL

**Code snippets**
`config/environments/production/database.json`
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "postgres",
        "host": "127.0.0.1",
        "port": "5432",
        "database": "strapi",
        "username": "db_username",
        "password": "db_password",
        "ssl": false
      },
      "options": {
        "debug": false,
        "acquireConnectionTimeout": 100000,
        "pool": {
          "min": 0,
          "max": 10,
          "createTimeoutMillis": 30000,
          "acquireTimeoutMillis": 600000,
          "idleTimeoutMillis": 20000,
          "reapIntervalMillis": 20000,
          "createRetryIntervalMillis": 200
        }
      }
    }
  }
}
```

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.17.5
- Database: Postgres
- Operating system: MacOS, Debian (Docker)

**Comment by derrickmehaffy** [comment] 2019-11-06 21:34
Can you try moving the ssl setting into the options object? I forget it's either mongo or the SQL databases that need it in the settings.

**Comment by sbeyeler** [comment] 2019-11-06 21:39
Same result as before - actually as I am testing more, I don't think the `ssl` option is working at all. When I set `ssl` to `true` in development mode, it isn't using ssl. 

It seems like it is defaulting to is essentially
```
if (process.env.NODE_ENV === "development") {
    config["ssl"] = false;
} else {
    config["ssl"] = true;
}
```

**Comment by derrickmehaffy** [comment] 2019-11-06 21:40
:thinking: That is odd, I'll look to see where that is set but I believe that entire settings is just being passed to Knex/Tarn there shouldn't be anywhere it would be hard coded.

**Comment by sbeyeler** [comment] 2019-11-06 22:30
It looks like knex doesn't have an SSL config option for postgres 🤔 
https://github.com/knex/knex/blob/af129408ca7173bfa0f4a777fb5d3206339cd634/types/index.d.ts#L1789

So this might actually be a bug with knex rather than strapi (or a intentional design decision, albeit a poor one)

**Comment by derrickmehaffy** [comment] 2019-11-06 22:32
Indeed it does looks like a Knex issue, you may try passing an issue over there. My guess would be a limit of the clients being used? I'd imagine it comes from the pg package: https://www.npmjs.com/package/pg

**Comment by derrickmehaffy** [comment] 2019-11-06 22:34
Looks like `pg` supports it but knex isn't using it: https://node-postgres.com/features/ssl

**Comment by sbeyeler** [comment] 2019-11-07 15:19
Okay after having done a few more tests, I think there might have been an issue with my original post's bug report, and I will clarify exactly what I think this issue is.

After running the create-strapi-app, the `config/environments/production/database.json` has the following structure
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "postgres",
        "host": "${process.env.DATABASE_HOST || '127.0.0.1'}",
        "port": "${process.env.DATABASE_PORT || 27017}",
        "srv": "${process.env.DATABASE_SRV || false}",
        "database": "${process.env.DATABASE_NAME || 'strapi'}",
        "username": "${process.env.DATABASE_USERNAME || ''}",
        "password": "${process.env.DATABASE_PASSWORD || ''}",
        "ssl": "${process.env.DATABASE_SSL || false}"
      },
      "options": {
        "ssl": "${process.env.DATABASE_SSL || false}",
        "authenticationDatabase": "${process.env.DATABASE_AUTHENTICATION_DATABASE || ''}"
      }
    }
  }
}
```

The issue with this configuration is that when `"ssl": "${process.env.DATABASE_SSL || false}"` gets resolved by strapi and passed into knex it is passing in this value as a string, not a boolean.

After some more tests with the latest version of knex, passing in `"ssl": false` works as intended, but `"ssl": "false"` will not disable ssl

I would assume that ` "srv": "${process.env.DATABASE_SRV || false}",` also has similar issues but I haven't tested it yet.

**Comment by derrickmehaffy** [comment] 2019-11-08 21:21
I have a PR in place to remove those options from the templated config (they shouldn't be strings and they are disabled by default so there is no reason to put the false option in by default)

https://github.com/strapi/strapi/pull/4444

**Comment by lauriejim** [comment] 2019-11-14 15:13
Hello! Can you send the error message, please.

**Comment by sbeyeler** [comment] 2019-11-14 15:24
The error message is 
```
> test@0.1.0 start /Users/sbeyeler/git/cms-service-test/test
> strapi start

[2019-11-14T15:20:20.121Z] error Impossible to register the 'core_store' model.
[2019-11-14T15:20:20.122Z] error Error: The server does not support SSL connections
    at Socket.<anonymous> (/Users/sbeyeler/git/cms-service-test/test/node_modules/pg/lib/connection.js:88:35)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

As I said in an earlier message I am fairly certain this is caused by the fact that when you set 
```
"ssl": "${process.env.DATABASE_SSL || false}"
```

Knex interprets either state as a string which is truthy, and enables ssl because of it. I think a potential fix would be parsing the values that are needed to be a boolean with something like 

```js
if (config.ssl.toLowerCase === "false") {
    config.ssl = false
}
```

**Comment by SirReaDy** [comment] 2019-11-16 16:22
Any fix for this issue yet?

**Comment by derrickmehaffy** [comment] 2019-11-16 21:04
If you are on Postgres @SirReaDy the issue isn't with strapi, it appears Knex doesn't support SSL on postgres.

**Comment by SirReaDy** [comment] 2019-11-16 21:37
> If you are on Postgres @SirReaDy the issue isn't with strapi, it appears Knex doesn't support SSL on postgres.

Using mysql and tried mongo. I just remove the ssl option and works

**Comment by sbeyeler** [comment] 2019-11-18 14:00
> If you are on Postgres @SirReaDy the issue isn't with strapi, it appears Knex doesn't support SSL on postgres.

If you look above, this is actually not true

> After some more tests with the latest version of knex, passing in "ssl": false works as intended, but "ssl": "false" will not disable ssl

**Comment by derrickmehaffy** [comment] 2019-11-18 14:23
@sbeyeler ah yes you are right, I blame my lack of coffee. It seems those SSL settings come from the mongo side of things. I do have a PR submitted removing all those options and more so requiring users to refer the documentation instead to add in specifics (give you do select the SSL settings during the install phase which may improperly feed that boolean as a string, will need to test)

**Comment by websocket98765** [comment] 2019-11-25 17:06
@sbeyeler Another alternative is to remove database.json, add [this file](https://github.com/strapi/strapi/issues/3094#issuecomment-538784881) as database.js (which Strapi will automatically use with no other changes), and specify a DATABASE_URL env var in proper format as noted in the file's comment: `postgres://username:password@hostname:port/dbname?ssl=false`. Fewer env vars to deal with and no SSL issues.

**Comment by mattywong** [comment] 2019-12-17 02:57
Have also run in to this issue when trying to pass through an object to ssl with ca using mysql:

```
"ssl": {
    "ca": "-----BEGIN CERTIFICATE-----........."
}
```

Errors out with:

```
[2019-12-17T02:31:35.752Z] error Error: unable to get local issuer certificate
    at TLSSocket.<anonymous>
```

Using the above database.js file fix instead of json works.

**Closed** 2019-12-20 12:33 UTC
Labels: type: help wanted 🤷‍♂️

**Comment by Arman-AP** [comment] 2020-03-11 06:15
I am facing a similar issue, I am not sure if my issue is related to SSL or not but in development environment I am able to succesfuly npm start/develop and the app will run without a problem. When pushed to production(heroku) it fails at npm start and gives the following error.
*MYSERVER.com is not my actual host name
`
2020-03-11T06:08:12.435708+00:00 app[web.1]: [2020-03-11T06:08:12.435Z] error Impossible to register the 'core_store' model.
2020-03-11T06:08:12.436391+00:00 app[web.1]: [2020-03-11T06:08:12.436Z] error Error: getaddrinfo ENOTFOUND MYSERVER.COM
2020-03-11T06:08:12.436406+00:00 app[web.1]: at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
2020-03-11T06:08:12.436407+00:00 app[web.1]: --------------------    
2020-03-11T06:08:12.436408+00:00 app[web.1]: at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
2020-03-11T06:08:12.436408+00:00 app[web.1]: at Protocol.handshake (/app/node_modules/mysql/lib/protocol/Protocol.js:51:23)`

Any suggestions as to what is causing the issue
