### ISSUE TITLE
Customize field on list content

### ISSUE THREAD

**Issue by kapik** [strapi/strapi#5048] opened 2020-01-22 08:12 UTC
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

Hi !! 👋 

To illustrate this I have created a `Test 2` content type.
It contains a single `Testcomponent` (no repeatable) which itself contains a single `Title` field.
On the list, there is no field to distinguish this kind of content.

On my gif, I have created a new `Test 2` and on the list I don't have the possibility to have interesting information to distinguish the content. We have only `ID`, `created_ad` and `update_at`

![2020-01-21_22-25-59](https://user-images.githubusercontent.com/511247/72876627-3a3ebc00-3cf7-11ea-87f3-85bc77da7016.gif)

Maybe this feature/bug is related to https://github.com/strapi/strapi/issues/5044 
What do you think about this ? 

Thx 😃

**Comment by derrickmehaffy** [comment] 2020-01-22 08:15
@kapik in the backend it's a relation so it would fall under this: https://portal.productboard.com/strapi/1-public-roadmap/c/49-display-relational-field-in-list-view

**Comment by derrickmehaffy** [comment] 2020-01-22 08:15
I will close this due to it being a duplicate of an existing feature request but do feel free to continue the discussion.

**Closed by derrickmehaffy** 2020-01-22 08:15 UTC
