### ISSUE TITLE
MongoDb collections from a relation "has many" of content types, the array attribute is not being saved.

### ISSUE THREAD

**Issue by ytachi0026** [strapi/strapi#6115] opened 2020-05-07 20:49 UTC
**Describe the bug**
When you create a relation "**has many**" between _2 content types,_ .
Let's says Collection A, and Collection B. A has many B.
Where A field name is bplural and B field name is asingle.

When you linked one of them on the admin panel, or even using the endpoints.
A doesn't get the field bplural on the MongoDb collection. However, B gets the asingle with the object Id from A.

**Steps to reproduce the behavior**
1. Go to content type 'A'
2. Click on 'Add another field'
3. Select relation of **has many** to B.
4. Name the A field name to bplural.
5. Name the B field name to asingle.
6. Input some sample data on A and B.
7. Link these 2 input data.
8. You will see on the admin panel that the relation exists.
9. But, if you check the mongoDB collections, there is a problem. 
- The B collections do have the field single
- Problem: The A collections do not have the field bplural.

**Expected behavior**
The A collections should have the field bplural as an array of the ObjectIds from B that are linked to it.

**Screenshots**
1. Collection relation
![image](https://user-images.githubusercontent.com/1701423/81342872-94327a00-9079-11ea-821f-ecce147973b1.png)

![image](https://user-images.githubusercontent.com/1701423/81342903-9dbbe200-9079-11ea-8f60-daa8a36ef6a5.png)

2. Collections data on Mongo DB
A collection:
![image](https://user-images.githubusercontent.com/1701423/81343016-d5c32500-9079-11ea-9e37-7ab334920f90.png)

B collection:
![image](https://user-images.githubusercontent.com/1701423/81343074-e8d5f500-9079-11ea-85ad-40f6bf249288.png)

**Code snippets**

**System**

- Node.js version: v12.16.2
- NPM version: 6.14.4
- Strapi version: 3.0.0-beta.20
- Database: MongoDb
- Operating system: MacOs Catalina, also in Ubuntu 18.04

**Additional context**
I am reporting this, because i wanna do deep filtering on A using B fields, but since there is no information about b arrays on A collection, it is impossible to do it.

**Comment by derrickmehaffy** [comment] 2020-05-07 21:24
I believe this is intended and you are likely using the wrong relation type for what you are trying to do.

You would need to set the relations on both sides. Can you give a full example of what you are trying to do using an english example?

**Comment by ytachi0026** [comment] 2020-05-07 23:40
hey derrick, I am using belongs to many. So, for some reason on the admin panel is asking me to put a fieldname on A (that belongs to many), but when i created a content for A, and linked to B, the fieldname didn't get save on MongoDb

**Comment by derrickmehaffy** [comment] 2020-05-10 02:12
> hey derrick, I am using belongs to many. So, for some reason on the admin panel is asking me to put a fieldname on A (that belongs to many), but when i created a content for A, and linked to B, the fieldname didn't get save on MongoDb

That's not uncommon, Strapi treats Mongo like a relational database (even though, yes, it's not) so only the "one" side gets saved on the "many", the inverse is not true.

**Comment by Jryke** [comment] 2020-06-30 15:14
Is there any workaround for this?  I am having the same issue and it is causing problems because I can see the relation in the admin panel but not in the mongo database.  The issue is that when I use the POST /auth/local endpoint to log in, I get the relations, but when I use the GET /users/me endpoint I don't get the relations.

I tried adding the relations by updating the user with the PUT users/:id endpoint but that also only updates it in the admin panel (not in the Mongo db).  Any suggestions on how I can get the endpoint to update the db?

**Comment by SalehAlbuga** [comment] 2020-07-10 21:10
@derrickmehaffy is there a workaround for this or any plans to change this behavior? I've tried adding a hasMany relation on both tables to get the parent/children fields. But this will require specifying the items manually and doesn't ensure consistency.

**Comment by coderdix** [comment] 2020-08-03 13:55
Having the same issue

**Comment by lauriejim** [comment] 2020-08-04 18:22
Hello! Please check this discussion - https://github.com/strapi/strapi/discussions/7231 - this can help you to customize the `/users/me` endpoint.

**Comment by derrickmehaffy** [comment] 2021-11-30 14:30
MongoDB is not supported anymore in Strapi v4, marking as closed

**Closed by derrickmehaffy** 2021-11-30 14:30 UTC
Labels: type: discussion
