### ISSUE TITLE
Yarn develop commands result in error after create strapi-app

### ISSUE THREAD

**Issue by sebaschartrand** [strapi/strapi#7684] opened 2020-09-02 03:11 UTC
**Describe the bug**
When create a new app with this command : 
`yarn create strapi-app my-project --quickstart`

In the script sequence, an error is throw at : `yarn develop`
_Expected pattern to be non-empty string_

**Steps to reproduce the behavior**
1. Just run this command : `yarn create strapi-app my-project --quickstart`

**Expected behavior**
Clean install

**Screenshots**
![image](https://user-images.githubusercontent.com/70615827/91927383-5e0faa80-eca7-11ea-81c1-c3db7d1eb8aa.png)

**System**

- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.4
- Database: 
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment] 2020-09-02 14:20
I'm guessing in this case it's due to that file path `D:\[ GIT ]\_strapi\strapi-sandbox`

Is this in WSL/WSL2?

**Comment by MattieBelt** [comment] 2020-09-02 14:36
Looks to me like Git Shell for windows.

**Comment by sebaschartrand** [comment] 2020-09-02 15:47
I use Git Bash as terminal.
Indeed, he doesn't like special characters in the file path.
Everything works fine without!

Thanks.

**Comment by derrickmehaffy** [comment] 2020-09-02 17:23
Marking as closed then, my guess here is the issue is with the spaces ;)

**Closed by derrickmehaffy** 2020-09-02 17:23 UTC
Labels: type: help wanted
