### ISSUE TITLE
Update of a component in a dynamiczone with unique on its prop causes error

### ISSUE THREAD

**Issue by diestrin** [strapi/strapi#13583] opened 2022-06-16 20:40 UTC
### Required System information

- Node.js version: 16.15.1
- NPM version: 8.11.0
- Strapi version: 4.1.12
- Database: postgres
- Operating system: linux (docker node:16 image)

### Describe the bug

After creating a page with a `dynamiczone` section and adding a component with a `unique` field, when updating this page, the editor shows an error saying the key must be unique, unless changed to a different value than the previous one.

### Steps to reproduce the behavior

1. Create a component with a content similar to this one:
```json
{
  "collectionName": "components_generics_key_values",
  "info": {
    "displayName": "KeyValue",
    "icon": "key"
  },
  "options": {},
  "attributes": {
    "key": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "value": {
      "type": "text",
      "required": true
    }
  }
}
```
2. Create a `content-type` similar to this one:
```json
{
  "kind": "collectionType",
  "collectionName": "pages",
  "info": {
    "singularName": "page",
    "pluralName": "pages",
    "displayName": "Page",
    "name": "page"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "Title": {
      "type": "string",
      "required": true,
      "unique": false
    },
    "CustomFields": {
      "type": "dynamiczone",
      "components": [
        "generics.key-value"
      ]
    }
  }
}
```
4. In the strapi administrator create a new instance of the `page` `content-type`, making sure to add a keyValue component and filling it with some content
5. Save the previous content, and then try to update something and save it again
6. You get the error saying the key of the keyValue component must be unique

### Expected behavior

It should update the page content without problems

### Screenshots

![image](https://user-images.githubusercontent.com/909327/174159748-efa7bf5d-9e93-4522-9542-fa61b33869f8.png)

**Comment by kasonde** [comment] 2022-06-24 10:51
Setting this as a duplicate of #12541

**Closed by kasonde** 2022-06-24 10:51 UTC
