### ISSUE TITLE
Validation error after upgrade from CE to EE

### ISSUE THREAD

**Issue by zhmura** [strapi/strapi#10123] opened 2021-04-23 15:40 UTC
### Describe the bug

Strapi license type: Enterprise.
Admin panel issue: User create form submit is finished with 'Validation Error' (Error code: 400, Bad request)
Downgrading Strapi to Community Edition resolves the problem because SSO switcher is not provided at all.

### Steps to reproduce the behavior

1. Go to 'Admin Panel -> Settings -> Users'
2. Click on 'Create new User'
3. Fill in all fields. Leave "enable SSO" switcher in any state.
4. See Validation error.

### Expected behavior
User is created successfully.

### Code snippets
We have to add manually additional logging in /strapi-admin/controllers/user.js here:

```
    try {
      await validateUserCreationInput(body);
    } catch (err) {
      console.error(err, err.stack);
      return ctx.badRequest('ValidationError', err);
    }
```

Log output for the error: { undefined: [ ‘this field has unspecified keys: useSSORegistration’ ] }

### System

- Node.js version: 12.6.1
- NPM version: 6.13.4
- Strapi version: 3.5.3
- Database: postgresql
- Operating system: Ubuntu

### Additional context

Please, also add better logging to avoid manual admin panel code modification to see validation or any other error problems in logs instead of pure http error code.

**Comment by derrickmehaffy** [comment] 2021-04-27 14:45
Hi @zhmura I am unable to reproduce this issue, please see the following Loom link

https://www.loom.com/share/4d4799b0c729482aba31e17318c72524

Do you have any other steps that may help us reproduce the issue?

Also:

> Strapi version: 3.5.3

Can you please try with the currently latest version v3.6.0

**Comment by derrickmehaffy** [comment] 2021-07-22 21:47
No new information added, closing as unable to reproduce with existing information

**Closed by derrickmehaffy** 2021-07-22 21:47 UTC
Labels: severity: low, source: admin, status: can't reproduce, type: bug

**Comment by cloakedninjas** [comment] 2021-11-23 09:12
This is happening to me with a 24hr Strapi demo project `api-hw63j`

- Create demo project
- Login to admin
- Settings -> User -> Create new user -> Submit

```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": "ValidationError",
  "data": {
    "": [
      "this field has unspecified keys: useSSORegistration"
    ]
  }
}
```
