### ISSUE TITLE
Really slow response on rest api with +50 elements

### ISSUE THREAD

**Issue by carloshs94** [strapi/strapi#5374] opened 2020-03-01 20:13 UTC
**Describe the bug**
Im adding content to the strapi server and its getting really slow. 
i do have 67 elements and the api response time is about 9-12 seconds

the content type does not have any relational content. is like this:
- 1 enum
- 2 booleans
- image
- repeatable content with 2 images. (usually 10-15 components each)

Im just trying to get all the content in the api call.

**Expected behavior**
Not to take seconds on the api response

**Screenshots**
N/A
**Code snippets**
N/A

**System**
- Node.js version: 12.14.1
- NPM version: 6.13.4
- Strapi version: v3.0.0-beta.18.7
- Database: mongodb
- Operating system: ubuntu 18.04

When the Strapi admin panel list the items its also slow, probably the same time (9-12 seconds)

**Comment by derrickmehaffy** [comment] 2020-03-02 14:36
I believe @soupette was already working on this, I can't seem to find the other issue though.

It's related to the react dom loading hidden UI elements.

**Comment by carloshs94** [comment] 2020-03-02 16:03
> I believe @soupette was already working on this, I can't seem to find the other issue though.
> 
> It's related to the react dom loading hidden UI elements.

But that's related with the admin panel listing the items? i think is the same problem. The api call to get every item.

As i comment, its easy to recreate this problem. create a content type like the one im describing and add multiple of them (with multiple repeatable components also). It will get slower with every new item added.

With 10 items the api response time is useless (from 300ms to 2-3 seconds) and im not refering to the api call made on the admin panel. im talking about a rest api call

**Comment by davidemorra** [comment] 2020-03-03 14:04
I also have some issue on performance .. 
https://github.com/strapi/strapi/issues/5274

**Comment by Naxomiun** [comment] 2020-03-03 19:43
I can confirm this issue. I'm trying to load +- 70 items and the JSON response takes between 10-12 seconds.

**Comment by soupette** [comment] 2020-03-04 15:22
Indeed it is not related to the admin panel.

**Comment by roelbeerens** [comment] 2020-03-10 22:07
Isn't this related to the media items in the repeatable field which are forced populated? I do think uploads have some kind of impact when used in combination with a repeatable field (like a gallery for instance). Isn't this because of the forced population of uploads (and maybe some 1+n problem?) It looks like when a repeatable field has a relation (which it has when a upload is present) it fires a query for each entry in the repeater. 

If I'm totally off here, please correct me. I haven't tested it on a MySQL database yet, so it could also be a mongo issue.

I did cut down some load by writing a custom query preventing the population but somehow the amount of items in the repeater does have impact on the response time (still)

**Comment by carloshs94** [comment] 2020-03-11 20:46
Could be possible to add a component like file upload but without relations? its really helpful for uploading assets which doesnt need any other relation and could return/save the path, the url or filename to make the complete url by yourself (knowing the public folder of the uploaded files).

**Comment by lauriejim** [comment] 2020-03-21 14:01
Thank you for reporting this - I ping @alexandrebodin

**Comment by inverleighdigital** [comment] 2020-04-20 23:22
I am also experiencing a similar issue. very slow load times with 50+  items with relations.
I'm seeing load times of over 10 seconds. Also using mongoDB.

**Comment by inverleighdigital** [comment] 2020-04-24 04:56
> Thank you for reporting this - I ping @alexandrebodin

As additional information I can confirm that repeatable component appears to be the main culprit. when I disable the load improves dramatically.   I have observed one request take over 12 seconds. 10 seconds  is strapi delay in getting the repeatable component data and process the 1 response.
![Screen Shot 2020-04-23 at 6 45 14 pm](https://user-images.githubusercontent.com/49383127/80176384-c389c580-863b-11ea-8871-4e852787bde0.png)

**Comment by alexandrebodin** [comment] 2020-04-24 08:18
@inverleighdigital Are you using mongoatlas by any chance ?

**Comment by inverleighdigital** [comment] 2020-04-24 08:39
Yes

**Comment by inverleighdigital** [comment] 2020-04-24 08:40
> @inverleighdigital Are you using mongoatlas by any chance ?

Yes. we are.

**Comment by alexandrebodin** [comment] 2020-04-24 08:45
Using mongo atlas means your server and database can be really far from each other and makes queries roundtrips longer. There are more queries to run when using components and relations. This can make a small latency difference become really an issue when your data grows.

The most important factor of speed is the latency between your server and database. This would also be an issue with a SQL db too.

**Comment by davidemorra** [comment] 2020-04-24 08:49
> Using mongo atlas means your server and database can be really far from each other and makes queries roundtrips longer. There are more queries to run when using components and relations. This can make a small latency difference become really an issue when your data grows.
> 
> The most important factor of speed is the latency between your server and database. This would also be an issue with a SQL db too.

and what about this?
https://github.com/strapi/strapi/issues/5274

**Comment by alexandrebodin** [comment] 2020-04-24 09:12
@davidemorra When doing this query I can the answer with a database of 10k users in 15ms. I would need to know the schema you have / the database setup and such to start investigating.

Right now I cannot reproduce much of those issues except when using either a really low performance cloud database or with a really long distance one.

**Comment by davidemorra** [comment] 2020-04-24 09:23
@alexandrebodin we didn't change anything in this schema, and the issue is related only on query made on Users so:

Strapi version: 3.0.0-beta.18.7
https://github.com/strapi/strapi/blob/v3.0.0-beta.18.7/packages/strapi-plugin-users-permissions/models/User.settings.json

(_feel free to reopen my ticket if better_)

**Comment by inverleighdigital** [comment] 2020-04-24 11:02
> Using mongo atlas means your server and database can be really far from each other and makes queries roundtrips longer. There are more queries to run when using components and relations. This can make a small latency difference become really an issue when your data grows.
> 
> The most important factor of speed is the latency between your server and database. This would also be an issue with a SQL db too.

In our case both Mongodb an our sraepi servers are in the same AWS region. 
As I mentioned I am also seeing issues when testing mysql though not as bad. 
when disabling the repeating component the performance  improves dramatically.
All our testing points to an  issue with strapi or the data structure.

**Comment by alexandrebodin** [comment] 2020-04-24 12:06
@inverleighdigital Can you give me a rough estimate of the size of your datastrucutre ? how many components in your model etc ?

**Comment by inverleighdigital** [comment] 2020-04-24 19:30
> @inverleighdigital Can you give me a rough estimate of the size of your datastrucutre ? how many components in your model etc ?

Can I send privately

**Comment by alexandrebodin** [comment] 2020-04-26 13:45
Ok so something related to relation + compos. Could you share your model settings.json ? (you can send this in DM on the public slack ;)

**Comment by inverleighdigital** [comment] 2020-04-27 20:41
> Ok so something related to relation + compos. Could you share your model settings.json ? (you can send this in DM on the public slack ;)

Done.

**Comment by jackneo216** [comment] 2020-06-03 18:49
I deployed Strapi on Heroku. It's too slow. It takes 40 secs ( 40, 000 ms ) to download all the resources.

**Comment by alexandrebodin** [comment] 2020-06-04 08:17
Right now the performance bottleneck is the relation population that is done by the underlying ORMs. We can't really make any significant improvements on that matter. The only possible solution is to restrict the relations / components / images loaded when querying data. You can use autoPopulate options to restrict which relations are loaded for example. 

We plan on improving granularity to better select what you want in your data so you can optimized queries. 

I'm Locking the conversation for this issue as we are aware of what we can improve and plan to do it in the future.

**Comment by derrickmehaffy** [comment] 2021-11-30 14:30
Should be fixed in the v4, marking as closed

**Closed by derrickmehaffy** 2021-11-30 14:30 UTC
Labels: type: enhancement, severity: medium, status: confirmed, source: core:framework
