### ISSUE TITLE
Upload provider local

### ISSUE THREAD

**Issue by dakshrathod40** [strapi/strapi#4077] opened 2019-09-23 07:59 UTC
**Describe the bug**
I am using upload feature in my application it worked fine till date but i have started facing unkwin issue saying **The provider package isn't installed. Please run `npm install strapi-provider-upload-local`**
While after doing also doesnt solve
**Steps to reproduce the behavior**
1. Go to File Upload
2. Click on Browse
3. Select file and save
4. See error in console

**Expected behavior**
Upload works fine

**Screenshots**
![Error1](https://user-images.githubusercontent.com/48468251/65409692-01084500-de06-11e9-8fda-7f377e862ab8.PNG)

**System**
- Node.js version: 11.4.0
- NPM version: 6.7.0
- Strapi version: 3.0.0-beta.7
- Database: Mongodb
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment] 2019-09-23 08:29
@dakshrathod40 two things:
You are on an unsupported node version: `Node.js version: 11.4.0` Use either node 10 or node 12
Test on the latest version of Strapi which I believe is beta.16.5: `Strapi version: 3.0.0-beta.7`

**Comment by dakshrathod40** [comment] 2019-09-23 08:31
I think that doesnt help
Because it seemed to be working fine till now on given confiuration
If it really  mattered then it should have worked before??

**Comment by derrickmehaffy** [comment] 2019-09-23 08:33
Debugging of issues only happens on latest releases, if it can't be reproduced on the latest version using the required node, npm versions then it isn't classified as a bug. Most likely you had some old cached packages.

**Comment by derrickmehaffy** [comment] 2019-09-23 08:34
Using your steps to reproduce on a fresh beta.16.5 I could not reproduce it, and to find the source of the bug we need to be able to reproduce it.

**Comment by lauriejim** [comment] 2019-09-23 12:05
Hello @dakshrathod40 !
Can you send us `dependencies` of your `package.json` files.
And tell me if you use `yarn` or `npx` (or an other way) and the command you use to start your application.

**Comment by derrickmehaffy** [comment] 2019-10-09 11:30
@dakshrathod40 I'm marking this as closed for now, if you can please provide the information that @lauriejim asked for we can reopen this. Thanks!

**Closed by derrickmehaffy** 2019-10-09 11:30 UTC
Labels: type: help wanted 🤷‍♂️
