### ISSUE TITLE
problem installing 3.5.0 by npx

### ISSUE THREAD

**Issue by noamtahan** [strapi/strapi#9450] opened 2021-02-18 17:28 UTC
Hi,
after run the command on my server
ubuntu : 20.04
node: v14.15.5
npm: 7.5.4

`npx create-strapi-app my-project --quickstart
`
I get

```
Creating a new Strapi application at /root/my-project.

Creating a quickstart project.
Creating files.
Error while installing dependencies:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-project@0.1.0
npm ERR! Found: knex@0.19.5
npm ERR! node_modules/knex
npm ERR!   knex@"<0.20.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"^0.20.0" from strapi-connector-bookshelf@3.5.0
npm ERR! node_modules/strapi-connector-bookshelf
npm ERR!   strapi-connector-bookshelf@"3.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-18T17_27_16_804Z-debug.log
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your p                                                       roject.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following                                                        command:

cd /root/my-project && npm install

npm ERR! code 1
npm ERR! path /root
npm ERR! command failed
npm ERR! command sh -c create-strapi-app "my-project" "--quickstart"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-18T17_27_17_934Z-debug.log
```

**Comment by derrickmehaffy** [comment] 2021-02-18 18:09
```
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"^0.20.0" from strapi-connector-bookshelf@3.5.0
```

Can you check your npm registry settings to see if you are using a 3rd party registry or proxy?

**Comment by nik0145** [comment] 2021-02-18 20:15
same problem :(

**Comment by nik0145** [comment] 2021-02-18 20:43
Just use yarn, it helped me.

**Comment by ruijt** [comment] 2021-02-19 08:25
same as my issue #9383

**Comment by Gaetax** [comment] 2021-02-19 13:18
Got the same issue, a quick look into strapi's developer decumentation gave me the solution : 
"Strapi only supports LTS versions of Node.js, the current recommended version to run Strapi is Node LTS v14. Other versions of of Node.js may not be compatible with the latest release of Strapi." 
I've install the latest LTS version of nodeJs on my Mac, and it works perfectly now :)


Hope it will help you, 
Have a nice day

**Comment by noamtahan** [comment] 2021-02-19 13:28
@derrickmehaffy  I have only https://registry.npmjs.org/
@nik0145 But maybe there is a bug with package.json dependencies using npm?
@ruijt I also failed to upgrade, but I tried also to reinstall in a new system, ant got those errors also.
@Gaetax nodejs v14.15.5 is LTS.
still not working.

**Comment by noamtahan** [comment] 2021-02-19 13:30
cat /root/.npm/_logs/2021-02-19T13_29_19_640Z-debug.log
`49 verbose stack Error: unable to resolve dependency tree
49 verbose stack     at Arborist.[failPeerConflict] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1136:25)
49 verbose stack     at Arborist.[loadPeerSet] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1116:34)
49 verbose stack     at async Arborist.[buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:834:11)
49 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
49 verbose stack     at async Promise.all (index 1)
49 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:127:5)
49 verbose stack     at async install (/usr/lib/node_modules/npm/lib/install.js:38:3)
50 verbose cwd /home/my-project
51 verbose Linux 5.4.0-65-generic
52 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--production" "--no-optional"
53 verbose node v14.15.5
54 verbose npm  v7.5.4
55 error code ERESOLVE
56 error ERESOLVE unable to resolve dependency tree
57 error
58 error While resolving: my-project@0.1.0
58 error Found: knex@0.19.5
58 error node_modules/knex
58 error   knex@"<0.20.0" from the root project
58 error
58 error Could not resolve dependency:
58 error peer knex@"^0.20.0" from strapi-connector-bookshelf@3.5.0
58 error node_modules/strapi-connector-bookshelf
58 error   strapi-connector-bookshelf@"3.5.0" from the root project
58 error
58 error Fix the upstream dependency conflict, or retry
58 error this command with --force, or --legacy-peer-deps
58 error to accept an incorrect (and potentially broken) dependency resolution.
58 error
58 error See /root/.npm/eresolve-report.txt for a full report.
59 verbose exit 1
`

**Comment by Igorgro** [comment] 2021-02-19 16:56
+1, Having exactly same problem even using custom setup mode.
<details>
<summary>Log</summary>

```
Creating a new Strapi application at /home/igormahov/dev/strapi/test-app.

? Choose your installation type Custom (manual settings)
? Choose your default database client postgres
? Database name: strapi
? Host: localhost
? Port: 5432
? Username: postgres
? Password: *
? Enable SSL connection: No

⛔️ Connection test failed: Command failed: npm install --prefix /tmp/strapi60ac1159482a strapi-connector-bookshelf@3.5.0 knex@<0.20.0 pg@latest
npm notice 
npm notice New patch version of npm available! 7.5.2 -> 7.5.4
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.5.4>
npm notice Run `npm install -g npm@7.5.4` to update!
npm notice 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: knex@0.19.5
npm ERR! node_modules/knex
npm ERR!   knex@"<0.20.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"^0.20.0" from strapi-connector-bookshelf@3.5.0
npm ERR! node_modules/strapi-connector-bookshelf
npm ERR!   strapi-connector-bookshelf@"3.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/igormahov/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/igormahov/.npm/_logs/2021-02-19T16_49_19_420Z-debug.log



Retrying...
```
</details>

OS: Debian Unstable (bullseye)
Node version: v12.20.1

**Comment by takahiro-yonei** [comment] 2021-02-19 17:49
+1, I'm having the same problem.

* node: v12.18.2
* npm: 7.5.1
* os: mac os 10.15.7

```
? Choose your installation type Custom (manual settings)
? Choose your default database client postgres
? Database name: try-strapi-350
? Host: 127.0.0.1
? Port: 5432
? Username:
? Password:
? Enable SSL connection: No

⛔️ Connection test failed: Command failed: npm install --prefix /var/folders/dt/wq6c3gpj2cl2s8vdfk_23p15qbkwsh/T/strapi874de1e4501c strapi-connector-bookshelf@3.5.0 knex@<0.20.0 pg@latest
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: knex@0.19.5
npm ERR! node_modules/knex
npm ERR!   knex@"<0.20.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"^0.20.0" from strapi-connector-bookshelf@3.5.0
npm ERR! node_modules/strapi-connector-bookshelf
npm ERR!   strapi-connector-bookshelf@"3.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

might the above error be related to the below?

https://github.com/strapi/strapi/blob/6d252b12e103fecf5771424e2379a5a1c8642866/packages/strapi-generate-new/lib/utils/db-client-dependencies.js#L20-L26

strapi-connector-bookshelf@3.5.0 requires knex "^0.20.0",
but "custom-setup" might try to test db connection with the above dependencies ( knex "<0.20.0" )
( and might confilicts )

I appreciate it might be helpful to solve this problem.
thanks in advance.

**Comment by MuradBuyukasik** [comment] 2021-02-20 00:12
> Got the same issue, a quick look into strapi's developer decumentation gave me the solution :
> "Strapi only supports LTS versions of Node.js, the current recommended version to run Strapi is Node LTS v14. Other versions of of Node.js may not be compatible with the latest release of Strapi."
> I've install the latest LTS version of nodeJs on my Mac, and it works perfectly now :)
> 
> Hope it will help you,
> Have a nice day

I downgraded to LTS but this did not work for me. A simple but bad workaround for me was to init Strapi on my dualboot machine using Windows 10 and then booting into Linux to continue development.

**Comment by noamtahan** [comment] 2021-02-21 14:37
One more test on windows 10;
node: v14.15.5
npm: 7.5.4

same problem

**Comment by noamtahan** [comment] 2021-02-21 14:43
@takahiro-yonei You are absolutely right,
but what is the correct one?
knex@"<0.20.0" gives knex@0.19.5 or knex@"^0.20.0"?

**Comment by takahiro-yonei** [comment] 2021-02-22 04:57
> knex@"<0.20.0" gives knex@0.19.5 or knex@"^0.20.0"?

I think it's knex@0.19.5.

**Comment by derrickmehaffy** [comment] 2021-02-22 14:16
> npm: 7.5.4

### Please note

**We do not support Node "Odd Versions" AKA non-LTS versions such as Node v13/15** 
Also we currently don't support NPM >v6
See: https://strapi.io/documentation/developer-docs/latest/getting-started/deployment.html#recommended-requirements

---

On that note, per this comment: https://github.com/strapi/strapi/issues/9383#issuecomment-782269472

We do probably need to review the dependencies inside of the strapi-connector-bookshelf to modify that knex depends. If anyone wants to submit a PR please do.

**Comment by takahiro-yonei** [comment] 2021-02-22 15:08
@derrickmehaffy 
thank you so much for your comment.

I modified npm config `legacy-peer-deps` to `true` and tried to `strapi new` again. And finally, I could create a new strapi app (v3.5.0).
https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps

As you commented, we should use npm v6.x or set `legacy-peer-deps` as true.
(or submit a PR.)
Thank you so much again.

**Comment by noamtahan** [comment] 2021-02-22 15:56
@derrickmehaffy Thank!
the issue is that npm: V7.5.4 is installing when installing node: v14.15.5 LTS.
So, for now, we can install strapi can be done in one way below
1. after downgrade npm -v  `npm i npm@6.14.11`
2. Set legacy-peer-deps to true in  `npm i npm` (latest - V7)

Thanks a lot.

**Comment by cullylarson** [comment] 2021-02-22 18:00
I posted a pretty simple workaround in another issue: https://github.com/strapi/strapi/issues/9383#issuecomment-780232124

**Comment by acalvino4** [comment] 2021-02-23 18:51
Doesn't seem like this should have been closed quite yet, since a workaround is not quite the same as being fixed - looks that that caused the automator to move it to 'Fixed' on the issues board, which it is not.

**Comment by cullylarson** [comment] 2021-02-23 19:24
@acalvino4 I got a reply to a similar issue saying that strapi doesn't support npm 7. I think that might be why the issue was closed.

**Comment by mirkonasato** [comment] 2021-02-24 12:03
I agree with @acalvino4: the issue should not have been closed. It had been marked as `confirmed`.

The unresolved problem is that there is an incompatibility between the `knex` version required by `strapi-connector-bookshelf` (0.20.x) and the one declared by the project generated by `create-strapi-api` (0.19.x).

This is only reported as an error by npm 7, but it's still there even if you use npm 6 or yarn. In fact yarn does report it as a warning:

```
warning " > strapi-connector-bookshelf@3.5.1" has incorrect peer dependency "knex@^0.20.0".
```

**Comment by derrickmehaffy** [comment] 2021-02-24 13:15
Please do feel free to create a PR :)

**Comment by mirkonasato** [comment] 2021-02-24 15:15
I cloned the `strapi` repo to create a PR, but the [e2e tests](https://github.com/mirkonasato/strapi/blob/master/CONTRIBUTING.md#running-the-tests) fail for me, before making any changes.

```
% node test/e2e.js --db=sqlite
...
[2/73] (3%) Running packages/strapi-admin/tests/admin-auth.test.e2e.js
  ●  process.exit called with "1"
```

As far as I can tell, the `knex` version for a new project is set to `<0.20.0` i.e. 0.19.x in [strapi-generate-new/lib/utils/db-client-dependencies.js](https://github.com/strapi/strapi/blob/master/packages/strapi-generate-new/lib/utils/db-client-dependencies.js#L17), while [strapi-connector-bookshelf/package.json](https://github.com/strapi/strapi/blob/master/packages/strapi-connector-bookshelf/package.json#L29) expects `^0.20.0` i.e 0.20.x, and [examples/getstarted/package.json](https://github.com/strapi/strapi/blob/master/examples/getstarted/package.json#L15) uses 0.21.x (`^0.21.14`).

**Comment by derrickmehaffy** [comment] 2021-02-24 17:48
Hi thread repliers!

Can I have you check the above attached PR to test if it fixes the issue you were seeing? We were able to reproduce the issue locally so I wanted to make sure that it solves the issue.

**Comment by mirkonasato** [comment] 2021-02-24 19:07
@derrickmehaffy seems fine to me, with the defaults i.e. sqlite. Here's how I tested it:

* upgraded npm to v7: `npm install -g npm`
* checked out the `fix/fix-knex-version` branch
* created a new app with `node packages/create-strapi-app --quickstart --use-npm ../test-app`
  * this failed because it used the published version of `strapi-connector-bookshelf`, not the locally modified one
* in `test-app` set `"strapi-connector-bookshelf": "file:../strapi/packages/strapi-connector-bookshelf"` to use the local version
* ran `npm install` again and this time it worked

**Closed** 2021-02-24 20:59 UTC
Labels: good first issue, severity: low, source: core:database, status: confirmed, type: bug

**Comment by sarazeaiter1** [comment] 2021-06-11 13:00
I had the same error, after checking the node version by running `node -v` in the command line, it showed that I have v16.2.0

so I run `nvm use v12.21.0` and then `npm install`, everything worked as expected
