### ISSUE TITLE
Can't add advanced settings on date field

### ISSUE THREAD

**Issue by majdi** [strapi/strapi#4848] opened 2019-12-28 11:25 UTC
**Describe the bug**
Hello, a simple bug on content-type field creation, if we want to add a date with any advanced settings an error occurred.

**Steps to reproduce the behavior**
1. Go to Content-Type builer
2. Click on ADD ANOTHER FIELD TO THIS CONTENT-TYPE
3. Add a Date field and choose Required field on advanced settings
4. Finish + save

**Expected behavior**
Normally it works :p

**System**
- Node.js version: v12.13.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.3
- Database: sqlite
- Operating system: Darwin 19.2.0 Darwin Kernel Version 19.2.0; root:xnu 6153.61.1~20/RELEASE_X86_64 x86_64

Thanks 😄

**Comment by lauriejim** [comment] 2019-12-31 14:10
Hello! I just tried and I was not able to reproduce.
[Here](https://www.loom.com/share/2a57009c0e454df1978f056833c18287) is what I did.
Maybe I missed something.

**Comment by Gary-KK** [comment] 2020-01-08 19:32
@lauriejim Only `datetime` or `time` type has this problem, `date` type does not have this problem

The error thrown is `contentType.attributes.XXX field cannot have keys not specified in the object shape`
Looks like the validation failed for `datetime` or `time` type

**Comment by Gary-KK** [comment] 2020-01-08 19:44
Looks like save error fixed in
https://github.com/strapi/strapi/commit/4965846d363eee621a4182f35d1b1a4539a58318

**Comment by derrickmehaffy** [comment] 2020-01-08 20:08
Marking closed as this should be fixed in https://github.com/strapi/strapi/pull/4944 and https://github.com/strapi/strapi/pull/4945

**Closed by derrickmehaffy** 2020-01-08 20:08 UTC
Labels: type: help wanted 🤷‍♂️

**Comment by majdi** [comment] 2020-01-08 20:29
Cool thanks :)

**Comment by iedmrc** [comment] 2020-02-02 17:24
> @lauriejim Only `datetime` or `time` type has this problem, `date` type does not have this problem
> 
> The error thrown is `contentType.attributes.XXX field cannot have keys not specified in the object shape` (In this case, it rejects `required` key when you check Required in advanced settings)
> Looks like no/invalid validation rule for `datetime` or `time` type? It should at least accept `required` key
> 
> Also the default input editor mismatch the selected type

Hey,
I had the exact same issue and it's been fixed in #4944 and #4945 as @derrickmehaffy said. Thanks for fixing but I have a question to @majdi :
How did you print that detailed error log.
I mean the 

> The error thrown is `contentType.attributes.XXX field cannot have keys not specified in the object shape` 

part. 
I just had `debug PUT /content-type-builder/content-types/application::video.video (12 ms) 400`.
Thanks!

**Comment by majdi** [comment] 2020-02-02 20:17
Hi @iedmrc, actually it's not me but @Gary-KK,  I didn't have this kind of error log :)

**Comment by iedmrc** [comment] 2020-02-02 21:05
Sorry for the confusion :)

**Comment by SylTi** [comment] 2020-02-03 13:30
I seem to have a related issue when trying to add an advanced setting on a Rich Text 
`contentType.attributes.About field cannot have keys not specified in the object shape`

My strapi version: v3.0.0-beta.18.7

@iedmrc for the error log check out your browser debugger.

**Comment by iedmrc** [comment] 2020-02-05 13:02
> I seem to have a related issue when trying to add an advanced setting on a Rich Text
> `contentType.attributes.About field cannot have keys not specified in the object shape`
> 
> My strapi version: v3.0.0-beta.18.7
> 
> @iedmrc for the error log check out your browser debugger.

Thank you for your reply. I use firefox and that's all I see in the debugger:

<img width="1919" alt="Ekran Resmi 2020-02-05 15 59 16" src="https://user-images.githubusercontent.com/13666448/73843871-8a0d9f00-4830-11ea-973b-654e307d6109.png">

And also, why logs are sent to my browsers debugger? I hope to see the errors flashed to STDOUT or STDERR on my shell.

**Comment by SylTi** [comment] 2020-02-05 13:17
Sorry my bad, it's in the network tab, if you look at the request that failed, you should see the error in the response..

**Comment by iedmrc** [comment] 2020-02-05 13:25
Thanks! I'll check out.
