### ISSUE TITLE
Many to Many duplicate entries

### ISSUE THREAD

**Issue by ivanguimam** [strapi/strapi#1729] opened 2018-08-08 14:32 UTC
**Informations**
- **Node.js 10.5.0**:
- **npm 6.1.0**:
- **Strapi 3.0.0-alpha.13.0.1**:
- **Mongodb**:
- **Ubuntu**:

**What is the current behavior?**

When I have a many-to-many ratio, the elements are getting duplicated.

Ex: There is the entity state and units.

    State: {
        Name: ' STRING ',
        Operating: ' ARRAY of units '
    }

    Unit: {
        Name: ' STRING '
    }

In my relationship several units can belong to various states. Only that when I will relate the data in the ADMIN panel, if I open a state and connect it to a drive works, but if I open a drive and bind it to a state it duplicates the data that were in the state.operating

**Steps to reproduce the problem**

Only that when I will relate the data in the ADMIN panel, if I open a state and connect it to a drive works, but if I open a drive and bind it to a state it duplicates the data that were in the state.operating

**What is the expected behavior?**

Other than duplicate elements

**Suggested solutions**
In the strapi-hook-mongoose Lib in the relations.js file on line 133 has the following if:

    if (_.isArray(entry[details.via])) {
        value[details.via] = entry[details.via].map(entry => _.get(entry, '_id', entry)).concat(value[details.via]);
    }

This is causing you to duplicate the data, my suggestion and exchange for this if:

    if (_.isArray(entry[details.via])) {
        value[details.via] = entry[details.via]
            .map(entry => _.get(entry, '_id', entry).toString())
            .concat(value[details.via])

        value[details.via] = _.uniq(value[details.via])
    }

So it will remove all duplicate IDs

There is this [PR 1669](https://github.com/strapi/strapi/issues/1669) that talk that corrected this problem but it does not

**Comment by lauriejim** [comment] 2018-08-09 13:13
@ivanguimam Can you check if it still happen in last version of Strapi (3.0.0-alpha.13.1)

**Comment by ivanguimam** [comment] 2018-08-14 16:13
I'm sorry I didn't tell you @lauriejim , I've been very busy at work these past few weeks and I haven't had time to test. But according to @fisher08  he still exists

**Comment by avdeyev** [comment] 2018-09-22 18:08
Version 3.0.0-alpha.14.1.1
Bug still occurs.

**Comment by g-div** [comment] 2018-10-24 13:09
@lauriejim the bug is pretty easy to reproduce: create a `manyToMany` relation and add more than one single entry to the relation.
 I've found that the bug is coming from [these](https://github.com/strapi/strapi/blob/fa94519c1d6a4daba2ed5238afc1060e97f47ea1/packages/strapi-hook-mongoose/lib/relations.js#L133_L135) lines. IMHO these lines can be just deleted, but I don't understand at all what @Aurelsicoko was trying there. Should I submit a PR ?

**Comment by g-div** [comment] 2018-10-24 13:11
BTW the bug is still there in version 3.0.0-alpha.14.2

**Comment by lauriejim** [comment] 2018-10-26 14:50
Hello @g-div, yes can you submit a PR please.
Will appreciate your contribution on this issue. We definitively miss time to fix all issues, we need your help.

**Comment by Aurelsicoko** [comment] 2018-11-01 15:20
@g-div If my memories are correct, I added this line because the `manyToOne` relation wasn't working correctly either. Maybe this part of the code should be only executed in a specific scenario.

If you remove these lines, please make sure that the `manyToMany`, `manyToOne` and `oneToMany` relations work perfectly by using the admin panel with multiples entries. Also, test the relation from both sides.

**Comment by jckw** [comment] 2018-11-08 15:43
Shouldn't this be a high priority issue? Many to Many fields are completely unusable until this is solved.

**Comment by lauriejim** [comment] 2018-11-09 15:38
Th PR will be merged for the next release if all is correct.

**Closed** 2018-11-09 16:20 UTC
Labels: priority: high, status: confirmed, type: bug 🐛
