### ISSUE TITLE
Cannot name Content Type "staff"

### ISSUE THREAD

**Issue by Achder** [strapi/strapi#7187] opened 2020-07-26 19:09 UTC
I can't seem to create collections with certain names.
I ran into this bug while preparing a project and I find it very frustrating. I setup the same project several times and sooner or later always get the same "An error occured" message. Or in the console: `POST /content-type-builder/content-types (27 ms) 400`

By now I realized the error always occurs when trying to create the collection named "staff". I can create collections with other name. But never staff. I had the hunch, it might have to do with pluralization and tried fish. Same thing. Can't create it. 

I tried this several times with completely fresh installations.
Is it possible that this happens on collection names where plural equals singular?

Node.js: v13.13.0
Strapi: 3.1.1
Database: SQlite
Mac OS

**Comment by derrickmehaffy** [comment] 2020-07-26 23:27
Hi @Achder `Node.js: v13.13.0` This version of node isn't supported, please test again with the latest LTS release (v12) and please update the issue to follow the template (making it easier to read)

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/

Please ensure you have also read and understand the contributing guide.

https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by lauriejim** [comment] 2020-07-27 09:12
Thank you for reporting this issue. We have a list of names that cause issues ... Thank you for reporting this one.
For now I suggest you to use another name :/
There is no workaround for that for now.

**Comment by Achder** [comment] 2020-07-27 20:26
The error itself is one thing. I think it’s worse, that it isn’t properly displayed. I had to check dev tools. The pop up only shows a generic message.

**Comment by soupette** [comment] 2020-07-28 07:31
@Achder I'll try to see if I can display these kind of error message more properly because I agree that the error displayed in the browser's console gives some useful information!

**Comment by intellecat** [comment] 2020-09-07 11:16
I encountered a simlar problem, I was trying to name a collection "series".
Database: Mysql

**Comment by axelra82** [comment] 2020-09-21 06:47
Same for "personnel".
Strapi 3.1.5, sqlite3.

**Comment by pavolhudran** [comment] 2020-11-13 09:10
I have also problem with name "series"

**Comment by budlight** [comment] 2021-03-28 03:09
I suspect this is a duplicate of #1198

**Comment by derrickmehaffy** [comment] 2021-03-29 18:59
It is @budlight thank you

Closing as duplicate of https://github.com/strapi/strapi/issues/1198

**Closed by derrickmehaffy** 2021-03-29 18:59 UTC
Labels: severity: medium, source: plugin:content-type-builder, status: confirmed, type: bug
