### ISSUE TITLE
Unauthorized" message: "Cast to ObjectId failed for value "14" at path "_id" for model "user"" statusCode: 401

### ISSUE THREAD

**Issue by Maris1984** [strapi/strapi#8539] opened 2020-11-01 13:03 UTC
- Node.js version: 12.16.1
- NPM version: 6.13.4
- Strapi version: 3.2.5
- Database: MongoDB Atlas
- Operating system: OSX 10.11

Attached a MongoDB Atlas database to an already existing Strapi instance (with Content Types already build).
Successfully got connected, created an admin user and was able to log in the admin panel.
Created a new role with all possible permissions assigned.
Created a new user and assigned to the newly created role.
Tried to log in the front-end (CRA) and upon sending a POST request to **http://localhost:1337/auth/local** with valid user and password ({identifier: "mynewuser", password: "mypassword"}), receive the following response:

> {statusCode: 401, error: "Unauthorized",…}
> error: "Unauthorized"
> message: "Cast to ObjectId failed for value "14" at path "_id" for model "user""
> statusCode: 401

When I deploy the very same version of code to Heroku, which is also connected to the very same MongoDB Atlas collection, there is no errors and I am able to successfully log in with newly created users.

What could be done to resolve this?

Thanks!

**Comment by aksdevac** [comment] 2020-11-02 05:09
Also post server error log with line number, it would be helpful for debugging. Also "14" is obviously an invalid Mongo Id so more debugging is needed.

**Comment by Maris1984** [comment] 2020-11-02 09:03
Since I'm on the free cluster of MongoDB Atlas, there are no logs available to download.
Also the Strapi terminal  does not output anything, as I try to log in and receive this error in Google Chrome console.
Is there any other place I could look for a more details about this exception?

**Comment by aksdevac** [comment] 2020-11-02 10:30
@Maris1984 ok strapi might be catching that error, you will need to debug server code by stepping into the code, you can start from [this line](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L23)

**Comment by derrickmehaffy** [comment] 2020-11-02 20:26
@Maris1984 two things to note here:

- We need steps to reproduce the bug, if you believe this issue to be caused by Strapi's code base, then steps are required for us to reproduce it, generally I would close out an issue like this for not following our bug report template, but it's an error I've not seen before. If you don't believe this is a bug in our code base, then please close this issue and post on our forum here: https://forum.strapi.io/
- Are you using an existing MongoDB database that was created by Strapi or a 3rd party application? If it's the former, we do not support external databases that Strapi did not create. The structure we use with MongoDB and Strapi doesn't follow all the best practices laid out in the MongoDB specification as we are treating MongoDB as a relational databases (even though, yes it's not) and we do not use child documents.

**Comment by Maris1984** [comment] 2020-11-02 20:44
Thank you for reply!
To be honest, I don't know if it's caused by Strapi codebase.
If you think it's not caused by the codebase, then close this and I'll continue to search for answers in forum.

Here's what I did:
- installed strapi-connector-mongoose in an existing Strapi instance, that were previously using SQLite (quickstart);
- created MongoDB Atlas collection and obtained the connection string, which I then placed in database.js;
- launched Strapi Admin page and successfully created the admin user, which obviously created all the tables in DB;
- created some content Types, fields, also - created a new Role and User.
- tried to log in the front-end (CRA) with that user and received the error 401 Unauthorized.
- for the sake of interest - deployed the very same instance to Heroku and repeated the steps.
This time I was able to logi-in without any issues.

If switching databases (especially from SQL Lite to Mongo) is not supported in this way, then we can certainly close this.

**Comment by derrickmehaffy** [comment] 2020-11-02 20:49
I think you are getting some kind of conflict due to the change from SQLite to Mongo, but it's quite odd. :thinking: 

I don't think it's directly related to the code-base so if you could move this over to the forum that would be great and I'll close this issue out. If after further discussion we determine it to be a bug I'll reopen this (can you please link this issue in your forum thread).

Also when you create the forum thread, if you could include a sample project that you can reproduce this in that would be handy.

**Closed by derrickmehaffy** 2020-11-02 20:49 UTC
Labels: status: can't reproduce
