### ISSUE TITLE
Strapi media library very slow or even fails to load when files are linked to multiple entities

### ISSUE THREAD

**Issue by weidox** [strapi/strapi#8020] opened 2020-09-24 06:50 UTC
**Describe the bug**
When files are linked to tens of entities, it taken very long to open media library. 

**Steps to reproduce the behavior**

1. Upload a single image to Strapi library.
2. Create a simple collection definition, having just single "file" property of type Media.
3. Fill collection with 50 records, all referencing the same file in Media Library.
4. Try to open Media Library.
5. See how long it takes to open media library, in my case it was 13 seconds.
debug GET /upload/files?_limit=10&_start=0&_sort=updatedAt:DESC (12788 ms) 200
6. Add 50 more records, see now 87 seconds.
debug GET /upload/files?_limit=10&_start=0&_sort=updatedAt:DESC (86799 ms) 200
7. Add 100 more records, go to make coffee, when you return if you're lucky you will have some number. I wasn't lucky and could not wait seemingly forever.

**Expected behavior**
Expected to be able to open Media Library under any circumstances, and in reasonable amount of time.

**Screenshots**
Not needed.

**Code snippets**
To quickly create 50 additional records on restart, may use this in bootstrap.js:
```
  const media = await strapi.query('file', 'upload').findOne({}, []);
  for (let i = 0; i < 50; i++) {
    await strapi.services['your-collection-with-file-property'].create({ file: media.id });
  }
```
**System**

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.4
- Database: MongoDB
- Operating system: both Linux and Windows

**Additional context**
As I figured out, each media item keeps track of linked entities in "related" property, and if this property gets loaded (by default, unless suppressed with populate parameter in query), it works unacceptably slowly.

**Comment by alexandrebodin** [comment] 2020-09-24 07:49
Hello, Please update the issue to match issue templates.  Closing this issue until it gets updated

**Comment by weidox** [comment] 2020-09-24 16:55
Updated.

**Comment by mukeshsolanki** [comment] 2020-10-30 09:52
Yes i agree im facing this exact issue as well

**Comment by zambawamba** [comment] 2021-01-03 11:30
@derrickmehaffy I'm having the same issue and I would say severity is definitely higher than low. At the moment I'm completely blocked from finishing work because the media library is essentially non-functional.

**Comment by sercanov** [comment] 2021-03-22 11:03
I can also confirm that Media Library performance degraded so bad after 2k of records. 
I assume it's because non-indexed queries to `upload_file` document via `related` field.

I'm using MongoDB Atlas M0 in the same AWS region as API

**Comment by andriichern** [comment] 2021-05-13 09:11
We faced the same issue in production. We can not add any items because Media Library count request makes the whole system frozen. In our case it takes the whole CPU resources and the only possible (and) temporary solution is to reload the whole strapi & mongo services. It definately should not work this way

**Comment by andriichern** [comment] 2021-05-20 12:33
@alexandrebodin After porforming some investigation and trying to find temporary work around solution now I can tell you the reason of this issue. Moreover I can tell for sure that it does not matter what DB you use: MongoDB, PostgreSQl or other.

As far as this issue arised for our production users this was very blocking for us. Firstly, we decide to change DB from `mongo` to `Postgres`. Secondly, we decided to made our own load testing of `strapi` system with the new DB. So we put 20000 records for our collection, (yes, 20000, and yes - we expect to work with such a huge amounts of records in the future and even more). We also put a few images to Media Library, just 4 items, because we use them very actively in our `strapi` data collection. Each item of those 20000 was connected to 1 specific image from Media Library. So in the end we had 20000 items and 4 images, and every image is linked to ~5000 items.

When we opend Media Library page from the `strapi` admin panel we saw the same situation: images were fetching too long. Not so long as with the `mongo`, but on our testing system (which is in the cloud) it was ~10 second. And this delay was caused by the same request: `GET /upload/files?_limit=10&_start=0&_sort=updatedAt:DESC`.

Querying this request with `Postman` gives us the first understanding of the root cause. The resulted response contains ALL linked collection items for EVERY image presented in the response. In our case it was array of 4 media objects (images) and every media object contains ~5000 linked collection items. All this data is present under `related` field in the madia object. The response json was about 9.5 MB (!!!) of size :flushed: and contained more than 300000 lines :disappointed:. Even `Postman` feels bad displaying that response to us :persevere:

Going through the source code of a `strapi-plugin-upload` proved our consideration. in the `File.settings.json` model definition there is a field `related`: 

```
"related": {
    "collection": "*",
        "filter": "field",
        "configurable": false
}
```

Thi is that same `related` field which we saw in the response cntained those huge amounts of data. And this is the field causing the slowdown for the whole Media Library.

P.S. To me it makes no sense to get all related items from all collections for media objects. Is it really necessary and what the purpose of it?

**Comment by alexandrebodin** [comment] 2021-05-21 07:34
> @alexandrebodin After porforming some investigation and trying to find temporary work around solution now I can tell you the reason of this issue. Moreover I can tell for sure that it does not matter what DB you use: MongoDB, PostgreSQl or other.
> 
> As far as this issue arised for our production users this was very blocking for us. Firstly, we decide to change DB from `mongo` to `Postgres`. Secondly, we decided to made our own load testing of `strapi` system with the new DB. So we put 20000 records for our collection, (yes, 20000, and yes - we expect to work with such a huge amounts of records in the future and even more). We also put a few images to Media Library, just 4 items, because we use them very actively in our `strapi` data collection. Each item of those 20000 was connected to 1 specific image from Media Library. So in the end we had 20000 items and 4 images, and every image is linked to ~5000 items.
> 
> When we opend Media Library page from the `strapi` admin panel we saw the same situation: images were fetching too long. Not so long as with the `mongo`, but on our testing system (which is in the cloud) it was ~10 second. And this delay was caused by the same request: `GET /upload/files?_limit=10&_start=0&_sort=updatedAt:DESC`.
> 
> Querying this request with `Postman` gives us the first understanding of the root cause. The resulted response contains ALL linked collection items for EVERY image presented in the response. In our case it was array of 4 media objects (images) and every media object contains ~5000 linked collection items. All this data is present under `related` field in the madia object. The response json was about 9.5 MB (!!!) of size 😳 and contained more than 300000 lines 😞. Even `Postman` feels bad displaying that response to us 😣
> 
> Going through the source code of a `strapi-plugin-upload` proved our consideration. in the `File.settings.json` model definition there is a field `related`:
> 
> ```
> "related": {
>     "collection": "*",
>         "filter": "field",
>         "configurable": false
> }
> ```
> 
> Thi is that same `related` field which we saw in the response cntained those huge amounts of data. And this is the field causing the slowdown for the whole Media Library.
> 
> P.S. To me it makes no sense to get all related items from all collections for media objects. Is it really necessary and what the purpose of it?

Have you tried extending the file model and adding `autoPopulate: false` ? Not sure this will work in this direction of the relation though but if not making a PR to allow this should be fairly easy

**Comment by andriichern** [comment] 2021-05-24 11:56
> > @alexandrebodin After porforming some investigation and trying to find temporary work around solution now I can tell you the reason of this issue. Moreover I can tell for sure that it does not matter what DB you use: MongoDB, PostgreSQl or other.
> > As far as this issue arised for our production users this was very blocking for us. Firstly, we decide to change DB from `mongo` to `Postgres`. Secondly, we decided to made our own load testing of `strapi` system with the new DB. So we put 20000 records for our collection, (yes, 20000, and yes - we expect to work with such a huge amounts of records in the future and even more). We also put a few images to Media Library, just 4 items, because we use them very actively in our `strapi` data collection. Each item of those 20000 was connected to 1 specific image from Media Library. So in the end we had 20000 items and 4 images, and every image is linked to ~5000 items.
> > When we opend Media Library page from the `strapi` admin panel we saw the same situation: images were fetching too long. Not so long as with the `mongo`, but on our testing system (which is in the cloud) it was ~10 second. And this delay was caused by the same request: `GET /upload/files?_limit=10&_start=0&_sort=updatedAt:DESC`.
> > Querying this request with `Postman` gives us the first understanding of the root cause. The resulted response contains ALL linked collection items for EVERY image presented in the response. In our case it was array of 4 media objects (images) and every media object contains ~5000 linked collection items. All this data is present under `related` field in the madia object. The response json was about 9.5 MB (!!!) of size flushed and contained more than 300000 lines disappointed. Even `Postman` feels bad displaying that response to us persevere
> > Going through the source code of a `strapi-plugin-upload` proved our consideration. in the `File.settings.json` model definition there is a field `related`:
> > ```
> > "related": {
> >     "collection": "*",
> >         "filter": "field",
> >         "configurable": false
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thi is that same `related` field which we saw in the response cntained those huge amounts of data. And this is the field causing the slowdown for the whole Media Library.
> > P.S. To me it makes no sense to get all related items from all collections for media objects. Is it really necessary and what the purpose of it?
> 
> Have you tried extending the file model and adding `autoPopulate: false` ? Not sure this will work in this direction of the relation though but if not making a PR to allow this should be fairly easy

`autoPopulate: false` option for file model did the job. Applying it removes `related` field from response. Will send a PR

**Comment by andriichern** [comment] 2021-05-24 12:47
@alexandrebodin I've added a PR for this fix

**Comment by derrickmehaffy** [comment] 2021-05-24 18:44
That is breaking changes, it's unlikely we would merge that by default in the v3 as we already plan to disable all population in the v4. For now this would likely need to remain on the user's side to implement as you have done but I'll let @alexandrebodin confirm.

**Closed** 2021-06-02 14:07 UTC
Labels: severity: medium, source: plugin:upload, status: confirmed, type: bug
