### ISSUE TITLE
Yarn setup run into problem with window

### ISSUE THREAD

**Issue by PhuQuy** [strapi/strapi#14543] opened 2022-10-05 04:01 UTC
### Required System information

- Node.js version: **v16.15.0**
- NPM version: 8.5.5
- Strapi version: 4.4.1
- Database:
- Operating system: Window 10

### Describe the bug

Build admin has some errors.
### Steps to reproduce the behavior

1. Pull strapi git
2. cd strapi
3. yarn setup
4. See error: [@strapi/admin  ] Error: Module parse failed: Unexpected token (10:25)
[@strapi/admin  ] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[@strapi/admin  ] | import Layout from '@strapi/icons/Layout';
[@strapi/admin  ] |
[@strapi/admin  ] > const PluginIcon = () => <Layout />;
[@strapi/admin  ] |
[@strapi/admin  ] | export default PluginIcon;
[@strapi/admin  ]     at E:\Demo\strapi\strapi\packages\core\admin\scripts\build.js:80:11
[@strapi/admin  ]     at finalCallback (E:\Demo\strapi\strapi\node_modules\webpack\lib\Compiler.js:441:32)
[@strapi/admin  ]     at E:\Demo\strapi\strapi\node_modules\webpack\lib\Compiler.js:458:13
[@strapi/admin  ]     at Hook.eval [as callAsync] (eval at create (E:\Demo\strapi\strapi\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:35:1)
[@strapi/admin  ]     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\Demo\strapi\strapi\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
[@strapi/admin  ]     at onCompiled (E:\Demo\strapi\strapi\node_modules\webpack\lib\Compiler.js:456:21)
[@strapi/admin  ]     at E:\Demo\strapi\strapi\node_modules\webpack\lib\Compiler.js:1196:17
[@strapi/admin  ]     at eval (eval at create (E:\Demo\strapi\strapi\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:14:1)
[@strapi/admin  ]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.strapi/admin  ]

### Expected behavior

Run yarn setup run successfully without any errors.

### Screenshots

![image](https://user-images.githubusercontent.com/17820409/193978785-e032b5b4-b9c7-48af-9c08-0f410abb7267.png)

**Comment by derrickmehaffy** [comment] 2022-10-07 19:26
Unable to reproduce on Mac, Linux, or Windows. Setup works fine. Need more steps to reproduce or more information about the users environment.

**Comment by derrickmehaffy** [comment] 2022-10-07 19:27
Marking as closed until we have updated information

**Closed by derrickmehaffy** 2022-10-07 19:27 UTC
Labels: status: can not reproduce

**Comment by BhuvaneshPatil** [comment] 2022-11-05 12:15
I am also running into the same issue.
@PhuQuy did you find any work around?

**Comment by PhuQuy** [comment] 2022-11-06 11:39
@BhuvaneshPatil change this one. I know they have bugs in window but somehow they just ignore me. 
![image](https://user-images.githubusercontent.com/17820409/200168344-45d7b472-6d31-46af-9028-900876e00562.png)
