### ISSUE TITLE
Updating Content Type name does not update the name in Roles & Permissions

### ISSUE THREAD

**Issue by virgil9306** [strapi/strapi#5090] opened 2020-01-25 07:33 UTC
**Describe the bug**
(Using DEV environment) Changed content type `collection name`, but `Roles & Permissions` section's `APPLICATION - Define all your project's allowed actions` shows old `collection name` even after restarting server

**Steps to reproduce the behavior**
1. `strapi dev`
2. Create a new Content Type (`Content Type A`)
3. Checked `Permissions` in `Create A New Role`, name shown as expected
4. Changed `collection name` of the `Content Type A`
5. Repeat Step 3 but name is not as expected; restarting server doesn't fix anything

**Expected behavior**
Expect step 3 above to show the collection name of `Content Type A` after changing

**Resolution/Steps Taken**

No resolution found. Steps taken are as follows:

* I deleted `Content Type A` and recreated one with the exact same name and `collection name`
* Run `strapi dev`.
* Error message: 

```
[2020-01-25T07:36:47.378Z] error Impossible to register the 'family-member' model.
[2020-01-25T07:36:47.378Z] error Error: SQLITE_ERROR: duplicate column name: parent
```

and Strapi will not start. (Removing from DB and `/api` folder fixed this, though I lost my work.)

Deletion + recreation does successfully show the new information in Roles & Permissions.

So maybe the cause of this bug is the Content Type is not getting thoroughly updated, or the Roles & Permissions is not seeing the updated data somehow.

**System**
- Node.js version: LTS
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.18.4 (node v12.11.1)
- Database: SQLite (default)
- Operating system: OS X latest

----

I checked issues for existing issue similar to this but could not find it.

**Comment by lauriejim** [comment] 2020-02-04 14:53
Hello! Can you precise the exact version of Strapi and the exact version of Node.js you are using please.

**Comment by lauriejim** [comment] 2020-02-04 14:58
Thank you for reporting this issue!

**Comment by virgil9306** [comment] 2020-02-05 08:25
Hi @lauriejim , I've updated the original post with this information! Thank you for looking into this.

**Comment by alexandrebodin** [comment] 2020-04-20 12:50
Hi, @virgil9306 when change the collectionName of a model it doesn't change its displayName. You will need to change the `info.name` field. To avoid any issues when you intentionnaly want to rename a contentType you will also have to rename it manually. 


I'm closing this issue as I think this is respecting the intended behavior. Let us know if this is not the case.

**Closed by alexandrebodin** 2020-04-20 12:50 UTC
Labels: priority: medium, source: plugin:users-permissions, status: confirmed, type: bug

**Comment by bilal42011** [comment] 2022-06-26 20:50
Issue Still not resolved please update the code !! Thanks in advance!
