### ISSUE TITLE
AWS S3 upload provider cause issue when relation field "relation"

### ISSUE THREAD

**Issue by iedmrc** [strapi/strapi#5189] opened 2020-02-05 14:07 UTC
**Describe the bug**
If you have 2 content-types which are related via the name of "domain", causes this exception:
```
[2020-02-05T13:55:22.399Z] error TypeError: domain.enter is not a function
    at Child.EventEmitter.emit (domain.js:459:10)
    at eventNames.forEach (/node_modules/bookshelf/lib/base/events.js:75:17)
    at Array.forEach (<anonymous>)
    at Child.trigger (/node_modules/bookshelf/lib/base/events.js:74:29)
    at Builder.builder.on (/node_modules/bookshelf/lib/bookshelf.js:544:47)
    at Builder.emit (events.js:182:13)
    at Builder.EventEmitter.emit (domain.js:442:20)
    at Runner.query (/node_modules/knex/lib/runner.js:132:18)
    at /node_modules/knex/lib/runner.js:39:23
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at /node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/node_modules/bluebird/js/release/promise.js:673:18)
    at PromiseArray._resolve (/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (/node_modules/bluebird/js/release/promise_array.js:145:14)
    at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/node_modules/bluebird/js/release/promise.js:729:18)
[2020-02-05T13:55:22.400Z] debug GET /content-manager/explorer/application::video.video/1 (9 ms) 500
```

I have `videos` and `domains` content-types that are connected with a "has many" relation. See the screenshots below.

**Steps to reproduce the behavior**
1. Create a content type named "video"
2. Create a content type named "domain"
3. Create such a "has many" relation:
Video Field name: domain
Domain Field name: videos
Domain  has many Videos
4. Go to Videos and try to add new record
5. See the error

**Expected behavior**
Create a relationship with a field named "domain".
It seems that is caused because of a dependency uses the deprecated [domain](https://nodejs.org/docs/latest-v10.x/api/domain.html) API of Node.js.

**Screenshots**
<img width="908" alt="Ekran Resmi 2020-02-05 16 58 00" src="https://user-images.githubusercontent.com/13666448/73848256-d361ec80-4838-11ea-8509-4503fca9db62.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 10.13.0
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.18.7 (node v10.13.0)
- Database: postgresql 12.1
- Operating system: macos catalina

**Additional context**

**Comment by lauriejim** [comment] 2020-02-05 15:45
Hello!
I just tried to reproduce your issue by following your steps and it works on my side (last version of strapi beta.18.7)
Here is what I did - https://www.loom.com/share/2ba856cfa07f4e4289402c3406f17d90
Can you tell me if I missed something?

**Comment by iedmrc** [comment] 2020-02-05 17:09
You did absolutely right. I also created a fresh project, followed steps and produced no error. I've updated my original strapi (i.e. the one made me create this issue) to beta.18.7 from beta.18.6 so it might be about that package upgrade.

**Comment by lauriejim** [comment] 2020-02-06 17:37
Hum strange, so I can close this issue.

**Comment by iedmrc** [comment] 2020-02-16 22:43
Okay, I found what causes the bug:

install s3 file upload provider via:

`yarn add strapi-provider-upload-aws-s3@beta`

And follow the steps in the issue to produce the error.  It seems that aws-s3 provider uses some legacy packages and that affects the whole strapi.

Could you please re-open after investigating?

Thanks!

**Comment by ugursogukpinar** [comment] 2020-02-17 10:35
@iedmrc  I've faced the same issue in other libs/projects and most of the time it happens if don't start the project with the same node version while installing the dependencies. Let's assume that you used node@8.x when you run `npm install/yarn`, then if you run `yarn start` with node@12.x (or vice versa) it cause `domain.enter` is not a function. I would suggest that remove the node_modules and be sure that you'r using the same node version. I'm not sure but it may related.

**Comment by iedmrc** [comment] 2020-02-17 10:48
Hi @ugursogukpinar thank you for the help.
I use nvm and here are the version details:
```
node -v                                        
v10.13.0
```

```
yarn versions
yarn versions v1.22.0
{ yarn:
   '1.22.0',
  http_parser:
   '2.8.0',
  node:
   '10.13.0',
  v8:
   '6.8.275.32-node.36',
  uv:
   '1.23.2',
  zlib:
   '1.2.11',
  ares:
   '1.14.0',
  modules:
   '64',
  nghttp2:
   '1.34.0',
  napi:
   '3',
  openssl:
   '1.1.0i',
  icu:
   '62.1',
  unicode:
   '11.0',
  cldr:
   '33.1',
  tz:
   '2018e' }
```

```
npm version                                    
{ npm: '6.4.1',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.13.0',
  openssl: '1.1.0i',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.36',
  zlib: '1.2.11' }
```

I also reinstalled node_modules again and again. But I'm suspecting the same thing as you. But I make sure that it's caused by the `strapi-provider-upload-aws-s3@beta` package.

**Comment by iedmrc** [comment] 2020-02-17 11:34
I've tried it in a dockerized environment with [node v10](https://github.com/nodejs/docker-node/blob/46f5203674c748b0701135c8eeea4b250b3ecb6d/10/stretch/Dockerfile) . Still, the issue persists.

**Comment by iedmrc** [comment] 2020-02-18 08:51
It's all about setting attribute name to "domain" when `strapi-provider-upload-aws-s3@beta` is installed. This seems like a bug that needs to be fixed but until then, here is a workaround for anyone needs:

video.settings.json file:
```
    "domains": {
      "model": "domain",
      "columnName": "domain",
      "via": "videos",
      "configurable": false
    },
```

domain.settings.json file:
```
    "videos": {
      "via": "domains",
      "collection": "video",
      "configurable": false
    }
```

In other words, set the attribute name to other than "domain" (here I set to "domains") and if  you want to keep column name as "domain" (on db) then set `columnName` to `domain`.

**Comment by derrickmehaffy** [comment] 2020-02-18 10:58
Reopening as more work is being done to find the root cause.

**Comment by lauriejim** [comment] 2020-06-09 12:40
Looks fixed in the stable version of Strapi.
Just tried and it works well.

**Closed by lauriejim** 2020-06-09 12:40 UTC
Labels: priority: low, source: plugin:upload, status: confirmed, type: bug
