### ISSUE TITLE
Add component above/below dropdown container height

### ISSUE THREAD

**Issue by IlirEdis** [strapi/strapi#17061] opened 2023-06-22 09:59 UTC
First, thanks for adding this feature! I had a long time waiting for this and didn't have time to ask for it on you feature requests. In fact the ability copy and paste a component would be even better :)
However i noticed this glitch when you have more items in the dropdown:

<img width="485" alt="Screenshot 2023-06-22 at 11 51 45" src="https://github.com/strapi/strapi/assets/128377763/5d89530d-9068-46e6-926e-2aa82a5813c2">

Hope you fix this in the next release.

**Comment by gu-stav** [comment] 2023-06-22 09:59
Closing as duplicate of https://github.com/strapi/design-system/issues/1142

**Closed by gu-stav** 2023-06-22 09:59 UTC
