### ISSUE TITLE
Bundles cannot be loaded if strapi runs behind a proxy

### ISSUE THREAD

**Issue by Tjerk-Haaye-Henricus** [strapi/strapi#5630] opened 2020-03-27 19:58 UTC
Hey guys

first of all... thanks for providing such a great product.

If one is running strapi behind an nginx proxy and the path of the admin panel changes, the bundles cannot be loaded.

I have a nginx proxy, and my strapi instance runs on path https://localhost/service/content
so the admin url should be https://localhost/service/content/admin

After hours of configuration, i cann request the admin panel, but if i open it in a browser, it cannot fetch the bundles because the bundle url is still https://localhost/admin. I searched a lot without victory. It seems to be that there is no way to change the path of the bundles. So proxiing isnt possible.

Using strapi version: 3.0.0-beta.19.3

Here's the server.json configuration:

`{
  "host": "${process.env.HOST}",
  "port": "${process.env.PORT}",
  "proxy": {
    "enabled": true,
    "ssl": true,
    "host": "localhost/service/content",
    "port": 443
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false,
    "build": {
      "host": "https://localhost/service/content/admin",
      "backend": "https://localhost/service/content/admin"
    }
  }
}
`
![image](https://user-images.githubusercontent.com/44015586/77795374-ba71fc80-706d-11ea-99b5-9747cc1e4922.png)

**Comment by christianguevara** [comment] 2020-03-27 20:01
That's because strapi doesn't know/care about the proxy.

@derrickmehaffy suggestion is:

"For now, my suggestion is throw Strapi on a subdomain and throw in a 301 redirect from main site"

**Comment by fedebabrauskas** [comment] 2020-03-27 23:15
Same problem here.
I can't host my admin panel without a subdomain, hope support for this will be added soon.

**Comment by derrickmehaffy** [comment] 2020-03-28 08:38
Closing as duplicate of https://github.com/strapi/strapi/issues/3507

**Closed by derrickmehaffy** 2020-03-28 08:38 UTC
