### ISSUE TITLE
The role titles on the user edit page are not displaying correctly in 4.12.5

### ISSUE THREAD

**Issue by smoothdvd** [strapi/strapi#17682] opened 2023-08-16 14:40 UTC
### Required System information

- Node.js version: 18.17.1
- NPM version: 9.6.7
- Strapi version: 4.12.5
- Database: PostgreSQL 15.x
- Operating system: macOS 13.5
- Is your project Javascript or Typescript: Typescript

### Describe the bug

The role titles on the user edit page are not displaying correctly. The role titles have been incorrectly replaced by role IDs.

### Steps to reproduce the behavior

1. Go to 'Content Manager'
2. Click on 'User' in Collection Types
3. Click on 'Create new entry'
4. Click on role's drop menu  arrow
5. See error

### Expected behavior

Show role's title

### Screenshots

<img width="673" alt="Screenshot 2023-08-16 at 10 39 31 PM" src="https://github.com/strapi/strapi/assets/22420/d4f7ab7e-cb3b-424c-8de7-058e34e65324">

**Comment by gu-stav** [comment] 2023-08-16 14:45
Closing as duplicate of https://github.com/strapi/strapi/issues/17561

**Closed by gu-stav** 2023-08-16 14:45 UTC
