### ISSUE TITLE
Impossible to create new entries (Content Manager, v4)

### ISSUE THREAD

**Issue by eriskhan** [strapi/strapi#10673] opened 2021-07-31 22:44 UTC
### Describe the bug

Most times it's impossible to create any entries in content manager. Frontend hangs completely while backend says it's 200 OK. According to the browser' console there's some error with processing responses: 

content-manager.e484941e.chunk.js:1 Uncaught (in promise) TypeError: Cannot read property 'payload' of undefined
    at content-manager.e484941e.chunk.js:1
    at content-manager.e484941e.chunk.js:1
    at f (main.7a3a19ec.js:2)
    at Generator._invoke (main.7a3a19ec.js:2)
    at Generator.throw (main.7a3a19ec.js:2)
    at t (main.7a3a19ec.js:2)
    at c (main.7a3a19ec.js:2)

### Steps to reproduce the behavior

1. Create a getstarted project
2. Click on any content type -> create new entry
3. Type anything and save the entry

### Expected behavior

An entry saved without frontend hanging up.

### Screenshots

![image](https://user-images.githubusercontent.com/20924122/127754044-77550e88-ef1c-45e8-8951-ebf2859873fb.png)

### System

- Node.js version: v14
- Strapi version: v4.0.0-next.0

**Comment by derrickmehaffy** [comment] 2021-08-02 20:36
Can you please test on 4.0.0-next.2 as I couldn't reproduce it

**Comment by eriskhan** [comment] 2021-08-03 00:36
Hey there @derrickmehaffy! I'll try to reproduce it tomorrow on the next version

**Comment by derrickmehaffy** [comment] 2021-08-03 13:59
(just as a heads up we expect quite a few bugs in the admin for the alpha since the new design system hasn't been integrated yet)

Alpha is more for validating the backend

**Comment by eriskhan** [comment] 2021-08-06 02:04
Hey there @derrickmehaffy! Sorry for being a little bit late with my feedback on .2 version. Closing the issue as I couldn't reproduce it on 4.0.0-next.2 either

**Comment by eriskhan** [comment] 2021-08-06 02:12
@derrickmehaffy I'm really sorry but it seems I've been too fast! The issue still exists with version 4.0.0-next.2. 
![image](https://user-images.githubusercontent.com/20924122/128445144-c59ce63f-47dd-4bd5-af30-d59efab1ef6d.png)
I suppose it'd be better to include my configuration. It's Windows 10, DB is SQLite. Node version 14.17.1, npm version 6.14.13. However it's obvious this happens much more rarely now than on 4.0.0-next.0 (about 75 to 80 percent requests, I'd say, would hang up Strapi - now it's 10 to 20 percent). I'm not sure this is an issue with strapi, however I can't reproduce this behaviour with v. 3.6.6 on exactly same machine.

**Comment by derrickmehaffy** [comment] 2021-08-06 20:18
I did bring this up with the engineering team in our internal weekly sync meeting. It's quite expected to hit some unusual bugs in the admin panel since it has almost none of the new code requirements.

We've only started integrating the backend and frontend together so the Alpha should only be used to test and validate the backend (basically query and internal API layers)

I will however keep this open until we get to the public beta later this month.

Thank you for reporting the issue and please feel free to report others too in separate issues.

**Comment by derrickmehaffy** [comment] 2021-09-30 12:43
Closing as couldn't reproduce in the beta

**Closed by derrickmehaffy** 2021-09-30 12:43 UTC
Labels: status: can't reproduce, flag: v4-Alpha/Beta
