### ISSUE TITLE
publicationState is not `live` by default in Graphql

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#8337] opened 2020-10-14 18:16 UTC
**Describe the bug**
The docs: https://strapi.io/documentation/v3.x/plugins/graphql.html#query-api tells us
```
publicationState (PublicationState): Only select entries matching the publication state provided.

Handled states are:

live: Return only published entries (default)
preview: Return both draft entries & published entries
```

but querying in graphql without a publicationState definitely give me everything, including drafts. I have to set `pages(publicationState:LIVE) {}` to remove drafts from the results. This is different to what the docs say. 

**Steps to reproduce the behavior**

1. create a model with `draftAndPublish: true`
2. query that model in graphql without filters
3. see you are also getting draft pages

**Expected behavior**
I'd expect only `live` pages when not providing the `publicationState`

**Screenshots**
<img width="800" alt="Schermafbeelding 2020-10-14 om 20 14 43" src="https://user-images.githubusercontent.com/6753724/96028833-207f6f00-0e5a-11eb-8e65-47560360823b.png">

**System**

- Node.js version: 12.18
- NPM version:6
- Strapi version: 3.2.3
- Database: mongo
- Operating system: macos

**Comment by derrickmehaffy** [comment] 2020-10-14 21:31
@laurenskling is this on a new project? I wasn't able to reproduce this on the current version.

**Comment by laurenskling** [comment] 2020-10-15 06:51
Yeah this project started before 3.2.0, i've added `draftAndPublish: true` to the model options

**Comment by Convly** [comment] 2020-10-15 09:39
Hello :wave: 

Here are the steps I've done to reproduce your issue:
- Created a project in `3.1.7`
- Added a simple content-type with a field `name: string`
- Created 5 entry
- Migrated to `3.2.3`
- Added `draftAndPublish: true` to the model's options
- Unpublished one of the entries

I've done these steps in **sqlite**, **mongo** and **postgres** with node `12.18.4`, and everything was working as expected.

![image](https://user-images.githubusercontent.com/25851739/96105945-e7d3aa00-0eda-11eb-94a7-9a188874a61c.png)
![image](https://user-images.githubusercontent.com/25851739/96105984-f3bf6c00-0eda-11eb-9d4f-ee04950ef90a.png)
![image](https://user-images.githubusercontent.com/25851739/96106033-fe7a0100-0eda-11eb-90be-696c17683d2e.png)

Could you provide an example project with the issue?

**Comment by laurenskling** [comment] 2020-10-15 09:56
Thanks for the deep research.

I will try to make a reproduce a.s.a.p.

one step that was different in my case that the one that shows up in the screenshot is not a unpublish, but is a new entry that hasn't been published yet. No idea if that is relevant, but different from your steps.

**Comment by Convly** [comment] 2020-10-15 11:59
An unpublished or a new entry shares the same properties since they're both drafts, so it shouldn't impact the results. (I've tried with a new entry, though, and it works well too).

I'll wait for your config/replica.

**Comment by laurenskling** [comment] 2020-10-24 09:58
I found the reason why this is happening in my model.

I'm running this model from a plugin, which means i create controller functions myself. in `controllers/pages.js` I have:

```
const model = 'plugins::pages.pages';

module.exports = {
  find: async ctx => {
    return strapi.entityService.find({
      params: ctx.query,
    }, { model });
  },
  findOne: async ctx => {
    return strapi.entityService.findOne({
      params: ctx.query,
    }, { model });
  },
};
```

But that is missing https://github.com/strapi/strapi/blob/b2b4515d9bf51060e6ae34ec9fef5099af19da62/packages/strapi/lib/core-api/service.js#L12 from the core-api. So in my self-built query, publicationState is never set to a default.

So this is not a bug. 

But I'd like to note that not running `core-api` code on models from plugins is increasing little problems like this. having models in plugin is what got my into Strapi. I am able to write models shared and maintained between project very easily. it's super powerful to me. I surely hope plugin don't get forgotten in new features, like Components are already :(

**Comment by derrickmehaffy** [comment] 2021-04-15 18:09
Closing as confirmed not a bug

**Closed by derrickmehaffy** 2021-04-15 18:09 UTC
Labels: status: can't reproduce
