### ISSUE TITLE
Auto-populate option for Components & Dynamic Zones

### ISSUE THREAD

**Issue by Mcastres** [strapi/strapi#11852] opened 2021-12-08 15:09 UTC
### Please describe your feature request

Having the option to auto-populate or not Components and Dynamic Zones in API responses from the Content-Types Builder.

![Capture d’écran 2021-12-08 à 15 25 01](https://user-images.githubusercontent.com/17828745/145229943-1e281881-1e22-467d-9c8f-cb27d99df7d4.png)

- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

### Summary

`Components` and `Dynamic Zones` (and media also) are not populated by default on v4. Why not have the option to auto-populate them?

### Why is it needed?

You might always need these fields to be returned in your API response for some Content-Types while not having to populate them manually using `populate` every time you create some new ones.

ex: `Page` Content-Type. I will always need to have my components and DZ components (`Auto-populate: true`)
ex: `Restaurant` Content-Types. I will not always need my dynamic zones components  (`Auto-populate: false`)

This can also prevent users to create big queries containing dozens of `populate` params if your Dynamic Zone contains dozens of components.

### Suggested solution(s)

Implement a checkbox for auto-populating or not their `Components`, `Dynamic Zones` (`Media fields?`)

**Comment by derrickmehaffy** [comment] 2021-12-08 15:20
Instead of a boolean on the DZ, I would suggest a file to specify the default full population if a `population` param isn't sent in the REST or GraphQL request. This would give a lot more control over the population in a standardized way.

Something like `./src/api/*/content-types/*/populate.js` with a simple structure like:

```js
module.exports = {
  populate: {
    metaDZ: {
      populate: {
        metaImage: {
          populate: {
            image: {
              fields: ['name', 'url']
            }
          }
        },
        relatedArticles: {
          fields: ['title', 'slug'],
        }
      }
    }
  }
}
```

**Comment by tomnovotny7** [comment] 2021-12-08 20:15
Something like this will be great. We are using this solution, for now, https://github.com/strapi/strapi/issues/11836#issuecomment-989131330 You can specify the depth, but not choose what to populate. This helper function can be modified to use autoPopulate parameter.

**Comment by gu-stav** [comment] 2021-12-09 09:26
3 thoughts on this, since it seems to cause a lot of confusion. To me idea 2 seems to be the most interesting one, but I haven't used the REST API from v4 yet, so it's pure theory :D

### 1. Reverse the behavoir

Population seems to cause a lot of confusion for people using strapi. Since it's mainly a performance optimization, but you want the REST API to be as easy as possible, why not reverse the behavoir?

- no `populate` query param: means `populate=*`
- in a `populate` query param is set, then only include the things requested

This way advanced users, who need to take performance into consideration, have the ability, but at the same time the things you need to know as a starter about the api is minimal.


### 2. @derrickmehaffy to build on top of your idea
I think it would sense to make this a programmable api, which can respond to the query. So maybe it's something like:

```js
module.exports = {
  populate(ctx) {
     return { /* your proposal */ }
  }
}
```

This would even allow to implement my proposal 1) on the user side of things. As far as I understand this is specific to the REST API, right? So this should somehow reflect that in the file structure, to make it clear that GraphQL users don't have to do this. Also the query engine wouldn't take this into account by default I guess, since this needs to be as flexible as possible?


### 3. Make this a flag on the schema JSON
A field/ zone whatever could define whether it should populate by default (basically the idea @Mcastres had)

**Comment by tomnovotny7** [comment] 2021-12-09 13:33
1. I do not think this is the way, populate=* is not sufficient, it does only first level. We need something like v3 behavior.
2. This would be nice if such a file would be used by core services. But for dynamic zones or nested relations, this could be hard to maintain. I would really appreciate having a generator for this. We have dozens of components in a dynamic zone and recursive relations. Handling changes in such a structure could be tedious when the population object for dynamic zones is the merge of population objects of components (some attributes may overlap).
3. This is suggesting Strapi v3 like behavior, I think this approach could be made a default population with some depth to avoid recursion.

**Comment by derrickmehaffy** [comment] 2021-12-10 03:23
## Just going to clarify immediately since it was confirmed by the engineering team, we will not revert to v3 behavior as that would be a breaking change

We can only add additional features that aren't breaking changes. I believe we already plan to add more wildcards regardless of other features being discussed here (eg `**` and `*.*`)

**Comment by WardenCommander** [comment] 2021-12-20 19:09
Hello all is there possibly to populate relation/ component/dynamic zone i lifecycles hook?

Example:
before Update (data)
"data" only shows data in collection type and not in relation/ component/dynamic zone.

**Comment by derrickmehaffy** [comment] 2021-12-20 20:39
> Hello all is there possibly to populate relation/ component/dynamic zone i lifecycles hook?
> 
> Example: before Update (data) "data" only shows data in collection type and not in relation/ component/dynamic zone.

No, it is not possible to populate the data passed into the lifecycle. Specifically that beforeUpdate data payload is what should be coming from the user who sent it.

**Comment by WardenCommander** [comment] 2021-12-20 21:40
> > Hello all is there possibly to populate relation/ component/dynamic zone i lifecycles hook?
> > Example: before Update (data) "data" only shows data in collection type and not in relation/ component/dynamic zone.
> 
> No, it is not possible to populate the data passed into the lifecycle. Specifically that beforeUpdate data payload is what should be coming from the user who sent it.

Hello @derrickmehaffy, thank you for reply. How would I be able to run function on collection type and its components every time collection type is updated?

If i would use lifecycle and call a function that in return updates that same collection type it would trigger Lifecycle again and create infinite loop.

**Comment by derrickmehaffy** [comment] 2021-12-20 21:42
> > > Hello all is there possibly to populate relation/ component/dynamic zone i lifecycles hook?
> > > Example: before Update (data) "data" only shows data in collection type and not in relation/ component/dynamic zone.
> > 
> > 
> > No, it is not possible to populate the data passed into the lifecycle. Specifically that beforeUpdate data payload is what should be coming from the user who sent it.
> 
> Hello @derrickmehaffy, thank you for reply. How would I be able to run function on collection type and its components every time collection type is updated?
> 
> If i would use lifecycle and call a function that in return updates that same collection type it would trigger Lifecycle again and create infinite loop.

This is not the place to talk about this type of question, please move the discussion on this to either our Discord or Forum.

**Comment by projectnoontide** [comment] 2022-01-02 04:55
I've tried many variations to achieve the following in a simple construct, to no avail:
?populate=*&populate[DZ]=*

If I try to open up a dynamic zone (i.e., populate[content][populate]=*), then all other auto-populate objects must be looped through and added individually to the query.

Is there currently any way to accomplish this simply?  Developers really need to have full parameter control to open up the depths of their data models in both a granular way, as well as setting defaults for all data types.  Let the developers be responsible for caching responses to complex queries and greater optimization.

**Comment by derrickmehaffy** [comment] 2022-01-03 11:30
> I've tried many variations to achieve the following in a simple construct, to no avail: ?populate=_&populate[DZ]=_
> 
> If I try to open up a dynamic zone (i.e., populate[content][populate]=*), then all other auto-populate objects must be looped through and added individually to the query.
> 
> Is there currently any way to accomplish this simply? Developers really need to have full parameter control to open up the depths of their data models in both a granular way, as well as setting defaults for all data types. Let the developers be responsible for caching responses to complex queries and greater optimization if they choose to open things up.
> 
> I'm tempted to restructure my data models so that everything is contained within a single dynamic zone, then just use populate[dynamiczone][populate]=*. This would change the way objects are organized for data entry, though. But I shouldn't need to do so in order to simplify my query logic.

Not currently but we are planning to add additional glob wildcards

**Comment by Erns** [comment] 2022-01-12 03:52
> Something like this will be great. We are using this solution, for now, [#11836 (comment)](https://github.com/strapi/strapi/issues/11836#issuecomment-989131330) You can specify the depth, but not choose what to populate. This helper function can be modified to use autoPopulate parameter.

This solution by @tomnovotny7 I found to be a great solution for my needs as it addresses the need for an easier nested populate as well as Strapi v4's use of the json:api format with the data.attributes way of things.  I think an "either or" sort of approach available by the Strapi API would be really beneficial.

**Comment by derrickmehaffy** [comment] 2022-03-24 22:12
We won't auto-populate but we will add additional population glob options to make population easier. Marking as closed

**Closed by derrickmehaffy** 2022-03-24 22:12 UTC
Labels: issue: feature request

**Comment by rrubio** [comment] 2022-04-13 22:42
Hi Guys, 

Hoping for some guidance. Using Strapi V4 and struggling to get images to populate under dynamic zones. 

I've detailed code, schema and response on [stackoverflow](https://stackoverflow.com/questions/71845372/strapi-v4-populate-dynamic-zones-media-not-populating), any assistance would be much appreciated.

**Comment by axufurisamu** [comment] 2022-04-25 19:34
I really wish they did not change how the API's worked before making sure we could mimic what the API's did before.  To me, the change to V4 is actually breaking!  I haven't been able to get my subobjects to populate properly in V4 and it is really frustrating that the most basic things you need from a CMS API were not thought out before changing it.

**Comment by derrickmehaffy** [comment] 2022-05-23 23:31
> I really wish they did not change how the API's worked before making sure we could mimic what the API's did before. To me, the change to V4 is actually breaking! I haven't been able to get my subobjects to populate properly in V4 and it is really frustrating that the most basic things you need from a CMS API were not thought out before changing it.

It is a breaking change, hence why we added in Strapi v4. I'd suggest posting our in our community spaces to get some help with population as once you get the hang of it, it's actually quite powerful.
