### ISSUE TITLE
Component identifier name is too long (ER_TOO_LONG_IDENT) - fails to start

### ISSUE THREAD

**Issue by luboslives** [strapi/strapi#17376] opened 2023-07-19 12:45 UTC
### Required System information

- Node.js version: 18.14.0
- NPM version: 9.4.1
- Yarn version: 3.6.1
- Strapi version: 4.11.5
- Database: MariaDB
- Operating system: MacOS Mojave 10.14.6
- Is your project Javascript or Typescript: JS

### Describe the bug

I was creating a custom component with a repeatable custom component inside of it. It's meant to hold the prize money given out to the top X finishers in a league. The user would add how many top finishers would be getting payouts, and specify the payout for each position.

I set up my simple structure and hit Save, the server restart process began, and then Strapi crashed with the following error message.

I attempted to start a new instance with `yarn develop` and the same errors print out, and the server does not start.

First time Strapi user here, so I need guidance on how to get this thing to run again. Maybe a simple bump to my SQL settings to increase the character limit? Maybe clear the yarn cache? Thanks.

### Steps to reproduce the behavior

1. Create a custom component named `payout-per-position` and give it a component type of `post-something` (I can't recall).
2. Create a custom component named `league-payout-structures` whose only field is the previously created custom component, and allow multiples, and select the same component type.
3. Save your changes to reboot the Strapi instance.

### Error Log

```
[2023-07-19 14:10:08.040] http: HEAD /_health (20 ms) 204
[2023-07-19 14:10:08.202] http: GET /admin/users/me/permissions (113 ms) 200
[2023-07-19 14:10:08.332] http: GET /content-type-builder/content-types (61 ms) 200
[2023-07-19 14:10:08.361] http: GET /content-type-builder/reserved-names (81 ms) 200
[2023-07-19 14:10:08.387] http: GET /content-type-builder/components (124 ms) 200
[2023-07-19 14:11:28.591] http: POST /content-type-builder/components (129 ms) 201
The server is restarting

Error: ER_TOO_LONG_IDENT: Identifier name 'components_post_data_league_payout_structures_component_type_index' is too long
    at Sequence._packetToError (/<project_dir>/.yarn/cache/mysql-npm-2.18.1-8fdb56201f-430dec8525.zip/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/<project_dir>/.yarn/cache/mysql-npm-2.18.1-8fdb56201f-430dec8525.zip/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/<project_dir>/.yarn/cache/mysql-npm-2.18.1-8fdb56201f-430dec8525.zip/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/<project_dir>/.yarn/cache/mysql-npm-2.18.1-8fdb56201f-430dec8525.zip/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/<project_dir>/.yarn/cache/mysql-npm-2.18.1-8fdb56201f-430dec8525.zip/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/<project_dir>/.yarn/cache/mysql-npm-2.18.1-8fdb56201f-430dec8525.zip/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/<project_dir>/.yarn/cache/mysql-npm-2.18.1-8fdb56201f-430dec8525.zip/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/<project_dir>/.yarn/cache/mysql-npm-2.18.1-8fdb56201f-430dec8525.zip/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Protocol._enqueue (/<project_dir>/.yarn/cache/mysql-npm-2.18.1-8fdb56201f-430dec8525.zip/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/<project_dir>/.yarn/cache/mysql-npm-2.18.1-8fdb56201f-430dec8525.zip/node_modules/mysql/lib/Connection.js:198:25)
    at /<project_dir>/.yarn/__virtual__/knex-virtual-f0ca1744b1/0/cache/knex-npm-2.4.0-6d3bc4efdd-66b4ae8412.zip/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/<project_dir>/.yarn/__virtual__/knex-virtual-f0ca1744b1/0/cache/knex-npm-2.4.0-6d3bc4efdd-66b4ae8412.zip/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/<project_dir>/.yarn/__virtual__/knex-virtual-f0ca1744b1/0/cache/knex-npm-2.4.0-6d3bc4efdd-66b4ae8412.zip/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/<project_dir>/.yarn/__virtual__/knex-virtual-f0ca1744b1/0/cache/knex-npm-2.4.0-6d3bc4efdd-66b4ae8412.zip/node_modules/knex/lib/client.js:146:12)
    at /<project_dir>/.yarn/__virtual__/knex-virtual-f0ca1744b1/0/cache/knex-npm-2.4.0-6d3bc4efdd-66b4ae8412.zip/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at trxClient.query (/<project_dir>/.yarn/__virtual__/knex-virtual-f0ca1744b1/0/cache/knex-npm-2.4.0-6d3bc4efdd-66b4ae8412.zip/node_modules/knex/lib/execution/transaction.js:358:12) {
  code: 'ER_TOO_LONG_IDENT',
  errno: 1059,
  sqlMessage: "Identifier name 'components_post_data_league_payout_structures_component_type_index' is too long",
  sqlState: '42000',
  index: 0,
  sql: 'alter table `components_post_data_league_payout_structures_components` add index `components_post_data_league_payout_structures_component_type_index`(`component_type`)'
}
```

**Comment by Boegie19** [comment] 2023-07-19 12:47
duplicate of https://github.com/strapi/strapi/issues/13117

**Closed by Boegie19** 2023-07-19 12:47 UTC

**Comment by luboslives** [comment] 2023-07-19 13:20
To follow up, if anyone finds themselves in the same position - as long as these are new components and you haven't created any content with them yet, the fix is trivial. Explained by https://github.com/strapi/strapi/issues/13117#issuecomment-1272505364

Navigate to `src/components/` and rename the collection names inside the .json files (and the files, for the sake of matching).  If one component is using another, make sure to update that reference inside the .json file.

You will want `components_` + `collection_name_` + `your_component_name_` + `component_type_index` to be shorter than 64 characters.
