### ISSUE TITLE
App breaks when a Content Type is renamed

### ISSUE THREAD

**Issue by fedecarg** [strapi/strapi#1584] opened 2018-07-17 11:00 UTC
Informations

Node.js version: v10.1.0
npm version: 5.6.0
Strapi version: 3.0.0-alpha.12.6
Database: MongoDB
Operating system: Linux

**What is the current behavior?**

If a Content Type that has a relationship is renamed, MongoDB complains about `globalId` not being defined and the app breaks. 

**Steps to reproduce the problem**

* Create 2 Content Types with a one-to-one relationship. 
* Add some data using the Content Manager plugin. 
* Rename one of the Content types. 

**What is the expected behavior?**

The app should not return a 503.

**Suggested solutions**

None.

**Comment by derrickmehaffy** [comment] 2018-07-19 07:40
@fedecarg you need to also rename it in the other model, as the other one will still attempt to reference the old name.

**Comment by fedecarg** [comment] 2018-07-19 07:52
@derrickmehaffy Makes sense. Shouldn't Strapi do that for the user?

**Comment by kamalbennani** [comment] 2018-07-19 07:56
Normally it should be handled by strapi

**Comment by lauriejim** [comment] 2018-08-01 15:19
Hello @fedecarg I'm not able to reproduce.
Can you be more precise on steps to reproduce.

What I did:

1. Create a content type `customer` (name:string)
2. Create a content type `payment` (name:string, customer:one-to-one:customer)
3. Create a customer via the content manager (name:customer1, without relation)
4. Create a payment via the content manager (name:payment1, with relation to customer1)
5. Update `payment` content type name by `candy`

And all works fin after that.

**Comment by fedecarg** [comment] 2018-08-16 12:11
This is still happening to us. Vey annoying bug because the node server dies after this and we can't change anything else.

**Comment by derrickmehaffy** [comment] 2018-08-16 12:15
@fedecarg are you using any special case for either the model or the field? (Spaces, symbols, camelCase, ect) ?

**Comment by derrickmehaffy** [comment] 2018-08-16 12:16
Also you can just update the names via the model settings file `api/modelname/models/modelname.settings.json`

It should be noted that Strapi doesn't rename the fields in or models stored in the DB, so by renaming you will "lose" that data (it is still there but no longer referenced properly)

**Comment by fedecarg** [comment] 2018-08-16 13:38
Nope. Restoring the files that were deleted using `git checkout -f master <files>` solved the problem.

**Comment by fedecarg** [comment] 2018-08-16 13:47
> It should be noted that Strapi doesn't rename the fields in or models stored in the DB, so by renaming you will "lose" that data (it is still there but no longer referenced properly)

Thanks Derrick.

Given that renaming a Content Type results in data not being updated (for obvious reasons), I wonder if allowing a user to `clone` instead of `rename` a Content Type would result in a better user experience.

Because when you `rename` a Content Type you don't expect to loose some data. But if you allow the user to `clone` it, then the user knows that it needs to update the relationships, and no data is lost in the process.

**Comment by derrickmehaffy** [comment] 2018-08-16 14:07
@fedecarg The Strapi team are aware of this issue, it has been brought up a few times. Eventually I think Strapi will have 2 options:

1. Delete the entire table (not sure what it is called in mongo) and lose all data and rebuild it
2. Dump/backup the data and do #1 (Obviously this is slower if being done on a large database.)

**Comment by lauriejim** [comment] 2018-08-20 13:52
@fedecarg an other issue exist about the data migration. I think we can close this issue.

**Closed** 2018-08-22 15:30 UTC
Labels: priority: medium, type: bug 🐛

**Comment by tonyberetini** [comment] 2018-09-05 21:08
Why is this issue close this should be a critical issue??

**Comment by derrickmehaffy** [comment] 2018-09-05 21:31
@tonyberetini because it is a duplicate problem dealing with data migration.

**Comment by tonyberetini** [comment] 2018-09-05 21:53
@derrickmehaffy which one is it I can't find it...

**Comment by derrickmehaffy** [comment] 2018-09-05 21:56
https://github.com/strapi/strapi/issues/1114

Read discussion between me and @Aurelsicoko

**Comment by jangroeneveld** [comment] 2018-11-21 10:15
I just ran into this issue myself, after looking around a bit, there was one model variable which did not update in the settings of another endpoint.

The relationship between those two was a "has one" relationship.

I fixed this by changing the model to the new name, and it looks like it's running smoothly now.

You could try a search for `"model": "<old name>"` in your IDE, and replace the old name with the new name.
