### ISSUE TITLE
Full text search return nothing in MySQL

### ISSUE THREAD

**Issue by 1um** [strapi/strapi#4813] opened 2019-12-24 00:14 UTC
**Describe the bug**
MySQL by spec doesn't support wildcard prepend on `... MATCH ... AGAINST`. 
([Spec](https://dev.mysql.com/doc/refman/8.0/en/fulltext-boolean.html), [StackOverflow](https://stackoverflow.com/questions/16720443/prepending-an-asterisk-to-a-fulltext-search-in-mysql))

Strapi prepends wildcard on every query:
https://github.com/strapi/strapi/blob/8d0c6848ba421680570e974e5d8606314735de3e/packages/strapi-connector-bookshelf/lib/queries.js#L768-L773

In some implementations it works, but in some (e.g. Amazon Aurora based on MySql 5.6.10a) it return empty results for any search.

**Steps to reproduce the behavior**
- Use aurora database on amazon
- Create entities 
- Search for entities in admin panel
- No results will be shown

**Expected behavior**
- Show relevant entities

**Code snippets**
```sql
#doesn't work:
select ... where MATCH(...) AGAINST('*a*' IN BOOLEAN MODE) limit 1
#works:
select ... where MATCH(...) AGAINST('a*' IN BOOLEAN MODE) limit 1
```

**System**
- Node.js version: v10.16.0
- NPM version:6.9.0
- Strapi version: 3.0.0-beta.18.3
- Database: Mysql Aurora (5.6.10a)
- Operating system: Ubuntu 18.04.2 LTS

**Comment by derrickmehaffy** [comment] 2019-12-24 04:59
I believe it should be usin `%` instead of `*` which is the proper SQL wildcard

**Comment by lauriejim** [comment] 2019-12-24 16:25
Ping @alexandrebodin for this type of topic

**Comment by alexandrebodin** [comment] 2019-12-24 17:01
@1um You are right. We should be appending the `*` only. IMO the query that should be generated should be without the * so a user can use the full power of the search engine. 

We are lacking time for this to be fixed right now but feel free to fix the prepended `*` first until we revisit the search as a whole.

@derrickmehaffy `%` is for the `LIKE` operator not the full text search ;)

**Comment by cadavre** [comment] 2020-02-20 14:20
# Same case for PostgreSQL

**Describe the bug**
`_q=2020` on entity with short text field like `Invoice 1235/65/2020` gives `[  ]` no results.

This problem is mainly hurting in admin panel UI.

**Steps to reproduce the behavior**
1. Create invoice entity, add simple text field called "invoice_no".
2. Create customer entity, add relation to invoice.
3. Add new invoice entity with `invoice_no="Invoice 1235/65/2020"`.
4. Try to add new customer with invoice, search for "2020" – you'll be given with no results.

Please don't care about domain logic in above example.

**Expected behavior**
Entity with "Invoice 1235/65/2020" is found.

**System**
- Node.js version: v12.13.0
- NPM version: 6.12.0
- Strapi version: 3.0.0-beta.18.7
- Database: postgres
- Operating system: Docker container on Ubuntu

**Additional context**
I tried playing with `strapi.utils.convertParams` putting default return type as:
```
        } else {
          type = '_contains';
        }
```
but this gives same results.

The problem is strictly with `strapi-connector-bookshelf` which uses `tsvector`s in `queries.js`. This does not produce results as one would except.

Shouldn't we explicitly define when we want to search in fulltext mode and when with just simple `LIKE %q%`?

**Comment by petersg83** [comment] 2020-04-16 09:17
@cadavre I think your issue is related to this one : https://github.com/strapi/strapi/issues/5573 which has been fixed

**Comment by petersg83** [comment] 2020-08-04 10:05
Hi,
The admin panel search is not using full text search anymore, it uses the LIKE syntax :)
I close the issue as it seems fixed. If you still experience some problems, don't hesitate to reopen it or open a new issue

**Closed by petersg83** 2020-08-04 10:05 UTC
Labels: priority: medium, source: core:database, status: confirmed, type: bug
