### ISSUE TITLE
Graphql calls `.find` for singleType in local plugins

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#7717] opened 2020-09-03 12:46 UTC
**Describe the bug**
The Graphql schema is looking for a `.find` function in my singleType, which isn't there ofcourse. Why isn't it looking for findOne?
It actually crashes the server until I add `find` to my controller.

**Steps to reproduce the behavior**
I guess just make `"kind": "singleType",` and install the graphql plugin. I am running my model from the `plugins` folder, tho. 

**Expected behavior**
a singleType running the `findOne` controller (created by strapi internals)

**System**

- Node.js version: 12.18
- NPM version: 6
- Strapi version: 3.1.4
- Database: mongo
- Operating system: macos

**Comment by derrickmehaffy** [comment] 2020-09-03 14:42
Currently in the process of trying to reproduce this issue.

**Comment by laurenskling** [comment] 2020-09-03 17:04
It might be running from local `plugins` has to do with it. It seems like the basic queries aren't created for my model in my plugin (also don't show up in Permissions), so graphql is not adding them to the schema either. But a singleType actually crashes the app.

**Comment by derrickmehaffy** [comment] 2020-09-03 17:35
Yeah I can't reproduce using it normally: 
![image](https://user-images.githubusercontent.com/8593673/92148302-39175680-edd1-11ea-990f-00e16af07053.png)

**Comment by laurenskling** [comment] 2020-09-03 17:42
![Schermafbeelding 2020-09-03 om 19 40 59](https://user-images.githubusercontent.com/6753724/92148887-7d304880-ee1d-11ea-8d92-476eb6a63e93.png)

This is the same config, but used in the local plugin called "pages"

**Comment by derrickmehaffy** [comment] 2020-09-03 18:28
@laurenskling are you trying to use single-types within a plugin?

**Comment by laurenskling** [comment] 2020-09-03 18:35
exactly. `./plugins/pages/models/homepage.settings.json`

**Comment by derrickmehaffy** [comment] 2020-09-03 18:37
@alexandrebodin to build on our previous combo about components, do we support single-types within a plugin?

**Comment by laurenskling** [comment] 2020-09-03 18:51
I'm curious about components as well, they seem to be not available from `plugins`, is that correct? That would be sad.

singleType do work tho; I just have to create my own find function in a controller. But I found out after I seem to need to do that in any case for models in plugins.. a singleType crashes, a collection just doesn't have controllers

**Comment by derrickmehaffy** [comment] 2020-09-03 18:53
@laurenskling I've marked it as a bug for now until I can get the backend team to confirm.

No it's not possible to use components within a plugin at this time, I'm not sure if we intended for single-types to work or not, but if it was then there is a certainly a bug.

**Comment by laurenskling** [comment] 2020-09-03 19:15
Thats very sad that I cannot use components in plugins. Would be really powerful if I could use these on my plugin models as well. Would be lovely if it would be possible one day.

Can you also confirm the default controller functions (find/findOne/count/create/update/delete) are not created automatically for models in a plugin?

**Comment by derrickmehaffy** [comment] 2020-09-03 19:20
@laurenskling they are yes, all models no matter where they are from should be pulled from the `core-api` (I believe but now I'm testing right now) however I am unsure of the `single-type`.

**Comment by derrickmehaffy** [comment] 2022-07-13 20:41
This should be fixed in v4 as GraphQL doesn't use the controllers anymore

**Closed by derrickmehaffy** 2022-07-13 20:41 UTC
Labels: issue: bug, status: confirmed
