### ISSUE TITLE
Not able to check plugin access in editor role of administrative panel.

### ISSUE THREAD

**Issue by spss20** [strapi/strapi#10415] opened 2021-05-31 21:56 UTC
### Screenshots

![image](https://user-images.githubusercontent.com/29224720/120244629-582e1080-c29d-11eb-934d-6019220f2ea3.png)

### Other information

Strapi version : 3.6.2
Node version : 14.x.x
Npm version: 6.x.x

**Comment by derrickmehaffy** [comment] 2021-06-02 20:45
@JabStrapi / @sam-pires / @Aurelsicoko

**Comment by soupette** [comment] 2021-06-07 07:20
I believe that this settings can be change only in the Entreprise edition, so it is an intended behaviour when running the Community Edition

**Comment by derrickmehaffy** [comment] 2022-03-25 18:36
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/feature-requests/p/lift-rbac-restrictions-for-community-users
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!

**Closed by derrickmehaffy** 2022-03-25 18:36 UTC
Labels: issue: feature request, source: core:admin
