### ISSUE TITLE
Digital Ocean One-Click Install Error Creating Admin

### ISSUE THREAD

**Issue by davidbwaters** [strapi/strapi#7134] opened 2020-07-23 11:48 UTC
The Digital Ocean one-click install snapshot is broken.  The droplet is giving a generic server error when I try to create an admin user and login. I've rebuild the Droplet and created a new one and get the same issue.  Using the 2gb $5/mo droplet. 

I create a droplet, gave it time to set up, click create admin, enter my info and clicking create doesn't give a response or redirect me.  After waiting a few minutes and accessing the setup URL, I am redirected to login but am given a 'server error' message when clicking submit.  The console isn't giving any output and the guide doesn't show any way to get a log of the error.

**Comment by derrickmehaffy** [comment] 2020-07-23 13:25
Closing as duplicate of: https://github.com/strapi/strapi/issues/7135

We will get a fix pushed out today (pending DO to approve the fix)

**Closed by derrickmehaffy** 2020-07-23 13:25 UTC
