### ISSUE TITLE
Slow response time on analytics.strapi.io

### ISSUE THREAD

**Issue by amaurer** [strapi/strapi#12704] opened 2022-03-01 20:17 UTC
### Describe the bug

I found that Strapi analytics were creating a significant amount of overhead to our login requests. 

### Steps to reproduce the behavior

Use the `/auth/local/` login. (user-permissions)

### Expected behavior

<=200ms response time. Even though this is from a 3.6.8 environment, v4 was released with many bugs so I had to hold off an upgrade. Hopefully you can address this as a critical item - performance

### Screenshots

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/561465/156242435-a09f9404-d2f8-49d5-87fe-ca42bde25c5d.png">

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/561465/156241393-485776d4-5307-4074-b442-e13cb204192d.png">

Removing the Strapi UUID, response time is reduced and no analytics.strapi.io call executed. 
<img width="1376" alt="image" src="https://user-images.githubusercontent.com/561465/156242220-20c3d6ba-7cb1-464e-bf0d-4b2548058243.png">
<img width="898" alt="image" src="https://user-images.githubusercontent.com/561465/156242277-036b1516-cc6c-43de-b0a0-64c4a6d6d950.png">

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14
- NPM version:
- Strapi version: 3.6.8
- Database: MySQL
- Operating system: CentOS + Strapi:14 Docker image

**Comment by derrickmehaffy** [comment] 2022-03-28 23:15
Can't reproduce on v4.1.5, marking as closed to see if we get updated information

**Closed by derrickmehaffy** 2022-03-28 23:15 UTC
Labels: severity: low, source: core:admin, status: pending reproduction
