### ISSUE TITLE
AWS Cognito redirect adding “https” twice in URL

### ISSUE THREAD

**Issue by khushvir** [strapi/strapi#17536] opened 2023-08-01 18:50 UTC
### Required System information

- Node.js version: 18.13.0
- NPM version: 8.15.0
- Strapi version: 4.12.0
- Database: SQLite
- Operating system: Windows 11
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I am using the below URL to log in to AWS Cognito.
http://localhost:1337/api/connect/cognito/

It’s redirecting me to my Cognito URL, but it’s adding “https” twice in the URL, e.g. "https://https//strapi.auth.ca-central-1.amazoncognito.com/oauth2/authorize?client_id=xxx"

### Expected behavior

It should redirect  to the AWS Cognito sign-in page without adding "https" twice.

### Screenshots

Redirect 
![aaa](https://github.com/strapi/strapi/assets/25701322/054c02ed-23f6-4573-9bb6-3fce0351f436)

Strapi Cognito config
![image](https://github.com/strapi/strapi/assets/25701322/956c4a50-18c3-4cfc-bd3e-93bffefa4e98)

### Code snippets

Server.js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('', 'http://localhost:1337/'),
  app: {
    keys: env.array('APP_KEYS'),
  },
  webhooks: {
    populateRelations: env.bool('WEBHOOKS_POPULATE_RELATIONS', false),
  },
});

### Additional context

After removing the second "https" manually from the URL, it works.

**Comment by Abhi1234-tech** [comment] 2023-08-24 06:38
@derrickmehaffy, I've implemented the requested changes in this pull request. Please provide an update on the status. I've also closed the previous pull request due to complications

**Comment by NmN03jain** [comment] 2023-10-02 21:23
can you pls suggest in which file i have to make changes ?

**Comment by Puneet-Amrutkar** [comment] 2023-10-03 18:01
can you please assign this issue to me

**Comment by ASCE-D** [comment] 2023-10-05 14:59
Hey @derrickmehaffy I would like to contribute to this issue, please assign me.

**Comment by derrickmehaffy** [comment] 2023-10-05 16:59
> Hey @derrickmehaffy I would like to contribute to this issue, please assign me.

Please go read https://github.com/strapi/strapi/issues/18298

**Comment by arg-adarsh** [comment] 2023-10-27 17:00
Hey @derrickmehaffy, I would like to contribute to this issue. Can i work on this issue too?

**Comment by Aditya8840** [comment] 2023-11-02 20:56
Hey @derrickmehaffy I would like to work of this issue, please assign me

**Comment by derrickmehaffy** [comment] 2023-11-02 21:30
> Hey @derrickmehaffy I would like to work of this issue, please assign me

We don't assign issues to non team members and we are in a community PR change freeze until March 2024

**Comment by sm0483** [comment] 2024-08-26 09:43
Hi, I’ve reproduced this issue. May I proceed with submitting a pull request containing my proposed fix?

**Closed as completed** 2024-10-03 13:03 UTC
Labels: issue: bug, severity: medium, good first issue, source: plugin:users-permissions, status: pending reproduction
