### ISSUE TITLE
Is it possible to replace WYSIWYG editor with another one, like CKEditor?

### ISSUE THREAD

**Issue by th0rv** [strapi/strapi#3865] opened 2019-08-29 14:02 UTC
Hey guys,

Have a requirement to replace default editor with something like CKEditor, checked issues here, like this one 
https://github.com/strapi/strapi/issues/2111#issuecomment-430573747
and I can't succeed with that approach... maybe you changed something from that time?

When I'm trying to follow the Steps to modify the front-end, like it was described here
https://github.com/strapi/strapi/issues/1943#issuecomment-430533710
I can't finish the second step because I don't have "admin" folder inside new "my-app". Could you please advise what could be the reason of the issue?

Thanks in advance and thank you for a good stuff!

**Comment by derrickmehaffy** [comment] 2019-08-29 14:09
@th0rv please see the following search as this question has been brought up a few times:
https://github.com/strapi/strapi/issues?q=is%3Aissue+CKEditor+is%3Aclosed

Also marking as closed as this is a duplicate of https://github.com/strapi/strapi/issues/2124

For now it is not something easy as the current status of plugin admin overrides (content-manager plugin) is not quite there and some feature development related to WYSIWYG editors along with a change in how strapi plans to store rich text is in progress.

In the short term your best bet would be to handle this on your frontend in some way, the long term may open this up but for now that is not the case.

**Closed by derrickmehaffy** 2019-08-29 14:09 UTC
