### ISSUE TITLE
WYSIWYG editor eats up any input that doesn't include latin characters or space

### ISSUE THREAD

**Issue by POPOEVER** [strapi/strapi#4287] opened 2019-10-18 14:45 UTC
**Describe the bug**
After making changes to the content in WYSIWYG editor and click Save button, the page redirects successfully, but the modifications are not actually saved to the database when there is no Latin characters or space included, for instance, when I add some Chinese characters and save, these Chinese characters are not saved.

**Steps to reproduce the behavior**
1. Open a text field which is setup using WYSIWYG editor
2. Input some non-Latin characters without inputting any space or tab.(here are some for your test purpose: 这些文字仅供测试)
3. Click "Save"
4. Revisit this text filed.

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: beta 16.8
- Database: SQLite
- Operating system: macOS Mojave 10.14.6

**Comment by veitbjarsch** [comment] 2019-10-19 14:11
@POPOEVER your should try the latest version of strapi. Only this version will supported: https://github.com/strapi/strapi/releases/tag/v3.0.0-beta.17.2

**Comment by POPOEVER** [comment] 2019-10-21 16:09
> @POPOEVER your should try the latest version of strapi. Only this version will supported: https://github.com/strapi/strapi/releases/tag/v3.0.0-beta.17.2

OK, let me try

**Comment by POPOEVER** [comment] 2019-10-21 17:54
I tried under 17.2, I'm afraid it hasn't been fixed, the problem still presents.

**Comment by lauriejim** [comment] 2019-10-24 13:43
Hello! I just created a new app and I added your `这些文字仅供测试` characters in a string and WYSIWYG input.
All works fine
![Screenshot 2019-10-24 at 3 42 52 PM](https://user-images.githubusercontent.com/5716596/67491287-f810ca80-f674-11e9-93f5-c32aba3261a0.png)

**Comment by loongmxbt** [comment] 2019-10-31 01:53
Same problem. Have to copy and paste strings including Chinese Characters each time.
Weird is, didn't come across this probelm in initial beta version.

**Comment by lauriejim** [comment] 2019-10-31 10:58
Can you tell me if I'm doing something wrong here? Looks working.

https://www.loom.com/share/df7bc66954d24bbca6af34a891316595

**Comment by loongmxbt** [comment] 2019-10-31 12:23
@lauriejim In my case, I update the beta version to the latest, at first the problem still exsits, may be cache? But today I cannot reproduce it again.

**Comment by derrickmehaffy** [comment] 2019-10-31 12:44
I'll go ahead and close the issue out @loongmxbt but yeah it was most likely cached from your lock file. Do let us know if the issue comes back up

**Closed by derrickmehaffy** 2019-10-31 12:44 UTC
Labels: type: help wanted 🤷‍♂️

**Comment by POPOEVER** [comment] 2019-11-01 08:10
> Can you tell me if I'm doing something wrong here? Looks working.
> 
> https://www.loom.com/share/df7bc66954d24bbca6af34a891316595

Because you entered line breaks, which are also detected as Latin characters I think.

**Comment by POPOEVER** [comment] 2019-11-01 08:50
> I'll go ahead and close the issue out @loongmxbt but yeah it was most likely cached from your lock file. Do let us know if the issue comes back up

No idea why this was closed, it's not fixed.

Of course I removed `/.cache`, `/build`, `/exports` and rebuild the admin dashboard after upgraded to 17.4, and also I cleaned up my browser cache as well, the issue persists.

The reproduction of the issue should be like inserting some Chinese characters then Save, just Chinese characters, no any other input like space, tab, symbols, line breaks, which are also Latin characters. 

This is a very common scenario in real life of editing a post for a Chinese user since Chinese writing is not separated by spaces, we might don't need to add spaces when inserting characters.

**Comment by derrickmehaffy** [comment] 2019-11-01 09:11
@POPOEVER we need some help trying to reproduce the issue. It's extremely hard to track down a bug if we can't reproduce this on our own system.

**Comment by POPOEVER** [comment] 2019-11-01 16:57
@derrickmehaffy I understand, and I'm 100% willing to offer my hand to help, just let me know how to, e.g, where does the editor's code lie? 

But, I still believe the issue should only be closed when the author confirmed a valid fix or an unsolvable status, please correct me if I'm wrong, thank you.

P.S, speaking reproduce the issue, maybe you can add Simplified Chinese to your system language, and IME as well, then you can type Chinese, it doesn't matter if you know what you type. I believe it's an issue that the editor's code doesn't handle double-byte character correctly, so actually not only Chinese, maybe other languages like Japanese and Korean are also affected.

Btw, I can bear with the current solution of inputting an extra space then deleting it, but that's a shame for a product.

**Comment by derrickmehaffy** [comment] 2019-11-01 17:10
Editor code is in the content manager plugin I believe I'm not much of a UI guy myself. I'd imagine if you look at the docs (or was it blog post?) One explained how to change the editor over to ckeditor that would also be the place for the current. 

Two birds one stone, if you can take a look at the current editor and also if you wanted to swap to a different one

**Comment by derrickmehaffy** [comment] 2019-11-01 17:11
Also could you possibly record a short video of the error happening?
