### ISSUE TITLE
The policy is not stopping the remove action

### ISSUE THREAD

**Issue by wil92** [strapi/strapi#6638] opened 2020-06-11 20:42 UTC
**Describe the bug**
I have a policy named `canRemoveOpinion.js` with this code

```
module.exports = async (ctx, next) => {
  ...
  if (condition) {
    return await next();
  }
  ctx.unauthorized();
};
```

what is happening, is that even when the policy is no calling the `next()` method, the delete action is called and the element is removed from the database. I didn't try thrown the rest API, this is happening with the graphql API.

**Steps to reproduce the behavior**

1. create a policy in one of the controllers in the route `api/controller-name/config/policies/myPolicy`
2. add the policy to the `schema.graphql.js` file in the configuration of the `delete` mutation
3. try to remove the element in a way that the policy didn't call the `next()` method and it will not work

**Expected behavior**
if the policy never call the `next()` method, the action in the controller shouldn't be executed

**System**

- Node.js version: 10.16.3
- NPM version: 6.9.0
- Strapi version: 3.0.1
- Database: mongodb
- Operating system: ubuntu 18.04

**Comment by derrickmehaffy** [comment] 2020-06-12 05:19
`return ctx.unauthorized();`

**Comment by wil92** [comment] 2020-06-12 21:46
> `return ctx.unauthorized();`

same result, I already try it

**Comment by wil92** [comment] 2020-06-13 13:59
I was taking a look to one dependency that Strapi is using `koa-compose`, and it looks to me that is expected that behavior, I mean, you can see this file that is the one that executes all the middlewares:

```
// node_modules/koa-compose/index.js:29
function compose (middleware) {
  if (!Array.isArray(middleware)) throw new TypeError('Middleware stack must be an array!')
  for (const fn of middleware) {
    if (typeof fn !== 'function') throw new TypeError('Middleware must be composed of functions!')
  }
  return function (context, next) {
    // last called middleware #
    let index = -1
    return dispatch(0)
    function dispatch (i) {
      if (i <= index) return Promise.reject(new Error('next() called multiple times'))
      index = i
      let fn = middleware[i]
      if (i === middleware.length) fn = next
      if (!fn) return Promise.resolve()
      try {
        return Promise.resolve(fn(context, dispatch.bind(null, i + 1)));
      } catch (err) {
        return Promise.reject(err)
      }
    }
  }
}
```

like you can see, no matter what happens, this library always calls all the policies. If one policy does not call the next method, it doesn't matter because in this function you can see that they in this case return `Promise.resolve()`.

The only way I found to really stop the chain of middlewares was throwing an Error. So the workaround that I found was this:

```
module.exports = async (ctx, next) => {
  ...
  if (condition) {
    return await next();
  }
  ctx.unauthorized();
  thrown new Error(); // add this to the policy
};
```

**Comment by lauriejim** [comment] 2020-06-16 13:25
Hello can you try to add a log in your policy, because I think your issue is a duplicate of this one - https://github.com/strapi/strapi/issues/5244

**Comment by wil92** [comment] 2020-06-18 18:47
In my case, I'm not using the kebab-cased, as I said in my comment, seems to me, like is something related to what is managing the policies, even when the policy is not calling the `next()` method, the flow is continuing

**Comment by DanijelBojcic** [comment] 2020-07-17 14:59
`ctx.unauthorized` didn't work for me neither.
I've solved it by digging in the users-permissions plugin where I found how they manage the policies:
```
"use strict";
/**
 * `isOwnUser` policy.
 */
const handleErrors = (ctx, err = undefined, type) => {
  throw strapi.errors[type](err);
};

module.exports = async (ctx, next) => {
  //check if the updatable user is the authenticated one
  if (ctx.params.id === ctx.state.user.id) {
    // Go to next policy or will reach the controller's action.
    return await next();
  }
  return handleErrors(ctx, undefined, 'forbidden');
};
```

**Closed** 2020-08-13 13:41 UTC
Labels: type: help wanted
