### ISSUE TITLE
When create new Strapi App with cli for MongoDB Collection New-Detail pages have error

### ISSUE THREAD

**Issue by yadigarbz** [strapi/strapi#11174] opened 2021-10-03 07:59 UTC
### Describe the bug

When you create a new Strapi with CLI as described with MongoDB connection or even create with **--quickstart** then convert it to mongoose connector. It's able to create collection types and work with such as settings and other functionalities which I already describe my created collections at MongoDB added as collection type and able to show them. 

But whenever I clicked and try to edit data nor try to click add new button I am facing with the error below 👇🏻

### Steps to reproduce the behavior

1. Create a new app with: `strapi new --dbclient=mongo <other necessary options of mongo>`
2. Go and login to admin panel
3. Click to pre-created Users collection
4. Click one of records or aren't there any record click add new user

### Expected behavior

Admin must be able to edit and new data. 
Tried with fresh **--quickstart** default DB system which is SQLlite everything is fine.
But I cannot edit my content in DB and it is too expensive to change my whole DB to another provider

### Screenshots

<img src="https://user-images.githubusercontent.com/25516540/135744934-52370f79-34b3-4769-9f51-3718f57720ec.png" width="300" />

### System

- Node.js version: v14.17.0
- NPM version: 6.14.13
- Strapi version: 3.6.8
- Database: Mongo
- Operating system: macOS 13.0 Monetary with M1 Bionic

### Additional context

I heard about articles Strapi gonna drop MongoDB support and understand there is little way to release v4 but isn't facing these errors even now a bit weird?. Hope it can be fixable or there is I do somewhere wrong

Also checked:
Issue [1912](https://github.com/strapi/strapi/issues/1912) either this is not working and looks different than my problem.
This one looks hole related to Mongo driver

**Comment by yadigarbz** [comment] 2021-10-03 08:45
Well, if you're obsessed as me you can never quit digging :) Found out config as --no-optimization when building and with this ability to saw detailed chunk JSs. And figured out the issue was related to Internalization and translations. When I went to settings and check English as the default language everything sorted out. 

With this can we consider when rebuilding the app in case there is no default language setting the first language as the default one?

**Comment by derrickmehaffy** [comment] 2021-10-04 20:34
I could not reproduce the described issue, can you give some more context?

Keep in mind, we will be dropping support for MongoDB with the coming v4 so I'm not sure we will even get to patching this if there is an issue since we have less than a month til v4 goes stable and v3 goes into security only updates.

**Comment by derrickmehaffy** [comment] 2021-11-30 14:28
MongoDB is not supported anymore in Strapi v4, marking as closed

**Closed by derrickmehaffy** 2021-11-30 14:28 UTC
Labels: status: can't reproduce
