### ISSUE TITLE
Required fields allow null values

### ISSUE THREAD

**Issue by luiselarad** [strapi/strapi#7283] opened 2020-07-31 20:16 UTC
**Describe the bug**

Collection fields are set as required, but still allow null values ​​from http call through Postman application.

**Steps to reproduce the behavior**

1. Go to admin page
2. Create a collection type with required fields
3. Make a POST HTTP call from Postman with the fields defined but empty.

**Expected behavior**

Show a validation error for the required field. "The field cannot be null". Same as how it happens when you try to enter an entry from the administrator.

**Screenshots**

![image](https://user-images.githubusercontent.com/20350377/89073496-9dfe0d80-d348-11ea-86e2-e8341627db1f.png)
![image](https://user-images.githubusercontent.com/20350377/89073584-cd147f00-d348-11ea-9311-9e75aec6d366.png)
![image](https://user-images.githubusercontent.com/20350377/89073655-eddcd480-d348-11ea-8447-993167c1f057.png)
![image](https://user-images.githubusercontent.com/20350377/89073792-2da3bc00-d349-11ea-844f-1b5d7cf8c2f5.png)
![image](https://user-images.githubusercontent.com/20350377/89078805-14a00880-d353-11ea-977f-0448d405a8a3.png)

**System**

- Node.js version: 12.18.0
- NPM version: 6.14.4
- Strapi version: 3.1.2
- Database: Postgresql 12
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment] 2020-07-31 20:39
Can you please update this with the bug report template? https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md

**Comment by lauriejim** [comment] 2020-08-01 10:13
@alexandrebodin what do you think about that behavior?
Thank you @luiselarad for reporting this.

**Comment by alexandrebodin** [comment] 2020-08-03 08:29
Hi, 

An empty field shouldn't be interpreted as an undefined/null value. if you send `""` the validator considers the value is here. It is not the same thing as not sending the key or null. a user could want to send an empty string or a 0 value.

You can use the `minLength` validation to avoid empty strings.

I think we can close this issue as this is the intended behaviour.

**Closed** 2020-08-03 10:17 UTC
Labels: type: discussion
