### ISSUE TITLE
Allow configuration of null sorting (first or last)

### ISSUE THREAD

**Issue by WalkingPizza** [strapi/strapi#12593] opened 2022-02-19 01:14 UTC
### Describe the bug

When sorting entries by a nullable numeric field `x`, all entries with `x = null` are put:
- At the end if we are sorting in ascending order
- At the beginning if we are sorting in descending order

### Steps to reproduce the behavior

1. Create a content type `restaurant` with a numeric `stars` field
2. Create a restaurant `a` with `stars` equal to `1`
3. Create a restaurant `b` leaving `stars` empty
3. GET `/api/restaurants?sort=stars:desc`
4. Notice how `b` comes before `a` despite `a` having more stars

### Expected behavior

When sorting, null values should come at the beginning for ascending lists and at the end for descending lists.

### Screenshots

<img width="525" alt="image" src="https://user-images.githubusercontent.com/34224657/154779978-2bfc8a8a-481f-46f8-a440-100409da6451.png">

### System

- Node.js version: v16
- Yarn version: v1.22.15
- Strapi version: v4.0.6
- Database: PostgreSQL
- Operating system: Alpine

**Comment by kasonde** [comment] 2022-02-22 07:44
I might be doing something wrong but using the description you provided,  data was returned as expected and not the way it happened with your response

**Comment by WalkingPizza** [comment] 2022-02-22 07:48
> I might be doing something wrong but using the description you provided,  data was returned as expected and not the way it happened with your response

Could you try to:
- Create the content type first
- Create two new entries
- Edit the content type adding the `stars` field
- Set the `stars` field in one of the entries but not the other
- Query through REST again

Thanks!

**Comment by kasonde** [comment] 2022-02-22 13:36
That's actually exactly what I did. I had an existing Strapi application in that version with my usual "Item" content type with a couple fields already populated and records stored. Did the exact last 3 steps you mentioned (the records already existed)

**Comment by derrickmehaffy** [comment] 2022-02-22 22:11
Can't reproduce on SQLite: 
![image](https://user-images.githubusercontent.com/8593673/155228116-46e751c4-0898-4331-b6e6-f6b8a24b8e65.png)
![image](https://user-images.githubusercontent.com/8593673/155228160-0427fdc5-c2c9-47c1-be88-a10a1067f660.png)

Guessing this could be database specific and how the database handles sorting mechanics

**Comment by derrickmehaffy** [comment] 2022-02-23 20:40
Talked with user on Discord, this is intended in PostgreSQL and Knex.js added a means to control if nulls are first or last.

Setting as a feature request. (It depends on the database, we could add a configuration for this but it's not a "bug")

**Comment by derrickmehaffy** [comment] 2022-05-05 20:37
Hey all, we are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://feedback.strapi.io/developer-experience/p/allow-configuration-of-null-sorting-first-or-last
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!

**Closed by derrickmehaffy** 2022-05-05 20:37 UTC
Labels: issue: feature request, source: core:database
