### ISSUE TITLE
Strapi quickstart: user-permissions plugin not installing.

### ISSUE THREAD

**Issue by tshelver** [strapi/strapi#3002] opened 2019-03-20 05:48 UTC
Node: v11.12.0
Npm: V6.7.0
Strapi: V3.0.0-alpha.25.2
Ubuntu 18.04.
DB: as deliverred 
**What is the current behavior?**
-----------------------------------------
Plugin user-permissions does not load.  
When I go to http://localhost:1337/admin, the quickstart guide is shown, but no Admin user setup is displayed, per the Quickstart guide

=================
See startup below

$ strapi new strapi_qs --quickstart
🚀 Starting to create your Strapi application.

✅ Connected to the database

🏗  Application generation:
✔ Copy dashboard
✔ Install plugin settings-manager.
✔ Install plugin content-type-builder.
✔ Install plugin content-manager.
⚠ An error occurred during users-permissions plugin installation.
- Install users-permissions plugin
✖ An error occurred during plugin installation. 
Please make sure this plugin is available on npm: https://www.npmjs.com/package/strapi-plugin-users-permissions

✔ Install plugin email.
✔ Install plugin upload.
✔ Link strapi dependency to the project.

👌 Your new application strapi_qs is ready at /home/tshelver/git/strapi_qs.

**Steps to reproduce the problem**
--------------------------------------------
Tried to manually install the plugin, same issue

**What is the expected behavior?**

**Suggested solutions**

**Comment by tshelver** [comment] 2019-03-20 12:00
Looking at https://github.com/strapi/strapi/issues/2324   it seems that Node 11 isn't supported, but that was some time ago.  Is node 11 still not supported?

**Comment by lauriejim** [comment] 2019-03-21 14:50
Hello @tshelver!

Can you to uninstall globally Strapi and install it again globally and retry to create your project.

I was not able to reproduce your issue.
I installed node 11, installed Strapi and created an app like you did all worked fine.

**Comment by tshelver** [comment] 2019-03-21 16:43
Thanks.  I will have to do some head scratching then.  I have tried uninstalling strapi and reinstalling, but same issue.
If I look in the plug-ins directory, the user-permissions directory is there, but nothing inside of it.
I's really hate to set up a fresh environment from Node/npm on.

**Comment by lauriejim** [comment] 2019-03-22 15:32
Arg not cool. I tested it again and it works well.
It's weird that happen to this plugin... The process is the same for all plugins.
Did you have full permission access to the folder you create your app?

**Comment by tshelver** [comment] 2019-03-25 07:50
Yup. everything is in my user home.  All the other plugins installed just fine.  This one leaves an empty user-permissions subdirectory in the plug ins folder

**Comment by tshelver** [comment] 2019-03-25 07:53
I will just keep monitoring the issues list for now, and switch the project workpath to something that does not require RESTful (or GraphQL) content for now, 
Maybe when the beta comes out there will be some resolution, or I may find something in my npm / node environment that isn't standard.

**Comment by lauriejim** [comment] 2019-03-25 15:36
Can you give me the path of the folder your are trying to create your application.
Can you try with an other application name (without `_` or special character)

**Comment by tshelver** [comment] 2019-03-25 16:18
It's in my user home (under the subdirectory containing all my git projects) directory:  /home/tshelver/git/cms/plugins/
In that directory I have:
tshelver@T540p:~/git/cms/plugins$ ls -la
total 36
drwxr-xr-x 9 tshelver tshelver 4096 Mar 21 13:02 .
drwxr-xr-x 9 tshelver tshelver 4096 Mar 20 20:32 ..
drwxr-xr-x 7 tshelver tshelver 4096 Mar 20 12:50 content-manager
drwxr-xr-x 8 tshelver tshelver 4096 Mar 20 12:50 content-type-builder
drwxr-xr-x 8 tshelver tshelver 4096 Mar 20 12:50 email
drwxr-xr-x 8 tshelver tshelver 4096 Mar 21 13:03 graphql
drwxr-xr-x 7 tshelver tshelver 4096 Mar 20 12:50 settings-manager
drwxr-xr-x 9 tshelver tshelver 4096 Mar 20 12:50 upload
drwxr-xr-x 2 tshelver tshelver 4096 Mar 20 12:50 users-permissions

All the other plugin folders are correctly populated.

**Comment by tshelver** [comment] 2019-03-25 16:30
Here is the next attempt:: different directory of my tshelver home (MEGAsync), called strapitest
Same result.  user-permissions fails, empty directory created: see below.
Perhaps being situated in South Africa means I can't get permissions ? :dancer: 

tshelver@T540p:~/MEGAsync$ strapi new strapitest --quickstart
🚀 Starting to create your Strapi application.


✅ Connected to the database

🏗  Application generation:
✔ Copy dashboard
✔ Install plugin settings-manager.
✔ Install plugin content-type-builder.
✔ Install plugin content-manager.
⚠ An error occurred during users-permissions plugin installation.
- Install users-permissions plugin
✖ An error occurred during plugin installation. 
Please make sure this plugin is available on npm: https://www.npmjs.com/package/strapi-plugin-users-permissions

✔ Install plugin email.
✔ Install plugin upload.
✔ Link strapi dependency to the project.

👌 Your new application strapitest is ready at /home/tshelver/MEGAsync/strapitest.

⚡ Change directory:
$ cd strapitest

⚡ Start application:
$ strapi start

[2019-03-25T16:26:35.494Z] info Time: Mon Mar 25 2019 18:26:35 GMT+0200 (South Africa Standard Time)
[2019-03-25T16:26:35.494Z] info Launched in: 9352 ms
[2019-03-25T16:26:35.494Z] info Environment: development
[2019-03-25T16:26:35.494Z] info Process PID: 16256
[2019-03-25T16:26:35.494Z] info Version: 3.0.0-alpha.25.2 (node v11.12.0)
[2019-03-25T16:26:35.494Z] info To shut down your server, press <CTRL> + C at any time

[2019-03-25T16:26:35.495Z] info ☄️  Admin panel: http://localhost:1337/admin
[2019-03-25T16:26:35.495Z] info ⚡ Server: http://localhost:1337

[2019-03-25T16:26:35.681Z] debug HEAD index.html (181 ms)
[2019-03-25T16:26:35.683Z] info ⏳ Opening the admin panel...
[2019-03-25T16:26:41.455Z] debug GET index.html (3 ms)
[2019-03-25T16:26:42.713Z] debug GET vendor.dll.js (2 ms)
[2019-03-25T16:26:42.747Z] debug GET main.js (2 ms)
[2019-03-25T16:26:44.032Z] debug GET /favicon.ico (1 ms)
[2019-03-25T16:26:45.234Z] debug GET plugins.json (1 ms)
[2019-03-25T16:26:45.858Z] debug GET /admin/gaConfig (560 ms)
[2019-03-25T16:26:45.862Z] debug GET /admin/strapiVersion (1 ms)
[2019-03-25T16:26:45.864Z] debug GET main.js (5 ms)
[2019-03-25T16:26:45.866Z] debug GET /admin/currentEnvironment (2 ms)
[2019-03-25T16:26:45.869Z] debug GET /admin/layout (1 ms)
[2019-03-25T16:26:45.872Z] debug GET main.js (5 ms)
[2019-03-25T16:26:45.872Z] debug GET bd03a2cc277bbbc338d464e679fe9942.woff2 (1 ms)
[2019-03-25T16:26:45.874Z] debug GET main.js (4 ms)
[2019-03-25T16:26:45.876Z] debug GET main.js (4 ms)
[2019-03-25T16:26:45.877Z] debug GET main.js (4 ms)
[2019-03-25T16:26:46.221Z] debug GET /content-type-builder/autoReload (2 ms)
[2019-03-25T16:26:46.290Z] debug GET /settings-manager/autoReload (1 ms)
[2019-03-25T16:26:46.416Z] debug GET /admin/gaConfig (2 ms)
[2019-03-25T16:26:46.419Z] debug GET /admin/strapiVersion (3 ms)
[2019-03-25T16:26:46.421Z] debug GET /admin/currentEnvironment (1 ms)
[2019-03-25T16:26:46.423Z] debug GET /admin/layout (1 ms)
[2019-03-25T16:26:46.435Z] debug GET /content-type-builder/autoReload (1 ms)
[2019-03-25T16:26:46.436Z] debug GET /settings-manager/autoReload (1 ms)
[2019-03-25T16:26:46.473Z] debug GET /content-manager/models (4 ms)
[2019-03-25T16:26:46.537Z] debug GET 0.c248ef1624427190a579.chunk.js (1 ms)
[2019-03-25T16:26:46.570Z] debug GET c9cbbdc3762c340d5d37073a54971487.woff2 (1 ms)
[2019-03-25T16:26:46.570Z] debug GET 267c6434976db0c52bedd6620cca7002.png (3 ms)
[2019-03-25T16:26:46.886Z] debug GET af7ae505a9eed503f8b8e6982036873e.woff2 (2 ms)
[2019-03-25T16:26:46.887Z] debug GET 8b4f872c5de19974857328d06d3fe48f.woff2 (2 ms)
[2019-03-25T16:26:46.887Z] debug GET cccb897485813c7c256901dbca54ecf2.woff2 (1 ms)
[2019-03-25T16:26:47.402Z] debug GET 6755917af369543435f7ea1cf2f7f443.png (6 ms)
[2019-03-25T16:26:47.402Z] debug GET 5472a94400e92f6e0cb08ec16118e86f.png (4 ms)
[2019-03-25T16:26:47.403Z] debug GET 57bdf4b3dab44f0fcda646945e133b9f.png (4 ms)
[2019-03-25T16:26:47.403Z] debug GET fbb35f166e78eadd0b14b7b0b41c4b28.png (3 ms)
[2019-03-25T16:26:47.404Z] debug GET 9f75b471e23e696377caba384242af1c.png (3 ms)
[2019-03-25T16:26:47.406Z] debug GET da6ad156e14024ad3451a00c2c344e94.png (2 ms)
[2019-03-25T16:26:48.022Z] debug GET 80f6811f6c30735dab68a01372d8b78f.woff2 (2 ms)
[2019-03-25T16:26:48.022Z] debug GET 5b11181129030291630a63021a34f343.png (1 ms)

**Comment by derrickmehaffy** [comment] 2019-03-25 16:42
@tshelver maybe see if you can check/change your npm repo? Try a US or EU mirror?

**Comment by tshelver** [comment] 2019-03-25 17:20
Not the issue....  I got the plugin installed. Now to test out if it works.
Maybe I misunderstood things or missed something in my original strapi install (did it twice, just to be sure though...)?  
I copied the  https://www.npmjs.com/package/strapi-plugin-users-permissions to my browser, and got through to the site, so no problem with the repo.  AFAIK it's the same repo worldwide.  Per
strapi-plugin-users-permissions
3.0.0-alpha.7 • Public • Published a year ago

I  copied the plugin npm install  npm i strapi-plugin-users-permissions and ran that as :+1: 
sudo npm i strapi-plugin-users-permissions

Then I started a new application (strapistest)
It all installed.....

I am a long way from being a node / npm expert, just starting off my background is more big systems and backend stuff.

When I did the npm install I got:
tshelver@T540p:~/MEGAsync/strapitest$ sudo npm i strapi-plugin-users-permissions 
[sudo] password for tshelver: 
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN bookshelf@0.12.1 requires a peer of knex@>=0.6.10 <0.15.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-ga@2.5.7 requires a peer of react@^15.6.2 || ^16.0 but none is installed. You must install peer dependencies yourself.
npm WARN video-react@0.13.6 requires a peer of react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN video-react@0.13.6 requires a peer of react-dom@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.

Anything to worry about?

**Comment by derrickmehaffy** [comment] 2019-03-25 17:38
@tshelver 
![image](https://user-images.githubusercontent.com/8593673/54941444-139ed180-4eea-11e9-94fb-ac4e58f4554e.png)

`npm i strapi-plugin-users-permissions@alpha`

v7 is olddddd and 99.999% sure is not gonna work :stuck_out_tongue:

**Comment by derrickmehaffy** [comment] 2019-03-25 17:39
Also you shouldn't need to use sudo to run an npm i inside of a project https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by derrickmehaffy** [comment] 2019-03-25 17:40
to be specific v7 is over a year old now: 
![image](https://user-images.githubusercontent.com/8593673/54941557-5eb8e480-4eea-11e9-9da4-9b646629fbde.png)

**Comment by tshelver** [comment] 2019-03-25 17:48
Follow the link:  https://www.npmjs.com/package/strapi-plugin-users-permissions.  That doesn't specify any version.  I just followed the standard install script....  When I followed the link in my browser, that is where i ended up.
last publish
10 days ago  according to the page, even if only V7
Where would i get a later release.
The npm install i  would not run without the sudo.
After I did the sudo, it all worked.

Maybe i can get rid of all my node stuff and start again?

**Comment by tshelver** [comment] 2019-03-26 14:38
I will close this one and monitor.  I have had a successful test cycle through pulling data from the API.
Plan to install on a clean server and test against a semi-live website / eStore built in Jekyll that i am currently populating products / prices from  LibreOffice Base CSVs.

**Closed** 2019-03-26 14:39 UTC
Labels: type: help wanted 🤷‍♂️

**Comment by Gerche** [comment] 2019-05-25 18:40
I have the exact same issue on both node 10.15.3 and 11.14.0. I tried reinstalling strapi but still no success.
os x: 10.14.5
npm: 6.9.0
strapi: 3.0.0-alpha.26.2
db: Postgres 11.2

**Comment by guiprix** [comment] 2020-04-29 13:12
I'm a beginner and i have the same problem with plugins error, can you tell me how to uninstall globally strapi pls? thanks

**Comment by gaurangrshah** [comment] 2020-09-22 05:54
Hey all, I had this same issue -- oddly my first attempt for another project had previously worked -- so I was really confused by this. I tried to diagnose for quite some time, but in the interest of saving time and moving forward I ended up pulling my original version down, and of course, it was still in working condition. 

All this to say I've stripped that version down to a very basic version of what I need as a base, but if anyone wants u can just clone that same repo... https://github.com/gaurangrshah/strapi-default-api.git

-- not a fix, just a workaround in the interest of saving time. You can always strip. It down further for your needs as I'm sure they'll differ. 

Hope this helps.
