### ISSUE TITLE
Invalid (My)SQL query generated, when GraphQL relation is draft

### ISSUE THREAD

**Issue by gu-stav** [strapi/strapi#10574] opened 2021-07-02 10:08 UTC
## Bug report

The following GraphQL query

```graphql
query AllGroupPaths {
  cities {
    group {
      id
    }
  }
}
```

generated an invalid SQL syntax when a group is in a draft state. The generated query looks like:

```sql
select `groups`.* from `groups` where `groups`.`id` = {} and (`groups`.`published_at` is not null) limit 1
```

and generated the following error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and (`groups`.`published_at` is not null) limit 1' at line 1

Stacktrace:

```
"stacktrace": [
    "Error: select `groups`.* from `groups` where `groups`.`id` = {} and (`groups`.`published_at` is not null) limit 1 - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and (`groups`.`published_at` is not null) limit 1' at line 1",
    "    at Query.Sequence._packetToError (/home/gustav/Development/seebruecke/cms/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)",
    "    at Query.ErrorPacket (/home/gustav/Development/seebruecke/cms/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)",
    "    at Protocol._parsePacket (/home/gustav/Development/seebruecke/cms/node_modules/mysql/lib/protocol/Protocol.js:291:23)",
    "    at Parser._parsePacket (/home/gustav/Development/seebruecke/cms/node_modules/mysql/lib/protocol/Parser.js:433:10)",
    "    at Parser.write (/home/gustav/Development/seebruecke/cms/node_modules/mysql/lib/protocol/Parser.js:43:10)",
    "    at Protocol.write (/home/gustav/Development/seebruecke/cms/node_modules/mysql/lib/protocol/Protocol.js:38:16)",
    "    at Socket.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/mysql/lib/Connection.js:88:28)",
    "    at Socket.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/mysql/lib/Connection.js:526:10)",
    "    at Socket.emit (events.js:376:20)",
    "    at addChunk (internal/streams/readable.js:309:12)",
    "    at readableAddChunk (internal/streams/readable.js:284:9)",
    "    at Socket.Readable.push (internal/streams/readable.js:223:10)",
    "    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
    "    at Protocol._enqueue (/home/gustav/Development/seebruecke/cms/node_modules/mysql/lib/protocol/Protocol.js:144:48)",
    "    at Connection.query (/home/gustav/Development/seebruecke/cms/node_modules/mysql/lib/Connection.js:198:25)",
    "    at /home/gustav/Development/seebruecke/cms/node_modules/knex/lib/dialects/mysql/index.js:126:18",
    "    at new Promise (<anonymous>)",
    "    at Client_MySQL._query (/home/gustav/Development/seebruecke/cms/node_modules/knex/lib/dialects/mysql/index.js:120:12)",
    "    at executeQuery (/home/gustav/Development/seebruecke/cms/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)",
    "    at Client_MySQL.query (/home/gustav/Development/seebruecke/cms/node_modules/knex/lib/client.js:134:12)",
    "    at Runner.query (/home/gustav/Development/seebruecke/cms/node_modules/knex/lib/execution/runner.js:130:36)",
    "    at ensureConnectionCallback (/home/gustav/Development/seebruecke/cms/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)",
    "    at Runner.ensureConnection (/home/gustav/Development/seebruecke/cms/node_modules/knex/lib/execution/runner.js:272:20)",
    "    at async Runner.run (/home/gustav/Development/seebruecke/cms/node_modules/knex/lib/execution/runner.js:30:19)",
    "From previous event:",
    "    at processImmediate (internal/timers.js:462:21)",
    "From previous event:",
    "    at Sync.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/sync.js:204:8)",
    "From previous event:",
    "    at Child.<anonymous> (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/collection.js:160:12)",
    "From previous event:",
    "    at Child.fetchAll (/home/gustav/Development/seebruecke/cms/node_modules/bookshelf/lib/model.js:878:10)",
    "    at find (/home/gustav/Development/seebruecke/cms/node_modules/strapi-connector-bookshelf/lib/queries.js:81:8)",
    "    at Object.findOne (/home/gustav/Development/seebruecke/cms/node_modules/strapi-connector-bookshelf/lib/queries.js:68:27)",
    "    at fn (/home/gustav/Development/seebruecke/cms/node_modules/strapi-database/lib/queries/helpers.js:31:54)",
    "    at Object.findOne (/home/gustav/Development/seebruecke/cms/node_modules/strapi-database/lib/queries/helpers.js:15:24)",
    "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
    "    at async Promise.all (index 0)"
  ]
```

The city model:

```json
{
  "kind": "collectionType",
  "collectionName": "cities",
  "info": {
    "name": "City",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "attributes": {
    "city": {
      "model": "city",
      "via": "group"
    },
    "group": {
      "via": "city",
      "model": "group"
    },
  }
}
```

The group model:

```json
{
  "kind": "collectionType",
  "collectionName": "groups",
  "info": {
    "name": "Group",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "attributes": {}
}
```

### Expected behavior

I expect the query to run successfully.

### System

- Strapi version: 3.6.5
- Database: MySQL, v5.7.30, InnoDB
- Operating system: Debian

**Comment by gustavpursche** [comment] 2021-07-05 19:47
@kasonde I was able to create a minimal reproduction, which you can find here: https://github.com/gustavpursche/strapi-null-reproduction

Steps you have to take:

1. Create a city (and publish)
2. Create a group (save, but don't publish)
3. Run the graphql query mentioned above

**Comment by gustavpursche** [comment] 2021-07-08 06:27
@derrickmehaffy I think the "status: pending reproduction" can be removed from this.

**Comment by kasonde** [comment] 2021-07-08 07:43
Hi @gustavpursche. I kept the, "pending reproduction" label because your issue is still in my queue and hasn't yet been confirmed. Thank you for your snippet, it should help the process massively. You'll get a response on this from me very soon.

**Comment by gustavpursche** [comment] 2021-07-08 08:35
@kasonde thanks! I just wanted to make sure that the issue isn't forgotten since it turned out to be a very basic problem, which could affect many.

Thanks for your response!

**Comment by Mortalife** [comment] 2021-07-20 12:37
Same issue as is described here:

https://github.com/strapi/strapi/issues/9149

**Comment by kasonde** [comment] 2021-11-01 08:28
@yoleoagain thanks for the additional report. For your question, however, please consider posting on one of our community platforms Discord/the Community Forum to ensure that we stay on topic for this issue.

**Comment by yoleoagain** [comment] 2021-11-05 13:37
> @yoleoagain thanks for the additional report. For your question, however, please consider posting on one of our community platforms Discord/the Community Forum to ensure that we stay on topic for this issue.
Everything started working when I removed the strict option from database.js 0_о
![image](https://user-images.githubusercontent.com/34099520/140518943-115277da-f69b-4810-be48-53b6dbcd95af.png)

**Comment by derrickmehaffy** [comment] 2022-01-05 21:44
Should be fixed in v4

**Closed by derrickmehaffy** 2022-01-05 21:44 UTC
Labels: severity: medium, source: core:database, source: plugin:graphql, status: pending reproduction

**Comment by boblitex** [comment] 2022-03-09 19:38
> Should be fixed in v4

@derrickmehaffy what's a fix for this in v3.? using 3.6.8 and not looking to move to v4 for this particular use case

**Comment by derrickmehaffy** [comment] 2022-03-09 19:40
> > Should be fixed in v4
> 
> @derrickmehaffy what's a fix for this in v3.? using 3.6.8 and not looking to move to v4 for this particular use case

Short answer is there likely isn't/won't be one. We are pushing fixes for v3 unless they are security related as the entire engineering team has moved on to working on v4.

**Comment by RodrigoLuglio** [comment] 2022-04-06 23:38
Will there be a migration guide from v3 to v4?
I`m having this issue in production...
