### ISSUE TITLE
[V4] Auth Providers issues

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#11337] opened 2021-10-22 12:59 UTC
### Describe the bug (2)

- [ ] Error: `Grant: mount session middleware first `
- [ ] logos missing from some providers (see https://github.com/strapi/strapi/issues/11337#issuecomment-963766035)
- [ ] To me it seems that the message `The redirect URL to add in your VK application configurations` needs be updated? (`VK` presumably is for the VKontakte Russian Facebook?)
- [x] `404 not found` - Trying to add Facebook auth provider (exact same setup as in V3) results in 404 not found, checking docs did not help. (adding `/api` prefix solves this)

### Screenshots

<img width="527" alt="Screen Shot 2021-10-22 at 3 53 44 PM" src="https://user-images.githubusercontent.com/11737572/138457188-b71150d8-f72f-482d-a2e0-da9a75f3fec0.png">
<img width="566" alt="Screen Shot 2021-10-22 at 3 53 28 PM" src="https://user-images.githubusercontent.com/11737572/138457196-1f82cdaa-a3e4-43ef-9695-6ba6007b94b7.png">
<img width="840" alt="Screen Shot 2021-10-22 at 3 52 33 PM" src="https://user-images.githubusercontent.com/11737572/138457199-d3d00c73-77cb-4d47-b5d0-c5544498844c.png">

### Additional Context
I looked into the user permissions plugin `auth` routes, which clearly has the route.

![](https://media.discordapp.net/attachments/841755530007805983/901543881361997864/Screen_Shot_2021-10-23_at_9.52.12_PM.png)

I also tried adding new route for testing and hitting that which also returned 404. Is there some place that registers these routes/filters some out?

### Question
- are auth providers ready to be used in V4?
  - if so, has something significantly changed?

### System
```json
    "@strapi/plugin-graphql": "4.0.0-beta.4",
    "@strapi/plugin-i18n": "4.0.0-beta.4",
    "@strapi/plugin-users-permissions": "4.0.0-beta.4",
    "@strapi/strapi": "4.0.0-beta.4",
```
- Database: Postgres

**Comment by derrickmehaffy** [comment] 2021-11-09 02:52
Tested with Discord on beta.11 and got the following error (using the v4 branch of the react-login from strapi-examples)

```json
{
  "data": null,
  "error": {
    "status": 400,
    "name": "BadRequestError",
    "message": "Grant: mount session middleware first"
  }
}
```

I also noticed that the Discord provider is using the wrong localization:
![image](https://user-images.githubusercontent.com/8593673/140853087-ff8a1ee0-f873-4f4a-8084-4b47da7e2e55.png)

Auth0 and CAS are missing logos (and all of the providers aren't capialized)
There is also some `defaults` provider that shouldn't exist.
![image](https://user-images.githubusercontent.com/8593673/140853199-0900789e-d925-4974-b9d3-72788502c96e.png)
![image](https://user-images.githubusercontent.com/8593673/140853225-179a1f75-a6c2-4dab-94c8-ea859cfb7b17.png)

**Comment by derrickmehaffy** [comment] 2021-11-09 02:53
Needless to say, confirmed on beta.11 (I didn't test all providers but I imagine there are similar problems)

**Comment by ScottAgirs** [comment] 2021-11-09 09:22
Woohoo! Very glad to see you have gotten to Providers!! 

Just a quick note - I was able to get to the `"Grant: mount session middleware first` only if I manually added `/api` to the URL, so instead of:
<img width="451" alt="Screen Shot 2021-11-09 at 11 21 46 AM" src="https://user-images.githubusercontent.com/11737572/140897276-92ffb223-b343-44ab-aeed-29dad924cee1.png">
to this
<img width="498" alt="Screen Shot 2021-11-09 at 11 22 01 AM" src="https://user-images.githubusercontent.com/11737572/140897296-e7b06fd8-eea9-4f63-bda2-49b6ce016b27.png">

This is still true for `beta.11`. 🤞🏼

**Comment by derrickmehaffy** [comment] 2021-11-10 00:01
That `/api` is required @ScottAgirs as it's the new default prefix assigned to all "content-api" routes (though it is configurable)

**Comment by ScottAgirs** [comment] 2021-11-10 08:39
@derrickmehaffy ahh got it 🙌🏼

**Comment by LuckeeDev** [comment] 2021-11-17 18:07
Confirmed on `beta.13`. Is there any workaround currently available?

**Comment by derrickmehaffy** [comment] 2021-11-18 16:43
> Confirmed on `beta.13`. Is there any workaround currently available?

No not currently, the engineer team will need to debug

**Comment by ScottAgirs** [comment] 2021-11-29 13:49
Hey folks, pardon the refresh - any updates on a potential ETA on this?

**Comment by derrickmehaffy** [comment] 2021-11-29 21:28
> Hey folks, pardon the refresh - any updates on a potential ETA on this?

The team might take a look this week, not sure. I'll ping @JabStrapi to see if he has any updates on schedule.

**Comment by rgoupil** [comment] 2021-12-02 17:48
I started from that hint:
https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/strapi/lib/middlewares/index.js#L14-L17

Simply uncommenting doesn't seem to do the trick as it look like the middleware hasn't been updated to the v4 api either:
* exporting an object with an `initialize` function instead of directly a function => https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/strapi/lib/middlewares/session/index.js#L95
* grabbing the settings through deprecated API `strapi.config.middleware.settings.session.client` => https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/strapi/lib/middlewares/session/index.js#L99

I've found a way to fix this issue with cookies and sqlite but I have yet to try with other clients.
@derrickmehaffy has the team taken care of the issue yet? If not I can keep working on this tomorrow ;)

**Comment by derrickmehaffy** [comment] 2021-12-02 20:34
> I started from that hint:
> 
> https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/strapi/lib/middlewares/index.js#L14-L17
> 
> Simply uncommenting doesn't seem to do the trick as it look like the middleware hasn't been updated to the v4 api either. A few examples:
> 
> * exporting an object with an `initialize` function instead of directly a function => https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/strapi/lib/middlewares/session/index.js#L95
> * grabbing the settings through deprecated API `strapi.config.middleware.settings.session.client` => https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/strapi/lib/middlewares/session/index.js#L97-L101
> 
> I've found a way to fix this issue with cookies and sqlite but I have yet to try with other clients. @derrickmehaffy has the team taken care of the issue yet? If not I can keep working on this tomorrow wink

I believe the team is looking into it and it should be fixed in the next release (v4.0.1) but beyond that I'm not sure of the details

**Comment by derrickmehaffy** [comment] 2021-12-02 20:34
Thank you for the details though!

**Comment by rgoupil** [comment] 2021-12-03 08:18
> I believe the team is looking into it and it should be fixed in the next release (v4.0.1) but beyond that I'm not sure of the details

Sounds great! If you don't mind I'll just drop my PR here for the middleware issue: https://github.com/strapi/strapi/pull/11777
Feel free to merge it if you'd like or keep it alive until v4.0.1 is released 😃

**Comment by asaf** [comment] 2021-12-03 16:42
@rgoupil I'm not sure this is related to this PR directly, but when UI hits Strapi backend with the  provided access_token via `http://localhost:1337/api/auth/crossid/callback?access_token=xyz`

Backend always returns

```json
{
"data":null,
"error":{"status":401,"name":"UnauthorizedError","message":"Missing or invalid credentials","details":{}}}
```

Looks like the provider code of the user-permissions plugin does not even get invoked,


Asaf.

**Comment by rgoupil** [comment] 2021-12-03 17:09
Hey @asaf, I'm no expert however I see no mention to a `crossid` auth provider.
I'm afraid I won't be able to help you much more than that.
How did you got there in the first place?

**Comment by asaf** [comment] 2021-12-03 17:21
@rgoupil It's just another provider I added, see [commit](https://github.com/crossid/strapi/commit/791aad747fef3df1b89d0c8cc69cbe85a6a59e99)

But atm in _master_, any provider I try to hit, I get the error above.

**Comment by asaf** [comment] 2021-12-03 18:47
@rgoupil I think I found the problem,
The `packages/plugins/users-permissions/server/services/jwt.js:getToken()` tries to invoke `this.verify(token)` on the given token and fails.

This causes the provider code not to be invoked at all.

If I return null from this function everything works as expected.

Maybe JWT verify & provider collides?

**Comment by petersg83** [comment] 2021-12-06 15:50
https://github.com/strapi/strapi/pull/11825 would fix:
- [x] Error: `Grant: mount session middleware first `
- [x] To me it seems that the message `The redirect URL to add in your VK application configurations` needs be updated? (`VK` presumably is for the VKontakte Russian Facebook?)

**Comment by VEXstar** [comment] 2021-12-19 21:34
I get the same error as @asaf when using built-in providers discord and github.
![image](https://user-images.githubusercontent.com/46082448/146691541-74d045cf-246b-4466-9848-b0b56a589187.png)

**Comment by jacintofleta** [comment] 2021-12-19 22:50
Same as above, exact same issue but when using the Google Provider

**Comment by petersg83** [comment] 2021-12-20 12:59
We are working on it, there will be a fix soon!

**Comment by rathorevaibhav** [comment] 2021-12-24 14:43
@petersg83 any updates on when this will be fixed? We're using Google as our primary auth provider and are unable to launch our app without the provider integration! Thanks!
I'm trying super hard to convince my team not to downgrade to Strapi v3 where this seems to be working really well!

**Comment by petersg83** [comment] 2021-12-24 15:05
Hi @rathorevaibhav :) we are almost all in holidays for the moment. We come back the 3rd so it will be out most certainly before mid-January :)

**Comment by fadhilx** [comment] 2021-12-25 11:01
is there any temporary workaround to fix this?

**Comment by derrickmehaffy** [comment] 2021-12-27 16:03
> is there any temporary workaround to fix this?

No not really, there is a WIP PR that addresses it but we have to basically completely rewrite a middleware that was more or less only used for this.

**Comment by Flosrn** [comment] 2022-01-06 12:42
> is there any temporary workaround to fix this?

If someone found any workaround, even a bad workaround, just temporary, I'll take it because still doesn't work on `4.0.3`

**Comment by derrickmehaffy** [comment] 2022-01-06 18:32
> > is there any temporary workaround to fix this?
> 
> If someone found any workaround, even a bad workaround, just temporary, I'll take it because still doesn't work on `4.0.3`

We are well aware and have a WIP PR to fix it. There is no simple workaround as we had to completely rewrite a middleware.

**Comment by kayac-chang** [comment] 2022-01-09 14:43
> @rgoupil I think I found the problem, The `packages/plugins/users-permissions/server/services/jwt.js:getToken()` tries to invoke `this.verify(token)` on the given token and fails.
> 
> This causes the provider code not to be invoked at all.
> 
> If I return null from this function everything works as expected.
> 
> Maybe JWT verify & provider collides?

Related from comment above.

Can I ask about the detail of jwt verification?
Currently, we are using our `JWT_SECRET` to verify `access_token` which is come from auth provider,
because of this, we got `token invalid` exception and be catch by `users-permissions.authenticate`, 
and just return `{ authenticated: false }` without any error message. 

but actually, 
I guess we need to using `App Secret` which came from provider to verify `access_token`.
Thank you. 🙏

**Comment by cloakedninjas** [comment] 2022-01-11 10:51
Eagerly awaiting these fixes 😁

**Comment by danielkamin** [comment] 2022-01-11 21:43
Apparently this issue is not fixes in 4.0.4 version. Would really enjoy this to be fixed soon. 

Thank you Strapi Team.
With regards

**Comment by derrickmehaffy** [comment] 2022-01-11 22:09
> Eagerly awaiting these fixes grin



> Apparently this issue is not fixes in 4.0.4 version. Would really enjoy this to be fixed soon.
> 
> Thank you Strapi Team. With regards

It's coming, we are still working through a few small things. The PR is attached to this issue, you are welcome to try and manually apply it to your project using patch package or wait patiently :)

**Comment by Seabon** [comment] 2022-01-20 14:01
Still have this issue in v4.0.5.

**Comment by derrickmehaffy** [comment] 2022-01-20 16:40
I'm going to go ahead and lock this issue, we are aware of the problem. Some things are being discussed and worked out in the linked PR. When that PR is merged this issue should be resolved.

**Closed** 2022-01-25 12:24 UTC
Labels: issue-type: bug, severity: low, status: confirmed, source: plugin:users-permissions, version: v4
