### ISSUE TITLE
Improve admin's initial load time

### ISSUE THREAD

**Issue by aksdevac** [strapi/strapi#7439] opened 2020-08-12 11:33 UTC
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Please describe your feature request:**
Strapi main bundle size is around 6.6 MB for just viewing 'login' page on fast net it takes around 6 sec time. 
It would be great If some components can be lazy loaded & main bundle size can be reduced.

<img width="825" alt="Screenshot 2020-08-12 at 4 58 24 PM" src="https://user-images.githubusercontent.com/2557058/90010521-941bc900-dcbd-11ea-845c-ace3bcdb8d26.png">

**Comment by alexandrebodin** [comment] 2020-08-12 11:40
You are using the dev bundle. When run yarn develop it is not building with optimization. 
Just run yarn build to get the optimized build :) 


Closing the issue as this is intended. Let us know if you still think there is an issue

**Comment by aksdevac** [comment] 2020-08-12 11:50
@alexandrebodin Hi, this is running on Production server, using 'yarn build' & prod env.  & I am also using latest strapi(3.1.3), its indeed loading 6.6 MB bundle on viewing 'login' page.

**Comment by alexandrebodin** [comment] 2020-08-12 12:34
@soupette  @HichamELBSI might be wort a look

**Comment by aksdevac** [comment] 2020-08-12 13:08
with `--no-optimization` flag in fresh project main bundle size is 10.2MB & without this flag its around 6.6MB, 
If I enable gzip on server its around 2.1MB, but extracted size will still be 6.6MB.

**Comment by derrickmehaffy** [comment] 2020-08-12 16:59
Most of this from what I understand is related to the fonts being used so I'm not sure how easily we can decrease this especially since we need to use specific fonts for certain languages (Russian comes to mind).

**Comment by aksdevac** [comment] 2020-08-13 05:27
main js file has fonts? anyways we only want EN support, if we can pass option for this at build time it would be great.

**Comment by TechQuery** [comment] 2020-08-30 14:34
> Most of this from what I understand is related to the fonts being used so I'm not sure how easily we can decrease this especially since we need to use specific fonts for certain languages (Russian comes to mind).

No, Fonts have their own *show time*:
![image](https://user-images.githubusercontent.com/19969570/91661816-e60f7c00-eb10-11ea-9b93-dafaa05e5bf8.png)

**Comment by Moizsohail** [comment] 2020-09-18 17:05
Any solution?

**Comment by derrickmehaffy** [comment] 2020-09-18 17:19
@Moizsohail there is no workarounds currently

**Comment by albatrocity** [comment] 2020-10-08 20:08
This is an issue for me as well. As of 3.2.1 the request for `admin/main.chunk.js` causes a request timeout on a Heroku production environment, and server logs say it takes up to 20s to serve at times. Is this file being built when it's requested? I know Heroku isn't made for serving flat files but 20s seems crazy.

**Comment by derrickmehaffy** [comment] 2020-10-08 20:21
On an initial load if heroku has put the dyno to sleep @albatrocity that's normal, if the dyno isn't asleep than no that's not normal for Strapi or Heroku.

The file size of that file is a bit large, but not 20s large unless you have a very poor connection or are a very long distance away from the Heroku server that it's running on.

**Comment by albatrocity** [comment] 2020-10-08 20:25
@derrickmehaffy these are production-level dynos, they don't go to sleep. I'm still narrowing down the cause but it wasn't an issue on 3.1.x for me.

**Comment by derrickmehaffy** [comment] 2020-10-08 20:28
(FYI it's not being built when requested, it is statically built before the server starts)

**Comment by soupette** [comment] 2020-10-09 07:13
@albatrocity, plus with the 3.2.x the build is slightly smaller

**Comment by albatrocity** [comment] 2020-10-09 14:03
@derrickmehaffy @soupette thanks for following up. My issue was introduced in v3.2.1 and I'm finding that it isn't related to the _size_ of the admin package, but the time it takes Heroku to serve it. After looking at the 3.2.0 - 3.2.1 release diff I saw a bump of `koa-compress` for additional gzip options, so I tried disabling the gzip middleware and my issue is resolved: the admin/main chunk is delivered in an acceptable time.

I've bumped to 3.2.2 this morning and the issue persists with gzip enabled. I have some custom admin UI extensions so I'll see if they are the culprit.

I wasn't able to recreate the issue with a fresh strapi app on Heroku so I've got some untangling to do, but it's safe to say that my issue doesn't belong in this thread 😄

**Comment by derrickmehaffy** [comment] 2020-10-09 14:54
Glad to hear that @albatrocity the issue may come from the CPU required to dynamically compress the pages during the request. In that case we need to reproduce it and make sure to add a note about this.

Downside is there won't be any compression for any route (not just admin).

**Comment by albatrocity** [comment] 2020-10-09 15:17
@derrickmehaffy it's definitely related to https://github.com/koajs/compress/issues/126 and Brotli being on by defaut. If I pass `{ br: false }` as gzip options, it doesn't suffer from the slow-down. I was running node 10, so I bumped to 12 TLS and it's _slightly_ faster, but still nears to 20s range for delivering that one admin js bundle.

In short, turning Brotli off with 
```js
gzip: {
  enabled: true,
  options: {
    br: false
  }
}
```
in the middleware config resolves my issue. 

I'll try to make time to put together a codebase where you can reproduce. For now it's probably worth watching that koa-compress issue.

**Comment by derrickmehaffy** [comment] 2020-10-09 16:03
The brotli compression was just recently added, so it looks like we need to update our guide. If you are up for it, do you want to submit a PR or would you rather we (Strapi) do it?

**Comment by albatrocity** [comment] 2020-10-09 16:25
@derrickmehaffy I'd be happy to submit a PR. Which guide would make sense to update? It seems like having Brotli disabled on Heroku is going to be recommended, so maybe that recommendation belongs in the Heroku guide specifically? I'm not sure if it affects other hosting providers.

Here is a minimum reproducible repo: https://github.com/albatrocity/strapi-heroku-gzip

Enabling the `gzip` middleware without any options will use the `koa-compress` default of enabling Brotli, which seems to have really poor performance in this scenario.

**Comment by Jokcy** [comment] 2020-11-04 02:19
I tried to use webpack-bundle-analyzer see what bundled into the main.js chunk. Here is the screenshot:
<img width="1792" alt="截屏2020-11-04 上午10 14 59" src="https://user-images.githubusercontent.com/2088642/98061475-e74d8400-1e86-11eb-863d-e679dd57d38d.png">
I'm trying hard to see what can be optimized and how to, it seems bundle the whole `lodash` pkg is unnecessary, also `fontawesome`, it's too big.

**Comment by derrickmehaffy** [comment] 2020-11-04 14:26
Moment.js also, we need to migrate to something a little smaller :thinking:

**Comment by anmol5varma** [comment] 2021-01-07 08:17
@albatrocity Can you help me in enabling the gzip compression?
currently, I have a middleware.js file which looks like

```
module.exports = {
  load: {
    before: ['responseTime', 'boom', 'logger', 'cors', 'responses', 'gzip'],
    after: ['parser', 'router'],
  },
  settings: {
    gzip: {
      enabled: true,
      options: {
        br: false
      }
    }
  }
};
```

**Comment by albatrocity** [comment] 2021-01-07 15:01
@anmol5varma without testing it, that configuration looks like it would work. Are you experiencing issues?

**Comment by mahcr** [comment] 2021-03-06 21:52
Did anyone found a solution? it's insane my bundle size 9mb!

**Comment by aksdevac** [comment] 2021-03-08 05:22
@mahcr Yes checked again after your comment it has increased from `6.6 (2.1 compressed)` to `9.3 MB (2.5 compressed)`, may be with new features size is increasing & no one is paying attention to bundle size, but still I don't notice loading speed issue on fast WiFi, but if someone needs to access admin using slow/average mobile internet, it would create issue. 
may be strapi can make some features optional or can load some modules lazily.

**Comment by derrickmehaffy** [comment] 2021-03-08 16:18
We have some plans in Q2 2021 that may decrease the size a bit (currently still in design and planning, and I can't speak about the details right now).

**Comment by ccqgithub** [comment] 2021-06-04 16:20
same issue, i use webpack's `optimization` and `splitchunks` to solve the problem temporarily.  And maybe can use react's suspense to lazy load compoents!

**Comment by franjorub** [comment] 2021-06-06 18:23
I made the setup for AWS and load the login the first time takes 5 min !! is just crazy the problem is loading a chunk file. once you are logged in everything is fast and works fine

**Comment by devpascoe** [comment] 2021-09-30 08:31
No more secrets or tips yet beyond br: false for speeding up that admin js chunk?

**Comment by allanvobraun** [comment] 2021-10-09 23:35
If anyone knows of any more workarounds, let us know in this issue please!

**Comment by soupette** [comment] 2021-10-11 06:44
We are actively working on this issue with the v4, the admin build size is reduced by more than half the current size, it's around 3.5MB and it will be lighter when the migration will be completed.

**Comment by m-farahmand** [comment] 2021-10-18 12:46
I hope it will be less than 2 MB, otherwise I should think about other solution.

**Comment by soupette** [comment] 2021-11-30 09:05
It's about 2.2MB when building for production.

**Comment by alexandrebodin** [comment] 2021-11-30 10:22
> It's about 2.2MB when building for production.

**Closed** 2021-11-30 14:10 UTC
Labels: type: enhancement, source: admin

**Comment by ihor-zinchenko** [comment] 2023-09-13 20:35
> It's about 2.2MB when building for production.

package.json
`
"@strapi-community/strapi-plugin-url-alias": "^1.0.0-alpha.10",
    "@strapi/plugin-documentation": "^4.13.3",
    "@strapi/plugin-i18n": "^4.13.3",
    "@strapi/plugin-users-permissions": "^4.13.3",
    "@strapi/strapi": "^4.13.3",
`

<img width="1192" alt="image" src="https://github.com/strapi/strapi/assets/38561554/eee7d3d7-2b1b-4278-b2eb-a579e34707e0">

what can be the reason?

**Comment by leonardyhuang** [comment] 2024-03-31 16:47
I'm not 100% sure, theoretically, turning Brotli off should speed up the API response too (at least for `koa-compress v5.0.1`)?

**Comment by m-farahmand** [comment] 2024-08-18 15:37
now I'm on strapi v4.24.1 and still exist this issue and my main bundle is about 6MB, is there any workaround?
![Untitled](https://github.com/user-attachments/assets/d7616bbb-14fa-44b0-b9e5-c8d347b6df2e)
