### ISSUE TITLE
Can't create new content type in development mode

### ISSUE THREAD

**Issue by akelani** [strapi/strapi#8693] opened 2020-11-19 06:41 UTC
### Describe the bug

The Content-Types-Builder menu shows the default content types but there is no link or button for creating a new content type. I cannot create any new content types.

### Steps to reproduce the behavior

1. Run yarn develop --watch-admin
2. Go to localhost:1337/admin
3. Sign in
4. Click 'Content Types Builder'
5. see there is no option for creating or adding new content types

### Expected behavior

Display button to create content type

### Screenshots

<img width="1680" alt="Screen Shot 2020-11-18 at 10 35 02 PM" src="https://user-images.githubusercontent.com/1649303/99630649-21726600-29ef-11eb-88b3-b0619158010e.png">

<img width="1678" alt="Screen Shot 2020-11-18 at 10 35 20 PM" src="https://user-images.githubusercontent.com/1649303/99630664-26cfb080-29ef-11eb-8788-70fbb19ed187.png">

### System

- Node.js version: 14.15.1
- NPM version: 6.14.8
- Strapi version: 3.3.3
- Database: sqlite
- Operating system: Mac OS 10.15.7

### Additional context

Ran "yarn develop --watch-admin" to run server. Server is in development mode as shown in screenshot.

**Comment by derrickmehaffy** [comment] 2020-11-19 16:43
@akelani I just tested this on a fresh project and couldn't reproduce. Can you break down the steps you did to reproduce this?

**Comment by akelani** [comment] 2020-11-20 05:31
I was on Strapi 3.1.5 initially and then upgraded to 3.3.3.  Then this behavior stared.  I ended up downgrading from 3.3.3 to 3.2.5 and now I can add data again.

**Comment by derrickmehaffy** [comment] 2020-11-20 14:04
@akelani I created a v3.1.5 project spun it up using the `--watch-admin` => made a copy => upgraded => ran the --watch-admin and could use the CTB with no issue.

I think it's a local environment issue on your side but there isn't much we can do to help debug that :/

![image](https://user-images.githubusercontent.com/8593673/99808821-ab5d2480-2afe-11eb-9fd5-010d36b36a65.png)

**Comment by odididi** [comment] 2020-11-20 15:17
I had a similar issue but resolved it.

Basically my issue, was that i had customized the admin dashboard and still kept the same code after updating strapi!
So basically, in the file i updated:
- Copy the newer version of the file
- Apply my changes again
- Rebuild clean and develop

Digging a bit deeper on it, i found the issue was missing some code in my old version that was not setting the autoReload variable to true when running develop. That led to the currentEnvironment not being set to `development`, and hence the consequent issues.

**Comment by odididi** [comment] 2020-11-20 15:19
Also it might be that you're running `strapi develop` instead of `npm run develop`, thus using your global strapi, which might need to be updated?

**Comment by derrickmehaffy** [comment] 2020-11-20 16:24
@odididi that is a good point and we expressly mention this on our migration guides

https://strapi.io/documentation/v3.x/migration-guide/
https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.2.5-to-3.3.0.html

> If you are using extensions to create custom code or modifying existing code, you will need to update your code and compare your version to the new changes on the repository.
> Not updating your extensions can break your app in unexpected ways that we cannot predict.

If you have any extensions (actual extensions directory or the admin directory) you will need to compare your files to ours and make the required merges of code. It's extremely likely this could be the cause.

**Comment by andyngdz** [comment] 2020-11-21 17:11
![Screen Shot 2020-11-22 at 12 11 05 AM](https://user-images.githubusercontent.com/10527554/99883042-394c2300-2c57-11eb-9cf8-eae0a2f88db7.png)

I'm also getting the same issue. I've started a new project

```
"dependencies": {
    "strapi": "3.3.3",
    "strapi-admin": "3.3.3",
    "strapi-utils": "3.3.3",
    "strapi-plugin-content-type-builder": "3.3.3",
    "strapi-plugin-content-manager": "3.3.3",
    "strapi-plugin-users-permissions": "3.3.3",
    "strapi-plugin-email": "3.3.3",
    "strapi-plugin-upload": "3.3.3",
    "strapi-connector-bookshelf": "3.3.3",
    "knex": "<0.20.0",
    "pg": "latest"
  },
```

**Comment by chamanoS** [comment] 2021-01-04 08:07
I just ran this command : yarn develop --watch-admin... and it worked..thanks @akelani

**Comment by derrickmehaffy** [comment] 2021-01-04 14:48
Marking this issue as closed as it's likely unrelated to Strapi and is most likely a user environment issue. No new information has been given.

**Closed by derrickmehaffy** 2021-01-04 14:48 UTC
Labels: status: can't reproduce

**Comment by duc-gp** [comment] 2022-03-01 10:38
maybe this helps others having this issue, I ran `npm run build` and then it worked with `npm run develop`

**Comment by P0SEID0N** [comment] 2022-06-30 18:24
Worth mentioning when you start a new community project self hosted the CLI documentation tells you to run `npm run develop ` the problem with that is if you only run the develop it seems as though the /admin/content-type-builder isnt built and therefore will not work. As @duc-gp mentioned you need to `npm run build` first and then `npm run develop` worked for me as well.

**Comment by parthmern** [comment] 2023-10-17 18:41
💚 Working - `yarn develop --watch-admin`  or  `npm run develop --watch-admin`
