### ISSUE TITLE
[change-access-url]: LeftMenuLinkContent component issue

### ISSUE THREAD

**Issue by gondar00** [strapi/strapi#8873] opened 2020-12-11 12:57 UTC
If we set a custom URL as mentioned in [here](https://strapi.io/documentation/v3.x/admin-panel/customization.html#change-access-url) 

getting `cannot .replace of undefined` error due to [this](https://github.com/strapi/strapi/blob/6b5954009138f7100a3ec13fcb0d57cbea1b225a/packages/strapi-admin/admin/src/components/LeftMenu/LeftMenuLink/LeftMenuLinkContent.js#L28) line since `/admin` route doesn't exist anymore

**Comment by derrickmehaffy** [comment] 2020-12-22 21:21
> This is a templated message

Hello, please follow the [issue template](https://raw.githubusercontent.com/strapi/strapi/master/.github/ISSUE_TEMPLATE/BUG_REPORT.md).

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines and properly fill out the template. You can see the template guidelines for bug reports [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

Please update the issue with the template and we can reopen this report.

Thank you.

**Comment by derrickmehaffy** [comment] 2020-12-22 21:21
Re-opening per @soupette's comment, in the future please follow our templates.

**Comment by soupette** [comment] 2020-12-24 11:11
I am not able to reproduce the issue. Did you change the config file of the admin package?

**Comment by derrickmehaffy** [comment] 2020-12-28 21:01
Marking as closed until user provides more information.

**Closed by derrickmehaffy** 2020-12-28 21:01 UTC
Labels: severity: high, source: admin, status: confirmed

**Comment by gondar00** [comment] 2021-01-11 12:49
@soupette actually in config line I had added only 1 line - 

```
export const SHOW_TUTORIALS = false;
```

When I added all the mentioned config variables the issue disappeared - 

```
export const LOGIN_LOGO = null;
export const SHOW_TUTORIALS = false;
export const SETTINGS_BASE_URL = '/settings';
export const STRAPI_UPDATE_NOTIF = false;
```

**Comment by gondar00** [comment] 2021-01-11 12:52
But the highlight doesn't work on the sidebar item if I change the [access url](https://strapi.io/documentation/v3.x/admin-panel/customization.html#change-access-url) 

 [mostly due to this line here](https://github.com/strapi/strapi/blob/6b5954009138f7100a3ec13fcb0d57cbea1b225a/packages/strapi-admin/admin/src/components/LeftMenu/LeftMenuLink/LeftMenuLinkContent.js#L28)
 
 And ideally it should have thrown me the same error saying `cannot .replace of undefined` but that is failing silently, 

can you please guide me where I can place a `console.log` to catch such silent errors in the application?
