### ISSUE TITLE
Can't update API permission with database which has a large amout of users with same role

### ISSUE THREAD

**Issue by hyperion0201** [strapi/strapi#6317] opened 2020-05-22 10:22 UTC
**Describe the bug**
Can't update API permission with db has a large amount of users (~10k users with same role)
**Steps to reproduce the behavior**

1. Go to *admin dashboard*
2. Click on *Roles and Permissions*
3. Click on *Authenticated* (for example)
4. Check/uncheck any api controller
5. Click *Save*

**Expected behavior**
Update the API permission for role.

**System**

- Node.js version: 12.16.2 
- NPM version: 6.14.4
- Strapi version: lastest (3.0.0-beta.20.3)
- Database: MongoDB
- Operating system: Ubuntu 20.04 

**Additional context**
This problem occured because the web browser must render all of users by roles (make browser laggy too), after click 'Save', it sent all of users as request payload to server. I check log and found the 413 code. Maybe the request body was too large, right? Idk why Strapi need to send all users back to server when update a role/permission.

**Comment by conghai** [comment] 2020-05-23 08:00
I got the same issue when the system had nearly **4000 users.**

When adding Permissions for Authenticated role, the system was loaded all users and post it back to the server => **Request body was too large**

For now NO way is to manually directly edit in Database.

**It should split into two functions:**
```
1 - Set permissions for role
2 - Add the user to role
```

**Comment by derrickmehaffy** [comment] 2020-05-23 09:59
Pinging @alexandrebodin and @petersg83 about this.

**Comment by alexandrebodin** [comment] 2020-05-27 09:13
Hi, we are aware of this, right now we don't have enough hands on deck to help so if you want to work on a PR we can discuss the best approach :)

**Comment by lauriejim** [comment] 2020-05-28 09:51
This issue is a duplicate of this one - https://github.com/strapi/strapi/issues/2992

**Closed by lauriejim** 2020-05-28 09:51 UTC
