### ISSUE TITLE
Warning Accessing non-existent property MongoError

### ISSUE THREAD

**Issue by dalbitresb12** [strapi/strapi#9530] opened 2021-02-26 06:43 UTC
### Describe the bug

This warning appears when making a POST request to the `/auth/local` endpoint with valid credentials:

```
(node:29573) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

I used the following command to get stack trace of this warning: `NODE_OPTIONS="--trace-warnings" yarn develop`

```
(node:29665) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Object.<anonymous> ([redacted]/strapi-test-sqlite-app/node_modules/mongodb/lib/operations/operation.js:4:38)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> ([redacted]/strapi-test-sqlite-app/node_modules/mongodb/lib/operations/execute_operation.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> ([redacted]/strapi-test-sqlite-app/node_modules/mongodb/lib/core/cursor.js:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

### Steps to reproduce the behavior

1. Create a clean Strapi app with SQLite or MySQL
2. Create a test user using the admin panel
3. Send POST request to `/auth/local/` with the test user credentials.
4. See warning in the console

### Expected behavior

No warning should show up.

### System

- Node.js version: v14.16.0 (lts/fermium)
- NPM version: v6.14.11
- Strapi version: v3.5.1
- Database: SQLite and MySQL Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
- Operating system: Ubuntu 20.04 in WSL2 on Windows 10 2004

### Additional context

Something to note is that this warning doesn't appear when using Node v12 (tested using v12.21.0), but it does in Node v14 (tested using v14.16.0).

#6526 is similar to this error but with different properties. Also, that issue was closed when Node v14 still wasn't LTS, but v14 is now LTS.

Also, it is important to know that **I'm not even using MongoDB**. The project in which I tested this is a clean project created with `create-strapi-app --quickstart` using SQLite. This warning initially showed up in another project I have using MySQL, but there I have modified parts of the users-permissions extension so I thought it could be related to that, but it doesn't seem so.

Finally, I've noticed that this warning only shows up the first time this endpoint is used after starting the server (and it also makes the request slower: for example, the request with the warning took 625 ms, while the same request done again took 129 ms). Other times won't make the warning appear.

**Comment by aksdevac** [comment] 2021-02-26 07:24
this is very strange if you are not using MongoDB it should not have mongodb folder inside `node_modules`.

**Comment by dalbitresb12** [comment] 2021-02-26 07:31
I don't know how, but it does get into my `node_modules` folder. This is the `package.json` file that got created with the quickstart project:

```json
{
  "name": "strapi-test-sqlite-app",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "strapi": "3.5.1",
    "strapi-admin": "3.5.1",
    "strapi-utils": "3.5.1",
    "strapi-plugin-content-type-builder": "3.5.1",
    "strapi-plugin-content-manager": "3.5.1",
    "strapi-plugin-users-permissions": "3.5.1",
    "strapi-plugin-email": "3.5.1",
    "strapi-plugin-upload": "3.5.1",
    "strapi-connector-bookshelf": "3.5.1",
    "knex": "<0.20.0",
    "sqlite3": "5.0.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "05342b31-7515-415e-bf65-92f3f22e267e"
  },
  "engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": "^6.0.0"
  },
  "license": "MIT"
}
```

**Comment by derrickmehaffy** [comment] 2021-02-26 20:28
I was not able to reproduce this on 4 different environments:

- Windows (native)
- WSL2
- Linux Mint 20 (Ubuntu 20.04)
- MacOS Catalina

**Comment by dalbitresb12** [comment] 2021-02-27 00:57
@derrickmehaffy That's strange. I've managed to reproduce this error in a clean VM from Google Cloud. This are all the steps I've done to reproduce it (I'll detail everything, even if obvious, in case something helps):

1. I created a VM in Google Cloud with the Ubuntu 20.04 image (preemptible so that it doesn't cost too much). Any machine type should work, but I chose `e2-medium (2 vCPUs, 4 GB memory)` with 10GB of SSD.
2. I opened an SSH session with the server and installed [NVM](https://github.com/nvm-sh/nvm) with this command: `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash` and then restarted the SSH session to load NVM.
3. Then I installed Node v14 with this command: `nvm install lts/fermium` (it installed v14.16.0).
4. Then I installed Yarn: `npm install -g yarn` (output of `yarn --version`: 1.22.10).
5. Then I created a quickstart Strapi app: `yarn create strapi-app strapi-test-app --quickstart`.
6. I didn't even opened the admin panel to register the first administrator, I just POSTed to `http://localhost:1337/auth/local/register` directly with the following body:

    ```json
    {
      "username": "user",
      "email": "user@example.com",
      "password": "somesecurepass"
    }
    ```

7. The initial warning appeared:
    ```
    (node:1800) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
    (Use `node --trace-warnings ...` to show where the warning was created)
    ```
8. Then I closed the server (just did <kbd>Ctrl</kbd>+<kbd>C</kbd>) and then started it again (`cd strapi-test-app && yarn develop`).
9. POSTed to the login endpoint (`http://localhost:1337/auth/local`) with the following body:

    ```
    {
      "identifier": "user@example.com",
      "password": "somesecurepass"
    }
    ```

10. The same warning appeared:
    ```
    (node:2142) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
    (Use `node --trace-warnings ...` to show where the warning was created)
    ```

Just in case it helps, I listed the packages that matched `mongo` with yarn. This is the output:

```bash
$ yarn list --pattern mongo
yarn list v1.22.10
├─ @types/mongodb@3.6.8
├─ mongodb@3.6.4
├─ mongoose-legacy-pluralize@1.0.2
└─ mongoose@5.11.18
Done in 1.21s.
```

Also, when making the POST requests I used the [Postman app for Windows](https://www.postman.com/downloads/) (Version 8.0.6) and because the server was in Google Cloud, I had to do port forwarding with SSH with the following command: `ssh -L 1337:127.0.0.1:1337 <ip of server>`. This last part isn't necessary if testing locally (I couldn't test locally with a clean machine).

Finally, I'll attach some screenshots of the Terminal in case there's something I missed:

![image](https://user-images.githubusercontent.com/7624090/109369830-150e6c80-786c-11eb-9c4d-7fb4aa842277.png)

![image](https://user-images.githubusercontent.com/7624090/109369850-26f00f80-786c-11eb-993e-8c0fd8a59f96.png)

(This time I accidentally made a GET request first instead of a POST request. That's why there's two requests to `/auth/local/register`. But GET requests don't make the warning appear, I've only seen this with POST requests).

![image](https://user-images.githubusercontent.com/7624090/109369859-31aaa480-786c-11eb-921e-cd9eac6dbca2.png)

(This one is after I restarted the server and POSTed to `/auth/local` with the credentials used during the previous registration).

![image](https://user-images.githubusercontent.com/7624090/109369873-3a9b7600-786c-11eb-8c09-f2d6ecf0ca14.png)

---

I hope something here helps in reproducing this warning. 😄

**Comment by aksdevac** [comment] 2021-02-27 05:36
Hi, I also tired `yarn create strapi-app strapi-test-app --quickstart` could not regenerate this completely on Mac OS 11.2.1, but my `node_modules` has mongodb, mongoose folder, found that it is coming from `strapi-plugin-users-permissions -> koa2-ratelimit -> mongoose "^5.5.13"` , so this warning might be related to this package. Also it seems `koa2-ratelimit` is not maintained.

**Comment by dalbitresb12** [comment] 2021-02-27 05:40
I really don't have any Apple devices so I can't test on Mac OS, so I don't know if this happens there. But at least in Ubuntu this warning appears.

**Comment by aksdevac** [comment] 2021-02-27 05:48
@dalbitresb12 Hi, it looks like I made a mistake, I tested on wrong server url,
Now  I can regenerate this on Mac OS with your steps,
just run `yarn create strapi-app strapi-test-app --quickstart` & then make POST request on `/auth/local/register` route using Postman, & see following warning:

> (node:13885) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[2021-02-27T05:45:28.711Z] debug POST /auth/local/register (658 ms) 200

**Comment by dalbitresb12** [comment] 2021-02-27 05:52
Thank you for helping to recreate this warning, @aksdevac! I hope the same steps help @derrickmehaffy in reproducing it as well. (I was about to try to make a VM for Mac OS on Windows 😆)

**Comment by dalbitresb12** [comment] 2021-02-27 06:03
It does seem like `koa2-ratelimit` is the one installing dependencies for mongo, even when not using MongoDB: ysocorp/koa2-ratelimit#20.

**Comment by derrickmehaffy** [comment] 2021-03-01 22:54
@dalbitresb12 it's used by default on the users-permissions plugin: https://github.com/strapi/strapi/blob/65bc2d04d3c41e37f410d96248a8bd828b8e972a/packages/strapi-plugin-users-permissions/config/policies/rateLimit.js#L5

**Comment by dalbitresb12** [comment] 2021-03-01 23:16
> even when not using it

@derrickmehaffy What I meant with this is that even when I'm not using MongoDB with Strapi (because I'm using SQLite or MySQL), `koa2-ratelimit` still installs the dependencies needed for Mongo.

**Comment by derrickmehaffy** [comment] 2021-03-01 23:35
It's because it has the option to use another source to store the information instead of just node-memory. I'm guessing the issue is simply the mongoose version that depends has is massively out of date.

I will have to talk to @alexandrebodin to see what we can do about it.

**Comment by derrickmehaffy** [comment] 2021-11-30 14:28
MongoDB is not supported anymore in Strapi v4, marking as closed

**Closed by derrickmehaffy** 2021-11-30 14:28 UTC
Labels: type: bug, severity: low, status: confirmed, source: external
