### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by reskwer** [strapi/strapi#1535] opened 2018-07-07 02:32 UTC
**Informations**
- **Node.js version**: 9.11.1
- **npm version**: 5.6
- **Strapi version**: afla 12.6
- **Database**: mongo
- **Operating system**: windows 10 LTSB

**What is the current behavior?**
tried to upload an image
![image](https://user-images.githubusercontent.com/8849299/42405921-b38eaa9c-81a6-11e8-9d03-98a633d914bf.png)

then I decided to update the page and flew the language file
![image](https://user-images.githubusercontent.com/8849299/42405946-fae60fb6-81a6-11e8-9777-10348a67b2f1.png)

text translate "google translate" sorry :)

**Steps to reproduce the problem**

**What is the expected behavior?**

**Suggested solutions**

**Comment by reskwer** [comment] 2018-07-07 02:43
Guys, want to STRAP on the combat project to try, your product is really loved, even premium pay - but very humid, very unstable, 1 day several of the bugs we catch. Come on guys, thank you :)))

typeof $strapi // 'bug'

**Comment by derrickmehaffy** [comment] 2018-07-07 08:32
@reskwer I don't quite understand the bug your having.

**Comment by reskwer** [comment] 2018-07-07 11:14
image not loaded

**Comment by lauriejim** [comment] 2018-07-08 09:31
Hello @reskwer , please follow the issue template so we can get a better understanding about the origin of your bug.

One bug per opened issue. And please check your own issue, it look duplicate of this: https://github.com/strapi/strapi/issues/1518

Thank you.

**Closed by lauriejim** 2018-07-08 09:31 UTC
