### ISSUE TITLE
Clone functionality does not work for a custom database schema

### ISSUE THREAD

**Issue by EsterkaM** [strapi/strapi#19429] opened 2024-02-05 11:02 UTC
### Required System information

- Node.js version: **v18.12.0**
- NPM version: **8.19.2**
- Strapi version: **4.19.1**
- Database: **PostgreSQL**
- Operating system: **macOS Sonoma 14.0 (M1 Max)** - **darwin-arm64**
- Is your project Javascript or Typescript: **Typescript**

### Describe the bug

**Clone** functionality does not work for the entity with a relation to the other entity. [For custom database schema].

### Steps to reproduce the behavior

1. Run strapi instance od **cms** database schema. (It's important!) 
2. Add 2 entities (`draft & publish: false`):
- **City** with the `required` `unique` **name** attribute
- **Citizen** with the `required`, `unique` **name** attribute and another attribute called **city** with this relation: `(City has many Citizens)`.
3. Fill in this base data:
- City (name: **Prague**)
- Citizen (name: **Michal**, city: **City.Prague**)
4. Try to clone the Michal citizen and you will see an error
<img width="592" alt="image" src="https://github.com/strapi/strapi/assets/159007025/0a18277b-4b66-479f-a88e-dc261f93a168">

and when you check the server log you can see this error:

```
update "citizens_city_links" as "t1" set "citizen_order" = (select max(citizen_order) + 1 from "citizens_city_links" as "t2" 
where t2.city_id = t1.city_id) where "t1"."citizen_id" = $1 - relation "citizens_city_links" does not exist
error: update "citizens_city_links" as "t1" set "citizen_order" = (select max(citizen_order) + 1 from "citizens_city_links" as "t2"
where t2.city_id = t1.city_id) where "t1"."citizen_id" = $1 - relation "citizens_city_links" does not exist
```

### Expected behaviour

Strapi should clone the entity with the reference.

**Comment by ueda000** [comment] 2024-03-02 02:42
I also have an environment with a custom database schema and was able to reproduce the issue.
Could you reopen the issue?

I've submitted a PR with a fix. https://github.com/strapi/strapi/pull/19657

**Comment by alexandrebodin** [comment] 2024-07-01 12:09
Looks like related to this issue too https://github.com/strapi/strapi/issues/20509

**Comment by alexandrebodin** [comment] 2024-07-16 08:37
Hi, it looks like this was fixed in https://github.com/strapi/strapi/pull/20531 and released in the most recent version of v4. 

@EsterkaM Can you test this again and let us know 🙏 ?

**Closed by alexandrebodin** 2024-07-16 08:37 UTC
