### ISSUE TITLE
allows table named rows in mysql

### ISSUE THREAD

**Issue by salientknight** [strapi/strapi#3759] opened 2019-08-10 03:51 UTC
I crated a content type called row and strapi created a table called rows which is a keyword in mysql  -- so the table is not addressable, and cannot be droped 

**Steps to reproduce the behavior**

1. create new content type
2. name the content type row

**Expected behavior**
strapi should prevent tables with this name while allowing content types with this name

![Screenshot 2019-08-09 23 50 39](https://user-images.githubusercontent.com/40220684/62817208-983c6600-bb00-11e9-8fb4-02b6a721f841.png)

**Comment by lauriejim** [comment] 2019-08-12 11:04
Helo! I just tried and it works well.
<img width="257" alt="Screenshot 2019-08-12 at 1 03 49 PM" src="https://user-images.githubusercontent.com/5716596/62860799-ae654480-bd01-11e9-8b4b-470ad15cb4dc.png">

**Comment by salientknight** [comment] 2019-08-12 16:43
Now try running desc rows

You should not be able to create a table called rows.

**Comment by lauriejim** [comment] 2019-08-13 11:43
What do you mean by `running decs rows` ?

**Comment by derrickmehaffy** [comment] 2019-08-13 12:02
@salientknight looks fine:

![image](https://user-images.githubusercontent.com/8593673/62940068-8e786400-bd87-11e9-89c6-250ed86e0991.png)

marking as closed as this is not a bug and will work fine as long as you are using proper escapes.

**Closed by derrickmehaffy** 2019-08-13 12:02 UTC
Labels: type: help wanted 🤷‍♂️
