### ISSUE TITLE
GraphQL upload not working

### ISSUE THREAD

**Issue by pauldariye** [strapi/strapi#2558] opened 2018-12-28 23:06 UTC
**Informations**
- **Node.js version**: v11.0.0 
- **NPM version**: 6.5.0

- **Strapi version**:3.0.0-alpha.17 
- **Database**: 
- **Operating system**: MacOS Mojave
- **(Optional) Link to your Project**: 

**What is the current behavior?**
I'm unable to upload upload a file using apollo and unsure what the issue is.

**Steps to reproduce the problem**

Using
 - [apollo-client-upload](https://github.com/jaydenseric/apollo-upload-client)
 - [cloudinary provider](https://www.npmjs.com/package/strapi-upload-cloudinary)

And following the [upload example](https://github.com/strapi/strapi-examples/blob/f20733121ec960136ae9487e1ceee092cccbb79d/apollo-upload-graphql/app/components/upload-file.js)

Apollo-Link Config

```
const uploadLink = createUploadLink({
  uri: GRAPHQL_URI,
})
```
Mutation query
```
UPLOAD_FILE = gql`
  mutation UploadFile($file: Upload!, $ref: String!, $refId: String, $field: String) {
    upload(file: $file, ref: $ref, refId: $refId, field: $field) {
      _id
      name
      mime
      url
      __typename
    }
  }
`
```
Apollo Mutation component
```
<Mutation
  mutation={UPLOAD_FILE}>
  {(uploadFile, res) => {
    console.log(res)
    return (
      <Fragment>
        <Avatar src={community.image ? community.image.url : '/static/logo.png'} width={105} height={105} />
        <IconButton name="edit" size={16} color="white" fill="white" />
        <FileInput
          type="file"
          name="file"
          onChange={({ target: { validity, files: [file] }}) => {
            console.log(file)
            validity.valid && uploadFile({ 
              variables: { file, ref: `UploadFile`, refId: id, field: 'image' }
            })
          }}/>
      </Fragment>
  )}}
</Mutation>
```

<img width="1310" alt="screen shot 2018-12-28 at 17 48 35" src="https://user-images.githubusercontent.com/3650761/50530422-41cb6b80-0acb-11e9-9b1e-09ed2bfd5403.png">

<img width="783" alt="screen shot 2018-12-28 at 18 05 52" src="https://user-images.githubusercontent.com/3650761/50530427-47c14c80-0acb-11e9-8afb-93f16e2eca24.png">

**Comment by lauriejim** [comment] 2019-01-03 10:12
@pauldariye did you try without GraphQL? By using REST route to upload your file ?
Just to know if it come from GraphQL or not.

**Comment by tombunn** [comment] 2019-01-06 10:01
@lauriejim I have a very similar issue and errors with this trying to upload any files using the GraphQL plugin with `apollo-client-upload`. There is an error message that comes back from the node server and this is why @pauldariye might be the CORS issue i think:

```[ { [BadRequestError: Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).]
    message: 'Missing multipart field ‘operations’ (https://github.com/jaydenseric/graphql-multipart-request-spec).',
    locations: undefined,
    path: undefined,
    extensions: { code: 'INTERNAL_SERVER_ERROR' } },
  headers: { 'Access-Control-Allow-Origin': 'http://localhost:3000',
    vary: 'Origin' } ]

  Error: Cannot wrap non-Error object
      at Object.exports.assert (/usr/local/lib/node_modules/strapi/node_modules/hoek/lib/index.js:740:11)
      at Object.exports.wrap (/usr/local/lib/node_modules/strapi/node_modules/boom/lib/index.js:95:10)
      at strapi.app.use (/usr/local/lib/node_modules/strapi/lib/middlewares/boom/index.js:35:20)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
This is using the following mutation:

```
mutation($logo: Upload!) {
      upload(file: $logo) {
        id
      }
    }
```

If I try without using `apollo-client-upload` the mutation will return a success response but it will return null for the id ( or anything else) and no file is added. The format of the file is correct I think as there are no validation errors from GraphQL.

Here is the client error:

<img width="761" alt="error" src="https://user-images.githubusercontent.com/7679976/50734576-fedb5900-1198-11e9-8208-6b881e90475e.png">

Any advice would be appreciated. Possibly i'm missing something..

**Comment by lauriejim** [comment] 2019-01-06 12:19
Okay look strange!
And it works for other mutation/queries ?

I actually don't have time to investigate on this issue. Will appreciate is the community can do something to help us.

**Comment by tombunn** [comment] 2019-01-07 13:02
@lauriejim I can confirm other mutations and queries work fine under the same conditions. I have also tested with the example in the [strapi-examples](https://github.com/strapi/strapi-examples/tree/master/apollo-upload-graphql) repo which I imagine did work at some point. All types of upload fail, not just a single file with the same error message.

I tested on both alpha version 13 and 18 and the result is the same regardless.

**Comment by lauriejim** [comment] 2019-01-07 15:08
Okay thank you for the clarification.

**Comment by pauldariye** [comment] 2019-01-10 05:19
<img width="1269" alt="screen_shot_2019-01-10_at_00_11_39" src="https://user-images.githubusercontent.com/3650761/50947606-0aff3900-146d-11e9-8056-b70bb016b977.png">

Hey @lauriejim, I gave the rest api a try but still getting the same error.

Here's my code:

```javascript
...
const form = new FormData()
form.append('ref', 'file')
form.append('field', 'avatar')
form.append('refId', id)
form.append('file', file)

const endpoint = `${process.env.API_URL}/upload`
const response = await fetch(endpoint, {
  method: 'POST',
  body: form
})
...
```

Could you share the server/security config for a strapi instance you have in production that uses a provider like cloudinary or aws?

**Comment by lauriejim** [comment] 2019-01-11 14:19
403 is caused by restricted access to your API I think.

**Comment by pauldariye** [comment] 2019-01-11 14:32
hey @lauriejim, you're right. I'm unsure what the right production config is to avoid this for the API. Are you able to share an example production server and security configuration?

**Comment by tombunn** [comment] 2019-01-11 15:35
@pauldariye Your header with your Bearer token is missing in your REST example so unless the upload endpoint permissions are public it should fail I think? I did have a working example with REST that uses axios which you might want to adapt which you can find [here](https://github.com/strapi/strapi/issues/1919#issuecomment-420400750).

**Comment by pauldariye** [comment] 2019-01-12 10:07
Thanks @tombunn, I'll give this a try.

**Comment by pauldariye** [comment] 2019-01-15 04:15
@lauriejim, the error seems to be coming from [strapi-hook-mongoose#L163](https://github.com/strapi/strapi/blob/2b4ad0009555d56000b4a1ad0be3dd7340e819fa/packages/strapi-hook-mongoose/lib/relations.js#L163). I believe the `users-permissions_user` model is missing the globalId.

I'm not too familiar with the strapi codebase but I'm happy to work on a PR if someone's able to point me in the right direction.

**Comment by Aurelsicoko** [comment] 2019-01-24 13:20
The `globalId` are generated here (see https://github.com/strapi/strapi/blob/master/packages/strapi/lib/core/configurations.js#L196).

The real issue seems to come from this line: https://github.com/strapi/strapi/blob/2b4ad0009555d56000b4a1ad0be3dd7340e819fa/packages/strapi-hook-mongoose/lib/relations.js#L163

Especially the `_.toLower(obj.ref)`... You should take a look at the value of `obj.ref`.

**Comment by rosdanys** [comment] 2019-02-13 14:15
some solution to this problem globalId

**Comment by rosdanys** [comment] 2019-02-13 14:16
I have the same error, and I can not find any solution

**Comment by nightire** [comment] 2019-04-25 09:31
I'm facing the same problem and it just likes what @tombunn describes before. I can confirm that other mutations/queries are both fine, and REST upload is OK as well, the only thing can not work is the upload mutation.

I've tried all I can to figure out what the root cause but got no lucky, [here](https://github.com/jaydenseric/graphql-upload/issues/141) is what I can find the best currently.

**Comment by diogopalhais** [comment] 2019-07-23 12:33
This module can help with cors `import 'cross-fetch/polyfill';`
But graphql upload file currently dont work.

**Comment by derrickmehaffy** [comment] 2020-01-03 12:02
Can any of you confirm if this is still valid on the latest beta? (beta.18.3)

**Comment by lauriejim** [comment] 2020-01-06 14:28
Still have an issue.

**Comment by alexandrebodin** [comment] 2020-01-23 20:51
Hi. I'm pretty sure this issue is fixed now.

You can look at this example on how to use the upload mutation. The multipleUpload mutation is the same but with an array ;)

https://gist.github.com/alexandrebodin/4f658155290360325ff1c96c0be22b94

**Comment by alexandrebodin** [comment] 2020-03-30 13:51
Closing this issue as we have shared examples on how to achieve graphql upload.

**Closed by alexandrebodin** 2020-03-30 13:51 UTC
Labels: priority: medium, source: plugin:graphql, status: confirmed, type: bug
