### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length') after upgrade to 4.20.3

### ISSUE THREAD

**Issue by vsamofal** [strapi/strapi#19660] opened 2024-03-04 00:27 UTC
### Required System information

STRAPI_ENFORCE_SOURCEMAPS=true in your .env --> (sorry I tried it, but it's not working)

- Node.js version: v18.14.2
- NPM version: 9.5.0
- Strapi version: 4.20.3
- Database: postgres
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: js

### Describe the bug

After to upgrade to latest version, frontend is failing with exception on reading a length property, on one particular collection, and lead to white screen in both dev and prod modes. Refreshing the page helps, and it loading entity and allows me to add/edit and do everything that I want. But once I go to another collection and moving back to this entity - white screen again. Refresh and it's working just fine. 

If I'm switching menu and getting back to content manager, I can open this page fine, so the problem appears only when I'm switching between collections. 

If I'm switching to single types, I can back to collection just fine as well. So again the problem appears only 

### Expected behavior

Switching between collections should work fine 

### Code snippets

Sorry for this... but I can't make source map works

```js
main.0f63a8e2.js:805 TypeError: Cannot read properties of undefined (reading 'length')
```

Error happens here, f is undefined
![image](https://github.com/strapi/strapi/assets/27850115/eb7878ea-2945-434b-9d36-035a941826ab)

```json
field definition

  "faq": {
      "displayName": "faq",
      "type": "component",
      "repeatable": true,
      "component": "general.faq"
    }
```

but when I'm refreshing the page, this field is there, seems like some async processing happen: 

![image](https://github.com/strapi/strapi/assets/27850115/b7fce1d1-7561-4d54-9fc9-144f9ce5e9a2)

hopefully it helpful and enough, if not let me know what else to share

**Comment by brechtpallemans** [comment] 2024-03-07 13:26
Same issue here, I'm on version 4.20.2

**Comment by coderdix24** [comment] 2024-03-19 15:15
same issue

**Comment by vsamofal** [comment] 2024-03-27 00:59
4.21.0 still here

**Comment by vsamofal** [comment] 2024-03-27 01:02
Found that it happen also with a backend error, where limit passed to the query is undefined 
![image](https://github.com/strapi/strapi/assets/27850115/3041e6ab-0c84-45b6-adac-d5a9082a9c83)

**Comment by ioanaasurdu** [comment] 2024-04-05 09:19
Any updates on this?

**Comment by anurodhsahu** [comment] 2024-04-08 12:13
I was also facing the same issue. Deleting and re-creating the collection worked for me.

**Comment by anil1712** [comment] 2024-04-08 18:27
Same issue, any solution for this?

**Comment by topolar** [comment] 2024-04-08 20:33
same issue :-(

**Comment by anil1712** [comment] 2024-04-10 07:39
will it resolve if I downgrade the version?

**Comment by magikarp28** [comment] 2024-04-10 07:44
> will it resolve if I downgrade the version?

Yes, this was a critical issue for me so I had to downgrade. I'm currently on strapi version 4.16.2 and the issue is not present.

**Comment by dennism501** [comment] 2024-04-19 11:02
Internal TID: 6529

**Comment by alexandrebodin** [comment] 2024-04-22 07:07
Hello, 

@vsamofal can you share what version you were upgrading from so we can try to reproduce ? we can't reproduce by just using the v4.20.x version as of now.

Something you can test (locally at 1st and with non important data ⚠️) is to clear the `plugin_content_manager_xxx` keys in your `strapi_core_store_settings` table to see if it's a data inconsistency.

Also this might have been fixed in more recent version of Strapi, have you tried upgrading to latest since then ?

**Comment by Bobivankenobi** [comment] 2024-04-22 19:05
@alexandrebodin I'm facing this error for latest version of strapi `4.23.1`.
I'm also happy to jump on call with you if you want, I think bug is related with using of repeatable component.
https://github.com/strapi/strapi/assets/58746326/2746f9f3-22c1-4996-b0b3-c1fb3ef85842

**Comment by Bobivankenobi** [comment] 2024-04-22 19:09
@alexandrebodin Question collection type.

<img width="1450" alt="Screenshot 2024-04-22 at 21 06 40" src="https://github.com/strapi/strapi/assets/58746326/7491f1dc-0ac1-42f6-97f6-0d29679fc7c3">

**Comment by vsamofal** [comment] 2024-04-22 22:48
I was on 4.16.1, and quite a similar situation as @Bobivankenobi has, I do have a repeatable component in my collection type as well 

![image](https://github.com/strapi/strapi/assets/27850115/7b24423d-46f0-4023-8dc2-05e7339cd477)

**Comment by alexandrebodin** [comment] 2024-04-23 11:49
Thanks for the details 🙌  I'll dig into it later today

**Comment by alexandrebodin** [comment] 2024-04-23 14:00
ℹ️  The fix will be released tomorrow :)

**Closed by alexandrebodin** 2024-04-23 14:00 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:admin, flag: EE, version: 4

**Comment by Bobivankenobi** [comment] 2024-04-23 14:59
> ℹ️ The fix will be released tomorrow :)

Awesome @alexandrebodin Thank you.
