### ISSUE TITLE
Media Library List View navigation issues

### ISSUE THREAD

**Issue by mikenavi** [strapi/strapi#17560] opened 2023-08-03 11:32 UTC
## Bug report

Media Library folders not accessible in list view in root folder.
Non root folders navigate to root folder as well.

### Required System information

- Node.js version: 16.20.1
- NPM version: 8.19.4
- Strapi version: 4.12.0
- Database: PG-14
- Operating system: Ubuntu
- Is your project Javascript or Typescript: TS

### Steps to reproduce the behavior

1. Go to Media Library
2. Create any folder
3. Activate List View
4. Click on folder
5. Nothing happens **<-- (Bug)**
6. Switch to grid view
7. Navigate to folder
8. Create subfolder
9. Switch to list view
10. Click on subfolder
11. Instead of content, you get to the root folder **<-- (Bug)**

### Expected behavior

Navigate to folder content.

### Screenshots

![screen](https://github.com/strapi/strapi/assets/4928270/fe4d60f7-da3f-48f2-98d0-220360974847)

**Comment by noobCode-69** [comment] 2023-08-03 17:50
Hey @mikenavi  I think this issue is related to this issue `Folder Links Not Clickable In List View` #17564
I have created a PR , that PR will solve both the bug 
1. Bug around navigation in List view
2. Bug around navigating to subfolder in List view

**Comment by mikenavi** [comment] 2023-08-03 18:21
Hi @noobCode-69  I think it is definitely the same issue, TY

**Comment by kasonde** [comment] 2023-08-04 13:55
Closed as duplicate of #17564 (since the PR is related to that issue)

**Closed by kasonde** 2023-08-04 13:55 UTC
Labels: status: duplicate

**Comment by noobCode-69** [comment] 2023-08-05 09:15
Hey @kasonde  I have solved this isssue and made a PR can you please review that PR  https://github.com/strapi/strapi/issues/17564
