### ISSUE TITLE
Strapi 5 beta breaks on npm run build

### ISSUE THREAD

**Issue by abhishek1020N** [strapi/strapi#19928] opened 2024-03-26 10:49 UTC
### Required System information

- Node.js version: 20.10.0
- NPM version: 10.2.3
- Strapi version: 5.0.0-beta.0
- Database: sqllite
- Operating system: windows 11
- Is your project Javascript or Typescript: js

### Describe the bug

 Error: Could not load js config file D:\Code\strapi_5_beta\node_modules\@strapi\content-releases\strapi-server.js: Package subpath './dist/utils/ee' is not defined by "exports" in    │
│   D:\Code\strapi_5_beta\node_modules\@strapi\strapi\package.json                                                                                                                         │
│   at loadJsFile (D:\Code\strapi_5_beta\node_modules\@strapi\core\dist\utils\load-config-file.js:18:13)                                                                                   │
│   at Module.loadConfigFile (D:\Code\strapi_5_beta\node_modules\@strapi\core\dist\utils\load-config-file.js:37:14)                                                                        │
│   at loadPlugins (D:\Code\strapi_5_beta\node_modules\@strapi\core\dist\loaders\plugins\index.js:91:41)                                                                                   │
│   at async Promise.all (index 3)                                                                                                                                                         │
│   at async Module.loadApplicationContext (D:\Code\strapi_5_beta\node_modules\@strapi\core\dist\loaders\index.js:13:3)                                                                    │
│   at async Strapi.register (D:\Code\strapi_5_beta\node_modules\@strapi\core\dist\Strapi.js:344:5)                                                                                        │
│   at async Strapi.load (D:\Code\strapi_5_beta\node_modules\@strapi\core\dist\Strapi.js:415:5)                                                                                            │
│   at async Module.develop (D:\Code\strapi_5_beta\node_modules\@strapi\strapi\dist\node\develop.js:177:28)                                                                                │
│   at async action (D:\Code\strapi_5_beta\node_modules\@strapi\strapi\dist\cli\commands\develop.js:18:5)                                                                                  │
│   at async Command.parseAsync (D:\Code\strapi_5_beta\node_modules\commander\lib\command.js:923:5)      

### Steps to reproduce the behavior

run 

1. npm install
2. npm run build

### Additional information
![image](https://github.com/strapi/strapi/assets/85883112/7a77dceb-f27d-4d79-a232-07b070b7abf1)

**Comment by joshuaellis** [comment] 2024-03-27 08:22
duplicate of #19903

**Closed by joshuaellis** 2024-03-27 08:22 UTC
