### ISSUE TITLE
Koa Proxy Not Working With Third Party Auth in Cloud

### ISSUE THREAD

**Issue by PaulBratslavsky** [strapi/strapi#21506] opened 2024-09-27 18:54 UTC
### Required System information

- Node.js version: 20.11.1
- NPM version: 10.2.4
- Strapi version:  5.0.1
- Database: sqlite
- Operating system: darwin-arm64
- Is your project Typescript:

### Describe the bug

When creating a Strapi 5 TypeScript project locally with the GitHub provider, everything works as expected. However, after deploying the project to Strapi Cloud and setting up all the authentication settings, attempting to log in with GitHub results in a 500 server error.

After discussing the issue with Derrick, who confirmed the bug, we suspect that the Koa proxy configuration may not be set correctly.

### Steps to reproduce the behavior

- Deploy Strapi 5 TS project to strapi cloud
- Set up git hub provider
- Try to authenticate with GitHub

### Expected behavior

Should be able to authenticated with GitHub

### Screenshots
Proxy is set to true but it doesn't seem to be registering.
![image](https://github.com/user-attachments/assets/0a067e0a-c6c3-4d2a-986b-313c965faa12)

Error from Strapi Backend Running logs.
![image3](https://github.com/user-attachments/assets/45b8a0a6-3d1a-4b21-994b-799dc3c45cd1)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment] 2024-09-30 17:28
I was able to confirm this with Paul in a test cloud instance. Engineers if you see this and need me to add you to that cloud project just poke me on Slack.

**Comment by derrickmehaffy** [comment] 2024-09-30 17:29
I'm marking this as high without an EE label because this impacts all usage of users-permissions 3rd party providers while on Cloud with Typescript

It can only be reproduced in Typescript, CJS works fine

**Comment by PaulBratslavsky** [comment] 2024-10-23 16:17
Any updates on this issue?  Just asking for a friend.

**Comment by derrickmehaffy** [comment] 2024-11-12 16:27
Possible this may impact self-hosted EE as well via TID8887. We are confirming

**Comment by derrickmehaffy** [comment] 2024-11-27 17:06
I know the problem now, in Strapi 5 there was a breaking change related to using `proxy: true` (which is what we set automatically in Strapi Cloud)

https://docs.strapi.io/dev-docs/migration/v4-to-v5/breaking-changes/server-proxy

We need to move this to `proxy: { koa: true }` instead

**Comment by derrickmehaffy** [comment] 2024-11-27 19:56
Looks like our Cloud engineering team worked on this issue about a month ago and I tested today and it looks like at least SSO is working properly now so I'll go ahead and close this one out.

**Closed by derrickmehaffy** 2024-11-27 19:56 UTC
Labels: issue: bug, severity: high, status: confirmed, source: plugin:users-permissions, source: typescript, version: 5, source: core:core

**Comment by PaulBratslavsky** [comment] 2024-11-28 01:59
@derrickmehaffy, did you have to redeploy the app?  When using social providers, I still get the same previous error.

**Comment by derrickmehaffy** [comment] 2024-11-30 20:49
Mmmmm I'm not sure, I tested on new apps but yeah it was working for me.

**Comment by PaulBratslavsky** [comment] 2024-12-03 13:03
@derrickmehaffy thank you, it may be something on my end, I will create a fresh example to double check.  Thank you.
