### ISSUE TITLE
The updated_by field is not updated in database when publishing or unpublishing an entry

### ISSUE THREAD

**Issue by PritamSangani** [strapi/strapi#9218] opened 2021-01-25 21:39 UTC
### Describe the bug

When publishing or unpublishing an entry the user who edited the entry last (before the publish/unpublish) is set as the user is last updated the entry. 

e.g. if user A updated an unpublished entry and then user B published the entry then user A is set as the user who last updated the entry.

### Steps to reproduce the behavior

1. Create a user with first name User and last name A.
2. Create a second user with first name User and last name B.
3. Create a collection type with a short text field called 'Text' with **Draft and Publish turned on**
4. Log in as the first user (User A).
5. Add an entry of the collection type created in step 3. **Do not publish at this stage**
6. Log out and then log back in as the second user (User B)
7. Go into the entry created as part of step 5 and publish.
8. Notice that in the information section, the Last updated by remains as User A.
9. Staying logged in as User B, make some changes to the entry, and then save.
10. Log out and then log back in as User A. 
11. Going to the published entry, unpublish and see that the Last updated by remains as User B.

### Expected behavior

When publishing or unpublishing an entry the user who performed the publish/unpublish action should be set as the user who last updated.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12.19.0
- NPM version:
- Strapi version: 3.4.4
- Database: MySQL
- Operating system: MacOS

**Comment by derrickmehaffy** [comment] 2021-01-25 22:34
@strapi/maintainers will need clarification if this is a bug.

Logically speaking, the current action is the correct one, as publishing is an update and it's being performed by the user linked in the updated by, much like the updated at field is automatically changed by the database to indicate a change has been made on the table.

The only alternative I see is a boolean toggle to turn off changing the updated by for publishing or add a new automated field like `published_by`.

Leaving open as discussion until this is confirmed as either a bug report, feature request, or intended action.

**Comment by PritamSangani** [comment] 2021-01-27 18:18
Looking at the code, it seems like it is intended as unlike the create and update controller methods in the collection-types.js file for the content-manager plugin, the user object is not taken from the context that comes in with the REST API call. However, I would argue that publishing or unpublishing an entry is making an update so that should be reflected in the database by also updating the `updated_by` field. 

This is quite important for my solution as there is a requirement to have an audit table, which I have implemented for CREATE and UPDATE actions, but I can't do this for PUBLISH or UNPUBLISH if the correct user is not being set as the updater.

**Comment by Strapi-User** [comment] 2021-11-22 15:51
Related to the above, the `updated_by` field is also not updated when an update was done from the REST API by an 'end user'. 
Steps to reproduce: 

1. Create a new entry from the REST API (e.g., POST blogs/)
2. View the entry in the content manager of the Admin UI, note that the "By" field is empty
3. Make an update to the entry as an admin user in the UI and press save
4. Note that the "Last update" and "By" field is updated with the current admin user that made the change
5. Make a change to the entry as an end-user from the REST API (e.g., PUT blogs/1)
6. Reload the entry in the Admin UI content manager, note that "Last update" has been updated but that "By" still shows the last update as if the admin user had made it, when in fact it was done by an end-user from the REST API.

**Comment by derrickmehaffy** [comment] 2021-11-22 20:14
Fixed in v4-beta.14 I believe. We will not be backporting this to v3: https://github.com/strapi/strapi/pull/11627

**Closed by derrickmehaffy** 2021-11-22 20:14 UTC
Labels: type: discussion

**Comment by derrickmehaffy** [comment] 2021-11-22 20:15
> Related to the above, the `updated_by` field is also not updated when an update was done from the REST API by an 'end user'. Steps to reproduce:
> 
> 1. Create a new entry from the REST API (e.g., POST blogs/)
> 2. View the entry in the content manager of the Admin UI, note that the "By" field is empty
> 3. Make an update to the entry as an admin user in the UI and press save
> 4. Note that the "Last update" and "By" field is updated with the current admin user that made the change
> 5. Make a change to the entry as an end-user from the REST API (e.g., PUT blogs/1)
> 6. Reload the entry in the Admin UI content manager, note that "Last update" has been updated but that "By" still shows the last update as if the admin user had made it, when in fact it was done by an end-user from the REST API.

That is normal because the relation for `updatedBy / createdBy` is to the `strapi-admin` set of admins, it's not possible to change this to users-permissions, especially now in v4 that plugin is optional. 

If you need this you will have to implement it manually.
