### ISSUE TITLE
core::5.0.0-discard-drafts migration fails when not using i18n

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#20225] opened 2024-04-28 18:55 UTC
### Required System information

Environment: development
OS: darwin-arm64
Strapi Version: 5.0.0-beta.5
Node/Yarn Version: yarn/1.22.19 npm/? node/v18.20.2 darwin arm64
Edition: Community
Database: sqlite

### Describe the bug

Starting beta.5 runs migration `core::5.0.0-discard-drafts` thats crashes on a missing `locale` field

### Steps to reproduce the behavior

1. have a strapi 4 without i18n
2. install beta 5
3. start
4. crash

### Expected behavior

No crash

**Comment by n-alonso** [comment] 2024-05-02 11:03
Hi @laurenskling ,

I am not able to reproduce the in `5.0.0-beta.5`.
Im also in a mac, using yarn 1.22, node 18, SQLite and upgraded from v4@latest without i18. `yarn develop` still works just fine and I am able to create and delete content.

Also your reproduction steps are not very descriptive, please in the future try to be as explicit as possible.

I will mark this issue as 'unable to reproduce' until you provide further steps.

**Comment by laurenskling** [comment] 2024-05-02 19:03
Hi Nicolas, 
thanks for taking the time to debug this.
Sorry for my limited bug report. Somewhere I was sure this migration just forgot about v4 working without having i18n turned on and it just failed to work with that use case. But you mention that you are able to migration from a v4 without i18n, that changes the situation.
My error:

```
⠙ Loading Strapi{ event: 'migrating', name: 'core::5.0.0-discard-drafts' }
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

MigrationError: Migration core::5.0.0-discard-drafts (up) failed: Original error: select `t0`.`id`, `t0`.`document_id`, `t0`.`locale` from                  
`documents_document` as `t0` where (`t0`.`published_at` is not null) order by `t0`.`id` asc limit 1000 - no such column: t0.locale                          
at /Users/laurenskling/sites/strapi5/node_modules/umzug/lib/umzug.js:151:27                                                                                
at async Umzug.runCommand (/Users/laurenskling/sites/strapi5/node_modules/umzug/lib/umzug.js:107:20)                                                       
at async Object.up (/Users/laurenskling/sites/strapi5/node_modules/@strapi/database/dist/index.js:6239:7)                                                  
at async Object.up (/Users/laurenskling/sites/strapi5/node_modules/@strapi/database/dist/index.js:6263:11)                                                 
at async Object.sync (/Users/laurenskling/sites/strapi5/node_modules/@strapi/database/dist/index.js:2211:9)                                                
at async Strapi.bootstrap (/Users/laurenskling/sites/strapi5/node_modules/@strapi/core/dist/Strapi.js:328:5)                                                
at async Strapi.load (/Users/laurenskling/sites/strapi5/node_modules/@strapi/core/dist/Strapi.js:294:5)                                                     
at async Module.develop (/Users/laurenskling/sites/strapi5/node_modules/@strapi/strapi/dist/node/develop.js:177:28)                                         
at async action (/Users/laurenskling/sites/strapi5/node_modules/@strapi/strapi/dist/cli/commands/develop.js:18:5)                                           
at async Command.parseAsync (/Users/laurenskling/sites/strapi5/node_modules/commander/lib/command.js:923:5)                                                 

My situation:
- i come from a v4 without i18n
- i have content types in plugins
- i still do not have i18n installed in v5, as it is now auto installed

**Comment by laurenskling** [comment] 2024-05-02 19:25
By the way, I am talking about the migration. If I start without a database, yes it boots and you can work. But thats not the point. The point is the migration called `core::5.0.0-discard-drafts` when I have content.

**Comment by derrickmehaffy** [comment] 2024-05-02 21:05
> By the way, I am talking about the migration. If I start without a database, yes it boots and you can work. But thats not the point. The point is the migration called `core::5.0.0-discard-drafts` when I have content.

@laurenskling we aren't to the point of being ready for testing migrations from v4 yet. We don't expect to be able to do that until probably around May 22nd or so.

**Comment by laurenskling** [comment] 2024-05-05 08:32
Thanks @derrickmehaffy , I guess we can keep this open until testing of migration starts then :)

**Comment by Convly** [comment] 2024-06-03 13:06
Hey @laurenskling, sorry I took so long to come back to you.

I've taken a shot at fixing your issue in https://github.com/strapi/strapi/pull/20422

If you could try this experimental version (`0.0.0-experimental.4ddd402c7194d1a969a797313bf007c93148d59a`) and tell me if it fixes the issue on your side, it would be perfect.

Have a nice afternoon!

**Comment by laurenskling** [comment] 2024-06-03 18:30
Thanks for your work on this @Convly 

I installed version `0.0.0-experimental.4ddd402c7194d1a969a797313bf007c93148d59a` for all strapi packages
Still crashes:

```
⠙ Loading Strapi{
  event: 'migrating',
  name: '5.0.0-rename-identifiers-longer-than-max-length'
}
{
  event: 'migrated',
  name: '5.0.0-rename-identifiers-longer-than-max-length',
  durationSeconds: 1.337
}
{ event: 'migrating', name: '5.0.0-02-created-document-id' }
{
  event: 'migrated',
  name: '5.0.0-02-created-document-id',
  durationSeconds: 1.784
}
{ event: 'migrating', name: '5.0.0-03-created-locale' }
{
  event: 'migrated',
  name: '5.0.0-03-created-locale',
  durationSeconds: 0.18
}
{ event: 'migrating', name: 'core::5.0.0-discard-drafts' }
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

MigrationError: Migration core::5.0.0-discard-drafts (up) failed: Original error: select `t0`.`id`, `t0`.`document_id`, `t0`.`locale` from `documents_document` as `t0` where (`t0`.`published_at` is not null) order by `t0`.`id` asc limit 1000 - no such column: t0.locale                                                                                                                                   
at /Users/laurenskling/sites/strapi5/node_modules/umzug/lib/umzug.js:151:27                                                                                                                               
at async Umzug.runCommand (/Users/laurenskling/sites/strapi5/node_modules/umzug/lib/umzug.js:107:20)                                                                                                      
at async Object.up (/Users/laurenskling/sites/strapi5/node_modules/@strapi/database/dist/index.js:6284:7)                                                                                                 
at async Object.up (/Users/laurenskling/sites/strapi5/node_modules/@strapi/database/dist/index.js:6308:11)                                                                                                
at async Object.sync (/Users/laurenskling/sites/strapi5/node_modules/@strapi/database/dist/index.js:2220:9)                                                                                               
at async Strapi.bootstrap (/Users/laurenskling/sites/strapi5/node_modules/@strapi/core/dist/Strapi.js:328:5)                                                                                              
at async Strapi.load (/Users/laurenskling/sites/strapi5/node_modules/@strapi/core/dist/Strapi.js:294:5)                                                                                                   
at async Module.develop (/Users/laurenskling/sites/strapi5/node_modules/@strapi/strapi/dist/node/develop.js:177:28)                                                                                       
at async action (/Users/laurenskling/sites/strapi5/node_modules/@strapi/strapi/dist/cli/commands/develop.js:18:5)                                                                                         
at async Command.parseAsync (/Users/laurenskling/sites/strapi5/node_modules/commander/lib/command.js:923:5)                                                                                              

✨  Done in 7.14s.
```

did I miss any installation steps?

**Comment by laurenskling** [comment] 2024-06-03 18:41
I did some digging, now I realized where this migration code actually is.

It's crashing on this line: https://github.com/strapi/strapi/blob/4ddd402c7194d1a969a797313bf007c93148d59a/packages/core/core/src/migrations/database/5.0.0-discard-drafts.ts#L35 there `locale` is hard selected.

**Comment by ildfreelancer** [comment] 2024-06-20 08:40
@Convly sorry to mention you.
However, I see you made a PR here: https://github.com/strapi/strapi/pull/20422
Do you know when the PR is merged?
Any issues we can do to make it merged?

**Comment by Convly** [comment] 2024-06-20 12:52
Hey there, my PR allegedly fixes the issue, but as pointed out in this comment (https://github.com/strapi/strapi/pull/20422#discussion_r1644458596) another change might fix it in a simpler manner.
I would like to wait for this to be merged, see if it solves the issue, and potentially close my PR if it's not needed anymore.

**Comment by shamglam** [comment] 2024-06-24 08:45
seems like the migration works in beta.15 but starting strapi fails

`Unknown column 't0.locale' in 'field list'
    at Packet.asError (/home/shamrez/my-pro/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/home/shamrez/my-pro/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/home/shamrez/my-pro/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/home/shamrez/my-pro/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/home/shamrez/my-pro/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/shamrez/my-pro/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 't0.locale' in 'field list'",`

**Comment by shamglam** [comment] 2024-06-24 08:46
seems like the migration works but something else fails when trying to start strapi

```
Unknown column 't0.locale' in 'field list'
    at Packet.asError (/home/user/my-pro/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/home/user/my-pro/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/home/user/my-pro/node_modules/mysql2/lib/connection.js:481:34)
    at PacketParser.onPacket (/home/user/my-pro/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/home/user/my-pro/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/user/my-pro/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:518:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sqlState: '42S22',
  sqlMessage: "Unknown column 't0.locale' in 'field list'",
```

**Comment by alexandrebodin** [comment] 2024-06-28 13:26
@shamglam can you test this with the RC version we release 2 days ago ?

**Comment by shamglam** [comment] 2024-07-29 09:23
@alexandrebodin I actually got it working in rc0 after seeing that the reason for the error was that the migration 
wasn't completed properly. I deleted the migration entry from the database and then everything worked as expected.

**Closed** 2024-08-26 15:16 UTC
Labels: issue: bug, severity: high, status: confirmed, version: 5, source: core:core
