### ISSUE TITLE
Field names doesn't change in the database 

### ISSUE THREAD

**Issue by deebov** [strapi/strapi#4481] opened 2019-11-08 09:23 UTC
**Describe the bug**
Strapi does not rename the field names in the database when I rename them in strapi. I mean, if you change any fields name strapi will just ignore the old field no matter it contains any value or not. the old fields will stay in the database with their values. what actually strapi is doing is creating a new field instead of replacing it in the database.

**Steps to reproduce the behavior**
1. Create content type with some fields
2. Create some content for that type
3. Go to `Content type manager`
4. Change some fields name
5. Go to that content type and you can see the we field with empty value
6. Go to your database 
7. Check if the old field is there

**Expected behavior**
Strapi changes the fields names both in the database and in strapi

**Screenshots**
Content in the database:
![image](https://user-images.githubusercontent.com/28673719/68464636-c3833e00-0232-11ea-8532-a2390b878271.png)

Content type in Strapi:
![image](https://user-images.githubusercontent.com/28673719/68464667-d433b400-0232-11ea-87d5-1bec5d3480d4.png)

P.s. fields that start with `event` ( e.g. `eventTitle` ) has been renamed to just without `event` in the start

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: 12.9.1
- NPM version: 6.10.2
- Strapi version: 3.0.0-beta.15
- Database: MongoDb ( mLab in heroku )
- Operating system: macOs catalina 10.15.1 ( the app is deployed in heroku )

**Comment by derrickmehaffy** [comment] 2019-11-08 21:08
Closing as duplicate of https://github.com/strapi/strapi/issues/1114

@deebov Strapi does not rename or drop anything it will only create at this time. Migrations need to be done manually.

**Closed by derrickmehaffy** 2019-11-08 21:08 UTC
