### ISSUE TITLE
Content Manager 500s on call to API with undefined in URL path for Single Type with Relation to Collection Type

### ISSUE THREAD

**Issue by psunderhaus-alto** [strapi/strapi#20514] opened 2024-06-14 02:13 UTC
### Required System information

- Environment: development
- OS: darwin-arm64
- Strapi Version: 4.25.0
- Node/Yarn Version: npm/10.6.0 node/v20.10.0 darwin arm64 workspaces/false
- Edition: Community & Enterprise
- Database: postgres
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I believe this issue is related to #20410, but I am not experiencing app crashing. My symptoms are a consistent 500 error the admin panel appears to recover from.

When I create a Single Type with a relation field with a 1:1 mapping to a Collection Type, upon saving that Single Type and reloading the page, the following server error occurs.

```
[2024-06-13 17:27:51.578] error: select "t0".* from "public"."featured_restaurants" as "t0" where ("t0"."id" = $1) limit $2 - invalid input syntax for type integer: "undefined"
error: select "t0".* from "public"."featured_restaurants" as "t0" where ("t0"."id" = $1) limit $2 - invalid input syntax for type integer: "undefined"
    at Parser.parseErrorMessage (/Users/****/strapi-single-type-with-relation-issue/node_modules/pg-protocol/dist/parser.js:283:98)
    at Parser.handlePacket (/Users/****/strapi-single-type-with-relation-issue/node_modules/pg-protocol/dist/parser.js:122:29)
    at Parser.parse (/Users/****/strapi-single-type-with-relation-issue/node_modules/pg-protocol/dist/parser.js:35:38)
    at Socket.<anonymous> (/Users/****/strapi-single-type-with-relation-issue/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

Also observe that the request URL contains the term `undefined` in the path. This GET fails with a 500 because, I believe Strapi is mishandling or improperly sourcing the ID of the entry stored in the relation field.
```
http://localhost:1337/content-manager/relations/api::featured-restaurant.featured-restaurant/undefined/restaurant?pageSize=5&page=1
```

### Steps to reproduce the behavior

I've created a repository with a simple Restaurant (Collection Type) and Featured Restaurant (Single Type) example. Please consult it and the instructions below to recreate the bug.

https://github.com/psunderhaus-alto/strapi-single-type-with-relation-issue

1. docker compose up
2. npm run develop
3. Save a Restaurant entry
4. Save a Featured Restaurant entry with the relation field populated with the entry from step 3.
5. Reload the Featured Restaurant entry and observe 500 error in your browser's network tab and server STDOUT.

### Expected behavior

Strapi should load the single type entry as expected without error.

**Comment by psunderhaus-alto** [comment] 2024-07-09 15:19
Writing to report this is continuing to occur for me on Strapi v4.25.2 with Node v20.15.0.

**Comment by derrickmehaffy** [comment] 2024-07-09 21:45
Closing this one as a duplicate of https://github.com/strapi/strapi/issues/20715 since the newer issue is related to an ee ticket.

Thank you for the bug report we just didn't see this one when we created a new one.

**Closed by derrickmehaffy** 2024-07-09 21:45 UTC
