### ISSUE TITLE
Update v4.11.1  to v4.11.4 breaks uploads

### ISSUE THREAD

**Issue by vandres** [strapi/strapi#17228] opened 2023-07-07 11:38 UTC
### Required System information

- Node.js version: v16.20.1
- NPM version: 8.19.4
- Strapi version: v4.11.4
- Database: SQLite
- Operating system: MacOS
- Is your project Javascript or Typescript: JS

### Describe the bug

We have all our uploads in the root folder. The DB looks something like this. This project was updated from v3 to v4 before.

![grafik](https://github.com/strapi/strapi/assets/1436383/fee0308d-73f0-4cec-ab5a-28f43213732a)

When we use v.4.11.1 everything works well. We upgraded to v4.11.4 today and the Media Library is empty. All linked images in the content are still visible.

I debugged the problem down to `node_modules/@strapi/plugin-upload/server/controllers/admin-file.js` around line 29. When looking at the query filters, they changed between versions.

v.4.11.1:

![grafik](https://github.com/strapi/strapi/assets/1436383/abb697cf-6a7c-40ac-880b-86c593ffa4ef)

v4.11.4:

![grafik](https://github.com/strapi/strapi/assets/1436383/29493f11-aa33-4085-83c9-c47fae9fd5c6)

I think from the query filters you can see the problem. Was this an intended change? Is there some note on this breaking change?

**Comment by joshuaellis** [comment] 2023-07-07 12:32
> I think from the query filters you can see the problem

No I can't i find them really hard to read 😅 

Can I clarify the bug youre experience is you viewing the media in the admin panel? If so where? Is this a UI bug etc. I think your description could be a bit more verbose – that would really help :)

**Comment by vandres** [comment] 2023-07-07 13:17
Hi @joshuaellis 

Sorry for that :D Yes, I am talking about the Admin UI. The "Media Library" there is empty after the update. I just followed the api calls from there, which led me to `node_modules/@strapi/plugin-upload/server/controllers/admin-file.js`

**Comment by joshuaellis** [comment] 2023-07-07 13:29
Cool, looking at your screenshot none of your media assets have `folderPath` which if they're all at the root of the project should just have the string `'/'` i believe... CC @Marc-Roig ?

**Comment by Marc-Roig** [comment] 2023-07-07 14:02
@joshuaellis we might not have had any migration to migrate empty `folderPath` columns to `/` , so people upgrading might have this issue. I believe we will have to update the filter path to look for `/` and `null` values, or revert it to what we had before.

**Comment by joshuaellis** [comment] 2023-07-07 14:05
Thanks @Marc-Roig i'd like to avoid reverting because it causes performance issues in the BE.

@vandres two questions:
* do you use media folders at the moment?
* and if you do, do any of your assets have a `folderPath`?

**Comment by vandres** [comment] 2023-07-07 15:05
@joshuaellis 

All our files are in the root folder, so we are not using folders itself. None of them has a `folderPath`.

I fixed the problem for us now by executing the following SQL `UPDATE files SET folder_path = "/"`. But other people might run into this problem and it is a breaking change between patch releases...

**Comment by Boegie19** [comment] 2023-07-07 15:15
I agree a notice should be put on the release

**Comment by joshuaellis** [comment] 2023-07-07 15:20
@vandres & @Boegie19 – No it's not a breaking change, we changed the query in the admin panel – the issue is for the migration steps when we introduced folders no one included a script to change the `null` values to `'/'`, that I can unfortunately only apologise for the developers who did the feature. 

Moving forward i'll amend the query to also look for `folderPath === null` 👍🏼

**Comment by Boegie19** [comment] 2023-07-07 15:24
@joshuaellis You would still need to add a note to the release since this is breaking you will fix it in the next release but this release has a breaking change.

**Comment by joshuaellis** [comment] 2023-07-07 15:24
> @joshuaellis You would still need to add a note to the release since this is breaking you will fix it in the next release but this release has a breaking change.

we'll agree to disagree on the term breaking change.

**Comment by Boegie19** [comment] 2023-07-07 15:27
Okay lets say it diffrently you guys broke someting in this release so it mind be nice to add it to the release notes that this is broken and would be fixed in the next release.

**Comment by derrickmehaffy** [comment] 2023-07-07 18:21
> > @joshuaellis You would still need to add a note to the release since this is breaking you will fix it in the next release but this release has a breaking change.
> 
> we'll agree to disagree on the term breaking change.

Josh I agree here with @Boegie19 that this is a breaking change as previously existing and default functionality no longer works after upgrading a minor release as per our internal breaking change definition. 

https://www.notion.so/strapi/Breaking-changes-definition-1ab2fdb9663848828b1dd1b68e9bb771

**Comment by derrickmehaffy** [comment] 2023-07-12 22:48
Related internal TID:4356 Enterprise customer unable to see over 900+ assets in their media library

**Comment by derrickmehaffy** [comment] 2023-07-12 22:51
Raising sev to critical as per our severity escalations policy:

![image](https://github.com/strapi/strapi/assets/8593673/505701fe-0000-46dd-aa65-51d6636399bc)
https://www.notion.so/strapi/FreshDesk-GitHub-Ticket-Issue-Management-03e1e7b5bfc54f6bbfd527172ef238c5?pvs=4#dbeb91d6553545bcbba450251b2b8ede

**Comment by Marc-Roig** [comment] 2023-07-14 09:04
For now we have created a migration guide you can install to fix this issue, we have a PR open but you can check a preview here https://documentation-git-migration-media-library-folder-path-strapijs.vercel.app/dev-docs/migration/v4/migration-guide-4.7.0-to-4.11.4#installing-database-migration-script-optional

Our objective is to create a transparent migration so users do not require a manual migration, we will be working with that next weeks, but for now we provided this other solution

**Closed** 2023-07-14 14:24 UTC
Labels: issue: bug, severity: critical, status: confirmed, flag: 💥 Breaking change, source: core:upload, flag: EE

**Comment by alumedot** [comment] 2023-07-31 15:27
Hey @Marc-Roig, I still have the issue, we see only 2 images (instead of 3 pages) in our library, I've tried the migration script but nothing has changed.
Media Library works fine in **v4.14.3**

**Comment by andres9722** [comment] 2023-09-13 17:51
Hey @Marc-Roig trying We only see 77 of images out of more than 3000, we are on version 4.11.5
Trying to do the migration we get this error, any advice? thanks

MigrationError: Migration 2023.06.14T00.00.00.update-file-paths.js (up) failed: Original error: update "files" set "folder_path" = $1 where "folder_path" is null - relation "files" does not exist

**Comment by Marc-Roig** [comment] 2023-09-26 09:22
@alumedot hello , do you have an error or something that your migration script prints?

Do you have access to any tool to visuallize the  `files` table in your database?
