### ISSUE TITLE
i18n new locale selection box not scrolling properly

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#14752] opened 2022-11-01 14:34 UTC
### Required System information

- Node.js version: 16.17.1
- NPM version: 8.15.0
- Yarn version: 1.22.19
- Strapi version: 4.4.5
- Database: SQLite
- Operating system: Linux Mint 20.3 (Ubuntu 20.04.3)

### Describe the bug

When adding a new locale and trying to search the list box is not scrolling to match the search

### Steps to reproduce the behavior

https://www.loom.com/share/5c4a5d5683414bbab559c16ecb7a6ef8

### Expected behavior

When I start typing, the list box should auto-scroll/filter based on my search query

### Screenshots

N/A

### Code snippets

N/A

### Additional context

N/A

**Comment by ivanThePleasant** [comment] 2022-11-10 15:46
The issue is that the `iso-locales.json` file has duplicate entries. The scrolling functionality is working as expected, but because of the duplicates you always see them first in the list. Essentially, the bug is with react keys not being unique due to locale duplicates. I'll push a PR shortly to fix this

**Comment by ronronscelestes** [comment] 2022-12-12 11:05
Seems fixed on my side with @ivanThePleasant PR - should we close it? 👀

**Comment by ivanThePleasant** [comment] 2022-12-12 12:14
I'll close this for now, I believe @derrickmehaffy tested this since he also approved the PR

**Closed by ivanThePleasant** 2022-12-12 12:14 UTC
Labels: issue: bug, severity: low, status: confirmed, source: plugin:i18n
