### ISSUE TITLE
after deploy with railway cant access /admin 

### ISSUE THREAD

**Issue by ilham89** [strapi/strapi#15230] opened 2022-12-21 10:37 UTC
### Required System information

- Node.js version: >=12.x.x <=16.x.x,
- NPM version: >=6.0.0
- Strapi version: 4.1.9
- Database: pg
- Operating system: windows 10

### Describe the bug
i deploy my strapi to railway, i can access route domain but when i access [/admin](tg://bot_command?command=admin) i getting an error like this. can anyone help me?

error:  Refused to connect to 'http://localhost:1337/admin/project-type' because it violates the following Content Security Policy directive: "connect-src 'self' https: https://www.google-analytics.com".

### Screenshots

![image](https://user-images.githubusercontent.com/56493086/208883058-2a502b63-e47d-4845-88d0-725ed8422b1c.png)
![image](https://user-images.githubusercontent.com/56493086/208885406-add288ad-f408-4b9c-8677-e13ba7b5ae88.png)

**Comment by bis0072** [comment] 2022-12-22 18:01
It's a database error.

**Comment by ilham89** [comment] 2022-12-23 01:45
how do i fix it?, i didn't change anything from the strapi railway starter

> It's a database error.

**Comment by bis0072** [comment] 2022-12-23 16:43
check .env with the following values first --->
HOST=0.0.0.0
PORT=1337
APP_KEYS=********************
API_TOKEN_SALT=*****************
ADMIN_JWT_SECRET=********************
JWT_SECRET=*******************
CLOUDINARY_NAME=**************
CLOUDINARY_KEY=*************
CLOUDINARY_SECRET=*********************

Put your values and redeploy.

**Comment by ecosse3** [comment] 2022-12-24 05:59
I have the same issue with AWS. Seems like a duplicate of #15118

**Comment by ilham89** [comment] 2022-12-24 14:56
> check .env with the following values first ---> HOST=0.0.0.0 PORT=1337 APP_KEYS=******************** API_TOKEN_SALT=***************** ADMIN_JWT_SECRET=******************** JWT_SECRET=******************* CLOUDINARY_NAME=************** CLOUDINARY_KEY=************* CLOUDINARY_SECRET=*********************
> 
> Put your values and redeploy.

![image](https://user-images.githubusercontent.com/56493086/209441583-d5432ad0-7deb-476e-a4b3-5cec1d393b6b.png)

I've added it from the start, but it doesn't affect anything

**Comment by derrickmehaffy** [comment] 2022-12-27 21:21
You need to set the URL key in the `./config/server.js` (ideally with a env variable if railway exposes that.

I'm going to close this issue though as it's not really a Strapi bug, it's just missing a config setting so this would be better suited as question on our community spaces:

---

Hello,

I see you are wanting to ask a question that is not really a bug report, 

- questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). 
- feature requests should be directed to our [feedback and feature request database](https://feedback.strapi.io)

Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Closed by derrickmehaffy** 2022-12-27 21:21 UTC
