### ISSUE TITLE
Video upload via media library cannot be selected for removal

### ISSUE THREAD

**Issue by Audit-a-la-Carte** [strapi/strapi#13260] opened 2022-05-06 19:13 UTC
### Required System information
NODE VERSION: v16.15.0
Strapi V4.1.9
Chrome on Mac 101.0.4951.54 (x86_64)
Managed database on Digital Ocean
App on Digital Ocean

### Describe the bug
As a user, I can upload images (photos) and store them on DigitalOcean Spaces. I can select multiple pictures and delete them. Once I upload a video, this works and the video will be stored on the Spaces environment but the interface of the Strapi media library does not allow me to click the video (select it) and delete it. So the videos cannot be deleted at this time.

### Steps to reproduce the behavior

1. Go to 'media library'
2. Click on 'upload assets'
3. select a Video
4. Upload succeeded, try to select the checkbox
5. The checkbox cannot be clicked

### Expected behavior
I would expect, similar to the pictures this video file can be deleted. But the checkbox is never selected.

### Additional context
I briefly discussed it with Piwi in Discord, but he could not reproduce it. Not sure if the link to the screen recording works here: https://cdn.discordapp.com/attachments/972122163492556840/972129682571030558/strapi-video-example.mov

**Comment by Audit-a-la-Carte** [comment] 2022-06-07 14:18
Sure thing, will do this asap! Sorry for the late response, has been a bit hectic recently but certainly will follow up in the coming weeks.

**Comment by NicoHof** [comment] 2022-06-07 16:56
I experienced the same issue (videos hosted on s3 bucket) and could fix it by adding CORS headers in amazon settings.
So you maybe can open your devtools and check if there are some CORS errors?

Maybe it helps for reproducing the issue @derrickmehaffy

Sidenote: For me the 2 pixels on the very top of the checkbox were clickable. ;-)

**Comment by Audit-a-la-Carte** [comment] 2022-06-08 06:21
Hi Nico,

Thanks for thinking along, much appreciated! I double-checked (again) if this is a CORS issue, but no errors on the console I am afraid. I also tried all the corners to find those 2 pixes, but no luck here.

Since you are so persistent, I took this approach too :-)

I adjusted the z-index of the video layer and I was able to select (and delete) them now. So it seems a styling issue, preventing me to click the checkbox. Hopefully, this screenshot is sufficient to patch this in the next release?

Thanks for the pointer @NicoHof! @derrickmehaffy are you able to confirm this? If not, perhaps some Chrome extension might be causing this? 

<img width="1402" alt="Screenshot 2022-06-08 at 08 16 15" src="https://user-images.githubusercontent.com/34521947/172545642-929e8808-9346-402a-976f-f1402249b336.png">

**Comment by derrickmehaffy** [comment] 2022-06-14 08:38
I'm not able to reproduce no, a chrome extension can modify the styling absolutely but I wouldn't even know where to start other than testing in a clean browser.

**Comment by Audit-a-la-Carte** [comment] 2022-06-14 09:02
In that case, I will shortly try using a blank browser, disabling all extensions to exclude that possibility.  Thanks @derrickmehaffy for the additional efforts.

**Comment by derrickmehaffy** [comment] 2022-06-30 16:31
I'm going to set this as closed as we don't have any new information and we are unable to reproduce. However if you have new information to add please feel free and we can look at reopening.

Thanks.

**Closed by derrickmehaffy** 2022-06-30 16:31 UTC
Labels: issue: bug, severity: low, status: can not reproduce, source: core:admin, source: core:upload

**Comment by Zenith-Lair** [comment] 2023-01-02 10:51
I have the similar issue as well. @Audit-a-la-Carte did you know how to fix it?

**Comment by Audit-a-la-Carte** [comment] 2023-01-02 10:59
@Zenith-Lair it got resolved with an update later that month. It was a CSS issue if I remember correctly.

**Comment by Boegie19** [comment] 2023-01-02 11:00
Seems to me like the same issue as https://github.com/strapi/strapi/issues/15275

**Comment by Zenith-Lair** [comment] 2023-01-02 12:56
@Boegie19 So it's still not fixed then?

**Comment by Boegie19** [comment] 2023-01-02 14:15
> @Boegie19 So it's still not fixed then?

It is fixed for normal MP4s only when the preview can't load the video because of for example unknown file format it will break.
