### ISSUE TITLE
Custom policy: `ctx.unauthorized(`message`)` generates `"INTERNAL_SERVER_ERROR"`

### ISSUE THREAD

**Issue by baptisteArno** [strapi/strapi#9052] opened 2021-01-06 10:18 UTC
### Describe the bug

When I setup a custom policy that calls `ctx.unauthorized("You're not authorized");`, it returns:
```
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field WomenModels.name.",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "updateWomenModel",
        "womenModel",
        "name"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field WomenModels.name.",
            "    at completeValue (/Users/baptistearnaud/Dev/Wiki-Fashion/backend/node_modules/graphql/execution/execute.js:561:13)",
            "    at resolveField (/Users/baptistearnaud/Dev/Wiki-Fashion/backend/node_modules/graphql/execution/execute.js:474:19)",
            "    at executeFields (/Users/baptistearnaud/Dev/Wiki-Fashion/backend/node_modules/graphql/execution/execute.js:294:18)",
            "    at collectAndExecuteSubfields (/Users/baptistearnaud/Dev/Wiki-Fashion/backend/node_modules/graphql/execution/execute.js:749:10)",
            "    at completeObjectValue (/Users/baptistearnaud/Dev/Wiki-Fashion/backend/node_modules/graphql/execution/execute.js:739:10)",
            "    at completeValue (/Users/baptistearnaud/Dev/Wiki-Fashion/backend/node_modules/graphql/execution/execute.js:592:12)",
            "    at resolveField (/Users/baptistearnaud/Dev/Wiki-Fashion/backend/node_modules/graphql/execution/execute.js:474:19)",
            "    at executeFields (/Users/baptistearnaud/Dev/Wiki-Fashion/backend/node_modules/graphql/execution/execute.js:294:18)",
            "    at collectAndExecuteSubfields (/Users/baptistearnaud/Dev/Wiki-Fashion/backend/node_modules/graphql/execution/execute.js:749:10)",
            "    at completeObjectValue (/Users/baptistearnaud/Dev/Wiki-Fashion/backend/node_modules/graphql/execution/execute.js:739:10)",
            "    at completeValue (/Users/baptistearnaud/Dev/Wiki-Fashion/backend/node_modules/graphql/execution/execute.js:592:12)",
            "    at /Users/baptistearnaud/Dev/Wiki-Fashion/backend/node_modules/graphql/execution/execute.js:471:16"
          ]
        }
      }
    }
  ],
  "data": {
    "updateWomenModel": {
      "womenModel": null
    }
  }
}
```

### Steps to reproduce the behavior

1. Setup GraphQL
2. Add custom policy:
in schema.graphql.js:
```
module.exports = {
  resolver: {
    Mutation: {
      updateWomenModel: {
        description: "Update woman model",
        policies: ["isModelOwner"],
      },
    },
  },
};
```
policies/isModelOwner.js:

```
"use strict";

/**
 * `isModelOwner` policy.
 */

module.exports = async (ctx, next) => {
  ctx.unauthorized(`You're not logged in!`);
};
```
3. Call the `updateWomenModel` mutation with an authenticated user 

### Expected behavior

It should return an "Unauthorized" message and status code

### System

- Strapi version: 3.4.0

**Comment by derrickmehaffy** [comment] 2021-01-06 13:10
Use `return ctx.unauthorized()`

Closing as this not a bug within Strapi but is a customization error, for questions like thisnplease use our forums: https://forum.strapi.io

**Closed by derrickmehaffy** 2021-01-06 13:10 UTC

**Comment by LeBenLeBen** [comment] 2021-03-27 16:06
Returning `ctx.unauthorized()` does not solve the issue, GraphQL still return a server error "Cannot return null for non-nullable field". This has been reported again in #8995.
