### ISSUE TITLE
Strapi UI disappears when uploading image (modified port)

### ISSUE THREAD

**Issue by ksb86** [strapi/strapi#17975] opened 2023-09-08 00:09 UTC
### Required System information

- Node.js version: 18.17.0
- NPM version: 9.6.7
- Strapi version: 4.13.3
- Database: sqlite, postgres
- Operating system: OSX
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After changing the default application port from the default of 1337, the Strapi UI disappears when uploading an image through the Media Library plugin.

### Steps to reproduce the behavior

1. Create new Strapi project.
2. Change the PORT environment variable in .env file from 1337 to something else (1234 for example)
3. Rebuild Strapi with `yarn build` (might not be necessary)
4. Start Strapi with `yarn develop` and log in
5. Upload image from computer in 'Media Library' tab
6. Strapi UI disappears (and won't load again even after refresh)

### Expected behavior

Strapi UI should not disappear and should show uploaded image(s)

### Screenshots
<img width="1034" alt="Screenshot 2023-09-07 at 5 39 57 PM" src="https://github.com/strapi/strapi/assets/3429882/8b1c542c-bb97-4c05-a898-2239c09c5384">

### Code snippets

(none)

### Additional context

One way I've been able to make the Media Library UI work again is by deleting all the files out of the strapi files table:
`delete from files;` (when using postgres)

**Comment by Terraxel99** [comment] 2023-09-08 00:32
I have the same issue using SQLite and without changing the default port.

**Comment by ksb86** [comment] 2023-09-08 00:40
> I have the same issue using SQLite and without changing the default port.

Have you configured an upload provider or just using the default filesystem (uploads to public directory in project)? (I have not configured one, just using the default)

**Comment by Terraxel99** [comment] 2023-09-08 00:42
> > I have the same issue using SQLite and without changing the default port.
> 
> @Terraxel99 Have you configured an upload provider or just using the default filesystem (uploads to public directory in project)? (I have not configured one, just using the default)

I am using the default filesystem, my pictures are uploaded and I can access the images using the URL. The thing is that it just throws an error from the media UI view when validating the URL I guess, which makes everything fail.

**Comment by dgrebb** [comment] 2023-09-08 00:48
Thank you for keeping me sane @Terraxel99 @ksb86 🥲 Same here. 

#17967 looks promising for this, though manually patching hasn't fixed the `new URL(relativePathString)` error for me. 

Adding my local domain manually (see below) fixes this, but using `window.strapi.backendURL`, as done in #17967, does not.

```javascript
File: node_modules/@strapi/plugin-upload/admin/src/utils/appendSearchParamsToUrl.js

line 13:   const urlObj = new URL(url, 'http://local.something');
```

If the support team notices this, I'm working on an example, but there may be an issue between pre-`4.13.2` media uploads and post-`4.13.2` upgrades. I have _not_ been able to reproduce with a fresh install of `4.13.3`.

Possible migration candidate?

**Comment by ksb86** [comment] 2023-09-08 00:49
> > > I have the same issue using SQLite and without changing the default port.
> > 
> > 
> > @Terraxel99 Have you configured an upload provider or just using the default filesystem (uploads to public directory in project)? (I have not configured one, just using the default)
> 
> I am using the default filesystem, my pictures are uploaded and I can access the images using the URL (https://localhost:1337/uploads/path.png for example). The thing is that it just throws an error from the media UI in the backoffice view when validating the relative URL of the media I guess, which makes everything fail.

Ah I checked and also can access the asset via the http://localhost/uploads url.  However I'm only getting errors in the browser console for the Strapi UI, and not the Strapi server logs:
<img width="1051" alt="Screenshot 2023-09-07 at 6 46 23 PM" src="https://github.com/strapi/strapi/assets/3429882/dac3da5b-fe7f-48d1-9428-b963e7336e40">

**Comment by ksb86** [comment] 2023-09-08 00:50
> Thank you for keeping me sane @Terraxel99 @ksb86 🥲 Same here.
> 
> #17967 looks promising for this, though manually patching hasn't fixed the `new URL(relativePathString)` error for me.
> 
> Adding my local domain manually (see below) fixes this, but using `window.strapi.backendURL`, as done in #17967, does not.
> 
> ```js
> File: node_modules/@strapi/plugin-upload/admin/src/utils/appendSearchParamsToUrl.js
> 
> line 13:   const urlObj = new URL(url, 'http://local.something');
> ```
> 
> If the support team notices this, I'm working on an example, but there may be an issue between pre-`4.13.2` media uploads and post-`4.13.2` upgrades. I have _not_ been able to reproduce with a fresh install of `4.13.3`.
> 
> Possible migration candidate?

Interesting it's not reproducible on 4.13.3 for you.  That's the only version I've tried so far..

**Comment by Terraxel99** [comment] 2023-09-08 00:50
> 

You're right, I just found out that if you modify the URL of the media file in the database to have the URLs in the JSON and in the "url" property to be absolute (so with http://...) it works fine :

![image](https://github.com/strapi/strapi/assets/36198830/89f42884-0149-4fdd-9bf7-e97393c46294)

This is clearly not viable but I guess the bug resides in the URL validation. As you said @dgrebb, you are in the right direction I believe.

**Comment by dgrebb** [comment] 2023-09-08 00:51
FWIW the error in `console` is due to passing a relative path to `new URL()`, which needs a second argument when not passing a valid domain.

MDN docs for details: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL#parameters

**Comment by Terraxel99** [comment] 2023-09-08 00:52
> 

You are totally right. However, I can reproduce on 4.13.3, it's the only version I tried (as said @ksb86 )

**Comment by dgrebb** [comment] 2023-09-08 00:56
Hopefully this discussion helps shed more light on the underlying cause. I think this #17938 is also related.

**Comment by dgrebb** [comment] 2023-09-08 01:30
Also relevant: #17931

**Comment by imqdcn** [comment] 2023-09-08 06:00
when I upgrade to v4.13.3,then i have the some issue using mysql and without changing the default port.
In chrome，got error:Uncaught TypeError: Failed to construct 'URL': Invalid URL
In firefox, got error:TypeError: URL constructor: /uploads/thumbnail_Ai_8deeb0013e.jpg is not a valid URL.

**Comment by karoyqiu** [comment] 2023-09-08 09:19
I have exact the same issue on v4.13.3 & v4.13.2, but not on v4.13.1.

**Comment by joshuaellis** [comment] 2023-09-08 10:25
this is a duplicate of #17931 which was solved by #17967 and will be released in the next release. You can use the PR to patch the your package if you so choose to do so.

**Closed by joshuaellis** 2023-09-08 10:25 UTC

**Comment by dgrebb** [comment] 2023-09-08 11:36
@joshuaellis after applying the patch, I do still see `window.strapi.backendURL` breaking `new URL()`, as it appears to be an empty string. Am I missing something?

<img width="498" alt="image" src="https://github.com/strapi/strapi/assets/445891/bf5655a1-b05d-48da-b92a-2cf2420cebc7">

Where does one manually set `STRAPI_ADMIN_BACKEND_URL`? I have not seen this come through in `npm run develop -- STRAPI_ADMIN_BACKEND_URL=http://localhost:1337` or `STRAPI_ADMIN_BACKEND_URL=http://localhost:1337 npm run develop`.

**Comment by joshuaellis** [comment] 2023-09-08 11:43
Thanks for raising this, we had assumed that `backendURL` had a fallback..... but maybe that's not the case...

**Comment by dgrebb** [comment] 2023-09-08 13:13
@joshuaellis I was going to ask if making the browser do the work is an OK solution. Looks like it is with #17982 😄.

Thanks again for looking into and adding a fix!

**Comment by dgrebb** [comment] 2023-09-08 14:07
@joshuaellis one more thought...

It may need to be `const urlObj = new URL(url, window.strapi.backendURL || `${window.location.protocol}//${window.location.host}`);`

`window.location.href` will have the full path (including query params for the media library), and `window.location.host` will only have `hostname` and `port`, but not protocol. The above covers usecases for both `http` and `https`.

Also, `??` appears to return `window.strapi.backendURL`, as it isn't null or undefined, but appears to be an empty string?

Hope this helps. Thank you again!

**Comment by joshuaellis** [comment] 2023-09-08 14:12
> @joshuaellis one more thought...
> 
> It may need to be:
> 
> ```js
> const urlObj = new URL(url, window.strapi.backendURL || `${window.location.protocol}//${window.location.host}`);
> ```
> 
> `window.location.href` will have the full path (including query params for the media library), and `window.location.host` will only have `hostname` and `port`, but not protocol. The above covers usecases for both `http` and `https`.
> 
> Also, `??` appears to return `window.strapi.backendURL`, as it isn't null or undefined, but appears to be an empty string?
> 
> Hope this helps. Thank you again!

Can you leave these comments on the PR please, very valuable :)
