### ISSUE TITLE
Deployment docs are MIA on v3.0 docs site

### ISSUE THREAD

**Issue by cube-dan** [strapi/strapi#6564] opened 2020-06-05 15:05 UTC
**Describe the bug**
Deployment docs missing at url: https://strapi.io/documentation/v3.x/getting-started/deployment

**Steps to reproduce the behavior**
1. Go to https://strapi.io/documentation/v3.x/getting-started/installation.html#deployment-guides
2. Click on  "related documentation" link
3. **BAM!** 404

![image](https://user-images.githubusercontent.com/8559668/83891895-bb28ae00-a702-11ea-9cb1-5fb12b7e2847.png)

Thanks for taking a look guys.

**Comment by derrickmehaffy** [comment] 2020-06-05 15:35
They are up, but for some reason the new docs are having issues with links: https://strapi.io/documentation/v3.x/getting-started/deployment.html

**Comment by cube-dan** [comment] 2020-06-05 17:03
Thanks Derrick, reading now. Just came back to suggest that the .html was missing from the link on the installation page. Meaning url: https://strapi.io/documentation/v3.x/getting-started/deployment => maybe should be: https://strapi.io/documentation/v3.x/getting-started/deployment.html on https://strapi.io/documentation/v3.x/getting-started/installation.html#deployment-guides

**Comment by derrickmehaffy** [comment] 2020-06-05 17:08
Yeah there are numerous cases of it, me and the Strapi team have been trying to debug it instead of forcefully hard coding it for every instance (this wasn't a problem in the beta docs, so something changed between beta/stable/new website that is causing it)

Would rather find the root cause then to hard code .html on everything because... no lol

**Comment by lauriejim** [comment] 2020-06-15 16:17
I'm closing this issue because of this one - https://github.com/strapi/strapi/issues/6368
Thank you for reporting it.

**Closed by lauriejim** 2020-06-15 16:17 UTC

**Comment by cube-dan** [comment] 2020-06-28 21:25
Thanks for the update guys. Keep up the great work!
