### ISSUE TITLE
Can't use Redis db for session storage in Strapi-Beta v3 

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#5417] opened 2020-03-04 18:34 UTC
**Describe the topic**

I can't use `Redis` db for saving session in `Strapi-Beta` v`3.0.0-beta.18.4`

I used Redis with `strapi-hook-redis` connector in Strapi-Alpha code and it worked. 
But in `Strapi-Beta` i not able to use  `strapi-hook-redis` connector,  it looks i need use` strapi-connector-redis` in v3: https://github.com/strapi/strapi/blob/v3.0.0-beta.18.4/packages/strapi-database/lib/require-connector.js#L19  but i couldn’t find `strapi-connector-redis` connector/plugin.

**Your suggestions for this topic** 
I should be able to use Redis db for saving session with connector

**Code snippets**
<img width="629" alt="database json — radar-cms 2020-03-04 20-01-25" src="https://user-images.githubusercontent.com/23507845/75940556-0d7fd780-5e53-11ea-9fc9-41305d330f39.png">

**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-beta.18.4
- Database: Mongo & Redis
- Operating system: MAC

**Additional context**

**Comment by derrickmehaffy** [comment] 2020-03-10 07:38
Duplicate of https://github.com/strapi/strapi/issues/5433

@vinod77 currently Strapi aren't supporting Redis, you are welcome to follow the tracking discussion here: https://github.com/strapi/strapi/issues/3866 to building a community version but so far there has been no action on it.

**Closed by derrickmehaffy** 2020-03-10 07:38 UTC

**Comment by gtamas** [comment] 2020-07-23 16:22
@derrickmehaffy 
Any news on this?

If Redis is still not supported, what other options do we have right now? Only cookie?

I need some persistent storage, even MongoDB would be good. I also need the ability to invalidate / destroy sessions programmatically and I cannot do that with the cookie.  Please help! :)

**Comment by derrickmehaffy** [comment] 2020-07-23 17:15
> @derrickmehaffy 
> Any news on this?
> 
> If Redis is still not supported, what other options do we have right now? Only cookie?
> 
> I need some persistent storage, even MongoDB would be good. I also need the ability to invalidate / destroy sessions programmatically and I cannot do that with the cookie (I can but I have to write custom code).  Please help! :)

No news yet, you could build a custom option as others have integrated redis into their projects directly or via plugins/middleware (the cache middleware created by the community is a good example of that). But currently we don't have any internal plans yet to work on this in the short term future.

I'll bring it up with the team to see about possibly adding this into the v4 plan (among other popular redis usecases)

**Comment by gtamas** [comment] 2020-07-23 18:31
OK I see! Thanks for the info!

**Comment by cosydney** [comment] 2021-02-02 16:28
Hey, curious to know if you've got any update on redis ? The link to track the feature isn't valid anymore.

**Comment by derrickmehaffy** [comment] 2021-02-02 17:16
@cosydney can you open a new issue regarding the session middleware? This needs a refactor but it would be good to have an actual bug report for it.

https://github.com/strapi/strapi/blob/master/packages/strapi/lib/middlewares/session/index.js

**Comment by cosydney** [comment] 2021-02-03 17:34
Hey @derrickmehaffy, thanks I might actually go with agenda thanks for your response though
