### ISSUE TITLE
chrome --inspect

### ISSUE THREAD

**Issue by q-jason** [strapi/strapi#2846] opened 2019-02-19 02:43 UTC
Sorry my English is not very good.
I want to use chrome --inspect feature.
Excuse How to use?

```bash
node --inspect main.js
```

**Comment by Nowhy** [comment] 2019-02-19 06:49
![image](https://user-images.githubusercontent.com/14275418/52995405-8208f380-3455-11e9-8047-a714bfeea6d4.png)

**Comment by Nowhy** [comment] 2019-02-19 06:50
yes... node --inspect server.js
My project works.

**Comment by q-jason** [comment] 2019-02-19 07:04
@Nowhy

node server.js not hot load...

**Comment by Nowhy** [comment] 2019-02-19 07:29
==
which file contains "strapi.start()"...pls use that one

**Comment by derrickmehaffy** [comment] 2019-02-19 08:19
@q-jason As this is not a bug report nor a feature request I am marking this issue as closed. For questions please use the Slack: https://slack.strapi.io

You may still reply on this issue, but it is marked as closed.

**Closed by derrickmehaffy** 2019-02-19 08:19 UTC
