### ISSUE TITLE
Bug: not duplicated values for enum field could not be saved

### ISSUE THREAD

**Issue by dfang** [strapi/strapi#13441] opened 2022-06-01 09:27 UTC
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.1.2
- Strapi version: 4.1.12
- Database: pg
- Operating system: macOS

### Steps to reproduce the behavior

1. Go to 'collections types'
2. add a Content-Type
3. add a enum

### Expected behavior

the form could be saved

### Screenshots

<img width="484" alt="image" src="https://user-images.githubusercontent.com/1277047/171372453-c90e62ec-aa64-4464-bbea-fe2c2abfe623.png">

if the values are 

```
basic
intermediate
senior
```

the form could be saved, replaced with corresponding chinese (and it's not duplicated), it can't be saved.

**Comment by derrickmehaffy** [comment] 2022-06-01 15:52
appears to be a duplicate of: https://github.com/strapi/strapi/issues/13017

**Closed by derrickmehaffy** 2022-06-01 15:52 UTC
Labels: status: duplicate
