### ISSUE TITLE
Deleting/Updating content-type doesn't drop/migrate the database

### ISSUE THREAD

**Issue by piere129** [strapi/strapi#1114] opened 2018-05-04 09:32 UTC
**Informations**
- **Node.js version**: 9.9.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha 12.1.2
- **Database**: MySQL
- **Operating system**: Windows 10

**What is the current behavior?**

Deleting a content-type does not drop the database table in MySQL, & when I navigate to roles & permissions, I can still see the deleted content-type and edit its permissions. When i create a new user role however, it only shows the non-deleted content-types. So for some reason, the content-types don't get deleted from the memory of existing user roles

**Steps to reproduce the problem**

1) create content-type 
2) add a string field to it 
3) save
4) delete content-type
5) content-type is not in the list of content-types anymore but the database table still exists + the reference to the content-type remains in the roles & permissions folder of a user role, when editing permissions.

**What is the expected behavior?**

deleting a content-type should remove all references of this content-type ever existing + drop its database automatically. Dropping the database manually still doesn't make the reference to the content-type in roles & permissions disappear. Dropping the whole database and re-creating it does however fix the problem

**Suggested solutions**

N.A.

- [ x ] I'm sure that this issue hasn't already been referenced

**Comment by soupette** [comment] 2018-05-04 09:41
Hi @piere129!
As stated in #1025, we don't delete your tables we just create new ones, therefore the behavior you described is the correct one.

However, the behavior you about the `users-permissions` plugin is not the one expected.

**Comment by derrickmehaffy** [comment] 2018-05-04 10:04
@soupette for ease of use and general non-technical users I think the delete function is quite important. I referenced something similar with MongoDB before as well. If you create a endpoint, then remove it, it should drop those tables.

We wouldn't want in-experienced people having to drop tables manually in mysql, there is no case in which that is the proper way to handle it :P

**Comment by derrickmehaffy** [comment] 2018-05-04 10:05
If its not already in the works to do, I think its something that should be looked at again, I understand it isn't possible currently but in the future it will need to be. Everything should be possible via the adminUI.

**Comment by Aurelsicoko** [comment] 2018-05-07 09:53
@derrickmehaffy I don't agree, we have to think for more use cases. What happens if you start the project with a production database and one the model name doesn't match with one of the tables in your database? Do we drop it? No, we can't do that. We want to avoid as many as we can to delete tables and data. We don't want to be the cause of data loss.

I think the best solution is to add a strict mode where the database structure follows the exact same schema defined in the project. If this mode is disabled, we will only create or add new table/column without deleting anything (as it is currently the case). We could also imagine a button in the UI to clear all the unnecessary tables and columns. It means that the user understands what it does and we won't be blamed for data loss.

**Comment by derrickmehaffy** [comment] 2018-05-07 16:13
@Aurelsicoko I think the strict mode is a great solution, even if it's enabled by default. I just wanted to share my opinion that the delete functions shouldn't be axed completely to be used as a data safety net for inexperienced developers.

After all in order to learn from mistakes they have to be made by someone :) And by axing a, as I feel, a very important feature for the power users, it isolates us to use work aroundss that could cause further issues.

**Comment by derrickmehaffy** [comment] 2018-05-07 16:16
As a side note, I'm not sure with Mongo as I'm not as experienced with it, but with MySQL it is extremely easy to export a database as a backup. Obviously this is something that could be extremely taxing to the system. However it could prove useful if you needed to make a so called emergency backup before major deletes are done. Especially in regards to Strapi version changes where it's possible and update may break the database.

**Comment by Aurelsicoko** [comment] 2018-05-08 08:51
@derrickmehaffy We could generate a backup but it could be very long if the database has a lot of data... Could it be another option to add? Quick vs safe migration.

**Comment by derrickmehaffy** [comment] 2018-05-09 06:57
@Aurelsicoko thats exactly what I was thinking. Just as a quick side note, the same type of issue applies when you add an additional column to an already existing model/table. At this moment strapi will not add the new column and will error out in which you have to manually delete the table and restart the server for it to add the new column.

The backup would work in this case also I believe, but some additional thought should be put into how deletes happen. In this case you shouldn't need to delete the entire table to add a new column.

**Comment by derrickmehaffy** [comment] 2018-05-09 07:03
in regards to the backup I think a prompt on delete could appear with a slider checkbox to simply ask:
`Are you sure you wish to delete this model? N/Y` and `Would you like to create a backup of the database? Y/N' (Note the default values on the checkbox)

**Comment by Aurelsicoko** [comment] 2018-05-09 08:55
To resume our thoughts:

- Adding a **strict mode** that will remove the table when a content-type is deleted or when a relationship changes between two models (especially in a many-to-many case because it creates a relational table). In my opinion, we shouldn't enable this mode by default.
- **Quick vs safe** migration mode:
  -  **Quick** mode will rename, drop columns and tables.
  -  **Safe** mode will do the same but it will also create a backup before starting the work. It will be slower but the developer will be able to rollback if the migration doesn't work as expected. 

Both proposals are complementaries. If the *strict mode* is activated, then you will have to choose between the *quick or safe* mode. If the *strict mode* is disabled, the *quick or safe* mode is useless because nothing will be deleted.

**Comment by derrickmehaffy** [comment] 2018-05-09 09:00
That sounds exactly like what I was thinking @Aurelsicoko you just explained it a little easier. :+1: :)

**Comment by Aurelsicoko** [comment] 2018-05-09 09:06
Perfect, it sounds good to me as well!

**Comment by derrickmehaffy** [comment] 2018-07-17 09:29
@Aurelsicoko just curious do you have any update on this. I know you guys have quite a bit on your plate and wasn't sure where this landed in terms of the roadmap. Didn't know if any other further internal discussion happened as to the plans for this.

**Comment by Aurelsicoko** [comment] 2018-07-20 09:26
@derrickmehaffy Nothing has been planned so far... It's not something very important, the clean of the columns/tables can be done manually. It would be better to automatically handle the cleaning but the projects are still working even if there are useless columns & tables (this is the most important).

**Comment by lnaie** [comment] 2018-09-04 14:11
yes, i've just noticed that today. and it breaks most of content type managing screens. i had to create a new content type with a different name and remove them manually from mongodb.

guys, great product, but before adding more features, please get to stabilize what you have.

also post a roadmap, visibly. ;)

**Comment by Aurelsicoko** [comment] 2018-09-06 08:53
@lnaie @tonyberetini I understand your point if you're able to help almost everything has been detailed in this issue. We are doing our best, there are so many topics where we have to make improvements. We are not adding a lot of features but we are making a lot of enhancements to make Strapi more usable in production.

**Comment by dwehrmann** [comment] 2018-10-03 18:43
I'm at exactly the same situation right now. While developing a strapi-/gatsby site, 80% done, I noticed some of my tables should be renamed. It's a pity this cannot be handled in the strapi backend.

**Comment by dwehrmann** [comment] 2018-10-03 18:57
To be precise, I understand that under the hood the actual behaviour is that strapi does not "rename" the table but create a new one which is of course empty. 

As any user would expect not to lose the data in the original table when trying to rename a table, it would be nice if strapi could create a new table, copy over the original table's contents and reference the new table from there on. User = happy.

@Aurelsicoko is there a workaround for the time being? Btw, I'm currently using mongodb.

**Comment by derrickmehaffy** [comment] 2018-10-03 18:59
@dwehrmann this would be quite complex, as strapi doesn't "remember" the old name, it will overwrite the model file, which is used by the hooks (mongoose and bookshelf/knex) to construct the database.

I'm sure it is possible, but would require some major modifications. That being said I also would like to see this.

**Comment by dwehrmann** [comment] 2018-10-03 19:59
@derrickmehaffy I see. I think this is over my head, otherwise I'd be happy to help. This would be a great help, usability-wise.

As a workaround for now, I have taken the following steps – maybe this helps someone else:
with mongo 3.4.10:

- create a new (string) field in strapi with the correct name using the content type builder
- restart strapi (feels better to see the new field)
- enter mongo shell
- `use.<yourCollection>`
- `db.getCollection('<collection_name>').update({}, {$rename:{"<old_fieldName>":"<new_fieldName"}}, false, true);`

worked for me. Don't forget to adjust the queries in your application to the new field names.

**Comment by lauriejim** [comment] 2018-10-04 14:48
Thank you for your feedback @dwehrmann .

**Comment by connectwithub** [comment] 2018-12-23 17:32
Hi, 
Any update on this matter?

**Comment by lauriejim** [comment] 2018-12-23 17:50
We are not actually working on it, we will give an update when we will start this topic.

**Comment by lauriejim** [comment] 2020-09-24 13:36
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/deploying-model-and-database-migrations/83/2

**Comment by lauriejim** [comment] 2020-10-13 13:50
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/error-relation-already-exists/406/2

**Comment by lauriejim** [comment] 2020-10-13 15:43
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/strapi-doesnt-delete-content-type-field/395/3

**Comment by derrickmehaffy** [comment] 2021-01-13 08:43
**Unlocking thread for people to provide suggestions or additional info**

Please do not comment here asking for an ETA or a timeline, we have a **rough** idea for this in Q3 2021 but there is no guarantee. This is a sensitive subject and we want to do it right, not fast.

**Comment by derrickmehaffy** [comment] 2021-02-01 21:52
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/env-setup-for-production-and-local-development/242/42

**Comment by BodhiKatha** [comment] 2021-03-23 04:48
@Aurelsicoko, I m using Strapi 3.5.3 and MySQL 5.7.31.

database.js:

module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'mysql',
        host: env('DATABASE_HOST', '127.0.0.1'),
        port: env.int('DATABASE_PORT', 3306),
        database: env('DATABASE_NAME', 'beta'),
        username: env('DATABASE_USERNAME', 'root'),
        password: env('DATABASE_PASSWORD', ''),
        ssl: env.bool('DATABASE_SSL', false),
        collation: 'latin1_swedish_ci'
      },
      options: {
        strict: 'true',
        collation: 'latin1_swedish_ci'
      }
    },
  },
});

I tried using strict mode, but to no avail. The MySQL db still contains the content type table and fields. Has there been any changes since this workaround? I am pretty new to strapi and I am kinda stuck. :) Cheers!

**Comment by BodhiKatha** [comment] 2021-03-23 05:16
I’m very new to Strapi (version) 3.5.3 and MySQL 5.7.31.

Deleting a content type doesn’t delete the table/fields from the db. I tried using strict mode (with reference to issue no.1114, but to no avail. The MySQL db still contains the content type table and fields.
database.js:

```
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'mysql',
        host: env('DATABASE_HOST', '127.0.0.1'),
        port: env.int('DATABASE_PORT', 3306),
        database: env('DATABASE_NAME', 'beta'),
        username: env('DATABASE_USERNAME', 'root'),
        password: env('DATABASE_PASSWORD', ''),
        ssl: env.bool('DATABASE_SSL', false),
        collation: 'latin1_swedish_ci'
      },
      options: {
        strict: 'true',
        collation: 'latin1_swedish_ci'
      }
    },
  },
});
```
Has there been any changes since this workaround? I am pretty new to strapi and I am kinda stuck. Cheers!

**Comment by derrickmehaffy** [comment] 2021-03-23 21:15
@BodhiKatha Not currently, we are planning to address it in Q3 2021 per my previous update: https://github.com/strapi/strapi/issues/1114#issuecomment-759297723

For the moment you will need to manually migrate/clean your database using .sql migration scripts.

**Comment by derrickmehaffy** [comment] 2021-04-05 16:39
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/error-relation-already-exists/406/6

**Comment by derrickmehaffy** [comment] 2021-04-09 17:46
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/deleting-old-fields-from-the-api-response/4067/4

**Comment by derrickmehaffy** [comment] 2021-05-17 17:50
> I'm running strapi in production and I'm very disappointed to see this hasn't been solved before 
> 
> > I think the best solution is to add a strict mode where the database structure follows the exact same schema defined in the project. If this mode is disabled, we will only create or add new table/column without deleting anything (as it is currently the case). We could also imagine a button in the UI to clear all the unnecessary tables and columns. It means that the user understands what it does and we won't be blamed for data loss.
> 
> Or just generate migrations files, so that the user can version, review and customize database migrations, instead of doing unexpected changes to the database. Having both strapi-managed and user-managed migrations is pretty painful and offer poor developer experience. I'd love to see a proper migration system in Strapi.

We are already planning that in the Strapi v4, we will have more information once the RFC is ready to be released as I mentioned in https://github.com/strapi/strapi/issues/1114#issuecomment-805265946

**Comment by derrickmehaffy** [comment] 2021-08-09 20:23
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/server-wasnt-able-to-start-properly/9352/2

**Comment by derrickmehaffy** [comment] 2021-11-30 14:10
FINALLY!

Fixed in v4, marking as closed

**Closed by derrickmehaffy** 2021-11-30 14:10 UTC
Labels: type: enhancement, severity: medium, source: core:framework

**Comment by olayinkade** [comment] 2022-08-02 18:15
> FINALLY!
> 
> Fixed in v4, marking as closed

This comment mentions the issue has been fixed but doesn't mention the solution we should adopt. is it still the strict mode in the database.js file? There is no example on the Strapi official documentation

**Comment by derrickmehaffy** [comment] 2022-08-02 22:48
> > FINALLY!
> > 
> > Fixed in v4, marking as closed
> 
> This comment mentions the issue has been fixed but doesn't mention the solution we should adopt. is it still the strict mode in the database.js file? There is no example on the Strapi official documentation

There is no configuration for this as we will just delete the column/table on reboot when it's deleted. We did discuss a warning or a safer method but opted not to do it in v4.

When you use v4 we will simply clean up the database for you.

**Comment by simongcc** [comment] 2022-10-12 12:53
I am just trying Strapi 4.4.1 with testing database of sqlite and postgres.
1 If I create a plugin and add content-type to it > build then adding data
2 then I comment out the export scheme pretending to remove it > build 
3 then I remove the comment and let the content-type being exported again > build

The database table is regenerated with a new one or being deleted, the previous data are gone. Is this a desired and default behaviour in current version?
How to prevent data loss or what is the suggested method to preserve the data?
Because careless developer might comment out the content-type in a plugin. Then even though the test data will be gone for not sure if it is good.

**Comment by derrickmehaffy** [comment] 2022-10-14 19:02
Yes this is currently intended (as you deleted the schema effectively), the best method to hold onto the data is take a database backup.

Certainly any modifications a dev is making should be tested in a staging environment. If you are simply renaming a content-type or field then you will have to (for now) write a custom migration: https://docs.strapi.io/developer-docs/latest/developer-resources/database-migrations.html

**Comment by GLorenz90** [comment] 2022-12-06 16:20
> @derrickmehaffy I don't agree, we have to think for more use cases. What happens if you start the project with a production database and one the model name doesn't match with one of the tables in your database? Do we drop it? No, we can't do that. We want to avoid as many as we can to delete tables and data. We don't want to be the cause of data loss.
> 
> I think the best solution is to add a strict mode where the database structure follows the exact same schema defined in the project. If this mode is disabled, we will only create or add new table/column without deleting anything (as it is currently the case). We could also imagine a button in the UI to clear all the unnecessary tables and columns. It means that the user understands what it does and we won't be blamed for data loss.

It absolutely kills me that this incredibly sane solution was not the one y'all went with, especially after seeing that after the change a bunch of people lost a lot of data. This is possibly the biggest breaking change I've ever seen implemented in a project that could have been avoided. Please for the love of all that is good add back in strict mode. Just because most people aren't senior devs, doesn't mean no one is. We were so excited to use strappi, but for almost every one of our clients we would want to use this for there is existing data that we would still like to have available for migration later, or for other custom components we don't want in the admin. This one lack of a feature will take strappi off the board for us if a work around is not easy to implement.

**Comment by sundowndev** [comment] 2022-12-07 07:17
> We were so excited to use strappi, but for almost every one of our clients we would want to use this for there is existing data that we would still like to have available for migration later, or for other custom components we don't want in the admin. This one lack of a feature will take strappi off the board for us if a work around is not easy to implement.

@GLorenz90 I came across nearly the same experience and ended up thinking Strapi is still not ready for production. It shouldn't have reached a stable version, as there was still design issues and problems to solve. It's so confusing to have such issues with what seems to be a mature product.

I discovered [pocketbase](https://github.com/pocketbase/pocketbase) recently which addresses the db migration problem much better and has a better versioning strategy.

**Comment by derrickmehaffy** [comment] 2023-01-05 20:26
> With this functionality, it makes it exceedingly hard to work on a strap project in development.
> 
> What happens when you need to change branch to check a different feature? All your data is deleted.
> 
> What happens when you're doing a merge and the site is still on? All your data is deleted.
> 
> With this change, the development environment becomes so brittle as to almost become unusable for anything more than the simplest of workflows (one feature at a time)
> 
> Is it the suggestion of Strapi for every developer to roll their own custom backup-solution, and to take backup before each and every branch change?

eventually that will be the purpose of our DEITS feature: https://forum.strapi.io/t/data-import-export-open-beta-v4-6-0-beta-x/24443

**Comment by kristijorgji** [comment] 2023-11-15 10:45
I can't delete content type in new strapi version.
https://github.com/strapi/strapi/issues/18799

help me in the issue with steps to delete some content type

**Comment by er-santosh** [comment] 2023-11-28 09:32
I am encountering the same issue of not able to delete the content types. 
Actual behavior of my project is like content type folder from api/  gets deleted when i delete but it still appears in admin dashboard. And now on delete it throws error on deletion.

Also i tried to run 
`yarn strapi content-types:list` and the deleted content type still appears iin the list.
`yarn strapi ts:generate-types` is also unable to update the generated contenttypes since its already deleted.

Help me in this issue.

**Comment by er-santosh** [comment] 2023-11-28 10:03
> I can't delete content type in new strapi version. #18799
> 
> help me in the issue with steps to delete some content type

@kristijorgji if you are also facing issue like me as mentioned above. You can restart the serve after deleting .strapi/ dist/ and all the types from contentTpes.d.ts.

**Comment by up_the_irons** [comment] 2024-06-03 03:59
I came upon this thread from the link in the documentation:
https://docs.strapi.io/user-docs/content-type-builder/managing-content-types

I am confused by the statement under heading "Deleting content-types" that reads: "All the data that was created based on that content-type is however kept in the database."  Is this out-dated?  I removed a content type in my relatively recent Strapi install, and it killed the database table on its own.  It was the intended behavior in my case, so no worries, but I just wanted to get clarification on the issue...

**Comment by sokhuong-uon** [comment] 2024-06-15 04:57
Does this setting delete the entire database?
```json
"options": {
  "strict": "true"
}
```

**Comment by derrickmehaffy** [comment] 2025-01-14 00:38
> I came upon this thread from the link in the documentation: [docs.strapi.io/user-docs/content-type-builder/managing-content-types](https://docs.strapi.io/user-docs/content-type-builder/managing-content-types)
> 
> I am confused by the statement under heading "Deleting content-types" that reads: "All the data that was created based on that content-type is however kept in the database." Is this out-dated? I removed a content type in my relatively recent Strapi install, and it killed the database table on its own. It was the intended behavior in my case, so no worries, but I just wanted to get clarification on the issue...

It is intentional, I believe we have since fixed that documentation but yes it will delete the data as well.

**Comment by daguttt** [comment] 2025-03-19 16:53
I just came from the [Beta docs](https://docs-next.strapi.io/cms/features/content-type-builder#configuring-fields-content-type) from the same callout. @derrickmehaffy, it seems the docs hasn't been fixed relating to the current behavior @up_the_irons mentioned

**Comment by jameshome** [comment] 2025-07-03 00:12
Docs now give no indication that they are beta and [still say this](https://docs.strapi.io/cms/features/content-type-builder#deleting-content-types).
