### ISSUE TITLE
Component in collection "No permissions to see this field" for super admin

### ISSUE THREAD

**Issue by sereda93** [strapi/strapi#9200] opened 2021-01-23 18:47 UTC
## Bug report
Component in collection "No permissions to see this field" for super admin
### Describe the bug
When creating a collection item, I see an error for the component field. I'm logged in as a super admin

### Steps to reproduce the behavior

1. Go to 'edit collection and add field (some component)'
2. Open collection item
3. I see "No permissions to see this field" for added component

### Screenshots
![image](https://user-images.githubusercontent.com/2189429/105611004-95e4cf00-5dbb-11eb-827b-a5642bea8651.png)
![image](https://user-images.githubusercontent.com/2189429/105611112-228f8d00-5dbc-11eb-9ee5-af8777bc6a95.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.4.1
- Database: sqlite3
- Operating system: windows 10

**Comment by sereda93** [comment] 2021-01-24 10:17
I found the reason. There were no fields in the child components.
Maybe in this case you should to output some other error.

**Comment by derrickmehaffy** [comment] 2021-01-25 21:11
Marking as closed as the user did find the error but it's also a duplicate of: https://github.com/strapi/strapi/issues/9194

**Closed by derrickmehaffy** 2021-01-25 21:11 UTC
