### ISSUE TITLE
Cannot read attributes of undenfined on relation created

### ISSUE THREAD

**Issue by purrplingcat** [strapi/strapi#1652] opened 2018-07-26 19:36 UTC
**Informations**
- **Node.js version**: 10.7.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.13.0.1
- **Database**: MongoDB
- **Operating system**: Windows 7 (I am developing on)

**What is the current behavior?**

I created two content types: Article and ArticleType. When I try to create relation between `Article` and `ArticleType` on Article typ ArticleType has many Articles, then I got:

```
[2018-07-26T19:19:28.624Z] error Something went wrong in the model `Article` with the attribute `articleType`
[2018-07-26T19:19:28.628Z] error Cannot read property 'attributes' of undefined
```

And strapi server crashed and I can't run it, because this errors.

**Steps to reproduce the problem**

1. Create content type `Article`
2. Create content type `ArticleType`
3. Make relation on `Article` to `ArticleType` type `ArticleType` has many `Article`
4. Click "Save"
- THEN loading bar shown
- AND strapi server crashed with error *Cannot read property 'attributes' of undefined*

**What is the expected behavior?**

Strapi server not crashed after create a relation and relation has successfully created and works.

**Comment by mnlbox** [comment] 2018-07-28 01:57
I also see this error in any strapi project. It's because of an old admin ui bug. You need to add 1:N or N:1 relation manually (from code and without admin ui) until a working fix.

**Comment by lauriejim** [comment] 2018-07-29 12:48
Hello @purrplingcat , this issue looks to be a duplicate of this one https://github.com/strapi/strapi/issues/1139

**Closed by lauriejim** 2018-07-29 12:48 UTC
