### ISSUE TITLE
Newly registered user login error:

### ISSUE THREAD

**Issue by wangyuks** [strapi/strapi#4734] opened 2019-12-16 10:17 UTC
Newly registered user login error:
`{
    "statusCode": 400,
    "error": "Bad Request",
    "message": [
        {
            "messages": [
                {
                    "id": "Auth.form.error.invalid",
                    "message": "Identifier or password invalid."
                }
            ]
        }
    ]
}`

**Comment by soupette** [comment] 2019-12-16 10:52
I'm closing this issue as it doesn't follow the issue template and also it seems a duplicate of #4735

**Closed by soupette** 2019-12-16 10:52 UTC
