### ISSUE TITLE
Bug: cannot open the admin dashboard

### ISSUE THREAD

**Issue by mirfmaster** [strapi/strapi#12602] opened 2022-02-20 14:32 UTC
## Bug report

I don't know why I can't open the admin dashboard, but this is what I found on the console and it seems to block me to open the admin dashboard.

Is there any workaround for this issue?

### Describe the bug

Cannot open the admin dashboard

### Steps to reproduce the behavior

1. npm run develop
2. go to http://127.0.0.1:1337/admin
3. see the error

### Expected behavior

open the admin page

### Screenshots
![image](https://user-images.githubusercontent.com/37706944/154847492-022955ab-827e-41f5-bb47-56e0c4675e1b.png)
![image](https://user-images.githubusercontent.com/37706944/154847672-0ace515d-76d9-4e2d-9531-e0914f6f73df.png)

### System

- Node.js version: v16.14.0
- NPM version: v8.3.1
- Strapi version: v. 4.0.7
- Database: mysql
- Operating system: linux mint cinnamon 20

### Additional context

I've tried to restart the laptop, reinstalling the node_modules.  But if I hit the endpoint it's still working

**Comment by kasonde** [comment] 2022-02-22 07:03
I'm currently unable to reproduce this issue using the instructions provided. Is this happening with a completely newly generated Strapi application as well? i.e for all Strapi projects on your machine? Do you have any proxy service running locally on your machine like ngrok, or nginx?

**Comment by mirfmaster** [comment] 2022-02-23 01:52
Hi, @kasonde thanks for the response, since I need to race with the deadlines I've decided to rebuild the cms with laravel.

currently, I'm not running any proxy service, yesterday I hit the admin page with history URL i.e (URL to content-manager) and it was working. even I tried with button Open the administration and it worked. but since I have configuration auto-remove history for 3 days, so currently it's still bugging. Maybe later I will try to generate a fresh Strapi application

but here is the detailed problematic request, hope it helps.
![image](https://user-images.githubusercontent.com/37706944/155248718-88f0e1bc-347f-44ba-9c6f-408ff03ec41d.png)
![image](https://user-images.githubusercontent.com/37706944/155249587-72eb3c34-a7b1-430b-a7b2-f9aefea61ab8.png)

**Comment by derrickmehaffy** [comment] 2022-02-23 20:27
I'm also a linux mint user (20.3) and I can't reproduce this, but what I find interesting is your 127.0.0.1 requests return fine however your localhost one doesn't meaning you might have a problem with the resolution of localhost.

Either way I don't believe this is a Strapi issue but likely an isolated environment issue. We need more information to reproduce, marking as closed for now as there isn't much we can do to "fix" this

**Closed by derrickmehaffy** 2022-02-23 20:27 UTC
Labels: status: pending reproduction
