### ISSUE TITLE
Cannot open localhost:1337/admin

### ISSUE THREAD

**Issue by VitorHUMoreira** [strapi/strapi#9864] opened 2021-03-29 19:36 UTC
### Describe the bug

I'm trying to create my first project using Strapi, but the http://localhost:1337/admin does not open correctly, displays the following error: HTTP ERROR 426 (Upgrade Required).

### Steps to reproduce the behavior

1. Create new project with "yarn create strapi-app my-project ".
2. Using manual settings to use Postgres as host 127.0.0.1 and port 5432.
3. Ffter the application is successfully created, I run " yarn develop".
4. The browser open "localhost:1337/admin" but shows the error mentioned above.

### Expected behavior

Open the administration panel.

### System

- Using WSL2 in Windows 10 x64
- Operating system: Ubuntu 20.04
- Node.js version: v14.16.0
- NPM version: 6.14.11
- Yarn version: 1.22.10
- Strapi version:  3.5.4
- Database: Postgres 12.6

**Comment by derrickmehaffy** [comment] 2021-03-29 21:18
Please provide your `./config/server.js` and `./config/database.js` as I'm not able to reproduce this on Windows 10 using WSL2

**Comment by VitorHUMoreira** [comment] 2021-03-29 21:25
**server.js**
`module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', '600760fb936bd953de2aa9bbac963d7c'),
    },
  },
});`

**database.js**
`module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: env('DATABASE_HOST', '127.0.0.1'),
        port: env.int('DATABASE_PORT', 5432),
        database: env('DATABASE_NAME', 'tcc'),
        username: env('DATABASE_USERNAME', 'tcc'),
        password: env('DATABASE_PASSWORD', 'tcc123'),
        ssl: env.bool('DATABASE_SSL', false),
      },
      options: {}
    },
  },
});`

**Comment by VitorHUMoreira** [comment] 2021-03-29 21:41
**server.js**

`module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', '600760fb936bd953de2aa9bbac963d7c'),
    },
  },
});`

**database.js**

`module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: env('DATABASE_HOST', '127.0.0.1'),
        port: env.int('DATABASE_PORT', 5432),
        database: env('DATABASE_NAME', 'tcc'),
        username: env('DATABASE_USERNAME', 'tcc'),
        password: env('DATABASE_PASSWORD', 'tcc123'),
        ssl: env.bool('DATABASE_SSL', false),
      },
      options: {}
    },
  },
});`

**Comment by derrickmehaffy** [comment] 2021-03-29 22:27
I still am unable to reproduce it using your configs (swapping out the database name, user, and password.

**Comment by derrickmehaffy** [comment] 2021-03-29 22:27
We need additional information to confirm this bug.

**Comment by VitorHUMoreira** [comment] 2021-03-29 22:59
This problem cannot be related to the use of WSL2? Or something related to use of ports?

In Windows running the CMD as administrador and force killing the task with port 1337, and back to WSL2 terinal and run "yarn develop" again it works, but for a short period of time.

**Comment by nir099** [comment] 2021-03-30 14:18
Hey, I'm also using wsl2,  and I'm also facing the same error, 

![image](https://user-images.githubusercontent.com/33232105/112997384-b39f2d80-918a-11eb-9e47-2dec4227c4e6.png)


I have changed the port to 3001.
the interesting fact is when I click  http://127.0.0.1:3001/admin 

![image](https://user-images.githubusercontent.com/33232105/112997604-e5b08f80-918a-11eb-8ca7-34acc09d49c5.png)


it's opening on entire different port 

![image](https://user-images.githubusercontent.com/33232105/112997732-ff51d700-918a-11eb-8966-03f764c1d6a4.png)


this should be a port forwarding issue on windows and wsl2. 

if I kill the port and run the application it will again open on a different port.
and it seems the port number is increased each time. ex-> 3495, 6941, 7137 

and the process Id display in here 

![image](https://user-images.githubusercontent.com/33232105/113002443-670a2100-918f-11eb-803e-feb2f69f57a5.png)

is not matching for the machine process ID.

![image](https://user-images.githubusercontent.com/33232105/113002624-9b7ddd00-918f-11eb-896e-64a748b7401e.png)


The port is changing every time I start/restart the machine.

I have tried with different environments too, but the result is the same.
node - 12.19.0
npm - 6.14.8
strapi- 3.5.2

**Comment by derrickmehaffy** [comment] 2021-03-31 21:56
This appears to be outside the Strapi ecosystem and is functionally either a bug (or "feature" if you ask Microsoft).

I would start by trying to file a bug with the team behind WSL2, I still am unable to replicate it on both of my physical windows machines and my 3 windows virtual machines.

**Comment by nir099** [comment] 2021-04-02 05:45
The Issue was resolved with the latest windows update! thank you for the concern.

**Comment by derrickmehaffy** [comment] 2021-04-09 18:07
Marking as closed as it's confirmed this is outside Strapi's control.

**Closed by derrickmehaffy** 2021-04-09 18:07 UTC
Labels: status: can't reproduce

**Comment by LudoVio** [comment] 2021-10-31 01:35
I would like to reopen this issue as it is currently happening to me. 
I also develop other node.js applications like express and Next.js, running servers from wsl2 to all kind of ports. I can access all those apps without any problems via the same port I setup for the servers. The problem is only happening with Strapi.

**Comment by derrickmehaffy** [comment] 2021-10-31 01:38
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
