### ISSUE TITLE
[Custom Field] custom option not assignable to type 'CustomFieldOptionName' when using type `StrapiApp` on `register(app)`

### ISSUE THREAD

**Issue by Da-nie-elT** [strapi/strapi#22364] opened 2024-12-07 18:03 UTC
### Required System information

- Node.js version: **v20.17.0**
- NPM version: **10.9.0**
- Strapi version: **5.4.2**
- Database: **sqlite**
- Operating system: **Win10 - win32-x64**
- Is your project Javascript or Typescript: **Typescript**

### Describe the bug

When registering a plugin in 'admin/src/index' you can use the type `StrapiApp` from  '@strapi/strapi/admin'.

Adding a custom option to a custom field during registration you get a console error saying `"Uncaught (in promise) Invariant Violation: 'customOption' must be prefixed with 'options.'"`.
But it's not assignable to type 'CustomFieldOptionName'. Only `"required" | "max" | "maxLength" | "min" | "minLength" | "default" | "regex" | "enum" | "unique" | "private"` are allowed.

### Steps to reproduce the behavior

1. Create a plugin.
2. In `admin\src\index.ts` import `{ type StrapiApp } from '@strapi/strapi/admin';`
3. use the type in `register(app: StrapiApp) {`
4. Register a custom field.
5. Add a `CustomFieldOption` with a custom name.
6. see ts error on the `name` property of the custom field advanced option.

### Code snippets

```typescript
import { type StrapiApp } from '@strapi/strapi/admin';
import { PLUGIN_ID } from './pluginId';

export default {
  register(app: StrapiApp) {
    app.customFields.register({
      name: PLUGIN_ID,
      pluginId: PLUGIN_ID,
      type: 'string',
      intlLabel: {
        defaultMessage: 'Label'
      },
      intlDescription: {
        defaultMessage: 'description'
      },
      components: {
        Input: async () => import('./components/CustomInput')
      },
      options: {
        advanced: [
          {
            type: 'text',
            name: 'options.customOption',
            intlLabel: {},
            description: {}
          }
        ]
      }
    });
  }
};
``` 

### Expected behavior

Allow 'options.[...]' on type `CustomFieldOptionName`
(`description` should also be optional)

**Comment by derrickmehaffy** [comment] 2024-12-12 19:29
duplicate of https://github.com/strapi/strapi/issues/21151

**Closed by derrickmehaffy** 2024-12-12 19:29 UTC
