### ISSUE TITLE
Unable to use migrations - db.getConnection(...).transaction is not a function

### ISSUE THREAD

**Issue by bulby97** [strapi/strapi#12723] opened 2022-03-02 22:57 UTC
### Describe the bug

When creating js or sql file in the `databases/migrations` folder, I get an error

```js
db.getConnection(...).transaction is not a function
```

### Steps to reproduce the behavior

1. Create a sql or js file in `databases/migration`
2. Run strapi
3. See error

### Expected behavior

Migrations should work without error

### Screenshots

<img width="369" alt="image" src="https://user-images.githubusercontent.com/3509412/156463616-1843e425-f19a-478a-a9df-08155fbf474a.png">

### System

- Strapi version: 4.1.2
- Database: Postgres
- Operating system: OSX

**Comment by derrickmehaffy** [comment] 2022-04-18 20:26
Can't reproduce on v4.1.8, see the arrow in the screenshot showing that the file was ran without error. Need more information on what was in the migration file.

Marking as closed until we get new information

![image](https://user-images.githubusercontent.com/8593673/163872488-2c17d3b6-c1f1-43c7-960e-77fb759a0926.png)

**Closed by derrickmehaffy** 2022-04-18 20:26 UTC
Labels: issue: bug, severity: low, source: core:database, status: pending reproduction
