### ISSUE TITLE
[v4] Strapi APIs Fail with 404 error after uploading to cpanel

### ISSUE THREAD

**Issue by Thando-James** [strapi/strapi#13371] opened 2022-05-21 14:31 UTC
### Required System information

- Node.js version: v16
- NPM version:  v8.5.5
- Strapi version: v4.1.11
- Database: sqlite
- Operating system: Cloud linux

### Describe the bug

After uploading v4 of strapi onto my cpanel server, there are some strapi apis that return a 404 error. I am unable to set permissions for roles or add entries for some of my collections/single types. The error I get when I try to set permissions for a certain role is the following:
![Screenshot 2022-05-21 at 15 55 16](https://user-images.githubusercontent.com/20462145/169655494-b3d006a7-dc6f-4a4a-a887-a9edde4f9bbf.png)

And when I try to add entries on one of my single types i get the following error:
![Screenshot 2022-05-21 at 15 52 51](https://user-images.githubusercontent.com/20462145/169655510-00a1280b-0bce-44e6-bbdf-b810eab31eb1.png)

I tried replicating this locally and I could not. it works as expected locally on my machine but when I upload it to the server, i get the above issues.
I have created a temporary admin to allow you to see this error for yourselves. 

### Steps to reproduce the behavior

1. Go to api.mtsd.co.za/admin
2. Log in using the credentials: test@gmail.com Passw0rd
3. Click on Settings and got the the roles option under the users and permissions plugin
4. Click on the public role and set some permissions for some of the collections available
5. See error

### Expected behavior

To be able to set permissions to a role

### Screenshots

![Screenshot 2022-05-21 at 15 52 51](https://user-images.githubusercontent.com/20462145/169655510-00a1280b-0bce-44e6-bbdf-b810eab31eb1.png)
![Screenshot 2022-05-21 at 15 55 16](https://user-images.githubusercontent.com/20462145/169655494-b3d006a7-dc6f-4a4a-a887-a9edde4f9bbf.png)

**Comment by derrickmehaffy** [comment] 2022-05-23 20:06
It would appear you have configured the domain for this incorrectly and it looks like you tried to remove the prefix which isn't supported. For example the content manager should be at `/admin/content-manager/collectionType/api::faq.faq` not `/content-manager/collectionType/api::faq.faq`

However I'm going to close this as it's not a bug but an environmental issue/configuration issue

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io) or our [Discord](https://discord.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Closed by derrickmehaffy** 2022-05-23 20:06 UTC
