### ISSUE TITLE
The select on the UI are not working since v4.4.2

### ISSUE THREAD

**Issue by squelix** [strapi/strapi#14699] opened 2022-10-21 13:34 UTC
### Required System information

- Node.js version: v16
- NPM version: v8
- Strapi version: Since 4.4.2 to 4.4.5 version
- Database: Postgres
- Operating system: Heroku so i guess

### Describe the bug

All the select on the UI are not working and i don't know why :/ 

### Steps to reproduce the behavior

1. Update to 4.4.2 or most recent version until 4.4.5
2. Run `npm install`
3. Run `npm run build`
4. Run `npm run start`

### Expected behavior

The selects should work.

### Screenshots

https://user-images.githubusercontent.com/3955239/197208404-b5b8447f-e2d0-419e-8fd0-48ebfc2ad3f9.mov

**Comment by bolg55** [comment] 2022-10-21 13:56
Hi - is this a local Strapi instance or production? I am not able to reproduce on a brand-new instance of v4.4.5 running locally. It also looks like you're using a plugin that may or may not be compatible with the latest version. If you disable your plugin and just try to use the native select dropdown (to the left of the gear icon), does the issue persist?

**Comment by squelix** [comment] 2022-10-21 14:03
I removed the plugin `strapi-plugin-sitemap` from `package.json` and now it's working. Thank you and sorry for the inconvenience ;)

**Comment by bolg55** [comment] 2022-10-21 14:21
No problem, please feel free to go here: https://market.strapi.io/plugins/strapi-plugin-sitemap and report an issue to the plugin developer. 

Closing

**Closed by bolg55** 2022-10-21 14:21 UTC
Labels: issue: bug, severity: medium, status: can not reproduce, source: core:admin
