### ISSUE TITLE
Media Library sort by upload time doesn't work

### ISSUE THREAD

**Issue by Pixfloage** [strapi/strapi#9281] opened 2021-02-01 14:31 UTC
Hello! 

## Bug description
The "Sort by" feature in the Media Library doesn't work. No matter what i choose (except alphabetical), they always show up in oldest --> most recent order. I have at least a couple of days of uploaded-time difference between the assets. 

## Steps to reproduce the behavior
1. Open admin page, go to Media Library
2. Upload assets one by one, or multiple at once, doesn't really matter
3. Set a sorting method with the "Sort by" button, nothing happens

## Expected behavior
Sort the assets by the selected sorting method. If i choose "most recent updates", then the most recently uploaded assets should show up first. Then in descending order the rest.

## Screenshots
![Screenshot at Feb 01 15-13-53](https://user-images.githubusercontent.com/12548918/106471514-fd78d980-64a1-11eb-9db6-6b5588dd230e.png)
![Screenshot at Feb 01 15-14-05](https://user-images.githubusercontent.com/12548918/106471526-010c6080-64a2-11eb-8cf5-a4e3cdd6c3f1.png)

## System
- Node.js version: v12.20.0
- NPM version: 6.14.8
- Strapi version: 3.4.3
- Database: mongodb
- Operating system: macOS 10.15.4

**Comment by derrickmehaffy** [comment] 2021-02-01 14:47
Unable to reproduce on v3.4.5:

Newest: 

![image](https://user-images.githubusercontent.com/8593673/106473990-abb05f00-6461-11eb-8894-43175fb4d64a.png)

Oldest: 

![image](https://user-images.githubusercontent.com/8593673/106474021-b4089a00-6461-11eb-9e8a-7db03fbd85ef.png)

**Comment by Pixfloage** [comment] 2021-02-01 15:44
I upgraded all my Strapi dependencies to v3.4.5 (also rebuilt the panel), with no luck to sorting.

![Screenshot at Feb 01 16-42-23](https://user-images.githubusercontent.com/12548918/106481377-aa585400-64ac-11eb-8917-3be18933b705.png)

Where can i take a peek to this endpoint's service?

**Comment by derrickmehaffy** [comment] 2021-02-02 20:56
https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-upload

**Comment by kahoowkh** [comment] 2021-02-25 07:41
I'm having the same problem with v3.4.6 with MongoDB. I found that the field in `upload_file` should be `createdAt` instead of `created_at`. So when I change the query string to `_sort=createdAt:DESC`, it works completely fine.

I upgraded from `v3.0.0-beta.20` to `v3.4.6`, so I'm not sure if the field name is changed.

**Comment by derrickmehaffy** [comment] 2021-02-26 19:55
I can confirm the issue is mongodb only, all SQL databases work fine. Going to close this issue in favor of: https://github.com/strapi/strapi/issues/9473

**Closed by derrickmehaffy** 2021-02-26 19:55 UTC
Labels: severity: low, source: plugin:upload, status: can't reproduce
