### ISSUE TITLE
Missing fields in API response when using relations in components

### ISSUE THREAD

**Issue by pkogler-tgm** [strapi/strapi#8078] opened 2020-09-28 10:11 UTC
**Describe the bug**
When adding a relation to a component, not all Fields are present in the corresponding API Response.
Even if autoPopulate is set to true.

**Steps to reproduce the behavior**

1. Create Collection Type "Article"
2. Create any custom Component i.e "colorCombination" and add it to Collection Type Article
3. Create component "link-to-article" with realtion to Article
4. Add component "link-to-article" to Article Collection Type
5. Add new Article and fill out link-to-article
5. Query /articles 
6. All components inside Article like colorCombination are missing in response.

**Expected behavior**
In my opinion relations in components should work the same like relations in Collection Types

**Screenshots**
![image](https://user-images.githubusercontent.com/9964013/94419911-ac6b7880-0183-11eb-8bbd-3ce111f7c286.png)

**Code snippets**
**article.settings.json**
`
{
	"kind": "collectionType",
	"collectionName": "articles",
	"info": {
		"name": "Article"
	},
	"options": {
		"increments": true,
		"timestamps": true
	},
	"attributes": {
		"title": {
			"type": "string"
		},
		"color": {
			"type": "component",
			"repeatable": false,
			"component": "allgemein.color-combi"
		},
		"link": {
			"type": "component",
			"repeatable": false,
			"component": "links.link-to-article"
		}
	}
}
`
**link-to-article,json**
`
{
  "collectionName": "components_links_link_to_articles",
  "info": {
    "name": "linkToArticle",
    "icon": "arrow-alt-circle-up"
  },
  "options": {},
  "attributes": {
    "articles": {
      "collection": "article"
    }
  }
}
`

**System**

- Strapi version: 
- Database: sqlite, postreSQL 13
- Operating system: windows

**Comment by derrickmehaffy** [comment] 2020-09-28 17:18
Duplicate of https://github.com/strapi/strapi/issues/7360

**Closed by derrickmehaffy** 2020-09-28 17:18 UTC
Labels: status: duplicate
