### ISSUE TITLE
users/me route missing relational items

### ISSUE THREAD

**Issue by JeffWScott** [strapi/strapi#8425] opened 2020-10-21 17:26 UTC
Relational User items aren't returned by users/me route

### Describe the bug

auth/local returns relational items added to the User Content, but a call using the jwt token to users/me doesn't contain the same items (only has default)

### Steps to reproduce the behavior

1. Add relational item and link to a user
2. Login as user (new field is included in users property of the auth/local response
3. Use JWT to call users/me, and relational item is not returned

### Expected behavior

I would expect all properties that are returned via auth/local to be returned vai users/me.  I only want to store the JWT when email and password are submitted to auth/local and then I want to do a subsequent call to users/me to get the user's account information.

### System

- Node.js version: 12
- NPM version: no idea, using platform.sh
- Strapi version: 3.2.2
- Database: postgresql
- Operating system: no idea, using platform.sh

**Comment by derrickmehaffy** [comment] 2020-10-21 19:45
Hello,

This is intended to increase performance, if you wish to modify the logic you will need to use the [extensions system to customize the plugin](https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#how-do-i-customize-a-plugin) and the specific service that handles this is located here:

https://github.com/strapi/strapi/blob/81c684d7b4ae6649bf701be119c740234a5f2d12/packages/strapi-plugin-users-permissions/services/User.js#L71-L77

Following the same logic as other services, you simply need to modify the populate array (default is `['role']`) so to add other relation fields you just need to include the name of the relational field in that array. Information on service population can be found here: https://strapi.io/documentation/v3.x/concepts/services.html#services

I'm going to mark this as closed as it's not a bug but intended.

**Closed by derrickmehaffy** 2020-10-21 19:45 UTC
