### ISSUE TITLE
Multiple webhooks sent on publish/unpublish event

### ISSUE THREAD

**Issue by jazzybuilds** [strapi/strapi#9590] opened 2021-03-04 03:55 UTC
### Describe the bug

I am using Strapi as a headless CMS and using Github actions to build a Gridsome front end. What I'm trying to achieve is to ensure the front end is always up to date with the latest published content.

When activating webhooks in Strapi for events (update, delete, publish, unpublish) it will:
Send 2 webhooks when content is published
Send 2 webhooks when content is unpublished

### Steps to reproduce the behavior

1. Create webhook in Strapi for events (update, delete, publish, unpublish) 
2. Create new content and publish
3. Unpublished content

### Expected behavior

One webhook is sent per publish/unpublish event

### Code snippets

This is the custom webhook route that the webhook posts to:

```
{
    "routes": [
      {
        "method": "GET",
        "path": "/webhook",
        "handler": "webhook.index",
        "config": {
          "policies": []
        }
      },
      {
        "method": "POST",
        "path": "/webhook",
        "handler": "webhook.index",
        "config": {
          "policies": []
        }
      }
    ]
  }
```

This is a custom controller tied to a custom route:

```
"use` strict";
const axios = require("axios");

module.exports = {
   
     async index(ctx) {
        console.log('Webhook Server is working');
        const url =
                "https://api.github.com/my workflow";

        const token = process.env.GITHUB_TOKEN;

        const headers = {
            Authorization: `Bearer ${'GITHUB_TOKEN'}`,
            "Content-Type": "application/json",
            Accept: "application/vnd.github.v3+json",
        };

        const axiosResult = axios.post(
                url,
                    { ref: "dev" },
                    { headers });
    },
  };
```

### System

- Node.js version: 14.15.5
- NPM version: 7.6.0
- Strapi version: 3.5.0
- Database: postgresQL/SQLite
- Operating system: Ubuntu/MacOS

### Additional comments

In relation to my goal it would be good if Strapi could have a new event (Updates to published content) for webhooks that is triggered for published content that is:
-Updated
-Deleted

Currently it is sending unnecessary webhooks for content that is updated/deleted but is in an unpublished state.

This can perhaps be a feature request?

My first bug log on Github so let me know if I've missed anything.

**Comment by sqlninja** [comment] 2022-06-14 19:08
So my bug was indeed closed as a dupe of this issue. That being said, what is the status for this one?

**Comment by sqlninja** [comment] 2022-06-18 19:49
I found the issue was my bad programming which created an infinite loop in the webhook handler

**Closed** 2022-12-14 00:13 UTC
Labels: issue: bug, severity: medium, source: core:strapi, status: pending reproduction

**Comment by bhavesh-chaudhari** [comment] 2023-07-19 06:47
Any update on this? Unpublish and Publish events are triggering Update event as well.

**Comment by artemtech** [comment] 2023-12-07 03:35
any update on this ? it also happens to me when publish/unpublish entries triggering update event

**Comment by raniaamina** [comment] 2023-12-07 03:37
Me also waiting update for this, trying in latest version of strapi but still got same result as before

**Comment by AutomaRobin** [comment] 2024-04-03 14:25
This still happens

**Comment by Google4777** [comment] 2024-05-07 20:57
any update in this?
