### ISSUE TITLE
SQL ER_LOCK_DEADLOCK error while editing entry with 2-deep level components 

### ISSUE THREAD

**Issue by yuriyglushakov** [strapi/strapi#15508] opened 2023-01-20 03:04 UTC
### Required System information

- Node.js version: 16.15.1
- NPM version: 8.11.0
- Strapi version: 4.5.0
- Database: MySQL 8.0.30
- Operating system: Linux

### Describe the bug
I've found a strange bug on 4.5.X. version which causes an issue while updating contents.
I'm trying to edit and entry with 2-level component inside of it (screen below)
  <img width="880" alt="image" src="https://user-images.githubusercontent.com/6677070/213607993-ff099dd0-6d39-44c0-a114-64266e90079f.png">

During this process in some cases component entries can be randomly doubled (screencast below):
![Entry behaviour](https://user-images.githubusercontent.com/6677070/213608295-81bd1175-5a1f-46fe-a46d-c80e2fd6ff7d.gif)

In case if entry has more than 8 component records inside it causes error while saving content (ER_LOCK_DEADLOCK sql error is seen in logs) 

Please help to define what can be set up wrong. 

### Steps to reproduce the behavior

1. Create similar component with 2 level component system (repeatable component inside repeatable component)
2. Create an entry with several components 
3. Save and publish entry - you can potentially see that number of component records is doubled while saving
4. Try to add more than 10 entries and you can reproduce internal server error

### Expected behavior

Saving without issues and deadlock 

### PUT request example while saving entry
I've noticed that some id's are being doubled while strapi sending PUT request to update details. Maybe this causes an issue
```
{
    "id": 8,
    "name": "example",
    "slug": "example",
    "createdAt": "2022-09-25T16:08:12.104Z",
    "updatedAt": "2023-01-20T01:36:41.076Z",
    "publishedAt": "2022-09-25T16:20:58.143Z",
    "locale": "en",
    "preview": null,
    "questions": [
        {
            "id": 31,
            "question": "question example",
            "noteDescription": "note exmple",
            "answers": [
                { "id": 116, "answer": "example answer", "correct": false},
                { "id": 117, "answer": "example answer", "correct": false},
                { "id": 118, "answer": "example answer", "correct": false},
                { "id": 119, "answer": "example answer", "correct": false},
                { "id": 121, "answer": "example answer", "correct": false},
                { "id": 116, "answer": "example answer", "correct": false},
                { "id": 117, "answer": "example answer", "correct": false},
                { "id": 117, "answer": "example answer", "correct": false},
                { "id": 118, "answer": "example answer", "correct": false},
                { "id": 118, "answer": "example answer", "correct": false},
                { "id": 119, "answer": "example answer", "correct": false},
                { "id": 119, "answer": "example answer", "correct": false},
                { "id": 121, "answer": "example answer", "correct": false},
                { "id": 121, "answer": "example answer", "correct": false}
            ]
        },
        //...
    ],
    "createdBy": null,
    "updatedBy": 1,
    "localizations": []
}
```

Thank you in advance for any clarification

**Comment by petersg83** [comment] 2023-01-20 13:33
Hello :) Thank you for the report and the steps to reproduce ! It's a know issue since #15202. We already released multiple fixes but they seem to not have been enough. We are working on a more solid fix that I hope will be released for the next release :)
If it's ok for you I'll close this issue in favor of #15202 :)

**Closed by petersg83** 2023-01-20 13:33 UTC
