### ISSUE TITLE
User password field not saving correctly

### ISSUE THREAD

**Issue by webleahy** [strapi/strapi#3871] opened 2019-08-29 21:17 UTC
**When adding or updating a user their password becomes a random string of text**
After a fresh install of Strapi, I create an admin account, log in and add a new user with the password field set to `test`.  After saving the new user I go back to edit the new user and the password appears as `$2a$10$RGWFsVrZTqnt0izgi1F4Fus2Dd6ibzYNxd8mMtsPsaVu3QYocsp7K`.  I cannot sign into the admin panel as the new user because of this.

**Steps to reproduce the behavior**
1. Following README's install and new project guide 
```
npm install strapi@beta -g
strapi new my-project
cd my-project
strapi develop
```
2. Create the admin user and log in.
3. Click on `Users` under content types.
4. Add new user.
5. Fill out all fields with valid input
6. Save user.
7 Edit newly created user.
8. Look at the password.

**Expected behavior**
After adding a new user, the given password should persist after a save.

**Screenshots**
The password field with the jumbled string.
![image](https://user-images.githubusercontent.com/53451433/63976850-4abc7480-ca80-11e9-9254-aa3294eacfc7.png)

**System**
- Node.js version: 10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.15
- Database: ?
- Operating system: Windows 10

**Comment by soupette** [comment] 2019-08-30 09:48
@webleahy the API hashes the password for obvious security reasons it is an intended behaviour. We spoke with @alexandrebodin about this and we think that it would be better to not return the password at all in case of edition.

I am closing the issue since it is not a bug.

**Closed by soupette** 2019-08-30 09:48 UTC

**Comment by kumazhanov** [comment] 2019-08-30 09:57
I think that this is still a problem. Since when entering the account, the user and password are not accepted and strapi replies that the username and password are not correct.

**Comment by soupette** [comment] 2019-08-30 10:47
How do you authenticate your user what does your request look like?
