### ISSUE TITLE
Missing __component entry at root of a contentType in Rest API

### ISSUE THREAD

**Issue by jclaveau** [strapi/strapi#13738] opened 2022-07-11 01:12 UTC
### Required System information

- Node.js version: v16.15.1
- NPM version: 8.12.1
- Strapi version: @strapi/strapi@4.2.2
- Database: sqlite3
- Operating system: Ubuntu 20.04.4 LTS

### Describe the bug

While accessing a component being a direct attribute of a content type via Rest API, its content is returned but not it's type as the `__component` entry is missing.

### Steps to reproduce the behavior

1. Create a basic content type (Page) and a basic component as one of its attributes (I'm trying to create a Simple Page template to work with https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation)
2. Create a page and add a value to the template
3. Go to the rest API `/api/pages?populate=*`
4. The template as no `__component` entry

### Expected behavior

`__component` entry should be present

### Screenshots

![image](https://user-images.githubusercontent.com/1556489/178170291-2e8923f8-562e-4c7d-b6f6-8d6ce3097190.png)

As you can see, the same component in a dynamic zone just above has no problem.
SEO component from `@strapi/plugin-seo` misses this entry also.

I changed a bit my config after this screenshot but there is no such problem with GraphQL
![image](https://user-images.githubusercontent.com/1556489/178170383-ea685576-e658-4f2a-8967-2bbc360c9865.png)

### Code snippets
Here is the only content of my component
```js
{
  "collectionName": "components_templates_simple_pages",
  "info": {
    "displayName": "Simple Page",
    "icon": "file",
    "description": ""
  },
  "options": {},
  "attributes": {
    "lalala": {
      "type": "string"
    }
  }
}
```

### Additional context
This bug makes the https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation template feature failing (Even if I have to open a bug/PR on their side to add the missing `populate: template` which seems to be a legacy of Strapi 3 versions)

**Comment by derrickmehaffy** [comment] 2022-07-13 20:17
This has never existed as the GraphQL type is needed since we generate unions, going to close as a feature request instead.

---

Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [Canny](https://feedback.strapi.io/).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.

**Comment by jclaveau** [comment] 2022-07-15 09:14
Oh, my bad. If i understand well, this means that the `template` feature of the `Navigation` plugin never worked: https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/blob/master/server/utils/functions.ts#L80-L102

**Comment by derrickmehaffy** [comment] 2022-07-15 16:25
On 2nd review of this I believe I am wrong as:
- https://github.com/strapi/strapi/issues/10472
- https://github.com/strapi/strapi/issues/8453

So gonna reopen this for now and check with our engineers.

**Comment by kasonde** [comment] 2022-11-01 15:28
Reproducible on 4.4.5

**Comment by joshuaellis** [comment] 2023-02-23 08:10
We've taken a look at this issue and while there are subtle differences, at the root of the issue is the same cause, so we're going to close this issue in favour of #8453 as we've already began the process of resolving that issue. Thank you for the report 👍🏼

**Closed by joshuaellis** 2023-02-23 08:10 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:strapi
