### ISSUE TITLE
Apply min/max validation to strings at the API level

### ISSUE THREAD

**Issue by john916zhang** [strapi/strapi#10705] opened 2021-08-06 18:52 UTC
## Bug report

When updating a Username with two characters in the Admin console, an exception "The value is too short" appears. 

### Steps to reproduce the behavior

1. Go to 'https://localhost:2337/admin'
2. Click on 'Collection types / Users'
3. Click a user and update the username with two characters and click "save"
4. See "The value is too short".

### Expected behavior

We can set a Username with two characters.

### Screenshots

<img width="680" alt="Screen Shot 2021-08-06 at 2 45 36 PM" src="https://user-images.githubusercontent.com/195719/128558288-98090ce5-1143-42e8-b7ec-43ca738e333c.png">

### System

- Node.js version:  14.8 
- NPM version:
- Strapi version:  3.6.6 
- Database:  MongoDB
- Operating system: Ubuntu 16.06

**Comment by derrickmehaffy** [comment] 2021-08-09 19:59
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/models/User.settings.json#L12-L18

This is intended, if you wish to change the logic you will need to use our extensions system to modify the min length constraint

**Comment by john916zhang** [comment] 2021-08-09 20:29
But the problem is that I can create an account with a username of two characters without any problem by the API.

**Comment by derrickmehaffy** [comment] 2021-08-09 22:53
Indeed, certain validations are not currently handled by the API yet but we are looking to solve this hopefully in our v4.

I'll reopen as a feature request for now.

**Comment by soupette** [comment] 2022-01-13 09:23
I can confirm min and max validations are not applied in the V4 as well.

**Comment by soupette** [comment] 2022-03-17 10:49
It seems to be fixed on v4 now I have just tested with the 4.1.5 version

**Comment by derrickmehaffy** [comment] 2022-03-28 20:49
Marking as closed since it should be working now

**Closed by derrickmehaffy** 2022-03-28 20:49 UTC
Labels: issue: enhancement
