### ISSUE TITLE
`route.info` of `filterContentAPI` is undefined, causing "error: Cannot read properties of undefined (reading 'type')"

### ISSUE THREAD

**Issue by jsadoski-rockhall** [strapi/strapi#18464] opened 2023-10-16 20:32 UTC
### Required System information

- Node.js version: v18.17.1
- Yarn version: 3.6.3
- Strapi version: 4.14.4
- Database: SQLite & Postgres
- Operating system: Windows 11 & Ubuntu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When trying to access an API token in my local dev or in production, the field-level permissions do not populate.

In my logs, I have this error:

```
[2023-10-16 16:15:11.084] error: Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at filterContentAPI (<my project path>\node_modules\@strapi\strapi\dist\services\content-api\index.js:16:48)
    at Array.filter (<anonymous>)
    at <my project path>\node_modules\@strapi\strapi\dist\services\content-api\index.js:29:16
    at <my project path>\node_modules\lodash\lodash.js:4967:15
    at baseForOwn (<my project path>\node_modules\lodash\lodash.js:3032:24)
    at <my project path>\node_modules\lodash\lodash.js:4936:18
    at Function.forEach (<my project path>\node_modules\lodash\lodash.js:9410:14)
    at Object.getRoutesMap (<my project path>\node_modules\@strapi\strapi\dist\services\content-api\index.js:23:26)
    at Object.getRoutes (<my project path>\node_modules\@strapi\admin\server\controllers\content-api.js:11:47)
    at dispatch (<my project path>\node_modules\koa-compose\index.js:42:32)
```

### Steps to reproduce the behavior

1. Go to "Settings"
2. Click on "API Tokens"
3. Scroll down to Permissions/Advanced Settings

### Expected behavior

Permissions/Advanced Settings should load.

### Screenshots

<img width="866" alt="image" src="https://github.com/strapi/strapi/assets/110678743/cc0cc3a1-b4ce-432f-8f7d-12cd505ab200">

### Code snippets

Debugging the code, the error happens on this line:

<https://github.com/strapi/strapi/blob/91cf4ee737dd50a97bd44e64fdeb1c6aa8dc421f/packages/core/strapi/src/services/content-api/index.ts#L15>

And I can also see that `routes.info` is indeed undefined.

Adding optional chaining in the module code within my node_modules fixes the issue for me:

```javascript
const filterContentAPI = (route) => route.info?.type === 'content-api';
```

### Additional context

I don't have any custom routes. All of my routes are auto-generated with `factories.createCoreRouter()`

I'm willing to open a PR for this! ❤️

**Comment by Boegie19** [comment] 2023-10-18 17:00
@jsadoski-rockhall what plugins do you have installed since I can't replicate the issue.

**Comment by altruity** [comment] 2023-10-19 17:44
Just chiming in here, as I'm experiencing the same exact issue, on a project running locally. 

My deps:
```
    "@strapi/plugin-graphql": "4.14.5",
    "@strapi/plugin-i18n": "4.14.5",
    "@strapi/plugin-seo": "^1.9.4",
    "@strapi/plugin-users-permissions": "4.14.5",
    "@strapi/strapi": "4.14.5",
    "better-sqlite3": "8.6.0",
    "strapi-plugin-heroicons-field": "^0.0.4",
    "strapi-plugin-menus": "^1.5.0",
    "strapi-plugin-populate-deep": "^3.0.0",
    "strapi-plugin-vercel-deploy": "^1.4.0"
```

<details>
<summary>My `config/plugins.ts` file</summary>

```

module.exports = ({ env }) => ({
  seo: {
    enabled: true,
  },
  'vercel-deploy': {
    enabled: true,
    config: {
      deployHook: process.env.VERCEL_DEPLOY_PLUGIN_HOOK,
      apiToken: process.env.VERCEL_DEPLOY_PLUGIN_API_TOKEN,
      appFilter: process.env.VERCEL_DEPLOY_PLUGIN_APP_FILTER,
      teamFilter: process.env.VERCEL_DEPLOY_PLUGIN_TEAM_FILTER,
      roles: ['strapi-super-admin', 'strapi-editor', 'strapi-author'],
    },
  },
  'strapi-plugin-populate-deep': {
    config: {
      defaultDepth: 6, // Default is 5
    },
  },
  menus: {
    config: {
      maxDepth: 3,
    },
  },
  graphql: {
    config: {
      endpoint: '/graphql',
      shadowCRUD: true,
      playgroundAlways: false,
      depthLimit: 7, // 7 is default
      amountLimit: 100,
      apolloServer: {
        tracing: false,
      },
    },
  },
});

```
</details>

Also, not 100% sure, but it seems to prevent me from creating new folder-based routes (using NextJs 13.4.2).
Thanks for any insight! :pray:

**Comment by pavelvolynets** [comment] 2024-05-02 16:58
i have the same issue, but the reason was that in custom routes file i had a typo and after fix it works like a charm. maybe it will same someone some time

**Comment by cristian25cd** [comment] 2024-06-04 15:05
In my case the error was related with a wrong typescript configuration. I follow this [guide](https://docs-next.strapi.io/dev-docs/typescript/adding-support-to-existing-project) and everything works now.

**Comment by rajanSimform** [comment] 2024-11-19 15:08
The same issue was occurred with me while working with Strapi v5.4.0
I am using @strapi/plugin-users-permissions version "^5.4.0".
When I want to change the permission of collection type for "Public" users then I got the same error.

![image](https://github.com/user-attachments/assets/eedb6e60-0af1-4d84-88b6-ea59450bf901)

and it is coming from getRoutes() function in line 

``` }).filter((route) => route.info.type === 'content-api'); ```

**Comment by rajanSimform** [comment] 2024-11-20 05:33
I have reproduced the issue and fixed in my system. Possible cause of this type of error is:

- you  have created strapi project to typescript and then converted your project to use javascript then there will be issue with your API files (that can be collection type or single type) or vise-versa
- Please ensure that all of your api files are synced and uses the same js or ts  files.

**Closed as completed** 2024-11-20 15:05 UTC
Labels: issue: bug, severity: medium, source: core:admin, status: pending reproduction
