### ISSUE TITLE
About 9 min to building strapi

### ISSUE THREAD

**Issue by purnomoeko** [strapi/strapi#3207] opened 2019-04-30 10:10 UTC
**Informations**
- **Node.js version**:10.5.1  
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.22
- **Database**: MongoDb
- **Operating system**: MacOS Mojave
- **(Optional) Link to your Project**: 

**What is the current behavior?**
I wouldn't say it's a bug, but to build strapi plugin it needs about 9 minutes using MBP 2017 Core i7? I think this is unacceptable, is there any way to improve the performance? Please refer to this video link to see my build process.
https://drive.google.com/open?id=1bPZqbrGMwPnkbWEfAMSjG0iKWY8w_YBu

**Steps to reproduce the problem**
using npm run setup --plugins

**What is the expected behavior?**
Taking 9 min to build strapi. 

**Suggested solutions**

**Comment by derrickmehaffy** [comment] 2019-04-30 10:18
This should be resolved in the beta, also it should be noted that javascript/node is single threaded, trust me when I say it doesn't matter what CPU you are using (AMD Threadripper 16 core/32 threads overclocked here)

For the alpha this is normal but the build process is being streamlined in the beta.

Marking as closed due to this issue already being addressed

**Closed by derrickmehaffy** 2019-04-30 10:18 UTC

**Comment by purnomoeko** [comment] 2019-04-30 10:21
@derrickmehaffy ok understand. Where can I see the project milestone to Beta Version?

**Comment by lauriejim** [comment] 2019-04-30 10:23
Hello!
Thank you for this feedback.

First of all, we are working on a new architecture to make this setup faster. And we create a lighter build for your production application.

Currently there is no way to improve these performances so you will have to deal with.
This topic is an enhancement and not a bug. But I'm agree it can be frustrating.

> And please be careful with words you use (ref to "unacceptable") we are doing our best to offer your (freely) the best Headless CMS we can. https://github.com/strapi/strapi/blob/master/CODE_OF_CONDUCT.md

**Comment by purnomoeko** [comment] 2019-04-30 10:27
Sorry for the words unacceptable, I'm sure your team has done some good job. English is not my first language, surely will edit it.

**Comment by lauriejim** [comment] 2019-04-30 10:30
Thank you ;)
