### ISSUE TITLE
strapi-plugin-upload 3.2.5 Response 500 when upload files on heroku - cloudinary

### ISSUE THREAD

**Issue by Jessinra** [strapi/strapi#8464] opened 2020-10-24 05:11 UTC
### Found Solutions:
Add '?' into  `isPrivateAttribute` in `node_modules/strapi-plugin-upload/node_modules/strapi-utils/lib/content-types.js`
![Screenshot from 2020-10-24 13-01-17](https://user-images.githubusercontent.com/32489864/97069254-45fa3e80-15f9-11eb-8747-e6436e46b665.png)

Or revert back to 3.1.7

### Describe the bug

**Update**: I found out after updating local strapi-plugin-upload to 3.2.5 the same problem occur, probably specific to version 3.2.5

Hi, I tried to upload files using media plugin (I'm using Cloudinary plugin), on local, it works fine, but on Heroku, it shows as internal server error (500). The images always successfully uploaded to Cloudinary, sometimes it even shows on media plugin after I cancel/close the upload modal, but the response 500 is very annoying. 

The worst part, the log Heroku shows, (e.g. /app/node_modules/strapi-plugin-upload/node_modules/strapi-utils/lib/content-types.js:69:34), I can't find the line on my local `node_modules`, its only shows up to line 20. 

### Things I tried to solve this

I tried to make a new project on Heroku, with a brand new database (empty Postgres), these problems still occur.

I tried to reinstall the plugin obviously doesn't change anything.
**update**: it's actually failed when I tried to run `npm run strapi install upload`
![Screenshot from 2020-10-24 12-37-22](https://user-images.githubusercontent.com/32489864/97068903-dc2c6580-15f5-11eb-979b-508b06e94417.png)

I tried on the local machine, it works fine, I delete the `node_modules` on local then `npm install` again, and it's still working fine. 

I tried to set breakpoints on the function called on the log below, but the **breakpoints only getting called up to `Object.add`, `sanitizeEntity` -> `isPrivateAttribute` isn't called.** 

### Log 

```
2020-10-24T04:24:44.142169+00:00 app[web.1]: [2020-10-24T04:24:44.142Z] error TypeError: Cannot read property 'includes' of undefined
2020-10-24T04:24:44.142211+00:00 app[web.1]:     at isPrivateAttribute (/app/node_modules/strapi-plugin-upload/node_modules/strapi-utils/lib/content-types.js:69:34)
2020-10-24T04:24:44.142212+00:00 app[web.1]:     at shouldRemoveAttribute (/app/node_modules/strapi-plugin-upload/node_modules/strapi-utils/lib/sanitize-entity.js:139:21)
2020-10-24T04:24:44.142212+00:00 app[web.1]:     at reducerFn (/app/node_modules/strapi-plugin-upload/node_modules/strapi-utils/lib/sanitize-entity.js:40:9)
2020-10-24T04:24:44.142213+00:00 app[web.1]:     at /app/node_modules/strapi-plugin-upload/node_modules/lodash/lodash.js:914:11
2020-10-24T04:24:44.142213+00:00 app[web.1]:     at /app/node_modules/strapi-plugin-upload/node_modules/lodash/lodash.js:4925:15
2020-10-24T04:24:44.142214+00:00 app[web.1]:     at baseForOwn (/app/node_modules/strapi-plugin-upload/node_modules/lodash/lodash.js:2990:24)
2020-10-24T04:24:44.142214+00:00 app[web.1]:     at /app/node_modules/strapi-plugin-upload/node_modules/lodash/lodash.js:4894:18
2020-10-24T04:24:44.142215+00:00 app[web.1]:     at baseReduce (/app/node_modules/strapi-plugin-upload/node_modules/lodash/lodash.js:911:5)
2020-10-24T04:24:44.142215+00:00 app[web.1]:     at Function.reduce (/app/node_modules/strapi-plugin-upload/node_modules/lodash/lodash.js:9707:14)
2020-10-24T04:24:44.142215+00:00 app[web.1]:     at sanitizeEntity (/app/node_modules/strapi-plugin-upload/node_modules/strapi-utils/lib/sanitize-entity.js:95:12)
2020-10-24T04:24:44.142216+00:00 app[web.1]:     at Object.add (/app/node_modules/strapi-plugin-upload/services/Upload.js:303:49)
2020-10-24T04:24:44.142216+00:00 app[web.1]:     at async Promise.all (index 0)
2020-10-24T04:24:44.142217+00:00 app[web.1]:     at async Object.upload (/app/node_modules/strapi-plugin-upload/services/Upload.js:139:12)
2020-10-24T04:24:44.142217+00:00 app[web.1]:     at async uploadFiles (/app/node_modules/strapi-plugin-upload/controllers/upload/admin.js:186:27)
2020-10-24T04:24:44.142218+00:00 app[web.1]:     at async Object.upload (/app/node_modules/strapi-plugin-upload/controllers/Upload.js:64:5)
2020-10-24T04:24:44.142218+00:00 app[web.1]:     at async /app/node_modules/strapi/lib/middlewares/router/utils/routerChecker.js:79:22
2020-10-24T04:24:44.142669+00:00 app[web.1]: [2020-10-24T04:24:44.142Z] debug POST /upload (3055 ms) 500
```

### Steps to reproduce the behaviour

1. Go to a media plugin
2. Upload any files

### Expected behaviour

The upload modal closes, and file successfully uploaded.

### System

(local)
- Node.js version: 14.3.0
- NPM version: 6.14.5
- Strapi version: 3.1.4
- Database: Postgres
- Operating system: linux
![Screenshot from 2020-10-24 12-11-23](https://user-images.githubusercontent.com/32489864/97068480-1136b900-15f2-11eb-8051-6ec875d2eac1.png)

(heroku)
- Node.js version: 15.0.1
- NPM version: 6.14.5
- Strapi version: 3.1.4
- Database: Postgres
- Operating system: linux
![Screenshot from 2020-10-24 12-10-38](https://user-images.githubusercontent.com/32489864/97068466-03813380-15f2-11eb-96b4-39970deda215.png)

Really appreciate if anyone from Strapi's dev team could reach out to me :)
Thank you very much, have a nice day

**Comment by MattieBelt** [comment] 2020-10-24 07:15
Hey @Jessinra,

As what differs on your local vs heroku is your Node version. 
Node `v15` is and will not be supported by Strapi, only the active LTS versions.
Strapi [supports](https://github.com/strapi/strapi/issues/7921) `v14` since v3.2.4 so `v14` should be fine.

So I suggest you downgrade your heroku Node to `v14`.

**Comment by derrickmehaffy** [comment] 2020-10-26 18:41
Please test with the proper node version as suggested by @MattieBelt.

**Comment by Jessinra** [comment] 2020-10-27 17:45
@MattieBelt @derrickmehaffy sorry for the delay explanation,

I tested on node v14 LTS as well, the problem is not caused by the difference between my local vs Heroku setup. 
Initially, I was explaining that this bug occurs on both Heroku's **and** my local setup. 

The problem is solved by downgrading my `strapi` and `strapi-plugin-upload` to v3.1.4

for v3.2.5, I have to modify the node package, by adding '?' into `isPrivateAttribute` in `node_modules/strapi-plugin-upload/node_modules/strapi-utils/lib/content-types.js` but I'm not sure if this is the right way to do it. (It solves, but might not the be the right way)

Please investigate further and thank you for your hard work as always :)

**Comment by MattieBelt** [comment] 2020-10-28 12:25
Hey @Jessinra,

Thanks for updating and testing on `v14`.
Since you shared your package versions I know what the problem is.
You should always make sure you have the same version on all of your (official) strapi packages.
So indeed downgrading the upload plugin fixes it, because most of your (core) strapi packages are on `v3.1.4`.

Your `package.json` should look something like:
```js
  "dependencies": {
    //...
    "strapi": "3.1.4",
    "strapi-admin": "3.1.4",
    "strapi-utils": "3.1.4",
    "strapi-plugin-content-type-builder": "3.1.4",
    "strapi-plugin-content-manager": "3.1.4",
    "strapi-plugin-documentation": "3.1.4",
    "strapi-plugin-users-permissions": "3.1.4",
    "strapi-plugin-email": "3.1.4",
    "strapi-plugin-upload": "3.1.4",
    "strapi-provider-upload-cloudinary": "3.1.4",
    "strapi-connector-bookshelf": "3.1.4",
    //...
  },
```

As you can see there are no `^` before the versions, this could case mismatches like the issue you had.

If you want to upgrade to `v3.2.x` you could follow the [general update guide](https://strapi.io/documentation/v3.x/guides/update-version.html#upgrading-your-dependencies) to upgrade all of your packages. Do note the two migration guides that apply your your version step:
- [Migration guide from 3.2.3 to 3.2.4](https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.2.3-to-3.2.4.html)
- [Migration guide from 3.1.x to 3.2.3](https://strapi.io/documentation/v3.x/migration-guide/migration-guide-3.1.x-to-3.2.x.html)

After following the guides your package.json should look something like:
```js
  "dependencies": {
    //...
    "strapi": "3.2.5",
    "strapi-admin": "3.2.5",
    "strapi-utils": "3.2.5",
    "strapi-plugin-content-type-builder": "3.2.5",
    "strapi-plugin-content-manager": "3.2.5",
    "strapi-plugin-documentation": "3.2.5",
    "strapi-plugin-users-permissions": "3.2.5",
    "strapi-plugin-email": "3.2.5",
    "strapi-plugin-upload": "3.2.5",
    "strapi-provider-upload-cloudinary": "3.2.5",
    "strapi-connector-bookshelf": "3.2.5",
    //...
 },
```
Hope this explains a bit how to manage your strapi versions. :smiley:

**Comment by derrickmehaffy** [comment] 2020-10-28 20:41
Going to mark this as closed as @MattieBelt did suggest the proper solution.

@Jessinra if you still have issues please do update and let us know and we can reopen, thanks!

**Closed by derrickmehaffy** 2020-10-28 20:41 UTC
Labels: status: pending reproduction

**Comment by Jessinra** [comment] 2020-10-29 01:57
Thank you I'll stick with 3.1.4 for now :)
