### ISSUE TITLE
deep filtering breaks the pagination object

### ISSUE THREAD

**Issue by 3akram** [strapi/strapi#14066] opened 2022-08-10 17:20 UTC
Hi, So I'm trying to use the deep filtering feature with a default controller

What I have is a `collectionType` has a - one to many - relation with another `collectionType` Also has a non-repeatable component and this component has a `relation` field with yet another `collectionType`. 

What I'm trying to do is to perform a search on those three `collectionTypes` using `$containsi` to perform a `case-insensitive` search. 

Here is a sample cUrl for what I'm trying to do

```
curl --location -g --request GET 'http://localhost:8081/api/goals?populate[0]=activities&populate[1]=personality_association&populate[2]=categories&populate[3]=personality_association.personality.traits&filters[$or][0][title][$containsi]=practice&filters[$or][1][categories][title][$containsi]=practice&filters[$or][2][personality_association][personality][traits][title][$containsi]=practice' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNjYwMDUxMzM4LCJleHAiOjE2OTE1ODczMzh9.cSCUDtbGgFGTWzHH1QZMvzp57x_gjL1mR3O1RKWs97M'
```  

The pagination issue is simply that I just have `146` entries in my `collectionType` and after applying the deep filtering I receive the total in the pagination with the value `630` and when I visit the next page I find it empty since the actual data array length - the data that I have received - is `16` but the total is completely wrong in the `meta` object.

Strapi V4.2.3
macOS Montery

**Comment by kasonde** [comment] 2022-08-10 17:55
Hey @3akram thanks for the issue. I think this is a duplicate of #7631 and it's been fixed by #13928.

**Closed by kasonde** 2022-08-10 17:55 UTC
