### ISSUE TITLE
Upon import content-types throw error (logged: ve.cancelToken.subscribe is not a function)

### ISSUE THREAD

**Issue by dev-richierich** [strapi/strapi#15833] opened 2023-02-16 01:58 UTC
### Required System information

- Node.js version: 18.14.0
- NPM version: 9.3.1
- Strapi version: 4.6.1
- Database: Postgres 
- Operating system: Ubuntu
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When visiting the content manager section, I am getting an error notification and then a TypeError error in the console. The "body" part of the interface hangs with the loading graphic. 

### Steps to reproduce the behavior
1. Exported tar file from working instance in a preview environment
2. Import tar file into production environment 
3. Rebuild 
4. Login and visit the Content Manager area
5. From here a error notification appears 
6. Area continues to load (or show loading spinner)
7. Logs reveal TypeError ve.cancelToken.subscribe is not a function

### Expected behavior
To view my various content-types and single-types

### Screenshots
<img width="1220" alt="Screenshot 2023-02-15 at 7 57 11 PM" src="https://user-images.githubusercontent.com/103945372/219247901-9e983179-f898-45d6-abec-220122961d78.png">
<img width="1425" alt="Screenshot 2023-02-15 at 7 57 01 PM" src="https://user-images.githubusercontent.com/103945372/219247904-bcefb163-530d-4cfb-b125-3ea3992e3c14.png">

### Additional context

The export was from 4.6.1 version of strapi.

**Comment by gu-stav** [comment] 2023-02-16 08:10
@simotae14 Could you have a look? This might be related to the `useFetchClient` refactorings ...

**Comment by simotae14** [comment] 2023-02-16 09:45
Yes, sure I will have a look

**Comment by dev-richierich** [comment] 2023-02-16 15:50
Of course! 

So, in our preview/demo version where the export came, it was at 4.5.4. I then upgraded to 4.6.1. and did a basic export with no encryption using npm. Here are a list of the plugins: 

- "@googlemaps/google-maps-services-js": "^3.1.16",
- "@sendgrid/mail": "^7.7.0",
- "@sentry/node": "^7.9.0",
- "@sentry/tracing": "^7.9.0",
- "@strapi/plugin-content-manager": "4.6.1",
- "@strapi/plugin-content-type-builder": "^4.6.1",
- "@strapi/plugin-email": "^4.6.1",
- "@strapi/plugin-graphql": "^4.6.1",
- "@strapi/plugin-i18n": "^4.6.1",
- "@strapi/plugin-sentry": "^4.6.1",
- "@strapi/plugin-upload": "^4.6.1",
- "@strapi/plugin-users-permissions": "^4.6.1",
- "@strapi/provider-email-sendgrid": "^4.6.1",
- "@strapi/provider-upload-cloudinary": "^4.6.1",
- "@strapi/strapi": "4.6.1",
- "@strapi/utils": "^4.6.1",
- "axios": "^0.21.1",
- "better-sqlite3": "7.4.6",
- "cloudinary": "^1.32.0",
- "date-fns": "^2.25.0",
- "date-fns-tz": "^1.3.7",
- "ics": "^2.41.0",
- "mjml": "^4.13.0",
- "pg": "^8.8.0",
- "stripe": "^8.168.0",
- "uuid": "^9.0.0"

No customization made to the admin at all. That's the weird thing, all the network responses seem successful
<img width="1436" alt="strapi_error" src="https://user-images.githubusercontent.com/103945372/219417381-3644c13a-e822-4f66-8312-8892f6f7a223.png">

**Comment by bencreynolds** [comment] 2023-02-16 18:35
I also just ran into this bug. The REST API still works as intended, I just can't use the Content Manager in the admin panel.

Reverting to my previous working git commit did not fix the issue. I ran `yarn` (to clear my new installed packages), `yarn build`, and then `yarn develop`. Since this did not fix the issue, I believe this is related to a database issue.

 I will outline the two things I did between my previously working git commit and when the error occurred:

1. I added SendGrid as my mail provider. The content manager was still working at this point.
2. I attempted to create a custom plugin.

I was trying to set up Apple Sign In as a provider for my Strapi install using a custom plugin. I ran the typical` yarn strapi generate` to do this. After messing around with some things, I decided I would push this off for another time and MANUALLY DELETED the plugins folder from `src/plugins'. The plugins folder is no longer in my `src` folder. (It was also not there in my previously working commit, as I had not generated a custom plugin up until that point.)

The ONLY file I edited outside of the `plugins` directory was the `config/plugins.js` file so that I could enable the plugin as the documentation says. That change is obviously no longer there, since I reverted.

This is as detailed an explanation I can give. I'll reply back to this in a moment with my package.json as well as the console error I'm seeing and network logs.

**Comment by bencreynolds** [comment] 2023-02-16 18:41
![image](https://user-images.githubusercontent.com/68837716/219457139-17c1b761-9c15-4b78-8da3-d665d68d0467.png)

![image](https://user-images.githubusercontent.com/68837716/219457463-f088050a-a750-4d56-ae4b-1b48c5d5368d.png)

![image](https://user-images.githubusercontent.com/68837716/219458024-6e1bb271-4109-413d-bc01-6d75d6efccc3.png)

```
Error in Chrome Dev Console: 
TypeError: Ke.cancelToken.subscribe is not a function
    at main.7ad2d71b.js:7202:5791
    at new Promise (<anonymous>)
    at xhr (main.7ad2d71b.js:7202:3476)
    at Kt.Zt (main.7ad2d71b.js:7202:7030)
    at async Promise.all (index 0)
    at async Object.f [as current] (content-manager.04c3b57d.chunk.js:1139:14882)
```

**Comment by bencreynolds** [comment] 2023-02-16 18:52
I'll note that I'm using a SQLite database for my local development. I tested renaming my current DB and then running `yarn develop` to generate a fresh database, which "fixed" the issue. As in, I can use content manager again, but all of the data is gone, of course. 

I am going to investigate the issue further and see if there's anything I can see that is obviously different between the two db's. For reference, they have the same number of tables, so it's not that.

**Comment by bencreynolds** [comment] 2023-02-16 19:04
Welp, I guess I fixed it? 

I created a blank database by using `yarn develop` after renaming my previous SQLite database to something else and then renamed the _new_ database to something else and then renamed the _original_ database back to data.db. Then ran `yarn develop` and the Content Manager works now.

No idea why that would have fixed anything, but it did?

Steps to fix for anyone searching this:

(this assumes you are using SQLite)

1. Rename `data.db` to `data2.db` in the `.tmp` folder in your project's root directory.
2. Run `yarn develop`. This will create a new `data.db` file.
3. Sign into your Strapi instance (you will need to make a new admin account) and then ensure the Content Manager is working as expected (albeit with no data).
4. Rename `data.db` (the new database) to `data1.db`.
5. Rename `data2.db` to `data.db`.
6. Run `yarn develop`

Should be fixed then.

**Comment by simotae14** [comment] 2023-02-16 19:18
Wow, you did it! Great work and thanks for all the information provided. It will be helpful in future for similar cases. Thanks again

**Comment by bencreynolds** [comment] 2023-02-16 20:00
> Wow, you did it! Great work and thanks for all the information provided. It will be helpful in future for similar cases. Thanks again

Hey I actually decided to try and replicate this fix again and failed. My previous solution didn't fix the issue. Based on my tests, I believe this is some sort of caching issue, but I'm just not exactly sure how.

I manually edited the build main.js file and removed the problematic lines. This fixes the issue immediate after running `yarn develop`. If you run yarn build again though, the issue comes back. 

![image](https://user-images.githubusercontent.com/68837716/219473079-ab5ed151-66a4-4374-9e7c-db82de680965.png)

I can, however, successfully replicate the issue. 

Steps to replicate issue:

1. Using Strapi version `4.6.1`, run `yarn add strapi-provider-apple-login`
2. In your `config/plugins.js` file add the following code:
```js
"apple": {
    enabled: true,
  }
```

3. Run `yarn build`
4. Run `yarn develop`
5. Open Content Manager.

This should replicate the issue.

**Comment by bencreynolds** [comment] 2023-02-16 20:15
I may have isolated the issue to an axios version mismatch.

Running `yarn add axios` after doing the steps described in my previous comment appears to fix the issue.

**Comment by dev-richierich** [comment] 2023-02-16 20:15
I'm using a postgres server running on render... yeah i came back to it being an issue w/ axios as well

**Comment by bencreynolds** [comment] 2023-02-16 20:22
> I'm using a postgres server running on render... yeah i came back to it being an issue w/ axios as well

Is there a reason you're running such an old version of axios? Try using `"axios": "^1.3.3",` and then rebuild your strapi instance.

**Comment by dev-richierich** [comment] 2023-02-16 23:29
Man, I thought about that on the walk earlier (updating axios), and great suggestion cause it seems to work now!

**Comment by derrickmehaffy** [comment] 2023-02-17 13:51
> Man, I thought about that on the walk earlier (updating axios), and great suggestion cause it seems to work now! 

Glad you got it all fixed up, I'll go ahead and set this as closed. :)

**Closed by derrickmehaffy** 2023-02-17 13:51 UTC
