### ISSUE TITLE
BadRequest 400 (invalid token) when login with provider (google)

### ISSUE THREAD

**Issue by fellz** [strapi/strapi#7489] opened 2020-08-16 10:32 UTC
**Describe the bug**
When i use login with provider ( google) i got 400 error BadRequest, invalid token

**Steps to reproduce the behavior**
I follow this guide https://strapi.io/documentation/v3.x/plugins/users-permissions.html#providers

1. Created page loginprovider /loginprovider
2. Put there link to http://localhost:1337/connect/google
3. Created redirect URL to front-end app ->  `http://localhost:3000/connect/google/redirect`
4. Click link at loginporivder -> go to google, choose account to authenticate
5. Got redirect to `http://localhost:3000/connect/google/redirect?id_token=ej...` with id_token=ej...
6. Made get query to `/auth/google/callback?access_token=${this.$route.query.id_token}`  i use nuxt.js
7. Got an error BadRequest - Invalid token, invalid value 

**Expected behavior**
Should get response with user and jwt

**System**

- Node.js version: 12.16.1
- NPM version:  6.14.6
- Strapi version: 3.1.4
- Database: sqlite
- Operating system: windows

**Additional context**
If i put `/auth/google/callback` in front-end url then i got user and jwt from backend in json format

**Comment by fellz** [comment] 2020-08-16 15:08
The problem in **grant, purest, request** packages. It makes request to `https://accounts.google.com/o/oauth2/tokeninfo` with query string `?access_token=dfg...` but google doesn't accept `access_token` - correct query `?id_token=dfg...`.

**Comment by derrickmehaffy** [comment] 2020-08-17 16:56
The `access_token` should be sent to your frontend which then relays that back to Strapi to make the request. We have updated our `login-react` example here: https://github.com/strapi/strapi-examples/tree/master/login-react

That example should provide you with a better testing environment so you can see how the 3rd party auth works.

**Comment by fellz** [comment] 2020-08-17 19:41
> The `access_token` should be sent to your frontend which then relays that back to Strapi to make the request. We have updated our `login-react` example here: https://github.com/strapi/strapi-examples/tree/master/login-react
> 
> That example should provide you with a better testing environment so you can see how the 3rd party auth works.

I saw example.
I implemented this call in my app. https://github.com/strapi/strapi-examples/blob/219e36b9a111cac587db0a65b11ab1eae1b1ea4c/login-react/src/pages/LoginRedirect.js#L15
``` 
fetch(`${backendUrl}/auth/${params.providerName}/callback${location.search}`)
```

It will not work because `location.search` will return `id_token=ssdf..` when it hits google and then 'No token provided' because

https://github.com/strapi/strapi/blob/b39709a6edee136047260aefca34069e4cf8b0f8/packages/strapi-plugin-users-permissions/services/Providers.js#L27

```
const connect = (provider, query) => {
  const access_token = query.access_token || query.code || query.oauth_token;

  return new Promise((resolve, reject) => {
    if (!access_token) {
      return reject([null, { message: 'No access_token.' }]);
    }
```
I am providing correct `access_token` but grant makes wrong request to google.

**Comment by derrickmehaffy** [comment] 2020-08-17 20:21
Indeed I will ping @petersg83 to review when he gets a moment.

**Comment by fellz** [comment] 2020-08-17 20:31
> Indeed I will ping @petersg83 to review when he gets a moment.

I found solution. This line shoud be changed 

https://github.com/strapi/strapi/blob/b39709a6edee136047260aefca34069e4cf8b0f8/packages/strapi-plugin-users-permissions/services/Providers.js#L192

to `.qs({ id_token: access_token })` and it will work as expected )

**Comment by derrickmehaffy** [comment] 2020-08-17 20:35
@fellz can you submit a PR? :hugs:

**Comment by petersg83** [comment] 2020-08-18 16:48
Hi :)
Can you please show me the params you have put in strapi?
It should look like sommething like that:

<img width="930" alt="Capture d’écran 2020-08-18 à 18 47 04" src="https://user-images.githubusercontent.com/11708220/90541743-5b7b6400-e183-11ea-9975-f2c6af34bc63.png">

**Comment by fellz** [comment] 2020-08-20 06:51
@petersg83 sure, they are exactly like mine
![Screenshot_2](https://user-images.githubusercontent.com/96966/90726539-8f14d600-e2ca-11ea-8284-61583dff8c3c.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/96966/90726561-9805a780-e2ca-11ea-9373-d6284f286fe7.jpg)

**Comment by petersg83** [comment] 2020-08-20 09:29
Thanks!
Did you use your own front-end app or did you use the example app?

If you haven't tried, can you please try with the example app? To have a better understanding of where it comes from.
Clone this repo https://github.com/strapi/strapi-examples.
Then `cd strapi-examples/login-react && yarn install`.
Then launch it with `REACT_APP_BACKEND_URL=http://localhost:1337 yarn start`.
And then try to log in with google.

**Comment by fellz** [comment] 2020-08-20 11:31
> Thanks! Indeed it looks good
> Did you use your own front-end app or did you use the example app?
> 
> If you haven't tried, can you please try with the example app? To have a better understanding of where it comes from.
> Clone this repo https://github.com/strapi/strapi-examples.
> Then `cd strapi-examples/login-react && yarn install`.
> Then launch it with `REACT_APP_BACKEND_URL=http://localhost:1337 yarn start`.
> And then try to log in with google.

I guess we found the issue. Maybe you didn't notice. 

https://github.com/strapi/strapi/blob/b39709a6edee136047260aefca34069e4cf8b0f8/packages/strapi-plugin-users-permissions/services/Providers.js#L192

This line should be changed to `.qs({ id_token: access_token })` and it will work as expected .

**Comment by derrickmehaffy** [comment] 2020-08-24 13:56
Marking as closed per @fellz 

If you hit any more issues please let us know :smiley:

**Closed by derrickmehaffy** 2020-08-24 13:56 UTC
Labels: priority: medium, source: plugin:users-permissions, type: bug

**Comment by niwasmala** [comment] 2021-01-03 02:06
Hi, I'm having same problem. Using Strapi version 3.4.1 here. When I change `.qs({ id_token: access_token })`, it works fine. Seems like the problem appears when using new project in Google Cloud Developers?

**Comment by derrickmehaffy** [comment] 2021-01-04 14:54
@niwasmala can you open up a new issue, or create a thread on our Forum: https://forum.strapi.io

As the issue is a bit older

**Comment by niwasmala** [comment] 2021-01-05 00:00
My bad. The problem actually happen when I only send `id_token` as `access_token` when calling `STRAPI_BACKEND_URL/auth/${provider}/callback` 

As I'm seeing `id_token` as first parameter in `http://localhost:3000/connect/google/redirect?id_token=ej...` and didn't notice that there is `access_token` parameter. Sorry for the inconvenience 😢

**Comment by sebrojas14** [comment] 2022-03-22 01:37
> > Indeed I will ping @petersg83 to review when he gets a moment.
> 
> I found solution. This line shoud be changed
> 
> https://github.com/strapi/strapi/blob/b39709a6edee136047260aefca34069e4cf8b0f8/packages/strapi-plugin-users-permissions/services/Providers.js#L192
> 
> to `.qs({ id_token: access_token })` and it will work as expected . In my case i just replaced strapi `services/Providers.js` with fixed version in `extensions` folder and now it works fine!

how to?

**Comment by RioChndr** [comment] 2022-04-21 06:26
My Solution is follow [Copy some file to extentions](https://github.com/strapi/strapi/issues/12907#issuecomment-1081411799).

then, edit file `src/extensions/users-permissions/services/providers-list.js` on section `google`

```
case 'google': {
      const google = purest({ provider: 'google', config: purestConfig });

      return google
        .query('oauth')
        .get('tokeninfo')
        .qs({ id_token: access_token }) // <-- Update this line
        .request((err, res, body) => {
          if (err) {
            console.error(err);
            callback(err);
          } else {
            callback(null, {
              username: body.email.split('@')[0],
              email: body.email,
            });
          }
        });
      break;
    }

```

**Comment by freebreix** [comment] 2024-06-16 16:12
For anyone lost, the right solution is to pass all of the params not just `id_token`
