### ISSUE TITLE
Exclude current entry from relationship options

### ISSUE THREAD

**Issue by maurice-ellis** [strapi/strapi#15997] opened 2023-03-05 15:26 UTC
### Required System information

- Node.js version: 18.14.2
- NPM version: 9.5.0
- Strapi version: 4.7.1
- Database: SQLite
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When adding a relationship with the same target as itself, the current model is not excluded from the options.

### Steps to reproduce the behavior

1. Create a model attribute with the same target as itself
2. Create or edit an entry
3. Select the relationship
4. See the current model included in the list.

### Expected behavior

I'm expecting that the current model would be excluded from the options for the current model can't be its own relation.

### Screenshots

![image](https://user-images.githubusercontent.com/7678232/222969628-f1026ae8-074f-4062-87e5-12f89bbd1f08.png)

### Code snippets

```
 Parent: {
    type: "relation",
    relation: "manyToOne",
    target: "plugin::page.page",
    inversedBy: 'Children',
    configurable: false
},
Children: {
    type: "relation",
    relation: "oneToMany",
    target: "plugin::page.page",
    mappedBy: "Parent",
    visible: false,
    configurable: false
},
```

**Comment by Marc-Roig** [comment] 2023-04-05 13:08
Hello ! This is actually an intended behavior of relations, there are use cases where it is actually valid to self relate to itself. An example:

- A user has some supervisors
- The supervisor of the user is itself

We could try to define customizations and constrains on the list of relations but that would be more of a feature request.

Sorry this can not fit your use case but I will close the issue as this is an intended behavior.

**Closed by Marc-Roig** 2023-04-05 13:08 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:content-manager
