### ISSUE TITLE
useContentManagerInitData issue in Strapi 5

### ISSUE THREAD

**Issue by Giacomo-Greco** [strapi/strapi#22090] opened 2024-11-06 16:07 UTC
Hi everybody, I really need your help. I'm experiencing a lot of troubles with strapi. Is there any chance someone can help me with the following issue?

Thanks a lot.

I'm using strapi 5 and these are my dependencies:

 "dependencies": {
    "@sendgrid/mail": "^8.1.3",
    "@strapi-community/strapi-provider-upload-google-cloud-storage": "^4.10.5",
    "@strapi/plugin-cloud": "5.0.2",
    "@strapi/plugin-documentation": "^5.1.0",
    "@strapi/plugin-users-permissions": "5.0.2",
    "@strapi/provider-email-sendgrid": "^5.1.0",
    "@strapi/provider-upload-aws-s3": "^5.1.1",
    "@strapi/email": "5.0.2",
    "@strapi/strapi": "5.0.2",
    "better-sqlite3": "9.4.3",
    "dayjs": "^1.11.13",
    "mysql2": "^3.11.3",
    "qs": "^6.13.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "react-router-dom": "^6.0.0",
    "strapi-provider-upload-google-cloud-storage": "^4.0.0",
    "styled-components": "^6.0.0"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "@typescript-eslint/eslint-plugin": "^8.8.0",
    "@typescript-eslint/parser": "^8.8.0",
    "dotenv-cli": "^7.4.2",
    "eslint": "^8.57.1",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-import": "^2.30.0",
    "eslint-plugin-prettier": "^5.2.1",
    "eslint-plugin-react": "^7.37.1",
    "husky": "^8.0.0",
    "lint-staged": "^15.2.10",
    "prettier": "^3.3.3",
    "typescript": "^5"
  },

<img width="1470" alt="Screenshot 2024-11-06 alle 17 06 09" src="https://github.com/user-attachments/assets/8c942ff9-3b9d-46af-bdd1-c96fc286fdd2">

**Comment by innerdvations** [comment] 2024-11-19 09:24
Duplicate of https://github.com/strapi/strapi/issues/21151

**Closed** 2024-11-19 09:25 UTC
Labels: status: duplicate
