### ISSUE TITLE
[strapi v5 Beta] Custom admin URL causes blank panel in the production environment.

### ISSUE THREAD

**Issue by iamobj** [strapi/strapi#20473] opened 2024-06-08 19:04 UTC
### Required System information

- Node.js version: 20.11.1
- NPM version: 10.2.4
- Strapi version: 5.0.0-beta.9
- Database: sqlite
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I configured the URL in `config/admin.ts`, and it works fine in the development environment. However, after building and starting the project, the admin panel displays a blank page. The reason is that in the production environment, static resources are still being loaded from the `/admin` path.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment] 2024-07-23 21:15
Can't reproduce on rc.6

![image](https://github.com/user-attachments/assets/a412a065-4190-4881-af77-0c9a8be7882c)

marking as closed

**Comment by centi** [comment] 2024-08-28 15:50
I have the same issue in RC12. @iamobj explicitly mentioned, that this issue occures only on production build (npm start) and not in development (npm run develop). But @derrickmehaffy closed this issue as not reproducible but his screenshot shows localhost.

I think that the `config/admin.ts` URL is not taken into account in the compiled index.html.

**Comment by derrickmehaffy** [comment] 2024-08-28 18:26
Confirmed on RC.12



![Image](https://github.com/user-attachments/assets/69c537da-ae2b-430b-b92a-0d99b24a04b6)

**Comment by alexandrebodin** [comment] 2024-08-29 07:36
Is this a v5 only bug or also v4 ? (when using vite bundling)

**Comment by centi** [comment] 2024-08-29 08:06
It is v5 only. We are now using v4 with the custom admin url and I noticed this bug while upgrading to v5 of Strapi.

**Comment by alexandrebodin** [comment] 2024-08-29 08:11
thanks for the quick answer 👍

**Comment by alexandrebodin** [comment] 2024-08-29 12:48
Closing know that the fix is merged. Will be available in next weeks rc

**Comment by alexandrebodin** [comment] 2024-08-29 12:48
cc @oiorain

**Closed by alexandrebodin** 2024-08-29 12:48 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:admin, version: 5
