### ISSUE TITLE
Pnpm build issue since 4.6.2

### ISSUE THREAD

**Issue by Hugofgx9** [strapi/strapi#16202] opened 2023-03-24 13:13 UTC
### Required System information

- Node.js version: 17.3.1
- NPM version: 8.3.0
- PNPM version: 7.30.0
- Strapi version: 4.6.2 to current
- Database: Postgresql
- Operating system: Ventura 13.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I get an error when I build the project from version 4.6.2

### Steps to reproduce the behavior

1. run 'pnpm run build'
2. See error at 52% building

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

I tried with the command 'pnpm run build --shamefully-hoist' but I get the same error
Here is the error i am getting : 
```
● Webpack █████████████████████████ building (52%) 0/1 entries 13652/13731 dependencies 3868/4039 modules 117 active 
 esbuild-loader › .cache/ee/admin/pages/SettingsPage/pages/Roles/EditPage/components/GlobalActions/utils/constants.js

ModuleNotFoundError: Module not found: Error: Can't resolve 'domain' in '/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/dist/cjs/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "domain": require.resolve("domain-browser") }'
        - install 'domain-browser'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "domain": false }
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:6883:13
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:958:45
    at finishWithoutResolve (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
resolve 'domain' in '/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/dist/cjs/node'
  Parsed request is a module
  using description file: /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/package.json (relative path: ./dist/cjs/node)
    resolve as module
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/dist/cjs/node/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/dist/cjs/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/dist/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules
        single file module
          using description file: /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/package.json (relative path: ./node_modules/domain)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain.tsx doesn't exist
        /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain doesn't exist
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/dljl_manager/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules
        single file module
          using description file: /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/package.json (relative path: ./node_modules/domain)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain.tsx doesn't exist
        /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve 'domain' in '/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/dist/cjs/node'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "domain": require.resolve("domain-browser") }'
        - install 'domain-browser'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "domain": false }
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/neo-async@2.6.2/node_modules/neo-async/async.js:6883:13
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/webpack@5.76.2_webpack-cli@5.0.1/node_modules/webpack/lib/NormalModuleFactory.js:958:45
    at finishWithoutResolve (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:41:15
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
resolve 'domain' in '/Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/dist/cjs/node'
  Parsed request is a module
  using description file: /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/package.json (relative path: ./dist/cjs/node)
    resolve as module
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/dist/cjs/node/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/dist/cjs/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/dist/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/asap/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/@react-dnd/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules
        single file module
          using description file: /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/package.json (relative path: ./node_modules/domain)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain.tsx doesn't exist
        /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/domain doesn't exist
      /Users/hugofaugeroux/Dev/others/dljl_manager/back/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/dljl_manager/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/others/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/Dev/node_modules doesn't exist or is not a directory
      /Users/hugofaugeroux/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules
        single file module
          using description file: /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/package.json (relative path: ./node_modules/domain)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain.jsx doesn't exist
            .react.js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain.react.js doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain.tsx doesn't exist
        /Users/hugofaugeroux/Dev/others/dljl_manager/back/strapi/node_modules/.pnpm/@strapi+admin@4.6.2_jf6dqmri2uq7ngoqdmmszgnch4/node_modules/@strapi/admin/node_modules/domain doesn't exist
```

Hugo

**Comment by stevejcox** [comment] 2023-03-26 20:13
I tweaked the webpack config, which seems to do the trick. 

```
// src/admin/webpack.config.js

'use strict';

/* eslint-disable no-unused-vars */
module.exports = (config, webpack) => {
  // Note: we provide webpack above so you should not `require` it
  // Perform customizations to webpack config
  // Important: return the modified config
  config.resolve.fallback = { 
    ...config.resolve.fallback,
    "domain": false 
  }
  return config;
};
```

**Comment by joshuaellis** [comment] 2023-03-27 07:39
Thanks for the report, this is a duplicate of #15992

**Closed by joshuaellis** 2023-03-27 07:39 UTC
