### ISSUE TITLE
Unable to find entity in afterCreate lifecycle method

### ISSUE THREAD

**Issue by gondar00** [strapi/strapi#9178] opened 2021-01-21 17:52 UTC
### Describe the bug

I am trying to find the created entity using 

```
async afterCreate(result) {
  const entity = await strapi.query('crop-stage').find({ id: result.id })
}
```

But I am getting back an empty object

What I really want to do is: 

```
async afterCreate(result) {
  result.id_from_external_api = id_from_external_api 
  const entity = await strapi.query('crop-stage').update({ id: result.id }, result)
}
```

### Steps to reproduce the behavior

- Create a `afterSave` lifecycle method
- Use `query` to find the created entity

### Expected behavior

I expected to get back the created entity

### Screenshots
![image](https://user-images.githubusercontent.com/12490590/105445205-5623c780-5c95-11eb-8dbb-c051c203ba8c.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 12.18.4
- NPM version: 6.14.6
- Strapi version: 3.4.3
- Database: MongoDB
- Operating system: Windows

### Additional context

If there is any other way to `update` the created entity inside `afterCreate` lifecycle method I would be glad to know

**Comment by eriskhan** [comment] 2021-01-21 21:06
Hey there! You should use 'data' in afterCreate, not 'result'.
About updating the created entity: I'd totally support that, however don't think that's possible to implement technically. Why? The problem is that in beforeCreate you're interacting with request data. So you can basically change request data before the request reaches your DB. In afterCreate it isn't possible because the request had already reached the DB.  Here's an image illustrating the lifecycle of each request:
![image](https://user-images.githubusercontent.com/20924122/105412298-96f3f000-5c45-11eb-9859-6fe8c56be0f5.png)

**Comment by gondar00** [comment] 2021-01-22 03:08
- Data doesn't contain `id` attribute which I need
- I think its possible technically because I am able to successfully do a `partial` update i.e 

```
strapi.query('crop-stage').update(
  { crop_name: result.crop_name },
  { id_from_external_api: response.id_from_external_api  }
)
```

- In my current model I do not have a unique attribute and I wanted to perform a full update i.e `update by id` 

ref - https://strapi.io/documentation/developer-docs/latest/concepts/queries.html#api-reference

**Comment by gondar00** [comment] 2021-01-22 03:44
@aleksandryackovlev can you please confirm if my usecase is technically possible or not?

**Comment by gondar00** [comment] 2021-01-22 03:44
@alexandrebodin can you please confirm if this usecase is possible or not

**Comment by alexandrebodin** [comment] 2021-01-22 08:32
Hi, what you are trying to do works for a test I just did. 

```js

module.exports = {
  lifecycles: {

    async afterCreate(entity) {
      console.log('afterCreate');
      await strapi.query('restaurant').update({ id: entity.id }, { name: 'Another name' });
    },
  }
}
```

I'm not sure I understand when do you receive an empty object ? on the find or on the lifecycle result ?

**Comment by gondar00** [comment] 2021-01-22 09:55
What I am trying to `update` is actually a `component` does that have a slightly different syntax as mentioned [here](https://strapi.io/documentation/developer-docs/latest/concepts/queries.html#api-reference)

> I'm not sure I understand when do you receive an empty object ? on the find or on the lifecycle result ?

Apologies, sorry for not being clear, I am pretty new to strapi,

1. When I use `strapi.query('restaurant').find({id: entity.id})` I was receiving empty object
2. When I used `await strapi.query('restaurant').update({ id: result.id }, entity)`, I was getting error saying `entry.notFound`

I just realized that the attribute I am trying to update is actually a component, 

The `entity` object looks like [this](https://jsoneditoronline.org/#left=cloud.9fda1938d42b4113b5fcbf015020432a&right=local.pabuzi) and I am trying to update the `stage` array which is a `component` in content type builder

**Comment by alexandrebodin** [comment] 2021-01-22 11:14
Alright thank you for the clarification.

Let's say your compo is named `staged`

You have two options

**Option 1**
```js
// update the full entity
async afterCreate(entity) {
  const newCompo = entity.stage;
  newCompo.newField = "something";
  
  await strapi.query('model-uid').update({ id: entity.id }, { stage: newCompo })
}
```

**Option 2**
```js
// update the compo directly
async afterCreate(entity) {
  const compoId = entity.stage.id;

  await strapi.query('compo-uid').update({ id: compoId }, { fieldofTheCompoYouWantUpdate: 'newValue' })
}
```

**Comment by derrickmehaffy** [comment] 2021-01-22 21:07
Going to mark this one as closed for now since it's not a bug per say but just a technical question. Please feel free to continue the discussion or if you feel this is closed in error please let me know.

**Closed by derrickmehaffy** 2021-01-22 21:07 UTC
Labels: type: help wanted

**Comment by gondar00** [comment] 2021-01-24 10:13
Thank you @alexandrebodin, option 2 worked for me, you the best 😎
