### ISSUE TITLE
New blue floating button causes pagination element unclickable.

### ISSUE THREAD

**Issue by kenkz447** [strapi/strapi#3000] opened 2019-03-20 03:08 UTC
**Informations**
- **Node.js version**: 10.7.0 
- **NPM version**: 6.8.0
- **Strapi version**: 3.0.0-alpha.25 
- **Database**: Mongodb
- **Operating system**: Windows 10

**What is the current behavior?**
Click to change page in Content Manager

**Steps to reproduce the problem**
- In "Content Types menu", click a item
- Find and move mouse to page 2 link
- Click to go to page 2

**What is the expected behavior?**
- Unable to click page 2 link
- It happen on small and medium window viewport with 10 or more items in table.

**Comment by soupette** [comment] 2019-03-20 17:46
I agree I have noticed it also in the content type builder where we have all the delete CTAs that cannot be clicked because of the button...

@Aurelsicoko

**Comment by lauriejim** [comment] 2019-03-21 15:07
This issue has screenshot https://github.com/strapi/strapi/issues/3000

Duplicate issue. Closing this one.
In any case, thank you for this report.

**Comment by kenberkeley** [comment] 2019-03-25 22:36
![image](https://user-images.githubusercontent.com/13287948/54958648-938c7080-4faa-11e9-95c9-21e41249b474.png)

**Comment by derrickmehaffy** [comment] 2019-03-26 09:40
@lauriejim reopening because you referenced this same issue, there isn't a duplicate here.

**Comment by derrickmehaffy** [comment] 2019-03-26 09:40
Related but not exactly a duplicate: https://github.com/strapi/strapi/issues/3006

**Comment by derrickmehaffy** [comment] 2019-03-26 09:42
I can confirm this bug, if you have more than 10 entries (say 20) you can't use the paging options due to the help videos icon: 
![image](https://user-images.githubusercontent.com/8593673/54986901-ba2db580-4f70-11e9-83eb-08d6ad03852f.png)

**Comment by lauriejim** [comment] 2019-03-26 12:48
Okay clear

**Comment by derrickmehaffy** [comment] 2019-03-26 13:03
(I would gently say that this should be a high priority considering it makes paging basically impossible unless you manually change the page in the URL header bar)

Maybe even critical :stuck_out_tongue:

**Comment by lauriejim** [comment] 2019-03-26 16:01
True it's an high priority.

**Closed** 2019-04-02 15:09 UTC
Labels: priority: high, status: confirmed, type: bug 🐛
