### ISSUE TITLE
Cannot select the text of the component category input

### ISSUE THREAD

**Issue by lauriejim** [strapi/strapi#5176] opened 2020-02-04 14:13 UTC
**Describe the bug**
When a value is entered in the component category input, the input value is not selectable. 

**Steps to reproduce the behavior**
1. Go to the Content Type Builder plugin
2. Click to create a new Component
3. Enter a value into the category name input (and create the categetogy)
4. Then click in the input (you can't select and navigate in the input)

**Expected behavior**
To be able to navigate in the input value.

**Screenshots**
Here is a short video of the issue.

https://www.loom.com/share/ab8be160a8354e80b62fe94535250b06

**System**
- Node.js version: v12.14.1
- NPM version: 6.13.4
- Strapi version: v3.0.0-beta.18.7
- Database: SQLite
- Operating system: MacOs

**Comment by soupette** [comment] 2020-02-07 11:35
Thanks for reporting this issue.
In fact the bug is due to the [React select](https://react-select.com/creatable) library.
You can see the similar behaviour that after creating an item you cannot edit it.

If you want to edit the entered created category the lib requires you to delete it first by using the "x" button and re-create it.

I am closing this issue as this is the intended behaviour otherwise it would mean that you can edit already created categories.

**Closed by soupette** 2020-02-07 11:35 UTC
Labels: priority: low, type: enhancement 💅
