### ISSUE TITLE
Date fields should not default to current time when no default is specified (postgres)

### ISSUE THREAD

**Issue by websocket98765** [strapi/strapi#3997] opened 2019-09-14 19:53 UTC
**Describe the bug**

Date fields created in Content Type Builder default to the current timestamp, but should default to NULL when no default was specified when this field was defined.

**Steps to reproduce the behavior**

1. Create a Date field and do not specify a default:
<img width="649" alt="CTB" src="https://user-images.githubusercontent.com/41795874/64912901-882e2c80-d725-11e9-9a1b-ca7c30e1cbdd.png">
Details:
<img width="902" alt="CTB settings" src="https://user-images.githubusercontent.com/41795874/64912902-8a908680-d725-11e9-95ab-2320903f4c61.png">
Foo.settings.json:
<img width="174" alt="model json" src="https://user-images.githubusercontent.com/41795874/64912906-98460c00-d725-11e9-8fd8-f01fcaf1a26e.png">

2. Create an entry for the Content Type via the Strapi admin and do not specify a value for this property.

3. View the database (Postgres) to see its value:
<img width="225" alt="DB data" src="https://user-images.githubusercontent.com/41795874/64912926-10accd00-d726-11e9-819f-8d85495614e1.png">
4. We can confirm that the table was set up with a default value the tables DDL (in Postico): 
<img width="497" alt="ddl" src="https://user-images.githubusercontent.com/41795874/64912933-3043f580-d726-11e9-85b8-5c100e24c417.png">

**Expected behavior**
Value should default to NULL since no value was entered and no default value was specified when setting up this field in Content Type Builder. Causes incorrect data.

**Expected behavior**
Value defaults to current timestamp.

**System**
- Node.js version: 10.16.3
- NPM version: 6.11
- Strapi version: Strapi v3.0.0-beta.16.3
- Database: Postgres
- Operating system: MacOS

**Comment by websocket98765** [comment] 2019-09-14 19:56
Related? https://github.com/strapi/strapi/issues/3862  But that is labeled as a feature request, so not sure how the team interpreted that report. Might be different, so I want to report this buggy behavior.

**Comment by derrickmehaffy** [comment] 2019-09-14 20:03
Agreed @websocket98765 all the date fields are planned to be reworked here soon.

Also I think this would be a duplicate of this issue: https://github.com/strapi/strapi/issues/2300

But you are correct they should not auto fill

**Comment by derrickmehaffy** [comment] 2019-09-14 20:05
This is the rework issue on date, time, datetime, and timestamp. (with timestamp being the type that auto-fills)

**Comment by lauriejim** [comment] 2019-09-16 14:55
Hello! I close this issue because it's a duplicate of issues that @derrickmehaffy linked.
Thank you for this feedback.

**Closed by lauriejim** 2019-09-16 14:55 UTC
