### ISSUE TITLE
When uploading asset in admin interface, request method is GET

### ISSUE THREAD

**Issue by stat1k** [strapi/strapi#8908] opened 2020-12-16 11:08 UTC
### Describe the bug

When I'm uploading a file in the assets with the admin interface, the method of the request is GET instead of POST. 
On my localhost, everything is fine, the request to upload a file is a POST one as it should be.
But on my server the request is a GET one and it returns a 404 so it doesn't work.

### Steps to reproduce the behavior

Add a file to the assets in the admin interface.

### Expected behavior

The request should be a POST one and not return a 404

### Screenshots

![screenshot_strapi](https://user-images.githubusercontent.com/3199782/102340845-4c70bb00-3f97-11eb-8c01-b595c6e555d1.png)

### System

On my server :

- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.1
- Database: SQLite
- Operating system: Ubuntu
 
On my local :

- Node.js version: 12.18.3
- NPM version: 6.14.6
- Strapi version: 3.1.1
- Database: SQLite
- Operating system: macOS Mojave 10.14.6

**Comment by derrickmehaffy** [comment] 2020-12-22 21:05
> Strapi version: 3.1.1

Please test with the current release version (v3.4.1)

**Comment by derrickmehaffy** [comment] 2021-01-22 20:38
User hasn't responded on request to test with latest version, marking as closed as couldn't reproduce.

**Closed by derrickmehaffy** 2021-01-22 20:38 UTC
Labels: status: pending reproduction
