### ISSUE TITLE
GraphQL query to nested Has Many relationships fails with fatal error

### ISSUE THREAD

**Issue by jorisw** [strapi/strapi#7902] opened 2020-09-15 09:41 UTC
**Describe the bug**
When there is a nested one-way Has Many relationship in the structure being queried using GraphQL, an error is thrown.

**Steps to reproduce the behavior**

1. Set up a nested structure where there is a Has Many relationship inside a Has Many relationship. Example:
```
- Flow, has many:
   - Steps, has many:
      - Screens
```
2. Go to http://localhost:1337/graphql
3. Paste query cited below
4. See error cited below

**Expected behavior**
I expect the GraphQL response to be like the final cited query below.

**Actual behavior**
The error cited below is the response to executing the query in Strapi's GraphQL console web app.

**System**
- Node.js version: 12.10.0
- Yarn version: 1.22.5
- NPM version: 6.10.3
- Strapi version: 3.1.4
- Database: Whatever the Strapi 3.1.4 default is
- Operating system: macOS 10.15.6

**Additional context**

I have a `Flows` collection type that has a `Has Many` relation ship to `Steps`.

I have a `Step` collection type that has a `Has Many` relationship to `Screens`. 

My query:

```
{
  flows {
    steps {
      screens {
        route
      }
    }
  }
}
```

Result:

```
{
  "errors": [
    {
      "message": "Your filters contain a field 'undefined' that doesn't appear on your model definition nor it's relations",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "flows",
        0,
        "steps",
        0,
        "screens"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "status": 400,
          "stacktrace": [
            "Error: Your filters contain a field 'undefined' that doesn't appear on your model definition nor it's relations",
            "    at getAssociationFromFieldKey (./node_modules/strapi-utils/lib/build-query.js:35:19)",
            "    at ./node_modules/strapi-utils/lib/build-query.js:117:48",
            "    at Array.map (<anonymous>)",
            "    at normalizeClauses (./node_modules/strapi-utils/lib/build-query.js:108:6)",
            "    at buildQuery (./node_modules/strapi-utils/lib/build-query.js:152:21)",
            "    at Object.find (./node_modules/strapi-connector-bookshelf/lib/queries.js:61:14)",
            "    at fn (./node_modules/strapi-database/lib/queries/helpers.js:31:54)",
            "    at Object.find (./node_modules/strapi-database/lib/queries/helpers.js:15:24)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
          ]
        }
      }
    }
  ],
  "data": {
    "flows": [
      {
        "steps": [
          {
            "screens": null
          }
        ]
      }
    ]
  }
}
```

When I change the nested relationship between Steps and Screens to Has Many And Belongs To Many, the query succeeds:

```
{
  "data": {
    "flows": [
      {
        "steps": [
          {
            "screens": []
          }
        ]
      }
    ]
  }
}
```

Probably the same as https://github.com/strapi/strapi/issues/4353 , which was prematurely closed.

**Comment by derrickmehaffy** [comment] 2020-09-29 14:27
I was unable to reproduce this on v3.1.6 using the following test project (admin login info is `test@test.com` and `Test1234!`):

[test7902.zip](https://github.com/strapi/strapi/files/5299737/test7902.zip)

![image](https://user-images.githubusercontent.com/8593673/94571878-42a3ab00-0225-11eb-9309-e7ce373bbe84.png)

**Comment by derrickmehaffy** [comment] 2020-10-15 15:39
As we have received no new information, marking as closed

**Closed by derrickmehaffy** 2020-10-15 15:39 UTC
Labels: status: can't reproduce
