### ISSUE TITLE
Admin Panel changes doesn't work

### ISSUE THREAD

**Issue by baermathias** [strapi/strapi#8064] opened 2020-09-26 17:16 UTC
**Describe the bug**
I followed these instructions (https://strapi.io/documentation/3.0.0-beta.x/admin-panel/customization.html#development-mode), but adding the following changes does nothing to the admin panel:
- Adding `strapi-project/admin/assets/images/logo-strapi.png` (size 434x120).
- Adding `strapi-project/admin/assets/images/logo_strapi.png` (size 434x120).
- Adding `strapi-project/admin/src/components/LeftMenuHeader` with `index.js` and `Wrapper.js`, where I made a color change inside `Wrapper.js` like this `background-color: #A49673;`
- Adding `strapi-project/admin/src/config.js` with the following code:
```Javascript
export const LOGIN_LOGO = null;
export const SHOW_TUTORIALS = false;
export const SETTINGS_BASE_URL = '/settings';
```

I also run `npm run build` and also started strapi with `--watch-admin` flag.

**Steps to reproduce the behavior**
See above

**Expected behavior**
See a different logo, background color, no video tutorial links, etc.

**System**

- Node.js version: v12.18.2
- NPM version: 6.14.5
- Strapi version: 3.1.6
- Database: Sqlite
- Operating system: Ubuntu 19.10

**Additional context**
By the way when I run strapi with --watch-admin flag I get multiple warnings like the following ones. I also tried to delete node_modules and package-lock and then reinstall everything, the warnings are still there:
```
  Multiple versions of deepmerge found:
    1.5.2 ./~/deepmerge from ./~/react-with-direction/dist/withDirection.js
    2.2.1 ./~/formik/~/deepmerge from ./~/formik/dist/formik.cjs.development.js
  Multiple versions of es-abstract found:
    1.17.6 ./~/array.prototype.find/~/es-abstract from ./~/array.prototype.find/implementation.js
    1.18.0-next.0 ./~/es-abstract from ./~/es-abstract/helpers/callBind.js
  Multiple versions of escape-string-regexp found:
    2.0.0 ./~/@sindresorhus/transliterate/~/escape-string-regexp from ./~/@sindresorhus/transliterate/index.js
    4.0.0 ./~/@sindresorhus/slugify/~/escape-string-regexp from ./~/@sindresorhus/slugify/index.js

```

**Comment by purnellbp** [comment] 2020-09-28 17:07
Did you try `npm run build -- --clean` ?

**Comment by derrickmehaffy** [comment] 2020-09-28 17:08
It appears the docs you are referencing are the old ones, see: https://strapi.io/documentation/v3.x/admin-panel/customization.html#development-mode

**Comment by baermathias** [comment] 2020-09-30 06:09
@purnellbp Just tried it out, no changes,
@derrickmehaffy Just checked the docs, I did it exactly as it is mentioned there

**Comment by derrickmehaffy** [comment] 2020-09-30 21:21
Alright going to break this down a bit on how I tested, using the `yarn develop --watch-admin`

### Removing tutorial videos

Created the `./admin/src/config.js`

```
export const LOGIN_LOGO = null;
export const SHOW_TUTORIALS = false;
export const SETTINGS_BASE_URL = '/settings';
```

**Result**: worked fined, hot-reloaded and tutorials were gone
![image](https://user-images.githubusercontent.com/8593673/94739810-64d12200-0326-11eb-9385-cd165944b46d.png)


### Swapping out logo files

Added my own test images for both
- `./admin/src/assets/images/logo-strapi.png`
- `./admin/src/assets/images/logo_strapi.png`

**Result**: worked fine, did need to manually refresh with a `ctrl + r` to blow away chrome's image cache. Excuse the poor example image

![image](https://user-images.githubusercontent.com/8593673/94740304-4586c480-0327-11eb-83b0-4a1701fb1d7a.png)

### Swapping Left Menu header background

Copied the following content: https://raw.githubusercontent.com/strapi/strapi/master/packages/strapi-admin/admin/src/components/LeftMenu/LeftMenuHeader/Wrapper.js into `./admin/src/components/LeftMenu/LeftMenuHeader/Wrapper.js`

And tweaked the background color with `background-color: #A49673;`

**Result**: Worked fine (again excuse the poor example image)

![image](https://user-images.githubusercontent.com/8593673/94740753-0147f400-0328-11eb-8c0b-cf408f4d40b2.png)

### Other

I'm not sure what changes were made in the referenced `index.js` but I don't believe there should be an issue there.

I've attached the test project I was using for you to take a look at: 
[test8064.zip](https://github.com/strapi/strapi/files/5308299/test8064.zip)

Let me know if there are issues that I didn't cover

**Comment by derrickmehaffy** [comment] 2020-10-15 14:44
As no new information provided, marking as closed.

**Closed by derrickmehaffy** 2020-10-15 14:44 UTC
Labels: type: help wanted

**Comment by giusecapo** [comment] 2020-10-20 07:56
@purnellbp @derrickmehaffy I have the same issue here. How did you solve it? It has nothing to do with how I customize admin panel, but as I start "strapi develop --watch-admin" I get this conflict error:
```
es-abstract
  Multiple versions of es-abstract found:
    1.17.7 ./~/array.prototype.find/~/es-abstract from ./~/array.prototype.find/implementation.js
    1.18.0-next.1 ./~/es-abstract from ./~/es-abstract/helpers/callBind.js
```

I did some research. It seems to be webpack-related issue (https://github.com/ljharb/es-abstract/issues/84). Let me know if you solved it and how you did! Thanks.

**Comment by derrickmehaffy** [comment] 2020-10-20 12:53
Entirely different issue.

**Comment by giusecapo** [comment] 2020-10-20 12:59
"Additional context" written by the author. It looks pretty relevant to me!

**Comment by derrickmehaffy** [comment] 2020-10-20 17:32
The issue in this case was the author was not seeing the changes, the error raised by from that additional context is a different issue to the root issue that I attempted to reproduce.

Can you please open up a new bug report with the context of your issue and any steps we can do to reproduce the issue?

**Comment by soupette** [comment] 2020-10-22 07:26
> "Additional context" written by the author. It looks pretty relevant to me!

It just that you have two different version of the same dependency that is in your build it's not an issue but more a warning.

**Comment by baermathias** [comment] 2020-11-04 09:50
Sorry for the late feedback, it was my fault! I had the wrong folder structure as can be seen in my initial post:

> Adding strapi-project/admin/assets/images/logo-strapi.png (size 434x120).
> Adding strapi-project/admin/assets/images/logo_strapi.png (size 434x120).
> Adding strapi-project/admin/src/components/LeftMenuHeader with index.js and Wrapper.js

It has to be `.../admin/src/...` and for the LeftMenuHeader it has to be `.../LeftMenu/LeftMenuHeader...`

@derrickmehaffy Thank you very much for your effort, it helped me to solve this issue!
