### ISSUE TITLE
TypeError destroy is not a function

### ISSUE THREAD

**Issue by prborisov17** [strapi/strapi#16994] opened 2023-06-13 04:51 UTC
### Required System information

- Node.js version: v18.16.0
- NPM version: 9.5.1
- Strapi version: 4.11.1
- Database: MySQL
- Operating system: Windows 10 22H2
- Is your project Javascript or Typescript: Javascript

### Describe the bug

destroy is not a function
TypeError: destroy is not a function
    at safelyCallDestroy (webpack-internal:///10344:22927:5)
    at commitHookEffectListUnmount (webpack-internal:///10344:23095:11)
    at commitPassiveUnmountInsideDeletedTreeOnFiber (webpack-internal:///10344:25093:11)
    at commitPassiveUnmountEffectsInsideOfDeletedTree_begin (webpack-internal:///10344:25043:5)
    at commitPassiveUnmountEffects_begin (webpack-internal:///10344:24951:11)
    at commitPassiveUnmountEffects (webpack-internal:///10344:24936:3)
    at flushPassiveEffectsImpl (webpack-internal:///10344:27033:3)
    at flushPassiveEffects (webpack-internal:///10344:26979:14)
    at commitRootImpl (webpack-internal:///10344:26930:5)
    at commitRoot (webpack-internal:///10344:26677:5)

### Steps to reproduce the behavior

1. Go to Content Manager
2. Click on Collection Item edit
3. Click on Back or Main Menu Item

### Screenshots
![image](https://github.com/strapi/strapi/assets/131133955/5f8f65f0-513c-40f4-8432-733bdc64944d)
![image](https://github.com/strapi/strapi/assets/131133955/ddb12cfa-d39c-4137-a6ac-3055c0fb3ab5)
![image](https://github.com/strapi/strapi/assets/131133955/6a0c4bc5-2ce5-40e2-9fcf-5b837a7676e8)

**Comment by Renkas** [comment] 2023-06-13 10:41
This seems to be same issue as in my report: #16998 

If I go through your repro case I see the same result as you and the error for me in the console is same as in my report.

**Comment by abdbadgithub** [comment] 2023-06-14 10:18
hi i updated the seo plugin from 1.8.0 to 1.9.1 (latest) and everything is now is working properly

**Comment by boazpoolman** [comment] 2023-06-17 07:48
This issue is likely caused by the [sitemap plugin](https://github.com/boazpoolman/strapi-plugin-sitemap).
A fix has since been released with `v2.0.11`. Upgrading to that version should do the trick.

The crash was caused by a faulty implementation of an async React `useEffect` hook.
See [the commit](https://github.com/boazpoolman/strapi-plugin-sitemap/commit/7208c87faf87b710007ecef49db00ba295bb7d65) that fixed the issue.

If you're not using the sitemap plugin - or upgrading doesn't fix the issue for you - you're probably using another plugin that also has this faulty `useEffect` implementatino in their codebase.

**Closed** 2023-06-17 10:05 UTC

**Comment by eli-taft-quoin** [comment] 2023-10-19 15:23
If you have written custom plugins, the cause might be the same thing that was broken in the above-referenced sitemap plugin. Here's the file they fixed: https://github.com/boazpoolman/strapi-plugin-sitemap/blob/67763eb20d6bfa5a73b8fa9e389877f67340ae59/admin/src/components/CMEditViewExclude/index.js#L19. 

Notice:

- they removed `async` from the `useEffect` hook
- they moved the async logic to another function
- they call that new async function within `useEffect` without using `await`.
- after the `useEffect` hook, they check whether the async content has been set or not. If not, return null.

I updated two of my plugins with this logic and it fixed the problem for me.
