### ISSUE TITLE
Can anyone look at Gatsby Source Strapi?

### ISSUE THREAD

**Issue by tranlehaiquan** [strapi/strapi#8293] opened 2020-10-12 10:18 UTC
**Describe the bug**
First: Sorry for post in strapi repo. Gatsby-source-strapi is outdated. Many issues and pull requests need to be a review like this: https://github.com/strapi/gatsby-source-strapi/pull/147 So please anyone look at this? 

**Steps to reproduce the behavior**

1. Go to https://github.com/strapi/gatsby-source-strapi
2. Check issues and pull request

**Expected behavior**

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Additional context**

**Comment by derrickmehaffy** [comment] 2020-10-13 17:58
@lauriejim @alexandrebodin correct me if I'm wrong, but aren't we looking for a maintainer for this repo?

**Comment by derrickmehaffy** [comment] 2020-10-13 17:59
Going to mark this as closed as it's not a bug and the template isn't filled out, but will be raising the issue with the team internally to get a response.

**Closed by derrickmehaffy** 2020-10-13 17:59 UTC
Labels: type: help wanted

**Comment by alexandrebodin** [comment] 2020-10-14 08:14
Right now we are short handed on this lib but will pick it up after some important changes in V4

**Comment by tranlehaiquan** [comment] 2020-10-14 17:12
@alexandrebodin It cools to hear that. But this still helpful for people how using the older versions?

**Comment by alexandrebodin** [comment] 2020-10-15 07:50
@tranlehaiquan Hey sorry but I'm not sure I understood your message. I'll try to spend some time on it in the next 2 week to merge a few PR and release a new version.

**Comment by tranlehaiquan** [comment] 2020-10-31 09:58
Any news?

**Comment by alexandrebodin** [comment] 2020-11-02 09:37
Nope no news we can't find the time to work on it right now. If you need extra fature you might want to fork it for now
