### ISSUE TITLE
Api content type json field not working

### ISSUE THREAD

**Issue by ZiedChekir** [strapi/strapi#721] opened 2018-03-01 22:29 UTC
i created a new content type with a JSON field with the name data then i created a new data But in mlab the Json field type was string not json i tried with diffent inputs as shown in the picture but i couldnt get it to work.
![capture d ecran 2018-03-01 23 24 51](https://user-images.githubusercontent.com/18351368/36873300-59b61c4c-1da8-11e8-9de6-f1f8f6fa39d6.png)

![capture d ecran 2018-03-01 23 05 49](https://user-images.githubusercontent.com/18351368/36872920-3136f792-1da7-11e8-95a4-85a44b213de0.png)
![capture d ecran 2018-03-01 23 08 07](https://user-images.githubusercontent.com/18351368/36872933-39e4dd28-1da7-11e8-8f6c-6e5f6253677c.png)

**Comment by lauriejim** [comment] 2018-03-05 09:29
I close this issue, duplicate of https://github.com/strapi/strapi/issues/496

**Closed by lauriejim** 2018-03-05 09:29 UTC
