### ISSUE TITLE
No pagination When using Strapi + GraphQL + MySQL

### ISSUE THREAD

**Issue by benramsay** [strapi/strapi#13157] opened 2022-04-19 16:33 UTC
Hello, 
I was using strapi with sqlite + graphQL. In this context it was possible to use "pagination". 
After that I started a new project, but based on mySQL + graphQL. And in this new context 
the same queries using pagination, that has been working with sqlite context , does not work anymore with the new MySQL context.

You can see in images: with sqlite I have : {pagination, filters, sort,... }
With MySql I had only {sort}

Did I forget something ?
Thx

![Capture d’écran 29](https://user-images.githubusercontent.com/96269862/164050954-36400758-8bf4-44c4-880a-6bc25542844c.jpg)
![Capture d’écran 2022-04-19 182519](https://user-images.githubusercontent.com/96269862/164050957-15b7fb9a-3eb7-4fb0-b99d-2eace873401e.jpg)

**Comment by FanghanHu** [comment] 2022-04-19 19:34
I am also using MYSQL here, and my schema doesn't have anything other than sort as well.
![image](https://user-images.githubusercontent.com/3207447/164081690-75f8dccd-925f-4bf1-8dde-d1b3838daa7e.png)

**Comment by bulby97** [comment] 2022-04-20 07:44
I don't think it's related to mySQL. We were using a long time project with Strapi + gQL + Postgres and after updating the dependencies, we lost filters and pagination

**Comment by Convly** [comment] 2022-04-20 07:47
Hi, thanks for opening this issue, which version are you using?

**Comment by bulby97** [comment] 2022-04-20 07:48
@Convly Thanks for replying. 4.1.7

```
    "@strapi/plugin-graphql": "4.1.7",
    "@strapi/plugin-i18n": "4.1.7",
    "@strapi/plugin-users-permissions": "4.1.7",
    "@strapi/provider-upload-cloud
```

**Comment by Convly** [comment] 2022-04-20 07:49
I'll look into it later today and try to reproduce/fix it. I'll keep you posted.

**Comment by bulby97** [comment] 2022-04-20 12:55
@Convly for whatever reason, the issue has been fixed for me by updating the yarn.lock file.

**Comment by Convly** [comment] 2022-04-20 13:38
Hey, glad you were able to fix it by updating the lockfile.
On my side I tried to reproduce it on a clean 4.1.7 application and failed to do so.
![image](https://user-images.githubusercontent.com/25851739/164243150-6dab42d1-1748-4cd5-a8db-355d9624634e.png)

![image](https://user-images.githubusercontent.com/25851739/164242841-9457dfd5-0b7f-4ce6-8f4a-abcf4896781f.png)

**Comment by Convly** [comment] 2022-04-25 09:08
@benramsay / @FanghanHu if you're also using v4.1.7, could you try updating your yarn.lock file? I wasn't able to reproduce the issue on my side

**Comment by TartagliaEG** [comment] 2022-04-25 21:13
I was having the same issue, but reinstalling the plugin fixed it.

```
npm run strapi uninstall graphql
npm run strapi install graphql
```

My setup was made on v4.1.8 with postgres, so it doesn't seems to be related with the database choice.

Also, #13137 seems to be related.

**Comment by derrickmehaffy** [comment] 2022-05-18 22:28
Marking this as closed since we can't reproduce it.

**Closed by derrickmehaffy** 2022-05-18 22:28 UTC
Labels: issue: bug, status: can not reproduce, source: plugin:graphql
