### ISSUE TITLE
Missing image dimensions

### ISSUE THREAD

**Issue by rktyt** [strapi/strapi#12766] opened 2022-03-07 02:02 UTC
### Describe the bug

Only the files defined in <https://github.com/strapi/strapi/blob/v4.1.2/packages/core/upload/server/services/image-manipulation.js#L12> can be used for image It appears that the dimensions are being obtained.

The definition here is only to determine if rotate, optimize, or resize is possible, and should have nothing to do with obtaining dimensions.

### Expected behavior

Dimensions are set for all images that can be acquired.
We need the dimensions of all images (when retrieved via Rest/Graphql API).

### Screenshots

<img width="314" alt="スクリーンショット 2022-03-07 10 37 29" src="https://user-images.githubusercontent.com/26789317/156953793-389a0763-7e40-475d-a8f5-ee6732d078d0.png">

### System

- Node.js version: 16
- NPM version: 8
- Strapi version: 4.1.2
- Database: mysql8
- Operating system: debian11

**Comment by jingkang99** [comment] 2022-03-11 17:21
this might be the root cause of starter GUI fail to lauch.
https://github.com/strapi/strapi-starter-next-corporate/issues/77
seems not many people working on this. try ghost later,
![image](https://user-images.githubusercontent.com/10793075/157916124-3adc70a6-3a24-46e4-8458-f8055f32cb5b.png)

**Comment by Zharkan** [comment] 2022-04-23 18:29
Then I probably opened a duplicate issue [here](https://github.com/strapi/strapi/issues/12823).

**Comment by Uniiq** [comment] 2022-04-27 09:24
I have the same issue with strapi version: 4.1.8.

**Comment by lexa18** [comment] 2022-04-27 19:46
Confirm problem version: 4.1.9

**Comment by rktyt** [comment] 2022-05-06 07:15
Same issue https://github.com/strapi/strapi/issues/13230

**Comment by rktyt** [comment] 2022-05-26 06:17
Are there any updates?

Here is an idea:

- `getDimensions` in image-manipulation.js move to a different new file.
- Calls to `getDimensions` should be outside the `isSupportedImage` discrimination.
- Use libraries like <https://github.com/SidOfc/leather> in `getDimensions`

Then <https://feedback.strapi.io/customization/p/video-dimensions-for-video-upload> can be supported too.

**Comment by jlabeit** [comment] 2022-06-06 19:14
I can also confirm this with version 4.1.12. I am wondering is there a known workaround for now? Or does anyone know with which version the issue occurred?

**Comment by gu-stav** [comment] 2022-06-07 07:05
I'll try to bring this issue to the attention of our team again soon and let you know once we decided something.

**Comment by gu-stav** [comment] 2022-06-21 10:52
[A fix has been merged](https://github.com/strapi/strapi/pull/13580) and will be released in the upcoming 4.2.1 release in approx. 2 weeks. 🚀

**Closed** 2022-06-21 10:52 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:upload
