### ISSUE TITLE
CustomFields not correctly loaded 

### ISSUE THREAD

**Issue by Torsten85** [strapi/strapi#15491] opened 2023-01-18 21:26 UTC
### Required System information

Strapi 4.5.6

### Describe the bug

When switching between collection / singleton types, the used custom fields on that types are not correctly loaded.
Only the custom fields on the first collection / singleton type you visit gets loaded. 
Fields from types you visit after that are not loaded add all, the UI only shows "not Supported"

### Steps to reproduce the behavior

1. Create two singleton types and two custom fields, use one field on the first type, the other field on the second
2. Open the first singleton in the content manager
3. See that the custom field is loaded
4. open the 2nd singleton without reloading the full page
5. See the "Not Supported" message where the 2nd custom field show be shown

### Expected behavior

All should load

### Code snippets

The custom fields are loaded with the `useLazyComponents` hook
This hook uses the following condition to check if anything should be loaded:

https://github.com/strapi/strapi/blob/0a4a76112a781d23a1f19e4ae1343431f81410c2/packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js#L39

the problem is `loading`, which is `true` when the hook is called for the first time with component uids, and `false` for every successive calls.

This can be seen here:

https://github.com/strapi/strapi/blob/0a4a76112a781d23a1f19e4ae1343431f81410c2/packages/core/admin/admin/src/content-manager/hooks/useLazyComponents/index.js#L4-L17

the first call loads the component store, and from there on `componentStore.size` will always be greater than 0.

**Comment by rktyt** [comment] 2023-01-19 01:39
same as https://github.com/strapi/strapi/issues/15273

**Comment by joshuaellis** [comment] 2023-01-19 08:15
This is a duplicate of #15273, so i'm gonna close this in favour of it.

**Closed by joshuaellis** 2023-01-19 08:15 UTC
Labels: status: duplicate
