### ISSUE TITLE
App Crashes 500 Error when Registering user with duplicate email or username

### ISSUE THREAD

**Issue by alexgrant999** [strapi/strapi#14281] opened 2022-08-31 18:57 UTC
### Required System information

- Node.js version: v16
- NPM version: v8.1.2
- Strapi version: 4.3.4
- Database: MySQL
- Operating system: MacOS 12.0

### Describe the bug

When registering a user for with the same email or username a 2nd time, the app crashes and gives a 500 error instead of returning a message that there is a duplicate user: 

`{
    "data": null,
    "error": {
        "status": 500,
        "name": "InternalServerError",
        "message": "Internal Server Error"
    }
}`

2022-09-01 04:53:26.183] http: POST /api/auth/local/register (2033 ms) 200
[2022-09-01 04:53:31.148] error: Email or Username are already taken
ApplicationError: Email or Username are already taken
    at Object.register (/Users/alexgrant/development/strapi-2022/somatic-coaching/node_modules/@strapi/plugin-users-permissions/server/controllers/auth.js:316:13)

### Steps to reproduce the behavior

1. Post to '{{url}}/api/auth/local/register'
2. data:{
    "username": "333333",
    "email": "333333@findyoga.com.au",
    "password": "333333"
}
3. Register same user twice
5. See error

### Expected behavior

The app returns a 400 error with a message that there is a duplicate user and does not throw an exception and crash

**Comment by bolg55** [comment] 2022-08-31 19:51
I'm not able to reproduce following the above steps

<img width="1242" alt="Screen Shot 2022-08-31 at 3 49 58 PM" src="https://user-images.githubusercontent.com/43022248/187769390-d2051022-d004-49aa-ad76-23e55bed3815.png">
<img width="624" alt="Screen Shot 2022-08-31 at 3 50 15 PM" src="https://user-images.githubusercontent.com/43022248/187769394-ac582b82-56d7-4c51-875e-e3c81b7948ac.png">

**Comment by alexgrant999** [comment] 2022-08-31 20:02
@bolg55  
Strange, here are my screenshots: 
<img width="883" alt="Screen Shot 2022-09-01 at 6 00 12 am" src="https://user-images.githubusercontent.com/4098580/187771118-5e6702f4-08c5-49d6-9a07-e6fbd517f82d.png">
<img width="981" alt="Screen Shot 2022-09-01 at 6 01 15 am" src="https://user-images.githubusercontent.com/4098580/187771317-3bf13c24-9e20-4952-8779-340e2b9cc4e4.png">

**Comment by ZhenFTW** [comment] 2022-09-02 15:24
![image](https://user-images.githubusercontent.com/17694257/188182440-46509f36-c05d-4e67-876e-2c3cf8bbae66.png)
Same issue

**Comment by alexgrant999** [comment] 2022-09-03 01:55
@ZhenFTW @bolg55 
I wonder if the problem has to do with koa or redis? 
https://forum.strapi.io/t/strapi-auth-local-500-error/12958/5

**Comment by Tina-otoge** [comment] 2022-09-12 08:52
I had the same issue but managed to fix it.
When using `strapi@4.3.8` but with `@strapi/plugin-users-permissions` pinned to 4.3.6, along with some of my other plugins, the issue was occuring.
I have set my strapi plugins to use version `latest` in my packages.json and only pin the strapi version, deleted my yarn.lock and reinstalled dependencies, and the problem is now gone.

**Comment by alexgrant999** [comment] 2022-09-15 21:09
> I had the same issue but managed to fix it. When using `strapi@4.3.8` but with `@strapi/plugin-users-permissions` pinned to 4.3.6, along with some of my other plugins, the issue was occuring. I have set my strapi plugins to use version `latest` in my packages.json and only pin the strapi version, deleted my yarn.lock and reinstalled dependencies, and the problem is now gone.

I have tried updating the plugins to the latest and tried strapi version 4.3.6 and also 4.3.8, I am still getting the same error. 
<img width="636" alt="Screen Shot 2022-09-16 at 7 08 03 am" src="https://user-images.githubusercontent.com/4098580/190509043-db4316a7-db96-4c7d-85ad-5e921272c86f.png">

**Comment by alexgrant999** [comment] 2022-09-18 03:39
@bolg55 
OK, so I have just hacked into the file:
/@strapi/plugin-users-permissions/server/controllers/auth.js
Commented out the Throw new error, and it stops crashing and returns the expected 400 error.  


Lines 308 - 324, 
`
  const conflictingUserCount = await strapi.query('plugin::users-permissions.user').count({
      where: { ...identifierFilter, provider },
    });

    // if (conflictingUserCount > 0) {
    //   throw new ApplicationError('Email or Username are already taken');
    // }

    if (settings.unique_email) {
      const conflictingUserCount = await strapi.query('plugin::users-permissions.user').count({
        where: { ...identifierFilter },
      });

      // if (conflictingUserCount > 0) {
      //   throw new ApplicationError('Email or Username are already taken');
      // }
    }

`

**Comment by Namstel** [comment] 2022-10-05 10:19
I also ran into this problem while running locally. My solution was to remove the `/node_modules` folder and `package-lock.json` file and then perform another `npm i`. Somehow that fixed it.

**Comment by alexgrant999** [comment] 2022-10-06 09:40
> I also ran into this problem while running locally. My solution was to remove the `/node_modules` folder and `package-lock.json` file and then perform another `npm i`. Somehow that fixed it.

@Namstel Seems like the version 4.4.3 has fixed it..  Must have been a bug in earlier versions of the User Permissions plugin.

**Comment by derrickmehaffy** [comment] 2022-10-07 20:14
Marking as closed as 2 people verified that latest version fixes issue.

**Closed by derrickmehaffy** 2022-10-07 20:14 UTC
Labels: status: can not reproduce
