### ISSUE TITLE
WYSIWYG text editor

### ISSUE THREAD

**Issue by Nicolas-vrcc** [strapi/strapi#9518] opened 2021-02-25 09:16 UTC
Hello, I'd like a WYSIWYG text editor please. I find it pretty annoying to have to use markdown all the time.

**Comment by soupette** [comment] 2021-02-25 09:34
Hello, you can find some community plugins that allows you to change the WYSIWYG [here](https://github.com/strapi/awesome-strapi#CommunityWYSIWYGReplacements) , also in our [documentation](https://strapi.io/documentation/developer-docs/latest/guides/registering-a-field-in-admin.html#setup) there is a section explaining how to customise the fields in the content manager.

I am closing this issue as it not a bug and it does not respect the issue template.

**Closed by soupette** 2021-02-25 09:34 UTC
