### ISSUE TITLE
Image relations not preserved when cloning?

### ISSUE THREAD

**Issue by cjsewell** [strapi/strapi#19807] opened 2024-03-17 22:10 UTC
### Required System information

- Node.js version: node/v20.10.0 linux x64
- NPM version: node/v20.10.0 linux x64
- Strapi version: 4.20.5
- Database: Postgres
- Operating system: Ubunutu
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When cloning a content type, image relations are not copies to the cloned object

### Steps to reproduce the behavior

1. Go to a collection type containing an image
2. Click on the "Duplicate" items button
3. The resulting clone does not contain a relation to the image saved on the cloned data

### Expected behavior
The resulting cloned object should contain a relation to all media that was attached to the original object

### Additional context

I tried searching here and https://feedback.strapi.io/feature-requests as I am sure there would be a similar report, but I cannot find any...

Some key words: duplicate clone image media files

Thanks!

**Comment by derrickmehaffy** [comment] 2024-03-28 20:58
duplicate of: https://github.com/strapi/strapi/issues/19230

**Closed by derrickmehaffy** 2024-03-28 20:58 UTC
Labels: status: duplicate
