### ISSUE TITLE
[documentation-plugin]: Invalid OpenAPI specs: missing description in 200 response

### ISSUE THREAD

**Issue by DennisHartrampf** [strapi/strapi#12487] opened 2022-02-11 11:41 UTC
### Describe the bug

The documentation plugin generates JSON files that don't comply to the OpenAPI spec 3.0.0. This leads to other tools like openapi-generator to fail with errors, when using these files as input. This can only be circumvented by disabling the validation step of openapi-generator.
The precise problem described in this issue is, that 200 responses are missing the required attribute `description`.

### Expected behavior

The JSON file(s) generated by the documentation plugin should adhere to the OpenAPI spec 3.0.0. The plugin should include a description field for 200 responses.

### Code snippets

```json
{
  "/email": {
    "post": {
      "responses": {
        "200": {
          "content": {
            "...": { "...": "..." }
          }
        },
        "400": {
          "description": "Bad Request",
          "content": {
            "...": { "...": "..." }
          }
        }
      }
    }
  }
}
```

### System

- Node.js version: v16.13.2
- NPM version: 7.19.0
- Strapi version: 4.0.5
- Database: PostgreSQL and SQLite
- Operating system: Windows 8.1 Pro and Docker

**Comment by derrickmehaffy** [comment] 2022-02-14 21:58
Related but not duplicate of: https://github.com/strapi/strapi/issues/12485

**Closed** 2022-03-04 08:48 UTC
Labels: issue: bug, severity: low, status: confirmed, source: plugin:documentation
