### ISSUE TITLE
[Graphql] do a query with sort, if two entity has a the same value at the sort field, one will be set to null in response

### ISSUE THREAD

**Issue by wujun4code** [strapi/strapi#9035] opened 2021-01-04 12:04 UTC
### do Graphql query with `limit`&`start`&`sort`

```graphql
query($condition: JSON, $limit: Int, $start: Int, $sort: String) {
  products(where: $condition, limit: $limit, start: $start, sort: $sort) {
    id
    name
    valuation_price
  }
}
```
and the query vars is

``` json
{"condition":{"categories":{"name":"rubber"}},"limit":4,"start":0,"sort":"valuation_price:desc,name:asc"}
```
you will get the following response:

```json
{
  "data": {
    "products": [
      {
        "id": "5fcb2eb28eac47001dbc7745",
        "name": "rubber-tenergy-05",
        "valuation_price": 480
      },
      {
        "id": "5faeab233a23f8001d57bdde",
        "name": "donic-bluestorm-z1",
        "valuation_price": 220
      },
      null,
      {
        "id": "5f9464a9a876c0001d16681f",
        "name": "kuangbiao-3-province-orange",
        "valuation_price": 180
      },
      {
        "id": "5fcaeda38eac47001dbc7735",
        "name": "rubber-kuangbiao3-normal",
        "valuation_price": 100
      }
    ]
  }
}
```

> please focus on the third obj in array, it is null value.

but **If sort by name, it works well**

```json
{"condition":{"categories":{"name":"rubber"}},"limit":4,"start":0,"sort":"name:asc"}
```
response sort by name only
```json
{
  "data": {
    "products": [
      {
        "id": "5faeab233a23f8001d57bdde",
        "name": "donic-bluestorm-z1",
        "valuation_price": 220
      },
      {
        "id": "5f9464a9a876c0001d16681f",
        "name": "kuangbiao-3-province-orange",
        "valuation_price": 180
      },
      {
        "id": "5fcaeda38eac47001dbc7735",
        "name": "rubber-kuangbiao3-normal",
        "valuation_price": 100
      },
      {
        "id": "5fcb2eb28eac47001dbc7745",
        "name": "rubber-tenergy-05",
        "valuation_price": 480
      }
    ]
  }
}
```

### System

- Node.js version: v14
- NPM version: v.6.8
- Strapi version: v3.4.1
- Database: MongoDb
- Operating system: Mac OS Cartalina

**Comment by wujun4code** [comment] 2021-01-04 12:05
Before strapi v3.4.0, it works well.

**Comment by alexandrebodin** [comment] 2021-01-04 14:15
Hi, I can't seem to reproduce this. Can you share your models settings.json so I can have a better idea of the data you have :)

**Comment by wujun4code** [comment] 2021-01-04 14:17
```json
{
  "kind": "collectionType",
  "collectionName": "products",
  "info": {
    "name": "Product",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "attributes": {
    "categories": {
      "collection": "category",
      "via": "products"
    },
    "name": {
      "type": "uid"
    },
    "description": {
      "type": "richtext"
    },
    "specification": {
      "type": "richtext"
    },
    "reviews": {
      "collection": "review",
      "via": "product"
    },
    "special_notes": {
      "type": "richtext"
    },
    "belongs_to_brand": {
      "model": "brand",
      "via": "owned_products"
    },
    "basic_attributes": {
      "via": "related_by_products_as_basic",
      "collection": "attribute",
      "dominant": true
    },
    "marketing_attributes": {
      "via": "related_by_products_marketing",
      "collection": "attribute",
      "dominant": true
    },
    "remarks": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "title_attributes": {
      "via": "products_title",
      "collection": "attribute",
      "dominant": true
    },
    "usage_advice_attributes": {
      "via": "related_usage_advice_products",
      "collection": "attribute",
      "dominant": true
    },
    "valuation_price": {
      "type": "decimal"
    },
    "vendor_sellers": {
      "collection": "seller",
      "via": "selling_products"
    },
    "gallery": {
      "collection": "file",
      "via": "related",
      "allowedTypes": [
        "images",
        "files",
        "videos"
      ],
      "plugin": "upload",
      "required": false
    },
    "marketedAt": {
      "type": "date"
    },
    "shared_content": {
      "type": "json"
    },
    "special_tags": {
      "via": "ralated_by_products_special_tags",
      "collection": "attribute",
      "dominant": true
    }
  }
}

```

**Comment by derrickmehaffy** [comment] 2021-01-04 14:39
I too am unable to reproduce this on v3.4.1, @wujun4code it might be easier if you can link us to your project code or create a sample repo where you are able to reproduce the issue.

**Comment by wujun4code** [comment] 2021-01-04 14:42
@derrickmehaffy ok, I will add a demo project.

**Comment by alexandrebodin** [comment] 2021-01-04 14:54
I have been able to reproduce :) this will be fixed in https://github.com/strapi/strapi/pull/9020

**Comment by alexandrebodin** [comment] 2021-01-04 15:09
@wujun4code Can you try that PR out to verify it fixes your specific issue ?

**Comment by wujun4code** [comment] 2021-01-04 15:16
emm.. sorry, can not try it quickly, it is mid-night in China, my bed is calling me back..ahaha, I will take a test tomorrow.
Thanks.

**Closed** 2021-01-05 14:46 UTC
Labels: source: plugin:graphql, status: can't reproduce
