### ISSUE TITLE
Strapi Admin - GET to /admin/* urls should not be hardcoded

### ISSUE THREAD

**Issue by borm** [strapi/strapi#9027] opened 2021-01-01 16:51 UTC
### Describe the bug
[strapi-admin/admin/src/containers/App/index.js#L64](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/containers/App/index.js#L64)

Should not be hardcoded
```js
await request('/admin/renew-token')
...
const { data } = await request('/admin/init', { method: 'GET' });
```

### Steps to reproduce the behavior

1. Go to `/config/server.js
2. change config like bellow
```
module.exports = ({ env }) => ({
  url: env('URL', 'http://mydomain.com'),
  admin: {
   ...,
    autoOpen: false,
    url: '/dashboard'
});
```
3. change your nginx config [Nginx Proxying](https://strapi.io/documentation/developer-docs/latest/deployment/nginx-proxy.html#sub-domain)  like bellow
```
location /  {
    try_files $uri $uri/ /index.html;
}
location /dashboard {
    proxy_pass http://localhost:1337;
    ....
}
```
4. make `strapi build`
5. try to open localhost:1337/dashboard

![image](https://user-images.githubusercontent.com/4027842/103443042-d8573800-4c63-11eb-8284-6c1abd6c4f86.png)

### Expected behavior
u should use `strapi.config.admin.url` instead of '/admin'

**Comment by derrickmehaffy** [comment] 2021-01-03 03:44
Closing as duplicate of https://github.com/strapi/strapi/issues/8616

**Closed by derrickmehaffy** 2021-01-03 03:44 UTC
Labels: status: duplicate
