### ISSUE TITLE
Update to 4.12.0 fails

### ISSUE THREAD

**Issue by IlirEdis** [strapi/strapi#17500] opened 2023-07-28 14:53 UTC
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.6.7
- Strapi version: 4.12.0
- Database: better-sqlite3 8.4.0
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

While trying to update strapi to 4.12.0 i deleted the `node_modules` folder, `package-lock.json` and the `.cache` folder, then when running `npm install` i got the error in the screenshot below 

### Expected behavior

update Strapi to 4.12.0

### Screenshots

<img width="1187" alt="Screenshot 2023-07-28 at 16 49 02" src="https://github.com/strapi/strapi/assets/128377763/4fa42a07-4894-492a-b9fa-da09b2cf8dca">

### Code snippets

If applicable, add code samples to help explain your problem.

Whole error report: 

```
ilirbajrami@ILIRs-MacBook-Pro-2 edis-cms-cloud % npm install
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated mailcomposer@3.12.0: This project is unmaintained
npm WARN deprecated apollo-datasource@3.3.2: The `apollo-datasource` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated apollo-server-plugin-base@3.7.2: The `apollo-server-plugin-base` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated apollo-server-types@3.8.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated apollo-server-errors@3.3.1: The `apollo-server-errors` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated apollo-server-koa@3.10.0: The `apollo-server-koa` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated buildmail@3.10.0: This project is unmaintained
npm WARN deprecated apollo-server-env@4.2.1: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated apollo-reporting-protobuf@3.4.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm WARN deprecated apollo-server-core@3.12.0: The `apollo-server-core` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
npm ERR! code 1
npm ERR! path /Users/ilirbajrami/Desktop/Works(prej-1-qershor-2023)/EDIS/Graphics-and-UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild --release
npm ERR! TOUCH ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR!   ACTION deps_sqlite3_gyp_locate_sqlite3_target_copy_builtin_sqlite3 ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR! rm ba23eeee118cd63e16015df367567cb043fed872.intermediate
npm ERR! prebuild-install warn install No prebuilt binaries found (target=18.16.0 runtime=node arch=arm64 libc= platform=darwin)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.1
npm ERR! gyp info using node@18.16.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
npm ERR! gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/ilirbajrami/Desktop/Works(prej-1-qershor-2023)/EDIS/Graphics-and-UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/ilirbajrami/Library/Caches/node-gyp/18.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/ilirbajrami/Library/Caches/node-gyp/18.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/ilirbajrami/Library/Caches/node-gyp/18.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/ilirbajrami/Desktop/Works(prej-1-qershor-2023)/EDIS/Graphics-and-UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: -c: line 0: syntax error near unexpected token `('
npm ERR! /bin/sh: -c: line 0: `LD_LIBRARY_PATH=/Users/ilirbajrami/Desktop/Works(prej-1-qershor-2023)/EDIS/Graphics-and-UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3/build/Release/lib.host:/Users/ilirbajrami/Desktop/Works(prej-1-qershor-2023)/EDIS/Graphics-and-UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps; mkdir -p /Users/ilirbajrami/Desktop/Works(prej-1-qershor-2023)/EDIS/Graphics-and-UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3; node copy.js "/Users/ilirbajrami/Desktop/Works(prej-1-qershor-2023)/EDIS/Graphics-and-UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3" ""'
npm ERR! make: *** [ba23eeee118cd63e16015df367567cb043fed872.intermediate] Error 2
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 22.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /Users/ilirbajrami/Desktop/Works(prej-1-qershor-2023)/EDIS/Graphics-and-UI/Web/Projects/edis-cms-cloud/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /Users/ilirbajrami/.npm/_logs/2023-07-31T19_18_33_148Z-debug-0.log
```

**Comment by gu-stav** [comment] 2023-07-28 14:56
@IlirEdis It looks to me as if you are using a space in one of your folder names "Works (preij 1.)". It is a known issue sqlite can't compile in this case - renaming the folder should be the fix this case 🤞🏼

**Comment by IlirEdis** [comment] 2023-07-28 15:23
@gu-stav unfortunately i got the same error even after renaming all the folders with empty spaces (screenshot below):
<img width="1168" alt="Screenshot 2023-07-28 at 17 20 03" src="https://github.com/strapi/strapi/assets/128377763/314f694d-8d6d-437b-9d9b-670e54dd20cb">

Please not that i deleted the `.cache`, `node_modules` and `package-lock.json`. But its not working even after i put them back into the project

**Comment by IlirEdis** [comment] 2023-07-31 19:38
Issue updated, please reopen.

**Comment by IlirEdis** [comment] 2023-07-31 20:37
Ok, i managed to make it work after i reverted back the deleted folders and files (mentioned above) and setting the `better-sqlite` version to `8.0.1` which is the only version working. If i try to install a newer version i get the same error as above (while the latest update is `8.5.0`).

**Comment by derrickmehaffy** [comment] 2023-08-01 19:58
I can't reproduce on Linux, might be something to do with node-gyp or the node build tools on Mac?

**Comment by derrickmehaffy** [comment] 2023-08-01 20:03
@IlirEdis can you confirm the actual file/folder path to your Strapi project, specifically does the `(prej-1-qershor-2023)` actually exist in your path as it's shown in the logs: `/Users/ilirbajrami/Desktop/Works(prej-1-qershor-2023)/EDIS/...`

**Comment by IlirEdis** [comment] 2023-08-01 20:31
Hello @derrickmehaffy , When i `cd` to `Works(prej-1-qershor-2023)` directory i get `zsh: missing end of string`.

<img width="725" alt="Screenshot 2023-08-01 at 22 29 51" src="https://github.com/strapi/strapi/assets/128377763/f8f91d0c-b15c-41b8-998b-62116e05e103">

**Comment by IlirEdis** [comment] 2023-08-01 20:34
Does this mean that i shouldn't use parenthesis in file/folder names?

**Comment by 20x-dz** [comment] 2023-08-01 21:10
Did you try to copy/move the project to a path without parenthesis and retry?

**Comment by derrickmehaffy** [comment] 2023-08-01 21:40
I think the issue is the same as having a space, can you go into your Strapi project and run a `pwd` command (it dumps out the entire present working directory path).

But my guess is that for whatever reason better-sqlite builds aren't working with paths that contain special chars

**Comment by derrickmehaffy** [comment] 2023-08-01 21:40
Also just guessing but you are probably on an ARM-based mac and not an intel which I can't currently test as the only Mac device I have is an Intel one.

**Comment by IlirEdis** [comment] 2023-08-02 19:17
Ok, so i just copied the project into `Desktop` and it worked.

<img width="793" alt="Screenshot 2023-08-02 at 21 08 41" src="https://github.com/strapi/strapi/assets/128377763/19b834ca-638e-4b29-917e-862deb573d67">

Now whats the best way to go? Rename my folders and remove the special characters?

**Comment by 20x-dz** [comment] 2023-08-02 19:19
> Now whats the best way to go? Rename my folders and remove the special characters?
Yes (not the best, but the most straightforward way)

**Comment by IlirEdis** [comment] 2023-08-02 19:31
Yes, it works after renaming my folders. Thank you all!

**Comment by 20x-dz** [comment] 2023-08-02 19:52
Great. Feel free to close this bug and maybe open a bug upstream at [better-sqlite](https://github.com/WiseLibs/better-sqlite3/issues) for them to be able to look into it. Referencing this issue might help.

**Closed** 2023-08-03 04:27 UTC
Labels: issue: bug, severity: medium, source: dependencies, status: pending reproduction
