### ISSUE TITLE
Cannot create Content Type after quickstart/initialization

### ISSUE THREAD

**Issue by madflow** [strapi/strapi#9385] opened 2021-02-11 16:52 UTC
### Describe the bug

After following the quickstart example - I cannot create any Content-Type, when stopping the server - and cd*ing into the app folder and run `yarn start`

### Steps to reproduce the behavior

I have created a Strapi Project with:

`yarn create strapi-app strapi-cms --quickstart`

* The app compiles etc
* The the server start in development mode and opens the configured Browser
* I have create a Test user
* Loggout
* Stop the server with control-c

Then cd into the newly created app folder

* start Strapi with `yarn run start`
* visit the App http://localhost:1337/admin
* Goto Content-type Editor

* Then a popup displays with something about the autoreload feature has to be enabled
* I cannot create a new Content-Type

### Expected behavior

* I can create content types

### Screenshots

![grafik](https://user-images.githubusercontent.com/183248/107669068-a806ae80-6c91-11eb-8222-a6d041aeb8bf.png)

![grafik](https://user-images.githubusercontent.com/183248/107669260-d7b5b680-6c91-11eb-8108-bf0e0a2af863.png)

### System

- Node.js version: v12 latest
- NPM version: I used yarn 1.22.10
- Strapi version: 3.4.6 (node v12.20.1)
- Database: sqllite (I guess - I have not configured anything else)
- Operating system: Macos Mojave 10.14.6

**Comment by ruijt** [comment] 2021-02-11 17:23
I have the same problem

**Comment by derrickmehaffy** [comment] 2021-02-11 19:42
The content-type builder only works with the develop command: https://strapi.io/documentation/developer-docs/latest/cli/CLI.html#strapi-develop

And only in the development node env.

All new projects have a handful of scripts, the one you are looking for is `yarn develop` or `npm run develop`

The various CLI commands can used like `yarn strapi develop` as an example.

Marking as closed as not a bug.

**Closed by derrickmehaffy** 2021-02-11 19:42 UTC
