### ISSUE TITLE
Bug using filters operators

### ISSUE THREAD

**Issue by juanfh** [strapi/strapi#12731] opened 2022-03-03 07:49 UTC
## Bug report
When use an filter operator in the query it fails and throws a cors error:

### Describe the bug

If don't use operators all queries works fine in the server but when use any filter operator it gets a cors bug. In localhost all queries work fine (with or without operators).

In the server a query like this **https://myapi.com/api/table?filters[name]=thename** works fine but **https://myapi.com/api/table?filters[name][$eq]=thename** gets a cors error: 

`Access to XMLHttpRequest at 'http://myapi.com/api/...' from origin 'http://myapp.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

This happens when using any filter operator ($eq, $or, $and, $lt, …):

```
https://myapi.com/api/table?filters[$or][0][date][$eq]=2022-03-01&[$or][1]filters[date][$eq]=2022-04-01
https://myapi.com/api/table?filters[$and][0][quantity][$lte]=2&[$and][1]filters[quantity][$gte]=5
...
```

### System

- Node.js version: v14.19.0
- NPM version: v6.14.16
- Strapi version: v4.0.7
- Database: MariaDB

**Comment by kasonde** [comment] 2022-03-03 10:21
Without information about where/how this project is deployed and if you're using a reverse proxy on the server and how you're making requests to the API (postman/client app of some sort), I am unable to reproduce this issue. (You deleted the steps to reproduce section of the issue template)

**Comment by derrickmehaffy** [comment] 2022-03-28 23:16
@juanfh I tested on a deployed application and I can't reproduce, we need more information on methods to reproduce the issue.

Marking as closed until we get more information

**Closed by derrickmehaffy** 2022-03-28 23:16 UTC
Labels: status: can not reproduce

**Comment by jonathanschlitt** [comment] 2022-09-11 17:35
Hey, i have exactly the same error. All requests are working but only the filter (?populate=*&filters[Slug][$eq]=test) is causing this error.

I hope someone can help.

**Comment by jonathanschlitt** [comment] 2022-09-11 17:37
> @juanfh I tested on a deployed application and I can't reproduce, we need more information on methods to reproduce the issue.
> 
> Marking as closed until we get more information

I think you can open this issue again ;)

**Comment by derrickmehaffy** [comment] 2022-09-12 21:38
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
