### ISSUE TITLE
Unable to publish a draft record, fails with "let not supported" MongoError

### ISSUE THREAD

**Issue by ocasiom** [strapi/strapi#10049] opened 2021-04-15 14:46 UTC
### Describe the bug

Hi, I am getting MongoError: "let not supported" when trying to publish a draft record. This is a fresh installation of Strapi using the quickstart and connecting to Azure CosmosDB for MongoDB. 

### Steps to reproduce the behavior

1. Go to admin, add a new Single Type, I called mine "Hello World"
2. Add a "name" text field and Save the new type
3. Add a new record of type "Hello World", I entered "test" in the name field
4. Click save
5. Click publish, error occurs

### Expected behavior
Record would be published

### System

- Node.js version: 12.18.4
- NPM version: yarn 1.22.10
- Strapi version: 3.5.4
- Database: Azure CosmosDB for MongoDB (3.6)
- Operating system: Windows 10 Home Development Machine

### Additional context

Here is the console output with stack trace:

```
[2021-04-15T14:33:45.954Z] debug GET /admin/users/me/permissions (232 ms) 200
[2021-04-15T14:33:46.123Z] debug GET /content-manager/content-types (123 ms) 200
[2021-04-15T14:33:46.173Z] debug GET /content-manager/content-types (139 ms) 200
[2021-04-15T14:33:46.278Z] debug GET /content-type-builder/components (125 ms) 200
[2021-04-15T14:33:46.305Z] debug GET /content-type-builder/reserved-names (120 ms) 200
[2021-04-15T14:33:46.327Z] debug GET /content-type-builder/content-types (148 ms) 200
[2021-04-15T14:33:47.095Z] debug GET /content-manager/content-types (100 ms) 200
[2021-04-15T14:33:47.122Z] debug GET /content-manager/components (126 ms) 200
[2021-04-15T14:33:47.295Z] debug GET /content-manager/content-types/plugins::users-permissions.user/configuration (150 ms) 200
[2021-04-15T14:33:47.574Z] debug GET /content-manager/collection-types/plugins::users-permissions.user?page=1&pageSize=10&_sort=username:ASC (190 ms) 200
[2021-04-15T14:33:52.276Z] debug GET /content-manager/content-types/application::hello-world.hello-world/configuration (141 ms) 200
[2021-04-15T14:33:52.470Z] debug GET /content-manager/single-types/application::hello-world.hello-world (183 ms) 404
[2021-04-15T14:33:58.789Z] debug PUT /content-manager/single-types/application::hello-world.hello-world (649 ms) 200
[2021-04-15T14:34:00.863Z] error MongoError: let not supported
    at MessageStream.messageHandler (C:\dev\CaravelLabsWeb\mongo-project\node_modules\mongodb\lib\cmap\connection.js:268:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (C:\dev\CaravelLabsWeb\mongo-project\node_modules\mongodb\lib\cmap\message_stream.js:144:12)
    at MessageStream._write (C:\dev\CaravelLabsWeb\mongo-project\node_modules\mongodb\lib\cmap\message_stream.js:42:5)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MessageStream.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.ondata (_stream_readable.js:716:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
[2021-04-15T14:34:00.863Z] debug POST /content-manager/single-types/application::hello-world.hello-world/actions/publish (231 ms) 500
[2021-04-15T14:34:05.134Z] error MongoError: let not supported
    at MessageStream.messageHandler (C:\dev\CaravelLabsWeb\mongo-project\node_modules\mongodb\lib\cmap\connection.js:268:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (C:\dev\CaravelLabsWeb\mongo-project\node_modules\mongodb\lib\cmap\message_stream.js:144:12)
    at MessageStream._write (C:\dev\CaravelLabsWeb\mongo-project\node_modules\mongodb\lib\cmap\message_stream.js:42:5)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at MessageStream.Writable.write (_stream_writable.js:318:11)
    at TLSSocket.ondata (_stream_readable.js:716:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
[2021-04-15T14:34:05.144Z] debug POST /content-manager/single-types/application::hello-world.hello-world/actions/publish (201 ms) 500
```

**Comment by aksdevac** [comment] 2021-04-19 12:15
I think Azure CosmosDB is not same as MongoDB & its not yet supported by strapi.

**Comment by derrickmehaffy** [comment] 2021-04-19 20:02
Exactly @aksdevac it's not the same as mongodb and it's not a supported database.

Marking as closed as I can't reproduce on MongoDB itself (local or atlas)

**Closed by derrickmehaffy** 2021-04-19 20:02 UTC
