### ISSUE TITLE
The publicationState parameter is not defaulted to live

### ISSUE THREAD

**Issue by WalkingPizza** [strapi/strapi#12739] opened 2022-03-03 11:35 UTC
### Describe the bug

When using the entity service, `findMany` defaults `publicationState` to `preview` instead of `live` as mentioned [in the docs](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/entity-service/crud.html#findmany). This means you will always get draft content unless you explicitly set `publicationState` to `live`, which is quite annoying.

### Steps to reproduce the behavior

1. Create a draftable content type called `Restaurants`
2. Create a restaurant, but don't publish it
3. Run `entityService.findMany` anywhere in your code without specifying the `publicationState` parameter and notice how the result contains the restaurant contained in step 2 even if it shouldn't.

### Expected behavior

The `publicationState` parameter should be defaulted to `live` as per the docs, so that `findMany` does not return drafted content unless the dev wants it to.

### Code snippets

Altering the `convertPublicationStateParams` function to automatically inject `live` as the default value fixes the issue, but breaks the admin panel, which no longer shows draft content.

I assume the admin panel relies on the entity service, so the ideal fix would be to make such change in `convertPublicationStateParams` and then alter the admin panel code so that it sets `publicationState` to `preview` by default.

### System

- Node.js version: 14.18.2
- Yarn version: 1.22.17
- Strapi version: 4.1.2 and 4.0.6
- Database: Postgres
- Operating system: MacOS / Alpine

### Additional context

https://github.com/strapi/strapi/blob/e764f35dd2a9d248477baa3491196049ea5c9fca/packages/core/utils/lib/convert-query-params.js

**Comment by iicdii** [comment] 2022-03-03 12:07
Confirmed.
If you run `strapi.entityService.findMany`, `publicationState: live` filter is not applied by default.
The `publicationState` filter is applied when auto-generates content-type.

https://github.com/strapi/strapi/blob/50733c4f51a7ad5fa2522950fbe05fd097afbce5/packages/core/strapi/lib/core-api/controller/collection-type.js#L24

https://github.com/strapi/strapi/blob/master/packages/core/strapi/lib/core-api/service/collection-type.js#L30

https://github.com/strapi/strapi/blob/master/packages/core/strapi/lib/core-api/service/index.js#L30-L40

As you can see the code, the core-api service injects publicationState filter to entityService.
By the way if you run `strapi.service(uid).find(uid, params)` you can get only live entries.

**Comment by Krak86** [comment] 2022-11-02 14:21
Is it bug and will be fixed in future or not documented feature that everyone should know and never been fixed?
Can someone clarify?

**Comment by derrickmehaffy** [comment] 2022-11-02 17:29
> Is it bug and will be fixed in future or not documented feature that everyone should know and never been fixed? Can someone clarify?

Bug to be fixed in the future

**Comment by eliasleyton** [comment] 2022-12-09 13:16
Any news relative this issue?

**Comment by parsagholipour** [comment] 2023-02-04 19:01
is there any workaround for this?

**Comment by Krak86** [comment] 2023-02-06 13:27
> Is there any workaround for this?

use explicit status in query:
```
{
     publishedStatus: "published",     
}
```

**Comment by Namstel** [comment] 2023-04-06 13:52
Is it too much to ask to remove it from the docs where it says the default is `live`? 
https://docs.strapi.io/dev-docs/api/entity-service/crud#findmany

**Comment by alexandrebodin** [comment] 2023-07-12 12:45
The doc was updated since then and this is intended that using programmatic APIs you will get the biggest amount of data. We do that to enforce explicit code & queries without too much magic happening. 

Going to close as we will not change the behavior in v4.

**Closed by alexandrebodin** 2023-07-12 12:45 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:database
