### ISSUE TITLE
The 'compilation' argument must be an instance of Compilation - Upgrade from 4.0.0 to 4.0.2

### ISSUE THREAD

**Issue by bobaved** [strapi/strapi#12030] opened 2021-12-27 13:46 UTC
### Describe the bug

After I upgraded from Strapi 4.0.0 to Strapi 4.0.2 following this guide
https://docs.strapi.io/developer-docs/latest/update-migration-guides/update-version.html#upgrade-your-dependencies

When building Strapi again I receive this webpack error(also on Heroku):

`Building your admin UI with development configuration ...
TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/home/devday2019/projects/headless/hertha-strapi/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:141:10)
    at /home/devday2019/projects/headless/hertha-strapi/node_modules/terser-webpack-plugin/dist/index.js:566:67
    at _next33 (eval at create (/home/devday2019/projects/headless/hertha-strapi/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:44:1)
    at _next11 (eval at create (/home/devday2019/projects/headless/hertha-strapi/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
    at Hook.eval [as call] (eval at create (/home/devday2019/projects/headless/hertha-strapi/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:123:1)
    at Hook.CALL_DELEGATE [as _call] (/home/devday2019/projects/headless/hertha-strapi/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/devday2019/projects/headless/hertha-strapi/node_modules/@strapi/admin/node_modules/webpack/lib/Compiler.js:1031:26)
    at /home/devday2019/projects/headless/hertha-strapi/node_modules/@strapi/admin/node_modules/webpack/lib/Compiler.js:1073:29
    at Hook.eval [as callAsync] (eval at create (/home/devday2019/projects/headless/hertha-strapi/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/devday2019/projects/headless/hertha-strapi/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/devday2019/projects/headless/hertha-strapi/node_modules/@strapi/admin/node_modules/webpack/lib/Compiler.js:1068:28)
    at /home/devday2019/projects/headless/hertha-strapi/node_modules/@strapi/admin/node_modules/webpack/lib/Compiler.js:496:12
    at Compiler.readRecords (/home/devday2019/projects/headless/hertha-strapi/node_modules/@strapi/admin/node_modules/webpack/lib/Compiler.js:908:11)
    at /home/devday2019/projects/headless/hertha-strapi/node_modules/@strapi/admin/node_modules/webpack/lib/Compiler.js:493:11
    at Hook.eval [as callAsync] (eval at create (/home/devday2019/projects/headless/hertha-strapi/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/devday2019/projects/headless/hertha-strapi/node_modules/tapable/lib/Hook.js:18:14)`

### Steps to reproduce the behavior

1. Change Strapi package.json depencies from 4.0.0 to 4.0.2
2. Do npm|yarn install
3. Build strapi

### Expected behavior

Build of Strapi should work.

### Code snippets

Dependecies I have changed:
`  "dependencies": {
    "@strapi/design-system": "^0.0.1-alpha.70",
    "@strapi/plugin-graphql": "^4.0.2",
    "@strapi/plugin-i18n": "4.0.2",
    "@strapi/plugin-users-permissions": "4.0.2",
    "@strapi/strapi": "4.0.2",
    "pg": "^8.7.1",
    "pg-connection-string": "^2.5.0",
    "sqlite3": "5.0.2"
  },`

### System

- Node.js version: 16 lts
- NPM version: 8.1.2
- Strapi version: 4.0.0
- Database: sqlite (local) postgres (prd)
- Operating system: linux

**Comment by derrickmehaffy** [comment] 2021-12-27 17:11
Can you please try a `yarn build --clean` or a `npm run build -- --clean`

**Comment by nfrasser** [comment] 2021-12-28 01:05
> Can you please try a `yarn build --clean` or a `npm run build -- --clean`

Getting the same issue, I can confirm that this did not work for me.

**Comment by codeorelse** [comment] 2021-12-28 09:07
Same issue:

### System

Node.js version: 14.18.1
NPM version: 8.1.2
Strapi version: 4.0.2
Database: sqlite (local) postgres (prd)
Operating system: macOS Monterey

**Comment by derrickmehaffy** [comment] 2021-12-28 16:57
I spun up a test app yesterday on heroku and I can't reproduce this: 

https://github.com/derrickmehaffy/strapi-test-v4-herokuDeploy
https://fierce-citadel-78889.herokuapp.com/

@codeorelse You specifically shouldn't be using npm 8 with Node 14. If you are on Node 14 you should be on npm 6 as npm 8 is only for node 16+

**Comment by nfrasser** [comment] 2021-12-28 18:40
Some additional insight.

This error happens because on [this line](https://github.com/webpack/webpack/blob/v5.65.0/lib/javascript/JavascriptModulesPlugin.js#L140) the `compilation` instance is derived from `node_modules/@strapi/admin/node_modules/webpack/lib/Compilation.js` but the `Compilation` class is declared in `node_modules/webpack/lib/Compilation.js`

This seems to be because the `@strapi/admin` package required a fixed version of webpack (5.36.2) compared to other dependencies (which resolve to 5.65.0 on my system).

Output of `npm why webpack`:
```
webpack@5.36.2
node_modules/@strapi/admin/node_modules/webpack
  webpack@"5.36.2" from @strapi/admin@4.0.2
  node_modules/@strapi/admin
    @strapi/admin@"4.0.2" from @strapi/strapi@4.0.2
    node_modules/@strapi/strapi
      @strapi/strapi@"4.0.2" from the root project
  peer webpack@"^5.1.0" from terser-webpack-plugin@5.3.0
  node_modules/@strapi/admin/node_modules/webpack/node_modules/terser-webpack-plugin
    terser-webpack-plugin@"^5.1.1" from webpack@5.36.2

webpack@5.65.0 peer
node_modules/webpack
  peer webpack@"4.x.x || 5.x.x" from @webpack-cli/configtest@1.1.0
  node_modules/@webpack-cli/configtest
    @webpack-cli/configtest@"^1.1.0" from webpack-cli@4.9.1
    node_modules/webpack-cli
      webpack-cli@"4.9.1" from @strapi/admin@4.0.2
      node_modules/@strapi/admin
        @strapi/admin@"4.0.2" from @strapi/strapi@4.0.2
        node_modules/@strapi/strapi
          @strapi/strapi@"4.0.2" from the root project
<truncated for brevity>
```

OS: macOS 12.1
Node version: v15.14.0
NPM version: v7.7.6
Dependencies:
```
"@strapi/plugin-i18n": "4.0.2",
"@strapi/plugin-users-permissions": "4.0.2",
"@strapi/provider-upload-aws-s3": "4.0.2",
"@strapi/strapi": "4.0.2",
"pg-connection-string": "^2.4.0",
"sqlite3": "5.0.2"
```

**Comment by nfrasser** [comment] 2021-12-28 18:43
I also tried switching to yarn but got the following error:
```
$ yarn run build
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: @strapi/admin tried to access object-assign, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: object-assign
Required by: @strapi/admin@npm:4.0.0 (via .yarn/cache/@strapi-admin-npm-4.0.0-b083d9a1ca-39e39b7365.zip/node_modules/@strapi/admin/)

Require stack:
- .yarn/cache/@strapi-admin-npm-4.0.0-b083d9a1ca-39e39b7365.zip/node_modules/@strapi/admin/webpack.alias.js
- .yarn/cache/@strapi-admin-npm-4.0.0-b083d9a1ca-39e39b7365.zip/node_modules/@strapi/admin/webpack.config.js
- .yarn/cache/@strapi-admin-npm-4.0.0-b083d9a1ca-39e39b7365.zip/node_modules/@strapi/admin/index.js
- .yarn/unplugged/@strapi-strapi-npm-4.0.0-c988dbe88c/node_modules/@strapi/strapi/lib/commands/build.js
- .yarn/unplugged/@strapi-strapi-npm-4.0.0-c988dbe88c/node_modules/@strapi/strapi/bin/strapi.js
    at Function.external_module_.Module._resolveFilename (.pnp.cjs:27159:55)
    at Function.resolve (node:internal/modules/cjs/helpers:98:19)
    at .yarn/cache/@strapi-admin-npm-4.0.0-b083d9a1ca-39e39b7365.zip/node_modules/@strapi/admin/webpack.alias.js:46:31
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (.yarn/cache/@strapi-admin-npm-4.0.0-b083d9a1ca-39e39b7365.zip/node_modules/@strapi/admin/webpack.alias.js:44:24)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.external_module_.Module._load (.pnp.cjs:27008:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
```

**Comment by derrickmehaffy** [comment] 2021-12-28 18:50
> I also tried switching to yarn instead of npm but got the following error:
> 
> ```
> $ yarn run build
> This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
> Error: @strapi/admin tried to access object-assign, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
> 
> Required package: object-assign
> Required by: @strapi/admin@npm:4.0.0 (via .yarn/cache/@strapi-admin-npm-4.0.0-b083d9a1ca-39e39b7365.zip/node_modules/@strapi/admin/)
> 
> Require stack:
> - .yarn/cache/@strapi-admin-npm-4.0.0-b083d9a1ca-39e39b7365.zip/node_modules/@strapi/admin/webpack.alias.js
> - .yarn/cache/@strapi-admin-npm-4.0.0-b083d9a1ca-39e39b7365.zip/node_modules/@strapi/admin/webpack.config.js
> - .yarn/cache/@strapi-admin-npm-4.0.0-b083d9a1ca-39e39b7365.zip/node_modules/@strapi/admin/index.js
> - .yarn/unplugged/@strapi-strapi-npm-4.0.0-c988dbe88c/node_modules/@strapi/strapi/lib/commands/build.js
> - .yarn/unplugged/@strapi-strapi-npm-4.0.0-c988dbe88c/node_modules/@strapi/strapi/bin/strapi.js
>     at Function.external_module_.Module._resolveFilename (.pnp.cjs:27159:55)
>     at Function.resolve (node:internal/modules/cjs/helpers:98:19)
>     at .yarn/cache/@strapi-admin-npm-4.0.0-b083d9a1ca-39e39b7365.zip/node_modules/@strapi/admin/webpack.alias.js:46:31
>     at Array.reduce (<anonymous>)
>     at Object.<anonymous> (.yarn/cache/@strapi-admin-npm-4.0.0-b083d9a1ca-39e39b7365.zip/node_modules/@strapi/admin/webpack.alias.js:44:24)
>     at Module._compile (node:internal/modules/cjs/loader:1092:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
>     at Module.load (node:internal/modules/cjs/loader:972:32)
>     at Function.external_module_.Module._load (.pnp.cjs:27008:14)
>     at Module.require (node:internal/modules/cjs/loader:996:19)
> ```

Alright, delete your `package-lock.json`, `yarn.lock`, 'build`, '.cache` and `node_modules` and reinstall modules/rebuild the admin.

Your bouncing around various node and npm versions without cleaning up before running stuff it looks like. We don't support odd node versions either. Current choices for node/npm are:

- Node 12 / NPM 6
- Node 14 / NPM 6
- Node 16 / NPM 8 + Yarn

Node 11, 13, 15, 17 are all unsupported. Node 16 with NPM only has a bug that we are already aware of and will work on in January.

**Comment by nfrasser** [comment] 2021-12-28 19:26
@derrickmehaffy alright did a a full clean up with proper versions (I definitely forgot to bump strapi packages back to 4.0.2 when switching to yarn, my bad). Upgraded to Node v16.13.1 and NPM v8.1.2. yarn version is reported as 3.1.1. Still getting the same  `@strapi/admin tried to access object-assign, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.` error

Full output: [strapi-install-build-output.txt](https://github.com/strapi/strapi/files/7786098/strapi-install-build-output.txt)

These were the only dependencies in `package.json` when this ran:

    "@strapi/plugin-i18n": "4.0.2",
    "@strapi/plugin-users-permissions": "4.0.2",
    "@strapi/provider-upload-aws-s3": "4.0.2",
    "@strapi/strapi": "4.0.2",
    "pg-connection-string": "^2.4.0",
    "sqlite3": "5.0.2"

**Comment by derrickmehaffy** [comment] 2021-12-28 19:36
> @derrickmehaffy alright did a a full clean up with proper versions (I definitely forgot to bump strapi packages back to 4.0.2 when switching to yarn, my bad). Upgraded to Node v16.13.1 and NPM v8.1.2. yarn version is reported as 3.1.1. Still getting the same  `@strapi/admin tried to access object-assign, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.` error
> 
> Full output: [strapi-install-build-output.txt](https://github.com/strapi/strapi/files/7786098/strapi-install-build-output.txt)
> 
> These were the only dependencies in `package.json` when this ran:
> 
>     "@strapi/plugin-i18n": "4.0.2",
>     "@strapi/plugin-users-permissions": "4.0.2",
>     "@strapi/provider-upload-aws-s3": "4.0.2",
>     "@strapi/strapi": "4.0.2",
>     "pg-connection-string": "^2.4.0",
>     "sqlite3": "5.0.2"
> 

I don't know if yarn berry will work, I haven't tested and sorry I should have said yarn 1.x

**Comment by nfrasser** [comment] 2021-12-28 20:07
@derrickmehaffy using yarn v1 seems to have done the trick, thanks for your help

**Comment by derrickmehaffy** [comment] 2021-12-28 20:45
I'm marking this as a duplicate of https://github.com/strapi/strapi/issues/11729 as it's clearly a node/npm/yarn combination issue.

**Closed by derrickmehaffy** 2021-12-28 20:45 UTC
Labels: status: duplicate

**Comment by lkjimy** [comment] 2021-12-31 14:40
There's no support for npm 7?
I got the same error using node: 'v12.22.1' and npm: '7.24.2'.
`TypeError: The 'compilation' argument must be an instance of Compilation`

**Comment by surya-ven** [comment] 2022-01-08 09:57
For anyone else experiencing this issue and your issue is not a duplicate webpack dependency, simply switching to yarn instead of npm worked for me.

**Comment by GaryFrazier** [comment] 2022-09-12 17:02
Another thing for me, make sure your path in the terminal matches the casing of your folders exactly. My folder was in "Dev" but my terminal was in "dev", same folder, bash had the wrong casing when I cd'd into it. Could be a cause.
