### ISSUE TITLE
Adding Range header to video/audio file 

### ISSUE THREAD

**Issue by creativeesprit** [strapi/strapi#2246] opened 2018-11-01 19:37 UTC
**Informations**
- **Node.js version**: 10.6.0
- **npm version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: mongo
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**

Video/Audio files not working in Safari 9+

**Steps to reproduce the problem**

This could fall under a feature request, though I assume users would expect video/audio files to work in Safari out-the-box.

On a clean installation upload an MP4 file from the Strapi dashboard.
Click record to copy file location to clipboard and then paste in Safari.
Video does not stream.

**What is the expected behavior?**

It should stream the video as it does in Chrome and IE

**Tested**

Tested opening video in Safari from desktop to ensure it's not an encoding/corrupt file issue.

**Suggested solutions**

After some research it seems the solution would be to add `Range` to request headers for these file types as this is now seems mandatory in Safari.

Thanks

**Comment by lauriejim** [comment] 2018-11-05 14:46
Hello @creativeesprit , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by lauriejim** [comment] 2018-12-05 17:54
I just tried with Safari 12 (last version) so please update your Safari version

**Comment by ruizanthony** [comment] 2019-04-22 11:30
Video streaming doesn't work on iOS. It wasn't working with iOS 12.1. Tried upgrading to the latest version (iOS 12.2). It doesn't work either. 

According to Apple, the server MUST support byte-range / content-range / partial-range for videos to be able to play on iOS
https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/CreatingVideoforSafarioniPhone/CreatingVideoforSafarioniPhone.html#//apple_ref/doc/uid/TP40006514-SW6

Please add support for byte-range. I would like to develop an iphone app for manufacturing industries and being able to play videos is mandatory.

**Comment by techgeniuswang** [comment] 2019-08-05 06:37
I met this problem too.

**Steps to reproduce the behavior**
1. Go to http://localhost:1337/admin/plugins/upload
2. Upload a mp4 file
3. View the uploaded mp4 file.

**Expected behavior**
Can play the mp4 file normally by **safari**/chrome/firefox




**System**
- Node.js version: v10.15.3
- NPM version: 6.4.1
- Strapi version: 3.0.0-alpha.23
- Database: MongoDB 4.0.2
- Operating system: macOS 10.14.5 

@ruizanthony May I know if you resolved this problem?

**Comment by ruizanthony** [comment] 2019-08-05 07:24
@techgeniuswang : I didn't resolve the problem and decided to walk away from strapi (at least for now). Being unable to play videos was a deal breaker for me.

**Comment by techgeniuswang** [comment] 2019-08-06 01:31
@ruizanthony : got it, thanks for your reply.

**Comment by techgeniuswang** [comment] 2019-08-06 16:41
Hi @lauriejim 
 I met this problem too. And to play media by Safari is very important to our business, so may I know if your team has a plan to resolve this issue. Or already has a solution? 
  Look forward to your guide. Really appreciate.

**Comment by birdm4n** [comment] 2019-08-16 08:20
I seem to have found a solution for a related problem: 
Due to the absence of the range header, I was not able to rewind, seek, skip forward on streamed videos hosted by strapi even in chrome. This is due to the missing 206 response. 

by going into /node_modules/strapi/ and adding two node modules for koa there and modifing  /node_modules/lib/Strapi.js a little bit I could get it to work properly. 

just add https://github.com/koajs/koa-range and koa-route and then in Strapi.js modify the following lines: 

`…
…
// Add range/route
const range = require('koa-range');
const route = require('koa-route');
…
…
  async load() {
    await this.enhancer();
    this.app.use(range); // new instead of the following

    /*this.app.use(async (ctx, next) => {
      if (ctx.request.url === '/_health' && ctx.request.method === 'HEAD') {
        ctx.set('strapi', 'You are so French!');
        ctx.status = 204;
      } else {
         await next();
      }
    }); */
…
…`

Just restart strapi and it seems like it's working as it should. Perhaps it's just a workaround for now and a native fix would be better, but could help some people, I guess.  Could someone verify this or does that break something?

**Comment by derrickmehaffy** [comment] 2019-08-16 08:42
Reopening as issue still persists

**Comment by derrickmehaffy** [comment] 2019-08-16 08:42
@birdm4n can you submit a pull Request with your changes?

**Comment by derrickmehaffy** [comment] 2019-08-16 08:44
@alexandrebodin iirc koa-route was swapped out for something else wasn't it?

**Comment by birdm4n** [comment] 2019-08-16 08:47
Sorry. koa-route is completely unnecessary for that fix. That was just part of the koa-range example. I'll try to submit the changes (honestly have never done that 😅)

**Comment by derrickmehaffy** [comment] 2019-08-16 08:50
@birdm4n to do a pull request:

1. Fork the Strapi repo
2. Create a new branch based on the one you want to modify (on your fork)
3. Make your changes
4. Push to your fork branch
5. Create a PR and select the Strapi/branch you want to send the PR to (if you go to the homepage of your repo after you push it should give you the option to create a PR)
6. Fill out the template for the PR and submit

Here is a short guide from Github but a few minutes poking about with some google searches you can probably find more detailed ones.

https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by fl034** [comment] 2020-01-29 20:33
Hey guys any updates on this? Should work out of the box with the local upload plugin IMHO.
Can't stream audio or video at all on Safari.
Sure I will now switch to a proper storage provider, but for small and quick projects, would be cool to have this working fine.

**Comment by lauriejim** [comment] 2020-02-05 10:09
Hello! This issue will be fixed during the Media Lib plugins development.

**Comment by birdm4n** [comment] 2020-02-19 09:45
Is there a roadmap for that? We are planning to use Strapi (multiple instances of it actually) for a big project soon. Would be cool if that issue was solved and we would not have to manipulate the core parts (like above)  just to get correct video streaming.

**Comment by alexandrebodin** [comment] 2020-02-19 09:49
Hi @birdm4n You can find the roadmap here https://portal.productboard.com/strapi/1-public-roadmap/tabs/6-in-progress-design

The Media library is planned to be released before end of Q1 2020

**Comment by birdm4n** [comment] 2020-02-19 09:52
Did not find it in the roadmap as I probably was looking for other keywords. 
Wow, that would be awesome and perfectly fitting our roadmap for the project. Keeping my fingers crossed, that this works out. Thanks!

**Comment by lauriejim** [comment] 2020-06-08 13:29
Just tested, it works fine since we published the Media Lib feature.

**Closed by lauriejim** 2020-06-08 13:29 UTC
Labels: priority: low, status: confirmed, type: bug

**Comment by tiberiumihai** [comment] 2020-10-17 17:15
Can anyone tell me in which version of strapi was this released?
I've created a symlink into the public folder and I'm trying to server some video content with strapi using Range headers and apparently strapi returns the whole file.
I'm running an older version of strapi@3.0.5.
Thanks!

**Comment by derrickmehaffy** [comment] 2020-10-19 15:24
@tiberiumihai the header was never added, the PR was closed as no one created a new PR: https://github.com/strapi/strapi/pull/3791

**Comment by alexandrebodin** [comment] 2020-10-19 15:43
Hi, FYI We added koa-range when we released the media-library actually.

**Comment by tiberiumihai** [comment] 2020-10-19 15:58
Cool. Then, I can safely remove `strapi.app.use(range);` and keep only the handling part in the custom range middleware.

**Comment by alexandrebodin** [comment] 2020-10-20 09:01
make sure to check you are serving your file from the upload route as the middleware is only installed on media lib plugin to avoid bugs with other strapi routes. If you serve custom files from custom routes you will need to install the middleware for them too :)

**Comment by shmdhussain** [comment] 2022-09-05 13:38
Using strapi version 3.6.10

I am facing different issue in safari that is

In the response header "content-range: start-end/total_size_in_bytes", the total size value is incorrect in safari when the video is requested from uploads folder.


After restarting , issue is resolved, correct total size value is coming in content-range header.

Working good in chrome and other browsers. Only issue is in safari.

Anyone facing the issue?.

Issue not happens when there are less number of files in uploads folder, issue happens when there are more files in the uploads folder
