### ISSUE TITLE
Unable to upload videos to a Content type field called media

### ISSUE THREAD

**Issue by Nyuykimac** [strapi/strapi#9824] opened 2021-03-24 09:04 UTC
### Describe the bug

I created a Content type called video with a field media with advance settings set to videos only, each time I try to upload a video I get the error message 'error Error: Input buffer contains unsupported image format'
### Expected behavior
The video should appear in the media library

### Screenshots

![Screenshot from 2021-03-23 13-07-51](https://user-images.githubusercontent.com/37134304/112282595-897bd600-8c87-11eb-81e6-42029cf05a42.png)
![Screenshot from 2021-03-23 13-07-57](https://user-images.githubusercontent.com/37134304/112282608-8c76c680-8c87-11eb-9b99-0ccc0e9ef74c.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version:v14.13.0
- NPM version: 6.14.9
- Strapi version: V3.3.3
- Database:Sqlite
- Operating system: ubuntu 18.04

**Comment by emmayusufu** [comment] 2021-03-28 15:38
you shoud try to update your strapi version to the latest version 3.5.4 and try again

**Comment by derrickmehaffy** [comment] 2021-03-29 21:47
> you shoud try to update your strapi version to the latest version 3.5.4 and try again

As @emmayusufu stated, test on the latest version, also I couldn't reproduce on v3.5.4 marking as closed until the user can provide more detailed reproduction steps.

**Closed by derrickmehaffy** 2021-03-29 21:47 UTC
