### ISSUE TITLE
Strapi stuck when editing model with many relations

### ISSUE THREAD

**Issue by ivadimko** [strapi/strapi#3782] opened 2019-08-14 07:18 UTC
**Describe the bug**
It's quite hard to edit model which has many relations. E.g. we have model `course` with relation `candidates`. For the moment it is more than 3.5k related entries of `candidate`. 
Every time when I try to edit model (on every key press event) my laptop (which is high end MacBook) stuck for few seconds. If I remove `candidate` from displaying on `course` edit page, everything is going as expected. Also, there is ~1.3mb transferred data for each `save` request with enabled `candidate`

**Steps to reproduce the behavior**
1. Create 2 content types. One parent, and one child (in my case it was one-to-many relation)
2. Create many child models (1k +)
3. Make sure child is displayed for parent's edit page
4. Try to edit parent entry
5. See how it stuck

**Expected behavior**
Entry is being edited without stuck.

**Screenshots**
![image](https://user-images.githubusercontent.com/29413892/63001163-a6311480-be7b-11e9-9156-eb5977990c7f.png)
![image](https://user-images.githubusercontent.com/29413892/63001358-2192c600-be7c-11e9-8a9d-37c1e14f2c2b.png)

**System**
- Node.js version: v11
- NPM version: 6.9.0
- Strapi version: Strapi v3.0.0-beta.6
- Database: postgres v10
- Operating system: MacOS Mojave v 10.14.5

**Additional context**
Also, it would be nice to see human-readable fields instead of IDs of related entries. If it is possible to configure which field to display, I just want to know how to do it.

**Comment by derrickmehaffy** [comment] 2019-08-14 07:28
> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Comment by ivadimko** [comment] 2019-08-14 07:36
@derrickmehaffy updated explanation

**Comment by derrickmehaffy** [comment] 2019-08-14 07:37
@ivadimko make sure you update to the latest version `Strapi v3.0.0-beta.15`

**Comment by derrickmehaffy** [comment] 2019-08-14 07:39
Seems related to this: https://github.com/strapi/strapi/issues/2415

**Comment by lauriejim** [comment] 2019-08-14 13:20
Hello! Yes it's a duplicate of this issue.
Thank you for this report. 
@soupette talk to me this morning about this issue.

**Closed by lauriejim** 2019-08-14 13:20 UTC
Labels: status: duplicate
