### ISSUE TITLE
Can't select text using the keyboard in some fields within a dynamiczone nested component

### ISSUE THREAD

**Issue by AdrianFahrbach** [strapi/strapi#14323] opened 2022-09-06 09:59 UTC
### Required System information

- Node.js version: v16.14.0
- NPM version: v8.7.0
- Strapi version: v4.3.2
- Database: Postgres
- Operating system: MacOS 12.2

### Describe the bug

I can't select text using shift and the arrow keys when I'm editing a `string` or `text` field within a dynamiczone nested component.
It works fine within a `richtext` field and outside of the component.

### Steps to reproduce the behavior

1. Setup a page with the schema of my code snippet below.
2. Add an `FAQ` block and FAQ entries (`faqEntries`) within it and fill it with placeholder content.
3. Open an entry in `faqEntries`
4. Click inside the `text` field (should be filled with placeholder content) and try to select text using shift and the arrow keys of your keyboard. It should be working.
5. Try to reproduce step 4 with the `groupId` field. It should not be working.

### Expected behavior

I should be able to select text with the keyboard.

### Screenshots
I'm not able to select text with the keyboard in fields with a red border.
Fields with a green border are working fine.

![Bildschirmfoto 2022-09-06 um 11 42 32](https://user-images.githubusercontent.com/45072099/188605410-07dec2ba-e1ce-47e0-a2ce-5a6ac42b0d39.png)

![Bildschirmfoto 2022-09-06 um 11 44 18](https://user-images.githubusercontent.com/45072099/188605406-aa5cdbaa-3ad4-41d8-96fd-3e56e3df5986.png)

### Code snippets

My setup is as followed:

I have a page that has a dynamic zone with an faq component in it:
```json
{
  "content": {
    "type": "dynamiczone",
    "components": ["content.faq"],
    "pluginOptions": {
      "i18n": {
        "localized": true
      }
    }
  }
}
```

The FAQ component basically looks like this and has its entries as child components:
```json
{
    "collectionName": "components_content_faq",
    "info": {
      "displayName": "FAQ",
      "icon": "align-left"
    },
    "options": {},
    "attributes": {
      "pageNavigationLabel": {
        "type": "string"
      },
      "faqEntries": {
        "displayName": "FAQ Entries",
        "type": "component",
        "repeatable": true,
        "component": "content.faq-entry"
      }
    }
  }
  ```

The FAQ entry itself looks like this and won't let me select text with the keyboard on `headline` and `groupId`:
```json
{
    "collectionName": "components_content_faq_entries",
    "info": {
      "displayName": "FAQ Entry",
      "icon": "align-left",
      "description": ""
    },
    "options": {},
    "attributes": {
      "groupId": {
        "type": "string"
      },
      "headline": {
        "type": "string",
        "required": true,
        "pluginOptions": {
          "search": {
            "searchable": true
          }
        }
      },
      "text": {
        "type": "richtext",
        "required": true,
        "pluginOptions": {
          "search": {
            "searchable": true
          }
        }
      }
    }
  }
  ```

**Comment by joshuaellis** [comment] 2022-09-22 09:50
related to https://github.com/strapi/design-system/issues/642 & https://github.com/strapi/design-system/issues/614

**Comment by joshuaellis** [comment] 2022-09-23 09:45
After investigation, this issue is a duplicate of #12432 so I'm going to close this, for updates follow that issue.

**Closed by joshuaellis** 2022-09-23 09:45 UTC
Labels: issue: bug, severity: medium, source: core:content-manager, status: will not fix
