### ISSUE TITLE
Custom field input components don't receive the expected props

### ISSUE THREAD

**Issue by remidej** [strapi/strapi#20915] opened 2024-07-31 13:25 UTC
Comes from a report and conversation with @shamglam on #20866.

In v5, custom field input components currently are not given the `value` and `onChange`.

Those could be retrieved using the useField hook. But in my opinion there's no need to introduce a breaking change here. We could call useField from the parent component, and pass value and onChange to the custom field's props.

This way we ensure backwards compatibility, and avoid breaking the existing custom field ecosystem in v5.

**Comment by AndreiMrakov** [comment] 2024-08-16 22:46
@remidej any updates or possible "hotfix" u did find? Coz i'm trying to update CKEditor and face with the same issue: input type "richtext" and almost half props is missing including `value` and `onChange`. But `useField` also doen't work coz returns empty object

**Comment by brianbento** [comment] 2024-09-05 13:19
@remidej Any idea when this will be fixed? Working on building my own custom fields and plugins and this is a major blocker.

Is there a workaround for now?

Thank you

**Comment by brianbento** [comment] 2024-09-05 18:20
@remidej Not a bug. This has been removed and replaced.

View code here as in #20866 
https://github.com/strapi/strapi/blob/baabf9edef4d0079bdbe0f891dcba743afc5a571/packages/plugins/color-picker/admin/src/components/ColorPickerInput.tsx#L79

This should be added to the breaking changes documentation.

**Comment by AndreiMrakov** [comment] 2024-09-11 23:32
> @remidej Not a bug. This has been removed and replaced.
> 
> View code here as in #20866
> 
> https://github.com/strapi/strapi/blob/baabf9edef4d0079bdbe0f891dcba743afc5a571/packages/plugins/color-picker/admin/src/components/ColorPickerInput.tsx#L79
> 
> This should be added to the breaking changes documentation.

@brianbento 
It returns empty object in this case, that’s the core problem

**Closed** 2024-09-13 09:16 UTC
Labels: issue: bug, severity: medium, source: core:admin
