### ISSUE TITLE
Can't add blocks to Dynamic zone

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#18755] opened 2023-11-11 16:31 UTC
Project information                                                          

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Sat Nov 11 2023 13:24:26 GMT-0300 (GMT-03:00)    │
│ Launched in        │ 507 ms                                           │
│ Environment        │ development                                      │
│ Process PID        │ 64746                                            │
│ Version            │ 4.15.4 (node v18.18.1)                           │
│ Edition            │ Community                                        │
│ Database           │ sqlite                                           │
└────────────────────┴──────────────────────────────────────────────────┘

Video is attached:

https://github.com/strapi/strapi/assets/1038168/7bf7a3cd-0206-444f-910a-8b7f0b0855e6

**Issue Description:**

After following the specified steps to create a component, navigate to the collection type 'Posts,' and attempt to add the new component to blocks in the Dynamic Zone, clicking on "Add a component" results in a blank page.

**Steps to Reproduce:**

Create a new component.
Navigate to the 'Posts' collection type.
Attempt to add the newly created component to blocks in the Dynamic Zone.
Click on "Add a component."
Observe the appearance of a blank page.

**Expected Result:**

The component should be successfully added to blocks in the Dynamic Zone without causing a blank page.

**Actual Result:**

Clicking on "Add a component" leads to a blank page.

**Comment by dgrebb** [comment] 2023-11-12 00:18
@teinett FYA — #18665

**Comment by teinett** [comment] 2023-11-12 03:22
Duplicate

**Comment by derrickmehaffy** [comment] 2023-11-12 05:41
Closing as duplicate of https://github.com/strapi/strapi/issues/18665

**Closed** 2023-11-12 05:41 UTC
Labels: status: duplicate
