### ISSUE TITLE
Model lifecycle issues

### ISSUE THREAD

**Issue by zedissime** [strapi/strapi#3876] opened 2019-08-31 06:21 UTC
Hello there,

I'm trying to write some enhancement for a model. I have an Address model which have some fields : 
```
street_name
street_number
street_box
city
country
zip_code
```
I'm using the beforeSave hook to geocode the address and get the lat and lng.
Here is my beforeSave hook : 
```
beforeSave: async (model) => {
    const { latitude, longitude } = await strapi.services.address.geocode({
      street_name:   model.attributes.street_name,
      street_number: model.attributes.street_number,
      street_box:    model.attributes.street_box,
      city:          model.attributes.city,
      country:       model.attributes.country,
      zip_code:      model.attributes.zip_code,
    });
    model.set('latitude', latitude);
    model.set('longitude', longitude);
  },
```

I have noticed some inconsistencies : 

1. It is well triggered when i'm updating or creating an address from the admin panel **but** the latitude and longitude are added to the model but it is not saved.
![image](https://user-images.githubusercontent.com/1235591/64059938-01763d00-cbc6-11e9-8f82-7ea28b6df4a1.png)

2. It is also triggered when i'm updating or creating an address from an api call **but** the format of received data is not the same than from the admin panel 
![image](https://user-images.githubusercontent.com/1235591/64060013-1e5f4000-cbc7-11e9-8610-e8ddc1bc5d85.png)

I am also a bit confused, the [Concepts > Models](https://strapi.io/documentation/3.0.0-beta.x/concepts/concepts.html#models) doc doesn't expose the same structure than the [Lifecycle Callbacks](https://strapi.io/documentation/3.0.0-alpha.x/guides/models.html#lifecycle-callbacks) docs.
Concept > Models : 
```
/ Before saving a value.
  // Fired before an `insert` or `update` query.
  beforeSave: next => {
    // Use `this` to get your current object
    next();
  },
```

Lifecycle Callbacks :
```
module.exports = {

  /**
   * Triggered before user creation.
   */
  beforeCreate: async (model, attrs, options) => {
    // Hash password.
    const passwordHashed = await strapi.api.user.services.user.hashPassword(model.attributes.password);

    // Set the password.
    model.set('password', passwordHashed);
  }
}
```

I'm proabably doing something wrong but I can't find a correct solution in the doc.

**Comment by derrickmehaffy** [comment] 2019-09-03 09:03
Duplicate of:
https://github.com/strapi/strapi/issues/3863
https://github.com/strapi/strapi/issues/3473
https://github.com/strapi/strapi/issues/1443

> This is a templated message

Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> A copy of the bug report template can be found below:

```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

**Closed by derrickmehaffy** 2019-09-03 09:03 UTC
