### ISSUE TITLE
Server reload not work

### ISSUE THREAD

**Issue by amorev** [strapi/strapi#6126] opened 2020-05-08 13:30 UTC
**Describe the bug**
Server auto reload in developer mode not work on 3.0.0-beta.20.3

**Steps to reproduce the behavior**

1. I created strapi app by command
```bash
npx create-strapi-app my-project --quickstart
```
2. Created admin user
3. Add file api/test/controllers/test.js or change something on any code

**Expected behavior**
Server is autoreloading

**Screenshots**
![image](https://user-images.githubusercontent.com/8593411/81410261-1ccc1b80-9149-11ea-8e9b-75ddb2a419a7.png)
Silence:)

**Code snippets**
No snippets. Just created app

**System**

- Node.js version: v12.14.1
- NPM version: 6.13.7
- Strapi version: 3.0.0-beta.20.3
- Database: sqlite
- Operating system: Windows 10, MacOS

**Additional context**
On version 3.0.0-beta.19.5 everything works fine on all operiation systems.

P.S. Thank you for such an awesome strapi!

**Comment by derrickmehaffy** [comment] 2020-05-15 18:37
I cannot reproduce this on beta.20.3

**Comment by amorev** [comment] 2020-05-16 15:11
Strange. I'll try to record video to show you the problem

**Comment by MaheshCasiraghi** [comment] 2020-05-19 09:09
Same here, since beta.20, reload on save using `strapi develop` does not refresh files in memory, and server needs to be restarted.

**Comment by lauriejim** [comment] 2020-05-23 09:41
Maybe due to windows?
Can't reproduce on MacOS.

**Comment by derrickmehaffy** [comment] 2020-05-23 09:55
@lauriejim I believe this to be a user environment issue.

@amorev we need additional information to reproduce this, or at the very least please test on another operating system/computer to see if you can reproduce it yourself.

**Comment by amorev** [comment] 2020-05-23 17:21
Reproducing bug on windows 10. I still have this problem(

**Comment by amorev** [comment] 2020-05-24 07:05
Problem is reproduced on Mac OS. I think it isn't connected with environment.

For example I can create github repo with code, which has this problem and you'll try to check it.

**Comment by lauriejim** [comment] 2020-05-28 12:33
Hello here is what I did - [video](https://www.loom.com/share/d4099a968736424681f2788053889a04)

Did I miss something?

**Comment by amorev** [comment] 2020-05-28 13:34
> Hello here is what I did - [video](https://www.loom.com/share/d4099a968736424681f2788053889a04)
> 
> Did I miss something?

Firstly, thank you for video and being so interesting in my issue. It's awesome!

And yes - you did what I did and it works fine at you place. I'll try do it and share video soon.

Thanks!

**Comment by lauriejim** [comment] 2020-06-12 10:49
I'm closing this issue, will reopen it if needed.

**Closed by lauriejim** 2020-06-12 10:49 UTC
Labels: status: can't reproduce

**Comment by geekdada** [comment] 2020-08-08 05:48
@lauriejim I was experiencing the same issue, until I found out the ignored rules:

```
[
      /(^|[/\\])\../, // dot files
      /tmp/,
      '**/admin',
      '**/admin/**',
      'extensions/**/admin',
      'extensions/**/admin/**',
      '**/documentation',
      '**/documentation/**',
      '**/node_modules',
      '**/node_modules/**',
      '**/plugins.json',
      '**/index.html',
      '**/public',
      '**/public/**',
      '**/*.db*',
      '**/exports/**',
      ...watchIgnoreFiles,
]
```

This is simply because the project folder named `admin`. I didn't find any workaround to this issue expect changing the project/folder name.

Maybe you should put this tip in the documentations.

**Comment by amorev** [comment] 2020-08-08 08:33
omg. that's was the problem. Renaming folder solved my issue
