### ISSUE TITLE
Regular development crash because of knex/postgres/tarn ?

### ISSUE THREAD

**Issue by MoOx** [strapi/strapi#13190] opened 2022-04-26 20:56 UTC
### Required System information

- Node.js version: v16.13.2
- NPM version: 8.7.0
- Strapi version:
  ```
    "dependencies": {
        "@strapi/plugin-graphql": "^4.1.8",
        "@strapi/plugin-i18n": "4.1.8",
        "@strapi/plugin-users-permissions": "4.1.8",
        "@strapi/provider-email-nodemailer": "^4.1.8",
        "@strapi/strapi": "4.1.8",
        "pg": "^8.7.3"
      },
  ```
- Database:  PostgreSQL 14.2 (inside Docker container Debian 14.2-1.pgdg110+1)
- Operating system: macOS 12.3.1 (21E258)

### Describe the bug

Regularly, I got failure from the API (I am developing an app with Next.js + Strapi/GraphQL)

Then a crash randomly append::

```
[2022-04-26 22:40:56.031] info: File changed: {PROJECT}/db-data/global/pg_control
[2022-04-26 22:40:56.032] info: File changed: {PROJECT}/db-data/base/16384/16402
[2022-04-26 22:40:56.032] info: The server is restarting

[2022-04-26 22:40:56.032] info: File changed: {PROJECT}/db-data/base/16384/2619
[2022-04-26 22:40:56.033] info: File changed: {PROJECT}/db-data/base/16384/1259
[2022-04-26 22:40:56.033] info: File changed: {PROJECT}/db-data/base/16384/16406
[2022-04-26 22:40:56.033] info: File changed: {PROJECT}/db-data/base/16384/16407
[2022-04-26 22:40:56.090] debug: ⛔️ Server wasn't able to start properly.
[2022-04-26 22:40:56.090] error: aborted
Error: aborted
    at PendingOperation.abort ({PROJECT}/node_modules/tarn/dist/PendingOperation.js:25:21)
    at {PROJECT}/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at {PROJECT}/node_modules/tarn/dist/Pool.js:207:53
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client_PG.destroy ({PROJECT}/node_modules/@strapi/database/node_modules/knex/lib/client.js:333:9)
    at async Database.destroy ({PROJECT}/node_modules/@strapi/database/lib/index.js:67:5)
    at async Strapi.destroy ({PROJECT}/node_modules/@strapi/strapi/lib/Strapi.js:182:7)
    at async process.<anonymous> ({PROJECT}/node_modules/@strapi/strapi/lib/commands/develop.js:86:13)
```

### Steps to reproduce the behavior

1. Anytime there is a db operation, a file is touched, & strapi server is restarting.
2. Sometimes, it crashes when restarting.

### Expected behavior

I should not expect development crash. Or at least the error message should be more clear about what I am doing wrong.

**Comment by Kzai** [comment] 2022-04-29 21:15
+1 
Node v14.7.1, 
Strapi 4.1.8, 
PostgreSQL 12.0 (Debian 12.0-2.pgdg100+1)

**Comment by MoOx** [comment] 2022-04-29 21:22
Some workarounds:
- don't use `develop` if you don't need it (use start, no watcher on db files, no crash)
- don't put db files on your actual fs and keep them in docker instance if possible

**Comment by derrickmehaffy** [comment] 2022-05-05 21:11
We do not recommend running Strapi in development mode while in production. Development mode is logically designed for local development (hence auto-restarting on file changes, ect). Closing this as we won't fix an issue that results from using Strapi in a way we do not recommend.

**Closed by derrickmehaffy** 2022-05-05 21:11 UTC

**Comment by MoOx** [comment] 2022-05-06 09:05
My setup was for development. My project is not in production and I do not intent to use develop command for production.
Is there a way to ignore some files to restart the server ?

**Comment by derrickmehaffy** [comment] 2022-05-24 00:09
Your looking for the `watchIgnoreFiles` from the admin.js config: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/required/admin-panel.html#available-options

**Comment by korokd** [comment] 2022-08-11 19:23
+1

@derrickmehaffy Is it expected behavior that the development mode crashes when doing what it's supposed to (observing db changes)?

It's been a really poor experience.

**Comment by derrickmehaffy** [comment] 2022-08-12 04:46
> +1
> 
> @derrickmehaffy Is it expected behavior that the development mode crashes when doing something it's supposed to (observing db changes)? Some of these files update even when I'm not interacting with Strapi, and then I want to reload a page and it's crashed. Could it at least restart by itself? Because that's what I do - run `yarn develop` again.
> 
> It's been a really poor experience.

Not quite sure what you are referring to, can you show a reproduction?

**Comment by korokd** [comment] 2022-08-16 15:14
> > +1
> > @derrickmehaffy Is it expected behavior that the development mode crashes when doing something it's supposed to (observing db changes)? Some of these files update even when I'm not interacting with Strapi, and then I want to reload a page and it's crashed. Could it at least restart by itself? Because that's what I do - run `yarn develop` again.
> > It's been a really poor experience.
> 
> Not quite sure what you are referring to, can you show a reproduction?

I may not be able to express myself properly here, so sorry in advance.

Most of the time when I interact with the Strapi Admin interface and actually update some data/schema, it updates the file, then restarts the server and it keeps working fine.

However, often there are some files that are updated without me interacting with Strapi at all, and when that happens the server crashes nearly 100% of the times. Thinking more about it, it might be something with how I've set up things, but maybe you can shine a light on me.

Hope this SS helps you visualize it:
<img width="1803" alt="Screen Shot 2022-08-16 at 12 10 39" src="https://user-images.githubusercontent.com/18357691/184915669-5b233585-a256-4354-ad48-29f2df067b63.png">

**Comment by MoOx** [comment] 2022-08-16 15:21
Did you actually [read this](https://github.com/strapi/strapi/issues/13190#issuecomment-1135259739) and used the option?

**Comment by derrickmehaffy** [comment] 2022-08-16 15:52
> > > +1
> > > @derrickmehaffy Is it expected behavior that the development mode crashes when doing something it's supposed to (observing db changes)? Some of these files update even when I'm not interacting with Strapi, and then I want to reload a page and it's crashed. Could it at least restart by itself? Because that's what I do - run `yarn develop` again.
> > > It's been a really poor experience.
> > 
> > 
> > Not quite sure what you are referring to, can you show a reproduction?
> 
> I may not be able to express myself properly here, so sorry in advance.
> 
> Most of the time when I interact with the Strapi Admin interface and actually update some data/schema, it updates the file, then restarts the server and it keeps working fine.
> 
> However, often there are some files that are updated without me interacting with Strapi at all, and when that happens the server crashes nearly 100% of the times. Thinking more about it, it might be something with how I've set up things, but maybe you can shine a light on me.
> 
> The error I get when that happens is
> 
> ```
> [2022-08-16 11:59:03.973] debug: ⛔️ Server wasn't able to start properly.
> [2022-08-16 11:59:03.973] error: aborted
> Error: aborted
>     at PendingOperation.abort (/Users/dkorok/Ambush/CG/website-cms/node_modules/tarn/dist/PendingOperation.js:25:21)
>     at /Users/dkorok/Ambush/CG/website-cms/node_modules/tarn/dist/Pool.js:208:25
>     at Array.map (<anonymous>)
>     at /Users/dkorok/Ambush/CG/website-cms/node_modules/tarn/dist/Pool.js:207:53
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async Client_PG.destroy (/Users/dkorok/Ambush/CG/website-cms/node_modules/knex/lib/client.js:333:9)
>     at async Database.destroy (/Users/dkorok/Ambush/CG/website-cms/node_modules/@strapi/database/lib/index.js:67:5)
>     at async Strapi.destroy (/Users/dkorok/Ambush/CG/website-cms/node_modules/@strapi/strapi/lib/Strapi.js:188:7)
>     at async process.<anonymous> (/Users/dkorok/Ambush/CG/website-cms/node_modules/@strapi/strapi/lib/commands/develop.js:86:13)
> error Command failed with exit code 1.
> ```
> 
> And the paths that were changed right before the crash look like `/data/base/16384/2841` (there were 5, and it didn't even get to log the `info: The server is restarting` message)

Strapi has no method for restarting during normal usage unless you are using the content-type builder or something is creating files in watched directories. How do you start Strapi on your deployed host as you should be using `start` not `develop`

**Comment by derrickmehaffy** [comment] 2022-08-16 15:54
That specific error message has nothing to do with the Strapi server itself but is most likely because the database aborted your connection, if you are using Docker or any container hosting system you should set your tarn pool minimum to zero as dockers (albeit terrible) networking code will actively kill idle connections which is what tarn pooling is, it keeps a certain amount of idle connections open and reuses them to cut down on the TCP handshake latency.
