### ISSUE TITLE
[plugin][content-type-builder] ReferenceError: Cannot access 'originalIcon' before initialization.

### ISSUE THREAD

**Issue by mimshins** [strapi/strapi#7539] opened 2020-08-20 16:40 UTC
**Describe the bug**

`ComponentIconPicker` throws `ReferenceError: Cannot access 'originalIcon' before initialization`.

**Steps to reproduce the behavior**

1. Go to `http://localhost:1337/admin`
2. Click on 'Content-Types Builder' in the left menu.
3. In 'Components > ComponentCategory' section click on a ComponentCategory.
4. Click on the edit icon next to the Title on top of the body.

**System**

- Node.js version: 14.2.0
- NPM version: 6.14.4
- Strapi version: 3.1.4
- Database: MongoDB
- Operating system: macOS High Sierra - v10.13.6

**Additional context**

The source of the error is in the `ComponentIconPicker` codebase.
you are referencing the `originalIcon` at Line 23: `return !allComponentsIconAlreadyTaken.filter(icon => icon !== originalIcon).includes(ico);` while you have declared it at Line 27!

**Comment by derrickmehaffy** [comment] 2020-08-20 16:49
Can you please update your issue with the **System** block of the bug report template:

```
**System**

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:
```

**Comment by derrickmehaffy** [comment] 2020-08-24 13:50
Hello current Strapi does not support Node v14 as it doesn't go LTS until October, can you please test with the currently supported Node version v12.

I have tested on v12 with Strapi v3.1.4 and am unable to reproduce the error.

My Steps of reproduction where the following:
- Create a new Strapi app on Node v12, Strapi v3.1.4
- Create a new content type `article` with one text field
- Create a new component into the `article` model with the name `test.comp` with a single integer field
- Set the initial icon on the component
- Save and navigate back to edit the icon
- Icon was changed without error

Test Project with the following admin login `test@test.com // Test1234`: 
[test7539.zip](https://github.com/strapi/strapi/files/5118228/test7539.zip)

**Comment by derrickmehaffy** [comment] 2020-10-15 14:31
Closing as no new information provided.

**Closed by derrickmehaffy** 2020-10-15 14:31 UTC
Labels: type: help wanted
