### ISSUE TITLE
Auth providers not working: Facebook and GitHub login

### ISSUE THREAD

**Issue by ScottAgirs** [strapi/strapi#6653] opened 2020-06-12 19:08 UTC
**Describe the bug**
Auth providers are broken, currently tested with:
1. Facebook
 - Facebook gives the `Can't Load URL: ...`
https://strapi.slack.com/archives/C0BLB2VJ7/p1591904900000000
2. Github
- Github returns in the backend console
```
/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch
```

To ensure this is not my project-specific, I set up a completely fresh project I followed Jim's recipe
https://www.youtube.com/watch?v=s_vQqQ4tpHs

**Steps to reproduce the behavior**

1. Install as per the recipe instructions
2. Fill in the auth provider details (let me know if in need of my Facebook details, though, it's done correctly and was working before)
<img width="568" alt="Screen Shot 2020-06-12 at 3 04 43 PM" src="https://user-images.githubusercontent.com/11737572/84537594-0ec86800-acbe-11ea-9316-a8e9d91327bb.png">
3. Try to authorize with the one of the two to reproduce the error.

**System**

- Node.js version: latest
- NPM version: latest
- Strapi version: tested on  3.0.0 & 3.0.1
- Database: Postgres

**Additional context**
Facebook auth has been working for me in the past and without any particular changes to user-permissions or the facebook login app it just stopped working.

**Comment by lauriejim** [comment] 2020-06-16 14:05
Duplicate of this issue - https://github.com/strapi/strapi/issues/6570=
Thank you for reporting it.

**Closed by lauriejim** 2020-06-16 14:05 UTC

**Comment by jonathanmach** [comment] 2020-06-25 16:14
I'm facing the same issue
