### ISSUE TITLE
Support dynamic zone inside components and able to enter data in content-manager

### ISSUE THREAD

**Issue by iapain** [strapi/strapi#6283] opened 2020-05-19 15:56 UTC
- [ ] **I have created my request on the Product Board before I submitted this issue**
- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**

**Support dynamic zone inside components and ability to enter data in strapi content-manager**

Currently it is not possible to create dynamic zone(DZ) inside a component in content type builder plugin. However, it's possible to create DZ inside a component in a component file. As mentioned in [5798](https://github.com/strapi/strapi/issues/5798). If you create content for a content type using such component then it says **This dynamiczone is not available**.

In strapi admin it should be possible to add data for such content type where a component with dynamic zone is being used.

**Comment by lauriejim** [comment] 2020-05-25 10:03
Thank you for this feature request.
We will not work on this for next months.
This is a huge UI challenge and we are focus on other features.
Thank you for your understanding.

**Comment by Riya3006** [comment] 2020-07-23 16:58
Is there any update on this? Can we add the Dynamic Zone inside the Component? In any way. Please let me know.

**Comment by MrTheFirst** [comment] 2020-09-04 16:25
Any news on this issue?

**Comment by derrickmehaffy** [comment] 2020-09-04 17:24
We have not started work on this currently, when work starts you will see a linked pull request.

Currently other features and bug reports have taken a higher priority, and we provide no promises that requested features will be added until they are moved to our product board under `planned`.

You can find a link to this here: https://portal.productboard.com/strapi/1-roadmap/tabs/3-planned

For now I will lock this thread and should we move the request to product board or if we need additional information in the future we will unlock it. Thank you for making the feature request and I hope you have a wonderful day.

**Comment by derrickmehaffy** [comment] 2022-02-16 23:30
going to close this one as I just realized it's a duplicate of https://github.com/strapi/strapi/issues/5798

**Closed by derrickmehaffy** 2022-02-16 23:30 UTC
Labels: issue-type: feature request, severity: low
