### ISSUE TITLE
Reordering repeatable component can reorder parent components (also repeatable)

### ISSUE THREAD

**Issue by thevisualfox** [strapi/strapi#15914] opened 2023-02-24 16:20 UTC
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.6.2
- Database: mysql
- Operating system: CentOS / Local MacOS
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I have a repeatable component inside a repeatable component. When I reorder the child components the parent components get reordered as well. This is not happening on Strapi 4.5.6, but was introduced in Strapi 4.6.0

I sometimes get a blank screen with an error in the console outlined in the video posted below.

### Steps to reproduce the behavior

See video I posted below

### Expected behavior

If a child component gets reordered, the parent component order should stay the same

### Screenshots

See video I posted below

### Code snippets

N.A.

### Additional context

https://user-images.githubusercontent.com/43511726/221231075-99cfdbdf-d457-477d-a27b-5d6373225598.mov

**Comment by joshuaellis** [comment] 2023-03-22 09:13
Thanks for the report @thevisualfox, this issue is a duplicate of #15764 and as such i'll be closing the issue and I recommend you subscribe to the other one to see updates :)

**Closed by joshuaellis** 2023-03-22 09:13 UTC
Labels: issue: bug, severity: medium, status: duplicate, source: core:content-manager
