### ISSUE TITLE
“site can't be reached” flicker after saving a content type

### ISSUE THREAD

**Issue by maccomaccomaccomacco** [strapi/strapi#20363] opened 2024-05-23 18:54 UTC
### Required System information

- Node.js version: 20
- NPM version: 10
- Strapi version: 5.0.0-beta.7
- Database: sqlite
- Operating system: mac
- Is your project Javascript or Typescript: Javascript

### Describe the bug
When a content type is save, after the server restart box, there is a brief flicker showing a browser “site can't be reached” is shown before the ctb reloads

### Steps to reproduce the behavior
1. run strapi in develop mode
2. edit a content type
3. delete a field from the content type
4. save

### Expected behavior

I should not see any error messages as part of the reload process

**Comment by alexandrebodin** [comment] 2024-06-06 09:12
I can't reproduce this on beta-9 @Eventyret can you try that again ?

**Comment by Eventyret** [comment] 2024-06-06 09:22
Will do @alexandrebodin

**Comment by alexandrebodin** [comment] 2024-06-06 09:28
It happened to me randomly after a while :(

**Comment by Eventyret** [comment] 2024-06-06 09:29
So it's the "time" it takes for strapi to reload after saving changes if it's quick enough, OR strapi doesn't send a request I think from the admin panel you will not get it I think that's where the issue lies.

**Comment by alexandrebodin** [comment] 2024-06-06 10:50
I'm gonna close this in favor of this duplicate that is already in the DX squad backlog https://github.com/strapi/strapi/issues/20220

**Closed by alexandrebodin** 2024-06-06 10:50 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-type-builder, version: 5
