### ISSUE TITLE
CKEditor as rich text field does not work when the collection has a relation field

### ISSUE THREAD

**Issue by GilianMoa** [strapi/strapi#9011] opened 2020-12-28 15:29 UTC
### Describe the bug

I added CKEditor as default rich text editor in my Strapi app. I created the app from zero following this tutorial https://strapi.io/documentation/developer-docs/latest/guides/registering-a-field-in-admin.html#introduction

The editor is working fine, I added it as a field in a collection and now I can format the text before saving it.

BUT, as soon as I add a relationship field in my collection, the editor stops working. 
When I edit the entry, the editor doesn't load the content. It still saves the content if you enter some text, but don’t load the content anymore when editing.

Any idea on how to fix that?

### Steps to reproduce the behavior

1, Create 2 collections, eg: Post and Category

2, In the Post collection, add the following fields:
Slug as Text, and 
Content as Rich Text

3, In the Category, 
add the field: 
Name as Text

4, At this point if you create a new Post entry by clicking in Add New Post, you will be able to enter some text in the editor and save it.

5, If you edit the entry you just created, you will see that the text inside the editor is there, so you will notice that everything is working fine until now.

6, Now, go to the Content Type Builder, 
open the Collection Type Post 
and add a new Relation field and configure this field with a many-to-many relationship with Categories and save.

7, Now, if you try to edit the Post entry you just created, you will notice that the text you saved in the Content field didn’t load and that is the problem.

### System

- Node.js version: v14.15.3 LTS
- NPM version: 6.14.9
- Strapi version: v3.4.1
- Database: MongoDB
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment] 2020-12-28 15:56
Can you please test the community built CKEditor plugin instead of custom modification:
https://github.com/TechQuery/strapi-plugin-ckeditor
Provided by the community here: https://github.com/strapi/awesome-strapi#community-plugins

**Comment by GilianMoa** [comment] 2020-12-28 20:28
> Can you please test the community built CKEditor plugin instead of custom modification:
> https://github.com/TechQuery/strapi-plugin-ckeditor
> Provided by the community here: https://github.com/strapi/awesome-strapi#community-plugins

Thanks @derrickmehaffy , I'll test.

**Comment by roslovets** [comment] 2020-12-29 15:50
Also try this new plugin:
https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5
I have developed it to work with Strapi v3.4.1.

**Comment by polcham** [comment] 2020-12-30 04:24
> Also try this new plugin:
> https://github.com/Roslovets-Inc/strapi-plugin-ckeditor5
> I have developed it to work with Strapi v3.4.1.

I have tried this with Strapi v3.4.0 but I'm getting minified error, I think it has something to do with the latest version of ckeditor5 - 3.0.0 

Using "@ckeditor/ckeditor5-react": "^2.1.0" works fine

**Comment by derrickmehaffy** [comment] 2021-04-15 18:26
closing as workaround exists and it's not a bug from Strapi

**Closed by derrickmehaffy** 2021-04-15 18:26 UTC
Labels: type: help wanted
