### ISSUE TITLE
Reordering Relations in Dynamic Zone cause blank screen

### ISSUE THREAD

**Issue by kevinlaihk01** [strapi/strapi#14908] opened 2022-11-17 08:32 UTC
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.5.0
- Database: mysql v8
- Operating system: macOs 12.5

### Describe the bug

When a Relation component is used in a Dynamic Zone, reordering the Relation component will lead to a blank screen with following error:

```
TypeError: i is not iterable
```

### Steps to reproduce the behavior

1. create Relation component
2. create a Dynamic Zone which use that Relation component, and also any other component type
3. in Content Manager, reorder the added Relation component among other components in the same Dynamic Zone

### Expected behavior

Reordering a Relation component in Dynamic Zone won't lead to a blank screen

### Screenshots

<img width="404" alt="Screenshot 2022-11-17 at 4 25 30 PM" src="https://user-images.githubusercontent.com/66235468/202394609-63b1c2a2-5b16-41f5-b242-7e8cbe004c9b.png">

### Code snippets

suggest to change this line — https://github.com/strapi/strapi/blob/b169f6fe33253d3b6875131fc56454b786ef119e/packages/core/admin/admin/src/content-manager/components/EditViewDataManagerProvider/reducer.js#L140

from

```
        set(draftState, initialDataPath, uniqBy([...value, ...initialDataRelations], 'id'));
```

```
        set(draftState, initialDataPath, uniqBy([...value, ...(initialDataRelations || [])], 'id'));
```

So it wont spreading an undefined `initialDataRelations` (which its index in dynamic zone is changed) when reordering the Relation component

**Comment by joshuaellis** [comment] 2022-11-18 11:34
I'm unable to reproduce this error. I would suggest you add a more detailed steps to reproduce so we can be more accurate in trying to replicate your conditions.

**Comment by hoggworks** [comment] 2022-11-25 16:18
@joshuaellis This issue happens consistently to me when trying to re-order open components in the Dynamic Zone. Reordering works just fine when they're closed, but if you expand an item and then click either up or down buttons to reorder, you get the "not iterable" error.

**Comment by joshuaellis** [comment] 2022-11-25 16:29
Can you share the schema of the two components & the content type in a minimal way so basically, _just_ the comps and contents that make it break, i'll then try to reproduce on my side using those schemas because I just tried it again and still am not getting an error.

A video would be helpful too & more details i.e. how many components do you put in the dynamic zone and which ones? what data do you put in etc.

**Comment by hoggworks** [comment] 2022-11-25 16:33
> Can you share the schema of the two components & the content type in a minimal way so basically, _just_ the comps and contents that make it break, i'll then try to reproduce on my side using those schemas because I just tried it again and still am not getting an error.
> 
> A video would be helpful too & more details i.e. how many components do you put in the dynamic zone and which ones? what data do you put in etc.

Absolutely! I'm new to strapi, is there a quick way to output my schema for you to see?

**Comment by joshuaellis** [comment] 2022-11-25 16:39
> Absolutely! I'm new to strapi, is there a quick way to output my schema for you to see?

Component schemas are in `src/components/COMPONENT_GROUP/COMPONENT_NAME.json` and schemas are in `src/api/CONTENT_TYPE/content-types/CONTENT_TYPE/schema.json` try to make those schemas as small as possible where they still reproduce the bug though, e.g. if your content type has 20 different text inputs but they're not needed in the schema for the bug to happen, then omit them 😄

**Comment by hoggworks** [comment] 2022-11-25 17:25
I've got a single type "Main page" defined like this:
```
{
  "kind": "singleType",
  "collectionName": "main_pages",
  "info": {
    "singularName": "main-page",
    "pluralName": "main-pages",
    "displayName": "Main page",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "Title": {
      "type": "string"
    },
    "Header": {
      "type": "media",
      "multiple": true,
      "required": false,
      "allowedTypes": [
        "images",
        "files",
        "videos",
        "audios"
      ]
    },
    "Layout": {
      "type": "dynamiczone",
      "components": [
        "widgets.classes",
        "widgets.feature-sections",
        "widgets.wysiwyg-editor"
      ]
    }
  }
}

```

It references three components: Class, Announcements, Wsyiwyg Edtitor:
```{
  "collectionName": "components_widgets_classes",
  "info": {
    "displayName": "Class",
    "icon": "arrow-alt-circle-up",
    "description": ""
  },
  "options": {},
  "attributes": {
    "class": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::class.class"
    }
  }
}
```
```
{
  "collectionName": "components_widgets_feature_sections",
  "info": {
    "displayName": "Announcement",
    "icon": "american-sign-language-interpreting",
    "description": ""
  },
  "options": {},
  "attributes": {
    "announcements": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::announcement.announcement"
    }
  }
}
```

```
{
  "collectionName": "components_widgets_wysiwyg_editors",
  "info": {
    "displayName": "Wysiwyg Editor"
  },
  "options": {},
  "attributes": {
    "richtext": {
      "type": "richtext"
    }
  }
}
```

This the is strapi version I'm using (just installed this week, so there's no old schema or data in place):
```  "dependencies": {
    "@strapi/strapi": "4.5.2",
    "@strapi/plugin-users-permissions": "4.5.2",
    "@strapi/plugin-i18n": "4.5.2",
    "better-sqlite3": "7.4.6"
  },```
  
And here's a video reproduction of it:
https://user-images.githubusercontent.com/10200703/204032847-4b471905-dcf7-46d6-83a7-2690198b7f69.mov

Let me know if I can provide more info!

**Comment by giacomoforlani** [comment] 2022-12-06 13:16
@joshuaellis 

I have the same issue on my project and I prepared a minimum project setup to reproduce the bug.
You can clone my repo and follow the simple steps inside the README.

The problem seems to be caused by components that have relation fields and are used inside dynamic zones. As indicated by @hoggworks it's sufficient to swap two components of a different type to reproduce the bug, by deletion or movement.

https://github.com/giacomoforlani/my-strapi-project

**Comment by joshuaellis** [comment] 2023-01-13 15:25
Hi everyone (can't cc you all).

A small update that I didn't communicate yet (thought it was implicit so I apologise) this _should_ be fixed in our next release `4.6.0` with the attached PR 👍🏼

**Comment by nicoXXXXXtitan** [comment] 2023-01-16 21:08
> Hi everyone (can't cc you all).
> 
> A small update that I didn't communicate yet (thought it was implicit so I apologise) this _should_ be fixed in our next release `4.6.0` with the attached PR 👍🏼

great for the fix!
Thanks @joshuaellis

**Closed** 2023-01-17 11:09 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-manager

**Comment by hpmax00** [comment] 2023-06-02 06:35
Still have the same problem on strapi 4.7.1

**Comment by hpmax00** [comment] 2023-06-02 06:46
<img width="602" alt="image" src="https://github.com/strapi/strapi/assets/40781942/0d0aacdc-3eb2-4ce9-aca6-836e580b973c">
<img width="556" alt="image" src="https://github.com/strapi/strapi/assets/40781942/432adabe-81fc-4f3b-a0d5-bbb4fcaaae92">
