### ISSUE TITLE
Populate results in MissingSchemaError

### ISSUE THREAD

**Issue by kekami** [strapi/strapi#6627] opened 2020-06-11 09:13 UTC
**Describe the bug**
I have a model called page and I am trying to use populate on one of the properties to get the actual objects rather than the ids. However, when I add anything other than an empty array as the second argument of findOne, I get `error MissingSchemaError: Schema hasn't been registered for model "page".
Use mongoose.model(name, schema)` 

```
// api/page/services/page.js
module.exports = {
  findOne(params, populate) {
    return strapi.query('page').model.findOne(params, ['foo.bar']);
  },
};
```
**Expected behavior**
I expect to receive

```
{
  // page stuff
  foo: {
   bar: {
     // bar stuff
   }
  }
}
```

rather than

```
{
  // page stuff
  foo: {
   bar: "5ee1ea57e6d7a41689b6ac42"
  }
}
```

**System**

- Node.js version: v12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.1
- Database: MongoDB shell version v4.2.6
- Operating system: MacOS 10.15.5

**Comment by derrickmehaffy** [comment] 2020-06-11 09:26
You also need to add `foo` to that array. Moving this to a discussion as it's not a bug.

**Closed by derrickmehaffy** 2020-06-11 09:26 UTC
