### ISSUE TITLE
Unable to upload files larger than ~1GB [error 413]

### ISSUE THREAD

**Issue by lopermo** [strapi/strapi#8772] opened 2020-11-30 20:26 UTC
### Describe the bug

After modifying `middleware.js` to support files up to 10GB (10 * 1024 * 1024 * 1024 = 10737418240), and configuring nginx to remove any limit to debug the problem `client_max_body_size 0`, I'm still not able to upload files larger than ~1GB to S3 using the proper provider plugin.

So far I've tried debugging by uploading files up to 2GB to S3 manually, and they've been uploaded properly. From Strapi's admin panel, I've been able to upload files up to 1GB, with files weighting ~1.5GB failing already. They do fail after a long wait (so not the typical "File is too big" error). So I assume the request fails after it's close to a threshold I haven't been able to determine (but with my bandwith is close to 30-40min).

The bucket has the acceleration API activated.

### Steps to reproduce the behavior
***—config/middleware.js***
```
module.exports = ({ env }) => {
  return {
    settings: {
      parser: {
        enabled: true,
        multipart: true,
        textLimit: 10737418240,
        formLimit: 10737418240,
        jsonLimit: 10737418240,
        includeUnparsed: true,
        formidable: {
          maxFileSize: 10737418240 // 10 GB
        }
      },
      cors: {
        origin: ['http://localhost:3000', 'http://localhost', 'https://domain.com', 'http://localhost:1337', 'http://localhost:8000'],
      },
    }
  }
}
```

***—domain.com.conf (nginx virtualhost file)***
```
server {
        server_name domain.com;
        client_max_body_size 0;
        client_header_timeout   10000s;
        client_body_timeout     10000s;

        location / {
                client_max_body_size 0;

                proxy_pass http://localhost:1337;
                proxy_connect_timeout              10000s;
                proxy_send_timeout                 10000s;
                proxy_read_timeout                 10000s;

                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Host $http_host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }

        error_log /var/log/nginx/error.log info;

    listen 443 ssl; # managed by Certbot
    [...]
}
```

### Expected behavior

It should work as expected, hence uploading the file to S3.

### Screenshots

While files are being uploaded (for about 30-40min as I mentioned), this is how it looks like:
![image](https://user-images.githubusercontent.com/11388254/100661154-510c6100-3353-11eb-897e-e59b253ab96d.png)
![image](https://user-images.githubusercontent.com/11388254/100661060-34702900-3353-11eb-982f-9461c14971d8.png)
![image](https://user-images.githubusercontent.com/11388254/100661329-9af54700-3353-11eb-929f-b486daa59a41.png)

### System

- Node.js version: v14.13.0
- NPM version: v6.14.8
- Strapi version: strapi@3.3.2 // 
- Database: MySQL RDS
- Operating system: Ubuntu 20.04.1 LTS

_**— package.js**_ 
```
[...]
"devDependencies": {},
  "dependencies": {
    "knex": "<0.20.0",
    "mysql": "^2.18.1",
    "sqlite3": "latest",
    "strapi": "3.3.2",
    "strapi-admin": "3.3.2",
    "strapi-connector-bookshelf": "3.3.2",
    "strapi-plugin-content-manager": "3.3.2",
    "strapi-plugin-content-type-builder": "3.3.2",
    "strapi-plugin-documentation": "^3.3.2",
    "strapi-plugin-email": "3.3.2",
    "strapi-plugin-upload": "3.3.2",
    "strapi-plugin-users-permissions": "3.3.2",
    "strapi-provider-upload-aws-s3": "^3.3.2",
    "strapi-utils": "3.3.2"
  },
"engines": {
    "node": ">=10.16.0 <=14.x.x",
    "npm": ">=6.0.0"
  },
  "resolutions": {
    "formidable": "1.1.1"
  },
[...]
```

### Additional context

I've read that it might be a problem involving Node's(V8) buffer module, as stated by another user here https://github.com/strapi/strapi/issues/5470#issuecomment-718386733 but I have been unable of confirming.

**Comment by derrickmehaffy** [comment] 2020-11-30 20:42
> but with my bandwith is close to 30-40min

I'm guessing this might be the reason? some kind of request timeout? I spun up an EC2 instance and our test S3 bucket and was able to upload a test file of 2.5GB :thinking:

**Comment by lopermo** [comment] 2020-11-30 20:49
> > but with my bandwith is close to 30-40min
> 
> I'm guessing this might be the reason? some kind of request timeout? I spun up an EC2 instance and our test S3 bucket and was able to upload a test file of 2.5GB 🤔

When I upload it through the S3 file explorer it takes the same... :/
Any idea how can I determine if it's because of that?
I'm using an EC2 I(t3a.medium) instance and all I can upload is 1GB as I said. I'm running out of ideas of how to debug where is the source of the problem. I tried different settings on nginx, and strapi. But I seriously don't know how to continue debugging to see if it's the server or what...

**Comment by derrickmehaffy** [comment] 2020-11-30 21:20
TBH I'm not entirely sure either here, does it only happen in the admin or also via REST? I know we have a couple of issues via the admin atm.

(For now I'm going to mark this as a bug and see if there something my backend engineers can add)

**Comment by lopermo** [comment] 2020-11-30 22:37
I appreciate it @derrickmehaffy 

I continued debugging and came across this now. The strapi process is killed (and then restarted by pm2) and the upload ends with a `502 Bad Gateway` error. Is it possible it runs out of memory or something like that?

**Comment by derrickmehaffy** [comment] 2020-11-30 23:29
Entirely possible, we identified an issue in the upload memory buffer: https://github.com/strapi/strapi/issues/6432

Could very likely be related.

**Comment by lopermo** [comment] 2020-12-01 00:15
> Entirely possible, we identified an issue in the upload memory buffer: #6432
> 
> Could very likely be related.

Alright, so more debugging: 
If I try to upload several large (+1GB) files at the same time, strapi is killed and restarted _probably_ because of running out of memory.

On the other hand, uploading a single large file continues giving me the original issue. 413, file too big.

**Comment by lopermo** [comment] 2021-01-22 10:29
Still having this issue, any development on this?

**Comment by lopermo** [comment] 2021-02-08 09:14
After a few months, I still haven't been able to fix this problem, even getting a larger EC2 instance... This issue is a total deal breaker since uploading videos is part of the core of my website, therefore I can't still release it in production.

**Comment by derrickmehaffy** [comment] 2021-04-15 18:13
Closing as a duplicate of: https://github.com/strapi/strapi/issues/6432

(Out of memory)

**Closed by derrickmehaffy** 2021-04-15 18:13 UTC
Labels: status: duplicate

**Comment by Chandrapalsingh12** [comment] 2023-07-03 07:27
@lopermo Have you found any solution?

**Comment by gwu929** [comment] 2024-05-07 21:48
I encountered this same error today, after configuring max file upload size to 3G following the doc here:
https://docs.strapi.io/dev-docs/plugins/upload

<img width="832" alt="Screenshot 2024-05-07 at 5 36 32 PM" src="https://github.com/strapi/strapi/assets/162289888/d5d5d1df-cb1e-4af8-a517-807f0a73a161">

but i am still getting this 1G size limit error, and it looks like there is a hard coded size limit in Strapi source that limit the max file size to 1G....so i grabbed the installed @Strappi under node_modules for that error string, i got:
`${file.name} exceeds size limit of ${bytesToHumanReadable(sizeLimit)}.`

and further traced where the sizeLimit comes from, it is hardcoded in Strapi source code:
node_modules/@strapi/plugin-upload/server/config.js:    sizeLimit: 1000000000, // 1GB

**Comment by gwu929** [comment] 2024-05-07 22:27
and it turns out strapi doc for upload plugin has been uploaded to include config change in plugin.ts as well
