### ISSUE TITLE
Register hide username error "missing username"  

### ISSUE THREAD

**Issue by J2A2B** [strapi/strapi#8466] opened 2020-10-24 13:34 UTC
**Describe the bug**

Hi i'm tying to do the same thing that in the issue #3757  to create a user without username.
I did all the steps mentioned in the issue but it doesn't works.

I'll give to you some screen about the situation if you have any ideas.

Thanks in advance

**Screenshot**

<img width="1410" alt="Capture d’écran 2020-10-24 à 15 29 05" src="https://user-images.githubusercontent.com/15554576/97083077-2de0ea00-160e-11eb-8aa8-adff195b2251.png">

![Capture d’écran 2020-10-24 à 15 30 11](https://user-images.githubusercontent.com/15554576/97083083-36d1bb80-160e-11eb-96b9-5aa961103858.png)

<img width="1434" alt="Capture d’écran 2020-10-24 à 15 29 57" src="https://user-images.githubusercontent.com/15554576/97083089-43561400-160e-11eb-8f50-227beb205f19.png">

**Comment by derrickmehaffy** [comment] 2020-10-26 18:44
Currently username is a required field throughout the codebase (specifically the users-permissions plugin) and you will need to modify all of the controller/service code using this via the extensions system. Along with this you may need to extend the content-type-manager plugin as well to remove the required username.

We do not currently recommend removing this requirement, though in the future we are evaluating which option to choose as our unique index key (username or email).

**Comment by derrickmehaffy** [comment] 2020-10-26 18:45
I'm going to mark this as closed as it's not a bug of the code base but is more so a question about customization. Questions like these should be directed towards our [Forum](https://forum.strapi.io/)

**Closed by derrickmehaffy** 2020-10-26 18:45 UTC

**Comment by gbailey4** [comment] 2020-11-02 20:13
@J2A2B were you ever able to set up users w/o username? I'm running into the same issue in the app I'm starting as well
