### ISSUE TITLE
bootstrap function in admin failed

### ISSUE THREAD

**Issue by chandra655** [strapi/strapi#10423] opened 2021-06-02 13:52 UTC
### Describe the bug

After upgrading from 3.1.4 to 3.6.2, on server start facing below issue

[2021-06-02T13:38:10.010Z] error bootstrap function in admin failed
[2021-06-02T13:38:10.011Z] error TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at sortPermissionProperties (node_modules/strapi-admin/services/role.js:51:17)
    at Array.map (<anonymous>)
    at arePermissionsEqual (node_modules/strapi-admin/services/role.js:60:6)
    at f (node_modules/lodash/lodash.min.js:10:238)
    at Hr (node_modules/lodash/lodash.min.js:34:209)
    at node_modules/lodash/lodash.min.js:117:39
    at n (node_modules/lodash/lodash.min.js:9:117)
    at node_modules/lodash/lodash.min.js:73:58
    at l (node_modules/lodash/lodash.min.js:58:213)
    at assignPermissions (node_modules/strapi-admin/services/role.js:355:28)
    at async Object.resetSuperAdminPermissions (node_modules/strapi-admin/services/role.js:430:3)
    at async module.exports (node_modules/strapi-admin/config/functions/bootstrap.js:51:3)
    at async module.exports (node_modules/strapi-admin/ee/config/functions/bootstrap.js:18:3)
    at async Strapi.load (node_modules/strapi/lib/Strapi.js:379:5)
    at async Strapi.start (node_modules/strapi/lib/Strapi.js:196:9)
error Command failed with exit code 1.

### Steps to reproduce the behavior

1. upgraded packages
2. started server 

### Expected behavior

1. should start the server

### System

- Node.js version: v12.18.1
- NPM version: v6.14.10
- Strapi version: 3.6.2
- Database: mysql
- Operating system: OSX/linux

**Comment by derrickmehaffy** [comment] 2021-06-02 20:48
did you follow the migration guides in our documentation? Or are you using Extensions?

https://strapi.io/documentation/developer-docs/latest/update-migration-guides/migration-guides.html

**Comment by tonoli** [comment] 2021-06-07 14:45
I have the same issue I followed all the migration guides

**Comment by tonoli** [comment] 2021-06-07 15:56
I don't know why but when I do `SELECT * FROM public.strapi_permission
ORDER BY id ASC ` 
All the rows have their properties field to NULL 

- I tried to fix it with `UPDATE public.strapi_permission SET properties = '{}';`

It did fix the bootstrap error but then when I go to a Single Type on my Content Editor admin I get an error without a lot of details: 
```
Something went wrong.
Details
Cannot read property 'code' of undefined
TypeError: Cannot read property 'code' of undefined
    at h (http://localhost:1337/admin/main.a7c0d6c0.chunk.js:1:9006911)
```

- I tried to delete all the row form public.strapi_permission but this resulted to the same result. 

Any idea how I can solve this @derrickmehaffy ?

**Comment by chandra655** [comment] 2021-06-08 06:42
can we connect on zoom call @derrickmehaffy

**Comment by tonoli** [comment] 2021-06-11 15:26
I don't think he can give that kind of support but a quick message to show us what to try would be great

**Comment by derrickmehaffy** [comment] 2021-06-14 14:00
We can hop in a Discord help channel to do screen sharing, PM me on the Discord server so we can setup a time/date and we can try some troubleshooting. The Strapi Discord is https://discord.strapi.io


> I don't think he can give that kind of support but a quick message to show us what to try would be great

Generally no, but in certain cases where it's easier to see whats going on and troubleshoot live it may help. Happy to have both of you.

**Comment by tonoli** [comment] 2021-06-14 14:23
@chandra655 We planned a live troubleshooting session with @derrickmehaffy, the 15th of June at 5pm Paris Time Zone. If you can't be there I'll try to write down the solution.

**Comment by iserko** [comment] 2021-06-21 15:01
@derrickmehaffy having the same issue here ... same migration pattern, going from 3.1.7 to 3.6.3, not using any custom extensions or customized admin. Properties seems to be `NULL` on every `strapi_permission` record.

Should the suggestion be, to run the SQL that @tonoli mentioned if you're doing an upgrade like that?
```UPDATE public.strapi_permission SET properties = '{}' WHERE properties IS NULL;``` ?

**Comment by iserko** [comment] 2021-06-21 16:08
@derrickmehaffy found the problem ... https://github.com/strapi/strapi/blob/master/packages/strapi-admin/config/migrations/permissions-fields-to-properties.js#L15 ... it doesn't account for `previousDefinition` being undefined, so it never migrates it properly.

**Comment by derrickmehaffy** [comment] 2021-06-21 21:56
:thinking: interesting will need to check what the difference was in 3.5.4

**Comment by iserko** [comment] 2021-06-21 22:34
> 🤔 interesting will need to check what the difference was in 3.5.4

@derrickmehaffy it wasn’t 3.5.4, it’s 3.6.0 … the i18n feature. This migration file was never tested against a pre-3.2.0 db state.

I think it should be replicatable if you create a project with 3.1.x and upgrade directly to 3.6.x

**Comment by derrickmehaffy** [comment] 2021-07-01 22:07
> > thinking interesting will need to check what the difference was in 3.5.4
> 
> @derrickmehaffy it wasn’t 3.5.4, it’s 3.6.0 … the i18n feature. This migration file was never tested against a pre-3.2.0 db state.
> 
> I think it should be replicatable if you create a project with 3.1.x and upgrade directly to 3.6.x

I'll give that a shot, thank you.

**Comment by derrickmehaffy** [comment] 2021-07-22 21:51
I'm still unable to reproduce this doing all kinds of various upgrades :thinking:

**Comment by tonoli** [comment] 2021-07-27 21:07
@iserko solution helped me so I updated the Strapi version first to 3.5.x and then to 3.6.x and I solved the issue

**Comment by hoquangtri289** [comment] 2021-08-01 13:35
<img width="731" alt="Screenshot_263" src="https://user-images.githubusercontent.com/23572898/127772813-a62ac9ad-2841-435c-9cf4-cb7795c3c890.png">
<img width="621" alt="Screenshot_264" src="https://user-images.githubusercontent.com/23572898/127772816-170192af-0d96-4b27-81a7-a2b745615722.png">

Tôi cũng bị như vậy. Mặc dù vẫn chạy tốt.

**Comment by derrickmehaffy** [comment] 2021-08-02 19:01
> <img width="731" alt="Screenshot_263" src="https://user-images.githubusercontent.com/23572898/127772813-a62ac9ad-2841-435c-9cf4-cb7795c3c890.png">
> <img width="621" alt="Screenshot_264" src="https://user-images.githubusercontent.com/23572898/127772816-170192af-0d96-4b27-81a7-a2b745615722.png">
> 
> Tôi cũng bị như vậy. Mặc dù vẫn chạy tốt.

Can you please use English for responses. Thank you!

**Comment by benalexander** [comment] 2021-08-18 11:06
Hi there, just to add to people's experiences, I had the same issue and the workaround of updating the Strapi version first to 3.5.x and then to 3.6.x also solved it for me 👍

**Comment by derrickmehaffy** [comment] 2021-08-18 17:37
Setting as closed as multiple people confirmed following step by step upgrades worked for them.

**Closed by derrickmehaffy** 2021-08-18 17:37 UTC
Labels: status: can't reproduce

**Comment by baermathias** [comment] 2021-09-15 09:58
I think this is the same issue https://forum.strapi.io/t/cannot-start-application-bootstrap-function-in-admin-failed/5923

**Comment by pm2monit** [comment] 2021-09-20 08:40
> @derrickmehaffy found the problem ... https://github.com/strapi/strapi/blob/master/packages/strapi-admin/config/migrations/permissions-fields-to-properties.js#L15 ... it doesn't account for `previousDefinition` being `undefined`, so it never migrates it properly.
> 
> Perhaps the proper (and tested) way is to migrate via another version (testing via 3.5.4 now)?
> 
> Update: confirmed ... if you update via 3.5.4 you do not have the same issue. @derrickmehaffy time for another article in the Migration Guides for updating to 3.6.x

same issue, thank's @derrickmehaffy
