### ISSUE TITLE
Strapi filter: the "or" works as "and" in graphql

### ISSUE THREAD

**Issue by ahmadjoya** [strapi/strapi#14302] opened 2022-09-02 14:28 UTC
## Bug report

- Node.js version: 16.15.1
- NPM version: 8.11.0
- Strapi version: 4.3.6
- Database: postgreSQL
- Operating system: Windows

### Strapi filter: "or" works as "and" in graphql

hello community!
I am troubled while wanted to use complex filter using "or" for two fields.
here firstly I wanted filter by slug and setting an or operator that if the first filter is not working, than the second operator which is filter by itSlug should run.

#### this single filter is working
![image](https://user-images.githubusercontent.com/35627961/188170785-eec3c076-0f50-49d2-b4c5-368a6b7cc311.png)

#### this complex query is not working
![image](https://user-images.githubusercontent.com/35627961/188170975-4b8f8fb8-ebad-4440-853e-495fcaca2591.png)

### Code snippets
```
query category($locale: I18NLocaleCode, $slug: String) {
    categories(locale: $locale, filters: {slug: {eq: $slug}, or: [{itSlug: {eq: $slug}}]} ) {
      data {
        id
        attributes {
          categoryName
          slug
          description
          locale
        }
      }
    }
  }
```

**Comment by Convly** [comment] 2022-09-02 15:07
Hi,

If you want to use `or`, you need to pass all the targeted clauses inside its array, putting the `or` next to another clause will create an `and` clause between the `or` components and the other ones.

Basically, what should work would be smth like: `or: [{ slug: { eq: $slug } }, { itSlug: { eq: $slug } }]`

**Comment by bolg55** [comment] 2022-09-02 16:12
Closing as @Convly provided correct syntax. Not a bug.

**Closed by bolg55** 2022-09-02 16:12 UTC

**Comment by ahmadjoya** [comment] 2022-09-05 07:34
> [{ slug: { eq: $slug } }, { itSlug: { eq: $slug } }]

Thank you so much @Convly
