### ISSUE TITLE
Records that are restricted by custom roles are not restricted through the Relation component.

### ISSUE THREAD

**Issue by nogumaruo** [strapi/strapi#14226] opened 2022-08-26 04:43 UTC
### Required System information

- Node.js version:v16.14.0
- NPM version:8.6.1
- Strapi version:4.3.6
- Database:postgresql
- Operating system:mac OS 12.2.1

### Describe the bug
Records that are restricted by custom roles are not restricted through the Relation component.

## Prerequisite
strapi is Enterprise edition

## Steps
1. Create a List collection of Distributor.
```
{
  "kind": "collectionType",
  "collectionName": "distributors",
  "info": {
    "singularName": "distributor",
    "pluralName": "distributors",
    "displayName": "distributor",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string",
      "unique": true,
      "required": true
    },
  }
}
```
2. create a List collection of Article. Create a List collection of Articles with Distributor as a relation attribute.
```
{
  "kind": "collectionType",
  "collectionName": "articles",
  "info": {
    "singularName": "article",
    "pluralName": "articles",
    "displayName": "Article",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "title": {
      "type": "string",
      "required": true,
    },
     "distributor": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::distributor.distributor"
    },
  }
}

```
3. Create two types of Role from AdminPanel Roles in Settings (let's say ARole and BRole).
4. configure ARole and BRole as shown in the following images.
![image](https://user-images.githubusercontent.com/98809021/186816526-0f5f7813-3aa6-451a-b242-f6c76e7c7ef7.png)
5. Create two accounts and assign ARole and BRole to each account. (Let's say user A and user B).
6. log in as user A and create a Distributor record.
7. Log in as user B and create a Distributor record.
8. when a new Article record is created by user B and Distributor is selected from the list, the record created by user A can also be selected.

### Expected behavior

We expect that the only records that a B user can select in the Distributor of an Article are those created by the B user (or BRole).

### Screenshots

![image](https://user-images.githubusercontent.com/98809021/186822737-3e8b66fb-92d0-474e-af7d-5f242817a9b8.png)

### Code snippets

@strapi/plugin-content-manager/server/controllers/relations.js
The following modification to relations.js will improve the situation.
I would appreciate your confirmation that I may have omitted some considerations.
[before]
```
  async find(ctx) {
    const { model, targetField } = ctx.params;
    const { _component, ...query } = ctx.request.query;
    const { idsToOmit } = ctx.request.body;

    if (!targetField) {
      return ctx.badRequest();
    }

    const modelDef = _component ? strapi.getModel(_component) : strapi.getModel(model);

    if (!modelDef) {
      return ctx.notFound('model.notFound');
    }

    const attribute = modelDef.attributes[targetField];
    if (!attribute || attribute.type !== 'relation') {
      return ctx.badRequest('targetField.invalid');
    }

    const target = strapi.getModel(attribute.target);

    if (!target) {
      return ctx.notFound('target.notFound');
    }

    if (idsToOmit && Array.isArray(idsToOmit)) {
      query.filters = {
        $and: [
          {
            id: {
              $notIn: idsToOmit,
            },
          },
        ].concat(query.filters || []),
      };
    }

    const entityManager = getService('entity-manager');

    const entities = await entityManager.find(query, target.uid, []);

    if (!entities) {
      return ctx.notFound();
    }

    const modelConfig = _component
      ? await getService('components').findConfiguration(modelDef)
      : await getService('content-types').findConfiguration(modelDef);

    const field = prop(`metadatas.${targetField}.edit.mainField`, modelConfig) || 'id';
    const pickFields = [field, 'id', target.primaryKey, PUBLISHED_AT_ATTRIBUTE];

    ctx.body = entities.map(pick(pickFields));
  },
```

[after]
```
  async find(ctx) {
    const { model, targetField } = ctx.params;
    const { _component, ...query } = ctx.request.query;
    const { idsToOmit } = ctx.request.body;
    const { userAbility } = ctx.state;

    if (!targetField) {
      return ctx.badRequest();
    }

    const modelDef = _component ? strapi.getModel(_component) : strapi.getModel(model);

    if (!modelDef) {
      return ctx.notFound('model.notFound');
    }

    const attribute = modelDef.attributes[targetField];
    if (!attribute || attribute.type !== 'relation') {
      return ctx.badRequest('targetField.invalid');
    }

    const target = strapi.getModel(attribute.target);

    if (!target) {
      return ctx.notFound('target.notFound');
    }

    if (idsToOmit && Array.isArray(idsToOmit)) {
      query.filters = {
        $and: [
          {
            id: {
              $notIn: idsToOmit,
            },
          },
        ].concat(query.filters || []),
      };
    }

    const entityManager = getService('entity-manager');

    const permissionChecker = getService('permission-checker').create({ userAbility, model });
    if (permissionChecker.cannot.read()) {
      return ctx.forbidden();
    }
    const permissionQuery = permissionChecker.buildReadQuery(query);

    const entities = await entityManager.find(permissionQuery, target.uid, []);

    if (!entities) {
      return ctx.notFound();
    }

    const modelConfig = _component
      ? await getService('components').findConfiguration(modelDef)
      : await getService('content-types').findConfiguration(modelDef);

    const field = prop(`metadatas.${targetField}.edit.mainField`, modelConfig) || 'id';
    const pickFields = [field, 'id', target.primaryKey, PUBLISHED_AT_ATTRIBUTE];

    ctx.body = entities.map(pick(pickFields));
  },
```

**Comment by kasonde** [comment] 2022-09-09 11:09
Hi @nogumaruo I believe this was intended for performance reasons. I've reached out to our Eng team to get more technical details around this. 
cc @derrickmehaffy if you have those details in the mean time.

**Comment by derrickmehaffy** [comment] 2022-09-09 12:59
It wasn't performance, it's more so that the relation fields in the admin aren't filtered currently, I would consider this more of a feature request than a bug for now.

**Comment by kasonde** [comment] 2022-09-09 20:04
We are currently moving many feature requests to our new feedback and feature request website to help clean up the GitHub issues and make it easier for us to review bug reports and fix them.

I have moved this feature to the following URL: https://strapi.canny.io/admin/feedback/feature-requests/p/apply-rbac-conditionals-to-relations-list
If you are interested in this feature please feel free to go there and add more comments and/or upvote it there.

For now I will close this and lock it so that all new information goes into our new feedback website.
Thanks!

**Closed by kasonde** 2022-09-09 20:04 UTC
Labels: issue: feature request, status: confirmed, source: core:admin

**Comment by nogumaruo** [comment] 2022-09-12 00:27
@kasonde @derrickmehaffy 

Thanks for the answers and for moving this to the request list!

We needed this feature because we are going live this month for commercial use.
For now, we will get by with content-manager customization.

src/extensions/content-manager/strapi-server.js
```
const { find } = require('. /server/controllers/relations');

module.exports = (plugin) => {

  plugin.controllers["relations"].find = (ctx) => {
    return find(ctx)
  };

  return plugin;
};
```
