### ISSUE TITLE
new custom GET endpoint must contains params

### ISSUE THREAD

**Issue by lordzpipo** [strapi/strapi#5246] opened 2020-02-15 08:35 UTC
**Describe the bug**
after initial a new endpoint in `GET` method, will return me 404 (already enable this endpoint on admin portals)

**Steps to reproduce the behavior**
1. add new endpoint in `routes.json` as bellow
```js
...
{
   "method": "GET",
   "path": "/model/lookup",
    "handler": "model.lookup",
    "config": {
         "policies": []
    }
}
```
2. create new controller functions in `model.js`
```js
...
async lookup(ctx) {
    let entities;
    entities = await strapi.query("model").find({});
    return entities.map(entity => {
         sanitizeEntity(entity, {model: strapi.models.model})
    })
},
```
3. enable `lookup` api in admin portal
4. call `localhost:1337/model/lookup` in `GET` method (for this case i use browser)

**Expected behavior**
return model array in json, but get 
```
{"statusCode":404,"error":"Not Found","message":"Not Found"}
```

**Screenshots**
-

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10.9.0
- Strapi version: beta.18.7
- Database: mongodb (mlab)
- Operating system: windows

**Additional context**
-

**Comment by derrickmehaffy** [comment] 2020-02-15 21:18
`Strapi version: latest` Define latest please as in give the exact version number from your package.json

**Comment by AkashV10** [comment] 2020-02-16 06:35
I can confirm the same issue with latest version -  Strapi v3.0.0-beta.18.7     
package.json - "strapi": "3.0.0-beta.18.7",
database- postgres
node.js version- 12.14.0
OS- Windows

**Comment by AkashV10** [comment] 2020-02-16 07:09
@lordzpipo shouldn't the controller be defined in "handler" key and not in "handle"?
```diff
{
   "method": "GET",
   "path": "/model/lookup",
-  "handle"~: "model.lookup", 
+  "handler"~: "model.lookup",
    "config": {
         "policies": []
    }
}
```

**Comment by lordzpipo** [comment] 2020-02-16 13:22
hi @AkashV10 , i am sorry, it's typo on sample code,
in my actual code it's `handler`

**Comment by lordzpipo** [comment] 2020-02-16 13:25
hi @derrickmehaffy, i am sorry.
`"strapi": "3.0.0-beta.18.7",`

**Comment by lauriejim** [comment] 2020-02-18 15:31
Hello! Can you give us more information about how and where you created your controller and added the new route.
This will help us to reproduce and understand your error.

**Comment by lordzpipo** [comment] 2020-02-19 03:52
hi @lauriejim , please check `Steps to reproduce the behavior`

**Comment by lauriejim** [comment] 2020-02-19 17:03
Did you tried `/models/lookup` ?
When you are going in the Users-Permission section and if you click on the controller function, you can see your endpoint on the right side.

**Comment by AkashV10** [comment] 2020-02-19 17:17
> Did you tried `/models/lookup` ?
> When you are going in the Users-Permission section and if you click on the controller function, you can see your endpoint on the right side.
@lauriejim would the route really matter when you are defining a custom one? He can also define it as "/modellist/lookup" and it should work (provided he enables it in role permissions) , the controller function should be called. I tried reproducing his issue but couldn't.

@lordzpipo can you add some logs(console etc) to your controller function and see if the request is reaching there?
Would it be possible to share your repository or an example repo so others can try to reproduce the issue?

**Comment by lordzpipo** [comment] 2020-02-21 06:04
> > Did you tried `/models/lookup` ?
> > When you are going in the Users-Permission section and if you click on the controller function, you can see your endpoint on the right side.
> > @lauriejim would the route really matter when you are defining a custom one? He can also define it as "/modellist/lookup" and it should work (provided he enables it in role permissions) , the controller function should be called. I tried reproducing his issue but couldn't.
> 
> @lordzpipo can you add some logs(console etc) to your controller function and see if the request is reaching there?
> Would it be possible to share your repository or an example repo so others can try to reproduce the issue?

hi @AkashV10 , i tried before, it interrupt before reaching endpoint
i will try create a example repo to reproduce it, thanks for help

**Comment by lordzpipo** [comment] 2020-02-21 07:29
hi @AkashV10 ,
this is my example repo: [click me](https://github.com/lordzpipo/strapi-bug)

**Comment by AkashV10** [comment] 2020-02-21 08:20
hi @lordzpipo , your problem is you are defining the same route again. You already have following routes-
```http
1. GET - /dummies/
2. GET - /dummies/:id
3. GET- /dummies/test
4. GET - /dummies/test/:id
```
The second and third routes (/dummies/:id and /dummies/test) are overlapping.  So when you call /dummies/test, actual call goes to /dummies/:id with test being the value for id used in the dummy.find controller. 
4th route works becuase it calls its specific dummy.test controller. 
You are getting 404 on third route because your find function is unable to find any dummy matching id as 'test'.

Rename your path to something like `/dummies/test/new` and it should work. I was able to fix your issue with correcting the route. 

@lauriejim you can close this issue. It's not a valid bug.

**Comment by lauriejim** [comment] 2020-02-21 16:34
Thank you for your help @AkashV10

**Closed** 2020-02-21 16:33 UTC
Labels: type: help wanted
