### ISSUE TITLE
Error using Mysql Database with strapi

### ISSUE THREAD

**Issue by dyunggertrude** [strapi/strapi#378] opened 2017-12-14 15:19 UTC
**Node.js version v8.9.3 **:
**npm 5.6.0 **:
**Strapi 3.0.0-alpha.7**:
**Windows 10**:

I followed the tutorial, I created users in MongoDB and added MySQL connection, and with it created a simple API through  'Content Type Builder' menu !!. 
The JS code has been generated, when i add a value in database Mysql the server strapi restart after a PUT

INFO (13492 on PC-DE-DANIEL): To shut down your server, press <CTRL> + C at any time
DEBUG (13492 on PC-DE-DANIEL): GET 6cdae4ac03569436db8d1d34de49b2f5.svg (17 ms)
DEBUG (13492 on PC-DE-DANIEL): GET /content-type-builder/models/carf (11 ms)
DEBUG (13492 on PC-DE-DANIEL): GET /content-type-builder/models/carf (3 ms)
INFO (1220 on PC-DE-DANIEL): The server is restarting

> DEBUG (13492 on PC-DE-DANIEL): PUT /content-type-builder/models/carf (18 ms)

INFO (14248 on PC-DE-DANIEL): Server started in C:\Users\PC-DE-DANIEL\Downloads\projet\strapi\GertrudeApi
INFO (14248 on PC-DE-DANIEL): Your server is running at http://localhost:1337
DEBUG (14248 on PC-DE-DANIEL): Time: Thu Dec 14 2017 16:12:06 GMT+0100 (Paris, Madrid)
DEBUG (14248 on PC-DE-DANIEL): Launched in: 2737 ms
DEBUG (14248 on PC-DE-DANIEL): Environment: development
DEBUG (14248 on PC-DE-DANIEL): Process PID: 14248
DEBUG (14248 on PC-DE-DANIEL): Version: 3.0.0-alpha.7 (node v8.9.3)
INFO (14248 on PC-DE-DANIEL): To shut down your server, press <CTRL> + C at any time

**Comment by soupette** [comment] 2017-12-15 09:56
Hello! I am having trouble understanding your issue... Could you be more specific when you say that the server restart after adding a new value?
If you're adding a new field or modifying an existing from the content type builder the server must restart since we're writing a file in your app.

**Comment by kakaroto1500** [comment] 2017-12-22 18:20
so I understood I think the complaint of it and when it throws a new die using api and the server give a restart

**Comment by soupette** [comment] 2018-01-08 13:12
I'm closing the issue since it doesn't appear to be a bug but the expected behavior

**Closed by soupette** 2018-01-08 13:12 UTC
Labels: priority: low, source: plugin content-type-builder
