### ISSUE TITLE
SSO admin login gets stuck on redirect to DOMAIN/admin/auth/login/success

### ISSUE THREAD

**Issue by dtriag** [strapi/strapi#19777] opened 2024-03-14 11:58 UTC
### Required System information

- Node.js version: Node/Yarn Version: yarn/1.22.19 npm/? node/v20.11.0 linux x64
- NPM version:
- Strapi version: v4.20.3:
- Database: SQLite
- Operating system: linux-x64
- Edition: Enterprise:

### Describe the bug

We have set up SSO (OIDC passport-azure-ad ) to the admin panel with Azure AD. After successfully loggin in on the azure page, and redirecting back to strapi, the process gets stuck at the redirect to DOMAIN/admin/auth/login/success. Strapi does not go through with DOMAIN/admin/auth/login?redirectTo=%2Fauth%2Flogin%2Fsuccess.
Manually entering DOMAIN/admin/auth/login/success will complete the login and land the user on the DOMAIN/admin page.

### Steps to reproduce the behavior

1. Set up SSO Provider for admin panel
2. log in through SSO
3. Get stuck on DOMAIN/admin/auth/login?redirectTo=%2Fauth%2Flogin%2Fsuccess.

### Expected behavior

1. Set up SSO Provider for admin panel
2. log in through SSO
3. Get redirected to DOMAIN/admin/auth/login/success
4. Get access to DOMAIN/admin page

**Comment by derrickmehaffy** [comment] 2024-03-18 21:41
Closing this as a question, not a bug report. We are already planning to refactor the SSO documentation post Strapi 5's stable release but in this case you'll need to prefix the redirect URL with your server's public URL (likewise make sure the public URL is set).

```js
// path: ./config/server.js

module.exports = ({ env }) => ({
  // ...
  url: env('PUBLIC_URL')
  // ...
});
```

Then in your admin config you can reuse this same environment variable to prefix the callback URL:

```js
// path: ./config/admin.js

module.exports = ({ env }) => ({
  auth: {
    // ...
    providers: [
      {
        // ...
        createStrategy: (strapi) =>
          new SomeStrategy(
            {
              // ...
              callbackURL:
                env('PUBLIC_URL') +
                strapi.admin.services.passport.getStrategyCallbackURL(
                  "someProvider"
                ),
            },
            (accessToken, refreshToken, profile, done) => {
              done(null, {
                // ...
              });
            }
          ),
      },
    ],
  },
});
```

**Closed** 2024-03-18 21:41 UTC
Labels: source: core:admin, flag: question, version: 4

**Comment by dtriag** [comment] 2024-03-19 07:04
Hi @derrickmehaffy 
the public URL is set both in server.js and in the strategy, so this is not a configuration issue but definitly a bug. Note that the login proccess succeeds up to the finaly redirect step. So the issue is not with the redirect from the IDP in the OIDC process, but strapi internally the final redirect to DOMAIN/admin/auth/login/success.
