### ISSUE TITLE
Cannot start/build Admin Panel

### ISSUE THREAD

**Issue by andre-av** [strapi/strapi#1751] opened 2018-08-14 16:10 UTC
Node: 8.11.3
npm: 6.2.0
strapi: 3.0.0-alpha.13.0.1
OS: Mac OS 10.13.6

**What is the current behavior?**

Npm throws errors when using scripts

**Steps to reproduce the problem**

1. strapi new testapi
2. cd testapi/admin
3. npm install
4. npm start

output:
```
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js

module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/andre/Documents/workspace/px/test/admin/node_modules/strapi-helper-plugin/node_modules/.bin/cross-env'
```
Tried `npm link strapi-helper-plugin` but I get same error

**Comment by soupette** [comment] 2018-08-14 16:26
hi @andre-av you need to refer to the [CONTRIBUTING GUIDE](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md) in order to customise the admin.

I'm closing the issue since it's a duplicate of #1006 and others.

**Closed by soupette** 2018-08-14 16:26 UTC

**Comment by andre-av** [comment] 2018-08-14 16:43
I understand now that I read the guide, but the official documentation leads to user confusion in this topic. One can assume that the contributing guide is for contributors, or people who wish to help in strapi's development, not for internal local changes. I could help with a PR to update the documentation if it helps future users, anyways thanks for the help.
