### ISSUE TITLE
Strapi crashes on a JS error on Content Type Builder

### ISSUE THREAD

**Issue by ZeldOcarina** [strapi/strapi#13397] opened 2022-05-26 14:21 UTC
Hi!

With the new patch at 4.1.12 Strapi is crashing in the content type builder with a JS error:

`TypeError: Cannot destructure property 'startSection' of '(0 , t.useGuidedTour)(...)' as it is undefined.`

It's probably an error with the guided tour I guess.

I will downgrade now but wanted to let you know.

UPDATE: This is the same as this issue: https://github.com/strapi/strapi/issues/13293

I am using NPM 8.10.0 and Node 14.16.0.

Now same error goes with Strapi 4.1.11 too.

**Comment by ZeldOcarina** [comment] 2022-05-26 14:41
UPDATE: removing the build folder, node_modules and package-lock.json, re-running npm install and npm run build fixed the issue. Now I will try to re-update.

**Comment by mortenmoulder** [comment] 2022-06-05 01:47
I do not feel like this issue needs to be closed. I'm encountering the same issue.

I can reproduce it by creating a blog from the templates, then simply going into the schema editor and removing something from the blocks section, such as media, quote, or slider. I think the problem is, there are already created articles, and those articles contain some of the sections I am trying to remove.

**Comment by mdespeuilles** [comment] 2022-06-09 15:13
For information I have resolve this issue by using Yarn instead npm

**Comment by Casal0x** [comment] 2022-06-13 23:54
How i can fix it in heroku, is the only place I get that error.

**Comment by ZeldOcarina** [comment] 2022-06-14 06:21
@mortenmoulder Should I reopen this for the Strapi team to look into it?

**Comment by mortenmoulder** [comment] 2022-06-14 13:03
@ZeldOcarina Please do. The problem is, as I said, quite easy to replicate:

1. Create a new project (I used the blog template): `npx create-strapi-app my-app-name --template blog`
2. Log into /admin with your new user
3. Go find the article collection type
4. Remove any of the blocks (like Media, Quote, or Slider)
5. Save changes
6. Go edit any article

You should now see a white screen. I commented on [my own issue](https://github.com/strapi/strapi/issues/13469#issuecomment-1146901211) here with some pictures and videos as well.

**Comment by derrickmehaffy** [comment] 2022-06-14 13:37
duplicate of https://github.com/strapi/strapi/issues/12837

**Closed by derrickmehaffy** 2022-06-14 13:37 UTC
Labels: status: duplicate
