### ISSUE TITLE
Creating a new project with a GraphQL API returns an error 

### ISSUE THREAD

**Issue by jaderyan** [strapi/strapi#13060] opened 2022-04-05 13:45 UTC
### Required System information

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Strapi version: 4.1.7
- Database: sqlite
- Operating system: Ubuntu

### Describe the bug

After creating a project from scratch and installing the GraphQL plugin, the server will not connect and the playground returns an error:

```
{
  "error": "Unexpected end of JSON input"
}
```

### Steps to reproduce the behavior

1. `yarn create strapi-app my-project --quickstart`
2.  Move into `my-project` folder and run `yarn strapi install graphql`
3. `yarn build`
4. `yarn develop`
5. Visit http://localhost:1337/graphql
6. See error

### Expected behavior

Visiting the playground should load the schema and allow interactivity with the GraphQL API.

**Comment by derrickmehaffy** [comment] 2022-04-11 17:39
Tested using v4.1.7 and tried both yarn and npm / tested installing the package manually vs using the strapi command and could not reproduce the issue.

Marking as closed until we get updated information on how to reproduce the issue. Based on the error message it looks like there is a syntax error in one of the config files but doesn't appear to be caused by us.

**Closed by derrickmehaffy** 2022-04-11 17:39 UTC
Labels: issue: bug, severity: low, status: can not reproduce, source: plugin:graphql
