### ISSUE TITLE
 Arrows navigation not working inside repeatable components

### ISSUE THREAD

**Issue by nayara** [strapi/strapi#12432] opened 2022-02-08 12:34 UTC
### Describe the bug

When create a repeatable component with text field(long or short) the keyboard arrows not work to navigate through the text. The keys as `End` or `Home` keep working.

### Steps to reproduce the behavior

1. Create a repeatable component
2. Add a text field
3. Populate the field
4. Try to navigate with keyboard arrows

### Expected behavior

Navigate in the text fields with arrows in all components.

### Screenshots

N/A

### Code snippets

N/A

### System

- Node.js version: v14.17 
- NPM version: 6.14.14
- Strapi version: 4.0.7 and 4.0.6 
- Database: Postgres
- Operating system: iOS and Linux

### Additional context

The bug is reproducible when creates a new application with `npx create-strapi-app@latest`.

**Comment by Matb85** [comment] 2022-02-10 09:12
Hi, the issue should be **P0 or severity high** as it completely destroys User Experience when working with repeatable components or dynamic zones. Please take care of that 🙏🙏🙏

**Comment by BhuvaneshPatil** [comment] 2022-02-12 14:35
The issue is because of react-dnd.
Here is the issue on react-dnd repo - https://github.com/react-dnd/react-dnd/issues/1971

**Comment by kodermax** [comment] 2022-03-07 06:05
How can a workaround add an option to disable draggable?

**Comment by kodermax** [comment] 2022-03-08 06:57
really need a fix

**Comment by kjoscha** [comment] 2022-06-02 05:54
> Hi, the issue should be **at least severity medium** as it completely destroys User Experience when working with repeatable components or dynamic zones. Please take care of that praypraypray

I can confirm this. Repeatable components are very important, because they give the users the capability of sorting articles by hand, but they are not really usable in the current state

**Comment by jkomkin** [comment] 2022-06-23 15:44
Experiencing the same thing. It's especially bad when dealing with WYSIWYG fields within repeatable components.

![strapi](https://user-images.githubusercontent.com/605620/175339762-89e83a44-d482-496d-a5f6-677b20e7f92a.gif)

**Comment by derrickmehaffy** [comment] 2022-07-14 21:24
Raising this to medium as there is no workaround

**Comment by ihassansattar** [comment] 2022-08-17 07:26
Any update on this?

**Comment by derrickmehaffy** [comment] 2022-08-17 19:57
Not currently no

**Comment by ihassansattar** [comment] 2022-08-18 11:16
Hopefully, this gets resolved soon, it destroys the UX.

**Comment by gu-stav** [comment] 2022-08-18 11:25
@ihassansattar I have on my todo-list. Unfortunately the problem is bigger than it first seems and spreads into tables, dynamic-zones and maybe some other areas. That being said: I/ we see the importance of the issue and will work on it, as soon as we have some capacity in the squad.

**Comment by ihassansattar** [comment] 2022-08-18 11:28
Thank you, I appreciate it.

**Comment by dpodz** [comment] 2022-08-19 18:27
> @ihassansattar I have on my todo-list. Unfortunately the problem is bigger than it first seems and spreads into tables, dynamic-zones, repeatable-components and maybe some other areas. That being said: I/ we see the importance of the issue and will work on it, as soon as we have some capacity in the squad.

Thanks! This is a big UX bug for our non-technical content authoring team.

**Comment by joshuaellis** [comment] 2022-09-23 10:11
Hey everyone, we all appreciate everyone's patience, we've had some capacity to look into this and a PR is now open for review so hopefully this should be fixed soon 😄

**Closed** 2022-09-28 10:10 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-manager
