### ISSUE TITLE
Issue when click to dropDown menu on strapi v4

### ISSUE THREAD

**Issue by dogusdeniz** [strapi/strapi#15162] opened 2022-12-13 01:35 UTC
### Required System information

- Node.js version: v16.14.2
- NPM version: 8.5.0
- Strapi version: 4.5.3
- Database:  5.7.36, for Win64 (x86_64)
- Operating system: Win64

### Description

whenever i click on a dropdown menu i get an error.

### Steps to reproduce the behavior

1. Go to Content Manager
3. Click on any collection
4. Scroll down to bottom
5. Click on the dropdown menu
6. See error "Woops! Something went wrong. Please, try again."

### Expected behavior

Data must be listed.

### Screenshots

![53cbf0e6-7a01-4640-b182-be1e3d1c907f](https://user-images.githubusercontent.com/32245914/207205418-75a30f0c-db19-4e8d-b4c3-98af794e3906.jpg)

![04d1a7c2-4a5c-47d7-9530-547b9cb5ee76](https://user-images.githubusercontent.com/32245914/207205362-d4ad37f3-a092-41f3-9a77-23ba459a0675.jpg)

**Comment by joshuaellis** [comment] 2022-12-13 08:43
duplicate of #14993

**Closed by joshuaellis** 2022-12-13 08:43 UTC
Labels: status: duplicate
