### ISSUE TITLE
Server config admin.autoOpen flag not working for the first start

### ISSUE THREAD

**Issue by bluehawk27** [strapi/strapi#5960] opened 2020-04-26 17:13 UTC
**Describe the bug**

**Steps to reproduce the behavior**

1. NODE_ENV=production npm run start 

**Expected behavior**
When the flag is set to false I expect the app to not open the admin panel in a browser

**Code snippets**
```
{
  "host": "${process.env.HOST || '0.0.0.0'}",
  "port": "${process.env.PORT || 1337}",
  "production": true,
  "proxy": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false
  }
}
```

**System**

- Node.js version: v12.13.0
- NPM version: 6.14.1
- Strapi version: 3.0.0-beta.20
- Database: Mysql
- Operating system: OSX/Linux

**Additional context**

**Comment by derrickmehaffy** [comment] 2020-04-26 17:23
Please clarify which version not just "latest" `Strapi version: latest beta`

**Comment by bluehawk27** [comment] 2020-04-26 22:07
@derrickmehaffy updated

**Comment by lauriejim** [comment] 2020-04-28 08:28
Hello! Can you precise the steps to reproduce.
Because I'm not sure to understand what you did before `NODE_ENV=production npm run start`

**Comment by bluehawk27** [comment] 2020-04-28 19:24
@lauriejim `yarn create strapi-app my-project` then filled in the db options and then the build script and start with the node_env set

**Comment by cuongphamcxa** [comment] 2020-04-29 10:10
Hi, I got the same issue. Any updates on this

**Comment by derrickmehaffy** [comment] 2020-05-07 14:13
This should be fixed in the next major version (beta.21) when the new changes to the config structure are released

**Comment by lauriejim** [comment] 2020-05-13 16:16
OKay thank you for this detail.

**Comment by derrickmehaffy** [comment] 2020-05-14 06:46
I'll update to say that it's already fixed in rc.0 and next.57 (what will be rc.1)

**Comment by baumannalexj** [comment] 2020-06-05 17:23
@derrickmehaffy -- I do not see this working in the 3.0.1 release. 

there is no visible difference between `autoOpen` =true or =false

**Comment by lauriejim** [comment] 2020-06-11 12:40
Hello here is the code that manage the opening of the browser - [code](https://github.com/strapi/strapi/blob/4a6ef4120124d77310e2540bf2056019b6c8889f/packages/strapi/lib/Strapi.js#L204)

We can see the option `autoOpen` is well used.
But in the case that the project is `isInitialised` (meaning that you are starting your app for the fist time) the admin will open in any case. Event the `autoOpen` is set to false.

This is the attempted behavior for now.

What is your use case for that?

**Comment by derrickmehaffy** [comment] 2020-10-22 18:02
Marking as closed as no discussion on this for the past few months

**Closed by derrickmehaffy** 2020-10-22 18:02 UTC
Labels: type: discussion

**Comment by jzsn2018** [comment] 2021-06-12 03:52
Hi, I got the same issue. Any updates on this

**Comment by Shingaz** [comment] 2021-06-14 21:55
Same issue here.

**Comment by Dmitry1987** [comment] 2021-11-25 20:18
Similar issue, the CMS container I deploy gets stuck at ```info ⏳ Opening the admin panel...```
is it an expected behavior? the autoOpen=false doesn't fix it. How can we make it just start serving the admin panel on the port, and not try to open it? nothing gets served on the port :(

**Comment by jvdbrink-netpulse** [comment] 2022-02-27 13:38
> 

Still an issue in 2022

**Comment by jvdbrink-netpulse** [comment] 2022-02-27 18:30
> > 
> 
> Still an issue in 2022

As it turns out I was missing the network option in my docker-compose file. So strapi was unreachable, the info message was normal behaviour.
