### ISSUE TITLE
strapi yarn2 failed with Can't resolve 'strapi-helper-plugin'

### ISSUE THREAD

**Issue by wenerme** [strapi/strapi#6495] opened 2020-06-01 16:44 UTC
**Describe the bug**

yarn2 develop failed

**Steps to reproduce the behavior**

```bash
yarn create strapi-app my-strapi --quickstart
cd my-strapi
yarn set version berry
yarn

yarn develop
```

```
$ yarn develop
(node:20146) [MODULE_NOT_FOUND] Error: debug tried to access supports-color (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
(node:20146) [MODULE_NOT_FOUND] Error: node-fetch tried to access encoding, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:20148) [MODULE_NOT_FOUND] Error: promise-inflight tried to access bluebird, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:20148) [MODULE_NOT_FOUND] Error: strapi-admin tried to access object-assign, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:20148) [MODULE_NOT_FOUND] Error: strapi-admin tried to access whatwg-fetch, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:20148) [MODULE_NOT_FOUND] Error: debug tried to access supports-color (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
Building your admin UI with development configuration ...

● Webpack █████████████████████████ building (70%) 87/99 modules 12 active
 babel-loader › .cache/admin/src/containers/NotificationProvider/actions.js

Error: Module not found: Error: Can't resolve 'strapi-helper-plugin' in '/temp/next/my-strapi/.cache/admin/src'
    at /temp/next/my-strapi/.yarn/cache/strapi-admin-npm-3.0.1-445e2a90e6-3.zip/node_modules/strapi-admin/index.js:67:23
    at finalCallback (/temp/next/my-strapi/.yarn/cache/webpack-npm-4.43.0-06b502aafb-3.zip/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/temp/next/my-strapi/.yarn/cache/webpack-npm-4.43.0-06b502aafb-3.zip/node_modules/webpack/lib/Compiler.js:265:20)
    at /temp/next/my-strapi/.yarn/cache/webpack-npm-4.43.0-06b502aafb-3.zip/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/temp/next/my-strapi/.yarn/cache/tapable-npm-1.1.3-5d1594602f-3.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /temp/next/my-strapi/.yarn/cache/webpack-npm-4.43.0-06b502aafb-3.zip/node_modules/webpack/lib/Compilation.js:1173:13
    at /temp/next/my-strapi/.yarn/cache/webpack-npm-4.43.0-06b502aafb-3.zip/node_modules/webpack/lib/Compilation.js:1096:25
    at /temp/next/my-strapi/.yarn/cache/webpack-npm-4.43.0-06b502aafb-3.zip/node_modules/webpack/lib/Compilation.js:1017:13
    at /temp/next/my-strapi/.yarn/cache/neo-async-npm-2.6.1-efc21b0f01-3.zip/node_modules/neo-async/async.js:2830:7
    at /temp/next/my-strapi/.yarn/cache/neo-async-npm-2.6.1-efc21b0f01-3.zip/node_modules/neo-async/async.js:2830:7
    at done (/temp/next/my-strapi/.yarn/cache/neo-async-npm-2.6.1-efc21b0f01-3.zip/node_modules/neo-async/async.js:2863:11)
    at /temp/next/my-strapi/.yarn/cache/neo-async-npm-2.6.1-efc21b0f01-3.zip/node_modules/neo-async/async.js:2818:7
    at errorAndCallback (/temp/next/my-strapi/.yarn/cache/webpack-npm-4.43.0-06b502aafb-3.zip/node_modules/webpack/lib/Compilation.js:883:7)
    at errorOrWarningAndCallback (/temp/next/my-strapi/.yarn/cache/webpack-npm-4.43.0-06b502aafb-3.zip/node_modules/webpack/lib/Compilation.js:918:17)
    at /temp/next/my-strapi/.yarn/cache/webpack-npm-4.43.0-06b502aafb-3.zip/node_modules/webpack/lib/Compilation.js:924:16
    at /temp/next/my-strapi/.yarn/cache/webpack-npm-4.43.0-06b502aafb-3.zip/node_modules/webpack/lib/NormalModuleFactory.js:401:22
```

**Expected behavior**
success

**System**

- Node.js version: v12.14.1
- NPM version: v6.14.5
- Strapi version: 3.0.1
- Database:
- Operating system: macos

**Additional context**

**Comment by derrickmehaffy** [comment] 2020-06-01 18:08
Moving this to a discussion as it's not a bug with Strapi but an issue with user environment.

**Closed by derrickmehaffy** 2020-06-01 18:08 UTC
