### ISSUE TITLE
Weird error when there is a field with name `key` in any content type

### ISSUE THREAD

**Issue by dzcpy** [strapi/strapi#12591] opened 2022-02-18 18:21 UTC
### Describe the bug

When there is a field with the name of `key`, it will create an error when you try to get a list of content of this type.

### Steps to reproduce the behavior

1. Go to content type builder, create a content type, add any fields named with `key`
2. Go to content manager, click the content type that has just been created
3. Check error messages

### Expected behavior

A content type should allow fields with any name. Or at least throw an error message when user tries to name it with reserved keywords.

### Screenshots

![image](https://user-images.githubusercontent.com/203980/154740437-1cbb4d47-4fac-40cb-9f1f-72277b217f11.png)

![image](https://user-images.githubusercontent.com/203980/154740391-0d02db11-fbaa-46b0-aed4-d8739a1b5b4b.png)
![image](https://user-images.githubusercontent.com/203980/154740552-0ffe36ce-b120-4ca9-b135-fada3d95458c.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 16.x 
- NPM version: 
- Strapi version: 4.0.8 
- Database: PostgreSQL
- Operating system: Windows 10

**Comment by kasonde** [comment] 2022-02-22 07:50
Please update your issue to fill in the rest of your System information

**Comment by dzcpy** [comment] 2022-02-22 07:57
> Please update your issue to fill in the rest of your System information

Updated, is that because of PostgreSQL?

**Comment by kasonde** [comment] 2022-02-22 13:37
> > Please update your issue to fill in the rest of your System information
> 
> Updated, is that because of PostgreSQL?

I'd have to verify that and share what we find. As of yet, I'm not too sure.

**Comment by KimmoHernborg** [comment] 2022-02-23 17:14
I have the same issue, with a field with the name of `key` - but I am using Sqlite, so probably not the database that is the issue. I only have issues on /api/ and when getting the results with filters. Changing the name of the field to something else fixed the issue.

This seems like a recent issue, since it started when I upgraded Strapi from 4.0.7 to 4.1.0.

**Comment by rassin04** [comment] 2022-02-25 05:56
Looks like this is an issue with the error in code at
 `node_modules/@strapi/utils/lib/convert-query-params.js => convertAndSanitizeFilters()` line number 253
 where I believe it should be
`const attribute = get(key, schema.attributes);` instead of `const attribute = get('key', schema.attributes);`

**Comment by kasonde** [comment] 2022-03-02 21:37
Duplicate of #12569

**Closed by kasonde** 2022-03-02 21:37 UTC
Labels: source: core:admin, status: pending reproduction
