### ISSUE TITLE
Tracking Issue: Allow filter on null for relations

### ISSUE THREAD

**Issue by uguptu** [strapi/strapi#5414] opened 2020-03-04 18:03 UTC
# Edited by @derrickmehaffy 

Hijacking this issue and setting it as a tracking issue for anything related to filtering on `_null` for relational fields or any field that doesn't work with the `_null` filter.

We are aware of this issue, and it should be addressed in our upcoming Strapi v4. We will not be back porting the fix to the v3 as we have almost entirely rewritten the database and query layers in the v4, which in doing so has already fixed this issue.

For more information about the v4 see: https://strapi.io/v4

---

Strapi GraphQL plugin provides automatically generated query types for every content type, and they contain `where` parameter. If there is a filter `where: { field: $value }`, and $value is set to `null`, the filter is ignored. There is also a filter `where: { field_null: true }`, which would be useful to use to check if certain relation is not set. But this filter doesn't work with relations, and when `field_null: true`, filter is ignored.

**Steps to reproduce the behavior**
1. Create a content type Child 
    ```
    type ChildType {
        id: ID!
        name: String 
        sex: String
    }
    ```
2. Create a content type Parent with a relation to many Child instances
    ```
    type ParentType {
        id: ID!
        name: String 
        children: [ChildType]
    }
    ```
3. Strapi will automatically create query types 
    ```
    parents(
        sort: String
        limit: Int
        start: Int
        where: JSON
    ): [ParentType]

    children(
        sort: String
        limit: Int
        start: Int
        where: JSON
    ): [ChildType]
    ```
4. Create Child1, Child2, Parent1 with relations to Child1 and Child2, Parent2 without any Child relations
5. Try to query in GraphQL:
    ```
    query1 {
        parentsWithSons: parents(where: { children: { sex: 'male' } }) {
            name
            children {
                name
                sex
            }
        }
    }

    query2 {
        childlessParents: parents(where: { children: null }) {
            name
            children {
                name
                sex
            }
        }
    }

    query3 {
        childlessParents: parents(where: { children_null: true }) {
            name
            children {
                name
                sex
            }
        }
    }    ```
6. Observe that first query works as expected, while query 2 and 3 return ALL parents

**Expected behavior**
First query should return all parents who has sons.
Second query should return all parents, as setting `null` to a filter should still skip the filter
Third query should return NO parents, as it explicitly set to return items with children === null.

**System**
- Node.js version: 12
- NPM version: any
- Strapi version: beta.18.8, beta.19
- Database: MongoDB
- Operating system: Alpine Linux in Docker

**Comment by derrickmehaffy** [comment] 2020-03-04 18:19
I can confirm this on beta.19.1 null filter does not work on relations (maybe only some?) guessing it has to do with joins in the backend

**Comment by tylerforesthauser** [comment] 2021-01-12 20:40
I'm rather surprised this hasn't been addressed yet...

**Comment by derrickmehaffy** [comment] 2021-01-16 19:10
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/filter-where-field-null-true-not-working-in-graphql/2213/2

**Comment by tylerforesthauser** [comment] 2021-01-16 19:32
@derrickmehaffy Unfortunately all it does is describe the bug perfectly and then provides a link to this issue...

**Comment by derrickmehaffy** [comment] 2021-01-16 21:37
> @derrickmehaffy Unfortunately all it does is describe the bug perfectly and then provides a link to this issue...

That's a bot that just uses my name, anytime a github issue is linked in a forum thread it auto links here.

**Comment by tylerforesthauser** [comment] 2021-01-16 22:17
Ahhhhh that makes all of the sense. Sorry for the ping

**Comment by ngohuynhngockhanh** [comment] 2021-01-27 05:18
Hi, i found the bug.
The bug is only appears on version 3.4.x. 
Because when strapi makes a query with null filter on relation field, it add published condition to the raw sql. You can add this code in function find in (strapi-connector-bookshelf/lib/queries.js) to see the raw sql.
```
.query(function(qb) {
	qb.debug(true);
})

```
To hot fix this issue, we just switch off the draft system. 
![Strapi - Content Type Builder - Google Chrome](https://user-images.githubusercontent.com/5621213/105946177-50652200-6099-11eb-9ab1-4152413ff4e9.jpg)

I hope strapi team will make a patch for this bug soon. 

p/s:
Without draft system in null query
![OpenSSH SSH client](https://user-images.githubusercontent.com/5621213/105946253-7c80a300-6099-11eb-9ad3-4dafad0dd259.jpg)

With draft system in null query
![OpenSSH SSH client 2_2](https://user-images.githubusercontent.com/5621213/105946394-c5d0f280-6099-11eb-9bc1-bf9a52f509b7.jpg)

**Comment by jtan-devicebits** [comment] 2021-03-22 08:18
this issue still occurred on the current Strapi version v3.5.2

**Comment by jmezzacappa** [comment] 2021-05-29 22:34
This issue is still around in v3.6.2.
Doesn't this seem to fit more of a "type: bug" label than a "type: enhancement" label?

**Comment by jovenntann** [comment] 2021-05-31 13:01
> This issue is still around in v3.6.2.
> Doesn't this seem to fit more of a "type: bug" label than a "type: enhancement" label?

Agree this should be label as bug

**Comment by ico85** [comment] 2021-08-29 21:07
Yes definitely a bug.

**Comment by derrickmehaffy** [comment] 2021-08-30 21:46
I've converted this issue to a global tracking issue.

**Comment by derrickmehaffy** [comment] 2021-11-30 14:11
Fixed in v4, marking as closed

**Closed by derrickmehaffy** 2021-11-30 14:11 UTC
Labels: type: bug, severity: medium, status: confirmed, source: core:database
