### ISSUE TITLE
Strapi create new field instead of updating the existing one

### ISSUE THREAD

**Issue by SorinGFS** [strapi/strapi#8083] opened 2020-09-28 17:32 UTC
**Describe the bug**
Trying to rename a field ended up by creating a new field with no data in it

**Steps to reproduce the behavior**

1. Go to `Admin Panel`
2. Click on `Content-Type Builder`
3. Click on `Collection Type -> User`
4. Click on `+Add a new field to this collection type` (to obtain an editable field to test)
5. Select `field TEXT` and Type the field name: `Audience`, then Finish + Save
6. Now let's put some data in the new field for a given user: `Content type -> Users -> Select an user to edit -> add some text in the newly created field`, then `SAVE`. Now if we check the database everything is as espected. 
7. Let's try to edit the newly created field name:  repeat the steps 2 and 3, then click on icon `edit this field` (Audience).
8. Change the name from `Audience` to `audience`, then `SAVE`
9. Now, if you check the data you entered in the `step 6` there is no data, instead if you check the database there you can see that the old field **was not edited, but instead was created a new field with no data!**

**Expected behavior**
Edit means **edit**, not **replace with a new empty field**

**System**

- Node.js version: Node LTS version (v12) 
- Strapi version: 3.1.6
- Database: mongoDb latest
- Operating system: windows

**Comment by derrickmehaffy** [comment] 2020-09-28 17:32
Duplicate of #1114

**Closed by derrickmehaffy** 2020-09-28 17:32 UTC
Labels: status: duplicate

**Comment by SorinGFS** [comment] 2020-09-28 17:35
@derrickmehaffy Not quite the same Derrick, I don't try to delete anything, just to update existing field.

**Comment by SorinGFS** [comment] 2020-09-28 17:46
![Untitled](https://user-images.githubusercontent.com/25417015/94467453-abf6d000-01cb-11eb-92d1-cf6e657eea11.png)

**Comment by derrickmehaffy** [comment] 2020-09-28 17:49
The same applies to updates @SorinGFS see: https://github.com/strapi/strapi/issues/1114#issuecomment-426757844

**Comment by SorinGFS** [comment] 2020-09-28 18:03
@derrickmehaffy If so, that is a **BIG** mistake! As I know databases have the functionality to safely rename fields without "migrating data". For example [rename fields in mongoDb](https://docs.mongodb.com/manual/reference/operator/update/rename/)

**Comment by derrickmehaffy** [comment] 2020-09-28 18:16
> @derrickmehaffy If so, that is a **BIG** mistake! As I know databases have the functionality to safely rename fields without "migrating data". For example [rename fields in mongoDb](https://docs.mongodb.com/manual/reference/operator/update/rename/)

You are correct but we have to handle **all** of our supported databases and ensuring that migration is properly handled on all of them. When we develop/build features we do so at an equal level. We have a planned database refresh for Q4: https://portal.productboard.com/strapi/1-roadmap/c/73-database-layer-v4

But not all databases support just a simple rename (SQLite) though most do (Mongo, PostgreSQL, MariaDB, and MySQL) it's more a matter of properly handling the migration process and due to how our framework functions, when to execute these changes and mitigate any possible data loss/proper rollback if an error happens.

**Comment by derrickmehaffy** [comment] 2020-09-28 18:16
We are well aware of the information required as stated on the linked issue, for now I'm going to lock this as we have already explored this in depth and are currently working on plans internally. When we have more information to share, or require more information we will let the community know.
