### ISSUE TITLE
nx run @strapi/plugin-i18n:build error

### ISSUE THREAD

**Issue by xtuyaowu** [strapi/strapi#20166] opened 2024-04-21 08:23 UTC
## Bug report
yarn build fail
nx run @strapi/plugin-i18n:build
### Required System information

- Node.js version:v20.12.2
- NPM version:4.0.1
- Strapi version:v5.0.0-beta.4
- Database: sqlite
- Operating system:ubuntu22
- Is your project Javascript or Typescript:Typescript

### Steps to reproduce the behavior

git clone git clone https://github.com/strapi/strapi.git
cd strapi
git checkout v5.0.0-beta.4
yarn install
yarn build

### Expected behavior

build success

### Screenshots

![1](https://github.com/strapi/strapi/assets/20146795/408ff6ca-edb9-48b8-b452-9a69ef57bb6b)
![2](https://github.com/strapi/strapi/assets/20146795/2c62e615-775e-4a8d-92ef-1967aace8bcb)

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment] 2024-04-22 17:30
What are you trying to do?

**Comment by derrickmehaffy** [comment] 2024-04-24 17:24
Can't reproduce with the `v5/main` as of today, steps I took:

- Clone repo: `git clone git@github.com:strapi/strapi.git --branch v5/main strapi-v5`
- Install packages `yarn`
- Run setup `yarn setup`
- Change to example project `cd examples/gettingstarted`
- Start the example project: `yarn develop`

Marking as closed

**Closed by derrickmehaffy** 2024-04-24 17:24 UTC
Labels: issue: bug, severity: low, source: tooling, status: pending reproduction, version: 5
