### ISSUE TITLE
Media Library changes file extension to .bin

### ISSUE THREAD

**Issue by chaitanyya** [strapi/strapi#6872] opened 2020-06-30 17:50 UTC
**Bug Description:**

After the update to v3.0.5 I see all our` .GP` file uploads are converted to `.BIN` files. The file content is unchanged and I'm able to make it work after manually updating the file back to `.GP`. I'm using S3 provider with production built. Not sure if this is limited to only this filetype but I did some rough testing with other file types like `.CSV` but couldn't reproduce.

**Steps to reproduce the behavior:**

1. Go to Media Library
2. Click on Upload Assets
3. Pick a `.GP` file from local system. 
4. Wait for the file to finish uploading.
5. The file type is changed to `.BIN`

**Expected Behavior:**

The Media Library should not later the file type of the provided files for upload.

**Screenshots:**

<img width="268" alt="GP File Upload Example" src="https://user-images.githubusercontent.com/13115490/86159370-da5f0380-bb27-11ea-9a4b-2946d747abbb.png">

**System:**

**- Node.js version:** 12.13.0
**- Yarn version:** 1.19.1
**- Strapi version:** v3.0.5
**- Database:** Postgres
**- Operating system:** Amazon Linux

**Comment by Trireir** [comment] 2020-07-01 11:09
I had the same issue, but it seems that it's already fixed in master right now, should be available in the next release.

The problem was that the [strapi-plugin-upload](https://github.com/strapi/strapi/blob/v3.0.5/packages/strapi-plugin-upload/services/Upload.js#L46) retrieved the extension of the file from the mimetype. Those kind of files doesn't have an specific one, so they have the default application/octet-stream, that it's converted to a .bin file extension.

**Comment by Trireir** [comment] 2020-07-09 11:45
I did this fork in the meantime. You can use it like this in your package.json:
`"strapi-plugin-upload": "https://github.com/Trireir/strapi.git",`
But I'll remove it as soon as the new version of strapi come out :)

**Comment by petersg83** [comment] 2020-08-04 09:16
Hi, thanks for your issue!
I can confirm it wasn't working with 3.0.5 and that it works now with the latest version :)
I close the issue since the bug has been fixed

**Closed by petersg83** 2020-08-04 09:16 UTC
