### ISSUE TITLE
Unable to use strapi.query in strapi console

### ISSUE THREAD

**Issue by rvigneshw** [strapi/strapi#8330] opened 2020-10-14 11:23 UTC
**Describe the bug**
Unable to use strapi.query in strapi console(It says 

**Steps to reproduce the behavior**

strapi console
type `const result = await strapi.query("notification").model.find();`

**Expected behavior**
Output of data

**actual OP**
const result = await strapi.query("notification").model.find();
               ^^^^^

Uncaught SyntaxError: await is only valid in async function

**Comment by alexandrebodin** [comment] 2020-10-14 11:47
Hello, you just can't use await at the top level of a module or in the console. you can just use then to get the data or wrap it in an async function first :)

check this for more details https://github.com/tc39/proposal-top-level-await

Closing as it is not a bug

**Closed by alexandrebodin** 2020-10-14 11:47 UTC
