### ISSUE TITLE
Admin Panel not accessible

### ISSUE THREAD

**Issue by Bendrog** [strapi/strapi#6892] opened 2020-07-02 16:36 UTC
**Describe the bug**

When going to `/admin/auth/local` and validating my credentials, the Admin panel won't open.

I get a `forbidden 403` such as shwoun bellow

**Console**
```cmd
Welcome back!
To manage your project �, go to the administration panel at:
http://localhost:1337/admin

To access the server ⚡️, go to:
http://localhost:1337

[2020-07-02T15:48:38.864Z] debug GET /admin (15 ms) 200
[2020-07-02T15:48:38.901Z] debug GET main.88a19c2e.chunk.js (12 ms) 200
[2020-07-02T15:48:38.902Z] debug GET runtime~main.57681402.js (4 ms) 200
[2020-07-02T15:48:39.583Z] debug GET /favicon.ico (0 ms) 200
[2020-07-02T15:48:39.971Z] debug GET /users-permissions/init (90 ms) 200
[2020-07-02T15:48:39.990Z] debug GET /admin/init (2 ms) 200
[2020-07-02T15:48:40.301Z] debug GET /content-manager/content-types (200 ms) 403
[2020-07-02T15:48:40.320Z] debug GET /content-manager/content-types (193 ms) 403
```

**Steps to reproduce the behavior**

This probably comes from the fact that I "played" with the plugins.

I took most of `config` & `controllers` from [This repo](https://github.com/larsgroeber/riedbergtv/tree/e925058d561772ff183ca4d9740384d94203b22a/rtv-backend/plugins/users-permissions)

**System**

- Node.js version: 12.16.2
- NPM version: 16.14.4
- Strapi version: 3.0.2
- Database: PgAdmin 12
- Operating system: Win 10

**Comment by derrickmehaffy** [comment] 2020-07-03 11:02
Considering those haven't been updated in over a year, yes the issue is with using those controllers. I'm marking this as closed as it's not a bug.

**Closed by derrickmehaffy** 2020-07-03 11:02 UTC
