### ISSUE TITLE
Can't create a new Strapi project using docker using v3.0.0-beta.19.4 release

### ISSUE THREAD

**Issue by devpaulomarques** [strapi/strapi#5662] opened 2020-03-31 15:33 UTC
When I tried to get the last release and update my current project, I got an error ERR_EMPTY_RESPONSE when consuming any service or just trying to access the admin panel, so I decided to try to create a new project and also doesn't work.

**Steps to reproduce the behavior**
follow step by step from here [Installing using Docker
](https://strapi.io/documentation/3.0.0-beta.x/installation/docker.html)

**System**
- Node.js version: 12.13.0
- NPM version: 6.9.0
- Strapi version: v3.0.0-beta.19.4
- Database: MongoDB
- Operating system: Catalina 10.15.4
- Docker: 19.03.8

**Additional context**
I've tried to another clean machine without any other image or previous usage to development and got the same behavior

**Comment by alexandrebodin** [comment] 2020-03-31 15:37
Hi, this is a Duplicate of #https://github.com/strapi/strapi-docker/issues/191

**Closed by alexandrebodin** 2020-03-31 15:37 UTC
