### ISSUE TITLE
v5: It does not allow to select multiples images in field: multiple media

### ISSUE THREAD

**Issue by damoclesgil** [strapi/strapi#20241] opened 2024-05-01 17:17 UTC
## Bug report

Required System information
Environment: development
OS: Windows Pro
Strapi Version: 5.0.0-beta.5
Node: v20.10.0
Npm: v10.5.2
Edition: Community
Database: postgres
Typescript

## Describe the bug
It does not allow you to select more than one image when registering.

## Steps to reproduce the behavior
Go to the Content-Type Build. Add another field > Select field media and select type: **multiple media**.
Go to the Content Manager. Try select more than one image to the field **multiple media**

## Expected behavior
It would be expected the strapi would allow you to select more than one image in the gallery.

## Screenshots

![input_type_multiple_media](https://github.com/strapi/strapi/assets/14218789/ca5247b1-ac6a-40aa-b9bd-80ae3c997612)

![nao_consigo_marcar_mais_um](https://github.com/strapi/strapi/assets/14218789/38ac13aa-b5bd-4fa7-94ef-2d8094784425)

**Comment by alexandrebodin** [comment] 2024-06-06 09:25
Closing, duplicate of https://github.com/strapi/strapi/issues/20083

**Closed by alexandrebodin** 2024-06-06 09:25 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-manager, source: core:content-type-builder, version: 5
