### ISSUE TITLE
Integer fields let save float values but fails when queried

### ISSUE THREAD

**Issue by Blacknosaur** [strapi/strapi#2502] opened 2018-12-17 15:27 UTC
**Informations**
- **Node.js version**: v10.12.0npm
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.16 (I have also tried in 3.0.0-alpha.14.2)
- **Database**: MongoDB (mLab)
- **Operating system**: Ubuntu 18.04.1 LTS 

**What is the current behavior?**
If you define a content type with a integer field and you save an entry with an float value in this field, it does not fail. If you try to query this integer field via GraphQL, it will return null with an error similar to these one

```
{
  "errors": [
    {
      "message": "Int cannot represent non-integer value: 1.1",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "qwes",
        0,
        "qqq"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Int cannot represent non-integer value: 1.1",
            "    at GraphQLScalarType.serializeInt [as serialize] (/home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/type/scalars.js:49:11)",
            "    at completeLeafValue (/home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/execution/execute.js:641:37)",
            "    at completeValue (/home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/execution/execute.js:587:12)",
            "    at completeValueCatchingError (/home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/execution/execute.js:503:19)",
            "    at resolveField (/home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/execution/execute.js:447:10)",
            "    at executeFields (/home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/execution/execute.js:293:18)",
            "    at collectAndExecuteSubfields (/home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/execution/execute.js:717:10)",
            "    at completeObjectValue (/home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/execution/execute.js:707:10)",
            "    at completeValue (/home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/execution/execute.js:598:12)",
            "    at completeValueCatchingError (/home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/execution/execute.js:503:19)",
            "    at /home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/execution/execute.js:623:25",
            "    at Array.forEach (<anonymous>)",
            "    at forEach (/home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/iterall/index.js:83:25)",
            "    at completeListValue (/home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/execution/execute.js:619:24)",
            "    at completeValue (/home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/execution/execute.js:581:12)",
            "    at /home/ec2-user/environment/cet/api-migrando/plugins/graphql/node_modules/graphql/execution/execute.js:500:16",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": {
    "qwes": [
      {
        "_id": "5c17b766bd23624788637290",
        "qqq": null
      }
    ]
  }
}
```

**Steps to reproduce the problem**
Create a model with an integer field, save an entry putting a decimal into this integer field and query it with GraphQL

**What is the expected behavior?**
It should fail when you try to save the entry with an incorrect data type, not when you query it.

**Suggested solutions**
I don't know how is the validation implemented but it should
 check if the value is an integer as well as if it's a number

**Comment by derrickmehaffy** [comment] 2018-12-17 16:04
There is no validation layer in strapi yet: https://portal.productboard.com/strapi/c/14-validations

For now there really isn't an easy fix for this. The error in GraphQL is like you said, a non-int in an int field. It's an upstream error.

I'm marking this issue as a duplicate of the validations feature request, it is a feature that doesn't currently exist but is planned. If you feel this was closed in error please let me or one of the Strapi team know and we can look at re-opening it.

**Closed by derrickmehaffy** 2018-12-17 16:04 UTC
