### ISSUE TITLE
"This provider is disabled" When using a provider 

### ISSUE THREAD

**Issue by sylver-john** [strapi/strapi#6323] opened 2020-05-22 13:52 UTC
Hi,

i'm trying to setup oauth connection with Google as provider

1. Follow Strapi documentation about provider => setting Google as oauth provider
2. From my Front-app, calling GET "http://localhost:3002/connect/google"
3. See error "{"statusCode":400,"error":"Bad Request","message":"This provider is disabled.","data":"This provider is disabled."}"

When looking into the plugin strapi-plugin-users-permissions in file "controllers/Auth.js" line 258 : 

![image](https://user-images.githubusercontent.com/6161547/82674549-c4fedb80-9c43-11ea-8532-ea647f217be2.png)

`requestPath.split('\\')[2]` return undefined
`requestPath.split('/')[2]` return the right value but not used since `process.platform` return `win32`

**System**

- Node.js version: 12.16.3
- NPM version: 6.14.4
- Strapi version: 20.1
- Database: SQlite
- Operating system: Windows 10

Should I provide a PR to fix this ?

Regards

**Comment by bglidwell** [comment] 2020-05-25 01:51
This fixed the issue for me as well. Please provide a PR so this gets merged in.

**Comment by lauriejim** [comment] 2020-05-28 13:40
This is a duplicate of this issue - https://github.com/strapi/strapi/issues/6089

Please submit a PR to fix this. I will appreciate your contribution to this issue.
Thank you :)

**Closed by lauriejim** 2020-05-28 13:40 UTC
Labels: good first issue, priority: medium, source: plugin:users-permissions, type: bug
