### ISSUE TITLE
Can't edit CRUD permission on field level

### ISSUE THREAD

**Issue by Jessinra** [strapi/strapi#8321] opened 2020-10-13 15:05 UTC
**Describe the bug**
Hello, I can't seem to change CRUD permission for each field in a collection type or singular type.

**Steps to reproduce the behaviour**

1. See under 'general' section, 
2. Open setting > permission > role > edit role (choose editor / secondary admin role)
3. Click on any type of collection type 

**Expected behaviour**
User can choose to enable each C R U permission separately for each field
I assume this should work since for each field, there's a separate checkbox

**Screenshots**
![Screenshot from 2020-10-13 21-48-13](https://user-images.githubusercontent.com/32489864/95878858-e18ce300-0d9f-11eb-80a7-7624e4e8c36d.png)

**System**

- Node.js version: v14.3.0
- NPM version: v6.14.5
- Strapi version: 3.1.4
- Database: postgres
- Operating system: linux 18.04

Really appreciate if I can get quick updates on this, thank you very much in advances

**Comment by derrickmehaffy** [comment] 2020-10-13 17:58
@Jessinra as I mentioned on the other issue, specific action control (Advanced field level permissions) only applies to the EE (Enterprise Edition) and is not an option within the CE (Community Edition).

With the CE you can only enable/disable fields themselves, control over actions and specific policies can only be used with an EE license.

See the pricing information: https://strapi.io/pricing

I'm going to mark this as closed as it's not a bug but please feel free to reply back if you have questions.

**Closed by derrickmehaffy** 2020-10-13 17:58 UTC

**Comment by MattieBelt** [comment] 2020-10-13 19:19
Linking [#8270 (comment)](https://github.com/strapi/strapi/issues/8270#issuecomment-707127808) as this explains a bit more.
