### ISSUE TITLE
duplicate button edits the clicked content when there is a horizontal scrollbar in table. 

### ISSUE THREAD

**Issue by Seyolas** [strapi/strapi#18281] opened 2023-10-04 09:01 UTC
- Node.js version: 18.14.2
- NPM version: 9.5.0
- Strapi version:4.12.5
- Database:postgres
- Operating system: windows
- Is your project Javascript or Typescript: js

### Describe the bug

Clicking duplicate button edits the current content. I have different types of collection types and the issues is same for all. 
**Please note that. It's happening only when there is a horizontal scrollbar in table. It works fine when there is no horizontal scrollbar in table.**  

Also, except strapi's default dependecies i had just installed "@_sh/strapi-plugin-ckeditor": "^1.1.3" as a plugin. 

[screen-capture (2).webm](https://github.com/strapi/strapi/assets/39236950/3e3525bb-9532-426f-812f-d514d5e703d5)

### Expected behavior

when clicking the duplicate button it should create a new entry with filled inputs.

**Comment by joshuaellis** [comment] 2023-10-04 09:22
duplicate of #17880 please check other issues before you open them

**Closed by joshuaellis** 2023-10-04 09:22 UTC
Labels: status: duplicate

**Comment by Seyolas** [comment] 2023-10-04 09:50
> duplicate of #17880 please check other issues before you open them

I did actullay but i searched as "duplicate button issue/bug" 
thanks
