### ISSUE TITLE
User update now requires email & password in body

### ISSUE THREAD

**Issue by Vincent-Loi** [strapi/strapi#3959] opened 2019-09-11 09:07 UTC
**Describe the bug**
After updating to 3.0.0-beta16, the update User endpoint now requires `email`, `username`, `password` in the body.

Note: If this is not intended, I believe it should take these fields from `ctx.state.user` rather than `ctx.request.body`.

eg:  
Replace ```const { email, username, password } = ctx.request.body;``` with   
```const { email, username, password } = ctx.state.user;```

Let me know if you would like a Pull Request 👍 

**Steps to reproduce the behavior**
1. Make PUT request to /users/:id
2. Update any field in the User model

**Expected behavior**
Able to update the field.

**Code snippets**
```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "missing.email"
}
```

**System**
- Node.js version: v10.16.3
- NPM version: 6.11.3
- Strapi version: 3.0.0-beta16
- Database: MongoDB
- Operating system: macOS

**Comment by alexandrebodin** [comment] 2019-09-11 09:10
Hi @Vincent-Loi,

This is the intended behaviour. This route is made to update any user not the one connected :) Closing this issue as it is not a bug

**Comment by derrickmehaffy** [comment] 2019-09-11 09:22
@alexandrebodin I disagree with this.

If I have something like a user's address that needs to be updated I have to send their password? That seems highly insecure that I would even have access to that?

And if this is intended that password would be required then we need a PUT `/users/me`

**Comment by alexandrebodin** [comment] 2019-09-11 09:26
this is a legacy issue that makes it necessary for the admin panel to work. I agree the password shouldn't be required. 

The point is mostly that is route isn't to update the connected user in ctx.state.user

**Comment by derrickmehaffy** [comment] 2019-09-11 09:27
> this is a legacy issue that makes it necessary for the admin panel to work. I agree the password shouldn't be required.
> 
> The point is mostly that is route isn't to update the connected user in ctx.state.user

That's totally fine but an alternative needs to be made before this is done.

**Comment by alexandrebodin** [comment] 2019-09-11 09:29
@Vincent-Loi you can make a PR to allow some optional fields. but still shouldn't use the ctx.state.user

**Comment by Vincent-Loi** [comment] 2019-09-11 09:44
@alexandrebodin Right - it's a bit of an inconvenience as I'm using this on the client-side and good practice not to store passwords. For now, I have to override this with an extension.

I'm not familiar on exactly how the admin UI interacts with this API but generally looking, password should definitely be optional, and only either username or email should be needed. Does that sound good?

**Comment by alexandrebodin** [comment] 2019-09-11 09:47
@Vincent-Loi you could even send an empty object tbh. Just make sure to keep the user email / username checks for duplicates ;)

**Comment by barthicus** [comment] 2019-09-11 16:41
@Vincent-Loi I faced exactly the same problem after upgrading to beta 16.

I also didn't want to store user passwords in redux so I solved this by adding strapi User.js controller under `backend\extensions\users-permissions\controllers\User.js` and commenting out the line 175: `if (!password) return ctx.badRequest('missing.password');`.

This is not perfect because I have to send also username and email on every user data update but it is better for now than storing user passwords in frontend IMO.

**Comment by Vincent-Loi** [comment] 2019-09-11 16:52
@barthicus Yup that's also what I did except taking it from `ctx.state.user` to avoid changing the client-side.

I will make a PR request when possible with the changes @alexandrebodin proposed so you won't need to pass username or email either.

**Comment by Vincent-Loi** [comment] 2019-09-11 21:51
#3970

**Comment by alexandrebodin** [comment] 2019-09-18 12:08
Fix by https://github.com/strapi/strapi/pull/4040. Closing

**Closed by alexandrebodin** 2019-09-18 12:08 UTC
Labels: Good for new contributors, priority: high, status: confirmed, type: bug 🐛
