### ISSUE TITLE
Cannot read properties of null (reading 'schema')

### ISSUE THREAD

**Issue by arbenaziri** [strapi/strapi#22120] opened 2024-11-10 08:28 UTC
```
TypeError: Cannot read properties of null (reading 'schema')
    at FormModalHeader (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-MYWO5QRF.js?v=57be3818:5218:83)
    at renderWithHooks (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=57be3818:11568:26)
    at updateFunctionComponent (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=57be3818:14602:28)
    at beginWork (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=57be3818:15944:22)
    at beginWork$1 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=57be3818:19781:22)
    at performUnitOfWork (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=57be3818:19226:20)
    at workLoopSync (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=57be3818:19165:13)
    at renderRootSync (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=57be3818:19144:15)
    at recoverFromConcurrentError (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=57be3818:18764:28)
    at performSyncWorkOnRoot (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=57be3818:18907:28)
```

**Comment by leaHaimovich** [comment] 2024-11-13 14:25
Check for Initialization & Add a Null Check

**Comment by innerdvations** [comment] 2024-11-15 09:07
Duplicate of https://github.com/strapi/strapi/issues/21943

**Closed by innerdvations** 2024-11-15 09:07 UTC
