### ISSUE TITLE
The port 1337 is already used by another application

### ISSUE THREAD

**Issue by t1gu1** [strapi/strapi#3762] opened 2019-08-10 09:39 UTC
**Describe the bug**
 The port 1337 is already used by another application.

**Steps to reproduce the behavior**
1. Create a project
2. npm run develop

**Expected behavior**
Use a port that's not use.
Maybe in a first step we could just change the default port.

**Additional context**
Editable in `Project\config\environments\development\server.json`

**Comment by yassinebridi** [comment] 2019-08-10 14:02
You could either try to kill the opened port : sudo lsof -t -i:1337
or you could start the project with a different port: npm run develop -- -p 5000

**Comment by xargr** [comment] 2019-08-10 14:26
Or you can close the terminal and open it again

**Comment by gianfigueroa** [comment] 2019-08-12 02:45
sudo fuser -k 1337/tcp

**Comment by davidkartuzinski** [comment] 2019-08-12 08:46
>  you could start the project with a different port: npm run develop -- -p 5000

@yassinebridi - Hi. I was curious if you have read somewhere that `npm run develop -- -p 5000`, should work? 

This part of the docs, https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#configuration, explains how to set-up Strapi on a different port (in case of conflicts or other reasons).  

Thank you.

**Comment by derrickmehaffy** [comment] 2019-08-12 08:52
I am marking this issue as closed as it is not a bug with Strapi itself but the users environment. 

You are welcome to change the port used by strapi in the config path you found, this is also documented in the link that @davidkartuzinski gave.

Also in the future please be sure to completely fill out the bug report including the section templated as this:

```
**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:
```

**Closed by derrickmehaffy** 2019-08-12 08:52 UTC

**Comment by M-Tee** [comment] 2020-01-16 19:16
> sudo fuser -k 1337/tcp

This worked out for me.

**Comment by Ezra-Siton-UIX** [comment] 2020-02-04 13:07
Windows 10. Under:
`\my-project\config\environments\development`

I change her to `5000` - and the problem solved.

![image](https://user-images.githubusercontent.com/16711871/73747238-b3122f00-475f-11ea-9f6b-ddd17f734a73.png)

![image](https://user-images.githubusercontent.com/16711871/73747431-17cd8980-4760-11ea-9a11-dd81a78680d3.png)

**Comment by brianmhsu** [comment] 2022-01-14 07:15
In my case (Windows 10 + wsl2) is the "RzSDKService" using the 1337 port

1. Check if port 1337 used
    Run "Command Prompt" as admin `netstat -ab`
2. Check which PID is using port 1337
    Run "Command Prompt" as admin `netstat -ano | findstr :1337`
3. Find the process using the PID found from the last step, in "Task Manager"'s "Detail" tab by matching the PID
    In my case is the "RzSDKService"
4. Kill the PID (Strapi works after killing the PID and freeing up the port)
    Run "Command Prompt" as admin `taskkill /PID <PID> /F`
5. (Optional) Uninstall. Make sure you do not need the "Software" which uses up the 1337 port.
    In my case, the "RzSDKService" is inessential

Hope this helps someone
