### ISSUE TITLE
GraphQL plugin doesn't work if any model has a private relationship

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#2971] opened 2019-03-12 12:43 UTC
**Informations**
- **Node.js version**: v11.6.0
- **NPM version**: v6.9.0
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: MongoDB
- **Operating system**: macOS

**What is the current behavior?**

When I have any model with a private relationship, GraphQL plugin doesn't work.
Example (note the `"private": true`):
```
    "votes": {
      "collection": "vote",
      "via": "user",
      "private": true
    }
```

Error in the `strapi start`:

```
(node:5941) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at Object.isPrimitiveType (/Users/abdonrd/my-api/plugins/graphql/services/Aggregator.js:21:24)
    at Object.extractType (/Users/abdonrd/my-api/plugins/graphql/services/Aggregator.js:155:17)
    at primitiveFields.getFieldsByTypes (/Users/abdonrd/my-api/plugins/graphql/services/Aggregator.js:401:28)
    at _.reduce (/Users/abdonrd/my-api/plugins/graphql/services/Aggregator.js:86:28)
    at /Users/abdonrd/my-api/plugins/graphql/node_modules/lodash/lodash.js:914:11
    at /Users/abdonrd/my-api/plugins/graphql/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/Users/abdonrd/my-api/plugins/graphql/node_modules/lodash/lodash.js:2996:24)
    at /Users/abdonrd/my-api/plugins/graphql/node_modules/lodash/lodash.js:4880:18
    at baseReduce (/Users/abdonrd/my-api/plugins/graphql/node_modules/lodash/lodash.js:911:5)
    at Function.reduce (/Users/abdonrd/my-api/plugins/graphql/node_modules/lodash/lodash.js:9683:14)
    at Object.getFieldsByTypes (/Users/abdonrd/my-api/plugins/graphql/services/Aggregator.js:82:14)
    at Object.generateConnectionFieldsTypes (/Users/abdonrd/my-api/plugins/graphql/services/Aggregator.js:398:34)
    at Object.formatConnectionGroupBy (/Users/abdonrd/my-api/plugins/graphql/services/Aggregator.js:435:26)
    at Object.formatModelConnectionsGQL (/Users/abdonrd/my-api/plugins/graphql/services/Aggregator.js:333:32)
    at models.reduce (/Users/abdonrd/my-api/plugins/graphql/services/Resolvers.js:244:44)
    at Array.reduce (<anonymous>)
    at Object.shadowCRUD (/Users/abdonrd/my-api/plugins/graphql/services/Resolvers.js:41:19)
    at strapi.plugins.graphql.config.shadowCRUD.Object.keys.reduce (/Users/abdonrd/my-api/plugins/graphql/services/Schema.js:150:27)
    at Array.reduce (<anonymous>)
    at /Users/abdonrd/my-api/plugins/graphql/services/Schema.js:144:46
    at Object.generateSchema (/Users/abdonrd/my-api/plugins/graphql/services/Schema.js:164:11)
    at Function.initialize (/Users/abdonrd/my-api/plugins/graphql/hooks/graphql/index.js:148:50)
    at /Users/abdonrd/my-api/node_modules/strapi/lib/hooks/index.js:19:29
    at after (/Users/abdonrd/my-api/node_modules/strapi/lib/hooks/index.js:122:39)
    at /Users/abdonrd/my-api/node_modules/lodash/lodash.js:9999:23
    at Strapi.once (/Users/abdonrd/my-api/node_modules/strapi/lib/hooks/index.js:133:17)
    at Object.onceWrapper (events.js:276:13)
    at Strapi.emit (events.js:188:13)
(node:5941) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5941) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-03-12T12:40:38.014Z] debug ⛔️ Server wasn't able to start properly.
[2019-03-12T12:40:38.015Z] error (hook:graphql) takes too long to load
(hook:graphql) takes too long to load
```

If I just remove the `"private": true`, everything works.

**Comment by lauriejim** [comment] 2019-03-12 16:36
Thank you to report this issue @abdonrd .

We are focus on other issue. If someone can investigate we will appreciate your help.

**Comment by mdacosta** [comment] 2019-11-04 13:35
Hi.
The issue is still present in 3.0.0-beta.17.4, but the error message is different:
`Error: XXX defined in resolvers, but not in schema`.

The problem seems to be located here: https://github.com/mdacosta/strapi/blob/master/packages/strapi-plugin-graphql/services/Resolvers.js#L62
We don't filter associations which are marked as `private: true` in the model.
A fix would be something like this:
```
return associations
    .filter(association => model.attributes[association.alias].private !== true)
    .reduce((resolver, association) => {
...
```

**Closed** 2019-11-07 08:19 UTC
Labels: priority: medium, status: confirmed, type: bug 🐛
