### ISSUE TITLE
findOne on content API return Forbidden (Public and Authenticated role permission findOne is checked)

### ISSUE THREAD

**Issue by Jbmanllr** [strapi/strapi#11163] opened 2021-10-01 08:28 UTC
### Describe the bug

For Strapi V 4.0.0-beta.0 !!

Using the route http://host.com/api/whatevers/:id on content API return Forbidden, yes, the public and authenticated role permission findOne is checked.

### Steps to reproduce the behavior

1. Create a content type whatever
2. Create an entry (id 1)
3. Go to USERS & PERMISSIONS PLUGIN > Roles > Public
4. Click on "whatever", select "find" and "findOne"
5. Repeat 2 & 3 for authenticated role.
6. Try the route http://host.com/api/whatevers/1

It returns forbidden...

### Expected behavior

Whatever id 1 datas are returned.

### System

- Node.js version: v14.15.1
- NPM version: 6.14.9
- Strapi version: 4.0.0-beta.0
- Database: postgres
- Operating system: macOs Big Sur

**Comment by MattieBelt** [comment] 2021-10-01 09:10
Duplicate of #11141

**Closed by MattieBelt** 2021-10-01 09:10 UTC
