### ISSUE TITLE
Role Level Permissions for super-admins should be authorized by default for content-types

### ISSUE THREAD

**Issue by Aliemeka** [strapi/strapi#9072] opened 2021-01-08 20:39 UTC
## Bug report
I can't edit fields due to role-based permissions.

### Steps to reproduce the behaviour
1. I created a content-type called categories in the GUI
2. I can't the fields even I am the super-admin

### Expected behaviour

Super admins should be able to edit fields in content-types

### System

- Node.js version: 14.15.3
- NPM version: 6.14.9
- Strapi version: 3.4.1

**Comment by derrickmehaffy** [comment] 2021-01-08 21:09
@Aliemeka Can you please provide more information?

**Comment by Aliemeka** [comment] 2021-01-09 14:27
I read some articles and I have been able to figure out the problem. But I'm of the opinion that field-based permissions should be allowed by default for super-admins.

You could also add a little doc guide to the CMS dashboard on getting started.

Thanks anyway!

**Comment by derrickmehaffy** [comment] 2021-01-11 17:53
Odd, the default should be all super-admins should have full perms on all fields within the Admin. Typically when I've seen this issue it's due to an improper build of the admin (usually after updating the project to a new version).

**Comment by Aliemeka** [comment] 2021-01-11 18:49
Yeah they should that's oddly inconsistent

**Comment by derrickmehaffy** [comment] 2021-01-11 20:50
Can you try running a clean admin build? `yarn build --clean` or `npm run build -- --clean` (<-- that npm command is not a typo, you need the extra dashes)

**Comment by Aliemeka** [comment] 2021-01-11 21:45
The issue has been resolved

**Comment by Aliemeka** [comment] 2021-01-13 21:09
> @Aliemeka Can you please provide more information?

When a new strapi.js cms is created, roles are not configured by default to allow super-admins have field-based permissions to content-types

**Comment by petersg83** [comment] 2021-01-14 13:46
Hi, can you be more precise on the steps to reproduce it please? I couldn't reproduce it.
The best is if you can do it from a fresh install

**Comment by derrickmehaffy** [comment] 2021-01-22 20:34
Closing in favor of: https://github.com/strapi/strapi/issues/9194

**Closed by derrickmehaffy** 2021-01-22 20:34 UTC
Labels: status: pending reproduction
