### ISSUE TITLE
Better post request error handling

### ISSUE THREAD

**Issue by tonxxd** [strapi/strapi#7872] opened 2020-09-13 09:11 UTC
**Describe the bug**
POST requests to content API that result in a 500 error still create the entry in the database.

**Steps to reproduce the behavior**

1. Create a content model with a repeatable component which contains a file field. Eg email with repeatable attachments field that have a media field and other metadata
2. Post a new entry with wrong JSON data `(eg attachments[index].media = {})` and correct form data file (attachments[index].media  = binary file)
3. Requests result in a 500 internal server error
```
CastError: Cast to ObjectId failed for value "[object Object]" at path "_id" for model "file"
    at new CastError (node_modules/mongoose/lib/error/cast.js:39:11)
    at ObjectId.cast (node_modules/mongoose/lib/schema/objectid.js:246:11)
    at ObjectId.SchemaType.applySetters (node_modules/mongoose/lib/schematype.js:975:12)
    at ObjectId.SchemaType._castForQuery (node_modules/mongoose/lib/schematype.js:1389:15)
    at ObjectId.SchemaType.castForQuery (node_modules/mongoose/lib/schematype.js:1379:15)
    at ObjectId.SchemaType.castForQueryWrapper (node_modules/mongoose/lib/schematype.js:1358:15)
    at cast (node_modules/mongoose/lib/cast.js:315:32)
    at model.Query.Query.cast (node_modules/mongoose/lib/query.js:4697:12)
    at model.Query.Query._castConditions (node_modules/mongoose/lib/query.js:1876:10)
    at model.Query._updateThunk (node_modules/mongoose/lib/query.js:3696:8)
    at model.Query.<anonymous> (node_modules/mongoose/lib/query.js:3806:23)
    at model.Query._wrappedThunk [as _updateMany] (node_modules/mongoose/lib/helpers/query/wrapThunk.js:16:8)
    at node_modules/kareem/index.js:278:20
    at _next (node_modules/kareem/index.js:102:16)
    at node_modules/kareem/index.js:507:38
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```
4. Entry is created anyway with empty fields

**Expected behavior**
Entry should not be created, in particular with empty fields. Maybe would be useful also a more detailed error label since it took me quite a bit to understand what was the issue since my model has several file fields and there is no reference to the field name.

**System**

- Node.js version: v14.5
- NPM version: 6.14.5
- Strapi version: 3.1.4
- Database: mongo
- Operating system: Mac OS

**Comment by derrickmehaffy** [comment] 2020-09-14 20:52
I was able to reproduce this on the latest version, this bug concerns the data being created regardless of the error thrown to the user, leading them to believe it's a server issue (it's a client one due to a missing parameter) and the content is still created, though with missing information.

**Comment by DanielWahl** [comment] 2020-10-06 10:53
Has anyone found a solution to that problem/behaviour?

**Comment by sam-pires** [comment] 2021-07-15 12:14
@derrickmehaffy Is this issue related to the upload plugin or just the REST API?

**Comment by derrickmehaffy** [comment] 2021-07-15 21:34
> @derrickmehaffy Is this issue related to the upload plugin or just the REST API?

This specific issue is related the upload plugin but our error handling in the entire application is a problem (especially users-permissions). I believe @alexandrebodin was planning a massive error handling rework for the v4 anyway (every level with predefined error codes to return to the user).

In this case specifically it's an error handling issue at the database connector issue.

**Comment by derrickmehaffy** [comment] 2022-07-13 20:42
This should be fixed in v4

**Closed by derrickmehaffy** 2022-07-13 20:42 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:upload
