### ISSUE TITLE
Strapi 5.0.4 - Content Manager - Pagination doesn't work

### ISSUE THREAD

**Issue by cslegany-synerinsoft** [strapi/strapi#21775] opened 2024-10-10 09:33 UTC
### Required System information

- Node.js version: v20.11.0
- NPM version: 10.2.4
- Strapi version: 5.0.4
- Database: MySQL or SQLite, doesn't matter
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Steps to reproduce the behavior
0. Install a fresh strapi 5.0.4 using cli.  
use npx create-strapi@latest
Fill it with sample data, then add a few more articles to have at least 11 items.
1. Go to Content Manager, select Articles. 
http://localhost:1337/admin/content-manager/collection-types/api::article.article?pageSize=10&page=1&sort=title%3AASC
2. Click on Page 2 in the pagination at the bottom. Url changes to:
http://localhost:1337/admin/content-manager/collection-types/api::article.article?pageSize=10&page=2&sort=title%3AASC
3. **You'll see the same articles as on first page**
4. Click on Page 3 in the pagination at the bottom. You'll again see just the first 10 articles. You'll never be able to reach 11th article.

### Expected behavior

A functional pagination is required. It was working in version 5.0.2 but downgrade isn't an option because of other crucial fixes.

### Screenshots
![strapi_issue1](https://github.com/user-attachments/assets/99dce3a0-b997-4256-9d6b-40632029fb42)
![strapi_issue2](https://github.com/user-attachments/assets/ea3a201f-efcf-40ca-9fd7-11b00acbdd01)

### Additional context
Please fix it asap, a functional pagination is a required core feature.

**Comment by freshsid** [comment] 2024-10-10 14:31
Same here

**Comment by mdshack** [comment] 2024-10-10 15:12
Also experiencing this, [heres](https://discord.com/channels/811989166782021633/1019655562092355594/threads/1293667482141196388) a Discord help thread I opened in the official `strapi-questions` board.

**Comment by derrickmehaffy** [comment] 2024-10-10 19:03
duplicate of: https://github.com/strapi/strapi/issues/21789

**Closed by derrickmehaffy** 2024-10-10 19:03 UTC
Labels: status: duplicate
