### ISSUE TITLE
Error when generating typings when there are custom fields in schema

### ISSUE THREAD

**Issue by maurice-ellis** [strapi/strapi#16009] opened 2023-03-06 17:13 UTC
### Required System information

- Node.js version: 18.14.2
- NPM version:9.5.0
- Strapi version: 4.7.1
- Database: SQLite
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When generating typings via the command, I run into this error, but only when I have a custom field in my schema. The verbose flag didn't provide much more detail.

```
Error: Debug Failure. Unhandled SyntaxKind: Unknown.
    at pipelineEmitWithHintWorker (/Users/maurice/Documents/328/328studios.co/v2/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:109799:22)
    at pipelineEmitWithHint (/Users/maurice/Documents/328/328studios.co/v2/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:109334:17)
    at pipelineEmitWithComments (/Users/maurice/Documents/328/328studios.co/v2/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:112936:13)
    at pipelineEmit (/Users/maurice/Documents/328/328studios.co/v2/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:109274:13)
    at emitExpression (/Users/maurice/Documents/328/328studios.co/v2/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:109258:13)
    at emitLiteralType (/Users/maurice/Documents/328/328studios.co/v2/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:110336:13)
    at pipelineEmitWithHintWorker (/Users/maurice/Documents/328/328studios.co/v2/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:109449:32)
    at pipelineEmitWithHint (/Users/maurice/Documents/328/328studios.co/v2/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:109334:17)
    at pipelineEmitWithComments (/Users/maurice/Documents/328/328studios.co/v2/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:112936:13)
    at pipelineEmit (/Users/maurice/Documents/328/328studios.co/v2/backend/node_modules/@strapi/typescript-utils/node_modules/typescript/lib/typescript.js:109274:13)
```

### Steps to reproduce the behavior

1. Run `npx strapi ts:generate-types` command
2. Run into error above

### Expected behavior

I expect to be able to run this command successfully with no error with or without custom fields in schemas

**Comment by Eventyret** [comment] 2023-03-20 08:38
Thank you for your report @maurice-ellis 🙌 
To try to reproduce this, what type of **custom fields** did you have? Could you provide me with an example so I can try to reproduce this?

**Comment by Eventyret** [comment] 2023-03-20 12:22
Duplicate of https://github.com/strapi/strapi/issues/13893

**Closed by Eventyret** 2023-03-20 12:22 UTC
Labels: severity: low, status: duplicate, source: core:strapi
