### ISSUE TITLE
Document how to deploy at Google App Engine

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#3433] opened 2019-06-12 13:23 UTC
I want to propose to add a new deployment guide about Google App Engine.

https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html

**Comment by derrickmehaffy** [comment] 2019-06-12 13:34
@davidkartuzinski We were just talking about this lol

**Comment by derrickmehaffy** [comment] 2019-06-12 13:35
@abdonrd I think David would like you have your feedback and what not since you are currently using this right?

**Comment by derrickmehaffy** [comment] 2019-06-12 13:35
(BTW normally I'd close this as it doesn't follow the FR template, but in this case I'll leave it open)

**Comment by abdonrd** [comment] 2019-06-12 13:40
No, I'm using IBM Cloud at work, and Heroku at personal project. In this last one I am evaluating to migrate it to GAE. I documented my tests here: #2146.

---

The template told me to send it to ProductBoard, but it does not seem like a big feature to send there.

**Comment by derrickmehaffy** [comment] 2019-06-12 13:43
Aye yeah I have a PR open for a discussion template, just waiting for it to be approved for stuff like this.

**Comment by davidkartuzinski** [comment] 2019-06-12 13:55
@abdonrd - I would like you feedback regarding IBM Cloud and Heroku.  I can't tell if you got it working on GAE or not?

**Comment by abdonrd** [comment] 2019-07-08 14:50
@davidkartuzinski you already cover well the [Heroku deployment](https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#heroku).

About IBM Cloud, using Cloudfoundry, is similar. The only difference with the `alpha` version, is that now I have to run the `npm run build` before the deploy.

About GAE, I still have to try to deploy a beta version.

**Comment by davidkartuzinski** [comment] 2019-07-08 15:41
@adonrd - Maybe the Digital Ocean and AWS docs can help?  If you look at the PM2 and database sections... https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#amazon-aws - Please let me know.  Thank you

**Comment by fxw** [comment] 2019-07-11 07:33
Relared to this topics, any body have deployed a docker instance of strapi on Kubernetes (minikube, GCP, AWS or azure ?)

**Comment by ppsirius** [comment] 2019-08-04 11:04
Is someone maybe working on this App Engine documentation guide?

**Comment by Narmdo** [comment] 2019-09-23 12:53
Any news on this or quick tips? I'm struggling to get a deployment working right now.

Getting:
 error Bootstrap function in plugin "email" failed" 
SQLITE_READONLY: attempt to write a readonly database

server.json is simply the default:
`{
  "host": "localhost",
  "port": "${process.env.PORT || 1337}",
  "production": true,
  "proxy": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false
  }
}
`

**Comment by tolstenko** [comment] 2019-11-19 19:12
> @davidkartuzinski you already cover well the [Heroku deployment](https://strapi.io/documentation/3.0.0-beta.x/guides/deployment.html#heroku).
> 
> About IBM Cloud, using Cloudfoundry, is similar. The only difference with the `alpha` version, is that now I have to run the `npm run build` before the deploy. ( I use Travis CI)
> 
> About GAE, I still have to try to deploy a beta version.
> An option could be with: [App Engine documentation > Node.js > Running a custom build step](https://cloud.google.com/appengine/docs/standard/nodejs/running-custom-build-step)
> But I don't know about the environment variables (database, etc).

I make it work adding 
```
    "gcp-build": "npm install ; npm run build"
```
inside the `scripts` of the same `package.json`  from heroku doc

**Comment by vshirguppi** [comment] 2020-01-26 00:50
Here are the steps I used to deploy to GAE
- Create a new project on GAE
- Strapi updates
  - Add the following script to your package.json file
     `"gcp-build": "npm install; npm run build"`
  - Create app.yaml file in the root of your application with the following config
```
        runtime: nodejs10
        instance_class: F2
```
- cd into your strapi project
- `gcloud auth login`
- `gcloud config set project <project-name>`
- `gcloud app deploy`

**Comment by gambhiro** [comment] 2020-01-26 06:10
@vshirguppi Yes, the `gcp-build` step was an important discover for me.

Also, it was confusing to me how to configure something bigger like PostgreSQL, because GAE expects to use the unix socket path.

And I didn't understand that on GAE the app can't create files, so you have to create your content types locally and deploy it.

**Comment by psaia** [comment] 2020-02-08 20:52
Slightly relevant, we just deployed this in a gcloud managed k8s cluster with similar config: https://gist.github.com/psaia/b12b39557fa7694c3f26ec5276816ebf

Hope that's helpful.

**Comment by lauriejim** [comment] 2020-04-24 15:56
Here is the guide - https://strapi.io/documentation/3.0.0-beta.x/deployment/google-app-engine.html

**Closed by lauriejim** 2020-04-24 15:56 UTC
Labels: priority: low, source: documentation

**Comment by chrisrickenbacher** [comment] 2020-04-30 11:05
I followed the guide step by step but I always receive a server error 500. The only error I can find in the logs looks like this: 
`<timecode> error Error: listen EADDRNOTAVAIL: address not available <ip-address>:8081`
I really don't understand what I did wrong. Would be great if someone could help. Thanks!

**Comment by B-Scan** [comment] 2020-04-30 20:50
@chrisrickenbacher try changing host variable in `app.yaml` to:
`HOST: "0.0.0.0"`
That fixed the issue for me.

**Comment by chrisrickenbacher** [comment] 2020-05-02 14:44
@B-Scan great it works, thank you so much!

**Comment by t0m0120** [comment] 2020-05-02 18:40
@B-Scan 
Thanks !! 
I was stuck on the same problem.

**Comment by rmichael123** [comment] 2020-05-26 13:30
I've also followed the updated guide, but still get the "server error 500", 
Are there any other suggestions to fix this?

**Comment by B-Scan** [comment] 2020-05-28 11:15
@rmichael123 - I would suggest looking into the logs for this app engine instance. I would bet that DB connection settings are not correctly set. If not that, some other config issue.

**Comment by rmichael123** [comment] 2020-05-28 11:36
> @rmichael123 - I would suggest looking into the logs for this app engine instance. I would bet that DB connection settings are not correctly set. If not that, some other config issue.

yes was DB issue, that was it , thanks

**Comment by KrustyHack** [comment] 2020-06-28 17:06
Hi all,

I'm still struggling with one thing when deploying to GAE :

```
2020-06-28 16:42:55 default[20200628t182207]  "GET /favicon.ico HTTP/1.1" 500
2020-06-28 16:42:57 default[20200628t182207]  [2020-06-28T16:42:57.833Z] debug ⛔️ Server wasn't able to start properly.
2020-06-28 16:42:57 default[20200628t182207]  [2020-06-28T16:42:57.837Z] error Error: EROFS: read-only file system, mkdir '/workspace/.tmp'
2020-06-28 16:42:57 default[20200628t182207]      at Object.mkdirSync (fs.js:841:3)
2020-06-28 16:42:57 default[20200628t182207]      at /workspace/node_modules/strapi-connector-bookshelf/lib/knex.js:152:16
2020-06-28 16:42:57 default[20200628t182207]      at /workspace/node_modules/lodash/lodash.js:4905:15
2020-06-28 16:42:57 default[20200628t182207]      at baseForOwn (/workspace/node_modules/lodash/lodash.js:2990:24)
2020-06-28 16:42:57 default[20200628t182207]      at /workspace/node_modules/lodash/lodash.js:4874:18
2020-06-28 16:42:57 default[20200628t182207]      at Function.forEach (/workspace/node_modules/lodash/lodash.js:9342:14)
2020-06-28 16:42:57 default[20200628t182207]      at module.exports (/workspace/node_modules/strapi-connector-bookshelf/lib/knex.js:37:5)
2020-06-28 16:42:57 default[20200628t182207]      at Object.initialize (/workspace/node_modules/strapi-connector-bookshelf/lib/index.js:39:5)
2020-06-28 16:42:57 default[20200628t182207]      at Object.initialize (/workspace/node_modules/strapi-database/lib/connector-registry.js:30:25)
2020-06-28 16:42:57 default[20200628t182207]      at DatabaseManager.initialize (/workspace/node_modules/strapi-database/lib/database-manager.js:36:27)
2020-06-28 16:42:57 default[20200628t182207]      at Strapi.load (/workspace/node_modules/strapi/lib/Strapi.js:274:19)
```

Did I miss something in your guide ? :thinking:

**Comment by abbeyseto** [comment] 2020-10-08 00:48
> Any news on this or quick tips? I'm struggling to get a deployment working right now.
> 
> Getting:
> 
> ```
> error Bootstrap function in plugin "email" failed" 
> SQLITE_READONLY: attempt to write a readonly database
> ```
> 
> server.json is simply the default:
> 
> ```json
> {
>   "host": "localhost",
>   "port": "${process.env.PORT || 1337}",
>   "production": true,
>   "proxy": {
>     "enabled": false
>   },
>   "cron": {
>     "enabled": false
>   },
>   "admin": {
>     "autoOpen": false
>   }
> }
> ```

i am really having this issue too while deploying on Google App Engine. Becoming a bit frustrating.

![image](https://user-images.githubusercontent.com/14161363/95402735-52e41600-0908-11eb-9dc0-487d289c647d.png)

**Comment by B-Scan** [comment] 2020-10-08 07:06
@abbeyseto App Engine is a read-only system. That means you can't host your SQLite database there, since it requires write to store any data. 
If you wanted to connect to some other database, your production configuration needs to contain prod DB connection string.

**Comment by philliprognerud** [comment] 2020-12-19 00:50
@B-Scan I am also getting @abbeyseto issue.. my app won't start because of this error. I am connecting to my Mongo database and not writing anything to the file system. Why is this error coming up? I have also tried deploying on Heroku, no problems, and I can confirm nothing was being written to the system as I was connected to my mongo database connection. Why does this error only show up on GAE? Im not writing anything locally, is Strapi doing something under the hood?

**Comment by philliprognerud** [comment] 2020-12-20 00:58
**SOLVED:** If you were getting the error `EROFS: read-only file system ...` it was most likely due to one of the built-in plugins that Strapi provides!

The documentation plugin, for whatever reason, is writing something to the file system upon start up. Removing this plugin will get rid off this error and allow you to _see the Strapi dashboard in Google App Engine_. 

### Run this command to remove the documentation plugin:
```
yarn run strapi -- uninstall documentation -d
```

### Additional Info:
This is my Strapi `production/server.js`:
```
production: true,
host: env("HOST"),
port: env.int("PORT"),
admin: {
    autoOpen: false,
    auth: {
        secret: env("ADMIN_JWT_SECRET")
    }
},
autoReload: {
    enabled: false
},
cron: {
    enabled: false
}
```
My `package.json` scripts
```
{
    "dev": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "gcp-build": "strapi build",
    "deploy": "gcloud config set project <PROJECT_ID> && gcloud app deploy app.yaml --version=<VERSION>"
}
```

**Note:**
Google App Engine (node.js) prefers that the port be 8080, but Strapi's default is 1337. Make sure to change this if it still doesn't work.

**Comment by Samson11** [comment] 2021-12-25 16:20
Hi please how do i deploy a strapi app using docker to app engine in the flex environment

**Comment by JohnFlorez25** [comment] 2022-09-10 04:59
@derrickmehaffy If I want to have a **development environment** in a GAE with Strappi, How is the configuration project? I try to change the NODE_ENV, and enable **autoReload**, but continuously the deployment run in a **production environment**
![Screen Shot 2022-09-09 at 11 58 58 PM](https://user-images.githubusercontent.com/22262727/189469786-456f7b20-61b4-4b23-8a24-d2ae7b7e36e2.png)
