### ISSUE TITLE
error: unknown option `--watch-admin'

### ISSUE THREAD

**Issue by sumitdubey** [strapi/strapi#6217] opened 2020-05-15 02:13 UTC
**Describe the bug**
When executing command `$ strapi develop --watch-admin`, it gives the error `error: unknown option `--watch-admin'`

**Steps to reproduce the behavior**

1. npx create-strapi-app my-project --quickstart
2. strapi develop --watch-admin

**Expected behavior**
Starts your application with the autoReload enabled and the front-end development server. It allows you to customize the administration panel..

**Screenshots**
![image](https://user-images.githubusercontent.com/7381652/82003979-60f67900-967f-11ea-9824-ec446ddced9a.png)

**Code snippets**
NA

**System**

- Node.js Version: v12.16.1
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.14
- Database: sqlite, mongo
- Operating system: Ubuntu 18.04

**Additional context**
`strapi develop` works fine.

**Comment by derrickmehaffy** [comment] 2020-05-15 04:10
This is because your globally installed strapi Version is too old. You need to either remove that or update it. 

You can call the correct Strapi package from within the project using `yarn strapi develop --watch-admin`

I'm closing this as it's not a bug but a user environment problem.

**Closed by derrickmehaffy** 2020-05-15 04:10 UTC

**Comment by sumitdubey** [comment] 2020-05-15 13:15
@derrickmehaffy Thanks a lot. I removed the global package and now it works.
