### ISSUE TITLE
Server failed to start after clean install of graphql

### ISSUE THREAD

**Issue by Mike-Van** [strapi/strapi#1834] opened 2018-08-29 06:43 UTC
Im following the guide here: https://strapi.io/documentation/guides/graphql.html but after doing a clean install of graphql. I get this error when i try to start the server. It's only until i removed graphql that i can normally start the server. I havent touched or altered any setting yet. 

```
(node:27073) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Expected :, found Name "you"
    at syntaxError (/home/mike/Desktop/clik.asia.admin/plugins/graphql/node_modules/graphql/error/syntaxError.js:24:10)
    at expect (/home/mike/Desktop/clik.asia.admin/plugins/graphql/node_modules/graphql/language/parser.js:1299:32)
    at parseFieldDefinition (/home/mike/Desktop/clik.asia.admin/plugins/graphql/node_modules/graphql/language/parser.js:811:3)
    at many (/home/mike/Desktop/clik.asia.admin/plugins/graphql/node_modules/graphql/language/parser.js:1350:16)
    at parseFieldsDefinition (/home/mike/Desktop/clik.asia.admin/plugins/graphql/node_modules/graphql/language/parser.js:799:50)
    at parseObjectTypeDefinition (/home/mike/Desktop/clik.asia.admin/plugins/graphql/node_modules/graphql/language/parser.js:757:16)
    at parseTypeSystemDefinition (/home/mike/Desktop/clik.asia.admin/plugins/graphql/node_modules/graphql/language/parser.js:663:16)
    at parseDefinition (/home/mike/Desktop/clik.asia.admin/plugins/graphql/node_modules/graphql/language/parser.js:143:16)
    at parseDocument (/home/mike/Desktop/clik.asia.admin/plugins/graphql/node_modules/graphql/language/parser.js:110:22)
    at Object.parse (/home/mike/Desktop/clik.asia.admin/plugins/graphql/node_modules/graphql/language/parser.js:38:10)
    at Object.addPolymorphicUnionType (/home/mike/Desktop/clik.asia.admin/plugins/graphql/services/GraphQL.js:1263:27)
    at Object.generateSchema (/home/mike/Desktop/clik.asia.admin/plugins/graphql/services/GraphQL.js:1181:58)
    at Function.initialize (/home/mike/Desktop/clik.asia.admin/plugins/graphql/hooks/graphql/index.js:103:62)
    at /home/mike/Desktop/clik.asia.admin/node_modules/strapi/lib/hooks/index.js:19:29
    at after (/home/mike/Desktop/clik.asia.admin/node_modules/strapi/lib/hooks/index.js:122:39)
    at /home/mike/Desktop/clik.asia.admin/node_modules/lodash/lodash.js:9997:23
    at Strapi.once (/home/mike/Desktop/clik.asia.admin/node_modules/strapi/lib/hooks/index.js:133:17)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Strapi.emit (events.js:208:7)
    at loadedModule.initialize.call.err (/home/mike/Desktop/clik.asia.admin/node_modules/strapi/lib/hooks/index.js:32:12)
    at Function.initialize (/home/mike/Desktop/clik.asia.admin/node_modules/strapi-hook-bookshelf/lib/index.js:999:7)
(node:27073) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27073) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-08-29T06:42:28.178Z] debug ⛔️ Server wasn't able to start properly.
[2018-08-29T06:42:28.181Z] error (hook:graphql) takes too long to load
```

**Comment by derrickmehaffy** [comment] 2018-08-29 07:04
@Mike-Van Do you have enum values with spaces or special chars in them (in this case `:`) ?

**Comment by Duncanmoo** [comment] 2018-09-04 09:41
Similar issue for me, trying out Strapi, seems awesome, did the following all using the GUI:

- Added page content type
- Enabled graphQL plugin
- added image field to page content type (new field called "Featured image")
- CLI says `Server wasn't able to start properly`

`(node:57147) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Expected :, found Name "image"
    at syntaxError (/Users/duncanm/projects/strapi/testing/plugins/graphql/node_modules/graphql/error/syntaxError.js:24:10)
    at expect (/Users/duncanm/projects/strapi/testing/plugins/graphql/node_modules/graphql/language/parser.js:1299:32)
    at parseFieldDefinition (/Users/duncanm/projects/strapi/testing/plugins/graphql/node_modules/graphql/language/parser.js:811:3)
    at many (/Users/duncanm/projects/strapi/testing/plugins/graphql/node_modules/graphql/language/parser.js:1350:16)
    at parseFieldsDefinition (/Users/duncanm/projects/strapi/testing/plugins/graphql/node_modules/graphql/language/parser.js:799:50)
    at parseObjectTypeDefinition (/Users/duncanm/projects/strapi/testing/plugins/graphql/node_modules/graphql/language/parser.js:757:16)
    at parseTypeSystemDefinition (/Users/duncanm/projects/strapi/testing/plugins/graphql/node_modules/graphql/language/parser.js:663:16)
    at parseDefinition (/Users/duncanm/projects/strapi/testing/plugins/graphql/node_modules/graphql/language/parser.js:149:12)
    at parseDocument (/Users/duncanm/projects/strapi/testing/plugins/graphql/node_modules/graphql/language/parser.js:110:22)
    at Object.parse (/Users/duncanm/projects/strapi/testing/plugins/graphql/node_modules/graphql/language/parser.js:38:10)
    at Object.addPolymorphicUnionType (/Users/duncanm/projects/strapi/testing/plugins/graphql/services/GraphQL.js:1263:27)
    at Object.generateSchema (/Users/duncanm/projects/strapi/testing/plugins/graphql/services/GraphQL.js:1181:58)
    at Function.initialize (/Users/duncanm/projects/strapi/testing/plugins/graphql/hooks/graphql/index.js:103:62)
    at /usr/local/lib/node_modules/strapi/lib/hooks/index.js:19:29
    at after (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:122:39)
    at /usr/local/lib/node_modules/strapi/node_modules/lodash/lodash.js:9997:23
    at Strapi.once (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:133:17)
    at Object.onceWrapper (events.js:273:13)
    at Strapi.emit (events.js:182:13)
    at Strapi.EventEmitter.emit (domain.js:442:20)
    at loadedModule.initialize.call.err (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:32:12)
    at Function.initialize (/Users/duncanm/projects/strapi/testing/node_modules/strapi-hook-bookshelf/lib/index.js:1000:7)
(node:57147) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:57147) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-09-04T09:26:50.176Z] debug ⛔️ Server wasn't able to start properly.
[2018-09-04T09:26:50.177Z] error (hook:graphql) takes too long to load`

**Comment by Duncanmoo** [comment] 2018-09-04 10:39
I was able to confirm that without the GraphQL plugin I am able to add that field with a space in its name; Strapi allows me to save data to that field, the file gets uploaded to the CMS but re-editing that field shows that the image is not associated with that content.

Not trying to =hijack this issue but the OP issue may have been a space in the title of a field: https://github.com/strapi/strapi/issues/1789

**Comment by lauriejim** [comment] 2018-09-07 10:58
@Duncanmoo It looks be an other issue on GraphQL, can you submit a new PR with your error please.

**Comment by lauriejim** [comment] 2018-09-17 10:05
Duplicate of https://github.com/strapi/strapi/issues/1687

**Closed by lauriejim** 2018-09-17 10:05 UTC
Labels: type: help wanted 🤷‍♂️

**Comment by fatid** [comment] 2019-02-08 14:43
I had a same problem after typing "strapi install graphql" . Then i delete graphql with " strapi uninstall graphql". Now strapi works, but i can't use graphl.

**Comment by lauriejim** [comment] 2019-02-10 16:31
Did you check the linked issue ?

**Comment by keahie** [comment] 2019-03-27 14:59
I'm not sure if you still have the error but my solution was to check if any field in my content types had a space in it. I replaced all spaces with an underscore and now everything works fine.
