### ISSUE TITLE
Errors install plugin / create project when app folder path contains a space on Windows

### ISSUE THREAD

**Issue by SerQuicky** [strapi/strapi#1172] opened 2018-05-12 16:15 UTC
- **Node.js version**:9.8.0
- **npm version**:5.6.0
- **Strapi version**:3.0.0-alpha.12.1.3
- **Database**:MongoDB
- **Operating system**:Windows 7

I installed the newest version of strapi and tried to create a new project.
After the submit of the database configuration, I am getting multiple errors, but the installation still completes. I can start the strapi-server but when I try to open the admin panel, its just a blank page.
I looked into my mongodb and realized that a strapi database was not created. I think the problem occures, because of the mongoDB. But I don´t know why, because the mongoDB runs locally and it works with other projects.
.

**Informations**
![error1](https://user-images.githubusercontent.com/35799053/39959200-c1ef4da8-560e-11e8-9bb5-a0b2b2b75ff9.png)
![error2](https://user-images.githubusercontent.com/35799053/39959201-c2146f02-560e-11e8-80c3-6ad9c366ff2a.png)
![error3](https://user-images.githubusercontent.com/35799053/39959202-c230b1bc-560e-11e8-8f17-95e00e30759c.png)
![blankpage](https://user-images.githubusercontent.com/35799053/39959314-15d8fb7a-5610-11e8-9742-1fab8f1dadb4.png)

---

- [ ] I'm sure that this feature hasn't already been referenced.

**Comment by SerQuicky** [comment] 2018-05-12 18:30
I think the problem comes from my site, my profile folder got a whitespace and the git cmd has a problem with that. Just asked a friend to create and send me a strapi project and this project just works perfect.

**Comment by lauriejim** [comment] 2018-05-13 08:39
Hello @, thank you for reporting this issue. We won’t undertake this development because our focus is currently on another feature. Since time is lacking on our side, feel free to submit a PR, we’ll  be glad to count you as one of our contributors! 

@SerQuicky has said `Kamal` on slack, just use an other folder without space.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by lauriejim** [comment] 2018-05-13 08:40
And I think it's a really easy first issue to fix.

**Comment by avallete** [comment] 2018-08-27 16:42
I have not been able to reproduce this error.

I'm also using Window 7.

Maybe it has been fixed in another PR.

```
avallete@PC9168 MINGW64 ~/WebstormProjects/koko lasticot
$ strapi new test\ app2
🚀 Start creating your Strapi application. It might take a minute, please take a coffee ☕️

Lets configurate the connection to your database:
? Choose your main database: (Use arrow keys)
? Choose your main database: MongoDB (recommended)
? Database name: (strapi)
? Database name: strapi
? Host: (127.0.0.1) 192.168.99.100
? Host: 192.168.99.100
? Port: (27017)
? Port: 27017
? Username: root
? Username: root
? Password: root
? Password: ****
? Authentication database: admin
? Authentication database: admin
? Enable SSL connection: (false)
? Enable SSL connection: false

⏳ Testing database connection...
The app has been connected to the database successfully!

🏗  Application generation:
globalRootPath C:\Users\avalleteau\AppData\Roaming\npm\node_modules

depPath  C:\Users\avalleteau\AppData\Roaming\npm\node_modules\strapi
globalRootPath C:\Users\avalleteau\AppData\Roaming\npm\node_modules

depPath  C:\Users\avalleteau\AppData\Roaming\npm\node_modules\strapi-hook-mongoose

👌 Your new application test app2 is ready at C:\Users\avalleteau\WebstormProjects\koko lasticot\test app2.

⚡️ change directory:
$ cd test app2

⚡️ start application:
$ strapi start
```

PS: `depPath` and `globalRootPath` are some logs I made to verify everything is properly handled. Do not take care of it.

Please @SerQuicky can you retry with the latest version of strapi, and tell us if the issue persist on your side ?

**Comment by lauriejim** [comment] 2018-09-14 14:17
Look fixed :D

I am closing this issue because we don’t have any update/needed informations about it.
Will reopen it if activity come back.

**Closed by lauriejim** 2018-09-14 14:17 UTC
Labels: Good for New Contributors, priority: low, status: confirmed, type: bug 🐛
