### ISSUE TITLE
No locale parameter in URL being sent while crawling relations

### ISSUE THREAD

**Issue by rafdol97** [strapi/strapi#18550] opened 2023-10-24 12:45 UTC
### Required System information

- Node.js version: v16.16.0
- NPM version: 8.11.0
- Strapi version: 4.13.6
- Database: Postgres
- Operating system: Mac
- Is your project Javascript or Typescript: JS

### Describe the bug

Issue is about internationalization plugin and content-types which have relations. Basically when working on any content-type while using not default locale, you cannot point to valid record by relation. Additionally later on you can mix data from different locales. I will describe it in next section.

### Steps to reproduce the behavior

1. Create collection-type, allow internationalization (lets assume we got locale: DE- default, AT, CH). Let's say for me its called 'Section'.
3. Create record in Section in locale AT called "Test Section AT".
4. In other collection type (lets assume Page) make a component with relation like following:
<img width="846" alt="image" src="https://github.com/strapi/strapi/assets/84195937/71c4f9f1-1cc4-4324-ae74-6507cf3b31d5">
relation itself:
<img width="824" alt="image" src="https://github.com/strapi/strapi/assets/84195937/42873d69-6953-4697-a806-855c23d90077">
5. Pages are localized. Go to page in AT locale, link section like this:
<img width="653" alt="image" src="https://github.com/strapi/strapi/assets/84195937/31fa911a-93f9-4e61-b09f-f2cb27a17731">

6. After clicking you are here: ``` http://localhost:1337/admin/content-manager/collectionType/api::section.section/7 ``` 
instead of ``` http://localhost:1337/admin/content-manager/collectionType/api::section.section/7?plugins[i18n][locale]=de-AT ```

so outcome is that part : ``` ?plugins[i18n][locale]=de-AT ``` is missing.
Unfortunately, in this situation you are able to add content from DE locale inside section (default language) :D and not content from AT locale. Moreover, when u click save - it will work and it will be saved in proper locale (AT in my case) :D
So i end up with having section AT full of DE content (which is not possible if you enter the URL with locale parameter.
Moreover 2, in this situation when u will change locale manually (right side menu) - you will create an empty new record. 
 ### Expected behavior

Relations are pointing to proper records. You cannot mix up data from different locales.

### Screenshots

Attached.

**Comment by ls-ramos** [comment] 2024-03-15 16:37
I am experiencing the same issue, I would love to see this ticket with a higher severity. I am not sure how the severities are ranked at the moment, and I know that everyone has a different use case so it is not possible to make everyone happy.

But this issue is quite critical to us because it is very confusing for non-technical people managing strapi.

Here is a video showing the issue on my side:

https://github.com/strapi/strapi/assets/29318376/824281f0-e2dc-485a-be37-03829c0e440c

You can see on the video that:

1. I have an entry created on the locale DE on the content type Test.
2. This entry has a relation with another one, also created on the locale DE in the content type Test2.
3. When I go to entry with locale DE in the content type Test, and click on the relation, I end up in the EN locale.
4. Reloading the page does not affect anything, I tried it on the video.
5. Switching the locale to EN and then back to DE fixes the situation.


This was done in a newly create repo of strapi, using the command:
`npx create-strapi-app@latest --ts strapi-test-i18n`

**Comment by LexLuengas** [comment] 2024-03-22 13:26
Duplicates #17498

**Comment by derrickmehaffy** [comment] 2024-03-28 20:24
Closing as duplicate of https://github.com/strapi/strapi/issues/17498

**Closed** 2024-03-28 20:30 UTC
Labels: issue: bug, severity: low, source: core:admin, status: pending reproduction
