### ISSUE TITLE
Error while customizing components view

### ISSUE THREAD

**Issue by federicocappellotto97** [strapi/strapi#17577] opened 2023-08-06 10:06 UTC
- Node.js version: 18.6.0
- NPM version:
- Strapi version: 4.12.1
- Database: Mysql
- Operating system: Mac
- Is your project Javascript or Typescript: TS

When i try to customize any component view i get an error.
For example i created a link component, and i need to customize description and sizes for my fields, but i can't since i get an error every time i try to save
<img width="1795" alt="Screenshot 2023-08-06 at 12 05 35" src="https://github.com/strapi/strapi/assets/63153191/44dc95a4-f9a3-4d5f-9326-b7b665374455">

**Comment by MonsterDeveloper** [comment] 2023-08-06 11:43
Seems like a duplicate of my issue #17575

**Comment by nitin-pandita** [comment] 2023-08-06 13:17
I would like to work on it

**Comment by dgrebb** [comment] 2023-08-06 16:29
Same here. Seemingly out of nowhere! Upgraded to 4.12.1 last week. Ran a new `rm -rf node_modules package-lock.json && npm i && npm run build`, and also disabled `patch-package`.

`config:dump`: [configDump.txt](https://github.com/strapi/strapi/files/12270018/configDump.txt)

**`report --all`:**

```
Environment: development
OS: darwin-arm64
Strapi Version: 4.12.1
Node/Yarn Version: npm/9.6.7 node/v18.17.0 darwin arm64 workspaces/false
Edition: Community
Database: postgres
UUID: a88d5600-baef-47fb-8bf4-ff51888cc148
Dependencies: {
  "@strapi/plugin-i18n": "4.12.1",
  "@strapi/plugin-open-ai": "^1.0.1",
  "@strapi/plugin-sentry": "^4.12.1",
  "@strapi/plugin-seo": "^1.9.2",
  "@strapi/plugin-users-permissions": "4.12.1",
  "@strapi/provider-upload-aws-s3": "4.12.1",
  "@strapi/strapi": "4.12.1",
  "pg": "^8.10.0",
  "strapi-blurhash": "^1.1.1"
}
Dev Dependencies: {
  "patch-package": "^7.0.0"
}
```

**Request body:**

```{
  "stack": "Cn@http://my.local.host:1337/admin/main.d1cae481.js:3924:80112\nhn@http://my.local.host:1337/admin/main.d1cae481.js:3926:1042\nMn@http://my.local.host:1337/admin/main.d1cae481.js:3926:4456\nEventHandlerNonNull*52861/Et.xhr</<@http://my.local.host:1337/admin/main.d1cae481.js:3926:4524\n52861/Et.xhr<@http://my.local.host:1337/admin/main.d1cae481.js:3926:3526\nVe@http://my.local.host:1337/admin/main.d1cae481.js:3926:7102\npromise callback*request@http://my.local.host:1337/admin/main.d1cae481.js:3926:10910\n52861/</Be/<@http://my.local.host:1337/admin/main.d1cae481.js:3926:11567\n52861/o/<@http://my.local.host:1337/admin/main.d1cae481.js:3924:74521\nput@http://my.local.host:1337/admin/main.d1cae481.js:105:3129\n7755/Pn/K<@http://my.local.host:1337/admin/content-manager.c4737ca9.chunk.js:82:5965\nfn@http://my.local.host:1337/admin/main.d1cae481.js:1960:8173\nx@http://my.local.host:1337/admin/main.d1cae481.js:1960:27234\nw@http://my.local.host:1337/admin/main.d1cae481.js:1960:27862\n81262/P.executeMutation@http://my.local.host:1337/admin/main.d1cae481.js:1960:8111\n81262/P.execute/v<@http://my.local.host:1337/admin/main.d1cae481.js:1960:7129\npromise callback*81262/P.execute@http://my.local.host:1337/admin/main.d1cae481.js:1960:7104\n20464/oe.mutate@http://my.local.host:1337/admin/main.d1cae481.js:1960:34656\n20464/K/at<@http://my.local.host:1337/admin/main.d1cae481.js:1960:36229\nj@http://my.local.host:1337/admin/content-manager.c4737ca9.chunk.js:82:6290\nonClick@http://my.local.host:1337/admin/main.d1cae481.js:2471:253\nTt@http://my.local.host:1337/admin/main.d1cae481.js:1949:9884\nwe@http://my.local.host:1337/admin/main.d1cae481.js:1949:10046\nxe@http://my.local.host:1337/admin/main.d1cae481.js:1949:10108\nau@http://my.local.host:1337/admin/main.d1cae481.js:1949:31669\nOs@http://my.local.host:1337/admin/main.d1cae481.js:1949:32123\n64448/hc/<@http://my.local.host:1337/admin/main.d1cae481.js:1949:37357\nah@http://my.local.host:1337/admin/main.d1cae481.js:1952:38097\nqn@http://my.local.host:1337/admin/main.d1cae481.js:1949:9015\nhc@http://my.local.host:1337/admin/main.d1cae481.js:1949:33463\nai@http://my.local.host:1337/admin/main.d1cae481.js:1949:17530\nui@http://my.local.host:1337/admin/main.d1cae481.js:1949:17304\nEventListener.handleEvent*ud@http://my.local.host:1337/admin/main.d1cae481.js:1949:32933\nku@http://my.local.host:1337/admin/main.d1cae481.js:1949:32324\n64448/wa/<@http://my.local.host:1337/admin/main.d1cae481.js:1949:32489\nwa@http://my.local.host:1337/admin/main.d1cae481.js:1949:32434\nyi@http://my.local.host:1337/admin/main.d1cae481.js:1952:20377\nmh@http://my.local.host:1337/admin/main.d1cae481.js:1952:41350\nMh@http://my.local.host:1337/admin/main.d1cae481.js:1952:41103\nwh@http://my.local.host:1337/admin/main.d1cae481.js:1952:40972\nKf@http://my.local.host:1337/admin/main.d1cae481.js:1952:40822\nsh@http://my.local.host:1337/admin/main.d1cae481.js:1952:37826\nBa@http://my.local.host:1337/admin/main.d1cae481.js:1950:3290\n64448/Tl/<@http://my.local.host:1337/admin/main.d1cae481.js:1952:35370\nVoidFunction*Tl@http://my.local.host:1337/admin/main.d1cae481.js:1952:35347\n",
  "message": "Request failed with status code 405",
  "name": "AxiosError",
  "code": "ERR_BAD_REQUEST",
  "config": {
    "transitional": {
      "silentJSONParsing": true,
      "forcedJSONParsing": true,
      "clarifyTimeoutError": false
    },
    "adapter": [
      "xhr",
      "http"
    ],
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "maxBodyLength": -1,
    "env": {},
    "headers": {
      "Authorization": "Bearer hellothere",
      "Content-Type": "application/json"
    },
    "paramsSerializer": {},
    "baseURL": "",
    "signal": {},
    "method": "put",
    "url": "/components/posts.cc/configuration",
    "data": "{\"layouts\":{\"list\":[\"id\",\"asdf\",\"awser\",\"asdfwesrr\"],\"edit\":[[{\"name\":\"asdfwesrr\",\"size\":4},{\"name\":\"asdf\",\"size\":6}],[{\"name\":\"awser\",\"size\":4}]]},\"metadatas\":{\"id\":{\"edit\":{},\"list\":{\"label\":\"id\",\"searchable\":false,\"sortable\":false}},\"asdf\":{\"edit\":{\"label\":\"asdf\",\"description\":\"\",\"placeholder\":\"\",\"visible\":true,\"editable\":true},\"list\":{\"label\":\"asdf\",\"searchable\":true,\"sortable\":true}},\"awser\":{\"edit\":{\"label\":\"awser\",\"description\":\"\",\"placeholder\":\"\",\"visible\":true,\"editable\":true},\"list\":{\"label\":\"awser\",\"searchable\":true,\"sortable\":true}},\"asdfwesrr\":{\"edit\":{\"label\":\"asdfwesrr\",\"description\":\"\",\"placeholder\":\"\",\"visible\":true,\"editable\":true},\"list\":{\"label\":\"asdfwesrr\",\"searchable\":true,\"sortable\":true}}},\"settings\":{\"bulkable\":true,\"filterable\":true,\"searchable\":true,\"pageSize\":10,\"mainField\":\"asdf\",\"defaultSortBy\":\"asdf\",\"defaultSortOrder\":\"ASC\"}}"
  },
  "request": {},
  "response": {
    "data": "Method Not Allowed",
    "status": 405,
    "statusText": "Method Not Allowed",
    "headers": {
      "access-control-allow-credentials": "true",
      "access-control-allow-origin": "http://my.local.host:1337",
      "allow": "HEAD, GET",
      "connection": "keep-alive",
      "content-length": "18",
      "content-security-policy": "connect-src 'self' https:;img-src 'self' data: blob: market-assets.strapi.io stg.s.dgrebb.com;media-src 'self' data: blob: market-assets.strapi.io stg.s.dgrebb.com;default-src plausible.io;base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'",
      "content-type": "text/plain; charset=utf-8",
      "date": "Sun, 06 Aug 2023 16:14:30 GMT",
      "keep-alive": "timeout=5",
      "referrer-policy": "no-referrer",
      "strict-transport-security": "max-age=31536000; includeSubDomains",
      "vary": "Origin",
      "x-content-type-options": "nosniff",
      "x-dns-prefetch-control": "off",
      "x-download-options": "noopen",
      "x-frame-options": "SAMEORIGIN",
      "x-permitted-cross-domain-policies": "none",
      "x-powered-by": "Strapi <strapi.io>"
    },
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "adapter": [
        "xhr",
        "http"
      ],
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {},
      "headers": {
        "Authorization": "Bearer hellothere",
        "Content-Type": "application/json"
      },
      "paramsSerializer": {},
      "baseURL": "",
      "signal": {},
      "method": "put",
      "url": "/components/posts.cc/configuration",
      "data": "{\"layouts\":{\"list\":[\"id\",\"asdf\",\"awser\",\"asdfwesrr\"],\"edit\":[[{\"name\":\"asdfwesrr\",\"size\":4},{\"name\":\"asdf\",\"size\":6}],[{\"name\":\"awser\",\"size\":4}]]},\"metadatas\":{\"id\":{\"edit\":{},\"list\":{\"label\":\"id\",\"searchable\":false,\"sortable\":false}},\"asdf\":{\"edit\":{\"label\":\"asdf\",\"description\":\"\",\"placeholder\":\"\",\"visible\":true,\"editable\":true},\"list\":{\"label\":\"asdf\",\"searchable\":true,\"sortable\":true}},\"awser\":{\"edit\":{\"label\":\"awser\",\"description\":\"\",\"placeholder\":\"\",\"visible\":true,\"editable\":true},\"list\":{\"label\":\"awser\",\"searchable\":true,\"sortable\":true}},\"asdfwesrr\":{\"edit\":{\"label\":\"asdfwesrr\",\"description\":\"\",\"placeholder\":\"\",\"visible\":true,\"editable\":true},\"list\":{\"label\":\"asdfwesrr\",\"searchable\":true,\"sortable\":true}}},\"settings\":{\"bulkable\":true,\"filterable\":true,\"searchable\":true,\"pageSize\":10,\"mainField\":\"asdf\",\"defaultSortBy\":\"asdf\",\"defaultSortOrder\":\"ASC\"}}"
    },
    "request": {}
  }
}```

**Comment by gu-stav** [comment] 2023-08-07 10:37
Fixed by https://github.com/strapi/strapi/pull/17579

**Closed by gu-stav** 2023-08-07 10:37 UTC
