### ISSUE TITLE
Admin Crashes when user roles are accessed

### ISSUE THREAD

**Issue by ugobensaid** [strapi/strapi#16293] opened 2023-04-04 13:10 UTC
### Required System information

- Node.js version: 14.20.0
- NPM version: 6.0.0
- Strapi versions: 4.8.0, 4.8.1, 4.8.2 and 4.9.0
- Database: MySQL
- Operating system: linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When the admin roles page (/admin/settings/roles) is accessed in the settings by an admin user that does not have create or update rights for roles, the admin crashes (the whole page goes blank) and the following error is logged into dev console (twice):
when accessing the page `/admin/settings.roles` the admin crashes (the whole page goes blank) and the following error is logged into dev console (twice) :

`TypeError: (0 , h.default) is not a function
    at de (admin-roles-list.32798443.chunk.js:1:2285)
    at me (admin-roles-list.32798443.chunk.js:2:1309)
    at tf (main.57deddb7.js:1719:54446)
    at Vn (main.57deddb7.js:1723:9087)
    at hf (main.57deddb7.js:1723:987)
    at Fu (main.57deddb7.js:1723:915)
    at ko (main.57deddb7.js:1723:767)
    at bc (main.57deddb7.js:1721:10969)
    at main.57deddb7.js:1719:39312
    at x.unstable_runWithPriority (main.57deddb7.js:1751:3973)`

### Steps to reproduce the behavior

1. Go to /admin/settings/roles i.e. Settings => Administration Panel => roles
2. The page crashes

### Expected behavior

Have access to roles.

**Comment by branislav-brincko** [comment] 2023-04-04 14:53
duplicate of https://github.com/strapi/strapi/issues/16276

**Comment by derrickmehaffy** [comment] 2023-04-05 14:43
duplicate: https://github.com/strapi/strapi/issues/16276

**Closed by derrickmehaffy** 2023-04-05 14:43 UTC
Labels: status: duplicate
