### ISSUE TITLE
There is no option in content type builder to display a text as wysiyyg

### ISSUE THREAD

**Issue by rayan-nativex** [strapi/strapi#4617] opened 2019-11-28 08:42 UTC
I installed a fresh copy of strapi using the following command:
`npx create-strapi-app my-project --quickstart`,
The purpose is to test strapi's power to see if we should use it for our next project
..
I created the content type `page` and chose a text field and went to advanced settings to choose a WYSIWYG display as documentations however I couldn't find this option

![image](https://user-images.githubusercontent.com/48052862/69790659-883db480-11cb-11ea-9b14-e704582d0168.png)

**System**
- Node.js version:  10.15.1
- NPM version: 6.4.1
- Strapi version:  3.0.0-beta.17.6
- strapi-admin: "3.0.0-beta.17.6",
- strapi-plugin-content-manager : "3.0.0-beta.17.6",
- strapi-plugin-content-type-builder: "3.0.0-beta.17.6",
- database: sqlite3
- Operating system: windows 10

What am i missing here?

**Comment by derrickmehaffy** [comment] 2019-11-28 08:57
you need to create a richtext field, the WYSIWYG flag was removed in favor of a specific field for this purpose.

Marking as closed as this is not a bug.

**Closed by derrickmehaffy** 2019-11-28 08:57 UTC

**Comment by bmedici** [comment] 2020-04-17 15:11
Hi all, sorry but even with the RichText field type, I don't see any WYSIWYG option :
![image](https://user-images.githubusercontent.com/135799/79584146-49eb5800-80ce-11ea-9c6b-080fea718a76.png)
Maybe should we have Rich Markfodwn, and Rich HTML explicit types ?
Any clue?

Strapi v3.0.0-beta.20

**Comment by lauriejim** [comment] 2020-04-30 07:12
Hello! Into the docs, you will find a way to customize the WYSIWYG.
Here is a [Guide](https://strapi.io/documentation/3.0.0-beta.x/guides/registering-a-field-in-admin.html) that will let you know, how (with the first step of custom fields feature) you can replace it.
The thing that will unlock the issue is the Custom Field feature. That will let everyone create it's own fields that match your need.

**Comment by bmedici** [comment] 2020-04-30 16:47
Thank you, I'll let you know how I find the way to add it !
