### ISSUE TITLE
GraphQL File Upload Error: createReadStream is not a function

### ISSUE THREAD

**Issue by seanaye** [strapi/strapi#5284] opened 2020-02-20 19:51 UTC
**Describe the bug**
Uploading files via GrpahQL Plugin does not work. Regular file upload via GUI is fine.

```
TypeError: createReadStream is not a function

```
Stacktrace at strapiCMS/node_modules/strapi-plugin-upload/config/schema.graphql:93:18

**Steps to reproduce the behavior**
1. Send a graphql file upload 

**Expected behavior**
File should upload and return data correctly

**Code snippets**
I am scripting batch uploads via Python using GraphQL. Code modified for brevity 

```python
import httpx

with httpx.Client(base_url=MY_URL, headers={'Authorization': JWTSTRING}) as client:
    r = client.post('',
        json={
            'query': open('./gql/uploadFile.graphql').read(),
            'variables': {
                'file': 'file'
            }
        files={'file': open('./content/test/img.jpg', 'rb')}
    )
    print(r.json())
```
Where uploadFile.graphql is 

```graphql
mutation uploadFile($file: Upload!) {
    upload(file: $file) {
        id
    }
}
```
This returns
```
('{"errors":[{"message":"createReadStream is not a '
 'function","locations":[{"line":2,"column":5}],"path":["upload"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: '
 'createReadStream is not a function","    at formatFile '
 '(PROJ_PATH/node_modules/strapi-plugin-upload/config/schema.graphql:93:18)","    '
 'at async resolver '
 '(PROJ_PATH/node_modules/strapi-plugin-upload/config/schema.graphql:41:24)"]}}}],"data":null}\n')
```

**System**
- Node.js version: v12.12.0
- NPM version: 6.13.7
- Strapi version: 3.0.0-beta.18.7 
- Database: SQLlite3
- Operating system: Mac OS 10.14.6

**Comment by alexandrebodin** [comment] 2020-02-20 20:05
Hi,

The file upload is handled by apollo-serveur. You can check the server soec here:

https://github.com/jaydenseric/graphql-multipart-request-spec/blob/master/readme.md.

I’m closing this Issue as it is not a bug with strapi :) 

Let me know if you need more help ;)

**Closed by alexandrebodin** 2020-02-20 20:05 UTC

**Comment by seanaye** [comment] 2020-02-20 21:46
@alexandrebodin Thank you for the quick reply! That was very helpful.

I have implemented the spec according to the link but it returns 
```
Must provide a query string
```
as far as I can tell the spec does not provide a query string at the root of the form, only under the operations key.

I added in the query string at the root level of the form in addition to inside operations string. 
This of course returns the error that the variable is not provided even though the variables string is provided inside the operations string.

Once I add in the variables the second time (at root level just as query string) it says upload cannot be null. Though it is null in the spec. I have tried replacing the null value with the file index number and the filename, both give the original 
```
createReadStream is not a function
```

Revised code is as follows
```python
def upload(client, path, variables={'file': None}, files=['./content/test/img.jpg']):
    map_obj = {}
    if 'file' in variables:
        map_obj = {
            '0': ['variables.file']
        }
    elif 'files' in variables:
        map_obj = {
            x: [f'variables.files.{x}'] for x in range(len(variables['files']))
        }

    data={
        'operations': json.dumps({
            'query': open(path).read(),
            'variables': variables
        }),
        'map': json.dumps(map_obj),
        'query': open(path).read(), # Causes query string error if omitted
        'variables': json.dumps(variables), # causes variable error if omitted
        **{str(x): open(files[x], 'rb') for x in range(len(files))}
    }
    r = client.post('', data=data)
    return r.text
```

I appreciate you taking the time to help.

Thanks. :)

**Comment by seanaye** [comment] 2020-02-20 21:56
Please disregard the above. I was passing a file stream object without reading the data.
httpx supports passing file stream objects with the files property

Working code as follows

```python
def upload(client, path, variables={}, files=[]):
    map_obj = {}
    if 'file' in variables:
        map_obj = {
            '0': ['variables.file']
        }
    elif 'files' in variables:
        map_obj = {
            x: [f'variables.files.{x}'] for x in range(len(variables['files']))
        }

    data={
        'operations': json.dumps({
            'query': open(path).read(),
            'variables': variables
        }),
        'map': json.dumps(map_obj),
    }
    r = client.post('', data=data, files={str(x): open(files[x], 'rb') for x in range(len(files))})
    return r.json()
```

Sorry if this was off topic but hopefully it helps someone!

**Comment by alexandrebodin** [comment] 2020-02-21 09:18
I'm sure this will be useful for some users ;)

**Comment by dimer191996** [comment] 2021-04-05 07:08
wtf man
