### ISSUE TITLE
beforeDestroy() callback not receiving any model data in 3.0.0-beta.18.4

### ISSUE THREAD

**Issue by michalbakowski-monterail** [strapi/strapi#4989] opened 2020-01-14 09:29 UTC
**Describe the bug**

`beforeDestroy()` model callback stopped receiving model any data.

It used to work in `3.0.0-beta.17.8` and has stopped after upgrading to `3.0.0-beta.18.4`

Databases tested: PostgreSQL, SQLite

**Steps to reproduce the behavior**

1. Clone example repository: https://github.com/michalbakowski-monterail/ghbugs-strapi-4989
2. Enter admin panel
3. Click "BlogPosts" on the left menu
4. Create new `BlogPost` - any data
5. Click new `BlogPost` again, to enter edit mode
6. Click "Delete" and Confirm
7. Check console logs
    - `/api/blog-post/models/blog-post.js` has `beforeDestroy()` callback that logs data to console

**Expected behavior**

Expecting to see in logs BlogPost model data, like `id`, `title`, `some_number`

Example:
```
[Object: null prototype] {
    id: 1,
    title: 'Foo',
    some_number: 123
}
```

But receiving:

```
[Object: null prototype] {}
```

this way I cannot perform any check that will determine if I want to allow to delete a BlogPost entry

**Code snippets**

https://github.com/michalbakowski-monterail/ghbugs-strapi-4989

**System**
- Node.js `v10.18.0`
- NPM version: `6.13.4`
- Strapi version: `3.0.0-beta.18.4`
- Database: SQLite, PostgreSQL 9.6
- Operating system: MacOS 10.14.6 (Mojave)

**Comment by derrickmehaffy** [comment] 2020-01-14 09:33
@michalbakowski-monterail Lifecycle callbacks have been broken for some time now (and will continue to be until they are reviewed which should be here soon as I think the Strapi team intends to look at them and migrate them to the new `strapi-database` package and decouple them from the ORMs).

My suggestion to you would be to do any `beforeDelete` logic by overriding the default DELETE controller (Docs here: https://strapi.io/documentation/3.0.0-beta.x/concepts/controllers.html#delete )

For now I'm going to mark this as a duplicate of this issue which is the master Lifecycle callback review issue: https://github.com/strapi/strapi/issues/1443

**Closed by derrickmehaffy** 2020-01-14 09:33 UTC

**Comment by michalbakowski-monterail** [comment] 2020-01-14 09:35
@derrickmehaffy OK.

Thanks for the info :)

I will delay upgrading Strapi in my project, and stay with working version for some time
