### ISSUE TITLE
Error for other api relation with collation user after change user in content type builder

### ISSUE THREAD

**Issue by mehdiraized** [strapi/strapi#4787] opened 2019-12-21 09:09 UTC
**Describe the bug**
after save collection user in content type builder remove this line other models
"plugin": "users-permissions"

**Steps to reproduce the behavior**
1. Go to 'content type builder'
2. Click on 'user'
3. Click Add another field or edit fields
4. Click Save
5. After Restart strapi not run
6. Error for other api relation with collation user
6. in models.json see remove line "plugin": "users-permissions" in relation user

**System**
- Node.js version: v12.8.0
- NPM version: 6.13.4
- Strapi version: 18.2
- Database: Mysql
- Operating system: MacOs

**Comment by derrickmehaffy** [comment] 2019-12-23 06:53
closing as duplicate of https://github.com/strapi/strapi/issues/1443

(All lifecyle issues are being closed and linked to the above issue)

**Comment by alexandrebodin** [comment] 2019-12-23 08:45
@derrickmehaffy I'm pretty sure this has nothing to do with lifecycles mate :). Re opening

**Comment by alexandrebodin** [comment] 2019-12-23 08:46
@mehdiraized Can you share a specific use case (what field to add etc) and what error you get in the terminal

**Comment by mehdiraized** [comment] 2019-12-23 11:17
> @mehdiraized Can you share a specific use case (what field to add etc) and what error you get in the terminal

```
[2019-12-23T11:15:38.325Z] info File changed: /backend/api/factor/models/Factor.settings.json
[2019-12-23T11:15:38.333Z] info The server is restarting

[2019-12-23T11:15:44.611Z] error Something went wrong in the model `Factor` with the attribute `user`
[2019-12-23T11:15:44.615Z] error TypeError: Cannot read property 'attributes' of undefined
    at Object.getNature (/backend/node_modules/strapi-utils/lib/models.js:150:33)
    at /backend/node_modules/strapi-connector-bookshelf/lib/mount-models.js:156:21
    at Array.forEach (<anonymous>)
    at /backend/node_modules/strapi-connector-bookshelf/lib/mount-models.js:149:40
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Promise.all (index 3)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async DatabaseManager.initialize (/backend/node_modules/strapi-database/lib/database-manager.js:39:7)
    at async Strapi.load (/backend/node_modules/strapi/lib/Strapi.js:362:5)
    at async Strapi.start (/backend/node_modules/strapi/lib/Strapi.js:196:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mehdiraized** [comment] 2019-12-23 11:20
i manually change Factor.setting.json file
```
    "user": {
      "via": "factors",
      "model": "user"
    },
```
to 
```
    "user": {
      "via": "factors",
      "model": "user",
      "plugin": "users-permissions"
    },
```
This problem is solved

**Closed** 2019-12-23 12:21 UTC
