### ISSUE TITLE
TypeError: Cannot read property 'sizeOptimization' of null

### ISSUE THREAD

**Issue by PatricSPires** [strapi/strapi#9328] opened 2021-02-05 15:50 UTC
### Describe the bug
I'm trying to upload a file to my strapi project, but I received an error 500 and console show `TypeError: Cannot read property 'sizeOptimization' of null`

### Steps to reproduce the behavior

1. Go to media library
2. Click on 'upload assets'
3. Click on 'browser files' and select the file
4. See an error 500 in the console on the editor code.

### Expected behavior

Complete the upload file.

### Screenshots

![Strapi error](https://user-images.githubusercontent.com/23489471/107055975-9d8b7700-67b0-11eb-9c09-b579f1c9c047.jpg)

### System

- Node.js version: 12.20.1
- NPM version: 6.14.10
- Strapi version: 3.4.1
- Database: Postgrsql
- Operating system: Ubuntu 19.04

**Comment by derrickmehaffy** [comment] 2021-02-05 19:55
> Strapi version: 3.4.1

Can you please test on the latest release

**Comment by PatricSPires** [comment] 2021-02-08 20:17
@derrickmehaffy I have updated and receive the same error. Each time that I click on "settings/media library" I receive the error and the page keeps blank;

**Comment by demsullivan** [comment] 2021-03-09 14:53
I'm getting the same issue, using the aws-s3 upload provider, and using the official Strapi docker images, running Strapi 3.5.2

**Comment by brownstonetech** [comment] 2021-04-04 21:02
I encountered this too when upload file to media library. I'm using aws-s3 upload provider, running strapi in docker container.
 Project information

┌────────────────────┬──────────────────────────────────────────────────┐
│ Time               │ Sun Apr 04 2021 08:15:34 GMT+0000 (Coordinated … │
│ Launched in        │ 4048 ms                                          │
│ Environment        │ production                                       │
│ Process PID        │ 61                                               │
│ Version            │ 3.5.4 (node v12.20.1)                            │
│ Edition            │ Community                                        │
└────────────────────┴──────────────────────────────────────────────────┘

**Comment by demsullivan** [comment] 2021-04-06 12:37
This seems to have resolved itself for me... after it was resolved, I was getting an Access Denied error from AWS, which turned out to be caused by a policy that didn't grant all of the correct permissions to my access key.

I dug into the source for the Stapi upload plugin and discovered that what's happening here is that the plugin is retrieving some settings from the database. You can verify if those settings exist in the database like so:

```
$ npx strapi console
> strapi.store({ type: 'plugin', name: 'upload', key: 'settings').get().then(s => console.dir(s));
```

This should return an object that has the `sizeOptimization` and `responsiveDimensions` keys - mine did. Otherwise, maybe setting it manually would help?

`strapi.store({ type: 'plugin', name: 'upload', key: 'settings').set({ sizeOptimization: true, responsiveDimensions: true });`

Hopefully this helps the others encountering this issue.

**Comment by kulahad** [comment] 2021-04-13 00:05
Creating the `uploads` folder in the `public` folder resolved the issue for us.

**Comment by derrickmehaffy** [comment] 2021-04-18 02:56
two confirmations that it's working, marking as closed.

**Closed by derrickmehaffy** 2021-04-18 02:56 UTC
Labels: severity: low, source: plugin:upload, status: pending reproduction, type: bug

**Comment by nagman** [comment] 2021-09-01 12:36
I don't agree with this closed status.
I had the same issue, and it seemed related to the active connections with the s3 (a minio instance on a kubernetes cluster).
My local strapi instance were already connected to the staging s3, and my staging strapi instance weren't able to upload on the s3.
Yet the only error I got was the same as @PatricSPires 
I simply solved it by... stopping my local instance.
But this isn't a consistent behavior because I have been able to restart my local strapi and the staging upload was still working.
Very strange...

**Comment by stafyniaksacha** [comment] 2021-09-16 17:31
This issue still exists: it occurs because https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/services/Upload.js#L378 return undefined instead of an empty object when no settings are found

Then destructuring on undefined raise `TypeError: Cannot read property 'sizeOptimization' of null`
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/services/image-manipulation.js#L63

The workaround is to go in the admin panel and update any settings of media plugin

**Comment by derrickmehaffy** [comment] 2021-09-16 21:19
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.
