### ISSUE TITLE
(Russian cyrillic) ERROR on save  - Content Type name cannot be pluralized

### ISSUE THREAD

**Issue by reslear** [strapi/strapi#7098] opened 2020-07-21 12:16 UTC
**Describe the bug**

**Steps to reproduce the behavior**

1. Go to 'http://localhost:1337/admin/plugins/content-type-builder/'
2. Click on 'content-type edit'
3. change name in cyr symbols "Заказы"
4. Click on 'Save'
5. See error in console

**Expected behavior**
`payload: error: contentType.name`
`Content Type name "Заказы" cannot be pluralized. 
Suggestion: add Item after the name (e.g News -> NewsItem).`

**Screenshots**
![Снимок экрана 2020-07-21 в 15 14 00](https://user-images.githubusercontent.com/12596485/88053676-dd687500-cb64-11ea-8117-9232e93145af.png)

**System**

- Node.js version: v12.16.3
- NPM version: latest
- Strapi version: 3.0.6
- Database: postgres
- Operating system: macos

**Comment by lacoste-sochi** [comment] 2020-07-29 19:33
Please correct the error ....

I write strapi + nuxtjs, everything is very happy, but the error spoils the impression ...

You are the best!!! =)

**Comment by lauriejim** [comment] 2020-07-31 12:09
Hello! It's not planned to support this.
In fact, we should avoid the possibility to have other that Latin characters as Content-Type name (for now)
@petersg83 @alexandrebodin probably something easy to fix.

**Comment by reslear** [comment] 2020-08-02 21:51
> Hello! It's not planned to support this.
> In fact, we should avoid the possibility to have other that Latin characters as Content-Type name (for now)
> @petersg83 @alexandrebodin probably something easy to fix.
thx for answer 
unstable, but worked on previous versions (last beta), maybe need to make another text field label without pluralization and regexp check, for good visualization in the sidebar post types multi-language.
<img width="428" alt="Снимок экрана 2020-08-03 в 00 29 44" src="https://user-images.githubusercontent.com/12596485/89133295-61d2d480-d523-11ea-86cd-5d9e4203d017.png">

**Comment by Ashot-KR** [comment] 2020-09-07 21:43
@reslear  i have made some investigations.
Actually issue not in cyrillic, any non-latin words will throw error.
[pluralize library](https://www.npmjs.com/package/pluralize) works well with english, but will made wrong plurals for other languages. For example Czech: `kniha -> knihy`, but `pluralize` will return `knyhas`, which is wrong.

I found a little workaround (**but it's not ideal!** you will see explanation at the end of comment):
`pluralize` library has `addPluralRule` which allows to add custom rules for pluralization.
So we can preconfigure `pluralize` lib:
1. edit `config/functions/bootstrap.js` file:
```js
const pluralize = require('pluralize')

module.exports = () => {
  // add any rules. First argument is Regex, second is string to replace
  pluralize.addPluralRule(/я$/i, 'и')
  pluralize.addPluralRule(/мышь$/i, 'мыши')
};
```
2. create collection type in content-type builder, but type in `Article` as display name(**at this point i recommend use english, so stapi generate folders/files/rotes/etc with proper names**).
3. open articles content type edit dialog and set `статьи` as display name. save it.
4. voila! we have properly names
![image](https://user-images.githubusercontent.com/899218/92417434-c7d9f980-f16a-11ea-9ad9-8b2f106bb4a0.png)

But there is a bad thing i mentioned above: we have mis grammars in other places 😄 
![image](https://user-images.githubusercontent.com/899218/92417514-4a62b900-f16b-11ea-9476-37d77744278a.png) ![image](https://user-images.githubusercontent.com/899218/92417523-5484b780-f16b-11ea-9a5a-e4b062b18853.png)

This method can be used for any language.

**Comment by reslear** [comment] 2020-09-08 07:47
@Ashot-KR wow, good temporary solution 🎉
@lauriejim @alexandrebodin Please consider the idea of creating an additional field for the Label only for display in the admin panel

**Comment by iksent** [comment] 2020-10-20 17:25
This is a very important issue: If you change "info.name" (to smth, that can't be pluralized) from the code at .json file, then you can't add new fields to this content type.
Please, fix this asap.

**Comment by smwbtech** [comment] 2020-10-28 12:20
One of my project was on Strapi 3.0.0-beta.19. I got some free time and now want migrate for last and stable version. As code base was not large I started start from scratch, but I stuck with this problem. It would be nice to have extra field for side bar label.

**Comment by sam-pires** [comment] 2020-10-28 16:36
Hello everyone, thanks for your feedback.
We have an RFC (Request For Comments) about the pluralization topic in general. If you want to take part in the discussion and share feedback and suggest ideas you can do it there too :) 
https://github.com/strapi/rfcs/issues/18

**Comment by iksent** [comment] 2020-10-28 19:52
@sam-pires, hi! This issue is probably not about feature for pluralising and internationalising, but about fixing an error, which occurs when you trying to save content type with Cyrillic display name.

**Comment by fouber** [comment] 2021-01-15 03:37
Is it possible to add a property called "displayName" to model.settings.json, and it will be used to display the collection name in admin left menu. Sometimes, in other countries and regions, the collection name needs to be displayed in a different language

**Comment by fouber** [comment] 2021-01-15 04:22
> Is it possible to add a property called "displayName" to model.settings.json, and it will be used to display the collection name in admin left menu? Sometimes, in other countries and regions, the collection name needs to be displayed in a different language

I have found a way to fix this problem, hope it will be helpful to others:

1. ``mkdir -p admin/src/translations``
2. ``cp node_modules/strapi-admin/admin/src/translations/en.json admin/src/translations``
3. add displayName in ``admin/src/translations/en.json``.
 
e.g. your collectionName is ``books`` then add a key-value in en.json such as:

```json
{
   ...
   "Books": "图书"
}
```

strapi-admin decides whether to display i18n strings based on the key which defined only in en.json ( see the [code](https://github.com/strapi/strapi/blob/edc9aacf4b15497cda27961bb60415bd624937bb/packages/strapi-admin/admin/src/components/LeftMenu/LeftMenuLink/LeftMenuLinkContent.js#L35-L47) ), so if you want to change the display name of collection, you must add it into the en.json file

**Comment by budlight** [comment] 2021-03-28 03:10
This is pretty closely related to #1198

**Comment by derrickmehaffy** [comment] 2021-03-29 19:06
closing as duplicate of https://github.com/strapi/strapi/issues/1198 (ty again @budlight)

**Closed by derrickmehaffy** 2021-03-29 19:06 UTC
Labels: good first issue, severity: low, source: plugin:content-type-builder, status: confirmed, type: bug
