### ISSUE TITLE
TypeError: Cannot delete property 'regex' of #<Object>

### ISSUE THREAD

**Issue by ssoftwares** [strapi/strapi#9257] opened 2021-01-29 10:10 UTC
### TypeError: Cannot delete property 'regex' of #<Object>

This bug started coming after updating strapi to 3.4.5

### Screenshots

![image](https://user-images.githubusercontent.com/71498747/106261552-b7c0d480-6247-11eb-825d-16edfbcd8601.png)

### Code snippets
Regex Used are :
For Username : ^[a-z]+$
For domain: ^((?:([a-z0-9]\.|[a-z0-9][a-z0-9\-]{0,61}[a-z0-9])\.)+)([a-z0-9]{2,63}|(?:[a-z0-9][a-z0-9\-]{0,61}[a-z0-9]))\.?$
For Email: I have selected inbuilt content type for email which have pre built regex i think.

### System

- Node.js version: 14.15.2
- NPM version:  6.14.11
- Strapi version: 3.4.5
- Database: slqlite
- Operating system: Linux (CentOs)

**Comment by avdeyev** [comment] 2021-01-29 11:12
The same issue for 3.4.5/mongoDB
One field with regex  "^\\d{1,2}\\.\\d{1,2}$" and one 'email' field

**Comment by endrehegyi** [comment] 2021-01-29 11:21
Yup same issue with 3.4.5 SQLite, text field with regex enabled to contain URL slugs.

**Comment by wedneyyuri** [comment] 2021-01-29 11:39
It's a duplicate of https://github.com/strapi/strapi/issues/9236

**Comment by soupette** [comment] 2021-01-29 12:04
Thank you @wedneyyuri for linking the original issue. I am closing this one as then.

**Closed by soupette** 2021-01-29 12:04 UTC
Labels: source: plugin:content-manager, status: duplicate
