### ISSUE TITLE
How to handle AVPlayer - Strapi communication

### ISSUE THREAD

**Issue by sebinq** [strapi/strapi#5552] opened 2020-03-20 08:47 UTC
Hello.

I'm developing an API server for my React Native application using strapi. I have table, which contains uploaded video file (.mp4 format) and now I'm having following problem:

1. React Native fetches data and saves video url in order to obtain it from my server.
2. I'm trying to play this video using AVPlayer (react-native-video uses AVPlayer for IOS).

I keep getting **-11850 AVFoundationErrorDomain**  error and video cannot be played (even if it works perfectly in chrome or any other browser).

So I've tried to find a fix for this sitution and I found [following topic on stackoverflow](https://stackoverflow.com/a/42244954), which says that there is most probably some HTTP communication missmatch between AVPlayer and strapi endpoint for serving static files. To be more concrete, there is a relevant paragraph:

> So, we should understand that this is a server problem.
> 
> Now, we play a video, and grab all http request for analysis.
>
> Will find that AVPlayerItem sends an HTTP request.
>
> when AVPlayerItem receive a video URL , it do the following task:
>
> 1. Send a bytes request HTTP Request, and range = 0 -1
> 2. If the response code is 206 and return 1 bytes data, It do the 3th task, if not, AVErrorServerIncorrectlyConfigured error occurred.
> 3. continue send other HTTP Request, to download segment of All duration. and the response of VideoData code must be 206
>
> In my situation , when send range[0-1] HTTP request, the server side give me a 200 OK response, So error occurred.

I've created github issue instead of stackoverflow thread because I found that [someone else already had this issue](https://stackoverflow.com/questions/48267519/how-to-use-strapi-to-create-video-streaming-server) but he didn't get any follow.

I would like to ask you if anyone knows or is able to help me solve this kind of problem.

Thank you so much!

**Comment by derrickmehaffy** [comment] 2020-03-20 09:15
Closing as a duplicate of: https://github.com/strapi/strapi/issues/2246

**Closed by derrickmehaffy** 2020-03-20 09:15 UTC

**Comment by rintsyman** [comment] 2020-05-15 14:04
Your url on stackOverFlow helps me to solve my AVFoundationErrorDomain problem.
In fact the problem comes from the fact that the http server response, react native video does not allow to play the video as an image file with only one request and status 200, it needs to make the call little by little to load the video, so if your server returns status 200 after the call, react native video returns the AVFoundationErrorDomain error.
Solution you need to configure your server with proxy_force_ranges on 
after this configuration your server returns 206
