### ISSUE TITLE
types autogeneration fails on adding new content types

### ISSUE THREAD

**Issue by Demacri** [strapi/strapi#17084] opened 2023-06-23 14:54 UTC
### Required System information

- Node.js version: 18.16.0
- NPM version: 9.5.1
- Strapi version: 4.11.2
- Database: postgres 
- Operating system: windows
- Is your project Javascript or Typescript: typescript

### Describe the bug

Related to the new generating type system: https://github.com/strapi/strapi/pull/16917
Enabling this feature, autogeneration seems to be not correctly handled.
Running strapi in development mode and adding a new content type, the server reloads but it crashes because of new collection types are not added to contentTypes.d.ts .

### Steps to reproduce the behavior
0. add config/typescript.ts file with the following content:
`
export default ({ env }) => ({
  autogenerate: true,
});
`
1. generate types first time using "npm run strapi ts:generate-types"
2. run strapi using "npm run develop"
3. Go to admin/plugins/content-type-builder/content-types
4. Add a new collection with any name and any field(s).
5. Save, the server will try to restart
6. See error:
Argument of type '"api::entityname.entityname"' is not assignable to parameter of type 'ContentType'.
 export default factories.createCoreService('api::entityname.entityname');

### Expected behavior

Strapi should generate the new content types before restarting the server, avoiding the typescript error.

### Screenshots

![image](https://github.com/strapi/strapi/assets/9558528/cbd610d2-f5fc-411b-b31b-34d0d880fc46)
![image](https://github.com/strapi/strapi/assets/9558528/580a7a06-ce74-4089-aa89-398e10448cc0)

**Comment by ProfXponent** [comment] 2023-06-27 08:17
also experiencing this error

**Comment by ProfXponent** [comment] 2023-06-27 10:09
> also experiencing this error

marking a comment as spam when your CI can't catch a breaking change to your type system is a strange priority

this issue is preventing builds on 4.11.2, more than likely due to a race condition between your build task and ts type gen.

only resolution was to roll back to a previous version

**Comment by Convly** [comment] 2023-06-30 12:19
Hey @Demacri, thanks for reporting this issue. We actually stumbled upon this one recently internally and will be looking for a fix soon :slightly_smiling_face: 

@ProfXponent The type autogeneration is an experimental feature that's expected to have potential issues and bugs.

```ts
  /**
   * TypeScript automatic type generation upon dev server restart
   * Its implementation, configuration and behavior can change in future releases
   * @experimental
   */
```

However, I believe there has indeed been some miscommunication on our side as it's not marked as such in our documentation. I'll submit a PR to fix this and prevent anyone to consider it as stable.

**Closed** 2023-09-16 10:45 UTC
Labels: issue: bug, severity: low, status: confirmed, source: typescript

**Comment by Demacri** [comment] 2023-09-18 16:33
Just updated to 4.13.6, still able to reproduce the issue. Same environment as before.
config/typescript.ts
```
export default ({ env }) => ({
  autogenerate: true,
});
```
I successfully start the application the first time but as soon as i create a new entity, the following happens:
![image](https://github.com/strapi/strapi/assets/9558528/58aade6a-557e-4d06-abda-2a619d410911)

(after the error, if i delete the generated types and restart the app. it regenerates everything and it starts successfully).

**Comment by Convly** [comment] 2023-09-25 12:24
Hey, the fix was released in 4.13.7, not 4.13.6. Could you try this version instead, please?
Also, you don't need the typescript configuration file (with the autogenerate). Types are always generated in dev mode now.

**Comment by KonradNojman** [comment] 2023-10-08 17:10
Had the same issue with Strapi v4.13.6. I can confirm, updating to 4.13.7 resolves the problem! Thanks @Convly!

**Comment by entelostre** [comment] 2023-11-08 20:27
Happens in Strapi v4.15.2 too

**Comment by aaronksaunders** [comment] 2023-11-20 22:41
still happening in 4.15.4, not sure why this is closed.

**Comment by cuijie27** [comment] 2023-11-28 04:01
I have the same error in 4.15.4

**Comment by BriceN** [comment] 2023-11-28 14:16
Same in 4.15.4

**Comment by Convly** [comment] 2023-12-01 15:06
Hey @lopermo, I've just tested the behavior on 4.15.5 and everything seems to be working.

If you appear to have a similar issue, could you open a new one?

**Comment by sotoyjuan** [comment] 2024-01-05 19:32
Having the same issue in 4.15.5
