### ISSUE TITLE
Strapi can't handle basic authorization header with bearer token

### ISSUE THREAD

**Issue by 99michel99** [strapi/strapi#13234] opened 2022-05-04 09:32 UTC
### Required System information

- Node.js version: v14.18.2
- NPM version: 6.14.15
- Strapi version: 4.1.7
- Database: PostgresQL
- Operating system: Rocky Linux 8

### Describe the bug

When the requesting server uses basic authentication and sends an authorization header with "Basic [TOKEN]" and "Bearer [TOKEN]" the server doesn't separate the 2 and responds with 401. This happens when using Nuxt as a frontend with an Nginx reverse proxy and HTTP basic authentication.

### Steps to reproduce the behavior

Send a GET request to /users/me with a valid JWT token together with a valid basic token like "Basic [TOKEN], Bearer [TOKEN]".

### Expected behavior

The user data should be returned

**Comment by derrickmehaffy** [comment] 2022-05-05 21:06
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [[Canny](https://feedback.strapi.io/)[](https://feedback.strapi.io/)](https://feedback.strapi.io//).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.

**Closed by derrickmehaffy** 2022-05-05 21:06 UTC

**Comment by 99michel99** [comment] 2022-05-06 07:46
I wouldn't exactly call this a feature request, it's a basic feature of webserver

**Comment by derrickmehaffy** [comment] 2022-05-24 00:07
> I wouldn't exactly call this a feature request, it's a basic feature of webserver

Strapi isn't a web server

**Comment by 99michel99** [comment] 2022-05-24 08:22
> > I wouldn't exactly call this a feature request, it's a basic feature of webserver
> 
> Strapi isn't a web server

But Strapi is advertised to work with an NGINX reverse proxy, it not supporting NGINX's basic HTTP authentication seems like a bug to me.

**Comment by derrickmehaffy** [comment] 2022-05-25 18:30
It's not a bug, it would be a feature as it's an entirely different authentication scheme with it's own requirements, parsing, ect. 

Usage with Nginx is for it's proxying options, not it's authentication scheme.

I'm gonna set this issue as closed, if you would like to put in the feature request please do so on our feature request website linked above. Thanks :)
