### ISSUE TITLE
Can't create a component category

### ISSUE THREAD

**Issue by jsellam** [strapi/strapi#16691] opened 2023-05-11 14:01 UTC
### Required System information
Node 
NPM 

- Node.js version: 18.12.1
- NPM version: 8.19.2
- Strapi version: 4.10.4
- Database: sqlLite (--quickstart)
- Operating system: Mac os (tested on chrome and safari)
- Is your project Javascript or Typescript: javascript

### Describe the bug
I can't create a component category as you can see on this video

### Steps to reproduce the behavior

1. Go to 'content type builder'
2. Click on 'new component'
3. Click on 'create new component'
4. Enter a component name and a category name
5. Click on 'add first first field'
6. See error

### Expected behavior

The component should be created

### Screenshots

https://github.com/strapi/strapi/assets/26770991/29a70db4-1fbc-4d63-b8db-1af26488c191

**Comment by joshuaellis** [comment] 2023-05-11 14:09
Duplicate of #16677

**Closed by joshuaellis** 2023-05-11 14:09 UTC
