### ISSUE TITLE
API Token doesn't work (Missing or invalid credentials)

### ISSUE THREAD

**Issue by bastien70** [strapi/strapi#14649] opened 2022-10-18 09:27 UTC
## Bug report

Hello ! I'm trying Strapi, and his API token support.
I followed this video https://www.youtube.com/watch?v=dVQKqZYWyv4
I reproduces the same thing but I've a `UnauthorizedError`.

### Required System information

- Node.js version: 18.7.0
- NPM version: 8.15.0
- Strapi version: 4.4.3
- Database: /
- Operating system: Ubuntu 22.04

### Steps to reproduce the behavior

Just reproduce https://www.youtube.com/watch?v=dVQKqZYWyv4 steps in a fresh install

### Video

https://user-images.githubusercontent.com/53140475/196392303-141c58a2-38fd-4cb6-99ff-458f26979a46.mp4

EDIT : Here it is strange, I started again, and now it works. I have no explanation as to the origin of the problem unfortunately.

**Comment by Convly** [comment] 2022-10-18 11:22
Hi,

I've tried to reproduce it but couldn't. (using a brand new strapi app and a dummy post content type).

One thing I've noticed is that at 0:23 you get a 401 response which means the token has an invalid format.
I'm not using insomnia, but maybe you forgot to put "Bearer" as a prefix value in the input?

**Comment by Convly** [comment] 2022-10-18 11:24
Just saw your edit, basically you get a 401 if the token is not recognized and a 403 if the token is recognized but doesn't have the required permissions.

**Comment by Convly** [comment] 2022-10-18 11:24
(Closing the issue as I could not reproduce)

**Closed by Convly** 2022-10-18 11:24 UTC
