### ISSUE TITLE
Strapi crash on heroku after upgrading to 3.0.0-beta.19.4

### ISSUE THREAD

**Issue by jbty** [strapi/strapi#5669] opened 2020-04-01 00:40 UTC
hi ,

I recently upgraded strapi to 3.0.0-beta.19.4, my api is hosted to heroku and nothing work since i've updated strapi version.

here is heroku errors logs 👍 
```
2020-04-01T00:30:13.592927+00:00 heroku[web.1]: Restarting
2020-04-01T00:30:16.908702+00:00 app[web.1]: 
2020-04-01T00:30:16.908727+00:00 app[web.1]: > ai-workout-gen-api@1.0.2 start /app
2020-04-01T00:30:16.908727+00:00 app[web.1]: > strapi start
2020-04-01T00:30:16.908728+00:00 app[web.1]:
2020-04-01T00:30:25.923297+00:00 app[web.1]: 
2020-04-01T00:30:25.923311+00:00 app[web.1]: > ai-workout-gen-api@1.0.2 start /app
2020-04-01T00:30:25.923311+00:00 app[web.1]: > strapi start
2020-04-01T00:30:25.923311+00:00 app[web.1]:
2020-04-01T00:30:48.918543+00:00 app[web.1]: [2020-04-01T00:30:48.917Z] debug ⛔️ Server wasn't able to start properly.
2020-04-01T00:30:48.919616+00:00 app[web.1]: [2020-04-01T00:30:48.919Z] error Error connecting to the Mongo database. Server selection timed out after 30000 ms
2020-04-01T00:30:48.930023+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-04-01T00:30:48.930344+00:00 app[web.1]: npm ERR! errno 1
2020-04-01T00:30:48.931532+00:00 app[web.1]: npm ERR! ai-workout-gen-api@1.0.2 start: `strapi start`
2020-04-01T00:30:48.931671+00:00 app[web.1]: npm ERR! Exit status 1
2020-04-01T00:30:48.931856+00:00 app[web.1]: npm ERR!
2020-04-01T00:30:48.931989+00:00 app[web.1]: npm ERR! Failed at the ai-workout-gen-api@1.0.2 start script.
2020-04-01T00:30:48.932129+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-04-01T00:30:48.940629+00:00 app[web.1]:
2020-04-01T00:30:48.940682+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-04-01T00:30:48.940739+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-04-01T00_30_48_932Z-debug.log
2020-04-01T00:30:57.499952+00:00 heroku[web.1]: State changed from starting to crashed
2020-04-01T00:30:57.386206+00:00 app[web.1]: [2020-04-01T00:30:57.385Z] debug ⛔️ Server wasn't able to start properly.
2020-04-01T00:30:57.387133+00:00 app[web.1]: [2020-04-01T00:30:57.387Z] error Error connecting to the Mongo database. Server selection timed out after 30000 ms
2020-04-01T00:30:57.401159+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2020-04-01T00:30:57.401719+00:00 app[web.1]: npm ERR! errno 1
2020-04-01T00:30:57.402780+00:00 app[web.1]: npm ERR! ai-workout-gen-api@1.0.2 start: `strapi start`
2020-04-01T00:30:57.402968+00:00 app[web.1]: npm ERR! Exit status 1
2020-04-01T00:30:57.403183+00:00 app[web.1]: npm ERR!
2020-04-01T00:30:57.403422+00:00 app[web.1]: npm ERR! Failed at the ai-workout-gen-api@1.0.2 start script.
2020-04-01T00:30:57.403552+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-04-01T00:30:57.411911+00:00 app[web.1]:
2020-04-01T00:30:57.412206+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-04-01T00:30:57.412363+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-04-01T00_30_57_404Z-debug.log
```

My prod and dev config
```
{
  "defaultConnection": "default",
  "connections": {
    "default": {
      "connector": "mongoose",
      "settings": {
        "database": "xxxxxxxxxx",
        "uri": "mongodb://xxxxxx@xxxx-shard-00-00-uarvq.mongodb.net:27017,workoutgen-shard-00-01-uarvq.mongodb.net:21117,workoutgen-shard-01-02-uardvq.mongodb.net:27017/test?ssl=true&replicaSet=WorkoutGen-shard-0&authSource=admin&retryWrites=true&w=majority"
      },
      "options": {
        "ssl": true
      }
    }
  }
}
```

All ip is whitelisted in atlas, 
I do not know what to do :(

**Comment by derrickmehaffy** [comment] 2020-04-01 05:24
closing as duplicate of: https://github.com/strapi/strapi/issues/5652

**Closed by derrickmehaffy** 2020-04-01 05:24 UTC

**Comment by jbty** [comment] 2020-04-01 12:16
config/environments/production/server.json

for heroku your host and port values must be looks like this: 
"host": "0.0.0.0", 
"port": "${process.env.PORT}",

Work fine !  have a nice day
