### ISSUE TITLE
Error after upgrade from v3.5.4 to v3.6.0

### ISSUE THREAD

**Issue by bram-abe** [strapi/strapi#10122] opened 2021-04-23 15:07 UTC
### Describe the bug

After migrate from v3.5.4 to v.3.6.0 the page (admin UI) not showing anything, just white/plain page.
so I try to remove the custom admin folder, then the login page can appear but after the login process the admin UI page still not showing anything.

### Steps to reproduce the behavior

1. changing version in dependencies.
2. remove the old build 
3. run npm build
4. run npm develop

OR

1. changing version in dependencies.
2. remove the old build 
3. remove the custom admin folder
3. run npm build
4. run npm develop

### Expected behavior

It should run properly after changing version in dependencies file as usual.

### Error console

```
Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at t.n.render (main.c0b10731.chunk.js:1)
    at Fi (main.c0b10731.chunk.js:1)
    at Ii (main.c0b10731.chunk.js:1)
    at gl (main.c0b10731.chunk.js:1)
    at cs (main.c0b10731.chunk.js:1)
    at ls (main.c0b10731.chunk.js:1)
    at Xl (main.c0b10731.chunk.js:1)
    at main.c0b10731.chunk.js:1
    at t.unstable_runWithPriority (main.c0b10731.chunk.js:1)
    at Vo (main.c0b10731.chunk.js:1)
main.c0b10731.chunk.js:1 Here is some infos
main.c0b10731.chunk.js:1 
```

### System

- Node.js version: 14.16.0 LTS
- NPM version: 6.14.12
- Strapi version: 3.6.0
- Database: postgres
- Operating system: windows 10

**Comment by Igal-Kleiner** [comment] 2021-04-24 17:12
Did you try to execute `npm run build --clean`?

**Comment by TasosBak** [comment] 2021-04-26 15:46
I came across a similar error regarding ErrorBoundary. I had a custom admin\src\containers\PluginDispatcher\index.js and in that file the change that the team made was to go from 
import ErrorBoundary from '../ErrorBoundary'; to
import { ErrorBoundary } from 'react-error-boundary';

so I suggest you search where that import exists in your custom admin pages.

Here is where I found how it is supposed to be after the update
[PluginDispatcher/index.js](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/containers/PluginDispatcher/index.js)

**Comment by bram-abe** [comment] 2021-04-27 06:46
@TasosBak 

I was remove node_modules, package-lock.json, build folder, and run new install with 3.6.0 deps.
and then follow ur guide, now the page can show ADMIN UI but showing new error like below :
```
main.13157256.chunk.js:1 TypeError: Cannot read property 'collectionTypesRelatedPermissions' of undefined
    at t.selectCollectionTypePermissions (main.13157256.chunk.js:1)
    at main.13157256.chunk.js:1
    at main.13157256.chunk.js:1
    at l (main.13157256.chunk.js:1)
    at v (main.13157256.chunk.js:1)
    at Ka (main.13157256.chunk.js:1)
    at gl (main.13157256.chunk.js:1)
    at cs (main.13157256.chunk.js:1)
    at ls (main.13157256.chunk.js:1)
    at Xl (main.13157256.chunk.js:1)
```

**Comment by derrickmehaffy** [comment] 2021-04-27 07:25
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/update-to-3-6-0-from-3-5-4-breaks-admin/4480/1

**Comment by TasosBak** [comment] 2021-04-27 07:32
@derrickmehaffy The previous message is probably automated because I posted it in the forum asking for help - not providing any solution

**Comment by bram-abe** [comment] 2021-04-27 07:46
> This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:
> 
> https://forum.strapi.io/t/update-to-3-6-0-from-3-5-4-breaks-admin/4480/1

not solved the problem, like I was stated in my previous message it will get you to a new error message.

**Comment by soupette** [comment] 2021-04-27 07:48
It seems that you made some customisations to your app. You'll need to check the changes from v3.5 to v3.6 and apply them again with the new codebase.

**Comment by TasosBak** [comment] 2021-04-27 07:49
Thank you very much! What is the best way to check for changes between 3.5.4 and 3.6.0?

**Comment by soupette** [comment] 2021-04-27 07:56
If you did not fork the package and used the extensions system it will be a difficult. 
From what I see you have 2 options:

1. Check the PR #10000 
2. Check the corresponding new files in your application.

**Comment by TasosBak** [comment] 2021-04-27 11:10
Well that's 617 commits... Is there a recommended way to check which files have been changed from admin/src?

**Comment by soupette** [comment] 2021-04-27 13:41
Which file did you change?

**Comment by TasosBak** [comment] 2021-04-27 14:49
That's the thing - I've changed multiple files inside admin\src\components and in admin\src\containers. 

I find it hard to believe that doing heavy customizations in the admin has not been done before. So there must be a way to check the files that have been changed in the new releases so that we are able to solve the issues that will come up.

**Comment by derrickmehaffy** [comment] 2021-04-27 14:59
> @derrickmehaffy The previous message is probably automated because I posted it in the forum asking for help - not providing any solution

Yes it's automated

> I find it hard to believe that doing heavy customizations in the admin has not been done before. So there must be a way to check the files that have been changed in the new releases so that we are able to solve the issues that will come up.

You can use the PR interface in GitHub to view a changed file, then navigate back through the blob. For example here are the two changed folders for v3.6.0's PR:

https://github.com/strapi/strapi/tree/00637a801a093b3b39387fa5645a30162170525d/packages/strapi-admin/admin/src/components
https://github.com/strapi/strapi/tree/00637a801a093b3b39387fa5645a30162170525d/packages/strapi-admin/admin/src/containers

Yes heavy customizations have been done before, and many of our users do them **but** with the extensions system we specifically warn everyone in the update and migration guides that we do not support updating directly (easily) if you do. You will **always** need to compare your version to ours and merge changes in.

We will be changing this system in the v4 to a more "whole fork" or hook-based system but I don't have the details on that for now.

References: 
- https://strapi.io/documentation/developer-docs/latest/update-migration-guides/update-version.html#extensions
- https://strapi.io/documentation/developer-docs/latest/update-migration-guides/migration-guides.html#migrations-guides
- (Example) https://strapi.io/documentation/developer-docs/latest/update-migration-guides/migration-guides/migration-guide-3.4.x-to-3.4.4.html#migration-guide-from-3-4-x-to-3-4-4

![image](https://user-images.githubusercontent.com/8593673/116263499-46050380-a72e-11eb-8104-f942fbc78d8c.png)

---

We are marking this issue as closed as it is most likely caused by custom extensions that we cannot and do not know the scope of nor predict on Strapi version upgrades. If you feel this was closed in error do let us know.

**Closed by derrickmehaffy** 2021-04-27 14:59 UTC
Labels: status: can't reproduce

**Comment by TasosBak** [comment] 2021-04-27 15:07
Thank you very much for the info @derrickmehaffy! I will try the PR interface that you mentioned. Yes, I know that you explicitly state that we need to make our own tests, I was just asking for a way to find the files that have changed.

Again, thank you all for your time!

**Comment by derrickmehaffy** [comment] 2021-04-27 15:10
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/update-to-3-6-0-from-3-5-4-breaks-admin/4480/2

**Comment by derrickmehaffy** [comment] 2021-04-27 16:32
> Thank you very much for the info @derrickmehaffy! I will try the PR interface that you mentioned. Yes, I know that you explicitly state that we need to make our own tests, I was just asking for a way to find the files that have changed.
> 
> Again, thank you all for your time! 

Generally speaking you can usually look right at the master branch as we don't Generally directly merge new feature PRs into it and the master is usually a direct mirror of whatever the current release is, each release does also have a source code zip you can download and view also.
