### ISSUE TITLE
The user role is displayed strangely.

### ISSUE THREAD

**Issue by ainusdev** [strapi/strapi#17651] opened 2023-08-11 14:02 UTC
### Required System information

- Node.js version: v16.20.2
- NPM version: 8.19.4
- Strapi version: v4.12.1
- Database: postgresql
- Operating system: Cloud
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When you add a user in Content Manager, the role is displayed as a number that is assumed to be indexed.

### Steps to reproduce the behavior

1. Go to the Content Manger.
2. Select User from the Collection types.
3. Select +Create new entry.
4. Select the Add relation located at the bottom of the role.
5. Then you'll see a dropdown showing only numbers.

### Expected behavior

I had predicted that Authenticated and Public would be displayed.

### Screenshots

<img width="1265" alt="스크린샷 2023-08-11 오후 9 45 01" src="https://github.com/strapi/strapi/assets/50290684/37e949ca-706e-412e-9f11-a0a1d0ff579a">

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by gu-stav** [comment] 2023-08-11 14:03
Closing as duplicate of https://github.com/strapi/strapi/issues/17561

**Closed by gu-stav** 2023-08-11 14:03 UTC
Labels: status: duplicate
