### ISSUE TITLE
No routes is made for a collection type

### ISSUE THREAD

**Issue by parsagholipour** [strapi/strapi#15659] opened 2023-02-01 06:48 UTC
### Required System information
Node version: 16
Npm version: 8
Database: Postgresql
Strapi: 4.6.0
OS: Windows 11
### Describe the bug
All models except one doesn't have routes generated and all of its actions return 404 error.
It used to work but all of a sudden it didn't. I think it happened after upgrading to 4.6.0
Content type:
![image](https://user-images.githubusercontent.com/57809920/215809898-faaabc45-3386-4b2c-8814-bcbaed9178ba.png)
Request Result:
![image](https://user-images.githubusercontent.com/57809920/215809635-8a68bc67-758b-4c70-b816-d23c713741fb.png)
Also nothing in swagger.
Another strange thing is this model only has ```find``` and ```findOne``` permissions.
![image](https://user-images.githubusercontent.com/57809920/215811133-21388929-5d2b-432c-aa32-8608f8d7b6b4.png)
### Steps to reproduce the behavior
Not sure. It was an exception I think.
### Expected behavior
Routes get generated for `sector` model and all permissions be available.
Please let me know if there's anything more helpful I can provide to solve this issue.
Thank you

**Comment by derrickmehaffy** [comment] 2023-02-02 21:14
Can you please share the file/folder structure of your content-type and the contents of your routes file?

**Comment by parsagholipour** [comment] 2023-02-03 09:05
@derrickmehaffy 
Sector routes:
```
/**
 * sector router
 */

import { factories } from '@strapi/strapi';

export default factories.createCoreRouter('api::sector.sector');

```

Sector structure:
```
{
  "kind": "collectionType",
  "collectionName": "sectors",
  "info": {
    "singularName": "sector",
    "pluralName": "sectors",
    "displayName": "Sector"
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "title": {
      "type": "string",
      "required": true
    },
    "organizations": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::organization.organization",
      "inversedBy": "sectors"
    },
    "events": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::event.event",
      "inversedBy": "sectors"
    },
    "podcasts": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::podcast.podcast",
      "inversedBy": "sectors"
    },
    "jobs": {
      "type": "relation",
      "relation": "manyToMany",
      "target": "api::job-listing.job-listing",
      "inversedBy": "sectors"
    },
    "image": {
      "allowedTypes": [
        "images"
      ],
      "type": "media",
      "multiple": false
    }
  }
}
```

I got a backup of the project having this issue but removing and recreating the model fixes the problem.

**Comment by derrickmehaffy** [comment] 2023-02-03 21:07
> @derrickmehaffy Sector routes:
> 
> ```
> /**
>  * sector router
>  */
> 
> import { factories } from '@strapi/strapi';
> 
> export default factories.createCoreRouter('api::sector.sector');
> ```
> 
> Sector structure:
> 
> ```
> {
>   "kind": "collectionType",
>   "collectionName": "sectors",
>   "info": {
>     "singularName": "sector",
>     "pluralName": "sectors",
>     "displayName": "Sector"
>   },
>   "options": {
>     "draftAndPublish": true
>   },
>   "pluginOptions": {},
>   "attributes": {
>     "title": {
>       "type": "string",
>       "required": true
>     },
>     "organizations": {
>       "type": "relation",
>       "relation": "manyToMany",
>       "target": "api::organization.organization",
>       "inversedBy": "sectors"
>     },
>     "events": {
>       "type": "relation",
>       "relation": "manyToMany",
>       "target": "api::event.event",
>       "inversedBy": "sectors"
>     },
>     "podcasts": {
>       "type": "relation",
>       "relation": "manyToMany",
>       "target": "api::podcast.podcast",
>       "inversedBy": "sectors"
>     },
>     "jobs": {
>       "type": "relation",
>       "relation": "manyToMany",
>       "target": "api::job-listing.job-listing",
>       "inversedBy": "sectors"
>     },
>     "image": {
>       "allowedTypes": [
>         "images"
>       ],
>       "type": "media",
>       "multiple": false
>     }
>   }
> }
> ```
> 
> Folder structure:
> 
> ![image](https://user-images.githubusercontent.com/57809920/216558142-7e61500e-c00b-45d4-8747-869ac9921479.png)
> 
> I got a backup of the project having this issue but removing and recreating the model fixes the problem.

That's really quite odd :thinking: 

For now the issue is fixed for you yeah?

**Comment by parsagholipour** [comment] 2023-02-04 14:50
@derrickmehaffy Yeah I recreated it

**Comment by derrickmehaffy** [comment] 2023-02-07 04:44
Alright odd, since I can't reproduce and your issue is fixed I'll go ahead and close it but others hit the same problem we can look at reopening.

**Closed by derrickmehaffy** 2023-02-07 04:44 UTC
Labels: status: can not reproduce
