### ISSUE TITLE
[v4] te.map not a function console error admin dashboard

### ISSUE THREAD

**Issue by n10l** [strapi/strapi#12237] opened 2022-01-18 18:11 UTC
### Steps to reproduce the behavior

1. Go to Content Manager to add first record.
2. Click on Save after filling data
3. See error

`react_devtools_backend.js:4045 TypeError: te.map is not a function
    at content-manager.0e791cae.chunk.js:1:171893
    at Object.useMemo (main.81ff2f50.js:2:1911166)
    at t.useMemo (main.81ff2f50.js:2:2076841)
    at B (content-manager.0e791cae.chunk.js:1:171856)
    at si (main.81ff2f50.js:2:1905201)
    at Xu (main.81ff2f50.js:2:1957498)
    at ks (main.81ff2f50.js:2:1944739)
    at Ps (main.81ff2f50.js:2:1944667)
    at Ms (main.81ff2f50.js:2:1944530)
    at xs (main.81ff2f50.js:2:1941496)
overrideMethod @ react_devtools_backend.js:4045
fu @ main.81ff2f50.js:2
n.payload @ main.81ff2f50.js:2
va @ main.81ff2f50.js:2
Qi @ main.81ff2f50.js:2
Xu @ main.81ff2f50.js:2
ks @ main.81ff2f50.js:2
Ps @ main.81ff2f50.js:2
Ms @ main.81ff2f50.js:2
xs @ main.81ff2f50.js:2
(anonymous) @ main.81ff2f50.js:2
t.unstable_runWithPriority @ main.81ff2f50.js:2
Vo @ main.81ff2f50.js:2
Ko @ main.81ff2f50.js:2
$o @ main.81ff2f50.js:2
Fs @ main.81ff2f50.js:2
t.unstable_runWithPriority @ main.81ff2f50.js:2
Vo @ main.81ff2f50.js:2
zs @ main.81ff2f50.js:2
(anonymous) @ main.81ff2f50.js:2
L @ main.81ff2f50.js:2
w.port1.onmessage @ main.81ff2f50.js:2
react_devtools_backend.js:4045 Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at t.n.render (3706.47086dc2.chunk.js:2:1410896)
    at Gi (main.81ff2f50.js:2:1917832)
    at Qi (main.81ff2f50.js:2:1917629)
    at Xu (main.81ff2f50.js:2:1958571)
    at ks (main.81ff2f50.js:2:1944739)
    at Ps (main.81ff2f50.js:2:1944667)
    at Ms (main.81ff2f50.js:2:1944530)
    at xs (main.81ff2f50.js:2:1941496)
    at main.81ff2f50.js:2:1890993
    at t.unstable_runWithPriority (main.81ff2f50.js:2:2091789)
overrideMethod @ react_devtools_backend.js:4045
fu @ main.81ff2f50.js:2
n.callback @ main.81ff2f50.js:2
ga @ main.81ff2f50.js:2
yu @ main.81ff2f50.js:2
Rs @ main.81ff2f50.js:2
t.unstable_runWithPriority @ main.81ff2f50.js:2
Vo @ main.81ff2f50.js:2
As @ main.81ff2f50.js:2
xs @ main.81ff2f50.js:2
(anonymous) @ main.81ff2f50.js:2
t.unstable_runWithPriority @ main.81ff2f50.js:2
Vo @ main.81ff2f50.js:2
Ko @ main.81ff2f50.js:2
$o @ main.81ff2f50.js:2
Fs @ main.81ff2f50.js:2
t.unstable_runWithPriority @ main.81ff2f50.js:2
Vo @ main.81ff2f50.js:2
zs @ main.81ff2f50.js:2
(anonymous) @ main.81ff2f50.js:2
L @ main.81ff2f50.js:2
w.port1.onmessage @ main.81ff2f50.js:2
main.81ff2f50.js:2 Uncaught Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at t.n.render (3706.47086dc2.chunk.js:2:1410896)
    at Gi (main.81ff2f50.js:2:1917832)
    at Qi (main.81ff2f50.js:2:1917629)
    at Xu (main.81ff2f50.js:2:1958571)
    at ks (main.81ff2f50.js:2:1944739)
    at Ps (main.81ff2f50.js:2:1944667)
    at Ms (main.81ff2f50.js:2:1944530)
    at xs (main.81ff2f50.js:2:1941496)
    at main.81ff2f50.js:2:1890993
    at t.unstable_runWithPriority (main.81ff2f50.js:2:2091789)`

### Expected behavior

It should save the data properly.

### Screenshots

![image](https://user-images.githubusercontent.com/17937997/149993670-082e52d4-696d-4c95-85cb-9b6409441869.png)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v14.18.3
- NPM version: 6.14.15
- Strapi version: 4.0.2
- Database: MySQL
- Operating system: Mac OS

### Additional context

My content types are setup with localization.

**Comment by derrickmehaffy** [comment] 2022-01-18 23:45
Not enough reproduction information, couldn't reproduce on v4.0.4.

Closing until the author providers more comprehensive reproduction steps

**Closed by derrickmehaffy** 2022-01-18 23:45 UTC

**Comment by ly95** [comment] 2022-02-19 12:18
**some issue**


System
Node.js version: v14.17.1
NPM version: 8.4.1
Strapi version: 4.1.0
Database: PG
Operating system: Mac OS (M1)

<img width="1552" alt="截屏2022-02-19 20 09 02" src="https://user-images.githubusercontent.com/1676886/154800199-514ffad4-9d92-4885-8f09-e99e318e7688.png">

**Comment by derrickmehaffy** [comment] 2022-02-23 15:29
> **some issue**
> 
> System Node.js version: v14.17.1 NPM version: 8.4.1 Strapi version: 4.1.0 Database: PG Operating system: Mac OS (M1)
> 
> <img alt="截屏2022-02-19 20 09 02" width="1552" src="https://user-images.githubusercontent.com/1676886/154800199-514ffad4-9d92-4885-8f09-e99e318e7688.png">

Can you please provide more information on steps to reproduce?
