### ISSUE TITLE
GraphQL queries are extremely slow, they always populate automatically all relations

### ISSUE THREAD

**Issue by cgonzalezsan** [strapi/strapi#8535] opened 2020-10-31 20:49 UTC
## Bug report

GraphQL queries are extremely slow, most likely due to they populate all relations. It makes the app totally unusable.
It also happens with the queries that Strapi admin makes when fetching the data of the collection types.

### Describe the bug

I have experienced a drastic slow-down of MongoDB's performance. When fetching all data from a collection type (`Article category` which has 8 records) it will take ~13 seconds which is absolutely crazy. This collection type has a relation with `Articles` (~1200 records) which is what seems to be causing the speed issue, which still is crazy considering the amount of documents.

If I add `"autoPopulate" : false ` to the model, the GraphQL query will take milliseconds, but the problem is that in Strapi Admin, all  related `Articles` will be empty.

This is a common issue I've had after having thousands (~7k) of records in my DB and has made the app unusable (one heavier query currently takes 20seconds)

### Steps to reproduce the behavior

1. Run the below query or go to collection type `Article categories` to see the 8 existing records
2. See time necessary to get a response

### Expected behavior

The query should take milliseconds 

### Screenshots

Screenshots of the time it takes the query to resolve 13 seconds and also Strapi Admin's request in the collection type `Article categories` 

<img width="1794" alt="Screenshot 2020-10-31 at 21 41 40" src="https://user-images.githubusercontent.com/6850051/97789579-e33d1000-1bc1-11eb-93ea-44e667798c1f.png">
<img width="1533" alt="Screenshot 2020-10-31 at 21 36 52" src="https://user-images.githubusercontent.com/6850051/97789580-e7692d80-1bc1-11eb-82c4-20c2c6539f7b.png">

### Code snippets

GraphQL query : 
```
query ArticleCategories {
    articleCategories {
      id
      name_en
      name_de
    }
  }
```

article-category.settings.json
```
{
  "kind": "collectionType",
  "collectionName": "article_categories",
  "info": {
    "name": "Article Category"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "import_complete": {
      "default": false,
      "type": "boolean",
      "private": true
    },
    "name_en": {
      "type": "string"
    },
    "name_de": {
      "type": "string"
    },
    "description_en": {
      "type": "richtext"
    },
    "description_de": {
      "type": "richtext"
    },
    "pim_id": {
      "type": "string"
    },
    "pim_key": {
      "type": "string"
    },
    "channels": {
      "type": "json"
    },
    "article_subcategories": {
      "via": "article_category",
      "collection": "article-subcategory"
    },
    "slug": {
      "type": "uid",
      "targetField": "name_en"
    },
    "articles": {
      "via": "article_categories",
      "collection": "article"
    }
  }
}

```
### System

- Node.js version: 12.18.2
- NPM version:6.14.8
- Strapi version: 3.2.5
- Database: MongoDB
- Operating system: MacOS

**Comment by derrickmehaffy** [comment] 2020-11-02 20:04
closing as duplicate of:
https://github.com/strapi/strapi/issues/3552
https://github.com/strapi/strapi/issues/5182
https://github.com/strapi/strapi/issues/5363

Thank you for the additional information

**Closed by derrickmehaffy** 2020-11-02 20:04 UTC
Labels: status: duplicate

**Comment by derrickmehaffy** [comment] 2020-11-02 20:15
I am going to close and lock this thread in favor of our global tracking issue here: https://github.com/strapi/strapi/issues/8552

If anyone has additional comments please place them on the tracking issue, we are doing this to help centralize the issue and make it clearer where various related bug reports stem from the same source.
