### ISSUE TITLE
In admin UI, dates are entered in local time but displayed in UTC time

### ISSUE THREAD

**Issue by luc-plamondon** [strapi/strapi#2872] opened 2019-02-21 22:50 UTC
**Informations**
- **Node.js version**: 10.15.1 
- **NPM version**: * 6.4.1
- **Strapi version**: 3.0.0-alpha.24 
- **Database**: MongoDB
- **Operating system**: Ubuntu 18.04
- **(Optional) Link to your Project**: 

**What is the current behavior?**
In the admin UI, after entering a date with the datepicker and saving the object, the date displayed is different when viewing the object. 

**Steps to reproduce the problem**
Set your computer clock so that you are not in the UTC+0 timezone (otherwise you won't see the bug).

In the admin UI, create an object with a field of type Date. Enter a date like "2019-02-21 17:00:00" using the datepicker (which now works, big cheers to those who fixed bug #1960). Save the object.

Display the object again. The date shown will be, in my case: "2019-02-21 22:00:00". It is 5 hours later than the time I entered (17:00:00). Please note that I am in timezone UTC-5. 

**What is the expected behavior?**
The date displayed when viewing an object should be the same as the date entered when creating or modifying it.

**Suggested solutions**
The time as saved and displayed is technically correct in the sense that 17:00:00 in my timezone (UTC-5) is equal to 22:00:00 UTC. I checked in the database, the date stored is "2019-02-21T22:00:00.000Z". The problem is when displaying the date afterwards: the admin has to transform it back to the local timezone. That's the part missing.

This issue is not the same as #1960 because the latter pertains to entering a date. The current issue is about displaying it.

**Comment by lauriejim** [comment] 2019-02-25 13:03
I think it's duplicate of this issue https://github.com/strapi/strapi/issues/2811.

**Closed** 2019-02-25 13:04 UTC
Labels: status: duplicate

**Comment by luc-plamondon** [comment] 2019-02-25 14:38
It is indeed the same issue, sorry for the duplicate. My conclusion sums up issue #2811: it is a datepicker display bug, not a database one (note that I am using a different database than issue #2811). 

In my project, outside the admin, I had to display the date in the current timezone (same thing as the admin should do) and I found moment.format([your format here]) from Moment.js library to do the trick easily. If someone can help me pinpoint the file where the date is displayed in the Strapi admin, I might be able to help.

**Comment by lauriejim** [comment] 2019-02-25 15:07
Thank you these details

**Comment by alvinchencd** [comment] 2019-03-08 23:04
is there any followup on this issue? im trying to fix this issue on my own as well but like @luc-plamondon couldn't find the front end code that displaying the date in the admin

**Comment by cipiasentini** [comment] 2020-05-09 13:20
I can't believe this is still an issue. The timezone setting on the database is not being detected apparently. I also tried regenerating the database having the correct timezone applied beforehand and nothing. That affects the "createdAt" and "updatedAt" fields as well.
