### ISSUE TITLE
Lost data on components

### ISSUE THREAD

**Issue by mirza99** [strapi/strapi#13122] opened 2022-04-13 21:14 UTC
### Required System information

- Node.js version: 14.17.0
- Yarn version: 1.22.15
- Strapi version: 4.0.7
- Database: MySQL
- Operating system: Debian

### Describe the bug

Hello,

First of all, thank you for this great product, it saved me a lot of time of building my own headless CMS.
I built content-types for my company Website with 4 single types. Each single type is sharing multiple "common" components.
I don't know how or when but some of my data moved from Single Type A to Single Type B. 

I didn't use the option "Fill from another location" and some data moved from german to french and in wrong single types.

### Steps to reproduce the behavior

I filled a lot of content in the Website and I continue to develop by adding new fields (it's maybe the raison of the bug). 
I added new fields to some components (not to the components_common_text_items that caused the problem) and the data was lost.
Question : is it possible that the data can be lost when I add a field between two existing components ? I'm asking because the structure of the tables is a bit complexe and maybe there is an order.

### Expected behavior

The existing content not to move as I wasn't changing the structure to components_common_text_items. 

### Code snippets

Home single type: 

```
{
  "kind": "singleType",
  "collectionName": "homes",
  "info": {
    "singularName": "home",
    "pluralName": "homes",
    "displayName": "home",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {
    "i18n": {
      "localized": true
    }
  },
  "attributes": {
    "navigationTitle": {
      "type": "string"
    },
    "firstContent": {
      "type": "component",
      "repeatable": false,
      "component": "common.text-item",
      "pluginOptions": {
        "i18n": {
          "localized": true
        }
      }
    }
}
```

The others single type are similar. In this example I simplified the single types, the difference is that I always wrapped all components in child-components.

And the shared common component looks like this :

```
{
  "collectionName": "components_common_text_items",
  "info": {
    "displayName": "textItem",
    "icon": "ellipsis-h"
  },
  "options": {},
  "attributes": {
    "content": {
      "type": "string"
    }
  }
}

```

**Comment by kasonde** [comment] 2022-05-09 22:46
Setting this as a duplicate of #11955 as the issues are related, (we can track progress from one source).

**Closed by kasonde** 2022-05-09 22:46 UTC
Labels: status: duplicate
