### ISSUE TITLE
[Strapi v5 RC] Missing schema in defaultSanitizeOutput

### ISSUE THREAD

**Issue by komat1** [strapi/strapi#20955] opened 2024-08-06 20:17 UTC
### Required System information
Node: 20.15.1
System: MacOS

Environment: development
OS: darwin-arm64
Strapi Version: 5.0.0-rc.9
Node/Yarn Version: npm/10.7.0 node/v20.15.1 darwin arm64 workspaces/false
Edition: Community
Database: mysql

### Describe the bug

When I try to add a user to the strapi (from REST, GraphQL or admin panel), this error comes up: Missing schema in defaultSanitizeOutput.
But it adds the user anyway.
Also, it seems to only bug out when "Enable email confirmation" in the advanced settings is set to **TRUE**

### Steps to reproduce the behavior

1. Go to Strapi
2. Click on Create user using add
4. See error in the console

### Additional context

Also, strapi doesnt send emails after registering, but sending emails work.
**when using GraphQL**
{
  "errors": [
    {
      "message": "Email or Username are already taken",
      "path": [
        "register"
      ],
      "extensions": {
        "code": "STRAPI_APPLICATION_ERROR",
        "stacktrace": [
          "ApplicationError: Email or Username are already taken",
          "    at Object.register (/Users/matejkolestik/Desktop/gabnoc/gabnoc/node_modules/@strapi/plugin-users-permissions/server/controllers/auth.js:344:13)",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
          "    at async resolve (/Users/matejkolestik/Desktop/gabnoc/gabnoc/node_modules/@strapi/plugin-users-permissions/server/graphql/mutations/auth/register.js:24:7)"
        ],
        "error": {
          "name": "ApplicationError",
          "message": "Email or Username are already taken",
          "details": {}
        }
      }
    }
  ],
  "data": null
}

**Comment by dazzafact7** [comment] 2024-08-20 11:31
same issue when trying to create an user

```
const registerResponse = await axios.post(`${strapiUrl}/api/auth/local/register`, {
        username: user.username,
        email: user.email,
        password: user.password
      }, {
        headers: { 'Authorization': `Bearer ${strapiToken}` }
      });
```
User will be created, but with error and not getting an ID back as response

**Comment by alexandrebodin** [comment] 2024-09-02 18:02
Testing this on rc.12 I cannot reproduce. @dazzafact7 do you still have this if you upgrade to rc.12 ?

**Comment by xXnikosXx** [comment] 2024-09-13 11:52
Stumbled upon this error myself just now, using v5.0.0-rc.19.

**Comment by alexandrebodin** [comment] 2024-09-13 12:57
Hey @xXnikosXx 

Can you reproduce it consistently ? If you can share the steps you took that would be super helpful 🙏

**Comment by xXnikosXx** [comment] 2024-09-13 16:31
Here's a github repo. inside of the readme (open file, view as code) you can find every single step I followed in order to reproduce the error, just now, from a clean install of strapi 5 rc19.

I will try a couple more things and add my findings to the repo.

https://github.com/xXnikosXx/min-reproduction

**Comment by alexandrebodin** [comment] 2024-09-16 08:29
Thanks for the repro I have been able to fix it. And it will be part of the release

**Comment by xXnikosXx** [comment] 2024-09-16 09:22
Will the fix be part of a future RC, or directly on stable?

**Comment by hanpaine** [comment] 2024-09-16 09:39
Fixed and will be in the next release 🙏

**Closed by hanpaine** 2024-09-16 09:39 UTC
Labels: issue: bug, severity: high, status: pending reproduction, version: 5, source: core:core
