### ISSUE TITLE
Create a new record (POST API) doesn't filled data

### ISSUE THREAD

**Issue by Lith** [strapi/strapi#3550] opened 2019-06-28 16:46 UTC
**Describe the bug**
When I create a new record for my customer model, my field `user` is set to `null`.

**Steps to reproduce the behavior**
1. Create a model `customer` with a relation to `users-permissions` :
```
"user": {
      "unique": true,
      "model": "user",
      "via": "customer",
      "plugin": "users-permissions"
    }, 
```
2. Use `curl` and replace `xxx.xxx.xxx-xxx` by your own bearer token (in admin mode) and try to create a new customer :
```
curl -X POST "http://localhost:1337/customers" -H "accept: application/json" -H "Authorization: Bearer xxx.xxx.xxx-xxx" -H "Content-Type: application/json" -d "{\"user\":\"3733\"}"
```
3. Check your database and see if the user is set correctly
![image](https://user-images.githubusercontent.com/605495/60357457-f6d7d580-99d3-11e9-8b06-987468f84104.png)
4. Retry many times...
5. In my case, I need to retry 4 times before the last is set successfully
![image](https://user-images.githubusercontent.com/605495/60357598-58983f80-99d4-11e9-853e-eeb0a509aef3.png)

**Expected behavior**
When I create a customer, with the param 'user', the field `user`  is set correctly every times.

**System**
- Node.js version: v10.14.2
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.8 (but the bug is present in previous beta version)
- Database: bookshelf - mysql
- Operating system: Debian, Mac OS X

**Additionnal information**
Model ``Customer`` is not overloaded, I use default api controller, service...

**Comment by Lith** [comment] 2019-06-28 21:20
Temporary fix : 
I've changed into the ``User.settings.json`` file my ``customer`` attribute
**Before**
```
"customer": {
      "model": "customer",
      "via": "user"
    }
```
**After**
```
"customer": {
      "collection": "customer",
      "via": "user"
    }
```
This change the relation type "one-to-one" by "one-to-many" : 
- _user_ has now many _customer(s)_

**Comment by derrickmehaffy** [comment] 2019-07-08 05:00
@Lith I think this is intended as a user shouldn't have multiple customers if the relation is oneToOne.

@alexandrebodin @lauriejim confirm?

**Comment by alexandrebodin** [comment] 2019-07-08 07:09
@derrickmehaffy Yes it is the intended behavior :)

onetoOne relations means you can't avec the same user twice for customer. So everytime you create a model with a customer that is already is it is replaced and set to null in the other entities. Hence the result you get. 

the relation you realy want is a many-to-on (Many customers have one user)

**Comment by alexandrebodin** [comment] 2019-07-08 07:09
I'm closing this as it is the intended behavior :)

**Closed by alexandrebodin** 2019-07-08 07:09 UTC

**Comment by Lith** [comment] 2019-07-11 16:57
I want one unique customer for each user.
I use one-to-one relation, but I'm obligated to overload the "create" code by trying many times to set user to customer like that :
```
    /**
     * Tricks bug Strapi - retry link customer and user
     */
    while (!customer.toJSON().user) {
      customer = await strapi.services.customer.update({id: customer.toJSON().id}, params);
    }
```

Sometimes, this take one loop, but othertimes, 10 or more...
I've setting up the user with a unique customer at the creation of a new user only.

I think the one-to-one relation have really a problem.

It's not the unique model which I've had this bug. You can reproduce this problem with any one-to-one relation with MySQL database.

**Comment by alexandrebodin** [comment] 2019-07-11 17:18
Just merged a fix ;) 

https://github.com/strapi/strapi/pull/3607

Going to release it at the start of next week :)

**Comment by Lith** [comment] 2019-07-11 19:51
Perfect :) I'm not crazy ! Thanks 👍
