### ISSUE TITLE
Error when accessing the Advanced tab in datetime fields

### ISSUE THREAD

**Issue by gundall** [strapi/strapi#18504] opened 2023-10-19 09:56 UTC
### System information

- Node.js version: 18.17.0
- NPM version: 9.6.7
- Strapi version: 4.14.5
- Database: PostgeSQL
- Operating system: Windows 11
- Is your project Javascript or Typescript: JS

### Describe the bug
Hi! I'm having some trouble when editing a collection in the Content-Type Builder section.

When I try to open the "Advanced" tab in a Date field, if its property "type" is set to _datetime_, the screen turns white:

![error_datetime](https://github.com/strapi/strapi/assets/27724595/484ef77a-b9ef-4c98-85b9-32f7683f0a5a)

I have this error log:

![image](https://github.com/strapi/strapi/assets/27724595/9c55ab5d-1c7a-4cf6-ab73-e4d6e3bb72df)

### Steps to reproduce the behavior

1. Go to Content-Type Builder.
2. Create (or edit) a Date type field in any collection.
3. In the creation/edition dialog, set the "type" field to "datetime".
4. Now try to access the "Advanced" tab.
5. The screen should turn white, and you should receive the error above.

### Expected behavior

It should be possible to access the "Advanced" tab in the creation/edition dialog.

**Comment by joshuaellis** [comment] 2023-10-19 10:11
this is a duplicate of #18123

**Closed by joshuaellis** 2023-10-19 10:11 UTC
