### ISSUE TITLE
[Strapi v5 Beta] API Returns 404 for Invalid Requests and Asset Deletion on Dashboard

### ISSUE THREAD

**Issue by burakozdemir32** [strapi/strapi#20397] opened 2024-05-30 06:52 UTC
### Required System information

- Node.js version: 18.17.0
- NPM version: yarn/1.22.19
- Strapi version: 5.0.0-beta.8
- Database: sqlite
- Operating system: darwin-arm64
- Is your project Javascript or Typescript: Typescript

### Describe the bug

_The issues were generated on build mode, haven't tested on development mode, yet._

**Invalid Requests:** API responds with 404 instead of 400 for missing fields.
**Asset Deletion (s3 resource):** Dashboard shows 404 error, but the asset is deleted successfully upon refresh.

### Steps to reproduce the behavior
1. REST API
  - Make an API request without providing a required field in the request body.
    ```
    curl -X POST http://localhost:1337/content-type-endpoint -H "Content-Type: application/json" -d '{"missingRequiredField": "value"}'
     ```
  - Observe the response from the API.

2. For Asset Deletion:
  - Attempt to remove an asset on the dashboard.
  - Observe the 404 error message indicating the deletion failed.
  - Refresh the page.
  - Check if the asset is still listed or if it has been successfully removed.

### Expected behavior

1. For Invalid Requests:
  The API should respond with a validation error indicating which required field is missing or invalid, along with an appropriate status code (e.g., 400 Bad Request).

2. For Asset Deletion:
  The dashboard should confirm successful deletion of the asset without displaying a 404 error.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by Bassel17** [comment] 2024-06-24 14:21
Hello, I would invite you to try again with the latest beta to verify again,
I couldn't reproduce the issues mentioned here

**Comment by hanpaine** [comment] 2024-07-09 07:48
Closing due to no further response and inability to reproduce

**Closed by hanpaine** 2024-07-09 07:48 UTC
Labels: issue: bug, severity: high, source: core:admin, status: pending reproduction, version: 5, source: core:core
