### ISSUE TITLE
Unable to connect Strapi with MongoDB Atlas

### ISSUE THREAD

**Issue by felipe-lopez-avil** [strapi/strapi#10298] opened 2021-05-11 17:23 UTC
### Bug report
I run the npx create-strapi-app my-project command and follow the custom setup steps, but the Strapi installation fails and the terminal shows the error message:

Connection test failed: Cannot find module 'C:\Users\User\AppData\Local\Temp\strapi6233e60c65e1\node_modules\strapi-connector-mongoose\lib\utils\connectivity.js'
Require stack:
- C:\Users\User\AppData\Local\Yarn\Data\global\node_modules\strapi-generate-new\lib\create-customized-project.js
- C:\Users\User\AppData\Local\Yarn\Data\global\node_modules\strapi-generate-new\lib\generate-new.js
- C:\Users\User\AppData\Local\Yarn\Data\global\node_modules\strapi-generate-new\lib\index.js
- C:\Users\User\AppData\Local\Yarn\Data\global\node_modules\create-strapi-app\create-strapi-app.js
- C:\Users\User\AppData\Local\Yarn\Data\global\node_modules\create-strapi-app\index.js

### Describe the bug
I am trying to create a Strapi + MongoDB Atlas App, and is not working. 
I have tried to create it following the custom installation steps, and I also have tried to creating with the quickstart option and set it up later by editing the config/dabatase.js and the .env files. It doesn't work either way.

I don't think I'm missing something basic here (pretty sure I followed the steps properly and pasted in the correct info from Mongo Atlas. I searched online for answers, without success. I've noticed that a lot of people is having the exact same problem and

### Steps to reproduce the behavior
For creating a new Strapi project with Mongo Atlas (preferred connection)

Open new cmd terminal 
Run command: npx create-strapi-app my-project or yarn create strapi-app my project
Choose your default database client mongo
Database name: projectdb
Host: _Cluster host_
+srv connection: true
Port (It will be ignored if you enable +srv): 27017
Username: admin
Password: xxxxx
Authentication database (Maybe "admin" or blank): (blank)
Enable SSL connection: true
After following these steps, the terminal shows the error message above, followed by:

Retrying...
? Choose your default database client (Use arrow keys)
❯ sqlite
postgres
mysql
mongo

### Expected behavior
Initialize the strappi admin and is succesfully connected with Mongo Atlas

### System
Node.js version: 14.16.1
NPM version: 6.14.12
Strapi version: 3.6.2
Database: Mongo Atlas
Operating system: Windows 10

**Comment by felipe-lopez-avil** [comment] 2021-05-12 16:31
I'm also testing with my whitelist being 0.0.0.0/0 so I don't think that's the problem

**Comment by JohanAltamar** [comment] 2021-05-12 18:19
@felipe-lopez-avil I re install with Quickstart option and then add mongo db credentials. First, update package.json and add     "strapi-connector-mongoose": "3.6.1" as a dependency, then yarn install.
After that, update `config/database.js` as follow:
```
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'mongoose',
      settings: {
        uri: env('DATABASE_URI'),
      },
      options: {
        ssl: true,
      },
    },
  },
});
```
Create `.env` file and add `DATABASE_URI` and `DATABASE_NAME` variables. Database_uri is the whole string Atlas provide, so you will find the database_name inside database_uri string

**Comment by felipe-lopez-avil** [comment] 2021-05-13 14:22
Hi @JohanAltamar. It worked perfectly. I already have tried that following the official Strapi Documentation but it didn't work. In the docs there are three more lines in the settings object and one extra line in the options object. I guess those extra 4 lines of code that we can see in the documentation were the problem.
Anyway, thanks a lot!

**Comment by derrickmehaffy** [comment] 2021-05-14 14:01
Closing as duplicate of https://github.com/strapi/strapi/issues/10268

@JohanAltamar Thank you, I made a similiar suggestion in the above issue but without the example.

**Closed by derrickmehaffy** 2021-05-14 14:01 UTC
Labels: status: pending reproduction

**Comment by AnibalFigueroa** [comment] 2021-07-22 01:09
> @felipe-lopez-avil I re install with Quickstart option and then add mongo db credentials. First, update package.json and add "strapi-connector-mongoose": "3.6.1" as a dependency, then yarn install.
> After that, update `config/database.js` as follow:
> 
> ```
> module.exports = ({ env }) => ({
>   defaultConnection: 'default',
>   connections: {
>     default: {
>       connector: 'mongoose',
>       settings: {
>         uri: env('DATABASE_URI'),
>       },
>       options: {
>         ssl: true,
>       },
>     },
>   },
> });
> ```
> 
> Create `.env` file and add `DATABASE_URI` and `DATABASE_NAME` variables. Database_uri is the whole string Atlas provide, so you will find the database_name inside database_uri string

Good solution!

**Comment by hammadsohail** [comment] 2023-07-28 06:54
> @felipe-lopez-avil I re install with Quickstart option and then add mongo db credentials. First, update package.json and add "strapi-connector-mongoose": "3.6.1" as a dependency, then yarn install. After that, update `config/database.js` as follow:
> 
> ```
> module.exports = ({ env }) => ({
>   defaultConnection: 'default',
>   connections: {
>     default: {
>       connector: 'mongoose',
>       settings: {
>         uri: env('DATABASE_URI'),
>       },
>       options: {
>         ssl: true,
>       },
>     },
>   },
> });
> ```
> 
> Create `.env` file and add `DATABASE_URI` and `DATABASE_NAME` variables. Database_uri is the whole string Atlas provide, so you will find the database_name inside database_uri string

I did the same, and end up getting this error
Error: Unknown dialect undefined
    at getDialectName (C:\Users\muham\OneDrive\Documents\Nextjsbuilds\upwork-tom\travel-web\starpi-api\gotrip\node_modules\@strapi\database\lib\dialects\index.js:36:13)
    at getDialect (C:\Users\muham\OneDrive\Documents\Nextjsbuilds\upwork-tom\travel-web\starpi-api\gotrip\node_modules\@strapi\database\lib\dialects\index.js:42:23)
    at new Database (C:\Users\muham\OneDrive\Documents\Nextjsbuilds\upwork-tom\travel-web\starpi-api\gotrip\node_modules\@strapi\database\lib\index.js:31:20)
    at Database.init (C:\Users\muham\OneDrive\Documents\Nextjsbuilds\upwork-tom\travel-web\starpi-api\gotrip\node_modules\@strapi\database\lib\index.js:121:14)
    at Strapi.bootstrap (C:\Users\muham\OneDrive\Documents\Nextjsbuilds\upwork-tom\travel-web\starpi-api\gotrip\node_modules\@strapi\strapi\lib\Strapi.js:421:30)
    at Strapi.load (C:\Users\muham\OneDrive\Documents\Nextjsbuilds\upwork-tom\travel-web\starpi-api\gotrip\node_modules\@strapi\strapi\lib\Strapi.js:492:16)
    at async workerProcess (C:\Users\muham\OneDrive\Documents\Nextjsbuilds\upwork-tom\travel-web\starpi-api\gotrip\node_modules\@strapi\strapi\lib\commands\actions\develop\action.js:110:26)

**Comment by derrickmehaffy** [comment] 2023-07-28 10:58
Strapi v4 does not support mongodb, we dropped it.
