### ISSUE TITLE
Can't cancel after multiple file replacement

### ISSUE THREAD

**Issue by abepuentes** [strapi/strapi#6048] opened 2020-05-04 13:46 UTC
**Describe the bug**
If you try to replace a media file in your collections for a second time in a row a "Something went wrong" message appear and a blank page beside menu is displayed until refreshing the page.

**Steps to reproduce the behavior**
1. Go to 'Admin Panel'.
2. Pick any of yours collection types with a media file in it.
3. Click on "edit" (pencil) on any of your media files.
4. Click on "Replace media" in the pop up window.
5. Pick a picture from the "explorer" window.
6. You will be back on the "Edit" window with the option to "Replace media" or "Finish"
7. Click on "Replace media" again.
8. Click on "Cancel"  on your "explorer" window before choosing a file.
9. See error "Something went wrong" message.

**Expected behavior**
No error after canceling replacing media.

**Screenshots**
![image](https://user-images.githubusercontent.com/48102930/80972193-d47cc880-8deb-11ea-8e8f-0c542083966f.png)
![image](https://user-images.githubusercontent.com/48102930/80972226-de063080-8deb-11ea-9ef4-60f10d6ae9f7.png)
![image](https://user-images.githubusercontent.com/48102930/80972248-e52d3e80-8deb-11ea-9504-eb5759cdd2fc.png)
![image](https://user-images.githubusercontent.com/48102930/80972257-ea8a8900-8deb-11ea-88e1-c5056983f8bf.png)
![image](https://user-images.githubusercontent.com/48102930/80972290-f0806a00-8deb-11ea-9bea-f03a9fac2fb7.png)

**System**
- Node.js version: 10.15.3
- YARN version: 1.22.4
- Strapi version: 3.0.0-beta.20
- Database: MongoDB Atlas
- Operating system: Windows 10 Spanish

**Additional context**
Admin panel deployed on Heroku.
If someone can confirm this is node, yarn or language related will be appreciated because I will move to the recommended version.

**Comment by lauriejim** [comment] 2020-05-11 13:46
Thank you for reporting this issue.
I think it's not a big deal to fix, will appreciate if you take a look.
Ping @soupette about this issue.

**Comment by bishwenduk029** [comment] 2020-07-19 07:07
@lauriejim , Can I give this issue a try and submit a PR?

**Comment by OmarMorales71** [comment] 2020-12-09 02:46
@lauriejim someone is working on this issue? Can I give it?

**Comment by Goutam192002** [comment] 2021-02-25 11:39
Is this still open?

**Comment by derrickmehaffy** [comment] 2021-02-26 20:22
> Is this still open?

Yes the issue is still open and pending a fix

**Comment by daniel-julius-sam** [comment] 2021-07-26 07:59
Please close this issue as it is fixed.

**Comment by soupette** [comment] 2021-07-26 08:22
I am closing this issue as it is fixed

**Closed by soupette** 2021-07-26 08:22 UTC
Labels: good first issue, severity: low, source: plugin:content-manager, status: confirmed, type: bug
