### ISSUE TITLE
Admin panel take too long to respond Strapi

### ISSUE THREAD

**Issue by sediqamousavi** [strapi/strapi#9277] opened 2021-02-01 09:39 UTC
### Describe the bug

 The first time I load the admin interface takes a long time. More than 5 minute

### Expected behavior
load faster

### Screenshots
![Screenshot (78)](https://user-images.githubusercontent.com/43989585/106440918-087a3c80-6497-11eb-9046-2c4a12c46b68.png)

### System

- Node.js version: v12 
- NPM version: 6
- Strapi version: 3.4.5
- Database: MongoDB
- Operating system: ubuntu

**Comment by tttp** [comment] 2021-02-01 16:06
Could you clarify how you have configured? are you strapi and mongodb on the same server? how's the network between them? are you using a proxy (eg nginx) in front of strapi?

It's likely a problem with your specific installation, a network or proxy problem perhaps? 

are you using heroku type services? if you are using their free tier, it might take a while on the first connection as "your" server might have been stopped for instance.

**Comment by derrickmehaffy** [comment] 2021-02-02 15:22
What @tttp said, can you please provide more information on your environment.

**Comment by sediqamousavi** [comment] 2021-02-03 07:54
@derrickmehaffy and @tttp 
We don't use Heroku, Strapi and MongoDB are on the same server also We run Strapi on pm2 and we don't use a proxy for admin route. We only use the proxy for upload and graphql.

**Comment by derrickmehaffy** [comment] 2021-02-03 12:51
> @derrickmehaffy and @tttp 
> We don't use Heroku, Strapi and MongoDB are on the same server also We run Strapi on pm2 and we don't use a proxy for admin route. We only use the proxy for upload and graphql.
> 

Can you give us details? Which proxy, who's the hosting provider, what's the specs, are there any error logs, are you a significant distance from the host, do you have fast internet. 

We can't help if we don't have enough information to find the root cause.

**Comment by derrickmehaffy** [comment] 2021-04-15 18:16
Closing as user provided no updated information

**Closed by derrickmehaffy** 2021-04-15 18:16 UTC
Labels: status: can't reproduce
