### ISSUE TITLE
Admin interface crashes when select input is toggled

### ISSUE THREAD

**Issue by fabio-nettis** [strapi/strapi#15031] opened 2022-11-29 06:16 UTC
### Required System information

- Node.js version: v16.18.0
- NPM version: v8.19.2
- Strapi version: v4.5.2
- Database: PostgreSQL
- Operating system: MacOS 13.0 (Ventura)

### Describe the bug

Entire admin panel interface crashes when a select input of any kind is clicked. No matter if this input is contained in the actual content type via a option field or generally in the interface.

![Screen Recording 2022-11-29 at 07 01 34](https://user-images.githubusercontent.com/36916632/204452314-6ec0cb3f-1250-4d33-b3ae-d9a5f25558c5.gif)

### Steps to reproduce the behavior

1. Go to the admin panel
2. Click on a content type
3. Try to select displayed fields (for example)

### Expected behavior

Interface shouldn't crash or a at least an [error boundary](https://reactjs.org/docs/error-boundaries.html) should be provided to prevent the whole child component tree from disintegrating prematurely.

### Screenshots

![error-screenshot](https://user-images.githubusercontent.com/36916632/204452554-667f291e-d462-40c1-a5f2-96ce0551cd58.jpg)

### Code snippets

N/A

### Additional context

N/A

**Comment by matteoolefloch** [comment] 2022-11-29 06:53
Hey 👋,

Got the same issue, it's seems to happen only on dropdown input.

DEV ENV:
- Node.js version: v16.13.1
- NPM version: v8.1.2
- Strapi version: v4.5.2
- Database: PostgreSQL
- Operating system: MacOS 13.1 (Ventura)

**Comment by matteoolefloch** [comment] 2022-11-29 07:00
#14993

Duplicated issue

**Comment by joshuaellis** [comment] 2022-11-29 08:53
Closing as a duplicate of #14993

**Closed by joshuaellis** 2022-11-29 08:53 UTC
Labels: status: duplicate
