### ISSUE TITLE
GraphQL "query me" Error: "Cannot return null for non-nullable field UsersPermissionsMe.id."

### ISSUE THREAD

**Issue by onsombal** [strapi/strapi#7893] opened 2020-09-14 20:54 UTC
**Describe the bug**
I'm encountering a GraphQL "query me" error: `[{"message": "Cannot return null for non-nullable field UsersPermissionsMe.id.",`

The `GET /users/me` endpoint works perfectly. 

**Steps to reproduce the behavior**
In GraphQL playground enter the following query plus Authorization Token:
```
query {
  me {
    id
    username
    email
  }
}
```
**Expected behavior**
Query me GraphQL results.

**Screenshots**
<img width="1426" alt="Screen Shot 2020-09-13 at 7 21 23 PM" src="https://user-images.githubusercontent.com/1588266/93136729-66ee7c00-f6aa-11ea-92f9-e838688220d8.png">

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: v12.14.1
- NPM version: 6.14.5
- Strapi version: 3.1.4
- Database: MongoDB Atlas
- Operating system: MacOS

**Additional context**

**Comment by derrickmehaffy** [comment] 2020-09-14 22:20
I am unable to reproduce this using a local mongo database: 
![image](https://user-images.githubusercontent.com/8593673/93143787-79ae8400-f69d-11ea-8706-dec8fba55158.png)

The **only** way I could reproduce this is by starting an application using SQLite, moving to mongodb, and trying to use the old JWT from SQLite (which won't work since the JWT contains the users ID + expirey data, and the user ID would be wrong since it's an integer and not the object ID.)

SQLite JWT: 
![image](https://user-images.githubusercontent.com/8593673/93143923-bf6b4c80-f69d-11ea-8915-e06949039e1b.png)

MongoDB JWT:
![image](https://user-images.githubusercontent.com/8593673/93143955-cc883b80-f69d-11ea-893d-e46ad823ced9.png)

**Comment by onsombal** [comment] 2020-09-15 00:09
The only thing I'm doing different is using MongoDB Atlas for my database and Firebase for Authentication. Firebase auth works perfectly for my playground and React queries and mutations -- all except for the "me query".

I configured MongoDB Atlas during the Strapi npx create dialog -- _i.e. I did not start with SQLite or local MongoDB_. My database config follows:
```
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'mongoose',
      settings: {
        host: env('DATABASE_HOST', 'mycluster.mongodb.net'),
        srv: env.bool('DATABASE_SRV', true),
        port: env.int('DATABASE_PORT', 27017),
        database: env('DATABASE_NAME', 'gqlserver2'),
        username: env('DATABASE_USERNAME', 'my-username'),
        password: env('DATABASE_PASSWORD', 'my-password'),
      },
      options: {
        authenticationDatabase: env('AUTHENTICATION_DATABASE', null),
        ssl: env.bool('DATABASE_SSL', true),
      },
    },
  },
});
```

**Comment by onsombal** [comment] 2020-09-15 02:15
@derrickmehaffy -- I'm going to mark this issue closed. I just discovered that the User I created in my React code using Firebase authentication never got created in Strapi. Thus, there is no "me" if the User does not exist.

**Closed** 2020-09-15 02:18 UTC
Labels: status: can't reproduce, type: help wanted

**Comment by derrickmehaffy** [comment] 2020-09-15 02:24
Ah no biggie, it happens :wink:
