### ISSUE TITLE
Configure View Entry Title for Relation field with User (from admin) not working

### ISSUE THREAD

**Issue by adwinang** [strapi/strapi#17646] opened 2023-08-11 08:52 UTC
### Required System information

- Node.js version: v18.12.1
- NPM version: 8.19.2
- Strapi version: 4.12.4
- Database: sqlite
- Operating system: macOS and Ubuntu 22
- Is your project Javascript or Typescript: TypeScript

### Describe the bug
When I configure the entry title for any of the relation field with User (from admin), the Content Manager is not updated

### Steps to reproduce the behavior

1. Add a field relation with the User (from admin) to any content type
2. Configure the view and change the Entry Title to any field of your choice, or leaving as default will do as well
3. Attempt to create an item
4. The Relation Field input only shows the id of the user
5. See there is no console error

### Expected behavior
I expect to see the field input show the User's field value of the configured view

### Screenshots
![Screenshot 2023-08-11 at 4 41 55 PM](https://github.com/strapi/strapi/assets/34839258/e05e68ea-ea8d-4095-96d1-5560e47df81f)
The above is the setting of the Relation Field

![Screenshot 2023-08-11 at 4 42 25 PM](https://github.com/strapi/strapi/assets/34839258/3158ccbb-331b-41fe-9eb7-31b6cef9cd36)
The above is the configured view of the Relation Field

![Screenshot 2023-08-11 at 4 42 32 PM](https://github.com/strapi/strapi/assets/34839258/ade8b17d-2cf8-4495-b817-6c60bb7e6a62)
The above is the output, which is just showing the User id and that is weird.

### Code snippets
I used the UI to set it up

**Comment by gu-stav** [comment] 2023-08-11 10:15
Closing this as duplicate of https://github.com/strapi/strapi/issues/17561

**Closed by gu-stav** 2023-08-11 10:15 UTC
