### ISSUE TITLE
Rebuild administration pannel fails after migrate to 3.5.0

### ISSUE THREAD

**Issue by simeonackermann** [strapi/strapi#9442] opened 2021-02-18 12:47 UTC
### Describe the bug

After migrate from strapi 3.4.6 to 3.5.0  with [this guide](https://strapi.io/documentation/developer-docs/latest/migration-guide/) the administration panel rebuild fails.

### Steps to reproduce the behavior

1. migrate steps in [migration guide](https://strapi.io/documentation/developer-docs/latest/migration-guide/)
2. rebuild admin panel with `npm run build -- --clean`

### Code snippets

Terminal error output:
```
Building your admin UI with development configuration ...

● Webpack █████████████████████████ building (70%) 386/457 modules 71 active
 babel-loader › .cache/admin/src/containers/SettingsPage/utils/defaultRoutes.js

Error: Module not found: Error: Can't resolve '/usr/src/containers/App/utils/customRoutes' in '/usr/src/app/.cache/admin/src/containers/App/utils'
    at /usr/src/app/node_modules/strapi-admin/index.js:71:23
    at finalCallback (/usr/src/app/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/usr/src/app/node_modules/webpack/lib/Compiler.js:265:20)
    at /usr/src/app/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1173:13
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1096:25
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1017:13
    at /usr/src/app/node_modules/neo-async/async.js:2830:7
    at /usr/src/app/node_modules/neo-async/async.js:2830:7
    at done (/usr/src/app/node_modules/neo-async/async.js:2863:11)
    at /usr/src/app/node_modules/neo-async/async.js:2818:7
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1017:13
    at /usr/src/app/node_modules/neo-async/async.js:2830:7
    at /usr/src/app/node_modules/neo-async/async.js:2830:7
    at done (/usr/src/app/node_modules/neo-async/async.js:2863:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.1.0 build: `strapi build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2021-02-18T12_35_36_183Z-debug.log

```

### System

- Node.js version: 14
- NPM version: 6
- Strapi version: 3.5.0
- Database: MongoDB
- Operating system: Docker, Alpine-Linux

**Comment by soupette** [comment] 2021-02-18 13:18
Hello @simeonackermann, I tried to reproduce the issue, but the admin is building correctly on my side.
I am unsure how I can help you debug.

**Comment by simeonackermann** [comment] 2021-02-18 13:34
Hm, maybe some lack with my dependencies in package.json?

```json
...
"dependencies": {
    "strapi": "3.5.0",
    "strapi-admin": "3.5.0",
    "strapi-connector-mongoose": "3.5.0",
    "strapi-plugin-content-manager": "3.5.0",
    "strapi-plugin-content-type-builder": "3.5.0",
    "strapi-plugin-email": "3.5.0",
    "strapi-plugin-upload": "3.5.0",
    "strapi-plugin-users-permissions": "3.5.0",
    "strapi-utils": "3.5.0"
  },
...
```

**Comment by simeonackermann** [comment] 2021-02-18 13:34
Hm, maybe some lack with my dependencies in package.json?

```json
...
"dependencies": {
    "strapi": "3.5.0",
    "strapi-admin": "3.5.0",
    "strapi-connector-mongoose": "3.5.0",
    "strapi-plugin-content-manager": "3.5.0",
    "strapi-plugin-content-type-builder": "3.5.0",
    "strapi-plugin-email": "3.5.0",
    "strapi-plugin-upload": "3.5.0",
    "strapi-plugin-users-permissions": "3.5.0",
    "strapi-utils": "3.5.0"
  },
...
```

**Comment by jonmol** [comment] 2021-02-18 16:30
I'm having the same issue (and another one have reported it in slack as well https://strapi.slack.com/archives/C0BNGCDNH/p1613652596225700) 

It doesn't happen when I build it locally in production mode, but it does when circleci is building:
local:
```
 NODE_ENV=production yarn build --clean
yarn run v1.22.5
$ strapi build --clean
Building your admin UI with production configuration ...

✔ Webpack
  Compiled successfully in 6.74s

Done in 8.03s.
```
Circleci:
```
Step 11/12 : RUN yarn build
 ---> Running in 17c668f36de0
yarn run v1.22.5
$ strapi build
Building your admin UI with production configuration ...
ℹ Compiling Webpack
Error: Module not found: Error: Can't resolve '/ee/admin/containers/App/utils/customRoutes' in '/usr/src/app/.cache/admin/src/containers/App/utils'
    at /usr/src/app/node_modules/strapi-admin/index.js:71:23
    at finalCallback (/usr/src/app/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/usr/src/app/node_modules/webpack/lib/Compiler.js:265:20)
    at /usr/src/app/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1173:13
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1096:25
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1017:13
    at /usr/src/app/node_modules/neo-async/async.js:2830:7
    at /usr/src/app/node_modules/neo-async/async.js:2830:7
    at done (/usr/src/app/node_modules/neo-async/async.js:2863:11)
    at /usr/src/app/node_modules/neo-async/async.js:2818:7
    at /usr/src/app/node_modules/webpack/lib/Compilation.js:1017:13
    at /usr/src/app/node_modules/neo-async/async.js:2830:7
    at /usr/src/app/node_modules/neo-async/async.js:2830:7
    at done (/usr/src/app/node_modules/neo-async/async.js:2863:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build' returned a non-zero code: 1
```

**Comment by derrickmehaffy** [comment] 2021-02-18 18:29
In testing this appears to only be a Docker issue, I believe we are aware of the cause of the issue and will be working on a fix shortly

**Comment by coreyti** [comment] 2021-02-18 20:02
I'm seeing this on macOS "Big Sur" (v11.2.1). Using...

- nvm v0.37.2
- node v14.15.5
- yarn 1.22.10
- strapi 3.5.0

Created the project via the blog template:

```shell
$ yarn create strapi-app backend 
    --quickstart \
    --template https://github.com/strapi/strapi-template-blog
```

**Comment by coreyti** [comment] 2021-02-18 20:39
My issue appears to be due to the fact that I am creating my project within a path containing a `src` directory, which fouls things up in the [strapi-admin/webpack.config.js](https://github.com/strapi/strapi/blob/7102ebbcef1716b55f8a2ce8370f2cb1bd719a8a/packages/strapi-admin/webpack.config.js#L195).

Running the `yarn create` command above works fine if I move to a different path.

**Comment by jonmol** [comment] 2021-02-18 22:03
I can confirm that src seems to be the issue. Moved my working local build and tried building and now it fails:
```
 /usr/src/strapi-test/3.5.0-test$ yarn build
yarn run v1.22.5
$ strapi build
Building your admin UI with development configuration ...

● Webpack █████████████████████████ building (39%) 244/292 modules 48 active
 node_modules/path-to-regexp/index.js

Error: Module not found: Error: Can't resolve '/usr/src/containers/App/utils/customRoutes' in '/usr/src/strapi-test/3.5.0-test/.cache/admin/src/containers/App/utils'
    at /usr/src/strapi-test/3.5.0-test/node_modules/strapi-admin/index.js:71:23
    at finalCallback (/usr/src/strapi-test/3.5.0-test/node_modules/webpack/lib/Compiler.js:257:39)
    at onCompiled (/usr/src/strapi-test/3.5.0-test/node_modules/webpack/lib/Compiler.js:265:20)
    at /usr/src/strapi-test/3.5.0-test/node_modules/webpack/lib/Compiler.js:670:21
    at eval (eval at create (/usr/src/strapi-test/3.5.0-test/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
    at /usr/src/strapi-test/3.5.0-test/node_modules/webpack/lib/Compilation.js:1173:13
    at /usr/src/strapi-test/3.5.0-test/node_modules/webpack/lib/Compilation.js:1096:25
    at /usr/src/strapi-test/3.5.0-test/node_modules/webpack/lib/Compilation.js:1017:13
    at /usr/src/strapi-test/3.5.0-test/node_modules/neo-async/async.js:2830:7
    at /usr/src/strapi-test/3.5.0-test/node_modules/neo-async/async.js:2830:7
    at done (/usr/src/strapi-test/3.5.0-test/node_modules/neo-async/async.js:2863:11)
    at /usr/src/strapi-test/3.5.0-test/node_modules/neo-async/async.js:2818:7
    at /usr/src/strapi-test/3.5.0-test/node_modules/webpack/lib/Compilation.js:1017:13
    at /usr/src/strapi-test/3.5.0-test/node_modules/neo-async/async.js:2830:7
    at /usr/src/strapi-test/3.5.0-test/node_modules/neo-async/async.js:2830:7
    at done (/usr/src/strapi-test/3.5.0-test/node_modules/neo-async/async.js:2863:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``` 

Node, yarn, node_modules are all the same, just the path containing src makes it break

**Comment by hugomalaise** [comment] 2021-02-19 07:04
I confirm, it hapens to me on a simple fresh install.
If your path have a 'src' folder in it, you will have this error.

> Error: Module not found: Error: Can't resolve 'C:\XXX\src/containers/App/utils/customRoutes' in 'C:\XXXX\src\my-project\.cache\admin\src\containers\App\utils'

**Comment by tylerforesthauser** [comment] 2021-02-19 17:35
Just came here to confirm `/src` directory issue. 3.5.0 breaks deployment on render.com as they deploy to `/opt/render/project/src/`. 

Just (im)patiently waiting for a fix 😬

**Comment by j4t1nd3r** [comment] 2021-02-19 20:29
> Just came here to confirm `/src` directory issue. 3.5.0 breaks deployment on render.com as they deploy to `/opt/render/project/src/`.
> 
> Just (im)patiently waiting for a fix 😬

Thanks for the info, how did you figure out that it was down to render.com?

**Comment by tylerforesthauser** [comment] 2021-02-19 21:14
> Thanks for the info, how did you figure out that it was down to render.com?

I meant that for my particular use-case, I'm deploying Strapi on render.com and when I updated to 3.5.0 and tried to deploy, it failed.

**Comment by bubiblomer** [comment] 2021-02-19 23:24
I have the same situation with Strapi 3.5.0 in render.com 

Hopefully it can be fixed soon with an update

**Comment by didivassi** [comment] 2021-02-20 00:22
Same here with GCP and /usr/src/app

Hope it will be fixed soon :)

**Comment by fahadabdulaziz** [comment] 2021-02-20 05:11
Had this problem and solved by downgrading npm to  6.14.4

**Comment by bvolz** [comment] 2021-02-20 13:34
I had the same issue and I fixed it temporarily by replacing lines 195-197 in `node_modules/strapi-admin/webpack.config.json` (these lines start with `const splitPath = ...` and `let wantedPath = ...`) with the following:

```
let wantedPath = path.join(resource.context.substr(0, resource.context.lastIndexOf(`${path.sep}src${path.sep}`)), 'src');
```

It splits the path at the last occurrence of "src" and not the first one.

**Comment by didivassi** [comment] 2021-02-21 11:45
I've managed to get my docker working by doing the build in another folder and then linking to /usr/src/app directory.

Here's my  docker file

```
FROM strapi/base
WORKDIR /usr/src1/app
COPY ./package.json ./
COPY ./yarn.lock ./
RUN yarn install
COPY . .
ENV NODE_ENV production
RUN yarn build
EXPOSE 1337

RUN ln -s /usr/src1/app /usr/src/app

CMD ["yarn", "start"]
```

**Comment by soupette** [comment] 2021-02-22 07:35
@bvolz thanks a lot for providing a fix, would you mind opening a PR?

**Comment by derrickmehaffy** [comment] 2021-02-22 15:14
Closing as above PR was merged

**Closed by derrickmehaffy** 2021-02-22 15:14 UTC
Labels: severity: high, source: admin, status: confirmed, type: bug
