### ISSUE TITLE
Memory leak users-permissions 

### ISSUE THREAD

**Issue by marefati110** [strapi/strapi#6583] opened 2020-06-08 11:36 UTC
**Describe the bug**
On the admin page, when data is displayed, many query are executed, reducing speed and causing errors.
i have more than 140,000 user 
and this query execute when edit one user and save 
this query have no limit

**Screenshots**

![Screenshot from 2020-06-08 15-56-30](https://user-images.githubusercontent.com/42033084/84025547-065fec80-a9a1-11ea-969b-7c787199d7d3.png)

after executing this query strapi crashed and this erorr hapend

```
<--- Last few GCs --->

[10184:0x33fa3c0]   119028 ms: Mark-sweep 2044.3 (2053.3) -> 2043.6 (2053.5) MB, 2124.2 / 0.1 ms  (average mu = 0.056, current mu = 0.007) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2300544408d1 <JSObject>
    0: builtin exit frame: captureStackTrace(aka captureStackTrace)(this=0x3c973e1004b1 <undefined>,0x0c162b224b31 <JSFunction CapturedTrace (sfi = 0x161412993319)>,0x19ea0992ad79 <CapturedTrace map = 0x3619328c1c99>,0x3c973e1004b1 <undefined>)

    1: _then [0x151fe99180d9] [/home/ali/file/doctop-backend/node_modules/bluebird/js/release/promise.js:~248] [pc=0x1558f25cc0c3](this=0x19ea09929b39 <...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa07f90 node::Abort() [/usr/bin/node]
 2: 0xa0839c node::OnFatalError(char const*, char const*) [/usr/bin/node]
 3: 0xb80d9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 4: 0xb81119 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
 5: 0xd2d875  [/usr/bin/node]
 6: 0xd2df06 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/bin/node]
 7: 0xd3a785 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/bin/node]
 8: 0xd3b635 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
 9: 0xd3e0ec v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
10: 0xd0b0ad v8::internal::Factory::CopyFixedArrayAndGrow(v8::internal::Handle<v8::internal::FixedArray>, int, v8::internal::AllocationType) [/usr/bin/node]
11: 0xf0ef38 v8::internal::FrameArray::AppendJSFrame(v8::internal::Handle<v8::internal::FrameArray>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::AbstractCode>, int, int, v8::internal::Handle<v8::internal::FixedArray>) [/usr/bin/node]
12: 0xcd4f58  [/usr/bin/node]
13: 0xcd5543 v8::internal::Isolate::CaptureAndSetSimpleStackTrace(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>) [/usr/bin/node]
14: 0xc1b7ad v8::internal::Builtin_ErrorCaptureStackTrace(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
15: 0x13cb619  [/usr/bin/node]
Done in 130.97s.
```

mysql query::
```
select distinct `upload_file_morph`.* from `upload_file_morph` where `field` = 'avatar' and `upload_file_morph`.`related_id` in (2, 3, 5, 6, 7, 24, 75, 80 , ...) and `upload_file_morph`.`related_type` = 'users-permissions_user'
```

**System**

- Node.js version: 12
- NPM version:6
- Strapi version:3.0.1 
- Database:mysql
- Operating system:ubuntu

**Comment by derrickmehaffy** [comment] 2020-06-08 12:06
well that's a new one, exceeding 2GB of ram O_o

**Comment by derrickmehaffy** [comment] 2020-06-08 12:06
@soupette memory leak?

**Comment by maktoobgar** [comment] 2020-06-08 12:45
> **Describe the bug**
> On the admin page, when data is displayed, many query are executed, reducing speed and causing errors.
> i have more than 140,000 user
> and this query execute when edit one user and save
> this query have no limit
> 
> **Screenshots**
> 
> ![Screenshot from 2020-06-08 15-56-30](https://user-images.githubusercontent.com/42033084/84025547-065fec80-a9a1-11ea-969b-7c787199d7d3.png)
> 
> after executing this query strapi crashed and this erorr hapend
> 
> ```
> <--- Last few GCs --->
> 
> [10184:0x33fa3c0]   119028 ms: Mark-sweep 2044.3 (2053.3) -> 2043.6 (2053.5) MB, 2124.2 / 0.1 ms  (average mu = 0.056, current mu = 0.007) allocation failure scavenge might not succeed
> 
> 
> <--- JS stacktrace --->
> 
> ==== JS stack trace =========================================
> 
> Security context: 0x2300544408d1 <JSObject>
>     0: builtin exit frame: captureStackTrace(aka captureStackTrace)(this=0x3c973e1004b1 <undefined>,0x0c162b224b31 <JSFunction CapturedTrace (sfi = 0x161412993319)>,0x19ea0992ad79 <CapturedTrace map = 0x3619328c1c99>,0x3c973e1004b1 <undefined>)
> 
>     1: _then [0x151fe99180d9] [/home/ali/file/doctop-backend/node_modules/bluebird/js/release/promise.js:~248] [pc=0x1558f25cc0c3](this=0x19ea09929b39 <...
> 
> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
>  1: 0xa07f90 node::Abort() [/usr/bin/node]
>  2: 0xa0839c node::OnFatalError(char const*, char const*) [/usr/bin/node]
>  3: 0xb80d9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
>  4: 0xb81119 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]
>  5: 0xd2d875  [/usr/bin/node]
>  6: 0xd2df06 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/bin/node]
>  7: 0xd3a785 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/bin/node]
>  8: 0xd3b635 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]
>  9: 0xd3e0ec v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]
> 10: 0xd0b0ad v8::internal::Factory::CopyFixedArrayAndGrow(v8::internal::Handle<v8::internal::FixedArray>, int, v8::internal::AllocationType) [/usr/bin/node]
> 11: 0xf0ef38 v8::internal::FrameArray::AppendJSFrame(v8::internal::Handle<v8::internal::FrameArray>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Handle<v8::internal::AbstractCode>, int, int, v8::internal::Handle<v8::internal::FixedArray>) [/usr/bin/node]
> 12: 0xcd4f58  [/usr/bin/node]
> 13: 0xcd5543 v8::internal::Isolate::CaptureAndSetSimpleStackTrace(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::FrameSkipMode, v8::internal::Handle<v8::internal::Object>) [/usr/bin/node]
> 14: 0xc1b7ad v8::internal::Builtin_ErrorCaptureStackTrace(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]
> 15: 0x13cb619  [/usr/bin/node]
> Done in 130.97s.
> ```
> 
> mysql query::
> 
> ```
> select distinct `upload_file_morph`.* from `upload_file_morph` where `field` = 'avatar' and `upload_file_morph`.`related_id` in (2, 3, 5, 6, 7, 24, 75, 80 , ...) and `upload_file_morph`.`related_type` = 'users-permissions_user'
> ```
> 
> **System**
> 
> * Node.js version: 12
> * NPM version:6
> * Strapi version:3.0.1
> * Database:mysql
> * Operating system:ubuntu

Same problem

**Comment by marefati110** [comment] 2020-06-08 17:29
same problem in role and permissions plugin
when i click on doctor page stay on loading for a long time 

have to change permissions manually from database

![2020-06-08_21-56](https://user-images.githubusercontent.com/42033084/84061545-53f54d00-a9d3-11ea-9fd0-14dc04975991.png)

**Comment by lauriejim** [comment] 2020-06-16 12:47
I ping @alexandrebodin about this issue.
Can you confirm or not this issue is a duplicate of this one - https://github.com/strapi/strapi/issues/2992

**Comment by alexandrebodin** [comment] 2020-06-16 12:53
Yep looks like it is the same core pbl @lauriejim

**Comment by derrickmehaffy** [comment] 2020-06-21 08:52
Closing as duplicate of #2992

**Closed by derrickmehaffy** 2020-06-21 08:52 UTC
Labels: type: discussion
