### ISSUE TITLE
Newly created Content Type is changed automatically to deleted Content Type

### ISSUE THREAD

**Issue by henniaufmrenni** [strapi/strapi#7848] opened 2020-09-11 12:54 UTC
**Describe the bug**
While Deleting an old Content Type with the UID "people" I've changed the Display Name to "Person". I've then deleted the content type with the UID "people" and created a new content type called "person" with the UID "person". The advanced settings weren't touched. After the creation, the newly created content type was shown again under the name "People" with the UID "people". After testing the API, requests were only resolved with URL/oldUID and not URL/newUID. Issue remained after several restarts of the development server.

**Steps to reproduce the behavior**

**Expected behavior**
Expected to find the newly created content type under the UID shown in the GUI while creating, not under the UID of a deleted content type with the same Display Name as the newly created content type.

**Screenshots**
Creating new Content  Type:
![Screenshot from 2020-09-11 14-47-07](https://user-images.githubusercontent.com/65598400/92927558-1c68c780-f43e-11ea-84fb-8469c2741bd0.png)
Result after creation with conflicting name in the two columns:
![Screenshot from 2020-09-11 14-45-36](https://user-images.githubusercontent.com/65598400/92927574-21c61200-f43e-11ea-9e08-86d3a03259b2.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: v12.18.3
- NPM version: 6.14.6
- Strapi version: Version: 3.1.4 
- Database: MongoDB
- Operating system: Debian 10

**Additional context**

**Comment by derrickmehaffy** [comment] 2020-09-11 13:57
Closing as duplicate of https://github.com/strapi/strapi/issues/1114

**Closed by derrickmehaffy** 2020-09-11 13:57 UTC
Labels: status: duplicate

**Comment by henniaufmrenni** [comment] 2020-09-11 17:47
Actually no, whats causing it is [#504](https://github.com/strapi/strapi/issues/504). Person become people, woman become women. My bad.

**Comment by henniaufmrenni** [comment] 2020-09-11 17:50
Since its also happens after an install on a fresh machine, I rather believe that it's caused by [#504](https://github.com/strapi/strapi/issues/504) . Person become people, woman become women. My bad.
