### ISSUE TITLE
When I try to press the copy content icon, the icon escapes

### ISSUE THREAD

**Issue by nogumaruo** [strapi/strapi#14983] opened 2022-11-24 05:06 UTC
### Required System information

Node.js version:v16.17.0
NPM version:8.15
Strapi version:4.4.7
Database:postgresql
Operating system:mac OS 12.6
Browser Sidekick 104.30.1.25374（Official Build） （arm64）

### Describe the bug
When I try to press the copy content icon, the icon escapes

### Steps to reproduce the behavior

1. Disable bulk actions in content settings
2. Click on copy content icon

### Expected behavior

Copying content.

### Screenshots
![actual](https://user-images.githubusercontent.com/98809021/203698058-ff9fa563-27a1-4dda-8561-0d581c4e19d7.gif)

### Additional context
This event occurs when all of the following conditions are met.
* Disable bulk actions in content settings
* The screen size is such that horizontal scrolling occurs.
* Draft/Publish system is ON.

**Comment by raph941** [comment] 2022-12-14 12:44
Hi, @nogumaruo I see based on the fact that a clipboard icon was used here, it's understandable that you tried to copy the content by clicking the icon.
However, the icon is meant to duplicate the item, not necessarily copy its content.

**Comment by derrickmehaffy** [comment] 2022-12-23 15:24
Closing this as the feature is working as intended (duplicate, not copy)

**Closed by derrickmehaffy** 2022-12-23 15:24 UTC
