### ISSUE TITLE
Visual UI offset on Chrome

### ISSUE THREAD

**Issue by notio-ca** [strapi/strapi#5998] opened 2020-04-29 02:49 UTC
**Describe the bug**
There is a missing top padding on button elements but strapi is so great to deserve that

**Steps to reproduce the behavior**
1. Go to any app view on Chrome browser

**Expected behavior**
Label should be verticaly aligned inside the container and verticaly align with the icon if any

**System**
- Strapi version: 3.0.0-beta.20

**Screenshots**
![image](https://user-images.githubusercontent.com/64385706/80556554-ea305f00-89a1-11ea-808f-6d197e2e633b.png)

**Comment by elclanrs** [comment] 2020-07-23 22:37
I can see this issue in v3.1.1 but even more misaligned. Here are some screenshots:

![strapi-button-alignment-issue](https://user-images.githubusercontent.com/1661925/88345167-3f0e1800-ccfa-11ea-861a-20ae1c5eba43.png)
![strapi-button-alignment-issue-2](https://user-images.githubusercontent.com/1661925/88345165-3e758180-ccfa-11ea-8950-9f91ef0fd1a4.png)
![strapi-button-alignment-issue-3](https://user-images.githubusercontent.com/1661925/88345163-3ddceb00-ccfa-11ea-8aec-1356bdcee370.png)

The text is always more towards the top, perhaps due to line-height or something.

**Comment by iksent** [comment] 2020-10-27 08:38
I can confirm this is not fixed at the latest release (3.1.5)

![2020-10-27_13-35-35](https://user-images.githubusercontent.com/32956521/97276899-a091d580-1859-11eb-97b2-837102c39da2.png)
![2020-10-27_13-36-24](https://user-images.githubusercontent.com/32956521/97276904-a25b9900-1859-11eb-9bc9-be37e4f35a15.png)

**Comment by elclanrs** [comment] 2020-10-28 22:57
There is definitely something not right about the button styles. The padding is not even, height and line-height are clashing. If I get rid of the hardcoded height, remove the line-height, and use even padding, then the button looks much better. See before and after:

![strapi-alignment-issue](https://user-images.githubusercontent.com/1661925/97505432-24b98b00-1936-11eb-8d57-2d10fa12c8b9.png)

**Comment by derrickmehaffy** [comment] 2020-10-29 14:45
@iksent `I can confirm this is not fixed at the latest release (3.1.5)`

Can you check in the latest release v3.2.5 (unless that's what you meant ;) )

**Comment by elclanrs** [comment] 2020-10-29 16:55
@derrickmehaffy  yes it happens in 3.2.5 as well. The images I posted above from yesterday are from 3.2.5.

**Comment by iksent** [comment] 2020-10-29 18:21
Yes, my mistake, 3.2.5 of course.

**Comment by derrickmehaffy** [comment] 2020-10-30 01:55
I will reopen this to let you guys do some more testing :)

**Comment by elclanrs** [comment] 2020-11-24 05:09
Tracking this bug down, turns out the culprit is in the [strapi/buffet](https://github.com/strapi/buffet) package. I opened https://github.com/strapi/buffet/pull/164 with the fix discussed above

**Comment by elclanrs** [comment] 2020-11-24 17:24
@iksent are you using Windows or Linux? When I tested on macOS I didn't see any alignment issues surprisingly. I'm trying to find the right fix to open another PR. More details here https://github.com/strapi/buffet/pull/164

**Comment by iksent** [comment] 2020-11-24 17:27
I am using Chrome at Windows.

I've just checked it at Firefox and yes - the buttons alignment look fine there.

**Comment by elclanrs** [comment] 2020-12-01 01:17
@iksent I'm not sure what the right fix is for this. There were two PRs that got declined. I just wrote a [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en) override for my domain so you may find this useful:

```css
a {
    min-height: auto !important;
}

button {
    padding-bottom: 0 !important;
    line-height: 30px !important;
}
```

This seems to fix most misalignment issues like the buttons and the links with icons on the sidebar. At least with this temporary fix I don't have to see the UI issues anymore. I may apply this to all my localhost Strapi projects.

**Comment by derrickmehaffy** [comment] 2020-12-03 16:36
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/how-to-resolve-ui-issues-in-windows-and-linux/1451/1

**Comment by jpizzle34** [comment] 2021-04-28 09:07
I think this has something to do with the font family being used and the OS. 

A workaround I am using is to override the font-family that strapi is using with a System Font Stack. I do this by customizing ejecting admin/src/components/GlobalStyle.js (see Strapi docs regarding Admin Panel Customization) and making the following edit to `font-family`:

```
* {
    -webkit-font-smoothing: antialiased;
    box-sizing: border-box;
    // font-family: 'Lato';
    font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
  }
```

It's not an ideal solution, but at least it gets rid of the alignment issues without having to fight CSS rules.

**Comment by soupette** [comment] 2021-11-30 09:04
This should be fixed with the current v4.

**Comment by derrickmehaffy** [comment] 2021-12-02 22:33
Closing as fixed in v4

**Closed by derrickmehaffy** 2021-12-02 22:33 UTC
Labels: type: discussion, source: admin
