### ISSUE TITLE
The CJS build of Vite's Node API is deprecated

### ISSUE THREAD

**Issue by kaaax0815** [strapi/strapi#21716] opened 2024-10-09 07:22 UTC
### Required System information

- Node.js version: 20.18.0
- PNPM version: 9.12.1
- Strapi version: 5.0.3
- Database: MySQL
- Operating system: Mac OS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When running Strapi it shows 

```shell
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```

in the logs.

### Steps to reproduce the behavior

1. Create a new Project
2. Rename `src/admin/vite.config.example.ts` to `src/admin/vite.config.ts`
3. Run `pnpm dev`

### Expected behavior

No warning

### Additional context

As this is only a warning this is probably a non issue. But still shouldn't be there as it suggests the user did something wrong

**Comment by bolg55** [comment] 2024-10-10 20:53
Closing as this is not a bug, just a dependency warning.

**Closed by bolg55** 2024-10-10 20:53 UTC
