### ISSUE TITLE
More advanced ACL for the backend

### ISSUE THREAD

**Issue by panosru** [strapi/strapi#2657] opened 2019-01-20 09:50 UTC
- [X] **I have created my request on the Product Board before I submitted this issue**
- [X] **I have looked at all the other requests on the Product Board before I submitted this issue**

## Please describe your feature request:
From what I saw so far and played with the `alfa.19` release, currently, only administrators can log in to the backend.

It would be very helpful if we could add roles that would allow them to log in to the backend and contribute in data filling.

### The idea is that you have:
- Those who understand the data structure and create tables, fields, relations etc.;
- Those who only work on filling with data the created tables;

### A more advanced ACL that would allow doing the following:
- Have the `root` user; he will see everything;
- Have the `manager` role; he will be able to manage the structure and the content of one, many or all the databases;
- Have the `analyst` role; he will be able to fill with data one, many or all the tables from one, many or all the databases;

### Case study:
You are a company that doing a market analysis of several products *(each product is a separate database)*.
- Product A
- Product B
- Product C

In your team, you have the *product expert* and the *data expert (root)*, they together design the database structure *(tables, fields, relations)* for each product.

For *Product A* and *Product B* you have in-house *analysts* who work as two separated groups, each focusing on the market analysis of their assigned product. So the analysts of *group A* have access only to the database of *Product A* while the analysts of *group B* have access only to the database of *Product B*. They only allowed to do CRUD operations inside the tables; they have no access to altering the data structure of the tables, that is the responsibility of *data expert(s)*.

The *Product C* is a product that you share intellectual property with another company with which you entered into a joint venture agreement, and you combine your forces to do a market analysis for that product. Some *analysts* of your company from *group A* and *group B* jointly with some *analysts* of your partnership company combine their forces making *group C* to fill with data the database for *Product C*. From *group C*, the *analysts* who are employed by you would have CRUD access while the *analysts* from your partner company will be limited to CRU/RU access.

**Comment by derrickmehaffy** [comment] 2019-01-20 10:52
Closing as this is a duplicate of this: https://portal.productboard.com/strapi/c/8-administrators-roles-permissions

**Closed by derrickmehaffy** 2019-01-20 10:52 UTC
