### ISSUE TITLE
400 Error using Google Authentication 

### ISSUE THREAD

**Issue by kreimben** [strapi/strapi#10007] opened 2021-04-09 15:52 UTC
I can't sure 100% this is just BUG, but not working :/

OK.

I can get token from google. So Google Auth is working perfectly.
And then To get Strapi token, I have to submit google token to my Strapi server.

So I requested to ```https://MY_STRAPI_SERVER_ADDRESS/auth/google/callback?code=TOKEN```.
and ```https://MY_STRAPI_SERVER_ADDRESS/auth/google/callback?access_token=TOKEN```.

The reason that I requested both URL, I saw both of URLs in YouTube and blogs. (and surely both of them worked :/)

Results are fail. 400 both.
and messages are
```
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": {
    "error": "invalid_token",
    "error_description": "Invalid Value"
  },
  "data": {
    "error": "invalid_token",
    "error_description": "Invalid Value"
  }
}
```

### Expected behavior

My Strapi server have to give me jwt token properly.
But haven't been :(

### System

I'm running Strapi on docker and docker image is below.
Actually I already run image Strapi/strapi:latest but same bug.

- Docker Image: strapi/strapi:3.5.4-node12
- Database: mongo
- Operating system: linux (maybe)

Please help :(

**Comment by derrickmehaffy** [comment] 2021-04-09 19:05
Tested with our login-react example and couldn't reproduce: https://github.com/strapi/strapi-examples/tree/master/login-react

Need more information

**Comment by kreimben** [comment] 2021-04-10 15:10
Oh thanks about submitting example, but 400 too.

OK. 

To test my Strapi server, I didn't run backend server. (In fact, It's rather closer that I can't run backend server cuz I'm using node 15 :/ )

I started react app without any changes.

> REACT_APP_BACKEND_URL=https://MY_STRAPI_SERVER_URL yarn start

and then I got this.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/20333172/114274519-b5ee6b00-9a59-11eb-861f-e9e3a2f39953.png">

<img width="1440" alt="Screen Shot 2021-04-11 at 12 09 30 AM" src="https://user-images.githubusercontent.com/20333172/114274612-488f0a00-9a5a-11eb-9198-c8ff3cb46b61.png">

It's same 400 error :(

As I wrote above, I didn't change any thing in react app. and got same results.

Is there any log file or anything to upload here in Strapi server?

I really wanna solve this problem :(

**Comment by derrickmehaffy** [comment] 2021-04-10 15:58
You need to be running the Strapi backend server, and we don't support node 15 (or any non-LTS version of node)

Server side logs are dumped to terminal while it's running, if you are using something like PM2 you can use the `pm2 logs yourAppName` to get them.

Marking as closed without reproduction steps, once you can provide steps to reproduce we can take another look.

**Closed by derrickmehaffy** 2021-04-10 15:58 UTC
Labels: status: can't reproduce

**Comment by kreimben** [comment] 2021-04-10 16:10
OK.

you said I have to run Strapi backend server, but I already run it on docker. So I didn't run on local.

and if I run another Strapi server in localhost, How should I check that bug on the docker?

Is there no way to solve my server?

**Comment by derrickmehaffy** [comment] 2021-04-12 03:48
If you are running it in docker, then you need to pull the logs from Docker.

We need more information to help you, steps to reproduce (exact steps) with what you have done and how you are making requests.

**Comment by kreimben** [comment] 2021-04-12 03:51
Oh I already gave up to login through token :(
than I'm using email login.

Anyway, Thanks 🙏 
I'll re-comment if I have any helps.
Thanks.
