### ISSUE TITLE
v5/deps: react-router-dom 's version is inconsistent between repo generated by create-strapi-app@5.0.0-beta.0 and @strapi/design-system.v1.16.0

### ISSUE THREAD

**Issue by uptonking** [strapi/strapi#19890] opened 2024-03-22 06:09 UTC
### Required System information

- Node.js version: 20.11.0
- NPM version: 10.2.0
- Strapi version: 5.0.0-beta.0
- Database: sqlite
- Operating system: ubuntu
- Is your project Javascript or Typescript: ts

### Describe the bug

- 😍 I start to play with strapi `v5-beta.0`, but get errors about react-router-dom
- 🤔 will v5-beta.1 solve this peer deps ?

### Steps to reproduce the behavior

1. create a repo using `npx create-strapi-app@5.0.0-beta.0 strapi5-myqpp --quickstart --ts`. 
2. when i init using `npm install`, there's peer dependencies warning for react-router-dom. 
3. both `strapi-myapp` and `@strapi/admin.v5-beta.0` depends on `react-router-dom.v6`, but `@strapi/design-system.v1.6.0` depends on `react-router-dom.v5`. 

```
npm WARN While resolving: @strapi/design-system@1.16.0
npm WARN Found: react-router-dom@6.22.3
npm WARN node_modules/react-router-dom
npm WARN   react-router-dom@"^6.0.0" from the root project
npm WARN   7 more (@strapi/admin, @strapi/content-releases, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react-router-dom@"^5.2.0" from @strapi/design-system@1.16.0
npm WARN node_modules/@strapi/design-system
npm WARN   @strapi/design-system@"1.16.0" from @strapi/admin@5.0.0-beta.0
npm WARN   node_modules/@strapi/admin
npm WARN   7 more (@strapi/content-releases, @strapi/plugin-cloud, ...)
npm WARN 
```

### Expected behavior

`npm install` successfully

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment] 2024-03-22 07:13
@uptonking can you please fill out the template even if not all the info applies.

**Comment by derrickmehaffy** [comment] 2024-04-18 19:44
Can't reproduce in beta.4, closing

**Closed by derrickmehaffy** 2024-04-18 19:44 UTC
Labels: version: 5
