### ISSUE TITLE
strapi "shell" incorrectly parses the --quickstart argument on Windows

### ISSUE THREAD

**Issue by adriatic** [strapi/strapi#5759] opened 2020-04-10 02:56 UTC
**Describe the bug**
Running the command **`yarn create strapi-app backend --quickstart --no-run `** does not return the control back to the consile user

**Steps to reproduce the behavior**
1. Run **`yarn create strapi-app backend --quickstart --no-run`** and observe that the control does not return back to you. You would have to use "break" signal ("Ctrl-C") to get the control back.

3. Run **`yarn create strapi-app backend --no-run`** (omit specifying the **`--quickstart`** argument), and specify that argument when prompted for it - and to command runs as expected:

**Expected behavior**
Cases 1. and 2. above should behave the same way 

**Screenshots**

![image](https://user-images.githubusercontent.com/2712405/78957780-49423880-7ab4-11ea-8138-1da862452d88.png)

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v12.14.0 
- NPM version: 6.13.6
- Yarn version: 1.22.4
- Strapi version: 3.0.0-beta.19.5) 
- Database: default
- Operating system: Windows 10 PRO, version 1903

**Additional context**

**Comment by lauriejim** [comment] 2020-04-14 11:48
Hello! Thank you for reporting this issue.
I tested on MacOS and it works well, the issue is confirmed but only on Windows.

**Comment by adriatic** [comment] 2020-04-14 21:28
Eons ago (1992 - 1997), I worked as the VP Engineering at Visix (https://books.google.com/books?id=Kd79q0UEQc8C&pg=PA87&lpg=PA87&dq=visix+galaxy&source=bl&ots=HqJc9pNUVl&sig=ACfU3U2EUuZB4ae4YwumQRe6hdie0YhyfA&hl=en&sa=X&ved=2ahUKEwjMnKWp6ejoAhUVU80KHcyyBiYQ6AEwCHoECAwQKA#v=onepage&q=visix%20galaxy&f=false) with similar, but a lot more ambitious project than Strapi today. 

One of my biggest management problem was to ensure equal testing coverage on all supported platforms - our developers tried to avoid Windows as much as possible. No need to say, this "not Windows preference" turned to be costly and my memories from that time are still fresh in me 😄, so I decided to help you not repeat the same.

**Comment by adriatic** [comment] 2020-08-14 12:27
Hi Jim - I repeated the same issue because I wanted to make the point how this is really easy to fix and the bug is annoying to all newcomers - potential customers you would like to retain, not to send away :-) Hope you take this message for what it is meant to - benevolent remark.

**Comment by derrickmehaffy** [comment] 2020-08-14 13:43
> I wanted to make the point how this is really easy to fix

Can you submit a PR please?

**Comment by adriatic** [comment] 2020-08-14 16:12
@derrickmehaffy I know that your polite offer had a [schadenfreude](https://en.wikipedia.org/wiki/Schadenfreude) component present. Nevertheless, I will not be afraid to restate my opinion "easy to fix:" was poorly chosen. I made this conclusion based on Jim's comment that this feature works fine on macOS; so I thought that the problem was in some os-dependency check for the `quickstart` flag. 

Alas upon inspection of the Strapi source code I realized that the `quickstart` flag handling was an afterthought, as  this flag gets checked at 7 different files:

![image](https://user-images.githubusercontent.com/2712405/90268442-0824b100-de25-11ea-8d1f-e43c2d556765.png)

While the most likely place to address this issue is https://github.com/strapi/strapi/blob/master/packages/strapi-generate-new/lib/index.js#L34-L38, because of all other 6 locations referring `quickstart`, I would not dare to fix the problem we discuss here even if my name was any of the nine contributors to this code 😁.

And yes, I understand why has this issue not being fixed even months after I initially reported it. At the same time, allow me to say how the perception that the workaround (Ctrl-C break out of the loop) is simple enough, I am representing the first time user who tried the [Quick Start Guide](https://strapi.io/documentation/v3.x/getting-started/quick-start.html#_1-install-strapi-and-create-a-new-project) and left with the thought that not even the most basic example does not work (unless by some lunch this same user runs macOS)

**Comment by derrickmehaffy** [comment] 2020-08-14 20:05
Hi! Nope there was no `schadenfreude component` from me, I thought you found the cause.

For the moment since this is a limited scoped issue isolated to just windows users, and only on an initial `--quickstart` run and not with the standard project generation (database) we have deemed the issue to be a low priority, and it's a good issue for newer contributors to learn the code base and basic code troubleshooting.

Currently we have our plates full as a small team working on higher priority issues, if it's not fixed by a contributor we will eventually get to it but we currently have no ETA.

If anyone is interested don't hesitate to submit a pull request, else we will provide an update when we will work on a fix.

Thank you!

**Comment by adriatic** [comment] 2020-08-14 20:25
Sorry for misjudging your intent and please do not take me wrong - I understand the size of the team versus the size of the see of tasks in front of your team issue. I may try to address this problem, while I also have a huge task in front of me, task which if successful should mean more for Strapi (see **[full-stack-conversations/docs/README.md](https://github.com/full-stack-conversations/docs#docs)**)

**Closed** 2021-04-27 06:54 UTC
Labels: good first issue, severity: low, source: core:framework, status: confirmed, type: bug
