### ISSUE TITLE
Content-Manager plugin is not using the controllers and services that we customised

### ISSUE THREAD

**Issue by udaysamsani** [strapi/strapi#10887] opened 2021-09-06 04:08 UTC
### Describe the bug

I customised few resolvers, controllers and services for API in Strapi but when I try to use crud of admin dashboard of Strapi they are not used. Instead Content-manager is using its own service and using that for crud operations from admin dashboard.

### Steps to reproduce the behavior

1. Write a custom resolver or service
2. Go to admin dashboard
2. Try the crud operation you have over rided
3. See the logs in Strapi

### Expected behavior

Admin dashboard should use the services written in API rather than creating its own service so that whatever services we write or over ride are invoked.

### Screenshots

When ever I use Admin dashboard content-manager is calling my services or controllers.

![Screenshot (249)_LI](https://user-images.githubusercontent.com/82494414/132159067-f66344de-b7eb-4230-9eb1-e0a6362f373c.jpg)

### Some things I tried

- I tried lifecycles in models so that I can get data and I can write my logic there but I am getting `undefined` there as well.
- I tried copying content-manager plugin and changing few things but it did not work either.

### System

- Node.js version: v12
- NPM version: 7.21.0
- Strapi version: 3.6.3
- Database: Postgres
- Operating system: Windows, Mac Mojave

**Comment by tonny008** [comment] 2021-09-06 06:44
it is by design.

**Comment by udaysamsani** [comment] 2021-09-06 07:01
Can we over ride that design?

**Comment by derrickmehaffy** [comment] 2021-09-07 03:55
The Content manager has it's own internal controllers and services (it doesn't use GraphQL at all and never will)

See:

- https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-manager/controllers
- https://github.com/strapi/strapi/tree/master/packages/strapi-plugin-content-manager/services

Lifecycles are global as they are wrapped around the `strapi.query()` APIs in which the CTM services use these.

Closing this with the template below as it's not a bug, but you can move the convo over to the forum or Discord

---

Hello,

I see you are wanting to ask a question that is not really a bug report or a feature request, questions should be directed to [our forum](https://forum.strapi.io). Please see the following contributing guidelines for asking a question [here](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue).

**Closed by derrickmehaffy** 2021-09-07 03:55 UTC
