### ISSUE TITLE
Public API shows data that should not be exposed for Public Role

### ISSUE THREAD

**Issue by nabeelvalley** [strapi/strapi#5386] opened 2020-03-02 17:59 UTC
**Describe the bug**
I have two Content Types - one should be public and one the other should not 

When querying the public one the I shouldn't be able to to see the data for the non-public content type, but I am still able to see it in the HTTP response when querying the public one.

My permissions for the content types are as follows:

![image](https://user-images.githubusercontent.com/36758308/75702243-ca403000-5cbd-11ea-9c57-8e3178c902ba.png)

When making the HTTP Request to `/public-entities` I should not be able to see the detail for the `private_entity` data, however the request to `/public-entities` shows the non-public one too:

```json
[
   {
      "id":1,
      "private_entity":{
         "id":1,
         "Name":"I should be private",
         "public_entity":1,
         "created_at":"2020-03-02T17:08:13.187Z",
         "updated_at":"2020-03-02T17:08:52.520Z"
      },
      "Name":"I should be public",
      "created_at":"2020-03-02T17:08:18.463Z",
      "updated_at":"2020-03-02T17:08:52.527Z"
   }
]
```

However when making the request to `/private-entities` I get the expected 403

```json
{
   "statusCode":403,
   "error":"Forbidden",
   "message":"Forbidden"
}
```

**Steps to reproduce the behavior**
1. Clone the [sampe repository](https://github.com/nabeelvalley/strapi-permissions-issue) or copy the model configurations
2. Start in develop
3. Set up permissions for the Public Role as in the screenshot above
4. Make request to `/public-entities`, you should see the Private Entity list in the response data

**Expected behavior**
I would expect the `private__entity` field to be either empty or not present in the `public_entity` response

**System**
- Node.js version: v12.16.0
- NPM version: 6.13.4
- Strapi version: 3.0.0-beta.18.8
- Database: SQLite
- Operating system: Windows 10.0.17763

**Additional context**
I have also been experiencing this with a MongoDB Setup, but that is not reproduced in the [sample repo](https://github.com/nabeelvalley/strapi-permissions-issue)

**Comment by derrickmehaffy** [comment] 2020-03-02 18:02
@alexandrebodin Bug and high/critical? (I was speaking with the user on Slack and wanted him to make this issue as I wasn't sure if it was intended for people to manually set `autoPopulate: false` which is a workaround)

**Comment by alexandrebodin** [comment] 2020-03-02 18:23
@derrickmehaffy This has always been like this. The permissions are on the controller actions only not on the relations. We would need a completely different interface to control this.

**Comment by derrickmehaffy** [comment] 2020-03-02 19:28
I figured as much :thinking: I've just never hit it myself.

**Comment by nabeelvalley** [comment] 2020-03-03 05:54
What would the desired functionality for a case like this be then? Would using the `autoPopulate` param be the way to go about selecting whether or not the data gets filled?

**Comment by alexandrebodin** [comment] 2020-03-03 13:41
You could customize your controller to make sure the data isn't returned.

**Comment by nabeelvalley** [comment] 2020-03-08 11:48
@alexandrebodin great. Thanks for the information

**Comment by derrickmehaffy** [comment] 2020-03-10 07:41
@lauriejim something to add to the "To-Do" on making a guide for? I could see this being a common question.

**Comment by lauriejim** [comment] 2020-03-10 14:48
This already exists here - https://strapi.io/documentation/3.0.0-beta.x/guides/custom-data-response.html#apply-our-changes

**Comment by derrickmehaffy** [comment] 2020-03-10 15:52
Marking as closed for now then as I don't think this will be changed for some time. It can be revisited at a later date when the permissions system gets a rework.

**Closed by derrickmehaffy** 2020-03-10 15:52 UTC
Labels: type: discussion
