### ISSUE TITLE
Plugin Content Manager Error Relation Field

### ISSUE THREAD

**Issue by mehdiraized** [strapi/strapi#4634] opened 2019-12-01 11:52 UTC
Search in AutoCompelete Field Get This Error
i have 140k doctor and response mysql in 0.3s 
![Screen Shot 2019-12-01 at 3 16 14 PM](https://user-images.githubusercontent.com/4368004/69913554-4e301500-144e-11ea-9532-3c484a3ca381.png)

```
error Error: ER_FT_MATCHING_KEY_NOT_FOUND: Can't find FULLTEXT index matching the column list
    at Query.Sequence._packetToError (/U.../node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
```

**Screenshots**
![Screen Shot 2019-12-01 at 3 13 32 PM](https://user-images.githubusercontent.com/4368004/69913446-31471200-144d-11ea-8a26-7bc1077b63d9.png)
<img width="980" alt="Screen Shot 2019-12-01 at 3 17 35 PM" src="https://user-images.githubusercontent.com/4368004/69913519-f5607c80-144d-11ea-9688-71df7be67db2.png">

**System**
- Node.js version: 12
- NPM version: 6
- Strapi version: beta 17.7
- Database: mysql
- Operating system: Cent Os

**Comment by derrickmehaffy** [comment] 2019-12-01 19:23
@mehdiraized when you created your MySQL database what encoding did you use? I believe at least UTF8 would be required to work with (I think that's Arabic? could be wrong)

**Comment by mehdiraized** [comment] 2019-12-02 09:53
@derrickmehaffy 
No This is Persian language
All Table and Database and Fields is UTF-8 encoding
![Screen Shot 2019-12-02 at 1 20 56 PM](https://user-images.githubusercontent.com/4368004/69949390-a75b7f80-1506-11ea-81cf-3621915ef61b.png)
![Screen Shot 2019-12-02 at 1 21 54 PM](https://user-images.githubusercontent.com/4368004/69949454-c528e480-1506-11ea-93be-f6b8a31a4407.png)
![Screen Shot 2019-12-02 at 1 22 14 PM](https://user-images.githubusercontent.com/4368004/69949461-c8bc6b80-1506-11ea-94af-352d83a1c20e.png)

**Comment by lauriejim** [comment] 2019-12-04 14:30
Hello! Can you please provide steps to reproduce.
Because I don't understand what is your issue.

**Comment by derrickmehaffy** [comment] 2019-12-04 15:28
Honestly @lauriejim it looks like his Indexes are corrupt? But I can't tell why?

**Comment by TheRealBarenziah** [comment] 2019-12-06 13:34
Hello,

I believe I ran in a [similar issue](https://github.com/strapi/strapi/issues/4325#issuecomment-546366741)
Have you tried `ALTER TABLE x ADD FULLTEXT INDEX y (z)` (step 1) and/or `yarn build` (afaik, [it may trigger this](https://github.com/strapi/strapi/blob/f378680a000b60343aad65fd921fa00feafe6ebd/packages/strapi-hook-bookshelf/lib/buildDatabaseSchema.js#L41) allowing you to dodge doing the SQL manipulation by hand) ?

**Comment by mauricioaraldi** [comment] 2020-03-05 09:59
I ran into this same issue. I tried @TheRealBarenziah both suggestions (build and manually adding index) but I keep getting the error. Any idea?

**Comment by condran** [comment] 2020-05-01 06:56
I think this happens when you update the schema of a Collection Type (eg add a new Text field). The index does not get created for the new field and then this search error happens. 

I manually dropped the indexes on the modified collection eg: 
`DROP INDEX SEARCH_PEOPLE on peoples;` 

On next restart it updates all the indexes and the error goes away.

**Comment by lauriejim** [comment] 2020-06-09 09:11
Closing this help wanted issue.

**Closed** 2020-06-09 09:11 UTC
Labels: type: help wanted
