### ISSUE TITLE
Error `Cannot read properties of undefined (reading 'push')` when adding component to deeply nested content type in v5

### ISSUE THREAD

**Issue by tammyhart** [strapi/strapi#21267] opened 2024-09-16 02:36 UTC
### Required System information

- Environment: development
- OS: darwin-arm64
- Strapi Version: 5.0.0-rc.23
- Node/Yarn Version: yarn/1.22.22 npm/? node/v20.17.0 darwin arm64
- Edition: Community
- Database: sqlite

### Describe the bug

I have a collection content type called `page`. It has a few fields and a dynamic zone called `content`.
- One of its components is deeply nested, called `block`. 
- Block has some fields as well as a repeatable component called `section`.
- Section has some fields and a repeatable component called `lists`. 
- Lists has a single field and a repeatable component called `items`. 
- Items have a single field.

This has been working beautifully and is the main reason I decided to switch this brand new project to v5.

I have tried a few times to add a component directly to `page` called `seo`. When I load the content manager after adding the component, I get an error: `Cannot read properties of undefined (reading 'push')`

The function the error is happening in is called `formatEditLayout`. The line of code with the push:
```
panels[currentPanelIndex].push(row);
```

I have added `STRAPI_ENFORCE_SOURCEMAPS=true` to my .env, but this is still the best I get.

### Expected behavior

The `seo` component should be available on the `page` content type just as it is working correctly on other content types. The Content Manager should load the `page` admin index without error.

### Additional context

I first attempted to add the `seo` component to `page` at rc.13 and got this identical error. It has continued until the current rc.23

**Comment by tammyhart** [comment] 2024-09-18 07:10
Upon further investigation, I have learned that the error isn't happening because of the deeply nested `block` component in the `content` dynamic zone. It has something to do with the order the view tries to add my fields.

The view is configured like so:
1. text field
2. UID field
3. non-repeatable component: heading
  - text field
  - text field
  - custom field
4. dynamic zone: content
5. dynamic zone: ctas
6. non-repeatable component: seo

If I move `seo` to position 4, the error no longer happens. I'm not familiar with how the view manages to output each field, component, and dynamic zone, but I'm guessing that it behaves fine when it can simply group my fields and components together and then do the dynamic zones, but behaves badly when it tries to build an interface that mixes the order of dynamic zones and components.

**Comment by laurenskling** [comment] 2024-09-18 18:09
Related to: https://github.com/strapi/strapi/issues/20938

This happens when you do _something_ in the view layout. I only get it on one of my contentTypes after migration. Does it happen to you after migration or can you reproduce it in a clean install?

**Comment by tammyhart** [comment] 2024-09-18 23:34
[schema.json](https://github.com/user-attachments/files/17051379/schema.json)
This is the `page` content type schema. Let me know if you need this for any of the components as well.

**Comment by jvdbrink-netpulse** [comment] 2024-09-19 13:16
[schema.json](https://github.com/user-attachments/files/17059647/schema.json)

I'm having similar issues, opening the edit view from Content-Type Builder or just opening the type in the Content-Manager: "panels[currentPanelIndex] is undefined"

**Comment by jvdbrink-netpulse** [comment] 2024-09-19 13:21
One might almost jump to the conclusion it has something to do with the name "page"

**Comment by laurenskling** [comment] 2024-09-19 13:24
I have it on a content type called opening-hours

Op do 19 sep. 2024 15:21 schreef jvdbrink-netpulse ***@***.***

**Comment by at-woutervanderschagt** [comment] 2024-09-20 12:17
Same issue, i have 2 custom components, one dynamic zone and below that a few more custom components on a single type called "GlobalPage".

When i drag the components around in "config view" i get exactly the same error message.

Using strapi@latest (5.0.0).

**Comment by remidej** [comment] 2024-09-26 16:36
From my testing it seems like like the bug only happens when the dynamic zone if the first field in the content type. Please let me know if that's not the case for you

**Comment by jvdbrink-netpulse** [comment] 2024-09-26 17:56
> From my testing it seems like like the bug only happens when the dynamic zone is the first field in the content type. Please let me know if that's not the case for you

This is not the case for me, as you can see in the posted schema.json above. I might however run into the bug via a different route than others with similar error messages.

**Comment by laurenskling** [comment] 2024-09-26 18:07
@remidej you are absolutely right! Just tested with a clean install. Putting the DZ first in `configure the views` results in this reported crash!

**Comment by tammyhart** [comment] 2024-09-26 18:49
@remidej as you can see in my schema, this is not the case for me. Also, I just remembered that I manually moved the `seo` component above the dynamic zones when I was trying to debug things.

**Comment by laurenskling** [comment] 2024-09-26 18:55
The schema is not the view

**Comment by tammyhart** [comment] 2024-09-26 18:58
As stated in [this comment](https://github.com/strapi/strapi/issues/21267#issuecomment-2357677227) from last week, that is also not the case for me

**Comment by laurenskling** [comment] 2024-09-26 19:04
How are you able to configure the view? When this bug happens, it also happens on the configure the view page for me

**Comment by laurenskling** [comment] 2024-09-26 19:19
@tammyhart you are right. I've been testing, and 2/3/+ DZ + 1 or more somethings at the end makes it crash as well. 
I've been trying all combinations. Something with 2+ DZ, not last. But 1 at first will crash as well. @remidej can figure it out I'm sure ;)

**Comment by tammyhart** [comment] 2024-09-26 19:23
Oh boy, I hacked my ability to do that too. First, I removed the `seo` component from the schema. This allowed the configure view route to load properly. Then I put the component back into the schema and reloaded the route and it allows me to make changes.

However, the error first presented when I added `seo` originally and tried to load the `page` index route. I've been able to get around this error by using the above hack to force `seo` above my dynamic zones in the view configuration.

A follow-up issue I plan to add later is that the drag and drop interface for configuring views is severely lacking. I can't seem to drag anything above the first item or below the last item, and things shift badly when you drag anything. I was able to get it to work by magnifying the page by like 200%. For some reason, dragging and dropping works as expected when the viewport is technically narrower. Dunno how I figured that out, but yeah...

**Comment by laurenskling** [comment] 2024-09-26 19:25
> Oh boy, I hacked my ability to do that too. First, I removed the `seo` component from the schema. This allowed the configure view route to load properly. Then I put the component back into the schema and reloaded the route and it allows me to make changes.
> 
> However, the error first presented when I added `seo` originally and tried to load the `page` index route. I've been able to get around this error by using the above hack to force `seo` above my dynamic zones in the view configuration.
> 
> A follow-up issue I plan to add later is that the drag and drop interface for configuring views is severely lacking. I can't seem to drag anything above the first item or below the last item, and things shift badly when you drag anything. I was able to get it to work by magnifying the page by like 200%. For some reason, dragging and dropping works as expected when the viewport is technically narrower. Dunno how I figured that out, but yeah...

i too noticed dragging worked badly. Different to v4 at least.

**Comment by tammyhart** [comment] 2024-09-26 19:26
> i too noticed dragging worked badly. Different to v4 at least.

Yes, it's definitely a new issue with v5. In v4, dragging and dropping was flawless

**Comment by jvdbrink-netpulse** [comment] 2024-09-26 19:37
> The schema is not the view

True, but if you don't alter the view or as in my/our case are not able to, the order is determined by the schema I believe.

**Comment by laurenskling** [comment] 2024-09-26 19:38
> > The schema is not the view
> 
> True, but if you don't alter the view or as in my/our case are not able to, the order is determined by the schema I believe.

yes, initially, the view is just based on your schema. but the problem lies with the view, not with the schema. That was what I was trying to say.

**Comment by tammyhart** [comment] 2024-09-26 20:29
The problem exists outside of the configure view route. The error is thrown on the content type index route. Thus, the default order derived from the schema is relevant.

**Comment by remidej** [comment] 2024-09-27 08:12
Hello all, thanks for the details. I have a tentative fix but not sure yet if it covers all cases. Can you try upgrading Strapi to this experimental version and letting me know if the bug still occurs?

`0.0.0-experimental.b9dd0757c8a7db6ee1063edc33424319784ae3a6`

**Comment by remidej** [comment] 2024-09-27 10:40
@jvdbrink-netpulse could you test it too, since your case may be different?

**Comment by remidej** [comment] 2024-09-27 10:43
@cur1ou5soul are you talking about the content API?

**Comment by at-woutervanderschagt** [comment] 2024-09-27 11:09
I just tried it with v5.0.1 and the issue doesn't seem resolved yet.

I have a single type with a dynamic zone with 2 components (simple text), and an additional text component under it. When i go to the content i get the same error message "cannot read properties of undefined (push)".

**Comment by alexandrebodin** [comment] 2024-09-27 12:13
@at-woutervanderschagt  you need to test the experimental release made by @remidej the fix hasn't been released yet we need some help to confirm it fixes your issues 🙏 

`0.0.0-experimental.b9dd0757c8a7db6ee1063edc33424319784ae3a6`

**Comment by jvdbrink-netpulse** [comment] 2024-09-27 14:44
> @jvdbrink-netpulse could you test it too, since your case may be different?

Will do so shortly

**Comment by tammyhart** [comment] 2024-09-27 15:28
@remidej this experimental version seems to resolve the error. I'm no longer getting it on the configure view route or the index route

**Comment by jvdbrink-netpulse** [comment] 2024-09-27 15:39
> > @jvdbrink-netpulse could you test it too, since your case may be different?
> 
> Will do so shortly

Some interesting but discouraging findings:

used: npx create-strapi-app@0.0.0-experimental.b9dd0757c8a7db6ee1063edc33424319784ae3a6 test_release
Shows version 5 in the admin but the experimental version for deps: @strapi/plugin-cloud, @strapi/plugin-users-permissions, @strapi/strapi, Is this a correct way to test the build?

First replicating the error with old database export on 5.0 release and the issues did not occur, adding fields to the content-type (bools, text, media) the issue from before came back:  panels[currentPanelIndex] is undefined

Swapping the version over to 0.0.0-experimental.b9dd0757c8a7db6ee1063edc33424319784ae3a6 the issue still occurred removing the extra added fields from the schema and restarting and everything works.

Furthermore the copy error button does not work for me copies:
```

```

I also ran into: error loading dynamically imported module: https://strapi5.netpulse-dev.nl/node_modules/.strapi/vite/deps/EditViewPage-B82x_x1b-OYE3FE4I.js?v=8418d9fd 

But this was resolved by removing the .strapi folder and restarting.

**Comment by tammyhart** [comment] 2024-09-27 16:12
I just created a new branch, changed the strapi version in my package.json, and ran `yarn`.

```
  "dependencies": {
    "@strapi/plugin-cloud": "0.0.0-experimental.b9dd0757c8a7db6ee1063edc33424319784ae3a6",
    "@strapi/plugin-users-permissions": "0.0.0-experimental.b9dd0757c8a7db6ee1063edc33424319784ae3a6",
    "@strapi/strapi": "0.0.0-experimental.b9dd0757c8a7db6ee1063edc33424319784ae3a6",
    ...
```

**Comment by laurenskling** [comment] 2024-09-28 14:46
> Hello all, thanks for the details. I have a tentative fix but not sure yet if it covers all cases. Can you try upgrading Strapi to this experimental version and letting me know if the bug still occurs?
> 
> `0.0.0-experimental.b9dd0757c8a7db6ee1063edc33424319784ae3a6`

Seems to be working in all cases I could come up with :)

**Comment by at-woutervanderschagt** [comment] 2024-09-30 07:02
> @at-woutervanderschagt you need to test the experimental release made by @remidej the fix hasn't been released yet we need some help to confirm it fixes your issues 🙏
> 
> `0.0.0-experimental.b9dd0757c8a7db6ee1063edc33424319784ae3a6`

In this experimental version it seems to be working :) Thanks! I haven't encountered the error yet in this version. I will continue to test.

**Comment by remidej** [comment] 2024-09-30 08:36
Thanks for your comments, I'll merge it now. We'll ship it in the next patch release on Wednesday

@cur1ou5soul it's likely your relations issue will be fixed by #21428 shipping in the same release, if it's not, please open a new issue

**Closed** 2024-09-30 08:36 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:content-manager

**Comment by ManoloTonto1** [comment] 2024-10-01 18:13
> From my testing it seems like like the bug only happens when the dynamic zone is the first field in the content type. Please let me know if that's not the case for you

this was the case for me, extremely weird, I am on strapi 5.0.1

**Comment by at-woutervanderschagt** [comment] 2024-10-03 07:12
I've just tried it with version 5.0.2 and the issue remains. I'm still getting the error "cannot read properties of undefined (push)".....however I'm not getting it in the experimental version.

**Comment by jvdbrink-netpulse** [comment] 2024-10-03 08:04
> > > @jvdbrink-netpulse could you test it too, since your case may be different?
> > 
> > 
> > Will do so shortly
> 
> Some interesting but discouraging findings:
> 
> used: npx create-strapi-app@0.0.0-experimental.b9dd0757c8a7db6ee1063edc33424319784ae3a6 test_release Shows version 5 in the admin but the experimental version for deps: @strapi/plugin-cloud, @strapi/plugin-users-permissions, @strapi/strapi, Is this a correct way to test the build?
> 
> First replicating the error with old database export on 5.0 release and the issues did not occur, adding fields to the content-type (bools, text, media) the issue from before came back: panels[currentPanelIndex] is undefined
> 
> Swapping the version over to 0.0.0-experimental.b9dd0757c8a7db6ee1063edc33424319784ae3a6 the issue still occurred removing the extra added fields from the schema and restarting and everything works.
> 
> Furthermore the copy error button does not work for me copies:
> 
> ```
> 
> ```
> 
> I also ran into: error loading dynamically imported module: https://strapi5.netpulse-dev.nl/node_modules/.strapi/vite/deps/EditViewPage-B82x_x1b-OYE3FE4I.js?v=8418d9fd
> 
> But this was resolved by removing the .strapi folder and restarting.

Haven't been able to test since but I still had a related bug too, the error I had was:
` panels[currentPanelIndex] is undefined`
I'm not sure this method is also valid for testing:
` npx create-strapi-app@SPECIFIC_VERSION test_release`
But I assume it is.

**Comment by mad-zephyr** [comment] 2024-10-06 14:45
Currentrly, have project with "@strapi/strapi": "5.0.2", Issue remains 
step to reproduce
create collection entity ex: page

**if Component goes after DinamicZone you will got error** 

````
TypeError: Cannot read properties of undefined (reading 'push')
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-2Q67S5MJ.js?v=b5b63de7:1065:33
    at Array.reduce (<anonymous>)
    at formatEditLayout (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-2Q67S5MJ.js?v=b5b63de7:1057:5)
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-2Q67S5MJ.js?v=b5b63de7:1010:32
    at mountMemo (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=b5b63de7:12214:27)
    at Object.useMemo (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=b5b63de7:12538:24)
    at Object.useMemo (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-BCGHH3YY.js?v=b5b63de7:1094:29)
    at useDocumentLayout (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-2Q67S5MJ.js?v=b5b63de7:1009:28)
    at useDocLayout (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-2Q67S5MJ.js?v=b5b63de7:1043:10)
    at EditConfigurationPage (http://localhost:1337/node_modules/.strapi/vite/deps/EditConfigurationPage-DdPNAbl3-O2MENPEO.js?v=b5b63de7:60:61)
````

**if DynamicZone goes after Component in this case everythings OK**

**Comment by tommarshall** [comment] 2024-10-07 10:19
The issue is still present for me in the latest `5.0.2` release.

Re-ordering the attributes in the `schema.json` of the impacted type to put the Dynamic Zone at the bottom works as a workaround.

**Comment by jannescb** [comment] 2024-10-09 14:29
I still got this issue with `5.0.2` and I can also work around it by re-ordering the attributes so that the Dynamic Zone is not the very first attribute.

**Comment by at-woutervanderschagt** [comment] 2024-10-11 07:03
I tried it with v5.0.5 and it appears to work. Thanks.

I will continue testing and report back here if i encounter any similar issues.

**Comment by Sagar-echo** [comment] 2024-10-14 13:56
I tried it with v5.0.6 and it still throws same error

**Comment by tammyhart** [comment] 2024-10-22 03:28
Finally got around to bumping my project to a stable release: 5.1.0

Everything is working as expected for me
