### ISSUE TITLE
SQL syntax error when attempting to save a relation

### ISSUE THREAD

**Issue by iantrudell** [strapi/strapi#14904] opened 2022-11-16 22:00 UTC
### Required System information

- Node.js version: 18.12.1
- NPM version: 7.0.0
- Strapi version: 4.5.1
- Database: MySQL 5.7.31
- Operating system: Ubuntu 20.04.1 LTS

### Describe the bug

When attempting to update a relation using the standard REST endpoints, I am getting a SQL syntax error:

This is the SQL statement it is attempting to run:
```sql
UPDATE `clients_bdms_links` as a, (SELECT `id`, ROW_NUMBER() OVER (PARTITION BY `client_id` ORDER BY `resource_order`) AS src_order FROM `clients_bdms_links` WHERE `client_id` = 3) AS b SET `resource_order` = b.src_order WHERE b.id = a.id
```

When I paste that query into MySQL Workbench, it says:

```"(" is not valid at this position, expecting FOR, LOCK, ')'```

```Error Code: 1064. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `client_id` ORDER BY `resource_order`) AS src_order FROM `clients_' at line 1```

### Steps to reproduce the behavior

1. Save a relation via REST
2. Query has a syntax error

### Expected behavior

Able to execute an update on a relation table

### Full error log

```
1|STRAPI4  | [2022-11-16 16:50:16.184] error: UPDATE
1|STRAPI4  |             `clients_bdms_links` as a,
1|STRAPI4  |             (
1|STRAPI4  |               SELECT `id`, ROW_NUMBER() OVER (PARTITION BY `client_id` ORDER BY `resource_order`) AS src_order
1|STRAPI4  |               FROM `clients_bdms_links`
1|STRAPI4  |               WHERE `client_id` = 3
1|STRAPI4  |             ) AS b
1|STRAPI4  |           SET `resource_order` = b.src_order
1|STRAPI4  |           WHERE b.id = a.id - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `client_id` ORDER BY `resource_order`) AS src_order
1|STRAPI4  |               ' at line 3
1|STRAPI4  | Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(PARTITION BY `client_id` ORDER BY `resource_order`) AS src_order
1|STRAPI4  |               ' at line 3
1|STRAPI4  |     at Query.Sequence._packetToError (/home/test/backend/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
1|STRAPI4  |     at Query.ErrorPacket (/home/test/backend/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
1|STRAPI4  |     at Protocol._parsePacket (/home/test/backend/node_modules/mysql/lib/protocol/Protocol.js:291:23)
1|STRAPI4  |     at Parser._parsePacket (/home/test/backend/node_modules/mysql/lib/protocol/Parser.js:433:10)
1|STRAPI4  |     at Parser.write (/home/test/backend/node_modules/mysql/lib/protocol/Parser.js:43:10)
1|STRAPI4  |     at Protocol.write (/home/test/backend/node_modules/mysql/lib/protocol/Protocol.js:38:16)
1|STRAPI4  |     at Socket.<anonymous> (/home/test/backend/node_modules/mysql/lib/Connection.js:88:28)
1|STRAPI4  |     at Socket.<anonymous> (/home/test/backend/node_modules/mysql/lib/Connection.js:526:10)
1|STRAPI4  |     at Socket.emit (events.js:400:28)
1|STRAPI4  |     at Socket.emit (domain.js:475:12)
1|STRAPI4  |     --------------------
1|STRAPI4  |     at Protocol._enqueue (/home/test/backend/node_modules/mysql/lib/protocol/Protocol.js:144:48)
1|STRAPI4  |     at Connection.query (/home/test/backend/node_modules/mysql/lib/Connection.js:198:25)
1|STRAPI4  |     at /home/test/backend/node_modules/knex/lib/dialects/mysql/index.js:132:18
1|STRAPI4  |     at new Promise (<anonymous>)
1|STRAPI4  |     at Client_MySQL._query (/home/test/backend/node_modules/knex/lib/dialects/mysql/index.js:126:12)
1|STRAPI4  |     at executeQuery (/home/test/backend/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
1|STRAPI4  |     at Client_MySQL.query (/home/test/backend/node_modules/knex/lib/client.js:146:12)
1|STRAPI4  |     at /home/test/backend/node_modules/knex/lib/execution/transaction.js:363:24
1|STRAPI4  |     at new Promise (<anonymous>)
1|STRAPI4  |     at Client_MySQL.trxClient.query (/home/test/</anonymous>backend/node_modules/knex/lib/execution/transaction.js:358:12)
```

**Comment by andoro** [comment] 2022-11-16 23:59
I have the same issue I think.
In my example I've a carousel, which has related field (manufacturer).
When I try to save I get a server error 500

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/775765/202320694-e99944da-0056-4935-8d40-2e4f58356a3b.png">

<img width="843" alt="image" src="https://user-images.githubusercontent.com/775765/202320719-eaf52194-855e-42da-8b6c-6d9443513f5a.png">

**Comment by gu-stav** [comment] 2022-11-17 05:38
Duplicate of https://github.com/strapi/strapi/issues/14840

**Closed by gu-stav** 2022-11-17 05:38 UTC
