### ISSUE TITLE
Forbidden attribute naming keeps crushing the admin 

### ISSUE THREAD

**Issue by ihmpavel** [strapi/strapi#14511] opened 2022-09-30 14:41 UTC
## Bug report
Naming sections attributes as `fields` causing error while getting data in a plugin.
_See `Example 1` below_ 

_Edit: Naming anything from https://github.com/strapi/strapi/blob/main/packages/core/utils/lib/convert-query-params.js#L239 is the problem - not just `fields`_

### Required System information

- Node.js version: 16.15.1
- NPM version: 8.11.0
- Strapi version: 4.4.1
- Database: PostgreSQL
- Operating system: Unix

### Describe the bug

Create component `sections/table.json`
```
{
  "collectionName": "components_sections_tables",
  "info": {
    "displayName": "Table",
    "icon": "table"
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "string"
    },
    "fields": { // <-- name is the problem
      "type": "component",
      "repeatable": true,
      "component": "components.content"
    }
  }
}
```
and `components/content.json`
```
{
  "collectionName": "components_components_contents",
  "info": {
    "displayName": "Content",
    "icon": "paragraph",
    "description": ""
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "text"
    },
    "content": {
      "type": "text"
    }
  }
}
```

Use it on some page.

In the administration everything is OK. You can edit/create/delete without issue.

Create a plugin and try to populate all text content on backend using `strapi.entityService.findOne...`

Everything should pass, but an error `Invalid fields parameter. Expected a string or an array of strings` occurs. Stacktrace is below.

### Expected behavior
After renaming `attributes -> fields` to `attributes -> something`, everything works without issue.

### Code snippets
_Example 1_
```
{
  "collectionName": "components_sections_tables",
  "info": {
    "displayName": "Table",
    "icon": "table"
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "string"
    },
    "fields": { // <-- rename to something else - an error will not occur again
      "type": "component",
      "repeatable": true,
      "component": "components.content"
    }
  }
}
```

Input for the function `convertFieldsQueryParams` is `{ populate: '*' }` and `0`. The parent function `convertNestedPopulate` receives `{ populate: '*', fields: { populate: '*' } }` where `fields` are component attributes - not some core feature.

Error in the console
```
 error: Invalid fields parameter. Expected a string or an array of strings

Error: Invalid fields parameter. Expected a string or an array of strings
    at convertFieldsQueryParams (/opt/node_modules/@strapi/utils/lib/convert-query-params.js:282:9)
    at convertNestedPopulate (/opt/node_modules/@strapi/utils/lib/convert-query-params.js:252:20)
    at /opt/node_modules/@strapi/utils/lib/convert-query-params.js:212:28
    at Array.reduce (<anonymous>)
    at convertPopulateObject (/opt/node_modules/@strapi/utils/lib/convert-query-params.js:165:35)
    at convertPopulateQueryParams (/opt/node_modules/@strapi/utils/lib/convert-query-params.js:152:12)
    at transformParamsToQuery (/opt/node_modules/@strapi/strapi/lib/services/entity-service/params.js:43:22)
    at Object.findMany (/opt/node_modules/@strapi/strapi/lib/services/entity-service/index.js:63:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Bug found while using https://github.com/localazy/strapi-plugin, but the issue is in the Strapi core

**Comment by ihmpavel** [comment] 2022-10-19 18:06
Hi @derrickmehaffy 
Is the error of intended behavior or it should be documented in the docs? 

On [Discord](https://discord.com/channels/811989166782021633/1028777488555446272/1028777488555446272) is more info.

**Comment by derrickmehaffy** [comment] 2022-10-31 17:48
I believe this is a duplicate of https://github.com/strapi/strapi/issues/1198, it's absolutely not intended.

**Closed by derrickmehaffy** 2022-10-31 17:48 UTC
