### ISSUE TITLE
Update trigger ER_LOCK_DEADLOCK on database

### ISSUE THREAD

**Issue by PakornRu** [strapi/strapi#15434] opened 2023-01-13 07:33 UTC
### Required System information

- Node.js version: 16.18
- NPM version: 8
- Strapi version: 4.5.5
- Database: MySQL
- Operating system: node:16.18.0-bullseye-slim

### Describe the bug
- We found some unexpected return from Strapi which return Internal Errors
- After check logs we found that our database (AWS-RDS) trigger ER_LOCK_DEADLOCK: Deadlock
### Steps to reproduce the behavior

1. Create Single type 
```{
  "collectionName": "components_campaign_hero_carousels",
  "info": {
    "displayName": "HeroCarousel",
    "description": ""
  },
  "options": {},
  "attributes": {
    "name": {
      "type": "string",
      "required": true
    },
    "remark": {
      "type": "text",
      "private": true
    },
    "actionLink": {
      "type": "enumeration",
      "enum": [
        "URL",
        "Component"
      ],
      "required": true,
      "default": "URL"
    },
    "urlLink": {
      "type": "string"
    },
    "activeOn": {
      "type": "datetime",
      "required": true
    },
    "expiresAt": {
      "type": "datetime",
      "required": true
    },
    "imageWeb": {
      "type": "media",
      "multiple": false,
      "required": true,
      "allowedTypes": [
        "images"
      ]
    },
    "imageMobile": {
      "type": "media",
      "multiple": false,
      "required": true,
      "allowedTypes": [
        "images"
      ]
    }
  }
}
```
2. Fill data from Content Manager 3-4 row 
3. Try to save data
4. Edit of change sequence and try to save again
5. Strapi Can't save and return 500, I found log in system 
```
[2023-01-10 07:30:37.881] [31merror[39m: delete from `files_related_morphs` where (`related_id` = 34 and `related_type` = ‘campaign.hero-carousel’ and `field` = ‘imageWeb’) - ER_LOCK_DEADLOCK: Deadlock found when trying to get lock; try restarting transaction
```

### Expected behavior

It should not trigger any ER_LOCK_DEADLOCK

### Screenshots

<img width="564" alt="image" src="https://user-images.githubusercontent.com/121850992/212262710-c012b69c-4234-4e96-be23-0065772c2883.png">

<img width="1079" alt="image (1)" src="https://user-images.githubusercontent.com/121850992/212262773-ef5e50e8-9a2b-4804-8a80-14ef3895eefb.png">

### Additional context

- We use ECS as our cluster with running 2 tasks
- We use RDS as our database with running on MySQL 8.0
-

**Comment by MHZarei** [comment] 2023-01-16 12:18
I have same problem on admin_users table.
I changed another entity, but after restart Strapi, it want remove update and create foreign key.

**Comment by petersg83** [comment] 2023-01-20 13:34
Hello :) Thank you for the report and the steps to reproduce ! It's a known issue since #15202. We already released multiple fixes but they seem to not have been enough. We are working on a more solid fix that I hope will be released for the next release :)
If it's ok for you I'll close this issue in favor of #15202 :)

**Closed by petersg83** 2023-01-20 13:34 UTC
