### ISSUE TITLE
GraphQL: Shadow CRUD cannot be disabled

### ISSUE THREAD

**Issue by yeegor** [strapi/strapi#10996] opened 2021-09-16 15:25 UTC
### Describe the bug

The server is unabled to start when the `strapi-plugin-graphql` is installed and `shadowCRUD` is set to `false` in the configuration.

### Steps to reproduce the behavior

1. In the Strapi project, run `npm run strapi install graphql`
2. Go to `config/plugins.js` and set `graphql.shadowCRUD` to `false`
3. Start the server with `strapi develop`
4. The following error occurs.

Please note that in the snippet below I have replaced the actual absolute paths `/Users/name/.../project-name` with `...`

```bash
[2021-09-16T15:11:13.511Z] debug ⛔️ Server wasn't able to start properly.
[2021-09-16T15:11:13.512Z] error TypeError: Cannot read property 'startsWith' of undefined
    at getActionDetails (.../strapi/node_modules/strapi-plugin-graphql/services/utils.js:153:16)
    at getPolicies (.../strapi/node_modules/strapi-plugin-graphql/services/resolvers-builder.js:179:7)
    at buildQuery (.../strapi/node_modules/strapi-plugin-graphql/services/resolvers-builder.js:94:38)
    at .../strapi/node_modules/strapi-plugin-graphql/services/schema-generator.js:166:44
    at Array.reduce (<anonymous>)
    at .../strapi/node_modules/strapi-plugin-graphql/services/schema-generator.js:149:41
    at Array.reduce (<anonymous>)
    at buildResolvers (.../strapi/node_modules/strapi-plugin-graphql/services/schema-generator.js:144:33)
    at Object.generateSchema (.../strapi/node_modules/strapi-plugin-graphql/services/schema-generator.js:49:49)
    at Object.initialize (.../strapi/node_modules/strapi-plugin-graphql/hooks/graphql/index.js:76:74)
    at .../strapi/node_modules/strapi/lib/hooks/index.js:37:28
error Command failed with exit code 1.
```

### Expected behavior

The server starts properly, default CRUD GraphQL queries and mutations are inaccessible.

### Code snippets

See the configuration file below:

```js
upload: { ... },
email: { ... },
graphql: {
  endpoint: '/graphql',
  shadowCRUD: false,
  playgroundAlways: false,
  depthLimit: 7,
  amountLimit: 100,
  apolloServer: {
    tracing: true
  }
}
```

### System

- Node.js version: 14.16.0
- NPM version: 7.12.0 <- ran `strapi install graphql` with this
- YARN version: 1.18.0 <- installed the dependencies with this
- Strapi version: 3.6.6, 3.6.8
- Database: MongoDB
- Operating system: MacOS Big Sur 11.5.2

### Additional context

The users-permissions plugin is used in the application too.

EDIT: Address the `users-permissions` plugin in the Additional Context block.

**Comment by marcoautiero** [comment] 2023-03-05 22:12
Closing because the issue is fixed in v4

**Closed by marcoautiero** 2023-03-05 22:12 UTC
Labels: issue: bug, status: confirmed, source: plugin:graphql
