### ISSUE TITLE
Required component doesn't validate require

### ISSUE THREAD

**Issue by abdonrd** [strapi/strapi#5862] opened 2020-04-18 10:32 UTC
**Describe the bug**

Required component doesn't validate require

**Steps to reproduce the behavior**

1. Create a Type with a required Component
2. Try to create a new document from the admin panel without the required Component

**Expected behavior**

I expect a warning for the required Component, but it creates the document

**Screenshots**

<img width="917" alt="Screenshot 2020-04-18 at 12 18 12" src="https://user-images.githubusercontent.com/1007051/79635043-ba49b600-816e-11ea-9795-a3e4e91a106d.png">

**System**

- Node.js version: v12
- NPM version: v6
- Strapi version: v3.0.0-beta.20
- Database: MongoDB
- Operating system: macOS

**Comment by derrickmehaffy** [comment] 2020-04-18 10:45
Components are treated like relations in the backend so this would be a duplicate of: https://github.com/strapi/strapi/issues/557

**Closed by derrickmehaffy** 2020-04-18 10:45 UTC
