### ISSUE TITLE
Non-localizable fields don't keep their value after locale switch and no "fill in from another locale" button in collection types

### ISSUE THREAD

**Issue by drazik** [strapi/strapi#17700] opened 2023-08-18 14:04 UTC
### Required System information

- Node.js version: 18.12.1
- NPM version: 8.19.2
- Strapi version: 4.12.5
- Database: MySQL 5.7
- Operating system: Ubuntu 22.04.3
- Is your project Javascript or Typescript: Typescript

### Describe the bug
I have two locales in my application: fr (default) and en. I have a `team-member` collection type with 3 non-localizable fields and 1 localizable field. When I fill the FR locale data and save it, then switch to English locale, I don't see the "Fill in from another locale" button and all the fields are empty, forcing me to re-type all the non-localizable fields data.

After filling the EN data and saving, the "Fill in from another locale" button appears.

The problem also exist on edit.

### Steps to reproduce the behavior

1. Create an item in a collection type with localizable fields
2. Fill all fields of the default locale
3. Save it
4. Switch to another locale
5. Non-localizable fields are empty and "Fill in from another locale" button is absent

### Expected behavior

The non-localizable fields should keep the value entered for the default locale, and the "Fill in from another locale" button should be visible.

### Screenshots

Default locale (FR) data entered and saved:

![image](https://github.com/strapi/strapi/assets/1606068/59b00d12-b310-427c-a36e-e732e09d7df0)

After switch to other locale (EN):

![image](https://github.com/strapi/strapi/assets/1606068/6ac227ca-01ea-4142-bb7f-ddeba1d7481f)

### Code snippets

N/A

### Additional context
N/A

**Comment by BennyMoser** [comment] 2023-08-22 10:07
i have the same issue as described by @drazik after updating from 4.10.5 to 4.12.5. (node 18.17.1)

reloading the page loads the "Fill from another locale" button, but it would be helpful to have the old behavior back.

**Comment by rktyt** [comment] 2023-08-24 09:29
Same issue.
strapi v4.12.6

We have upgraded from 4.11.3 to 4.12.1 and then to 4.12.6.
However, we are not upgrading the production environment because of a critical bug for us.
This is one of them.

**Comment by web-admin** [comment] 2023-09-07 10:54
Same here... Updated to 4.13.3.
Fill up default EN language -> move to other language and the "Fill from another locale" link is not visible -> you have to refresh to see it. Also in this case ready languages are not visible (no green dot next to them) ->refresh helps again.

**Comment by derrickmehaffy** [comment] 2023-09-07 18:25
Might be related to (or duplicate of https://github.com/strapi/strapi/issues/17860)

**Comment by Eventyret** [comment] 2023-09-15 14:25
Escalated due to confirmation from TID 4804

**Comment by MAxiaq** [comment] 2023-10-06 10:25
Any update on this, I ran into the same problem after updating to 4.14.0. Is this being looked into?

**Comment by Boegie19** [comment] 2023-10-06 10:27
I am 99% sure it does since they escalated it due to an internal ticket of an enterprise user.

**Comment by lukesmmr** [comment] 2023-10-10 17:20
Any update on this issue? We can still verify this behaviour in `4.14.3`.

**Comment by derrickmehaffy** [comment] 2023-10-12 19:50
I've mentioned it to our engineers in a call yesterday (specifically to an engineering manager) and they will take a look.

However it looks like a community member has made a PR that might also resolve it.

**Comment by joshuaellis** [comment] 2023-10-19 09:31
I've just taken a look at this issue using our latest `main` version and i've not been able to reproduce (see video attached) have you upgraded and rechecked the issue is still happening? 

https://github.com/strapi/strapi/assets/37798644/f4aee72b-6440-447a-894f-9578ea3dbb18

**Comment by JustTB** [comment] 2023-10-23 15:23
I can still reproduce it after update to current version v4.14.5
Since this is a race condition (looking at the fix above) you might try more complex types with relations.
v4.14.5 did not solve that for us.

**Comment by derrickmehaffy** [comment] 2023-10-23 22:56
If the issue isn't closed and the PR isn't merged then it was never released, constantly stating the issue is still happening does not help here. The PR is pending review, when it's merged and released is when it will be fixed.

**Comment by BennyMoser** [comment] 2023-10-24 08:27
I can confirm that this problem occurs in the latest version 4.14.5. 

It took me 5 minutes to reproduce this error with the normal strapi create cli. All I did was add a localizable collection type and even with just one field the error is reproducible. 
Here is the link for my project, hoping someone can fix this problem: 
[https://github.com/BennyMoser/strapi-localization-bug](https://github.com/BennyMoser/strapi-localization-bug) 


https://github.com/strapi/strapi/assets/107918220/d6ac50d1-46a0-424b-8c6e-bf317ef808d8

**Comment by derrickmehaffy** [comment] 2023-10-24 18:57
I'm also able to reproduce the issue but the "fill in button" doesn't even exist anymore for me either:

https://www.loom.com/share/9c0393ec505b4f1aab724e7719089eed?sid=27ca6f0e-7a46-40fb-8fe8-cdc853990c41

**Comment by JustTB** [comment] 2023-10-26 02:31
Just as a note. Still reproducible in 4.15.0
@derrickmehaffy yes the fill in button only comes when server side rendering as well - but it was the whole time like that for us - just a page refresh helps (triggers server side rendering)

**Comment by sam-gre** [comment] 2023-11-24 10:13
I can confirm the same. I have upgraded to the latest stable version of strapi (4.15.4) and have the exact same issues. Something i noticed is that if the locale already has content, the "fill from another localed" appears. If no content, then it requires the reload for it to appear.

**Comment by JustTB** [comment] 2024-03-01 02:03
It would be really nice if this issue gets some attention. Since the PR is open with a comment from January that it will be fixed in the afternoon. Please, please fix. 🙏🏽 🥺

**Comment by hanpaine** [comment] 2024-03-26 17:37
Thanks for your patience folks - we're hoping to get the fix merged this week and deployed next 🤞🏻

**Comment by derrickmehaffy** [comment] 2024-03-26 23:37
> It would be really nice if this issue gets some attention. Since the PR is open with a comment from January that it will be fixed in the afternoon. Please, please fix. 🙏🏽 🥺 

Sorry about that, fell off my radar. PR updated and hopefully should be merged soon.

**Closed** 2024-03-27 11:53 UTC
Labels: issue: bug, severity: high, status: confirmed, source: plugin:i18n, flag: EE

**Comment by filonitta** [comment] 2024-11-24 12:30
strapi@5.4.1 - the issue persists
