### ISSUE TITLE
Plugin upload multiple - Remove a file need to remove the relation too

### ISSUE THREAD

**Issue by Lith** [strapi/strapi#5380] opened 2020-03-02 11:29 UTC
Hello,

- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [x] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
This feature concern the `strapi-plugin-upload` with "_**Multiple Medias**_" version.

When I `DELETE ​/upload​/files​/{id}` a file, the relation is not removed and an array with empty element are returned from the API.

For now : 
- I need to rewrite API response into Client in order to remove manually all empty data from the JSON response.
- I need to "cron" a task that remove all relations from removed media (_madness_)

**Your suggestions for this topic**
When I want to remove a file, with the route `DELETE ​/upload​/files​/{id}`, this will remove the relation in `upload_file_morph` and the entry in `upload_file`.

**Screenshots**
_None for now._

**Code snippets**
_None for now._

**Additional context**
- Relate maybe with #4918 

**Environment**
- Strapi beta 18.8
- Bookshelf: MySQL
- Provider : test with local & Google Cloud Storage

**Comment by derrickmehaffy** [comment] 2020-03-02 11:37
Marking this as discussion as me and @Lith discussed on slack.

There is a few parts to this:
- Need documentation on how to properly handle both single and multi file deletes
- How to handle files that have a relation to a model entry
- (Soon) How to handle deleting just the entry relation and not the file itself for the new media library feature

The way I understand it currently is you fire a PUT (or DELETE) request to the model entry to either remove the relation or delete the entry entirely (this leaves the file and likewise the file database entry intact). 

Then you need to delete the file entry itself with another DELETE entry, this should also delete the actual file from the filesystem or the provider.

Strapi Team (@alexandrebodin @lauriejim ?) can you guys weigh in on this and correct me and @Lith if we are wrong here?

In either case documentation needs to be updated to handle this as I've seen this question come up especially when relating to cascading delete, I'm sure with the new media lib being worked on, this will only further complicate this issue.

The only information I could find in the current docs is just stating that `DELETE /upload/files/:id` exists, not what it does or how it handles related entries linked to that file.

https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#endpoints

**Comment by alexandrebodin** [comment] 2020-03-02 12:18
@derrickmehaffy  This is just a bug here. When deleting a file the relations to it should be deleted from db.

**Comment by derrickmehaffy** [comment] 2020-03-02 13:37
> @derrickmehaffy This is just a bug here. When deleting a file the relations to it should be deleted from db.

That's what I thought but I could of sworn seeing something about cascade delete. Do you want me to mark this as a bug and confirmed?

**Comment by alexandrebodin** [comment] 2020-03-02 13:48
Might be a duplicate 🤔

**Comment by derrickmehaffy** [comment] 2020-03-02 13:50
I think the other one got converted into a feature request and is now on the product board even though it is a bug :laughing: There is a reason for the product board though relating to other types of relations with cascade delete.

This upload one as you said is most certainly a bug. :wink:

**Comment by windwp** [comment] 2020-03-04 01:26
This is a bug
the related data in table upload_file_morph is not delete 

https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-upload/services/Upload.js#L137

**Comment by jeremy-scroggs** [comment] 2020-03-07 21:59
I would also agree that this is a bug. What would be the reasoning for not removing references to data that was intentionally removed?

**Comment by laportem** [comment] 2020-03-12 22:23
This also has an impact on the related record to which the file was attached.
1.	Let say I have a product record with 2 files (file_id= 1 and file_id = 2)
2.	I then send a DELETE /upload/files/1
The file (id =1) is deleted in the “upload_file” table but the relationship with product remains in ‘upload_file_morph’
3.	Now if I change the product data  (say product Quantity) and send a GraphQL mutation
If get this hasException

> I/flutter ( 1737): GraphQL Errors:
> I/flutter ( 1737): Cannot return null for non-nullable field UploadFile.id.: Undefined location

4.	The product do get updated in Strapi. I would guess the error is related to the return query but the funny thing is UploadFile is not even part of my return document query

**Comment by laportem** [comment] 2020-03-25 19:31
For anyone struggling with this is issue, until there is fix, a workaround is to add a database trigger on the ‘upload_file’ table to delete the orphan relationship in ‘upload_file_morph’.

It seems to work both with API file delete and Strapi Admin UI file delete

I use postgressql and the code is as follows:

```
CREATE OR REPLACE FUNCTION delink_file_fnc()
RETURNS trigger AS $delink_file_fnc$
DECLARE
BEGIN
IF EXISTS (SELECT 1 FROM upload_file_morph WHERE upload_file_id=OLD.id) THEN
  DELETE FROM upload_file_morph WHERE upload_file_id=OLD.id;
END IF;
RETURN OLD;
END;
$delink_file_fnc$ LANGUAGE plpgsql;

CREATE TRIGGER delink_file_trigger
BEFORE DELETE ON upload_file
    FOR EACH ROW EXECUTE PROCEDURE delink_file_fnc();
```

**Comment by Lith** [comment] 2020-04-17 22:24
Hello, 
Could we have an ETA about this bug fix ?
Thanks :)

**Comment by alexandrebodin** [comment] 2020-04-20 07:23
Hi, this has been fixed in the latest beta.20 release.  I'm closing this issue.

**Closed by alexandrebodin** 2020-04-20 07:23 UTC
Labels: priority: high, source: plugin:upload, status: confirmed, type: bug
