### ISSUE TITLE
Storing Cloudinary images id for API manipulation

### ISSUE THREAD

**Issue by tpiros** [strapi/strapi#3556] opened 2019-07-02 15:28 UTC
**Describe the bug** 

The strapi-plugin-cloudinary saves complete URLs to the database for images, only the  'Public_ID' portion of the URL should be saved. This allows for Cloudinary to apply transformations and execute other manipulations to the image.

**Steps to reproduce the behavior**

Install and configure the `strapi-plugin-cloudinary`
Create a new Content-Type with a `Media field` for images.
Save an image to the Content Type
Check DB and see complete URL.

**Expected behavior** 
 

Rather than the `photo.url` being a hardcoded value, the databases stores the `public_id`. 

The "issue" with this approach is that photo.url is now a hardcoded value, which means that there's no easy way of applying transformations/optimizations to the image itself.

Cloudinary allows you to, for example, generate a 250x250 image, by appending the URL (adding w_250,h_250). At the moment, the only thing that I could do is to read this data from the database, split('/') the Cloudinary URL add the transformations options to it, and then do a join('/').

I'd love to see a feature where the database stores the `public_id` of a Cloudinary image which is `yvyt9omqoqe6aj3wkeix.jpg`in the code snippet below and then use the Cloudinary SDK to generate transformation URLs, such as: `cloudinary.url(public_id, { width: 250, height: 250, effect: 'cartoonify' });

**Code snippets** 

The below returned object shows the photo.url being a complete URL.

```
{
  "city": "London",
  "country": "United Kingdom",
  "description": "Noisy, vibrant and truly multicultural, London is a megalopolis of people, ideas and frenetic energy. The capital and largest city of both England and of the United Kingdom, it is also the largest city in Western Europe and the European Union. Most residents of Greater London are very proud of their capital, the multiculturalism of the city, and their membership of the European Union, despite 52% of the UK population as a whole who voted in a recent referendum choosing to leave the EU. It is unclear what the outcome of the referendum will be on London.\n\nSituated on the River Thames in South-East England, Greater London has an official population of a little over 8 million. However, London's urban area stretched to 9,787,426 in 2011, while the figure of 14 million for the city's wider metropolitan area more accurately reflects its size and importance. Considered one of the world's leading \"global cities\", London remains an international capital of culture, music, education, fashion, politics, finance and trade.",
  "_id": "5c877ba28dde70b9973e6223",
  "createdAt": "2019-03-12T09:28:02.260Z",
  "updatedAt": "2019-03-12T14:56:17.796Z",
  "__v": 0,
  "id": "5c877ba28dde70b9973e6223",
  "photo": {
    "_id": "5c87c89d503362c3a9834f11",
    "name": "jaanus-jagomagi-393163-unsplash.jpg",
    "sha256": "fHZuIgFCYxjMR_ygpWcjGQqApL1muzJZWliilFMTiUA",
    "hash": "e15343b49dca41719b73fefff34ada7c",
    "ext": ".jpg",
    "mime": "image/jpeg",
    "size": "3992.02",
    "public_id": "yvyt9omqoqe6aj3wkeix",
    "url": "https://res.cloudinary.com/tamas-demo/image/upload/v1552402598/yvyt9omqoqe6aj3wkeix.jpg",
    "provider": "cloudinary",
    "related": [
    "5c877ba28dde70b9973e6223"
    ],
    "createdAt": "2019-03-12T14:56:29.543Z",
    "updatedAt": "2019-03-12T14:56:29.573Z",
    "__v": 0,
    "id": "5c87c89d503362c3a9834f11"
  }
}

```

**System**

Node.js version:10.x. (same behaviour on v12.x)
npm version: Latest
Strapi version: 3.0.0-beta.7
Database: MongoDB (v3)
Operating system: Mac

**Comment by derrickmehaffy** [comment] 2019-07-08 04:56
Technically is not a bug, but a feature request. However this format provides the needed data.

I do believe this would apply to this (given it is for cloudinary specific features): https://portal.productboard.com/strapi/1-public-roadmap/c/28-media-library-with-edit-crop-resize-capabilities

**Comment by tpiros** [comment] 2019-07-08 08:17
@derrickmehaffy you're right, it does apply however I'd also mention that if the public URL is stored and then the Cloudinary SDK is used for displaying a media asset you can do crop / format / optimise / transform videos as well as images. (In the public roadmap you only mention image support: "We would like to also introduce a bit of image processing to be able to edit, crop and resize images.")

**Comment by derrickmehaffy** [comment] 2019-07-08 08:18
Agreed more needs to be looked at, tis the reason I am leaving this one open.

Although I will ping @Aurelsicoko and let him read through in case he wants to add/modify that FR entry.

**Comment by tpiros** [comment] 2019-07-08 08:20
thanks @derrickmehaffy - also FYI, I did talk a lot about this issue with @davidkartuzinski :)

**Comment by derrickmehaffy** [comment] 2019-07-08 08:21
Good to know yeah. Hopefully more support will happen in the future. There is just so much to do and not enough time/people :wink:

**Comment by davidkartuzinski** [comment] 2019-07-08 09:51
@derrickmehaffy FYI - Right now images **_are not_** being manipulated by Cloudinary, just another S3 bucket... and we can change one thing and make it possible to manipulate... :)  This is definitely a bug...

**Comment by derrickmehaffy** [comment] 2019-07-08 10:03
@davidkartuzinski I know that currently aren't, but I don't think that it was ever intended when the plugin was built hence why I don't really see this as a bug but instead it is a feature request.

Similar to the AWS-S3 and folders, it was never intended (as local upload doesn't even have folder support) but was added later as a feature. This one in my mind is similar in that the issue is a missing feature and not something that was added but doesn't work :wink:

**Comment by tpiros** [comment] 2019-07-08 11:01
I understand both of your points @davidkartuzinski and @derrickmehaffy - suffice to say that it's great to have this feature in place currently but it's not at its fullest potential (using Cloudinary just as an image storing mechanism is 1% of what Cloudinary can actually do). So let's keep this open as an "issue to be discussed" :)

**Comment by Aurelsicoko** [comment] 2019-07-11 08:52
We could store both values in the database, right? The `public_id` to allow Cloudinary manipulation, then a full URL. The full URL is useful because you can directly use it in your frontend without doing nothing.

However, I would check if we can apply the same process for other providers? If we need it for Cloudinary, it could also be the case for another one like Rackspace...

**Comment by davidkartuzinski** [comment] 2019-07-11 09:27
> The full URL is useful because you can directly use it in your frontend without doing nothing.

I think you're approach could work. But I see issues and extra unnecessary work in storing absolute URLs.

At least with Cloudinary (and gatsby-image-remark which natively wants a relative URL (apparently)) - any manipulations are not done on an image from a absolute path and extra work to make it work.  (Here is an explanation https://spectrum.chat/gatsby-js/general/absolute-image-paths-in-json~66df91e6-a415-4e74-9c1f-37a2a83ea72f)

I don't know why anyone would want to use a full URL for the purpose of making it easier to display on the front-end with out extra work.  Mostly, people do want to serve different assets (at least) based on mobile/desktop/tablet etc version. img srcset, for example, is almost always used with relative URLs. 

Having said that, anyone counting on SEO for images (like a photographer), almost always should use an absolute URL as the Google spider makes fewer mistakes and properly "counts" these images.  So, having the option to store and use either would be okay in the long-term.

WordPress had to deal with this and had issues with storing absolute URLs as many developers cut/paste their installs as a based for new projects which automatically breaks all the images if they are absolute. I mention this, because if we do end up storing absolute URLs, then we have to have some logic about this. 

Agencies and Developers doing many sites will appreciate relative URLs most and makes more sense to me as the default method of storing the images.

**Comment by tpiros** [comment] 2019-07-11 11:21
@Aurelsicoko - yes, you could store the `public_id` and the full URL as well. In this way there'll be two options:

1) I upload the image and I don't want to optimise/transform it so I just use the full URL - this will always return a full, valid, Cloudinary URL: `https://res.cloudinary.com/....`

2) I want to transform/optimise my image: I will need to import the Cloudinary SDK, and then use `cloudinary.url(public_id)` or even `cloudinary.image(public_id)` and pass in the appropriate options to achieve the task at hand. (FYI `.url()` generates the full URL, `.image()` generates a full `<img>` tag with the `src` attribute set to the the correct URL)

**Comment by Aurelsicoko** [comment] 2019-07-12 11:56
@davidkartuzinski We are talking about the providers for the `strapi-plugin-upload` which is not the Media Library we will develop. It doesn't have the same goal. The purpose of this plugin is to store files. Nothing else. Currently, the community is using it store images and extend its usage to something which will be handled by the Media Library plugin.

I agree with you but what you talk about isn't in the scope of this plugin. It will be into the scope of the Media Library plugin 👍

I perfectly know what could be the pain point to store the full URL instead of a relative path. It was one of the mistakes made by WordPress, and we won't do it, be sure of that.

**Comment by davidkartuzinski** [comment] 2019-07-12 16:45
@Aurelsicoko - Sorry to confuse the two plugins.  Yes yes.  But that means, for now we can accomplish this using something like a lodash method to get the part of the URL needed for the Cloudinary plugin. 

Anyway, I can sleep now that we all agree not to make some mistakes regarding the full URL in the future, seriously.

**Comment by lauriejim** [comment] 2020-01-02 17:43
Since this `provider_metadata` exist every provider cans store the ID and other info of the image.

https://github.com/strapi/strapi/commit/0ab5a8a40746b0f8179860600b96b3aac12dda89

**Closed by lauriejim** 2020-01-02 17:43 UTC
Labels: good first issue, priority: low, type: enhancement 💅
