### ISSUE TITLE
Standard Starpi email plugin not working when recipient's email address is hyphenated

### ISSUE THREAD

**Issue by adam-bubela** [strapi/strapi#3603] opened 2019-07-11 12:37 UTC
The following snippet is taken from official Strapi documentation 
https://strapi.io/documentation/3.0.0-beta.x/guides/email.html#usage

```
await strapi.plugins['email'].services.email.send({
      to: 'somebody@estee-lauder.co.uk',
      from: 'no-reply@estee-lauder.co.uk',
      replyTo: 'no-reply@estee-lauder.co.uk',
      subject: 'test',
      text: 'test,
      html: 'test'
});
```
I injected it into an API controller which is usually located in 
{PROJECT_DIRECTORY}/api/{ENDPOINT}/controllers/{CONTROLLER}

It works fine every time I call this API method and email is sent out as expected, however, 
when the `to` parameter contains hyphen the below error is returned 

> Error: Cannot wrap non-Error object 
>   at Object.exports.assert (/node_modules/hoek/lib/index.js:740:11) 
>   at Object.exports.wrap (/node_modules/boom/lib/index.js:95:10) 
>   at strapi.app.use (/node_modules/strapi/lib/middlewares/boom/index.js:47:22)       
>   at process._tickCallback (internal/process/next_tick.js:68:7)

**System**
Ubuntu 18.04.2 LTS
Node v10.16.0
Strapi 3.0.0-beta.9

**Comment by derrickmehaffy** [comment] 2019-07-11 15:08
@adam-bubela please ensure you use the bug report template and fill it out completely for instance with this link: https://github.com/strapi/strapi/issues/new?template=BUG_REPORT.md

You can however just edit your original post using the following template:
```
<!--
Hello 👋 Thank you for submitting an issue.

Before you start, please make sure your issue is understandable and reproducible.
To make your issue readable make sure you use valid Markdown syntax.

https://guides.github.com/features/mastering-markdown/
-->

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce the behavior**
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: <!-- Please ensure you are using the Node LTS version (v10) -->
- NPM version:
- Strapi version: <!-- Please make sure you are on the latest version -->
- Database:
- Operating system:

**Additional context**
Add any other context about the problem here.
```

For now I will mark this issue as closed as it doesn't follow the template, after you have updated the issue to use it reply back and it can be reopened.

Thank you

**Comment by adam-bubela** [comment] 2019-07-12 09:50
@derrickmehaffy I enhanced post can you please review it? Thanks.

**Comment by lauriejim** [comment] 2019-07-12 13:14
Hello! Can you give me the address that fail please.

**Comment by adam-bubela** [comment] 2019-07-13 13:47
Hi @lauriejim, it was mnash@estee-lauder.co.uk

**Comment by lauriejim** [comment] 2019-07-15 10:11
And you use the default solution that strapi offer you? You did not configure and other provider to send email?
So it use `sendmail` node module to send email.
Normally it have to work...

I tested it on my side and it look working well.
I haven't errors

**Comment by LorhanSohaky** [comment] 2019-08-04 00:28
@lauriejim, how did you configure sendmail with SMTP?

**Comment by lauriejim** [comment] 2019-08-08 13:21
I close this issue since we don't have new about the original issue.

You have nothing to do to make it works. Just make sure your server is able to send mails.

**Closed by lauriejim** 2019-08-08 13:21 UTC
Labels: status: can't reproduce, type: bug 🐛

**Comment by vlad320** [comment] 2019-09-30 17:21
@lauriejim Helloy, I also ran into this problem, although literally a week ago everything was ok. I catch this error both on the local PC and on the battle server. I moved from the main one from beta15 to beta16.6.

![image](https://user-images.githubusercontent.com/16899697/65900829-d6178580-e3f1-11e9-97a5-6c072698248b.png)

Test emails from the server console successfully reach.
Email format is not important, I catch an error always now.

**Comment by wemod123** [comment] 2019-10-10 11:31
I had check the root cause to some extend since I run into same error, it's because the proxy things, related to the configuration of 'host' field, see [here](https://github.com/strapi/strapi/blob/40d3d78b0db90d40ed3d8b5d20d50bc9a429138c/packages/strapi-provider-email-mailgun/lib/index.js#L42)

if you just disable this field, you will fix it

**Comment by dextherry** [comment] 2020-01-21 22:26
Hi, am using sendgrid, and it has this same bug 
![image](https://user-images.githubusercontent.com/1903077/72848477-adeab580-3c72-11ea-9d21-b8823ee0a32f.png)
this is the code (I just changed the emails):

`
module.exports = {
    send: async ctx => {
        
        await strapi.plugins['email'].services.email.send({
            to: 'myemail@abc.com',
            from: 'myemail@abc.com',
            replyTo: 'no-reply@strapi.io',
            subject: 'Use strapi email provider successfully',
            text: 'Hello world!',
            html: 'Hello world!',
        });

        ctx.send('Hello World!2');
    },
};
`

how can I fix it?
I am using strapi 3.0.0-beta.18.4

**Comment by lauriejim** [comment] 2020-01-23 22:55
Are your credentials correct?

**Comment by dextherry** [comment] 2020-01-23 23:04
I fixed it, it was because i was using credentials of another email provider instead of sendgrid (damn ads in google searchs, it confused me and I registered in another email provider)
