### ISSUE TITLE
[v4]Admin panel override files are not be copied

### ISSUE THREAD

**Issue by george-rb2** [strapi/strapi#11523] opened 2021-11-09 15:50 UTC
### Describe the bug

It seems like the files under the `admin` folder are not be copied and complied into the admin panel.
It was worked in the v3 version.

### Steps to reproduce the behavior

1. Go to 'admin' folder
2. Create file 'components/LeftMenu/index.js'
3. Execute 'yarn build'
4. Execute 'yarn develop'
5. The admin panel is not be updated.

### Expected behavior

Admin panel ban be customized by the custom files.

### System

- Node.js version:  v14.17.5
- NPM version: 7.22.0
- Strapi version: V4-beta.11
- Database: MySql
- Operating system: MacOs

**Comment by derrickmehaffy** [comment] 2021-11-09 22:46
@pwizla correct me if I'm wrong but we don't have documentation yet for customizing the Admin in the v4 since it won't use the same system as the v3

**Comment by pwizla** [comment] 2021-11-10 08:26
Hello! We do have [admin customization](https://docs-next.strapi.io/developer-docs/latest/development/admin-customization.html) docs 🙂 

You might want to pay special attention to the [webpack configuration section](https://docs-next.strapi.io/developer-docs/latest/development/admin-customization.html#webpack-configuration) and especially to the following note:
![Screenshot 2021-11-10 at 09 24 27](https://user-images.githubusercontent.com/4233866/141076936-5767e9a5-8ccd-4576-ac09-1494daba95b8.png)

Hope this helps! 🙂

**Comment by soupette** [comment] 2021-11-10 09:12
@george-rb2 with the v4 the admin customisation workflow has been changed.

Currently you can only customise the parts that are opened to customisations:
- Theme,
- translations
- Injection zone API

If you need more customisation the workflow with the v4 is to fork the package you want to customise and install your fork instead.

I am closing this issue as it is the intended behaviour of the V4.

**Closed by soupette** 2021-11-10 09:12 UTC
Labels: type: help wanted, version: v4-Alpha/Beta

**Comment by george-rb2** [comment] 2021-11-11 13:22
okay, good to know. thanks.

**Comment by derrickmehaffy** [comment] 2021-11-11 21:38
(alternatively you can use patch-package instead of forking)
