### ISSUE TITLE
Error creating entity with component via rest api 

### ISSUE THREAD

**Issue by Keith-Hon** [strapi/strapi#13329] opened 2022-05-16 10:09 UTC
Describe the bug

1. I am using the rest api (/api/product-categories) to create entities, which has a component field called "name". "name" has 3 fields of text (var 255 length). The api sometimes return 500 error from time to time

{
    "data": null,
    "error": {
        "status": 500,
        "name": "InternalServerError",
        "message": "Internal Server Error"
    }
}

and when i check the strapi logs, it shows 

![image](https://user-images.githubusercontent.com/23226987/168570033-d54fc65c-7aa9-4576-acb2-a64a21ed5784.png)

![image](https://user-images.githubusercontent.com/23226987/168570112-12adfb46-1b9d-4cff-8585-7ff289503687.png)

Steps to reproduce the behavior
1. Create a component and assign that to an entity. Use rest api to repeatedly create entites with such component

System
Node.js version: v12.22.8
NPM version: 6.14.15
Strapi version: v4.1.10
Database: postgres
Operating system: ubuntu 20.04.2 LTS

**Comment by derrickmehaffy** [comment] 2022-05-26 16:41
Can't reproduce on v4.1.12 need more information.

Closing until we get some additional reproduction steps

**Closed by derrickmehaffy** 2022-05-26 16:41 UTC
Labels: status: can not reproduce

**Comment by Keith-Hon** [comment] 2022-05-27 02:20
Hi @derrickmehaffy . How did you try to reproduce? How many entities did you try to create, what's fields does the component have?

**Comment by derrickmehaffy** [comment] 2022-06-01 22:07
> Hi @derrickmehaffy . How did you try to reproduce? How many entities did you try to create, what's fields does the component have?

Used a repeat compo with 1 text field: 
![image](https://user-images.githubusercontent.com/8593673/171509767-95f0937f-f564-4afd-bfa1-6c0476b14bc2.png)

That error you get though has nothing to do with volume or total fields, it's saying there is a problem with reading an ID which sounds like an update request that has an invalid component ID.

**Comment by derrickmehaffy** [comment] 2022-06-01 22:07
EG I don't think this is a bug but a problem with the logic on how you are creating/updating data. Hence why I asked for more reproduction steps.
