### ISSUE TITLE
Sorting for SelectMany doesn't save

### ISSUE THREAD

**Issue by rafalolszewski94** [strapi/strapi#7636] opened 2020-08-28 11:22 UTC
**Describe the bug**
Sorting for SelectMany doesn't save when order of items inside of it is changed. Visually, it "changes" the order, but after coming back to this item we're creating or editing, it comes back to it's previous state.

**Steps to reproduce the behavior**

1. Create custom component with SelectMany widget
2. Have at least 2 items to selcet in this widget
3. Re-order them few times

**Expected behavior**
Order should be saved somewhere

**System**

- Node.js version: v12.16.2
- NPM version: 6.14.4
- Strapi version: 3.1.1
- Database: Postgresql (using bookshelf)
- Operating system: Ubuntu 18.04.4 LTS (Bionic)

**Screenshots**
![image](https://user-images.githubusercontent.com/37925892/91555601-9de63300-e931-11ea-9314-6375724d313e.png)
This is the widget I'm talking about

**Comment by derrickmehaffy** [comment] 2020-09-03 15:51
Closing as duplicate of: https://github.com/strapi/strapi/issues/7039

Currently at @rafalolszewski94 we don't save the order of relations, only components. You can see the relevant FAQ here: https://strapi.io/documentation/v3.x/getting-started/troubleshooting.html#relations-aren-t-maintaining-their-sort-order

Likewise another user did offer a workaround in the duplicate issue I linked but it's not supported by us.

**Closed by derrickmehaffy** 2020-09-03 15:51 UTC
Labels: status: duplicate
