### ISSUE TITLE
Error - Unescaped at-sign in authority section

### ISSUE THREAD

**Issue by ronaldaug** [strapi/strapi#2466] opened 2018-12-11 14:54 UTC
**Informations**
- **Node.js version**:  v10.14.1 
- **NPM version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.16 
- **Database**: MongoDB ( MLab )
- **Operating system**:  OSX/El Captain/10.11.6 

**What is the current behavior?**
When running `strapi start` , the server don't start.
It shows this error as below.
```
[2018-12-11T14:36:24.703Z] debug ⛔️ Server wasn't able to start properly.
[2018-12-11T14:36:24.704Z] error Unescaped at-sign in authority section
```

**Steps to reproduce the problem**
This happen when giving MongoDB(mlab) passwords with special characters including `!@#$%^`

**What is the expected behavior?**
On running `Strapi start`, Server should start properly.

**Suggested solutions**
https://stackoverflow.com/questions/7486623/mongodb-password-with-in-it#answer-48342945

**Comment by derrickmehaffy** [comment] 2018-12-11 16:53
Yeah it looks like there was an issue in the mongoose repo based on this issue: https://github.com/Automattic/mongoose/issues/6881

However it seems to be fixed, @ronaldaug if you wanted to submit a PR for a fix on encoding the password you could give it a try :smile: I believe the spot you need to modify is here: 

https://github.com/strapi/strapi/blob/83771ae15488e6aed1dc60c4ee85b58ef5793762/packages/strapi-hook-mongoose/lib/index.js#L85

I've never really used Mongo or mongoose myself.

**Comment by derrickmehaffy** [comment] 2018-12-11 16:55
Actually I just realized that this is a duplicate of https://github.com/strapi/strapi/issues/2441

So I will close this issue and we can continue discussion in the linked issue

**Closed by derrickmehaffy** 2018-12-11 16:55 UTC
