### ISSUE TITLE
Media Library Wrongly Rotating Images on Resize

### ISSUE THREAD

**Issue by nevil2** [strapi/strapi#18645] opened 2023-11-02 12:31 UTC
### Required System information

- Node.js version: 18.12.1
- NPM version: 9.8.1
- Strapi version: 4.14.5
- Database: Postgres
- Operating system: linux-x64 / Ubuntu 22.04
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Strapi Media is rotating the attached jpg image during resize.

![Early conditions on the Ben, Dec '23](https://github.com/strapi/strapi/assets/56249975/ff488e4c-1c89-4cfb-b377-1f1ff7d2062f)

This happens regardless of whether Auto Rotation is set to true or false.

It would appear that it is ignoring the EXIF information.

The resized image is attached.

![4a98118eb5fc3befce00194a43b49df9](https://github.com/strapi/strapi/assets/56249975/4b395bf6-fba4-42fc-bd93-908829f609e7)

### Steps to reproduce the behavior

Load the attached photo into Strapi Media Library

Same behaviour on both local development and production (Docker container running on Digital Ocean).

### Expected behavior

The resized images have same orientation as original.

### Screenshots

![Screenshot 2023-11-02 114037](https://github.com/strapi/strapi/assets/56249975/0cb6a169-11f2-47bc-ac4c-08b66ed88ff1)

### Code snippets

N/A

### Additional context

Other issues with Media library are:
 - The crop function does not work.
 - Assets in main folder cannot be moved to sub-folders

**Comment by Boegie19** [comment] 2023-11-02 12:36
Duplicate of https://github.com/strapi/strapi/issues/18338

**Closed by Boegie19** 2023-11-02 12:36 UTC
