### ISSUE TITLE
Strapi is not allowing me to see Content Manager

### ISSUE THREAD

**Issue by hiteshujani2002** [strapi/strapi#14479] opened 2022-09-28 01:12 UTC
### Required System information

- Node.js version: 14.17.3
- NPM version:8.19.2
- Strapi version:4.1.12
- Database:
- Operating system:Windows 10

### Describe the bug

I am working with Next + Strapi project when am I ran strapi start in my terminal I get to go on the administration but when I click on the Content Manager it tells me that "You are not allowed to see this document".

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by derrickmehaffy** [comment] 2022-09-28 21:28
Need more reproduction steps or information as I am unable to reproduce. Closing this until more information is provided.

**Closed by derrickmehaffy** 2022-09-28 21:28 UTC
Labels: status: can not reproduce
