### ISSUE TITLE
Suspended admin accounts after migration to 3.1.0 from 3.0.6

### ISSUE THREAD

**Issue by tofijak** [strapi/strapi#7158] opened 2020-07-24 12:03 UTC
**Describe the bug**
After migrating to 3.1.0 from 3.0.6, following the migration guide, all admin accounts were suspended. 

The issue is the new field 'active' in the strapi-administrator table. 
The 'active' value for the account created in Strapi 3.0.6 was set to null by default after migration. 
Setting the field 'active' to true directly in .tmp/data.db fixed the problem. 

**Steps to reproduce the behavior**

1. Local install of Strapi 3.0.6
2. Create admin account
3. Migrate to 3.1.0 following the guide
4. Try to login with same admin account 
5. Redirects to 'Oops the account is suspended....'

**Comment by alexandrebodin** [comment] 2020-07-24 12:18
Hi there is a startup script that set the user to active on startup the first time your migrate. This should not be possible in theory. Can you please add your system informations so we can reproduce ?

**Comment by tofijak** [comment] 2020-07-24 12:26
Sure

- Node.js version: 12.13.1
- NPM version: 6.14.5
- Strapi version: 3.0.6 to 3.1.0
- Database: SQLite (default)
- Operating system: macOS Mojave 10.14.6

**Comment by alexandrebodin** [comment] 2020-07-24 12:29
@petersg83 Can you check if the script might have issues ?

**Comment by petersg83** [comment] 2020-07-24 16:23
Hi, thanks for the issue!
Do you remember what was written for your users in the column `blocked` before the migration ?
The script: https://github.com/strapi/strapi/blob/master/packages/strapi-admin/services/user.js#L277 handles when it is written `false` or `null`

**Comment by jeremyrajan** [comment] 2020-07-26 07:54
Facing the same, 3.0.4 -> 3.1.1. All my admin accounts are suspended.

![image](https://user-images.githubusercontent.com/2890683/88474360-3286fb00-cf58-11ea-825b-4e9d78ac13b6.png)

**Comment by tofijak** [comment] 2020-07-26 08:59
> Hi, thanks for the issue!
> Do you remember what was written for your users in the column `blocked` before the migration ?
> The script: https://github.com/strapi/strapi/blob/master/packages/strapi-admin/services/user.js#L277 handles when it is written `false` or `null`

All users had the value false in the blocked column before migration

**Comment by petersg83** [comment] 2020-07-27 07:52
@jeremyrajan What database do you use?

**Comment by jeremyrajan** [comment] 2020-07-28 10:01
@petersg83 I am using sqlite. Yea I restarted it after the upgrade.

**Comment by petersg83** [comment] 2020-07-28 16:14
Thanks for the information!
I couldn't reproduce it. Can you both tell me your sqlite version please?
And of course, if you have detailed steps to reproduce it, it would be the best!

**Comment by catalinaII** [comment] 2020-08-17 14:00
I've the same issue and I'm using this version for sqlite "sqlite3": "^4.2.0" in package.json

**Comment by gutaku** [comment] 2020-08-18 07:30
I've the same issue and I'm using this version for sqlite "sqlite3": "^5.0.0" in package.json

**Comment by ly525** [comment] 2020-08-19 05:47
I've the same issue and I'm using this version for sqlite "sqlite3": "^4.1.1" in package.json

**Comment by Muhammad-1990** [comment] 2020-08-25 08:38
Hi there,
I googled "suspended admin accounts strapi" and i got here and then i quickly realised that any solution in here my not resolve my specific issue.

That being said, I am also facing the "suspended" message when logging into my strapi heroku review app.
I am using the bootstrap.js file to import a custom module.export which basically adds the admin user using the user service.

I resolved my issue by using the await keyword inside bootstrap.js when calling my custom userSeed.js module.
heres the code:

bootstrap.js - 

`'use strict';
const userSeed = require('./seeds');

module.exports = async () => {
    if (process.env.NODE_ENV == "development") {
        await userSeed.createUser();
    }
};
`

userSeed.js -

`module.exports.createUser = async () => {
    // Required fields:
    const params = {
        username: process.env.ADMIN_USER || 'admin',
        password: process.env.ADMIN_PASS || 'admin',
        email: process.env.ADMIN_EMAIL || 'test@testing.com',
        blocked: false
    };

    const admins = await strapi.query('user', 'admin').find({ _limit: 1 });
    if (admins.length) {
        console.error('You can\'t register a new admin');
    } else {

        // Hash password before storing in the database
        params.password = await strapi.admin.services.auth.hashPassword(params.password);

        try {
            // Create admin account
            const admin = await strapi.query('user', 'admin').create({
                username: params.username,
                password: params.password,
                email: params.email,
                blocked: params.blocked
            });

            console.info('(Admin) Account created:', admin);

        } catch (error) {
            console.error(error);
        }
    }
};`

Im fairly new to all this and i may not know what im talking about half the time but perhaps the above might trigger a brilliant mind. Maybe some migration code is terminating adding the user before the transaction commits...

good luck.
thanks,
(disclaimer: the userSeed.js is not my code - https://github.com/strapi/strapi/issues/3365)
feel free to discard this post if it breaks to many rules.

**Comment by zoltot** [comment] 2020-09-05 19:01
I did a little bit of investigating and their are two issues one is simple the other I have no idea how to go about it first the simple 
`    const params = {
      username: process.env.ADMIN_USER || 'admin',
      password: process.env.ADMIN_PASS || 'admin',
      email: process.env.ADMIN_EMAIL || 'youremail@email.com',
      blocked: false,
      isActive: true,  // this flag being set to true is required (problem 1 easy)
      roles : [
                 // we need to get the admin super key into here (probblem 2 hard)
   ], 
    };`
Setting the Active Key to true allows you to log into the user but you don't have any permssion to do anything.  You need to be able to grab the  strapi-role item with "code" : "strapi-super-admin" and add its id into the roles array.  My issue is that it doesn't seem that strapi has a way of programatically getting at these roles.  You can always manaually get from the database you create but that feels very hacky

**Comment by zoltot** [comment] 2020-09-06 13:45
I actuall found a set up that works for this

```
'use strict';

/**
 * An asynchronous bootstrap function that runs before
 * your application gets started.
 *
 * This gives you an opportunity to set up your data model,
 * run jobs, or perform some special logic.
 *
 * See more details here: https://strapi.io/documentation/v3.x/concepts/configurations.html#bootstrap
 */
const mongoose = require('mongoose');
module.exports = async () => {

    // Required fields:
    const params = {
      username: process.env.ADMIN_USER || 'test',
      password: process.env.ADMIN_PASS || 'test',
      firstname : process.env.ADMIN_USER || "Test", 
      lastname : process.env.ADMIN_USER ||"Test", 
      email: process.env.ADMIN_EMAIL || 'example@website.com',
      blocked: false,
      isActive: true,
    };
  
    // Check if exist any admin account - NOTE: you can change this query to find by specific email
    const admins = await strapi.query('user', 'admin').find({ _limit: 1 });
    if (admins.length) {
      console.error('You can\'t register a new admin');
    } else {
    try {
     // in the admin under services you can find the super admin role
      const superAdminRole = await strapi.admin.services.role.getSuperAdmin();
      // Hash password before storing in the database
      params.roles = [superAdminRole._id]
      params.password = await strapi.admin.services.auth.hashPassword(params.password);
  

        // Create admin account
        const admin = await strapi.query('user', 'admin').create({
          ...params
        });
  
        console.info('(Admin) Account created:', admin);
  
      } catch (error) {
        console.error(error);
      }
    }
  };
```
This setup will create your first user with all the credentials

**Comment by derrickmehaffy** [comment] 2020-10-15 14:17
As we have no updated information from the user, marking as closed.

**Closed by derrickmehaffy** 2020-10-15 14:17 UTC
Labels: type: help wanted

**Comment by JackMcKew** [comment] 2020-12-14 00:22
For anyone stumbling across this, during a migration my Super Admin was set to inactive with no roles

I added this piece of code to do an update to the existing user to enable them again in the `if(admins.length` part of the code above from @zoltot 

```
if (!admins[0].isActive || !admins[0].blocked || !admins[0].roles.length) {
        console.info(`Updating existing admin account ${admins[0].email} with roles`);
        await strapi.query('user', 'admin').update(
          { id: admins[0].id },
          {
            ...params,
          },
        );
      }
```

In it's entirety the change was:

```

  const setUpAdmin = async () => {
  // Required fields:
    const params = {
      username: process.env.STRAPI_ADMIN_USERNAME || 'test',
      password: process.env.STRAPI_ADMIN_PASSWORD || 'test',
      firstname: process.env.STRAPI_ADMIN_USERNAME || 'Test',
      lastname: process.env.STRAPI_ADMIN_USERNAME || 'Test',
      email: process.env.STRAPI_ADMIN_EMAIL || 'example@website.com',
      blocked: false,
      isActive: true,
    };

    // Check if exist any admin account - NOTE: you can change this query to find by specific email
    const admins = await strapi.query('user', 'admin').find({ _limit: 1 });
    // in the admin under services you can find the super admin role
    const superAdminRole = await strapi.admin.services.role.getSuperAdmin();
    // Hash password before storing in the database
    params.roles = [superAdminRole._id];
    params.password = await strapi.admin.services.auth.hashPassword(params.password);

    if (admins.length) {
      console.error('You can\'t register a new admin');
      console.info(`Current admin account ${admins[0].email}`);
      if (!admins[0].isActive || !admins[0].blocked || !admins[0].roles.length) {
        console.info(`Updating existing admin account ${admins[0].email} with roles`);
        await strapi.query('user', 'admin').update(
          { id: admins[0].id },
          {
            ...params,
          },
        );
      }
    } else {
      try {
        // Create admin account
        const admin = await strapi.query('user', 'admin').create({
          ...params,
        });

        console.info('(Admin) Account created:', admin);
      } catch (error) {
        console.error(error);
      }
    }
  };

  setUpAdmin();
```
