### ISSUE TITLE
Cloudinary other files than images

### ISSUE THREAD

**Issue by holyduke** [strapi/strapi#8502] opened 2020-10-28 08:09 UTC
## Bug report

When I try to upload files other than images to cloudinary, it doesn´t upload properly.

### Steps to reproduce the behavior

1. Go to strapi administration panel
2. Click on Media Library
3. Try to upload focx file
4. Go to cloudinary and see file you just uploaded - it has wrong file format 

### Expected behavior

File upload of .docx and .pdf files to cloudinary provider should be working

### Screenshots

![image](https://user-images.githubusercontent.com/48070343/97408434-5ca3dc80-18fc-11eb-85dc-1bdbfafa2697.png)

### Code snippets

I am using 
`"strapi-provider-upload-cloudinary": "3.2.4"`

### System

- Node.js version: ">=10.0.0"
- NPM version: ">=6.0.0"
- Strapi version: 3.2.4
- Database: MongoDB
- Operating system: Windows10

**Comment by derrickmehaffy** [comment] 2020-10-28 21:24
I'm going to mark this as a duplicate of https://github.com/strapi/strapi/issues/8462 as I believe they are related.

But thank you @holyduke

**Closed by derrickmehaffy** 2020-10-28 21:24 UTC
Labels: status: duplicate
