### ISSUE TITLE
created_by and updated_by is null

### ISSUE THREAD

**Issue by kevindelange** [strapi/strapi#7758] opened 2020-09-07 07:54 UTC
When posting data to the api with an authenticated user the created_by and updated_by are null.

**Steps to reproduce the behavior**

1. Login with an authenticated user (via postman for instance)
2. Use the token in the authenticated post request
3. Response of the request will say that the created_by and updated_by are null.

**Expected behavior**
Returning the same object of information as when you enter data to Strapi with the admin interface.

**System**

- Node.js version: 10.17.0
- NPM version: 6.11.3
- Strapi version: 3.1.4
- Database: postgres
- Operating system: macos

**Comment by alexandrebodin** [comment] 2020-09-07 07:56
Hi, this is a Duplicate of #7635 :)

**Closed by alexandrebodin** 2020-09-07 07:56 UTC

**Comment by kevindelange** [comment] 2020-09-07 07:58
I'm sorry, not sure how I overlooked this.

Thanks!
