### ISSUE TITLE
strapi update collection type with “update service”

### ISSUE THREAD

**Issue by MustafaWael** [strapi/strapi#9238] opened 2021-01-27 17:14 UTC
### Describe the bug

when i update the order by "payment_intent_id" the api return "not found" response, but actually the order updated, so when i check the order collection in strapi dashboard i found it "paid".

otherwise when i update by id every thing works as expected.

### Expected behavior
I wanna the API return the sanitized order not "not found" response when i update by "payment_intent_id"

### Screenshots
![routes json - Untitled (Workspace) - Visual Studio Code 1_27_2021 7_19_11 PM](https://user-images.githubusercontent.com/29284370/106028540-c175fb00-60d4-11eb-967b-3234ea05799d.png)

![Settings and 7 more pages - Personal - Microsoft​ Edge 1_27_2021 7_01_47 PM](https://user-images.githubusercontent.com/29284370/106026592-b15d1c00-60d2-11eb-8ce4-f64401768403.png)

![Postman 1_27_2021 7_02_12 PM](https://user-images.githubusercontent.com/29284370/106026532-97bbd480-60d2-11eb-9ba6-4ad1b09f6851.png)

![Postman 1_27_2021 6_59_10 PM](https://user-images.githubusercontent.com/29284370/106026470-87a3f500-60d2-11eb-8e7a-beaa4d0a5bb9.png)

![Strapi - Content Manager and 7 more pages - Personal - Microsoft​ Edge 1_27_2021 7_06_56 PM](https://user-images.githubusercontent.com/29284370/106026986-1dd81b00-60d3-11eb-9b37-9039b69d507f.png)

![Strapi - Content Manager and 7 more pages - Personal - Microsoft​ Edge 1_27_2021 7_07_13 PM](https://user-images.githubusercontent.com/29284370/106027011-24ff2900-60d3-11eb-87f9-b119a24054cd.png)

### Code snippets

```
confirm: async (ctx) => {
    const { payment_intent_id } = ctx.request.body;
    const session = await stripe.paymentIntents.retrieve(payment_intent_id);

    if (session.status === "succeeded") {
      const updatedOrder = await strapi.services.order.update(
        { payment_intent_id },
        { status: "paid" }
      );

      return sanitizeEntity(updatedOrder, { model: strapi.models.order });
    } else {
      ctx.throw(400, "The payment wasn't successful, please call support");
    }
  },
```

### System

- Node.js version: v14.15.4
- NPM version: 6.14.10
- Strapi version: 3.4.5
- Database: MongoDB
- Operating system: windows 10

**Comment by derrickmehaffy** [comment] 2022-01-05 22:07
Not a bug as it's customization, closing

**Closed by derrickmehaffy** 2022-01-05 22:07 UTC
Labels: status: pending reproduction
