### ISSUE TITLE
Relation one-to-one allows multiple inserts

### ISSUE THREAD

**Issue by oscardemadriz** [strapi/strapi#13155] opened 2022-04-19 11:29 UTC
### Required System information

- Node.js version: v14.19.0
- NPM version: 6.14.16
- Strapi version:  4.1.2
- Database: PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit (Docker)
- Operating system: Windows 10

### Describe the bug

There is a race condition on creating new elements with one-to-one relations, creating 100 entries into Strapi relates most of the entries, like one-to-many; Instead of limiting them to the last one.

### Steps to reproduce the behavior

1. Create a model with a one-to-one relation (in the example I used the user)
![image](https://user-images.githubusercontent.com/35626977/163984829-78821a2b-1cd3-4daa-8ac1-32554efa3b11.png)
2. Add the user context in the method (Check Snippets 1)
3. Use a quick method to trigger the race condition, for example, a script (Check Snippets 2)
4. Check how in DB and the Admin Panel it's shown
![image](https://user-images.githubusercontent.com/35626977/163985095-0b278084-6ab6-443b-979f-6daf42df061d.png)
![image](https://user-images.githubusercontent.com/35626977/163985203-d57a3821-327e-4b8c-b982-edb1c42bda41.png)

### Expected behavior

You can only create one element related, the last one prevails.

### Screenshots

Added to Steps to reproduce.

#### 1. Method

```javascript
module.exports = createCoreController("api::wish.wish", ({ strapi }) => ({
  async create(ctx) {
    let { data } = ctx.request.body;
    data = await super.sanitizeInput(data);
    data.user = ctx.state.user.id;

    const wish = await strapi.service("api::wish.wish").create({ data });

    return wish;
  },
}));
```
#### 2. Script 
The script triggers the race condition (in empty dir)
```
npm init -y
npm i axios
npm i chance
```
Add your JWT token into *TOKEN_HERE*

```js
var axios = require("axios");
const chance = require("chance").Chance();

for (let index = 0; index < 20; index++) {
  var data = JSON.stringify({
    data: {
      text: chance.sentence(),
      plant_type: 1,
      location: "28.0953162 -15.4426483",
    },
  });

  var config = {
    method: "post",
    url: "http://localhost:1337/api/wishes",
    headers: {
      Accept: "application/json, text/plain, */*",
      "Accept-Language": "es-ES,es;q=0.9",
      Authorization:
        "Bearer TOKEN_HERE",
      "Content-Type": "application/json",
    },
    data: data,
  };

  axios(config)
    .then(function (response) {
      console.log(JSON.stringify(response.data));
    })
    .catch(function (error) {
      console.log(error.response.status);
    });
}

```

### Additional context

If you create an entry after the script, it ***resets*** and relates to the last one.

**Comment by derrickmehaffy** [comment] 2022-04-21 17:11
confirmed on v4.1.8, but I have no idea the root cause. It feels like a race condition that might not be an easy solve

**Comment by Marc-Roig** [comment] 2023-02-22 11:29
confirmed, this is caused by a race condition. The same as was mentioned here https://github.com/strapi/strapi/issues/15558 So I am closing this in favor of that issue, where we already summarized some points about how we can handle race conditions in strapi.

For now, the best solution would be to sequentially await one by one the axios request you are making. This would ensure no race conditions occur.

**Closed by Marc-Roig** 2023-02-22 11:30 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:strapi, source: core:database
