### ISSUE TITLE
Unable to add more than one dynamic component 

### ISSUE THREAD

**Issue by Niteshcodes** [strapi/strapi#18816] opened 2023-11-16 11:43 UTC
**Project setup by --->**npx create-strapi-app@latest my-project

**mode--> recommended** 

{  
  npm: '10.2.3',
  node: '18.17.0',
}

- ---> when i click on add a component 

![image](https://github.com/strapi/strapi/assets/109732362/fc4acfc0-de20-4012-a327-67f44d8be93b)

- --->Display a White screen 

![image](https://github.com/strapi/strapi/assets/109732362/52fc6c4f-f563-4caf-8d1f-b78bb2855092)

- and show this error in console 

![image](https://github.com/strapi/strapi/assets/109732362/f601bd03-b8bf-4427-9f68-5f6ec3dd2ccb)

**Comment by Boegie19** [comment] 2023-11-16 14:40
duplicate of https://github.com/strapi/strapi/issues/18665

**Closed by Boegie19** 2023-11-16 14:40 UTC
Labels: status: duplicate
