### ISSUE TITLE
GrahpQL variables not working

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#3571] opened 2019-07-04 20:22 UTC
**Describe the bug**
Query gives wrong results

**Steps to reproduce the behavior**
1. Send to graphql the provided query.

**Expected behavior**
One item as the graphql query result

**Screenshots**

![Captura de pantalla de 2019-07-04 17-19-20](https://user-images.githubusercontent.com/517228/60686551-d1d5dd80-9e7f-11e9-938a-b48778f0374c.png)

**Code snippets**

```
query ReleaseDetail($slug: String!) {
  releases(where: {slug: $slug}) {
    slug
    name
    sortableVersion
    changelog
    product {
      slug
      name
      __typename
    }
    files {
      _id
      name
      size
      url
      __typename
    }
    createdAt
    updatedAt
    __typename
  }
}
```

with vars:
```
{ "slug": "nexion-smart-erp-16-2-2-14"}
```

**System**
- Node.js version: 10
- NPM version: 
- Strapi version: 3.0.0-beta.9
- Database: mongodb
- Operating system: linux

**Additional context**

This query was working just fine before, on alpha for example; as can be seen on the screenshot, it is returning an array of results, where `slug` is any value, and no the requested one. If i put the fixed value like this

```
query ReleaseDetail {
  releases(where: {slug: "nexion-smart-erp-16-2-2-14"}) {
    slug
    name
    sortableVersion
    changelog
    product {
      slug
      name
      __typename
    }
    files {
      _id
      name
      size
      url
      __typename
    }
    createdAt
    updatedAt
    __typename
  }
}
```

it works.

**Comment by alexandrebodin** [comment] 2019-07-04 21:26
Hi, it's a duplicate of #3537 I'm closing this ;)

**Closed by alexandrebodin** 2019-07-04 21:26 UTC
