### ISSUE TITLE
How to migrate database setups?

### ISSUE THREAD

**Issue by madonzy** [strapi/strapi#2334] opened 2018-11-19 10:39 UTC
Hello, guys, how do you migrate your database setups? I mean items of content-types and configurations?

**Comment by MartinMuzatko** [comment] 2018-11-19 10:50
Could be a duplicate of this: https://github.com/strapi/strapi/issues/2189
your conten-types stay there as JSON files (`/api`) and are universal for all db engines. But as of now, there is no way to take an existing schema and use it in another db.
This initialization step is not automated yet. So you have either re-create all your models from scratch using the new setup, or make sure the tables/documents exist.

**Comment by madonzy** [comment] 2018-11-19 11:47
Ok, thanks, hope to see this feature soon :)

**Comment by lauriejim** [comment] 2018-11-20 11:05
Thank you for this feedback. 
https://portal.productboard.com/strapi

**Closed by lauriejim** 2018-11-20 11:05 UTC

**Comment by ilanl** [comment] 2020-06-30 07:16
I'd like to use Strapi, but we already have a postgres db with many tables. How can I import my tables?
Installing manually destroys the other tables.

**Comment by StianOvrevage** [comment] 2020-11-25 22:09
@ilanl You can create a new `schema` inside the same `database` in PostgreSQL and configure Strapi to use that. That avoids collisions and I assume destruction of the existing tables (that are by default in the `public` schema.)
