### ISSUE TITLE
Login not working at all

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#730] opened 2018-03-03 07:02 UTC
**Node.js version**:
v9.7.1
**npm version**:
v5.6.0
**Strapi version**:
v3.0.0-alpha.10.3
**Mongo version**:
v3.6.3
**Operating system**:
Linux Mint 18.2

I try to login to my strapi app but it's return this error:
```
{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Please provide your username or your e-mail."
}
```

This is my request and response in postman:
![screenshot from 2018-03-03 10-28-34](https://user-images.githubusercontent.com/25859075/36931562-b2f9efa6-1ecd-11e8-8fe6-50443ae3e488.png)

I also try to drop db and rerun server but it's still not working. I can't login with any user. I can only login to `/admin` with my admin user.

**Comment by Aurelsicoko** [comment] 2018-03-05 16:31
@mnlbox Try to use raw request using Postman instead of form-data request... Let me know if the issue is resolved and feel free to close it.

**Closed** 2018-03-12 17:49 UTC
Labels: priority: high, status: have to reproduce, type: bug 🐛

**Comment by Perseus** [comment] 2018-05-16 07:32
I'm having the same issue right now. Could someone tell me how this was resolved? I tried using the raw request as well. Not sure what I'm doing wrong :|

![](https://i.gyazo.com/a5d9ba9143ce129743e191b9c02d47ef.png)

**Comment by derrickmehaffy** [comment] 2018-05-16 07:49
@Perseus use the `x-www-form-urlencoded` not the body. But also you have an extra comma in there 😛

**Comment by Perseus** [comment] 2018-05-16 08:43
@derrickmehaffy holy crap, thank you so much! I thought I had already tried that, but apparently, I hadn't. Thanks for the help!

**Comment by derrickmehaffy** [comment] 2018-05-16 10:05
No problem @Perseus

**Comment by mathb67** [comment] 2018-05-25 14:41
Same issue here with the registrar route (using postman), but the @derrickmehaffy's answer fix it ! Thanks

**Comment by shuzootani** [comment] 2018-11-03 07:17
Hi @Perseus 
> Still having the issue with a post request using axios while setting the content type to be application/x-www-form-urlencoded but I'm pretty sure there's something wonky in my code over there.

I got 400 error for requesting login with axios [this example with axios](https://github.com/strapi/strapi/blob/8e393492d22cb4eb5a501ebde88b52a3d5eb79f9/docs/3.x.x/guides/authentication.md#local)
Did you figure something out?
Thanks

**Comment by Charlesdoiron** [comment] 2020-11-27 15:19
I get a lot of 400 too : )
Then i switch from _text_ to _JSON_ with **raw** selected and it works !

<img width="716" alt="Capture d’écran 2020-11-27 à 16 18 07" src="https://user-images.githubusercontent.com/4417717/100463575-586e0900-30cc-11eb-839f-e9914358edfb.png">

**Comment by kazerlelutin** [comment] 2020-12-15 20:59
doesn't work with **super admin** but succes with classic user (in raw/JSON)

**Comment by atularvind** [comment] 2021-01-23 14:19
This is a bit confusing at the start, but I figured out the way to overcome this. 
1. you need to **create the User from the Content Manager** not from the "settings > Anmistriation Panel > User"

<img width="840" alt="Screenshot at Jan 23 19-36-24" src="https://user-images.githubusercontent.com/1876476/105580601-574b1680-5db3-11eb-8517-0491c6477f30.png">

2. Make a POST request from the postman with identifier and password, make sure you use the `x-www-form-urlencoded`.

<img width="639" alt="Screenshot at Jan 23 19-41-57" src="https://user-images.githubusercontent.com/1876476/105580697-efe19680-5db3-11eb-9dbb-577c96cbdf6e.png">


Hope this helps! :)

**Comment by jscontreras** [comment] 2021-02-11 01:41
@atularvind  u're the best!! I literally spent hours trying to figure out what I was doing wrong

**Comment by gleenk** [comment] 2021-03-12 15:17
> This is a bit confusing at the start, but I figured out the way to overcome this.
> 
> 1. you need to **Create the User from the Content Manager** not from the "settings > Anmistriation Panel > User"
> 
> <img alt="Screenshot at Jan 23 19-36-24" width="840" src="https://user-images.githubusercontent.com/1876476/105580601-574b1680-5db3-11eb-8517-0491c6477f30.png">
> 
> 1. Make a POST request from the postman with identifier and password, make sure you use the `x-www-form-urlencoded`.
> 
> <img alt="Screenshot at Jan 23 19-41-57" width="639" src="https://user-images.githubusercontent.com/1876476/105580697-efe19680-5db3-11eb-9dbb-577c96cbdf6e.png">
> 
> Hope this helps! :)

Thank you man. They should add this to documentation....
