### ISSUE TITLE
The API call to publish a translated entity returns an error 400, with no indication on the ui

### ISSUE THREAD

**Issue by Frank-Krick** [strapi/strapi#19533] opened 2024-02-16 16:04 UTC
### Required System information

OS: win32-x64
Strapi Version: 4.20.1
Node/Yarn Version: yarn/1.22.19 npm/? node/v18.17.0 win32 x64
Edition: Community
Database: postgres
Language: Typescript

### Describe the bug

Translations can't be published and do not show up in API calls with `locale` filter.

They do show up in API call with `populate=localization` if reading one entity.

### Steps to reproduce the behavior

1. Create an entity in default language and publish
2. Create a translation and fill out all fields
3. Save
4. Open dev console
5. Publish
6. Console and network show failing call to strapi

*Request*
Request URL:
http://localhost:1337/content-manager/collection-types/api::product.product/5/actions/publish?locale=de-DE&relatedEntityId=4
Request Method:
POST

*Response*
```
{
    "data": null,
    "error": {
        "status": 400,
        "name": "ApplicationError",
        "message": "The related entity doesn't exist or the entity already exists in this locale",
        "details": {}
    }
}
```

### Expected behavior

Publishing should not fail, and additionally if it fails for valid reasons, the reason should be displayed in the user interface,

### Additional context

Upgraded to 4.20.1 to solve problem with internationalization in 4.14, just to find more  internationalization problems

**Comment by jy-choo** [comment] 2024-02-26 06:44
@Frank-Krick I faced this issue on both 4.20.1 and 4.20.2. Downgraded to 4.19.1 and seems to be okay now, perhaps that could be a temporary workaround until they release a more comprehensive fix.

**Comment by joshuaellis** [comment] 2024-02-28 08:59
Duplicate of #19528 which we're in the process of fixing :)

**Closed by joshuaellis** 2024-02-28 08:59 UTC
Labels: status: duplicate
