### ISSUE TITLE
It is possible to store empty required fields in drafts

### ISSUE THREAD

**Issue by pointout** [strapi/strapi#8394] opened 2020-10-19 21:04 UTC
### Describe the bug

If a collection entry is unpublished, you can save empty fields, although they are required.

### Steps to reproduce the behavior

1. create a required field (just tested it with textfields) in a collection
2. add an entry to the collection
3. unpublish the entry
4. delete the content of the required textfield and save the entry
5. empty required field is saved

### Expected behavior

show error message, that the field is required 

### System

- Strapi version: 3.2.4
- Database: sqlite
- Operating system: windows 10

**Comment by lauriejim** [comment] 2020-10-19 21:04
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/should-it-stay-possible-to-store-empty-mandatory-fields-at-updating-data-in-draft-mode/550/3

**Comment by derrickmehaffy** [comment] 2020-10-19 21:07
(Pending response from engineering team to know if this is actually a bug or intended)

**Comment by soupette** [comment] 2020-10-20 07:07
It is indeed an intended feature. As a content type can have many required fields we thought it was a good to let users be able to save their drafts with empty required fields. However, if you try to publish the same draft that does not check the validations an error will popup.

I am closing this issue since it is not a bug.

**Closed by soupette** 2020-10-20 07:07 UTC
Labels: priority: medium, source: core:framework
