### ISSUE TITLE
Impossible to access Strapi admin on my Ubuntu server

### ISSUE THREAD

**Issue by willembeke** [strapi/strapi#16000] opened 2023-03-06 00:23 UTC
Hi there, 

I've been struggling for hours to install Strapi successfully on my server, but can't find the solution.

## Bug report
After creating my admin account, you should get redirected to the admin dashboard but I only receive this message without any further information or any error message.

![Error message](https://user-images.githubusercontent.com/84085640/222994422-52528523-1db7-4a61-bf21-37e2249697df.png)

This screen I get on every path I'm trying to access.

### Required System information

- Node.js version: v16.13.0
- NPM version: 8.1.0
- Strapi version: 4.7.1
- Database: Postgres
- Operating system: Ubuntu20.04
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I'm stuck after registering the admin user and I'm left without any error message.

### Steps to reproduce the behavior

I simply installed Strapi locally where everything worked fine. After pulling it to my server, it seemed to work as well, but after the registration I can not go any further. The user I registered was added to my postgres db.

### Expected behavior

I should at least be able to see the admin dashboard or any error message but I simply don't know what went wrong...

### Code snippets

config/database.js

```
module.exports = ({ env }) => ({
  connection: {
    client: 'postgres',
    connection: {
      host: env('DATABASE_HOST', 'localhost'),
      port: env.int('DATABASE_PORT', 5432),
      database: env('DATABASE_NAME', 'strapi'),
      user: env('DATABASE_USERNAME', 'postgres'),
      password: env('DATABASE_PASSWORD', '0000'),
      schema: env('DATABASE_SCHEMA', 'public'), // Not required
      ssl: env.bool('DATABASE_SSL', false),
    },
    debug: false,
  },
});
```
config/server.js

```
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  app: {
      keys: env.array('APP_KEYS'),
    },
  webhooks: {
    populateRelations: env.bool('WEBHOOKS_POPULATE_RELATIONS', false),
  },
});
```

**Comment by derrickmehaffy** [comment] 2023-03-06 12:59
You need to set the server.js URL and rebuild your admin.

Not a bug, marking as closed.

**Closed by derrickmehaffy** 2023-03-06 12:59 UTC

**Comment by derrickmehaffy** [comment] 2023-03-06 18:34
That one can be safely ignored as that error isn't blocking, double check your network requests and make sure they are calling the correct URL.

**Comment by danielbeardsley** [comment] 2023-11-08 00:27
I can confirm I'm also seeing this problem. Visiting `/admin` makes a request to `/admin/telemetry-properties` which returns a 401; [it seems it's supposed to only be fore admins?](https://github.com/strapi/strapi/blob/22ffc8b6b74f91fbde5c273d7075ac5b44bbee12/packages/core/admin/server/routes/admin.js#L57). This response throws an exception which shows the error in the screenshot and prevents the page from rendering, forever showing a spinner.

**Comment by derrickmehaffy** [comment] 2023-11-08 04:29
> I can confirm I'm also seeing this problem. Visiting `/admin` makes a request to `/admin/telemetry-properties` which returns a 401; [it seems it's supposed to only be fore admins?](https://github.com/strapi/strapi/blob/22ffc8b6b74f91fbde5c273d7075ac5b44bbee12/packages/core/admin/server/routes/admin.js#L57). This response throws an exception which shows the error in the screenshot and prevents the page from rendering, forever showing a spinner.

The telemetry is not the cause and that error won't stop the page from loading.

**Comment by danielbeardsley** [comment] 2023-11-08 17:03
> The telemetry is not the cause and that error won't stop the page from loading.

I don't think this is correct.

This request hits a 401 and while the `await` doesn't throw an exception because of the `validateStatus` option, the resulting destructuring on an error response body *does* throw an exception. This exception is caught in the outer try/catch but the result is that we dont' get to line 160 and thus don't clear the "loading" state.

https://github.com/strapi/strapi/blob/6129ef3c6cf63481868f3c79cd1771ad61d036b0/packages/core/admin/admin/src/App.tsx#L127-L132

https://github.com/strapi/strapi/blob/6129ef3c6cf63481868f3c79cd1771ad61d036b0/packages/core/admin/admin/src/App.tsx#L160

**Comment by rakibulinux** [comment] 2024-05-13 06:32
@derrickmehaffy I'm facing similar issues. When I run the project in dev mode then it's start infinite loop. In every 3-4 second new tab is opening. Please take a look the video. Let me know how can I fix this issue.

https://github.com/strapi/strapi/assets/59226530/5abfea48-1e18-4b13-9647-a5872c72025a
