### ISSUE TITLE
DB content tables reset/truncated

### ISSUE THREAD

**Issue by cajoy** [strapi/strapi#18211] opened 2023-09-30 10:06 UTC
### Required System information

Launched In: 525 ms
OS: darwin-arm64
Strapi Version: 4.13.7
Node/Yarn Version: yarn/1.22.19 npm/? node/v18.16.1 darwin arm64
Edition: Community
Database: postgres

### Describe the bug

Database content tables truncates randomly. I have a site which last time changes was 5 days ago. Yesterday all content has been reset for no reason. before that was:

`relation "public.crawls" does not exist`
`"query": "select \"t0\".* from \"public\".\"crawls\" as \"t0\" where (\"t0\".\"url\" = $1 and \"t0\".\"published_at\" is not null) limit $2",
      "query_id": 0,
      "query_pos": 20,
      "session_id": "6516de9c.1f7e5",`
      
In configs I have in prod:
```
  return {
    connection: {
      client,
      ...connections[client],
      acquireConnectionTimeout: env.int('DATABASE_CONNECTION_TIMEOUT', 300000),
    },
    settings: {
      forceMigration: false,
      runMigrations: false,
    }
  };
```

After the `error` queries, strapi restarts itself. And seems like on restart it resets all content.

I suppose it is because DB become unavailable for a minute or so which causes errors on POD. GKE restart pod and on restart DB is not available yet which then causes tables restarts or some other reason.

### Expected behavior

Content tables should not reset and honour 

      forceMigration: false,
      runMigrations: false,

###

Is there any other config setting to block/stop resetting database tables?

**Comment by Boegie19** [comment] 2023-10-01 22:20
The most likely scenario is that is that someone connected a blank strapi instance without those settings to the database. what would auto remove all unknown content-types.

adding a can not replicate to auto close this issue in 2 weeks if noting else happens.

**Comment by Robert-Griffin** [comment] 2023-10-03 17:57
I've been struggling with this same issue and trying to find a solution.

**Comment by derrickmehaffy** [comment] 2023-10-03 18:22
I'll be blunt here as I'm talking with @Boegie19 on Discord. Strapi does not have the capability to "randomly delete data", as in we quite literally don't have the functions to do so.

There are several things that could cause this but we would need more information on.

The most common use-cases I see is that someone tried to connect a different Strapi project with a different content-type structure which deleted the tables. There is no way to completely turn off the auto-migrations as they are required to Strapi to run properly.

**Comment by Robert-Griffin** [comment] 2023-10-03 18:55
I don't believe it's randomly deleting data, I believe something is triggering a migration to run when it shouldn't and I can't find what's triggering the migration to run. 

We're running Strapi version 4.11.3. We're hosting our project on GCP. Strapi is running in an AppEngine flexible environment and the database is a cloudSQL PostgreSQL db version 14.9. 

We've had this same problem 3 times now. The project is a staging project and is only used by a small team of devs to test changes before deploying to prod. 

We typically notice that the content manager in the admin page doesn't reflect the content-type builder and shows a generic error message: 
![image](https://github.com/strapi/strapi/assets/73795111/a00e49ac-5afc-4d81-ba67-e482e1ebce3a)


We have to reset to app engine instance to get the CMS working again and then we're left with some deleted data and some incomplete data. 

Let me know if there's other information that would be helpful in tracking down this problem.

**Comment by derrickmehaffy** [comment] 2023-10-03 19:38
I would like to understand better how that staging environment works and confirm that it is not running in development mode.

How are changes pushed to that environment? Is the staging data pulled from production as a snapshot or is it persistent?

Database migrations will destroy any table where the content type doesn't exist, that was implemented in response to #1114 and is entirely intended.

**Comment by Robert-Griffin** [comment] 2023-10-03 19:56
The staging environment is running in production mode. Staging doesn't pull any data from the production environment and has it's own separate database. When we have changes to the CMS we rebuild using 'NODE_ENV=production strapi build'  then run with 'strapi start'. The logs confirm strapi is in production mode. The migrations when we deploy updates work fine and we don't have any problems at that point. It's always some time after a deployment that we have issues. Say a week or so after the last schema change.

**Comment by derrickmehaffy** [comment] 2023-10-04 07:12
> The staging environment is running in production mode. Staging doesn't pull any data from the production environment and has it's own separate database. When we have changes to the CMS we rebuild using 'NODE_ENV=production strapi build'  then run with 'strapi start'. The logs confirm strapi is in production mode. The migrations when we deploy updates work fine and we don't have any problems at that point. It's always some time after a deployment that we have issues. Say a week or so after the last schema change. 

That absolutely sounds like something is connecting to that database that shouldn't be. If it's not consistent then it's probably someone who has access to the database credentials connecting it to something that they shouldn't, or possibly some other scripted action.

**Comment by Robert-Griffin** [comment] 2023-10-04 17:50
Okay. Is there a way I can get more debug data around what specifically is triggering the migration to run? Or how could I reproduce the scenario that you mentioned in the previous reply to see if that is indeed what is triggering the bug? 

I've set debug: true in the config/database.ts file but I'm not seeing any indication in any logs that confirm that a migration is running/has run. I believe a migration was run because we saw DROP TABLE queries shortly after the vm container restarted.

I would like to know what can trigger migrations and how to test/log those migrations. I would also like to know if there's anything that Strapi does besides migrations that could drop tables.

It is also worth noting that our schema is never altered around the time that we see this bug.

**Comment by derrickmehaffy** [comment] 2023-10-13 15:05
Then it's not that app specificly that's doing it, do you have anything else that could possibly be connecting to this database?

If the schema isn't altered we wouldn't drop the tables.

**Comment by michalkos** [comment] 2023-12-07 09:48
We just had the issue with data deletion and we were able to reproduce the issue. We are on 4.15.5

We have one development database, localhost and test server connected to the development database.
On the localhost, we created content types and some data in it, but it was not yet synced to test server that is connected to the same database.

The test server in the cloud stopped because it was inactive for some time (or you can just restart the server). Once it started, it deleted the content types in database that Strapi didn't have in the configuration because it was not in sync.

I guess the same will happen when 2 devs work on same db but the code is not yet in sync? We did not try that yet.

**Comment by cajoy** [comment] 2023-12-07 10:49
I know what happened to me. I was storing data in Supabase postrgress database. It was randomly truncating. After move to Google Cloud it works as expected since then.

I suppose it has been truncated as Suppabase persist "intermal" information like permissions and so on in the database shared with strapi. 

On restart strapi possibly deletes tables of suppabase which causes to restart/restore from backup automatically. So it goes back to some backup point. Basically automatically restored to allow Supabase postrgress behave as expected.

**Closed** 2023-12-27 00:11 UTC
Labels: issue: bug, severity: medium, status: can not reproduce, source: core:strapi
