### ISSUE TITLE
400 Bad Request for Forgot Password API

### ISSUE THREAD

**Issue by john916zhang** [strapi/strapi#10727] opened 2021-08-12 23:35 UTC
## Bug report

when using /auth/forgot-password, always get a 400 bad request error.

![image](https://user-images.githubusercontent.com/195719/129283023-0b0d888b-e4d9-481b-87a3-63a3db21b711.png)

### System

- Node.js version:  14.8 
- NPM version:
- Strapi version:  3.6.6 
- Database:  MongoDB
- Operating system: Ubuntu 16.06

**Comment by derrickmehaffy** [comment] 2021-08-13 20:37
Which email provider are you using, if you are on the default did you properly configure sendmail?

Also if you setup an email provider, did you go into the email templates and change out the `@strapi.io` emails that come by default?

Closing for now as I can't reproduce this with a properly configured sendgrid provider (can't test sendmail as my ISP doesn't allow it). Will reopen when there is more information on reproducing the issue.

**Closed by derrickmehaffy** 2021-08-13 20:37 UTC
Labels: status: can't reproduce

**Comment by john916zhang** [comment] 2021-08-15 01:15
Thanks for the explanation. Could you change "400 bad request" to something more informational?

**Comment by derrickmehaffy** [comment] 2021-08-16 14:47
> Thanks for the explanation. Could you change "400 bad request" to something more informational?

We are planning to adjust all of the error handling in v4, I'm not sure of the exact plans for the current users & permissions plugin with it's refactoring for v4 but I would imagine we will be adjusting the error handling in that plugin to reflect the new v4 error system.
