### ISSUE TITLE
Unable to create a new user. Role select dropdown is not working properly

### ISSUE THREAD

**Issue by bledar** [strapi/strapi#18996] opened 2023-12-06 17:14 UTC
### Required System information
- Node.js version: 18
- Strapi version: v4.15.5
- Database: MySQL
- Operating system: Linux
- Is your project JavaScript or Typescript: Typescript

### Describe the bug
As a super admin I cannot create a new system user since when I try to select user role (required field) the whole form modal is closed, and all form data are lost. Seems to be a bug with the drop down since it is causing the whole modal to be closed. Normally after you select values only the dropdown is closed.

### Steps to reproduce the behavior

1. Go to _Settings > Admin panel > Users_
2. Click on **Invite new user**
3. Fill user form
4. Open **User's Role** dropdown and select or multiple roles.
5. Click outside dropdown to close it. 
6. The whole modal is closed, and all form data are lost.

### Expected behavior

After selecting the roles and clicking outside dropdown **ONLY the dropdown should be closed. **

### Screenshots

![CleanShot 2023-12-06 at 17 48 26](https://github.com/strapi/strapi/assets/4134276/86cb7e65-aa0f-492c-a674-5d85f997aeb5)

**Comment by joshuaellis** [comment] 2023-12-07 10:44
closing as it's a duplicate of #18293

**Closed by joshuaellis** 2023-12-07 10:44 UTC
Labels: status: duplicate
