### ISSUE TITLE
Route handling doesn't check called request method in array

### ISSUE THREAD

**Issue by daksamit** [strapi/strapi#7961] opened 2020-09-20 12:18 UTC
**Describe the bug**

Generated API doesn't handle properly route array of methods like described [here](https://strapi.io/documentation/v3.x/concepts/routing.html#how-to-create-a-route)

**Steps to reproduce the behavior**

New api for example "test" with routes.json like
```json
{
  "routes": [{
    "method": ["GET", "POST"],
    "path": "/(.*)",
    "handler": "test.index",
    "config": {
      "policies": []
    }
  }]
}
```

then `yarn develop` returns

```
[2020-09-20T11:54:28.534Z] debug ⛔️ Server wasn't able to start properly.
[2020-09-20T11:54:28.536Z] error TypeError: router[method] is not a function
    at /home/daksamit/dev/strapi/node_modules/strapi/lib/middlewares/router/utils/composeEndpoint.js:23:19
    at /home/daksamit/dev/strapi/node_modules/strapi/lib/middlewares/router/index.js:52:13
    at Array.forEach (<anonymous>)
    at /home/daksamit/dev/strapi/node_modules/strapi/lib/middlewares/router/index.js:50:40
    at /home/daksamit/dev/strapi/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/home/daksamit/dev/strapi/node_modules/lodash/lodash.js:2990:24)
    at /home/daksamit/dev/strapi/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/home/daksamit/dev/strapi/node_modules/lodash/lodash.js:9368:14)
    at Object.initialize (/home/daksamit/dev/strapi/node_modules/strapi/lib/middlewares/router/index.js:45:11)
    at /home/daksamit/dev/strapi/node_modules/strapi/lib/middlewares/index.js:53:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Expected behavior**

Api requests should read both GET and POST and handle proper method?

file: `node_modules/strapi/lib/middlewares/router/utils/composeEndpoint.js`
calls method `'get,post'` in my case instead of `'get'` or `'post'` accordingly.

**System**

- Node.js version: 12.13.0
- NPM version: 6.12.0
- Strapi version: 3.1.5
- Database: mongodb
- Operating system: linux

**Comment by derrickmehaffy** [comment] 2020-09-20 17:07
This is a koa thing, no it can't read methods in an array, they must be a string.

 I'm marking this as closed as it's not a bug, but an upstream design choice and not something within Strapi's control

**Comment by daksamit** [comment] 2020-09-21 08:19
It could be a nice feature then, anyway there is misleading information in docs

**Comment by derrickmehaffy** [comment] 2020-09-21 09:26
> It could be a nice feature then, anyway there is misleading information in docs

Can you link me to the misleading information in the docs so I can fix it? (Thank you!)

**Comment by daksamit** [comment] 2020-09-21 09:28
https://strapi.io/documentation/v3.x/concepts/routing.html#how-to-create-a-route
there is such example:
```
    {
      "method": ["POST", "PUT"],
      "path": "/restaurants/:id",
      "handler": "Restaurant.createOrUpdate",
      "config": {
        "policies": []
      }
    },

**Comment by derrickmehaffy** [comment] 2020-09-21 10:58
I am reaching out to our backend team to clarify the documentation first so for now going to reopen this until I can get a response from them.

**Comment by derrickmehaffy** [comment] 2020-09-21 13:32
I have confirmed with out backend team the example was bad, method must be a string and not an array. You can easily duplicate the route and have them both call the same controller, but it must be multiple route entries.

**Comment by daksamit** [comment] 2020-09-21 13:39
Yep, exactly what I did.
In some specific cases, it could be redundant and not really readable, but you right its better to duplicate route options with another method.

**Comment by derrickmehaffy** [comment] 2020-09-21 13:45
I've submitted that PR to fix the doc example, once it's merged it will close out this issue automatically, but thank you for pointing it out.

We have a massive documentation rewrite planned over the next 2 quarters. ;)

**Closed** 2020-09-21 14:53 UTC
Labels: type: help wanted
