### ISSUE TITLE
Admin url not updatable

### ISSUE THREAD

**Issue by JejomStark** [strapi/strapi#13589] opened 2022-06-17 09:52 UTC
### Required System information

- Node.js version: v14.19.3
- NPM version:'6.14.17
- Strapi version: 4.2.0
- Database: Postgresql
- Operating system: ubuntu

### Describe the bug
When I update the url of admin section, I get a white page.

### Steps to reproduce the behavior

1. Go to config/admin.js
2. Add an url attribute like this :

```
module.exports = ({ env }) => ({
  url: '/administrator',
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT'),
  },
});

```

4. Go to STRAPI_URL + '/administrator '
5. See error

### Expected behavior

Access to admin interface

**Comment by derrickmehaffy** [comment] 2022-06-17 10:55
Did you build the admin?

**Comment by JejomStark** [comment] 2022-06-17 14:50
I build the project with 'strapi build', is there a special command to rebuild the admin panel ?

**Comment by derrickmehaffy** [comment] 2022-06-17 21:32
You need to use `yarn build` or `npm run build`

**Comment by derrickmehaffy** [comment] 2022-06-17 21:33
Unable to reproduce on v4.2.0 or v4.3.0.beta.1 closing until we have more information from the user to reproduce.

**Closed by derrickmehaffy** 2022-06-17 21:33 UTC
Labels: status: can not reproduce
