### ISSUE TITLE
Change datetime field from drop-down to text field

### ISSUE THREAD

**Issue by teinett** [strapi/strapi#12175] opened 2022-01-11 12:13 UTC
### Describe the bug

The field of time is drop-down list, not text field in Strapi v4. 

So as an editor I can only create material with an accuracy of up to 15 minutes, although in news media, an accuracy of up to 1 minute is important.

### Steps to reproduce the behavior

Add date field with type of datetime. Try to enter any time by typing - this option is no available, because it's drop-down field.

### Expected behavior

The date and time fields allow to type text to be able to type time 01:22, for example. 

### Screenshots

<img width="1398" alt="2022-01-11 15-02-04" src="https://user-images.githubusercontent.com/1038168/148939814-21475f76-4c05-4f16-b5ba-b12ac8bd8365.png">

### System

- Node.js version: 14.17.5 -->
- NPM version: 6.14.14
- Strapi version: 4.0.3
- Database: SQLite
- Operating system: MacOS

**Comment by kasonde** [comment] 2022-01-11 15:03
Next time @teinett please follow the feature request template.

**Comment by yanniskadiri** [comment] 2022-01-25 13:54
A PR will be opened this week to solve this issue, thanks for highlighting it!

**Comment by alex2600** [comment] 2022-02-21 13:32
Referring the fix @HichamELBSI applied regarding this issue:
The fix applied by @HichamELBSI here https://github.com/strapi/strapi/pull/12298 does not address the issue properly.
> Change the DateTimePicker time dropdown step from 15 min to 1
![image](https://user-images.githubusercontent.com/2094273/154964881-813d49c7-f12c-420a-ba9f-2923bec34b83.png)

As stated by the original poster @teinett the expected behavior is to be able to type text into the time field. 
The expected behavior is NOT to have 60x12=720 filelds in a drop down box, which is a honestly speaking a UX nightmare.
I would prefer having a simple input box für text over this.

The original approach with 15min increments was working fine for most cases.
Alternatively one should be able to input a custom time using the keyboard (which is not working right now at all).

So I would ask you to:
- revert the change which introduced 1min increments into the time-picker
- allow keyboard input for the time-picker

Thanks

**Comment by alex2600** [comment] 2022-02-21 13:40
Furthermore todays date is no longer highlighted in the datepicker popup:
![image](https://user-images.githubusercontent.com/2094273/154965972-d3474ca5-fff0-483b-95d6-a2ed895307e0.png)

This used to be the case in v3.6.8:
![image](https://user-images.githubusercontent.com/2094273/154966130-4165b9ec-9001-41e3-bf50-a35c669e0235.png)

**Comment by yanniskadiri** [comment] 2022-02-22 14:37
@alex2600 you will be happy because this was actually a temporary quick fix to allow users to have a 1-min accuracy. 
I agree it's not perfect in terms of UX and that's why we are currently addressing it. You should see a change in the coming weeks.

**Comment by derrickmehaffy** [comment] 2022-05-06 16:04
closing as duplicate of: https://github.com/strapi/strapi/issues/10510

**Closed by derrickmehaffy** 2022-05-06 16:04 UTC
Labels: issue: enhancement, source: core:admin

**Comment by gulshanAI** [comment] 2023-01-19 09:59
Yes, Strapi provides the time dropdown  based on  
![Screenshot 2023-01-19 at 3 25 53 PM](https://user-images.githubusercontent.com/35621580/213411857-ba8bb12d-0e8a-4f85-ab26-92f3093892e6.png)

**Here is the process**

![ezgif com-gif-maker](https://user-images.githubusercontent.com/35621580/213412490-23611c54-2411-4595-b4a7-3c7f2fb492b3.gif)

1. Go to Configure View
2. Click on Edit 
3. There you can see the Time interval (minutes)

**Comment by gagal18** [comment] 2023-12-06 09:44
Is this available on version 4.15.4? @gulshanAI
