### ISSUE TITLE
🐛 codemirror Error in 'strapi-plugin-content-manager' 3.5.2

### ISSUE THREAD

**Issue by macarthuror** [strapi/strapi#9577] opened 2021-03-02 22:02 UTC
### Describe the bug

When the `develop` command is executed and webpack is compiling it shows the following error:
```terminal
Error: Module not found: Error: Can't resolve 'codemirror' in 'C:\Users\Usuario\Desktop\saaguita-back\.cache\plugins\strapi-plugin-content-manager\admin\src\components\InputJSON'
```

I think it is related to #9564

### Steps to reproduce the behavior

1. It's necessary to have all the dependencies of strapi in the 3.5.2 version
> If you downgrade _strapi-plugin-content-manager_ `3.5.1` runs ok

2. Run `yarn develop`
3. See error

### Expected behavior

Initialize the development server

### Screenshots

![image](https://user-images.githubusercontent.com/24395219/109720152-573af500-7b6f-11eb-8d4a-3b569a1fcafe.png)

### System

- Node.js version: v14.15.4
- NPM version: v6.14.10
- Strapi version: v3.5.2
- Database: MongoDB 
- Operating system: win64

### Additional context

*This problem is solved using the _strapi-plugin-content-manager_ 3.5.1 version*

**Comment by soupette** [comment] 2021-03-03 10:57
Hello @macarthuror I tried to reproduce your issue on my machine (Mac OS) but I can't reproduce it.

Can you try to delete your node_modules and your `yarn.lock` and check if the problem persists?

**Comment by derrickmehaffy** [comment] 2021-04-15 18:19
Closing as no new information

**Closed by derrickmehaffy** 2021-04-15 18:19 UTC
Labels: status: can't reproduce
