### ISSUE TITLE
strapi-plugin-users-permissions: password validation should be done asynchronously

### ISSUE THREAD

**Issue by haschu** [strapi/strapi#7261] opened 2020-07-30 09:27 UTC
I'm not sure whether you consider this a bug or a feature, but it should be fixed soon anyways.

Right now, the password validation uses `bcrypt.compareSync` - which is quite an expensive operation:
https://github.com/strapi/strapi/blob/97dfde210a793452d70e5b99b5df05899f26de1b/packages/strapi-plugin-users-permissions/services/User.js#L116-L118

Synchronous functions are blocking the event-loop and should be avoided. Hence we should use `bcrypt.compare` and make `validatePassword` return a `Promise`.

I could come up with a pull request if you guys are okay with that change :)

**Comment by lauriejim** [comment] 2020-07-31 12:40
Hello! Thank you for this proposition.
I think if @alexandrebodin or @petersg83 valid that, you will be able to create a PR to update that according to every place this function is used.

**Comment by petersg83** [comment] 2020-07-31 13:09
You're right, that would be nice, thank you :)

**Comment by harshilparmar** [comment] 2020-08-04 19:45
@lauriejim @petersg83 Can I try this?

**Comment by alexandrebodin** [comment] 2020-08-04 21:23
@harshilparmar go ahead :)

**Comment by harshilparmar** [comment] 2020-08-07 11:46
@alexandrebodin I couldn't figure out how to setup project locally,Can you help :) What to do after yarn setup? How to run ?

**Comment by lauriejim** [comment] 2020-08-10 09:34
It's really simple, just follow the CLI installation guide into the documentation.
Here is the link - https://strapi.io/documentation/v3.x/installation/cli.html

**Comment by alexandrebodin** [comment] 2020-08-10 11:54
@harshilparmar to setup the local dev env you can follow the contribution guide . basically clone the repo / yarn setup go into getstarted and yarn develop.

**Comment by harshilparmar** [comment] 2020-08-10 11:55
Thanks @lauriejim @alexandrebodin 👍

**Comment by VinitSarvade** [comment] 2020-08-26 07:37
@harshilparmar: If you haven't been able to take this, would you mind me taking this up?

**Comment by harshilparmar** [comment] 2020-08-26 08:56
@VinitSarvade  Yeah sure

**Comment by VinitSarvade** [comment] 2020-08-26 12:25
@lauriejim @alexandrebodin @petersg83: Please review my PR #7612 and provide any feedback to improve the fix if required.

**Comment by lauriejim** [comment] 2020-09-01 14:22
Thank you for your PR, the tech team will review it as soon as possible.

**Comment by alexandrebodin** [comment] 2020-09-01 15:05
Closing as PR was merged

**Closed by alexandrebodin** 2020-09-01 15:05 UTC
Labels: good first issue, priority: low, source: plugin:users-permissions, type: enhancement

**Comment by baermathias** [comment] 2020-10-07 09:32
Just wanted to mention that there is a potential risk of logging in a user with an arbitrary password. It appears in the case of having worked with the previous version of Strapi and having copied the whole `Auth.js` file into `root_project/extensions/users-permissions/controllers/Auth.js` and edited it for some reason (custom registration process or whatever). The problem is that in the older version `validatePassword` was called like this:

```Javascript
const validPassword = strapi.plugins['users-permissions'].services.user.validatePassword(
  params.password,
  user.password
);
```

Instead of how it is called right now:

```Javascript
const validPassword = await strapi.plugins['users-permissions'].services.user.validatePassword(
  params.password,
  user.password
);
```

And if you old function call overwrites the new version it leads to the problem, that you can pass an arbitrary password, e.g.: 

`{
  "identifier": "correct-user-email@email.com",
  "password": "anything-here-sdfjkdhs78zt895hruien89"
}`

to the login endpoint (`http://localhost:1337/auth/local`) and it will response you with status 200 + the whole user object

**Comment by haschu** [comment] 2020-10-07 12:51
@baermathias Very good point. This should at least be mentioned in the changelog.

**Comment by baermathias** [comment] 2020-10-07 13:26
@haschu I also think, that this should be mentioned in the changelog. Or maybe even in the docs somewhere under `Migrations guides`. What do you think @lauriejim ?

**Comment by alexandrebodin** [comment] 2020-10-07 13:40
Hello, sorry but we cannot mention every changes that happened in files that you can overwritte :)
We actually have a big warning on the migration guide about reviewing and upgrading your extensions on version update.

**Comment by lh15** [comment] 2020-10-28 05:04
I had the same issue that I copied `Auth.js` and it didn't have `await` in the `const validPassword` call.

**Comment by mattf96s** [comment] 2020-12-09 09:51
@alexandrebodin hi Alex, I see now that this is what I was referencing.

It is the exact scenario as mentioned by @baermathias: anyone with a custom auth controller who didn't realize the validatePassword was now asynchronous is at risk. 

I understand that not everything can be referenced in the migration docs, but I feel like this was serious enough to warrant so. 
Thanks
Matt

**Comment by alexandrebodin** [comment] 2020-12-09 12:56
Hi ! 
Ok makes more sense with the rest of the conversation I only saw the comment in the commit :) 
We add a warning on every update doc / migration guides to make sure the developpers diff their code. It is not perfect for sure. 
We are working on news ways to improve this and our vision is pretty clear on the fact that extensions should be specified & limited so they can be maintained  & documented :)

If you want to know more about that feel free to read this new RFC https://github.com/strapi/rfcs/pull/23 :)

**Comment by lh15** [comment] 2020-12-09 14:58
@alexandrebodin what is the strapi recommended way to handle the JWT client side?

From everything I read the cookie should really be httpOnly.

So to me it seems that strapi users plug-in is pretty much unusable without overriding that file.

What are your thoughts on this?

Thanks
