### ISSUE TITLE
Saving content with a line break appended in a JSON-based rich text editor field throws error

### ISSUE THREAD

**Issue by Simran-B** [strapi/strapi#20515] opened 2024-06-14 10:09 UTC
### Required System information

- Node.js version: node/v18.14.1 win32 x64 workspaces/false
- NPM version: npm/9.3.1
- Strapi version: 5.0.0-beta.10
- Database: sqlite
- Operating system: win32-x64
- Is your project Javascript or Typescript: Type**S**cript

### Describe the bug

If you add line breaks to the end of a Rich text (Blocks) field, saving the content raises an error. This is even the case if you add text after it. Publishing does not throw an error, however. Adding line breaks at the top or somewhere in the middle does not have this error, either.

```
TypeError: Cannot read properties of undefined (reading 'type')
    at checkButtonDisabled (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JT3VOTYO.js?v=03705833:75309:49)
    at BlocksToolbar (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-JT3VOTYO.js?v=03705833:75314:28)
    at renderWithHooks (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:11568:26)
    at mountIndeterminateComponent (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:14946:21)
    at beginWork (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:15934:22)
    at beginWork$1 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:19781:22)
    at performUnitOfWork (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:19226:20)
    at workLoopSync (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:19165:13)
    at renderRootSync (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:19144:15)
    at recoverFromConcurrentError (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:18764:28)
```

### Steps to reproduce the behavior

1. Create a content type with **Draft & Publish** enabled
2. Add a **Rich text (Blocks)** field and save
3. Go to **Content Manager**, enter a word, and **Publish**
4. Optionally enter a line break after the word and **Publish** - no error
5. Enter a line break at the end and **Save** - error occurs

### Expected behavior

Saving should simply work like Publishing does.

### Screenshots

![image](https://github.com/strapi/strapi/assets/7819991/9548054b-ddd5-4f1d-b000-b8c1022b28fa)

**Comment by remidej** [comment] 2024-06-28 09:14
closing as a duplicate of #20028

**Closed by remidej** 2024-06-28 09:14 UTC
