### ISSUE TITLE
Malformed query in Media Library thumbnail URL when using S3 presigned URLs

### ISSUE THREAD

**Issue by InSecker** [strapi/strapi#18370] opened 2023-10-09 14:58 UTC
### Required System information

- Node.js version: 16.20.1
- NPM version: 8.19.4
- Strapi version: 4.14.3
- Database: postgres
- Operating system: MacOS 13.5
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I'm still having the bug described in [this issue](https://github.com/strapi/strapi/issues/17608). Media library thumbnails are broken when using AWS S3 provider because of the `updatedAt` query param. Marked as resolve in the previous issue but I'm still experiencing it with the latest version.

### Steps to reproduce the behavior

1. Install the [AWS S3 provider](https://market.strapi.io/providers/@strapi-provider-upload-aws-s3) and set ACL to private to enable S3 presigned URLs
2. Add an asset to the Media Library in Strapi
3. View the Media Library at `https://<your strapi hostname>/admin/plugins/upload`
4. Get a 403 for the asset thumbnail and a broken image icon

### Expected behavior

Asset thumbnails should appear.

### Screenshots

![image](https://github.com/strapi/strapi/assets/41473901/1ee06f95-a099-46e6-9e55-261ea04f210d)

### Code snippets

See previous issue.

**Comment by joshuaellis** [comment] 2023-10-09 15:01
Thanks for the report, this is a duplicate of #17938

**Closed by joshuaellis** 2023-10-09 15:01 UTC
