### ISSUE TITLE
Admin UI crash while using the plugin-color-picker

### ISSUE THREAD

**Issue by chuankaiwei** [strapi/strapi#18585] opened 2023-10-26 09:28 UTC
### Required System information

- Node.js version: v18
- NPM version: 9.8.1
- Strapi version: 4.13.7
- Database: SQLite
- Operating system: macOS
- Is your project Javascript or Typescript: Javascript
- @strapi/plugin-color-picker version: 4.13.7

### Describe the bug

may be that the wrong `NODE_ENV` was used to build the plugin-color-picker and release it.

```
main.0e454836.js:80672  TypeError: (0 , react_jsx_dev_runtime__WEBPACK_IMPORTED_MODULE_1__.jsxDEV) is not a function
    at ColorPickerIcon (main.0e454836.js:156322:293)
    at Xh (main.0e454836.js:80650:137)
    at Wk (main.0e454836.js:80773:337)
    at Vk (main.0e454836.js:80763:389)
    at Uk (main.0e454836.js:80763:320)
    at Jk (main.0e454836.js:80763:180)
    at Ok (main.0e454836.js:80754:88)
    at Hk (main.0e454836.js:80751:429)
    at J (main.0e454836.js:91942:203)
    at MessagePort.R (main.0e454836.js:91943:128)
```

### Steps to reproduce the behavior

1. Install @strapi/plugin-color-picker
2. Go to 'Content-Type Builder'
3. See error

### Screenshots

<img width="2254" alt="image" src="https://github.com/strapi/strapi/assets/88698599/8fc5282a-2e97-4f52-8e26-89c627706d00">

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by joshuaellis** [comment] 2023-10-26 09:40
duplicate of #18575, please check other issues before opening them.

**Closed by joshuaellis** 2023-10-26 09:40 UTC
