### ISSUE TITLE
invalid JSON allowed in database

### ISSUE THREAD

**Issue by letternumber** [strapi/strapi#13129] opened 2022-04-14 12:17 UTC
### Required System information

    Node.js version: v14.15.0
    NPM version: 6.14.16
    Strapi version: 4.1.5
    Database: pg
    Operating system: Debian
    Browser: Chromium Version 90.0.4430.212 (Developer Build) built on Debian 11.0, running on Debian 10.1 (Qinux 3.1) (64-bit)

### Describe the bug

An empty string "" can be inserted into a JSON type field without validation.  
@strapi/database/lib/fields.js

```
`class JSONField extends Field {
  toDB(value) {
    return JSON.stringify(value);
  }

  fromDB(value) {
    if (typeof value === 'string') return JSON.parse(value);
    return value;
  }
}`
```
on retrieval the JSON parse thows an error.  This displays an error message in the admin panel and no data is displayed for the collection, just a spinner.

### Steps to reproduce the behavior

    create collection that has a JSON type
    either through the admin panel in the code window or via a post request; insert and empty string into the JSON type in the collection.

### Expected behavior

alert the user in the admin panel that the data in the field is not valid  and return a 400 error when posting via the api

### Attempted fixes

a simple try/catch/throw will keep the data out of the database but I could not find were form validation happens to alert the user beforehand
```
toDB(value) {
    try {
      JSON.parse(value)
    } catch {
      throw new Error(`Invalid JSON format, got ${value}`);
    }
    return JSON.stringify(value);
  }
```

**Comment by derrickmehaffy** [comment] 2022-04-18 21:01
Hello!

First thank you for reporting this feature need.

To manage feature requests and the Strapi roadmap, we are using [[Canny](https://feedback.strapi.io/)[](https://feedback.strapi.io/)](https://feedback.strapi.io//).
You will be able to access the Public Roadmap here: [https://feedback.strapi.io](https://feedback.strapi.io/).

In your message, please mention the URL of this thread in case some messages are posted there. But the most important is to have your feedback posted on our feedback/roadmap site.
The product team is reading EVERY comment, that really helps us to develop the project in the right direction.
We are keeping all feature requests and project insights in one place, our feedback website.
I'm closing this GitHub issue, but please feel free to continue the discussion with other community members here.

Thank you for your insight and have a good day.

**Comment by vripoche** [comment] 2022-05-30 12:18
Hello,

It is still a bug because data  with wrong JSON is saved on update (not on create) and it breaks the list: the page of collection list with the entry return also a `500` error. The workaround is a temporarily fix but cannot be a solution :(

**Comment by petersg83** [comment] 2022-09-02 17:44
Hello everyone :) 
I'm not sure to understand how to reproduce it.
Could you do a screen recording of the problem?

**Comment by ScyDev** [comment] 2022-09-02 20:26
Post invalid JSON via the API to a content type that has a JSON field.

**Comment by petersg83** [comment] 2022-09-02 21:05
I receive an error when I try this
<img width="663" alt="Capture d’écran 2022-09-02 à 23 03 10" src="https://user-images.githubusercontent.com/11708220/188235023-5acd47ef-2ce8-4f43-9863-987a23196aef.png">

**Closed** 2022-10-12 08:21 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:strapi, source: core:database
