### ISSUE TITLE
Cannot add a component (which has already a component field) to a new component

### ISSUE THREAD

**Issue by sarneeh** [strapi/strapi#4890] opened 2020-01-03 14:22 UTC
**Describe the bug**
I can't attach a component (which has a component field already), to a new component. Components, which already have component fields in it are not available in the components select menu:

![image](https://user-images.githubusercontent.com/11553624/71728042-5a880300-2e3c-11ea-9fd0-1dcd62a25fba.png)

**Steps to reproduce the behavior**
1. Create a new component `component1`
2. Create a new component `component2` with field which holds `component1`
3. Try to create a new component `component3` with field which holds `component2`
4. `component2` will not be available to attach

**Expected behavior**
I expect the above scenario to work.

**System**
- Node.js version: 12.10.0
- NPM version: 6.10.3
- Strapi version: 3.0.0-beta.18.3
- Database: MongoDB
- Operating system: MacOS

**Comment by soupette** [comment] 2020-01-03 15:08
@sarneeh in fact it's an intended behaviour has the ui doesn't scale for n level of nested components. However, you can create them manually by editing your files the UI should still work.

I am closing this issue as it is not a bug.

**Closed by soupette** 2020-01-03 15:08 UTC

**Comment by sarneeh** [comment] 2020-01-03 15:16
@soupette You're right, editing the files manually does work! Thanks for the explanation!

**Comment by Equable** [comment] 2020-05-14 18:30
@soupette should this be preventing me from editing fields in the UI when this type of change is made.

currently running into the issue where if I add a nested component via json I can't edit the fields in the UI until the nested component is removed. Just wondering if there are any extra steps. Works great for our layouts, sucks that i can no longer change/add fields in the ui once that change has been made for that component

**Comment by avneeshroks** [comment] 2020-06-13 08:16
> @soupette should this be preventing me from editing fields in the UI when this type of change is made.
> 
> currently running into the issue where if I add a nested component via json I can't edit the fields in the UI until the nested component is removed. Just wondering if there are any extra steps. Works great for our layouts, sucks that i can no longer change/add fields in the ui once that change has been made for that component

Facing the same, kind of confusing..

**Comment by filipe-q** [comment] 2020-06-27 19:26
In case someone is wondering which file you're supposed to edit, it should be the json file of the component where you want to add the nested field, the directory should be /components/<category_name>. And then after your last attribute's closing } you should add a comma and then paste below:
`"<component_you_want_to_add>": {
      "type": "component",
      "repeatable": true,
      "component": "<category_name>.<component_you_want_to_add>"
 }`

**Comment by christopher4lis** [comment] 2020-09-16 18:23
Would love to see this as an enhancement in the future. Been a big fan of WordPress' Advanced Custom Fields plugin that allows for an unlimited amount of nesting via the frontend interface.

**Comment by lauriejim** [comment] 2020-09-17 09:31
Thank you for this feedback.
