### ISSUE TITLE
strapi-5@0.1.0 error: Cannot find module '@strapi/email/package.json' on first start 

### ISSUE THREAD

**Issue by rbjs** [strapi/strapi#20298] opened 2024-05-11 09:14 UTC
### Required System information
- Node.js version: v20.12.2
- NPM version: 10.5.2
- Strapi version: 5.0.0-beta.7
- Database: n/a
- Operating system: macOS 13.6.4
- Is your project Javascript or Typescript: n/a
### Describe the bug

'npm run develop' returns fatal error on first run after fresh installation.

> strapi-5@0.1.0 develop
> strapi develop

⠋ Loading Strapi⠋ Building build context
[INFO] Including the following ENV variables as part of the JS bundle:
    - ADMIN_PATH
    - STRAPI_ADMIN_BACKEND_URL
    - STRAPI_TELEMETRY_DISABLED
✔ Building build context (47ms)
✔ Creating admin (378ms)
[ERROR]  There seems to be an unexpected error, try again with --debug for more information
`                                                                               
│   Error: Cannot find module '@strapi/email/package.json' 
│   Require stack:  
│   - /Users/dev/strapi5/node_modules/@strapi/core/dist/loaders/plugins/get-enabled-plugins.js 
│   - /Users/dev/strapi5/node_modules/@strapi/core/dist/loaders/plugins/index.js
│   - /Users/dev/strapi5/node_modules/@strapi/core/dist/loaders/index.js 
│   - /Users/dev/strapi5/node_modules/@strapi/core/dist/providers/registries.js 
│   - /Users/dev/strapi5/node_modules/@strapi/core/dist/providers/index.js 
│   - /Users/dev/strapi5/node_modules/@strapi/core/dist/Strapi.js 
│   - /Users/dev/strapi5/node_modules/@strapi/core/dist/index.js 
│   - /Users/dev/strapi5/node_modules/@strapi/strapi/dist/cli/commands/admin/create-user.js 
│   - /Users/dev/strapi5/node_modules/@strapi/strapi/dist/cli/commands/index.js 
│   - /Users/dev/strapi5/node_modules/@strapi/strapi/dist/cli/index.js 
│   - /Users/dev/strapi5/node_modules/@strapi/strapi/bin/strapi.js 
│   at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)           
│   at Module._load (node:internal/modules/cjs/loader:984:27)                       
│   at Module.require (node:internal/modules/cjs/loader:1231:19)                    
│   at require (node:internal/modules/helpers:179:18)
│   at Module.getEnabledPlugins (/Users/dev/strapi5/node_modules/@strapi/core/dist/loaders/plugins/get-enabled-plugins.js:55:25) 
│   at loadPlugins (/Users/dev/strapi5/node_modules/@strapi/core/dist/loaders/plugins/index.js:76:50) 
│   at Module.loadApplicationContext (/Users/dev/strapi5/node_modules/@strapi/core/dist/loaders/index.js:16:5)
│   at Object.register (/Users/dev/strapi5/node_modules/@strapi/core/dist/providers/registries.js:26:17) 
│   at Strapi.register (/Users/dev/strapi5/node_modules/@strapi/core/dist/Strapi.js:301:32) 
│   at Strapi.load (/Users/dev/strapi5/node_modules/@strapi/core/dist/Strapi.js:293:16) 

`
### Steps to reproduce the behavior

npx create-strapi-app@beta my-project  --quickstart
cd my-project
npm run develop

**Comment by Ophuscado** [comment] 2024-05-11 17:07
You can work around it temporarily until a true patch comes out by commenting out line 14 at `node_modules/@strapi/core/dist/loaders/plugins/get-enabled-plugins.js`.

**Comment by corvallo** [comment] 2024-05-13 19:24
I manage to solve by installing manually @strapi/email@5.0.0-beta.7

**Comment by joshuaellis** [comment] 2024-05-14 08:59
@rbjs can you run `npm ls @strapi/email` and share the output please?

**Comment by corvallo** [comment] 2024-05-14 09:29
`strapi@0.1.0 /Users/corvallo/strapi
├── @strapi/email@5.0.0-beta.7
└─┬ @strapi/strapi@5.0.0-beta.7
  └── @strapi/email@5.0.0-beta.7`

**Comment by LuisRodriguezLD** [comment] 2024-05-14 17:54
Usually I don't write comments like 'same here' but I'm also seeing this and I can provide more input.

Same env as OP but:
- Using TS
- Using SQLite

Running `npm ls @strapi/email` yields
```
project@0.1.0 /Users/user/dev/project
└─┬ @strapi/strapi@5.0.0-beta.7
  └── @strapi/email@5.0.0-beta.7
```

The file requiring this package is here -> https://github.com/strapi/strapi/blob/v5.0.0-beta.7/packages/core/core/src/loaders/plugins/get-enabled-plugins.ts

Let me know if you have additional questions

**Comment by joshuaellis** [comment] 2024-05-14 18:07
Thanks @LuisRodriguezLD, what package manager are you using? 😊

**Comment by LuisRodriguezLD** [comment] 2024-05-14 18:13
NPM 10.5.0
NODE 20.12.1

**Comment by joshuaellis** [comment] 2024-05-15 08:21
The issue comes from the fact that only `@strapi/strapi` has `@strapi/email` listed as a dependency, _but_ `@strapi/core` tries to load it dynamically without having it listed as a dependency, this will most likely break `pnpm` anyway.

@alexandrebodin || @innerdvations I think it's worth reviewing how plugins are loaded by strapi/core because whilst the immediate fix would be to add `@strapi/email` to the list of deps in `@strapi/core` I think it's a brittle solution considering that the package wants to load deps it doesn't know about and thus relies on package manager implementation which as we can see is subject to break. Made a loom to demonstrate the issue https://www.loom.com/share/a75b25cbed004b829d3df761bcef7a1e?sid=219dcfa1-79ec-4a2b-aa9f-5807c4fe4871

**Comment by lerry** [comment] 2024-05-15 08:31
I have the same issue.
Node.js version: v20.13.1
NPM version: 10.5.2
Strapi version: 5.0.0-beta.7
Database: postgresql
Operating system: Debian 12
Is your project Javascript or Typescript: Typescript

**Comment by lunatiqqc** [comment] 2024-05-20 07:26
"yarn install" fixes for me

**Comment by Convly** [comment] 2024-05-23 07:19
Hey there, just sharing here that I'm trying to look at this issue but can't reproduce it locally with NPM 10.5.0 (or .2) and node 20.12.1.

I'll continue, but it might take a bit longer than expected.

**Comment by LuisRodriguezLD** [comment] 2024-05-23 15:30
Thanks for looking into this @Convly 
However, wouldn't it make sense to add this `.npmrc` file as part of the initial template?
I feel this could make life easier for devs who just want to try Strapi without needing to dig into why it's randomly failing

I'm happy to work on this if you think is a good idea.

**Comment by Convly** [comment] 2024-05-24 07:21
Hey @LuisRodriguezLD !

Thanks for your input. We've talked about your proposal internally and concluded that we would rather fix the bug directly rather than add a temporary workaround for the beta. Adding more configuration for default apps for such a niche issue feels a bit too much for us. 

One thing that we can do though, is to add some troubleshooting into the documentation with a clear explanation of what's happening and how to solve it.

We'll add the development of a fix for this issue on our current backlog and try to deliver a satisfying solution asap.

What do you think?

Also, to be sure, can you confirm that adding `hoist=false` in your app's config fixed the issue?

**Comment by LuisRodriguezLD** [comment] 2024-05-24 13:17
Understandable.
Please note I have been unsuccessfully in having it work with `npm 10.5` as it currently lacks the option to set hoisting settings. There is an [install strategy](https://docs.npmjs.com/cli/v10/using-npm/config#install-strategy) but I've tried all options with no success.

Hoisting config exists in [pnpm](https://pnpm.io/npmrc#hoist) and [yarn](https://yarnpkg.com/configuration/manifest#installConfig) but is still a RFC in [npm](https://github.com/npm/rfcs/issues/287) 
There is a way to [trick npm](https://github.com/zackerydev/noist?tab=readme-ov-file) but it doesn't feel right 

That being said, would you guys considering updating the severity to `medium`?

**Comment by derrickmehaffy** [comment] 2024-05-24 13:53
If there is a valid workaround to the issue then we leave it at low. In this case the workaround is to use that config, downgrade your npm version, or use an alternative like yarn.

That's why it remains at low for now.

**Comment by Convly** [comment] 2024-05-24 14:33
On that note, while our criterion mandates us to have it as low on GitHub (for good reasons), we bumped it to medium in our internal team's backlog as we want to get it done as soon as we can

**Comment by mirkonasato** [comment] 2024-05-24 15:28
> From what I've found, it comes down to hoisting settings:
> 
> * if hoisting is enabled, no issue arise
> * if you add `hoist=false` to your project `.npmrc` (or disable hoisting globally), then dependency errors arise.
> 
> **Note: This is something that also happen on v4 since its launch.**

I never encountered and still don't see this problem with v4. I only got it when trying v5 for the first time right now.

This is using the Node `v20.13.1` and npm `10.8.0` for both v4 and v5, and I don't have any custom `.npmrc` settings.

**Comment by mirkonasato** [comment] 2024-05-24 15:37
As a workaround, adding `@strapi/email` as an explicit dependency in `package.json` seems to fix it.

**Comment by luismendoza-ec** [comment] 2024-05-25 17:22
> As a workaround, adding `@strapi/email` as an explicit dependency in `package.json` seems to fix it.

Thanks! I tried this, but now getting the following error (image attached).
![image](https://github.com/strapi/strapi/assets/125885777/78191710-debe-4943-bd92-9c92ba1a8ca7)

Using:
Node v20.9.0
NPM 10.1.0

**Comment by imdimasan** [comment] 2024-05-26 13:08
The same error occured.
Win11
NPM 10.5.2
NODE 20.13.1

**Comment by Jank1310** [comment] 2024-05-28 06:56
> > As a workaround, adding `@strapi/email` as an explicit dependency in `package.json` seems to fix it.
> 
> Thanks! I tried this, but now getting the following error (image attached). ![image](https://private-user-images.githubusercontent.com/125885777/333820729-78191710-debe-4943-bd92-9c92ba1a8ca7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4Nzk1NzgsIm5iZiI6MTcxNjg3OTI3OCwicGF0aCI6Ii8xMjU4ODU3NzcvMzMzODIwNzI5LTc4MTkxNzEwLWRlYmUtNDk0My1iZDkyLTljOTJiYTFhOGNhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQwNjU0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2E4MjllZGY1ODE3ZTMzYmQxOTAxMTI1YjJjZWI0ZWRjNTZjNDRlNjg4NzM3NjMwMzc2M2JmMDUwZTBhN2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9vKi9qlsyJz9dt-z35p1QybkWHS5cqJe2Q7EIa_ONJc)
> 
> Using: Node v20.9.0 NPM 10.1.0

Did you try to add 5.0.0-beta.8 release of @strapi/email, it works for me

**Comment by yusuf-saydullayev** [comment] 2024-05-29 07:23
The same error occured.
Win11
NPM 10.8.0
NODE 20.13.1
Strapi version: 5.0.0-beta.8 release

**Comment by luismendoza-ec** [comment] 2024-05-30 14:12
> > > As a workaround, adding `@strapi/email` as an explicit dependency in `package.json` seems to fix it.
> > 
> > 
> > Thanks! I tried this, but now getting the following error (image attached). ![image](https://private-user-images.githubusercontent.com/125885777/333820729-78191710-debe-4943-bd92-9c92ba1a8ca7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4Nzk1NzgsIm5iZiI6MTcxNjg3OTI3OCwicGF0aCI6Ii8xMjU4ODU3NzcvMzMzODIwNzI5LTc4MTkxNzEwLWRlYmUtNDk0My1iZDkyLTljOTJiYTFhOGNhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQwNjU0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2E4MjllZGY1ODE3ZTMzYmQxOTAxMTI1YjJjZWI0ZWRjNTZjNDRlNjg4NzM3NjMwMzc2M2JmMDUwZTBhN2U3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9vKi9qlsyJz9dt-z35p1QybkWHS5cqJe2Q7EIa_ONJc)
> > Using: Node v20.9.0 NPM 10.1.0
> 
> Did you try to add 5.0.0-beta.8 release of @strapi/email, it works for me

Yes, thanks! that worked for me

**Comment by folt3k** [comment] 2024-06-02 19:08
I had same issue and adding `"@strapi/email": "5.0.0-beta.8"` in `packege.json` fixed it.

**Comment by mickaeltr** [comment] 2024-06-19 10:59
I had the same issue, however explicitly adding "@strapi/email" didn't fix it. It's due to the fact that my project is a monorepo, where strapi is an [NPM workspace](https://docs.npmjs.com/cli/v10/using-npm/workspaces).

NPM workspaces work with a single `node_modules`, located at the root of the project:
- `/package.json` → `{"workspaces": ["strapi"]}`
- `/package-lock.json`
- `/node_modules`
- `/strapi/package.json`

So it looks like the way these dependencies are loaded could be improved.

I hope this helps

**Comment by anubhavranjan** [comment] 2024-07-24 10:46
I am facing a similar issue.

`Error: Cannot find module '@strapi\email\package.json'`

- Using TS
- Using PostgreSQL
- Node v20.10.0
- npm v10.8.2

Running `npm ls @strapi/email` yields

4wd-strapi@0.1.0 D:\strapi-test
└─┬ @strapi/strapi@5.0.0-rc.6
  └── @strapi/email@5.0.0-rc.6

**Comment by anubhavranjan** [comment] 2024-07-24 10:53
For me it got resolved, after running the command `npm install @strapi/email@rc`

**Comment by alexandrebodin** [comment] 2024-07-25 09:25
Hi all 👋  

We just opened a PR with a tentative bug fix. 

Can you try the experiemntal `0.0.0-experimental.f31889311d753b5f7d95198ae84d8fce1d156cd6` version and see if it solves your issues 🙏

**Comment by alexandrebodin** [comment] 2024-07-26 08:09
@rbjs @anubhavranjan @mickaeltr @mirkonasato Would you be able to test this version in the upcoming days ?

**Comment by mirkonasato** [comment] 2024-07-26 16:21
@alexandrebodin yes it works fine for me

```
% node -v
v20.16.0
% npm -v
10.8.2
% npx create-strapi-app@0.0.0-experimental.f31889311d753b5f7d95198ae84d8fce1d156cd6 --quickstart --use-npm strapi-app
...
info: Strapi started successfully
```

**Comment by nlundquist** [comment] 2024-08-06 19:21
I am getting the very similar "Error: @strapi/email/package.json couldn't be resolved." when trying to use Strapi 5 RC8 in an NPM-based monorepo. Using Strapi 5 RC3 I don't experience any issue.

**Comment by samuelsson** [comment] 2024-08-07 17:12
> I am getting the very similar "Error: @strapi/email/package.json couldn't be resolved." when trying to use Strapi 5 RC8 in an NPM-based monorepo. Using Strapi 5 RC3 I don't experience any issue.
> 
> Edit: Confirmed the last version that works for me was Strapi 5.0 RC6. Everything thereafter gives the @strapi/email resolution error.

I'm getting the same in RC9. If I install the email package with `npm install @strapi/email@rc`, Strapi runs perfectly fine after that.

**Comment by me-gusta** [comment] 2024-09-19 10:38
Just got this error — `npm install @strapi/email@rc` easy fixed

**Comment by alexandrebodin** [comment] 2024-09-19 11:59
Hey @me-gusta did this happen with the newly release 5.0.0 or an rc version ?

**Comment by DonikaV** [comment] 2024-09-19 14:19
Happening now after update from version 4 to 5

**Comment by alexandrebodin** [comment] 2024-09-19 14:52
Are you using any specific email providers ?

**Comment by dzakki** [comment] 2024-09-24 04:37
> Happening now after update from version 4 to 5

how did you solve this issue @DonikaV ?

**Comment by mmb-michaelrazmgah** [comment] 2024-09-26 06:43
Happened to me as well with Strapi 5.0.1, managed to get passed it by installing it manually
`npm install @strapi/email`

**Comment by michaelrazmgah** [comment] 2024-09-26 06:45
Happened to me as well when upgrading to Strapi 5. I managed to solve it by installing it manually:
`npm install @strapi/email`

**Comment by Convly** [comment] 2024-09-26 08:39
Hey everyone, I've been trying to reproduce the issue to see how we could deliver a fix, but I can't figure out a way to make it fail.

Could someone having this issue provide me with reproducible steps (including version of npm/pnpm/node + the actual setup, ideally the command line used to create a project that fails)

That would be greatly appreciated, thanks!

**Comment by mmb-michaelrazmgah** [comment] 2024-09-26 08:52
> Could someone having this issue provide me with reproducible steps (including version of npm/pnpm/node + the actual setup, ideally the command line used to create a project that fails)

I tried it just now with a fresh and empty postgres DB and had the same results. Upgrading from 4.24.4 using `npx @strapi/upgrade major`

Using npm.

node version v20.12.2, npm version 10.5.0

**Comment by Convly** [comment] 2024-09-26 09:03
Hey, thanks for the quick reply, here's what I've tried

```
$ node -v
v20.12.2

$ npm -v
10.5.0
```

1. `npx create-strapi-app@4.24.4 app`
2. `cd app`
3. `npm run develop` :heavy_check_mark: 
4. `npx @strapi/upgrade minor`
5. `npx @strapi/upgrade major`
6. `npm run develop` :heavy_check_mark: 
 
Everything worked on my side.

Not sure what other configuration could cause everything to fail :thinking:

**Comment by michaelrazmgah** [comment] 2024-09-26 09:13
> Hey, thanks for the quick reply, here's what I've tried
> 
> ```
> $ node -v
> v20.12.2
> 
> $ npm -v
> 10.5.0
> ```
> 
> 1. `npx create-strapi-app@4.24.4 app`
> 2. `cd app`
> 3. `npm run develop` ✔️
> 4. `npx @strapi/upgrade minor`
> 5. `npx @strapi/upgrade major`
> 6. `npm run develop` ✔️
> 
> Everything worked on my side.
> 
> Not sure what other configuration could cause everything to fail 🤔

Here is my exact error, if that helps
```
[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                  │
│   Error: @strapi/email/package.json couldn't be resolved                                                                                         │
│       at toDetailedDeclaration (/Users/michael/code/strapi-cms/node_modules/@strapi/core/dist/loaders/plugins/get-enabled-plugins.js:65:17)      │
│       at Module.getEnabledPlugins (/Users/michael/code/strapi-cms/node_modules/@strapi/core/dist/loaders/plugins/get-enabled-plugins.js:83:10)   │
│       at loadPlugins (/Users/michael/code/strapi-cms/node_modules/@strapi/core/dist/loaders/plugins/index.js:96:50)                              │
│       at Module.loadApplicationContext (/Users/michael/code/strapi-cms/node_modules/@strapi/core/dist/loaders/index.js:16:5)                     │
│       at Object.register (/Users/michael/code/strapi-cms/node_modules/@strapi/core/dist/providers/registries.js:26:17)                           │
│       at Strapi.register (/Users/michael/code/strapi-cms/node_modules/@strapi/core/dist/Strapi.js:322:32)                                        │
│       at Strapi.load (/Users/michael/code/strapi-cms/node_modules/@strapi/core/dist/Strapi.js:314:16)                                            │
│       at Module.develop (/Users/michael/code/strapi-cms/node_modules/@strapi/strapi/dist/node/develop.js:177:41)                                 │
│       at async action (/Users/michael/code/strapi-cms/node_modules/@strapi/strapi/dist/cli/commands/develop.js:18:5)                             │
│       at async Command.parseAsync (/Users/michael/code/strapi-cms/node_modules/commander/lib/command.js:923:5)                                   │
│                                                                                                                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

**Comment by Convly** [comment] 2024-09-26 09:16
Could you run 
`npm config ls -l | grep "install-strategy"`
in your project, and share the result here?

**Comment by michaelrazmgah** [comment] 2024-09-26 09:54
> npm config ls -l | grep "install-strategy"

`install-strategy = "hoisted" `

I get this error when I try to run `npm run develop`.

I even tried following your steps, but I get the following issue:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: strapi-4@0.1.0
npm ERR! Found: @strapi/plugin-cloud@4.25.12
npm ERR! node_modules/@strapi/plugin-cloud
npm ERR!   @strapi/plugin-cloud@"5.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @strapi/plugin-cloud@"5.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @strapi/strapi@5.0.0
npm ERR! node_modules/@strapi/strapi
npm ERR!   peer @strapi/strapi@"^5.0.0 || ^5.0.0-beta || ^5.0.0-alpha || ^5.0.0-rc" from @strapi/plugin-cloud@5.0.0
npm ERR!   node_modules/@strapi/plugin-cloud
npm ERR!     @strapi/plugin-cloud@"5.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/michael/.npm/_logs/2024-09-26T09_50_52_479Z-eresolve-report.txt
```

I had to do the following steps:

npx create-strapi-app@4.24.4 app
cd app
npm run develop ✔️
npx @strapi/upgrade minor
npx @strapi/upgrade major
rm -rf node_modules/
rm package-lock.json
npm install
npm run develop ✔️

And the outcome is the same:

`[ERROR]  There seems to be an unexpected error, try again with --debug for more information 

┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                                                         │
│   Error: @strapi/email/package.json couldn't be resolved                                                                                                │
│       at toDetailedDeclaration (/Users/michael/code/next-app/strapi-4/node_modules/@strapi/core/dist/loaders/plugins/get-enabled-plugins.js:65:17)      │
│       at Module.getEnabledPlugins (/Users/michael/code/next-app/strapi-4/node_modules/@strapi/core/dist/loaders/plugins/get-enabled-plugins.js:83:10)   │
│       at loadPlugins (/Users/michael/code/next-app/strapi-4/node_modules/@strapi/core/dist/loaders/plugins/index.js:96:50)                              │
│       at Module.loadApplicationContext (/Users/michael/code/next-app/strapi-4/node_modules/@strapi/core/dist/loaders/index.js:16:5)                     │
│       at Object.register (/Users/michael/code/next-app/strapi-4/node_modules/@strapi/core/dist/providers/registries.js:26:17)                           │
│       at Strapi.register (/Users/michael/code/next-app/strapi-4/node_modules/@strapi/core/dist/Strapi.js:322:32)                                        │
│       at Strapi.load (/Users/michael/code/next-app/strapi-4/node_modules/@strapi/core/dist/Strapi.js:314:16)                                            │
│       at Module.develop (/Users/michael/code/next-app/strapi-4/node_modules/@strapi/strapi/dist/node/develop.js:177:41)                                 │
│       at async action (/Users/michael/code/next-app/strapi-4/node_modules/@strapi/strapi/dist/cli/commands/develop.js:18:5)                             │
│       at async Command.parseAsync (/Users/michael/code/next-app/strapi-4/node_modules/commander/lib/command.js:923:5)                                   │
│                                                                                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘`

**Comment by Ridys** [comment] 2024-09-26 10:11
I'm facing the same error after upgrading to 5.0.1 from 4.25.12.

My actions:
1. npx @strapi/upgrade major
On updating dependencies the script failed with a version incompatibility error.
2. Manually deleted node_modules and package-lock.json.
3. npm install
Installation completed, but with a warning:
```
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: msw@1.3.0
npm warn Found: typescript@5.3.2
npm warn node_modules/typescript
npm warn   peerOptional typescript@"^4.7 || 5" from @formatjs/intl@2.10.0
npm warn   node_modules/@formatjs/intl
npm warn     @formatjs/intl@"2.10.0" from react-intl@6.6.2
npm warn     node_modules/react-intl
npm warn   7 more (@strapi/admin, @strapi/strapi, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peerOptional typescript@">= 4.4.x <= 5.2.x" from msw@1.3.0
npm warn node_modules/@strapi/admin/node_modules/msw
npm warn   node_modules/@strapi/admin
npm warn
npm warn Conflicting peer dependency: typescript@5.2.2
npm warn node_modules/typescript
npm warn   peerOptional typescript@">= 4.4.x <= 5.2.x" from msw@1.3.0
npm warn   node_modules/@strapi/admin/node_modules/msw
npm warn     msw@"1.3.0" from @strapi/admin@5.0.0
npm warn     node_modules/@strapi/admin
```
4. npx @strapi/upgrade minor
Successful, but with the same warning from step 3.
6. npm run develop
`Error: @strapi\email\package.json couldn't be resolved `

Manual installation of the package helped: `npm install @strapi/email`

`install-strategy = "hoisted"`
Windows, node v20.11.0, npm 10.8.3

**Comment by limonte** [comment] 2024-09-26 20:40
Same in Strapi Cloud:

![CleanShot 2024-09-26 at 23 39 32@2x](https://github.com/user-attachments/assets/84b8069b-82a5-4dc4-b978-b3895a6abf3e)

**Comment by dziamid** [comment] 2024-09-28 07:28
For me, `npx create-strapi-app@latest strapi-example` worked w/o issues. However, when i moved it into a turborepo, i got this error as well.

Steps to reproduce:
1. `git clone https://github.com/dziamid/turbo-strapi`
2. `npm run build`
3. `npm run dev`

Actual result: all packages build except strapi, strapi fails with:

<img width="1242" alt="image" src="https://github.com/user-attachments/assets/82e1164b-a8ba-46d1-964c-b3493022598c">

**Comment by V-Shadbolt** [comment] 2024-09-30 04:13
I'm running into the same issue with my automated Docker builds. Starting a clean Strapi project on 5.0.0 and attempting to update to 5.0.1 throws the `@strapi\email\package.json couldn't be resolved` error.  

Here is the [testing section](https://github.com/V-Shadbolt/docker-strapi/blob/86769919516965932ea723e4c5b448ce5e0d80fa/.github/workflows/publish-docker-images.yml#L40) of my workflow that builds and deploys a clean 5.0.0 project before attempting to update to latest. 
<img width="1022" alt="Screenshot 2024-09-29 at 9 05 04 PM" src="https://github.com/user-attachments/assets/78879e5a-14d3-4fa2-bea5-3b1e04816c56">

**Comment by Convly** [comment] 2024-09-30 08:09
Thanks for all your answers, greatly appreciated, I'll investigate the repos this week!

**Comment by derrickmehaffy** [comment] 2024-09-30 22:01
Related issue but for @strapi/plugin-cloud rather than the email package: https://github.com/strapi/strapi/issues/21462

**Comment by Convly** [comment] 2024-10-02 09:33
I've been able to reproduce the issue thanks to the projects you've sent. Thanks!

I'll now work on a fix, and will keep you posted if I make any progress.

**Comment by Convly** [comment] 2024-10-02 12:33
Hey there, me again :wave: 
I've opened a PR to fix the issue (#21557).
To make sure it works for everyone, I've released an experimental version:
`0.0.0-experimental.0e316dc69ac15cab63af4c7f91191d12fc2bbc27`

It works on my side, but if some of you can validate it also fixes the issue on your side, then we'll be able to merge and release it.

**Comment by limonte** [comment] 2024-10-03 06:51
@Convly how to scaffold a new project from this experimental release?

**Comment by limonte** [comment] 2024-10-03 10:04
nope, that's not working

![CleanShot 2024-10-03 at 13 03 39@2x](https://github.com/user-attachments/assets/80ebc239-ca0d-4aeb-af17-60dd0a9f4fcd)

**Comment by limonte** [comment] 2024-10-03 10:05
just ship that as a normal release, I mean v5 is already broken and you can't break it more 😆

**Comment by Convly** [comment] 2024-10-03 10:38
Oh right, you were testing on the cloud. Not sure how it reacts to experimentals :thinking: 
The issue seems to be with the strapi/strapi dependency (not matching v5-ish) rather than the email plugin.

If someone else can test it with a local project, that would be great.

The fix won't be release until next Wednesday anyway (when we do our releases)

**Comment by LucaNerlich** [comment] 2024-10-04 08:17
This happend to me directly after I ran `npm install --workspaces` and then `npm run dev --workspaces` from the parent package.json of my strapi project. Strapi ran fine, without using workspaces, but is broken since trying workspaces once. Strapi does not start, even without workspaces now :/

Strapi 5.0.2. Happens on Windows and MacOS. Node 20.15

**Comment by Convly** [comment] 2024-10-04 08:42
@LucaNerlich Did you try the experimental version with the potential fix?

**Comment by LucaNerlich** [comment] 2024-10-04 08:46
@Convly I can confirm that the experimental version fixes the problem in an npm-workspaces setup

![image](https://github.com/user-attachments/assets/a9ec28ab-e28d-4637-9355-b309e373d18c)

Thanks a lot!

**Comment by Convly** [comment] 2024-10-04 09:02
Glad to hear that, thanks for the confirmation!

**Closed** 2024-10-04 09:03 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:strapi, version: 5

**Comment by Hristijan95** [comment] 2024-10-04 13:05
> Hey there, me again 👋 I've opened a PR to fix the issue (#21557). To make sure it works for everyone, I've released an experimental version: `0.0.0-experimental.0e316dc69ac15cab63af4c7f91191d12fc2bbc27`
> 
> It works on my side, but if some of you can validate it also fixes the issue on your side, then we'll be able to merge and release it.

Fixed the issue for me as well.

**Comment by jhonnyesquivel** [comment] 2024-10-05 19:16
> Hey there, me again 👋 I've opened a PR to fix the issue (#21557). To make sure it works for everyone, I've released an experimental version: `0.0.0-experimental.0e316dc69ac15cab63af4c7f91191d12fc2bbc27`
> 
> It works on my side, but if some of you can validate it also fixes the issue on your side, then we'll be able to merge and release it.

I just faced this issue today and already solved it with this, Thanks

**Comment by varloc2000** [comment] 2024-10-06 10:24
> ### Brand New App
> ```shell
> npx create-strapi@0.0.0-experimental.0e316dc69ac15cab63af4c7f91191d12fc2bbc27 my-app [options]
> ```
> 
> ### Existing App
> #### Manually
> * Go to your project `package.json`
> * Update every `@strapi/` dependencies with `0.0.0-experimental.0e316dc69ac15cab63af4c7f91191d12fc2bbc27`
> * `npm/yarn/pnpm install`
> 
> #### Upgrade Tool
> ```shell
> npx @strapi/upgrade to 0.0.0-experimental.0e316dc69ac15cab63af4c7f91191d12fc2bbc27 -d
> ```

@Convly is that fully valid suggestion?
Project created by default will have such @strapi dependencies as 
"@strapi/plugin-cloud": "5.0.2",
"@strapi/plugin-users-permissions": "5.0.2",

Ann setting `0.0.0-experimental.0e316dc69ac15cab63af4c7f91191d12fc2bbc27` to all as you suggested gives errors 

I could proceed only by setting 0.0.0 eperimental for @strapi/strapi 
With lots of warning

----

Also I see solution was merged to develop 
Is there any better way to resolve issue then putting experimental version to package.json? I don't see any tag was created after PR was merged. Does it mean there is no patch version that includes that fix?

![image](https://github.com/user-attachments/assets/c846376e-b5ed-41fc-b62f-aeb78f12e1ba)

**Comment by varloc2000** [comment] 2024-10-06 10:52
Figured out that npm does not tolerate experimental version `0.0.0-experimental.0e316dc69ac15cab63af4c7f91191d12fc2bbc27`
While yarn install will do the job with no errors.

**Comment by Convly** [comment] 2024-10-07 08:48
Creating a new app using

> `npx create-strapi@0.0.0-experimental.0e316dc69ac15cab63af4c7f91191d12fc2bbc27 my-app [options]`

is working for me. Maybe something in your `npm` version or configuration?

![image](https://github.com/user-attachments/assets/0ffb5333-e957-445e-93f9-98df0e447eb4)


Regarding a patch version, as stated in a previous comment, we do a weekly release on Wednesday. 

> The fix won't be released until next Wednesday anyway (when we do our releases)

Thus, the fix will be available in two days from now (`v5.0.3`) :slightly_smiling_face: 

> Is there any better way to resolve issue then putting experimental version to package.json?

Experimental versions (for Strapi) are used to share new fixes, ideas or improvements to users. They should never be used in production. To resolve the issue, I'm afraid we'll have to wait for Wednesday and the new official release.

**Comment by derrickmehaffy** [comment] 2024-10-07 15:30
> Thus, the fix will be available in two days from now (v5.0.3) 🙂

Correction as we issued a hotfix today it'll be in v5.0.4 this wednesday

**Comment by michielswaanen** [comment] 2024-10-09 09:43
@derrickmehaffy Any timings on when this update will be released today?

**Comment by sarunluitel** [comment] 2024-10-09 11:26
looking forward to this fix

**Comment by Hristijan95** [comment] 2024-10-09 21:05
All good now after upgrading to 5.0.4.

**Comment by pandeyprafull** [comment] 2024-10-14 06:23
still facing the same issue...

**Comment by pandeyprafull** [comment] 2024-10-14 06:33
@Hristijan95 Do we need to upgrade  only `@strapi/strapi` to 5.0.4 or all the package starts with `@strapi/**`    ?
