### ISSUE TITLE
Can't connect to a postgres but no issues with sqlite

### ISSUE THREAD

**Issue by nmaxcom** [strapi/strapi#3553] opened 2019-07-02 04:18 UTC
**Describe the bug**
I have a working postgreSQL in AWS RDS working flawlessly (I checked with an SQL client from the same laptop I'm using with strapi). From clean, I run `strapi new pgsql` and give the wizard all the data its asking I get:

```
[...]
? Password: ********************
? Enable SSL connection: false

⏳ Testing database connection...
It might take a minute, please have a coffee ☕️

The app has been connected to the database successfully!
🏗  Application generation:
✔ Copying files ...
✔ Installing dependencies ...

👌 Your application was created at /Users/merl/STUFF/Code/Todo VAC/webVac.

⚡️ Change directory:
$ cd webVac

⚡️ Start your application:
$ strapi develop
```

Ok, from within the folder I run `strapi develop`:

```
merl /Users/merl/STUFF/Code/Todo VAC/webVaC $ strapi develop                                                                                                                 ● [04:04:56]
Building your admin UI with development configuration ...

✔ Webpack
  Compiled successfully in 1.05m

[2019-07-02T02:06:21.357Z] error Impossible to use the `default` connection...
[2019-07-02T02:06:21.357Z] warn Be sure that your client `default` are in the same node_modules directory
[2019-07-02T02:06:21.358Z] error Error: Tarn: unsupported option opt.afterCreate
    at new Pool (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/tarn/lib/Pool.js:63:23)
    at Client_PG.initializePool (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/strapi-hook-knex/node_modules/knex/lib/client.js:320:17)
    at Client_PG.Client (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/strapi-hook-knex/node_modules/knex/lib/client.js:87:12)
    at new Client_PG (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/strapi-hook-knex/node_modules/knex/lib/dialects/postgres/index.js:31:19)
    at Knex (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/strapi-hook-knex/node_modules/knex/lib/knex.js:57:42)
    at _.forEach (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/strapi-hook-knex/lib/index.js:178:45)
    at /Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/lodash/lodash.js:4911:15
    at baseForOwn (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/lodash/lodash.js:2996:24)
    at /Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/lodash/lodash.js:4880:18
    at Function.forEach (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/lodash/lodash.js:9344:14)
    at Function.initialize (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/strapi-hook-knex/lib/index.js:49:9)
    at /Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/strapi/lib/hooks/index.js:52:31
    at Promise (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/strapi/lib/hooks/index.js:149:37)
    at new Promise (<anonymous>)
    at Promise.all.Object.keys.map.hook (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/strapi/lib/hooks/index.js:75:9)
    at Array.map (<anonymous>)
    at Strapi.module.exports (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/strapi/lib/hooks/index.js:73:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
merl /Users/merl/STUFF/Code/Todo VAC/webVaC $ ..
```
But, while troubleshooting I tried this in a new directory `strapi new test --quickstart` which by default uses sqlite:

```
merl /Users/merl/STUFF/Code/Todo VAC $ strapi new test --quickstart                                                                                                            [04:15:20]
🚀 Creating your Strapi application.


✅ Connected to the database
🏗  Application generation:
✔ Copying files ...
✔ Installing dependencies ...

[...]

[2019-07-02T02:18:19.563Z] debug GET af7ae505a9eed503f8b8e6982036873e.woff2 (8 ms)
[2019-07-02T02:18:19.564Z] debug GET 33d5f0d956f3fc30bc51f81047a2c47d.woff2 (5 ms)
```

It works perfectly. So I compared the two folders (the one using postgres and this using sqlite) with the only differences being the database.json obviously:

Test
![image](https://user-images.githubusercontent.com/8936090/60479736-24987500-9c87-11e9-9a24-becfcf2d4c1a.png)

Postgres
![image](https://user-images.githubusercontent.com/8936090/60479805-5dd0e500-9c87-11e9-912f-47f0354a18fd.png)

And the dependencies in package.json
![image](https://user-images.githubusercontent.com/8936090/60479871-a8eaf800-9c87-11e9-86bf-ae175e37d531.png)

I tried to change the database.json content in the Test for the postgres data, and installing the pg dependency, but it goes to the same errors.

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: Version: 3.0.0-beta.8, latest at the time of this post
- Database: PostgreSQL 10.6
- Operating system: macOS 10.12

**Comment by alexandrebodin** [comment] 2019-07-02 07:24
Hi this issue is a  duplicate of #3554 where we added some context. I'm closing this one ;)

**Closed by alexandrebodin** 2019-07-02 07:24 UTC
