### ISSUE TITLE
A bug in the realtion field

### ISSUE THREAD

**Issue by Mourad-Ouerghi** [strapi/strapi#17775] opened 2023-08-24 10:52 UTC
### Required System information

- Node.js version: 18.17.1
- NPM version: 9.6.7
- Strapi version: 4.12.6
- Database: postgres
- Operating system: windows
- Is your project Javascript or Typescript: javascript

### Describe the bug

A relation field is saved empty if it doesn't have any value which caused us problems in our frontend

### Steps to reproduce the behavior

1. Create two collection types let's say the first is called "Company" and the second is called "Internship"
2. In our business logic a company could have one to many internships
3. Create a relation field called "company" in the collection type "Internship"  
4. Create one or two companies using the "Company" collection type
5. Go back to the "Internship" collection type and try not to choose any of the companies created previously in the company field
6. You'll see that you can type text in it, try typing some text and then save
7. A banner of "Internal server error" appears but the internship is created eventually

### Expected behavior

In our case that Internship shouldn't be created because every internship should have a company related to it

### Screenshots

1. First of all here is how the relation is created 
![image](https://github.com/strapi/strapi/assets/86426480/70c19e01-c806-44eb-846c-62a2e03fd76c)
2. Here is a company created
![image](https://github.com/strapi/strapi/assets/86426480/786af1ef-097a-4760-bf1a-772bacef1aef)
3. Here I'm trying to create an internship
![Capture d’écran (61)](https://github.com/strapi/strapi/assets/86426480/7759dc5a-efcd-4a8b-9f22-a7367aabc2c4)
4. Here you can see the internal server error banner
![Capture d’écran (62)](https://github.com/strapi/strapi/assets/86426480/4ece51d0-23ef-4548-a41b-3a983af34dca)
5. Here you can see that the internship is created but the company field is empty therefore the internhsip object is created with company value as null
![image](https://github.com/strapi/strapi/assets/86426480/4633f781-6f4a-4649-a741-15a0a60a8432)

### Code snippets

Here is the error in the console
```[2023-08-24 11:14:33.085] error: Cannot read properties of undefined (reading 'addOrReplace')
TypeError: Cannot read properties of undefined (reading 'addOrReplace')
    at Object.afterCreate (D:\work\Hi-Interns\strapi-db\src\api\internship\content-types\internship\lifecycles.js:18:7)
    at modelsLifecyclesSubscriber (D:\work\Hi-Interns\strapi-db\node_modules\@strapi\database\lib\lifecycles\subscribers\models-lifecycles.js:15:41)
    at Object.run (D:\work\Hi-Interns\strapi-db\node_modules\@strapi\database\lib\lifecycles\index.js:62:17)
    at Object.create (D:\work\Hi-Interns\strapi-db\node_modules\@strapi\database\lib\entity-manager\index.js:247:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.create (D:\work\Hi-Interns\strapi-db\node_modules\@strapi\strapi\lib\services\entity-service\index.js:154:18)
    at async Object.<anonymous> (D:\work\Hi-Interns\strapi-db\node_modules\@strapi\strapi\lib\services\entity-service\index.js:327:20)
    at async Object.create (D:\work\Hi-Interns\strapi-db\node_modules\@strapi\plugin-content-manager\server\services\entity-manager.js:171:20)
    at async Object.create (D:\work\Hi-Interns\strapi-db\node_modules\@strapi\plugin-content-manager\server\controllers\collection-types.js:83:20)
    at async returnBodyMiddleware (D:\work\Hi-Interns\strapi-db\node_modules\@strapi\strapi\lib\services\server\compose-endpoint.js:52:18)```

**Comment by derrickmehaffy** [comment] 2023-08-25 19:11
Can you please give us the content of this file: `src\api\internship\content-types\internship\lifecycles.js:18:7` as this doesn't look like a bug with our code but something to do with your lifecycles?

**Comment by Mourad-Ouerghi** [comment] 2023-08-28 11:45
Hello in fact the error banner was from the lifecycle.js I figured it out, but the main bug still exists because I can't make the relation field  required so it saved with null value

**Comment by derrickmehaffy** [comment] 2023-08-28 14:09
Closing as duplicate of https://feedback.strapi.io/customization/p/specify-relation-column-as-required

**Closed by derrickmehaffy** 2023-08-28 14:09 UTC
Labels: status: can not reproduce
