### ISSUE TITLE
There is no GraphQL equivalent for GET request i18n/locales

### ISSUE THREAD

**Issue by seleckis** [strapi/strapi#10951] opened 2021-09-13 13:16 UTC
i18n locales are missing in grapql queries. Enabling them for unauthenticated users returns locales using REST API, but not for GraphQL.

### Steps to reproduce the behavior

1. Enable i18n plugin. And add some locales
2. Go to Plugins -> Roles -> Public -> i18n and add checkbox for Locales -> listlocales. Save.
3. Check request to localhost:1337/i18n/locales. List of locales is returned.
4. Check query `{  i18n {  locales  }  }` in localhost:1337/graphql. See error: Cannot query field \"i18n\" on type \"Query\".

### Expected behavior

I expect to get the same result as for REST API. List of locales should be returned.

### System

- Node.js version: 16.5.0
- NPM version: 7.19.1
- Strapi version: 3.6.8
- Database: SQLite
- Operating system: MacOS

**Comment by kasonde** [comment] 2021-09-13 13:32
Hi @seleckis you can remedy this by extending the i18n plugin. Create a new file called `schema.graphql.js` in the `./extensions/i18n/config` folder (Create if it doesn't exist). And paste the code below:
```javascript
module.exports = {
  definition: ``,
  query: ``,
  type: {},
  resolver: {
    Query: {
      locales: {
        resolver: "plugins::i18n.locales.listLocales",
      },
    },
  },
};

```

**Comment by seleckis** [comment] 2021-09-13 13:53
@kasonde Thank you for the answer. Why you think this should be extended but not available right from the box? For example `locale` and `localizations` fields are available without extending i18n plugin as [described in docs](https://strapi.io/documentation/developer-docs/latest/development/plugins/i18n.html#usage-with-the-graphql-plugin).

**Comment by kasonde** [comment] 2021-09-13 14:09
I don't actually think it should be extended. I believe your question is stemming from the fact that the issue was closed is a mis-click on my part. The tags however do place it under a potential enhancement for the future.

**Comment by seleckis** [comment] 2021-09-13 14:14
Alright, makes sense

**Comment by derrickmehaffy** [comment] 2021-09-13 17:34
The reason it doesn't exist now is this endpoint was not intended for normal end-user consumption but we modified that the last minute to make the API available for the end-users (it used to have a policy that restricted it to the admin only) and we don't expose admin endpoints over GraphQL at all.

**Comment by seleckis** [comment] 2021-09-16 18:54
So you plan to disable it also in REST API? What is a main method to fetch all locales to create a language switcher in this case?

**Comment by derrickmehaffy** [comment] 2021-09-16 21:21
> So you plan to disable it also in REST API? What is a main method to fetch all locales to create a language switcher in this case?

No, in the v4 this will be one of the "exceptions to the rule" as we are isolating the admin APIs from the content (aka end-user) APIs. So the REST form will still exist, I don't know if we were planning to add the same option to GraphQL or not.

CC @Convly is this on your radar?

**Comment by Convly** [comment] 2021-09-17 04:51
Hello there :wave: 
This isn't currently implemented for GraphQL V4 but IMO it would make sense to add it, mainly to add consistency with the REST API.

**Comment by Convly** [comment] 2021-09-17 05:02
Hello :wave: 
The I18N `locales` queries have been enabled for GraphQL V4 (find one & find many)

**Comment by derrickmehaffy** [comment] 2021-11-30 14:20
Fixed in v4, marking as closed

**Closed by derrickmehaffy** 2021-11-30 14:20 UTC
Labels: type: enhancement, severity: low, source: plugin:i18n

**Comment by Convly** [comment] 2021-11-30 15:24
> Fixed in v4, marking as closed

:arrow_down: To query all the locales as of V4 :arrow_down: 

```graphql
query {
  i18NLocales {
    data {
      id
      attributes {
        name
        code
      }
    }
  }
}
```

**Comment by andrea-mono** [comment] 2022-06-28 16:08
@Convly i'm currently using V4 but i can't get the locales list. I've set the permission but the query returns forbidden access

**Comment by kevinjmo** [comment] 2022-06-28 21:19
> @Convly i'm currently using V4 but i can't get the locales list. I've set the permission but the query returns forbidden access

I’m in the same boat as @andrea-mono (but fetching via API instead of GraphQL).

When querying for `/api/i18n/locales` as an Authenticated User (with API token set in `headers.Authorization`), it still returns a 403 Forbidden. All other routes that require authentication are returning 200.

I found that when allowing the `listLocales` actions in the Public unauthenticated route (and not setting any `headers.Authorization`), it returns the list of locales properly.

I have a meeting tomorrow morning with @quentin-js where I will bring this up. Still figured to mention it here so that someone on the team (maybe @derrickmehaffy) can also take a look.

**Comment by derrickmehaffy** [comment] 2022-06-28 22:39
> > @Convly i'm currently using V4 but i can't get the locales list. I've set the permission but the query returns forbidden access
> 
> I’m in the same boat as @andrea-mono (but fetching via API instead of GraphQL).
> 
> When querying for `/api/i18n/locales` as an Authenticated User (with API token set in `headers.Authorization`), it still returns a 403 Forbidden. All other routes that require authentication are returning 200.
> 
> I found that when allowing the `listLocales` actions in the Public unauthenticated route (and not setting any `headers.Authorization`), it returns the list of locales properly.
> 
> I have a meeting tomorrow morning with @quentin-js where I will bring this up. Still figured to mention it here so that someone on the team (maybe @derrickmehaffy) can also take a look.

Thanks for this, given the age of this issue could you open up a new issue for v4 with some reproduction steps/examples and maybe a quick loom video showing your permission setup?

Thanks.

**Comment by kevinjmo** [comment] 2022-06-29 01:12
> could you open up a new issue for v4 with some reproduction steps/examples and maybe a quick loom video showing your permission setup?

Thank you for the response and taking the time to look into this, @derrickmehaffy!

Here’s a quick screencast demonstrating the GET requests for a Test collection type and for `listLocales`. You can see that in the admin panel, both are checked (and this is under the Authenticated Role). And when making the request with the API token, getting all the `tests` work while getting the locales return a 403.

![Screen Recording 2022-06-28 at 18 05 10](https://user-images.githubusercontent.com/9851651/176329474-f7a8f3c8-dbf0-4e06-95d1-7c4e293330ad.gif)

However, it seems to work when we enable it in the Public role as an unauthenticated user. Here you’ll see that I enabled the find actions for Tests and i18n locales and they both return 200.

![Screen Recording 2022-06-28 at 18 08 31](https://user-images.githubusercontent.com/9851651/176329748-3191fb4e-eb2a-43f2-b312-64fb47092bee.gif)

Hope that helps. Let me know what other information you may need.

**Comment by derrickmehaffy** [comment] 2022-06-29 14:34
> > could you open up a new issue for v4 with some reproduction steps/examples and maybe a quick loom video showing your permission setup?
> 
> Thank you for the response and taking the time to look into this, @derrickmehaffy!
> 
> Here’s a quick screencast demonstrating the GET requests for a Test collection type and for `listLocales`. You can see that in the admin panel, both are checked (and this is under the Authenticated Role). And when making the request with the API token, getting all the `tests` work while getting the locales return a 403.
> 
> ![Screen Recording 2022-06-28 at 18 05 10](https://user-images.githubusercontent.com/9851651/176329474-f7a8f3c8-dbf0-4e06-95d1-7c4e293330ad.gif) [ ](https://user-images.githubusercontent.com/9851651/176329474-f7a8f3c8-dbf0-4e06-95d1-7c4e293330ad.gif) ![Screen Recording 2022-06-28 at 18 05 10](https://user-images.githubusercontent.com/9851651/176329474-f7a8f3c8-dbf0-4e06-95d1-7c4e293330ad.gif) [ ](https://user-images.githubusercontent.com/9851651/176329474-f7a8f3c8-dbf0-4e06-95d1-7c4e293330ad.gif)
> 
> However, it seems to work when we enable it in the Public role as an unauthenticated user. Here you’ll see that I enabled the find actions for Tests and i18n locales and they both return 200.
> 
> ![Screen Recording 2022-06-28 at 18 08 31](https://user-images.githubusercontent.com/9851651/176329748-3191fb4e-eb2a-43f2-b312-64fb47092bee.gif) [ ](https://user-images.githubusercontent.com/9851651/176329748-3191fb4e-eb2a-43f2-b312-64fb47092bee.gif) ![Screen Recording 2022-06-28 at 18 08 31](https://user-images.githubusercontent.com/9851651/176329748-3191fb4e-eb2a-43f2-b312-64fb47092bee.gif) [ ](https://user-images.githubusercontent.com/9851651/176329748-3191fb4e-eb2a-43f2-b312-64fb47092bee.gif)
> 
> Hope that helps. Let me know what other information you may need.

Can you actually create a new issue on GitHub so we don't have to reopen a very old issue that is largely unrelated to this problem (this original issue was created for v3 not v4)

Thanks!
