### ISSUE TITLE
Google provider error

### ISSUE THREAD

**Issue by wi4er** [strapi/strapi#1132] opened 2018-05-06 14:13 UTC
**Informations**
- **Node.js version**: 9.11
- **npm version**: 5.6
- **Strapi version**: 3.0.0-alpha.12.1.2
- **Database**: mongodb
- **Operating system**: ubuntu 16.04

**What is the current behavior?**
When I am trying to set auth provider for google, I have completed all steps. But in last step I getting this error in back end:

**error undefined is not a function**

and in front end:

**{"message":"An internal server error occurred","statusCode":500,"error":"Internal Server Error"}**

on the http://localhost:1337/auth/google/callback page.
Google side works correct.

**Steps to reproduce the problem**
 - install strapi
- populate google provider settings
- enter localhost:1337/connect/google/ page
- execute google side
- getting error

**What is the expected behavior?**
getting token in last step

**Suggested solutions**

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by lauriejim** [comment] 2018-05-11 09:41
Hello @, thank you for reporting this issue. We won’t undertake this development because our focus is currently on another feature. Since time is lacking on our side, feel free to submit a PR, we’ll be glad to count you as one of our contributors! 
Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by soupette** [comment] 2018-06-11 13:59
Hi @wi4er I  tried to reproduce your issue but it's working fine on my side, I'm using the [`strapi-sdk-javascript`](https://github.com/strapi/strapi-sdk-javascript).

**Comment by soupette** [comment] 2018-06-20 07:54
I'm closing the issue, here's the [documentation](https://github.com/strapi/strapi-examples/tree/master/login-react) on how to use custom providers.

**Closed by soupette** 2018-06-20 07:54 UTC
Labels: priority: medium, type: bug 🐛

**Comment by tatraijozsef** [comment] 2018-12-14 16:04
Despite this issue status, I'd like to add, that the sitation is still the same, as @wi4er stated earlier. There is no difficulty to reprduce the sitation: clean alpha strapi install with one admin user, enable Google provider and so, as @wi4er wrote it. No programming or React-magic needed...

It is frustrating situation, when there is a feature, which should work some way, but when you start to use it, you just end up with undocumented errors... I know, strapi is only at apha stage, but not everybody is a full/time programmer, who wants to use strapi.

The [strapi documentation](https://strapi.io/documentation/1.x.x/users.html#providers) states:

> Redirect your user to: GET /connect/:provider.
> After their approval, they will be redirected to /auth/:provider/callback. The jwt and user will be available in the querystring.
> 

Well, this is not the situation at the moment with the packed in Google provider.

**Comment by dggodfrey** [comment] 2018-12-17 23:45
I am on the latest version of strapi (alpha-16) and google auth works great! I did get this issue for a while (hence how I found this page when searching google for help). I quickly realized, I created the id and secret and didn't actually enable the service on the google side. So, @efezus make sure you have enabled the google service. Creating the client secret isn't enough. You can view the google service status at this url, just select your app: https://console.developers.google.com/apis/api/plus.googleapis.com/overview

Hopefully this helps and you get your auth working!
