### ISSUE TITLE
graphql exception on quering  by nested document's 

### ISSUE THREAD

**Issue by s4n** [strapi/strapi#7806] opened 2020-09-09 00:02 UTC
**Describe the bug**
Exception being thrown when querying nested documents with relationship "X has many Y"

**Steps to reproduce the behavior**
 The following is the Query when running using http://localhost:1337/graphql throws exception
```
query Type! {
 TypeA (id:1) {
    TypeB{
       TypeC{
         field1
      }    
    }
  }
}
```
**Content Type Structure**
_TypeA_
```
  field1: text
  field2: Relation with TypeB (TypeA has many TypeB)
```
_TypeB_
```
 field1: text
 field2: Relation with Type C(TypeB has many TypeC)
 field3: Relation with Type D(TypeB has many TypceD)
```
_TypeC_
```
 field1: text
 field2: text
```
_TypeD_
```
 field1: text
```
**Error and Stack Trace**
```
"errors": [
    {
      "message": "Your filters contain a field 'undefined' that doesn't appear on your model definition nor it's relations",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
```
```
"Error: Your filters contain a field 'undefined' that doesn't appear on your model definition nor it's relations",
            "    at getAssociationFromFieldKey (/dev/node_modules/strapi-utils/lib/build-query.js:35:19)",
            "    at /dev/node_modules/strapi-utils/lib/build-query.js:117:48",
            "    at Array.map (<anonymous>)",
            "    at normalizeClauses (/dev/node_modules/strapi-utils/lib/build-query.js:108:6)",
            "    at buildQuery (/dev/node_modules/strapi-utils/lib/build-query.js:152:21)",
            "    at Object.find (/dev/node_modules/strapi-connector-bookshelf/lib/queries.js:61:14)",
            "    at fn (/dev/node_modules/strapi-database/lib/queries/helpers.js:31:54)",
            "    at Object.find (/dev/node_modules/strapi-database/lib/queries/helpers.js:15:24)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
```
**System**

- Node.js version: v14.8.0
- NPM version: 6.14.7
- Strapi version: Strapi v3.1.4
- Database: MySQL 8.0.21
- Operating system: Mac OS v10.15

**Workaround (not ideal)**
Changing the relationship from "_X has many Y_ " to "_X belongs to many Y_ " in Content Type "TypeB" structure for the referenced field in query fixes the issue.

**Similar tickets - Closed**
[4353](https://github.com/strapi/strapi/issues/4353)
[5355](https://github.com/strapi/strapi/issues/5355)

**Comment by jorisw** [comment] 2020-09-15 09:49
I have found that using "X has many Y and X belongs to many Y" also works, meaning you don't have to reverse your associations when using the CMS.

**Comment by derrickmehaffy** [comment] 2020-09-29 14:31
`Node.js version: v14.8.0` Node v14 isn't supported see: https://github.com/strapi/strapi/issues/7921

But on that note I was not able to reproduce the issue using v3.1.6 and node v12.

**Comment by derrickmehaffy** [comment] 2020-10-15 15:39
As we have received no new information, marking as closed

**Closed by derrickmehaffy** 2020-10-15 15:39 UTC
Labels: status: can't reproduce
