### ISSUE TITLE
GraphQL query with where  and variable not work

### ISSUE THREAD

**Issue by maxbaluev** [strapi/strapi#3651] opened 2019-07-19 17:54 UTC
**Describe the bug**

Hardcoded variables work fine

![image](https://user-images.githubusercontent.com/9191176/61555263-6e9b9c00-aa78-11e9-9782-2f14f92974f2.png)
![image](https://user-images.githubusercontent.com/9191176/61555285-7bb88b00-aa78-11e9-84ad-33a434140250.png)

But when i use variable inside code like 

![image](https://user-images.githubusercontent.com/9191176/61555338-968aff80-aa78-11e9-9d8d-5523be27e168.png)

I am always receive all table results not only results with where condition

![image](https://user-images.githubusercontent.com/9191176/61555108-0056d980-aa78-11e9-893f-0a2267aeba94.png)

strapi beta 13

**Comment by derrickmehaffy** [comment] 2019-07-19 18:23
@maxbaluev you have to pass them in query variables:

![image](https://user-images.githubusercontent.com/8593673/61556778-7f67f580-aa17-11e9-87b9-b1baa6f6cfd7.png)

some example code (not entirely sure this works but you get the idea

```
let query = 'query GET_BODIES ($where: JSON){
  bodies (where: $where, limit: 2) {
    bodyName
    system {
      systemName
    }
  }
}'
let variables = { "where": { "system": { "systemName_contains": "syn" } } }

fetch('/graphql', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'Accept': 'application/json',
  },
  body: JSON.stringify({
    query,
    variables
  })
})
```

**Comment by derrickmehaffy** [comment] 2019-07-19 18:23
closing as duplicate of: https://github.com/strapi/strapi/issues/3537

**Closed by derrickmehaffy** 2019-07-19 18:23 UTC
