### ISSUE TITLE
Is it possible to display in content manager list, the field of related model?

### ISSUE THREAD

**Issue by bolotkalil** [strapi/strapi#3236] opened 2019-05-07 17:33 UTC
Is it possible to display in content manager list, the field of related model?
For example:
I have two related models User and Countries, when I edit user entity and choose country then Can I see field(Name of country) in users list?
Is it possible add to "List Behavior" the field of related model?

**Comment by derrickmehaffy** [comment] 2019-05-07 21:16
I am closing this because it is not a bug report nor a feature request.

Also this has already been suggested and is planned: https://portal.productboard.com/strapi/c/49-display-relational-field-in-list-view

There currently is no way to do this, and there is no ETA for this feature yet. For questions please use either:

1) [StackOverflow](http://stackoverflow.com/questions/tagged/strapi)
2) [Slack](http://slack.strapi.io/)

Per the README.md github is only for feature requests and bug reports:
![image](https://user-images.githubusercontent.com/8593673/57333790-ada18e80-70d2-11e9-9fa8-9ccfbe51827e.png)

**Closed by derrickmehaffy** 2019-05-07 21:16 UTC
