### ISSUE TITLE
emailConfirmation graphql mutation does not work as expected

### ISSUE THREAD

**Issue by e23thr** [strapi/strapi#12772] opened 2022-03-08 05:04 UTC
### Describe the bug

graphql mutation (emailConfirmation) does not pass confirmation correctly to auth.emailConfirmation

### Steps to reproduce the behavior

1. Go to register new user with email/password
2. Use the code to call graphql 
```json
{"query":"\n  mutation ($confirmation:String!){\n    emailConfirmation(confirmation: $confirmation) {\n      jwt\n    }\n  }\n  ","variables":{"confirmation":"code-from-email"}}
```
3. See error
```json
{
  "errors": [
    {
      "message": "token.invalid",
      "extensions": {
        "error": {
          "name": "ValidationError",
          "message": "token.invalid",
          "details": {}
        },
        "code": "BAD_USER_INPUT"
      }
    }
  ],
  "data": {
    "emailConfirmation": null
  }
}
```

### Expected behavior

Correct code should be able to return jwt

### System

- Node.js version: 16.13.2
- NPM version: 8.1.2
- Strapi version: 4.1.2
- Database: mysql 5.7
- Operating system: Debian GNU/Linux 10 (buster)

**Comment by derrickmehaffy** [comment] 2022-06-01 18:33
Marking as closed as I believe this was fixed previously, could not reproduce on v4.1.12

**Closed by derrickmehaffy** 2022-06-01 18:33 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: plugin:users-permissions
