### ISSUE TITLE
"ChunkLoadError: Loading chunk 1 failed" in Safari

### ISSUE THREAD

**Issue by b1sh0pe** [strapi/strapi#8647] opened 2020-11-13 13:18 UTC
### Describe the bug

Opening the Edit screen for the model provokes "ChunkLoadError: Loading chunk 1 failed." in Safari.
In other browsers everything works fine. Fails both for production and development builds.

### Steps to reproduce the behavior

1. Open your Safari browser, I checked on version 13.1.1 (14609.2.9.1.3) 
2. Go to your admin panel.
3. Click on any of your models and select "Edit".
4. See error.

### Expected behavior

The chunk should be loading fine in Safari.

### Screenshots

![зображення](https://user-images.githubusercontent.com/20316468/99076069-38662200-25c3-11eb-91e0-11ab3cd5a5c6.png)

### System

- Node.js version: 12.18.4
- NPM version: 6.14.6
- Strapi version: 3.3.2
- Database: PostgreSQL
- Operating system: Ubuntu

**Comment by derrickmehaffy** [comment] 2020-11-16 18:53
@b1sh0pe I'm unable to reproduce, can you provide a link to your project? Most likely this is related to some custom modifications you have done to the admin.

**Comment by b1sh0pe** [comment] 2020-11-17 23:06
@derrickmehaffy I've sent you an invite for the project, will be grateful for your help :)

**Comment by soupette** [comment] 2020-11-18 07:23
@b1sh0pe can you add as well?

**Comment by b1sh0pe** [comment] 2020-11-18 10:06
@soupette Of course, added you as well

**Comment by soupette** [comment] 2020-11-18 10:57
Your app seems to be working normally in development. I am not sure how I can help

**Comment by b1sh0pe** [comment] 2020-11-18 11:19
Have you tried to open the Content-Manager edit views from the Safari?
The issue is with production build, but I tried it in development and it was there too

**Comment by derrickmehaffy** [comment] 2020-11-18 14:32
@b1sh0pe I've pulled your code locally and it built and ran fine for me in both Development and Production environment (although you did have your `server.js` url key set to an odd value that would likely cause issues in proxying)

**Comment by derrickmehaffy** [comment] 2020-11-18 14:33
Marking this as closed for now as we don't have the steps to reproduce, if you can provide the steps to reproduce the issue in a fresh project we can try to assist. Once you have those let us know and we can look at reopening the issue.

**Closed by derrickmehaffy** 2020-11-18 14:33 UTC
Labels: status: can't reproduce

**Comment by b1sh0pe** [comment] 2020-11-19 11:11
@derrickmehaffy @soupette Hi, guys! I don't know if it can help, but I recorded a short video with steps to reproduce. It's from the mobile version of Safari, but it can be reproduced in the desktop version too.
I'm already in despair as I have no other ideas what could be a reason :(
[video_2020-11-19_13-02-25 (online-video-cutter.com).zip](https://github.com/strapi/strapi/files/5566341/video_2020-11-19_13-02-25.online-video-cutter.com.zip)

**Comment by derrickmehaffy** [comment] 2020-11-19 16:01
`In other browsers, everything works fine.` That doesn't sound like a Strapi problem :cry: I'm sorry but there isn't much we can do to help if we don't know how to reproduce the issue.

**Comment by soupette** [comment] 2020-11-20 09:07
it might be due to your custom wysiwyg I saw some heavy modifications in your app. it might come from there.

**Comment by b1sh0pe** [comment] 2020-11-20 17:11
I tried to remove it totally, and use the default one, but it's still not working..
Anyway, thank you for your help! :)
