### ISSUE TITLE
Cannot create an API that have a plugins's controller name

### ISSUE THREAD

**Issue by sefo** [strapi/strapi#4665] opened 2019-12-06 10:31 UTC
**Describe the bug**
On a brand new project, scaffolding API breaks the project with error:

>npm run develop
>[2019-12-06T10:23:27.143Z] debug ⛔️ Server wasn't able to start properly.
>[2019-12-06T10:23:27.144Z] error TypeError: Cannot read property 'bind' of undefined

**Steps to reproduce the behavior**
1. On the command line: `strapi generate:api auth`

**Expected behavior**
Routes, controllers...etc are generated but
I expect the server to run and my new API to be functional.

**Screenshots**
not applicable

**Code snippets**
not applicable

**System**
- Node.js version: 12.13.1
- NPM version: 6.12.1
- Strapi version: 3.0.0-beta.17.8
- Database: SQLite
- Operating system: MacOS

**Comment by lauriejim** [comment] 2019-12-14 16:37
Hello! Thank you for reporting this issue.

In fact, the issue is about the name of your API.
You cant create a content type that have the same name as an other controller.
The users-permissions plugin has a controller that have this name.

**Comment by derrickmehaffy** [comment] 2020-01-03 12:08
@lauriejim is this something strapi's plans to fix or can I close this out?

**Comment by lauriejim** [comment] 2020-01-06 14:34
Hello @derrickmehaffy. We will have to fix it.
The issue also can happen from the Admin Panel.

**Comment by derrickmehaffy** [comment] 2020-01-06 14:36
Gotcha just wanted to check on it to see if it was a `won't fix` or not.

**Comment by harrysaini** [comment] 2020-06-29 11:27
Hi,I recently used Strapi and got good understanding of code and folder structure.
Can I try to resolve this issue. I am new to open source, i will be my first contribution.
Is this still relevant?

**Comment by MattieBelt** [comment] 2020-10-27 09:55
Looks like this is fixed, right?
1. `yarn create strapi-app test-4665 --quickstart`
2. Login and successfully create a collection type _Auth_
3. Remove the collection type and stop the server 
4. `cd test-4665`
5. `yarn strapi generate:api auth name:string` 
6. ![image](https://user-images.githubusercontent.com/31662805/97285743-e1322480-1842-11eb-857b-f14779b014a6.png)

**Closed** 2020-10-27 14:44 UTC
Labels: Hacktoberfest, priority: low, source: core:framework, status: confirmed, type: bug
