### ISSUE TITLE
Can't filter by boolean on SQLite

### ISSUE THREAD

**Issue by ivanhuay** [strapi/strapi#3573] opened 2019-07-05 14:55 UTC
**Describe the bug**
In content with some boolean parameter isn't possible to filter.

**Steps to reproduce the behavior**
1. Create a content type with a boolean field for example `enabled`.
2. Make the content type public.
3. Create some documents.
3. Make a request to the API with this param. For example: `/films?enabled=true`.
4. You should get an empty response.

**Expected behavior**
Get the documents with the filter applyed.

**Screenshots**
Example content type
<img width="868" alt="imagen" src="https://user-images.githubusercontent.com/5782286/60730204-f8952200-9f1a-11e9-8a66-614d7cfb148c.png">

<img width="1154" alt="imagen" src="https://user-images.githubusercontent.com/5782286/60730430-7c4f0e80-9f1b-11e9-864c-9666f27c9374.png">

empty response
<img width="464" alt="imagen" src="https://user-images.githubusercontent.com/5782286/60730471-9b4da080-9f1b-11e9-8433-59411a1c619b.png">

**Code snippets**
```
curl http://localhost:1337/films?enabled=true
```

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.9
- Database: mongo
- Operating system: mac os

**Comment by derrickmehaffy** [comment] 2019-07-08 04:46
I am unable to reproduce this on Beta.9 using Bookshelf, possible Mongo bug?

**Comment by ivanhuay** [comment] 2019-07-08 12:02
@derrickmehaffy sorry, I thought I was using mongo but no. I was using `SQLite` because i made `--quickstart`

```
strapi new test --quickstart
```

**Comment by lauriejim** [comment] 2019-07-09 12:11
@ivanhuay @derrickmehaffy This issue is related to SQLite.
It'm not able to reproduce using Mongo and Postgres. But I'm able with SQLite.

Thank you @ivanhuay for reporting this issue.

**Comment by lauriejim** [comment] 2019-08-16 15:42
This issue is fixed in last version of beta version (at least beta.15)

**Closed by lauriejim** 2019-08-16 15:42 UTC
Labels: priority: high, status: confirmed, type: bug 🐛
