### ISSUE TITLE
Insert into "Component Name" Error after changing a component property name.

### ISSUE THREAD

**Issue by alikazai** [strapi/strapi#8566] opened 2020-11-03 17:05 UTC
### Describe the bug

After trying to use graphql I ran into a error because i used the property name 'Title' on several different components which didnt play well with graphql, so i went back into the collection types and renamed them from 'Title' to 'CompNameTitle' these are normal string properties that have also been set to Required in the advanced section.

Everything seem to start working from then until i went into my Collection Type View to start adding content which caused a major problem when trying to save. this is the error i got.
```
insert into "components_page_comps_benefits" ("benefitTitle") values ($1) returning * - null value in column "title" violates not-null constraint
```

### Steps to reproduce the behavior

1. Create a new component with "someName" name property and set it to Required
2. Save and exit
3. Go back to the newly created component and rename the property you added to "someOtherName"
4. save and exit
5. go to your collection and enter some information into the fields then press save
6. the error should now be displayed (not very long had to quickly screenshot it to try and read it)

### Expected behavior

I expect that after changing the name i should be able to go into the collection type view and just and my information and press save and it saves without any problems.

### What I suspect

after a few minutes playing around I decided to go into the database and see what's happening as i suspected that the previously created property 'Title' was still lingering in the database table.

my suspicion was correct as the column 'Title' that was renamed was still there and it also still had the not-null settings on it which meant that when i was trying to save before the database was preventing me from creating an entry as i didnt have any value for that required property.

we should have these tables automatically renamed when we rename the property or removed as it cause problems that requires to drop the columns manually.

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: v12.18.4
- NPM version: 6.14.6
- Strapi version: 3.2.5
- Database: postgreSQL
- Operating system: windows 10.

**Comment by derrickmehaffy** [comment] 2020-11-03 18:23
Can you please fill out the system information:

```
### System

- Node.js version: <!-- Please ensure you are using the Node LTS version (v12) -->
- NPM version:
- Strapi version: <!-- Beta and Alpha versions are no longer supported -->
- Database:
- Operating system:
```

**Comment by alikazai** [comment] 2020-11-04 09:07
i updated the ticket with the information you requested

**Comment by derrickmehaffy** [comment] 2020-11-04 16:16
You are correct @alikazai they do need to be but currently aren't (see: https://github.com/strapi/strapi/issues/1114 ) and for the moment this needs to be done manually.

Can you confirm your issue is a duplicate of the linked issue?

**Comment by alikazai** [comment] 2020-11-05 11:17
yes this looks the same, different database type but the same problem... feel free to delete this if needed thanks.

**Comment by derrickmehaffy** [comment] 2020-11-05 21:11
Just going to mark as closed but thanks for confirming!

**Closed by derrickmehaffy** 2020-11-05 21:11 UTC
Labels: status: duplicate
