### ISSUE TITLE
Relationship Contentype is listed as list of json with lot of numbers in API

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4172] opened 2019-10-03 09:35 UTC
**Describe the bug**
API response of ContentType is showing irrelevant values for relationship ContentType

**Steps to reproduce the behavior**
1. Create a CT as "Category"
2. Create a CT as Article and create a Field as one to many Categories
3. Create a Article
4. http://locahost:1337/articles - Check the response. Irrelevant json in Category

**Expected behavior**
Irrelevant json to be ignored 

**Screenshots**
![1](https://user-images.githubusercontent.com/2913281/66115833-3de6ef80-e5ef-11e9-98fa-828a8edf4a30.png)

**Code snippets**
API Output  : "categories":[  
         {  
            "_id":"5d95b8e228309d41ae769412",
            "category":"Hollywood",
            "createdAt":"2019-10-03T09:01:22.788Z",
            "updatedAt":"2019-10-03T09:26:19.142Z",
            "__v":0,
            "article":{  
               "0":"5",
               "1":"d",
               "2":"9",
               "3":"3",
               "4":"2",
               "5":"1",
               "6":"a",
               "7":"8",
               "8":"8",
               "9":"5",
               "10":"4",
               "11":"0",
               "12":"f",
               "13":"5",
               "14":"3",
               "15":"9",
               "16":"9",
               "17":"4",
               "18":"7",
               "19":"d",
               "20":"2",
               "21":"a",
               "22":"c",
               "23":"a"
            },
            "id":"5d95b8e228309d41ae769412"
**System**
- Node.js version: 10.16.0
- NPM version:6.9.0
- Strapi version: v 3.0.0-beta 16.6
- Database:Mongo
- Operating system:ubuntu 18.04

**Additional context**
NA

**Comment by lauriejim** [comment] 2019-10-03 12:42
This issue is a duplicate of this one https://github.com/strapi/strapi/issues/4172

**Closed by lauriejim** 2019-10-03 12:42 UTC

**Comment by sunithakarthikeyan** [comment] 2019-10-04 06:20
You are referring the same ID .

**Comment by lauriejim** [comment] 2019-10-05 08:59
Woops! The issue has been hot fixed.
Please upgrade your application to `beta.16.8`
