### ISSUE TITLE
 My data were deleted from Postgres after some time.

### ISSUE THREAD

**Issue by zprx** [strapi/strapi#14779] opened 2022-11-03 19:54 UTC
### Required System information

- Node.js version: v16.13.0
- Strapi version: v4.4.1
- Database: PostgreSQL
- Operating system: Linux

### Describe the bug

Second time in one week data were deleted from PostgreSQL by itself.
I have not done any update, and I today when I was not able to build project, I found out that database empty, and all data dropped. It's second case in one week, what is going on , how I can fix this?

### Code snippets

**_database.js_**
```const fs = require('fs');
const path = require('path');

export default ({ env }) => {
  return {
    connection: {
      client: 'postgres',
      connection: {
        host: env('DATABASE_HOST', ''),
        port: env.int('DATABASE_PORT', 25060),
        database: env('DATABASE_NAME', ''),
        user: env('DATABASE_USERNAME', ''),
        password: env('DATABASE_PASSWORD', ''),
        ssl: {
          ca: env('DATABASE_SSL', fs.readFileSync(`${path.resolve('./')}/config/ca.crt`).toString()),
        },
      },
    },
  }
};
```

**_Dockerfile_** 
```
FROM node:16-alpine3.15

# Create app directory
WORKDIR /usr/src/app

COPY . ./
RUN rm -rf ./node_modules
RUN npm install
RUN npm install --save @strapi/strapi
RUN npm run build
EXPOSE 1337
```
**_DOCKER-COMPOSE_**
```
version: "3.9"
services:
  content-api_dev:
    restart: always
    env_file:
    - .env
    image: {ACCOOUNT}cms-api:latest
    command: npm run start
    ports:
      - "2000:1337"
```

P.S.: All credentials were removed for secure reason 

I am using digitalocean cloud database service.

**Comment by Eventyret** [comment] 2022-11-05 17:08
Are you sharing the database by any chance.

Like spin it up development and on the server if so strapi might drop tables as its different then what it was.

Using different environments always use different environmental config

**Comment by derrickmehaffy** [comment] 2022-11-05 18:52
As I said in the previous issue it is not possible for data to simply delete itself. You provided no new information as to how your environment is ran or any kind of actions that were taken on your environment. Since your issue is practically impossible to reproduce given the information that you have given us I'm marking it as closed.

**Closed by derrickmehaffy** 2022-11-05 18:52 UTC

**Comment by aroksetx** [comment] 2022-11-05 21:01
@Eventyret we are sharing databases in next way, we have local version and production. Locally we are creating  new Strapi models, and doing development. After this we are doing delivery to production. As I understood that can be the reason that strapi deletes tables(content)??
