### ISSUE TITLE
403 when requesting content via /api/{resources} in beta 

### ISSUE THREAD

**Issue by tefkah** [strapi/strapi#13333] opened 2022-05-16 14:59 UTC
### Required System information

- Node.js version: 16
- NPM version: 8.6.0
- Strapi version: 4.2.0-beta2
- Database: any
- Operating system: MacOS

### Describe the bug

When upgrading to typescript in the beta, Strapi allows you to keep the api exports in .js, but will fail when requesting the resources via `strapi routes:list` and yield a 403 through `/api/{resources}`.

### Steps to reproduce the behavior

1. Upgrade strapi to 4.2.0-beta2
2. Replace all files with .ts EXCEPT the api declarations (this assumes you have some already)
3. Notice that Strapi starts correctly, will even build without throwing an error
4. Make a request to some api endpoint
5. Get a 403 error without a clear explanation why.

### Expected behavior

Strapi should inform you that you need to update your API exports to .ts or provide some tool for doing so.

(completely reasonable that this tool does not exist yet ofc!)

### Code snippets

Sample .ts file which works (just changing to `.ts` will throw an error)

```ts
/**
 *  blog-author controller
 */

import { factories } from '@strapi/strapi'

const controller = factories.createCoreController('api::blog-author.blog-author')
export default controller

```

### Additional context

This is kind of a niche problem which I solved already, but may be useful for someone else running into the same issue.

**Comment by ThomasFKJorna** [comment] 2022-05-30 10:51
Yes, these are the contents

```json
{
  "extends": "@strapi/typescript-utils/lib/configs/server",
  "compilerOptions": {
    "resolveJsonModule": true,
    "outDir": "dist",
    "rootDir": "."
  },
  "include": ["./", "src/**/*.json"],
  "exclude": [
    "node_modules/",
    "build/",
    "dist/",
    ".cache/",
    ".tmp/",
    "src/admin/",
    "**/*.test.ts",
    "src/plugins/**"
  ]
}
```

The problem is that when naively migrating to typescript, (in my case installing the latest beta and renaming (most) files to `.ts`, but _not_ the `{resource}.js` files in `api/{resource}/controllers/{resource}.js` and `api/{resource}/routes/{resource}.js`) will lead to those content types not being accessible through the API.

After renaming e.g. `api/article/controllers/article.js` to `api/article/controllers/article**.ts**` and changing the contents to be as follows 
```ts
'use strict'

/**
 *  article controller
 */

import { factories } from '@strapi/strapi'

const controller = factories.createCoreController('api::article.article')
export default controller
```

the routing worked again.

**Comment by Convly** [comment] 2022-07-11 08:28
Hey @tefkah, if you want to be able to have both JavaScript and TypeScript files, you can try and enable the `allowJs` property in your tsconfig.json. If it's disabled, then it's normal that you've to manually rename your file and change their content to fit TypeScritp syntax.

I'll close this as it's the expected behavior but feel free to continue the discussion if something is not clear.

**Closed by Convly** 2022-07-11 08:28 UTC
Labels: source: typescript
