### ISSUE TITLE
Enumeration field - Duplicate values are not allowed (only alphanumeric characters are taken into account).

### ISSUE THREAD

**Issue by sudo-allahrakha** [strapi/strapi#16477] opened 2023-04-23 15:13 UTC
### Required System information

- Node.js version: v18.0.0
- NPM version:  8.11.0
- Strapi version: 
- Database: POSTGRESQL
- Operating system: DEEPIN 20.9 
- Is your project Javascript or Typescript:  Javascript

### Describe the bug

Creating enumeration field and adding blood groups A+,A-, B+,B-,O+,O- etc . It gives error Duplicate values are not allowed (only alphanumeric characters are taken into account).

### Screenshots

![Screenshot_select-area_20230423200523](https://user-images.githubusercontent.com/81164804/233847978-9d563e73-1156-4dc4-8207-0ff16733cc8a.png)

**Comment by Boegie19** [comment] 2023-04-23 19:59
@sudo-allahrakha Duplicate of https://github.com/strapi/strapi/issues/15180

**Closed by Boegie19** 2023-04-23 19:59 UTC
Labels: status: duplicate
