### ISSUE TITLE
No global strapi command after setup own strapi fork for contributing

### ISSUE THREAD

**Issue by cimchd** [strapi/strapi#3398] opened 2019-06-07 07:07 UTC
**Describe the bug**
I updated my strapi fork to the latest beta version. After running the setup and run the global strapi command, there was an error message 'strapi: command not found`.
The same setup has worked before with the alpha version.

**Steps to reproduce the behavior**
Follow the steps of the contributing guide: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

1. git clone https://github.com/cimchd/strapi.git
2. cd strapi
3. yarn setup
4. strapi -v

**Expected behavior**
The strapi command will be executed.

**System**
- Node.js version: 10.16.0 
- NPM version: 6.9.0
- Yarn version: 1.16.0
- Strapi version: 3.0.0-beta.2
- Database: MongoDB
- Operating system: Debian 9 (Stretch)

**Additional context**
I also checked `npm run setup` with the same result.

**Comment by alexandrebodin** [comment] 2019-06-07 08:54
There are no more global linking of the strapi binary in the new version of strapi.

You contributing guide doesn't mention using a global strapi command anymore https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md.

If you really want to have your local strapi command available globally you can run `yarn link` in the packages/strapi folder


I'm closing this issue as it is the intended behaviour.

**Closed by alexandrebodin** 2019-06-07 08:54 UTC
