### ISSUE TITLE
"error TypeError: m.pivot.get is not a function" is raised when "Pivot" is used as collection name

### ISSUE THREAD

**Issue by JeanLEUNG** [strapi/strapi#9174] opened 2021-01-21 12:47 UTC
## Bug report

New records may fail or even corrupt data when a collection called "Pivot" is used in the model. 2 behaviours can occur : 
* the object cannot be saved, and a popup is raised : 
![image](https://user-images.githubusercontent.com/26717079/105352041-ac3d3000-5bed-11eb-9ab8-a9c3e6ab9d14.png)
* the object is created, but the linked object is corrupted (cannot be requested anymore)
(this one requires a more complex data structure and is not described here)

### Steps to reproduce the behavior

1. Create one collection "Pivot" with a name:string field
2. Create one collection, let's say "Activity" with a name:string field, and a one-to-one relation with Pivot
3. Create a Pivot record
4. Create an Activity record, and choose the pivot object as link
5. Save your Activity record

### Expected behavior

No error should occur and the save should succeed.

### Screenshots

![image](https://user-images.githubusercontent.com/26717079/105352388-1f46a680-5bee-11eb-8208-de6cd154cca6.png)
![image](https://user-images.githubusercontent.com/26717079/105352442-2bcaff00-5bee-11eb-8da4-a31cef11fdf2.png)

### System
tested in 2 environments : GCP (docker-K8s) and Windows

- Node.js version: (GCP) 14-alpine (Win) 14.15.1
- NPM version: 6.14.8
- Strapi version: 3.4.4
- Database: (GCP) postgres (Win) sqlite
- Operating system: (GCP) 14-alpine (Win) windows 10 version 1803

**Comment by derrickmehaffy** [comment] 2021-01-22 21:16
Can confirm on v3.4.4

```
[2021-01-22T21:15:28.752Z] error TypeError: m.pivot.get is not a function
    at /home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/relation.js:455:27
    at arrayAggregator (/home/dmehaffy/Development/test9174/node_modules/lodash/lodash.js:497:34)
    at Function.groupBy (/home/dmehaffy/Development/test9174/node_modules/lodash/lodash.js:4843:16)
    at Child.eagerPair (/home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/relation.js:449:25)
    at EagerRelation.pushModels (/home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/base/eager.js:107:24)
    at EagerRelation._eagerLoadHelper (/home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/eager.js:81:53)
    at Sync.<anonymous> (/home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/eager.js:31:31)
From previous event:
    at EagerRelation.eagerFetch (/home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/eager.js:31:8)
    at EagerRelation.<anonymous> (/home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at Child._handleEager (/home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/model.js:1526:56)
    at Child.<anonymous> (/home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/model.js:732:27)
From previous event:
    at Child.<anonymous> (/home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/model.js:730:12)
From previous event:
    at Child.refresh (/home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/model.js:544:19)
    at Child.<anonymous> (/home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/model.js:1191:27)
From previous event:
    at Child.<anonymous> (/home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/model.js:1162:14)
From previous event:
    at Child.<anonymous> (/home/dmehaffy/Development/test9174/node_modules/bookshelf/lib/model.js:1060:10)
From previous event:
    at Child.<anonymous> (/home/dmehaffy/Development/test9174/node_modules/strapi-connector-bookshelf/lib/relations.js:157:72)
    at processImmediate (internal/timers.js:461:21)
From previous event:
    at /home/dmehaffy/Development/test9174/node_modules/strapi-connector-bookshelf/lib/relations.js:156:14
    at Array.reduce (<anonymous>)
    at Function.update [as updateRelations] (/home/dmehaffy/Development/test9174/node_modules/strapi-connector-bookshelf/lib/relations.js:105:68)
```

Reproduction project:
[test9174.zip](https://github.com/strapi/strapi/files/5858627/test9174.zip)

**Comment by Marc-Roig** [comment] 2023-02-08 10:26
This seems to be fixed in v4. As v3 reached EOL I am closing this issue.

@derrickmehaffy did you reproduce this in v4? If that is the case I will reopen the issue. But I can not find a way to reproduce it.

**Closed by Marc-Roig** 2023-02-08 10:26 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:strapi
