### ISSUE TITLE
Ordering child relationships

### ISSUE THREAD

**Issue by ChrisRArendt** [strapi/strapi#2616] opened 2019-01-11 20:05 UTC
- **Node.js version**: 10.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.17
- **Database**: MongoDB, db is v3.6.8
- **Operating system**: OSX 420 Sierra

**What is the current behavior?**
Can drag and drop child relation items to order them and save. On opening the parent item again, the child items are there but out of order.

**Steps to reproduce the problem**

1. Create two content types with a one to many relation. 
2. Create rows for each. 
3. Connect child rows to a parent. 
4. Try to reorder items in the right-hand relationship list in the parent.
5. Save.
6. Return to parent item and check order of the children. 
7. Profit

**What is the expected behavior?**
The drag and drop option makes it seem like children should remain in order.

**Suggested solutions**
If the intended functionality is to order, then it should be saved. There are auto generated fields like id and v, perhaps perhaps an order number could work.
If it is just a list, then the drag and drop functionality should be removed.

**My settings.jsons**
Page.settings.json (parent)
```
{
  "connection": "default",
  "collectionName": "page",
  "info": {
    "name": "page",
    "description": "Page"
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "CMS Name": {
      "default": "",
      "type": "string"
    },
    "parentPage": {
      "model": "page"
    },
    "ChildCouplings": {
      "collection": "coupling",
      "via": "ParentPage"
    }
  }
}
```

Coupling.settings.json (child)
```
{
  "connection": "default",
  "collectionName": "coupling",
  "info": {
    "name": "coupling",
    "description": "Coupling"
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "CMS Name": {
      "default": "",
      "type": "string"
    },
    "ParentPage": {
      "model": "page",
      "via": "ChildCouplings"
    },
    "ParentCoupling": {
      "model": "coupling",
      "via": "ChildCouplings"
    },
    "ChildCouplings": {
      "collection": "coupling",
      "via": "ParentCoupling"
    }
  }
}
```

**Comment by lauriejim** [comment] 2019-01-13 17:18
Hello! This issue is a duplicate of this one - https://github.com/strapi/strapi/issues/2166

**Closed by lauriejim** 2019-01-13 17:18 UTC

**Comment by Downloaddave** [comment] 2019-03-19 16:21
@lauriejim It looks like I'm running into this issue too using mongoDB, using the dominate flag as described in #2166 doesn't seem to work either. I'm noticing that the ticket commenting was locked so I'm not sure if there is a fix that you guys are working on or something else I can try to test on my end.

To provide some more context, it doesn't seem to happen with every content type only a specific ones. Meaning, the ordering will save for one content-type, but not another. I'm hoping to experiment with this to try and help figure it out. 

So far are you guys thinking it could be an issue with the api/ or perhaps the structure in the mongoDB?

**Comment by cpres** [comment] 2019-09-25 21:56
setting `"dominant": true` does not work for me either. I think this ticket should be reopened and using order within the schema would be a good update, as of now I can't see a way to fix the order in the database shy of swapping the entire data sans-ids in the database

**Comment by MaffooBristol** [comment] 2019-12-09 11:14
This isn't just a Mongo thing. I'm using postgres and I can't even see anywhere in the database where this ordering should be kept (everything defaults to `1`).

I also think that the response on #2166 is not very polite. Basically saying "do your ordering programatically". So tell me, where exactly in Strapi is a non-technical user meant to be able to decide what order their content displays? There's no weighting anywhere in the system (except perhaps in groups). The relations display has a "reorder hamburger". When you move the items and save, it ignores it. I think this is something important that should be addressed.

It's actually even buggier than I thought, because it seems that (on the same content) one relational field I have saves the order seemingly randomly to what I did, and one orders it by ID. No difference between the fields, but they just decide to do their own thing.

**Comment by MaffooBristol** [comment] 2019-12-09 11:19
Due to the inability to order my content, I created another content type called "ordering" which I thought I could use to arrange my other content and then request both and sort against eachother in my request. A really hacky method in and of itself. But then it turned out that wouldn't work either. So it means that I'm going to have to go into my content types and add an arbitrary "weight" field that will be queried. Not very user friendly (although trying to drag around relations in the tiny right hand column isn't really either). Is there a "correct" way to do this? It seems like one of the basic features a CMS should be able to do.

I don't mean to sound rude or demanding, but I'm getting increasingly frustrated by the amount of basic stuff in Strapi that doesn't exist or doesn't work...

**Comment by lauriejim** [comment] 2019-12-15 19:41
Thank you for these details.

**Comment by morganfeeney** [comment] 2020-02-17 09:20
@lauriejim can I ask, what is the intended purpose of the ordering functionality mentioned in this thread?

**Comment by lauriejim** [comment] 2020-02-18 15:48
Via the Content Manager, be able to order relations and retrieve the same order in the API response.

**Comment by nickjanssen** [comment] 2020-03-04 13:16
Here's a valid workaround: use Groups.

Instead of using a relation directly, create a group which contains the relation (in other words, wrap the relation with a group). Then you can drag and drop groups and the order will be preserved.

**Comment by lauriejim** [comment] 2020-03-10 09:26
That is a workaround if you don't want to use deep filtering.
You currently cant filters by entries of values that are in a component.

**Comment by apppel** [comment] 2020-03-26 13:30
Perhaps we should allow comments again on issue #2166 ? There seems to still be a lot of need for this feature with no real solution presented?

**Comment by janbaykara** [comment] 2020-04-07 22:44
Yes, there is a real difference between...

<img width="237" alt="Screenshot 2020-04-07 at 23 43 14" src="https://user-images.githubusercontent.com/237556/78726315-2d5a5d80-7921-11ea-91c8-297fdfda9a16.png">

... and ...

<img width="443" alt="Screenshot 2020-04-07 at 22 30 23" src="https://user-images.githubusercontent.com/237556/78726353-48c56880-7921-11ea-829c-daed55005dba.png">

In terms of self-explanation. The pain is the ID-for-label when you really want the title of the child relationship to trickle up, if this workaround is to really work.

**Comment by lauriejim** [comment] 2020-04-10 13:54
Hello guys!

We already collected needs about this "order" feature, that is the reason why we locked the topic.
No solution is presented because with the current version of Strapi there is no easy workaround to achieve that.

About @janbaykara can you please create an issue, please.
I think in the config you should be able to set up the right value there.
But after that, it's a good method to keep the order.
