### ISSUE TITLE
Duplicated collection name, server won't start.

### ISSUE THREAD

**Issue by idebeijer** [strapi/strapi#10929] opened 2021-09-10 07:48 UTC
### Describe the bug

When I create a single type and call it e.g. 'case', the server restarts and it works fine. When I want to create a collection type and I name it 'case' as well it tells me that name already exists. But when I append the name with an 's', naming it 'cases' the server will restart and it will fail to start again with an error (error below in code snippets).

### Steps to reproduce the behavior

1. Start by creating a single type.
2. Name it e.g. 'case'.
3. After saving, the server restarts and create a collection type.
4. Name the collection type the same as the single type but append it with an 's', so in this case it would be 'cases'.
5. Now when you save, the server restarts and won't start again (error output below in code snippets).

### How I fixed the server

1. Go to you Strapi server's installation.
2. Head to the folder 'api'.
3. In here you will see your single type 'case' and collection type 'cases'.
4. Within either of those you head over to the folder 'models'.
5. Then edit the 'cases.settings.json' or 'case.settings.json'.
6. At the top of the file it will say either "kind": "collectionType" or "kind": "singeType".
7. In one of those you will edit names from e.g. 'case' to something anything else but 'case' or 'cases' so it will not have the conflict anymore.

### Expected behavior

I would expect that the panel would tell you that this name is not available just like it does when you want to call it the exact same. Instead the server won't start anymore, it does give an error and I was able to fix it for myself. But it would be nice that Strapi handles this error in the first place by saying the name is not available and not adding the collection or single type, which now it does and leads to the server not starting.

### Code snippets

```
error Error: Duplicated collection name: `cases`.
The same collection name can't be used for two different models.
First found in API `case`, model `case`.
Second found in API `cases`, model `cases`.
    at /home/idebeijer/strapi/strapi/node_modules/strapi-database/lib/validation/check-duplicated-table-names.js:55:13
    at Array.forEach (<anonymous>)
    at checkDuplicatedTableNames (/home/idebeijer/strapi/strapi/node_modules/strapi-database/lib/validation/check-duplicated-table-names.js:47:18)
    at validateModelSchemas (/home/idebeijer/strapi/strapi/node_modules/strapi-database/lib/validation/index.js:7:3)
    at DatabaseManager.initialize (/home/idebeijer/strapi/strapi/node_modules/strapi-database/lib/database-manager.js:39:5)
    at Strapi.load (/home/idebeijer/strapi/strapi/node_modules/strapi/lib/Strapi.js:354:19)
    at async Strapi.start (/home/idebeijer/strapi/strapi/node_modules/strapi/lib/Strapi.js:196:9)
error Command failed with exit code 1.
```

### System

- Node.js version: v14.17.6 
- NPM version: 6.14.15
- Strapi version: 3.6.8 
- Database: MongoDB
- Operating system: Ubuntu also on Debian

**Comment by derrickmehaffy** [comment] 2021-09-10 19:59
This type of configuration isn't possible. It will generate duplicate routes in the Koa router.

Since this is a naming issue it would be a duplicate of: https://github.com/strapi/strapi/issues/1198

Your collection type will need to have a different name like `case-item` or something like that.

**Closed by derrickmehaffy** 2021-09-10 19:59 UTC
