### ISSUE TITLE
Strapi asks to upgrade its version although it is already the latest version.

### ISSUE THREAD

**Issue by kevinadhiguna** [strapi/strapi#9336] opened 2021-02-07 09:44 UTC
### Describe the bug

I upgraded a Strapi app that I created last year to version 3.4.6 which is the latest version. Nevertheless, in the Strapi administration panel, it asks me to upgrade Strapi to the latest version.

### Steps to reproduce the behavior

1. Go to `General` on the left side in the Strapi Administration Panel
2. Click on `Settings`
3. See `Application` to see project details
4. Below the `Strapi version`, a text saying "Upgrade your project" is showing although it is already the latest version of Strapi.

### Expected behavior

The text `Upgrade your project` will not show, just like the picture below (another brand new project).

![Another Brand New Project](https://user-images.githubusercontent.com/43397636/107142691-2f3ae600-6963-11eb-8160-8d673ffd2255.png)

### Screenshots;

Strapi asks to upgrade its version although it is already the latest version.

![Issue](https://user-images.githubusercontent.com/43397636/107142666-12061780-6963-11eb-8b4d-4f3f69f0a292.png)

Here is the `package.json` file of the project : 

![package.json](https://user-images.githubusercontent.com/43397636/107142599-ca7f8b80-6962-11eb-813a-03d4235a90d6.png)

### System

- Node.js version: v14.15.4 
- Yarn version: 1.22.5
- Strapi version: v3.4.6
- Database: MongoDB
- Operating system: Ubuntu 20.04 LTS

**Comment by derrickmehaffy** [comment] 2021-02-07 19:15
We do version matching based on the version in the package.json and we do not currently recommend using `~` / `^` / `<` / `>` for versions due to our migration guides: https://strapi.io/documentation/developer-docs/latest/migration-guide/#instructions

Marking as closed as this works as intended.

**Closed by derrickmehaffy** 2021-02-07 19:15 UTC

**Comment by kevinadhiguna** [comment] 2021-02-08 11:09
Thanks, it worked after I removed `~` before semantic versioning.
