### ISSUE TITLE
Hebrew is treated as duplicate in Enumeration fields

### ISSUE THREAD

**Issue by agamm** [strapi/strapi#13766] opened 2022-07-13 15:24 UTC
### Required System information

- Node.js version: v16.15.1
- NPM version: 8.11
- Strapi version: 4.2.3
- Database: 
- Operating system: Linux (fedora)

### Describe the bug
When adding text in Hebrew there is an error that there is a duplicate eventhough there isn't one:
![image](https://user-images.githubusercontent.com/1269911/178770987-16570a8a-4c50-4416-9c36-48309ec8998e.png)

### Steps to reproduce the behavior

1. Go to create a new enumeration field
2. Type words in hebrew (more than one line) try: אאא
3. Try to save it and get the duplicate error.

### Expected behavior

It should allow un-duplicated hebrew text.

### Screenshots

See above.

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by agamm** [comment] 2022-07-13 15:52
@gu-stav Here you go:
```
מרכז
דרום
```

**Comment by gu-stav** [comment] 2022-07-14 10:07
I have had a look today: the issue is, that values for GraphQL enumerations can only contain ASCII values. We are using a library to translate some special characters into their latin counterparts, but this is currently not supported for hebrew. We will work on enumerations at some point soon, which will allow you to seperate the value from the label. Until then, the only solution I can offer is to use latin / ascii characters.

Closing as duplicate of: https://github.com/strapi/strapi/issues/13017

**Closed by gu-stav** 2022-07-14 10:07 UTC
Labels: issue: bug, severity: low, source: core:content-type-builder, status: pending reproduction
