### ISSUE TITLE
changing permissions on a requried field are broken

### ISSUE THREAD

**Issue by DenuxPlays** [strapi/strapi#19892] opened 2024-03-22 08:04 UTC
### Required System information

- Node.js version:v20.11.0
- NPM version: v1.22.19 (yarn)
- Strapi version: v4.21.0
- Database: MariaDb 10.6
- Operating system: Debian-12
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When you have a requried field which gets auto-genrated and you try to change the permissions that non-admin users cannot see, edit or delete the field the user still is able to.
You can save this an strapi says that everything is ok but when you go into the non-admin user and visit a type where the field is there you can still see, edit and delete the field.
Go back to the permissions page and see that the permissions has been resetted.

### Steps to reproduce the behavior

1. create a field that required & auto-generated
2. go change the permissions that a user cannot change, view or delete the field
3. login as this user and see that you are still able to
4. go back to the permissions page and see that it has been resetted

### Expected behavior

Either the permissions should work or strapi should return an error if you are not allowed to do this!

### Screenshots

///

### Code snippets

///

### Additional context

If you just remove the add and change field (so that the user can just see the field) everything works fine.

**Comment by DenuxPlays** [comment] 2024-03-22 08:21
Update:

This issue appears on combination with a plugin but I am not sure where the bug acutally occurrs in which system:
https://github.com/pluginpal/strapi-plugin-config-sync/issues/125

**Comment by edporras** [comment] 2024-03-26 15:07
This is possibly related to https://github.com/strapi/strapi/issues/18997, which has been opened since Dec 😞

**Comment by DenuxPlays** [comment] 2024-03-26 16:11
> This is possibly related to https://github.com/strapi/strapi/issues/18997, which has been opened since Dec 😞 

I hope they fix this soon
Strapi has already the huge flaw that things cannot be committed without a third party plugin (basically install it once on the production system and set it up there).

**Comment by derrickmehaffy** [comment] 2024-03-28 20:54
Duplicate of https://github.com/strapi/strapi/issues/18997

**Closed by derrickmehaffy** 2024-03-28 20:54 UTC
Labels: status: duplicate
