### ISSUE TITLE
Cant install GraphQL plugin (Windows / Docker)

### ISSUE THREAD

**Issue by KonradDeskiewicz** [strapi/strapi#10124] opened 2021-04-23 17:55 UTC
### Describe the bug

Receiving an error each time I'm trying to install graphql plugin from the "market"

### Steps to reproduce the behavior

1. Go to market
2. Click on Download in GraphQL plugin
3. Error in console:
```
[2021-04-23T17:46:44.042Z] error Error: Command failed: npm run strapi -- install graphql
- Installing dependencies
Command failed: yarn add strapi-plugin-graphql@3.6.0
warning "strapi-admin > bootstrap@4.6.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning "strapi-admin > bootstrap@4.6.0" has unmet peer dependency "popper.js@^1.16.1".
warning "strapi-plugin-users-permissions > grant-koa@5.4.8" has unmet peer dependency "koa@>=2.0.0".
warning "strapi-plugin-graphql > graphql-playground-middleware-koa@1.6.21" has unmet peer dependency "koa@^2".
warning "strapi-plugin-graphql > graphql-type-long@0.1.1" has incorrect peer dependency "graphql@^0.9.1 || ^0.10.0 || ^0.12.0 || ^0.13.0".
warning "strapi-plugin-graphql > graphql-iso-date@3.6.1" has incorrect peer dependency "graphql@^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
error An unexpected error occurred: "EEXIST: file already exists, copyfile '/usr/local/share/.cache/yarn/v6/npm-form-data-3.0.1-ebd53791b78356a99af9a300d4282c4d5eb9755f-integrity/node_modules/form-data/Readme.md' -> '/srv/app/node_modules/form-data/Readme.md'".
yarn add v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
info If you think this is a bug, please open a bug report with the information provided in "/srv/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@0.1.0 strapi: `strapi "install" "graphql"`
npm ERR! Exit status 1

npm ERR!
npm ERR! Failed at the app@0.1.0 strapi script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2021-04-23T17_46_44_032Z-debug.log
```

### System

- Node.js version: 12.20.1
- NPM version: 
- Strapi version: 3.6
- Database: posgres
- Operating system: Windows / Docker

**Comment by kasonde** [comment] 2021-04-26 12:20
HI @KonradDeskiewicz, if you can, please provide some information about your setup i.e `docker-compose.yml` or a `.Dockerfile` describing your environment setup.

**Comment by KonradDeskiewicz** [comment] 2021-04-26 13:00
@kasonde this is my `docker.compose.yml`

```
version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi_demo
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password_to_database
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
```

Not sure why the default version uses Node 12 while on docker hub "latest" is next to node 14 version. 
Anyway, Strapi is setting up correctly without issues until of course GraphQL plugin is requested.

**Comment by Muhammad-1990** [comment] 2021-07-07 00:08
Hi,
Yes it seems that the Strapi/strapi image fails to install the grapghql plugin from the market place.
incase someone comes here for a work around:

Setup strapi with docker-compose as per usual, kill the docker and volumes then install from terminal, however this brings about other issues for non linux os

what worked for me:
$rm -rf node_modules && yarn cache clean 
$yarn install && yarn strapi install graphql
(and also delete .cache folder)
if all goes well then 
$rm -rf node_modules && yarn cache clean && docker-compose up -d

**Comment by derrickmehaffy** [comment] 2022-01-05 21:53
can't reproduce on v4, marking as closed

**Closed by derrickmehaffy** 2022-01-05 21:53 UTC
Labels: status: pending reproduction

**Comment by lucaoskaique** [comment] 2022-03-03 14:19
> rm -rf node_modules && yarn cache clean && docker-compose up -d

worked like a charm!!!!
