### ISSUE TITLE
FetchError: request to custome admin url failed, reason: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by geekplux** [strapi/strapi#8501] opened 2020-10-28 04:49 UTC
### Describe the bug

I tried to deploy by following https://strapi.io/documentation/v3.x/deployment/nginx-proxy.html, no matter what solution I used (Sub-Folder Unified or Sub-Folder Split) I still got error below:

> Create your first administrator 💻 by going to the administration panel at:
> https://custom_url.com/xadmin
> FetchError: request to https://custom_url.com/xadmin failed, reason: getaddrinfo ENOTFOUND custom_url.com
    at ClientRequest.<anonymous> (/home/userxxx/project-backend/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:428:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND'
}

the `nginx.conf` and `config/server.js` are same as the example which you provided. After a digging through the doc I didn't find anything other options I can attempt to fix this error. Much appreciated if you can figure out or give some tips.

### Steps to reproduce the behavior

1. Quick start according to docs
2. change url or admin url in `config/server.js`
3. config the nginx proxy
4. run and get error

### Expected behavior

No error if there is custom url.
(it's actually no error now if I drop all the url changing)

### Code snippets

config/server.js

```js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  // url: 'https://customurl.com/api',
  admin: {
    // url: 'https://customurl.com/xadmin',
    auth: {
      secret: env('ADMIN_JWT_SECRET', '1e978b20a8532605b42d18bf01ea37f4'),
    },
  },
});
```

### System

- Node.js version: 12.19.0
- NPM version: 6.14.8
- Strapi version: 3.1.4
- Database: mysql 8.0.22
- Operating system: debian 10

**Comment by geekplux** [comment] 2020-10-28 08:58
could I skip the permission checking session? directly get into admin page without login

**Comment by lauriejim** [comment] 2020-10-28 09:31
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/admin-login-fails-with-401/754/2

**Comment by derrickmehaffy** [comment] 2020-10-28 13:25
Ummm `nginx.conf` the configs we show on our drive are not modifications or replacements of this file, they are virtual host config files.

See: https://www.keycdn.com/support/nginx-virtual-host as an example.

**Comment by derrickmehaffy** [comment] 2021-01-22 17:53
Can't reproduce on v3.4.4 with the exception of the issue detailed here: https://github.com/strapi/strapi/issues/8616

Marking as closed until we get further information

**Closed by derrickmehaffy** 2021-01-22 17:53 UTC
Labels: status: can't reproduce
