### ISSUE TITLE
Typescript projects do not read the license.txt due to incorrect path

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#14328] opened 2022-09-06 15:35 UTC
### Required System information

- Node.js version: 14.19.3
- NPM version: 6.14.17
- Yarn version: 1.22.18
- Strapi version: 4.3.6
- Database: SQLite
- Operating system: Linux Mint 20.3 (Ubuntu 20.04.3)

### Describe the bug

When creating/running a typescript project the `license.txt` is not properly detected and the project will run in community mode instead of enterprise. When using the `STRAPI_LICENSE` env var either manually in the CLI or via `.env` it will properly detect the EE version.

### Steps to reproduce the behavior

1. Create a TS project
2. Create a `license.txt` file at the root of the project and copy in a valid EE key
3. Start TS project
4. See that the server is ran in community mode

### Expected behavior

Typescript should properly read the license.txt file path and load the EE key

### Screenshots

N/A

### Code snippets

N/A

### Additional context

N/A

**Comment by derrickmehaffy** [comment] 2022-09-06 15:36
Confirmed via @kasonde / @fdel-car via discord during the tuesday internal AMA

**Comment by fdel-car** [comment] 2022-09-09 13:52
I didn't test it but I think the issue is coming from [here](https://github.com/strapi/strapi/blob/760b396b7d7ea88f7dddde87829814e20bccab85/packages/core/strapi/lib/Strapi.js#L120). We're passing the dist folder as the location where the `license.txt`, but it's often not the case in TypeScript project.

**Comment by Convly** [comment] 2022-10-27 13:56
Should have been fixed in https://github.com/strapi/strapi/pull/14691
It'll be available in the next release (4.4.6)

**Closed by Convly** 2022-10-27 13:56 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:strapi, source: typescript
