### ISSUE TITLE
`useContentManagerInitData` must be used within `StrapiApp`

### ISSUE THREAD

**Issue by zensarCompass** [strapi/strapi#21779] opened 2024-10-10 11:05 UTC
### Required System information

- Node.js version: v20.10.0
- NPM version: 10.2.3
- Strapi version: 5.0.2
- Operating system: Windows 11

### Describe the bug

```
Error: `useContentManagerInitData` must be used within `StrapiApp`
    at http://localhost:1337/node_modules/.strapi/vite/deps/chunk-7AYCCE4I.js?v=59a775bb:105:11
    at h (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-L727TDNB.js?v=59a775bb:4120:70)
    at useContext2 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-7AYCCE4I.js?v=59a775bb:102:51)
    at useContentManagerInitData (http://localhost:1337/node_modules/.strapi/vite/deps/layout-_5-cXs34-ES4SVMDW.js?v=59a775bb:344:28)
    at Layout (http://localhost:1337/node_modules/.strapi/vite/deps/layout-_5-cXs34-ES4SVMDW.js?v=59a775bb:481:71)
    at renderWithHooks (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=59a775bb:11568:26)
    at mountIndeterminateComponent (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=59a775bb:14946:21)
    at beginWork (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=59a775bb:15934:22)
    at beginWork$1 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=59a775bb:19781:22)
    at performUnitOfWork (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=59a775bb:19226:20)
```

### Steps to reproduce the behavior

1. Upgraded from Strapi v4 to Strapi V5 
2. Npm installl
3. Open strapi UI
4. Click on content manager

### Expected behavior

Strapi console should run properly without error

### Screenshots

![{862E926A-AAAA-463F-9CA0-EED28F292DE6}](https://github.com/user-attachments/assets/5a294715-3385-4d16-9192-563f2413d122)

**Comment by bolg55** [comment] 2024-10-10 20:41
Possibly related to #21785

**Comment by michsko544** [comment] 2024-10-23 09:26
I found a temporary solution. For example, if you are using `Strapi 5.0.5` like me you need to add the following `overrides` to `package.json` and reinstall packages `pnpm install`.

```json
"overrides": {
    "@strapi/admin": "5.0.5",
    "@strapi/database": "5.0.5",
    "@strapi/generators": "5.0.5",
    "@strapi/logger": "5.0.5",
    "@strapi/permissions": "5.0.5",
    "@strapi/types": "5.0.5",
    "@strapi/typescript-utils": "5.0.5",
    "@strapi/utils": "5.0.5"
  },
```

I think the problem is caused by installing different versions of Strapi packages in `node_modules` since Strapi uses `workspace:*` as a version tag (#20929). For example, the problem always occurred for me after a new version of Strapi was released. When my pipeline built an application in which I did not update Strapi to the latest one, the problem occurred.

I took a look at the `pnpm-lock.yaml` file and noticed that the `@strapi/admin@5.0.6` package was installed when I was using Strapi 5.0.5. After adding `overrides` the problem disappeared. Probably setting `@strapi/strapi@latest` will also solve the problem, but I prefer to have a fixed Strapi version, due to more control.

**Comment by SalahAdDin** [comment] 2024-10-23 14:35
Not able to migrate plugins to version 5 yet!

**Comment by innerdvations** [comment] 2024-11-14 09:43
Duplicate of https://github.com/strapi/strapi/issues/21151 ?

**Closed** 2024-11-19 09:25 UTC
Labels: issue: bug, severity: high, status: duplicate, source: core:content-manager, status: pending reproduction, version: 5
