### ISSUE TITLE
[BUG] Empty component entries are automatically added back on save 

### ISSUE THREAD

**Issue by thevisualfox** [strapi/strapi#16153] opened 2023-03-21 09:41 UTC
### Required System information

- Node.js version: 16.14.0
- NPM version: 8.3.1
- Strapi version: 4.8.0
- Database: MySQL
- Operating system: CentOs / MacOs
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Example: 

I have a hero component that has another component inside of it named "Link" where you can fill out a title, externalUrl, a page relation and a color. When I go to the single type that has a hero component to fill some content and I choose to **not** add a link to this specific hero and press save, then the component link entry is automatically added back with empty fields. Since my "Title" is required, you cannot save the page unless you delete all automatically filled components that have a required field.  

This applies to all components, not components inside components specifically. This bug was introduced at version 4.8.0 --> Version 4.7.1 does not appear to have this issue.

### Steps to reproduce the behavior

1. Make a component that contains some fields
2. Add the component to a single type along with some other fields
3. Don't add content to the component, but do so for the other fields
4. Press save and watch the component add itself back with empty fields

### Expected behavior

If a component entry is not added to a specific content field, it should not be automatically added back when the page is saved.

### Video

https://user-images.githubusercontent.com/43511726/226564955-bcfe3cf9-ff4a-45c3-a189-fe61a6906fe2.mov

**Comment by joshuaellis** [comment] 2023-03-21 09:47
Thanks for the report, however this is a duplicate of https://github.com/strapi/strapi/issues/16111

**Closed by joshuaellis** 2023-03-21 09:47 UTC
Labels: status: duplicate
