### ISSUE TITLE
GraphQL component relation field throws after relation is deleted

### ISSUE THREAD

**Issue by LeBenLeBen** [strapi/strapi#9961] opened 2021-04-05 17:26 UTC
### Describe the bug

I have the following Recipe model:

```json
{
  "kind": "collectionType",
  "collectionName": "recipes",
  "info": {
    "name": "Recipes",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "attributes": {
    "title": {
      "type": "string",
      "required": true
    },
    // ...
    "author": {
      "via": "recipes",
      "plugin": "users-permissions",
      "model": "user"
    }
  }
}
```

I also have the following component:

```json
{
  "collectionName": "components_users_last_viewed_recipes",
  "info": {
    "name": "LastViewedRecipes",
    "icon": "list-ol",
    "description": ""
  },
  "options": {},
  "attributes": {
    "recipe": {
      "unique": true,
      "model": "recipe"
    },
    "viewedAt": {
      "type": "datetime"
    }
  }
}
```

Which I use to store the recipes a user has recently viewed on the User model of the Users Permissions plugin. I couldn’t use a relation field directly on the model as order is important here.

```json
{
  "kind": "collectionType",
  "collectionName": "users-permissions_user",
  "info": {
    "name": "user",
    "description": ""
  },
  "options": {
    "draftAndPublish": false,
    "timestamps": true
  },
  "attributes": {
    // ...
    "recipes": {
      "collection": "recipe",
      "via": "author"
    },
    "lastViewedRecipes": {
      "type": "component",
      "repeatable": true,
      "component": "users.last-viewed-recipes"
    }
  }
}
```

~When I add an entry for this component but let the "recipe" field empty, GraphQL throws the following error when querying:~

**Edit:** When a recipe that was previously linked through the component gets deleted, Graphql start to throws when querying the recipe through the component:

```sql
select distinct "recipes".* from "recipes" where "recipes"."id" = $1 and ("recipes"."published_at" is not null) limit $2 - invalid input syntax for type integer: "{}"
```

And all of the component entries "recipe" field are empty in the response.

The issue cannot be reproduced on the REST side.

### Steps to reproduce the behavior

1. Create a model "recipe" with a "title" field
2. Create a component "lastViewedRecipes" that has a relation field named "recipe" on model "recipe"
3. Use this component on the Users Permissions "User" model
4. Edit a User, add an entry in the component without filling the "recipe" field and save
5. Query the User you just edited through GraphQL, like so:

```gql
query user($id: ID!) {
  user(id: $id) {
    lastViewedRecipes {
      id
      recipe {
        id
      }
    }
  }
}
```

### Expected behavior

GraphQL shouldn’t throw. It should return a value for components that have a relation set and null otherwise.

### System

- Node.js version: 12.20.1
- NPM version: 6.14.10
- Strapi version: 3.5.4
- Database: PostgreSQL
- Operating system: MacOS

**Comment by LeBenLeBen** [comment] 2021-04-07 09:17
I’ve spent some time investigating this issue in a brand new project to try to find the origin. It’s actually a bit more complicate to replicate it. The problem doesn’t occur if you just create an entry in the component without a value for the relation. You need to put a value and save first. The problem occur when the entry to which the field was referencing is being deleted.

I’ve created a reproduction repo with detailed instructions to reproduce: https://github.com/LeBenLeBen/strapi-issue-9961

**Comment by LeBenLeBen** [comment] 2021-09-19 10:03
@derrickmehaffy I’ve attached a reproduction, can you please update the status?

**Comment by derrickmehaffy** [comment] 2021-10-04 21:55
That tag is for a 2nd or 3rd party to reproduce. At the moment the team is largely busy on v4 but it's in our backlog.

(Keep in mind the v4 most likely has already fixed this)

**Comment by derrickmehaffy** [comment] 2022-01-05 21:54
can't reproduce in v4, marking as closed

**Closed by derrickmehaffy** 2022-01-05 21:54 UTC
Labels: issue-type: bug, severity: medium, source: plugin:graphql, status: pending reproduction

**Comment by RodrigoLuglio** [comment] 2022-04-06 23:37
so who is using the version 3 is doomed? As there is no guide for migration to v4...
Anyone who is having this issue in production on version 3 is abandoned?
