### ISSUE TITLE
Dynamic zone with maximum of 1 shows "opened" Add a component view instead of closed

### ISSUE THREAD

**Issue by b5-studios** [strapi/strapi#8913] opened 2020-12-16 17:27 UTC
### Describe the bug

when i have a maximum set for components in a dynamic zone i'am still able to add as many components as i want,
since the button for "add a component" is in already in opened.

of course i can not save it, but i should not be able to have the possibility to add more components in the first place.

### Steps to reproduce the behavior

1. have a dynamic zone in a collection type which has a component. Min set to 1 max set to 1
2. make a new entry of this collection type and add a component
3. you see that you could add another component and the view is already open not collapsed (see screens=

### Expected behavior

Expected behaviour would be that instead of the opened status "X" the close status should be shown "+".
It works when i save the current entry and reopen it. the it shows the correct view.

### Screenshots

![Bildschirmfoto 2020-12-16 um 18 16 43](https://user-images.githubusercontent.com/25486533/102383605-08e47400-3fcc-11eb-88ae-8eb8681ed270.jpg)
![Bildschirmfoto 2020-12-16 um 18 16 53](https://user-images.githubusercontent.com/25486533/102383612-097d0a80-3fcc-11eb-8e22-6568aa622a79.jpg)
![Bildschirmfoto 2020-12-16 um 18 17 15](https://user-images.githubusercontent.com/25486533/102383616-0a15a100-3fcc-11eb-8b47-a3f487abe771.jpg)
![Bildschirmfoto 2020-12-16 um 18 19 50](https://user-images.githubusercontent.com/25486533/102383620-0b46ce00-3fcc-11eb-8212-847429fa51e7.jpg)

### System

- Node.js version: v14
- NPM version: current
- Strapi version: 3.3.4
- Database: Mogno
- Operating system: Mac

**Comment by derrickmehaffy** [comment] 2020-12-22 21:31
[test8913.zip](https://github.com/strapi/strapi/files/5732086/test8913.zip)

Can't reproduce in the above test project on v3.4.1

Please test on the latest version, if the issue persists reply back and we can reopen. For the moment, marking as closed.

**Closed by derrickmehaffy** 2020-12-22 21:31 UTC
