### ISSUE TITLE
Plugin graphql dont´t works 

### ISSUE THREAD

**Issue by mbistuer** [strapi/strapi#3872] opened 2019-08-29 21:37 UTC
Hello ,

After modifying a model in the admin panel, the reboot has been blocked and from that moment the graphql plugi does not work, I unistallled  it I deleted the database and it still does not work
The error return this error 
The variable strapi.groups is undefined ...
`TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
node_modules/strapi-plugin-graphql/services/Schema.js:160:25)
`
Any idea?

**Code snippets**

**System**
- Node.js version: v10.16.0
- Strapi version: 3.0.0-beta.15
- Database:Mysql
- Operating system:Macos

**Comment by janober** [comment] 2019-08-30 08:22
Looks like I have the same issue since I updated from beta14 to beta15.

**Comment by janober** [comment] 2019-08-30 08:56
Sadly also after going back to beta14 it does still not work again (blew also away package-lock and node_modules). Wonder if some other dependency released a new version which breakes things...

**Comment by janober** [comment] 2019-08-30 09:00
Just remembered that I did a backup of the whole folder (including node_modules) like a week ago. So did simply copy its whole node_modules folder in my current strapi-folder and now it works again perfectly. So must really be a dependency.

**Comment by derrickmehaffy** [comment] 2019-08-30 09:25
@mbistuer please properly fillout the required template:

```
System

Node.js version: nodeLTS
Strapi version: latest version
Database:Mysql
Operating system:Macos
```

specifically these two:
```
Node.js version: nodeLTS
Strapi version: latest version
```

**Comment by janober** [comment] 2019-08-30 09:30
As I have the same problem I can also supply that information.

**System**

Node.js version: v10.16.0
Strapi version: 3.0.0-beta.14 & 3.0.0-beta.15
Database: Postgres 10.9
Operating system: Ubuntu Linux 18.04.3 LTS

**Comment by derrickmehaffy** [comment] 2019-08-30 10:05
@janober @mbistuer can you please look at your package-lock.json or yarn.lock and provider the resolved graphql package version

**Comment by janober** [comment] 2019-08-30 10:11
The one it worked with:
graphql@14.4.2

The one which installs now:
graphql@14.5.4

**Comment by mbistuer** [comment] 2019-08-30 10:11
`"version": "3.0.0-next.20",
      "resolved": "https://registry.npmjs.org/strapi-plugin-graphql/-/strapi-plugin-graphql-3.0.0-next.20.tgz",
      ",`

**Comment by derrickmehaffy** [comment] 2019-08-30 10:18
Checking @janober for any breaking changes upstream

**Comment by janober** [comment] 2019-08-30 10:20
Did manually install some older versions of the different graphql libraries which get used. But it still did not work get it to work untill I downgraded
`strapi-plugin-graphql@3.0.0-next.20`
to
`strapi-plugin-graphql@3.0.0-beta.14`

Then everything did run again fine. So the issue gets caused by this package.

**Comment by derrickmehaffy** [comment] 2019-08-30 10:21
https://github.com/graphql/graphql-js/releases/tag/v14.5.4

I don't see any major changes

**Comment by janober** [comment] 2019-08-30 10:22
Ah yes it also works with graphql@14.5.4 it is for sure the `strapi-plugin-graphql` package which causes the problems.

**Comment by derrickmehaffy** [comment] 2019-08-30 10:30
So there is another depends causing the issue, we need to track down what that is

**Comment by janober** [comment] 2019-08-30 10:33
Do not understand. You do not think the issue is in "strapi-plugin-graphql" itself?

Can sadly not find any information about the `strapi-plugin-graphql@3.0.0-next.20` version and what is different to the `strapi-plugin-graphql@3.0.0-beta.15` (which also still works like beta.14).

**Comment by janober** [comment] 2019-08-30 10:52
Actually should not really install the next version anyway or not? If I understand it correctly that is the development versions where bugs are expected?
It is defined like that in my package.json `"strapi-plugin-graphql": "^3.0.0-beta.14"` (guess already from the template/setup-script).

Expected that it then only installs other `beta` versions and not the `next` ones. Apparently that is not the case. So I guess for "regular" users (like I) which do not want to life on the edge (just nearby as also the other version is still beta) should simply changing it to: `"strapi-plugin-graphql": "3.0.0-beta.14"` to "solve" the problem for them.

**Comment by derrickmehaffy** [comment] 2019-08-30 10:54
Indeed the next versions are not for production usage, they are developmental builds but some light testing needs to be done at some point as these changes are due to be released in beta.16.... lol

**Comment by janober** [comment] 2019-08-30 11:05
Ah yes should be addressed for sure ;-) But I guess the person which maintains that package and probably made the change (which broke it) knows immediately what is wrong and can fix it very fast. No need for me to spend now hours trying to set up the development environment, read code, ... and try to fix it.

**Comment by janober** [comment] 2019-08-30 11:07
@mbistuer So simply change your dependency `"strapi-plugin-graphql": "^3.0.0-beta.14"` to `"strapi-plugin-graphql": "3.0.0-beta.15"` and then run `npm install strapi-plugin-graphql`. It should then work fine.

**Comment by mbistuer** [comment] 2019-08-30 12:01
> @mbistuer So simply change your dependency `"strapi-plugin-graphql": "^3.0.0-beta.14"` to `"strapi-plugin-graphql": "3.0.0-beta.15"` and then run `npm install strapi-plugin-graphql`. It should then work fine.
@janober  It does not work for me

**Comment by derrickmehaffy** [comment] 2019-08-30 12:05
@alexandrebodin have you noticed anything odd with the GraphQL plugin from develop branch?

**Comment by janober** [comment] 2019-08-30 12:08
@mbistuer Very strange it should work unless there is more wrong for you for some reason.
To be sure you can just try to blow away `package-lock.json` file and the `node_modules` folder and then do another `npm install`. But if that does not work I sadly have no idea anymore right now why it should not work for you when it does for me.

**Comment by mbistuer** [comment] 2019-08-30 12:10
it worked for me uninstalled everything and then install it with` strapi install graphql`

**Closed** 2019-08-30 12:23 UTC

**Comment by derrickmehaffy** [comment] 2019-09-02 08:56
@janober @mbistuer I found the issue if you are on beta.15

In your package.json make sure you don't have a carrot on the version: 
**BAD** - `"strapi-plugin-graphql": "^3.0.0-beta.15",`
**GOOD** - `"strapi-plugin-graphql": "3.0.0-beta.15",`
