### ISSUE TITLE
Adding required fields when records already exist.

### ISSUE THREAD

**Issue by t2** [strapi/strapi#2621] opened 2019-01-13 16:04 UTC
**Informations**
- **Node.js version**: 
v10.11.0
- **NPM version**: 
6.5.0
- **Strapi version**: 
3.0.0-alpha.18
- **Database**: 
postgres
- **Operating system**: 
Mac OS Mojave

**What is the current behavior?**
When adding a required field to a content type where records already exist there is an error thrown because the existing records are not getting the default value set on save.

```
(node:28797) UnhandledPromiseRejectionWarning: error: column "testing" contains null values
    at Connection.parseE (/Users/Trent/Projects/airship/babypalooza/babypalooza-api/node_modules/pg/lib/connection.js:555:11)
    at Connection.parseMessage (/Users/Trent/Projects/airship/babypalooza/babypalooza-api/node_modules/pg/lib/connection.js:380:19)
    at Socket.<anonymous> (/Users/Trent/Projects/airship/babypalooza/babypalooza-api/node_modules/pg/lib/connection.js:120:22)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Client_PG._query (/Users/Trent/Projects/airship/babypalooza/babypalooza-api/node_modules/knex/lib/dialects/postgres/index.js:240:12)
    at Client_PG.query (/Users/Trent/Projects/airship/babypalooza/babypalooza-api/node_modules/knex/lib/client.js:192:17)
    at Runner.<anonymous> (/Users/Trent/Projects/airship/babypalooza/babypalooza-api/node_modules/knex/lib/runner.js:138:36)
From previous event:
    at /Users/Trent/Projects/airship/babypalooza/babypalooza-api/node_modules/knex/lib/runner.js:47:21
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
    at process.topLevelDomainCallback (domain.js:121:23)
From previous event:
    at Runner.run (/Users/Trent/Projects/airship/babypalooza/babypalooza-api/node_modules/knex/lib/runner.js:33:30)
    at Raw.Target.then (/Users/Trent/Projects/airship/babypalooza/babypalooza-api/node_modules/knex/lib/interface.js:23:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:28797) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28797) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-01-13T13:39:00.011Z] debug ⛔️ Server wasn't able to start properly.
[2019-01-13T13:39:00.012Z] error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load
```

**Steps to reproduce the problem**
1. Click 'Content Type Builder' in main navigation under Plugins.
2. Click on the 'User' row in the table.
3. Click Add New Field
4. Select the Number field type and under Advanced Settings, choose Required field and set the default to 0.
5. Click Continue
6. Click Save in the top right. 

When the serve tries a restart, you will receive the error.

**What is the expected behavior?**
I would expect that the default value is required if you choose the Required field setting and I would also expect all existing records to be updated to that default value.

**Suggested solutions**
I am still learning this code base so I do not yet have a solution in mind. I am trying to determine if this is a knex/bookshelf issue or a Strapi issue.

**Comment by lauriejim** [comment] 2019-01-13 17:41
Hello @t2 ! thank you to report this issue.

Actually this issue is "normal" cause you change your data model after creating some data.

The question we have to ask is, does it Strapi work to update all you existing data to update previous `null` value to `?` (we don't know, `empty string` ?) value. You can understand it's a little be tricky.
It's the same question if you start with `price` attribute with `decimal` spec and you move to `integer`. Have we to convert `12.99` to `12` or `13` ? It's a complexe question to manage a model update (for an existing attribute).

In a futur yes we will be able to make transition but for now we are not able to manage this feature.

So for now I suggest you to create a quick script that update all you `null` to what you want.

**Comment by t2** [comment] 2019-01-13 17:46
@lauriejim I agree completely! Where would such a script go? In the Rails world we would have a migration that I would edit to have this business logic take place along side the schema update. Is their documentation showing where I would put a script like this?

**Comment by lauriejim** [comment] 2019-01-13 18:16
You can see our roadmap here - https://portal.productboard.com/strapi. There is a **Data Management** section and we talk about that in intern. Feel free to add a feedback here 😉

Bookshelf can't be load by Strapi (that the issue log) so we will not be able to exec any script that use a database. You will have to create a standalone script for that.

**Comment by lauriejim** [comment] 2019-01-13 18:19
Some things to help you.

```
// Database connection
var knex = require('knex')({
  client: 'pg',
  connection: {
    ...yourDatabaseConnection
  }
});

var bookshelf = require('bookshelf')(knex);

var YourModel = bookshelf.Model.extend({
  tableName: 'yourTableName',
});

Then exec queries you need to fectAll and then Update data.
```

**Comment by t2** [comment] 2019-01-14 18:48
@lauriejim Happy to close this if you feel like it's necessary.

**Comment by nmaxcom** [comment] 2019-07-04 05:21
Same here. I just realized only one type had the first letter uppercase, so I changed from "Titulo" to "titulo" to be consistent. When I hit save the admin site said it had to restart the server, ok. And then it showed:

```
The restart takes longer than expected
The server should have restarted, please check your logs in the terminal
```

So I did:

```log
[2019-07-04T04:52:43.841Z] debug GET eb3367b483a67f72c65065392b1d2a2f.png (9 ms)
[2019-07-04T04:54:21.771Z] debug PUT /content-type-builder/models/blogpost (2364 ms)
[2019-07-04T04:54:21.777Z] info The server is restarting

[2019-07-04T04:54:32.952Z] warn The SQL database indexes haven't been generated successfully. Please enable the debug mode for more details.
{ error: column "titulo" contains null values
    at Connection.parseE (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 126,
  severity: 'ERROR',
  code: '23502',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'blogposts',
  column: 'titulo',
  dataType: undefined,
  constraint: undefined,
  file: 'tablecmds.c',
  line: '4575',
  routine: 'ATRewriteTable' }
[2019-07-04T04:54:33.182Z] debug ⛔️ Server wasn't able to start properly.
[2019-07-04T04:54:33.182Z] error error: column "titulo" contains null values
    at Connection.parseE (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/Users/merl/STUFF/Code/Todo VAC/webVac/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
merl /Users/merl/STUFF/Code/Todo VAC/webVaC $
```

I went to check the db and it was still "Titulo", so "titulo" didn't exist. I made this change after generating the first blog post, a dummy post. The "id" field was 1. Also, I added a new field named "publicado".

I manually corrected to "titulo" in the db. So now I can't run strapi because it complains that: `error: column "publicado" contains null values`. But I can't seem to be able to add this one manually, PostgreSQL won't allow me.

Hence I'm stuck.

**Comment by lauriejim** [comment] 2019-07-23 15:40
I close this issue because of the `require` option is due to the data management.
And the last issue mentioned is a duplicate of this issue https://github.com/strapi/strapi/issues/2998

**Closed by lauriejim** 2019-07-23 15:40 UTC
Labels: priority: high, status: confirmed, type: bug 🐛
