### ISSUE TITLE
Send mail doesn't work when called from other app, but works if called from postman

### ISSUE THREAD

**Issue by Ant-V** [strapi/strapi#7627] opened 2020-08-27 13:33 UTC
**Describe the bug**
I've build a custom route where it just takes all the data and sends it to an email

When I call the api through postman, it works perfectly.
When I call it through the nuxtjs app I'm planning to use strapi with, it catches the following error in the console:
`````
Error: can not connect to any SMTP server
    at tryConnect (/..../strapi/node_modules/sendmail/sendmail.js:88:49)
    at Socket.<anonymous> (/..../strapi/node_modules/sendmail/sendmail.js:94:13)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
`````

**Steps to reproduce the behavior**
Call the route via postman => Works
Call it through Axios in Nuxt => Error: can not connect to any SMTP server

**Expected behavior**
It should either work or not work...

**Code snippets**
This is the code:

`````
async formSubmit(ctx) {
    try {
      // console.log(ctx.request.body)
      const { touser, client } = (ctx.request.body)
      // const touser = touser
      const subject = "New Test Form: " + (client.name ? client.name : 'unknown name');
      var text = "Your lack of html is rather annoying...\r\n\r\n"
      var html = `<h1>${(client.name ? client.name : 'unknown name')} has submitted a Test Form</h1><br><table><tbody>`
      for (var key in client) {
        text += `${key}: ${client[key]}\r\n`
        html += '<tr><td style="text-transform: capitalize;text-align:right">' + key + ' </td><td>' + client[key] + ' </td></tr>'
      }
      html += '</tbody></table>'
      await strapi.plugins['email'].services.email.send({
        to: touser,
        from: 'no-reply@non-existing-domain.com',
        subject,
        text,
        html,
      });
    } catch (ex) {
      console.log(ex)
      return { error: "We could not submit your form. Please try again later!" }
    }
    return { message: "success" }
  }
`````
And this is my custom route.js

`````
  ...
    {
      "method": "POST",
      "path": "/wt/form-submit",
      "handler": "wt.formSubmit",
      "config": {
        "policies": []
      }
    }
`````

**System**

- Node.js version: v13.12.0
- NPM version: 6.14.7
- Strapi version: 3.1.4
- Database: mySQL
- Operating system: MacOS 10.15.6

**Additional context**
I do not know if it is of any significance, but the custom route has no model attached to it.

**Comment by derrickmehaffy** [comment] 2020-08-31 17:13
I've tested this myself and couldn't reproduce the issue, it would appear your sendmail settings aren't being loaded? Are the two tests done on different servers? (Remote server vs local?)

**Comment by Ant-V** [comment] 2020-08-31 21:19
So, here's the weird thing, I cannot replicate it at this time either. After a restart of strapi (or maybe more) it started working perfectly.
Both tests were done locally, so localhost:1337 for strapi, localhost:3000 for Nuxt and localhost for Postman...

I have honestly no idea how it happened and most important how it got fixed...

**Comment by derrickmehaffy** [comment] 2020-08-31 21:37
:thinking: For now I'll close it @Ant-V but please don't hesitate to let us know if the ugly bug rears it's head again. Glad it's working for you though. :wink:

**Closed by derrickmehaffy** 2020-08-31 21:37 UTC
Labels: type: help wanted
