### ISSUE TITLE
Date field advanced settings throws error in content type builder when type is set to datetime.

### ISSUE THREAD

**Issue by westende** [strapi/strapi#18468] opened 2023-10-17 07:50 UTC
### Required System information

- Node.js version: 18.18
- NPM version: 9.8.1
- Strapi version: 4.14.4
- Database: sqlite
- Operating system: osx
- Is your project Javascript or Typescript: Javascript

### Describe the bug

When opening the advanced settings of a date field in the content type builder that is set to type datetime we get a white screen (WSOD). The console logs an error:

```
TypeError: Ze.toDate is not a function
    j DateTimePicker.mjs:100
    React 13
    onTabClick Tabs.mjs:45
    ke Tabs.mjs:118
    React 27
    Redux 3
    Gf React
    Redux 4
    Ae localePermissionMiddleware.js:8
    Bn extendCTBAttributeInitialDataMiddleware.js:72
    dn extendCTBInitialDataMiddleware.js:27
    jt addCommonFieldsToInitialDataMiddleware.js:23
    current index.js:126
react-dom.production.min.js:189:29
    React 14
    onTabClick Tabs.mjs:45
    ke Tabs.mjs:118
    React 27
    Redux 3
    Gf React
    Redux 4
    Ae localePermissionMiddleware.js:8
    Bn extendCTBAttributeInitialDataMiddleware.js:72
    dn extendCTBInitialDataMiddleware.js:27
    jt addCommonFieldsToInitialDataMiddleware.js:23
    current index.js:126
```

### Steps to reproduce the behavior

1. Setup a clean Strapi project.
2. Create a content type.
3. Add a date field and set the type to "datetime".
4. Click "Advanced settings" tab.
5. White screen with console error.

### Expected behavior

The advanced settings for this field with the datetime type should be displayed.

**Comment by martinbeentjes** [comment] 2023-10-18 09:54
I'm also seeing this behavior.

**Comment by Boegie19** [comment] 2023-10-18 16:28
@martinbeentjes Issue is I think strapi frontend not giving it a datetime value.

duplicate of https://github.com/strapi/strapi/issues/18123

**Closed by Boegie19** 2023-10-18 16:28 UTC
