### ISSUE TITLE
Error while installing dependencies

### ISSUE THREAD

**Issue by fedehiga** [strapi/strapi#19924] opened 2024-03-26 01:41 UTC
### Required System information

- Node.js version: 18.17
- NPM version: 9.6.3
- Strapi version: 5
- Database: SQLite
- Operating system: Mac OS 12.6.7
- Is your project Javascript or Typescript: Javascript

### Steps to reproduce the behavior

1. Run 'npx create-strapi-app@beta strapi-test' in terminal
2. Choose your installation type 'Quickstart'
3. See error

### Expected behavior

I'm expecting Strapi 5 beta to install successfully, but i'm getting 'npm ERR! ERESOLVE unable to resolve dependency tree' instead 

### Screenshots

![Screen Shot 2024-03-25 at 22 37 44](https://github.com/strapi/strapi/assets/55226858/dd12978b-4ff1-4e7c-be7a-2327f16bea27)

**Comment by egyleader** [comment] 2024-03-26 09:44
same error happened to me : 

```node
npx create-strapi-app@beta strapi-test --quickstart       


Need to install the following packages:
create-strapi-app@5.0.0-beta.0
Ok to proceed? (y) y
Creating a quickstart project.
Creating a new Strapi application at strapi-test.
Creating files.
Error while installing dependencies:
npm WARN config production Use `--omit=dev` instead.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config 
npm WARN config     Default value does install optional deps unless otherwise omitted.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: strapi-test@0.1.0
npm ERR! Found: @strapi/strapi@5.0.0-beta.0
npm ERR! node_modules/@strapi/strapi
npm ERR!   @strapi/strapi@"5.0.0-beta.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @strapi/strapi@"^4.0.0" from @strapi/plugin-users-permissions@5.0.0-beta.0
npm ERR! node_modules/@strapi/plugin-users-permissions
npm ERR!   @strapi/plugin-users-permissions@"5.0.0-beta.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /[reducted]/.npm/_logs/2024-03-26T09_38_24_515Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/egyleader/.npm/_logs/2024-03-26T09_38_24_515Z-debug-0.log
 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following command:
cd strapi-test && npm install

```

**Comment by pointout** [comment] 2024-03-26 11:17
same here:
Node.js version: v20.11.0
NPM version: 10.4.0
Strapi version: 5
Database: SQLite
Operating system: Windows 11

**Comment by joshuaellis** [comment] 2024-03-27 08:22
duplicate of #19903

**Closed by joshuaellis** 2024-03-27 08:22 UTC
