### ISSUE TITLE
White screen with stacktrace after uploading media asset

### ISSUE THREAD

**Issue by maikdiepenbroek** [strapi/strapi#17988] opened 2023-09-08 19:34 UTC
### Required System information

- Node.js version: v18.12.1
- NPM version: 9.1.3
- Strapi version: 4.13.3 (after downgrading to 4.11.0 the issue is gone)
- Database: mysql
- Operating system: MacOs Ventura
- Is your project Javascript or Typescript: Typescript

### Describe the bug

After uploading an asset, the media library page completely breaks with a stacktrace:

`Uncaught TypeError: Failed to construct 'URL': Invalid URL`
After adding a debugger i see the following happening:
1. Upload phase goes fine, URL gets parsed as: `blob:http://localhost:1337/public/asset-name.png`
2. Page reloads, tries to load asset, URL gets parsed as `/public/asset-name.png` which breaks

### Steps to reproduce the behavior

1. Go to http://localhost:1337/admin/plugins/upload
3. Click on add media assets
4. Upload asset
5. See error

### Expected behavior

I expect the error not to be there, so that i can upload an asset succesfully

### Code snippets
(main.99afe32f.js:1918 Uncaught TypeError: Failed to construct 'URL': Invalid URL)

### Additional context

After downgrading to 4.11 the problem is gone.

**Comment by alvarolozano** [comment] 2023-09-08 21:42
Similar issue: #17931

**Comment by jobe451** [comment] 2023-09-09 04:59
I have the same issue, but not only when uploading. whenever I access the media library to view any folder with images in it, I get this typo of error (blank screen with Failed to construct 'URL': Invalid URL)

**Comment by growley-git** [comment] 2023-09-09 17:37
Confirmed this issue as well, however after upgrading just now to 14.3.3 the issue still remains.

> Seems to be solved in: #17931 (PR #17967)

**Comment by dgrebb** [comment] 2023-09-09 22:40
There's a second, open PR for this: #17982, which will add a fallback when `window.strapi.backendURL` is an empty string, which is where #17967 left off.

If the urge to apply a patch in the meantime is irresistible, I left some comments in #17982 that should cover all bases, both in `development` and `production` modes, local and higher environments.

Cheers!

**Comment by joshuaellis** [comment] 2023-09-11 07:20
closing as duplicate of https://github.com/strapi/strapi/issues/17931

**Closed by joshuaellis** 2023-09-11 07:20 UTC
Labels: status: duplicate
