### ISSUE TITLE
author role should not replace others users images 

### ISSUE THREAD

**Issue by fabiel-leon** [strapi/strapi#10366] opened 2021-05-23 17:43 UTC
### Describe the bug

The author role should not replace images in multimedia library that are not owned by him.

### Steps to reproduce the behavior

0. Create and strapi app `yarn create strapi-app my-project`
1. Create an admin  and a author user
2. Upload an image to multimedia library with the admin user
3. Replace image with the author user 
4. See replaced image

### Expected behavior

Dont allow author user to edit other user image

### System

- Node.js version: 12.21
- NPM version: 6.14.11
- Strapi version: 3.6.2
- Database: Mongodb
- Operating system: Ubuntu 18.04.5 LTS

**Comment by derrickmehaffy** [comment] 2021-05-25 20:21
I believe this is a duplicate of: https://github.com/strapi/strapi/issues/10221 which should be fixed in 3.6.3

**Closed by derrickmehaffy** 2021-05-25 20:21 UTC
Labels: status: duplicate
