### ISSUE TITLE
cannot findAll a deck of related 90k cards 

### ISSUE THREAD

**Issue by ctrngk** [strapi/strapi#8878] opened 2020-12-12 03:40 UTC
## Bug report
cannot findAll a deck of related 90k cards 

### Describe the bug
I have a deck with related 90k cards.

When I visit https://localhost:1337/cards, it renders the first 100 cards.
When I visit https://localhost:1337/cards/count, it renders 95002
When I visit https://localhost:1337/decks/count, it renders 1
When I visit https://localhost:1337/decks, it is not working. The error message is as follows

<details>
  <summary>When I visit https://localhost:1337/decks, it is not working. The error message is as follows</summary>
  
  ## Terminal console message
[2020-12-12T02:58:11.591Z] debug GET /decks (9591 ms) 500
[2020-12-12T02:58:18.326Z] error error: select distinct "upload_file_morph".* from "upload_file_morph" where "field" = $1 and "upload_file_morph"."related_id" in ($2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, .... )
bind message has 28255 parameter formats but 0 parameters
    at Parser.parseErrorMessage (/Users/kmac/src/github/boki/boki-backend/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Users/kmac/src/github/boki/boki-backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/kmac/src/github/boki/boki-backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/kmac/src/github/boki/boki-backend/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (node:events:329:20)
    at addChunk (node:internal/streams/readable:304:12)
    at readableAddChunk (node:internal/streams/readable:279:9)
    at Socket.Readable.push (node:internal/streams/readable:218:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:192:23)
From previous event:
    at processImmediate (node:internal/timers:463:21)
From previous event:
    at Sync.<anonymous> (/Users/kmac/src/github/boki/boki-backend/node_modules/bookshelf/lib/sync.js:204:8)
From previous event:
    at EagerRelation.eagerFetch (/Users/kmac/src/github/boki/boki-backend/node_modules/bookshelf/lib/eager.js:30:8)
    at EagerRelation.<anonymous> (/Users/kmac/src/github/boki/boki-backend/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at /Users/kmac/src/github/boki/boki-backend/node_modules/bookshelf/lib/eager.js:96:73
From previous event:
    at EagerRelation._eagerLoadHelper (/Users/kmac/src/github/boki/boki-backend/node_modules/bookshelf/lib/eager.js:83:23)
    at Sync.<anonymous> (/Users/kmac/src/github/boki/boki-backend/node_modules/bookshelf/lib/eager.js:31:31)
From previous event:
    at EagerRelation.eagerFetch (/Users/kmac/src/github/boki/boki-backend/node_modules/bookshelf/lib/eager.js:31:8)
    at EagerRelation.<anonymous> (/Users/kmac/src/github/boki/boki-backend/node_modules/bookshelf/lib/base/eager.js:67:14)
From previous event:
    at Child._handleEager (/Users/kmac/src/github/boki/boki-backend/node_modules/bookshelf/lib/collection.js:527:73)
    at Child.<anonymous> (/Users/kmac/src/github/boki/boki-backend/node_modules/bookshelf/lib/collection.js:179:27)
    at processImmediate (node:internal/timers:463:21)
From previous event:
    at Child.<anonymous> (/Users/kmac/src/github/boki/boki-backend/node_modules/bookshelf/lib/collection.js:177:12)
From previous event:
    at Child.fetchAll (/Users/kmac/src/github/boki/boki-backend/node_modules/bookshelf/lib/model.js:878:10)
    at Object.find (/Users/kmac/src/github/boki/boki-backend/node_modules/strapi-connector-bookshelf/lib/queries.js:66:8)
    at fn (/Users/kmac/src/github/boki/boki-backend/node_modules/strapi-database/lib/queries/helpers.js:31:54)
    at Object.find (/Users/kmac/src/github/boki/boki-backend/node_modules/strapi-database/lib/queries/helpers.js:15:24)

</details>

<details>
  <summary>when I visit deck inside localhost:1337/admin, it is not working too. The error message is as follows</summary>
  
  ## Terminal console message
GET /content-manager/explorer/application::deck.deck/count?_limit=10&_sort=title%3AASC&_start=0 (38 ms) 200
[2020-12-12T03:33:25.932Z] error error: bind message has 29468 parameter formats but 0 parameters
    at Parser.parseErrorMessage (/Users/kmac/src/github/boki/boki-backend/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Users/kmac/src/github/boki/boki-backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/kmac/src/github/boki/boki-backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/kmac/src/github/boki/boki-backend/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
From previous event:
    at Client_PG._query (/Users/kmac/src/github/boki/boki-backend/node_modules/knex/lib/dialects/postgres/index.js:234:12)
    at Client_PG.query (/Users/kmac/src/github/boki/boki-backend/node_modules/knex/lib/client.js:158:17)
    at Runner.query (/Users/kmac/src/github/boki/boki-backend/node_modules/knex/lib/runner.js:135:36)
    at /Users/kmac/src/github/boki/boki-backend/node_modules/knex/lib/runner.js:39:23
From previous event:
    at Runner.run (/Users/kmac/src/github/boki/boki-backend/node_modules/knex/lib/runner.js:25:16)
    at Builder.Target.then (/Users/kmac/src/github/boki/boki-backend/node_modules/knex/lib/interface.js:14:43)
    at processImmediate (internal/timers.js:461:21)
[2020-12-12T03:33:25.934Z] debug GET /content-manager/explorer/application::deck.deck?_limit=10&_sort=title%3AASC&_start=0 (8033 ms) 500
</details>

- Node.js version: node 12
- NPM version: 7.0.8
- Strapi version: 3.2.5
- Database: postgresql
- Operating system: macOS

**Comment by derrickmehaffy** [comment] 2020-12-22 21:17
We need the code of your `decks` endpoint as based on that query it doesn't look like a standard query we provide.

Two other side points:

- We **very strongly** advise against queries like this as they are extremely destructive to performance. We suggest you use paging instead. Such as:

`GET localhost:1337/cards?_limit=250&deck=theDeckID&_start=0`
`GET localhost:1337/cards?_limit=250&deck=theDeckID&_start=250`
`GET localhost:1337/cards?_limit=250&deck=theDeckID&_start=500`
`GET localhost:1337/cards?_limit=250&deck=theDeckID&_start=750`

- Can you please test on the latest release of Strapi (v3.4.1)

**Comment by derrickmehaffy** [comment] 2021-04-15 18:15
Closing as not a bug

**Closed by derrickmehaffy** 2021-04-15 18:15 UTC
Labels: status: can't reproduce
