### ISSUE TITLE
Graphql query return incorrect value for related data on One-to-Many relation

### ISSUE THREAD

**Issue by fsc7** [strapi/strapi#2238] opened 2018-10-31 12:55 UTC
**Informations**
- **Node.js version**: v11.0.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: PostgreSQL
- **Operating system**: Ubuntu 18.04

**What is the current behavior?**
I have one table RFQ (Request for Quotation) which has a Purchaser, a purchaser may have many RFQs.
My query is 
```
{
  rfqs {
    id
    date
    purchaser {
      id
      name
      email
    }
  }
}
```

In the database and Strapi Admin Interface I receive the right information about purchaser (id, name and email). But when I make a graphql request it returns wrong information. It repeats the info about the first purchaser in the first row.
It happens in other classes with relations as well.

**Steps to reproduce the problem**
Create two tables with one to many relationship.
Make a query retrieving related data.

**What is the expected behavior?**
Return correct information for all rows

**Suggested solutions**
No suggestion.

**Comment by fsc7** [comment] 2018-10-31 13:02
REST Request works fine.

**Comment by lauriejim** [comment] 2018-11-01 13:37
I think your issue is a duplicate of this one. Can you confirm https://github.com/strapi/strapi/issues/2192

**Comment by fsc7** [comment] 2018-11-01 17:29
@lauriejim It is not exact the same problem but it can be related. My problem happens with simple one-to-many relation.

**Comment by fsc7** [comment] 2018-11-05 15:38
Hello @lauriejim ,

I will not submit it as a merge request because I think is not yet a complete solution. But it solves partially the problem and I believe it might help somehow to identify where the problem is.
In plugins/graphql/services/Resolvers.js
line 376
I changed 
```
            if (association.type === 'model') {
              params.id = obj[association.alias];
            }
```
to
```
            if (association.type === 'model') {
              if(!isNaN(obj[association.alias])){
                params.id = obj[association.alias];
              } else {
                params.id = obj[association.alias].id;
              }
            }
```
And now I can get the correct response.
Hope it helps somehow and you can find the proper solution.

Best regards,

Felipe

**Comment by NickBolles** [comment] 2018-11-08 04:31
Possibly fixed by #1948? @kamalbennani could you weigh in?

**Comment by fsc7** [comment] 2018-11-08 08:17
Hello @NickBolles,

Thanks for the response, I really liked to give it a try but unfortunately my knowledge is limited.
Sorry for the newbie question, but here it goes anyway: I have a strapi server running, how can I test this pull request and revert it for the original state if necessary?

**Comment by shuzootani** [comment] 2018-11-11 09:17
Bonjour @lauriejim
I guess I'm having the same kind of error.
GraphQL query returns wrong values.(rest looks good)

on my side, even for `role` that has a relation with user model by default, it returns `Administrator` for all users, which is supposed to be owned by only one user.

<img width="1279" alt="screen shot 2018-11-11 at 1 01 18" src="https://user-images.githubusercontent.com/19385183/48311007-5371a780-e54d-11e8-996a-e90f0d61fbc5.png">

please let me know if I'm doing wrong.
Thanks

**Comment by fsc7** [comment] 2018-11-12 08:09
@shuzootani You are doing nothing wrong. Strapi is. GraphQL plugin is not fully functional right now.

**Closed** 2018-11-18 14:04 UTC
Labels: priority: high, status: confirmed, type: bug 🐛
