### ISSUE TITLE
Reset Rassword return 204 even if user doesn't exist

### ISSUE THREAD

**Issue by amin-da75** [strapi/strapi#9001] opened 2020-12-27 11:37 UTC
### Describe the bug

Reset Password doesn't return Error when user doesn't exist or entered wrong email 

### Steps to reproduce the behavior

1. **POST** /auth/forgot-password { email: 'thatdoesnt@exist.com' }
2. Receive `204`

### Expected behavior

return 404 or anything like that to show the problem

### Screenshots

![bugreport](https://user-images.githubusercontent.com/66317752/103169866-c8e78180-4854-11eb-8768-3d4bcb0b67a0.jpg)

### System

- Node.js version: v14.15.1
- NPM version: 6.14.8
- Strapi version: 3.4.0
- Database: Mysql
- Operating system: Win10

**Comment by derrickmehaffy** [comment] 2021-01-22 20:37
Tested on v3.4.4 and could not reproduce. Marking as closed until we have more information

![image](https://user-images.githubusercontent.com/8593673/105543350-ecb4b080-5cb6-11eb-910b-d47ab7e446f4.png)

**Closed by derrickmehaffy** 2021-01-22 20:37 UTC
Labels: status: can't reproduce

**Comment by amin-da75** [comment] 2021-01-23 09:10
My bad, it's /admin/forgot-password, not /auth/forgot-password.
