### ISSUE TITLE
Cannot create content-types with content-type-builder permission issue??

### ISSUE THREAD

**Issue by P0SEID0N** [strapi/strapi#13669] opened 2022-07-01 03:54 UTC
### Required System information

- Node.js version: 16
- NPM version: 8.11.0
- Strapi version: 4.2.2
- Database: SQLITE
- Operating system: Windows

### Describe the bug

I have installed multiple different versions of Strapi both on windows and on docker implementations. I have used create-strapi-app and create-strapi-starter

The only version of Strapi that does not have the below problem is V3:

In the content-type-builder plugin there is a default User type but I cannot add any fields to it nor can I make any new Content-types (Collection types, Single types, or Components) When you click on any of the following:

![image](https://user-images.githubusercontent.com/21989712/176819613-5530da1e-a4ad-41e4-bf79-4908c54f5758.png)

Nothing happens, in the network tab the only thing that happens is a call is fired on the /track URL I assume this is some sort of strapi.api tracking functionality. But the actual functionality to create new content-types does not work.

When trying to navigate directly to: http://localhost:1337/admin/plugins/content-type-builder/ it redirects to one of the content types: http://localhost:1337/admin/plugins/content-type-builder/content-types/api::article.article

I have done some investigations, I have installed several times both with MYSQL and SQLITE and have come to the conclusion that there must be some permission error that is happening that is controlling the routing of the admin panel to not allow for the proper use of the content-type-builder plugin. 

Any assistance would be appreciated, I can have been trying to figure out the issue for a few hours now and it would be super helpful if someone could give some assistance to figure this out as it might take way less time to someone who is familiar with the code base.

The only thing I have not tried is forking the strapi repo and installing each plugin individually instead of using the create-strapi-app. 

### Steps to reproduce the behavior

1. Install new strapi using npx create-strapi-app@latest project-name
2. This will bring you to create an admin user. Create one.
3. Then you will get to the home page where it asks you to create a Content-type I click on that button and it directs me to one of the content-types not the content-type-builder modal that opens in the V3 example.
4. The error should be all over this page. None of the create buttons work, none of the add buttons work (see the screenshot I attached above)

### Expected behavior

I expect to be able to create content-types and edit them

### Screenshots

![image](https://user-images.githubusercontent.com/21989712/176819613-5530da1e-a4ad-41e4-bf79-4908c54f5758.png)

**Comment by derrickmehaffy** [comment] 2022-07-07 17:09
Unable to reproduce, can you possibly record a short video showing the issue? 

Tested on Windows, Linux, and Mac. Note that we do not have a docker container for v4, only v3 so didn't test a custom docker container but it should work there as well as we have various users (including internal engineers) using docker daily.

Marking as closed for now until we have new information then I can reopen this.

**Closed by derrickmehaffy** 2022-07-07 17:09 UTC

**Comment by blackMoja** [comment] 2022-07-19 11:10
I have the same issue. 👀

![스크린샷 2022-07-19 오후 8 09 12](https://user-images.githubusercontent.com/24522378/179736550-901787c7-372a-4fcc-b5ac-a91148daf8bb.png)

**Comment by derrickmehaffy** [comment] 2022-07-27 21:57
> I have the same issue. eyes
> 
> My postgreSql version is 13.2
> 
> ![스크린샷 2022-07-19 오후 8 09 12](https://user-images.githubusercontent.com/24522378/179736550-901787c7-372a-4fcc-b5ac-a91148daf8bb.png)

That's a different issue, please open a new bug report and follow the template.
