### ISSUE TITLE
Can not create new admin user and can not update roles of admins

### ISSUE THREAD

**Issue by alicanso** [strapi/strapi#18702] opened 2023-11-08 14:36 UTC
### Required System information

- Node.js version: 16.20.1
- NPM version: 8.19.4
- Strapi version: 4.14.6
- Database: mysql
- Operating system: ubuntu
- Is your project Javascript or Typescript: TS

### Describe the bug

I can't create new admin user. This is the error I get:

> insert into `admin_users_roles_links` (`role_id`, `role_order`, `user_id`, `user_order`) values ('2', 1, 3, 2) - ER_DUP_ENTRY: Duplicate entry '0' for key 'admin_users_roles_links.PRIMARY' Error: ER_DUP_ENTRY: Duplicate entry '0' for key 'admin_users_roles_links.PRIMARY' at Query.Sequence._packetToError (/opt/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14) at Query.ErrorPacket (/opt/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18) at Protocol._parsePacket (/opt/app/node_modules/mysql/lib/protocol/Protocol.js:291:23) at Parser._parsePacket (/opt/app/node_modules/mysql/lib/protocol/Parser.js:433:10) at Parser.write (/opt/app/node_modules/mysql/lib/protocol/Parser.js:43:10) at Protocol.write (/opt/app/node_modules/mysql/lib/protocol/Protocol.js:38:16) at Socket.<anonymous> (/opt/app/node_modules/mysql/lib/Connection.js:88:28) at Socket.<anonymous> (/opt/app/node_modules/mysql/lib/Connection.js:526:10) at Socket.emit (node:events:513:28) at Soc...

I also can not update the users' role. There is no error. Just not updating.

### Steps to reproduce the behavior

1. Go to /admin/settings/users?pageSize=10&page=1&sort=firstname
2. Click on "Invite new user"
3. Fill the form and submit

**Comment by bolg55** [comment] 2023-12-12 14:47
I believe this is a duplicate of #18293

**Comment by derrickmehaffy** [comment] 2023-12-12 20:14
indeed, duplicate of https://github.com/strapi/strapi/issues/18293

**Closed by derrickmehaffy** 2023-12-12 20:14 UTC
Labels: issue: bug, severity: medium, status: duplicate, source: core:admin, status: pending reproduction
