### ISSUE TITLE
Dynamic zone fetch not showing dynamic zone of nested relationship

### ISSUE THREAD

**Issue by davidmgrana** [strapi/strapi#10307] opened 2021-05-12 14:14 UTC
### Describe the bug

This is the current response:

```
{
  "id": 1,
  "name": "Aerial",
  "slug": "aerial",
  "published_at": "2021-05-07T22:33:18.772Z",
  "created_at": "2021-05-07T22:33:07.566Z",
  "updated_at": "2021-05-11T20:47:25.610Z",
  "sections": [
    {
      "__component": "sections.rotating-text",
      "id": 1,
      "text": "last chance"
    },
    {
      "__component": "sections.product-grid",
      "id": 1,
      "product_grid_layout": {
        "id": 1,
        "name": "crazy layout",
        "published_at": "2021-05-11T20:47:12.864Z",
        "created_at": "2021-05-11T20:47:01.470Z",
        "updated_at": "2021-05-11T20:47:12.885Z"
      }
    }
  ]
}
```
product_grid_layout is a relationship of the sections.product-grid component and it also has a dynamic zone with components which are not being fetched for some reason, as you can see it's only pulling id, name and the timestamps.

this is what a findone call to that same product grid layout looks like:
```
{
  "id": 1,
  "name": "crazy layout",
  "published_at": "2021-05-11T20:47:12.864Z",
  "created_at": "2021-05-11T20:47:01.470Z",
  "updated_at": "2021-05-11T20:47:12.885Z",
  "grid": [
    {
      "__component": "sections.article",
      "id": 2,
      "title": "my article",
      "order": 3
    }
  ]
}
```
### Steps to reproduce the behavior

1. Create the following components:
```{
  "collectionName": "components_sections_product_grids",
  "info": {
    "name": "Product Grid",
    "icon": "air-freshener"
  },
  "options": {},
  "attributes": {
    "product_grid_layout": {
      "model": "product-grid-layouts"
    }
  }
}
```

```{
  "collectionName": "components_sections_articles",
  "info": {
    "name": "article",
    "icon": "align-justify",
    "description": ""
  },
  "options": {},
  "attributes": {
    "title": {
      "type": "string"
    },
    "order": {
      "type": "integer"
    }
  }
}
```

2. Create the following collections:
```{
  "kind": "collectionType",
  "collectionName": "product_grid_layouts",
  "info": {
    "name": "product grid layouts",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "grid": {
      "type": "dynamiczone",
      "components": [
        "sections.article"
      ]
    },
    "name": {
      "type": "string"
    }
  }
}
```

```{
  "kind": "collectionType",
  "collectionName": "collections",
  "info": {
    "name": "Collection",
    "description": ""
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "name": {
      "type": "string"
    },
    "products": {
      "collection": "product",
      "via": "productCollection"
    },
    "sections": {
      "autoPopulate": true,
      "type": "dynamiczone",
      "components": [
        "sections.artwork-carousel",
        "sections.rotating-text",
        "sections.product-grid"
      ]
    },
    "slug": {
      "type": "uid",
      "required": true,
      "private": false
    }
  }
}
```

### Expected behavior

It should be pulling the product_grid_layout dynamic zone field "grid"

### Screenshots

https://www.evernote.com/l/AXzmE6nnW5tFD5RgkWhyk-D_w3sq2NexbDI
https://www.evernote.com/l/AXyD_XEuU8tKr7DM6Af5lfcn3m8DN2Khhc8

### System

- Node.js version: v16.0.0
- NPM version: 7.11.2
- Strapi version: 3.6.2
- Database: sqlite
- Operating system: osx

### Additional context

Check the screenshots and you'll understand inmediately

**Comment by derrickmehaffy** [comment] 2021-05-13 20:43
We have placed a limit on the maximum depth of resolving due to many performance issues, you will need to customize the [service](https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#services) and handle the advanced population there or use [custom queries](https://strapi.io/documentation/developer-docs/latest/development/backend-customization.html#custom-queries).

I'm going to mark this as closed as it's not a bug but intended for now to keep performance to a sane amount until our performance improvements on the database layer in v4

**Closed by derrickmehaffy** 2021-05-13 20:43 UTC
