### ISSUE TITLE
Order of relations not respected on GraphQL

### ISSUE THREAD

**Issue by diogotcorreia** [strapi/strapi#6010] opened 2020-04-30 17:36 UTC
Related to #2166

**Describe the bug**
When fetching from GraphQL and no sorting option is provided, the order of the related items is not respected. However, it works fine on REST.

**Steps to reproduce the behavior**
Should be clearly explained in the related issue (#2166).  
However, I'm using `has many` relation in this case.

**Expected behavior**
GraphQL should respect the order set in the admin panel.
I've verified, the order is maintained in the database, as well as the REST response.

**Screenshots**
![image](https://user-images.githubusercontent.com/7467891/80740196-a0658700-8b0f-11ea-9c07-3e576e6ce11c.png)
![image](https://user-images.githubusercontent.com/7467891/80740251-b83d0b00-8b0f-11ea-91aa-6974e203df85.png)
![image](https://user-images.githubusercontent.com/7467891/80740349-dc005100-8b0f-11ea-90da-afce7ad856ec.png)

**Code snippets**
_none_

**System**

- Node.js version: `13.7.0` (also reproducible in v12)
- NPM version: `6.13.6` (yarn `1.22.4`)
- Strapi version: `3.0.0-beta.20`
- Database: `MongoDB 3.6.3`
- Operating system: `Windows 10 1909 w/ WSL Ubuntu 18.04 LTS`

**Additional context**
I've been pulling my hair over this the whole day.
After loads of debugging, I've found the following:
- GraphQL completely ignores the populated relation data and refetches it anyway.
- The order is maintained through the content type's controllers and services.
- The first location where I can see that the order was not maintained anymore (it's shuffled somewhere before, but I can't figure out where) is in the [DataLoader for the `product` content type](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/data-loaders.js#L45). Here, the `keys` param isn't ordered anymore (and instead is sorted by `_id`).

**Comment by derrickmehaffy** [comment] 2020-04-30 17:51
Ordering of relational data is not currently supported with the exception of components (though not sure if that applies to graphql or not)

https://strapi.io/documentation/3.0.0-beta.x/getting-started/troubleshooting.html#relations-aren-t-maintaining-their-sort-order

**Comment by derrickmehaffy** [comment] 2020-04-30 17:55
Likewise I'm closing this as it's a duplicate of: https://github.com/strapi/strapi/issues/2166

**Closed by derrickmehaffy** 2020-04-30 17:55 UTC

**Comment by jorisw** [comment] 2020-12-04 15:16
Here's a workaround that works for us:
* If you haven't already, create your 'parent' entity type that will refer to the relations
* Add a Component Collection field to the content type, name it the plural of the other content type
* Choose to create a new Component for this Component Collection
* Add a single field to the Component, which is a 1:1 relationship to another Content Type, i.e. the one you want to assign ordered relations of
* Save the new content type (Strapi restarts)
* Create a new item of the new type
* Fill the component collection with components, each with a the foreign content type’s item of your choosing, assigned as the only relation
* Change the order in the component collection as you wish
* Save
* Use REST or the GraphQL playground to retrieve the data, and notice the order is respected
