### ISSUE TITLE
[Build file is too large]`NODE_ENV=production yarn run build` is the same size as the packaged file of `yarn run build`.

### ISSUE THREAD

**Issue by xiaoer3301** [strapi/strapi#7709] opened 2020-09-03 03:47 UTC
**Describe the bug**
The developer told me that the files packaged by `production` will optimize the file size, but the files packaged by `NODE_ENV=production yarn run build` and `yarn run build` are the same size.

**Screenshots**
<img width="1280" alt="iShot2020-09-03上午11 28 10" src="https://user-images.githubusercontent.com/49556560/92068723-3a00b600-edda-11ea-8cf9-c9f81b09aee0.png">
<img width="1275" alt="iShot2020-09-03上午11 29 24" src="https://user-images.githubusercontent.com/49556560/92068731-3ec56a00-edda-11ea-8173-7f02bf1d6e93.png">

**System**

- Node.js version: v12.13.1
- NPM version: -
- Yarn version: v1.22.4
- Strapi version: 3.1.4
- Database: mysql
- Operating system: macOS 10.15.6

**Comment by aksdevac** [comment] 2020-09-03 06:04
Its not a bug see #7439.

**Comment by derrickmehaffy** [comment] 2020-09-03 13:53
Closing as duplicate of: https://github.com/strapi/strapi/issues/7439

**Closed by derrickmehaffy** 2020-09-03 13:53 UTC
Labels: status: duplicate
