### ISSUE TITLE
Symlink broken on Ubuntu

### ISSUE THREAD

**Issue by hessamhoseinkhani** [strapi/strapi#2710] opened 2019-01-29 13:52 UTC
Im trying to make a strapi project for development via " strapi new <prj-name> --dev" 

**Informations**
- **Node.js version**: 10.15.0
- **NPM version**: 6.4.1
- **Strapi version**: @3.0.0 alpha
- **Database**: Mysql
- **Operating system**: linux Ubuntu 16.04.3

**What is the current behavior?**
$ strapi new myprj --dev
$ cd myprj &&  strapi start

error ENOENT: no such file or directory, stat '/home/samix/Public/dev-three/plugins/content-manager'

**What is the expected behavior?**

  server to be run in dev mode

**Comment by derrickmehaffy** [comment] 2019-01-29 13:55
`Strapi version: @3.0.0 alpha` please include your full strapi version, can be found on the CLI by running `strapi version`

**Comment by hsam1997** [comment] 2019-01-30 07:55
@derrickmehaffy 3.0.0-alpha.x

**Comment by lauriejim** [comment] 2019-01-30 08:21
@hsam1997 what is x please ?

**Comment by MatteoViera** [comment] 2019-01-30 11:03
Getting the same problem on Ubuntu 18.10

**Comment by lauriejim** [comment] 2019-01-31 19:25
And your plugin `content-manager` exist in your `plugins` folder ?
You haven't any error when you create your app?

It looks an issue of symlink 🤔

**Comment by MatteoViera** [comment] 2019-01-31 19:45
@lauriejim I checked, and the content-manager exist. Also i got no error when i created my app. I dont know for the creater of the issue

**Comment by hessamhoseinkhani** [comment] 2019-02-01 10:42
@lauriejim i've checked it  ,  there are different plugin **files** like content-manager ,  ...  but when u clicking on em it says no such a directory or file :|  so i guess technically they don't exist .

**Comment by MatteoViera** [comment] 2019-02-06 08:02
someone managed to resolve the problem?

**Comment by MatteoViera** [comment] 2019-02-08 12:57
@lauriejim I've tried to create a new project (following the steps on the quick start) and still got the same problem. I checked all the files in the plugins folder and they all seems to do not exist (even if you can see the file)
I took a couple of screenshots so you can see
![1](https://user-images.githubusercontent.com/46556959/52479601-77bf3d80-2ba9-11e9-8803-84db7d9f18a5.PNG)

![2](https://user-images.githubusercontent.com/46556959/52479579-683ff480-2ba9-11e9-853e-a45ca503e538.PNG)

**Comment by derrickmehaffy** [comment] 2019-02-09 10:04
@lauriejim this looks like a user env symlink issue

**Comment by lauriejim** [comment] 2019-02-09 10:05
I think it can come from permission about symlink creation.
Make sure Strapi can create symlink every where in your computer.

**Comment by derrickmehaffy** [comment] 2019-02-09 10:09
@hessamhoseinkhani I believe this should help you, the problem is the location of your node_modules global folder and permission: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

If you follow that, you can move the location of your "global" node packages to your user (each user can have their own "global" packages).

for now I'm going to mark this issue as closed, if you are still having problems feel free to says so and this can be re-looked at. However I could not reproduce this issue on 16.04 or 18.04

**Closed by derrickmehaffy** 2019-02-09 10:09 UTC
Labels: type: help wanted 🤷‍♂️
