### ISSUE TITLE
UI report

### ISSUE THREAD

**Issue by octoduchilli** [strapi/strapi#8207] opened 2020-10-06 14:22 UTC
**Describe the bug**

Cannot click on the next page button

![image](https://user-images.githubusercontent.com/38497518/95214221-f8579680-07ef-11eb-8924-14af8866db75.png)

**Steps to reproduce the behavior**

Install strapi quickstart
npx create-strapi-app my-project --quickstart

_In Strapi Admin_

Create a Model and fill it with multiples rows

**System**

Node.js version: 12.18.4
yarn version: 1.22.5
Strapi version: 3.1.5
Database: Postgres
Operating system: MacOS
Google chrome

**Package.json**

```
{
  "name": "dressing-solidaire-backend",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "NODE_ENV=development strapi develop",
    "start": "NODE_ENV=production strapi start",
    "build": "NODE_ENV=production strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "fs": "^0.0.1-security",
    "knex": "<0.20.0",
    "pg": "^8.3.3",
    "sqlite3": "latest",
    "strapi": "3.1.5",
    "strapi-admin": "3.1.5",
    "strapi-connector-bookshelf": "3.1.5",
    "strapi-plugin-content-manager": "3.1.5",
    "strapi-plugin-content-type-builder": "3.1.5",
    "strapi-plugin-email": "3.1.5",
    "strapi-plugin-upload": "3.1.5",
    "strapi-plugin-users-permissions": "3.1.5",
    "strapi-provider-email-nodemailer": "^3.0.0",
    "strapi-provider-upload-aws-s3": "^3.1.5",
    "strapi-utils": "3.1.5"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "b4e385ab-d01f-4a77-9650-10997ed87247"
  },
  "engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

Thanks !

**Comment by MattieBelt** [comment] 2020-10-06 14:31
Duplicate of #7289.

Please upgrade to `v3.1.5` or higher, if it still occurs please fill out the complete [Bug Report template](https://github.com/strapi/strapi/issues/new?template=BUG_REPORT.md).

**Comment by octoduchilli** [comment] 2020-10-06 15:22
@MattieBelt Bug report updated

**Comment by MattieBelt** [comment] 2020-10-06 19:54
@octoduchilli did you rebuild the admin panel, checkout [this guide](https://strapi.io/documentation/v3.x/guides/update-version.html) on updating your Strapi version.

I'm not able to reproduce this issue with:
`npx create-strapi-app@3.1.5 my-project-2 --quickstart`
or
`npx create-strapi-app@latest my-project- --quickstart`

**Comment by derrickmehaffy** [comment] 2020-10-07 18:37
This should be fixed currently, going to mark as closed for now. @octoduchilli please let us know if the issue still exists after you update and we can look at reopening.

Thank you!

**Closed by derrickmehaffy** 2020-10-07 18:37 UTC
