### ISSUE TITLE
Cant setup new strapi project

### ISSUE THREAD

**Issue by muhrusdi** [strapi/strapi#12085] opened 2022-01-03 17:08 UTC
### Describe the bug
I cant setup new strapi project, i got this error 

### Expected behavior

I should can see new project after execute the command create strapi project

### Screenshots

![image](https://user-images.githubusercontent.com/9457288/147958846-0d23299a-da5f-4c4e-b49d-7145ac6afa69.png)

### System

- Node.js version: v16.13.1
- NPM version:8.3.0
- Strapi version: 4
- Database: postgres
- Operating system: windows

**Comment by sulaymankhan** [comment] 2022-01-04 00:26
can you try yarn create strapi-app strapi-starter

**Comment by muhrusdi** [comment] 2022-01-04 14:10
@sulaymankhan same issue
![image](https://user-images.githubusercontent.com/9457288/148071367-b625dfba-7fdf-41e6-a4bd-84fc0a9b258f.png)

**Comment by derrickmehaffy** [comment] 2022-01-04 21:39
Can't reproduce with the information provided, need more information.

**Comment by muhrusdi** [comment] 2022-01-05 01:19
Is there any other way to setup new strapi project?

**Comment by sulaymankhan** [comment] 2022-01-06 01:59
> Is there any other way to setup new strapi project?

Have you tried npx create-strapi-app@latest my-project ?

**Comment by muhrusdi** [comment] 2022-01-06 08:16
@sulaymankhan thankyou, its work, i have tried before without `@latest` but its not work
![image](https://user-images.githubusercontent.com/9457288/148351037-970bb425-e25d-466d-b32f-1889c6f71740.png)

**Comment by sulaymankhan** [comment] 2022-01-06 08:52
Thanks great. Please close the issue.

**Closed** 2022-01-06 09:41 UTC
Labels: status: can't reproduce
