### ISSUE TITLE
graphQL: amountLimit is not working in v3.0.0-beta.3

### ISSUE THREAD

**Issue by yurijmikhalevich** [strapi/strapi#3420] opened 2019-06-11 10:15 UTC
**Describe the bug**

```{courses(limit: -1) {Title}}``` → returns all records
// amountLimit: 100
```{courses(limit: 150) {Title}}``` → returns 150 records, should return 100 records

It also will be useful to have this feature on the REST API.

**Steps to reproduce the behavior**

- Create a data type
- Add more than 100 records
- Install GraphQL plugin
- Query it using limit set to -1 and >amountLimit

**Code snippets**

N/A

**System**

Node.js version: v11.10.1
NPM version: 6.9.0
Strapi version: 3.0.0-beta.3
Database: sqlite3
Operating system: Ubuntu 18.04.2 LTS

**Comment by derrickmehaffy** [comment] 2019-06-11 10:18
@yurijmikhalevich Please follow the bug report template, I am marking this as closed for now.

After you have updated your post following the correct template this can be reopened.

Thank you!

**Comment by yurijmikhalevich** [comment] 2019-06-11 10:28
@derrickmehaffy done. PTAL.

**Comment by derrickmehaffy** [comment] 2019-06-11 10:35
I can confirm this error it appears the limiting amount on GraphQL is not working as intended.

(I also agree it would be nice to have on the REST, but for another issue :P )

**Comment by derrickmehaffy** [comment] 2019-06-11 10:37
related code: https://github.com/strapi/strapi/blob/33cbe98b5f783f242efd91ad36ca3dc38dfa54c9/packages/strapi-plugin-graphql/services/Query.js#L45-L59

**Comment by alexandrebodin** [comment] 2019-06-11 10:49
Hi,

Yep that code haven't changed with beta though but it certainly is buggy. Will try to release a fix with beta.4 before the end of the week

**Closed** 2019-06-11 12:59 UTC

**Comment by yurijmikhalevich** [comment] 2019-06-11 15:02
Thank you!
