### ISSUE TITLE
Node version incompatible when upgrading 3.1.4 to 3.2.0

### ISSUE THREAD

**Issue by Aylay** [strapi/strapi#8217] opened 2020-10-07 07:52 UTC
**The bug**
When I'm trying to upgrade Strapi to 3.2.0 version, I have an issue :
`error strapi@3.2.0: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <13". Got "14.9.0"`

**Steps to reproduce the behavior**
1. Change 3.1.4 into 3.2.0 in the package.json file
2. Remove yarn.lock
3. `Yarn install`

**Expected behavior**
None issue :)

**System**
- Node.js version: 14.9.0
- Yarn version: 1.22.5
- Strapi version: 3.1.4 to 3.2.0
- Database: SQLite
- Operating system: macOS Catalina

**Other info**
No issue when I'm upgrading with NPM
NPM version : 6.14.8

I also tried to remove /node_modules/, same issue.

**Comment by meck93** [comment] 2020-10-07 09:14
Hi @Aylay, the problem is that you're using node.js version 14 which is not yet supported. Try again with node v12. For more information, see here: https://strapi.io/documentation/v3.x/installation/cli.html

**Comment by Aylay** [comment] 2020-10-07 09:16
Hi @meck93 , I understand that and It's solved the problem 👍 

Just to inform, it's not working with yarn but with NPM ;) 

And I used Yarn without node problem when it was 3.1.4 strapi version.

**Comment by meck93** [comment] 2020-10-07 09:19
Hi @Aylay, ah, I see. Was there some warning message when installing with NPM? Or nothing at all?

**Comment by Aylay** [comment] 2020-10-07 09:47
Yes few warning but the new version is working and, unfortunately, i don't keep the messages

**Comment by derrickmehaffy** [comment] 2020-10-07 12:57
We don't officially support node v14 yet, yarn was telling you that based on our version settings in the package.json 

See: https://github.com/strapi/strapi/issues/7921

Marking as closed as not a bug, you use v14 at your own risk.

**Closed by derrickmehaffy** 2020-10-07 12:57 UTC
