### ISSUE TITLE
 I can't run my project 

### ISSUE THREAD

**Issue by GabrielMerigo** [strapi/strapi#12904] opened 2022-03-22 01:41 UTC
### Describe the bug
 I can't run my project after that I have installed graphQL. I was working in my Strapi project and when I have installed graphQL with
`yarn strapi install graphql ` or `yarn add @strapi/plugin-graphql` my application returned this error about `globalId`. It always happens when I install the graphQL with both comands.

### Steps to reproduce the behavior

1. You should clone with my [repo](https://github.com/GabrielMerigo/reactavancado).
2. You Should install the graphQL with `yarn strapi install graphql ` or `yarn add @strapi/plugin-graphql` or with `npm run strapi install graphql`
3. And then the installation, you should run `yarn develop` to see the error

### Expected behavior

Run the project and to use graphQL.

### Screenshots

![image](https://user-images.githubusercontent.com/72055874/159389033-9903b1f4-6d6d-4b71-a81e-265d6103449b.png)

### Code snippets

There isn't.

### System

- Node.js version: 16.14.0
- Strapi version: 4.1.5
- Database: postgresql
- Operating system: WLS2

**Comment by derrickmehaffy** [comment] 2022-03-24 22:56
Can you please share your project code, I'm not able to reproduce given the information you provided

**Comment by derrickmehaffy** [comment] 2022-03-28 22:51
Closing for now until the user responds with additional information

**Closed by derrickmehaffy** 2022-03-28 22:51 UTC
Labels: issue: bug, severity: low, status: can not reproduce, source: plugin:graphql
