### ISSUE TITLE
Admin code is not overriding default strapi-admin

### ISSUE THREAD

**Issue by vinod77** [strapi/strapi#5120] opened 2020-01-29 07:16 UTC
**Describe the bug**
I have installed  Strapi `3.0.0-beta.18.4`, I want to override `node_modules/strapi-admin/controller/admin.js` to add a new function. So i  created `/admin` folder and copied `node_modules/strapi-admin` code in to it. When i modify `admin/controller/admin.js` it is not getting overridden. 

**Note:** 
- When i modify in the default `node_modules/strapi-admin/controller/admin.js` it's changes are getting reflected.
- Also when i create `admin/src` with `admin/admin/src` it's changes are getting overriden.

**Strapi Installation:**
Used this URL: https://strapi.io/documentation/3.0.0-alpha.x/guides/databases.html#_2-install-strapi-locally-with-mongodb  to install `Strapi` `3.0.0-beta.18.4` with `MongoDB` 

**Steps to reproduce the behavior**

- Create `admin` folder in the root directory
- Copy `node_modules/strapi-admin` code in to `/admin`
- Modify `admin/controller/admin.js` - **This code is not getting used**/not overriding

**Expected behavior:**

- `/admin` code should override default `node_modules/strapi-admin` code
- Changes in `/admin/controller/admin.js` should be reflected

**Note:** It was working as expected in `Strapi 3.0.0-alpha.23.1` 

**System:**

Node.js version: `v10.15.3`
NPM version: `6.4.1`
Strapi version: Latest `strapi-3.0.0-Beta-18.4`
Database: `MongoDB`
OS: `Mac`

**Uploads:**
`Strapi Beta File Structure:`
<img width="511" alt="Strapi-Beta-File_structure" src="https://user-images.githubusercontent.com/23507845/73335404-e53e0100-4234-11ea-8245-d6511897864c.png">

**Comment by derrickmehaffy** [comment] 2020-01-29 09:04
@vinod77 There currently isn't a straight forward way for this yet, but I have already put in a feature-request for this and they do plan to covert `strapi-admin` into `strapi-plugin-admin` to support this. Please see this request: https://github.com/strapi/strapi/issues/4838

In the short term you may want to fork that package, the easiest way to create a folder at the root of your project called `packages` and copy the package from the source code here on github into that folder.

You can then set the package.json to pull the local dependency instead of from npm. 

[Example](https://stackoverflow.com/questions/15806241/how-to-specify-local-modules-as-npm-package-dependencies):
```
{
  "name": "baz",
  "dependencies": {
    "bar": "file:../foo/bar"
  }
}
```

For now I'm going to mark this as closed as it is realistically a duplicate of the above linked feature request.

**Closed by derrickmehaffy** 2020-01-29 09:04 UTC
