### ISSUE TITLE
After Migrating to 3.4.0 Error occurs when trying to acces /admin

### ISSUE THREAD

**Issue by Ortimis** [strapi/strapi#8934] opened 2020-12-18 09:53 UTC
## Bug report
Upgrading to 3.4.0 (after having executed the migration script) caused the following error to appear in the console. Login to admin not possible after that.

```
Uncaught TypeError: Invalid Version: function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
    at Function.SemVer (main.5c36beab.chunk.js:227192)
    at main.5c36beab.chunk.js:228110
    at Object.<anonymous> (main.5c36beab.chunk.js:228114)
    at __webpack_require__ (runtime~main.313e4d17.js:85)
    at Object.<anonymous> (main.5c36beab.chunk.js:226922)
    at __webpack_require__ (runtime~main.313e4d17.js:85)
    at Object.<anonymous> (main.5c36beab.chunk.js:34209)
    at __webpack_require__ (runtime~main.313e4d17.js:85)
    at Object.<anonymous> (main.5c36beab.chunk.js:225973)
    at __webpack_require__ (runtime~main.313e4d17.js:85)
```

### Steps to reproduce the behavior

I only updated to 3.4.0, dont know yet how to reproduce.

### Expected behavior

Login-UI on /admin should accessible in the browser

### System

- Node.js version: 12.18.4
- NPM version: 6.14.6
- Strapi version: 3.4.0
- Database: sqlite
- Operating system: Windows

**Comment by sunnysonx** [comment] 2020-12-18 11:56
@Ortimis  After migration, you should rebuild the admin. Have you done this?

**Comment by Ortimis** [comment] 2020-12-18 18:59
@sunnysonx Yes, I have rebuilt it

**Comment by derrickmehaffy** [comment] 2020-12-19 20:30
We need more information or a link to your project code.

Have you done any extensions to plug-ins or over-ridden the admin?

Did you try and skip any migration guides?

Whats your package.json look like?

---

For the moment I'm marking this as closed until we have steps to reproduce.

**Comment by haschu** [comment] 2020-12-21 18:12
Hey! I have the exact same issueafter switching from `yarn` to `npm`.

`npm install` and then `npm run develop` throws this exception.

**Comment by Ortimis** [comment] 2020-12-22 09:56
Made a reproduction repo here. To cause the error run `npm install` and `npm run develop`

https://github.com/Ortimis/strapi-reproduction

**Comment by derrickmehaffy** [comment] 2020-12-22 19:02
@Ortimis your reproduction repo had quite a few other issues.

- Bootstrap script was causing a failure
- Improper upload provider configuration location

Removing those the issue didn't show up: 
![image](https://user-images.githubusercontent.com/8593673/102923716-1921a680-4445-11eb-8504-a4d455a32957.png)

If you can reproduce the issue and provide reproduction steps on a fresh project we can take another look. My guess is this issue is due to a failure at the project level, but without more information we can't help in resolving it.

(Side point our automated tests for every commit test with Yarn and NPM)

**Comment by derrickmehaffy** [comment] 2021-04-15 18:15
Closing as no new information

**Closed by derrickmehaffy** 2021-04-15 18:15 UTC
Labels: status: can't reproduce
