### ISSUE TITLE
Content-Type builder doesn't allow specials chars in enum values

### ISSUE THREAD

**Issue by laurenskling** [strapi/strapi#7873] opened 2020-09-13 10:45 UTC
While it works perfectly to have an array of random strings as enum values in the model json; the Content-Type Builder textarea is very picky. It doesn't even allow `-` or let alone a space (` `)

**Comment by laurenskling** [comment] 2020-09-13 10:46
It will throw "The value does not match the regex."

**Comment by derrickmehaffy** [comment] 2020-09-13 21:26
Closing as duplicate of https://github.com/strapi/strapi/discussions/4780

At this time we do not have a good work around as enumeration types have very specific requirements when dealing with certain databases as well as GraphQL specifications. In order to keep compatibility, we have enforced the GraphQL regex validation on enum fields. See the above discussion for more information.

**Closed by derrickmehaffy** 2020-09-13 21:26 UTC
Labels: status: duplicate

**Comment by laurenskling** [comment] 2020-09-14 06:51
I'm sorry for the duplicate, I tried finding closed issued but I was aiming at the content-type builder, should have just searched for enum.

So I understand the issue now. Indeed, when installing Graphql my app crashes on the enums. But doesn't this show another issue? That I can write "wrong" values in the enum field in de model JSON and the app starts normally? (until you install graphql or try to save a content-type builder model)

**Comment by derrickmehaffy** [comment] 2020-09-14 13:45
You are correct, you could add wrong values manually and it would be fine until you install GraphQL. Certainly this could be a solution for you if you don't plan to install GraphQL.

However we enforce it at the CTB level for those that are using GraphQL to ensure novices don't try adding them. Enumeration value types are a very strict type designed for developers and programmers, I would suggest that if you absolutely need a more basic version to use a `value holding` model and a `oneWay` or `manyWay` relationship (plus side to this, you can update the values in production if you need more, whereas enumeration are statically hard coded and cannot be changed in production).

Enums are designed to be very basic and simple like colors
- blue
- green
- red

Or sex orientation 
- male
- female
- other

**Comment by laurenskling** [comment] 2020-09-14 20:52
Not only will graphQL not work, you cannot use the Content-Type Builder. It will fail saving the model with a "wrong" enum inside of it. 

Since the decision is made not to support key/label values for selectboxes, enum is pretty much all you've got. So it makes sense you'd want to try and get some human readable values inside. A relationship for just a selectbox of values that will contain a space or a dash seem quite overkill. 

I now understand _why_ this happens. But I'm still not comfortable with it.

**Comment by derrickmehaffy** [comment] 2020-09-14 22:01
Until we (Strapi) or someone in the community can get around to some of the work-arounds listed in that discussion this is how it will be :confused:

**Comment by globalexport** [comment] 2020-09-28 10:44
This is a bummer for non English languages. It is not possible to use the enumeration for German federal states like "Baden-Württemberg" (ü and -).

**Comment by derrickmehaffy** [comment] 2020-09-28 14:50
@globalexport for now there isn't much we can do due to the limits upstream, please do feel free to apply feedback on the tracking issue linked above, for now I'm going to lock this as we want to try and keep the tracking issue for all comments about the issue.
