### ISSUE TITLE
Strapi GraphQL does not allow publishedStatus

### ISSUE THREAD

**Issue by SalahAdDin** [strapi/strapi#8443] opened 2020-10-22 15:12 UTC
I'm using the new `draft & publish` feature in my blog. I have a use case when i get a `tag` who has many `pages` where pages can be published or not; what I want is getting just the published pages and tags altogether.

So, i do something like this:
```
query {
  tags {
    id
    slug
    pages(publicationState: LIVE) {
      published_at
      title_en
    }
  }
}
```

But, doing this I get the next error:
```
event - compiled successfully
[
  {
    message: 'Unknown argument "publicationState" on field "Tag.pages".',
    locations: [ [Object] ],
    extensions: { code: 'GRAPHQL_VALIDATION_FAILED', exception: [Object] }
  }
]
Error: Failed to fetch API
    at fetchAPI (webpack-internal:///./lib/api/utils.js:20:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getTagBySlug (webpack-internal:///./lib/api/tags.js:142:16)
    at async getStaticProps (webpack-internal:///./pages/tags/[slug].js:168:16)
    at async renderToHTML (/home/joselito92/Proyectos/Work/portfolio/frontend/node_modules/next/dist/next-server/server/render.js:26:109)
    at async /home/joselito92/Proyectos/Work/portfolio/frontend/node_modules/next/dist/next-server/server/next-server.js:76:329
    at async __wrapper (/home/joselito92/Proyectos/Work/portfolio/frontend/node_modules/next/dist/lib/coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (/home/joselito92/Proyectos/Work/portfolio/frontend/node_modules/next/dist/next-server/server/next-server.js:99:365)
    at async DevServer.renderToHTML (/home/joselito92/Proyectos/Work/portfolio/frontend/node_modules/next/dist/next-server/server/next-server.js:100:656)
wait  - compiling...
```

When  I go to the `GraphQL` console and I type the query I can't see `publicationStatus` as an option inside of nested `pages` query.
![Screen Capture_select-area_20201020160534](https://user-images.githubusercontent.com/5034215/96622786-12769600-1313-11eb-99ac-281bbcf52bf8.png)

We should query nested objects by `publicationStatus` too.

Thanks.

### System

- Node.js version: `12`(Docker)
- NPM version:
- Strapi version: `3.2.4`
- Database: `PostgreSQL 13`
- Operating system: `Manjaro Linux`

**Comment by alexandrebodin** [comment] 2020-10-22 15:14
Hello, the publicationState is only allowed on the root query and used in the nested ones automatically. it is the current intended behaviour :)

Closing as it is intended.

**Closed by alexandrebodin** 2020-10-22 15:14 UTC

**Comment by SalahAdDin** [comment] 2020-10-22 15:17
So, in which way can i use it inside of nested queries? `tag` has no publication status, and we want just filter all published pages tagged with such `tag`.

**Comment by alexandrebodin** [comment] 2020-10-22 15:32
By default you will already get the published content :) and youc an still set this parameter in the tags query so it set it for the whole query :) 

```graphql
query {
  tags(publicationState: LIVE) { ... }
}
```

**Comment by SalahAdDin** [comment] 2020-10-23 06:46
Would it work even when tags has no **Draft & Publish** system enabled?

**Comment by alexandrebodin** [comment] 2020-10-23 08:35
yes we allow it so the relations can be impacted :)

**Comment by SalahAdDin** [comment] 2020-10-26 12:30
Helped me a lot, thanks!
