### ISSUE TITLE
Media relations are not exported in components/dynamic zones/single types/collection types

### ISSUE THREAD

**Issue by pepegablaza** [strapi/strapi#19489] opened 2024-02-13 08:45 UTC
### Required System information

- Node.js version: v20.11.0
- NPM version: 10.2.4
- Strapi version: 4.17.1
- Database: PostgreSQL
- Operating system: macOS Sonoma 14.3.1
- Is your project Javascript or Typescript: Typescript

### Describe the bug

When importing and exporting strapi through commands and guide from official docs, i lose all relations in components to media files, but it exports/imports everything else correctly

### Steps to reproduce the behavior

npm run export/ npm run import

### Expected behavior
Export/import commands should save media relations for all components/dynamic zones/collection types and single types in database, as i have seen my database relations are empty

### Additional context
I have seen that this issue was addressed and strapi team said they are working on it so far i couldn't find any info on what version this bug is not present. So far i found several issues which were closed 
https://github.com/strapi/strapi/issues/17343 still no answwer on what version its working, i found some info that some experimental branch was opened and it worked there, but it is merged, atm its not working on 4.17.1 or 4.19.0.

**Comment by silverspectro** [comment] 2024-02-17 13:58
seems to be a bug with `has-and-belongs-to` relationships.
I tried many exports and imports with the 4.20.1 and every relations export and media seem to work, except the `has-and-belongs` relation.
I changed it for a `has-one` relation and it worked.

**Comment by pepegablaza** [comment] 2024-02-19 13:47
we made many tests and seems like strapi export/import exports and imports media relations completely fine, but still strapi components which are using medias are empty

**Comment by yehudabortz** [comment] 2024-03-08 19:43
Although not ideal, this can at least get current content from your remote Strapi into local. 

Steps: 
temporarily downgrade current `@strapi/strapi`  version to `"@strapi/strapi": "4.13.6"`
1. `npm i @strapi/strapi@4.13.6`
2. `npm run build`
3. `npm run db:drop`
4. `npm run db:create`
5. `npm run strapi import -f export_file.tar.gz`
6. revert package.json to your current strapi version
7. `npm i`
8. `npm run build`
9. `npm run dev`

Your content should be there now!

**Comment by derrickmehaffy** [comment] 2024-03-15 17:28
Raising Severity per escalation policy: Related TID: 6195

**Comment by derrickmehaffy** [comment] 2024-03-15 17:29
Related to but not a duplicate of: https://github.com/strapi/strapi/issues/18350

**Comment by lzhou-aops** [comment] 2024-03-15 20:36
Do you think this issue will be fixed with https://github.com/strapi/strapi/pull/19769?

**Comment by NdekoCode** [comment] 2024-03-31 13:13
@pepegablaza, @lzhou-aops, @derrickmehaffy   This error is still present even though everything works fine in version strapi 4.13.x I think we need to review what has been broken in relation to this current version

**Comment by christiancp100** [comment] 2024-04-02 14:32
Hello! @pepegablaza @NdekoCode can you provide an example schema? Also, can you check in 4.21.1 and tell me if it still happens? Thank you very much in advance!

**Comment by pepegablaza** [comment] 2024-04-09 12:01
@christiancp100 hey, same thing is happening on 4.21.1. but we solved issue with dumping postresql database and exporting strapi, so we import those 2 files into another instance and it is 1:1

**Comment by yehudabortz** [comment] 2024-05-03 14:49
The issue is not present anymore for me. Using version "4.24.0"

**Comment by edolix** [comment] 2024-05-09 15:23
> The issue is not present anymore for me. Using version "4.24.0"

Worked for me as well! Stripe version `4.24.2`

**Comment by derrickmehaffy** [comment] 2024-05-09 23:56
Marking as closed as confirmed fixed in 4.24.0+

**Closed by derrickmehaffy** 2024-05-09 23:56 UTC
Labels: issue: bug, severity: high, status: pending reproduction, flag: EE, source: core:data-transfer, version: 4
