### ISSUE TITLE
[Data Transfer] Error when transferring from Community to Enterprise Edition

### ISSUE THREAD

**Issue by rumbleperson** [strapi/strapi#16386] opened 2023-04-13 17:32 UTC
### Required System information

- Node.js version: v16.20.0
- NPM version: v8
- Strapi version: v4.9.1
- Database: PostgreSQL
- Operating system: Docker (node:16-alpine) & Strapi Cloud
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Attempting to run data transfer from a community edition instance to the Strapi Cloud instance which has the Enterprise Edition (and adds the audit log content type).

### Steps to reproduce the behavior

1. Run `npm run strapi transfer -- --to <strapi_cloud_url>/admin --force`
2. See Error
```
error: [FATAL] Invalid schema changes detected during integrity checks (using the strict strategy). Please find a summary of the changes below:
- admin::audit-log:
  -  exists in destination schema but not in source schema
Transfer process failed.
```

### Expected behavior

I'd expect it to ignore the audit log content type since it's only on the destination app (due to using Strapi Cloud which provides an Enterprise License).

### Screenshots

<img width="998" alt="Screenshot 2023-04-13 at 1 05 34 PM" src="https://user-images.githubusercontent.com/35318050/231837758-2f73d4e4-d62e-4f98-8692-c11ee79f6c22.png">

**Comment by Boegie19** [comment] 2023-04-13 18:06
duplicate of https://github.com/strapi/strapi/issues/15616

**Closed by Boegie19** 2023-04-13 18:06 UTC
Labels: status: duplicate
