### ISSUE TITLE
Cant' install Strapi(4.3.8) with --quickstart, better-sqlite3 error

### ISSUE THREAD

**Issue by StellaKim1230** [strapi/strapi#14386] opened 2022-09-12 12:16 UTC
## Bug report

When I try to install Strapi v4 from with `yarn create strapi-app my-project --quickstart`.
next step `cd my-project` and `yarn install`. I get the following error.

### Required System information

- Node.js version: 16.0.0
- NPM version: 7.10.0
- Yarn version: 1.22.10
- Strapi version: 4.3.8
- Database:
- Operating system: MacOS 12.5.1

### Error Code snippets
```
error /Users/jieunkim/admin/node_modules/better-sqlite3: Command failed.
Exit code: 1
Command: prebuild-install || npm run build-release
Arguments:
Directory: /Users/jieunkim/admin/node_modules/better-sqlite3
Output:
prebuild-install warn install No prebuilt binaries found (target=16.0.0 runtime=node arch=arm64 libc= platform=darwin)

> better-sqlite3@7.4.6 build-release
> node-gyp rebuild --release

gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@16.0.0 | darwin | arm64
gyp info find Python using Python version 3.8.2 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
(node:59700) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jieunkim/admin/node_modules/better-sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jieunkim/Library/Caches/node-gyp/16.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jieunkim/Library/Caches/node-gyp/16.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/jieunkim/Library/Caches/node-gyp/16.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/jieunkim/admin/node_modules/better-sqlite3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.



Traceback (most recent call last):
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1500, in XcodeVersion
    version_list = GetStdoutQuiet(["xcodebuild", "-version"]).splitlines()
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1563, in GetStdoutQuiet
    raise GypError("Error %d running %s" % (job.returncode, cmdlist[0]))
gyp.common.GypError: Error 1 running xcodebuild

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 51, in <module>
    sys.exit(gyp.script_main())
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 670, in script_main
    return main(sys.argv[1:])
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in main
    return gyp_main(args)
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 647, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2451, in GenerateOutput
    writer.Write(
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 799, in Write
    self.WriteActions(
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 933, in WriteActions
    env = self.GetSortedXcodeEnv()
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2104, in GetSortedXcodeEnv
    return gyp.xcode_emulation.GetSortedXcodeEnv(
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1890, in GetSortedXcodeEnv
    env = _GetXcodeEnv(
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1745, in _GetXcodeEnv
    "XCODE_VERSION_ACTUAL": XcodeVersion()[0],
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1511, in XcodeVersion
    version = CLTVersion()  # macOS Catalina returns 11.0.0.0.1.1567737322
  File "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1549, in CLTVersion
    return re.search(regex, output).groupdict()["version"]
AttributeError: 'NoneType' object has no attribute 'groupdict'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/Users/jieunkim/.nvm/versions/node/v16.0.0/bin/node" "/Users/jieunkim/.nvm/versions/node/v16.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /Users/jieunkim/admin/node_modules/better-sqlite3
```
Where do I need to edit?

**Comment by derrickmehaffy** [comment] 2022-09-28 17:44
> Node.js version: 16.0.0

Your node version is too old, can you try upgrading to v16.16.0 at minimum?

Marking as closed as this almost certainly is not a bug but an environment issue.

**Closed by derrickmehaffy** 2022-09-28 17:44 UTC
