### ISSUE TITLE
[v4] Date field always shows in CTM as 1 day prior

### ISSUE THREAD

**Issue by derrickmehaffy** [strapi/strapi#11509] opened 2021-11-09 02:22 UTC
### Describe the bug

When setting the date field (unable to test datetime as it doesn't exist in this version yet), it always shows as 1 day previous but it correctly returned in the API response.

### Steps to reproduce the behavior

1. Add a date field to a content type
2. Create an entry and select a day
3. See that the CTM UI shows the day before
4. See that the REST Response is correct

### Expected behavior

Should show the correct day, most likely this is caused by the usage of the browsers timezone and is trying to render the date based on that location (although I've tested in the morning, afternoon, and evening all with the same result)

### Screenshots

https://www.loom.com/share/09f2ccd20db9462880efe78ac58b3c02

### Code snippets

N/A

### System

- Node.js version: v14.17.5
- NPM version: v6.14.14
- Strapi version: 4.0.0-beta.11
- Database: SQLite
- Operating system:  Linux Mint 20.2

### Additional context

N/A

**Comment by JabStrapi** [comment] 2021-11-18 14:42
Hi Derrick, I tested with the datetime yesterday and it seems to work as expected: it is intended that the admin panel displays the browser timezone and that the date is stored without timezone. If you agree, can we close this issue?

**Comment by derrickmehaffy** [comment] 2021-11-18 16:37
> Hi Derrick, I tested with the datetime yesterday and it seems to work as expected: it is intended that the admin panel displays the browser timezone and that the date is stored without timezone. If you agree, can we close this issue?

The Datetime field works fine, it's just the date field:
https://www.loom.com/share/e026fabba46147dc8a62863e31d5cc50

The date field shouldn't take into account any timezones 

Confirmed in beta.13 (where that loom was recorded from)

**Comment by jakobsjoqvist** [comment] 2021-11-22 11:14
@derrickmehaffy Is this issue open for contribution? I would be happy to fix this issue :)

**Comment by derrickmehaffy** [comment] 2021-11-22 14:11
> @derrickmehaffy Is this issue open for contribution? I would be happy to fix this issue :)

Wouldn't see why not but there may be a member of the team already looking at it.

**Comment by haveamission** [comment] 2022-01-01 22:28
This is not just happening in V4, but also V3.

**Comment by derrickmehaffy** [comment] 2022-01-03 11:29
> This is not just happening in V4, but also V3.

We won't backport this fix to v3

**Comment by johan13** [comment] 2022-01-27 09:33
This appears to be a time zone issue. My server is running UTC and my local computer is in UTC+1. If I select 2021-01-29 in a date field and click Save, then the date is sent as "2022-01-28T23:00:00.000Z" in the PUT request. In the response returned by the PUT operation the date appears as "2022-01-28".

**Comment by derrickmehaffy** [comment] 2022-01-27 22:03
Should be fixed by those 2 PRs soon.

**Comment by johan13** [comment] 2022-02-07 14:49
What is the status of this issue? I am not happy about my current workaround:

![image](https://user-images.githubusercontent.com/643284/152808315-ab1bc27c-e1e9-482e-816f-fb3ac8eed9e3.png)

There are two PR:s related to this: #12267 (Front end) and #12234 (Back end). The former of these has been closed by @soupette who commented that dates should be passed around using the full `toISOString()` format. @petersg83 disagreed, arguing that `yyyy-MM-dd` is better when dealing with timezones.

Is there any work being done on this, or is this issue stuck in limbo?

**Comment by petersg83** [comment] 2022-02-07 14:52
Some people were on holidays last week, the work on it will continue this week :)

**Comment by SebaM90** [comment] 2022-02-15 04:36
> What is the status of this issue? I am not happy about my current workaround:
> 
> ![image](https://user-images.githubusercontent.com/643284/152808315-ab1bc27c-e1e9-482e-816f-fb3ac8eed9e3.png)
> 
> There are two PR:s related to this: #12267 (Front end) and #12234 (Back end). The former of these has been closed by @soupette who commented that dates should be passed around using the full `toISOString()` format. @petersg83 disagreed, arguing that `yyyy-MM-dd` is better when dealing with timezones.
> 
> Is there any work being done on this, or is this issue stuck in limbo?

I have same issue. When I save a date field, it shifts 2 days back.
Example: 31-12-2020 ➡ 29-12-2020

Temporarily I solve it by adding two days with the "datefns" library.

**Comment by petersg83** [comment] 2022-02-15 09:16
Hopefully the fix will be released tomorrow :)

**Comment by ippoippo** [comment] 2022-02-16 00:22
Hope this fix is coming out today(or is it tomorrow, lame joke).
We were getting this issue too. It was "working" fine when running locally on my development Mac (SQLite DB) (which is running in JST).
As soon as we run on AWS infra (Lightsail Instances, and MySQL DBs, running in UTC), we have this issue.
Testing before 09:00JST(OO:00UTC) for when the date between local and server is different, and after 09:00JST(OO:00UTC) when in theory the date is the same, I found the same incorrect behaviour. Inserts into the DB were always -1 day.

eg. This was me selecting 2022-02-28 in the UI, and hitting save.

mysql> select updated_at, xxxx_release_date from marketings where id=3;
+----------------------------+---------------------+
| updated_at                 | xxxx_release_date   |
+----------------------------+---------------------+
| 2022-02-16 00:05:11.001000 | 2022-02-27          |
+----------------------------+---------------------+

The date inserted was -1 day. And then it reads that date out back to UI and displays "correctly" (consistent with what is in the DB)

As soon as 4.0.8 is out, assuming fix is in place, will I will test ASAP

**Comment by SebaM90** [comment] 2022-02-16 15:31
> > What is the status of this issue? I am not happy about my current workaround:
> > ![image](https://user-images.githubusercontent.com/643284/152808315-ab1bc27c-e1e9-482e-816f-fb3ac8eed9e3.png)
> > There are two PR:s related to this: #12267 (Front end) and #12234 (Back end). The former of these has been closed by @soupette who commented that dates should be passed around using the full `toISOString()` format. @petersg83 disagreed, arguing that `yyyy-MM-dd` is better when dealing with timezones.
> > Is there any work being done on this, or is this issue stuck in limbo?
> 
> I have same issue. When I save a date field, it shifts 2 days back. Example: 31-12-2020 ➡ 29-12-2020
> 
> Temporarily I solve it by adding two days with the "datefns" library.


I updated to version v4.0.8 and the problem persists:

[https://www.loom.com/share/d935bbab68cf43149f6d9ead05038cd5](url)

**Comment by petersg83** [comment] 2022-02-16 15:35
If not, can you try to delete your node modules, install them again and rebuild the front?

**Comment by petersg83** [comment] 2022-02-16 15:36
Can you also show the content of the request sent please?

**Comment by SebaM90** [comment] 2022-02-16 15:47
> If not, can you try to delete your node modules, install them again and rebuild the front?

Yes, i do it.


> Can you also show the content of the request sent please?

I found that the console (npm run develop) is throwing the following warning:

![image](https://user-images.githubusercontent.com/39964514/154301664-230ba0a7-19ab-4fe1-9c5c-7655634f125e.png)
"(node:27784) Warning: [deprecated] Using a date format other than YYYY-MM-DD will be removed in future versions. Date received: 2022-02-01T03:00:00.000Z. Date stored: 2022-02-01."

In the field I selected the date: 2022-02-01

**Comment by SebaM90** [comment] 2022-02-16 15:55
> Can you also show the content of the request sent please?
![image](https://user-images.githubusercontent.com/39964514/154302752-4580bd94-da7e-4dff-a879-7223ef9bedbc.png)

• In the database it is saved correctly ✅
![image](https://user-images.githubusercontent.com/39964514/154302914-deb693d6-6267-49f4-a32f-7ac557ad9ee4.png)

• So it's just a Strapi/Admin issue displaying/loading the date:
![image](https://user-images.githubusercontent.com/39964514/154303256-bba0d78c-f020-4bc9-955a-574b1fb83be9.png)

**Comment by petersg83** [comment] 2022-02-16 16:05
It seems like the frontend is not correctly rebuilt.
Can you delete the folders `build` and `.cache` and build again?
Is your browser using the old build because of cache, cant your force refresh the page?

**Comment by SebaM90** [comment] 2022-02-16 17:53
> It seems like the frontend is not correctly rebuilt. Can you delete the folders `build` and `.cache` and build again? Is your browser using the old build because of cache, cant your force refresh the page?

This solved the problem. Thanks a lot. 👏

**Comment by ippoippo** [comment] 2022-02-16 23:14
I've done:

**Comment by jumptrnr** [comment] 2022-02-17 15:33
Filtering on Date in GraphQL no longer works - 4.0.9 - any chance this is related:?
for example this stopped returning filtered results. 

`query Currencies($dt_gt: DateTime, $dt_lt: DateTime) {
  currencies(filters: { Date: { gt: $dt_gt, lt: $dt_lt } }) {
    data {
      id
      attributes {
        To
        From
        Rate
        Date
      }
    }
  }
}`
with input as: 
`{ 
  "dt_gt": "2022-03-17T05:00:00.000Z",
  "dt_lt": "2022-03-19T05:00:00.000Z"
}`

filtered as expected in 4.0.6+ but not in 4.0.9+ (in apollostudio no front end involved)

**Comment by SebaM90** [comment] 2022-02-18 04:40
I want to add this little bug when the records are listed.
Although if you enter it is displayed well (1-2-2022).
(Strapi v4.1.0)

![image](https://user-images.githubusercontent.com/39964514/154617536-2583f6e0-f97b-40c0-b7ba-10348fde037b.png)

**Comment by madu8917** [comment] 2022-02-18 06:13
Sent from my Huawei phone-------- Original message --------From: Sebastián ***@***.***>Date: Fri, 18 Feb 2022, 10:11To: strapi/strapi ***@***.***>Cc: Subscribed ***@***.***>Subject: Re: [strapi/strapi] [v4] Date field always shows in CTM as 1 day prior (Issue #11509)
I want to add this little bug when the records are listed.
Although if you enter it is displayed well (1-2-2022).
(Strapi v4.1.0)

**Comment by petersg83** [comment] 2022-04-05 12:30
I close this issue as I believe it was fixed and I cannot reproduce it :) Don't hesitate to comment if not

**Closed by petersg83** 2022-04-05 12:30 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:content-manager

**Comment by ALWISHARIFF** [comment] 2022-09-13 15:16
Dear Strapi Team,
I am using The following specification of softwares.

    Node.js version: v16.17.0
    NPM version: v8.15.0
    Strapi version: 4.3.8
    Database: SQLite
    Operating system: Windows 10
I created my content schema using the content manager i now have a pubic route to fetch resources from the server.
The createdAt field that is automatically added by strapi is according to **UTC timezone format** I tried changing the `database.js file` in the _**config folder**_ added` timezone:"Africa/Nairobi" `to` connection.connection` object `as per the docs `but if **fails to record time with the current timezone** even after **adding various posts and publishing them**

**Comment by uulaal** [comment] 2023-08-03 07:18
Just opening and closing datepicker forces value to update

![chrome-capture-2023-7-3](https://github.com/strapi/strapi/assets/38786565/06f09827-069a-489e-8b00-aa0ae1022e45)

**Comment by matepaiva** [comment] 2023-08-09 12:42
@uulaal The same happens to me. Did you find any workaround? Version: "@strapi/strapi": "4.12.1"

Note: I am in a location with summer time and I think it has something to do with it.

**Comment by uulaal** [comment] 2023-08-15 08:24
@matepaiva I split "datetime" field into two separate "date" and "time" fields, they work correct

**Comment by jbebe** [comment] 2023-09-05 09:50
We are also experiencing this UI bug from CET summer time

**Comment by zan-liu** [comment] 2023-09-05 10:51
I also encountered this issue
