### ISSUE TITLE
Pointing local server at Heroku Postgre produces unexpected error: Could not load js config file config/database.js: Cannot read property ' charAt' of undefined

### ISSUE THREAD

**Issue by NLeRoy917** [strapi/strapi#8810] opened 2020-12-06 17:00 UTC
### Describe the bug

When installing the [strapi blog template](https://github.com/strapi/strapi-template-blog) locally according to the most [recent documentation](https://strapi.io/documentation/v3.x/deployment/heroku.html) everything works great. I can configure Heroku with a PostgreSQL database and I can add content types locally which get reflected on the production build... but if I add content (like a new Category or Article) to the local server, it isn't reflected on the production build. I tried to point the local development server at the PostgreSQL db by mirroring the `./config/env/production/database.js` in `./config/database.js` but I end up with this error:

`Could not load js config file config/database.js: Cannot read property ' charAt' of undefined`

I'm new to strapi, so I don't fully understand how data is stored,  but it seems like content-types are stored in the build itself, while content is stored in the database (SQLite locally and PostgreSQL in production), and that is where the discrepancy lies.

**So the question/issue:** Is there a way to **a.)** get the content to be in sync locally and in production, and **b.)** do it without producing that error above? This isn't critical obviously as the application can still fully function if I just revert to using sqlite for local development, but it feels off to me that I would be creating a CMS that has out-of-sync content depending on where I am editing things (Heroku v local). 

#### For out of sync content
1. Install the [strapi blog template](https://github.com/strapi/strapi-template-blog)
2. Deploy to Heroku using the most [recent documentation](https://strapi.io/documentation/v3.x/deployment/heroku.html)
3. Add content to a content-type
4. Rebuild production server
5. Observe no change in production

#### For `chartAt of undefined` error
1. Install the [strapi blog template](https://github.com/strapi/strapi-template-blog)
2. Deploy to Heroku using the most [recent documentation](https://strapi.io/documentation/v3.x/deployment/heroku.html)
3. Change `./config/database.js` to reflect the contents of `./config/env/production/database.js` as described [here](https://strapi.io/documentation/v3.x/deployment/heroku.html#_4-create-your-heroku-database-config-file-for-production)
4. Run `yarn develop` and observe error

### Expected behavior

I believe the local server should start as intended and use the PostgreSQL database on Heroku.

#### `./config/database.js`:
```
module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'sqlite',
        filename: env('DATABASE_FILENAME', '.tmp/data.db'),
      },
      options: {
        useNullAsDefault: true,
      },
    },
  },
});
```
#### `./config/env/production/database.js`:
```
const parse = require('pg-connection-string').parse;
const config = parse(process.env.DATABASE_URL);

module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'postgres',
        host: config.host,
        port: config.port,
        database: config.database,
        username: config.user,
        password: config.password,
      },
      options: {
        ssl: false,
      },
    },
  },
});
```

### System

- Node.js version: v14.15.1
- NPM version: v6.14.8
- Strapi version: v3.3.4
- Database: PostgreSQL
- Operating system: MacOS Big Sur v11.0.1

### Additional context

This error was also mentioned in issue #8164, but it doesn't seem like it was ever resolved

**Comment by derrickmehaffy** [comment] 2020-12-22 22:06
```
For chartAt of undefined error
- Install the strapi blog template
- Deploy to Heroku using the most recent documentation
- Change ./config/database.js to reflect the contents of ./config/env/production/database.js as described here
- Run yarn develop and observe error
```

The issue is you don't have a `DATABASE_URL` being passed, it's undefined so it can't be broken down to connect to the remote database. On that point Heroku really doesn't offer a good way to connect that remote database and you would be better off running a local PG database.

On the point of content management, it would be quite difficult to keep your local version in sync if you are using Heroku. I know you are slightly new to Strapi so the concept of how things are handled are a bit different than you are probably used to but it's generally not normal to build content locally then push that into production.

What I suggest is we move this conversation to the forum: https://forum.strapi.io as this isn't really a bug, but does require some discussion. Please feel free to ping me there when you open a thread and we can talk more but I'm going to close this issue as it's not a bug with the code.

**Closed by derrickmehaffy** 2020-12-22 22:06 UTC

**Comment by zimenkoilya** [comment] 2021-05-02 15:52
when i upload on heroku server, get the error cahtAt 
what is the heroku server problem?
how to connect database.js and config database url, port, host.... on heroku server?
please teach me.
thanks

**Comment by denza** [comment] 2021-06-14 15:34
The problem is that DATABASE_URL variable is not pushed on the command invoke. This is my workaround

`DATABASE_URL=$DATABASE_URL NODE_ENV=production npm run build`

**Comment by sahil-frontenddev** [comment] 2022-03-06 08:23
The problem is you have to add postgres add on first and then you need to restart the build again

**Comment by aouiniamine** [comment] 2024-10-27 14:37
I did the deployment with docker but it'll be the same case on Heroku as well,
**Context:**
The build breaks because pg-connection-string' parser can't read the DATABASE_URL
The issue is in config/env/production/database.ts:
```bash
const parse = require('pg-connection-string').parse;
const config = parse(process.env.DATABASE_URL);
```
To fix it change the database config to this example:
```bash
export default ({ env }) => {
  return {
    connection: {
      client: 'postgres',
      connection: {
        host: env('DATABASE_HOST'),
        port: env('DATABASE_PORT'),
        database: env('DATABASE_NAME'),
        user: env('DATABASE_USERNAME'),
        password: env('DATABASE_PASSWORD'),
        schema: env('DATABASE_SCHEMA', 'public'), // Not required
        ssl: env.bool('DATABASE_SSL', false),
      },
      debug: false,
    },
  }
}
```
