### ISSUE TITLE
Can't create admin user "An error occurred while requesting the API"

### ISSUE THREAD

**Issue by alpiua** [strapi/strapi#12278] opened 2022-01-24 01:05 UTC
## Bug report
I've tried with npm install and yarn install from the installation guide.
Install went successfull.

### Describe the bug
Receive a message "An error occurred while requesting the API" trying to open an address "http://1.2.3.4:1337/admin"
See screenshot 

### Steps to reproduce the behavior

1. Run proxmox LXC container with NodeJs https://www.turnkeylinux.org/nodejs 
2. Install Strapi with npm or yarn
3. Try to login on admin page

### Expected behavior

Expect to proceed with the admin user creation

### Screenshots

![image](https://user-images.githubusercontent.com/14225967/150705865-4e097a0d-c4c3-4424-8b9c-339db54775a6.png)

### System

- Node.js version: v14.15.5
- NPM version: 6.14.11
- Strapi version: latest
- Database:
- Operating system: Debian GNU/Linux 10 (buster)

### Additional context

I'm very very new with Node ecosystem and don't really know where to go further.

**Comment by pepesaladsss** [comment] 2022-01-24 21:08
Experiencing the same issue, reproducible in the same way. 

NPM Version: 6.14.15
Node.js Version: v12.22.9
Strapi Version: Latest
OS: Ubuntu 20.04.3 Server

Running on a VM in Proxmox VE 7.1-7
![image](https://user-images.githubusercontent.com/68161790/150864992-6479026d-d652-4084-87f8-b46d5207042a.png)

**Comment by derrickmehaffy** [comment] 2022-01-24 23:06
Running LXC locally, it's because we ship with a prebuilt admin to cut down on runtime that is hard coded with localhost.

In your config/server.js you should change the host param from 0.0.0.0 to whatever you containers IP is or you can use the `HOST=192.168.1.10` or whatever your IP is when you start via PM2 or whatever.

You will need to rebuild the admin panel for this though as it's statically compiled. The reason it fails is due to this request:
![image](https://user-images.githubusercontent.com/8593673/150879421-9d9d2e5e-add6-494d-acc6-492495bfa067.png)

---

Example: 
![image](https://user-images.githubusercontent.com/8593673/150879873-a1039b97-5f9e-4e04-bb2b-a1caefec4fe3.png)

Closing as it's not really a bug but lack of configuration ;)

**Comment by derrickmehaffy** [comment] 2022-01-24 23:06
(happy to see other LXC users though!)

**Closed by derrickmehaffy** 2022-01-24 23:06 UTC

**Comment by alpiua** [comment] 2022-01-27 22:36
Sorry for dump question, how exactly I suppose to rebuild admin panel? As I mentioned, I'm totally new in the node world.
I tried this
![image](https://user-images.githubusercontent.com/14225967/151454583-337f28e4-b986-4f0b-809e-29e410388304.png)

but still have the same request to localhost.

btw.. just thought that I could run nginx as proxy, so this is not "life or die" question. But still interesting.

**Comment by alpiua** [comment] 2022-01-27 22:50
Took some time to figure out how to rebuild the app :) NodeJs is terra incognita, will leave it here just in case.

yarn strapi build
yarn start

Now I can proceed with admin page.
Btw I just thought I could use nginx and proxy the request instead. 

Nevertheless thank you for been supportive.

**Comment by alpiua** [comment] 2022-01-29 00:38
I could solve this for one instance. 1.2.3.4:2929 and have it working. 
Thank you for help!

Anyway, there is something strange when I trying to start another strapi instance nearby in separate folder, on the same host.
Doing qite the same, with this config:
```
module.exports = ({ env }) => ({
  host: env('HOST', '1.2.3.4'),
  port: env.int('PORT', 3030),
  app: {
    keys: env.array('APP_KEYS'),
  },
});
```
doing yarn buid strapi && yarn developer I still see localhost:1337 in output.
![image](https://user-images.githubusercontent.com/14225967/151639235-a5a9df81-67a1-4fcb-9e5d-1dd7efd0b2f4.png)

But actually I can access this new instance by IP on 1337 port, not on 3030 which I set.
and got ERR_CONNECTION_REFUSED on 1.2.3.4:3030

How I can solve this?

**Comment by AmineAML** [comment] 2022-02-24 20:39
@alpiua The url you see in the console is from where you access you app and I think has nothing to do with the issue here, if you want to change it then update `/config/server.js` file:
```js
module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  app: {
    keys: env.array('APP_KEYS'),
  },
  // add this line
  url: 'https://domain.tld'
});

```

**Comment by JS-mark** [comment] 2023-08-11 02:05
Remember to re-build.
