### ISSUE TITLE
Side menu items rendered randomly

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi#1271] opened 2018-05-25 06:39 UTC
**Informations**
- **Node.js version**: 10.1.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: MongoDB
- **Operating system**: Linux

**What is the current behavior?**
Side menu items rendered randomly. Sometimes **Content Types** section items not rendered, sometimes **Plugins** section items not rendered but **General** section items always rendered successfully. See below gif for more info:
![strapi 11](https://user-images.githubusercontent.com/25859075/40529846-c47afc6e-600b-11e8-89b0-dcdec0f0e078.gif)

**Steps to reproduce the problem**
Refresh dashboard page many times.

**What is the expected behavior?**
We need see all menu items always.

**Suggested solutions**
--

**Comment by lauriejim** [comment] 2018-05-25 08:43
@mnlbox It's on Firefox ? It happen also on other browser you have ?

**Comment by soupette** [comment] 2018-05-25 08:59
How do you start your server (`npm start` or `strapi start`)?

**Comment by mnlbox** [comment] 2018-05-25 10:16
@lauriejim yes it's Firefox but I check and it's happen also on Chromium.
@soupette I run by `strapi start`.

**Comment by soupette** [comment] 2018-05-25 15:34
It seems that some plugins aren't loaded, but I'm unable to reproduce your issue.

**Comment by mnlbox** [comment] 2018-05-25 16:10
If I can help to reproduce issue please tell me. I don't know how help about this. :thinking:

**Comment by soupette** [comment] 2018-06-07 17:16
@mnlbox can I have an update on your issue?

**Comment by mnlbox** [comment] 2018-06-18 09:04
@soupette No it's still break sometimes. I don't know when but it's still not render menu items randomly.
I also try to update and also test again on a clean project.

**Comment by soupette** [comment] 2018-06-18 09:30
Do you have a repo I can access so I can try to debug? I'm still unable to reproduce the bug

**Comment by mnlbox** [comment] 2018-06-20 03:41
@soupette I try to create some dummy project for you. But I think it's something related to browser version because I also try clean project and this issue exist and randomly happens.

**Comment by lauriejim** [comment] 2018-07-19 15:18
Still we don't have a clear steps to reproduce I close this issue. 
Will reopen it when we will have steps. We are not able to work on without.

**Comment by mnlbox** [comment] 2018-07-25 10:30
@lauriejim **We haven't clear steps to reproduce this issue because as I told in issue title it's completely randomly**.
By close this type of issue (randomly issues) you keep this issue as is and known issue.

**Comment by derrickmehaffy** [comment] 2018-07-25 10:37
@mnlbox I do agree with you on this, if it is still happening randomly on v12.7.1 to only specific people the root cause needs to be found, either that be with Strapi or with the environment.

I know there are quite a lot of issues on the Strapi github but they shouldn't be closed out if they are following the proper format and it is believed the bug may still exist.

I too have had similar issues that are difficult to re-produce and have filed a few bug repots to offer an issue that others can relay additional details. I think having a page on the wiki listing issues that are considered "Known problems" is a good idea and linking to these issues to help promote discussion and ways to find a resolution.

@lauriejim @soupette @Aurelsicoko what are your thoughts?

**Comment by derrickmehaffy** [comment] 2018-07-25 10:41
@mnlbox Can you provide more information as to the specs of the host that is running Strapi? 

Such as:

* Is it a VM? If so what are the resources allocated to it
* Is the database on the same system
* Do you have other services/applications/ect running on the system
* If this is a physical machine what are the hardware specs and idle usage (not running strapi) vs strapi usage (total resource usage while strapi is running)

I want to rule out the possibility that strapi is rendering slow due to the hosts resources. I can say I have run strapi on a Vultr VM that only has 1 CPU core and ~1GB of memory so the usage shouldn't be very high (given strapi did not perform very fast, but it worked without issue)

**Comment by Aurelsicoko** [comment] 2018-07-27 14:37
@derrickmehaffy I've my thoughts on this and it's pretty simple. First, there is no order for the load of the plugins (there are mounting once there are loaded) and there is also a browser issue. It seems to never happen with Chrome but only with Firefox and Chromium.

**Comment by mnlbox** [comment] 2018-08-24 11:43
@Aurelsicoko yes many of UI issues happens in Firefox and Chromium.
I think we need some UI test based on this or using general UI tools like bootstrap that works anywhere without issue.

**Comment by Aurelsicoko** [comment] 2018-09-06 09:59
I would love to see [Cypress](https://www.cypress.io/) implemented on Strapi in our tests suit.

**Closed** 2018-11-07 18:07 UTC
Labels: priority: low, status: can't reproduce, type: bug 🐛
