### ISSUE TITLE
Error when saving a model containing a component with a model relation

### ISSUE THREAD

**Issue by AntonShan** [strapi/strapi#8447] opened 2020-10-22 17:32 UTC
### Describe the bug

I have a model (model name is Build) that has a repeatable component (name is Gear Slot). Said component has a relation with a model called Set. When I attempt to create new Build model I receive an error `A model cannot be updated without a "where" clause or an idAttribute.`

### Steps to reproduce the behavior

In attached issue reproduction repository:
1. Go to Builds collection.
2. Click on Add New build
3. Fill the required `name` field
4. In Set field of GearSlot collection select the only entry there - called test
5. Click Save
6. Get an error

### Expected behavior

I expect a new Build entry to be successfullty created.

### Screenshots

![image](https://user-images.githubusercontent.com/4890060/96908150-4980af00-14ad-11eb-8c26-4e9711bab039.png)

### Code snippets

Here is a reproduction repository - https://github.com/AntonShan/strapi-bug-reproduction
it contains an SQLite database with all required data to reproduce the issue. Admin credentials are - `admin@admin.com`/`Aa123456`

### System

- Node.js version: 12.16.3
- NPM version: 6.14.4 (actually using Yarn 1.22.5)
- Strapi version: 3.2.4
- Database: SQLite
- Operating system: Windows 10 Pro

**Comment by derrickmehaffy** [comment] 2020-10-26 18:21
@AntonShan I have cloned your sample reproduction repo and I see no `builds` collection?

![image](https://user-images.githubusercontent.com/8593673/97212238-5a674400-177d-11eb-8eb7-74957288361c.png)

**Comment by AntonShan** [comment] 2020-10-26 20:54
@derrickmehaffy sorry, I forgot to update .gitignore and this model was ignored. I updated the reproduction repo.

**Comment by derrickmehaffy** [comment] 2020-10-26 21:03
Confirmed with the following error response:

```json
{
  "statusCode": 400,
  "error": "Bad Request",
  "message": [
    {
      "messages": [
        {
          "id": "A model cannot be updated without a \"where\" clause or an idAttribute.",
          "message": "A model cannot be updated without a \"where\" clause or an idAttribute."
        }
      ]
    }
  ],
  "data": [
    {
      "messages": [
        {
          "id": "A model cannot be updated without a \"where\" clause or an idAttribute.",
          "message": "A model cannot be updated without a \"where\" clause or an idAttribute."
        }
      ]
    }
  ]
}
```

**Comment by soupette** [comment] 2020-11-25 15:11
It seems that the issue is having an attribute called set. Maybe we should forbid this name.

**Comment by derrickmehaffy** [comment] 2022-07-13 20:54
should be fixed in v4 else it's https://github.com/strapi/strapi/issues/1198

**Closed by derrickmehaffy** 2022-07-13 20:54 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:strapi
