### ISSUE TITLE
Transfer pull command hangs

### ISSUE THREAD

**Issue by molund** [strapi/strapi#16437] opened 2023-04-18 23:43 UTC
### Required System information

- Node.js version: 18.14.2
- NPM version: 8.19.2
- Strapi version: 4.9.1
- Database: Postgres
- Local Operation system: Ubuntu / WSL
- Remote Operating system: Red Hat 4.18.0-372.32.1.el8_6.x86_64
- Is your project Javascript or Typescript: Javascript

### Describe the bug

The Strapi transfer command hangs when pulling from a remote server to a local insance

local command window
```
michaelo:/mnt/c/work/bcparks.ca/src/cms$ npm run strapi transfer -- --from https://alpha-dev-cms.bcparks.ca/admin --from-token *********** --only content

> backend@0.1.0 strapi
> strapi transfer --from https://alpha-dev-cms.bcparks.ca/admin --from-token *********** --only content

? The transfer will delete all the local Strapi assets and its database. Are you sure you want to proceed? Yes
Starting transfer...
⠴ entities: 2242 transfered (size: 1.9 MB) (elapsed: 52547 ms) (37.3 KB/s)
```

server logs on alpha-dev
```
[2023-04-18 23:29:58.526] http: GET /admin/transfer/runner/pull (16 ms) 200

Error [ERR_HTTP_REQUEST_TIMEOUT]: Request timeout
at new NodeError (node:internal/errors:393:5)
at onRequestTimeout (node:_http_server:780:30)
at Server.checkConnections (node:_http_server:593:7)
at listOnTimeout (node:internal/timers:564:17)
at process.processTimers (node:internal/timers:507:7)
```

Note: It consistently dies at about **60 seconds**. The number of entities transferred is slightly different each time.

**Comment by christiancp100** [comment] 2023-04-19 07:53
Hi @molund, is there any way we can replicate your issue? Can you share with us what type of hardware your server has and your configuration (if you use nginx, docker, pm2...). Where is your DB? In the same server as your strapi instance? What's your network speed, could that be an issue? 

One of the possibilities is that your server is setting somewhere that websocket connections (or maybe all the connections) are killed after 60 seconds.

**Comment by molund** [comment] 2023-04-19 17:46
Thanks Christian. This is helpful to know that it's using websockets.  

We are hosted on Red Hat OpenShift, including the Postgres DB.  I added some route annotations as suggested in the OpenShift documentation, but it didn't make a difference.....
```
  annotations:
    haproxy.router.openshift.io/timeout: 600s
    haproxy.router.openshift.io/timeout-tunnel: 600s
```
I will continue to investigate on our end.

**Comment by Boegie19** [comment] 2023-04-21 23:52
Closing since strapi made a duplicate of this 
https://github.com/strapi/strapi/issues/16473

**Closed by Boegie19** 2023-04-21 23:52 UTC
