### ISSUE TITLE
Closing the Details dialog in the Media Library throws error

### ISSUE THREAD

**Issue by Simran-B** [strapi/strapi#20516] opened 2024-06-14 10:28 UTC
### Required System information

- Node.js version: node/v18.14.1 win32 x64 workspaces/false
- NPM version: npm/9.3.1
- Strapi version: 5.0.0-beta.10
- Database: sqlite
- Operating system: win32-x64
- Is your project Javascript or Typescript: Type**S**cript

### Describe the bug

I uploaded a local image to the Media Library. Clicking on the image opens the Details dialog and clicking the X button, Finish, or somewhere outside the dialog raises the following error:

```
TypeError: Cannot read properties of undefined (reading 'includes')
    at PreviewBox (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-2YBOHJVO.js?v=03705833:10942:33)
    at renderWithHooks (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:11568:26)
    at updateFunctionComponent (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:14602:28)
    at beginWork (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:15944:22)
    at beginWork$1 (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:19781:22)
    at performUnitOfWork (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:19226:20)
    at workLoopSync (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:19165:13)
    at renderRootSync (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:19144:15)
    at recoverFromConcurrentError (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:18764:28)
    at performSyncWorkOnRoot (http://localhost:1337/node_modules/.strapi/vite/deps/chunk-IYHTQODQ.js?v=03705833:18907:28)
```
      
### Steps to reproduce the behavior

1. `npx create-strapi-app@beta strapi5beta --quickstart` plus workarounds for beta 10 bugs
2. Enter credentials for admin user
3. Go to **Media Library**
4. **Add new assets**, **Browse files**, select a file, **Upload 1 asset to the library**
5. Click the asset and then close the dialog - error occurs

### Expected behavior

The dialog to close without errors.

**Comment by tomowang** [comment] 2024-07-16 12:37
Same here
![image](https://github.com/user-attachments/assets/14d62731-90bd-4a17-9fe3-66b831fb9dbc)

**Comment by derrickmehaffy** [comment] 2024-07-23 21:12
can't reproduce on rc.6 closing

**Closed by derrickmehaffy** 2024-07-23 21:12 UTC
Labels: issue: bug, severity: high, source: core:upload, status: pending reproduction, version: 5
