### ISSUE TITLE
strapi import error - insert into table violates foreign key constraint 

### ISSUE THREAD

**Issue by BigDaddy-Zephyr** [strapi/strapi#20055] opened 2024-04-05 15:29 UTC
### Required System information

- Node.js version: v18.18.0
- NPM version: 9.8.1
- Strapi version: 4.13.6
- Database: Postgres | Supabase
- Operating system: MacOS Sonoma 14.1.1
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I am trying to use `npm strapi import` on a backup created by strapi export, I get an error in the linking phase 

```
⠼ links: 271 transfered (size: 52.8 KB) (elapsed: 21074 ms) (2.5 KB/s)[2024-04-05 20:08:44.464]
  error: [ERROR] insert into "components_home_page_stocks_stock_links" 
("stock_id", "stock_order", "stocks_id") values ($1, $2, $3) - insert or update on table 
"components_home_page_stocks_stock_links" violates foreign key constraint 
"components_home_page_stocks_stock_links_fk"
⠙ links: 271 transfered (size: 52.8 KB) (elapsed: 21074 ms) (2.5 KB/s)Import process failed.
```

This is the schema for the component which is in the homepage
```
{
  "collectionName": "components_home_page_stocks",
  "info": {
    "displayName": "Stocks",
    "description": ""
  },
  "options": {},
  "attributes": {
    "heading": {
      "type": "text"
    },
    "subHeading": {
      "type": "text"
    },
    "ctaLink": {
      "type": "text"
    },
    "ctaText": {
      "type": "text"
    },
    "stock": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::stock.stock"
    }
  }
}
```

And this is the schema type for api/stock

```
{
  "kind": "collectionType",
  "collectionName": "stocks",
  "info": {
    "singularName": "stock",
    "pluralName": "stocks",
    "displayName": "Stock",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "stock": {
      "type": "component",
      "repeatable": false,
      "component": "home-page.stocks-card"
    }
  }
}
```

**Comment by derrickmehaffy** [comment] 2024-04-05 17:10
Duplicate of https://github.com/strapi/strapi/issues/18350 and already patched in a later version

**Closed by derrickmehaffy** 2024-04-05 17:10 UTC
Labels: status: duplicate
