### ISSUE TITLE
Draft/Published labels on collection types appear as "Draft" even when "Published"

### ISSUE THREAD

**Issue by lessainspasorchies** [strapi/strapi#22502] opened 2024-12-23 17:27 UTC
### Required System information

- Node.js version: 20.17.0
- NPM version: 10.8.2
- Strapi version: 5.6.0
- Database: mySQL
- Operating system: darwin arm64 / macOS 15.2 + Ubuntu 24 in prod
- Is your project Javascript or Typescript: TS

### Describe the bug

Draft/Published labels on collection types appear as "Draft" even when "Published"

### Steps to reproduce the behavior

1. Go to 'Content Manager'
2. Click on 'any collection type'
3. Published items get the "Draft" badge on the table
4. Click on any published item for details, the "Published" badge is shown correctly.

Bug was absent

### Expected behavior

Published items get the "Published" badge on the table

### Screenshots

On the collection list table:
![Capture d’écran 2024-12-23 à 18 19 58](https://github.com/user-attachments/assets/d76c008b-44a2-4a9a-8116-07fc27b45a7a)

In the collection item details:
![Capture d’écran 2024-12-23 à 18 22 03](https://github.com/user-attachments/assets/0367d52d-f222-48a8-8e1e-0fb2572a18d0)

### Code snippets

N/A

### Additional context

Bug was absent from previous Strapi versions (5.4 or 5.5). Appeared recently after upgrading.
Same behavior in dev mode locally (macOS 15.2, MacBookPro M1 Max) and in production on an Ubuntu 24 VPS with the same node/npm versions.

**Comment by Xzandro** [comment] 2024-12-23 18:04
Duplicate of #22470. Also already a PR available: https://github.com/strapi/strapi/pull/22473

**Closed** 2024-12-26 16:04 UTC
Labels: status: duplicate

**Comment by AlejandroAndrade98** [comment] 2024-12-30 00:06
Hey there! I just having the same issue in my end, I was thinking that was a conflict between my Strapi and something like the SQL, but I just check everything and seems that it's related with the app.
