### ISSUE TITLE
Error while creating single type Cannot read properties of null (reading 'schema')

### ISSUE THREAD

**Issue by rahul-nara** [strapi/strapi#22118] opened 2024-11-09 18:38 UTC
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by innerdvations** [comment] 2024-11-15 09:07
Duplicate of https://github.com/strapi/strapi/issues/21943

**Closed by innerdvations** 2024-11-15 09:07 UTC
