### ISSUE TITLE
[V4]  File upload does not work gives error code 400

### ISSUE THREAD

**Issue by mbistuer** [strapi/strapi#11528] opened 2021-11-09 18:25 UTC
Hello!

### Describe the bug

It does not work neither in a field of an entity, nor in the section of uploading files

### Screenshots

<img width="1040" alt="Captura de pantalla 2021-11-09 a las 19 15 03" src="https://user-images.githubusercontent.com/14913444/140982215-71c6ff6c-fba8-42fe-b9a4-8b93c2a2a49c.png">

### System

- Node.js version: v14.17.5 
- Strapi version:  v4.0.0-beta.11
- Database: postgres
- Operating system: MAC

**Comment by LucaNerlich** [comment] 2021-11-09 20:40
Duplicate of #11486

**Comment by derrickmehaffy** [comment] 2021-11-09 21:17
Fixed in beta.12 (ty though)

**Closed by derrickmehaffy** 2021-11-09 21:17 UTC
