### ISSUE TITLE
In Digital Ocean App Platform environment, Uploads to Cloudinary causing strapi to crash

### ISSUE THREAD

**Issue by neonnoe** [strapi/strapi#15921] opened 2023-02-26 16:54 UTC
### Required System information

- Node.js version: v17.9.1
- Strapi version: 4.6.2 (had the same behavior with 4.6.1)
- Database: postgres
- provider-upload-cloudinary: 4.6.2
- Installation on Digital Ocean App Platform (Test from localhost does not show this effect)

### Describe the bug

I installed strapi on a Digital Ocean Appl Platform instance and set Cloudinary to be the default upload provider. On my localhost environment everything works fine.

But in the DO live environment, starting an upload of an image from hard drive is infrequently causing strapi instance to crash. It's hard to describe because sometimes I can successfully upload 5-8 images un a row without problems and then suddenly the upload fails and stays in that state: 

<img width="829" alt="image" src="https://user-images.githubusercontent.com/1913046/221423540-4f0d1285-7cb9-4c2a-8651-ac0dbe455724.png">

sometimes I am able to cancel and try again, sometimes strapi crashes completely and showing this screen as a result:

<img width="2001" alt="image" src="https://user-images.githubusercontent.com/1913046/221424038-ff37e952-fefe-4a46-b365-64ff484611e1.png">

### Expected behavior

Upload to Cloudinary without causing crashes.

### Screenshots

See above

**Comment by neonnoe** [comment] 2023-02-26 20:28
I made some additional tests with a freshly installed strapi deployed as a DO app. I could reproduce the error and it seems to be dependent on the size of the images.

My default image size for uploading is 3000x2000 px. With size sometimes an upload is successfull, sometimes not.

With a smaller image size 2000x1333 all uploads seem to be successfull.

Selecting several larger images for the upload (5 images, each 2000x1333) fail everytime.

**Comment by iamterryclark** [comment] 2023-03-25 16:39
Yes I am also experiencing this with Strapi 4.8.2 production

I want to bulk upload and it does not complete. On my local strapi instance this is fine and completes bulk upload quickly.

**Comment by goodhoko** [comment] 2023-05-03 10:07
This has very likely the same cause as https://github.com/strapi/strapi/issues/16210.

**Comment by Boegie19** [comment] 2023-05-24 10:29
seems to me like this is a duplicate of https://github.com/strapi/strapi/issues/16210 

closing this one in favor of the other one.

**Closed by Boegie19** 2023-05-24 10:29 UTC
Labels: issue: bug, severity: low, source: core:upload, status: pending reproduction
