### ISSUE TITLE
Enum value with hyphen breaks

### ISSUE THREAD

**Issue by laportem** [strapi/strapi#1698] opened 2018-08-06 08:01 UTC
**Informations**
- **Node.js version**: 10.1.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.13.0.1
- **Database**: mongodb 4.0
- **Operating system**:  Ubuntu 14.04

**What is the current behavior?**
Looks like the enum field type is ultra-sensitive. If I have a value with hyphen the server failed to start
For example: this model entry works. Notice **no hyphen** with ""Free range Farming"

`    
"husbandry": {
      "type": "enumeration",
      "enum": [
        "Conventional Farming",
        "Organic Farming",
        "Factory Farming",
        "Free range Farming"
      ]
    }
`

and this one does not work. the server failed to start. Notice **the hyphen** with ""Free-range Farming"

`    
"husbandry": {
      "type": "enumeration",
      "enum": [
        "Conventional Farming",
        "Organic Farming",
        "Factory Farming",
        "Free-range Farming"
      ]
    }
`

the error on startup is:

`
/home/vagrant/strapiapp/node_modules/mongodb/lib/operations/mongo_client_ops.js:439
      throw err;
      ^
GraphQLError: Syntax Error: Invalid number, expected digit but got: "r".
    at syntaxError (/home/vagrant/strapiapp/plugins/graphql/node_modules/graphql/error/syntaxError.js:24:10)
`

**Steps to reproduce the problem**
Just add an enum field type and enter a value with hyphen 

**What is the expected behavior?**
hyphenated enum values are common and it should be accepted and not break the server

**Suggested solutions**
Allow for enum to have hyphenated values

**Comment by derrickmehaffy** [comment] 2018-08-06 08:14
@laportem this is a common issue if you have the GraphQL plugin installed, I ran into a similar issue with using spaces in Enum Values. 

I believe the implementation is based on Facebook's GraphQL enumeration `Name` which is as such:

`/[_A-Za-z][_0-9A-Za-z]*/`

Which basically translates to upper/lowercase letters, numbers, and underscore as the only allowed values. This is an issue from the upstream graphQL provider and not strapi itself, I believe the issue happens in schema generation, my recommendation is store them in this format and translate them on your frontend using some kind of alias.

IE: `conventialFarming` = `Conventional Farming` ect.

You can see the Facebook doc here: http://facebook.github.io/graphql/June2018/#Name

**Comment by lauriejim** [comment] 2018-08-23 12:32
Hello @laportem , thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by mmichelli** [comment] 2018-09-04 07:46
Enum also breaks if you use special characters, øæå

**Comment by mmichelli** [comment] 2018-09-04 08:04
Any attribute with a space breaks the plugin

**Comment by lauriejim** [comment] 2018-09-04 09:39
Thank you @mmichelli for these details

**Comment by derrickmehaffy** [comment] 2018-09-04 09:43
As stated above, currently the only allowed characters due to an upstream limitation is:

`/[_A-Za-z][_0-9A-Za-z]*/`

I recommend you use these to build your enums then translate them on your frontend application.

**Comment by MartinMuzatko** [comment] 2018-11-14 13:37
if you add double quotes to the graphql definition, then there are no problems.

e.g.:

```
enum ENUM_LOCATION_COUNTRY {  
 "Baden-Württemberg"
 Bayern 
 Berlin 
 "Thüringen"
 Bremen 
 Hamburg 
 Hessen
 Japan 
 China } type Location {
  id: ID!
  latitude: String
  longitude: String
  country: ENUM_LOCATION_COUNTRY!
}
```

**Comment by veryscarycary** [comment] 2019-03-22 06:45
> if you add double quotes to the graphql definition, then there are no problems.
> 
> e.g.:
> 
> ```
> enum ENUM_LOCATION_COUNTRY {  
>  "Baden-Württemberg"
>  Bayern 
>  Berlin 
>  "Thüringen"
>  Bremen 
>  Hamburg 
>  Hessen
>  Japan 
>  China } type Location {
>   id: ID!
>   latitude: String
>   longitude: String
>   country: ENUM_LOCATION_COUNTRY!
> }
> ```

This didn't work for me.

`Syntax Error: Expected Name, found String "Baden-Württemberg"`

**Comment by MartinMuzatko** [comment] 2019-03-22 08:21
Did you change that in your enum via strapi or in the generated graphql definition? @veryscarycary

**Comment by MatheusRV** [comment] 2019-04-05 16:38
Why not lock the input of special characters on the web ui?

**Comment by Aurelsicoko** [comment] 2019-04-12 12:37
@MatheusRV It's already done in the latest release, it should be available soon...

**Comment by derrickmehaffy** [comment] 2019-04-12 12:42
@Aurelsicoko I think you mean the master branch.

@MatheusRV It should be in the release that goes out monday

**Comment by Aurelsicoko** [comment] 2019-04-16 16:10
It is not done in the latest release... I made a mistake with the issue, I thought we were talking about another issue. The only changes we made is to remove the separation of the values with a comma by inserting one value per line.

The issue is still existing. We have to update the GraphQL plugin and generate the enumeration type with double-quotes around each value.

**Comment by tamihh** [comment] 2019-05-06 16:50
@Aurelsicoko any update about this issue? I am having the same problem here. It breaks everything and doesn't create a collection on db so I had to start everything again instead of just drop the collection.

**Comment by lauriejim** [comment] 2019-05-07 12:08
@tamihh update your generated models of the API `./api/:model/models/:Modes.settings.json` and remove the enum attribute, then you can restart your server.

We are currently focused on the beta version. So this issue is not a priority for us now.

**Comment by Aurelsicoko** [comment] 2019-05-10 08:51
@tamihh If you have enough time you can try to make a PR? We would love to merge it and close this issue in the same time :)

**Comment by tamihh** [comment] 2019-05-22 18:30
Sure! thanks for helping :)

**Closed** 2019-09-09 11:32 UTC
Labels: Good for new contributors, priority: medium, status: confirmed, type: bug 🐛
