### ISSUE TITLE
[v4] Strapi crash after creating components and attribute with same name

### ISSUE THREAD

**Issue by martincapek** [strapi/strapi#11909] opened 2021-12-14 19:45 UTC
### Describe the bug
Strapi crashes after I create component with same two names but different types (relation/component and text).  

A have this component. It is just dummy section with string named heading 
<img width="1210" alt="Screenshot 2021-12-14 at 14 54 53" src="https://user-images.githubusercontent.com/12203768/146067996-b14fbc30-4992-4f82-a51c-6be49a349503.png">

And Smart Section that contains heading as component.
<img width="1221" alt="Screenshot 2021-12-14 at 14 56 51" src="https://user-images.githubusercontent.com/12203768/146068162-e9d2236d-a673-49d9-a16c-cdd4e20a0513.png">

After I save it strapi returns bad request 
<img width="742" alt="Screenshot 2021-12-14 at 14 57 21" src="https://user-images.githubusercontent.com/12203768/146068217-e1a0b431-6a61-4ab6-82cd-1f5b5eb0f3aa.png">

Whole entry can't be deleted and list endpoint return error 500.

Error in console is 
<img width="1008" alt="Screenshot 2021-12-14 at 20 42 52" src="https://user-images.githubusercontent.com/12203768/146068334-5e839552-30cd-473d-b593-d1faf78a82e4.png">

After I commented out 
```JS
if (!types.isRelation(attribute.type)) {
      throw new Error(`Invalid populate field. Expected a relation, got ${attribute.type}`);
    }
```
from `node_modules/@strapi/database/lib/query/helpers/populate.js` it works. 

But I don't know if that can broke anything else.

**Comment by martincapek** [comment] 2021-12-14 19:50
I think its because you populate just names not whole path of component. 

This issue is also related. If I commented out same code this start working too.
https://github.com/strapi/strapi/issues/11857

**Comment by martincapek** [comment] 2021-12-15 15:48
Also https://github.com/strapi/strapi/issues/11919 looks like same problem..

**Comment by derrickmehaffy** [comment] 2021-12-21 20:13
closing as @martincapek is correct

**Comment by aleksei-savitski-softswiss** [comment] 2022-01-17 17:00
hi @derrickmehaffy @martincapek 

I think the issue described here is not related to  #11919 and is rather a bug in content-manager queries. Because error happens when I create an entity through Content Manager UI.

You can reproduce it with following content types and componets:

<details>
  <summary>Content type whith dynamic zone with 2 componets: </summary>
  
```json
{
  "kind": "singleType",
  "collectionName": "tests",
  "info": {
    "singularName": "test",
    "pluralName": "tests",
    "displayName": "test",
    "description": ""
  },
  "options": {
    "draftAndPublish": false
  },
  "pluginOptions": {},
  "attributes": {
    "dz": {
      "type": "dynamiczone",
      "components": [
        "content.label",
        "content.image"
      ]
    }
  }
}
```
</details>

<details>
  <summary>Component with attribute 'value' of <strong>media</strong> type:</summary>
  
```
{
  "collectionName": "components_content_images",
  "info": {
    "displayName": "Image",
    "icon": "image",
    "description": ""
  },
  "options": {},
  "attributes": {
    "key": {
      "type": "string",
      "required": true
    },
    "value": {
      "type": "media",
      "multiple": false,
      "required": true,
      "allowedTypes": [
        "images"
      ]
    }
  }
}
```
</details>

<details>
  <summary>Component with attribute 'value' of <strong>string</strong> type:</summary>
  
```
{
  "collectionName": "components_content_labels",
  "info": {
    "displayName": "Label",
    "icon": "pencil-alt",
    "description": ""
  },
  "options": {},
  "attributes": {
    "key": {
      "type": "string",
      "required": true
    },
    "value": {
      "type": "string",
      "required": true
    }
  }
}
```
</details>

Even when I create a entity with only Label component in dynamic zone the query builder thinks that 'value' property is complex type and prepares populate object with `dz: { populate: { value: true } },`.

To workaround the issue I can rename `value` attribute in my Image component.

**Comment by derrickmehaffy** [comment] 2022-02-14 21:22
will reopen as not a duplicate

**Comment by dogunbound** [comment] 2022-04-15 21:25
Similar issue to https://github.com/strapi/strapi/issues/11955

video explaining why I think so: https://www.youtube.com/watch?v=j-TYly0s0L0

**Comment by derrickmehaffy** [comment] 2022-05-05 21:16
Duplicate: https://github.com/strapi/strapi/issues/1198

**Closed by derrickmehaffy** 2022-05-05 21:16 UTC
Labels: issue: bug, severity: medium, status: duplicate, source: core:content-manager, status: pending reproduction

**Comment by chrift** [comment] 2022-08-08 13:52
I am on 4.3.2 and have just come across this issue, I don't think it's fixed.

Here is my dynamic zone structure:
```
{
  zoneItem1: {
   authenticated: 'relation to another item'
  },
  zoneItem2 : {
    authenticated: boolean
  }
}```

Navigating to the collection type page for this dynamic zone errors with: 
```error: Invalid populate field. Expected a relation, got boolean
Error: Invalid populate field. Expected a relation, got boolean
```

crashes with

**Comment by derrickmehaffy** [comment] 2022-08-08 14:01
> I am on 4.3.2 and have just come across this issue, I don't think it's fixed.
> 
> Here is my dynamic zone structure:
> 
> ```
> {
>   zoneItem1: {
>    authenticated: 'relation to another item'
>   },
>   zoneItem2 : {
>     authenticated: boolean
>   }
> }
> ```
> 
> Navigating to the collection type page for this dynamic zone errors with:
> 
> ```
> Error: Invalid populate field. Expected a relation, got boolean
> ```

This issue isn't fixed but it's a duplicate of another issue, please see #1198
