### ISSUE TITLE
TypeScript package is missing on core using pnpm

### ISSUE THREAD

**Issue by ScreamZ** [strapi/strapi#16280] opened 2023-04-03 09:35 UTC
### Required System information

- Node.js version: v18.15.0
- NPM version: 9.6.0 (pnpm 8.1.0)
- Strapi version: 9.6.0
- Database: sqlite
- Operating system: OSX Sillicon Chip
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Using `pnpm`, I'm getting the following messages.
> File '@strapi/typescript-utils/tsconfigs/server' not found.
in `tsconfig.json`.

Without `pnpm` it's ok.

It's probably due to the nature of `pnpm` of creating non-flat node_modules
> « pnpm creates a non-flat node_modules by default, so code has no access to arbitrary packages. »

### Steps to reproduce the behavior

`pnpm create strapi-app strapi-cityway --quickstart --ts --no-run `

### Expected behavior

TypeScript typing should be exposed or listed as dev-deps

**Comment by joshuaellis** [comment] 2023-04-11 08:28
I think this is a duplicate of another issue, read this comment for help please :) https://github.com/strapi/strapi/issues/15992#issuecomment-1485295974

**Closed by joshuaellis** 2023-04-11 08:28 UTC
Labels: issue: bug, severity: low, status: pending reproduction, source: typescript

**Comment by ScreamZ** [comment] 2023-04-11 08:33
@joshuaellis I'm not sure, and `shamefully-hoist=true` is not an option, because this means « apply the default npm logic » which is a bad specification because it allows using module of other modules whereas they are not defined as dependencies, which can results in a lot of breaking change side effect when upgrading some library.

**Comment by ScreamZ** [comment] 2023-04-11 08:47
@joshuaellis I understand the answer and I agree that you don't want to spend time on that at the moment. But you shouldn't mark this issue as resolved cbcause as you just said, it's a workaround and not expected behavior.

This could be nice to have some tracking on that :)

Have a nice day
