### ISSUE TITLE
Fresh install of strapi won't launch on Windows

### ISSUE THREAD

**Issue by eltharynd** [strapi/strapi#12158] opened 2022-01-10 14:24 UTC
### Describe the bug

I install the thing with either npm or yarn, then when i try to run
`npm develop` or `yarn develop` i get the same thing (that also puts my 5950x at 100% usage till i force close it)

https://i.imgur.com/NnlfYBr.mp4

### Steps to reproduce the behavior

1. run `npx create-strapi-app@latest my-project` 
2. run `yarn develop` 

### System

- Node.js version: v16 (tried different versions and clean install)
- NPM version: 8.1.2
- YARN version: 1.22.17
- Strapi version: @latest
- Database: tried SQLlite and MySQL
- Operating system: Windows 11

**Comment by kasonde** [comment] 2022-01-10 14:26
Duplicate of #12142

**Closed by kasonde** 2022-01-10 14:26 UTC
