### ISSUE TITLE
Media Library blank page in production.

### ISSUE THREAD

**Issue by mckennapaul27** [strapi/strapi#15454] opened 2023-01-15 14:46 UTC
### Required System information

- Node.js version: 
- NPM version: 8.1.2
- Strapi version: 4.5.6
- Database: 16.13.2
- Operating system: Mac

### Describe the bug

We have a Strapi CMS in production and it has been working perfectly.

Since yesterday the media library has been inaccessible from the admin UI in production. (get a blank screen)

It works perfectly fine locally but not in production.

- Cloudinary is the provider we are using.
- No images have been uploaded using API, only through the admin UI.

I have tried doing all the regular steps (rm cache, rm build, rm node_modules, rebuild etc) and I have tried updating to latest 4.5.6 and also tried 4.1.10.

I am getting the error:

<img width="1547" alt="Screenshot 2023-01-15 at 14 31 37" src="https://user-images.githubusercontent.com/29250192/212546752-2eb9df68-2ff0-437b-bf6d-9561afd0f084.png">

When I click on the error message it shows:

<img width="1664" alt="Screenshot 2023-01-15 at 14 32 41" src="https://user-images.githubusercontent.com/29250192/212546798-0d925dd4-ffe3-413f-b036-965aaec7b8b7.png">

As I said, media has only be uploaded from the UI, not via API.

When we try to add media from within content manager, we get the following error:

<img width="1336" alt="Screenshot 2023-01-15 at 14 49 55" src="https://user-images.githubusercontent.com/29250192/212548158-8e966152-86c1-4e21-b0aa-fc13f4f4051f.png">

When we go to Media Library we get the following:

<img width="1600" alt="Screenshot 2023-01-15 at 14 50 48" src="https://user-images.githubusercontent.com/29250192/212548199-354db922-770d-4660-9df8-7bbe369991ee.png">

### Steps to reproduce the behavior

The bug seemed to occur for no reason. The CMS has over 400 posts and 5000 images so I cannot think how I reproduce the behaviour. The bug appears to have come from nowhere. Since it is working fine locally I have checked environment variables and anything else I can think of that differs between local and production.

**Comment by petersg83** [comment] 2023-01-24 14:18
Hello :) 
It looks like this issue : https://github.com/strapi/strapi/issues/13174

Can you confirm there are files in your database (table `files`) that don't have a mime type (column `mime`)?

It's something that should not happen since we now set a default one if none is provided or detected. Do you have more info on how the files missing the mime value are uploaded to Strapi?

**Comment by mckennapaul27** [comment] 2023-01-25 09:30
Hi,

Thanks for getting back to me :-)

After adding more images, I realised the issue is just on 2 pages in the media library. This made it look like the whole media library was going to blank page as previously the images with the issue were on page 1 and 2.

So that means we have been able to continue using our CMS but we just can't access those 2 pages in media library. 

I have queried the database and yes, there are 4 images with no mime type (see below).

![Screenshot 2023-01-25 at 09 28 54](https://user-images.githubusercontent.com/29250192/214527142-0bd30d09-5791-4e2f-aaa0-c86a63a603f2.png)

The strange thing about this is that 100% of the image uploads have occurred via the admin UI. We are not using API to upload any images.

Issue https://github.com/strapi/strapi/issues/13174 covers API uploads only.

No idea what has caused this bug or why it has not set a default one as per the PR.

Thanks again

**Comment by petersg83** [comment] 2023-02-14 10:35
Thanks ! :) Would it be possible to send me one of the file that don't have a mime type ? So I can try to reproduce

**Comment by petersg83** [comment] 2023-02-14 11:07
> Issue #13174 covers API uploads only.

I looked at the code and the code should fix the issue for both the CONTENT API and the ADMIN API.


Do you know when those files were uploaded? In a Strapi version bellow [4.1.10](https://github.com/strapi/strapi/milestone/176) ? (it was released May 11th, 2022).
If yes, then you just need to put the write Mime in the database and the issue should not appear again

**Comment by joshuaellis** [comment] 2023-02-23 10:30
Great to here this solved the issue for you @mckennapaul27.

> The files were probably uploaded about 6 months ago and then all of a sudden they just could not be accessed. I think they may have been webp - not sure if that would cause an issue?

It shouldn't be. Because the issue is now resolved and we believe it shouldn't be happening anymore, i'm gonna close this. However, if the issue crops up again (especially with webp) then please, don't hesitate to open a new issue :)

**Closed by joshuaellis** 2023-02-23 10:30 UTC
Labels: issue: bug, severity: medium, source: core:upload, status: pending reproduction
