### ISSUE TITLE
[BUG] Error at saving Page's list view values with provider into the columns

### ISSUE THREAD

**Issue by SalahAdDin** [strapi/strapi#14022] opened 2022-08-09 01:36 UTC
### Required System information

- Node.js version: 4.3.2 (node v14.20.0)
- Strapi version: 4.3.2
- Plugin version: 2.0.8
- Database: PostgreSQL 13.7
- Operating system: Alpine Linux v3.16

### Describe the bug

When we try to add the **provider** property to the list view(as a column), we get the following error when saving it:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://analytics.strapi.io/track. (Reason: CORS request did not succeed). Status code: (null).
Uncaught (in promise) Error: Network Error
    exports http://localhost:1337/admin/main.c129a3b1.js:13118
    onerror http://localhost:1337/admin/main.c129a3b1.js:13118
    exports http://localhost:1337/admin/main.c129a3b1.js:13118
    exports http://localhost:1337/admin/main.c129a3b1.js:13118
    exports http://localhost:1337/admin/main.c129a3b1.js:13118
    request http://localhost:1337/admin/main.c129a3b1.js:13118
    d http://localhost:1337/admin/main.c129a3b1.js:13118
    exports http://localhost:1337/admin/main.c129a3b1.js:13118
    current http://localhost:1337/admin/main.c129a3b1.js:13103
    N http://localhost:1337/admin/content-manager.f89a9295.chunk.js:1178
    Kt http://localhost:1337/admin/main.c129a3b1.js:17497
    kn http://localhost:1337/admin/main.c129a3b1.js:17497
    Xt http://localhost:1337/admin/main.c129a3b1.js:17497
    Dr http://localhost:1337/admin/main.c129a3b1.js:17497
    xr http://localhost:1337/admin/main.c129a3b1.js:17497
    Wi http://localhost:1337/admin/main.c129a3b1.js:17497
    We http://localhost:1337/admin/main.c129a3b1.js:17501
    pt http://localhost:1337/admin/main.c129a3b1.js:17497
    Wi http://localhost:1337/admin/main.c129a3b1.js:17497
    Vr http://localhost:1337/admin/main.c129a3b1.js:17497
    Br http://localhost:1337/admin/main.c129a3b1.js:17497
    unstable_runWithPriority http://localhost:1337/admin/main.c129a3b1.js:17551
    rd http://localhost:1337/admin/main.c129a3b1.js:17497
    bt http://localhost:1337/admin/main.c129a3b1.js:17501
    si http://localhost:1337/admin/main.c129a3b1.js:17497
main.c129a3b1.js:13118:29523
XHRPUThttp://localhost:1337/content-manager/content-types/plugin::users-permissions.user/configuration
[HTTP/1.1 400 Bad Request 365ms]

	
PUT
	http://localhost:1337/content-manager/content-types/plugin::users-permissions.user/configuration
Status
400
Bad Request
VersionHTTP/1.1
Transferred1.27 kB (256 B size)
Referrer Policyno-referrer
Request PriorityHighest

Error: Request failed with status code 400
    exports http://localhost:1337/admin/main.c129a3b1.js:13176
    exports http://localhost:1337/admin/main.c129a3b1.js:13176
    E http://localhost:1337/admin/main.c129a3b1.js:13176
    exports http://localhost:1337/admin/main.c129a3b1.js:13176
    exports http://localhost:1337/admin/main.c129a3b1.js:13176
    exports http://localhost:1337/admin/main.c129a3b1.js:13176
    promise callback*30321/s.prototype.request http://localhost:1337/admin/main.c129a3b1.js:13176
    d http://localhost:1337/admin/main.c129a3b1.js:13176
    exports http://localhost:1337/admin/main.c129a3b1.js:13176
    Dv http://localhost:1337/admin/content-manager.f89a9295.chunk.js:1111
    74239/Xl/$< http://localhost:1337/admin/content-manager.f89a9295.chunk.js:1178
    fn http://localhost:1337/admin/main.c129a3b1.js:17523
    f http://localhost:1337/admin/main.c129a3b1.js:17523
    s http://localhost:1337/admin/main.c129a3b1.js:17523
    executeMutation http://localhost:1337/admin/main.c129a3b1.js:17523
    i http://localhost:1337/admin/main.c129a3b1.js:17523
    promise callback*98816/b.execute http://localhost:1337/admin/main.c129a3b1.js:17523
    mutate http://localhost:1337/admin/main.c129a3b1.js:17523
    R http://localhost:1337/admin/main.c129a3b1.js:17523
    W http://localhost:1337/admin/content-manager.f89a9295.chunk.js:1178
    Kv http://localhost:1337/admin/content-manager.f89a9295.chunk.js:1178
    Kv http://localhost:1337/admin/content-manager.f89a9295.chunk.js:1178
    W http://localhost:1337/admin/content-manager.f89a9295.chunk.js:1178
    onClick http://localhost:1337/admin/main.c129a3b1.js:2988
    Kt http://localhost:1337/admin/main.c129a3b1.js:17497
    kn http://localhost:1337/admin/main.c129a3b1.js:17497
    Xt http://localhost:1337/admin/main.c129a3b1.js:17497
    Dr http://localhost:1337/admin/main.c129a3b1.js:17497
    xr http://localhost:1337/admin/main.c129a3b1.js:17497
    Wi http://localhost:1337/admin/main.c129a3b1.js:17497
    We http://localhost:1337/admin/main.c129a3b1.js:17501
    pt http://localhost:1337/admin/main.c129a3b1.js:17497
    Wi http://localhost:1337/admin/main.c129a3b1.js:17497
    Vr http://localhost:1337/admin/main.c129a3b1.js:17497
    Br http://localhost:1337/admin/main.c129a3b1.js:17497
    unstable_runWithPriority http://localhost:1337/admin/main.c129a3b1.js:17551
    rd http://localhost:1337/admin/main.c129a3b1.js:17497
    bt http://localhost:1337/admin/main.c129a3b1.js:17501
    si http://localhost:1337/admin/main.c129a3b1.js:17497
    As http://localhost:1337/admin/main.c129a3b1.js:17497
    Xo http://localhost:1337/admin/main.c129a3b1.js:17497
    qi http://localhost:1337/admin/main.c129a3b1.js:17497
    qi http://localhost:1337/admin/main.c129a3b1.js:17497
    qh http://localhost:1337/admin/main.c129a3b1.js:17497
    vl http://localhost:1337/admin/main.c129a3b1.js:17501
    Km http://localhost:1337/admin/main.c129a3b1.js:17501
    th http://localhost:1337/admin/main.c129a3b1.js:17501
    eh http://localhost:1337/admin/main.c129a3b1.js:17501
    hc http://localhost:1337/admin/main.c129a3b1.js:17499
    hg http://localhost:1337/admin/main.c129a3b1.js:17497
    unstable_runWithPriority http://localhost:1337/admin/main.c129a3b1.js:17551
    rd http://localhost:1337/admin/main.c129a3b1.js:17497
    hg http://localhost:1337/admin/main.c129a3b1.js:17497
    ll http://localhost:1337/admin/main.c129a3b1.js:17497
    bt http://localhost:1337/admin/main.c129a3b1.js:17501
    si http://localhost:1337/admin/main.c129a3b1.js:17497
main.c129a3b1.js:17523:11972
    i http://localhost:1337/admin/main.c129a3b1.js:17523
    (Async: promise callback)
    execute http://localhost:1337/admin/main.c129a3b1.js:17523
    mutate http://localhost:1337/admin/main.c129a3b1.js:17523
    R http://localhost:1337/admin/main.c129a3b1.js:17523
    W http://localhost:1337/admin/content-manager.f89a9295.chunk.js:1178
    Kv http://localhost:1337/admin/content-manager.f89a9295.chunk.js:1178
    Kv http://localhost:1337/admin/content-manager.f89a9295.chunk.js:1178
    W http://localhost:1337/admin/content-manager.f89a9295.chunk.js:1178
    onClick http://localhost:1337/admin/main.c129a3b1.js:2988
    Kt http://localhost:1337/admin/main.c129a3b1.js:17497
    kn http://localhost:1337/admin/main.c129a3b1.js:17497
    Xt http://localhost:1337/admin/main.c129a3b1.js:17497
    Dr http://localhost:1337/admin/main.c129a3b1.js:17497
    xr http://localhost:1337/admin/main.c129a3b1.js:17497
    Wi http://localhost:1337/admin/main.c129a3b1.js:17497
    We http://localhost:1337/admin/main.c129a3b1.js:17501
    pt http://localhost:1337/admin/main.c129a3b1.js:17497
    Wi http://localhost:1337/admin/main.c129a3b1.js:17497
    Vr http://localhost:1337/admin/main.c129a3b1.js:17497
    Br http://localhost:1337/admin/main.c129a3b1.js:17497
    unstable_runWithPriority http://localhost:1337/admin/main.c129a3b1.js:17551
    rd http://localhost:1337/admin/main.c129a3b1.js:17497
    bt http://localhost:1337/admin/main.c129a3b1.js:17501
    si http://localhost:1337/admin/main.c129a3b1.js:17497
    As http://localhost:1337/admin/main.c129a3b1.js:17497
    Xo http://localhost:1337/admin/main.c129a3b1.js:17497
    qi http://localhost:1337/admin/main.c129a3b1.js:17497
    qi http://localhost:1337/admin/main.c129a3b1.js:17497
    qh http://localhost:1337/admin/main.c129a3b1.js:17497
    vl http://localhost:1337/admin/main.c129a3b1.js:17501
    Km http://localhost:1337/admin/main.c129a3b1.js:17501
    th http://localhost:1337/admin/main.c129a3b1.js:17501
    eh http://localhost:1337/admin/main.c129a3b1.js:17501
    hc http://localhost:1337/admin/main.c129a3b1.js:17499
    hg http://localhost:1337/admin/main.c129a3b1.js:17497
    unstable_runWithPriority http://localhost:1337/admin/main.c129a3b1.js:17551
    rd http://localhost:1337/admin/main.c129a3b1.js:17497
    hg http://localhost:1337/admin/main.c129a3b1.js:17497
    ll http://localhost:1337/admin/main.c129a3b1.js:17497
    bt http://localhost:1337/admin/main.c129a3b1.js:17501
    si http://localhost:1337/admin/main.c129a3b1.js:17497

```

### Steps to reproduce the behavior

1. Go to 'Content Manager > Users'
2. Click on 'Configure the View'
3. Add the `provider` property in 'View'
4. Click on 'Save'.
5. Click on 'Confirmation'.
6. See the `Warning` alert.

### Expected behavior

It would save the updated settings.

### Screenshots

<img width="1222" alt="Screen Shot 2022-08-09 at 04 19 28" src="https://user-images.githubusercontent.com/5034215/183541922-b6519967-a333-4aa2-b0a4-2ee7e3d17d19.png">

<img width="1253" alt="Screen Shot 2022-08-09 at 04 23 22" src="https://user-images.githubusercontent.com/5034215/183542302-b4369c53-df51-481e-b40b-47fd948e7de9.png">

**Comment by jhoward1994** [comment] 2023-02-13 14:13
Duplicate of https://github.com/strapi/strapi/issues/12611

**Closed by jhoward1994** 2023-02-13 14:13 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:content-manager
