### ISSUE TITLE
The records remain after deleting their Content-Type

### ISSUE THREAD

**Issue by AminZibayi** [strapi/strapi#3869] opened 2019-08-29 19:15 UTC
**Describe the bug**
After deleting a Content-Type, The created records for that Content-Type will remain

**Steps to reproduce the behavior**
1. Create a new Content-Type
2. Create some records
3. Delete Content-Type
4. Check the database and see that the created records are remaining

**Expected behavior**
After deleting a Content-Type, The related records should be deleted.

**System**
- Node.js version: v10.16.0
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.9
- Database: MongoDB
- Operating system: Ubuntu

**Comment by soupette** [comment] 2019-08-30 09:52
@AminZibayi it is an intended behaviour, similarly when you remove an attribute of your content type we don't delete the associated column in your database.

**Comment by derrickmehaffy** [comment] 2019-08-30 09:59
Closing as duplicate of here: https://github.com/strapi/strapi/issues/1114

@AminZibayi I would recommend you take a look at the linked issue as there was a lot of discussion about this, no implementation timeline yet but it was discussed at length. For now you will need to go drop the collection manually

**Closed by derrickmehaffy** 2019-08-30 09:59 UTC
Labels: type: discussion ✍️
