### ISSUE TITLE
Model attribute length's conditions not used

### ISSUE THREAD

**Issue by edimitchel** [strapi/strapi#279] opened 2017-10-16 15:12 UTC
**Node.js version**:
5.4.2
**npm version**:
v8.6.0
**Strapi version**:
3.0.0-alpha.6.3
**Operating system**:
CentOS 7

**Title + Images Speak Louder Than Words**

![image](https://user-images.githubusercontent.com/2922851/31619367-9e91ffcc-b294-11e7-923d-d2589ad49c8b.png)
![image](https://user-images.githubusercontent.com/2922851/31619440-cc8ae6b4-b294-11e7-9243-b753033c3748.png)
![image](https://user-images.githubusercontent.com/2922851/31619451-d71c98a2-b294-11e7-9bd4-3a125104574e.png)
![image](https://user-images.githubusercontent.com/2922851/31619543-19d56f7a-b295-11e7-8f8a-ab782d779929.png)

**Comment by Aurelsicoko** [comment] 2017-10-16 15:31
@edimitchel Thanks for reporting this issue! I'm not sure to understand what's the issue here? The error messages are correct and the validations work fine on my machine.

**Comment by edimitchel** [comment] 2017-10-16 15:35
@Aurelsicoko I've no validation error when I create an Event with a title small than 10 or longer than 50 even with the constraint that I've set.

**Comment by Aurelsicoko** [comment] 2017-10-16 15:39
![Screenshot](https://cldup.com/958ib0hfLP-3000x3000.png)

I tested on both `string` and  `text` type.

**Comment by edimitchel** [comment] 2017-10-16 15:43
And with 5 characters ?

**Comment by Aurelsicoko** [comment] 2017-10-16 15:48
Yes, it works as well. Try to reload your page. I'm sorry but I can't reproduce your issue, I need more details.

![Screenshot - It works!](https://cldup.com/13cNghQAkw.thumb.png)

**Comment by edimitchel** [comment] 2017-10-30 14:26
Let see the issue in live !

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2922851/32175952-a831b818-bd86-11e7-984b-d2b3eae97cdc.gif)

**Comment by edimitchel** [comment] 2017-10-30 14:33
Require's condition working well but not about length..

**Comment by soupette** [comment] 2017-10-31 13:22
It should be fixed and available in the next release https://github.com/strapi/strapi/pull/313/commits/35d7993cf6400edd99ed8f25102a6ff496198052

**Closed by soupette** 2017-10-31 13:22 UTC
Labels: admin, bug

**Comment by edimitchel** [comment] 2017-10-31 13:26
Thanks !
