### ISSUE TITLE
error on model/bookshelf-level does not get passed on to strapi-admin/context (error: duplicate key value violates unique constraint "root_slug_unique")

### ISSUE THREAD

**Issue by speexy** [strapi/strapi#5227] opened 2020-02-11 16:05 UTC
**Describe the bug**
I'm setting a unique-constraint on a field that gets populated from other content-type-fields. When I create a duplicate entry, the model/bookshelf correctly throws an error. However in the strapi admin this fails silently. 

**Steps to reproduce the behavior**
1. Create ContentTypeA with a field "slug" and a one-to-many relationship with "Roots"
2. Create ContentTypeB with a field "slug" and a one-to-many relationship with "Roots"
3. Create a content type "Root" with a field "slug" and make the field unique
4. write functions for ContenTypeA an ContentTypeB that add the slug to "Roots" (via `beforeSave` and `afterSave`), examples:
```
update:  async (model, attr, options) => {
  if (options.method=="update" && model.hasChanged('slug')){
      strapi.query('root').create({slug: slugify(attr.slug), [model.tableName] : model.id})
  }
},
create: async(model, response, options) =>{
  if (response.method==="insert"){
      strapi.query('root').create({ slug: slugify(model.attributes.slug), [model.tableName]: model.id})
  }
}
```
5. Add a new ContentTypeA entry with "uniqueslug" in the slug field and save.
6. Add a new ContentTypeA entry with "uniqueslug" in the slug field and save.

**Expected behavior**
Step 6 should throw an error in the admin. Instead it will create the entry but fail at inserting the slug into "Roots"
This also applies in the case of updating.

**More context**
In my code I have both a `beforeSave` and an `afterSave` hook. I could see why this happens `afterSave`, but at least in the update case, which get's triggered with `beforeSave`, the save should fail in the admin and display the error. 

I can catch the error in the hook `strapi.query('root').create({slug: slugify(attr.slug), [model.tableName] : model.id}).catch(e=>console.log("my error ", e))` but don't see how I could pass it on. I think it needs to go into the ctx-object somehow?

I tried to intercept this with the controller, which receives the context object, but apparently the controller methods don't get triggered by actions in the admin. 

Any ideas for workarounds appreciated

**System**
- Node.js version: ">=10.0.0",
- NPM version: ">=6.0.0"
- Strapi version: "3.0.0-beta.18.2",
- Database: postgres 12.1 (Debian 12.1-1.pgdg100+1)
- Operating system: docker/ubuntu16.04LTS

**Comment by derrickmehaffy** [comment] 2020-02-11 16:10
@speexy Lifecycle callbacks are currently considered broken: https://github.com/strapi/strapi/issues/1443

You can (as you tried) use the controller workaround for the REST/GraphQL, for the AdminUI you will need to override the Content Manager Plugin following the plugin extensions on the documentation.

Specifically this file: https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-content-manager/controllers/ContentManager.js

Which as you can guess is not easy as you will have to check which model is being called to properly handle for only that model. Not difficult but not clean either.

I will let @lauriejim decide if this is a duplicate of #1443 or not and close.

**Comment by lauriejim** [comment] 2020-02-13 13:55
Hello! This is due to the life cycle issue yes.
Access to `ctx` from life cycle function is a part of the issue.
I'm closing this issue, but thank you for this use case. That will help us to develop the fix and make sure all use cases are covered.

**Closed by lauriejim** 2020-02-13 13:55 UTC
