### ISSUE TITLE
[v4] GraphQL cache issue because of API schema format

### ISSUE THREAD

**Issue by M1CK431** [strapi/strapi#12180] opened 2022-01-11 22:51 UTC
### Describe the bug

Because of `id` and `attributes` split in API schema the GraphQL cache can't be updated and raise a warning in the browser console (among obvious cache handling issue).

The warning message from the console is:
```
invariant.ts?6cf4:42 Cache data may be lost when replacing the attributes field of a ExampleEntity object.

To address this problem (which is not a bug in Apollo Client), either ensure all objects of type Example have an ID or a custom merge function, or define a custom merge function for the ExampleEntity.attributes field, so InMemoryCache can safely merge these objects:

  existing: {"__typename":"Example","createdAt":"2021-12-25T23:43:56.648Z","firstName":"John","lastName":"Do","message":"I'm asleep","status":"NEW","dueDate":null,"referer":"https://example.com","contactDetails":[],"user":{"__typename":"UsersPermissionsUserEntityResponse","data":null}}
  incoming: {"__typename":"Example","dueDate":null,"firstName":"John","lastName":"Do","message":"I'm asleep","referer":"https://example.com","ipAddress":"12.34.56.78","createdAt":"2021-12-25T23:43:56.648Z","updatedAt":"2021-12-25T23:43:56.648Z","contactDetails":[],"communications":[]}

For more information about these options, please refer to the documentation:

  * Ensuring entity objects have IDs: https://go.apollo.dev/c/generating-unique-identifiers
  * Defining custom merge functions: https://go.apollo.dev/c/merging-non-normalized-objects
```

This is because the GraphQL schema is the following:
- `example` query:
```js
example(id: ID): ExampleEntityResponse
type ExampleEntityResponse {
  data: ExampleEntity
}
id: ID
```

and

```js
data: ExampleEntity
type ExampleEntity {
  id: ID
  attributes: Example
}
```

### Steps to reproduce the behavior

1. Using GraphQL API, request the same asset in a query and in the result of a mutation (for example)
2. See warning message in the browser console

### Expected behavior

The `id` and `attributes` split in the GraphQL API schema is incomprehensible for me. I can't understand why there are not in the same object (like `Apollo Client` is obviously expecting to find it). In addition, I also can't understand why we need to wrap everything in a `data` object while fetching a single asset. I guess there is strong reasons for such things, but I can't actually believe them :exploding_head: 

IMHO, the expected schema should be like this:
```js
example(id: ID!): Example
type Example {
  id: ID!
  createdAt: DateTime!
  updatedAt: DateTime!
  // other fields...
}
```

### Screenshots

N/A

### Code snippets

Regardless the GraphQL cache issue, I'm currently forced to write such code in every query/mutation (and I really hate it :angry:):
```js
function Example({ id, attributes }) {
  Object.assign(this, { id, ...attributes });
}

this.$apollo
  .query({ query: examplesQuery, variables: { ids: this.ids } })
  .then(({ data: { examples: { data } } }) => {
    const examples = data.map(e => new Example(e));
    // finally some useful code
  }
```

Strapi v3 use by far more "dev friendly" in this respect (no useless `data` wrapper for single asset, no incomprehensible `id` and `attributes` split).

### System

- Node.js version: v16.13.1
- NPM version: v8.1.2
- Strapi version: v4.0.5
- Database: MariaDB
- Operating system: Archlinux

**Comment by M1CK431** [comment] 2022-01-19 22:34
Up! :upside_down_face:

**Comment by derrickmehaffy** [comment] 2022-01-20 17:38
Can you please share this information here: https://forum.strapi.io/t/discussion-regarding-the-complex-response-structure-for-rest-graphql-developer-experience/13400

I'm going to close this as it's not "technically" a bug, I know the new structure is a bit frustrating and some caching issues (especially client-side) do exist with the new structure especially with apollo-client but we are trying to centralize feedback.

Thank you

**Closed by derrickmehaffy** 2022-01-20 17:38 UTC

**Comment by M1CK431** [comment] 2022-01-20 20:49
Hi @derrickmehaffy ,

Thanks for your reply and pointed me out the related forum discussion. I will copy my bug report as requested.

However, this issue is mainly about caching issue and as you stand yourself **there is a knowned caching issue**, regardless technical choices which leads to that issue. In addition, a lot of dev/users don't use strapi forum but check for existing issues and report issue on github. That's why I think that issue should stay open until a fix is provided.

**Comment by derrickmehaffy** [comment] 2022-01-20 22:35
> Hi @derrickmehaffy ,
> 
> Thanks for your reply and pointed me out the related forum discussion. I will copy my bug report as requested.
> 
> However, this issue is mainly about caching issue and as you stand yourself **there is a knowned caching issue**, regardless technical choices which leads to that issue. In addition, a lot of dev/users don't use strapi forum but check for existing (open) issues and report issue on github. That's why I think that issue should stay open until a fix is provided.

While normally I would agree with you, this isn't something that is "easily fixed" and it's a problem that mainly happens upstream on the client side. Given I will say the issue is caused by our structure it just relates to that discussion so for now I'll leave it as closed with the hope that our engineering team can raise the discussion to an actual bug report.

**Comment by M1CK431** [comment] 2022-01-20 22:55
> > Hi @derrickmehaffy ,
> > Thanks for your reply and pointed me out the related forum discussion. I will copy my bug report as requested.
> > However, this issue is mainly about caching issue and as you stand yourself **there is a knowned caching issue**, regardless technical choices which leads to that issue. In addition, a lot of dev/users don't use strapi forum but check for existing (open) issues and report issue on github. That's why I think that issue should stay open until a fix is provided.
> 
> While normally I would agree with you, this isn't something that is "easily fixed" and it's a problem that mainly happens upstream on the client side. Given I will say the issue is caused by our structure it just relates to that discussion so for now I'll leave it as closed with the hope that our engineering team can raise the discussion to an actual bug report.

Sorry, I don't understand the arg "this isn't something that is "easily fixed"". Ok it's not easy to fix... and then? It's still an issue!
And about "it's a problem that mainly happens upstream on the client side", well, not a surprise honestly, since strapi is an API, the biggest issues happens when a client can't use it as expected, right? :hand_over_mouth: 

But after all, your repo, your rules :man_shrugging: 
I hope you will not have too many new other issues about that to close in the futur :crossed_fingers: 

Again, thanks to provide the discussion in the forum. Now I know that this issue will not be fixed soon and I can take decisions accordingly :kissing_heart:

**Comment by JWesorick** [comment] 2022-06-24 09:21
Does anyone have an example of how they fixed the Apollo Cache issue?

**Comment by petersino** [comment] 2022-10-25 01:46
> Contributor

Hi, did you find any solution?

**Comment by M1CK431** [comment] 2023-02-04 20:21
> in case anyone land on this page, you can merge attributes by indicating it in apollo cache like this :
> 
> ```
>   typePolicies: {
>     ExampleEntity: {
>       fields: {
>         attributes: {
>           merge: true,
>         }
>       }
>     }
>   }
> });
> ```

I'm even doing massively for years:
```js
new ApolloClient({
  link: "<insert your link here>",
  cache: new InMemoryCache({
    typePolicies: [
      "UsersPermissionsUser",
      "Asset1",
      "Asset2",
      "AssetX",
    ].reduce((acc, type) => ({ ...acc, [type]: { merge: true } }), {})
  })
});
```

This is just a workaround. The real issue come from Strapi with it's abnormal schema.

IIRC it was even one of the reasons why Strapi team keep alive v3 until now.
However v3 is reaching OEL very soon and the problematic GQL schema is still there... 😢

**Comment by jbcrestot** [comment] 2023-02-19 14:09
Oh, I agree entirely with you ; attributes object without id is annoying

**Comment by M1CK431** [comment] 2024-03-20 22:59
> > > in case anyone land on this page, you can merge attributes by indicating it in apollo cache like this :
> > > ```
> > >   typePolicies: {
> > >     ExampleEntity: {
> > >       fields: {
> > >         attributes: {
> > >           merge: true,
> > >         }
> > >       }
> > >     }
> > >   }
> > > });
> > > ```
> > 
> > 
> > I'm even doing this massively for years:
> > ```js
> > new ApolloClient({
> >   link: "<insert your link here>",
> >   cache: new InMemoryCache({
> >     typePolicies: [
> >       "UsersPermissionsUser",
> >       "Asset1",
> >       "Asset2",
> >       "AssetX",
> >     ].reduce((acc, type) => ({ ...acc, [type]: { merge: true } }), {})
> >   })
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is just a workaround. The real issue come from Strapi with it's abnormal schema.
> > IIRC it was even one of the reasons why Strapi team keep alive v3 until now. However v3 is reaching EOL very soon and the problematic GQL schema is still there... 😢
> 
> @M1CK431 Does this fix the caching issue? Is there any downside?
> 
> In my case I have types such as ArticleEntity, CategoryEntity, LocationEntity, etc. Should I include all of these?
> 
> > ```js
> > new ApolloClient({
> >   link: "<insert your link here>",
> >   cache: new InMemoryCache({
> >     typePolicies: [
> >       "ArticleEntity",
> >       "CategoryEntity",
> >       "LocationEntity",
> >     ].reduce((acc, type) => ({ ...acc, [type]: { merge: true } }), {})
> >   })
> > });
> > ```

Yes, it workaround the cache issue, no downside.
The only project where I'm still using Strapi (for historical reasons) is working with that for years until now.

TBH, I have even written a special Vue.js "plugin" called `strapollo` (closed source) which wrap the regular Apollo client and merge `id` and `attributes` in the response globally. However, I still have to use the horrible GQL schema in queries and mutations because AFAIK there is no simple way to workaround that.

However, **my advise is to not use Strapi if you plan to use the GraphQL API**. Creating your own API with NodeJs/Koa is a far better alternative, especially if your main need is a regular CRUD around some assets, and you can even add subscriptions support.

As an example, I urge you to take a look on [my recent open source project](https://github.com/M1CK431/url-checker) where I'm doing exactly that. Especially, [this file](https://github.com/M1CK431/url-checker/blob/develop/api/src/Model.js) could be very helpful for you because it's a kind of "generator": you call it with an object describing your model and almost everything is generated for you (GQL type, DB model, filters/sort, etc...). See [usage example here](https://github.com/M1CK431/url-checker/blob/2c9e65d8ec6d9c1d34cdbb135f6b9ffb780ab392/api/src/checkResults.js#L14).

In addition, you may be also interested by [Nexus/Prisma](https://graphql-nexus.github.io/nexus-prisma).

Hope it helps 🤞🏼

**Comment by ulysse-lacour** [comment] 2024-06-05 07:55
Would anyone help implement those solutions in a strapi app ?
`new ApolloClient({
  link: "<insert your link here>",
  cache: new InMemoryCache({
    typePolicies: [
      "ArticleEntity",
      "CategoryEntity",
      "LocationEntity",
    ].reduce((acc, type) => ({ ...acc, [type]: { merge: true } }), {})
  })
});`

`  typePolicies: {
    ExampleEntity: {
      fields: {
        attributes: {
          merge: true,
        }
      }
    }
  }
});`

I can't find where I could do this in the plugin config, or is it from frontend that we should implement it ? (I'm using Nuxt 3)
