### ISSUE TITLE
UID Field Selection Crashes

### ISSUE THREAD

**Issue by pzehle** [strapi/strapi#5568] opened 2020-03-21 20:43 UTC
**Describe the bug**
When creating a new content type, and selecting UID as a field, application crashes with the error `TypeError: undefined is not an object (evaluating 'option.value')`.

**Steps to reproduce the behavior**
1. Create a new content type.
2. Click on UID field.
3. Error appearing.

**Expected behavior**
Be able to generate a UID field.

**Screenshots**
<img width="2032" alt="Bildschirmfoto 2020-03-21 um 21 40 47" src="https://user-images.githubusercontent.com/27866874/77236196-aedd8c00-6bbc-11ea-8e34-dfa4a1ba0972.png">
<img width="2032" alt="Bildschirmfoto 2020-03-21 um 21 40 56" src="https://user-images.githubusercontent.com/27866874/77236199-b3a24000-6bbc-11ea-8b7a-5ba23f01ba09.png">

**System**
- Node.js version: 12.6.0
- NPM version: 6.14.2
- Strapi version: 3.0.0-beta.19.3
- Database: Postgres
- Operating system: Mac OS

**Comment by frilansutvecklaren** [comment] 2020-03-22 01:01
Have the same problem after installing a fresh copy of latest beta (19.3). Didn't have this problem before with the 19.3.

**Comment by derrickmehaffy** [comment] 2020-03-22 08:14
I can confirm this issue on a fresh quickstart beta.19.3, happens as soon as I click on the UID field while creating a collection type.

![image](https://user-images.githubusercontent.com/8593673/77245256-7ba9f580-6bda-11ea-831b-3eb7704e36dd.png)

Tagging @soupette @virginieky

**Comment by frilansutvecklaren** [comment] 2020-03-22 17:18
So why does it crash when selecting UID field?

**Comment by derrickmehaffy** [comment] 2020-03-23 08:44
@frilansutvecklaren the Strapi team are currently looking into this, it's most likely an upstream package issue.

**Comment by alexandrebodin** [comment] 2020-03-23 14:54
Hi we couldn't reproduce this issue. It might have come from one of the dependencies. Are you still having the issue @pzehle  ?

**Comment by pzehle** [comment] 2020-03-23 15:02
@alexandrebodin thanks. Yes, issue is still there, no matter how many fresh installs I perform, issue persists. I think I am not the only one having this issue.

**Comment by HichamELBSI** [comment] 2020-03-23 16:13
Hi @pzehle, can you clear the npm/yarn cache and retry, please.

**Comment by soupette** [comment] 2020-03-23 16:40
@pzehle I am having a really hard time reproducing it can you give a link to a repo so I can check the bug?

**Comment by derrickmehaffy** [comment] 2020-03-23 16:41
I also can't seem to reproduce it again.

**Comment by pzehle** [comment] 2020-03-23 16:44
Clearing cache solves the problem. Thank you!

**Comment by derrickmehaffy** [comment] 2020-03-23 16:47
I'm guessing this is an issue with some cached upstream package that was fixed over the weekend.

@soupette @alexandrebodin you guys good with closing this out for now? (I can't get it to reproduce again)

**Comment by derrickmehaffy** [comment] 2020-03-25 12:47
For now marking this as closed, if I or anyone else sees this issue come up we can reopen.

**Closed by derrickmehaffy** 2020-03-25 12:47 UTC
Labels: priority: high, status: confirmed, type: bug

**Comment by soupette** [comment] 2020-03-26 07:27
Thanks @derrickmehaffy if anyone comes up with the issue please provide a link to repo so we can try to debug.
