### ISSUE TITLE
Many To Many On User Creates Infinite Login

### ISSUE THREAD

**Issue by fostergn** [strapi/strapi#2959] opened 2019-03-10 04:03 UTC
**Information**
- **Node.js version**: v10.13.0
- **NPM version**: 6.5.0
- **Strapi version**: 3.0.0-alpha.24.1
- **Database**: MySQL
- **Operating system**: MacOS 

**What is the current behavior?**
**Steps to reproduce the problem**
- Create a new content type "Event". Create a many-to-many relation on "User" to "Event". Page refreshes and get sent to `http://localhost:1337/admin/plugins/users-permissions/auth/login`. On correct login, a flash of the dashboard and then refresh and redirected to `http://localhost:1337/admin/plugins/users-permissions/auth/login`

**What is the expected behavior?**
Not get logged out, or be able to login.

**Suggested solutions**
n/a

**Comment by ralphMevision** [comment] 2019-03-11 08:05
Have the same issue

**Comment by lauriejim** [comment] 2019-03-12 14:59
Hello!

I just created a new app.

1. Register a new admin
2. Create a content type `event`
3. Add `string` field named `name`
4. Add relation `many-to-many` with `User`
5. Save to create the content type

And all works fine. May be I miss something ?

**Comment by fakedob** [comment] 2019-04-19 22:37
If you repeat all the above steps and just restart the app and then refresh the page, you will experience this behaviour. It is not reproducable if you have more than one user in the db.
What you get is multiple 403 response codes to the auth endpoint and finaly it logs you out

**Comment by lauriejim** [comment] 2019-04-22 15:39
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.

**Comment by Emadeddin-eibo** [comment] 2019-04-28 11:59
Same issue:

1. Create a new type (Product)
2. Add some Fields
3. Go to User Type
4. Add new (Relation) to Product as (Many to Many)
5. Server restarted
6. Go to /admin, any login attempt will login successfully and then redirect to login page with the url: (admin/plugins/users-permissions/auth/login)

*working on localhost env.

**Comment by max-ivaneychyk** [comment] 2019-05-17 13:17
> Same issue:
> 
> 1. Create a new type (Product)
> 2. Add some Fields
> 3. Go to User Type
> 4. Add new (Relation) to Product as (Many to Many)
> 5. Server restarted
> 6. Go to /admin, any login attempt will login successfully and then redirect to login page with the url: (admin/plugins/users-permissions/auth/login)
> 
> *working on localhost env.



> I am closing this issue because we don’t have any updated/needed information regarding it.
> Will reopen it if activity come back.

Hi. Please check code in packages/strapi-hook-bookshelf/lib/index.js
Now always creates one association table for each entity.
On screenshot, I fix it.

![Screenshot from 2019-05-17 16-04-13](https://user-images.githubusercontent.com/16804848/57930446-acd0df80-78be-11e9-8ce9-0447627d0245.png)

**Comment by lauriejim** [comment] 2019-08-14 16:17
This issue is fixed in last beta version of strapi (at least beta.15 version)
I close this issue.

**Closed by lauriejim** 2019-08-14 16:17 UTC
Labels: priority: high, status: confirmed, type: bug 🐛
