### ISSUE TITLE
Delete one relation will delete two fields

### ISSUE THREAD

**Issue by yummyelin** [strapi/strapi#1269] opened 2018-05-24 21:23 UTC
**Informations**
- **Node.js version**: 9.10.1
- **npm version**:5.6.0
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: mongodb 3.6.4
- **Operating system**: macOS

**What is the current behavior?**
Deleting one relation in a content type, two fields in the content type will be deleted. 
For example, I have one relation in INVESTMENTS called PRODUCTID which is oneToOne related to ID in PRODUCT. 
![screen shot 2018-05-24 at 2 14 53 pm](https://user-images.githubusercontent.com/3782817/40514192-25a7a8f2-5f5d-11e8-9d7a-25c65c0b42ce.png)
While I delete PRODUCTID and confirmed, two fields deleted, including PRODUCTID and INTEREST, the last field in PRODUCT
![screen shot 2018-05-24 at 2 15 01 pm](https://user-images.githubusercontent.com/3782817/40514230-4afa1fd6-5f5d-11e8-9b72-1db9dc7f4fc7.png)

**Steps to reproduce the problem**
1. Create a content type C.
2. Add a few fields to C.
3. Add one relation, oneToOne related to a field in content type A.
4. Add another relation, oneToOne related to a field in content type B.
5. Delete one relation.

**What is the expected behavior?**
Only one relation is deleted.

**Suggested solutions**

**Comment by soupette** [comment] 2018-05-28 13:53
Hi @yummyelin I tried to reproduce your issue but it working as expected on my side

**Comment by yummyelin** [comment] 2018-05-30 19:19
@soupette I pushed an example project which reproduced the issue, please clone from [here](https://github.com/yummyelin/strapi-hello-world), checkout commit 2c7c67d. 

Delete UID in PROFILE will cause this issue.

**Comment by derrickmehaffy** [comment] 2018-05-30 21:00
@yummyelin just something I noticed your package.json in that example is listing `"strapi": "3.0.0-alpha.12"` and not  `"strapi": "3.0.0-alpha.12.2"`

Can you try and generate a new clean project and add your models to test with a clean 12.2 project?

**Comment by lauriejim** [comment] 2018-06-05 20:47
It's have been fixed in last version of Strapi

**Comment by yummyelin** [comment] 2018-06-05 21:39
@derrickmehaffy I am now using `"strapi": "3.0.0-alpha.12.2"`, and create a new clean project, [here](https://github.com/yummyelin/strapi-test), the issue is still there.
If you delete UID in PROFILE content type, you can see this issue.

**Comment by soupette** [comment] 2018-06-06 08:46
@yummyelin the error is happening because you have the same field name for both `Profile` & `User`.

@lauriejim is it allowed to have such condition?

**Closed** 2018-06-11 15:59 UTC
Labels: priority: medium, status: can't reproduce, type: bug 🐛
