### ISSUE TITLE
Duplicated records / entries if you press buttons quickly

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#8830] opened 2020-12-08 12:51 UTC
### Describe the bug

When you create a new content and press in "+ Add New {content}" if you press twice or more times quickly, you can create duplicate records

### Expected behavior

Multiple Save to be Controlled Or Progressing symbol to be shown to avoid the user from clicking twice

### Code snippets
https://github.com/strapi/strapi/issues/8827
soupette commented ---
can you upgrade your app to the latest version which is 3.3.4. The bug has been fixed.
I am closing this issue as we don't maintain the alpha version anymore.

Can you please let us know how the issue is fixed with Bug Issue no. So that will try to fix the same in 3.0.2. Kindly share the bug number and resolution

### System

Informations

Node.js version: Node v10.14.2
NPM version: npm v6.4.1
Strapi version: Strapi 3.0.2
Database: Mongodb 4.0.4
Operating system: Ubuntu 18.04
(Optional) Link to your Project::

**Comment by derrickmehaffy** [comment] 2020-12-08 14:10
Tested on a fresh v3.3.4 project and could not reproduce. Please confirm on the **latest release**, v3.0.2 is 6 months old.

**Comment by derrickmehaffy** [comment] 2021-04-15 18:14
Closing as no new information

**Closed by derrickmehaffy** 2021-04-15 18:14 UTC
Labels: status: can't reproduce
