### ISSUE TITLE
Users permission roles is not even viewable in production environment

### ISSUE THREAD

**Issue by webcoderkz** [strapi/strapi#3533] opened 2019-06-26 17:26 UTC
I'm using Strapi v3.0.0-beta.6 with PostgreSQL 10.8 as DB, installed new instance locally using strapi CLI command, then decided to deploy this CMS instance on production VPS. So i launched it on production using following commands:

`NODE_ENV=production npm run build` - to build an admin panel frontend.

`NODE_ENV=production npm run start` - to start whole app.

Everything started as expected, i went in to admin panel, using credentials for the admin user i've created on the first run locally (i imported dev database in to a production), then went to edit user permissions "url/admin/plugins/users-permissions/roles/edit/1", but load never finished, i opened "network" tab in a google chrome and noticed a request "url//users-permissions/roles/1?lang=en-US" that never finishes loading. Thus, i cannot even view edit form of permissions.

**Expected behavior**
I expect it to load and i would able to edit permissions on production.

**Screenshots**
![image](https://user-images.githubusercontent.com/5739191/60201276-b0666780-9869-11e9-897a-c0907521844d.png)

**System**
- Node.js version: 10 LTS
- NPM version: Shipped with node 10 LTS
- Strapi version: 3.0.0-beta6
- Database: PostgreSQL
- Operating system: MacOS / Ubuntu 18.04

**Comment by derrickmehaffy** [comment] 2019-07-08 05:09
@webcoderkz Are you using a proxy like nginx or apache? If so and you are using SSL this is likely the cause:

https://github.com/strapi/strapi/issues/2424

**Comment by webcoderkz** [comment] 2019-07-08 05:16
@derrickmehaffy my production VPS has no external network interface (because it's production), that's the cause? But why it does need an external connection for local roles? Curious :)

**Comment by derrickmehaffy** [comment] 2019-07-08 05:19
It's a bug related to the strapi marketplace, can you update to beta.9 and test again. They were supposed to fix that.... lol

**Comment by lauriejim** [comment] 2019-07-08 09:50
Hello @webcoderkz !
Can you please share your browser console.
I would like to know if there is error.

I tested to reproduce your issue, but it works well on my side with `beta.8`

**Comment by webcoderkz** [comment] 2019-07-08 10:02
@lauriejim console shows no error, it just sends request (in a network tab) as i described then time-outing. Probably, as @derrickmehaffy told before, i'm gonna try with beta.9 when i can get home.

And locally, even beta.6 works with roles on my local machine, it's related to external network and ssl i think.

**Comment by derrickmehaffy** [comment] 2019-07-08 10:06
I believe that it is either related to SSL issue coming from CTM or as @webcoderkz stated it might be related to the lack of external network (assuming the user has this deployment locked behind a firewall, which is excellent) In which case it's related to the fact it can't contact https://strapi.io/marketplace

The latter of which I've seen a few issues with that I think a number of fixes has tried to address. :thinking:

**Comment by webcoderkz** [comment] 2019-07-08 10:10
@lauriejim could you try to edit a role as i described without internet access at all?

**Comment by derrickmehaffy** [comment] 2019-07-08 10:12
Likewise you can set the route to the strapi.io domain manually to something like `127.0.0.1` and test that way as well. Which I am working on testing right now.

**Comment by derrickmehaffy** [comment] 2019-07-08 10:18
Just tested on beta.9 using my route modification and could access them just fine (not behind a proxy) @webcoderkz When you get a moment if you need me to take a look at your nginx config you can PM me on the slack.

**Comment by webcoderkz** [comment] 2019-07-08 10:20
@derrickmehaffy and without route modification - would it work if you just disable external network??

**Comment by derrickmehaffy** [comment] 2019-07-08 10:21
Aye yeah I also quickly checked by removing my hard line and going offline and it worked as well. So I'm guessing it's related to the missing security header that nginx isn't sending. For reference: 

https://github.com/strapi/strapi/issues/2424#issuecomment-467851988

That is the fix I use as my Strapi instances sit behind Nginx as well.

**Comment by webcoderkz** [comment] 2019-07-08 10:53
Here's my config:

```
    location ~ ^/cms(.*)$ {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://172.28.5.154:8290;
        rewrite ^/cms/(.*) /$1 break;
        proxy_redirect default;
    }
```

The only difference with yours config is:

```
proxy_set_header X-Real-IP $remote_addr;
```

Is that important?

**Comment by derrickmehaffy** [comment] 2019-07-08 10:56
This line here:
```
proxy_set_header X-Forwarded-Host

# You have 
proxy_set_header X-Forwarded-Host $host;

# Strapi needs
proxy_set_header X-Forwarded-Host "strapi";
```

In my case I let Nginx choose based on the request. I threw this at the top of the config:
```
map $http_x_forwarded_host $custom_forwarded_host {
  default "$server_name";
  strapi "strapi";
}
```

And reference it in my proxy config
```
  location / {
    proxy_pass http://localhost:1337;
    proxy_redirect off;
    proxy_connect_timeout 2;
    proxy_read_timeout 86400;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $custom_forwarded_host;   <-------- HERE
  }
```

**Comment by webcoderkz** [comment] 2019-07-10 04:23
@derrickmehaffy it has no effect for me, i guess the problem is somewhere else.

**Comment by derrickmehaffy** [comment] 2019-07-19 09:27
@webcoderkz that error isn't related to this.

**Comment by derrickmehaffy** [comment] 2019-07-19 09:28
@lauriejim you won't be able to reproduce if you are only working on localhost, in essence this is related to https://github.com/strapi/strapi/issues/2424

I'm going to close this issue and reopen 2424 as it is still a problem that needs to be addressed

**Closed by derrickmehaffy** 2019-07-19 09:28 UTC
Labels: type: help wanted 🤷‍♂️
