### ISSUE TITLE
Calling GET User API with an unknown id raises an exception

### ISSUE THREAD

**Issue by dsciamma** [strapi/strapi#5132] opened 2020-01-30 08:10 UTC
**Describe the bug**
When calling findOne controller for user model from user-permission plugin with an unknown id, it raises a NPE.
```
TypeError: Cannot read property 'isBoom' of null
      at C:\Users\DavidSciamma\Documents\dev\pratix\practices-back\node_modules\strapi\lib\middlewares\boom\index.js:98:41
      at async C:\Users\DavidSciamma\Documents\dev\pratix\practices-back\node_modules\strapi\lib\middlewares\responses\index.js:17:9
      at async cors (C:\Users\DavidSciamma\Documents\dev\pratix\practices-back\node_modules\@koa\cors\index.js:85:16)
      at async C:\Users\DavidSciamma\Documents\dev\pratix\practices-back\node_modules\strapi\lib\middlewares\logger\index.js:43:11
      at async C:\Users\DavidSciamma\Documents\dev\pratix\practices-back\node_modules\strapi\lib\Strapi.js:303:9
```

**Steps to reproduce the behavior**
1. Call get user GraphQL API with an unknown id
2. Server return an error 500 and an exception is traced in the log

**Expected behavior**
A 204 or 404 HTTP code should be returned

**System**
- Node.js version: 12.3.1
- NPM version: 6.9.0
- Strapi version: 3.0.0-beta.18.4
- Database: Postgres
- Operating system: Windows

**Additional context**
It seems to be a race condition in Boom middleware. ctx.status is changing the value of ctx.body for certain codes.
Switching the 2 lines is solving the problem
https://github.com/strapi/strapi/blob/817618417e232863d61fe0cd1fc00efd5fcb054a/packages/strapi/lib/middlewares/boom/index.js#L98

**Comment by lauriejim** [comment] 2020-02-05 11:04
Hello! Can you please send me the GraphQL request you did.
I'm not able to reproduce your issue with information of your issue.
Thank you.

**Comment by dsciamma** [comment] 2020-02-06 21:14
Here is a failing GraphQL
query User($id: ID!) {
  user(id: $id) {
    id
    email
  }
}

With an unknown ID like 999999

**Comment by lauriejim** [comment] 2020-02-07 09:52
Hello! Thank you for sharing the query.
I just tried and it works well on my side with the last version of Strapi (beta.18.7)
Here is what I did - https://www.loom.com/share/94c0144918554eeebbc8a17793a4fec0
Let me know if I missed something.

**Comment by dsciamma** [comment] 2020-02-14 16:06
Indeed, the behavior is different on my side (Strapi beta.18.4).
I don't understand why but ok, you could probably close this issue as invalid.

**Comment by derrickmehaffy** [comment] 2020-02-18 11:15
Before I close this @dsciamma `Strapi version: 3.0.0-beta.18.4` can you test on the latest version please?

**Closed** 2020-06-09 10:58 UTC
Labels: type: help wanted
