### ISSUE TITLE
`useContentManagerInitData` must be used within `StrapiApp`

### ISSUE THREAD

**Issue by ouizz** [strapi/strapi#22199] opened 2024-11-18 22:19 UTC
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Code snippets

If applicable, add code samples to help explain your problem.

**Comment by ouizz** [comment] 2024-11-18 22:19
Something went wrong
It seems like there is a bug in your instance, but we've got you covered. Please notify your technical team so they can investigate the source of the problem and report the issue to us by opening a bug report on 
[Strapi's GitHub](https://github.com/strapi/strapi/issues/new?assignees=&labels=&projects=&template=BUG_REPORT.md)
.

**Comment by innerdvations** [comment] 2024-11-19 09:23
Duplicate of https://github.com/strapi/strapi/issues/21151

**Closed** 2024-11-19 09:25 UTC
Labels: status: duplicate
