### ISSUE TITLE
Plural version of words is not correct for non-english languages

### ISSUE THREAD

**Issue by DavidSanek** [strapi/strapi#6332] opened 2020-05-23 22:01 UTC
**Describe the bug**
At Collection types transfering a singular verb into its plural version is not correct for non-english languages.

**Steps to reproduce the behavior**

1. Go to admin dashboard.
2. Create a new Collection type with a singular word in non-english language (eg _Nabídka_) as a name.
4. The name does not get transfered correctly. In Admin dashboard we can see _Nabídkas_, which is not correct for word's language.

**Expected behavior**
Do not automatically transfer words into their plural version. If plural version is needed, I suggest adding an input for plural word into Advanced settings tab when creating a new Collection type.

**Comment by derrickmehaffy** [comment] 2020-05-24 05:22
Closing as duplicate: https://github.com/strapi/strapi/issues?q=is%3Aissue+is%3Aopen+plural

**Closed by derrickmehaffy** 2020-05-24 05:22 UTC

**Comment by noname202** [comment] 2020-05-24 19:39
I don‘t agree that this issue is a duplicate of #1198. While both are indeed very similar, there are only few exceptions to the „s“ rule in English, while the rule doesn't work for Most words in many other languages. I believe it would be best to allow setting the display name (and it‘s plural form) independent of the internal collection name.

**Comment by jjarcik** [comment] 2020-06-15 10:55
You can modify _LeftMenuLinkSection_ file and custom rendering the label

- Open file api/Nabidka/nabidka.settings.json (nabidka is your collection name)
- Add key displayName to info part of config
`"info": { "name": "Nabidka", "displayName": "Nabídky" }`
- create a file ```admin/src/components/LeftMenuLinkSection/index.js```
- copy into it the contents of file
```node_modules/strapi-admin/admin/src/components/LeftMenuLinkSection/index.js```
- Change this
```
<LeftMenuLink  label={link.label} />
```
to this
``` 
<LeftMenuLink
     label={link.schema && link.schema.info.displayName ? link.schema.info.displayName : link.label}
    />
```

- yarn strapi build

**Comment by tomastuser** [comment] 2020-08-06 10:00
Thanks  jjarcik for the idea. Because of a Strapi update it didn't work for me, but eventually I found a solution. Instead of modifing LeftMenuLinkSection file, i had to modify the generateModelsLinks.js file. This is what worked for me:

- Open file api/Nabidka/nabidka.settings.json (nabidka is your collection name)

- Add key displayName to info part of config
`"info": { "name": "Nabidka", "displayName": "Nabídky" }`

- create a file `admin/src/containers/LeftMenu/utils/generateModelsLinks.js`

- copy into it the contents of file
    `node_modules/strapi-admin/admin/src/containers/LeftMenu/utils/generateModelsLinks.js`
- Change this

`label: link.label,`

to this

```
label:
          link.schema && link.schema.info.displayName
            ? link.schema.info.displayName
            : link.label,
```
- npm run build
