### ISSUE TITLE
Yarn (v3) build errors related to ts-zen dependency

### ISSUE THREAD

**Issue by dwightgunning** [strapi/strapi#18319] opened 2023-10-05 13:30 UTC
## Bug report

I'm experiencing issues while attempting to build and deploy a vanilla Strapi "quickstart" project to [render.com](https://render.com/).

Building (`yarn build`)  and running (`yarn develop`) locally on a MBP works just fine. I suspect something bespoke with render.com is contributing to the issue, but given the similarity to another issue with the ts-zen dependency (https://github.com/strapi/strapi/issues/18299), I hope this can be looked into (and may be helpful to others too).

### Required System information

- Node.js version: **20.6.0**
- Yarn version: **3.6.4**
- Strapi version: **4.14.3**
- Database: **SQLite**
- Operating system: **Debian GNU/Linux 10 (buster)**
- Is your project Javascript or Typescript: **TypeScript**

### Describe the bug

The `yarn build` fails at the "Fetch step":

> Oct 5 02:53:25 PM  ➤ YN0018: │ ts-zen@https://github.com/strapi/ts-zen.git#commit=66e02232f5997674cc7032ea3ee59d9864863732: The remote archive doesn't match the expected checksum.

The problem seems to stem from the build process falling back to use Yarn classic to pack the ts-zen dependency.

> Oct 5 02:53:13 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT Packing ts-zen@https://github.com/strapi/ts-zen.git#commit=66e02232f5997674cc7032ea3ee59d9864863732 from sources
Oct 5 02:53:13 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile

### Steps to reproduce the behavior

1. Follow the quickstart guide and setup the project with `yarn create strapi-app strapi-demo --quickstart --typescript --no-run`.
2. Declare node and yarn versions via `.nvm`, `.yarnrc` and `package.json`
3. Initiate a deployment with the commands `yarn install && yarn build`

### Expected behavior

`yarn build` should complete.

### Code snippets

package.json
```
{
  "name": "strapi-demo",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "dependencies": {
    "@strapi/plugin-i18n": "4.14.3",
    "@strapi/plugin-users-permissions": "4.14.3",
    "@strapi/strapi": "4.14.3",
    "better-sqlite3": "8.6.0"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "dcce881f-c6fe-4469-9fc3-823d03c237db"
  },
  "engines": {
    "node": "20.6.0",
    "yarn": "3.6.4"
  },
  "packageManager": "yarn@3.6.4",
  "license": "MIT"
}

```

.yarnrc.yml
```
defaultSemverRangePrefix: ""

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
```

.nvmrc
```
v20.6.0
```

### Additional context

Full build log:

```
Oct 5 02:51:14 PM  ==> Cloning from https://github.com/interviewingio/strapi...
Oct 5 02:51:15 PM  ==> Checking out commit c2e2b2b2c8ec02ce13da914687038ad6af38a65a in branch staging
Oct 5 02:51:18 PM  ==> Downloading cache...
Oct 5 02:51:25 PM  ==> Still downloading cache...
Oct 5 02:51:31 PM  ==> Using Node version 20.6.0 via /opt/render/project/src/.nvmrc
Oct 5 02:51:31 PM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Oct 5 02:51:33 PM  ==> Running build command 'node --version && yarn --version && yarn install && yarn build'...
Oct 5 02:51:33 PM  v20.6.0
Oct 5 02:51:34 PM  3.6.4
Oct 5 02:51:35 PM  ➤ YN0000: ┌ Resolution step
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/design-system@npm:1.11.0 [4844d] doesn't provide @codemirror/view (pef021), requested by @uiw/react-codemirror
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/design-system@npm:1.11.0 [facde] doesn't provide @codemirror/view (p6a6e9), requested by @uiw/react-codemirror
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/strapi@npm:4.14.3 doesn't provide react (p6c029), requested by @strapi/plugin-content-type-builder
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/strapi@npm:4.14.3 doesn't provide react (pa256f), requested by @strapi/plugin-email
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/strapi@npm:4.14.3 doesn't provide react (p4481d), requested by @strapi/plugin-upload
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/strapi@npm:4.14.3 doesn't provide react-dom (pa9a63), requested by @strapi/plugin-content-type-builder
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/strapi@npm:4.14.3 doesn't provide react-dom (pfce64), requested by @strapi/plugin-email
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/strapi@npm:4.14.3 doesn't provide react-dom (p47585), requested by @strapi/plugin-upload
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/strapi@npm:4.14.3 doesn't provide react-router-dom (p2a5e3), requested by @strapi/plugin-content-type-builder
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/strapi@npm:4.14.3 doesn't provide react-router-dom (p41421), requested by @strapi/plugin-email
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/strapi@npm:4.14.3 doesn't provide react-router-dom (pe7dd0), requested by @strapi/plugin-upload
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/strapi@npm:4.14.3 doesn't provide styled-components (p41e85), requested by @strapi/plugin-content-type-builder
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/strapi@npm:4.14.3 doesn't provide styled-components (p5c77c), requested by @strapi/plugin-email
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/strapi@npm:4.14.3 doesn't provide styled-components (p1dba9), requested by @strapi/plugin-upload
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/types@npm:4.14.3 doesn't provide jest (pf18ff), requested by ts-zen
Oct 5 02:51:36 PM  ➤ YN0002: │ @strapi/types@npm:4.14.3 doesn't provide typescript (p9d62b), requested by ts-zen
Oct 5 02:51:36 PM  ➤ YN0002: │ babel-plugin-styled-components@npm:2.1.4 [5d586] doesn't provide @babel/core (pae47f), requested by @babel/plugin-syntax-jsx
Oct 5 02:51:36 PM  ➤ YN0002: │ strapi-demo@workspace:. doesn't provide react (p71310), requested by @strapi/plugin-i18n
Oct 5 02:51:36 PM  ➤ YN0002: │ strapi-demo@workspace:. doesn't provide react (paa092), requested by @strapi/plugin-users-permissions
Oct 5 02:51:36 PM  ➤ YN0002: │ strapi-demo@workspace:. doesn't provide react-dom (p3460e), requested by @strapi/plugin-i18n
Oct 5 02:51:36 PM  ➤ YN0002: │ strapi-demo@workspace:. doesn't provide react-dom (p589ab), requested by @strapi/plugin-users-permissions
Oct 5 02:51:36 PM  ➤ YN0002: │ strapi-demo@workspace:. doesn't provide react-router-dom (pdef9c), requested by @strapi/plugin-i18n
Oct 5 02:51:36 PM  ➤ YN0002: │ strapi-demo@workspace:. doesn't provide react-router-dom (p1aa51), requested by @strapi/plugin-users-permissions
Oct 5 02:51:36 PM  ➤ YN0002: │ strapi-demo@workspace:. doesn't provide styled-components (pe6377), requested by @strapi/plugin-i18n
Oct 5 02:51:36 PM  ➤ YN0002: │ strapi-demo@workspace:. doesn't provide styled-components (pdd497), requested by @strapi/plugin-users-permissions
Oct 5 02:51:36 PM  ➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
Oct 5 02:51:36 PM  ➤ YN0000: └ Completed in 0s 465ms
Oct 5 02:51:36 PM  ➤ YN0000: ┌ Fetch step
Oct 5 02:52:24 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT Packing ts-zen@https://github.com/strapi/ts-zen.git#commit=66e02232f5997674cc7032ea3ee59d9864863732 from sources
Oct 5 02:52:24 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile
Oct 5 02:52:24 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT
Oct 5 02:52:28 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT ➤ YN0000: Retrieving https://classic.yarnpkg.com/latest.js
Oct 5 02:52:29 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT ➤ YN0000: Saving the new release in .yarn/releases/yarn-1.22.19.cjs
Oct 5 02:52:29 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT ➤ YN0000: Done in 1s 688ms
Oct 5 02:52:29 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT
Oct 5 02:52:31 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT yarn install v1.22.19
Oct 5 02:52:31 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT [1/5] Validating package.json...
Oct 5 02:52:31 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT [2/5] Resolving packages...
Oct 5 02:52:31 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT [3/5] Fetching packages...
Oct 5 02:53:06 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT [4/5] Linking dependencies...
Oct 5 02:53:06 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT [5/5] Building fresh packages...
Oct 5 02:53:06 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT Done in 25.59s.
Oct 5 02:53:06 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT
Oct 5 02:53:07 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT yarn pack v1.22.19
Oct 5 02:53:07 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT $ yarn build
Oct 5 02:53:07 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT yarn run v1.22.19
Oct 5 02:53:07 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT $ tsc && tsc-alias
Oct 5 02:53:11 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT Done in 3.57s.
Oct 5 02:53:11 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT success Wrote tarball to "/tmp/xfs-84aee614/package.tgz".
Oct 5 02:53:11 PM  ➤ YN0000: │ /tmp/xfs-84aee614 STDOUT Done in 4.03s.
Oct 5 02:53:13 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT Packing ts-zen@https://github.com/strapi/ts-zen.git#commit=66e02232f5997674cc7032ea3ee59d9864863732 from sources
Oct 5 02:53:13 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile
Oct 5 02:53:13 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT
Oct 5 02:53:13 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT ➤ YN0000: Retrieving https://classic.yarnpkg.com/latest.js
Oct 5 02:53:14 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT ➤ YN0000: Saving the new release in .yarn/releases/yarn-1.22.19.cjs
Oct 5 02:53:14 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT ➤ YN0000: Done in 0s 798ms
Oct 5 02:53:14 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT
Oct 5 02:53:15 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT yarn install v1.22.19
Oct 5 02:53:15 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT [1/5] Validating package.json...
Oct 5 02:53:15 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT [2/5] Resolving packages...
Oct 5 02:53:15 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT [3/5] Fetching packages...
Oct 5 02:53:16 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT [4/5] Linking dependencies...
Oct 5 02:53:20 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT [5/5] Building fresh packages...
Oct 5 02:53:20 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT Done in 5.35s.
Oct 5 02:53:20 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT
Oct 5 02:53:21 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT yarn pack v1.22.19
Oct 5 02:53:21 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT $ yarn build
Oct 5 02:53:21 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT yarn run v1.22.19
Oct 5 02:53:21 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT $ tsc && tsc-alias
Oct 5 02:53:25 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT Done in 3.88s.
Oct 5 02:53:25 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT success Wrote tarball to "/tmp/xfs-1d835e53/package.tgz".
Oct 5 02:53:25 PM  ➤ YN0000: │ /tmp/xfs-1d835e53 STDOUT Done in 4.37s.
Oct 5 02:53:25 PM  ➤ YN0018: │ ts-zen@https://github.com/strapi/ts-zen.git#commit=66e02232f5997674cc7032ea3ee59d9864863732: The remote archive doesn't match the expected checksum
Oct 5 02:53:25 PM  ➤ YN0013: │ 45 packages were already cached, 1256 had to be fetched
Oct 5 02:53:25 PM  ➤ YN0000: └ Completed in 1m 50s
Oct 5 02:53:25 PM  ➤ YN0000: Failed with errors in 1m 50s
Oct 5 02:53:27 PM  ==> Build failed 😞
```

**Comment by Boegie19** [comment] 2023-10-05 14:23
duplicate of https://github.com/strapi/strapi/issues/18299

**Comment by Convly** [comment] 2023-10-05 14:25
Not really the same error as in 18299 :thinking: 

The origin of the issue is indeed the same though

**Comment by Boegie19** [comment] 2023-10-05 14:30
@Convly Want me to re open it? since I like to add everyting with the same cause together.

**Comment by dwightgunning** [comment] 2023-10-05 14:46
It'll probably depend whether the approach to resolving #18299 will be simply to publish an NPM package (to avoid docker networking issues). The error I've reported isn't with networking. It pulls the package from github but then attempts to pack it using Yarn v1 because of the classic style yarn.lock.

**Comment by alexandrebodin** [comment] 2023-10-05 14:59
FYI we will release this package on npm to fix that early next week :)

**Closed** 2023-10-09 14:32 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: dependencies

**Comment by dwightgunning** [comment] 2023-10-17 12:42
Confirming the update to 14.14 resolved this issue.

Thanks!
