### ISSUE TITLE
Adding an extra image to a multiple media upload, replaces existing images on windows

### ISSUE THREAD

**Issue by MartinMuzatko** [strapi/strapi#1770] opened 2018-08-20 13:15 UTC
**Informations**
- **Node.js version**: 10.8.0
- **npm version**: 6.2.0
- **Strapi version**: alpha 13.1
- **Database**: pg
- **Operating system**: WSL/Ubuntu Linux

**What is the current behavior?**

I need to select all images I want to upload at once, If I do it one after another, only the last image is used. Also if there is also an image, and I want to add one, the new one replaces the old ones.

![strapi-bug](https://user-images.githubusercontent.com/2950505/44342593-cfe37580-a48b-11e8-935b-c2c6806721de.gif)

**Steps to reproduce the problem**

- have a model with a field `media` with multiple uploads allowed.
- create a new entry with any amount of images attached to it
- edit the entry, add another file
- save
- re-open the entry 
- there is only the last images added left.

**What is the expected behavior?**

Add the images to the existing ones, not replace them)

**Suggested solutions**

Always add to the list of images, not replace.
I believe the `PUT` request is made without the existing images.

**Comment by MartinMuzatko** [comment] 2018-08-20 13:17
Duplicate of #1645

**Comment by danielehrhardt** [comment] 2018-08-21 14:02
@MartinMuzatko Why did you closed the Ticket?

**Comment by MartinMuzatko** [comment] 2018-08-21 14:07
I wanted to clean it up in favor of the older one. Didn't know @soupette liked the detail I put into this ticket :P

**Comment by derrickmehaffy** [comment] 2018-08-28 12:50
@danielehrhardt can you confirm this still exists with Strapi v14 please.

**Comment by danielehrhardt** [comment] 2018-08-29 16:47
@MartinMuzatko could you please check the Question from derrickmehaffy

**Comment by danielehrhardt** [comment] 2018-08-30 12:36
I think it is fixed with v14.

**Comment by MartinMuzatko** [comment] 2018-08-30 13:13
I'll check the next days

**Comment by danielehrhardt** [comment] 2018-08-30 13:16
It is still not working.

**Comment by lauriejim** [comment] 2018-08-30 13:25
I tried and I'm not able to reproduce.

**Comment by danielehrhardt** [comment] 2018-08-30 14:53
@lauriejim 
https://drive.google.com/file/d/1XHQ0OuGm-j4dLO8JgCakxSWeYw1b4m6L/view

**Comment by soupette** [comment] 2018-08-30 16:05
@danielehrhardt are you using the last version of strapi?

**Comment by lauriejim** [comment] 2018-08-30 17:03
Test with last version of Strapi and with a fresh new app.

**Comment by danielehrhardt** [comment] 2018-08-30 17:08
Yes I tested with Alpha 14 and with a new Setup.
I am using Windows 10.

**Comment by lauriejim** [comment] 2018-08-31 08:11
Someone with MacOs can test it please.

**Comment by danielehrhardt** [comment] 2018-09-02 22:57
it works with mac osx. This is extreme wried.

**Comment by lauriejim** [comment] 2018-09-03 10:37
🤦‍♂️ Okay !

**Comment by giona69** [comment] 2019-01-16 21:47
I report the same bug
it doesn't work on macos x locally and on a linux (amazon image) deployed build.

**Informations**
- **Node.js version**: 10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: alpha.19
- **Database**: mysql
- **Operating system**: macosx mojave

**What is the current behavior?**
I added a content type with a media field with "Allow multiple files" enabled. 
While when I edit a content I can add multiple files, and they are correctly uploaded, after I save I can see only one content (1/1), abnd when I query them I see only one content.  

**Steps to reproduce the problem**
added a new content type with a media field and "Allow multiple files" enabled.
add a content item in that content type.
add two medias.
save.
edit again that content item.
verify that we have only one media attached now.

**What is the expected behavior?**
added a new content type with a media field and "Allow multiple files" enabled.
add a content item in that content type.
add two medias.
save.
edit again that content item.
verify that we have two media attached now.

**Comment by lauriejim** [comment] 2019-03-13 11:33
I just tested it with window and mac os with last version of Strapi (alpha.24.1) and this issue look fixed.

**Closed by lauriejim** 2019-03-13 11:33 UTC
Labels: priority: medium, status: confirmed, type: bug 🐛

**Comment by Emadeddin-eibo** [comment] 2019-05-24 14:56
it's fixed on local "uploads" folder, but the issue still exists on Upload Providers (Tested on Cloudinary)

**Comment by ascott** [comment] 2019-08-01 20:14
i'm using strapi v3.0.0-alpha.17 on mac osx locally and on heroku and i'm seeing this issue. any ideas how to resolve?

**Comment by paddymccallan** [comment] 2019-08-13 20:59
Still seeing this is well with heroku & v3.0.0-alpha

**Comment by Radau** [comment] 2019-08-29 19:05
Strapi 3.0.0-alpha.26.1 here,

I'm seeing this happen in node_modules/strapi-hook-bookshelf/lib/relations.js where the nature is checked (by `if (association.nature === 'manyMorphToOne') {`). 

If your field uses `via: 'related'`, it will use the `manyMorphToOne` instead of the nature set for the field, which will wipe out any existing relationships in the upload_file_morph table when you upload a new file.

I came up with this workaround for now which seems to work fine, hopefully a strapi dev can weigh in, I'd imagine there's a better place to implement it but this got it so we can at least continue content entry.

replace `if (association.nature === 'manyMorphToOne') {` in node_modules/strapi-hook-bookshelf/lib/relations.js
```
// Use the Fields nature if linked via 'related'
let associationNature = association.nature;
if (association.alias === 'related' && obj.field) {
  const fieldAssociation = model.associations.filter(x => x.alias === obj.field)[0];
  if (fieldAssociation) {
    associationNature = fieldAssociation.nature;
  }
}

// Remove existing relationship because only one file
// can be related to this field.
if (associationNature === 'manyMorphToOne') {
```

This issue was compounded on our staging server, where if you uploaded a few larger files they would overwrite eachother as they saved, so if you uploaded 9 files you would have maybe 1 or 2 when you refresh the page. Resolving the association nature mismatch using the workaround also fixed this for us for anyone running into a similar problem.

Here is an example of the mismatch we noticed


```
{ alias: 'ActivityMaterials',
  type: 'collection',
  collection: 'file',
  via: 'related',
  nature: 'manyToManyMorph',
  autoPopulate: true,
  dominant: true,
  plugin: 'upload',
  filter: 'field' }
```

vs

```
{ alias: 'related',
  type: 'collection',
  related:
   [ 'Activity',
     'Activityinstanceupload',
     'Benchmark',
     'Funderreportupload' ],
  nature: 'manyMorphToOne',
  autoPopulate: true,
  filter: 'field' }
```
