### ISSUE TITLE
GraphQL returning null for a non-empty relation when using custom queries

### ISSUE THREAD

**Issue by cgonzalezsan** [strapi/strapi#9934] opened 2021-04-01 19:08 UTC
### Describe the bug

GraphQL is returning an empty relation (product_series) when using GraphQL but not when using REST API. They both are using the same controller (and service).

### Steps to reproduce the behavior

1. Run GraphQL query: product series is null
2. Run REST API endpoint: product series is filled in

### Expected behavior
The output of the GraphQL query should have product series, but it's returning NULL instead. 
The rest endpoint returns the right value for product series.

### Screenshots

REST API endpoint output:
<img width="1254" alt="Screenshot 2021-04-01 at 21 47 25" src="https://user-images.githubusercontent.com/6850051/113340166-34e5f400-9334-11eb-93ee-dc511675bec7.png">

GraphQL query output
<img width="855" alt="Screenshot 2021-04-01 at 21 51 23" src="https://user-images.githubusercontent.com/6850051/113340353-71b1eb00-9334-11eb-80ab-97b66dc65c25.png">

### Code snippets

GraphQL query:

```
query productSearc {  
    productsSearch(limit: 3) {
      name_en
      name_de
      slug
      product_series{
        name_en
      }
    }
}
```

schema.graphql.js
```
module.exports = {
  query: `
  productsCount(where: JSON, outputChannel: String!): [Int]!
  productsSearch(where: JSON, locale: String, limit: Int! = 20, offset: Int! = 0, sortColumn: String = "", sortDirection: String = "asc"): [Product]!
  searchResultsCount(where: JSON, locale: String): Int
`,
  resolver: {
    Query: {
      productsCount: {
        description: 'Return the count of products',
        resolver: 'application::product.product.categoriesCount',
      },
      searchResultsCount: {
        description: 'Return the total count of products search',
        resolver: 'application::product.product.searchResultsCount',
      },
      productsSearch: {
        description: 'Return search results for products search',
        resolverOf: 'application::product-category.product.count',
        resolver: 'application::product.product.search',
      },
    },
  },
};

```

routes.json
```
{
      "method": "POST",
      "path": "/productSearch",
      "handler": "product.productSearch",
      "config": {
        "policies": []
      }
}
```
### System

- Node.js version: 14.16.0
- NPM version: 6.14.11
- Strapi version: 3.5.1
- Database: MongoDB
- Operating system: Mac

**Comment by derrickmehaffy** [comment] 2021-04-01 19:42
I believe in this context the custom resolver is not resolving the relations due to the missing content-manager service query.

@strapi/contributors can you take a look to see if there is any guidance we can provide on why the relations aren't being resolved.

@cgonzalezsan can you provide your custom code examples so we can try to reproduce?

**Comment by cgonzalezsan** [comment] 2021-04-01 19:46
controller -> product.js
```
productSearch: async (ctx) => {
    const { product } = strapi.services;

    ctx.send(
      await product.productSearch(
        ctx.request.body.where,
        ctx.request.body.locale,
        ctx.request.body.limit,
        ctx.request.body.offset,
        ctx.request.body.sortColumn,
        ctx.request.body.sortDirection,
      )
    );
  },
```



services -> product.js
```
'use strict';

const _ = require('lodash');

const getTermField = (locale) => {
  return locale === 'de' ? 'term_de' : 'term_en';
};

// returns null for query params that would return no results
// so the query can be avoided
const getFindParams = async (filters, locale) => {
  const params = { published_at: { $exists: true, $ne: null } };

  if (!filters) {
    return params;
  }
  const field = getTermField(locale);
  if (!_.isEmpty(filters.term)) {
    const regex = new RegExp(_.escapeRegExp(filters.term), 'i');

    params['$or'] = [{ [field]: regex }, { pim_id: regex }];
  }

  if (!_.isEmpty(filters.categoryIds)) {
    params['product_categories'] = {
      $in: filters.categoryIds,
    };
  }

  if (!_.isEmpty(filters.subcategoryIds)) {
    params['product_subcategories'] = {
      $in: filters.subcategoryIds,
    };
  }

  if (!_.isEmpty(filters.designerIds)) {
    //Find product series from the designer
    const productSeries = await strapi
      .query('product-series')
      .model.find({ designer: { $in: filters.designerIds } });
    if (productSeries.length) {
      params['product_series'] = {
        $in: productSeries,
      };
    } else {
      return null;
    }
  }

  if (!_.isEmpty(filters.categorySlug)) {
    const category = await strapi
      .query('product-category')
      .model.findOne({ slug: filters.categorySlug });
    if (category) {
      params['product_categories'] = {
        $in: category.get('id'),
      };
    } else {
      return null;
    }
  }

  if (!_.isEmpty(filters.designerSlug)) {
    //Find first the designer model
    const designer = await strapi.query('designer').model.findOne({ slug: filters.designerSlug });
    if (designer) {
      //Find product series from the designer
      const productSeries = await strapi
        .query('product-series')
        .model.find({ designer: designer.get('id') });
      //Filter products which have the above product series
      if (productSeries.length) {
        params['product_series'] = {
          $in: productSeries.map((p) => p.id),
        };
      } else {
        return null;
      }
    } else {
      return null;
    }
  }

  if (!_.isEmpty(filters.locationTypeIds)) {
    params['location_types'] = {
      $in: filters.locationTypeIds,
    };
  }

  if (!_.isEmpty(filters.outputChannel)) {
    params['channels'] = filters.outputChannel;
  }

  return params;
};

module.exports = {
  search: async (
    filters,
    locale,
    limit = 20,
    offset = 0,
    sortColumn = 'ranking',
    sortDirection = 'asc'
  ) => {
    const params = await getFindParams(filters, locale);

    // if params are null, return an empty array and avoid searching
    if (!params) {
      return [];
    }

    let querySortColumn;
    switch (sortColumn) {
      case 'modelNumber':
        querySortColumn = 'pim_id';
        break;
      case 'name':
        querySortColumn = getTermField(locale);
        break;
      default:
        querySortColumn = 'ranking';
    }

    return await strapi
      .query('product')
      .model.find(params)
      .sort({ [querySortColumn]: sortDirection === 'asc' ? 1 : -1 })
      .skip(offset)
      .limit(limit);
  },

  searchResultsCount: async (filters, locale) => {
    const params = await getFindParams(filters, locale);
    if (!params) {
      return 0;
    }

    return (await strapi.query('product').model.count(params)) || 0;
  },

  categoriesCount: async (outputChannel) => {
    const categories = await strapi.query('product-category').find();
    const totalCounts = [];
    for (let i = 0; i < categories.length; i++) {
      const count = await strapi.query('product').countSearch({
        product_categories: { $in: categories[i].id },
        channels: outputChannel,
      });
      totalCounts.push(count);
    }

    return totalCounts;
  },

  // used for rest endpoint
  productSearch: async (
    filters,
    locale,
    limit = 20,
    offset = 0,
    sortColumn = 'ranking',
    sortDirection = 'asc'
  ) => {
    const params = await getFindParams(filters, locale);

    // if params are null, return an empty array and avoid searching
    if (!params) {
      return { results: [], count: 0 };
    }

    let querySortColumn;
    switch (sortColumn) {
      case 'modelNumber':
        querySortColumn = 'pim_id';
        break;
      case 'name':
        querySortColumn = getTermField(locale);
        break;
      default:
        querySortColumn = 'ranking';
    }

    const results = await strapi
      .query('product')
      .model.find(params)
      .select('+id +name_en +name_de +pim_id +slug +product_categories +product_series +assets')
      // .select('id name_en name_de pim_id slug product_categories product_series assets')
      .populate([
        { path: 'product_categories', select: '+id +slug' },
        {
          path: 'product_series',
          select: '+id +name_en +name_de +designer',
          populate: { path: 'designer', select: 'id name' },
        },
        {
          path: 'assets',
          // select: '-products +type +subtype +file',
          match: { type: 'image', subtype: 'picture.pdp-cutout.' },
          // sort: { sorting: 1 },
          // limit: 1,
          populate: {
            path: 'file',
            select:
              '+formats +url-_id -name -alternativeText -hash -ext -mime -size -width -height',
          },
        },
      ])
      .sort({ [querySortColumn]: sortDirection === 'asc' ? 1 : -1 })
      .skip(offset)
      .limit(limit);

    results.forEach((r) => {
      if (r.assets && r.assets.length) {
        r.assets = [r.assets.sort((a, b) => (a.sorting < b.sorting ? -1 : 1))[0]];
      } else {
        r.assets = [];
      }
    });

    const count = (await strapi.query('product').model.count(params)) || 0;

    return { results, count };
  },
};

```

**Comment by cgonzalezsan** [comment] 2021-04-01 19:48
For the record, other relations are being populated correctly through GraphQL, e.g. Assets

<img width="1539" alt="Screenshot 2021-04-01 at 22 41 18" src="https://user-images.githubusercontent.com/6850051/113346329-619e0980-933c-11eb-8120-98f8941e3735.png">

**Comment by derrickmehaffy** [comment] 2022-01-05 21:55
shouldn't be an issue in v4, marking as closed

**Closed by derrickmehaffy** 2022-01-05 21:55 UTC
Labels: severity: low, issue-type: help wanted, source: plugin:graphql, status: pending reproduction
