### ISSUE TITLE
GraphQL Plugin => TypeError: Cannot read property "call" of undefined

### ISSUE THREAD

**Issue by danielmaartens-sovtech** [strapi/strapi#5569] opened 2020-03-23 05:20 UTC
**Edit:** Please avoid pinging people unless needed.

After installing the graphql plugin I get the following error:

```
[2020-03-23T05:00:59.057Z] info The server is restarting

/Users/danielmaartens/drm/sovtech/acdc/strapi-develop/plugins/graphql/hooks/graphql/index.js:48
                .call(strapi, files, true)
                 ^

TypeError: Cannot read property 'call' of undefined
    at glob (/Users/danielmaartens/drm/sovtech/acdc/strapi-develop/plugins/graphql/hooks/graphql/index.js:48:18)
    at f (/Users/danielmaartens/drm/sovtech/acdc/strapi-develop/plugins/graphql/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/danielmaartens/drm/sovtech/acdc/strapi-develop/plugins/graphql/node_modules/glob/glob.js:151:7)
    at Glob.emit (events.js:189:13)
    at Glob._finish (/Users/danielmaartens/drm/sovtech/acdc/strapi-develop/plugins/graphql/node_modules/glob/glob.js:197:8)
    at done (/Users/danielmaartens/drm/sovtech/acdc/strapi-develop/plugins/graphql/node_modules/glob/glob.js:182:14)
    at Glob._processReaddir2 (/Users/danielmaartens/drm/sovtech/acdc/strapi-develop/plugins/graphql/node_modules/glob/glob.js:408:12)
    at /Users/danielmaartens/drm/sovtech/acdc/strapi-develop/plugins/graphql/node_modules/glob/glob.js:371:17
    at RES (/Users/danielmaartens/drm/sovtech/acdc/strapi-develop/plugins/graphql/node_modules/inflight/inflight.js:31:16)
    at f (/Users/danielmaartens/drm/sovtech/acdc/strapi-develop/plugins/graphql/node_modules/once/once.js:25:25)
    at Glob._readdirEntries (/Users/danielmaartens/drm/sovtech/acdc/strapi-develop/plugins/graphql/node_modules/glob/glob.js:578:10)
    at /Users/danielmaartens/drm/sovtech/acdc/strapi-develop/plugins/graphql/node_modules/glob/glob.js:555:12
    at FSReqWrap.oncomplete (fs.js:141:20)
```

**Steps to reproduce the behavior**
1. RUN `yarn create strapi-app strapi-develop --quickstart`
2. RUN `strapi install graphql`
3. Restart strapi app

**Expected behavior**
You are expected to access the graphql playground.

![image](https://user-images.githubusercontent.com/59686723/77283629-7ed5dc00-6cd5-11ea-9d4d-b3e50805923f.png)

**System**
- Node.js version: v10.15.1
- NPM version: 6.4.1
- Strapi version: beta.19.3
- Database: SQLite
- Operating system: MacOS Mojave

**Comment by derrickmehaffy** [comment] 2020-03-23 05:44
@danielmaartens-sovtech please avoid pinging Strapi team members unless you need to, I have edited your OP.

**Comment by danielmaartens-sovtech** [comment] 2020-03-23 05:51
@derrickmehaffy I did so to get a quick response as this is quite urgent.

**Comment by derrickmehaffy** [comment] 2020-03-23 05:56
Was not able to reproduce this on linux using beta.19.3

![image](https://user-images.githubusercontent.com/8593673/77286378-524ba100-6c90-11ea-85bf-5d16f0bdfb65.png)

![image](https://user-images.githubusercontent.com/8593673/77286392-5bd50900-6c90-11ea-885c-b210fc463bc7.png)

**Comment by derrickmehaffy** [comment] 2020-03-23 05:59
I'm not sure how you managed to do it but your graphql plugin is being installed in the wrong directory:

`plugins/graphql/hooks/graphql/index.js`

It should be coming from `node_modules`, can you confirm that you don't have a very old version of strapi installed globally on your system using `which strapi` in a terminal. And likewise please delete the graphql folder from your `plugins` folder in your project.

**Comment by danielmaartens-sovtech** [comment] 2020-03-23 06:09
I think my global version might be the issue as I followed the steps you did above, specificall `yarn strapi install graphql` instead of `strapi install graphql`.

BTW, `which strapi` returns:
`/Users/danielmaartens/.nvm/versions/node/v10.15.1/bin/strapi`

**Comment by derrickmehaffy** [comment] 2020-03-23 06:10
if you run `strapi version` that should dump out the old version, which I'm guessing is some alpha one.

I'd suggest you update that global version or just remove it completely. In either case, going to go ahead and mark this as closed as it isn't a bug with Strapi itself.

**Closed by derrickmehaffy** 2020-03-23 06:10 UTC
