### ISSUE TITLE
strapi is not able to install

### ISSUE THREAD

**Issue by AnjaliMahawar** [strapi/strapi#12148] opened 2022-01-10 07:54 UTC
### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version:
- Strapi version: 
- Database:
- Operating system:

**Comment by EzraEn1** [comment] 2022-01-10 07:58
Please ensure that the issue template is filled out properly. Please also check that your issue is not a duplicate of #12142.

**Comment by EzraEn1** [comment] 2022-01-10 09:23
Please close this issue @AnjaliMahawar.
Duplicate of #12142

**Comment by kasonde** [comment] 2022-01-10 14:27
Duplicate of #12142

**Closed by kasonde** 2022-01-10 14:27 UTC
