### ISSUE TITLE
Number field with default value 0 it is created as null

### ISSUE THREAD

**Issue by Pablo-Aldana** [strapi/strapi#10463] opened 2021-06-10 08:22 UTC
## Bug report

When you create a new number field with the default value as 0 and the call the API to create a new item this field is created with null value instead with 0. If the default value is set to 1 this does not occur.

### Steps to reproduce the behavior

1. Go to Content-type builder 
2. Click on User or any other created type or create your own
4. Add new field i.e loyaltypoints with type Number, number format: Integer
5. In advance settings, set default value 0 and minimum value = 0
6. Save the changes
7. Call the API to create a new entity 
 -  A: Do not pass the parameter loyalty points -> record is created with loyaltypoint = null
 
 - B: Do pass the parameter as 0 -> record is created with loyaltypoint=null

### Expected behaviour

In scenario A: as the default value was set to 0 the record should be created with value 0.
in Scenario B: as the parameter is being passed with value0 the record should be created with value 0.

As commented in scenario B if you change the passed value to something different than 0, ie: 1, the record is successfully created with loyaltypoints = 1 (or the value passed)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 14.15.1 
- NPM version: 7.5.3
- Strapi version: 3.6.3
- Database: Postgress
- Operating system: MacOS

**Comment by derrickmehaffy** [comment] 2021-06-15 14:51
Cannot reproduce v3.6.3 using the following model structure:

```json
{
  "kind": "collectionType",
  "collectionName": "tests",
  "info": {
    "name": "test"
  },
  "options": {
    "increments": true,
    "timestamps": true,
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "default_zero": {
      "type": "integer",
      "default": 0,
      "min": 0
    },
    "default_one": {
      "type": "integer",
      "default": 1,
      "min": 1
    }
  }
}
```

When creating a new entry in the admin the defaults are already set correct:

```
[
  {
    "id": 1,
    "default_zero": 0,
    "default_one": 1,
    "published_at": "2021-06-15T14:45:22.263Z",
    "created_at": "2021-06-15T14:44:10.355Z",
    "updated_at": "2021-06-15T14:45:22.276Z"
  }
]
```

---

I see in your step 6 you are doing it through the API and right now we don't apply defaults at the API layer. The best way to implement that until we get to our v4 is via a policy that checks the coming data and if the field isn't specified then inject the default.

**Comment by derrickmehaffy** [comment] 2021-06-25 18:34
Closing as no new information

**Closed by derrickmehaffy** 2021-06-25 18:34 UTC
Labels: status: can't reproduce
