### ISSUE TITLE
Regression in relation tooltip styling in dark mode

### ISSUE THREAD

**Issue by Sija** [strapi/strapi#13868] opened 2022-07-27 14:58 UTC
### Required System information

- Node.js version: v16.16.0
- Strapi version: v4.3.0

### Describe the bug

Relation selector is not having dark-mode styling applied.

### Steps to reproduce the behavior

1. Switch to dark mode
2. Open the relation selector
3. See error

### Expected behavior

Dark-mode matching styles to be applied.

### Screenshots

<img width="663" alt="image" src="https://user-images.githubusercontent.com/988/181279542-e0466b8c-dd4f-42f5-a51f-b70224ff50d4.png">

**Comment by AdrianFahrbach** [comment] 2022-07-27 15:52
Already saw that too.

It also seems like this is only an issue in one-to-one relations, not in one-to-many. The multiple selection dropdown is working as intended.

**Comment by gu-stav** [comment] 2022-07-28 13:46
Thank you for opening the issue. 🌻 

The two attached PRs will solve both bugs and will be released as part of 4.3.1 on the 10th auf August.

**Closed by gu-stav** 2022-07-28 13:46 UTC

**Comment by Sija** [comment] 2022-07-28 13:47
@gu-stav Sweet news! Thanks for the quick turnaround 🙏

**Comment by AdrianFahrbach** [comment] 2022-08-04 06:48
This issue is not fixed in 4.3.2.
