### ISSUE TITLE
Microsoft SSO login callback exceed header fields too large

### ISSUE THREAD

**Issue by lordzpipo** [strapi/strapi#9767] opened 2021-03-18 17:39 UTC
### Describe the bug
exceed header fields too large during microsoft AAD sso login

example: 
```
http://frontend.url?access_token=eyJ0eXAiOiJKV1QiLCJub25jZSI6Ik9wVnNTZ1hmbzdtVm1rU2NGRGFRTWthMDZ6LUVkYmRsQjZ0SVhNS08tYU0iLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zMjI4YWY1YS02ZGI2LTRlM2EtYTZjNC0yY2FjNjhlOGQ4ZTIvIiwiaWF0IjoxNjE2MDg3NzEzLCJuYmYiOjE2MTYwODc3MTMsImV4cCI6MTYxNjA5MTYxMywiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXI6cmVnaXN0ZXJzZWN1cml0eWluZm8iLCJ1cm46bWljcm9zb2Z0OnJlcTEiLCJ1cm46bWljcm9zb2Z0OnJlcTIiLCJ1cm46bWljcm9zb2Z0OnJlcTMiLCJjMSIsImMyIiwiYzMiLCJjNCIsImM1IiwiYzYiLCJjNyIsImM4IiwiYzkiLCJjMTAiLCJjMTEiLCJjMTIiLCJjMTMiLCJjMTQiLCJjMTUiLCJjMTYiLCJjMTciLCJjMTgiLCJjMTkiLCJjMjAiLCJjMjEiLCJjMjIiLCJjMjMiLCJjMjQiLCJjMjUiXSwiYWlvIjoiQVNRQTIvOFRBQUFBdFBlTW5mclhDWCtJK3BCRGFxWFBPSnhvd3ZpbDJjVjZ2MlBKNnZpWUNhST0iLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6InN0cmFwaSB0ZXN0IiwiYXBwaWQiOiJmYTE2NTg2OC1mZWQyLTRkN2ItODY0MS03ZTc2MmNlZjQzOGUiLCJhcHBpZGFjciI6IjEiLCJmYW1pbHlfbmFtZSI6InRlc3QiLCJnaXZlbl9uYW1lIjoidGVzdCIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjEyMS4xMjIuMTExLjIxNyIsIm5hbWUiOiJzdHJhcGkiLCJvaWQiOiI5ZjQ3ZDIxMS0xZWI2LTRjNjYtODA4Mi0zMGEzZjFjMDlmNGMiLCJwbGF0ZiI6IjUiLCJwdWlkIjoiMTAwMzIwMDExRDcyRkYwNCIsInJoIjoiMC5BQUFBV3E4b01yWnRPazZteEN5c2FPalk0bWhZRnZyU19udE5oa0YtZGl6dlE0NXhBTWsuIiwic2NwIjoiVXNlci5SZWFkIHByb2ZpbGUgb3BlbmlkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoid2tMNzdhODFGcFdqTTVjRF93MEZ6NU9OamR1QVZoY2VqdHByTWpIOVBSZyIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJBUyIsInRpZCI6IjMyMjhhZjVhLTZkYjYtNGUzYS1hNmM0LTJjYWM2OGU4ZDhlMiIsInVuaXF1ZV9uYW1lIjoic3RyYXBpQGtlbnBoYW5nMTk5MWhvdG1haWwub25taWNyb3NvZnQuY29tIiwidXBuIjoic3RyYXBpQGtlbnBoYW5nMTk5MWhvdG1haWwub25taWNyb3NvZnQuY29tIiwidXRpIjoiUTlmbnZoekhwa0dOWG5qZXpsRUJBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJRN1ZWSVhFUTMzNlhsN2FFMXZDakNFWnRxeXJtZVZBX1BVb0VuMnZ0QU9zIn0sInhtc190Y2R0IjoxNjAxNTE5OTkzfQ.f24uTc6u9kP169dUw4mJa5AhRgtTz5cAVv5tgWuvQu2zYZ_U7dpXrFY39Njr7AQFr3s4XegNbml4JBrMeTMAT0raXpFDHAMDcmn1BOFz6GGhXQdBQlgcB2iw6UcpFwIX74RQrlsA0jpTifAvn9FJ6GahUmKHQhcHLMBViDI9N0HVzUdtmEK506yF-So1D-Uh448BV3-XcUgYRAPN7xQyDV4rq1V2EjiLYbe6E6N29-jtF8JA_1K4EMeh1tuBZKj4wX4EXunGSAHouCcv7-epr3DiUjLOxFM49Y-KZoKOLC0goaRT8GV5ZbYbMZVx3NupY0XocgKVlYgyehRBh8GnCw&raw%5Btoken_type%5D=Bearer&raw%5Bscope%5D=User.Read%20profile%20openid%20email&raw%5Bexpires_in%5D=3599&raw%5Bext_expires_in%5D=3599&raw%5Baccess_token%5D=eyJ0eXAiOiJKV1QiLCJub25jZSI6Ik9wVnNTZ1hmbzdtVm1rU2NGRGFRTWthMDZ6LUVkYmRsQjZ0SVhNS08tYU0iLCJhbGciOiJSUzI1NiIsIng1dCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCI6Im5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zMjI4YWY1YS02ZGI2LTRlM2EtYTZjNC0yY2FjNjhlOGQ4ZTIvIiwiaWF0IjoxNjE2MDg3NzEzLCJuYmYiOjE2MTYwODc3MTMsImV4cCI6MTYxNjA5MTYxMywiYWNjdCI6MCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXI6cmVnaXN0ZXJzZWN1cml0eWluZm8iLCJ1cm46bWljcm9zb2Z0OnJlcTEiLCJ1cm46bWljcm9zb2Z0OnJlcTIiLCJ1cm46bWljcm9zb2Z0OnJlcTMiLCJjMSIsImMyIiwiYzMiLCJjNCIsImM1IiwiYzYiLCJjNyIsImM4IiwiYzkiLCJjMTAiLCJjMTEiLCJjMTIiLCJjMTMiLCJjMTQiLCJjMTUiLCJjMTYiLCJjMTciLCJjMTgiLCJjMTkiLCJjMjAiLCJjMjEiLCJjMjIiLCJjMjMiLCJjMjQiLCJjMjUiXSwiYWlvIjoiQVNRQTIvOFRBQUFBdFBlTW5mclhDWCtJK3BCRGFxWFBPSnhvd3ZpbDJjVjZ2MlBKNnZpWUNhST0iLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6InN0cmFwaSB0ZXN0IiwiYXBwaWQiOiJmYTE2NTg2OC1mZWQyLTRkN2ItODY0MS03ZTc2MmNlZjQzOGUiLCJhcHBpZGFjciI6IjEiLCJmYW1pbHlfbmFtZSI6InRlc3QiLCJnaXZlbl9uYW1lIjoidGVzdCIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjEyMS4xMjIuMTExLjIxNyIsIm5hbWUiOiJzdHJhcGkiLCJvaWQiOiI5ZjQ3ZDIxMS0xZWI2LTRjNjYtODA4Mi0zMGEzZjFjMDlmNGMiLCJwbGF0ZiI6IjUiLCJwdWlkIjoiMTAwMzIwMDExRDcyRkYwNCIsInJoIjoiMC5BQUFBV3E4b01yWnRPazZteEN5c2FPalk0bWhZRnZyU19udE5oa0YtZGl6dlE0NXhBTWsuIiwic2NwIjoiVXNlci5SZWFkIHByb2ZpbGUgb3BlbmlkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoid2tMNzdhODFGcFdqTTVjRF93MEZ6NU9OamR1QVZoY2VqdHByTWpIOVBSZyIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJBUyIsInRpZCI6IjMyMjhhZjVhLTZkYjYtNGUzYS1hNmM0LTJjYWM2OGU4ZDhlMiIsInVuaXF1ZV9uYW1lIjoic3RyYXBpQGtlbnBoYW5nMTk5MWhvdG1haWwub25taWNyb3NvZnQuY29tIiwidXBuIjoic3RyYXBpQGtlbnBoYW5nMTk5MWhvdG1haWwub25taWNyb3NvZnQuY29tIiwidXRpIjoiUTlmbnZoekhwa0dOWG5qZXpsRUJBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJRN1ZWSVhFUTMzNlhsN2FFMXZDakNFWnRxeXJtZVZBX1BVb0VuMnZ0QU9zIn0sInhtc190Y2R0IjoxNjAxNTE5OTkzfQ.f24uTc6u9kP169dUw4mJa5AhRgtTz5cAVv5tgWuvQu2zYZ_U7dpXrFY39Njr7AQFr3s4XegNbml4JBrMeTMAT0raXpFDHAMDcmn1BOFz6GGhXQdBQlgcB2iw6UcpFwIX74RQrlsA0jpTifAvn9FJ6GahUmKHQhcHLMBViDI9N0HVzUdtmEK506yF-So1D-Uh448BV3-XcUgYRAPN7xQyDV4rq1V2EjiLYbe6E6N29-jtF8JA_1K4EMeh1tuBZKj4wX4EXunGSAHouCcv7-epr3DiUjLOxFM49Y-KZoKOLC0goaRT8GV5ZbYbMZVx3NupY0XocgKVlYgyehRBh8GnCw#
```

some breakdown for this params:
```
access_token,
raw%5Btoken_type%5D,
raw%5Bscope%5D,
raw%5Bexpires_in%5D,
raw%5Bext_expires_in%5D,
raw%5Baccess_token%5D <--- duplicate
```

in this case, it will cause a 431 error (Request header fields too large) during redirect on azure app services

### Steps to reproduce the behavior

1. Go to `settings -> providers`
2. enable `microsoft` and set the redirect path to `/auth/microsoft/callback` (example, should frontend url)
3. See error 431

### Expected behavior
no error 

### System

- Node.js version: v12-lts
- NPM version:
- Strapi version: 3.4.4
- Database: mysql
- Operating system: linux, Azure App Services

### Additional context

please help.. i'm rushing delivery to my client... 
thanks

**Comment by derrickmehaffy** [comment] 2021-03-29 22:07
Please provide additional debugging steps as I couldn't reproduce this on v3.5.4

Marking as closed until additional information is provided.

**Comment by lordzpipo** [comment] 2021-04-17 09:50
i am sorry for late reply @derrickmehaffy ,

please have a look the console output
```
[2021-04-17T09:3:21.949Z] debug GET /auth/microsoft/callback?access_token=eyJ0eXAiOiJKV1QiLCJub25jZSIImhNb2RvczIwMXF4ak5kZEZ1Tmp2NXJmcXd2RmVYN3VuV3d2QjZxczRueHMiLCJhbGciOiJSUzI1NiIsIng1dCIIm5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCIIm5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zMjI4YWY1YS02ZGI2LTRlM2EtYTZjNC0yY2FjNjhlOGQ4ZTIvIiwiaWF0IjoxNjE4NjUxODgxLCJuYmYiOjE2MTg2NTE4ODEsImV4cCIMTYxODY1NTc4MSwiYWNjdCIMCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXIcmVnaXN0ZXJzZWN1cml0eWluZm8iLCJ1cm4bWljcm9zb2Z0OnJlcTEiLCJ1cm4bWljcm9zb2Z0OnJlcTIiLCJ1cm4bWljcm9zb2Z0OnJlcTMiLCJjMSIsImMyIiwiYzMiLCJjNCIsImM1IiwiYzYiLCJjNyIsImM4IiwiYzkiLCJjMTAiLCJjMTEiLCJjMTIiLCJjMTMiLCJjMTQiLCJjMTUiLCJjMTYiLCJjMTciLCJjMTgiLCJjMTkiLCJjMjAiLCJjMjEiLCJjMjIiLCJjMjMiLCJjMjQiLCJjMjUiXSwiYWlvIjoiQVNRQTIvOFRBQUFBRVZObnVkYmlvT3NUMDdDbnA2ZmJKVXdaRXU0cEtWUW5PVjdIcHp0Si9Ncz0iLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSIInN0cmFwaSB0ZXN0IiwiYXBwaWQiOiJmYTE2NTg2OC1mZWQyLTRkN2ItODY0MS03ZTc2MmNlZjQzOGUiLCJhcHBpZGFjciIIjEiLCJmYW1pbHlfbmFtZSIInRlc3QiLCJnaXZlbl9uYW1lIjoidGVzdCIsImlkdHlwIjoidXNlciIsImlwYWRkciIIjEyMS4xMjIuMTExLjIzNCIsIm5hbWUiOiJzdHJhcGkiLCJvaWQiOiI5ZjQ3ZDIxMS0xZWI2LTRjNjYtODA4Mi0zMGEzZjFjMDlmNGMiLCJwbGF0ZiIIjUiLCJwdWlkIjoiMTAwMzIwMDExRDcyRkYwNCIsInJoIjoiMC5BWEVBV3E4b01yWnRPazZteEN5c2FPalk0bWhZRnZyU19udE5oa0YtZGldlE0NXhBTWsuIiwic2NwIjoiVXNlci5SZWFkIHByb2ZpbGUgb3BlbmlkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoid2tMNzdhODFGcFdqTTVjRF93MEZNU9OamR1QVZoY2VqdHByTWpIOVBSZyIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJBUyIsInRpZCIIjMyMjhhZjVhLTZkYjYtNGUzYS1hNmM0LTJjYWM2OGU4ZDhlMiIsInVuaXF1ZV9uYW1lIjoic3RyYXBpQGtlbnBoYW5nMTk5MWhvdG1haWwub25taWNyb3NvZnQuY29tIiwidXBuIjoic3RyYXBpQGtlbnBoYW5nMTk5MWhvdG1haWwub25taWNyb3NvZnQuY29tIiwidXRpIjoiSnR3UXdNS1EVU9LSHpGVU1iWVhBQSIsInZlciIIjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCIeyJzdWIiOiJRN1ZWSVhFUTMzNlhsN2FFMXZDakNFWnRxeXJtZVZBX1BVb0VuMnZ0QU9zIn0sInhtc190Y2R0IjoxNjAxNTE5OTkzfQ.laUT8G0G3n3VVajxJjflHLOdM-E3iG7nl0Wi7fe8jt8CqCFXK1ckWWMpKbLRfc5ld3lPWZcGBYHh2MgiDmxnPcinn7kRQUofsjpnHVieXKTPcPh_AV380cvhoOoCydtkKAL8sny5V_XAeo_uIwaYYoi57UrNWddXrN3LDKA_EAHx2iPvyyoDrDeHCsQGdYxFzVNYqd0_0RzkyYUeBsMzLpx5O1sIXm9Lhl9XT1rSQAgiyeSmD1R4-hrlQjBq_AvTCScnl70B20hyEkucZL-hfe0UsHODWxpV0dPXMAt9lhUhN9okgHzRePDr7lfNnkrmpZCC8zmf2GR9EjlJfLEA (247 ms) 200
[2021-04-17T09:3:21.953Z] debug GET /connect/microsoft-v2/callback?access_token=eyJ0eXAiOiJKV1QiLCJub25jZSIImhNb2RvczIwMXF4ak5kZEZ1Tmp2NXJmcXd2RmVYN3VuV3d2QjZxczRueHMiLCJhbGciOiJSUzI1NiIsIng1dCIIm5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCIIm5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zMjI4YWY1YS02ZGI2LTRlM2EtYTZjNC0yY2FjNjhlOGQ4ZTIvIiwiaWF0IjoxNjE4NjUxODgxLCJuYmYiOjE2MTg2NTE4ODEsImV4cCIMTYxODY1NTc4MSwiYWNjdCIMCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXIcmVnaXN0ZXJzZWN1cml0eWluZm8iLCJ1cm4bWljcm9zb2Z0OnJlcTEiLCJ1cm4bWljcm9zb2Z0OnJlcTIiLCJ1cm4bWljcm9zb2Z0OnJlcTMiLCJjMSIsImMyIiwiYzMiLCJjNCIsImM1IiwiYzYiLCJjNyIsImM4IiwiYzkiLCJjMTAiLCJjMTEiLCJjMTIiLCJjMTMiLCJjMTQiLCJjMTUiLCJjMTYiLCJjMTciLCJjMTgiLCJjMTkiLCJjMjAiLCJjMjEiLCJjMjIiLCJjMjMiLCJjMjQiLCJjMjUiXSwiYWlvIjoiQVNRQTIvOFRBQUFBRVZObnVkYmlvT3NUMDdDbnA2ZmJKVXdaRXU0cEtWUW5PVjdIcHp0Si9Ncz0iLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSIInN0cmFwaSB0ZXN0IiwiYXBwaWQiOiJmYTE2NTg2OC1mZWQyLTRkN2ItODY0MS03ZTc2MmNlZjQzOGUiLCJhcHBpZGFjciIIjEiLCJmYW1pbHlfbmFtZSIInRlc3QiLCJnaXZlbl9uYW1lIjoidGVzdCIsImlkdHlwIjoidXNlciIsImlwYWRkciIIjEyMS4xMjIuMTExLjIzNCIsIm5hbWUiOiJzdHJhcGkiLCJvaWQiOiI5ZjQ3ZDIxMS0xZWI2LTRjNjYtODA4Mi0zMGEzZjFjMDlmNGMiLCJwbGF0ZiIIjUiLCJwdWlkIjoiMTAwMzIwMDExRDcyRkYwNCIsInJoIjoiMC5BWEVBV3E4b01yWnRPazZteEN5c2FPalk0bWhZRnZyU19udE5oa0YtZGldlE0NXhBTWsuIiwic2NwIjoiVXNlci5SZWFkIHByb2ZpbGUgb3BlbmlkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoid2tMNzdhODFGcFdqTTVjRF93MEZNU9OamR1QVZoY2VqdHByTWpIOVBSZyIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJBUyIsInRpZCIIjMyMjhhZjVhLTZkYjYtNGUzYS1hNmM0LTJjYWM2OGU4ZDhlMiIsInVuaXF1ZV9uYW1lIjoic3RyYXBpQGtlbnBoYW5nMTk5MWhvdG1haWwub25taWNyb3NvZnQuY29tIiwidXBuIjoic3RyYXBpQGtlbnBoYW5nMTk5MWhvdG1haWwub25taWNyb3NvZnQuY29tIiwidXRpIjoiSnR3UXdNS1EVU9LSHpGVU1iWVhBQSIsInZlciIIjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCIeyJzdWIiOiJRN1ZWSVhFUTMzNlhsN2FFMXZDakNFWnRxeXJtZVZBX1BVb0VuMnZ0QU9zIn0sInhtc190Y2R0IjoxNjAxNTE5OTkzfQ.laUT8G0G3n3VVajxJjflHLOdM-E3iG7nl0Wi7fe8jt8CqCFXK1ckWWMpKbLRfc5ld3lPWZcGBYHh2MgiDmxnPcinn7kRQUofsjpnHVieXKTPcPh_AV380cvhoOoCydtkKAL8sny5V_XAeo_uIwaYYoi57UrNWddXrN3LDKA_EAHx2iPvyyoDrDeHCsQGdYxFzVNYqd0_0RzkyYUeBsMzLpx5O1sIXm9Lhl9XT1rSQAgiyeSmD1R4-hrlQjBq_AvTCScnl70B20hyEkucZL-hfe0UsHODWxpV0dPXMAt9lhUhN9okgHzRePDr7lfNnkrmpZCC8zmf2GR9EjlJfLEA&raw%5Btoken_type%5D=Bearer&raw%5Bscope%5D=User.Read%20profile%20openid%20email&raw%5Bexpires_in%5D=3599&raw%5Bext_expires_in%5D=3599&raw%5Baccess_token%5D=eyJ0eXAiOiJKV1QiLCJub25jZSIImhNb2RvczIwMXF4ak5kZEZ1Tmp2NXJmcXd2RmVYN3VuV3d2QjZxczRueHMiLCJhbGciOiJSUzI1NiIsIng1dCIIm5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyIsImtpZCIIm5PbzNaRHJPRFhFSzFqS1doWHNsSFJfS1hFZyJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zMjI4YWY1YS02ZGI2LTRlM2EtYTZjNC0yY2FjNjhlOGQ4ZTIvIiwiaWF0IjoxNjE4NjUxODgxLCJuYmYiOjE2MTg2NTE4ODEsImV4cCIMTYxODY1NTc4MSwiYWNjdCIMCwiYWNyIjoiMSIsImFjcnMiOlsidXJuOnVzZXIcmVnaXN0ZXJzZWN1cml0eWluZm8iLCJ1cm4bWljcm9zb2Z0OnJlcTEiLCJ1cm4bWljcm9zb2Z0OnJlcTIiLCJ1cm4bWljcm9zb2Z0OnJlcTMiLCJjMSIsImMyIiwiYzMiLCJjNCIsImM1IiwiYzYiLCJjNyIsImM4IiwiYzkiLCJjMTAiLCJjMTEiLCJjMTIiLCJjMTMiLCJjMTQiLCJjMTUiLCJjMTYiLCJjMTciLCJjMTgiLCJjMTkiLCJjMjAiLCJjMjEiLCJjMjIiLCJjMjMiLCJjMjQiLCJjMjUiXSwiYWlvIjoiQVNRQTIvOFRBQUFBRVZObnVkYmlvT3NUMDdDbnA2ZmJKVXdaRXU0cEtWUW5PVjdIcHp0Si9Ncz0iLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSIInN0cmFwaSB0ZXN0IiwiYXBwaWQiOiJmYTE2NTg2OC1mZWQyLTRkN2ItODY0MS03ZTc2MmNlZjQzOGUiLCJhcHBpZGFjciIIjEiLCJmYW1pbHlfbmFtZSIInRlc3QiLCJnaXZlbl9uYW1lIjoidGVzdCIsImlkdHlwIjoidXNlciIsImlwYWRkciIIjEyMS4xMjIuMTExLjIzNCIsIm5hbWUiOiJzdHJhcGkiLCJvaWQiOiI5ZjQ3ZDIxMS0xZWI2LTRjNjYtODA4Mi0zMGEzZjFjMDlmNGMiLCJwbGF0ZiIIjUiLCJwdWlkIjoiMTAwMzIwMDExRDcyRkYwNCIsInJoIjoiMC5BWEVBV3E4b01yWnRPazZteEN5c2FPalk0bWhZRnZyU19udE5oa0YtZGldlE0NXhBTWsuIiwic2NwIjoiVXNlci5SZWFkIHByb2ZpbGUgb3BlbmlkIGVtYWlsIiwic2lnbmluX3N0YXRlIjpbImttc2kiXSwic3ViIjoid2tMNzdhODFGcFdqTTVjRF93MEZNU9OamR1QVZoY2VqdHByTWpIOVBSZyIsInRlbmFudF9yZWdpb25fc2NvcGUiOiJBUyIsInRpZCIIjMyMjhhZjVhLTZkYjYtNGUzYS1hNmM0LTJjYWM2OGU4ZDhlMiIsInVuaXF1ZV9uYW1lIjoic3RyYXBpQGtlbnBoYW5nMTk5MWhvdG1haWwub25taWNyb3NvZnQuY29tIiwidXBuIjoic3RyYXBpQGtlbnBoYW5nMTk5MWhvdG1haWwub25taWNyb3NvZnQuY29tIiwidXRpIjoiSnR3UXdNS1EVU9LSHpGVU1iWVhBQSIsInZlciIIjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCIeyJzdWIiOiJRN1ZWSVhFUTMzNlhsN2FFMXZDakNFWnRxeXJtZVZBX1BVb0VuMnZ0QU9zIn0sInhtc190Y2R0IjoxNjAxNTE5OTkzfQ.laUT8G0G3n3VVajxJjflHLOdM-E3iG7nl0Wi7fe8jt8CqCFXK1ckWWMpKbLRfc5ld3lPWZcGBYHh2MgiDmxnPcinn7kRQUofsjpnHVieXKTPcPh_AV380cvhoOoCydtkKAL8sny5V_XAeo_uIwaYYoi57UrNWddXrN3LDKA_EAHx2iPvyyoDrDeHCsQGdYxFzVNYqd0_0RzkyYUeBsMzLpx5O1sIXm9Lhl9XT1rSQAgiyeSmD1R4-hrlQjBq_AvTCScnl70B20hyEkucZL-hfe0UsHODWxpV0dPXMAt9lhUhN9okgHzRePDr7lfNnkrmpZCC8zmf2GR9EjlJfLEA (277 ms)
```

as u see, the callback after `auth/microsoft/callback` and redirect to the actual url we set in the settings page 
example: `/connect/microsoft-v2/callback` in the case,

the query params will sudden increase, have another look for the breakdown:
```
access_token, <--- actual need
raw%5Btoken_type%5D, <--- extra
raw%5Bscope%5D, <--- extra
raw%5Bexpires_in%5D, <--- extra
raw%5Bext_expires_in%5D, <--- extra
raw%5Baccess_token%5D <--- extra, basically it's duplicate
```

the reason i raise up this question, it's because azure app service is limit the request url length and this issues will exceed the limit

i try to modify the plugin but i really have no idea where the api attach this query params

**Comment by lordzpipo** [comment] 2021-04-18 03:28
@derrickmehaffy i found out the reason, this is because `grant-koa` default settings,
response will default include the raw data in the options, 
have a look [https://github.com/simov/grant#configuration-values](url).

i fix it by override this value in `extensions/users-permissions/controller/Auth.js`

```js
 // Ability to pass OAuth callback dynamically
    grantConfig[provider].callback = _.get(ctx, 'query.callback') || grantConfig[provider].callback;
    grantConfig[provider].redirect_uri = strapi.plugins[
      'users-permissions'
    ].services.providers.buildRedirectUri(provider);
    grantConfig[provider].response = ['tokens']; <---
```

**Comment by derrickmehaffy** [comment] 2021-04-27 18:15
@lordzpipo are you up for contributing a PR to resolve the issue for everyone?

**Comment by maxisam** [comment] 2021-05-21 04:45
Is this issue solved?

I am on 3.6.2 

After I login to Microsoft, it takes me back to strapi with access token, however, nothing happens after that.

https://strapi.xxxx.com/auth/microsoft/callback?access_token=eyJ0eXAiOiJKV1QiLC....

It shows 

{"jwt":"xxxxxxxxxxxxxxxx","user":{"id":1,"username":"xxxxx@xxxx.com","email":"xxx@xxxxx.com","provider":"microsoft","confirmed":true,"blocked":null,"role":{"id":1,"name":"Authenticated","description":"Default role given to authenticated user.","type":"authenticated"},"created_at":"2021-05-21T03:32:30.182Z","updated_at":"2021-05-21T03:32:30.196Z"}}

**Comment by derrickmehaffy** [comment] 2021-05-24 18:40
> Is this issue solved?
> 
> I am on 3.6.2
> 
> After I login to Microsoft, it takes me back to strapi with access token, however, nothing happens after that.
> 
> https://strapi.xxxx.com/auth/microsoft/callback?access_token=eyJ0eXAiOiJKV1QiLC....
> 
> It shows
> 
> {"jwt":"xxxxxxxxxxxxxxxx","user":{"id":1,"username":"[xxxxx@xxxx.com](mailto:xxxxx@xxxx.com)","email":"[xxx@xxxxx.com](mailto:xxx@xxxxx.com)","provider":"microsoft","confirmed":true,"blocked":null,"role":{"id":1,"name":"Authenticated","description":"Default role given to authenticated user.","type":"authenticated"},"created_at":"2021-05-21T03:32:30.182Z","updated_at":"2021-05-21T03:32:30.196Z"}}

No, we have not had time to open a PR and the author hasn't replied on their intent to open one.

**Comment by derrickmehaffy** [comment] 2022-01-05 21:58
Closing this in favor of https://github.com/strapi/strapi/issues/11337

**Closed by derrickmehaffy** 2022-01-05 21:58 UTC
Labels: issue-type: bug, status: pending reproduction
