### ISSUE TITLE
Image optimising removed EXIF-data

### ISSUE THREAD

**Issue by Froelund** [strapi/strapi#6868] opened 2020-06-30 17:04 UTC
**Describe the bug**

When uploading images, with the "Enable size optimization" enabled, the EXIF data is being removed. The consequence for us, is that the rotation flag is missing, and we do not have anyway to know in which rotation the image should be displayed.

**Steps to reproduce the behavior**

1. With the "Enable size optimization" enabled in `/admin/settings/media-library`.
2. Upload an image taken in portrait-mode.
3. Open the image from `/admin/plugins/upload`.

Now you'll see that the image is tilted 90 degrees.

1. Now with the "Enable size optimization" disabled in `/admin/settings/media-library`.
2. Upload an image taken in portrait-mode.
3. Open the image from `/admin/plugins/upload`.

Now you'll see that the image is upright, as expected.

**Expected behavior**

Image should "keep" it's meta-date. Sharp library has a feature for doing that called `withMetadata`.

**Screenshots**

![image](https://user-images.githubusercontent.com/2089088/86155182-58a9ae80-bb04-11ea-9fa2-67c153f1d641.png)

**System**

- Node.js version: v12.16.3
- NPM version: 6.14.4
- Strapi version: 3.0.2
- Database: Postgres
- Operating system: Ubuntu/OSx

**Comment by lauriejim** [comment] 2020-08-13 14:10
Hello! Thank you for reporting this issue, 
can you please give us a the file to reproduce the issue and be able to fix it.
Thank you :)

**Comment by Cr0s4k** [comment] 2020-08-31 12:00
This bug was already posted in https://github.com/strapi/strapi/issues/5996, fixed in https://github.com/strapi/strapi/pull/6768 and merged in https://github.com/strapi/strapi/releases/tag/v3.1.0 so I guess this issue can be closed!

**Comment by derrickmehaffy** [comment] 2020-08-31 13:37
Marking as closed as duplicate of #5996 let us know if this needs to be reopened for any reason

**Closed by derrickmehaffy** 2020-08-31 13:37 UTC
Labels: good first issue, priority: low, source: plugin:upload, type: bug

**Comment by Froelund** [comment] 2020-09-01 10:13
I assume that #6768 wouldn't fix the issue of loosing exif-data, as it doesn't use `sharp#withmetadata`.

I haven't tested it though.

https://sharp.pixelplumbing.com/api-output#withmetadata

**Comment by lutoma** [comment] 2021-03-13 19:03
@derrickmehaffy I don't think this issue is fixed at all. While the problem is gone for the one special case of rotation metadata, I don't believe it is acceptable behavior for Strapi to just throw away part of image files by default without warning or at least keeping a copy of the original. Especially since the wording for the setting makes no mention of that.

**Comment by derrickmehaffy** [comment] 2021-03-19 12:42
This issue has been mentioned on **Strapi Community Forum**. There might be relevant details there:

https://forum.strapi.io/t/image-upload-rotating-exif-param/3538/1

**Comment by Froelund** [comment] 2021-05-12 06:13
Fixed in v3.6.2 by PR #10161
