### ISSUE TITLE
REST queries in Strapi Admin are extremely slow, they always populate automatically all relations

### ISSUE THREAD

**Issue by cgonzalezsan** [strapi/strapi#8553] opened 2020-11-02 20:45 UTC
## Bug report

REST queries are extremely slow, most likely due to they populate all relations. It happens with the queries that Strapi admin makes when fetching the data of the collection types. It makes the app totally unusable, as 14 seconds for a collection type which has 8 records is absolutely unacceptable from a user perspective. 

## Describe the bug
I have experienced a drastic slow-down of MongoDB's performance. When fetching all data from a collection type (Article category which has 8 records) it will take ~14 seconds which is absolutely crazy. This collection type has a relation with Articles (~1200 records) which is what seems to be causing the speed issue, which still is crazy considering the amount of documents.

If I add "autoPopulate" : false to the model, the query will take milliseconds, but the problem is that in Strapi Admin, all related Articles will be empty.

This is a common issue I've had after having thousands (~7k) of records in my DB and has made the app unusable (one heavier query currently takes 20seconds)

### Steps to reproduce the behavior
In Strapi Admin, just going to the collection type `Article categories` which will make the below call

http://localhost:1337/content-manager/explorer/application::article-category.article-category?_limit=10&_sort=id%3AASC&_start=0

### Expected behavior

The query should take milliseconds

### Screenshots

<img width="1533" alt="Screenshot 2020-10-31 at 21 36 52" src="https://user-images.githubusercontent.com/6850051/97917000-1adbc180-1d54-11eb-9042-0c9e8411d983.png">

### Code snippets

article-category.settings.json
```
{
  "kind": "collectionType",
  "collectionName": "article_categories",
  "info": {
    "name": "Article Category"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "import_complete": {
      "default": false,
      "type": "boolean",
      "private": true
    },
    "name_en": {
      "type": "string"
    },
    "name_de": {
      "type": "string"
    },
    "description_en": {
      "type": "richtext"
    },
    "description_de": {
      "type": "richtext"
    },
    "pim_id": {
      "type": "string"
    },
    "pim_key": {
      "type": "string"
    },
    "channels": {
      "type": "json"
    },
    "article_subcategories": {
      "via": "article_category",
      "collection": "article-subcategory"
    },
    "slug": {
      "type": "uid",
      "targetField": "name_en"
    },
    "articles": {
      "via": "article_categories",
      "collection": "article"
    }
  }
}

```

### System

- Node.js version: 12.18.2
- NPM version:6.14.8
- Strapi version: 3.2.5
- Database: MongoDB
- Operating system: MacOS

**Comment by derrickmehaffy** [comment] 2020-11-02 20:53
@cgonzalezsan can you include a sample project and some data if possible so we can do some testing to reproduce this?

**Comment by cgonzalezsan** [comment] 2020-11-02 21:04
@derrickmehaffy if you mean setting `"autoPopulate" : false` in the model, it'll work in the list view but in the details view, the articles are coming up empty, which will be an issue for my client. See the below screenshot
<img width="1050" alt="Screenshot 2020-11-02 at 21 59 55" src="https://user-images.githubusercontent.com/6850051/97918749-e87f9380-1d56-11eb-9195-0a178777909e.png">

If no `autoPopulate` is set, articles will show up but the loading time will increase exponentially and makes the CMS unusable for my client.
<img width="1049" alt="Screenshot 2020-11-02 at 22 00 13" src="https://user-images.githubusercontent.com/6850051/97918760-eae1ed80-1d56-11eb-9218-e6862e76f922.png">

Is there anyway to set `autoPopulate` only for the listing view, and not the details view?

**Comment by derrickmehaffy** [comment] 2020-11-02 21:07
Not currently @cgonzalezsan the issue is with the internal API that the CTM (Content-Type manager) is using, specifically related to the query: 

https://github.com/strapi/strapi/blob/b19873ae8c99117436f402c904d280d43bac2e52/packages/strapi-plugin-content-manager/services/ContentManager.js#L25-L32

In the list view that `populate` should just be an empty array (until we add the new relational value in the list view feature at the end of the month).

And in the edit view, it shouldn't matter as the population there is going to happen regardless: 
https://github.com/strapi/strapi/blob/b19873ae8c99117436f402c904d280d43bac2e52/packages/strapi-plugin-content-manager/services/ContentManager.js#L34-L44

**Comment by cgonzalezsan** [comment] 2020-11-02 21:14
@derrickmehaffy as you can see from the screenshots, populate does matter, as if it's set to false, articles will come up empty in the Edit view (see first screenshot from my first comment). Is there any workaround for this?

Otherwise, would you consider having separate autoPopulate properties or maybe including it as a query string parameter?

```
"articles": {
      "via": "article_categories",
      "collection": "article",
      "autoPopulate": false
    }
```

**Comment by derrickmehaffy** [comment] 2020-11-02 22:01
I can't really provide any context as to work arounds at the moment, we will need to wait for the engineering team to take a look.

**Comment by aksdevac** [comment] 2020-11-04 05:20
Custom populate control is also needed in update queries: https://github.com/strapi/strapi/issues/7731, 
if model has 1200+ relational record like this then update query will also become slow & we can't use its return value to return updated data as API response directly (means without omitting relational entity manually). consider assigning priority to this issue as well.

**Comment by stafyniaksacha** [comment] 2021-03-04 19:34
Any update about this ? 
The only workaround that I found is to override all find controller !

**Comment by frosato-dev** [comment] 2021-05-12 12:21
I think that the relations are unnecessarily populated in [this file](https://github.com/strapi/strapi/blob/43b947b2ba2f153dd6056e0710d7dcd92fb9bc7c/packages/strapi-plugin-content-manager/controllers/relations.js)

Passing an empty array as a third param to prevent relation to populate solves this performance issue.
Would tou accept a PR @alexandrebodin ? 

cc: @cgonzalezsan 

https://github.com/strapi/strapi/blob/43b947b2ba2f153dd6056e0710d7dcd92fb9bc7c/packages/strapi-plugin-content-manager/controllers/relations.js#L45

 ```javascript
 entities = await entityManager.search(query, target.uid, []); 
 ```
 
 https://github.com/strapi/strapi/blob/43b947b2ba2f153dd6056e0710d7dcd92fb9bc7c/packages/strapi-plugin-content-manager/controllers/relations.js#L47
 
 ```javascript
 entities = await entityManager.find(query, target.uid, []);
 ```

**Comment by alexandrebodin** [comment] 2021-05-12 14:11
I think you are totally right. That is something we could accept in a PR if this doesn't create unintended issues :)

**Comment by raisolanoapps** [comment] 2021-11-22 05:24
@frosato-dev your solution without autoPopulate was right for me, thanks!

**Comment by yugdamor-git** [comment] 2022-02-10 04:00
total records in 1st collection : 25397
it has 3 relational fields,
each having more than 50K entries

and now when i use admin panel, it takes 7 second to load just one page, btw strapi version : 4.0.6

i tried rest api, it takes same time, i was going to use it in my website, but it turns out i wasted 3-4 days to just import data and then i got to know that any populate query with relational fields will take 7 second, and which is unacceptable.

guess what, now i am thinking to stay away from things that requires less time setup and we dont know whats going on in background,

i know strapi team may tried their best, but no one waits 7 second to just load the page,

it seems raw sql queries are faster and best, even if it takes time to set it up,  but it wont get slow,

and to me the reason behind this perfomance issue is the database design, 
i checked the database file and also checked all tables, whenever localization enabled, it create new table to store it,
and it always create many to many realationship

if you have 10 records that means localization table will have (10 * 10 entries - some duplicate entry)

i am not sure about actual issue,but to me it seems database schema. and how relational fields are stored.

**Comment by rktyt** [comment] 2022-02-18 14:39
I hope you'll make performance a priority.
Even with a not so large number of data, it is still slow.

Even version 4.0.8 is slow.

**Comment by kibblerz** [comment] 2022-03-04 15:16
Can this get some more attention? The performance of the admin is rather debilitating. It takes 10-15 seconds to load a content type with two relations (maximum of 50 records for each relation in my setup). 

I notice that when populating the relations,  the full records for the relations are returned also.  This is absolutely absurd since the query only needs the id, and possibly one other field for the display name of the relations. I saw this mentioned in other issues, but it was said to be resolved. Yet this doesn't seem to be the case.

One solution i read in previous versions is to disabled Auto populate. Yet this doesn't exist in v4. I'm a bit at a loss as to why content manager is pulling all of this data, when it only needs two fields at most from relational records

**Comment by alexandrebodin** [comment] 2022-03-08 09:07
Hello, We just merged a PR to fix this https://github.com/strapi/strapi/pull/12758. This will be published in the next release coming next week

**Comment by kibblerz** [comment] 2022-03-11 14:27
@alexandrebodin I installed the update and everything seems to be working great now! Great work!

**Comment by derrickmehaffy** [comment] 2022-03-14 22:57
Closing as fixed in https://github.com/strapi/strapi/pull/12758

**Closed by derrickmehaffy** 2022-03-14 22:57 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-manager
