### ISSUE TITLE
Graphql: Different schema body in query

### ISSUE THREAD

**Issue by hieuxinhe94** [strapi/strapi#11868] opened 2021-12-10 06:53 UTC
Hello, thank you for making an awesome project.

In strapi v4.
I found a different schema while making a query to strapi graphql: 
Why do we need specified data, attributes? 

`query events {
  events  {
    data {
      attributes {
        title
        description
      }
    }
  }
}`

![image](https://user-images.githubusercontent.com/19610013/145530995-1daeefc0-fe5a-4358-af6e-c9bc44d46af3.png)

That makes it very difficult to integrate with some other clients like  @apollo/client (nextjs, nuxtjs)
How can I simply query as

query events {
  events  {
        title
        description
  }
}

![image](https://user-images.githubusercontent.com/19610013/145537332-eda42174-1edc-43df-9c03-273f9b1b6612.png)

Please give me suggestions to work around.

**Comment by ScottAgirs** [comment] 2021-12-10 08:23
Duplicate https://github.com/strapi/strapi/issues/11649

**Comment by derrickmehaffy** [comment] 2021-12-10 19:45
Duplicate of https://github.com/strapi/strapi/issues/11649 closing

**Closed by derrickmehaffy** 2021-12-10 19:45 UTC
Labels: status: duplicate
