### ISSUE TITLE
Sort by more than two attributes

### ISSUE THREAD

**Issue by Nowhy** [strapi/strapi#2819] opened 2019-02-13 07:56 UTC
Informations

Node.js version: v10.13.0
NPM version: 6.4.1
Strapi version: " "^3.0.0-alpha.18"
Database: "mongoose": "5.3.16",
Operating system: Mac OSX 10.13.6
What is the current behavior?
how to sort by multiple columns? When I use the guide book, it is hard to find answers. Could it be possible for providing more examples on the website?   

Steps to reproduce the problem
I have many attributes in one model and I want to sort by A first and then sort by B. Even then sort by C. In addition, I need to use aggregation for this model. Thus, I edit  
 filters.sort = `A B ${filters.sort}`; when I got the url like http://thisisanexample.model?_sort=C

What is the expected behavior?
sort data by A first, B second, C finally.

Suggested solutions

**Comment by derrickmehaffy** [comment] 2019-02-13 08:02
I can confirm this on latest version, currently there is no "And" // "Or" options on the filters.

@lauriejim I think this is important, but not sure if it classifies as a Bug Report for Feature Request

**Comment by Nowhy** [comment] 2019-02-13 09:06
@derrickmehaffy now How can I deal with this problem?

**Comment by derrickmehaffy** [comment] 2019-02-13 09:10
@Nowhy right now there is no work around, you would have to modify the filter code and submit a PR.

**Comment by lauriejim** [comment] 2019-02-13 18:51
This is a new feature. 
To deal with it, you will have to manually update your API code.

**Comment by derrickmehaffy** [comment] 2019-02-13 18:53
@Aurelsicoko I 2nd this feature, while I don't have the skills to implement it in my own project, I feel this is a pretty important one.

**Comment by Aurelsicoko** [comment] 2019-02-21 09:26
@derrickmehaffy You might use the work done by @kamalbennani on GraphQL to allow this kind of sorting? Any thoughts?

**Comment by kamalbennani** [comment] 2019-02-23 21:27
@Aurelsicoko It can be implemented easily using the new Filter API, I spent around 1 hour to work on a POC and it seems to be working:
![screenshot 2019-02-23 at 12 13 31](https://user-images.githubusercontent.com/14129459/53285757-a9690480-3764-11e9-900c-e42e36e249cb.png)
You can define not only 1 but multiple sort pipelines :D

**Comment by derrickmehaffy** [comment] 2019-02-23 21:28
@kamalbennani you think this is also possible for the other filters? Basically a `and` / `or` system for filters?

**Comment by kamalbennani** [comment] 2019-02-23 21:39
I think that we're also able to sort by relational fields :O
![screenshot 2019-02-23 at 22 38 44](https://user-images.githubusercontent.com/14129459/53291971-da285880-37bb-11e9-8e38-b60022d30ca4.png)

**Comment by Aurelsicoko** [comment] 2019-02-28 12:25
It's only working on GraphQL for now, we should make sure that our query parameters can support this as well.

`GET /products?price_gte=3&_sort=name:DESC,price:ASC`?

**Comment by derrickmehaffy** [comment] 2019-02-28 12:44
@Aurelsicoko There are many ways to handle AND/OR on Rest but I think some of the best ways may require a pretty large change of how the filters are used (more in line with a typical REST API specification)

Some examples: https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/#

**Comment by scorpionking90** [comment] 2019-04-11 10:55
Any update on this. I am also waiting for this feature to be live. I have strong use case for this feature. Please provide any workaround other than graphql.

**Comment by derrickmehaffy** [comment] 2019-04-11 10:56
@scorpionking90 no update and there is no known workaround. If you are willing to work on it, you can submit a PR.

**Comment by scorpionking90** [comment] 2019-04-12 10:36
@derrickmehaffy I have made customization according to my use case using search query in api/services/Points.js.
expected: https://xxx/points?associate=25&created_at_gte=2019-04-01&created_at_lte=2019-04-08
changed: https://xxx/points?_q=2019-04-01%262019-04-08%2625

We should be changing our "strapi.utils.models.convertParams" as it is overriding same parameter values and make use of andWhere instead of orWhere according.

**Comment by Aurelsicoko** [comment] 2019-04-12 13:37
@alexandrebodin can you confirm that you added this feature in the latest release?

**Comment by alexandrebodin** [comment] 2019-04-12 15:27
You will be able to sort by multiple attributes in the next release (alpha-0.26). 

(e.g `created_at:desc,other:asc`)
No sorting on nested fields for now to avoid any confusion

**Comment by lauriejim** [comment] 2019-04-16 17:12
So we can close this issue.

**Closed by lauriejim** 2019-04-16 17:12 UTC
Labels: priority: low, type: feature request 🙏

**Comment by doublemarked** [comment] 2019-05-14 11:42
Despite the documentation and the comment from @alexandrebodin, this does not appear work in alpha-0.26.2. The [relevant code from strapi.utils.models.convertParams](https://github.com/strapi/strapi/blob/master/packages/strapi-utils/lib/models.js#L499-L501) hasn't been touched recently. Is supported only via GraphQL or something?

**Comment by ikesler-tenengroup** [comment] 2019-09-18 15:57
> You will be able to sort by multiple attributes in the next release (alpha-0.26).
> 
> (e.g `created_at:desc,other:asc`)
> No sorting on nested fields for now to avoid any confusion

@alexandrebodin do you have some updates about sorting on nested fields? Are there plans to support it?

**Comment by mbistuer** [comment] 2019-09-22 01:53
> I think that we're also able to sort by relational fields :O
> ![screenshot 2019-02-23 at 22 38 44](https://user-images.githubusercontent.com/14129459/53291971-da285880-37bb-11e9-8e38-b60022d30ca4.png)


how can i implement this in my project

**Comment by cpednekar** [comment] 2021-05-26 07:31
> 
> 
> > You will be able to sort by multiple attributes in the next release (alpha-0.26).
> > (e.g `created_at:desc,other:asc`)
> > No sorting on nested fields for now to avoid any confusion
> 
> @alexandrebodin do you have some updates about sorting on nested fields? Are there plans to support it?

this still isn't working on graphql.

this is my sort query part
"_sort" : "title:asc" (this works)

but following doesn't
"_sort" : "title:asc,amount:desc"

**Comment by derrickmehaffy** [comment] 2021-05-26 18:01
> > > You will be able to sort by multiple attributes in the next release (alpha-0.26).
> > > (e.g `created_at:desc,other:asc`)
> > > No sorting on nested fields for now to avoid any confusion
> > 
> > 
> > @alexandrebodin do you have some updates about sorting on nested fields? Are there plans to support it?
> 
> this still isn't working on graphql.
> 
> this is my sort query part
> "_sort" : "title:asc" (this works)
> 
> but following doesn't
> "_sort" : "title:asc,amount:desc"

for GraphQL you shouldn't use the `_` it's just `sort: "title:asc,amount:desc"`
