### ISSUE TITLE
Filtering nested objects returns `Cannot convert object to primitive value`

### ISSUE THREAD

**Issue by BroTrue** [strapi/strapi#1587] opened 2018-07-17 14:54 UTC
**Informations**
- **Node.js version**: v10.6.0
- **npm version**:  6.1.0
- **Strapi version**:  3.0.0-alpha.12.7.1
- **Database**: MongoDB
- **Operating system**: Debian 9

**What is the current behavior?**

Cant use `(where: {} )` in graphql. Returns : `"Cannot convert object to primitive value"`

**Steps to reproduce the problem**
1. Create new project `strapi new my-app`
2. Add 2x Content type : `page` and `product` 
3. Add for both of them  fields: 
-string - `title` 
-relation - many to many between them
4.  Open `http://localhost:1337/playground`
5. Type 
```
query{
  pages{
    title
    products(where:{title: "Test"}){
      title
    }
  }
}
```
6. Get on right box
```
{
  "data": {
    "pages": [
      {
        "title": "Main",
        "products": null
      }
    ]
  },
  "errors": [
    {
      "message": "Cannot convert object to primitive value",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "pages",
        0,
        "products"
      ]
    }
  ]
}
``` 

**What is the expected behavior?**

**Suggested solutions**

**It was working well at strapi  3.0.0-alpha.12.5**

**Comment by BroTrue** [comment] 2018-07-17 15:21
Models ( it was autogenereted)!

`api/page/models/Page.settings.json/

```
{
  "connection": "default",
  "collectionName": "page",
  "info": {
    "name": "page",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "title": {
      "type": "string"
    },
    "products": {
      "collection": "product",
      "via": "pages",
      "dominant": true
    }
  }
}
```

`api/product/models/Product.settings.json/`
```
{
  "connection": "default",
  "collectionName": "",
  "info": {
    "name": "product",
    "description": ""
  },
  "options": {
    "timestamps": true
  },
  "attributes": {
    "title": {
      "type": "string"
    },
    "pages": {
      "collection": "page",
      "via": "products"
    }
  }
}
```

**Comment by lauriejim** [comment] 2018-07-18 11:51
I think your issue is a duplicate of this one https://github.com/strapi/strapi/issues/1484
And you already publish on the issue. I think it's not necessary to open new issue.

**Closed** 2018-07-19 16:56 UTC
Labels: status: duplicate
