### ISSUE TITLE
afterCreate hook don't have media fields filled

### ISSUE THREAD

**Issue by MaksZhukov** [strapi/strapi#15804] opened 2023-02-13 13:09 UTC
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.6.0
- Database: MySql
- Operating system: Windows
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I have a collection A;
It has images field with type Media(Image);
When I create an Item for collection A via POST request with files(images)
I use `afterCreate` hook for my collection.
And when I try to get field images by `entityService.find(id, {populate: ['images]})` in the hooks the field is null.
But when I do setTimeout for a second with `entityService.find(id,{populate: ['images]})` I have the images field

### Steps to reproduce the behavior

1. Create a collection with media type
2. Add lifecycles file
3. Register afterCreateHook and put code of finding code of a field with type media type
5. Use post request to create an Item with media type field
7. See that field with media type is empty

### Expected behavior

media field should have items

### Screenshots

This is how it works with setTimeout
![image](https://user-images.githubusercontent.com/23615115/218467007-e3edf7e5-2f63-477e-bb51-eb2a7457ce5d.png)
![image](https://user-images.githubusercontent.com/23615115/218466541-42e69a0f-cbd7-4971-95ab-4ee025c44342.png)

**Comment by petersg83** [comment] 2023-02-14 13:19
Hello :)
The lifecycle just wraps the `create`, `update` etc. functions. So what params are entered and what result the function returns entirely depend on the original request. If nothing is populated, it's because the original request didn't populate it.
If you need to have data that is not already there, you will need to fetch the data on your side.

So I don't think we can consider that an issue as it is working the way it was intented.
What do you think?

**Comment by MaksZhukov** [comment] 2023-02-14 14:34
@petersg83 Hey! But as you can see I didn't use data(images) from afterCreate hook I did additional service call by myself inside the afterCreate hook, but the field images was null.

I can assume that afterCreate hook occurs before images were uploaded and i have the result in service call

**Comment by petersg83** [comment] 2023-02-15 09:40
You're right sorry! I read too quickly.
Indeed this is a bug. The code responsible for that is here: https://github.com/strapi/strapi/blob/main/packages/core/strapi/lib/services/entity-service/index.js#L154

**Comment by cmario92** [comment] 2023-02-22 19:46
hi, this should be critical - do we have any updates?
thanks

**Comment by derrickmehaffy** [comment] 2023-02-22 20:23
> hi, this should be critical - do we have any updates?
> thanks

It would not be critical no, we have very strong definitions of severity

**Comment by Marc-Roig** [comment] 2023-03-06 14:49
Hello,  are you uploading the file directly on the entity creation? https://docs.strapi.io/dev-docs/plugins/upload/#upload-files-at-entry-creation

If that is the case this will be difficult to implement.
![image](https://user-images.githubusercontent.com/20578351/223143762-4dc1a5f5-3fc6-4126-b855-699318657780.png)

We upload the images after creating the entity, and that is why probably it works when you use the setTimeOut.
Because at the point of where you are requesting it , the image is still not uploaded.

This would require to implement in Strapi, a way of creating an entity that's related on the `db.query.create` level, which currently is not possible.

I am afraid, that if this is the issue, the only workaround would be:
- using the webhook, which will have the data file
- using the setTimeout trick you mentioned.

**Comment by MaksZhukov** [comment] 2023-03-07 11:57
@Marc-Roig Hey! Yes directly.
But when I add population for image field for the post request it works. i get the images field in the afterCreate hook or using entity service.

**Comment by derrickmehaffy** [comment] 2023-04-05 15:45
This is a duplicate of: https://github.com/strapi/strapi/issues/16258

Short answer is it won't be possible in the model lifecycles, you would need to refetch the entity within the lifecycle using entity service and populate it again. Lifecycles sit too low level.

**Closed by derrickmehaffy** 2023-04-05 15:45 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:strapi
