### ISSUE TITLE
Insert image into Wysiwyg Editor in selected position

### ISSUE THREAD

**Issue by hanyuei** [strapi/strapi#978] opened 2018-04-20 07:23 UTC
Informations

Operating system:
Mac 10.12
Web Browser
Google Version 65

**What is the current behavior?**
insert image into Editor will append text to the end rather than append text in the selection place.

**Steps to reproduce the problem**
using  `click image button in the toolbar` or the `dragging & dropping, selecting` way

**What is the expected behavior?**
insert image markdown in the current selection place,
it's useful especially when the text is long.

**Comment by soupette** [comment] 2018-04-20 08:07
In order to prevent this bug you can paste an image into the selection.

**Comment by zhuang17** [comment] 2018-04-20 08:52
@soupette  `paste an image into the editor` work nearly the same on my side. (with an extra filename `xxx.png` will be append in the current selection place, )
but the markdown text `![text](http://localhost:1337/uploads/892ec69c7d45428d9d034050434cbf9a.png)` will be append to the end as well.


![1](https://user-images.githubusercontent.com/6997095/39041238-f91d15cc-44ba-11e8-87bc-0b3507d57d52.gif)

**Comment by soupette** [comment] 2018-04-20 09:26
@zhuang17 I see, I'm going to make a fix then

**Comment by zhuang17** [comment] 2018-04-20 09:46
@soupette  
thanks for your confirmation and quick response.
the editor is awesome, great work.

**Comment by amartincolby** [comment] 2019-10-17 17:47
Quite a long time later, I know, but I'm seeing behavior like this again in Beta 16.8.

**Comment by lauriejim** [comment] 2019-10-21 11:56
Ping @soupette about this issue.

**Comment by petersg83** [comment] 2020-08-04 09:51
I think this bug has been fixed since then. I can't reproduce the issue.
@soupette Can you confirm and close the issue please?

**Comment by soupette** [comment] 2020-08-04 10:14
@petersg83 the issue has not been fixed (yet)

**Comment by ngphong** [comment] 2021-09-22 09:52
I insert an image between Rich text. But after action, image appear in the end of text.I think my problem is the same with this bug. Can you resolve this issue please?

**Comment by ronronscelestes** [comment] 2022-12-28 10:33
hi!
tested today on 4.5.4 and I cannot reproduce this issue:

https://user-images.githubusercontent.com/71838159/209798608-615d922d-cca7-46b6-b1d2-9f872a6e87f7.mov

could one of you test it also and insert a video if you find any issue? 🙏

**Closed** 2023-01-14 00:11 UTC
Labels: issue: bug, severity: low, status: can not reproduce, source: core:content-manager
