### ISSUE TITLE
Create collection type - "s" finishing-words forbidden?

### ISSUE THREAD

**Issue by DocBouCou** [strapi/strapi#8646] opened 2020-11-13 10:46 UTC
### Describe the bug
If I try to create a new collection type containing the word "nous" (we or us in french), I cannot save (an error happens). 
~~To be clear : if i create a collection type called "test", I save it, it works (server restarts etc.) ;  but if I create a collection type called "test-nous", it does not save (I just re-test, re-try, it again).~~
So, the issue is not coming from a specific word, apparently you cannot create a content type called with a "s" finishing word. I just tried to create a "Home-section-trois" (Home-section-three, not the best of names I know...), and error. So, ok, the issue is maybe that the error message is not clear at all about that (I just see "une erreur est survenue" => "an error happened").

### Steps to reproduce the behavior

1. Go to plugin/content-type-builder/new collection type
2. Call it "nous", or "section-nous", or "home-nous", or "sectionNous"... I tried many different word combinations, in the end, if I'm not wrong, "nous" is the problem. ("nous" means "we" in French) => It seems the issue is due to the "s" at the end.
3. Add some field (in the end I just tested adding a text field named "a"), 
4. Save (or try to)

### Expected behavior

Well, I should be able to create my collection type, no matter its name. Or at least get a sensible error message (so I do not lost too much time on it...).

Apparently the "s" at the end is forbidden. Why not. But, I have not seen it in the docs (or I missed it). Second but: the error message should be explicit, sensible.

### System

- Node.js version: 12.19.0
- NPM version: 6.14.8
- Strapi version: 3.2.5
- Database: sql-lite (--quickstart)
- Operating system: ubuntu 18

**Comment by derrickmehaffy** [comment] 2020-11-16 18:52
Duplicate of: https://github.com/strapi/strapi/issues/1198

But thank you for the additional information!

**Closed by derrickmehaffy** 2020-11-16 18:52 UTC
Labels: status: duplicate

**Comment by DocBouCou** [comment] 2020-11-17 07:18
@derrickmehaffy Thank you for your answer. Is there some plans / thoughts / wills to make the error message more sensible in the admin panel?

**Comment by DocBouCou** [comment] 2020-11-17 07:42
@derrickmehaffy  I have read about the openCRUD convention, and I left [an issue there](https://github.com/opencrud/opencrud/issues/35). I can't help myself but think that this naming convention with plural english words is wrong/stupid (not your bad at strapi, I know). Concerning strapi, if we consider the admin dashboard might be used by everyone (thus including non-developpers and non-english-speakers), it is a real problem if we cannot name the collection types correctly for any language.

**Comment by derrickmehaffy** [comment] 2020-11-17 13:09
Totally agree and understand and it's something we are discussing internally right now about changing in the future v4.

**Comment by DocBouCou** [comment] 2020-11-17 16:24
Great news! Thank you for having taken the time to answer.
