### ISSUE TITLE
Unique fields must be localized error for Integer type field

### ISSUE THREAD

**Issue by Vigneshmuthusamy** [strapi/strapi#12436] opened 2022-02-08 16:59 UTC
### Describe the bug
While adding a new number field in content-type, I made the field unique since that field is supposed to be a phone number field for the user. But when I do that and save it, it throws below error
```Unique fields must be localized```
### Steps to reproduce the behavior

1. Go to 'Plugins -> Content-Type Builder'
2. Click on 'Add new field' under any collection type
3. Select Number field from the selection and make it unique
4. See an error ```Unique fields must be localized``` if localization is enabled

### Expected behavior

Number fields shouldn't have a localization option

### Screenshots

![image](https://user-images.githubusercontent.com/11820699/153036812-8e1dc2be-1950-4776-89ef-ae6257a53ec7.png)

### System

- Node.js version: v16
- NPM version: 8.1.2
- Strapi version: v4
- Database: sql-lite
- Operating system: Ubuntu

**Comment by petersg83** [comment] 2022-02-15 15:09
Is i18n activated for your content-type Maid ? Is it in purpose ?

It's a duplicate of :
https://github.com/strapi/strapi/issues/12248
https://github.com/strapi/strapi/issues/10107
https://github.com/strapi/strapi/issues/10169

@derrickmehaffy Do we close the issues and let only one open?
Also, should we change this one as a feature request like the others?

**Comment by Vigneshmuthusamy** [comment] 2022-02-15 16:09
@petersg83 Yes. i18n is activated for Maid content-type since some fields may have different content based on language. But integer field ideally shouldn't have this check since we can't translate integers.

**Comment by derrickmehaffy** [comment] 2022-02-15 16:11
Closing and locking in favor of the tracking issue: https://github.com/strapi/strapi/issues/12538

**Closed by derrickmehaffy** 2022-02-15 16:11 UTC
Labels: issue-type: bug, severity: medium, status: confirmed, source: core:content-type-builder, source: plugin:i18n
