### ISSUE TITLE
Media Library Bulk Delete Server Error

### ISSUE THREAD

**Issue by elena-rafailova** [strapi/strapi#14452] opened 2022-09-21 07:57 UTC
### Required System information
- Node.js version: 14.18.1
- NPM version: 6.14.15
- Strapi version: 4.3.0
- Database: MySQL
- Operating system: Linux

### Describe the bug
When I try to delete few assets from Media Library with the bulk delete functionality, assets are successfully deleted but server return Internal Server Error 500. No matter if assets are related to something or I just uploaded them.

Problem is that in admin-folder-file.js controller in the deleteMany method there is no check if deleteFolders is truthy, so when it is undefined ( when I haven't deleted any folders ) that is why I get the error. 

### Steps to reproduce the behavior

1. Go to 'Admin panel Media Library'
2. Upload 2 images
3. Then try to delete both of them

### Expected behavior

Return toast for success

### Code snippets
I added checks locally and it seems to work like that:

 if (deletedFiles? .length + deletedFolders? .length > 1) {
      strapi.telemetry.send("didBulkDeleteMediaLibraryElements" .....)
 }

ctx.body = {
    data: {
      files: **deletedFiles ?** await pmFile.sanitizeOutput(deletedFiles) : [],
      folders: **deletedFolders ?** await pmFolder.sanitizeOutput(deletedFolders) : [],
    },
};

**Comment by CleberRossi** [comment] 2022-10-08 16:42
Hello @elena-rafailova .

I could not reproduce the erro. I found that on 4.3.0 the folder feature was release. I looked for and seemed that it was already fixed by https://github.com/strapi/strapi/releases/tag/v4.3.2

https://github.com/strapi/strapi/pull/13871

Can you try with some new releases, please?

@derrickmehaffy I think this can be closed. Awaiting user to reply.

**Comment by derrickmehaffy** [comment] 2022-10-11 03:56
Sounds good, I'm mark it as closed for now but if the user still has a problem we can always reopen later.

**Closed by derrickmehaffy** 2022-10-11 03:56 UTC
