### ISSUE TITLE
Localization is broken for single types

### ISSUE THREAD

**Issue by magom001** [strapi/strapi#19805] opened 2024-03-17 16:44 UTC
### Required System information

- Node.js version:
- NPM version:
- Strapi version:
- Database:
- Operating system:
- Is your project Javascript or Typescript:

### Describe the bug

Unable to publish a single type entry for second locale.

### Steps to reproduce the behavior

Tried on version 4.20.5

1. Create a localized single type.
2. Create an entry in content manager in locale A, save and publish
3. Create an entry in content manager for locale B, save, try publish

Expected result: locale B is saved and published
Actual result: "Warning: Not Found"

After inspecting the DB I see that the second entry is saved under locale A instead of locale B

<img width="178" alt="Screenshot 2024-03-17 at 17 42 27" src="https://github.com/strapi/strapi/assets/2744275/7cbbb959-a688-43fb-8164-24262ea60e9c">

How to mitigate: manually change in the DB `A` to `B` - publishing works.

**Comment by marina-svdv** [comment] 2024-03-18 09:49
Yes, I have the same. it is a very annoying bug

**Comment by fatsecret-marketing** [comment] 2024-03-19 23:42
Same issue here. Need a fix asap, as this breaks the entire use of localization. Single types cannot be saved for a localized variant as it either saves nothing and gives a 'not found' error when attempting to Publish a localized single type. Despite it being 'saved' nothing is also saved for a localization for a single type.

**Comment by michaelnapl** [comment] 2024-03-19 23:44
Same issue here. Need a fix asap, as this breaks the entire use of localization. Single types cannot be saved for a localized variant as it either saves nothing and gives a 'not found' error when attempting to Publish a localized single type. Despite it being 'saved' nothing is also saved for a localization for a single type.

**Comment by dalvelab** [comment] 2024-03-20 09:54
Same for me. Can anybody give stable version where it is not broken?

**Comment by JeffDev1981** [comment] 2024-03-20 10:46
Same for me

**Comment by magom001** [comment] 2024-03-20 18:03
Probably not related but another issue:

1. Create a localized collection type and an unlocalized collection type
1. In the localized collection type reference the unlocalized collection type
1. Create some content

Try to query the localized collection items with populate=*

Expected result:
The referenced unlocalized collection data is present in the response

Actual result:
The data is missing

**Comment by mbarr1111** [comment] 2024-03-20 21:41
same here, broken, using latest versions, I get not found too

**Comment by hi-wildly** [comment] 2024-03-21 09:42
Why is this not fixed yet? Cant use the single types with the latest version

**Comment by mbarr1111** [comment] 2024-03-21 09:53
wonder which is an stable version , we are using 4.21.0, and we chosed this tool over others thinking was mature enough, but now we are strugling with errors like this one, which version do you recommend us? we are using also strapi cloud.

**Comment by tagperfect** [comment] 2024-03-21 16:55
4.21.0 meets this issue too... Any suggestions on how to get rid of it?

**Comment by mbarr1111** [comment] 2024-03-21 19:22
> 4.21.0 meets this issue too... Any suggestions on how to get rid of it?

I just started to use the collection type, seems to be more stable

**Comment by tagperfect** [comment] 2024-03-22 07:50
> > 4.21.0 meets this issue too... Any suggestions on how to get rid of it?
> 
> I just started to use the collection type, seems to be more stable

Collections seem to work fine, my issue was related to a single type. 

BTW. Got it working with the help of @magom001, and corrected the locale in DB.

**Comment by n-alonso** [comment] 2024-03-27 09:51
Internal TID 6307

**Comment by alexandrebodin** [comment] 2024-03-29 19:47
Hi, After trying multiple times I am unable to reproduce this issue on the latest (v4.21.1). I wish I was so I could fix it :/

- I created a single type 
- I enabled & disabled i18N multiple times
- I enabled & disabled i18n on different field multiple times. 

Can some of you test again on that version. I'm wondering if it might be data issue that I can't fix in the code 🤔

**Comment by michaelnapl** [comment] 2024-04-03 02:28
@alexandrebodin Just updated to Strapi 4.21.1. I'm not getting any errors anymore, even on saving a localized single type, however it's not saving any data. It saves the default language fine, however setting the localized variants, hitting save, gives a success message, but going back into the locale shows no data (empty record).

**Comment by alexandrebodin** [comment] 2024-04-03 08:35
Thanks for the extra context, Sadly from a new project I can't reproduce any of those issues. 

My current conclusion is that there was a bug that created inconsistency in the db and that even updating the code looks for the wrong info in db or is missing links in the xxx_localizations table. 

If someone is willing to share their project & anonymized data with me it would help a lot to get reproduction and see how we can fix it for existing apps in this state.

**Comment by Annoiiyed** [comment] 2024-04-03 12:42
Fixed in #19799 :)

**Closed** 2024-04-03 13:05 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: plugin:i18n, version: 4

**Comment by alexandrebodin** [comment] 2024-04-03 13:08
that's what happens when you test already fixed code. gg @Marc-Roig
