### ISSUE TITLE
[V4] CTB - Browser confirmation displayed when adding a new field in a CT

### ISSUE THREAD

**Issue by sam-pires** [strapi/strapi#11201] opened 2021-10-05 19:31 UTC
### Describe the bug
Hello

When creating a new CT in the CTB, after I name the first field and want to add another field I get a confirmation popup from Chrome
The confirmation indicates that my current work can be lost, which is not correct, the popup can be annoying in the flow I believe, but most importantly it's not the correct type of message as the work is not lost :) 

It also happens when I want to close the CTB modal while creating the CT (this might be normal though)

### Steps to reproduce the behavior

1. Go to the CTB
2. Create a new CTB
3. Fill in the fileds for the first field
4. Click on Add another field -> See the popup

### Expected behavior

No popup or a different kind with the right message

### Screenshots
<img width="453" alt="Capture d’écran 2021-10-05 à 21 22 24" src="https://user-images.githubusercontent.com/25405887/136089200-b3d5adf6-a780-44fb-bedd-122d017eb8c4.png">

<img width="1439" alt="Capture d’écran 2021-10-05 à 21 32 25" src="https://user-images.githubusercontent.com/25405887/136090665-659f8386-a3d5-4382-b623-d163a81342a6.png">

[Loom](https://www.loom.com/share/bb2385cef4b14298857b0464686ecc7a) but we don't see the popup, check the comments to see when it appears

### System

- Node.js version: 12.8.1
- NPM version: 6.10.3
- Strapi version: v4 beta2
- Database: The quickstart one
- Operating system: MacOS

**Comment by derrickmehaffy** [comment] 2021-10-05 19:38
Confirmed on beta.2

**Comment by sam-pires** [comment] 2021-10-05 19:39
haha you're too fast @derrickmehaffy 🔥 

I hope you are doing well 🙂

**Comment by derrickmehaffy** [comment] 2021-10-05 19:40
> haha you're too fast @derrickmehaffy fire
> 
> I hope you are doing well slightly_smiling_face

Very well, I hope the same for you Sam

**Comment by sam-pires** [comment] 2021-10-05 19:44
I do as well, I miss the team 🙂

**Comment by sam-pires** [comment] 2021-10-05 19:45
Talking about the bug, it also happens when clicking on "Finish"
And if I click on cancel in the popup, the field is added anyway

**Comment by derrickmehaffy** [comment] 2021-10-05 19:46
Yeah it has something to do with the v3 popup menu with the v4 page. We rushed a bit on the DS for the CTB to get a very early version of the beta out for testing. I'm guessing the frontend engineers will solve it once this finish porting that popup menu to the new DS.

**Comment by derrickmehaffy** [comment] 2021-10-05 19:46
(I just got back from 2 week vacation so I'm not completely up to date on the DS migration so far)

**Comment by rowild** [comment] 2021-10-06 18:11
Just wanted to open a new issue about that, then I saw that the problem is already posted. However, I made a little video that demonstrates the popup problem. Maybe it is of some use.

https://user-images.githubusercontent.com/213803/136259556-550f0fc1-d1d3-4db8-8c6d-827e03266d5f.mp4

**Comment by derrickmehaffy** [comment] 2021-11-05 22:19
Fixed in one of the beta releases (don't remember which)

**Closed by derrickmehaffy** 2021-11-05 22:19 UTC
Labels: type: bug, severity: low, status: confirmed, source: plugin:content-type-builder, version: v4-Alpha/Beta
