### ISSUE TITLE
Timeout — Http requests from Strapi to another Strapi

### ISSUE THREAD

**Issue by Illuday** [strapi/strapi#7216] opened 2020-07-27 17:36 UTC
**Describe the bug**
Strapi webhooks and Axios get timeout when trying to reach another online Strapi.

**Steps to reproduce the behavior**

1. Create two online Strapi (A & B)
2. Try to reach A endpoint from B webhook
3. See the timeout

**System**

- Node.js version: 14.5.0
- NPM version: 6.14.5
- Strapi version: 3.0.5
- Database: Mongo
- Operating system: Debian 10

**Additional context**
Postman can reach my endpoint. Stripe webhooks also. There is only webhooks (axios, http request..) from another Strapi (I try from two), that can't.

**Comment by lauriejim** [comment] 2020-07-27 19:16
Hello! Do you have any cors issue?
Because with information we have here it will be hard to know :/

**Comment by Illuday** [comment] 2020-07-27 19:21
Hi!
I've no cors issues. After some research, I think this isn't related to Strapi. It's seems to be a http request issue, when two domains are on the same IP (It's a hypothesis).

My two strapies are on 2 proxmox containers and they can't communicate between each others with http requests. However, every things are working well beyond that.

**Comment by derrickmehaffy** [comment] 2020-07-28 02:10
> Hi!
> I've no cors issues. After some research, I think this isn't related to Strapi. It's seems to be a http request issue, when two domains are on the same IP (It's a hypothesis).
> 
> My two strapies are on 2 proxmox containers and they can't communicate between each others with http requests. However, every things are working well beyond that.

Yeah this sounds like a networking issue within proxmox, going to mark this as closed as we won't be able to reproduce this.

**Closed by derrickmehaffy** 2020-07-28 02:10 UTC
Labels: type: help wanted
