### ISSUE TITLE
Blank page after upgrade to 4.10.4

### ISSUE THREAD

**Issue by smoothdvd** [strapi/strapi#16684] opened 2023-05-11 05:42 UTC
### Required System information

- Node.js version: 18.16.0
- NPM version:
- Strapi version: 4.10.4
- Database: PostgreSQL
- Operating system: macOS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Blank page after upgrade to 4.10.4

### Steps to reproduce the behavior

Upgrade from 4.10.2 to 4.10.4

### Expected behavior

Show admin page normal

### Screenshots

```
pnpm develop --watch-admin
```
<img width="1423" alt="Screenshot 2023-05-11 at 1 39 44 PM" src="https://github.com/strapi/strapi/assets/22420/afd60a97-cb08-4a72-8e50-56bbc4e58407">
<img width="1440" alt="Screenshot 2023-05-11 at 1 39 17 PM" src="https://github.com/strapi/strapi/assets/22420/c6e5d43a-287c-49ed-9e4e-0f7fb9aaf0bd">

```
pnpm develop
```
<img width="541" alt="Screenshot 2023-05-11 at 1 39 04 PM" src="https://github.com/strapi/strapi/assets/22420/c291c164-0c92-4fc5-b549-f9f4549093f8">

**Comment by Torsten85** [comment] 2023-05-11 08:14
Same error here... it happens way too often that a patch level update breaks everything for us.

**Comment by joshuaellis** [comment] 2023-05-11 09:15
Sorry to hear you're both having issues – I appreciate how this can be frustrating.

For the record, we don't officially support `pnpm` (referring to the original issue). Those error messages i'm sorry to say are impossible to help us figure this out, if you can add `webpack.config.js` to `src/admin` with this:

```js
module.exports = (config, webpack) => {
  // Note: we provide webpack above so you should not `require` it
  // Perform customizations to webpack config
  // Important: return the modified config
  config.devtool = 'source-map';
  return config;
};
```

I believe you'll get sourcemaps which would help debug this issue to see if there's a bug with the code or it's a pnpm issue 🤔

**Comment by smoothdvd** [comment] 2023-05-11 09:26
After enable source map, I get this warn from command line:
```
WARNING in ../../node_modules/.pnpm/react-router-dom@5.3.4_react@17.0.2/node_modules/react-router/esm/react-router.js 438:18-38
export 'default' (imported as 'pathToRegexp') was not found in 'path-to-regexp' (possible exports: compile, match, parse, pathToRegexp, regexpToFunction, tokensToFunction, tokensToRegexp)
 @ ../../node_modules/.pnpm/react-router-dom@5.3.4_react@17.0.2/node_modules/react-router-dom/esm/react-router-dom.js 1:0-66 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 34:44-50 79:44-50 178:42-66 261:42-66 268:30-39
 @ ./.cache/admin/src/StrapiApp.js 4:0-49 394:45-58
 @ ./.cache/admin/src/index.js 45:26-48:3

WARNING in ../../node_modules/.pnpm/react-router-dom@5.3.4_react@17.0.2/node_modules/react-router/esm/react-router.js 525:15-27
export 'default' (imported as 'pathToRegexp') was not found in 'path-to-regexp' (possible exports: compile, match, parse, pathToRegexp, regexpToFunction, tokensToFunction, tokensToRegexp)
 @ ../../node_modules/.pnpm/react-router-dom@5.3.4_react@17.0.2/node_modules/react-router-dom/esm/react-router-dom.js 1:0-66 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 2:0-187 34:44-50 79:44-50 178:42-66 261:42-66 268:30-39
 @ ./.cache/admin/src/StrapiApp.js 4:0-49 394:45-58
 @ ./.cache/admin/src/index.js 45:26-48:3

webpack 5.82.1 compiled with 2 warnings in 12888 ms
```

**Comment by joshuaellis** [comment] 2023-05-11 09:30
Yeah i think this is down to the fact we don't support `pnpm` because of our `cache` folder that we create on the fly 🤔 so this seems to be related to #15992.

**Comment by smoothdvd** [comment] 2023-05-15 02:32
@joshuaellis I find a correct way to resolve this problem: using pnpm's packageExtensions https://pnpm.io/package_json#pnpmpackageextensions

In this issue, you can do like this in package.json

```
{
  ...
  "pnpm": {
    "packageExtensions": {
      "react-router": {
        "dependencies": {
          "path-to-regexp": "^1.7.0"
        }
      }
    }
  },
  ...
}
```

**Comment by joshuaellis** [comment] 2023-06-28 15:21
This is almost a duplicate of #15992 so i'm going to close this

**Closed by joshuaellis** 2023-06-28 15:21 UTC
Labels: issue: bug, severity: low, source: tooling, status: will not fix
