### ISSUE TITLE
White screen of dead dynamic zones

### ISSUE THREAD

**Issue by Boegie19** [strapi/strapi#16602] opened 2023-05-03 11:23 UTC
### Required System information

Environment: development
OS: win32-x64
Strapi Version: 4.10.1
Node/Yarn Version: yarn/1.22.19 npm/? node/v18.9.1 win32 x64
Edition: Community
Database: sqlite
- Is your project Javascript or Typescript: Javascript

### Describe the bug

White screen of dead

### Steps to reproduce the behavior

1. Create fresh strapi instance
2. create content-type
3 add dynamic zone
4 name it and press ` add components to the zone`
4 create a category
5 switch to `Use an existing component`
6 switch back to `Create a new component`
7 Get the white screen of dead 

### Expected behavior

For the screen not to turn white

### Screenshots

![](https://i.gyazo.com/d91d8fe15ca12a807bc7af55a40a3e7b.gif)

### Additional context
in.841e0dcb.js:768 TypeError: Cannot read properties of undefined (reading 'props')
    at Pe (6404.68405699.chunk.js:16:2197)
    at S (6404.68405699.chunk.js:16:4480)
    at nc (main.841e0dcb.js:766:54222)
    at On (main.841e0dcb.js:770:9048)
    at bf (main.841e0dcb.js:770:985)
    at Ql (main.841e0dcb.js:770:913)
    at bl (main.841e0dcb.js:770:767)
    at kf (main.841e0dcb.js:768:10914)
    at main.841e0dcb.js:766:39167
    at E.unstable_runWithPriority (main.841e0dcb.js:805:3975)
Vl @ main.841e0dcb.js:768
main.841e0dcb.js:766 Uncaught TypeError: Cannot read properties of undefined (reading 'props')
    at Pe (6404.68405699.chunk.js:16:2197)
    at S (6404.68405699.chunk.js:16:4480)
    at nc (main.841e0dcb.js:766:54222)
    at On (main.841e0dcb.js:770:9048)
    at bf (main.841e0dcb.js:770:985)
    at Ql (main.841e0dcb.js:770:913)
    at bl (main.841e0dcb.js:770:767)
    at kf (main.841e0dcb.js:768:10914)
    at main.841e0dcb.js:766:39167
    at E.unstable_runWithPriority (main.841e0dcb.js:805:3975)

**Comment by AshishBarvaliya** [comment] 2023-05-31 04:00
@joshuaellis @Boegie19 Unable to reproduce the bug; it appears to have been resolved as part of a different issue.

**Comment by Boegie19** [comment] 2023-05-31 09:56
Thanks for checking and tagging me I will do a double check later today and if you are correct I will close it.

**Comment by alexandrebodin** [comment] 2023-07-12 14:55
I couldn't reproduce today so I'll close it :) don't hesitate to ping us if this comes back

**Closed by alexandrebodin** 2023-07-12 14:55 UTC
Labels: issue: bug, severity: low, status: confirmed, source: core:content-type-builder
