### ISSUE TITLE
Unable to view complete name of uploaded assets

### ISSUE THREAD

**Issue by msaeed99** [strapi/strapi#9242] opened 2021-01-27 23:40 UTC
When asset name is very large, the full not name is not displayable, there is no way to find the name other than clicking on the asset itself to see the name. This cause an issue when when we have a lot of assets with the same name.

1. Go to Strapi Admin
2. Click on Media Library
3. Click on Upload asset
4. Upload multiple assets with very large names.
3. View uploaded assets
4. They are all having the same initial names

Expected behavior:
Full name of the asset to be displayed

Screenshots:
![image](https://user-images.githubusercontent.com/71661406/106068583-df834000-6154-11eb-97f6-3fb9009dba98.png)

Code snippets: N\A

System

- Node.js version: v12.18.4
- NPM version: v12.18.4
- Strapi version: v3.4.0
- Database: AWS\RDS Postgres
- Operating system: Ubuntu 20.04.1 LTS

Additional context: N\A

**Comment by derrickmehaffy** [comment] 2021-01-28 00:08
@sam-pires / @maevalienard If you don't mind, wanted to get clarification if this is considered a bug or if it should be tagged as a feature request / enhancement.

**Comment by maevalienard** [comment] 2021-01-28 09:01
Derrick: not a bug, this is the way we handle most of the texts in the admin panel. It can be tagged feature request / enhancement, we'll try to find a solution for that asap :) 

@msaeed99: would a tooltip on hover help meanwhile we find a solution for this problem? :)

**Comment by msaeed99** [comment] 2021-01-28 13:51
Thanks, A tooltip will be helpful to our team.

**Comment by maevalienard** [comment] 2021-01-28 15:09
I'll see with the team how we can handle that quickly then, thanks for your issue :)

**Comment by derrickmehaffy** [comment] 2022-03-24 21:17
currently fixed in v4, marking as closed

**Closed by derrickmehaffy** 2022-03-24 21:17 UTC
Labels: issue: enhancement, issue: feature request
