### ISSUE TITLE
[Admin UI - Content Manager - Duplicate Item] Relations not populated in the duplicated item after Strapi upgrade

### ISSUE THREAD

**Issue by geeky-biz** [strapi/strapi#15184] opened 2022-12-15 05:17 UTC
**Required System information**

Node.js version: 16.13.0
NPM/YARN version: NA/1.22.19
Strapi version: 4.5.2
Database: PostgreSQL 14.6
Operating system: macOS Ventura 13.0

**Describe the bug**
After upgrading from 4.2.0 to 4.5.2 - the following issue is observed:
- From the Admin UI => content manager => any collection type
- When we click the icon to 'Duplicate' an existing record
- If this record has certain fields of type "relation" (oneToMany, manyToOne, manyToMany - any of these) - the duplicated item does not populate the values for these relation fields that the original record had.
- When we try duplicating the exact same record for the same collection with Strapi 4.2.0 - it does populate the same relation fields in the duplicated item.
- I suspect this change must have happened from 4.5.0 onwards when the way relation fields are displayed & loaded on the Admin UI has changed.
 
**Expected Behavior**
- The duplicated record should also populate the values for relation fields like it used to earlier.

**Additional Context**
We heavily use the 'Duplicate' Admin UI feature and our content types contain multiple relation fields. With this bug - we cannot duplicate items.

**Comment by Eventyret** [comment] 2022-12-15 06:44
Does it work without the duplicate button?
Because if so might want to rase it with the plugin author.

https://github.com/lautr/strapi-plugin-duplicate-button

**Comment by geeky-biz** [comment] 2022-12-15 08:56
When I stated the icon to duplicate an existing record - I meant clicking the icon shown in this screenshot on the Content Manager list view - 

<img width="606" alt="image" src="https://user-images.githubusercontent.com/17068206/207815771-615becbb-a3f3-48bd-983f-605a94033943.png">

**Comment by joshuaellis** [comment] 2022-12-15 13:58
This is a duplicate of #15093, i would monitor that issue :)

**Closed by joshuaellis** 2022-12-15 13:58 UTC
