### ISSUE TITLE
CustomError: No Rows Updated - We are using multiple pods for STRAPI CMS and while starting multiple pods at the same time, some of our pods are getting crashed with the above error.

### ISSUE THREAD

**Issue by rahul3103** [strapi/strapi#10837] opened 2021-08-31 11:56 UTC
The following issue we are getting on prod build, which is crashing our pods.

```
Loading environment variables
{"time_taken_ms": 74.37896728515625}
Starting services
yarn run v1.22.4
$ strapi start
[2021-08-31T11:34:35.796Z] error bootstrap function in admin failed
[2021-08-31T11:34:35.797Z] error CustomError: No Rows Updated
    at Child.<anonymous> (/web-scms/node_modules/bookshelf/lib/model.js:1182:25)
    at Child.tryCatcher (/web-scms/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/web-scms/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/web-scms/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/web-scms/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/web-scms/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/web-scms/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/web-scms/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/web-scms/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/web-scms/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```

Starting services
yarn run v1.22.4
$ strapi start
[2021-09-01T05:48:53.723Z] error bootstrap function in admin failed
[2021-09-01T05:48:53.724Z] error Error: entry.notFound
    at deleteOne (/web-scms/node_modules/strapi-connector-bookshelf/lib/queries.js:162:19)
    at async /web-scms/node_modules/p-map/index.js:57:22
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### System

- Node.js version: v12.18.1
- NPM version:  v6.14.10
- Strapi version: 3.6.6
- Database: postgres
- Operating system: linux

**Comment by rahul3103** [comment] 2021-08-31 11:57
@derrickmehaffy Can you help?

**Comment by rahul3103** [comment] 2021-09-01 13:23
@derrickmehaffy This happened when we upgraded from 3.5.1 to 3.6.6. So after setting strapi_permission table column properties={}. It worked for us.

**Comment by rahul3103** [comment] 2021-09-01 13:34
https://git.forum.ircam.fr/Guillaume.Pellerin/speak-web-backend/-/issues/10 @derrickmehaffy Someone also had this issue

**Comment by rahul3103** [comment] 2021-09-01 15:39
@derrickmehaffy We are using multiple pods for STRAPI CMS and while starting multiple pods at the same time, some of our pods are getting crashed with the above error.

**Comment by MattieBelt** [comment] 2021-09-01 19:05
@rahul3103, does this only happen when they are started at the same time?
I think it has something to do with the registration and syncing of admin roles & permissions.

https://github.com/strapi/strapi/blob/8972d78e8d1783ded6089d0318bfb62aff8e6962/packages/strapi-admin/config/functions/bootstrap.js#L41-L60

This is execute on startup and maybe due to doing it multiple times at the same time the table gets locked and trows this error but not sure entirely. 

Can you still elaborate a bit more on how this could be reproduce, which service are you using to deploy multiple pods for example? 

Also did you have an look at this issue already?
#10423

**Comment by wintercounter** [comment] 2021-10-05 08:14
For me this is happening in the following scenario:

- Using Strapi in Docker, and I have multiple cron scripts to sync my contents, all with a 60 second interval.
- Sync is invoked as `node cron/syncFoo.js`
- The file is loading Strapi as `const Strapi = require('strapi')`
- Using Ofelia to run cron jobs inside the container.
- 2 of 3 scripts are failing with the above error, because they will run in parallel.

So you can easily repro this by creating 3 files let's say, all requiring Strapi and running them at the same time from crontab.

**Comment by vaunus** [comment] 2021-12-09 13:00
We are seeing exactly the same issue here when multiple Strapi instances start at the same time. As @MattieBelt says it definitely looks like some kind of database concurrency problem. 

Could this be solved by making the permissions bootstrap transactional maybe? 

Alternatively, I wondering if this would be solved in v4 at all given the data layer looks like it has been significantly changed. If anyone knows please let us know as this is a major blocker at the moment and we are an enterprise customer.

**Comment by derrickmehaffy** [comment] 2021-12-10 03:20
> We are seeing exactly the same issue here when multiple Strapi instances start at the same time. As @MattieBelt says it definitely looks like some kind of database concurrency problem.
> 
> Could this be solved by making the permissions bootstrap transactional maybe?
> 
> Alternatively, I wondering if this would be solved in v4 at all given the data layer looks like it has been significantly changed. If anyone knows please let us know as this is a major blocker at the moment and we are an enterprise customer.

It's due to the autoMigration stuff that happens on boot, you basically need one "primary" node that starts first to handle checking the DB and all the others should have it disabled. Both of the v3 and v4 docs under database has the config option on how to disable the auto migration.

I'm marking this as closed as there is nothing to be fixed.

**Closed by derrickmehaffy** 2021-12-10 03:20 UTC
Labels: status: can't reproduce, status: won't fix

**Comment by wintercounter** [comment] 2021-12-10 11:58
So how we should deal with this when we technically don't run multiple
instances, but we use require('strapi') in custom scripts? Same problem
happenes. Should we just use an env variable and set process.env before
every script run?

**Comment by derrickmehaffy** [comment] 2021-12-10 19:01
> So how we should deal with this when we technically don't run multiple instances, but we use require('strapi') in custom scripts? Same problem happenes. Should we just use an env variable and set process.env before every script run?


yes pretty much, using env vars

**Comment by vaunus** [comment] 2022-01-13 16:20
> It's due to the autoMigration stuff that happens on boot, you basically need one "primary" node that starts first to handle checking the DB and all the others should have it disabled. Both of the v3 and v4 docs under database has the config option on how to disable the auto migration.
> 
> I'm marking this as closed as there is nothing to be fixed.

@derrickmehaffy I have disabled autoMigration under the database options and I'm afraid it has made no difference. My config looks like this:
```
// config/database.js

module.exports = ({ env }) => ({
  defaultConnection: 'default',
  connections: {
    default: {
      connector: 'bookshelf',
      settings: {
        client: 'mysql',
        host: env('DATABASE_HOST'),
        port: env.int('DATABASE_PORT'),
        database: env('DATABASE_NAME'),
        username: env('DATABASE_USERNAME'),
        password: env('DATABASE_PASSWORD'),
        ssl: env.bool('DATABASE_SSL')
      },
      options: {
        debug: true,
        autoMigration: false
      }
    }
  }
})
```

Some output from our nodes:

**Node 1**:
```
2022-01-13T14:47:08.734Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, null, null, 346 ], __knexQueryUid: 'SSG-zsiQOEEWxcEngdf-a', sql: 'update `users-permissions_permission` set `role` = ?, `created_by` = ?, `updated_by` = ? where `id` = ?' }
2022-01-13T14:47:08.734Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, null, null, 347 ], __knexQueryUid: 'xN4ABAWuA_gL6-HWf3tqJ', sql: 'update `users-permissions_permission` set `role` = ?, `created_by` = ?, `updated_by` = ? where `id` = ?' }
2022-01-13T14:47:08.735Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, null, null, 348 ], __knexQueryUid: 'eC5k2bFXZSLNCEc9T7Tx4', sql: 'update `users-permissions_permission` set `role` = ?, `created_by` = ?, `updated_by` = ? where `id` = ?' }
2022-01-13T14:47:08.735Z INFO { method: 'select', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ 330, 1 ], __knexQueryUid: 'RTzPe5G54CIJytGVIPpY3', sql: 'select `users-permissions_permission`.* from `users-permissions_permission` where `users-permissions_permission`.`id` = ? limit ?' }

[2022-01-13T14:47:08.741Z] error bootstrap function in plugin "users-permissions" failed
[2022-01-13T14:47:08.742Z] error CustomError: No Rows Updated
    at Child.<anonymous> (/var/task/node_modules/bookshelf/lib/model.js:1182:25)
    at Child.<anonymous> (/var/task/node_modules/bookshelf/lib/model.js:1162:14)
    at Child.<anonymous> (/var/task/node_modules/bookshelf/lib/model.js:1162:14)
    at processImmediate (internal/timers.js:464:21)
    at Child.<anonymous> (/var/task/node_modules/bookshelf/lib/model.js:1060:10)
    at Function.update [as updateRelations] (/var/task/node_modules/strapi-connector-bookshelf/lib/relations.js:374:10)
    at async deleteOne (/var/task/node_modules/strapi-connector-bookshelf/lib/queries.js:167:5)
    at async /var/task/node_modules/p-map/index.js:57:22
```

**Node 2**:
```
2022-01-13T14:47:08.681Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, null, null, 342 ], __knexQueryUid: 'QOsaSQJiA_-M7sgHsc2vb', sql: 'update `users-permissions_permission` set `role` = ?, `created_by` = ?, `updated_by` = ? where `id` = ?' }
2022-01-13T14:47:08.682Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, null, null, 340 ], __knexQueryUid: 'D9rYP_WwNNZ5v20TfK9ma', sql: 'update `users-permissions_permission` set `role` = ?, `created_by` = ?, `updated_by` = ? where `id` = ?' }
2022-01-13T14:47:08.682Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, null, null, 336 ], __knexQueryUid: 'SWVv520O4jMh_jy7cgskx', sql: 'update `users-permissions_permission` set `role` = ?, `created_by` = ?, `updated_by` = ? where `id` = ?' }
2022-01-13T14:47:08.713Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, null, null, 335 ], __knexQueryUid: 'pkN0pDJJN1o3NGiYoTaX1', sql: 'update `users-permissions_permission` set `role` = ?, `created_by` = ?, `updated_by` = ? where `id` = ?' }

[2022-01-13T14:47:08.716Z] error bootstrap function in plugin "users-permissions" failed
[2022-01-13T14:47:08.717Z] error CustomError: No Rows Updated
    at Child.<anonymous> (/var/task/node_modules/bookshelf/lib/model.js:1182:25)
    at Child.<anonymous> (/var/task/node_modules/bookshelf/lib/model.js:1162:14)
    at processImmediate (internal/timers.js:464:21)
    at Child.<anonymous> (/var/task/node_modules/bookshelf/lib/model.js:1060:10)
    at Function.update [as updateRelations] (/var/task/node_modules/strapi-connector-bookshelf/lib/relations.js:374:10)
    at async deleteOne (/var/task/node_modules/strapi-connector-bookshelf/lib/queries.js:167:5)
    at async /var/task/node_modules/p-map/index.js:57:22
```

The above 2 nodes seem to be both be trying to concurrently update the `users-permissions_permission` table. A brief look at the code and I can see some deletes and updates happening on records here which I presume is why there is an issue.


**Node 3**:
```
2022-01-13T14:47:10.021Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, 2022-01-13T14:47:10.019Z, 1864 ], __knexQueryUid: 'bRzMnHJ5sozcqBe-R93It', sql: 'update `strapi_permission` set `role` = ?, `updated_at` = ? where `id` = ?' }
2022-01-13T14:47:10.022Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, 2022-01-13T14:47:10.019Z, 1865 ], __knexQueryUid: 'cZAgsDWq-LqoyS7zRSSjP', sql: 'update `strapi_permission` set `role` = ?, `updated_at` = ? where `id` = ?' }
2022-01-13T14:47:10.023Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, 2022-01-13T14:47:10.020Z, 1862 ], __knexQueryUid: 'OpW7a5yk9B7pmWp-c_ylU', sql: 'update `strapi_permission` set `role` = ?, `updated_at` = ? where `id` = ?' }
2022-01-13T14:47:10.039Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, 2022-01-13T14:47:10.020Z, 1863 ], __knexQueryUid: 'EBVuROcm_nfksV0QrltMn', sql: 'update `strapi_permission` set `role` = ?, `updated_at` = ? where `id` = ?' }

[2022-01-13T14:47:10.060Z] error bootstrap function in admin failed
[2022-01-13T14:47:10.061Z] error CustomError: No Rows Updated
    at Child.<anonymous> (/var/task/node_modules/bookshelf/lib/model.js:1182:25)
    at Child.<anonymous> (/var/task/node_modules/bookshelf/lib/model.js:1162:14)
    at processImmediate (internal/timers.js:464:21)
    at Child.<anonymous> (/var/task/node_modules/bookshelf/lib/model.js:1060:10)
    at Function.update [as updateRelations] (/var/task/node_modules/strapi-connector-bookshelf/lib/relations.js:374:10)
    at async deleteOne (/var/task/node_modules/strapi-connector-bookshelf/lib/queries.js:167:5)
    at async /var/task/node_modules/p-map/index.js:57:22
```

**Node 4**:
```
2022-01-13T14:47:10.035Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, 2022-01-13T14:47:10.016Z, 1868 ], __knexQueryUid: 'RX9TAw_b1x4zor43CYajR', sql: 'update `strapi_permission` set `role` = ?, `updated_at` = ? where `id` = ?' }
2022-01-13T14:47:10.036Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, 2022-01-13T14:47:10.016Z, 1863 ], __knexQueryUid: 'ImD1lqSiYZEddIXH_UEm3', sql: 'update `strapi_permission` set `role` = ?, `updated_at` = ? where `id` = ?' }
2022-01-13T14:47:10.036Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, 2022-01-13T14:47:10.017Z, 74 ], __knexQueryUid: 'KxcWmaeJXMXxSBXdSK6Ne', sql: 'update `strapi_permission` set `role` = ?, `updated_at` = ? where `id` = ?' }
2022-01-13T14:47:10.037Z INFO { method: 'update', options: {}, timeout: false, cancelOnTimeout: false, bindings: [ null, 2022-01-13T14:47:10.017Z, 75 ], __knexQueryUid: '16EenJ7BsIlGyKFue5Gkf', sql: 'update `strapi_permission` set `role` = ?, `updated_at` = ? where `id` = ?' }

[2022-01-13T14:47:10.055Z] error bootstrap function in admin failed
[2022-01-13T14:47:10.055Z] error CustomError: No Rows Updated
    at Child.<anonymous> (/var/task/node_modules/bookshelf/lib/model.js:1182:25)
    at Child.<anonymous> (/var/task/node_modules/bookshelf/lib/model.js:1162:14)
    at processImmediate (internal/timers.js:464:21)
    at Child.<anonymous> (/var/task/node_modules/bookshelf/lib/model.js:1060:10)
    at Function.update [as updateRelations] (/var/task/node_modules/strapi-connector-bookshelf/lib/relations.js:374:10)
    at async deleteOne (/var/task/node_modules/strapi-connector-bookshelf/lib/queries.js:167:5)
    at async /var/task/node_modules/p-map/index.js:57:22
```

Node 3 and 4 start a few seconds later and have a similar issue, but this time on the `strapi_permission` table.

If you have any ideas on this let me know, otherwise I will have to implement some kind of locking mechanism myself to ensure servers start properly as they are fine once they come online.

**Comment by derrickmehaffy** [comment] 2022-01-13 22:25
Can you take a full log dump and throw it on something like paste.ee and drop the link here, or if you want to make sure there is no private info in it PM me on Discord: `DMehaffy@1337`

**Comment by vaunus** [comment] 2022-01-14 14:26
@derrickmehaffy I've just added you on Discord.

**Comment by derrickmehaffy** [comment] 2022-01-18 22:43
I just noticed something, this is on Strapi v3, I don't believe this issue should be reproducible on v4 but we aren't fixing issues on v3 unless they are security related or considered critical (by our definition of critical).

Even if we could reproduce this on v4 (which I can't) we won't backport a fix to v3

**Comment by derrickmehaffy** [comment] 2022-01-18 22:45
But I can tell based on this log that the autoMigration setting isn't applied since it's still looking at the core_store and trying to do updates or the core_store is empty when it's booting and those keys are needed.

**Comment by wintercounter** [comment] 2022-01-18 23:17
So the real solution is to use v4 but there's still no migration guide/script released. This is starting to piss off a lot of people, including me. We're sitting on shitton of bugs and hacks which v4 is supposedly fixing, but everywhere the answer is: "we can't reproduce this in v4". Thanks! Sorry, I'm frustrated!

**Comment by derrickmehaffy** [comment] 2022-01-18 23:22
> So the real solution is to use v4 but there's still no migration guide/script released. This is starting to piss off a lot of people, including me. We're sitting on shitton of bugs and hacks which v4 is supposedly fixing, but everywhere the answer is: "we can't reproduce this in v4". Thanks! Sorry, I'm frustrated!

I know trust me you aren't the only one frustrated. We are working on the migration guide as fast as possible.
I will share the feedback with the team though.

**Comment by vaunus** [comment] 2022-01-19 08:29
I would also like to echo the frustration here. If you say v4 is the solution, then we are now also waiting for this migration guide.

**Comment by derrickmehaffy** [comment] 2022-01-19 19:48
> I would also like to echo the frustration here. If you say v4 is the solution, then we are now also waiting for this migration guide.

It is being worked on as we speak. In the meantime I would suggest validating that the autoMigration config is being taken into account during your deployment as the logs shared with me privately indicated that it was not.

Likewise in the meantime, a single node booted first should stop the issue of multiple nodes trying to make updates and falling into a race condition. Those failures and warnings though shouldn't stop the application from booting regardless.
