### ISSUE TITLE
Possible to create users with duplicate usernames via google provider

### ISSUE THREAD

**Issue by smoatymsl** [strapi/strapi#14122] opened 2022-08-17 15:46 UTC
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Strapi version: 4.3.4
- Database: Postgres
- Operating system: Linux

### Describe the bug

I have both local and google providers configured in strapi and a test next.js app configured with next-auth using strapi as the backend.
In next auth I have the google and credentials provider enabled. I am able to login/out and all works as expected with one small issue.

If a user exists in strapi already with a username for example  "john", and another user logs in via the google provider with a username of "john" then an account is created/provisioned in strapi (expected) but with a duplicated username (unexpected). 

This results in two users with the same username.

### Steps to reproduce the behavior

1. Enable the google provider
2. First create a local account with same username as a google account but different email address
3. login with google provider in client app
4. Open content-manager in admin and note the new user with a username that is already taken in another row.

### Expected behavior

I would expect the username created in strapi to be adjusted somehow so it's unique in the instance. john1 or john5 whatever until not taken or account creation to fail with some warning (the first would be better).
 
Adding a username to strapi in the content manager checks for uniqueness and prevents duplicates, this would make user provisioning via providers behave the same way as it does when creating a local user account.

**Comment by derrickmehaffy** [comment] 2022-08-17 18:34
I'm going to close this one as a duplicate of https://github.com/strapi/strapi/issues/8807

**Closed by derrickmehaffy** 2022-08-17 18:35 UTC
Labels: status: duplicate
