### ISSUE TITLE
Floats and decimals are rounded to 3 decimals in content manager table

### ISSUE THREAD

**Issue by oscarsandberg** [strapi/strapi#11893] opened 2021-12-13 20:44 UTC
### Describe the bug

UI bug in content manager table. If there are entries with the content type number(float or decimal) and the value contains more than 3 decimals, the value will be rounded to 3 decimals.

### Steps to reproduce the behavior

1. Add a new number field
2. Set to float (ex: 3.33333333) or decimal (ex: 2.22)
3. Go to content editor and add a floating point number (example, lat/long) or decimal with more than 3 decimals.
4. Save.
5. The value in the table is rounded to 3 decimals

### Expected behavior

The value should not be rounded to 3 decimals, if there are more decimals in the value.

### Screenshots

<img width="681" alt="1" src="https://user-images.githubusercontent.com/46453769/145885722-c266ed15-1272-4b01-b7c9-81729b2ffb70.png">

<img width="879" alt="2" src="https://user-images.githubusercontent.com/46453769/145885746-7ceefa90-4c79-4f97-8f3c-a70e89eba643.png">

### System

- Node.js version: v16
- NPM version: 6.14.15
- Strapi version: v4
- Database: sqllite (from quickstart)
- Operating system: Mac

**Comment by ejgonzalez17** [comment] 2021-12-22 19:12
Hi, I would like to take this issue to start contributing to your project.

**Comment by oscarsandberg** [comment] 2021-12-22 20:17
> Hi, I would like to take this issue to start contributing to your project.
> 
> 

Hi, there is already a PR for this bug and it should be in the history of this issue. However, I don't know if anyone has reviewed it.

**Comment by ejgonzalez17** [comment] 2021-12-22 21:09
ohh okay, I will look for another issue to work on, thanks for the prompt reply!

**Comment by petersg83** [comment] 2022-01-18 09:47
@HichamELBSI Is this issue fixed by https://github.com/strapi/strapi/pull/11890 ?

**Comment by petersg83** [comment] 2022-01-18 09:50
Is this a duplicate of https://github.com/strapi/strapi/issues/11821 ?

**Comment by HichamELBSI** [comment] 2022-01-18 10:08
> @HichamELBSI Is this issue fixed by #11890 ?

@petersg83 Yes, this issue is fixed 👍🏽 

> Is this a duplicate of #11821 ?

It is not a duplicate

**Comment by petersg83** [comment] 2022-01-18 10:10
Thanks :)

**Closed by petersg83** 2022-01-18 10:10 UTC
Labels: issue-type: bug, severity: low, status: confirmed, source: core:content-manager
