### ISSUE TITLE
The UI Elements in the Media Library Screen are hard to click on. 

### ISSUE THREAD

**Issue by selected-pixel-jameson** [strapi/strapi#13043] opened 2022-04-01 16:47 UTC
It's often times hard to actually click on the selectable elements within this interface. When checking the selection box or clicking on the edit button you have to make sure the cursor turns to the hand icon, which is not always where you would think you need to click. For example the edit button requires that you click almost exactly on the pencil icon and not the button as a whole. 

![Screen Shot 2022-04-01 at 11 39 06 AM](https://user-images.githubusercontent.com/28204537/161306904-a3bd7635-9ba9-4276-a3ad-1a789aafb02e.png)

- Node.js version: 14
- NPM version: 6
- Strapi version: 4.1.7
- Database: Postgres
- Operating system: MacOS 
- Browser: Brave

**Comment by selected-pixel-jameson** [comment] 2022-04-11 13:00
Just an update... for some reason I can't click on the icon at all now. I haven't changed or updated anything. I'm using Strapi 4.1.7.  I've rebuilt the admin and deleted cached files.

**Comment by derrickmehaffy** [comment] 2022-04-11 17:11
@selected-pixel-jameson normally I would close issues for not following our bug report template, but since @gu-stav already assigned it to the content squad's project I'll leave it open however can you please edit your post to at least provide some of the required system information?

Thanks

**Comment by selected-pixel-jameson** [comment] 2022-04-11 17:19
@derrickmehaffy Updated. Sorry about that.

**Comment by derrickmehaffy** [comment] 2022-04-11 17:33
> @derrickmehaffy Updated. Sorry about that. 

Np problem, thank you! 🤗

**Comment by joshuaellis** [comment] 2022-09-15 13:17
Hey @selected-pixel-jameson I've been looking at this one for you & I'm unable to reproduce on the latest version of Strapi. Can you test with the latest version? If it's still not working it'd be helpful if you could fill this template in:

---

### Steps to reproduce the behavior

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

---

**Comment by selected-pixel-jameson** [comment] 2022-09-15 13:26
@joshuaellis This issue seems to have resolved itself. I'm not sure what the function of the three little dots in the lower right corner is. I still cannot click on that element, but I'm not sure what it's purpose is so that might be working as intended.

**Comment by joshuaellis** [comment] 2022-09-15 13:57
> I'm not sure what the function of the three little dots in the lower right corner is

That should show you the length of your video (see screenshot). 

<img width="353" alt="CleanShot 2022-09-15 at 14 56 23@2x" src="https://user-images.githubusercontent.com/37798644/190422905-2cf392fc-af65-4cf8-8157-97b80d92f369.png">

Thanks for confirming so quickly! We can revisit if the issue reappears.

**Closed by joshuaellis** 2022-09-15 13:57 UTC
Labels: issue: bug, severity: medium, source: core:content-manager, source: core:upload, status: pending reproduction

**Comment by selected-pixel-jameson** [comment] 2022-09-15 14:47
Ah, that is a separate issue that I have yet to resolve then. The images and the  the videos don't actually load in the media library. I'm referencing them through a CDN and I believe there is some security settings that needs to be adjusted.
