### ISSUE TITLE
MS SQL support

### ISSUE THREAD

**Issue by umuttuncer** [strapi/strapi#2341] opened 2018-11-20 12:29 UTC
**Informations**
- **Node.js version**: 10.13.0
- **npm version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: Azure MsSQL
- **Operating system**: WSL and Ubuntu

**What is the current behavior?**
In this database.json:
```json
"mssql-test": {
  "connector": "strapi-hook-bookshelf",
  "settings": {
    "client": "mssql",
    "host": "my_host",
    "username": "my_username",
    "password": "my_password",
    "options": {
      "port": 1443,
      "database": "my_database",
      "encrypt": true
    }
  }
}
```

It gives an error

```
{ TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Timeout._onTimeout project_folder/node_modules/knex/lib/client.js:287:18)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
From previous event:
    at Client_MSSQL.acquireConnection (project_folder/node_modules/knex/lib/client.js:280:12)
    at **/node_modules/knex/lib/runner.js:208:30
From previous event:
    at **/node_modules/knex/lib/runner.js:206:35
From previous event:
    at Runner.ensureConnection (project_folder/node_modules/knex/lib/runner.js:205:34)
    at Runner.run (project_folder/node_modules/knex/lib/runner.js:51:42)
    at Builder.Target.then (project_folder/node_modules/knex/lib/interface.js:35:43)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23) sql: undefined, bindings: undefined }
```
If i changed database.json to:
```json
"mssql-test": {
  "connector": "strapi-hook-bookshelf",
  "settings": {
    "client": "mssql",
    "host": "***",
    "port": 1443,
    "database": "***",
    "username": "***",
    "password": "***"
  },
  "options": {
    "ssl": true
  }
}
```
Gives an error:
```
debug ⛔️ Server wasn't able to start properly.
error (hook:bookshelf) takes too long to load
(hook:bookshelf) takes too long to load
```
If i remove options ssl or encrypt parameter from database.json like:
```json
"mssql-test": {
  "connector": "strapi-hook-bookshelf",
  "settings": {
    "client": "mssql",
    "host": "my_host",
    "port": 1443,
    "database": "my_database",
    "username": "my_username",
    "password": "my_password"
  }
}
```
then returns this error:
```
{ ConnectionError: Failed to connect to my_host.database.windows.net:1443 in 15000ms
    at Connection.<anonymous> (project_folder/node_modules/mssql/lib/tedious.js:378:25)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Connection.EventEmitter.emit (domain.js:442:20)
    at Connection.connectTimeout (project_folder/node_modules/tedious/lib/connection.js:467:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
From previous event:
    at Client_MSSQL.acquireRawConnection (project_folder/node_modules/knex/lib/dialects/mssql/index.js:134:12)
    at Object.create (project_folder/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (project_folder/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool.dispense [as _dispense] (project_folder/node_modules/generic-pool/lib/generic-pool.js:314:10)
    at Pool.acquire (project_folder/node_modules/generic-pool/lib/generic-pool.js:436:8)
    at project_folder/node_modules/knex/lib/client.js:289:19
From previous event:
    at Client_MSSQL.acquireConnection (project_folder/node_modules/knex/lib/client.js:280:12)
    at project_folder/node_modules/knex/lib/runner.js:208:30
From previous event:
    at project_folder/node_modules/knex/lib/runner.js:206:35
From previous event:
    at Runner.ensureConnection (project_folder/node_modules/knex/lib/runner.js:205:34)
    at Runner.run (project_folder/node_modules/knex/lib/runner.js:51:42)
    at Builder.Target.then (project_folder/node_modules/knex/lib/interface.js:35:43)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:121:23)
  name: 'ConnectionError',
  message:
   'Failed to connect to my_host.database.windows.net:1443 in 15000ms',
  code: 'ETIMEOUT' }
```
How can i pass encrypt argument? What is the right way?

**Comment by lauriejim** [comment] 2018-11-20 13:44
Can you please well format your JSON and error.
It's just not readable.

**Comment by umuttuncer** [comment] 2018-11-21 10:41
> Can you please well format your JSON and error.
> It's just not readable.

I formatted my jsons and errors.

**Comment by MMayla** [comment] 2018-12-01 18:47
I have same problem

**Comment by wemod123** [comment] 2018-12-04 04:38
Hi guys, this issue was specifically related to Azure mssql, it was caused by the field "encrypt", which was mandatory if you want connected to.

I got the same issue, I solve it with some temporary solutions, by change some node_modules.

The solution step is:
1. Modify the` ...config/envirunments/.../database.json ` setting, add ` "encrypt": true`
```
    "mssql": {
      "connector": "strapi-hook-bookshelf",
      "settings": {
        "client": "mssql",
        "user": "your user get from mssql, like: username@db",
        "password": "***",
        "host": "you db host",
        "database": "you db",
       "encrypt": true
     }
   }
```
2. `npm install mssql@3.3.0`, it have to be specifically use the version 3.3.0, otherwise you will get error with latest mssql version.

3. Modify the `.../node_modules/strapi-hook-knex/lib/index.js`, (the strapi-hook-bookshelf depends on this  and knex etc...):
Near line #-100 add below line:
`options: {encrypt:_.get(connection.settings, 'encrypt') || '',}`
Just ensure you add a options inside default options.
So finally you will have the options like below to pass into knex:
```

 
       {
        "client": "mssql",
        "user": "your user get from mssql, like: username@db",
        "password": "***",
        "host": "you db host",
        "database": "you db",
        "options":{
            "encrypt": true
        }
     }
   
```
**: you can not get this by just specify it in database.json, since the strapi-hook-knex will re-organize all options.


Now you should able to connect to your db.
That's all for this topic.

Some additional issue: 
After you connected to mssql,  one more issue is the model ***id*** field: it ***cannot*** be created by strapi automatically, I dont know why, it was a bug for mssql?
So you have to handle it in the `.../api/model/models/Model.js` , to manually add the model id before create any itmes, in `beforeCreate `function.

***Further more:***
Hello Strapi teams, it's just simple to add one line code in the strapi-hood-knex, and give a sample JSON database configuration in document, to enable Azure mssql connection.
Will you do that in next release?

**Comment by derrickmehaffy** [comment] 2018-12-04 04:41
@wemod123 you can submit a PR for testing with your changes.

**Comment by derrickmehaffy** [comment] 2018-12-04 04:42
@umuttuncer 
```
    "client": "mssql",
```

Until changes are made to the bookshelf plugin Microsoft SQL is not supported. You are welcome to submit a PR to add in support for MSSQL

**Comment by wemod123** [comment] 2018-12-04 04:57
@derrickmehaffy

aha, I see, since bookshelf is made with Knex, and Knex support ssql officially, see [their website](https://knexjs.org/)
![image](https://user-images.githubusercontent.com/26819270/49419797-70537080-f7c3-11e8-9529-2e9c350a18e5.png)


Then I just think strapi automatically should support ssql.

Good features to support "mssql".

@umuttuncer, you are welcome to submit a PR

**Comment by derrickmehaffy** [comment] 2018-12-04 05:10
@wemod123 I'm fully aware that knex supports it, however bookshelf itself does not officially support it

https://bookshelfjs.org/

![image](https://user-images.githubusercontent.com/8593673/49420250-cedb0900-f747-11e8-8442-ee70b9c4bc25.png)

Strapi won't "automatically" support it as advanced testing needs to be worked on, and right now adding in another database is not a primary concern of the Strapi team, they are focused on a stable release and plugin framework rewrites for 3rd party plugins. If other members of the community wish to create PRs and properly test not only the MSSQL parts but all other databases to ensure there is no additional bugs, and/or loss of performance/features with other databases then by all means please do.

The Strapi team is very small, and do not have time to dedicate to each and every feature request within a short amount of time, they are quite busy and rely on the community to also help them with building and adding new features.

**Comment by derrickmehaffy** [comment] 2018-12-04 05:12
this is also not the first time that MSSQL has been suggested:

https://github.com/strapi/strapi/issues/1890
https://github.com/strapi/strapi/issues/1462
https://github.com/strapi/strapi/issues/855

**Comment by kktam** [comment] 2019-06-20 00:39
There are lots of small to midsize companies and corporations that uses MS SQL server or SQL Azure. The feature will enable a large audience who currently has a MS SQL installation, especially for companies between 1000 to 20000 employee. Please consider making this a high priority.

Here are some of the statistics:

[https://enlyft.com/tech/products/microsoft-sql-server](https://enlyft.com/tech/products/microsoft-sql-server)

[https://www.infoclutch.com/installed-base/dbms/microsoft-sql-server/](https://www.infoclutch.com/installed-base/dbms/microsoft-sql-server/)

**Comment by derrickmehaffy** [comment] 2019-06-20 04:18
@kktam it's been mentioned before that if someone in the community wants this by all means submit a PR. :)

**Comment by jon64digital** [comment] 2019-12-16 14:13
I just found Strapi today and I can't use it because of lack of MSSQL support. I'm kind of surprised that less popular databases ares upoorted out of the box but not MSSQL, specifically Azure SQL.

**Comment by derrickmehaffy** [comment] 2019-12-16 14:32
As stated before @jon64digital if someone in the community wanted to create a PR to add it by all means. Bookshelf and knex technically support MS-SQL but whoever is making the PR would need to make sure any type mappings that don't match MySQL are statically defined.

Same for relations. Strapi focused on the OSS databases and MS-SQL is not open source.

**Comment by lauriejim** [comment] 2019-12-20 13:28
I close this issue.
This is not something we will work on.
So I'm closing this topic.

**Closed by lauriejim** 2019-12-20 13:28 UTC
Labels: priority: low, type: feature request 🙏

**Comment by pmcfernandes** [comment] 2020-04-13 14:20
In my opinion mssql is not needed because you can use webhooks to replicate data to a webservice or to another database types. I use sqlite3 and webhooks to integrate with other services.
