### ISSUE TITLE
[V4] Media Library netowrk error

### ISSUE THREAD

**Issue by tw1t611** [strapi/strapi#11699] opened 2021-11-28 17:13 UTC
### Describe the bug

When uploading many files at once (600 in my case), some uploads error out with a 502 server error.
While something like this happened on strapi v3 too, I had the possibility to press the upload button again to upload the the remaining files.
Furthermore, when uploading over 1000 files, the page goes blank and the upload stops altogether. 
I am not using a plugin.

### Steps to reproduce the behavior

1. Upload many files at once
4. See  error

### Expected behavior

1. Files get uploaded regardless of the amount
2. UI never blanks out on upload.
3. When a upload failed, It should be possible to try the upload again pressing the button.

### System

- Node.js version: v14.15.3
- NPM version: 7.17.0
- Strapi version: "4.0.0-beta.17
- Database: postgres 14
- Operating system:  fedora

### Additional context

package.json
```
{
  "name": "strapi",
  "private": true,
  "version": "0.1.0",
  "description": "A Strapi application",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {
    "pg-connection-string": "^2.5.0"
  },
  "dependencies": {
    "@strapi/plugin-graphql": "4.0.0-beta.17",
    "@strapi/plugin-i18n": "4.0.0-beta.17",
    "@strapi/plugin-users-permissions": "4.0.0-beta.17",
    "@strapi/strapi": "4.0.0-beta.17",
    "pg": "^8.7.1"
  },
  "author": {
    "name": "A Strapi developer"
  },
  "strapi": {
    "uuid": "d6e21050-b511-4fc7-b221-b0d22952984e"
  },
  "engines": {
    "node": ">=12.x.x <=16.x.x",
    "npm": ">=6.0.0"
  },
  "license": "MIT"
}
```

**Comment by Cpaczek** [comment] 2021-11-30 08:37
I was unable to replicate on a clean install of v4. (523 files 600mb)

I did experience the screen going black though however that was only after it switched tabs and then came back however after a bit it did come back and all files did get uploaded. the only difference is I was using sqlite and not pg could you try on sqlite and see if that fixes your issue? It could be a pg rate limit thing but i kinda doubt it.

**Comment by tw1t611** [comment] 2021-11-30 10:04
It actually worked with sqlite. Seems like you need to look into pg.
I tested it on localhost with pg again. The issue remains.

Please keep in mind, that this isn't working like it did in v3 atm and would be very appreciated:
`3. When a upload failed, It should be possible to try the upload again pressing the button.`

Regarding to the issue. It was no problem to upload 150 images at once, so its not urgent to solve this part.

**Comment by derrickmehaffy** [comment] 2022-11-01 18:56
Couldn't reproduce this on v4.4.5, marking as closed for now but if someone still hits this issue let us know and we can look at reopening it.

**Closed** 2022-11-01 18:56 UTC
Labels: issue: bug, severity: low, source: core:upload, status: pending reproduction
