### ISSUE TITLE
Strapi can't execute GraphQL queries with `_in` filters, containing more than 101 items

### ISSUE THREAD

**Issue by MurzNN** [strapi/strapi#10083] opened 2021-04-20 08:43 UTC
### Describe the bug

Strapi GraphQL plugin can't execute queries, that contains in `_in` condition - more that 101 items to filtering. Problem is reproducible with Mongoose (MongoDB) and Knex (SQLite) database libraries.

I know that this type of query is bad for performance, but sometimes we need to have queries like this because of some custom logic, which can't be converted to simple filters using relation field (JOIN tables).

### Steps to reproduce the behavior

1. Have at least 1 user in Strapi `Users` table.
2. Execute in GraphQL explorer the test query:
SQLite:
```graphql
query {
  users(where: {
    id_in: [
      "1",
[repeat above line 99 times]
      "1",
    ]}) {
    id, username
  }
}
```
MongoDB (with replacing id value to some real user in your database: 
```graphql
query {
  users(where: {
    id_in: [
      "607e81eb1ec4fdf7bb73bac7",
[repeat above line 99 times]
      "607e81eb1ec4fdf7bb73bac7",
    ]}) {
    id, username
  }
}
```
3. See empty results in SQLite query (instead of user with id=1) and `INTERNAL_SERVER_ERROR` with `Cast to ObjectId failed for value` error on MongoDB.
4. Remove some lines from the arrays, to make items count less than 102 - the query will executes successfully and returns you the user with passed id in results.

The problem is reproducible with same filtering by other field values, and in other models too.
Extending the results limit from 100 to 1000, using https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#api - isn't help too

### Expected behavior

This query should return the matched user normally, even with 102+ items in array. Same queries works well in other JS GraphQL frameworks, for example in KeystoneJS, with 1000+ items in lists.

### System

- Node.js version: v14
- Strapi version: 3.5.4
- Operating system: Linux

**Comment by derrickmehaffy** [comment] 2021-04-20 14:33
Related to: https://github.com/strapi/strapi/issues/5995

**Comment by derrickmehaffy** [comment] 2021-04-20 15:54
Hi @MurzNN 

By default yes, you cannot use the `qs` or query-string parser for more than 100 entries. To do this properly with GraphQL two things are needed:

- Override the parser middleware settings to increase the array limit beyond the default of 100 (documented [here](https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#request-middlewares))
- Modify the GraphQL settings to crease the maximum limit (documented [here](https://strapi.io/documentation/developer-docs/latest/development/plugins/graphql.html#configurations))

I have attached a test project with some seeded data, the login (since I'm including the SQLite database file) is:

[test10083.zip](https://github.com/strapi/strapi/files/6344912/test10083.zip)

```
email: test@test.com
password: Test1234!
```

But here are the sample files for the two configurations I mentioned:

**Path:** `./config/middleware.js`

```js
module.exports = {
  settings: {
    parser: {
      queryStringParser: {
        arrayLimit: 250,
      },
    },
  },
};
```

**Path:** `./config/plugins.js`

```js
module.exports = {
  graphql: {
    endpoint: "/graphql",
    shadowCRUD: true,
    playgroundAlways: false,
    depthLimit: 7,
    amountLimit: 250,
    apolloServer: {
      tracing: false,
    },
  },
};
```

Using these configs and making a query in GraphQL:

![image](https://user-images.githubusercontent.com/8593673/115427077-fbc3d580-a1b5-11eb-8d8a-2196f4041aef.png)

**Comment by derrickmehaffy** [comment] 2021-04-20 15:55
Going to mark this as closed as it's not a bug per-say but a lack of configuration.

**Closed by derrickmehaffy** 2021-04-20 15:55 UTC

**Comment by MurzNN** [comment] 2021-04-21 09:21
Thanks for so detailed description of this limit and it's solution!

@derrickmehaffy Is it possible to expose some more useful info into GraphQL error text, to better understanding the source of the problem? Something like "Limit of 100 items in array is reached".

**Comment by lvshv** [comment] 2021-04-21 11:14
> Going to mark this as closed as it's not a bug per-say but a lack of configuration.

I have the same problem with MongoDB,  SQLite works well.

**Comment by derrickmehaffy** [comment] 2021-04-21 16:06
Proper error handling will be coming in v4 (we will release an RFC sometime this quarter) but since those are backend (server-side) related issues generally it's not a good idea to expose those to the user.

It more so comes down on how can we communicate these options to developers better without hiding it deep in our documentation.
