### ISSUE TITLE
plugin email send issue when to-property contains "-"

### ISSUE THREAD

**Issue by selbersuess** [strapi/strapi#9202] opened 2021-01-24 14:38 UTC
### Describe the bug

strapi.plugins["email"].services.email.send not sending when to-property contains "-"
example: test@test-test.com

### Code snippets

here is the way i use:

try {
      // Send an email to the user.
      await strapi.plugins["email"].services.email.send({
        **to:\`${user.email}\`**,
        from: settings.from.email || settings.from.name
        ? \`${settings.from.name} <${settings.from.email}>\`
        : undefined,
        replyTo: settings.response_email,
        subject: settings.object,
        text: settings.message,
        html: settings.message,
      });
    } catch (err) {
      strapi.log.debug("err strapi.email", err);
      return ctx.badRequest(null, err);
    }

send fails without error. i dont know how to debug

### System

- Node.js version: 12.20.1
- NPM version: 6.14.10
- Strapi version: 3.4.4
- Database: postgres
- Operating system: ubuntu

**Comment by selbersuess** [comment] 2021-01-24 15:44
now i config my nodemailer to another smtp and it works.
before i did not config nodemailer, maybe the reason for the problem?

**Comment by derrickmehaffy** [comment] 2022-01-05 22:08
can't reproduce, closing

**Closed by derrickmehaffy** 2022-01-05 22:08 UTC
Labels: source: core:email, status: pending reproduction
