### ISSUE TITLE
Can't deploy to MySQL 8 on a Digital Ocean Managed database due to tables without primary keys.

### ISSUE THREAD

**Issue by eugeneingram** [strapi/strapi#11723] opened 2021-11-30 13:49 UTC
### Table creation is rejected due to the default setting for MySQL not allowing tables without primary keys.

Example:

[2021-11-30 11:30:43.648] error: create table `admin_users_roles_links` (`user_id` int unsigned null, `role_id` int unsigned null) - UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
[2021-11-30 11:30:43] Error: UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.

Some of the tables affected:

admin_permissions_role_links
admin_users_roles_links
files_related_morphs
up_permissions_role_links
up_users_role_links

### Steps to reproduce the behavior

Deploy vanilla Strapi to Digital Ocean via a docker image used for an App with a MySQL 8 Managed Database.

### Expected behavior

All tables should have primary keys.

### System

- Strapi version: v4
- Database: MySQL 8

### Additional context

Digital Ocean have confirmed they won't relax the rule on primary keys.  They require this for performing database replication.

**Comment by derrickmehaffy** [comment] 2021-11-30 15:14
Strapi automatically creates primary keys, will try and test this later this week.

**Comment by derrickmehaffy** [comment] 2021-12-02 23:05
Can't reproduce on v4, working fine for me on a managed database.

Marking as closed until we have more information

**Comment by m-torin** [comment] 2021-12-04 19:41
@derrickmehaffy I'm getting this error too... What other details would be helpful?

DigitalOcean notes:

-  `/ 1 GB RAM / 1vCPU / 10 GB Disk / Primary only / NYC3 - MySQL 8`
- MySQL 8 running legacy MySQL 5 password encryption (acts like v5 for auth)
- DO requires `sslmode`
- Strapi 3.x works without problems

Package.json:
```json
"dependencies": {
  "@strapi/plugin-documentation": "^4.0.0",
  "@strapi/plugin-graphql": "^4.0.0",
  "@strapi/plugin-i18n": "^4.0.0",
  "@strapi/plugin-users-permissions": "^4.0.0",
  "@strapi/provider-upload-aws-s3": "^4.0.0",
  "@strapi/strapi": "^4.0.0",
  "mysql": "^2.18.1",
  "sqlite3": "5.0.2",
  "strapi-plugin-sentry": "^3.6.8",
  "strapi-provider-email-amazon-ses": "^3.6.8"
},
```


Console:
```bash
➜  strapi git:(develop) ✗ yarn dev:cms
[2021-12-04 14:33:01.339] debug: ⛔️ Server wasn't able to start properly.
[2021-12-04 14:33:01.340] error: create table `admin_permissions_role_links` (`permission_id` int unsigned null, `role_id` int unsigned null) - UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
Error: UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
    at Query.Sequence._packetToError (~/strapi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (~/strapi/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (~/strapi/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (~/strapi/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (~/strapi/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (~/strapi/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (~/strapi/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (~/strapi/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    --------------------
    at Protocol._enqueue (~/strapi/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (~/strapi/node_modules/mysql/lib/Connection.js:198:25)
    at ~/strapi/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (~/strapi/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (~/strapi/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (~/strapi/node_modules/knex/lib/client.js:134:12)
    at ~/strapi/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (~/strapi/node_modules/knex/lib/execution/transaction.js:358:12)
    at Runner.query (~/strapi/node_modules/knex/lib/execution/runner.js:130:36)
    at Runner.queryArray (~/strapi/node_modules/knex/lib/execution/runner.js:241:31)
    at ensureConnectionCallback (~/strapi/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19)
    at Runner.ensureConnection (~/strapi/node_modules/knex/lib/execution/runner.js:272:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Runner.run (~/strapi/node_modules/knex/lib/execution/runner.js:30:19)
```

**Comment by derrickmehaffy** [comment] 2021-12-06 01:10
> @derrickmehaffy I'm getting this error too... What other details would be helpful?
> 
> DigitalOcean notes:
> 
> * `/ 1 GB RAM / 1vCPU / 10 GB Disk / Primary only / NYC3 - MySQL 8`
> * MySQL 8 running legacy MySQL 5 password encryption (acts like v5 for auth)
> * DO requires `sslmode`
> * Strapi 3.x works without problems
> 
> Package.json:
> 
> ```json
> "dependencies": {
>   "@strapi/plugin-documentation": "^4.0.0",
>   "@strapi/plugin-graphql": "^4.0.0",
>   "@strapi/plugin-i18n": "^4.0.0",
>   "@strapi/plugin-users-permissions": "^4.0.0",
>   "@strapi/provider-upload-aws-s3": "^4.0.0",
>   "@strapi/strapi": "^4.0.0",
>   "mysql": "^2.18.1",
>   "sqlite3": "5.0.2",
>   "strapi-plugin-sentry": "^3.6.8",
>   "strapi-provider-email-amazon-ses": "^3.6.8"
> },
> ```
> 
> Console:
> 
> ```shell
> ➜  strapi git:(develop) ✗ yarn dev:cms
> [2021-12-04 14:33:01.339] debug: ⛔️ Server wasn't able to start properly.
> [2021-12-04 14:33:01.340] error: create table `admin_permissions_role_links` (`permission_id` int unsigned null, `role_id` int unsigned null) - UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
> Error: UNKNOWN_CODE_PLEASE_REPORT: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.
>     at Query.Sequence._packetToError (~/strapi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
>     at Query.ErrorPacket (~/strapi/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
>     at Protocol._parsePacket (~/strapi/node_modules/mysql/lib/protocol/Protocol.js:291:23)
>     at Parser._parsePacket (~/strapi/node_modules/mysql/lib/protocol/Parser.js:433:10)
>     at Parser.write (~/strapi/node_modules/mysql/lib/protocol/Parser.js:43:10)
>     at Protocol.write (~/strapi/node_modules/mysql/lib/protocol/Protocol.js:38:16)
>     at Socket.<anonymous> (~/strapi/node_modules/mysql/lib/Connection.js:88:28)
>     at Socket.<anonymous> (~/strapi/node_modules/mysql/lib/Connection.js:526:10)
>     at Socket.emit (events.js:400:28)
>     at Socket.emit (domain.js:475:12)
>     at addChunk (internal/streams/readable.js:293:12)
>     at readableAddChunk (internal/streams/readable.js:267:9)
>     at Socket.Readable.push (internal/streams/readable.js:206:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
>     --------------------
>     at Protocol._enqueue (~/strapi/node_modules/mysql/lib/protocol/Protocol.js:144:48)
>     at Connection.query (~/strapi/node_modules/mysql/lib/Connection.js:198:25)
>     at ~/strapi/node_modules/knex/lib/dialects/mysql/index.js:126:18
>     at new Promise (<anonymous>)
>     at Client_MySQL._query (~/strapi/node_modules/knex/lib/dialects/mysql/index.js:120:12)
>     at executeQuery (~/strapi/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
>     at Client_MySQL.query (~/strapi/node_modules/knex/lib/client.js:134:12)
>     at ~/strapi/node_modules/knex/lib/execution/transaction.js:363:24
>     at new Promise (<anonymous>)
>     at Client_MySQL.trxClient.query (~/strapi/node_modules/knex/lib/execution/transaction.js:358:12)
>     at Runner.query (~/strapi/node_modules/knex/lib/execution/runner.js:130:36)
>     at Runner.queryArray (~/strapi/node_modules/knex/lib/execution/runner.js:241:31)
>     at ensureConnectionCallback (~/strapi/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19)
>     at Runner.ensureConnection (~/strapi/node_modules/knex/lib/execution/runner.js:272:20)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async Runner.run (~/strapi/node_modules/knex/lib/execution/runner.js:30:19)
> ```

Can you please try to reproduce on a local install of MySQL 8? As I tested both local and a managed DB in DO and couldn't reproduce.

**Comment by eugeneingram** [comment] 2021-12-06 10:24
@m-torin I gave up trying to get MySQL 8 on DO working with Strapi.  I switched to using Postgres on DO instead and this worked fine.  Might be an option for you perhaps?

**Comment by fooyongyan** [comment] 2021-12-07 12:45
@eugeneingram I was trying on DO to get my instance going, but I am having a different issue of not having enough connection. I am wondering if you are able to advice me on that?

**Comment by eugeneingram** [comment] 2021-12-07 16:37
> @eugeneingram I was trying on DO to get my instance going, but I am having a different issue of not having enough connection. I am wondering if you are able to advice me on that?

@fooyongyan Not sure about a connection issue.  It depends what the error is, you may have to alter the password hashing mechanism: https://www.digitalocean.com/community/questions/how-to-change-caching_sha2_password-to-mysql_native_password-on-a-digitalocean-s-managed-mysql-database

Alternatively you may have to get the environment accessing the database to accept a self-signed certificate perhaps.

**Comment by ari-motors-team** [comment] 2021-12-08 19:17
@eugeneingram Did you set it up as app plattform? Can't get the postgres db connected somehow.

**Comment by eugeneingram** [comment] 2021-12-08 19:52
@ari-motors-team Yes, app is on the App platform in Digital Ocean.  The Postgres database is separate from that on Digital Ocean.  Did you add your app to the 'Trusted Sources' under the database settings tab?

**Comment by ari-motors-team** [comment] 2021-12-08 20:03
Yes I did. Also I created it separately before creating the app. Did you add the db as a component to the app platform afterwards?
![image](https://user-images.githubusercontent.com/95754840/145276046-0eda8001-f8b7-425a-b839-c24035ec2061.png)

Also did ypu set `ssl: false` to database.js?

Already nice to know, that it is possible. :)

**Comment by eugeneingram** [comment] 2021-12-08 22:15
@ari-motors-team I didn't add the database as a component of the app platform at all.  I just commissioned a database separately within the Databases section in the Digital Ocean console and added the app as a trusted source.  So on my app under Components I don't see the database listed at all as you're seeing in your console.  In Strapi database.js I've got `ssl: true`.

Did you launch the app with a Strapi image from somewhere on Docker Hub?  The component icon looks different to mine, I'm using my own docker container image that I've pushed up to the container registry on Digital Ocean.

You might find something helpful under the Console or Runtime Logs for your app perhaps that points you in the direction of the problem?  They were handy for me debugging issues when I was setting up.

**Comment by derrickmehaffy** [comment] 2021-12-08 22:27
Reopening this as I can reproduce now on MySQL 8 managed DB on DO.

One of our older test mysql8 instances there we use for testing didn't have the issue but a new one does.

**Comment by derrickmehaffy** [comment] 2021-12-08 22:28
![image](https://user-images.githubusercontent.com/8593673/145297519-8e05804a-1191-40b8-a057-b229ef055a3b.png)

**Comment by ari-motors-team** [comment] 2021-12-09 09:45
@eugeneingram Thank you so much for helping me out!
I use my own Dockerfile for local development, but only use the default node app for deployment.

The further steps I needed to make (for others comming across this issue).
1. Delete the component database in app plattform and only use the previously created db
2. Hard code the connection string to app plattform env (picture below)
3. Set NODE_ENV to production (picture below)
![image](https://user-images.githubusercontent.com/95754840/145372347-2c8a4c82-dfa4-4d2d-bc77-d2a373f07fe6.png)

3. Set ssl in database.js like this.
```js
ssl: {
  rejectUnauthorized: env.bool("DATABASE_SSL_SELF", false), // For self-signed certificates
}
```

**Comment by snnaik** [comment] 2022-01-16 01:34
I have this exact same issue on a fresh setup - managed mysql 8 DB on DO, legacy mysql auth, strapi v4.0.4 with ssl to DB. Any help is much appreciated.

**Comment by derrickmehaffy** [comment] 2022-01-18 23:03
Something weird is going on with DO because a locally installed version of MySQL 8 I can't reproduce this issue, even with SSL

**Comment by Keith-Hon** [comment] 2022-02-10 10:34
having same issue with managed database in DO

**Comment by ephb** [comment] 2022-02-10 17:29
I had the same issue on 4.0.6 last week with managed database in DO. Switching to Postgres was the only fix I could think of.

**Comment by derrickmehaffy** [comment] 2022-02-10 18:09
> I had the same issue on 4.0.6 last week with managed database in DO. Switching to Postgres was the only fix I could think of. @derrickmehaffy what was the patch version of MySQL 8 that worked for your locally?

I tested on MySQL 8.0.28 yesterday

**Comment by eugeneingram** [comment] 2022-02-15 18:41
@derrickmehaffy Any idea when this may be resolved?  I'm hitting this issue using Postgresql on Digital Ocean: https://github.com/strapi/strapi/issues/11860 and can find no resolution to this with several different connection pool configurations and even beefing up the DO database to 4GB and enlarging the max connection pool.  So it would see there is likely a bug with Strapi/knex and a large content model when trying to start strapi against an existing Postgresql database.

Since I can't resolve the issue using Postgresql, I've come back to look at MySQL.  But this issue stops me using MySQL on Digital Ocean.

This really is proving a blocker for us and I've a client depending on a stable production environment.

**Comment by derrickmehaffy** [comment] 2022-02-15 20:17
> @derrickmehaffy Any idea when this may be resolved?  I'm hitting this issue using Postgresql on Digital Ocean: https://github.com/strapi/strapi/issues/11860 and can find no resolution to this with several different connection pool configurations and even beefing up the DO database to 4GB and enlarging the max connection pool.  So it would seem there is likely a bug with Strapi/knex and a large content model when trying to start strapi against an existing Postgresql database.
> 
> Since I can't resolve the issue using Postgresql, I've come back to look at MySQL.  But this issue stops me using MySQL on Digital Ocean.
> 
> This really is proving a blocker for us and we've a client depending on a stable production environment.

I am planning to build a reproduction in DO today and I have a meeting with the backend engineers tomorrow morning to explain it and pick their brains on it but we currently have no idea why it's happening as it's only on DigitalOcean from what I can tell. Any default installation of MySQL 8 on any other environment than DO managed databases works normally.

Until we find the root cause, we can't fix it (if it's a problem on our side or a non-standard config on DO)

**Comment by eugeneingram** [comment] 2022-02-15 21:42
> > @derrickmehaffy Any idea when this may be resolved?  I'm hitting this issue using Postgresql on Digital Ocean: #11860 and can find no resolution to this with several different connection pool configurations and even beefing up the DO database to 4GB and enlarging the max connection pool.  So it would seem there is likely a bug with Strapi/knex and a large content model when trying to start strapi against an existing Postgresql database.
> > Since I can't resolve the issue using Postgresql, I've come back to look at MySQL.  But this issue stops me using MySQL on Digital Ocean.
> > This really is proving a blocker for us and we've a client depending on a stable production environment.
> 
> I am planning to build a reproduction in DO today and I have a meeting with the backend engineers tomorrow morning to explain it and pick their brains on it but we currently have no idea why it's happening as it's only on DigitalOcean from what I can tell. Any default installation of MySQL 8 on any other environment than DO managed databases works normally.
> 
> Until we find the root cause, we can't fix it (if it's a problem on our side or a non-standard config on DO)

If it's any help, the error I was seeing in MySQL was that it wouldn't allow a table to be created without a primary key, as I mentioned in my original post above.  It seems this setting is turned ON by default in Digital Ocean MySQL instances and they don't enable it to be turned off (I got in touch with DO about this).  The default for MySQL as standard is actually for this setting to be OFF which explains why you've not seen the problem on other MySQL instances.

https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_require_primary_key

So the fix could perhaps be ensuring that a primary key is set on all tables created by Strapi?

**Comment by derrickmehaffy** [comment] 2022-02-16 14:59
Thanks @eugeneingram we found the issue, DigitalOcean sets a non-default option to true on their managed database that we couldn't reproduce elsewhere because it's off by default everywhere else :see_no_evil: 

I've created a PR that disables this check on the session but to disable it globally you need to contact DigitalOcean per this answer: 

https://www.digitalocean.com/community/questions/how-to-disable-sql_require_primary_key-in-digital-ocean-manged-database-for-mysql?comment=168655

This PR should fix it, alternatively you can set this during the bootstrap function until we merge and release a new version with this fix.

**Comment by eugeneingram** [comment] 2022-02-16 18:03
I've asked Digital Ocean to make that setting change.  I can confirm Strapi now deploys correctly on a MySQL managed database on their platform after doing so.

**Comment by eugeneingram** [comment] 2022-02-16 18:03
@derrickmehaffy Thanks for getting this sorted today.

**Comment by derrickmehaffy** [comment] 2022-02-16 18:45
> @derrickmehaffy Thanks for getting this sorted today.

Quite welcome! Sorry it took so long, we have been very very busy.

**Comment by derrickmehaffy** [comment] 2022-03-02 22:43
Tested on v4.1.2 today as did @marcoautiero and we both could reproduce the issue with the following error:

![image](https://user-images.githubusercontent.com/8593673/156462262-6a7e0ec8-5de4-4b1f-a97f-c196fe535f09.png)

**Comment by derrickmehaffy** [comment] 2022-03-04 00:47
fixed in https://github.com/strapi/strapi/pull/12724

**Closed by derrickmehaffy** 2022-03-04 00:47 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:database

**Comment by matepaiva** [comment] 2022-03-15 12:16
I can confirm that it's fixed, but now I am getting emails from digitialocean saying:

```
Our systems have indicated that your MySQL cluster has tables without primary keys. We have identified that MySQL tables without primary keys can lead to service replication issues that jeopardize performance and availability. If primary keys are not present for database tables exceeding 5,000 rows, data-loss can occur.

We urge you to take the following actions to ensure that your database continues to operate correctly:

1. Review the following product documentation which details the issue and provides clear mitigation strategies for all impacted users.
2. Implement primary keys for all database tables as described in the documentation.

See the full details at the following link: https://www.digitalocean.com/docs/databases/mysql/how-to/create-primary-keys/

We will continue to notify you of this issue until all MySQL tables have primary keys.
```

**Comment by derrickmehaffy** [comment] 2022-03-15 21:08
> https://www.digitalocean.com/docs/databases/mysql/how-to/create-primary-keys/

Thanks for this, I'll notify the team

**Comment by jowe13** [comment] 2022-03-19 16:27
Hi, this still seems to be an issue.
After running npx create-strapi-app@latest v4test and yarn develop afterwards i get the following:

 error: insert into `up_permissions_role_links` (`permission_id`, `role_id`) values (3, 3) - ER_UNKNOWN_ERROR: Percona-XtraDB-Cluster prohibits use of DML command on a table (hspx.up_permissions_role_links) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER

Can someone provide any help please?

**Comment by gertmulder** [comment] 2022-03-27 12:06
You can now also change the setting using the Digital Ocean API. Details are given here:
https://docs.digitalocean.com/reference/api/api-reference/#operation/patch_database_config

They added this option a few weeks ago:
https://docs.digitalocean.com/products/databases/ (end of page, latest updates)

Just tried it myself, it worked for me.

**Comment by jonOreillyEasybell** [comment] 2022-06-03 10:26
Hi, I'm getting a similar error to @jowe13. 

I'm running Strapi with a Percona cluster, which requires all tables to have primary keys. The problem arises when I try to add an entry to a collection that has a component with a property to another collection. I get the sane "DML command" error because the `..._links` tables do not seem to have a primary key:
```sh
select * from components_home_usps_image_links;
+--------+----------+
| usp_id | image_id |
+--------+----------+
|      1 |        1 |
|      2 |        1 |
+--------+----------+
``` 

I believe this could be solved by adding a primary key to these links tables:

In [/packages/core/database/lib/metadata/relations.js -> createJoinTable](https://github.com/strapi/strapi/blob/0c14a069798989c4f6cd042806dfa3e8a598c6d2/packages/core/database/lib/metadata/relations.js#L396)
```js
metadata.add({
  ...,
  atributes: {
    id: {
      type: 'increments',
    },
    ...
  }
})
```

**Comment by derrickmehaffy** [comment] 2022-06-03 14:42
Hey @jonOreillyEasybell 

I know this is an annoying ask but could you open a new issue on this so we can track it a bit easier. We are on the fence if we need to actually implement (keeping in mind Percona is not actually a database we support)
