### ISSUE TITLE
Model error when searching for ampersand

### ISSUE THREAD

**Issue by dondracek** [strapi/strapi#12708] opened 2022-03-02 07:32 UTC
## Bug report
In the admin panel, searching for a string containing "&" will produce an error.

### Describe the bug

The "_q" parameter isn't escaped properly, so for example the search for "F&Q" in Pages will produce the following request:
`https://strapi.example.com/content-manager/collection-types/application::pages.pages?page=1&pageSize=10&_sort=UrlASC&_q=F&Q`
You can see the "F&Q" is producing query containing the parameters "_q=F" and "Q"(empty). Which throws a model error because "Q" is not a model property.

### Steps to reproduce the behavior

1. Go to admin panel
2. Click on any collection type
3. In the upper left corner of the content area, click the serach input and type in "F&Q"
4. An error is shown
5. Check the network devtools tab, there's an error:
```json
{
   error: "Bad Request",
   message: "Your filters contain a field 'A' that doesn't appear on your model definition nor its relations",
   statusCode: 400
}
```

### Expected behavior

F&Q is encoded and can be searched for

### Screenshots

![image](https://user-images.githubusercontent.com/12990642/156315293-fe956838-006c-4703-babf-b5b1f359f1b8.png)

### System

- Node.js version: v14
- NPM version: v8
- Strapi version: v3.6.6
- Database: PostgreSQL
- Operating system: Ubuntu 20

**Comment by kasonde** [comment] 2022-03-03 10:40
Duplicate of #10780

**Closed by kasonde** 2022-03-03 10:40 UTC
