### ISSUE TITLE
Media Library not opens if there are many files already uploaded

### ISSUE THREAD

**Issue by CTOlet** [strapi/strapi#16710] opened 2023-05-13 16:49 UTC
### Required System information

- Node.js version: v16.18.1
- NPM version: v8.19.2
- Strapi version: 4.9.1
- Database: PostgreSQL
- Operating system: Docker node-alpine
- Is your project Javascript or Typescript: TypeScript

### Describe the bug

When there are millions of files "Media Library" not loading. I saw that it is long running query that takes a number for pagination (?). 

### Steps to reproduce the behavior

Upload many files to the root of the "Media Library"

### Expected behavior

"Media Library" opens

### Screenshots

<img width="903" alt="image" src="https://github.com/strapi/strapi/assets/5058015/2471b854-c35b-4ddd-b113-18aa9d1efd66">
<img width="450" alt="image" src="https://github.com/strapi/strapi/assets/5058015/3432b44c-ee95-4aea-9a93-f1d534d43f56">
<img width="1181" alt="image" src="https://github.com/strapi/strapi/assets/5058015/0b1c7129-19f2-4d70-b57a-d267d4cdd493">

**Comment by Marc-Roig** [comment] 2023-05-30 14:30
Hello ! Thank you for that detailed issue description, it really helped pinpoint where the issue is.

I have been able to reproduce this issue ... Having 5M media, loading the Media Library takes ages.

We might be able to optimize this if we change the query we do in frontend, right now the query is doing the following filter:
`filters[$and][0][folder][id][$null]=true`

This, as you showed in the description, results in 2 Joins. Here we would be joining 5M rows with 5M rows, which makes the query REALLY slow.

In my opinion we could use the file `folderPath` (which is indexed) for this and do:
`filters[$and][0][folderPath][$eq]=/ ` (or the folder path being displayed in the Media Library)

This single query change improves the query time from 40s to 5s.

 @gu-stav @joshuaellis , this might be an extreme case, but nevertheless a very good opportunity to make a performance optimization. Do you think you could take this one?

**Comment by joshuaellis** [comment] 2023-06-05 09:00
> @gu-stav @joshuaellis , this is an extreme case, but one that can affect many users and a very good opportunity to make a performance optimization. Do you think you could take this one?

Yes, i'll assign this to us both and we'll try take a look at it as soon as feasible.

**Comment by CTOlet** [comment] 2023-06-15 05:24
@gu-stav @joshuaellis

Hello guys,

Do you have any updates?
Our production Admin Media Library UI is still useless

**Comment by Marc-Roig** [comment] 2023-06-21 07:02
@CTOlet hello, we are working on it and you can expect this to be fixed in a couple of weeks :)

**Closed** 2023-06-30 09:40 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:upload
