### ISSUE TITLE
Too many relations slows down admin ui

### ISSUE THREAD

**Issue by anitricks** [strapi/strapi#2764] opened 2019-02-05 17:52 UTC
**Informations**
- **Node.js version**: 11.9.0
- **NPM version**: 6.7.0
- **Strapi version**: 3.0.0-alpha.21
- **Database**: MySQL
- **Operating system**: OSX 
- **(Optional) Link to your Project**: 

**What is the current behavior?**
i currently have a model A with 2 relational fields of at least 1000 model B's attached to it. When i try to edit this model A name (string field), the admin UI starts to hang and takes on an average about 3-5 seconds just to edit the string field. the page hangs for any action evening saving...

**Steps to reproduce the problem**
create model B. create 1000 records for model B. then create model A with a string field and relation field (model B). attach the 1000 model Bs to one model A. then try to edit the model A in the admin UI and see if its hangs while modifying the string field

**What is the expected behavior?**
admin ui should not hang or delay while inputing

**Suggested solutions**
since its react i think the its updating the state with the 1000 relations every time i type into the input.

**Comment by lauriejim** [comment] 2019-02-06 11:06
Hello @anitricks !
Thank you for this report!

Can you please update with the exact version of Strapi you use.

**Comment by anitricks** [comment] 2019-02-06 23:02
yes it is 3.0.0-alpha.21

**Comment by lauriejim** [comment] 2019-02-08 17:30
What is you models cause I can't reproduce your issue.

**Comment by anitricks** [comment] 2019-02-09 14:38
i cant disclose the models names however here is somewhat a structure of the two models 
```javascript
Model A {
  string,
  json,
  number,
  relation1 -> Model B (2000-3000)
  relation2 -> Model C (1500-2000)
  string
  ... //bunch of stuff
}
Model B {
  string,
  number,
  json,
  relation1 -> Model D 1,
  relation2 -> Model E (10 max),
  relation3 -> Model F (1),
}
```
model b has multiple relations and pulling 3000s and their relations is an overload, tho i think it is a simple case of a blog with a lot comments; comments that contains author relation etc.

maybe try more relations 2000-3000??

**Comment by lauriejim** [comment] 2019-02-09 15:02
Can . you confirm it's not the same issue as this one https://github.com/strapi/strapi/issues/2415

**Comment by anitricks** [comment] 2019-02-13 04:17
yeah it is same. the last comment
https://github.com/strapi/strapi/issues/2415#issuecomment-445557424
it loading all the relationships when loading model B

**Comment by lauriejim** [comment] 2019-02-13 18:31
OKay so I close this issue.
Let's have one issue fo this topic.

**Closed by lauriejim** 2019-02-13 18:31 UTC
Labels: type: help wanted 🤷‍♂️
