### ISSUE TITLE
Not able to update media with multipart

### ISSUE THREAD

**Issue by dhruvsaxena1998** [strapi/strapi#9699] opened 2021-03-12 12:58 UTC
### Describe the bug
Media files are not being updated with multipart data

### Steps to reproduce the behavior

1. Create a collection with files `text`, `media`
2. Create an entry
3. Extend default `update` controller  (Presented test code snippet below)
4. Try to update the entry with `rest-api` multipart data

### Expected behavior

Not able to update files with multipart data but `data` is updating fine

### Code snippets
```js
"use strict";

const { parseMultipartData } = require("strapi-utils");
module.exports = {
  update: async (ctx) => {
    let entity;

    if (ctx.is("multipart")) {
      const { data, files } = parseMultipartData(ctx);

      entity = await strapi
        .query("test-collection")
        .update({ id: ctx.params.id }, data, { files });
    }

    return entity;
  },
};

```

### System

- Node.js version: v12.9.0
- NPM version: v6.14.8
- Strapi version: v3.5.2
- Database: MySQL
- Operating system: Window  10

**Comment by derrickmehaffy** [comment] 2021-03-12 13:01
Confirmed on v3.5.3 with the default users-permissions update controller. Will test on normal models to see if it's isolated to just users-permissions.

**Comment by dhruvsaxena1998** [comment] 2021-03-13 15:02
> Did these tests on 2 different systems on latest Strapi v3.5.3

- Tested on normal collections
✅ Default Controller 
❌ Default Controller if extended 
❌ Custom Controller

- Tested on users-permissions
❌ Default Controller
❌ Default Controller if extended
❌ Custom Controller

**Comment by jhoward1994** [comment] 2023-02-08 09:16
Closing as this is a duplicate of https://github.com/strapi/strapi/issues/13041

**Closed by jhoward1994** 2023-02-08 09:16 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: plugin:users-permissions
