### ISSUE TITLE
error when trying to send email using sendgrid provider with apikey: "403 Forbidden"

### ISSUE THREAD

**Issue by eitelkrauss** [strapi/strapi#9539] opened 2021-02-27 17:22 UTC
I'm trying to use Sendgrid for sending an order confirmation email to client.  A GET request to /email sends a test email and works just fine.. but when I try a POST request to /email the response is 403 Forbidden.  I did change the settings for public user.
Email confirmation works fine also.

This is in my strapi api and config folders

config/plugins.js
```
module.exports = ({env}) => ({
    email: {
        provider: 'sendgrid',
        providerOptions: {
            apiKey: env('SENDGRID_API_KEY'),
        },
        settings: {
            defaultFrom: "no-reply@mydomain.com",
            defaultReplyTo: "no-reply@mydomain.com"
        },
    }
})
```

api/mail/controllers/email.js
```

const { default: createStrapi } = require("strapi")

module.exports = {
  index: async ctx => {
    await strapi.plugins['email'].services.email.send({
      to: 'xxx@gmail.com',
      from: 'no-reply@mydomain.com',
      replyTo: 'support@mydomain.com',
      subject: 'test subject',
      text: 'Hello world!',
      html: 'Hello world!',
    });
    
  },  
  send: async (ctx) => {
        const body = ctx.request.body
        const sendTo = body.email
        strapi.log.debug(ctx.state.user)
        strapi.log.debug(`Trying to send an email to ${sendTo}`)
    
        try {
          const emailOptions = {
            to: sendTo,
            subject: 'This is a test',
            html: `<h1>Welcome!</h1><p>This is a test HTML email.</p>`,
          }
          await strapi.plugins['email'].services.email.send(emailOptions)
          strapi.log.debug(`Email sent to ${sendTo}`)
          ctx.send({ message: 'Email sent' })
        } catch (err) {
          strapi.log.error(`Error sending email to ${sendTo}`, err)
          ctx.send({ error: 'Error sending email' })
        }
      },
}
```
api/mail/config/routes.json
```
{
    "routes": [
        {
            "method": "GET",
            "path": "/email",
            "handler": "Email.index",
            "config": {
                "policies": []
            }
        },
        {
            "method": "POST",
            "path": "/email",
            "handler": "Email.send",
            "config": {
                "policies": []
            }
        }
    ]
}
```

"strapi": "3.3.4"
"strapi-provider-email-sendgrid": "^3.4.6",

**Comment by MattieBelt** [comment] 2021-03-05 16:14
Hey @eitelkrauss,

You need to update your config (`email.settings.defaultFrom`) to use the email configured with your sendgrid key, you aren't allowed to send email as _no-reply@mydomain.com_.

**Comment by derrickmehaffy** [comment] 2021-03-08 19:09
tested on v3.5.2 with sendgrid and it functioned fine, please try what @MattieBelt suggested. Marking as closed until reproduction steps are provided.

**Closed by derrickmehaffy** 2021-03-08 19:09 UTC
Labels: status: can't reproduce

**Comment by eitelkrauss** [comment] 2021-03-11 18:39
@MattieBelt ..will try this...  but it works alright with a GET request to /email... a test email is sent with defaultFrom: no-reply@mydomain.com..

A POST request returns 403 forbidden..

**Comment by eitelkrauss** [comment] 2021-03-12 15:52
I updated strapi to 3.5.2 ... GET request works fine ..https://imgur.com/qUd07Ev

Something to do with this part maybe ?

```
send: async (ctx) => {
        const body = ctx.request.body
        const sendTo = body.email
        strapi.log.debug(ctx.state.user)
        strapi.log.debug(`Trying to send an email to ${sendTo}`)
    
        try {
          const emailOptions = {
            to: sendTo,
            subject: 'This is a test',
            html: `<h1>Welcome!</h1><p>This is a test HTML email.</p>`,
          }
          await strapi.plugins['email'].services.email.send(emailOptions)
          strapi.log.debug(`Email sent to ${sendTo}`)
          ctx.send({ message: 'Email sent' })
        } catch (err) {
          strapi.log.error(`Error sending email to ${sendTo}`, err)
          ctx.send({ error: 'Error sending email' })
        }
      }

**Comment by MattieBelt** [comment] 2021-03-12 23:40
@eitelkrauss nice to hear that it works!

I have no Idea why it didn't work before, there has not been any (logic) changes on the email plugin since `3.3.4` nor on the sendgrid provider.

On a side note, if you would have upgraded to `3.5.3`, you would also be able to test your email provider from Admin Panel > _SETTINGS_ > _EMAIL PLUGIN SETTINGS_.

**Comment by eitelkrauss** [comment] 2021-03-16 18:14
@MattieBelt I upgraded to `3.5.3`

I edited my post too.  So this is what I have right now and can't get it to work with a `POST /email` route... does it work only with GET requests? I get a `403 forbidden`...

`strapi.log.debug(ctx.request.body)` prints `undefined`

I set Public role permissions for /email too.

I tested the plugin in the Admin Panel as you said and works fine.

**Comment by eitelkrauss** [comment] 2021-03-18 19:00
Still having this issue... if i write a `GET` route it works but cant send data to the api... a `POST` route response is `403 Forbidden`

![Screenshot from 2021-03-18 13-59-38](https://user-images.githubusercontent.com/45218341/111682396-4ab2cf80-87f2-11eb-87cc-56e28a8c98db.png)

**Comment by derrickmehaffy** [comment] 2021-03-23 21:22
Doublecheck your users-permissions permissions and make sure you didn't accidentally set the `isAuthenticated` dynamic policy (hit the hear icon next to the controller and it will show in the box on the right)

**Comment by eitelkrauss** [comment] 2021-03-24 16:32
@derrickmehaffy its set to "None" ..
![Screenshot_2021-03-24 Settings](https://user-images.githubusercontent.com/45218341/112347051-8d622500-8c94-11eb-97f2-36bf14f860d7.png)

**Comment by derrickmehaffy** [comment] 2021-03-29 18:35
@eitelkrauss do you have a link to your project code as we need more information to find the root cause, or at the very least a test repo that can reproduce the bug.

**Comment by eitelkrauss** [comment] 2021-04-02 17:36
@derrickmehaffy 

[https://github.com/eitelkrauss/bchwood-cms](https://github.com/eitelkrauss/bchwood-cms)

please

**Comment by gempathy-lmoore** [comment] 2021-04-05 12:17
@eitelkrauss Did you ever get this to work? I'm running into this exact same problem now.

I can use a GET request fine, but POST returns a 403. I've checked and double checked the permissions (Also set to None).

**Comment by eitelkrauss** [comment] 2021-04-05 15:19
hey @gempathy-lmoore .. not yet.. good to know its not just me I guess ..lol

**Comment by gempathy-lmoore** [comment] 2021-04-06 10:52
@eitelkrauss I just updated to the same version you are on 3.5.4 and now it works for me. I hope you get it figured out as well. Good luck.

**Comment by eitelkrauss** [comment] 2021-04-08 15:55
just updated `strapi-plugin-email` and `strapi-provider-email-sendgrid` to ^3.5.4 too... still not working for me

**Comment by gempathy-lmoore** [comment] 2021-04-10 10:47
@eitelkrauss 

One thing I'm pretty sure about is that I don't think the strapi-plugin-email is the problem. 

To verify, remove all of that logic and just put `console.log(ctx)` like I have just to see if the route is even being hit. I would bet you'll still get that 403, which means it's a route problem.

Another thing I noticed that we both named our route `email`. I changed mine to `contact` (and updated, which you've said you've done) and it worked.

**Comment by MattieBelt** [comment] 2021-04-10 14:40
On a side note @eitelkrauss, you should avoid using a caret `^` on the official strapi packages. 
This could result in errors.

**Comment by eitelkrauss** [comment] 2021-04-19 15:37
got it to work after removing the logic like you said @gempathy-lmoore thanks! starting from scratch now..

Just one more thing if I may...? @MattieBelt 

I'm testing the endpoint using the curl cli.. sending `-d '{"message": "hello"}'` ...but  a `console.log(ctx.request.body)` returns `{ '{"message": "hello"}': '' }`... is this an issue with using curl?
