### ISSUE TITLE
App fetching error when using `strapi develop --watch-admin`

### ISSUE THREAD

**Issue by bidoubiwa** [strapi/strapi#13852] opened 2022-07-26 11:16 UTC
### Required System information

- Node.js version: node 14/18 (tried on both)
- NPM version: 8.12.0
- Strapi version: 
     - "@strapi/strapi": "^4.2.3",
     - "@strapi/utils": "^4.2.2",
- Database: `sqlight`
- Operating system: Mac m1

### Describe the bug

When running my app with the following cmd :  `strapi develop --watch-admin` it briefly shows the login page and then is redirected to a page with the following: 
<img width="334" alt="Screenshot 2022-07-26 at 13 15 18" src="https://user-images.githubusercontent.com/33010418/180993449-574ac0c3-27d5-4f77-aebe-01bb6da4dba8.png">

### Steps to reproduce the behavior

1. Start server with `strapi develop --watch-admin`
2. Go to app

### Expected behavior

Stay on the login page.

**Comment by sg-code** [comment] 2022-08-02 06:29
I'm experiencing the same problem on a fresh `create-strapi-app` installation (Strapi v4.3.2). The issue persists on Node v14.20.0 & v16.16.0. Neither `yarn strapi develop --watch admin` nor `yarn strapi watch-admin` (with another shell running `yarn strapi develop`) work as expected.

**Comment by derrickmehaffy** [comment] 2022-08-04 20:29
Unable to reproduce, could either of you give us more information please?

**Comment by sg-code** [comment] 2022-08-04 21:38
# Required System information

- Node.js version: v14.20.0
- NPM version: 6.14.17
- Strapi version:
- "@strapi/strapi": "4.3.2",
- "@strapi/plugin-users-permissions": "4.3.2",
- "@strapi/plugin-i18n": "4.3.2",
- "better-sqlite3": "7.4.6"
- Database: sqlight
- Operating system: macOS Monterey 12.5, Intel i9

Error occurs on a fresh `create-strapi-app` install using the `--quickstart` flag. In this case I installed using:
```console
yarn create strapi-app my-project --quickstart
```

# Behavior

I've tested across different PORT settings in the .env, to no avail.

Just like with @bidoubiwa, the error occurs after passing through the login/auth page (which renders correctly). After which, the welcome screen will flash, and the the error screen (shown below) will display. The dev server restarts on change as intended, and the rendered welcome page will flash for a split second before the error appears.

# Screenshots

<img width="880" alt="Screen Shot 2022-08-04 at 3 21 30 PM" src="https://user-images.githubusercontent.com/57642478/182956982-7d13a3c2-43b4-4789-bc09-04c159516182.png">

With PORT set to 1337
<img width="1509" alt="Screen Shot 2022-08-04 at 3 25 21 PM" src="https://user-images.githubusercontent.com/57642478/182957057-9065748f-cb87-4990-9ec9-31ffa5d92a33.png">

With PORT set to 1339
<img width="1509" alt="Screen Shot 2022-08-04 at 3 23 04 PM" src="https://user-images.githubusercontent.com/57642478/182957169-7a9ed21c-010e-4bb3-a655-25ab9ccec0df.png">

Thanks for taking a look at this, @derrickmehaffy !

**Comment by sg-code** [comment] 2022-08-04 21:44
Okay, I made some headway: It looks like the error screen is trigged by the use of Ad blocking browser extensions. Once I turned my Ad blocker off, everything worked as expected, regardless of selected PORT number.

**Comment by sg-code** [comment] 2022-08-04 21:52
@bidoubiwa  I found a fix (at least on my machine):

Disable telemetry data using the following CLI command:
Yarn
```console
yarn strapi telemetry:disable
```
NPM
```console
npm run strapi telemetry:disable
```

**Comment by bidoubiwa** [comment] 2022-08-08 08:46
Oh it's the add block that causes an issue. Thanks a lot!

**Comment by derrickmehaffy** [comment] 2022-08-08 13:50
I'll set this one as closed as it was more or less confirmed that the issue's root cause didn't come from Strapi but a 3rd party browser extension. Others that hit this issue and search will see the workaround :)

Thanks!

**Closed by derrickmehaffy** 2022-08-08 13:50 UTC
Labels: status: can not reproduce
