### ISSUE TITLE
4.19.0 - Warning on user invitation (an error occured) - doesn't generate activate link/email

### ISSUE THREAD

**Issue by Digiversecz** [strapi/strapi#19352] opened 2024-01-28 12:49 UTC
### Required System information

- Node.js version: 20.9.0
- NPM version: 10.1.0
- Strapi version: 4.19.0.
- Database: MariaDB
- Operating system: Linux
- Is your project Javascript or Typescript: Javascript

### Describe the bug

After new user is invited into Strapi with any user role there is error/warning. User is created on the background but registration token is not visible or email is send (Nodemailer). Tested on current project with Strapi 4.19.0, tested on fresh Strapi project with 4.19.0 - doesn't work, and tested on Strapi 4.15.5 - WORKS.

Unfortunately there is no console error log

![image](https://github.com/strapi/strapi/assets/94712794/041b0e3e-2c55-4c54-8d70-9d4e01ae2008)

### Steps to reproduce the behavior

1. Settings -> Users
2. Invite new user
3. Fill in credentials
4. Invite user
5. User is created on the background
6. See a warning error

### Expected behavior

1. Settings -> Users
2. Invite new user
3. Fill in credentials
4. Invite user
5. User is created on the background
6. Email is send / Registration token is displayed

### Screenshots

**On version 4.15.5 works fine:**
![image](https://github.com/strapi/strapi/assets/94712794/4bee8b51-7c90-4f52-85ce-6e7a67295067)

**On version 4.19.0 error:**
![image](https://github.com/strapi/strapi/assets/94712794/f320bee5-dc54-46a6-8531-629cec386b7c)

**Comment by davidpv1** [comment] 2024-01-30 18:07
@derrickmehaffy The problem is that the response from createUser service has two `data` keys in the response. Posible fix inside file: `packages/core/admin/admin/src/pages/Settings/pages/Users/components/NewUserForm.tsx`

![image](https://github.com/strapi/strapi/assets/73908004/6fdb4654-2b1f-40aa-82eb-31c3df5eefa4)

**Comment by davidpv1** [comment] 2024-02-08 14:20
Fixed in version 4.20.0

**Closed** 2024-02-09 17:37 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:admin
