### ISSUE TITLE
Can we bind Upload as Related field in Content Type

### ISSUE THREAD

**Issue by sunithakarthikeyan** [strapi/strapi#4618] opened 2019-11-28 09:09 UTC
- [ ] I have created an RFC on the [Strapi RFC Repo](https://github.com/strapi/rfcs)
- [ ] I have checked for existing RFCs before creating this discussion topic

**Describe the topic**
Created a Content Type "Article" . In Add New Relation wan to add upload . This will be usefull to reuse images in the Articles

**Your suggestions for this topic**
In Add New Relation we can showing only Content Type. In addition to that "Upload" also to be shown 
**Screenshots**
![upload](https://user-images.githubusercontent.com/2913281/69792562-de6f1f80-11ec-11ea-9aa4-8fd4895dd547.png)

**Code snippets**

**Additional context**
Need Article has Many Uploads

**Comment by derrickmehaffy** [comment] 2019-11-28 09:22
closing as duplicate of https://portal.productboard.com/strapi/1-public-roadmap/c/28-media-library-with-edit-crop-resize-capabilities

**Closed by derrickmehaffy** 2019-11-28 09:22 UTC
