### ISSUE TITLE
Relations cannot be set through REST and GraphQL

### ISSUE THREAD

**Issue by WalkingPizza** [strapi/strapi#12238] opened 2022-01-18 22:02 UTC
### Describe the bug

Relations cannot be set through REST and GraphQL unless the user performing the request has `find` access over the related content type.

### Steps to reproduce the behavior

1. Create content types `question` and `answer`;
2. Add a relation between `question` and `answer` to `question`;
3. Give authenticated users `create` access over `question`;
4. Create a `question` via REST or GraphQL and pass `answer` id `x` to the data object;
5. Observe how `question` is created, but `answer` is not set to `x`;
6. Give authenticated users `find` access over `answer`;
7. Re-create the question with the exact same parameters as step 4;
8. Observe how `question` is created and answer is set to `x`.

### Expected behavior

Entries should be created even when users don't have `find` access over the related content type.

### Code snippets

GraphQL query
```graphql
mutation {
    createQuestion(data: { answer: 1 }) {
        data {
            answer {
                data {
                    id
                }
            }
        }
    }
}
```

POST request
```js
await axios.post("<APIURL>", {
    data: {
        answer: 1
    }
})
```

### System

- Node.js version: 14.18.2
- Yarn version: 1.22.17
- Strapi version: 4.0.4
- Database: Postgres
- Operating system: MacOS, Alpine

### Additional context

I believe the issue is related to [this sanitization function](https://github.com/strapi/strapi/blob/0f9b69298b2d94b31b434bd7217060570ae89374/packages/core/utils/lib/sanitize/visitors/remove-restricted-relations.js), that forces a verification over the `find` action even when there is no direct correlation between the scope requested and `find`.

Same issue as #12199, but for every relation and not just on REST.

**Comment by derrickmehaffy** [comment] 2022-01-18 22:03
Possibly related to https://github.com/strapi/strapi/issues/11957 but is not a duplicate

**Comment by derrickmehaffy** [comment] 2022-01-18 23:41
confirmed on v4.0.4, you need the `find` permission on the related entity just to create which absolutely shouldn't happen.

**Comment by stafyniaksacha** [comment] 2022-01-28 23:47
Another use case I get is :
1.  Create content type `order`;
2. Add a `owner` relation between `order` and `user`
3. Override the `create` controller to force the `owner`:
```js
"use strict";

/**
 *  order controller
 */

const { createCoreController } = require("@strapi/strapi").factories;

module.exports = createCoreController("api::order.order", ({ strapi }) => ({
  create(ctx) {
    ctx.request.body = {
      data: {
        ...ctx.request.body.data,
        owner: ctx.state.user.id,
      },
    };

    return super.create(ctx);
  },
}));
```

The `owner` data get removed by the [`sanitizeInput`](https://github.com/strapi/strapi/blob/0dd74c685bc8c8e5660e35546a76348ebe733f56/packages/core/strapi/lib/core-api/controller/collection-type.js#L59) method unless we give the `find` permission to `user`, which we totally do not want to

**Comment by soupette** [comment] 2022-03-14 09:21
@derrickmehaffy it's an intended behaviour you cannot associate a relation if you are not able to "see" it. In order to solve this issue we need to have a new permission implementation IMO

**Comment by derrickmehaffy** [comment] 2022-03-14 23:00
> @derrickmehaffy it's an intended behaviour you cannot associate a relation if you are not able to "see" it. In order to solve this issue we need to have a new permission implementation IMO.

so this would be an enhancement?

**Comment by WalkingPizza** [comment] 2022-03-14 23:17
> @derrickmehaffy it's an intended behaviour you cannot associate a relation if you are not able to "see" it. In order to solve this issue we need to have a new permission implementation IMO.

I understand your point of view, but I don't understand why we are linking creation and retrieval.

If I grant access over `create` to a user, I expect them to be able to create a new entry in its entirety.

Since as you were saying users may not have `find` access over the relations, wouldn't it make more sense if, instead of not letting the user populate the relations, their values were just sanitized in the response?

E.g.
- The model `Restaurant` has a relation with `Address`. I can fetch and create restaurants, but not addresses.
- I create an address referencing an address ID.
- The restaurant is created, the address is linked, but the response I get back does not contain any information regarding its address.

**Comment by soupette** [comment] 2022-03-15 07:40
@WalkingPizza well the idea is that if you are not allowed to `find` a `Restaurant` you cannot assign it to an `Address`. The current implementation of the users & permissions plugin is limited maybe we should refactor it to have a more granular control by introducing field level permissions.

@derrickmehaffy yes that would be an enhancement.

**Comment by mrehacek** [comment] 2022-03-20 19:42
I have been searching for this info for at least an hour, seen the same questions unanswered on strapi forum. I've just started learning and this was the first thing that I wanted to do by customizing the controller. An explanation [in the docs](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#create-an-entry) might be useful for a better experience.

**Comment by danny-dang** [comment] 2022-03-29 11:17
Please add this in the [docs](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest-api.html#create-an-entry).
This feature is so confusing. I have been searching for answer for hours

**Comment by LucaNerlich** [comment] 2022-06-06 12:05
Any updates here? How do we implement something like this now in v4?

We need to create an entry for teammember, which has a 1:1 relation to discount code

```json
"attributes": {
    "user": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "plugin::users-permissions.user"
    },
    "discount": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::discount-code.discount-code"
    },
    "validFrom": {
      "type": "date"
    }
  }
```

```json
"attributes": {
    "title": {
      "type": "string",
      "required": true
    },
    "validUntil": {
      "type": "date",
      "required": true
    },
    "code": {
      "type": "string",
      "required": true,
      "unique": true,
      "minLength": 8,
      "private": true
    },
   // [...]
    "package_types": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::package-type.package-type"
    }
  }
```

This is a hard blocker during our v4 migration right now.

**Comment by LucaNerlich** [comment] 2022-06-06 17:33
> @WalkingPizza well the idea is that if you are not allowed to `find` a `Restaurant` you cannot assign it to an `Address`. The current implementation of the users & permissions plugin is limited maybe we should refactor it to have a more granular control by introducing field level permissions.
> 
> @derrickmehaffy yes that would be an enhancement.

I do understand that approach, however, what's Strapi idea on adding content to a relation that's heavily "locked down" / should not have a public find?

Overwrite that relations find and "clear" its response? Would that stop strapi from stripping the data on create of an item that references this relation?

**Comment by joz3l** [comment] 2022-06-25 22:52
> @WalkingPizza well the idea is that if you are not allowed to `find` a `Restaurant` you cannot assign it to an `Address`. The current implementation of the users & permissions plugin is limited maybe we should refactor it to have a more granular control by introducing field level permissions.
> 
> @derrickmehaffy yes that would be an enhancement.

Before more granularity, this feature feels like a bug for Users & Permissions if `me` is considered. Wouldn't it make sense that `me` would allow creation with relation to yourself without requiring `find`?

**Comment by uschtwill** [comment] 2022-08-01 17:14
I am trying to implement an is-owner policy and this behaviour is, well... not helpful.

@stafyniaksacha What are the side-effects/risks of your work-around?

**Comment by uschtwill** [comment] 2022-08-01 17:43
Also found this approach:

```js
'use strict';

/**
 *  task controller
 */

const { createCoreController } = require('@strapi/strapi').factories;

module.exports = createCoreController('api::task.task', {
    async create(ctx) {
        const user = ctx.state.user;
        const task = await super.create(ctx);
        return await strapi.entityService.update("api::task.task", task.data.id, {
            data: {
                owner: user.id
            }
        });
    },
});
```

Source: https://dev.to/paratron/limit-access-of-strapi-users-to-their-own-entries-298l, thanks Christian! ❤️

**Comment by WalkingPizza** [comment] 2022-08-01 21:44
> Also found this approach:
> 
> ```js
> 'use strict';
> 
> /**
>  *  task controller
>  */
> 
> const { createCoreController } = require('@strapi/strapi').factories;
> 
> module.exports = createCoreController('api::task.task', {
>     async create(ctx) {
>         const user = ctx.state.user;
>         const task = await super.create(ctx);
>         return await strapi.entityService.update("api::task.task", task.data.id, {
>             data: {
>                 owner: user.id
>             }
>         });
>     },
> });
> ```
> 
> Source: https://dev.to/paratron/limit-access-of-strapi-users-to-their-own-entries-298l, thanks Christian! ❤️

Just wanted to point out that although this method works, I wouldn't rely on it too much because you are querying the database twice, once for the creation of the entry and once for the update.

**Comment by Paratron** [comment] 2022-08-15 22:09
Hey, the above code was from me :)

The method I wrote above is afaik the only method to have an owner field for a record right now. About the two queries, that should not be an issue unless you are creating a LOT of records in a short time. I think other workarounds should be used in that case.

I never had any performance issues with the above code, even with an SQLite database.

**Comment by Shadoworker** [comment] 2022-09-14 12:27
Had the same issue .

SOLUTION : 

Just give access to all endpoints for "Authenticated" role. 

![image](https://user-images.githubusercontent.com/13294161/190153134-53cb2860-c2f0-491a-b9ef-56a86e54c360.png)

**Comment by frankadrian** [comment] 2022-11-01 11:18
Has anyone found a solution for graphql? Ive tried adding a middleware which adds the userId to the mutation data. But this still required the User.find permission. eg:

`middlewares: [
            /!**
             * Always overwrite user with the id of the current logged-in user
             *!/
              (resolve, parent, args, context, info) => {
              const { id } = context.state.user
              return resolve(parent, {...args, data: { ...args.data, user: id }}, context, info)
            }
          ]`

 I like @Paratron 's approach, but this only works if you using the REST api.

**Comment by dpoerschke** [comment] 2022-12-02 14:47
> Had the same issue .
> 
> SOLUTION :
> 
> Just give access to all endpoints for "Authenticated" role.
> 

Security from hell - I think in most scenarios you really do not want to do this :-)

**Comment by derrickmehaffy** [comment] 2023-02-02 20:54
Hello,

In order to keep our GitHub issues clean and only related to bug reports I've moved your enhancement / feature requested over to our feedback database.

You can find your request here: https://feedback.strapi.io/feature-requests/p/field-level-permissions-end-user-management

Thanks!

**Closed by derrickmehaffy** 2023-02-02 20:54 UTC
Labels: issue: enhancement, source: plugin:users-permissions

**Comment by mtvphnx** [comment] 2023-02-22 23:24
It helped me solve this problem

![55082f08f3](https://user-images.githubusercontent.com/18383248/220786162-f9d5ba9a-a9fe-4428-82ba-704a36120672.jpg)

**Comment by Paratron** [comment] 2023-02-23 06:19
This would cause a major data breach since now everyone can query and look at all the users in your database. A privacy nightmare.

**Comment by FindMyMission** [comment] 2023-06-24 21:42
Just spent 3 hours trying to figure out why I couldn't set relations on a new entry, trying every possible syntax. Thank God this was the first thing that popped up when I finally decided to google it instead of pouring over the docs. Why in the world is this not mentioned in the "Relations" documentation? 🤦‍♂️

**Comment by Boegie19** [comment] 2023-06-24 21:44
@FindMyMission Have a issue open in the docs repo for this https://github.com/strapi/documentation/issues/1759

**Comment by regiside** [comment] 2023-06-24 21:57
Having just spent hours trying to troubleshoot this "feature". I'd say it should be listed in the REST [API > Relations](https://docs.strapi.io/dev-docs/api/rest/relations) page as a warning or note (see attachment) as it's required for almost every case when attempting to use the API to set relations on a new entry.

<img width="715" alt="Screen Shot 2023-06-24 at 2 50 09 PM" src="https://github.com/strapi/strapi/assets/10213359/e343490f-99f8-4583-adc3-fc76b65801d1">

**Comment by regiside** [comment] 2023-06-24 22:13
I'd still argue that this is a bug and should be addressed. I have a content type (Category) which is publicly findable, but using an API Token to create another type (Post), quietly fails to set the category relation unless I also enable finding Categories from my API Token. Even if I'm trying to set the category using a string like: category: "1".

**Comment by Boegie19** [comment] 2023-06-24 23:11
That is not a bug but a security feature that should be documented and it should have been its own switch but to late for that now

**Comment by jsmb768ypl** [comment] 2023-07-25 18:38
This is what I am using currently, I have to allow the "find" for users not that I want to but its the only way to get the find, findOne and update to work. Wish there was another way :(

`
'use strict';

/**
 * post controller
 */

const { createCoreController } = require('@strapi/strapi').factories;

const utils = require('@strapi/utils');
const { NotFoundError, UnauthorizedError } = utils.errors;

module.exports = createCoreController('api::post.post', {

    async create(ctx) {
        const user = ctx.state.user;

        const post = await super.create(ctx);

        const updated = await strapi.entityService.update("api::post.post", post.data.id, {
            data: {
                owner: user.id
            }
        });

        return result;
    },

    async find(ctx){
        const user = ctx.state.user;  
        
        ctx.query.filters = {
            ...(ctx.query.filters || {}),
            owner: user.id
        };
    
        return super.find(ctx);
    },

    async findOne(ctx){
        const user = ctx.state.user;
        const post = await super.findOne(ctx);
        const ownerID = post.data.attributes.owner.data.id;

        if (ownerID !== ctx.state.user.id){
            return ctx.notFound();
        }

        return post;
    },
    async update(ctx){
        const user = ctx.state.user;
        const post = await super.findOne(ctx);
        const ownerID = post.data.attributes.owner.data.id;

        if (ownerID !== ctx.state.user.id){
            return ctx.notFound();
        }
    
        return post;
    },
    async delete(ctx){
        const user = ctx.state.user;
    
        ctx.query.filters = {
            ...(ctx.query.filters || {}),
            owner: user.id
        };
    
        return super.delete(ctx);
    }
});
`

**Comment by gilbertlucas46** [comment] 2023-10-01 15:07
omy its still an issue

**Comment by arbuznik** [comment] 2023-10-22 02:10
How is this not only not fixed for two year, but not even considered an issue?

Not being able to set `me` as the author of the post, is just ridiculous. 

Upvoting joz3l.

**Comment by ShahriarKh** [comment] 2023-12-20 17:33
This def should be documented.

**Comment by jsmb768ypl** [comment] 2023-12-22 12:55
> How is this not only not fixed for two year, but not even considered an issue?
> 
> Not being able to set `me` as the author of the post, is just ridiculous.
> 
> Upvoting joz3l.

I can understand why they don't set the user who makes entries directly, it really isn't blog specific and if a user field is added but we delete that user then what happens to all the content that the user created as that content is now looking for a creator relationship? (yes I know you could just default it to a user or allow you to select a user to transfer the data to but its really only needed for things like blogs) Setting the user as a relationship yourself if your making a blog is easy, the hard part was restricting the content to just that user. 

If you are doing everything from the front end (such as your front end handles the creation/delete/update via api) then they have actually documented the best way to handle listing items that only you own: https://docs.strapi.io/dev-docs/backend-customization/middlewares#restricting-content-access-with-an-is-owner-policy

That can be expanded upon even further as you can add role checks that will supersede the user checks so if you have people who can edit/delete all posts you can check their role matches a set role and then skip checking the relationship ID.

**Comment by dassiorleando** [comment] 2024-01-07 07:19
I don't know how good it's, but to move quicker while waiting for the feature/improvement, I simply **copied** the [Core API Controller](https://github.com/strapi/strapi/blob/develop/packages/core/strapi/src/core-api/controller/collection-type.ts#L55) code from Strapi source code and made my changes within the lines to add the **owner** field:

```
import { isObject } from 'lodash/fp';
import { errors, parseMultipartData } from '@strapi/utils';
import { factories } from '@strapi/strapi'

// Could be moved elsewhere to make it cleaner
const parseBody = (ctx) => {
    if (ctx.is('multipart')) {
      return parseMultipartData(ctx);
    }

    const { data } = ctx.request.body || {};
  
    return { data };
};

export default factories.createCoreController('api::article.article', ({ strapi }) => ({

    /**
     * I had to copy the core API Controller code to customize it because of this pending issue/feature: https://github.com/strapi/strapi/issues/12238
     * @param ctx 
     * @returns 
     */
    async create(ctx) {     
        await this.validateQuery(ctx);
        const sanitizedQuery = await this.sanitizeQuery(ctx);
  
        const body = parseBody(ctx);
  
        if (!isObject(body.data)) {
          throw new errors.ValidationError('Missing "data" payload in the request body');
        }
  
        const sanitizedInputData: any = await this.sanitizeInput(body.data, ctx);

        // Link the current user to the Article being created
        sanitizedInputData.owner =  ctx.state.user.id;
        // End of custom codes
  
        const entity = await strapi.service('api::article.article').create({
          ...sanitizedQuery,
          data: sanitizedInputData,
          files: 'files' in body ? body.files : undefined,
        });
  
        const sanitizedEntity = await this.sanitizeOutput(entity, ctx);
  
        return this.transformResponse(sanitizedEntity);
    },
 
}));
```

Even if it looks verbose, which could be expected since it's a customization while waiting for the next Strapi update that covers this.

At least, I don't have to perform two queries to add the owner field once the Article is saved.

**Comment by FaijanSaifi99** [comment] 2024-04-03 04:58
> confirmed on v4.0.4, you need the `find` permission on the related entity just to create which absolutely shouldn't happen.

Thanks, it worked for me
