### ISSUE TITLE
Checkboxes not working in the backend list view if the search field was used

### ISSUE THREAD

**Issue by steampixel** [strapi/strapi#3380] opened 2019-06-05 12:21 UTC
**Describe the bug**
If you search something using the search field on the top of any list page in the backend, you cannot select records using the checkboxes inside the list view on the left side. So its impossible to bulk delete these entries. Sometimes I can select one or more of the checkboxes. This problem affect all data types I have created.

**Steps to reproduce the behavior**
1. Setup fresh strapi instance
2. Create a new data type with a text field
3. Create some entries
4. Switch to the list view and search for some entries
5. Try to select one ore more entries using the checkbox

**Expected behavior**
Check one ore more entries and show the bulk edit options.

**System**
- **Node.js version**: 10.6.0
- **NPM version**: 6.1.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: MongoDB
- **Operating system**: Linux

**Comment by soupette** [comment] 2019-06-12 10:05
Hi @steampixel I am unable to reproduce your issue.

Can you try to upgrade your application to beta and check if this is still happening?

**Comment by lauriejim** [comment] 2019-06-14 14:53
Thank to report this issue.

**Comment by soupette** [comment] 2019-06-17 11:56
Hi @steampixel I have just tried with the latest version of Strapi (beta.3) and I am unable to reproduce your issue.

Can you please upgrade your project and check if it still happens?

I'm closing the issue, feel free to reopen if the problem persists.

**Closed by soupette** 2019-06-17 11:56 UTC
Labels: priority: medium, status: confirmed, type: bug 🐛

**Comment by steampixel** [comment] 2019-06-17 13:01
No problem. I will try to upgrade my project this week.
