### ISSUE TITLE
on create adds current dateTime to date fields

### ISSUE THREAD

**Issue by wysher** [strapi/strapi#3675] opened 2019-07-24 16:26 UTC
**Describe the bug**
When creating new entry with date field without date value it changes from undefined to current dateTime.

**Steps to reproduce the behavior**
1. Go to create entry with date field
2. do NOT fill date field
3. save
4. Check created entry

**Expected behavior**
date fields remains undefined. Or even better - allow developer to set default value for date field using model manager:
- empty (default)
- now
- start of today (only date with 00:00 time)

**Code snippets**
I try this to avoid setting current Date and it worked:

```js
// payment/models/Payment.js

  beforeCreate: async (model, attrs, options) => {
    // keep fields undefined
    ['fromDate', 'toDate'].forEach(name => {
      if (attrs[name] === undefined) {
        model.set(name, undefined);
      }
    });
  },
```

**System**
Node.js v10
strapi: v3.0.0-beta.13
- Database: sqlite
- Operating system: Linux Manjaro

**Comment by derrickmehaffy** [comment] 2019-07-29 05:41
This is due to the date field being set as a timestamp value, this will likely be fixed when the date data types are updated to allow for more options.

**Comment by lauriejim** [comment] 2019-07-29 20:37
This is a duplicate of this issue https://github.com/strapi/strapi/issues/2300

**Closed by lauriejim** 2019-07-29 20:37 UTC
