### ISSUE TITLE
Strapi new project command freezes on database connection setting portion of CLI wizard on Windows

### ISSUE THREAD

**Issue by arcee123** [strapi/strapi#1281] opened 2018-05-27 05:22 UTC
**Informations**
- **Node.js version**: 10.2.1
- **npm version**: 6.2.1
- **Strapi version**: 3.0.0-alpha.12.2
- **Database**: 3.6.5
- **Operating system**: Windows Server 2016

**What is the current behavior?**
When selecting the database type (Mongodb in this case), the options for logging on do not appear.  The command prompt sticks and freezes in session.  I have also attempted to run the strapi installer attempting to connect with MySQL, only ending in the same result

**Steps to reproduce the problem**
npm install strapi -g
strapi new testapi
*Selected MongoDB

![image](https://user-images.githubusercontent.com/2981576/40582674-f1436f00-6142-11e8-965b-2fcdc14120bf.png)

**What is the expected behavior?**
strapi asks for the MongoDB login configuration.

**Suggested solutions**
Unknown at this time.  Request diagnosis steps.

**Comment by lauriejim** [comment] 2018-05-27 18:26
Hello @arcee123 ! 
I will need your help to try to understand where you issue come from.

Can you please investigate on this file https://github.com/strapi/strapi/blob/master/packages/strapi-generate-new/lib/before.js
It's where the database connection form is write.
And here https://github.com/strapi/strapi/blob/master/packages/strapi-mongoose/lib/utils/connectivity.js
for the database connection test.

We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and to submit a PR, we’ll appreciate your contribution on this issue! 

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/.github/CONTRIBUTING.md

**Comment by arcee123** [comment] 2018-05-28 03:02
Hi @lauriejim, so it appears like this problem is a Node 10.x.x version compatibility issue.  When I downgraded node back down to 8.x.x, it fired up correctly.  I'll be anxiously waiting for the next upgrade.  Thanks.

**Comment by dertuerke** [comment] 2018-05-29 06:45
Same problem here:
- with Node 10.2.1 it freez after MongoDB
- with Node-LTS 8.11.2 its work

**Comment by opgbaudouin** [comment] 2018-06-03 13:47
Same here 
node 10.2.1 
npm 6.1.0
strapi 3.0.0-alpha.12.2

windows 10 64bit

**Comment by derrickmehaffy** [comment] 2018-06-03 16:01
@dertuerke and @opgbaudouin I am unable to reproduce this issue on Ubuntu using the following versions:

Node 10.1.0
Node 10.2.1
Node 10.3.0

All using NPM 6.1.0, there might be an issue with your locally installed node version, or if you are on windows there are known issues with this. I would recommend if you are on a Windows 10 machine, you install the WSL (Ubuntu I recommend) and do further development on there. 

Or at the very least you can test to confirm the issue is related to windows. The Strapi team generally do all their development work on Mac/Linux thus Windows development support isn't a major priority for them. (And they may not have the machines to test it themselves)

**Comment by derrickmehaffy** [comment] 2018-06-03 16:07
https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by opgbaudouin** [comment] 2018-06-05 11:56
I can confirm NO issues on 

CentOS Linux release 7.5.1804
Strapi version: 3.0.0-alpha.12.2
Node: 10.3.0
npm: 6.1.0

Nonetheless it should be highlighted that as of this version with that combination something broke on Windows 10 - or simply 'limit' the scope of strapi. Obviously no-one will run production stuff with node on a Windows box, but many of us do use it for development.  Up to the team to class as BUG or not :)

**Comment by lauriejim** [comment] 2018-06-05 18:26
If it's work on Node LTS version it's OK.
@arcee123 and @dertuerke can you confirm it works with Node 9 ?

**Comment by arcee123** [comment] 2018-06-07 19:55
ok.  It appears that windows and strapi are not good bedvellows.
Even with Node 9, I run into problems where the strapi installation cannot find python.

As a result, I recommend that this library be tagged to support linux, until a decision is made to support windows specifically.  While I love linux over windows, I recommend we put it in as a feature request for future releases that code be expanded for windows support.

Thanks.

**Comment by ranjithkumar8352** [comment] 2018-06-10 12:36
Quick workaround on Windows 10 - Install Linux bash shell
https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by kevinhaesendonckx** [comment] 2018-07-04 10:57
Issue for me was fixed by downgrading from Node v10 to node v8

**Comment by corinthian13** [comment] 2018-08-17 12:40
+1 kevinhaesendonckx : Yes - NodeJS 8.11.4 works fine with NPM 6.0 and MongoDB 4.0

**Comment by httpiago** [comment] 2018-08-18 02:04
I'm having the same problem. My settings are the same as described by the people above:
Windows 10, Node 10.2.0, Strapi 3.0.0-alpha

I want to test to use in a project but I'm afraid of giving error in production

**Comment by corinthian13** [comment] 2018-08-18 13:50
@httpiago:

If this is the first time that you have used Strapi, then it is far too early to build a real commercial project with it. You must first evaluate it on a private project of your own that may have already been implemented using another technology. Then you can compare performance, stability, etc.

Firstly, you must install [NodeJS version 8](https://nodejs.org/en/download/).
This is the latest stable version that works with Strapi.
Despite the fact that Strapi says [here](https://strapi.io/getting-started) that it needs version 9 or later of NodeJS, it will work with NodeJS 8.
After installing Node 8, checking that your MongoDB is >= 3.4 and your npm is >= 5, follow the instructions in the Getting Started guide to create your first project.
After that you only have the [tutorials](https://strapi.io/documentation/tutorials/) to guide you.
The odd YouTube video that exists are usually old and too badly videoed to clearly see the PC screen.

**Comment by hari-haran** [comment] 2018-09-07 03:11
Works with Node V8! BTW instead of downgrading, install nvm(node version management tool) to have multiple version of nodejs. Cheers!

**Comment by BiscuiTech** [comment] 2018-09-12 20:41
Quick tip: if you're like me and don't want to install nvm nor do you want to change your Node.JS install, simply create the app through your WSL. I made my destination folder into my mnt/c/Users/.../Documents and everything works fine.

**Comment by maturanomx** [comment] 2018-09-12 21:55
Apparently passing the data to the CLI also work: https://github.com/strapi/strapi/issues/1898#issuecomment-418713033

**Comment by witek1902** [comment] 2018-11-14 15:34
I I confirm, works with npm v8 (8.11.3).

**Comment by anubhaavofficial** [comment] 2018-11-25 15:39
"strapi new ......" doesn't work with Node 10.xx or > . Works with 8.xx on windows. So, when will this be fixed?

**Comment by derrickmehaffy** [comment] 2018-11-25 16:18
@anubhaavofficial when the Strapi team have time, it isn't a priority for them right now. You're more than welcome to submit a PR. 😃

**Comment by MohammedFaragallah** [comment] 2018-11-26 00:51
The same problem fixed by git bash as administrator and everything works fine

node -v 10.11.0
npm -v 6.4.1
win10 x64

**Comment by anubhaavofficial** [comment] 2018-11-26 02:43
> 
> 
> @anubhaavofficial when the Strapi team have time, it isn't a priority for them right now. You're more than welcome to submit a PR. 😃

Ok, Thanks, I worked a way around. I used Node 8.xx for installation then switched to Node 11.xx. It is running fine now.

**Comment by eddyystop** [comment] 2018-12-01 01:21
I came across your posts while searching for the same problem with my @feathers-plus/cli. This is what I've tracked down so far.

Yeoman uses queues to schedule prompts together, to schedule writing together, to schedule copy, json, tpl writes together. The prompting runs fine on Node10 including the prompting callback, but the writing task never gets started.

I've received no reponse to my issue from Yeoman https://github.com/yeoman/generator/issues/1098 . No response for 14 days.

**Comment by lauriejim** [comment] 2018-12-01 17:00
Currently Windows has known issues, right now it is recommended that you either use WSL (Windows Subsystem Linux) or setup a Linux virtual machine. Better support will come eventually but right now it is not a priority for core Strapi development.

**Closed** 2019-01-09 15:22 UTC
Labels: priority: low, status: confirmed, type: bug 🐛
