### ISSUE TITLE
Documentation version 4.0.2 breaks

### ISSUE THREAD

**Issue by martijn10kb** [strapi/strapi#11996] opened 2021-12-22 15:38 UTC
### Describe the bug
After updating to 4.0.2 documentation page and settings page wont work (white screen) and I have an error in the console

### Steps to reproduce the behavior
Fresh strapi installation
`yarn strapi install documentation`

### System

- Node.js version: V12.22.7
- Strapi version: 4.0.0
- Operating system: WSL2 Linux 20.4

### Additional context

```
TypeError: Cannot read properties of undefined (reading 'toggleNotification')
    at t.default (main.f8629b79.js:2)
    at c (documentation-page.bcfb45a8.chunk.js:1)
    at M (documentation-page.bcfb45a8.chunk.js:1)
    at li (main.f8629b79.js:2)
    at $u (main.f8629b79.js:2)
    at kl (main.f8629b79.js:2)
    at Pl (main.f8629b79.js:2)
    at jl (main.f8629b79.js:2)
    at xl (main.f8629b79.js:2)
    at main.f8629b79.js:2
    ```

**Comment by derrickmehaffy** [comment] 2021-12-22 19:51
did you update all packages to v4.0.2 because you put `4.0.0` as your Strapi version?

**Comment by ippoippo** [comment] 2021-12-24 05:11
I'm seeing similar behaviour.
I locally updated to 4.0.2.

This is from my `package.json`

```
"dependencies": {
    "@strapi/plugin-i18n": "4.0.2",
    "@strapi/plugin-users-permissions": "4.0.2",
    "@strapi/provider-upload-aws-s3": "^4.0.2",
    "@strapi/strapi": "4.0.2",
    "mysql": "^2.18.1",
    "sqlite3": "5.0.2"
  },
```

Locally, I don't use `@strapi/provider-upload-aws-s3`, this is only for integration server deployments.

After having issues, I tried deleting `.tmp/data.db` and recreated my Admin User.

- `http://localhost:1337/admin` : No problems with this page
- Clicked Content Manager from menu on left: `http://localhost:1337/admin/content-manager/collectionType/plugin::users-permissions.user?page=1&pageSize=10&sort=username:ASC` : No problems with this page.
- `http://localhost:1337/admin/plugins/content-type-builder` : Screen is white. Browser Console log shows:

```
main.89c9e5d9.js:2 TypeError: Cannot read properties of undefined (reading 'allPermissions')
    at g (main.89c9e5d9.js:2)
    at li (main.89c9e5d9.js:2)
    at $u (main.89c9e5d9.js:2)
    at kl (main.89c9e5d9.js:2)
    at Pl (main.89c9e5d9.js:2)
    at jl (main.89c9e5d9.js:2)
    at Ol (main.89c9e5d9.js:2)
    at main.89c9e5d9.js:2
    at t.unstable_runWithPriority (main.89c9e5d9.js:2)
    at Vo (main.89c9e5d9.js:2)
```

- Media Library `http://localhost:1337/admin/plugins/upload?sort=updatedAt:DESC&page=1&pageSize=10` : White page, with error in Console.

```
TypeError: Cannot read properties of undefined (reading 'allPermissions')
    at t.default (main.89c9e5d9.js:2)
    at t.useMediaLibraryPermissions (main.89c9e5d9.js:2)
    at t.MediaLibrary (upload.6ec05b56.chunk.js:1)
    at li (main.89c9e5d9.js:2)
    at $u (main.89c9e5d9.js:2)
    at kl (main.89c9e5d9.js:2)
    at Pl (main.89c9e5d9.js:2)
    at jl (main.89c9e5d9.js:2)
    at Ol (main.89c9e5d9.js:2)
    at main.89c9e5d9.js:2
```

My Chrome Version is: Version 96.0.4664.110 (Official Build) (x86_64)
Running on MacOS: 11.6.1

**Comment by martijn10kb** [comment] 2021-12-24 08:30
> did you update all packages to v4.0.2 because you put `4.0.0` as your Strapi version?

Yes, my package.json contains these packages:
```   
    "@strapi/plugin-documentation": "^4.0.0",
    "@strapi/plugin-i18n": "^4.0.0",
    "@strapi/plugin-users-permissions": "^4.0.0",
    "@strapi/strapi": "^4.0.0",
```

**Comment by soupette** [comment] 2021-12-24 09:19
@martijn10kb can you try locking the version of each package?

```
 "@strapi/plugin-documentation": "4.0.2",
    "@strapi/plugin-i18n": "4.0.2",
    "@strapi/plugin-users-permissions": "4.0.2",
    "@strapi/strapi": "4.0.2",
```

Then can you try : 
- to remove your node_modules and the yarn.lock or the package-lock.json,
- Rebuild your panel completely: `yarn strapi build --clean`

**Comment by ippoippo** [comment] 2021-12-24 10:42
@soupette Out of interest, I created a completely clean strapi install on my personal machine.
I didn't observe any issues that I was getting on my work machine with a pre-existing 4.0.0 build, that had been upgraded to 4.0.2. (ref: https://github.com/strapi/strapi/issues/11996#issuecomment-1000658321)

I'm not using `yarn`, but I will return to my work machine and remove the package-lock.json and try again.

**Comment by ippoippo** [comment] 2021-12-24 11:23
> @soupette Out of interest, I created a completely clean strapi install on my personal machine. I didn't observe any issues that I was getting on my work machine with a pre-existing 4.0.0 build, that had been upgraded to 4.0.2. (ref: [#11996 (comment)](https://github.com/strapi/strapi/issues/11996#issuecomment-1000658321))
> 
> I'm not using `yarn`, but I will return to my work machine and remove the package-lock.json and try again.

Tested and was able to fix my local build.

```
rm package-lock.json
mv node_modules node_modules_bck
# Will now remove node_modules_bck
npm install
npm run build -- --clean
npm run develop
```

Whilst I have a solution to this issue, I'd like to understand what was causing this problem.

Reason is, I've followed these instructions for setting up a build to AWS (https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/deployment/hosting-guides/amazon-aws.html).
I suspect that relying on the pushing my local update to my Github repo is not going result in the AWS deployment correctly updating to 4.0.2.

**Comment by martijn10kb** [comment] 2021-12-24 12:48
`npm run build -- --clean` did the trick for me aswell, it is working again.

Just found anther bug though where the `full_documentation.json` is an valid openapi json, but will an other bug report for that (will search for an existing one first)

**Comment by whitekongdev** [comment] 2022-01-07 10:07
Same here:
I gess the problem is when upgrading the documentation plugin and the previous version is still used within the build.

Remove node_modules,
Remove package_lock.json

```bash
npm i
```
In my case I preferred to delete the "build" folder, rather than run new clean build
```
rm -rf ./buld
npm run develop
```

And working

**Comment by derrickmehaffy** [comment] 2022-01-10 21:41
attempt reproduction in  >= v4.0.4 else close

**Comment by cschuller** [comment] 2022-01-17 14:54
I have the same problem, after doing an upgrade from version v4.0.3 to v4.0.4 this pages have problems:
- media library
- settings / media library
- settings / users-permissions

This pages only show a white page with a console log error

```
main.0499f3a1.js:2 
        
       TypeError: Cannot read properties of undefined (reading 'allPermissions')
    at g (main.0499f3a1.js:2:1806008)
    at li (main.0499f3a1.js:2:1269355)
    at $u (main.0499f3a1.js:2:1321652)
    at kl (main.0499f3a1.js:2:1308893)
    at Pl (main.0499f3a1.js:2:1308821)
    at jl (main.0499f3a1.js:2:1308684)
    at Ol (main.0499f3a1.js:2:1305650)
    at main.0499f3a1.js:2:1255147
    at t.unstable_runWithPriority (main.0499f3a1.js:2:1345952)
    at Ga (main.0499f3a1.js:2:1254924)
```

I have tried to delete the `build` and `.cache` folder and run `npm run build -- clean` without solving the issue.

**Comment by martijn10kb** [comment] 2022-01-17 15:07
@cschuller Did you also try to remove node_modules and doe `npm ci` ?

**Comment by cschuller** [comment] 2022-01-17 15:10
@martijn10kb tried to build with NODE_ENV development and production

**Comment by martijn10kb** [comment] 2022-01-17 15:24
Not sure then maybe @derrickmehaffy knows

**Comment by cschuller** [comment] 2022-01-18 14:38
@martijn10kb 
@derrickmehaffy 
@ippoippo 

I have found a issue and how to reproduce the error: `TypeError: Cannot read properties of undefined (reading 'allPermissions')`
Created a new issue:
https://github.com/strapi/strapi/issues/12232

**Comment by derrickmehaffy** [comment] 2022-01-18 22:38
> @martijn10kb @derrickmehaffy @ippoippo
> 
> I have found a issue and how to reproduce the error: `TypeError: Cannot read properties of undefined (reading 'allPermissions')`
> 
> Documented the problem and possible work-arounds in a new issue: #12232

No need to ping a bunch of people, I get the notification regardless. As to the answer I don't have the slightest idea. We just clarified code ownership of the documentation plugin so it's been assigned to the internal squad who will review the issue.

**Comment by emilieringwald** [comment] 2022-01-28 10:06
Hello! Our team planned to work on the documentation plugin in the coming weeks, we'll keep you posted on the progress!

**Comment by markkaylor** [comment] 2022-02-03 16:25
It looks like the OP's issue was resolved with a clean build using either: `yarn strapi build --clean` or `yarn strapi build --clean`

@cschuller were you able to get it working? If not can you please provide more information about your environment: node version, os, yarn or npm version.

**Comment by cschuller** [comment] 2022-02-03 18:48
@markkaylor No, I have not tested the documentation plugin again... sry

**Comment by derrickmehaffy** [comment] 2022-02-03 19:58
Tested in v4.0.7 and couldn't reproduce, marking as closed until someone else comes with new steps to reproduce.

**Closed by derrickmehaffy** 2022-02-03 19:58 UTC
Labels: issue-type: bug, severity: low, source: plugin:documentation, status: pending reproduction

**Comment by mancku** [comment] 2022-03-10 15:40
I've been able (or should I say I'd been unlucky enough) to reproduce that error in two different computers, one (Strapi version 4.1.0) working with Windows and the other (Strapi version 4.0.5) a WSL 2 Ubuntu.
In both cases the solution was as simple as to delete the package-lock.json file and the node_modules folder and then run
> npm i

In my case I also deleted the .cache and the build folders, but I'm 95% sure they have nothing to do with the problem.

**Comment by derrickmehaffy** [comment] 2022-03-15 21:22
> I've been able (or should I say I'd been unlucky enough) to reproduce that error in two different computers, one (Strapi version 4.1.0) working with Windows and the other (Strapi version 4.0.5) a WSL 2 Ubuntu. In both cases the solution was as simple as to delete the package-lock.json file and the node_modules folder and then run
> 
> > npm i
> 
> In my case I also deleted the .cache and the build folders, but I'm 95% sure they have nothing to do with the problem.

99.999999% of the time it's because of the lock file, npm handles this -really- badly and yarn handles it much better.
