### ISSUE TITLE
There's no way to sort nested data. [Strapi v4]

### ISSUE THREAD

**Issue by JakubLog** [strapi/strapi#12494] opened 2022-02-12 06:34 UTC
### Describe the bug

There's no way to sort nested data (or documentation is uncompleted).

### Steps to reproduce the behavior

1. Create collection (ex. posts) with relation to the other collection (ex. comments).
2. By HTTP client send request to: _/api/posts?populate=*&sort[comments][0]=createdAt:desc_
3. Response should display sorted comments inside posts object but server send 500 error.

### Expected behavior

Response should give me response with sorted nested data, but there's no option to change this.

### System

- Strapi version: 4 (latest)
- Database: Postgres
- Operating system: Windows 10

**Comment by derrickmehaffy** [comment] 2022-02-14 22:22
The structure of your request is a little wrong, you are trying to sort posts by your comments createdAt not sorting the comments.

You will want something like this:
`populate[comments][sort][0]=body%3Adesc`

If if you are using QS to construct this (as it's way easier to read):

```js
const qs = require('qs');
const query = qs.stringify({
  populate: {
    comments: {
      sort: [
        "body:desc"
      ]
    }
  }
}, {
    encodeValuesOnly: true,
  });

console.log(query)
```

---

Example sorting by `body:desc`:
![image](https://user-images.githubusercontent.com/8593673/153956269-c0a9d218-de93-4224-b47f-1b3a1ad9c3e2.png)

Example sorting by `updatedAt:desc`:
![image](https://user-images.githubusercontent.com/8593673/153956467-f30cf513-224c-4d20-8e54-7a271218dbcb.png)


Closing as it's not a bug, just a malformed request

**Closed by derrickmehaffy** 2022-02-14 22:22 UTC
Labels: status: cant reproduce

**Comment by JakubLog** [comment] 2022-02-15 04:18
Okay, thanks for all.
Could you add this syntax or link to the population subpage [in the sort section](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/sort-pagination.html#sorting)? I couldn't find this in the docs and I think that new developers can check in this place for more information in this topic.
