### ISSUE TITLE
Admin.ts not working with NGINX Ingress issue on subfolders hosting

### ISSUE THREAD

**Issue by PaulCorbeau** [strapi/strapi#17400] opened 2023-07-21 08:15 UTC
### Required System information

- Node.js version: 18.17
- NPM version: 9.8.0
- Strapi version: 4.11.5
- Database: postgres
- Operating system: Ubuntu 22.04 LTS
- Is your project Javascript or Typescript: Typescript

### Describe the bug

I would like to deploy strapi on a Kubernetes cluster using nginx ingress.
The application works properly when I'm using subdomains : chart-example.local and chart-example.local/admin
It fails if I try to use subdirectory : chart-example.local/strapi is ok for the root of the application but chart-example.local/strapi/admin fails.
I've got 3 files that are not properly loaded with a 404 error : 

![image](https://github.com/strapi/strapi/assets/8874816/e9381a0f-80db-4d3a-a775-8f4b64c36281)

### Steps to reproduce the behavior

1 - Create a strapi app
2 - Create the docker image
3 - Deploy the application on Kubernetes or Rancher Desktop (I'm using helm)

### Expected behavior

I should be able to reach /admin on subdirectories

### Screenshots

Root page is working properly : 

![image](https://github.com/strapi/strapi/assets/8874816/33f9a87a-aae8-4ee6-8705-59164ffb94d2)

Admin page fails : 

![image](https://github.com/strapi/strapi/assets/8874816/b80cac1a-3eb8-45dd-90ae-ec8105e56f7d)

### Code snippets

This is my admin.ts:

```
export default ({ env }) => ({
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT'),
  },
  transfer: {
    token: {
      salt: env('TRANSFER_TOKEN_SALT'),
    },
  },
});
```

This is my server.ts:
```
export default ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('SERVER_URL', 'http://localhost:1337'),
  proxy: env.bool('IS_PROXIED', true),
  app: {
    keys: env.array("[APP_KEYS1],[APP_KEYS2]", ["testKey1", "testKey2"]),
  },
  webhooks: {
    populateRelations: env.bool('WEBHOOKS_POPULATE_RELATIONS', false),
  }
});
```

This is my ingress configuration : 

```
# Source: order-handling-cms/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-order-handling-cms-backend-ingress
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 32k
  labels:
    environment: "dev"
    system-component: "backend"
    helm.sh/chart: order-handling-cms-1.0.0
    app.kubernetes.io/name: order-handling-cms
    app.kubernetes.io/instance: release-name  
spec:
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /order-handling-cms/(.*)
            pathType: Prefix
            backend:
              service:
                name: release-name-order-handling-cms-backend-svc
                port:
                  name: http
```

This is my ENV:

```
image:
  tag: v1
  repository: cms
  secretName: "order-handling-cms"
  env:
    NODE_ENV: production
    DATABASE_CLIENT: "postgres"
    DATABASE_HOST: "acid-minimal-cluster.default.svc.cluster.local"
    DATABASE_PORT: "5432"
    DATABASE_NAME: "foo"
    SERVER_URL: "http://chart-example.local/order-handling-cms"
```

This is my DOCKERFILE:

```
FROM node:18.17-alpine as BUILD
# Set NODE_ENV to production
ENV NODE_ENV=production
# Install dependencies
RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev nasm bash
# Set Working Directory
WORKDIR /app
# Copy package.json and lock
COPY app/package*.json /app/
# Install dev dependencies 
RUN yarn install
# Copy app
COPY /app /app
# Build app
RUN yarn build


### RELEASE STAGE ####
FROM node:18.17-alpine as RELEASE
# Set NODE_ENV to production
ENV NODE_ENV=production
# Delete node user and add one anew. This ensures that we know the group and user ID.
# See: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#non-root-user
# Also, we install 'tini', which ensures that SIGINT (CTRL-C) is forwarded correctly
# See: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md#handling-kernel-signals
# And: https://github.com/krallin/tini#using-tini
RUN deluser --remove-home node \
  && addgroup -S -g 1001 docker \
  && adduser -S -G docker -u 1001 appuser \
  && mkdir -p /home/appuser/srv/app/.tmp \
  && chown 1001:1001 /home/appuser/srv/app/.tmp
# Switch to newly created user
RUN chown -Rh 1001:1001 /home/appuser/srv/app
USER 1001
# Switch to newly created user's app directory
WORKDIR /home/appuser/srv/app
# Copy app
COPY --from=BUILD --chown=1001:1001 /app /home/appuser/srv/app
# Set default host and expose port 1337 (used by strapi)
ENV HOST=0.0.0.0

ARG SERVER_URL
ENV SERVER_URL=$SERVER_URL

RUN yarn build

EXPOSE 1337
# Start the application
CMD [ "yarn", "start" ]
```

**Comment by vitalijalbu** [comment] 2023-07-21 13:52
I also have this issue, I'm using scalahosting.com with simply p2m runner. 
For deploy I need to uplaod builded folder ? Or just uplaod all strapi files? Thanks.

**Comment by derrickmehaffy** [comment] 2023-07-21 14:50
Per this doc: https://docs.strapi.io/dev-docs/deployment/nginx-proxy#subfolder-unified

Your rewrite rule will need to remove the sub-path before the request is proxied to Strapi such as:

`rewrite ^/test/?(.*)$ /$1 break;`

Not sure how to convert this to k8s ingress config but from what I could see in your config you are just passing `/$1` and not stripping the sub-path prefix out.

Going to close this as it's more of a question and not a bug.

**Closed** 2023-07-21 14:50 UTC
Labels: flag: question

**Comment by derrickmehaffy** [comment] 2023-07-22 18:52
> Hello,
> 
> I read this documentation and I'm already doing that.
> In my ingress I have this part : 
> 
> ´´´
> Spec:
>   rules:
>     - host: "chart-example.local"
>       http:
>         paths:
>           - path: /order-handling-cms/(.*)
>             pathType: Prefix
>             backend:
>               service:
>                 name: release-name-order-handling-cms-backend-svc
>                 port:
>                   name: http
> 
> ´´´
> 
> As you can see, everything taken after /order-handling-cms/ is caught by (.*) and rewritten by /$1
> 
> 

Have you set the server (and optionally the admin) URL keys and rebuilt the admin panel?

**Comment by PaulCorbeau** [comment] 2023-07-25 08:26
Hello,

Yes i did as mentioned here : 

```
export default ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  url: env('SERVER_URL', 'http://localhost:1337'),
  proxy: env.bool('IS_PROXIED', true),
  app: {
    keys: env.array("[APP_KEYS1],[APP_KEYS2]", ["testKey1", "testKey2"]),
  },
  webhooks: {
    populateRelations: env.bool('WEBHOOKS_POPULATE_RELATIONS', false),
  }
});
```
SERVER_URL is working properly when I set : 

http://chart-example.local and http://chart-example.local/admin works
http://test.chart-example.local and http://test.chart-example.local/admin works
http://chart-example.local/test works and http://chart-example.local/test/admin doesn't work.

**Comment by PaulCorbeau** [comment] 2023-07-25 11:49
I did multiple tests found that the url must be passed during the build part.
This is causing an issue because it means that you cannot use the same docker image for multiple deployment in different configurations.

Once the pod is running, If I go into the dist/build folder and open index.html, I can see hardcoded values (in my case /test) :

![image](https://github.com/strapi/strapi/assets/8874816/f91e5932-8ab4-4dda-8165-44a0bf0ea52d)


I would say that this should be considered as "bug". @derrickmehaffy

**Comment by derrickmehaffy** [comment] 2023-07-26 11:08
> I did multiple tests found that the url must be passed during the build part.
> This is causing an issue because it means that you cannot use the same docker image for multiple deployments in different configurations.
> 
> Once the pod is running, If I go into the dist/build folder and open index.html, I can see hardcoded values (in my case /test) :
> 
> ![image](https://github.com/strapi/strapi/assets/8874816/f91e5932-8ab4-4dda-8165-44a0bf0ea52d)
> 
> 
> I would say that this should be considered as "bug". @derrickmehaffy 

Not for now no, we have a feature request about this. 

https://feedback.strapi.io/developer-experience/p/configure-strapi-backend-url-after-build

**Comment by PaulCorbeau** [comment] 2023-07-26 12:12
Ah, good to know :)
thanks for that !

**Comment by vitalijalbu** [comment] 2023-08-11 13:38
> 

hi so basically how to build with url variable? I have strapi on subdomain and my **server.js** config file looks like this:
got 404 error
```
module.exports = ({ env }) => ({
  host: env('HOST', '127.0.0.1'),
  port: env.int('PORT', 3000),
  url: env('BASE_URL'),
  app: {
    keys: env.array('APP_KEYS'),
  },
  webhooks: {
    populateRelations: env.bool('WEBHOOKS_POPULATE_RELATIONS', false),
  },
});
```
