### ISSUE TITLE
Releases not showing locales properly in the list view

### ISSUE THREAD

**Issue by Aurelsicoko** [strapi/strapi#20021] opened 2024-04-03 21:56 UTC
## Bug report

The locales available for an entry as part of a release aren't readable and truncated even though we have enough space to display them.

### Required System information

Node.js version: 18.71.1
NPM version: 9.6.7
Strapi version: 4.22.0
Database: SQLite3
Operating system: MacOS
Is your project Javascript or Typescript: JS

### Steps to reproduce the behavior

1. Create a new Strapi project in Enterprise Edition
4. Create a content-type with at least 1 additional locale.
5. Create a Release
6. Add content to that Release

### Expected behavior

The locales names should be more visible.

### Screenshots

![image](https://github.com/strapi/strapi/assets/4144726/ae93c4e5-146b-4ff0-855e-c01567fbf991)

**Comment by lsarni** [comment] 2024-04-04 12:52
I think it might be a duplicate of #19790

**Comment by simotae14** [comment] 2024-04-10 15:29
Fixed in this PR https://github.com/strapi/strapi/pull/20059, thanks

**Closed by simotae14** 2024-04-10 15:29 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:content-releases, version: 4
