### ISSUE TITLE
Editing and Saving content type fields throws error 400 in admin panel

### ISSUE THREAD

**Issue by RanaOsamaAsif** [strapi/strapi#5095] opened 2020-01-26 09:16 UTC
**Describe the bug**
When I try to add a new field in a content type the admin panel shows "An error occurred" popup and `debug PUT /content-type-builder/content-types/application::ads.ads (308 ms) 400` log message is displayed in the terminal window.

I have tried to downgrade to 18.6 but the error still persists. I also created a new strapi project and copied my api and extensions folders to the new project, but the same issue occurred there as well. 

**Steps to reproduce the behavior**
1. Start in dev mode and go to Content Type Builder
2. Edit an existing content type and add a new field of any type
3. Click on save
4. An error occured message pops up

**Expected behavior**
Adding a new field in a Content Type and saving it afterwards should save the content type with the updated fields. Everything was working like this previously.

**System**
- Node.js version: 13.2.0
- NPM version: 6.13.1
- Yarn version: 1.19.2
- Strapi version: beta 18.6
- Database: mongoDB
- Operating system: Ubuntu 18.04 LTS

**Additional context**
I also tried to create a new administrator and use that to edit content types but the error persisted. It might be an issue with my specific environment but any sort of help to troubleshoot this issue will be very helpful.

Thank you!

**Comment by derrickmehaffy** [comment] 2020-01-27 04:14
@RanaOsamaAsif I cannot reproduce this. We need more information to be able to assist.

**Comment by holtmeister** [comment] 2020-01-31 06:20
@RanaOsamaAsif did you resolve this? am having the same issue

**Comment by mehmetacoskun** [comment] 2020-02-02 19:27
same issue...

**Comment by RanaOsamaAsif** [comment] 2020-02-02 19:36
@holtmeister I wasn't able to find a solution for this issue due to shortage of time. The workaround I used was to manually edit the settings.json(located in api/[MyContentType]/models/) file to edit/add new fields on my existing content types.

**Comment by VGamezz19** [comment] 2020-02-03 11:27
+1

**Comment by holtmeister** [comment] 2020-02-04 00:16
We fixed by putting Strapi into development mode. When finished adding content types, you can move back to production mode.

**Comment by lauriejim** [comment] 2020-02-04 15:31
Hello, can you please share with me the name of the content type you created and the name of the attribute you tried to create.
Thank you, I'm not able to reproduce with information you provide.

**Comment by Gauravp15** [comment] 2020-02-11 16:27
@lauriejim https://github.com/strapi/strapi/issues/3244#issuecomment-578914172

**Comment by Aidoboy** [comment] 2020-02-21 03:33
I'm also having this issue, I'm not familiar with the ins and outs of Strapi though, this is an undergrad capstone project that we're picking up from another semester's team. We (hopefully) upgraded from a few versions back in the Alpha to the latest Beta

**Comment by quitequinn** [comment] 2020-03-05 23:22
I am also having the same issue.

I am using the most current build (19.2), and I don't believe any content types work (text, relational, boolean, etc). I also tried with a variety of attribute names.

<img width="1405" alt="Screen Shot 2020-03-05 at 3 22 01 PM" src="https://user-images.githubusercontent.com/2885870/76034950-1f19bb80-5ef5-11ea-82b8-e23194c9bd93.png">

For now I will follow RanaOsamaAsif's temporary solution.

**Comment by ksenia-b** [comment] 2020-03-06 14:53
I go

> Hello, can you please share with me the name of the content type you created and the name of the attribute you tried to create.
> Thank you, I'm not able to reproduce with information you provide.

@lauriejim, 
The issue occurred each time I tried to update the fields in existing content type if Content-Type starts from the number. 

I am using the strapi version 3.18.7, but tested strapi different versions and got the same issue in strapi 3.18.6, strapi 3.19.3 also.

**Comment by lauriejim** [comment] 2020-03-06 15:36
Hello! Do you have a clear steps to be able to reproduce the issue and to try to find a solution?
Thank you.

**Comment by ksenia-b** [comment] 2020-03-06 16:01
@lauriejim ,

Step1. I created the Content-Type which is started from the number "123test" with one text field. Save d it.
Step2. Opened the Content-Type "123test" and added text field. Pressed "Save".
After that got 400 error.

But, this error does NOT OCCUR when I created the Content-Type "test123", so the content type which started from char character.

**Comment by lauriejim** [comment] 2020-03-06 17:16
Thank you for these steps! It helps a lot.
So due to numbers at the beginning...
And for your information, GraphQL plugin will fail if a Content Type name starts with a number.
So we have to fix this.

**Comment by ksenia-b** [comment] 2020-03-06 17:38
@lauriejim ,

happy to help!

**Comment by quitequinn** [comment] 2020-04-10 02:28
I fixed my issue  by changing the default values of the integer types from strings to numbers. I'm not 100% sure this is a migration issue... but I'm suspicious it was.

```javascript
    "major_version": {
      "type": "integer",
      "default": "0"
    },
```
to
```javascript
    "major_version": {
      "type": "integer",
      "default": 0
    },
```

**Comment by quitequinn** [comment] 2020-04-10 04:24
BUT for floats, you must use strings for default. 

```
    "completeness": {
      "type": "float",
      "default": "0",  // WORKS
    },
```

```
    "completeness": {
      "type": "float",
      "default": 0,  // Doesn't work
    },
```

**Comment by lauriejim** [comment] 2020-06-09 10:28
The issue has been fixed in the stable version of Strapi.
You can no longer create an attributer starting with a number.

**Closed by lauriejim** 2020-06-09 10:28 UTC
Labels: good first issue, priority: medium, status: confirmed, type: bug
