### ISSUE TITLE
Strapi generate new error ...databaseChoice.value

### ISSUE THREAD

**Issue by Dane411** [strapi/strapi#871] opened 2018-03-28 21:43 UTC
**Node.js version**: v6.10.2
**npm version**: 5.8.0
**Strapi version**: 3.0.0-alpha.11.2
**Operating system**: Win 8.1 (x64)
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
error Invalid `new` generator.
C:\Users\Current\AppData\Roaming\npm\node_modules\strapi\node_modules\strapi-generate-new\lib\before.js:125
          ...databaseChoice.value
          ^^^
SyntaxError: Unexpected token ...﻿

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Following steps from https://youtu.be/yMl5IcFHA74
> npm i strapi@alpha -g
> strapi new shop

**What is the expected behavior?**
It should create a base project, but it fails.

**Comment by soupette** [comment] 2018-03-29 08:30
Could you try after upgrading to node v.9?

**Comment by ConsoleTVs** [comment] 2018-03-29 16:51
![image](https://user-images.githubusercontent.com/6124435/38101995-310dd7d6-3382-11e8-989d-12a54de084a7.png)

NPM 5.8.0

**Comment by Dane411** [comment] 2018-04-19 06:15
@lauriejim Yes, I still have this issue, as the only feedback I got was the one of @soupette to upgrade node version, and that didn't fix anything at all, and haven´t messed with source files

**Comment by lauriejim** [comment] 2018-04-19 08:15
Did you change your npm registry ?

**Comment by Dane411** [comment] 2018-04-19 10:31
Nope, should I?

**Comment by lauriejim** [comment] 2018-04-25 15:56
Can you give me the full logs. I don't know where this issue come from.

**Comment by damtsnkff** [comment] 2018-04-30 08:14
@Dane411 which version of node are you using?

As mentioned in the documentation, Strapio requires Node >= 9. _(Requirements [here](https://strapi.io/documentation/getting-started/installation.html#requirements))_

I had the exact same issue because I was using Node > 8.

Tip: If you have to switch between nodes version for different projects, you might like [NVM](https://github.com/creationix/nvm) (a node version manager)

**Comment by Dane411** [comment] 2018-05-07 08:08
@damtsnkff Thank you! Reviewing my previous comments I just realised when I first tried to use strapi I had an outdated node version (v6.10.2), but at some point trying to get this to work, I upgraded everything:
**Node.js version:** v9.10.0
**npm version:** 6.0.0

Now not only strapi still doesnt work, but npm hangs during fetch operation when running install command... View https://github.com/npm/npm/issues/19588 ie.

It´s been a while so can´t really tell how the chain of events was.
My first goal at this time is to restore npm, then will move to strapi. Will provide feedback whether it worked or not, once I get there. :)

**Comment by damtsnkff** [comment] 2018-05-07 13:03
@Dane411 
I can't reproduce, with the same environment as yours. I recorded it, and can't reproduce.
https://youtu.be/mkqk_cqNrFY

Personally using NVM (as mentioned before) really helped me to get save time on my different environments.

Maybe try another version of Node with a new clean install of npm ?

Without any additional informations it's kinda hard to debug. :)

**Comment by Dane411** [comment] 2018-05-08 08:27
Good day @damtsnkff !

I think all the issue was that I didnt update node/npm, as it failed to detect the propagation operator '...'

Then after updating I had an issue with npm https://github.com/npm/npm/issues/20371
I uninstalled Node.js, and tried different versions (8, 9, 10) with NVM, but the issue persisted; so I downloaded strapi and its dependencies with yarn, and then installed with npm the cached packages _(as docs says strapi doesnt plan to add yarn compatibility, as seems yarn downloads but fails to "install" as `strapi -v` would return "unrecognized command strapi")_.

The installation ran smoothly except for:

> error Command failed: node %appdata%\Roaming\nvm\v9.10.0\node_modules\strapi\bin\strapi.js install email

Also https://github.com/strapi/strapi/issues/616 and port 1337 was in use, so changed the port as explained here:
https://strapi.io/documentation/advanced/customize-admin.html
And the bootstrap error dissapeared!

_Welcome.
You successfully created your Strapi application._

**Comment by lauriejim** [comment] 2018-05-08 09:01
It looks come from your machine. I close this issue. Good luck to restore your npm

**Closed by lauriejim** 2018-05-08 09:01 UTC
Labels: type: help wanted 🤷‍♂️

**Comment by fedwatch** [comment] 2018-07-10 16:46
strapi need LTS version .  most people not working in Node 9.

**Comment by derrickmehaffy** [comment] 2018-07-10 16:48
@fedwatch see: https://github.com/strapi/strapi/issues/1296 as to why we aren't using LTS

**Comment by piLinux** [comment] 2018-08-25 15:39
**OS:**
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

**Environment config:**

`nodejs -v`
v10.9.0

`npm -v`
6.2.0

`mongod --version`
db version v4.0.1
git version: 54f1582fc6eb01de4d4c42f26fc133e623f065fb
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1804
    distarch: x86_64
    target_arch: x86_64

**Strapi using deprecated sprintf package:**

`npm install strapi@alpha -g`
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.

**Comment:**
Can you replace _sprintf_ package with _sprintf-js_ package? Thank you.

**Comment by derrickmehaffy** [comment] 2018-08-25 17:13
@pilinux prob should open a new issue for that instead of on an old closed issue :p
