### ISSUE TITLE
Content-manager automatically "opens" all components

### ISSUE THREAD

**Issue by Alexnortung** [strapi/strapi#16195] opened 2023-03-23 16:03 UTC
### Required System information

- Node.js version: 18.13.0
- NPM version: 9.3.1
- Strapi version: 4.8.2
- Database: sqlite / postgres
- Operating system: NixOS / other Linux
- Is your project Javascript or Typescript: typescript

### Describe the bug

When creating a new entry in the content manager it seems that all components are automatically "opened". This is not really desirable if you do not want to fill in the content or some fields in the component are required, then you have to close it again using the trash can icon.

Furthermore, after saving an entry all "closed" components seem to "open" again, which again is not desirable.

~~When running Strapi in development mode everything works as it used to. However after building and running strapi in production the bug seems to happen.~~
I tried doing this in dev mode and observed saw that it worked as usual, but after trying again, the bug seemed to happen there as well.

### Steps to reproduce the behavior

1. Create a component with some fields
2. Create a content-type with that component
3. Go to content manager
4. Click create new entry
5. Observe that the component is now "open"

### Expected behavior

I expected the component to be "closed" when creating an entry. And a gin if I saved the component in a "closed" state, I expected it to remain "closed".

### Screenshots

Creating a new entry in production mode

![billede](https://user-images.githubusercontent.com/1552267/227262538-1ce546ac-62fb-4c15-9848-1a1bb78a05ae.png)

**Comment by f-masche** [comment] 2023-03-23 16:40
This is a duplicate of https://github.com/strapi/strapi/issues/16111. It looks like it has been fixed: https://github.com/strapi/strapi/pull/16158

**Comment by joshuaellis** [comment] 2023-03-23 16:50
What @f-masche said ⭐ ✨ ☝🏼

**Closed by joshuaellis** 2023-03-23 16:50 UTC
