### ISSUE TITLE
Reordering repeatable components inside repeatable components

### ISSUE THREAD

**Issue by sleeporsmile** [strapi/strapi#16328] opened 2023-04-07 13:53 UTC
### Required System information

- Node.js version: 18.15
- NPM version: 9.5
- Strapi version: 4.9
- Database: sqlite
- Operating system: mac os/ubuntu
- Is your project Javascript or Typescript: Javascript

### Describe the bug

Neighboring parent components change their position with reordering of a nested repeatable component in a repeatable parent component.

### Steps to reproduce the behavior

1. Create repeatable component with nested repeatable components in single type
2.  Add a few components as well as nested components in single type
3.  Try reorder nested components
4. See reordering parent components 

### Expected

Reordered nested components only

### Screenshots

https://user-images.githubusercontent.com/43747618/230620753-5dc1ee36-fa01-43aa-a318-88db713d615a.mov

**Comment by joshuaellis** [comment] 2023-04-08 11:40
Duplicate of #15764

**Closed** 2023-04-08 11:40 UTC
Labels: severity: medium, status: duplicate, source: core:content-manager
