### ISSUE TITLE
Reinstall fails due to babel-polyfill / no reinstall possible

### ISSUE THREAD

**Issue by sknat** [strapi/strapi#2042] opened 2018-09-28 13:04 UTC
Node 9.11.2
Npm 5.10.0
Strapi 3.0.0-alpha.14.2
mongo 3.6.7
OS: docker:node:9

**What is the current behavior?**

Getting a `Uncaught Error: only one instance of babel-polyfill is allowed` in JS on localhost:1337/admin 

**Steps to reproduce the problem**

* `strapi new test`
* Git add, commit and push
* Switch machine
* Git clone
* `npm install && npm run postinstall`
* `strapi start`

On localhost:1337/admin get 
````
Uncaught Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (main.js:1)
    at Object../node_modules/strapi-helper-plugin/node_modules/babel-polyfill/lib/index.js (main.js:1)
    at t (main.js:1)
    at Object.<anonymous> (main.js:1)
    at Object../admin/src/app.js (main.js:1)
    at t (main.js:1)
    at ../strapi-helper-plugin/node_modules/css-loader/index.js??ref--0-oneOf-1-2!../strapi-helper-plugin/node_modules/postcss-loader/lib/index.js??ref--0-oneOf-1-3!./node_modules/sanitize.css/sanitize.css (main.js:1)
````

**What is the expected behavior?**

No JS error

**Suggested solutions**

...

**Comment by Restry** [comment] 2018-09-29 02:45
i have resolve this issue after run this 
`
  npm run setup --plugins
`

**Comment by sknat** [comment] 2018-09-29 11:10
@Restry that works, so the whole 'reinstall' script looks like this :

	npm install
	for i in ./plugins/*
	do 
		cd $i
		npm install
		cd ../..
	done
	npm run setup --plugins
	mkdir ./public/uploads

Anyway, it would be cool that this documented somewhere + there is a comprehensive cli that allows for easy install.

**Comment by derrickmehaffy** [comment] 2018-10-01 10:01
@sknat  make sure you also delete the package-lock.json and/or make sure it is in your .gitignore

**Comment by sknat** [comment] 2018-10-01 10:16
@derrickmehaffy I think the point of having package-lock.json is precisely for it to be versioned and have some consistency accross deployments.
Also I spent almost three days trying to make this work so I've obviously tested it.

**Comment by sknat** [comment] 2018-10-01 10:17
I quote "Commit it. It's meant to be committed."
https://www.reddit.com/r/webdev/comments/6mupqt/packagelockjson_not_sure_if_i_should_commit_or_not/

**Comment by maturanomx** [comment] 2018-10-07 05:36
> I quote "Commit it. It's meant to be committed."
> https://www.reddit.com/r/webdev/comments/6mupqt/packagelockjson_not_sure_if_i_should_commit_or_not/

Totally agree!... But the reality is that, right now, strapi doesn't work using `package.log` file. You can see it along the code:
- https://github.com/strapi/strapi/blob/bf355c89110dde969cdc1648d1f959cb1cf3dc7e/package.json#L28
- https://github.com/strapi/strapi/blob/124d0b1ebbebd7dca712cd71a512c0cbac758f1e/scripts/setup.js#L137
- https://github.com/strapi/strapi/blob/60a7e99d11a2ac15317c7aeb378dec5022fb7776/packages/strapi-admin/scripts/preSetup.js#L20
https://github.com/strapi/strapi/blob/4edbef18405c56e51323a7f1685339278eea7bc2/packages/strapi-admin/admin/.gitignore#L7

This is sad, but you should not have this problem if you just run `npm run setup` after the installation. Simpler that you snipped.

I suggest close this issue and open a *feature request*: been able to work with the `package-lock.json` file :stuck_out_tongue:

**Comment by derrickmehaffy** [comment] 2018-10-07 06:44
Yeah me and @Aurelsicoko had a convo about this, the simple solution was just delete it.

**Comment by derrickmehaffy** [comment] 2018-10-08 06:39
Linking this here as an example of a related issue that was fixed by removing the package-lock.json

https://github.com/strapi/strapi/issues/2093#issuecomment-427732041

**Comment by derrickmehaffy** [comment] 2018-10-08 06:40
@sknat can you try by removing that file and ignoring it please? I'm guessing that should fix your issue and we can close this.

**Comment by Aurelsicoko** [comment] 2018-10-09 10:07
@maturanomx As the very beginning, the `package-lock.json` file wasn't working as expected. I know that NPM worked hard to make it better. We could try to reintroduce it in our install workflow.

It was the cause of so many issues and the setup was failed all the time. If it works, I'm okay to use it again.

**Closed** 2018-11-12 10:15 UTC
Labels: type: help wanted 🤷‍♂️
