### ISSUE TITLE
Support for Node > 13.0 version

### ISSUE THREAD

**Issue by SalahAdDin** [strapi/strapi#8074] opened 2020-09-28 07:12 UTC
**Describe the bug**
The last Strapi version does not support `node > 13.0`.

**Steps to reproduce the behavior**

1. Try to update Strapi: 
```
error strapi@3.1.6: The engine "node" is incompatible with this module. Expected version ">=10.16.0 <13". Got "14.10.0"
error Found incompatible module.
```

**Expected behavior**
Despite the compatibility problems, it should be updated.

**System**

- Node.js version: `v14.10.0`
- NPM version: `6.14.7`
- Strapi version: `3.1.6`
- Operating system: `Manjaro Linux x86_64`

**Additional context**
I didn't have problems to update from `3.0.5` to `3.1.4`.

**Comment by MattieBelt** [comment] 2020-09-28 10:38
Hey @SalahAdDin,

Node `v13` or higher isn't supported right now and `v14` isn't LTS until the end of October. 

Duplicate of #7921.

**Closed** 2020-09-28 13:09 UTC
Labels: status: duplicate
