### ISSUE TITLE
Relation displaying entry ID of collection type instead of its number field

### ISSUE THREAD

**Issue by guicalmeida** [strapi/strapi#10150] opened 2021-04-26 20:46 UTC
### Describe the bug

A collection type with only a number field (such as 'year') displays the entry ID instead of value at a relation field.

### Steps to reproduce the behavior

1. Go to Content Type Builder
2. Add a Collection Type (let's call it Year) with only a single field, the number field as an integer, with required and unique checked at the advanced tab.
3. Create another Collection Type (let's call it Project) and add a relation field: Project has one Year
4. Create a Year entry and then create a Project entry. Add a year to the project and see the error: it only shows the entries ID, not the actual year (field integer)

### Expected behavior

The dropdown at the relation field should show the actual entry value, not its ID. 

### Screenshots

[Printscreen](https://i.imgur.com/cKkDvVR.png)

### System

- Node.js version: 14.16.0
- NPM version: 6.14.11
- Strapi version: 3.6.0
- Database: Postgres
- Operating system: Ubuntu 18.04.5 LTS

**Comment by derrickmehaffy** [comment] 2021-04-27 21:00
The action you are seeing is intended, we will set the default display value to the first text based field in the model schema (string, can't remember if you can select rich text or not). 

However if you go into the edit view of your project model (where you would enter data), on the right there is an option to configure the view, select the relational field and you can change what field is shown.

We also have this documented here: https://strapi.io/documentation/user-docs/latest/content-manager/configuring-view-of-content-type.html

Marking as closed as not a bug

**Closed by derrickmehaffy** 2021-04-27 21:00 UTC
