### ISSUE TITLE
Dynamic zone content missing in API 

### ISSUE THREAD

**Issue by iammllr** [strapi/strapi#9451] opened 2021-02-18 17:28 UTC
### Describe the bug

The content from the dynamic zone is missing in REST API, when i link the collection type item with a many to one relation to the component in another dynamic zone.

### Steps to reproduce the behavior

1. Create two collection types "Page" and "Content". Both have one dynamic zone field.
2. Create two components. One component has a relation with "Content".
3. Add a component in the "Content" collection type
4. Add the component with the relation to "Content" to the "Page" collection type
5. Chose the "Content" item from the "Content" collection type
6. The Content from the "Content" collection type is missing in API call

### Expected behavior

Get the content from the dynamic zone.

### System

- Node.js version: v14.13.0
- NPM version: 6.14.8
- Strapi version: v.3.4.6
- Database: sqlite3
- Operating system: Win10 64-Bit

### Additional context

I'am searching a solution for the nested dynamic zones problem.

**Comment by LucaNerlich** [comment] 2021-02-22 17:53
Could you reproduce this and probide a publically available repository which one could clone to easily check this behaviour? Thanks

**Comment by derrickmehaffy** [comment] 2021-02-22 18:47
As mentioned by @LucaNerlich please provide a reproduction repo as I tested this and could not reproduce.

**Comment by shtelzerartem** [comment] 2021-02-24 17:08
Hey @derrickmehaffy , I have been experiencing the same bug. Have just created reproduction development.
Here is the link: https://github.com/shtelzerartem/strapi-dynamic-zone-bug
Just set up mongo instance and edit database.js connection string.  Instances would be created with bootstrap.js.
After that you will need to open 

[http://localhost:1337/graphql](http://localhost:1337/graphql)
Paste there smth like that:
```javascript 
# Write your query or mutation here
query {
  pages {
    Content {
      __typename
      ... on ComponentSectionsSection {
        SectionTitle
        link {
          LinksList {
            Link
            Title
          }
        }
      }
    }
  }
}
```

**Comment by shtelzerartem** [comment] 2021-02-28 12:38
@derrickmehaffy was you able to check a reproduction repo?

**Comment by LucaNerlich** [comment] 2021-03-03 14:22
Same bug here: https://github.com/strapi/strapi/issues/9578

**Comment by alexandrebodin** [comment] 2021-03-03 14:30
We are actively working on finding a fix for this issue.

We removed the behavior of loading components too deeply to avoid circular dependencies. We cannot revert this as it will just recreate the previous bugs.
While fixing this, it create a missing piece in the graphql plugin. It is now missing the data as it is not populated anymore.
To fix this we need to build new resolvers to load the components. 

This is taking some time to do it cleanly but we are making our best to fix this asap

**Comment by TheBit** [comment] 2021-03-09 17:58
@alaminut please take a look to the related issue, specifically [my comment](https://github.com/strapi/strapi/issues/9239#issuecomment-791623492) with link to reproduce repo. There you can find 3.5.2 with the issue present, and 3.4.1 folder (where everything is upgraded to 3.5.2 with GQL plugin downgraded to 3.4.1) - the issue is not happening there

**Comment by alaminut** [comment] 2021-03-09 18:46
@TheBit downgrading GQL plugin to 3.4.1 does not work for me. You can see the issue still happening in here https://github.com/alaminut/strapi-bug-repro - just create a product and celebrity pair, add product to celebrity and query celebrity by id you'll see products > name and products > description properties are not populated.

```
{
  "_id": "6047bee460c46a2d84e9f31d",
  "Fullname": "test celeb",
  "published_at": "2021-03-09T18:31:03.822Z",
  "publicTitle": [
    {
      "Locale": "TR",
      "_id": "6047bee460c46a2d84e9f31e",
      "LocalizedValue": "test celeb title",
      "__v": 0,
      "id": "6047bee460c46a2d84e9f31e"
    }
  ],
  "products": [
    {
      "__component": "sales.product-definition",
      "_id": "6047bee460c46a2d84e9f320",
      "Price": 100,
      "__v": 0,
      "product": {
        "_id": "6047bec760c46a2d84e9f318",
        "systemName": "test",
        "published_at": "2021-03-09T18:30:34.783Z",
        "name": [
          "6047bec760c46a2d84e9f319"
        ],
        "description": [
          "6047bec760c46a2d84e9f31b"
        ],
        "createdAt": "2021-03-09T18:30:31.047Z",
        "updatedAt": "2021-03-09T18:30:34.798Z",
        "__v": 2,
        "id": "6047bec760c46a2d84e9f318"
      },
      "id": "6047bee460c46a2d84e9f320"
    }
  ],
  "createdAt": "2021-03-09T18:31:00.416Z",
  "updatedAt": "2021-03-09T18:31:03.840Z",
  "__v": 2,
  "id": "6047bee460c46a2d84e9f31d"
}
```

**Comment by alexandrebodin** [comment] 2021-03-09 21:32
Hello all. I think I have been able to do a minimal code fix without going into too much refacto. 
-> Here is the PR https://github.com/strapi/strapi/pull/9660

Would be super helpful if any of you can test it out on their project :)

**Comment by TheBit** [comment] 2021-03-10 06:26
@alexandrebodin thanx! As soon I copied/overwritten contents of `type-definitions.js` into node_modules here https://github.com/TheBit/strapi-issue-9239/tree/main/my-project-3.5.2 - I started to get expected response.
I didn't touched strapi-connector-mongoose/lib/mount-models.js though as I'm on PG/bookshelf.
Thanx for quick reaction!

**Comment by TheBit** [comment] 2021-03-10 06:28
@LucaNerlich no, not only mongo, mysql/pg as well, see: https://github.com/strapi/strapi/issues/9239

**Comment by tbanys** [comment] 2021-03-10 07:43
@alexandrebodin sorry for dummy, question, but I'm new to open source development.

How can we could test your proposed changes?

**Comment by shtelzerartem** [comment] 2021-03-10 07:55
@alexandrebodin Due to my tests, and on my repo everything is working and populated: 
- [x] Entity -> DynamicZone -> Component -> RelationField -> Entity -> Repeated Component 
- [x] Entity -> DynamicZone -> Component -> Repeated Component -> RelationField -> Entity -> Repeated Component 

Also I have checked if circular dependencies would lead to crash, but it looks like nothing is being broken.

For me bug is fixed, great job!

**Comment by shtelzerartem** [comment] 2021-03-10 08:43
1. Update strapi and its packages to the latest version (```3.5.2```) 
2. As [TheBid](https://github.com/strapi/strapi/issues/9451#issuecomment-795043934) described, overwrite changed files from PR in your node_module dependencies.
3. Restart strapi and test it.

**Comment by alaminut** [comment] 2021-03-10 09:11
@alexandrebodin confirmed overriding PR files fix all relationship issues. Thanks for patching this!

**Closed** 2021-03-10 09:46 UTC
Labels: severity: medium, source: core:database, status: confirmed, type: bug
