### ISSUE TITLE
Editing strapi user shows 'this is not an email' for regular email addressses

### ISSUE THREAD

**Issue by stijn-gravity** [strapi/strapi#9615] opened 2021-03-05 10:20 UTC
### Describe the bug

This is reproducable for all strapi users in our system. We want to change their role, but can't make any changes because of a validation error on the email, which states that the field value is not an email address (it is). 

We tried changing the default filled email address, but none pass the validation (not even the example email). See the screenshot.

### Steps to reproduce the behavior

Go to settings, users (under administration panel), edit a user and try to save. 

### Expected behavior

Valid email addresses should be accepted by validation.

### Screenshots

<img width="450" alt="Screenshot 2021-03-05 at 11 11 30" src="https://user-images.githubusercontent.com/51475496/110101421-cb5dde80-7da3-11eb-87c8-f359ef787550.png">

### System

- Node.js version: 12
- NPM version: 
- Strapi version: 3.5.2
- Database: mongodb
- Operating system:

**Comment by MattieBelt** [comment] 2021-03-05 10:30
Hey @stijn-gravity, this issue has been fixed, and will be releases in `3.5.3`.

Duplicate of #9554 
Fixed in #9588

**Comment by derrickmehaffy** [comment] 2021-03-08 19:04
Closing as already fixed and will be released in v3.5.3

**Closed by derrickmehaffy** 2021-03-08 19:04 UTC

**Comment by lamualfa** [comment] 2021-03-12 06:56
@derrickmehaffy Still occurs in `v3.5.3`. See https://github.com/strapi/strapi/issues/9628#issuecomment-797279349.
