### ISSUE TITLE
getting error on strapi installation. " something went wrong installing the "sharp" module". with npx

### ISSUE THREAD

**Issue by mosin92** [strapi/strapi#12819] opened 2022-03-12 07:01 UTC
### Screenshots onyarn command
<img width="676" alt="yarn error" src="https://user-images.githubusercontent.com/55811423/158007584-4c7894c2-9790-4443-966d-4946e30bcda1.png">

### Screenshots on npx command
<img width="680" alt="npxerror" src="https://user-images.githubusercontent.com/55811423/158007821-1d34edd8-48ad-4197-ad20-5bad4cc735a5.png">

## Error log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\4 star\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'create-strapi-app@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   'C:\\Users\\4',
1 verbose cli   'star\\AppData\\Roaming\\npm-cache\\_npx\\15036',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v14.15.1
4 verbose npm-session c1681ba2ec765fbd
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for file:star\AppData\Roaming\npm-cache\_npx\15036 Could not install from "star\AppData\Roaming\npm-cache\_npx\15036" as it does not contain a package.json file.
8 http fetch GET 304 https://registry.npmjs.org/create-strapi-app 1232ms (from cache)
9 silly pacote tag manifest for create-strapi-app@latest fetched in 1256ms
10 timing stage:rollbackFailedOptional Completed in 0ms
11 timing stage:runTopLevelLifecycles Completed in 1264ms
12 verbose stack Error: ENOENT: no such file or directory, open 'D:\Mohsin-Work-Space\strapi_demo\star\AppData\Roaming\npm-cache\_npx\15036\package.json'
13 verbose cwd D:\Mohsin-Work-Space\strapi_demo
14 verbose Windows_NT 10.0.22000
15 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\4 star\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "create-strapi-app@latest" "--global" "--prefix" "C:\\Users\\4" "star\\AppData\\Roaming\\npm-cache\\_npx\\15036" "--loglevel" "error" "--json"
16 verbose node v14.15.1
17 verbose npm  v6.14.10
18 error code ENOLOCAL
19 error Could not install from "star\AppData\Roaming\npm-cache\_npx\15036" as it does not contain a package.json file.
20 verbose exit [ 1, true ]

### System

- Node.js version: v14.15.1
- NPM version:
- Strapi version: 4
- Database: sqlite
- Operating system: windows 11

**Comment by derrickmehaffy** [comment] 2022-03-15 16:54
```
7 silly fetchPackageMetaData error for file:star\AppData\Roaming\npm-cache_npx\15036 Could not install from "star\AppData\Roaming\npm-cache_npx\15036" as it does not contain a package.json file.
8 http fetch GET 304 https://registry.npmjs.org/create-strapi-app 1232ms (from cache)
```

Appears to be a cache issue, I'd suggest clearing your npm and yarn caches as there isn't anything we can really do to help you here.

Marking as closed as not a bug

**Closed by derrickmehaffy** 2022-03-15 16:54 UTC

**Comment by VishalKumarRec** [comment] 2023-04-18 10:25
@mosin92  pls share if you found the solution. I am facing same issue.

**Comment by mosin92** [comment] 2023-04-18 10:55
> @mosin92 pls share if you found the solution. I am facing same issue.

@VishalKumarRec  Yes, I resoled that .  Steps : 1) delete nodejs from system 2) install  node js same version or any stable version but while installation , When you click "Next" button once you reach at last "Next" button you will see above a check box. You must to be checked it , it will install all the required packages automatically . which has python config as well . then after you install again strapi . it will work fine.
