### ISSUE TITLE
Connect relation argument not being registered on query API update

### ISSUE THREAD

**Issue by sebscholl** [strapi/strapi#15601] opened 2023-01-27 03:12 UTC
### Required System information

- Node.js version: v18.7.0
- NPM version: 8.15.0
- Strapi version: 4.6.0
- Database: PG
- Operating system: MacOS

### Describe the bug

I want to update a relationship between the File type and a custom type (Content Pack). Following the documentation, my code below should handle the update successfully.

However, no relationship updates are made and no errors are thrown when it's executed.

Meanwhile, `set` operation works, which is why I feel that this may be a bug.

### Steps to reproduce the behavior

1. Create a Content Type with a Has_Many relationship to the Media type.
2. Create a new record with no related media.
3. Try updating a relationship using the query.update API and a connect argument.

### Code snippets

```js
// DOES NOT WORK
  const entry = await strapi.query(CONTENT_PACK_MODEL_UID).update({
    populate: true,
    where: { id: pack.id },
    data: {
      assets: {
        connect: [
          {
            id: file.id
          }
        ],
      },
    },
  });

// WORKS
  const entry = await strapi.query(CONTENT_PACK_MODEL_UID).update({
    populate: true,
    where: { id: pack.id },
    data: {
      assets: {
        set: [
          {
            id: file.id
          }
        ],
      },
    },
  });
```

**Comment by sebscholl** [comment] 2023-01-27 22:02
@joshuaellis I've tested it more and hope that these help with reproducing the behavior. The behavior is consistent across the `query` API and the `entityService` API.

```js
// This update successfully performs SET operation
await strapi.entityService.update(MODEL_UID, 2, {
 data: { 
   assets: [1, 2] 
  }
})

// This update successfully performs SET operation
await strapi.entityService.update(MODEL_UID, 2, {
 data: { 
   assets: {
      set: [1, 2] 
    }
  }
})

// This update successfully performs SET operation
await strapi.entityService.update(MODEL_UID, 2, {
 data: { 
   assets: {
      set: [1, 2] 
    }
  }
})

// This update fails and disconnects ALL relations on field
await strapi.entityService.update(MODEL_UID, 2, {
 data: { 
   assets: {
      connect: [1, 2] 
    }
  }
})

// This update successfully disconnects ALL relations on field
await strapi.entityService.update(MODEL_UID, 2, {
 data: { 
   assets: {
      connect: [1, 2] 
    }
  }
})
```

So essentially, the connect and the disconnect operation are performing identical behaviors.

**Comment by tap2k** [comment] 2023-02-07 13:01
Any updates on this?

**Comment by Marc-Roig** [comment] 2023-02-07 13:19
Hello :) Just in case, by the description I understand the `connect` syntax does not work when using it in `media` attributes.

If that is the case, we still do not support the connect syntax for media attributes, it's something that is on our radar. For now only the set is available.

I will update the documentation mentioning this.

**Comment by Marc-Roig** [comment] 2023-02-07 13:32
This is on our radar but not prioritized for the moment.

I will close the issue for now, if the issue is not related to media but many_to_many relations in general I will reopen it.

**Closed by Marc-Roig** 2023-02-07 13:32 UTC
Labels: issue: bug, severity: medium, source: core:content-manager, status: pending reproduction

**Comment by webpepper** [comment] 2024-10-08 15:44
I've encountered the same or similar issue in Strapi 4.25.13. It's not related to media or uploads in any way. 

EntityService doesn't seem to respect `connect` or `disconnect` as they're described in the official documentation when relations are nested inside of components.

This doesn't work:

```ts
await strapi.entityService.update('api::blah.blah', 123, {
  data: { someComponent: { someRelation: { connect: [1, 2, 3] } } }
});
```

The operation behaves as `set`. So instead of adding new items, everything is reset to the provided list of ids.  `disconnect` does the same.

My workaround is to fetch all existing relation ids first and then use them. Basically, an explicit list of ids needs to be built manually. It's not ideal and a fair bit of extra code, but at least it gets the job done.

```ts
const allIds = await fetchAllIds();

await strapi.entityService.update('api::blah.blah', 123, {
  data: { someComponent: { someRelation:  allIds } }
});
```

I don't know if it's a bug or a feature. But clearly when the documentation states one thing and the code does something else - that's a problem.
