### ISSUE TITLE
Can't update content with date field

### ISSUE THREAD

**Issue by andrewchmr** [strapi/strapi#7498] opened 2020-08-17 07:22 UTC
**Describe the bug**

When I try editing existing content that has date field, then I can't save it because of validation error in date field (however it was not changed). 

**Steps to reproduce the behavior**

Eg. from https://github.com/strapi/strapi-starter-next-blog

1. Go to admin panel
2. Choose one of the existing articles
3. Start editing any field
4. Try to save it
5. See validation error in `published_at` field

**Expected behavior**

There is no validation error at `published_at` (because it was not even changed)

**Screenshots**
![image](https://user-images.githubusercontent.com/43907473/90368784-ecaae780-e06a-11ea-88b2-5deda567ec8d.png)

**System**

- Operating system: MacOS
- Browser: Chrome

**Comment by derrickmehaffy** [comment] 2020-08-17 17:11
Please include all the fields when filling out a bug report on the `System`, In your case I'm guessing you are using an older version of the v3.1.x Strapi versions and this has been fixed in the more recent hotfixes.

Please update to Strapi v3.1.4 and this should resolve your issue, for now I'm marking as closed as without the proper information we cannot reproduce the issue.

**Closed by derrickmehaffy** 2020-08-17 17:11 UTC
