### ISSUE TITLE
npx create-strapi-api fails to install dependencies on Windows

### ISSUE THREAD

**Issue by lucasmike** [strapi/strapi#4370] opened 2019-10-26 10:29 UTC
**Describe the bug**
After running `npx create-strapi-app my-project` the installer hangs forever trying to install @buffetjs/styles@^1.0.0

**Steps to reproduce the behavior**
1. npx create-strapi-app my-project
2. See error: WARN tarball tarball data for @buffetjs/sty;es@^1.0.0 (...) seems to b corrupted. Trying one more time.

The installer cannot move past that point

**System**
- Node.js version: 10.15.3
- NPM version: 6.9.0
- Operating system: Windows 10

**Comment by lauriejim** [comment] 2019-10-27 13:37
Hello @lucasmike !
Can you please share a screenshot with your error please.
I'm not able to reproduce the issue.

**Comment by lucasmike** [comment] 2019-10-30 21:03
Hello @lauriejim !
please see the screenshot attached - it has been hanging on this step for the last 40 minutes or so after the command `npx create-strapi-app my-project --quickstart`

I have also updated node and npm since I reported the issue the first time above but the behaviour is the same. My current system is:

Node v12.13.0
npm 6.12.0
Windows 10


![Untitled](https://user-images.githubusercontent.com/33357688/67898559-70d1c400-fb58-11e9-8b8d-1bb32406ed99.png)

**Comment by gigablack** [comment] 2019-11-07 01:31
I have the same issue.

Node v10.15.1
npm  v6.4.1
Windows 7

**Comment by lauriejim** [comment] 2019-11-12 16:12
Arg it looks coming from Windows...

**Comment by TaylourPinard** [comment] 2019-11-13 17:06
I am also having this issue on Windows

**Comment by luglio7** [comment] 2019-11-30 15:30
Same here on WSL

**Comment by nativewulf** [comment] 2019-12-03 10:34
I have the same issue, did you fix the problem ?

**Comment by lauriejim** [comment] 2019-12-03 12:48
Just tested with my windows machine and all works well.
With yarn and npx...
No idea where it can come from.

**Comment by syedsimanta03** [comment] 2019-12-10 04:30
dependency error on windows 10 latest 64bit. I love strapi & depressed. quick strat or anything related to strapi not working when I type- strapi develop

**Comment by derrickmehaffy** [comment] 2019-12-10 05:19
Just tested on windows 10 and it worked perfect:

![image](https://user-images.githubusercontent.com/8593673/70497919-f9397200-1ad1-11ea-9849-d0727cf0bb9a.png)

**Comment by syedsimanta03** [comment] 2019-12-10 05:36
I used npx but all I get is dependency deprigreted or peer dependency needs to install manually message. Node 10.16 npm 6.x win10 64bit with kaspersky anti virus


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: DMehaffy <notifications@github.com> Date: 10/12/2019  11:19 a.m.  (GMT+06:00) To: strapi/strapi <strapi@noreply.github.com> Cc: syedsimanta03 <syed.simanta06@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [strapi/strapi] npx create-strapi-api fails to install dependencies on Windows (#4370) 
Just tested on windows 10 and it worked perfect:


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/strapi/strapi/issues/4370?email_source=notifications\u0026email_token=AF46ELIH7KMEP24ELLNLCV3QX4RGPA5CNFSM4JFMYGW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGNWTGQ#issuecomment-563833242",
"url": "https://github.com/strapi/strapi/issues/4370?email_source=notifications\u0026email_token=AF46ELIH7KMEP24ELLNLCV3QX4RGPA5CNFSM4JFMYGW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGNWTGQ#issuecomment-563833242",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by syedsimanta03** [comment] 2019-12-10 16:40
Strapi beta is not for all windows users, I love strapi

**Comment by fullmoon6661** [comment] 2019-12-16 19:23
Having same issue
* Node.js version: v10.16.0
* NPM version: 6.9.0
* Operating system: Windows 10

```
/ Installing dependencies:  tarball data for @buffetjs/styles@^1.0.0 (sha512-WYxNm4/w17m95plFURvO4KBrbczwZBARaY53YU+M65y
kAl3hDYOlJWQ4tv0cj6iKcFQuqIZnDlEEcHCAQyI6FQ==) seems to be corrupted. Trying one more time.
```

**Comment by lucasmike** [comment] 2019-12-16 20:39
yes, i have the same problem @fullmoon6661, turns out strapi doesn't work on Windows (I wish it was written somewhere in the docs, I wouldn't have wasted a few hours trying to make it through the installation!)

**Comment by fullmoon6661** [comment] 2019-12-16 21:26
I got it fixed by using VPN. That was very weird.

**Closed** 2019-12-20 10:30 UTC
Labels: type: help wanted 🤷‍♂️

**Comment by rakeshrana15** [comment] 2019-12-30 02:55
facing similar issue on windows 10, with npx create-strapi-app testapp --quickstart.
terminal windows hangs for some time and then exits with error messages as shown below in snapshot,

![Strapi_error1](https://user-images.githubusercontent.com/20044916/71566452-c6393b80-2add-11ea-863d-5052276330c6.png)

**Comment by ravindu-ubeysinghe** [comment] 2020-05-17 16:38
Exiting the app creation with CTRL ^ C and doing `npm i` worked for me.

**Comment by EmreYYZ** [comment] 2020-06-02 22:44
While `npm i` didn't work for me, like all the other solutions in similar topics, I just solve the issue, at least for me. Apparently the culprit was the NodeJS version. I was using the 14.4.0 version, I uninstalled it and installed the 12.17.0 LTS version (Not 12.18.0 LTS because I am using Choco and it doesn't have that package somehow.). I think some of the dependencies won't be installed for 14.4.0 therefore the problem.

**Comment by Boby** [comment] 2021-07-22 04:21
okay one that worked for me, using npx is not installing well in my windows pro 64bit env, but I tried using Yarn and it works rather than npx, so anyone can try shifting to yarn, not sure why npx is failing though
