### ISSUE TITLE
Set the base url, can't open administration panel

### ISSUE THREAD

**Issue by dotkiro** [strapi/strapi#14624] opened 2022-10-14 05:53 UTC
### Required System information

- Node.js version: 16.15.1
- NPM version:8.11.0
- Strapi version:4.4.3
- Database:mydql
- Operating system:windows 12

### Describe the bug

Set the base url, can't open administration panel

### Steps to reproduce the behavior

1. Go to 'config/server.ts'
2. set url: '/cms'
3. npm run develop
4. open browser
5. See error

**Comment by derrickmehaffy** [comment] 2022-10-23 19:50
We recommend using an absolute URL for the server, regardless closing as I'm unable to reproduce.

**Closed by derrickmehaffy** 2022-10-23 19:50 UTC
