### ISSUE TITLE
Cannot create Float or Decimal Fields

### ISSUE THREAD

**Issue by gridviewdesign** [strapi/strapi#2251] opened 2018-11-02 15:59 UTC
**Informations**
- **Node.js version**: 10.12.0
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.14.4.0
- **Database**: MongoDB
- **Operating system**: Windows 10

**What is the current behavior?**
When creating a number field, if "Float" or "Decimal" are selected from within Number Format, the server throws an error on restart: 

```
(node:21608) UnhandledPromiseRejectionWarning: TypeError: Undefined type `Float` at `total`
  Did you try nesting Schemas? You can only nest using refs or arrays.
...
(node:21608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2018-11-02T15:40:31.976Z] debug ⛔️ Server wasn't able to start properly.
[2018-11-02T15:40:31.980Z] error (hook:mongoose) takes too long to load
(hook:mongoose) takes too long to load

```

**Steps to reproduce the problem**
I have a content type that I named "order" and at the moment I have the fields "address: String", "city: String", "state: String", "zipcode: String", products: JSON", "total: Decimal."

The problem arises regardless of whether you try setting a default value or not. 

**What is the expected behavior?**

The field should be created without throwing any errors. 

**Suggested solutions**
I did see a similar issue reported in the now closed issue #1859.  Not sure if this is related to that or not, but maybe it's a place to start.

**Comment by mtmsuhail** [comment] 2018-11-02 22:49
I can confirm this issue.

**Comment by derrickmehaffy** [comment] 2018-11-03 00:02
@gridviewdesign please include your strapi version `Strapi version:`

If you are not on the latest please update to it.

**Comment by mtmsuhail** [comment] 2018-11-03 00:02
3.0.0-alpha.14.4.0

**Comment by mtmsuhail** [comment] 2018-11-03 00:05
The issue solved for me by changing the file **node_modules/strapi-hook-mongoose/lib/utils/index.js**

`module.exports = mongoose => {
  return {
    convertType: mongooseType => {
      switch (mongooseType.toLowerCase()) {
        case 'array':
          return Array;
        case 'boolean':
          return 'Boolean';
        case 'binary':
          return 'Buffer';
        case 'date':
        case 'datetime':
        case 'time':
        case 'timestamp':
          return Date;
        case 'decimal':
          return 'Number';
        case 'float':
          return  'Number';
        case 'json':
          return 'Mixed';
        case 'biginteger':
        case 'integer':
          return 'Number';
        case 'uuid':
          return 'ObjectId';
        case 'email':
        case 'enumeration':
        case 'password':
        case 'string':
        case 'text':
          return 'String';
        default:
      }
    },
  };
};
`

but please consider The library **mongoose-float** can solve one well known problem with JavaScript Number arithmetic imprecise, when, for example, 3.3 * 3 becomes 9.899999999999999, ugly. This can occur when you try to save double values in Mongo DB, it can be balance, discounts etc.

I am converting it manually.

**Comment by mtmsuhail** [comment] 2018-11-03 00:06
The issue solved for me by changing the file node_modules/strapi-hook-mongoose/lib/utils/index.js

`module.exports = mongoose => { return { convertType: mongooseType => { switch (mongooseType.toLowerCase()) { case 'array': return Array; case 'boolean': return 'Boolean'; case 'binary': return 'Buffer'; case 'date': case 'datetime': case 'time': case 'timestamp': return Date; case 'decimal': return 'Number'; case 'float': return 'Number'; case 'json': return 'Mixed'; case 'biginteger': case 'integer': return 'Number'; case 'uuid': return 'ObjectId'; case 'email': case 'enumeration': case 'password': case 'string': case 'text': return 'String'; default: } }, }; };`

but please consider The library mongoose-float can solve one well known problem with JavaScript Number arithmetic imprecise, when, for example, 3.3 * 3 becomes 9.899999999999999, ugly. This can occur when you try to save double values in Mongo DB, it can be balance, discounts etc.

I am converting it manually.

**Comment by mtmsuhail** [comment] 2018-11-03 00:07
The issue solved for me by changing the file node_modules/strapi-hook-mongoose/lib/utils/index.js

`'use strict';

/**
 * Module dependencies
 */

module.exports = mongoose => {
  return {
    convertType: mongooseType => {
      switch (mongooseType.toLowerCase()) {
        case 'array':
          return Array;
        case 'boolean':
          return 'Boolean';
        case 'binary':
          return 'Buffer';
        case 'date':
        case 'datetime':
        case 'time':
        case 'timestamp':
          return Date;
        case 'decimal':
          return 'Number';
        case 'float':
          return  'Number';
        case 'json':
          return 'Mixed';
        case 'biginteger':
        case 'integer':
          return 'Number';
        case 'uuid':
          return 'ObjectId';
        case 'email':
        case 'enumeration':
        case 'password':
        case 'string':
        case 'text':
          return 'String';
        default:
      }
    },
  };
};
`

but please consider The library mongoose-float can solve one well known problem with JavaScript Number arithmetic imprecise, when, for example, 3.3 * 3 becomes 9.899999999999999, ugly. This can occur when you try to save double values in Mongo DB, it can be balance, discounts etc.

I am converting it manually.

**Comment by gridviewdesign** [comment] 2018-11-03 00:47
I can confirm, Im on 3.0.0-alpha.14.4.0 as well.

**Comment by Leo1003** [comment] 2018-11-03 06:33
I also have this issue
#2252

**Comment by lauriejim** [comment] 2018-11-05 14:59
Hello, thank you for reporting this issue. We are currently on another feature and bug fix. Since time is lacking on our side, feel free investigate and submit a PR, we’ll appreciate your contribution on this issue! 

BTW please don't forgot to well template your messages to be more readable. We read more than 300 of your messages every days.

Check out the contributing guide to get started: https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md

**Comment by Leo1003** [comment] 2018-11-05 18:36
I believed that I found the reason of this bug.
#### Mongoose 5.3.8 (2018-10-30):
 - fix(mongoose): handle setting custom type on a separate mongoose global #7158 [c7f216c](https://github.com/Automattic/mongoose/commit/c7f216cb4349ea157ac3279cb6fd32c88892cfa8#diff-f412f4722a52cf22ed3d0a9a694b837d)

So, mongoose-float no longer worked because the custom type is separate now.

**Comment by lauriejim** [comment] 2018-11-07 15:50
@Leo1003 I think you can submit a PR to https://github.com/Vnkitaev/mongoose-float
Thank you for this details. Hope it can be made rapidly to fix our issue.
Thank you @Leo1003

**Comment by Leo1003** [comment] 2018-11-08 17:57
I submitted a [PR](https://github.com/Vnkitaev/mongoose-float/pull/4) to mongoose-float. 
But during the process, I found a new issue about the schema types problem between Decimal and Float.
#2282

**Comment by gianniskarmas** [comment] 2018-11-15 03:19
Still a problem in 14.5 so for future reference and while It took me a few minutes to go line by line as to understand the correct solution in @mtmsuhail 's [post](https://github.com/strapi/strapi/issues/2251?_pjax=%23js-repo-pjax-container#issuecomment-435543117) it is to change the following lines in `node_modules/strapi-hook-mongoose/lib/utils/index.js` to return **'Number'** and not **Decimal/Float**:
```
case 'decimal':
return 'Number';
case 'float':
return 'Number';
```

**Comment by sajjad-shirazy** [comment] 2018-11-15 08:37
Seems mongoose-float merged the fix of @Leo1003, but i don't can deploy yet. any idea?

**Comment by sajjad-shirazy** [comment] 2018-11-17 12:09
it's working in my case by downgrading "strapi-hook-mongoose" in `package.json`:
```javascript
"strapi-hook-mongoose": "3.0.0-alpha.13"
```

**Comment by Leo1003** [comment] 2018-11-17 15:59
The latest release of mongoose-float is 3 years ago. Maybe someone have to ask the author to release next version.

**Comment by sajjad-shirazy** [comment] 2018-11-18 09:22
> The latest release of mongoose-float is 3 years ago. Maybe someone has to ask the author to release the next version.
it's there. thanks @Vnkitaev . seems it's working now.

**Comment by henrych4** [comment] 2018-11-26 11:45
After migrating to strapi@3.0.0-alpha.14.5 with those changes related to mongoose, I find that all old records with field type float cannot be displayed correctly on strapi. 

Does anyone have similar situation?

**Closed** 2018-11-29 11:11 UTC
Labels: priority: high, status: confirmed, type: bug 🐛
