### ISSUE TITLE
Error after installing Graphql

### ISSUE THREAD

**Issue by kimboender1983** [strapi/strapi#3787] opened 2019-08-15 08:32 UTC
**Describe the bug**
When installing Graphql in a Strapi enviroment (either via Command line or marketplace) i get an error: message: 'Syntax Error: Invalid number, expected digit but got: "q".',
  locations: [ { line: 48, column: 4 } ] }
[2019-08-15T08:21:26.717Z] debug ⛔️ Server wasn't able to start properly.
[2019-08-15T08:21:26.718Z] error GraphQLError: Syntax Error: Invalid number, expected digit but got: "q".

**Steps to reproduce the behavior**
1. Create new Strapi install
2. Install Graphql via Command line or marketplace
3. Check terminal for the err described above

**Expected behavior**
Not getting any errors and proceed with using Graphql icw. Strapi.

**Code snippets**
message: 'Syntax Error: Invalid number, expected digit but got: "q".',
  locations: [ { line: 48, column: 4 } ] }
[2019-08-15T08:21:26.717Z] debug ⛔️ Server wasn't able to start properly.
[2019-08-15T08:21:26.718Z] error GraphQLError: Syntax Error: Invalid number, expected digit but got: "q".

**System**
- Node.js version: v11.10.1
- NPM version: 6.10.2
- Strapi version: 3.0.0-beta.15
- Database: SQLlite
- Operating system: MAC

**Additional context**

**Comment by derrickmehaffy** [comment] 2019-08-15 08:35
Closing as this is a duplicate of https://github.com/strapi/strapi/issues/1687#issuecomment-521548882

Please be sure to check for open issues before creating a new one. Thanks!

**Closed by derrickmehaffy** 2019-08-15 08:35 UTC
