### ISSUE TITLE
Make development setup:build work on Windows

### ISSUE THREAD

**Issue by avallete** [strapi/strapi#1837] opened 2018-08-29 14:47 UTC
Related to: https://github.com/strapi/strapi/issues/1828

**What is the expected behavior?**
```
git clone git@strapi... strapi
cd strapi
npm run setup:build
  ...
✅  Strapi has been succesfully installed.
```

At the moment, we have many problems when trying to setup strapi on a windows platform.
This issue is here to:

- List the current problems.
- Discuss the possible solutions.
- Address them in a coordinated way.

## The `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`  error

Related to: issue (#415) 

### Error log:
```
$ npm start

> strapi-admin@3.0.0-alpha.12.6 prestart E:\Proyectos\third-party\strapi\packages\strapi-admin
> node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js

E:\Proyectos\third-party\strapi\packages\strapi-helper-plugin\node_modules\.bin\cross-env:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.12.6 prestart: `node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.12.6 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Woofi\AppData\Roaming\npm-cache\_logs\2018-06-30T19_57_00_377Z-debug.log
```

#### Cause:
detailed here: https://github.com/strapi/strapi/issues/415#issuecomment-416565172

#### Resolution Proposal:
The root of this error is the 'tricky' way the cross-dependencies calls are made into the package.json scripts.
I made some proposals on the linked issue. Not sure any of them is a silver bullet. I'm really open to suggestion for this one.

### Impacted files:

The resolution of this issue will probably need changes on:

```
packages/*/package.json
scripts/createSymlinkDependencies.js (maybe, depending on the solution choose)
```

### Error log:
```
🏗  Building admin...
'IS_MONOREPO' n'est pas reconnu en tant que commande interne
ou externe, un programme executable ou un fichier de commandes.
...
'APP_PATH' n'est pas reconnu en tant que commande interne
ou externe, un programme executable ou un fichier de commandes.
```

#### Cause:
This issue is simply related to the way ENV vars are setted between OS's AND between shells.

We should avoid at the maximum to repose on the shell behavior, since it can hugely change between environment.

#### Resolution Proposal:
So, to achieve this, all the env changes into `package.json` scripts must be preceded with `cross-env`.

All the environment variables who need to be set for some shelljs command should be passed as command option (see: [childProcess](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback)) to avoid shell differences between `export X=Y` || `setenv X=Y` || `env X=Y` || `X=Y`.

### Impacted files:
```
packages/*/package.json
scripts/setup.js
packages/strapi-admin/scripts/setup.js
```

**Comment by Aurelsicoko** [comment] 2018-09-03 14:57
@avallete Thank you for raising this issue! Your analysis seems good to me, I would love to see you trying to implement these changes and ensure it works on Windows. 

However, I'm not sure to understand how you plan to avoid to use Shell variable. Can you give us an example? These variables are very important and required to run the setup and build scripts. Without them, nothing work...

**Comment by avallete** [comment] 2018-09-21 07:40
Hi @Aurelsicoko sorry for the response delay.

As I said, every variables passed by command line into the `package.json` must be passed using `cross-env` package. Which handle the way to set environment variables between OS's.

Also, every 'static' env variables into the installation script, must be passed using the appropriate option into childProcess.

Ex:

```
strapi/setup.js

...
      asyncWatcher(`🏗  Building ${name}...`, `cd ../strapi-${name} && IS_MONOREPO=true npm run build`, false, resolve);
```

The `watcher` option use `shelljs.exec` to execute the command. The error here is that the command contain the UNIX way to set a env variables before executing it.

It should be changed by  something like:

```
const asyncWatcher = (label, cmd, env, withSuccess = true, resolve) => {
  if (label.length > 0) {
    shell.echo(label);
  }

  return shell.exec(cmd, { silent, async: true, env }, (code, stdout, stderr) => {
    if (stderr && code !== 0) {
      console.error(stderr);
      process.exit(1);
    }

    return resolve();
  });
};
...
      asyncWatcher(`🏗  Building ${name}...`, `cd ../strapi-${name} && npm run build`,  { 'IS_MONOREPO': true },  false, resolve);
```

**Comment by Downloaddave** [comment] 2018-09-21 19:13
Hi Guys, I was wondering how things were going with this issue.

I'm currently trying to deploy Strapi to Azure but I keep running into an issue with deployment. I've came across the APP_PATH issue (which I tried to resolve using cross-env) by adding it to the admin/package.json and admin/scripts/setup.js by doing the following...

projectName/admin/package.json
 ```
 "devDependencies": {
    "sanitize.css": "^4.1.0",
    "strapi-helper-plugin": "3.0.0-alpha.14.1.1",
    "strapi-utils": "3.0.0-alpha.14.1.1",
    "cross-env": "latest"

...

 "scripts": {
    "analyze": "node ./node_modules/strapi-helper-plugin/lib/internals/scripts/analyze.js",
    "analyze:clean": "node ./node_modules/strapi-helper-plugin/node_modules/.bin/rimraf stats.json",
    "build": "cross-env APP_PATH=$APP_PATH npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress",
    "build:clean": "node ./node_modules/strapi-helper-plugin/node_modules/.bin/rimraf admin/build",
    "build:dev": "npm run build:dll && node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.prod.babel.js --color -p --progress",
    "build:dll": "cross-env APP_PATH=$APP_PATH node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/node_modules/.bin/webpack --config ./node_modules/strapi-helper-plugin/lib/internals/webpack/webpack.dll.babel.js --color -p --progress",
    "generate": "node ./node_modules/strapi-helper-plugin/node_modules/.bin/plop --plopfile ./node_modules/strapi-helper-plugin/lib/internals/generators/index.js",
    "preanalyze": "npm run analyze:clean",
    "prebuild": "cross-env APP_PATH=$APP_PATH node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js",
    "prepublishOnly": "IS_MONOREPO=true npm run build",
    "presetup": "node ./scripts/preSetup.js",
    "prestart": "node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js",
    "prettier": "node ./node_modules/strapi-helper-plugin/node_modules/.bin/prettier --single-quote --trailing-comma es5 --write \"{admin,__{tests,mocks}__}/**/*.js\"",
    "setup": "node ./scripts/setup.js",
    "start": "node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=development PORT=4000 IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/server",
    "test": "echo \"Error: no test specified\""
  },
```

projectName/admin/scripts/setup.js 
(I couldn't find strapi/setup.js)

```
const build = shell.exec(`cd "${path.resolve(appPath, 'admin')}" && cross-env APP_PATH="${appPath}" npm run build`, {
  silent
});

...

const build = shell.exec(`cd "${path.resolve(plugins, plugin)}" && cross-env APP_PATH="${appPath}" npm run build`, {
        silent
});

```

**Procedure:**
$ strapi new projectName
$ cd projectName
$ strapi start

Things look fine under localhost:1337 -- yay!!

![localhost](https://user-images.githubusercontent.com/828636/45899580-1598a400-bd92-11e8-84cd-5cda5a98605d.png)


Setup _projectName/config/environments/production_ with relevant server.json and database.json information.

Manually delete package-lock.json from:

- package-lock.json 
- admin/package-lock.json
- plugins/**/package-lock.json
- (all package-lock.json?)

Deploy to Azure through a lot of trial and error, eventually it worked but I'm missing some plugin packages. 

![azure](https://user-images.githubusercontent.com/828636/45899603-29dca100-bd92-11e8-991d-722cac1796d8.png)

Note that the Content Type Builder and Configurations are missing in the left menu.

I can see the plugins in the projectName/plugins/ directory on Azure:

![plugins](https://user-images.githubusercontent.com/828636/45900539-f2232880-bd94-11e8-9255-bfb4e7ef2d1d.png)


When I go into Azure (Kudu) and run the following in the wwwroot directory:

$ npm run setup (do I need to run this on the production server?)

I get the following errors:

```
ðŸ•“  The setup process can take few minutes.

ðŸ”¸  Administration Panel
ðŸ“¦  Installing packages...
Packaged installed successfully

> strapi-admin@3.0.0-alpha.14.1.1 setup D:\home\site\wwwroot\admin
> node ./scripts/setup.js

ðŸ—  Building the admin...
internal/modules/cjs/loader.js:583

    throw err;

    ^



Error: Cannot find module 'D:\home\site\wwwroot\admin\node_modules\strapi-helper-plugin\node_modules\.bin\cross-env'

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)

    at Function.Module._load (internal/modules/cjs/loader.js:507:25)

    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)

    at startup (internal/bootstrap/node.js:236:19)

    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.14.1.1 prebuild: `cross-env APP_PATH=$APP_PATH node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-admin@3.0.0-alpha.14.1.1 prebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\local\AppData\npm-cache\_logs\2018-09-21T19_08_05_711Z-debug.log



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.14.1.1 setup: `node ./scripts/setup.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strapi-admin@3.0.0-alpha.14.1.1 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\local\AppData\npm-cache\_logs\2018-09-21T19_08_05_904Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ladot-peoplestreet-cms@0.1.0 setup: `cd admin && npm run setup`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ladot-peoplestreet-cms@0.1.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\local\AppData\npm-cache\_logs\2018-09-21T19_08_05_976Z-debug.log

```


D:\local\AppData\npm-cache\_logs\2018-09-21T19_08_05_711Z-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files (x86)\\nodejs\\10.6.0\\node.exe',
1 verbose cli   'D:\\Program Files (x86)\\npm\\6.1.0\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.1.0
3 info using node@v10.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle strapi-admin@3.0.0-alpha.14.1.1~prebuild: strapi-admin@3.0.0-alpha.14.1.1
6 verbose lifecycle strapi-admin@3.0.0-alpha.14.1.1~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle strapi-admin@3.0.0-alpha.14.1.1~prebuild: PATH: D:\Program Files (x86)\npm\6.1.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\home\site\wwwroot\admin\node_modules\.bin;D:\Program Files (x86)\npm\6.1.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\home\site\wwwroot\admin\node_modules\.bin;D:\Program Files (x86)\npm\6.1.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\home\site\wwwroot\node_modules\.bin;D:\Program Files (x86)\SiteExtensions\Kudu\77.10830.3542\bin\NativeBinaries/x86;D:\home\site\deployments\tools;D:\Program Files (x86)\SiteExtensions\Kudu\77.10830.3542\bin\Scripts;D:\Program Files (x86)\MSBuild\14.0\Bin;D:\Program Files\Git\cmd;D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;D:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0;D:\Program Files\Git\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files (x86)\npm\6.1.0;D:\Program Files (x86)\bower\1.7.9;D:\Program Files (x86)\grunt\0.1.13;D:\Program Files (x86)\gulp\3.9.0.1;D:\Program Files (x86)\funcpack\1.0.0;D:\Program Files (x86)\nodejs\10.6.0;D:\Windows\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Windows\System32\WindowsPowerShell\v1.0\;D:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;D:\Program Files (x86)\dotnet;D:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;D:\Program Files (x86)\Git\cmd;D:\Program Files (x86)\PHP\v5.6;D:\Python27;
8 verbose lifecycle strapi-admin@3.0.0-alpha.14.1.1~prebuild: CWD: D:\home\site\wwwroot\admin
9 silly lifecycle strapi-admin@3.0.0-alpha.14.1.1~prebuild: Args: [ '/d /s /c',
9 silly lifecycle   'cross-env APP_PATH=$APP_PATH node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js' ]
10 silly lifecycle strapi-admin@3.0.0-alpha.14.1.1~prebuild: Returned: code: 1  signal: null
11 info lifecycle strapi-admin@3.0.0-alpha.14.1.1~prebuild: Failed to exec prebuild script
12 verbose stack Error: strapi-admin@3.0.0-alpha.14.1.1 prebuild: `cross-env APP_PATH=$APP_PATH node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (D:\Program Files (x86)\npm\6.1.0\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
12 verbose stack     at EventEmitter.emit (events.js:182:13)
12 verbose stack     at ChildProcess.<anonymous> (D:\Program Files (x86)\npm\6.1.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:182:13)
12 verbose stack     at maybeClose (internal/child_process.js:961:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
13 verbose pkgid strapi-admin@3.0.0-alpha.14.1.1
14 verbose cwd D:\home\site\wwwroot\admin
15 verbose Windows_NT 10.0.14393
16 verbose argv "D:\\Program Files (x86)\\nodejs\\10.6.0\\node.exe" "D:\\Program Files (x86)\\npm\\6.1.0\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
17 verbose node v10.6.0
18 verbose npm  v6.1.0
19 error code ELIFECYCLE
20 error errno 1
21 error strapi-admin@3.0.0-alpha.14.1.1 prebuild: `cross-env APP_PATH=$APP_PATH node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js`
21 error Exit status 1
22 error Failed at the strapi-admin@3.0.0-alpha.14.1.1 prebuild script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]
```


 D:\local\AppData\npm-cache\_logs\2018-09-21T19_08_05_976Z-debug.log

```

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files (x86)\\nodejs\\10.6.0\\node.exe',
1 verbose cli   'D:\\Program Files (x86)\\npm\\6.1.0\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'setup' ]
2 info using npm@6.1.0
3 info using node@v10.6.0
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info lifecycle ladot-peoplestreet-cms@0.1.0~presetup: ladot-peoplestreet-cms@0.1.0
6 info lifecycle ladot-peoplestreet-cms@0.1.0~setup: ladot-peoplestreet-cms@0.1.0
7 verbose lifecycle ladot-peoplestreet-cms@0.1.0~setup: unsafe-perm in lifecycle true
8 verbose lifecycle ladot-peoplestreet-cms@0.1.0~setup: PATH: D:\Program Files (x86)\npm\6.1.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\home\site\wwwroot\node_modules\.bin;D:\Program Files (x86)\SiteExtensions\Kudu\77.10830.3542\bin\NativeBinaries/x86;D:\home\site\deployments\tools;D:\Program Files (x86)\SiteExtensions\Kudu\77.10830.3542\bin\Scripts;D:\Program Files (x86)\MSBuild\14.0\Bin;D:\Program Files\Git\cmd;D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;D:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0;D:\Program Files\Git\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files (x86)\npm\6.1.0;D:\Program Files (x86)\bower\1.7.9;D:\Program Files (x86)\grunt\0.1.13;D:\Program Files (x86)\gulp\3.9.0.1;D:\Program Files (x86)\funcpack\1.0.0;D:\Program Files (x86)\nodejs\10.6.0;D:\Windows\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Windows\System32\WindowsPowerShell\v1.0\;D:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;D:\Program Files (x86)\dotnet;D:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;D:\Program Files (x86)\Git\cmd;D:\Program Files (x86)\PHP\v5.6;D:\Python27;
9 verbose lifecycle ladot-peoplestreet-cms@0.1.0~setup: CWD: D:\home\site\wwwroot
10 silly lifecycle ladot-peoplestreet-cms@0.1.0~setup: Args: [ '/d /s /c', 'cd admin && npm run setup' ]
11 silly lifecycle ladot-peoplestreet-cms@0.1.0~setup: Returned: code: 1  signal: null
12 info lifecycle ladot-peoplestreet-cms@0.1.0~setup: Failed to exec setup script
13 verbose stack Error: ladot-peoplestreet-cms@0.1.0 setup: `cd admin && npm run setup`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files (x86)\npm\6.1.0\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files (x86)\npm\6.1.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid ladot-peoplestreet-cms@0.1.0
15 verbose cwd D:\home\site\wwwroot
16 verbose Windows_NT 10.0.14393
17 verbose argv "D:\\Program Files (x86)\\nodejs\\10.6.0\\node.exe" "D:\\Program Files (x86)\\npm\\6.1.0\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
18 verbose node v10.6.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error ladot-peoplestreet-cms@0.1.0 setup: `cd admin && npm run setup`
22 error Exit status 1
23 error Failed at the ladot-peoplestreet-cms@0.1.0 setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]


```

Any ideas? Thank you in advance.

**Comment by NickBolles** [comment] 2018-09-22 20:18
I just fixed some other issues in #1941 
I'm going to put together a PR for this in the next week hopefully, unless someone else has already started on it. I have a few questions though.

Why were the scripts referencing the executable directly in the first place (the first issue in the OP)? I don't quite understand that right now, and like I said in my other issue I don't want to change it and break something else. 

@Aurelsicoko @avallete  do either of you have any input to the above question?

**Comment by avallete** [comment] 2018-09-23 17:16
@NickBolles I'm not sure to really understand your question.

Just to be sure, you are asking about the scripts we can found into the `script` section of the `packages.json` ?

So you are asking why this kind of lines exists ? :
```
...
 "build:clean": "node ./node_modules/strapi-helper-plugin/node_modules/.bin/rimraf admin/build"
...
```

Or did I have misunderstood what you said ? If so, can you provide an exemple of what you are talking about ?

**Comment by NickBolles** [comment] 2018-09-23 17:35
You have it right. Why does that line reference the script directly instead of like normal like this
```
...
 "build:clean": "rimraf admin/build"
...
```

**Comment by avallete** [comment] 2018-09-23 19:09
Yeah, it also confused me for a while.

I think that's because all the 'helper' packages are located into `strapi-helper-plugin` (and only here) to avoid duplicate dependencies download between plugins.

I will say it's a 'tricky' way to handle this kind of cross-dependencies. Mainly because, the `package.json` dependencies section should list ALL the dependencies that the 'module' use. It can be a major problem since it will make code auditing harder (for people as for automated tools (like `npm audit`)).

@NickBolles I've saw you mitigated this by using `npx` package using the `One-off invocation without local installation` option (at least for rimraf) package. It is certainly a more 'cross-platform' and reliable way to invoke the `rimraf` package. But it still have the same problem I raised before, also I don't see how you precise the package version of `rimraf` that `npx` must run (I'm not an expert of this packages, so I may have missed something).

I don't have a real silver bullet for this problem, but here is some reading that could be interesting on the subject of [peerDependencies](https://nodejs.org/en/blog/npm/peer-dependencies/). @Aurelsicoko  I think we could probably benefit of rethinking the way the plugins dependencies are handled. But that problem should probably be handled in another issue.

**Comment by avallete** [comment] 2018-09-24 08:38
@NickBolles I agree that my point about versions will probably doesn't matter for `rimraf`,  I was just pointing this could impact other packages (for example, let's say we add a new script who must run the tests, we want to be able to control which version of `mocha` is running).

But the problem about the use of undeclared dependencies using this method still occurs. So, in my opinion, even with `npx` which will automatically download the proper dependency if it not exist, we should still declare the dependency into the `devDependencies` section of the `package.json`. That way, we will also adress the version problem, so double benefit.

I agree with your reflexion about `over-optimization`, we should make use of the tools `npm` provide us, like peerDependencies and maybe also take a look on `dedup` command for example.

I said that it should probably be handled in a different issue, because this "root problem", does not affect windows platform only and isn't related with the other "windows specific" issues I have listed into the first post.
Since it will impact the whole project, on every platform, I think we may benefit to address it specifically on another issue to have a better clarity on it, but it's just an idea, would be nice to have the input of a maintainer on this topic.

**Comment by Downloaddave** [comment] 2018-09-25 20:09
Providing some (hopefully) helpful info...

I seem to get this issue on Azure after going to Kudu/SCM (aka Azure Online App Service Terminal) and running the following:

`
$ cd admin
$ npm run setup
D:\home\site\wwwroot\admin\node_modules\strapi-helper-plugin\node_modules\.bin\cross-env:2 basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')") ^^^^^^^ SyntaxError: missing ) after argument list at new Script (vm.js:74:7) at createScript (vm.js:246:10) at Object.runInThisContext (vm.js:298:10)
`

**Comment by NickBolles** [comment] 2018-09-25 20:43
@avallete Gotcha, I totally agree, good analysis. My only question is if the issues can be sperated or not.

I don't think I'm gonna be putting a PR together any time soon for this. We decided to put off modifying the admin panel.

**Comment by Aurelsicoko** [comment] 2018-10-02 12:51
@NickBolles @Downloaddave @avallete 

Here my thoughts about this issue. I'm agree with you on many things. However, there are 2 different states to handle:
- `monorepo setup build`
- `simple build`

The `monorepo setup build` is basically when you clone the repository and you run `npm run setup` at the root of the repository to install and link all the packages together to be able to make a PR and contribute to the project. This step also launchs a build. 

The `simple build` is when you want to re-build the plugin or the administration inside your project.

----

That's why, we have to define precisely the paths inside the `node_modules` folder. Also, our webpack configuration uses the location of the command to determine the application path to set the right configuration for webpack (see https://github.com/strapi/strapi/blob/master/packages/strapi-helper-plugin/lib/internals/webpack/webpack.base.babel.js#L22).

The issue is far more complex, but it doesn't mean there is no better way to do it. I'm pretty sure that the whole workflow can be simple and easier to understand.

**Comment by wemod123** [comment] 2018-11-05 14:00
Is there any updates of this issues?
For some reason, there be some big amout of coder have to work with windows, This issue definitely happend to windows, specifically win10 when I tested.
Is there any plan to fully support win10 of this project.
**We love this project, and hope it could spread widely in possible way, thus windows support are essential!**

**Comment by derrickmehaffy** [comment] 2018-11-05 20:10
@wemod123 they will work on it when they have time, if you on the other hand have free time and want to work on it please do :stuck_out_tongue: 

This is an Alpha, open sourced project that anyone can contribute to, the Strapi team have their hands full working on critical issues and framework changes needed to get a stable release.

To be completely honest windows support is not highly important, you can easily use WSL or a linux virtual machine. The core issue with node and not Strapi itself.

**Comment by NickBolles** [comment] 2018-11-05 20:51
> The core issue with node and not Strapi itself.

I 100% disagree. Node is a cross platform language, which some parts (such as shell commands or file system actions) need platform specific logic, but there are plenty of solutions to this with the node ecosystem, and even built into node.js itself. When you build a project (especially an open source frameworks that you want people to contribute to) you need to use cross platform methods. Period, or you are cutting out a portion of your controbuters and overly complicating things. (The build scripts in strapi are overly complex too but that's a different issue...)

That being said I have a large majority of the needed changes done locally. I can try to put together a PR for this in the coming days, although I expect there to be a little bit of discussion on if the way I'm solving it is the best way or not.

**Comment by derrickmehaffy** [comment] 2018-11-05 21:21
@NickBolles your correct in most of that, however it worked on node 8 (creating the project) and with node 10 it does not. This was due to a change in node, thus it was a node issue. That being said, it can be fixed on the strapi side.

I do agree that strapi is quite complex (sometimes to a fault).

**Comment by NickBolles** [comment] 2018-11-05 22:20
@derrickmehaffy I think you're confused. None of the issues in the OP are about node issues, they are all trying to use BASH syntax in CMD/Powershell. Those are all bad practices with node and it's associated tooling.

There is a seperate issue that you run into when you run `strapi new`, which is documented in #1281, and also has a workaround of passing in the options as parameters (see the[ this comment](https://github.com/strapi/strapi/issues/1898#issuecomment-418713033) for an example of that workaround)

**Comment by derrickmehaffy** [comment] 2018-11-06 07:35
@NickBolles you are right I didn't read the whole thread, my bad.

I'm so used to seeing duplicate windows threads that I jumped to my default response when people don't read open/closed issues, to the point I didn't read the issue haha.

In regards to the plugins, the Strapi team are more or less completely rebuilding the plugins framework right now I believe and over the course of the next month or two.

I do thing cross-env support is important but right now I don't believe the Strapi team have any windows machines to test on (or if any of them are versed in windows) as they all currently use Macs.

I would hope the team will release some info as to their progress to allow us to take a look before the rewrite is finished to convey our thoughts and suggestions. I'll ask the team myself also to see their opinion.

**Comment by alderla** [comment] 2018-11-21 15:05
Had some hard time following Strapi contributing instructions on windows, build always failed at some point. I was using WSL, and my mistake was to use mounted folder /mnt/c/... to clone and build Strapi, after switching to /home/<username>/ everything worked just fine. You can access linux home from explorer:

C:\Users\<username>\AppData\Local\lxss\home

**Comment by anderson916** [comment] 2018-11-29 03:08
> Providing some (hopefully) helpful info...
> 
> I seem to get this issue on Azure after going to Kudu/SCM (aka Azure Online App Service Terminal) and running the following:
> 
> ```
> $ cd admin
> $ npm run setup
> ```
> Response:
> 
> > Packaged installed successfully
> > strapi-admin@3.0.0-alpha.14.1.1 setup D:\home\site\wwwroot\admin
> > node ./scripts/setup.js
> > ðŸ�— Building the admin...
> > D:\home\site\wwwroot\admin\node_modules\strapi-helper-plugin\node_modules.bin\cross-env:2 basedir=$(dirname "$(echo "$0" | sed -e 's,\,/,g')") ^^^^^^^ SyntaxError: missing ) after argument list at new Script (vm.js:74:7) at createScript (vm.js:246:10) at Object.runInThisContext (vm.js:298:10) at Module._compile (internal/modules/cjs/loader.js:657:28) at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10) at Module.load (internal/modules/cjs/loader.js:599:32) at tryModuleLoad (internal/modules/cjs/loader.js:538:12) at Function.Module._load (internal/modules/cjs/loader.js:530:3) at Function.Module.runMain (internal/modules/cjs/loader.js:742:12) at startup (internal/bootstrap/node.js:236:19) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR!
> 
> > strapi-admin@3.0.0-alpha.14.1.1 prebuild: `cross-env APP_PATH=$APP_PATH node ./node_modules/strapi-helper-plugin/node_modules/.bin/cross-env NODE_ENV=production IS_ADMIN=true node ./node_modules/strapi-helper-plugin/lib/internals/scripts/loadAdminConfigurations.js`
> 
> > npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the strapi-admin@3.0.0-alpha.14.1.1 prebuild script.
> 
> > npm ERR! This is probably not a problem with npm. There is likely additional logging output above. npm ERR! A complete log of this run can be found in: npm ERR!

same here.

**Comment by kenberkeley** [comment] 2018-12-13 06:35
Same here

```
Ken@DESKTOP-KGSFTF6 MINGW64 ~/Desktop/strapi-test
$ npm run setup

> strapi-test@0.1.0 setup C:\Users\Ken\Desktop\strapi-test
> cd admin && npm run setup


> strapi-admin@3.0.0-alpha.16 presetup C:\Users\Ken\Desktop\strapi-test\admin
> node ./scripts/preSetup.js


🕓  The setup process can take few minutes.

🔸  Administration Panel
📦  Installing packages...

Packaged installed successfully

> strapi-admin@3.0.0-alpha.16 setup C:\Users\Ken\Desktop\strapi-test\admin
> node ./scripts/setup.js

🏗  Building the admin...
'APP_PATH' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-admin@3.0.0-alpha.16 setup: `node ./scripts/setup.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-admin@3.0.0-alpha.16 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ken\AppData\Roaming\npm-cache\_logs\2018-12-13T06_30_59_930Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! strapi-test@0.1.0 setup: `cd admin && npm run setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strapi-test@0.1.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ken\AppData\Roaming\npm-cache\_logs\2018-12-13T06_31_00_054Z-debug.log
```

**Comment by lauriejim** [comment] 2019-03-13 15:15
Was fixed in this PR https://github.com/strapi/strapi/pull/2709

**Closed by lauriejim** 2019-03-13 15:15 UTC
Labels: priority: medium, status: confirmed, type: bug 🐛
