### ISSUE TITLE
Error when try to create a new project

### ISSUE THREAD

**Issue by fabricadecodigo** [strapi/strapi#8412] opened 2020-10-20 23:01 UTC
### Describe the bug

Error when i try to create a new project.
Error: Module not found: Error: Can't resolve './immer.cjs.production.min.js' in "...node_modules\immer\dist"

The expected file "immer.cjs.production.min.js" doesn't exists.
There is only on file with the name index.js in the path "node_modules\immer\dist"

### Steps to reproduce the behavior

Run the command
 ```
npx create-strapi-app my-project --quickstart
```

### Expected behavior

Create the application

### System

- Node.js version: v12.16.0
- NPM version: 6.14.7
- Strapi version: 3.2.4
- Database:
- Operating system: Windows

### Additional context

All the npm log

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\felip\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.7
3 info using node@v12.16.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle wf-assessoria-eventos@0.1.0~prebuild: wf-assessoria-eventos@0.1.0
6 info lifecycle wf-assessoria-eventos@0.1.0~build: wf-assessoria-eventos@0.1.0
7 verbose lifecycle wf-assessoria-eventos@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle wf-assessoria-eventos@0.1.0~build: PATH: C:\Users\felip\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Projetos\Strapi\wf-assessoria-eventos\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Users\felip\AppData\Local\Android\Sdk\platform-tools;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;ANDROID_SDK_ROOT\tools\bin;ANDROID_SDK_ROOT\platform-tools;ANDROID_SDK_ROOT\emulator;ANDROID_SDK_ROOT\build-tools;C:\Program Files\Git\cmd;C:\Program Files (x86)\Yarn\bin\;C:\Users\felip\AppData\Local\Microsoft\WindowsApps;C:\Users\felip\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\felip\AppData\Roaming\npm;C:\Users\felip\AppData\Local\Yarn\bin;C:\Users\felip\AppData\Local\GitHubDesktop\bin;C:\Program Files\heroku\bin
9 verbose lifecycle wf-assessoria-eventos@0.1.0~build: CWD: C:\Projetos\Strapi\wf-assessoria-eventos
10 silly lifecycle wf-assessoria-eventos@0.1.0~build: Args: [ '/d /s /c', 'strapi build' ]
11 silly lifecycle wf-assessoria-eventos@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle wf-assessoria-eventos@0.1.0~build: Failed to exec build script
13 verbose stack Error: wf-assessoria-eventos@0.1.0 build: `strapi build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\felip\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:321:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\felip\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:321:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid wf-assessoria-eventos@0.1.0
15 verbose cwd C:\Projetos\Strapi\wf-assessoria-eventos
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\felip\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.16.0
19 verbose npm  v6.14.7
20 error code ELIFECYCLE
21 error errno 1
22 error wf-assessoria-eventos@0.1.0 build: `strapi build`
22 error Exit status 1
23 error Failed at the wf-assessoria-eventos@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by bigyanshr** [comment] 2020-10-20 23:27
I am also getting the same error #8413

**Comment by derrickmehaffy** [comment] 2020-10-21 13:59
Unable to reproduce on:
- Linux Mint 20 / Ubuntu 20.04
- MacOS
- Windows 10

My guess is an npm/yarn cache error

**Comment by derrickmehaffy** [comment] 2020-10-21 14:00
Closing as duplicate of: https://github.com/strapi/strapi/issues/8413

**Closed by derrickmehaffy** 2020-10-21 14:00 UTC
Labels: status: can't reproduce
