### ISSUE TITLE
Time to revert to koa-joi-router?

### ISSUE THREAD

**Issue by millette** [strapi/strapi#3465] opened 2019-06-15 20:40 UTC
I notice a couple of years ago there was a router change in #294 but our current router [koa-router-joi](https://www.npmjs.com/package/koa-router-joi) hasn't been updated in 2 years. Since the there have been many changes to the hapi environment (where joi comes from) and [koa-joi-router](https://www.npmjs.com/package/koa-joi-router) is maintained again and using recent depdendencies.

With the current router, ```npm audit``` complains about a few deps, most coming from ```koa-router-joi```.

**Comment by alexandrebodin** [comment] 2019-06-15 20:52
Hi @millette,

Sure thing we have planned on updating a lot of dependencies and switch the router back to a maintained one. I'm closing this as there are no actual bugs caused by this. 

Stay tuned for an upcoming release that will do that update ;)

**Closed** 2019-06-15 20:52 UTC
