### ISSUE TITLE
strapi start crashes after installing graphql plugin

### ISSUE THREAD

**Issue by frot-io** [strapi/strapi#3129] opened 2019-04-14 13:56 UTC
**Informations**
- **Node.js version**: 10.15.1
- **NPM version**: 6.9.0
- **Strapi version**: 3.0.0-alpha.25.2
- **Database**: MongoDB 4.0.8
- **Operating system**: MacOS Mojave 10.14.4
- **(Optional) Link to your Project**: https://github.com/frot-io/homepage 

**What is the current behavior?**

After executing `strapi install graphql`, the command `strapi start` inside the directory `server/` fails with the following output:
```
(node:31914) UnhandledPromiseRejectionWarning: GraphQLError: Syntax Error: Invalid number, expected digit but got: "i".
    at syntaxError (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/error/syntaxError.js:24:10)
    at readDigits (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/lexer.js:464:32)
    at readNumber (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/lexer.js:417:16)
    at readToken (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/lexer.js:303:14)
    at Object.lookahead (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/lexer.js:62:43)
    at Object.advanceLexer [as advance] (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/lexer.js:52:33)
    at expectToken (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/parser.js:1429:11)
    at parseName (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/parser.js:98:15)
    at parseInputValueDef (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/parser.js:906:14)
    at many (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/parser.js:1524:16)
    at parseInputFieldsDefinition (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/parser.js:1069:50)
    at parseInputObjectTypeDefinition (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/parser.js:1053:16)
    at parseTypeSystemDefinition (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/parser.js:723:16)
    at parseDefinition (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/parser.js:144:16)
    at many (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/parser.js:1524:16)
    at parseDocument (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/parser.js:115:18)
    at Object.parse (/Users/flo/Workspace/homepage/server/plugins/graphql/node_modules/graphql/language/parser.js:50:10)
    at Object.addPolymorphicUnionType (/Users/flo/Workspace/homepage/server/plugins/graphql/services/Types.js:155:8)
    at Object.generateSchema (/Users/flo/Workspace/homepage/server/plugins/graphql/services/Schema.js:179:15)
    at Function.initialize (/Users/flo/Workspace/homepage/server/plugins/graphql/hooks/graphql/index.js:148:50)
    at /usr/local/lib/node_modules/strapi/lib/hooks/index.js:19:29
    at after (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:122:39)
    at /usr/local/lib/node_modules/strapi/node_modules/lodash/lodash.js:9999:23
    at Strapi.once (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:133:17)
    at Object.onceWrapper (events.js:277:13)
    at Strapi.emit (events.js:189:13)
    at Strapi.EventEmitter.emit (domain.js:441:20)
    at loadedModule.initialize.call.err (/usr/local/lib/node_modules/strapi/lib/hooks/index.js:32:12)
(node:31914) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31914) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2019-04-14T12:56:19.708Z] debug ⛔️ Server wasn't able to start properly.
[2019-04-14T12:56:19.709Z] error (hook:graphql) takes too long to load
(hook:graphql) takes too long to load
```

**Steps to reproduce the problem**

Following the tutorial _🍝 Cooking a Deliveroo clone with Nuxt (Vue.js), GraphQL, Strapi and Stripe - 🏠 _ until this step: https://blog.strapi.io/cooking-a-deliveroo-clone-with-nuxt-vue-js-graphql-strapi-and-stripe-restaurants-list-part-2-7/#enablinggraphql with two exceptions:

Project folder is name `homepage` instead of `deliveroo-clone-tutorial`

Instead of `restaurant` I created Content Type `post` (none of the fields have additional options or defaults enabled):
![image](https://user-images.githubusercontent.com/14811889/56093815-3ad73600-5ecd-11e9-85ab-e7693f9ea4d1.png)

and added a post stub:
![image](https://user-images.githubusercontent.com/14811889/56093830-7bcf4a80-5ecd-11e9-8fee-94b6803642d2.png)

**What is the expected behavior?**

- `strapi start`starts the application without errors
- GraphQL API is reachable under `http://localhost:1337/graphql`

**Suggested solutions**

- removing `homepage/server/plugins/graphql` completely (and have no GraphQL endpoint)

**Comment by derrickmehaffy** [comment] 2019-04-14 14:35
@frot-io The problem is in your `Post` model. `featured-images` contains a symbol which isn't supported.

Duplicate of: 
https://github.com/strapi/strapi/issues/2477
https://github.com/strapi/strapi/issues/1698

Please see this FAQ Article: https://github.com/strapi/strapi/wiki/Frequently-Asked-Questions#model--field-naming-schemes

**Closed by derrickmehaffy** 2019-04-14 14:35 UTC
