### ISSUE TITLE
Can't query document by nested document's (MULTIPLE) ids

### ISSUE THREAD

**Issue by kosicielPL** [strapi/strapi#5355] opened 2020-02-28 10:00 UTC
**Describe the bug**
Can't query document by nested document's (MULTIPLE) ids

**Steps to reproduce the behavior**
1. Setup Strapi 3.0.0-beta.18.6 or 3.0.0-beta.18.7 (I've tried on both versions) on windows, with mongoDB and mongoose
2. Using admin panel, create following content types: 
- Blog <- one-to-many -> Articles
- Article <- many-to-many -> Tags
- Tags have property "name" (short string)
3. Create one blog and few articles having some tags
4. Query Articles by multiple tag ids in mongoose-fashion way (see code snippets below)
5. In every scenario query returns empty array

**Expected behavior**
Using sample query: 
`{host}/blogs/{blogId}/articles?tags.name={sampleTagName}`

And code below:: 
```
// route: {host}/blogs/:blogId/articles
// sample API call (as mentioned above): {host}/blogs/{blogId}/articles?tags.name={sampleTagName}

// controller
module.exports = {
    async search(ctx) {
        const blogId = ctx.params.blogId;
        const query = ctx.query;

        const entities = await strapi.services.article.search(blogId, query);

        // sanitize entities and return result
        // ...
    }
};

// service
module.exports = {
    async search(blogId, query) {
        const find = {
            blog: blogId,
        };

        const filters = strapi.utils.models.convertParams('article', query);

        // create populate object
        // ...
        const populate = {};
        // ...

        let tagIds = [];
        if (filters.where.tags) { // <-- if present, query "?tags.name={sampleTag}" successfully lands in filters.where.tags object
            const tags = await Tag
                .find(filters.where.tags); // <-- if so, we want to retrieve tags by given criteria (MongoDB doesn't support joins)
            //   ^^^^ tags are retrieved properly/no issue here

            tagIds = tags.map(t => t._id); // <-- then we map tags to array of _ids

            find.tags = { $in: tagIds }; // <-- we attach array of tag _ids to "find" object, with intention to pass it as argument to Article.find() method
            //            ^^^ we use mongoose syntax

            delete filters.where.tags; // <-- as we do not want this property to land in Article.find().where() method, we delete filters.where.tags property
        }

        return await Article
            .find(find)
            .where(filters.where)
            .sort(filters.sort)
            .start(filters.start)
            .limit(filters.limit)
            .populate(populate);
        // no matter what we do - we get empty array in the end
    }
};
```
... I want to retrieve only Articles with specified tags.

**What else have I tried** 

No matter with what syntax will I experiment, results are the same. 

1. Direct reference to array of tag ids
```
tagIds = tags.map(t => t._id);
find.tags = tagIds;
```

2. Use of mongoose.Types.ObjectId
```
const mongoose = require('mongoose');
tagIds = tags.map(t => mongoose.Types.ObjectId(t._id));

find.tags = tagIds; // find.tags = { $in: tagIds } also won't work
```

3. Id (instead of _id) reference
```
tagIds = tags.map(t => t.id);
find.tags = tagIds; // find.tags = { $in: tagIds } also won't work
```

**System**
- Node.js version: 12.14.1
- NPM version: 6.13.4
- Strapi version: I've tried on both 3.0.0-beta.18.6 and 3.0.0-beta.18.7
- Database: MongoDB
- Operating system: Windows 10

**Additional context**
Yes, I've been looking for help literally everywhere, before I got myself here.

**Comment by kosicielPL** [comment] 2020-02-28 11:43
I forgot to mention one more thing. 

In case of one-to-many relationship, passing document Id directly to find() method works perfeclty:

```
const find = {
    blog: blogId, // <-- this works! Function find() there fore retrieves only articles that belong to one blog
};
```

**Comment by deyceg** [comment] 2020-04-27 19:21
Duplicate of #4353 possibly

**Comment by lauriejim** [comment] 2020-05-09 17:53
Hello, can you try with the last version of Strapi please.
Minimum `v3.0.0-beta.20.3`

**Comment by lauriejim** [comment] 2020-06-09 15:13
Closing, I don't have any info

**Closed by lauriejim** 2020-06-09 15:13 UTC
