### ISSUE TITLE
Tracking Issue - Some words are not handled well for Model names (Pluralization, ect) and reserved words

### ISSUE THREAD

**Issue by johannpinson** [strapi/strapi#1198] opened 2018-05-15 15:28 UTC
# Edited by @derrickmehaffy on 2021/03/29

This issue has been converted to a global tracking issue regarding certain english or other language words that fail to work when building models. There are various examples, and for the moment the workarounds mean excluding these words from use and doing things like:

`news` => `newsItem` ect 

---

**Informations**
- **Node.js version**: 8.9.1
- **npm version**: 5.6.0
- **Strapi version**: 3.0.0-alpha.12.1.3
- **Database**: Mongo v3.4.9
- **Operating system**: MacOS 10.13.4

**What is the current behavior?**
When I create a new content type with a name which have the same plural version, the API generate will loop into a 500

**Steps to reproduce the problem**
- Create a new content type named "Fish" (or "News")
- Use a GraphQL IDE or look the terminal
![capture d ecran 2018-05-15 a 16 56 39](https://user-images.githubusercontent.com/2202989/40065254-a6476586-5861-11e8-97b9-66f6e377c014.png)

**What is the expected behavior?**
The problem is that some english words have a specific plural behavior (like child/children) or have the same orthograph
As example : https://github.com/atteo/evo-inflector/blob/master/src/main/java/org/atteo/evo/inflector/English.java#L131

**Suggested solutions**

**Best solution:**
Disallow to use "words" which can have an different plural/single mode (ex: fish, news, etc.)

Another solution is to add a flag "all" in front, a.k.a "allFish" (but it add a 2nd behavior so i don't think it's the best solution

---

- [x] I'm sure that this feature hasn't already been referenced.

**Comment by Aurelsicoko** [comment] 2018-05-15 16:04
Great question... It's complicated because we're going to follow the [OpenCRUD specs](https://github.com/opencrud/opencrud/) and this case doesn't seem to be handled. I'm going to ask how we should deal with this case.

**Comment by johannpinson** [comment] 2018-05-15 16:42
I know, i already have the problem with Prisma (who manages the OpenCRUD docs) about this problem: https://github.com/prismagraphql/prisma/issues/1772
In fact, the use a scala library to detect singular/plural words and blocks some of them.

**Comment by johannpinson** [comment] 2018-05-16 09:04
@Aurelsicoko 
Actually, Prisma blocks words which are invariable.

And in the [OpenCRUD doc](https://github.com/opencrud/opencrud/blob/master/spec/2-relational/2-2-queries/2-2-1-toplevel.md#naming), it talks about using the java library `evo-inflector` (because Prisma is built with Scala/Sangria) and it lists 51 words invariable.

Moreover, it looks like Strapi use the `pluralize` lib, so we can detect if the word have a plural way.

**Comment by Aurelsicoko** [comment] 2018-05-17 08:34
I understand but blocking words is not an optimal solution because as a workaround we can add the prefix `all` for these words or change the specs to make sure the plural queries are harmonized whatever the word used. It should be specified in the specs.

**Comment by Aurelsicoko** [comment] 2018-08-17 12:32
@MartinMuzatko Try to find another word for this model until we find a viable solution.

**Comment by MartinMuzatko** [comment] 2018-08-17 19:59
Sure - already did. I just hate to abuse the english language @Aurelsicoko

**Comment by kret13** [comment] 2019-02-22 13:16
Any update on this seems News keyword cant still be used as content type name?

**Comment by Aurelsicoko** [comment] 2019-02-22 14:58
@kret13 No update. You should find another name for the content type...

**Comment by davidkartuzinski** [comment] 2019-02-25 09:00
@kret13 - may I suggest that "news" isn't really a great name in general for a content type.  "News Article" or "News Post" or "News Release" are more description and more user friendly. Consider that you may syndicate your news.  You may have different content types for a News Snippet versus a News Article versus a News release.

I do understand also just using "news" as this will have a specific meaning to you and your team.

**Comment by emahuni** [comment] 2019-07-30 08:28
yah the sort of resulting solution to this is issue is wrecking havoc with the Graphql plugin and crashes Strapi. See issue  #3695.

**Comment by emahuni** [comment] 2019-07-30 08:35
> @kret13 - may I suggest that "news" isn't really a great name in general for a content type. "News Article" or "News Post" or "News Release" are more description and more user friendly. Consider that you may syndicate your news. You may have different content types for a News Snippet versus a News Article versus a News release.
> 
> I do understand also just using "news" as this will have a specific meaning to you and your team.

what about pants or scissors? I think the idea here is that it should just handle anything thrown at it fine. I think the actually the best solution here is the 'all' prefix, maybe it could be done as an option or for words that result to a tantum, whether singularia or pluralaria.

**Comment by MartinMuzatko** [comment] 2019-07-30 08:41
It would be sufficient for me to be notified on content type creation, that this can't be pluralized properly ;)

**Comment by emahuni** [comment] 2019-07-30 08:43
> It would be sufficient for me to be notified on content type creation, that this can't be pluralized properly ;)

exactly! Then once told, if you choose to continue be aware that its plural form will be "allNAME", sometimes you don't want to change it to anything else remember that.

**Comment by emahuni** [comment] 2019-07-30 09:09
> @kret13 - may I suggest that "news" isn't really a great name in general for a content type. "News Article" or "News Post" or "News Release" are more description and more user friendly. Consider that you may syndicate your news. You may have different content types for a News Snippet versus a News Article versus a News release.
> 
> I do understand also just using "news" as this will have a specific meaning to you and your team.

oh another thing is you can't define "newsArticle" as a content type, you can only do "newsarticle" as you can't specify caps in the name field, nor can you do "news_article". I don't know why exactly this is the case, but this deters your efforts.

**Comment by vlad320** [comment] 2019-08-18 16:58
model "news" dropped strapi))

**Comment by prawee** [comment] 2019-09-04 11:31
same same solved by change to another name such as "post"

**Comment by darron1217** [comment] 2020-09-09 05:28
Also `staff` has same problem

**Comment by darron1217** [comment] 2020-09-09 06:02
If anyone still suffer from this issue, here's my workaround

**./config/functions/boostrap.js**
```
// plural bug fix
const pluralize = require('pluralize')
const plural = pluralize.plural
pluralize.plural = (word, count) => {
  if(word == 'staff') return 'staffs'
  else if(word == 'Staff') return 'Staffs'
  return plural(word, count)
}

module.exports = () => {

};

```

**Comment by jwerle** [comment] 2020-09-15 15:12
@darron1217 this is great! thank you

**Comment by jwerle** [comment] 2020-09-15 15:13
I tried to get a PR to expose internal state, but... :man_shrugging: 
https://github.com/plurals/pluralize/pull/150

**Comment by lauriejim** [comment] 2020-10-13 15:45
This issue has been mentioned on **Strapi Community**. There might be relevant details there:

https://forum.strapi.io/t/quick-start-project-get-error/418/2

**Comment by darron1217** [comment] 2020-11-19 04:42
How about throwing Exception with proper message when developer trying to use un-pluralizable word on collection?

**Comment by RaisMansuri** [comment] 2020-12-22 11:10
my strapi error was this main.981c8002.chunk.js:1 GET https://dashboard.careernaksha.com/content-manager/explorer/application::blog.blog?_limit=10&_sort=id%3AASC&_start=0 500 (Internal Server Error) please answer why this type of error again and again

**Comment by KerimG** [comment] 2021-02-18 12:01
Is there a way to simply disable this? I don't want to be rude yet I also don't want to mince words, but this is _dumb as fuck_ lmao.

It's fine if the OpenCRUD spec dictates pluralizing collections but why can't the developer optionally just do it themselves? I mean, they have to do it manually for any language not covered by `pluralize` anyway. Might as well make it easier for the international community by showing a third textbox with the suggested pluralized version of the word and the possibility to change it. 

The half-assed implementation and subsequent fixing of errors of this crap is wasting a gazillion more resources than it saves.

**Comment by derrickmehaffy** [comment] 2021-02-22 20:24
> Is there a way to simply disable this? I don't want to be rude yet I also don't want to mince words, but this is really bad.

Thank you for remaining civil :hugs: (I truly mean that)

We do know the pluralization is frustrating, currently there is no easy on/off switch for this as there is a lot of legacy code that would require massive refactoring to completely remove it. Most likely we would tackle this in V4 since it's such a breaking change.

**Comment by budlight** [comment] 2021-03-28 03:10
I was about to write an issue that was a duplicate of this issue, I noticed there are multiple duplicates of this issue, so I made a list of the words giving people trouble, just incase they actually are different issues.

These should probably just be added to a unit test for content type creation
```
series

music
staff

moose
sheep
species
```

**Comment by bonniss** [comment] 2021-06-24 03:02
The issue repeats even with `Single Type` display name. Cannot make it to the words I want even with `pluralize` rules, somehow annoying. Have a workaround by creating the type with a "legal name" first, then go to `<your_model_name>.setting.json` and change `info.name` to the right stuff.

**Comment by cjx2240** [comment] 2021-08-13 09:41
Whilst this issue is completely understandable, I think it would help to have a more useful feedback for the CMS user than "an error occurred". In fact, validation on the collection name as you type it would probably make sense!

"news" is going to be a very common collection people try to make, I was 5 minutes into trying strapi for the first time and it didn't give me a first good impression to hit a completely nondescript error message

**Comment by KerimG** [comment] 2021-08-17 09:10
@bonniss 

Thanks for the good idea.

**Comment by derrickmehaffy** [comment] 2022-05-05 21:21
Summery of related (closed/duplicate) issues:

- https://github.com/strapi/strapi/issues/8060
- https://github.com/strapi/strapi/issues/8646
- https://github.com/strapi/strapi/issues/8713
- https://github.com/strapi/strapi/issues/9540
- https://github.com/strapi/strapi/issues/7187
- https://github.com/strapi/strapi/issues/7098
- https://github.com/strapi/strapi/issues/9266
- https://github.com/strapi/documentation/pull/199
- https://github.com/strapi/strapi/issues/4289
- https://github.com/strapi/strapi/issues/10327
- https://github.com/strapi/strapi/issues/10363
- https://github.com/strapi/strapi/issues/10710
- https://github.com/strapi/strapi/issues/10929
- https://github.com/strapi/strapi/issues/11235
- https://github.com/strapi/strapi/pull/11434
- https://github.com/strapi/strapi/issues/5464
- https://github.com/strapi/strapi/issues/12330
- https://github.com/strapi/strapi/issues/10181
- https://github.com/strapi/strapi/issues/12876
- https://github.com/strapi/strapi/issues/13182
- https://github.com/strapi/strapi/issues/9150
- https://github.com/strapi/strapi/issues/10357
- https://github.com/strapi/strapi/issues/11909

**Comment by derrickmehaffy** [comment] 2023-03-27 13:44
This Issue is now being closed and locked as we are breaking it up into two different tracking issues:

Reserved Words: https://github.com/strapi/strapi/issues/16222
Pluralization Issues: https://github.com/strapi/strapi/issues/16223

**Closed by derrickmehaffy** 2023-03-27 13:44 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:strapi, flag: tracking issue
