### ISSUE TITLE
Problem starting server with yarn develop command (using local PostgreSQL server )

### ISSUE THREAD

**Issue by ersenbasaransen** [strapi/strapi#9848] opened 2021-03-27 10:13 UTC
### Describe the bug

"yarn develop" returns the  following error.
debug ⛔️ Server wasn't able to start properly.
error The port 5432 is already used by another application.

### Steps to reproduce the behavior

1. yarn create strapi-app my-strapi-app
2. I choose Custom (manual settings)
3. I configure the database
4. It says "Your application was created at ...". Everything is fine till here.
5. Close all PostgreSQL clients, pgAdmin etc.
6. yarn develop
yarn run v1.22.10
$ strapi develop
[2021-03-27T10:09:28.592Z] debug ⛔️ Server wasn't able to start properly.
[2021-03-27T10:09:28.594Z] error The port 5432 is already used by another application.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Expected behavior

I want to see this page http://localhost:1337/admin 

### Screenshots

I closed all the PostgreSQL connections and check it with TCPview.

when I run the command "yarn develop" and inspect the process using port 5432 with TCPview

I see the following node processes running 
![image](https://user-images.githubusercontent.com/1652123/112717573-b128a380-8efe-11eb-8bda-1a7b7b36f044.png)

and immediately closing 
![image](https://user-images.githubusercontent.com/1652123/112717601-edf49a80-8efe-11eb-9872-b2fa4309df55.png)

and I returning the error;
[2021-03-27T10:09:28.592Z] debug ⛔️ Server wasn't able to start properly.
[2021-03-27T10:09:28.594Z] error The port 5432 is already used by another application.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Code snippets

-

### System

- Node.js version: v12.19.0
- NPM version: 6.14.8
- Strapi version: 3.5.4
- Database: PostgreSQL (on local development machine)
- Operating system: Windows 10 Enterprise

### Additional context

-

**Comment by eriskhan** [comment] 2021-03-27 13:12
Please, share your ./config/server.js file.
Seems like you're trying to start Strapi on 5432 port and it obviously fails because 5432 is used by PostgreSQL

**Comment by derrickmehaffy** [comment] 2021-03-27 18:20
> Please, share your ./config/server.js file.
> Seems like you're trying to start Strapi on 5432 port and it obviously fails because 5432 is used by PostgreSQL

I was going to say the exact same thing. We need more information as it looks like your app is trying to bind to a port that's in use (5432).

**Comment by ersenbasaransen** [comment] 2021-03-27 18:30
> Please, share your ./config/server.js file.
> Seems like you're trying to start Strapi on 5432 port and it obviously fails because 5432 is used by PostgreSQL

Hi @eriskhan ,
Here is the server.js file.

module.exports = ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  admin: {
    auth: {
      secret: env('ADMIN_JWT_SECRET', '11df5e7a77260200c9f1280b139f7930'),
    },
  },
});

**Comment by eriskhan** [comment] 2021-03-27 22:53
What if you try creating a quick start project? Is it working this way? If yes, I think it may be related to setting wrong config during the project creation.

**Comment by derrickmehaffy** [comment] 2021-03-29 18:58
What does your database.js look like?

**Comment by derrickmehaffy** [comment] 2021-07-22 21:46
No new information added, closing as unable to reproduce with existing information

**Closed by derrickmehaffy** 2021-07-22 21:46 UTC
Labels: status: can't reproduce
