### ISSUE TITLE
I tried to install strapi and then meet this problem

### ISSUE THREAD

**Issue by huangdafei645** [strapi/strapi#16934] opened 2023-06-06 15:42 UTC
### Required System information

- Node.js version: v16.14.1
- NPM version:8.5.0
- Strapi version: 3.6.11
- Database: sqlite
- Operating system: win11
- Is your project Javascript or Typescript: javascript

### Describe the bug

warning @strapi/strapi > koa-body > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
warning @strapi/strapi > @strapi/plugin-email > @strapi/provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
warning @strapi/strapi > @strapi/plugin-email > @strapi/provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning "@strapi/strapi > @strapi/plugin-email@4.10.7" has unmet peer dependency "react@^17.0.2".
warning "@strapi/strapi > @strapi/plugin-email@4.10.7" has unmet peer dependency "react-dom@^17.0.2".
warning "@strapi/strapi > @strapi/plugin-email@4.10.7" has unmet peer dependency "react-router-dom@^5.3.4".
warning "@strapi/strapi > @strapi/plugin-email@4.10.7" has unmet peer dependency "styled-components@^5.3.3".
warning "@strapi/strapi > @strapi/plugin-content-type-builder@4.10.7" has unmet peer dependency "react@^17.0.2".
warning "@strapi/strapi > @strapi/plugin-content-type-builder@4.10.7" has unmet peer dependency "react-dom@^17.0.2".
warning "@strapi/strapi > @strapi/plugin-content-type-builder@4.10.7" has unmet peer dependency "react-router-dom@^5.3.4".
warning "@strapi/strapi > @strapi/plugin-content-type-builder@4.10.7" has unmet peer dependency "styled-components@^5.3.3".
warning "@strapi/strapi > @strapi/plugin-upload@4.10.7" has unmet peer dependency "react@^17.0.2".
warning "@strapi/strapi > @strapi/plugin-upload@4.10.7" has unmet peer dependency "react-dom@^17.0.2".
warning "@strapi/strapi > @strapi/plugin-upload@4.10.7" has unmet peer dependency "react-router-dom@^5.3.4".
warning "@strapi/strapi > @strapi/plugin-upload@4.10.7" has unmet peer dependency "styled-components@^5.3.3".
warning "@strapi/plugin-users-permissions > @strapi/icons@1.7.9" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-users-permissions > @strapi/icons@1.7.9" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-users-permissions > @strapi/design-system@1.7.9" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-users-permissions > @strapi/design-system@1.7.9" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-users-permissions > @strapi/design-system@1.7.9" has unmet peer dependency "react-router-dom@^5.2.0".
warning "@strapi/plugin-users-permissions > @strapi/design-system@1.7.9" has unmet peer dependency "styled-components@^5.2.1".
warning "@strapi/plugin-users-permissions > react-intl@6.4.1" has unmet peer dependency "react@^16.6.0 || 17 || 18".
warning "@strapi/plugin-users-permissions > react-redux@8.0.5" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-content-type-builder > react-helmet@6.1.0" has unmet peer dependency "react@>=16.3.0".
warning "@strapi/strapi > @strapi/plugin-upload > react-dnd@15.1.2" has unmet peer dependency "react@>= 16.14".
warning "@strapi/strapi > @strapi/plugin-upload > react-select@5.7.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-upload > react-select@5.7.0" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/plugin-users-permissions > formik@2.4.0" has unmet peer dependency "react@>=16.8.0".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.10.7" has unmet peer dependency "react@^17.0.2".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.10.7" has unmet peer dependency "react-dom@^17.0.2".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.10.7" has unmet peer dependency "react-router-dom@^5.3.4".
warning "@strapi/plugin-users-permissions > @strapi/helper-plugin@4.10.7" has unmet peer dependency "styled-components@^5.3.3".
warning "@strapi/plugin-users-permissions > react-query@3.39.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @floating-ui/react-dom@1.3.0" has unmet peer dependency "react@>=16.8.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @floating-ui/react-dom@1.3.0" has unmet peer dependency "react-dom@>=16.8.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-focus-scope@1.0.2" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-focus-scope@1.0.2" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dismissable-layer@1.0.4" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dismissable-layer@1.0.4" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".     
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives@1.8.0" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives@1.8.0" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu@2.0.5" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu@2.0.5" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > react-remove-scroll@2.5.6" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @uiw/react-codemirror@4.21.1" has unmet peer dependency "@babel/runtime@>=7.11.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @uiw/react-codemirror@4.21.1" has unmet peer dependency "@codemirror/state@>=6.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @uiw/react-codemirror@4.21.1" has unmet peer dependency "@codemirror/theme-one-dark@>=6.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @uiw/react-codemirror@4.21.1" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @uiw/react-codemirror@4.21.1" has unmet peer dependency "codemirror@>=6.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @uiw/react-codemirror@4.21.1" has unmet peer dependency "react@>=16.8.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @uiw/react-codemirror@4.21.1" has unmet peer dependency "react-dom@>=16.8.0".
warning "@strapi/strapi > @strapi/plugin-content-type-builder > react-helmet > react-side-effect@2.1.2" has unmet peer dependency "react@^16.3.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-upload > react-select > @emotion/react@11.11.0" has unmet peer dependency "react@>=16.8.0".
warning "@strapi/strapi > @strapi/plugin-upload > react-select > react-transition-group@4.4.5" has unmet peer dependency "react@>=16.6.0".
warning "@strapi/strapi > @strapi/plugin-upload > react-select > react-transition-group@4.4.5" has unmet peer dependency "react-dom@>=16.6.0".
warning "@strapi/strapi > @strapi/plugin-upload > react-select > use-isomorphic-layout-effect@1.1.2" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-content-type-builder > react-redux > use-sync-external-store@1.2.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".        
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-focus-scope > @radix-ui/react-compose-refs@1.0.0" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dismissable-layer > @radix-ui/react-compose-refs@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-focus-scope > @radix-ui/react-primitive@1.0.2" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-focus-scope > @radix-ui/react-primitive@1.0.2" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dismissable-layer > @radix-ui/react-primitive@1.0.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dismissable-layer > @radix-ui/react-primitive@1.0.3" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-focus-scope > @radix-ui/react-use-callback-ref@1.0.0" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dismissable-layer > @radix-ui/react-use-callback-ref@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dismissable-layer > @radix-ui/react-use-escape-keydown@1.0.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-focus-guards@1.0.0" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-context@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-direction@1.0.0" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-collection@1.0.2" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-collection@1.0.2" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-collection > @radix-ui/react-context@1.0.0" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-id@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-use-controllable-state@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-slot@1.0.2" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-focus-scope > @radix-ui/react-primitive > @radix-ui/react-slot@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-portal@1.0.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-portal@1.0.3" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-use-layout-effect@1.0.0" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-id > @radix-ui/react-use-layout-effect@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > react-remove-scroll > react-remove-scroll-bar@2.3.4" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > react-remove-scroll > react-style-singleton@2.2.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > react-remove-scroll > use-callback-ref@1.3.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-use-previous@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > react-remove-scroll > use-sidecar@1.1.2" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".   
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper@1.1.2" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper@1.1.2" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper > @floating-ui/react-dom@2.0.0" has unmet peer dependency "react@>=16.8.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper > @floating-ui/react-dom@2.0.0" has unmet peer dependency "react-dom@>=16.8.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-visually-hidden@1.0.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-visually-hidden@1.0.3" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.1" has unmet peer dependency "@codemirror/autocomplete@>=6.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.1" has unmet peer dependency "@codemirror/language@>=6.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.1" has unmet peer dependency "@codemirror/lint@>=6.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.1" has unmet peer dependency "@codemirror/search@>=6.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.1" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu@2.0.5" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu@2.0.5" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-collection@1.0.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-collection@1.0.3" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-direction@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-focus-guards@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-focus-scope@1.0.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-focus-scope@1.0.3" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > react-remove-scroll@2.5.5" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @uiw/react-codemirror > codemirror > @codemirror/autocomplete@6.7.1" has unmet peer dependency "@lezer/common@^1.0.0".
warning "@strapi/strapi > @strapi/plugin-upload > react-select > @emotion/react > @emotion/use-insertion-effect-with-fallbacks@1.0.1" has unmet peer dependency "react@>=16.8.0".    
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper > @radix-ui/react-use-rect@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper > @radix-ui/react-use-size@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-presence@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-presence@1.0.1" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper > @radix-ui/react-arrow@1.0.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper > @radix-ui/react-arrow@1.0.3" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-roving-focus@1.0.4" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/strapi > @strapi/plugin-email > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-roving-focus@1.0.4" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning " > @strapi/plugin-users-permissions@4.10.7" has unmet peer dependency "react@^17.0.2".
warning " > @strapi/plugin-users-permissions@4.10.7" has unmet peer dependency "react-dom@^17.0.2".
warning " > @strapi/plugin-users-permissions@4.10.7" has unmet peer dependency "react-router-dom@^5.3.4".
warning " > @strapi/plugin-users-permissions@4.10.7" has unmet peer dependency "styled-components@^5.3.3".
warning " > @strapi/plugin-i18n@4.10.7" has unmet peer dependency "react@^17.0.2".
warning " > @strapi/plugin-i18n@4.10.7" has unmet peer dependency "react-dom@^17.0.2".
warning " > @strapi/plugin-i18n@4.10.7" has unmet peer dependency "react-router-dom@^5.3.4".
warning " > @strapi/plugin-i18n@4.10.7" has unmet peer dependency "styled-components@^5.3.3".
error D:\desktop\folder\server\my-project\node_modules\better-sqlite3: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild --release
Arguments:
Directory: D:\desktop\folder\server\my-project\node_modules\better-sqlite3
Output:
prebuild-install warn install No prebuilt binaries found (target=16.14.1 runtime=node arch=x64 libc= platform=win32)

D:\desktop\folder\server\my-project\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "D:\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )  else (node "D:\nvm\v16.14.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --release )
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@16.14.1 | win32 | x64
gyp info find Python using Python version 3.8.1 found at "D:\软件\python\python.exe"
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! stack     at D:\nvm\v16.14.1\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
gyp ERR! System Windows_NT 10.0.22621
gyp ERR! command "D:\\nodejs\\node.exe" "D:\\nvm\\v16.14.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd D:\desktop\folder\server\my-project\node_modules\better-sqlite3
gyp ERR! node -v v16.14.1
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
TypeError: Cannot read properties of undefined (reading 'addBreadcrumb')
    at C:\Users\16354\AppData\Local\npm-cache\_npx\2d56dd13733e9da7\node_modules\@strapi\generate-new\dist\utils\usage.js:67:28
    at Array.forEach (<anonymous>)
    at captureStderr (C:\Users\16354\AppData\Local\npm-cache\_npx\2d56dd13733e9da7\node_modules\@strapi\generate-new\dist\utils\usage.js:66:14)
    at createProject (C:\Users\16354\AppData\Local\npm-cache\_npx\2d56dd13733e9da7\node_modules\@strapi\generate-new\dist\create-project.js:126:41)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createQuickStartProject (C:\Users\16354\AppData\Local\npm-cache\_npx\2d56dd13733e9da7\node_modules\@strapi\generate-new\dist\create-quickstart-project.js:21:5)

### Steps to reproduce the behavior

1. open the terminal in administrator
2. npx create-strapi-app@latest my-project --quickstart

### Expected behavior

install the strapi successfully

### Screenshots

![image](https://github.com/strapi/strapi/assets/102475833/5495df93-0327-423c-9566-b11c9447fed8)

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

I tried a lot of methods, lowering the yarn version, replacing the node version, replacing the node, and I found many solutions on the Internet, but it didn't work for me

**Comment by GregorSondermeier** [comment] 2023-06-07 05:51
Strapi 3 is deprecated. Use Strapi 4.

**Comment by huangdafei645** [comment] 2023-06-07 08:42
> 

![image](https://github.com/strapi/strapi/assets/102475833/5454eb15-d464-4745-a6aa-c13ab139c005)
I can not use strapi 4, why?

**Comment by GregorSondermeier** [comment] 2023-06-07 08:56
https://www.npmjs.com/package/strapi
![image](https://github.com/strapi/strapi/assets/11959747/df52a286-1d59-4c86-9559-fd5894abd4ac)

Use https://www.npmjs.com/package/@strapi/strapi instead!

But it's better to head over to use `npx create-strapi-app@latest my-project` instead. Head over to https://docs.strapi.io/dev-docs/quick-start and follow that guide.

If you have problems, I'd suggest you first head over to https://forum.strapi.io/ and/or the [Strapi Discord](https://strapi.io/community) and get support there, as clearly what you are writing here is not a bug at the Strapi side, but rather on your side.

**Comment by huangdafei645** [comment] 2023-06-07 10:26
I tryed npx create-strapi-app my-project --quickstart,but it didn't work for me，I am new to use this，could you please help me

**Comment by derrickmehaffy** [comment] 2023-06-07 10:56
You need to specify as your npx command is most likely using a cached version:

`npx create-strapi-app@latest my-project --quickstart`

Marking as closed as the user is using an older Strapi version

**Closed by derrickmehaffy** 2023-06-07 10:56 UTC
Labels: status: can not reproduce

**Comment by mauriciabad** [comment] 2023-08-19 18:47
I was having a similar problem, and it got solved for me by installing Python and using the latest node version.
