### ISSUE TITLE
Morph 'ref' should use model name instead of collectionName

### ISSUE THREAD

**Issue by Goxiaoy** [strapi/strapi#7511] opened 2020-08-18 13:44 UTC
**Describe the bug**
Current morph use and store model collectionName instead of model name, which may cause confuses when collecionName != name

**Steps to reproduce the behavior**

1. Go to content types builder, create new content type `test`, add media field , the default collectionName will be `tests`
```
{
  "kind": "collectionType",
  "collectionName": "tests",
  "info": {
    "name": "test"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "pic": {
      "model": "file",
      "via": "related",
      "allowedTypes": [
        "images",
        "files",
        "videos"
      ],
      "plugin": "upload",
      "required": false
    }
  }
}
```

2. upload and set `media` field, check out database table `upload_file_morph`

3. you will see `related_type` value `tests`, which means when you use related api, you should set `ref` to `tests` not `test`
![image](https://user-images.githubusercontent.com/8577611/90520184-9d180900-e19b-11ea-9091-933af55e0cb3.png)

**Expected behavior**
related_type should use model name `test` not collection name

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**

- Node.js version: v12.18.3
- NPM version: 
- Strapi version: 3.1.3
- Database: sqlite
- Operating system: windows 10

**Additional context**

**Comment by derrickmehaffy** [comment] 2020-08-18 17:42
This is expected behavior because in this case it's not referencing the model but the other database table IE the collection name or name of the table.

I am closing because this is intended behavior but if you have any feedback on how we can make this more clear to others please let us know.

Thank you!

**Closed by derrickmehaffy** 2020-08-18 17:43 UTC

**Comment by Goxiaoy** [comment] 2020-08-18 18:34
I think it's more reasonable to rename `ref` to `refCollection` if you want to keep this logic. For most cases, developers will use model api instead of db layer api

And I am a little bit confuse about the plural format which makes me notice the difference . commented in https://github.com/strapi/strapi/discussions/6081#discussioncomment-52676
