### ISSUE TITLE
GraphQL schema does not put ! non-nullable for required Component

### ISSUE THREAD

**Issue by EricKit** [strapi/strapi#5538] opened 2020-03-18 19:19 UTC
With the following model:

```
{
  "kind": "collectionType",
  "connection": "default",
  "collectionName": "targets",
  "info": {
    "name": "target"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "coordinate": {
      "type": "component",
      "repeatable": false,
      "component": "target.coordinate",
      "required": true
    }
  }
}

```

And the following component:

```
{
  "connection": "default",
  "collectionName": "components_target_coordinates",
  "info": {
    "name": "Coordinate",
    "icon": "radiation"
  },
  "options": {},
  "attributes": {
    "latitude": {
      "type": "float",
      "required": true,
      "max": 90,
      "min": -90
    },
    "longitude": {
      "type": "float",
      "required": true,
      "min": -180,
      "max": 180
    }
  }
}
```

The type is produced in the `exports/graphql/schema.graphql` file as such:

```
type Target {
  coordinate: ComponentTargetCoordinate
}
```

**Expected behavior**

That the schema would be non-nullable. This effects graphql-codegen and makes the types optional in Typescript later.

```
type Target {
  coordinate: ComponentTargetCoordinate!
}
```

Or you don't have the ability to mark the field as required.

**System**
- Node.js version: 13.3.0
- NPM version: 6.13.1
- Strapi version: 3.0.0-beta.19.3
- Database: Postgres
- Operating system: MacOS

**Comment by lauriejim** [comment] 2020-03-23 10:35
Hello @EricKit !
Thank you for reporting this issue.
I think it's not really hard to fix it. Can you please try to check the GraphQL plugin, find the issue and submit a PR to fix it.
I will really appreciate your contribution to this issue.
Thank you.

**Comment by abdonrd** [comment] 2020-04-18 10:12
Related with https://github.com/strapi/strapi/issues/4548

**Comment by kitarp29** [comment] 2021-10-17 21:30
@lauriejim  @abdonrd  If this issue is still open Can I work on it?
Please assign it to me.

**Comment by kasonde** [comment] 2021-11-30 14:21
Fixed in v4. Can't reproduce.

**Closed by kasonde** 2021-11-30 14:21 UTC
Labels: type: bug, severity: low, good first issue, status: confirmed, source: plugin:graphql
