### ISSUE TITLE
Thumbnail is not generated into the file path defined

### ISSUE THREAD

**Issue by Lith** [strapi/strapi#5934] opened 2020-04-24 09:39 UTC
**Describe the bug**
When I upload a new image with a `path`, the new upload system with Media Library generate a thumbnail.
But the thumbnail is not uploaded into the filepath defined.

**Steps to reproduce the behavior**

1. Upload a new image with a defined `path`
2. Go to upload folder, and see the thumbnail into the path root

**Expected behavior**
The thumbnail need to be in the same folder path than the original image uploaded

**Example**
I upload a new image `avatar.png` with the path  `/users/1234/` :
- Image is correclty uploaded into `/users/1234/avatar.png`
- Thumbnail is upload to `/thumbnail_avatar.png`  instead of `/users/1234/thumbnail_avatar.png`

**System**

- Node.js version: v12.16.1
- NPM version: v6.13.4
- Strapi version: 3.0.0-beta.20
- Database: MySQL 5.7
- Operating system: MacOSX Catalina
- Upload Provider : local // google-cloud-storage

Thanks

**Comment by derrickmehaffy** [comment] 2020-04-24 09:44
`google-cloud-storage` This is not a Strapi built provider

As for local: https://strapi.io/documentation/3.0.0-beta.x/plugins/upload.html#request-parameters

`path (optional): The folder where the file(s) will be uploaded to (only supported on strapi-provider-upload-aws-s3).`

I'm marking this issue as closed as it's not a bug but intended.

**Comment by Lith** [comment] 2020-04-24 09:52
I reproduce the bug with local provider.
`path` is supported on `strapi-provider-upload-google-cloud-storage`, the original image is correctly uploaded into the good folder, but the thumbnail not.

If it's not a bug, How to have `thumbnail` correctly uploaded in the good path folder ?
Thanks.

**Comment by derrickmehaffy** [comment] 2020-04-24 16:38
I don't have a solid answer for that 🤔 I know this one has come up a few times but AFAIK specific folders for upload is currently a feature request https://github.com/strapi/strapi/issues/2972 (not local here)

**Comment by Lith** [comment] 2020-04-25 13:12
I think I found the bug here : 
- https://github.com/strapi/strapi/blob/8675eae14469f6c8bd38926a44d8f8ba40244927/packages/strapi-plugin-upload/services/image-manipulation.js#L44

` path` is not return when generatingThumbnails.

This will something like that maybe ?
```
return {
        hash: `thumbnail_${file.hash}`,
        ext: file.ext,
        mime: file.mime,
        width,
        height,
        size: bytesToKbytes(size),
        buffer: newBuff,
        path: file.path ? file.path : ''  /* add file path in return object */
      };
```

File path is set (if exist before) from here :
- https://github.com/strapi/strapi/blob/8675eae14469f6c8bd38926a44d8f8ba40244927/packages/strapi-plugin-upload/services/Upload.js#L65

I think this bug also concern `generateResponsiveFormats` method.

Thanks @derrickmehaffy for your help :)

**Comment by lauriejim** [comment] 2020-04-28 09:20
I ping @alexandrebodin to have his insight about this technical topic.

**Comment by alexandrebodin** [comment] 2020-04-28 10:16
Hi @Lith we didn't even consider the path option as it is supposed to only work with the aws3 provider and we wanted to handle it differently tbh :/ 

It is a pretty easy fix for sure. Would you consider submitting a PR to help get this merged faster ?

**Closed** 2020-05-09 18:04 UTC
Labels: priority: medium, source: plugin:upload, type: bug
