### ISSUE TITLE
Relation lazy loading shows only ID instead of the configured entry title

### ISSUE THREAD

**Issue by AndColla** [strapi/strapi#19625] opened 2024-02-28 09:39 UTC
### Required System information

- Node.js version: v18.19.1
- Yarn version: 1.22.21
- Strapi version: v4.20.2
- Database: sqlite/postgres
- Operating system: linux-x64 
- Is your project Javascript or Typescript: JS

### Describe the bug

When I have a many-to-many relation with more than 5 elements, the related elements in the admin panel are lazy loaded. The first 5 elements are shown correctly with the entry title and their status (published or draft). If I load more elements with the load more button the new elements are shown only by their IDs.

### Steps to reproduce the behavior

1. Create a many-to-many relation
2. Add more than 5 elements to the relation
3. Reload the page of the entry with more than 5 related objects
4. Click on "Load more"

### Expected behavior

I should get the new elements with their status (published or draft) and their correct names.

### Screenshots

![image](https://github.com/strapi/strapi/assets/14584600/759da4d8-4b6e-44da-beaf-ad4353fafc1a)

**Comment by victorfreitas** [comment] 2024-03-01 01:50
I've installed the new version of Strapi, create two collection types with the relation component and got the same error.

## Tested up with the latest version
- Strapi: 4.20.3
- Node: v20.11.1

## Doesn't working on Strapi >= 4.19.1

#### Strapi 4.19.1 doesn't show the load more button
![image](https://github.com/strapi/strapi/assets/21069978/6d2a0662-66fb-4801-9e90-3074971e7788)

#### Strapi 4.20.0 shows the button again but with the bug
![image](https://github.com/strapi/strapi/assets/21069978/615e638f-22cd-4fa7-9b17-743be061cbf5)

**Comment by dennism501** [comment] 2024-03-06 14:48
Internal TIDs: 6146 6144

**Comment by derrickmehaffy** [comment] 2024-03-12 18:29
Related to internal TID5849

**Comment by NileshKale-Globant** [comment] 2024-03-15 08:19
I am also facing the same issue in our Project.
When user loads the more records in Relation, then the main field (name/title) of related item is not shown. Instead of main field, an ID of the relation item is shown in relation view.

![StrapiRelationIssue](https://github.com/strapi/strapi/assets/89136696/af5d5f4c-388f-4b3e-90ee-7e7b11d8cd95)

**Comment by sleeporsmile** [comment] 2024-03-15 09:52
same issue

**Comment by fernandonmenezes** [comment] 2024-03-22 15:39
Just tested v4.21.0 and issue is still there

**Comment by zyshara** [comment] 2024-03-23 00:49
Also experiencing this issue, v4.21.0

**Comment by Marc-Roig** [comment] 2024-03-26 12:38
Hello :) This issue will be fixed in next week 4.22.0 release

**Comment by Marc-Roig** [comment] 2024-03-26 12:58
In case anyone is interested I created an experimental release `0.0.0-experimental.343968041bed1eb9d230115e687e9397b0f5fd50`

**Comment by CyrilGouv** [comment] 2024-06-21 07:56
Just testing Strapi v4.25.1 and I am also facing the same issue

**Comment by NEDDL** [comment] 2024-07-03 22:06
Facing the same issue v5.0.0-beta.17

**Comment by dennism501** [comment] 2024-07-25 13:32
Internal TID: 7576

**Comment by Marc-Roig** [comment] 2024-08-06 09:29
https://github.com/strapi/strapi/pull/20946 should fix the issue in the v5 versions.

However, I am not able to reproduce the issue on the latest v4 branch (4.25.6), @CyrilGouv could you elaborate a bit more your issue? or the content type / user permissions user has ?

**Closed** 2024-08-07 12:34 UTC
Labels: issue: bug, severity: high, status: confirmed, source: core:content-manager, flag: EE, version: 5, version: 4
