### ISSUE TITLE
 An error occurred during record deletion.

### ISSUE THREAD

**Issue by stiko** [strapi/strapi#2210] opened 2018-10-26 16:41 UTC
**Informations**
- **Node.js version**: v10.11.0
- **npm version**:  6.4.1
- **Strapi version**: 3.0.0-alpha.14.3
- **Database**: Mongo
- **Operating system**: Mac

**What is the current behavior?**
When you filter for content then try to remove a content, it gives an error
```
 An error occurred during record deletion.
```

**Steps to reproduce the problem**
1- Go to content type
2- filter for a content
3- remove a content

**What is the expected behavior?**
It should remove the content with no error

**Suggested solutions**

**Comment by lauriejim** [comment] 2018-10-27 15:47
Hello @stiko, can you give more precise steps please.

**Comment by stiko** [comment] 2018-10-27 16:11
@lauriejim Sure,
1. Visit a content type
2. Filter to search (3 letters or more)
3. try to delete one of the contents
4. You should get an error. If not, try again with more letters.

**Comment by stiko** [comment] 2018-10-27 16:29
**Update:** I just tested it with a different content type and it works, so I started looking at the calls it makes and when it fails (Only with this one content type).
When I delete without filtering it makes this successful call
`http://localhost:1337/content-manager/explorer/[content_type_singular_name]/5bd237a9f0ba82d37c8a4907?source=content-manager`
But when I filter it fails while it's making this call
`http://localhost:1337/content-manager/explorer/[content_type_singular_name]/?source=content-manager`

It looks like it's missing the id for some reason.

I will update to 14.4 sometime today and see.

**Comment by stiko** [comment] 2018-10-27 17:45
Updating to 14.4 does not solve this issue in addition to the weird behavior of 14.4.
This happens only with contents that were added via POST request (not via UI).

**Comment by lauriejim** [comment] 2018-11-12 11:32
What is the name of your content type ?

**Comment by stiko** [comment] 2018-11-12 16:05
I found the issue. I had a json field that was empty. It makes sense for it to not save, but I think I should be able to remove it. I'm not sure if that was intentional or it's a bug.
If you're curious how I had an empty json field on the first place, I added the content via HTTP POST

**Comment by lauriejim** [comment] 2018-11-12 20:30
Empty JSON field ? Can you precise please.

**Comment by stiko** [comment] 2018-11-12 21:42
Sure, Let me clarify some things before I explain
**Background**
Json field: even if it's not required, it can NOT be empty. At least you have to add `{}` to it in order to be able to save. The UI (after the update) is smart enough to add `{}`, but if you make a POST request without the json field, it will leave it empty.

**Issue**
For clarity let's add a content type called `test` and It's fields are `title` type `string` and `jsonfield` type `json`
Make a POST request to `localhost:1337/tests` with this body 
```
{
  "title": "test title"
}
```
Now go back to the UI and click on `test` content type
Then add to the filter `test` 
If you try to remove it, it will give you an error.
What's interesting is that if you don't filter, it will remove it just fine.

**Solution** 
I think there are two solutions
1. HTTP request should do what the UI is doing
2. JSON field always default to `{}`

**Comment by lauriejim** [comment] 2018-11-15 13:12
You speak about the search bar ? Not the filter section.

**Comment by stiko** [comment] 2018-11-16 01:19
I think it can go both ways. It is the only search/filter bar on that page.

**Comment by lauriejim** [comment] 2018-11-19 15:32
I highlight `Search bar` and `Filter` zone. What did you use ?

![zones](https://user-images.githubusercontent.com/5716596/48716848-8d5f3f80-ec18-11e8-85b1-b2bdd90b2fb6.jpg)

**Comment by stiko** [comment] 2018-11-27 15:38
My bad I never used filters :( 
It's the search bar

**Comment by lauriejim** [comment] 2018-11-28 16:34
There is an issue. I suggest you to use filter waiting the fix.

**Comment by lauriejim** [comment] 2018-12-05 17:32
Have been fixed in last version of Strapi (alpha.16)
Not able to reproduce it again.

**Closed by lauriejim** 2018-12-05 17:32 UTC
Labels: priority: medium, status: confirmed, type: bug 🐛
