### ISSUE TITLE
The build depends of the host where Strapi is deployed on

### ISSUE THREAD

**Issue by jprudent** [strapi/strapi#10867] opened 2021-09-02 08:30 UTC
### Describe the bug

When building the application with `yarn build`, the resulting packaged application has somehow hardcoded the `server.url` value to `0.0.0.0:1337`.  When the app is run (overriding the `server.url` with http://my.domain.com:1337 ) and accessed somewhere else, say `my.domain.com`, the admin application will make calls to `http://0.0.0.0:1337` instead of `http://my.domain.com:1337`.

### Steps to reproduce the behavior

1. `yarn build`
2. Run the app on some domain with `PUBLIC_URL=http://my.domain.com:1337 yarn start`
3. go to http://my.domain.com:1337/admin
4. An infinite spinner is displayed. As you open the console you see some resources have been downloaded from http://my.domain.com:1337 (like the spinner), but some calls are made to http://0.0.0.0:1337

### Expected behavior

At runtime, when application is run with `PUBLIC_URL=http://my.domain.com:1337 yarn start` then the Admin application only calls  http://my.domain.com:1337 (and it works).

The workaround I've found is to build with PUBLIC_URL set: 
`PUBLIC_URL=http://my.domain.com:1337 yarn build` 
This creates an application that I can deploy and access from http://my.domain.com:1337.
But that means that the build depends on where it's intended to be deployed. This is problematic.

### Code snippets 

config/server.js

```javascript
module.exports = ({ env }) => ({
  host: env('NODE_HOST', '0.0.0.0'),
  port: env.int('NODE_PORT', 1337),
  admin: {
    host: env('HOST', '0.0.0.0'),
    auth: {
      secret: env('ADMIN_JWT_SECRET', 'XXXXX'),
    },
  },
  url: env('PUBLIC_URL', "http://0.0.0.0:1337"),
});
```

### System

- Node.js version:  14.17.5
- NPM version: 6.14.14
- Strapi version:  3.6.6
- Database: sqlite
- Operating system: Linux

**Comment by derrickmehaffy** [comment] 2021-09-03 17:14
You need to pass the `PUBLIC_URL` to the build as well. That URL is pulled from the config during build time and is statically compiled into the build (it can't be changed in the react application during runtime).

I'm setting this as a duplicate of this feature request: https://github.com/strapi/strapi/issues/8246

**Closed by derrickmehaffy** 2021-09-03 17:14 UTC

**Comment by wolodek** [comment] 2023-07-18 12:21
Actually as PUBLIC_URL is statically compiled into the build you can override it before serving the app with simple replace script. We are having one build step in CI/CD and serve same package across many environemnts. I created a gist which can be run in some after-deploy hook to resolve this issue
https://gist.github.com/wolodek/973309c8540437e0cf33ca8b8148023e

**Comment by ababakanian** [comment] 2024-07-24 08:12
@wolodev I think the gist you shared is not available anymore.

**Comment by wolodev** [comment] 2024-07-24 16:41
Hey @ababakanian I updated the link 👍🏻
