### ISSUE TITLE
Strapi 4.5.4 very slow put request

### ISSUE THREAD

**Issue by chernyak88** [strapi/strapi#15472] opened 2023-01-17 09:01 UTC
### Required System information

- Node.js version: 16.19.0
- NPM version: 8.19.3
- Strapi version: 4.5.4 (4.5.5, 4.5.6)
- Database: Mysql 8.0.25
- Operating system: Ubuntu 22.04.1 LTS, Docker

### Describe the bug

Hello everyone!

Strapi version 4.5.3 worked fine.
But after upgrading to version 4.5.4, it takes a very long time to update if the request contains a 'many-to-many' relation.
Previously, the put request lasted ~100-150ms, and now ~15000-20000ms

If in the file @strapi/database/lib/entity-manager/regular-relations.js comment out the execution of the cleanOrderColumnsForInnoDB function, then everything works fast again.

### Steps to reproduce the behavior

1. Create two collection types
2. Make them "type": "relation", "relation": "manyToMany"
3. Update one of these collection types (there should be a lot of records in the database)
4. The more records there are in the database, the slower the update

### Expected behavior

The request is executed quickly, as before

### Screenshots

With the cleanOrderColumnsForInnoDB function:
![Screenshot from 2023-01-17 11-40-33](https://user-images.githubusercontent.com/45533701/212852896-2c0b7278-16df-4c0c-a0be-d444abf24754.png)

Without the cleanOrderColumnsForInnoDB function:
![Screenshot from 2023-01-17 11-42-02](https://user-images.githubusercontent.com/45533701/212852981-1c48d2df-137b-4148-918c-9083e741b7fe.png)
![Screenshot from 2023-01-17 11-41-28](https://user-images.githubusercontent.com/45533701/212853017-0bdf0ccb-39b4-4271-a20d-72736bb45bd0.png)

### Code snippets

In my shooting schema.json:
``` 
"employees": {
  "type": "relation",
  "relation": "manyToMany",
  "target": "api::employee.employee",
  "inversedBy": "shootings"
},
```

In my employee schema.json:
```
"shootings": {
  "type": "relation",
  "relation": "manyToMany",
  "target": "api::shooting.shooting",
  "private": true
},
```

### Additional context

In my case I have two collection types (shootings and employees), relation between them "manyToMany", number of records in the database 65469
![Screenshot from 2023-01-17 12-16-15](https://user-images.githubusercontent.com/45533701/212858102-4b971a14-4c1a-40f8-b36f-37d78a3a1708.png)

**Comment by Boegie19** [comment] 2023-01-17 09:07
How many `many-to-many` do you have in this relationship?

**Comment by chernyak88** [comment] 2023-01-17 09:17
Do you mean the number of records in the database?
If yes, then 65469 records
![Screenshot from 2023-01-17 12-16-15](https://user-images.githubusercontent.com/45533701/212858102-4b971a14-4c1a-40f8-b36f-37d78a3a1708.png)

**Comment by derrickmehaffy** [comment] 2023-01-17 18:54
Hello @chernyak88 normally because your issue didn't follow our issue template I would just immediately close the issue however I do think this is an important issue. Can you please update your issue to follow our template while I raise this with our engineers?

Thanks

---

Can you also share your content-modeling structure and the actions you took to reproduce this issue, knowing some information about your environment would also be very helpful.

**Comment by chernyak88** [comment] 2023-01-18 06:32
Hello @derrickmehaffy.
Sorry, I updated my issue

**Comment by derrickmehaffy** [comment] 2023-01-26 17:20
> Hello @derrickmehaffy. Sorry, I updated my issue.

thank you very much!

**Comment by derrickmehaffy** [comment] 2023-02-01 19:10
Duplicate of: https://github.com/strapi/strapi/issues/15539 and fixed in https://github.com/strapi/strapi/pull/15554

**Closed by derrickmehaffy** 2023-02-01 19:10 UTC
Labels: issue: bug, severity: high, source: core:database, status: pending reproduction
