### ISSUE TITLE
Customize admin left menu

### ISSUE THREAD

**Issue by 99darwin** [strapi/strapi#900] opened 2018-04-03 17:32 UTC
*FEATURE REQUEST*

**The problem**
Say you have 5 content types that all render on one page, currently there is no way to organize them all into one overarching group.

**What is the expected behavior?**
Allow for the organization of content types into categories. 

Proposed structure may look something like this:

```
Categories
└─── Blog
  └─── [additional categories]
    └─── [content-types]
└─── Home
   └─── [content-types]
└─── About the team
   └─── [content-types]
```

My team and I are working on this feature [here](https://github.com/99darwin/strapi-categories)
---

- [ ✔] I'm sure that this issue hasn't already been referenced

**Comment by oeddyo** [comment] 2018-04-04 01:26
Is it possible to add a "contentType" field on your article, then rendering differently based on the contentType field?

**Comment by Aurelsicoko** [comment] 2018-04-06 08:15
@99darwin Are you talking about organizing the left menu in the dashboard?

**Comment by Aurelsicoko** [comment] 2018-04-06 08:25
Not possible yet. However, it's a new configuration that should be available through the `Configurations` link at the bottom left of the menu. In my mind, this `Configurations` page will have the same layout as the Settings Manager.

**Comment by lauriejim** [comment] 2018-07-19 14:32
Hello @99darwin can you give us an update about your app https://github.com/99darwin/strapi-categories ?

**Comment by Aurelsicoko** [comment] 2018-07-20 08:33
I already made some research on this part. Here a preview of what we could imagine defining a custom menu according to the user role.

![settings manager - menu](https://user-images.githubusercontent.com/4144726/42992261-53487228-8c08-11e8-95b1-a3c5d1764c3e.png)

**Comment by derrickmehaffy** [comment] 2018-07-20 08:34
@Aurelsicoko **YES!** Please :heart_eyes:

**Comment by rdisabato** [comment] 2018-09-16 16:30
must-to-have i think

**Comment by yummyelin** [comment] 2018-10-02 18:00
@Aurelsicoko Just checking, will this feature be released soon?

**Comment by Aurelsicoko** [comment] 2018-10-03 10:09
@yummyelin I would like to... but we have more important things to do for now. I will share a clear roadmap in the coming weeks. We have to make a lot of architecture improvements to be able to release this kind of features in the future. However, I can confirm that this feature is one of our top priorities with the "Administrators and Permissions" plugin 👍

**Comment by wyamout** [comment] 2018-11-05 05:57
@Aurelsicoko hope this will be coming soon, being able to have a customized cms is why many users choosing to move away from wordpress.

**Comment by Aurelsicoko** [comment] 2018-11-09 16:40
Feel free to upvote the feature on Product Board and give me more insights (see https://portal.productboard.com/strapi/c/13-administration-menu). I'm closing this issue because we're going to implement it. However, feel free to comment or ping me if needed.

**Closed by Aurelsicoko** 2018-11-09 16:40 UTC
Labels: priority: medium, type: feature request 🙏

**Comment by zysc8313** [comment] 2020-08-29 05:06
When the settings manager will be release? It's been two years

**Comment by Aurelsicoko** [comment] 2020-09-03 16:32
The Settings Manager has been removed a year ago, and you now have to use the configurations files to edit the configurations of your project. Regarding the Menu, we have nothing in our backlog to facilitate its customization. Even if some of you asked for it, it isn't a priority for the project as there are more important things to do such as internationalization, migration between environment, make Strapi more customizable, etc.

**Comment by wyamout** [comment] 2020-10-03 17:26
@Aurelsicoko that feature should be a priority as having 70 items in an admin menu without the possibility to categorize them doesn't make any sense. All clients complained about that. Hope that would be considered soon. ♥

**Comment by gustavoFreireS** [comment] 2020-10-11 07:04
it's actually possible to do so, inside the strapi-app edit the `/node_modules/strapi-admin/admin/src/components/LeftMenu/LeftMenuLinkSection/index.js` there you can implement a custom filter to categorize items the way you want (remember that you have to rebuild the app to view the changes)

**here is just put the phrase 'this can be achieved' just to show that you can customize the menu content that way**
<img width="238" alt="Captura de Tela 2020-10-11 às 04 02 07" src="https://user-images.githubusercontent.com/8769796/95672367-95ab2580-0b76-11eb-893b-a3aaa5d048cf.png">

**Comment by MattieBelt** [comment] 2020-10-12 13:48
Hey @gustavoFreireS,

When overwriting the admin panel, you best could use [admin extensions](https://strapi.io/documentation/v3.x/concepts/customization.html#admin-extension) to preserve the changes and not need to edit the `node_modules` over and over again.

 You should copy `/node_modules/strapi-admin/admin/src/components/LeftMenu/LeftMenuLinkSection/index.js` to
`./admin/src/components/LeftMenu/LeftMenuLinkSection/index.js` if I'm correct.

**Comment by derrickmehaffy** [comment] 2020-10-13 17:45
Yes that's correct @MattieBelt

**Comment by JuanDiegoAW** [comment] 2021-06-23 18:17
This might not be the best solution, but I found a way to customize and classify the left menu resources. The final result looks like this: 

![Screenshot from 2021-06-23 11-58-12](https://user-images.githubusercontent.com/22400411/123145691-5548ba80-d41a-11eb-9fcf-f50fe8df295e.png)

In order to do it, I had to overwrite this file: [](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/containers/LeftMenu/index.js). On it, I created custom arrays with the CollectionTypeLinks I wanted to classify in the different sections, like this:

![Screenshot from 2021-06-23 12-09-53](https://user-images.githubusercontent.com/22400411/123147168-f4ba7d00-d41b-11eb-9d36-fa3e4689d429.png)

And then, in the same file, I manually added more elements to the LinksContainer wrapper that is being returned, with the arrays created above:

![Screenshot from 2021-06-23 12-10-21](https://user-images.githubusercontent.com/22400411/123147290-1582d280-d41c-11eb-97bf-6ebd4b39af92.png)

As you can see, each "LeftMenuLinksSection" component has an attribute called "section" and another one called "name". Those define the title of the section you are classifying the resources in. In order to make them work, you will also need to overwrite this file: [](https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/components/LeftMenu/LeftMenuLinkHeader/messages.json). On it, you need to add an object with the same name of the one you put in the "section" and "name" attributes on the index.js file. It will look something like this:

![Screenshot from 2021-06-23 12-16-06](https://user-images.githubusercontent.com/22400411/123147927-de60f100-d41c-11eb-90d6-1b79f6404ba3.png)

It is there where you define the title of your custom sections (on the "defaultMessage" attribute). And with that you can create your custom menu!

**Comment by bhavana-vs** [comment] 2021-06-24 17:56
@JuanDiegoAW  i am getting this error when followed your steps can you help me with this!!


<img width="409" alt="error" src="https://user-images.githubusercontent.com/86106185/123310170-6b9e6580-d543-11eb-8abc-131f3082fc59.png">

**Comment by JuanDiegoAW** [comment] 2021-06-24 18:27
@bhavana-vs the "id" property is defined in the **messages.json** file (https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/components/LeftMenu/LeftMenuLinkHeader/messages.json). You need to overwrite this file, and  add a new object in it with the same name that you are putting in the "name" and "section" properties of the "LeftMenuLinksSection" in your index.js file (https://github.com/strapi/strapi/blob/master/packages/strapi-admin/admin/src/containers/LeftMenu/index.js). I could help you a bit better if you share your index.js and messages.json files!

**Comment by bhavana-vs** [comment] 2021-06-25 05:10
@JuanDiegoAW ,I have done every single step you suggested ,still getting this,let me share my code snippets with you..
this is my index.js

<img width="389" alt="index" src="https://user-images.githubusercontent.com/86106185/123372617-89021c80-d5a1-11eb-8efc-0e60b8ef5d5c.png">

<img width="690" alt="Screenshot 2021-06-25 at 10 28 03 AM" src="https://user-images.githubusercontent.com/86106185/123372655-99b29280-d5a1-11eb-8f3f-2d8848475d9e.png">

and here is message.json
<img width="491" alt="message" src="https://user-images.githubusercontent.com/86106185/123372717-b2bb4380-d5a1-11eb-9fc2-2848fb5d91cc.png">

**Comment by JuanDiegoAW** [comment] 2021-06-25 15:57
@bhavana-vs Yes, everything seems to be fine. Just make sure the paths of the messages.json file is written correctly or it won't get overrided:

![Screenshot from 2021-06-25 09-52-27](https://user-images.githubusercontent.com/22400411/123452308-856b9700-d59b-11eb-8185-8ae6a85140cd.png)

And make sure you have built the project with **npm run build** before trying to see the changes.

**Comment by bhavana-vs** [comment] 2021-06-26 14:06
@JuanDiegoAW  my folder structure is same as yours! can you think once again,if forgot any step to mention,i need this feature to implement,it is really important!!

**Comment by JuanDiegoAW** [comment] 2021-06-26 20:15
@bhavana-vs I doubled checked, and yes. Every step needed to customize the left menu panel was included in the description I gave above. However, I created a quick repository showcasing a customized menu that should look like this:

![Screenshot from 2021-06-26 14-13-49](https://user-images.githubusercontent.com/22400411/123524613-cdb4b300-d688-11eb-8a7c-4779319c435b.png)

You can find it here: https://github.com/JuanDiegoAW/strapi-custom-menu-sample. I tested it, so you should've have any problems with it. 

I remind you once again that, in order to make everything work, **you need to build the admin panel before running the application**. You can find more information [here](https://strapi.io/documentation/developer-docs/latest/development/admin-customization.html#admin-extension), but I build the project with **npm run build**. If you still have any problems with it, feel free to write me. Good luck!

**Comment by AnjaliNirmala** [comment] 2021-12-21 15:32
> I already made some research on this part. Here a preview of what we could imagine defining a custom menu according to the user role.
> 
> ![settings manager - menu](https://user-images.githubusercontent.com/4144726/42992261-53487228-8c08-11e8-95b1-a3c5d1764c3e.png)



> I already made some research on this part. Here a preview of what we could imagine defining a custom menu according to the user role.
> 
> ![settings manager - menu](https://user-images.githubusercontent.com/4144726/42992261-53487228-8c08-11e8-95b1-a3c5d1764c3e.png)

I am new to Strapi. I have a doubt. I want to add icons to my collection- type. How can I do that?

**Comment by robclancy** [comment] 2023-07-20 14:09
This issue is concerning. (this was funny though, considering this is a "customization" everyone wants `not doing because "make Strapi more customizable, etc."`.

The concerning part isn't that this basic thing that is clear that is needed if you have more than like 7 collections. The concerning part is that not only is it seen as not an issue with strapi by the people in charge (directus has it which is making me regret the decision to move to strapi) but there is also no discussion or reasoning of why. It's just "nah not doing it" and close the issue.  
It also makes me feel like the people making strapi don't actually use strapi outside of small example sites. Or that they never have a client or someone who only uses the CMS (and not someone who made the fields) using strapi. It would explain a bunch of other weird UX issues.

If the workarounds don't work well enough or are too convoluted then we will just cut our losses and go back to directus.

**Comment by derrickmehaffy** [comment] 2023-07-20 15:21
> This issue is concerning. (this was funny though, considering this is a "customization" everyone wants `not doing because "make Strapi more customizable, etc."`.
> 
> The concerning part isn't that this basic thing that is clear that is needed if you have more than like 7 collections. The concerning part is that not only is it seen as not an issue with strapi by the people in charge (directus has it which is making me regret the decision to move to strapi) but there is also no discussion or reasoning of why. It's just "nah not doing it" and close the issue.  
> It also makes me feel like the people making strapi don't actually use strapi outside of small example sites. Or that they never have a client or someone who only uses the CMS (and not someone who made the fields) using strapi. It would explain a bunch of other weird UX issues.
> 
> If the workarounds don't work well enough or are too convoluted then we will just cut our losses and go back to directus.

This issue is quite old and quite a bit has changed with the project and company since then. We do have several feature requests related to this on https://feedback.strapi.io

Just because it's not in an issue doesn't mean we won't do it. Our GitHub issues are only for bug reports.

Feature requests and enhancements are on our feedback site.
