### ISSUE TITLE
Server constantly restarts after installation

### ISSUE THREAD

**Issue by tamasangyan** [strapi/strapi#6806] opened 2020-06-25 13:40 UTC
**Describe the bug**
Hello,
I'm opening this issue, because after
```
npx create-strapi-app my-project --quickstart
```
Strapi starts a development environment and opening the admin, but it constantly restarts the server leaving only this in the debug.log
```
[0625/152410.745:ERROR:crash_report_database_win.cc(469)] failed to stat report
```

**Steps to reproduce the behavior**
Well the only command I used is the one that is in the quickstart
```
npx create-strapi-app my-project --quickstart
```

**System**
Strapi version is: 3.0.5
NodeJS version is: 12.16.1 //also tried with 14.4
NPM version is: 6.13.4 //also tried with yarn
Database: SQLlite
Operating system: tried with Win 10 and WSL as well

**Expected behavior**
Expected behavior would be a running development environment with autorefresh.

**Comment by derrickmehaffy** [comment] 2020-06-25 15:52
References to this error point to chrome, this doesn't appear to be a Strapi issue.

FYI Node.js v14 (and whatever version of NPM it ships with) is not supported, only v12 or v10 is supported.

Going to mark this as closed as I could not reproduce this on Windows 10 2004 (and WSL/WSL2)

**Closed by derrickmehaffy** 2020-06-25 15:52 UTC

**Comment by tamasangyan** [comment] 2020-06-25 17:54
Thank you, Chrome was the issue, after changing browser it works like charm.
