### ISSUE TITLE
Oauth Redirect URI mismatch

### ISSUE THREAD

**Issue by lancevo** [strapi/strapi#707] opened 2018-02-27 03:40 UTC
**Node.js version**: 9.6.1

**npm version**: 5.6

**Strapi version**: 3@alpha 10.2

**Operating system**: mac os x

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
the port number in config/**/server.js is included in the oauth redirect uri, which causing problem for redirect uri. For example: the server is deployed to heroku, and heroku assigned a random port number 58743, and this port is mapped to https://mystrapi.herokuapp.com. When user redirected to /connect/google, after verification, google thrown error because uri passed to google oauth is http://mystrapi.herokuapp.com:58743/connect/google/callback is not matched as the one defined in google api console mystrapi.herokuapp.com:58734/connect/google/callback

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Deploy strapi to heroku, or any cloud platform. Go to strapi..../connect/google

**What is the expected behavior?**
it should correctly return to a predefined callback url as such https://mystrapi.herokuapp.com/connect/google/callback

**Comment by lancevo** [comment] 2018-02-27 03:45
By the way, is grant.json still needed? (see https://strapi.io/documentation/guides/authentication.html#providers) I think the doc is out dated. 
It'd be awesome if there's an article show how to hook this up in javascript rather than react. 
Thanks so much. Strapi is awesome!!

**Comment by lauriejim** [comment] 2018-02-27 09:04
@lancevo Yes you are right ! We have to update it.

**Comment by bsthomsen** [comment] 2018-03-09 01:03
An additional issue is that it doesn't respect the protocol used. For example if you call:
https://domain.tld/connect/facebook/ it will still send you to http://domain.tld/connect/facebook/callback:1337

**Comment by bsthomsen** [comment] 2018-03-09 01:17
A suggested fix could be to change this line:
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L141

To use the same switch/case in that tells the redirect_uri you should enter on a certain provider:
https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/admin/src/components/PopUpForm/index.js#L44-L58

Then the value would be correct as this:
https://imgur.com/a/oG50h

**Comment by simov** [comment] 2018-03-14 14:50
The idea in the underlying OAuth middleware (Grant) is to have your entire configuration based on your environment, meaning that if you have the following configuration:

```js
{
  "development": {
    "server": {
      "protocol": "http",
      "host": "localhost:1337"
    }
  },
  "production": {
    "server": {
      "protocol": "https",
      "host": "mystrapi.herokuapp.com"
    }
  }
}
```

Then in `strapi-plugin-users-permissions` you have to use the correct `protocol` and `host` options based on your environment.

---

Grant also supports [redirect_uri](https://github.com/simov/grant/blob/v4.0.0/lib/utils.js#L6-L16) option:

```json
{
  "google": {
    "redirect_uri": "https://mystrapi.herokuapp.com/connect/google/callback"
  }
}
```

With it end-users can completely bypass any option set under the `server` key. The sole purpose of the `protocol`, `host` and optionally the `path` options under the `server` key is to generate the correct `redirect_uri` for all of your providers. The `server` key in itself is not even required, you can specify any option found in it directly inside each individual provider's configuration. Also each option specified directly for a provider overrides the corresponding option set under the `server` key.

Hope that helps.

**Comment by soupette** [comment] 2018-06-20 07:48
I'm closing the issue, here's the [documentation](https://github.com/strapi/strapi-examples/tree/master/login-react) associated on how to work with custom providers

**Closed by soupette** 2018-06-20 07:48 UTC
Labels: priority: medium, status: have to reproduce, type: bug 🐛, type: documentation 📖

**Comment by thiagoterleski** [comment] 2019-05-02 21:16
I was going to open a new issue but I found this one, it might be related, I'm still having trouble with auth redirect_url:

**Informations**
- **Node.js version**: 10.14.1
- **NPM version**: 6.4.1
- **Strapi version**: 3.0.0-alpha.26
- **Database**: Mongo
- **Operating system**: 


Strapi is using localhost URL in production to redirect to google and facebook auth.

The google auth is running well in my localhost, but when I try to test it in production, the application redirects me to the google with a wrong `redirect_uri` param:
<img width="459" alt="Screen Shot 2019-05-02 at 1 44 31 PM" src="https://user-images.githubusercontent.com/2950918/57106554-8fa6e900-6ce2-11e9-9c99-e86858dcb166.png">

My configurations are right, I'm running the app in production mode, the database is right, but I have no idea why it's using localhost instead of the correct site URL.

<img width="734" alt="Screen Shot 2019-05-02 at 2 00 12 PM" src="https://user-images.githubusercontent.com/2950918/57106677-e44a6400-6ce2-11e9-870a-6201481c0f39.png">

I tested the same app in two different env, same problem, only different ports, so it seems that it only occurs in production mode. Testing it locally is fine.

<img width="802" alt="Screen Shot 2019-05-02 at 2 03 48 PM" src="https://user-images.githubusercontent.com/2950918/57106781-1f4c9780-6ce3-11e9-97dc-e08b3d6b16e7.png">

**Comment by JamesHMcKay** [comment] 2019-06-02 00:39
I have exactly the same issue as described in the above comment.  Did you find any solution for this @thiagoterleski ?

I have tried the latest beta version and get the same issue, for both Facebook and Google providers I get redirected to a **random localhost port,** but only when using Strapi deployed to Heroku.

Any suggestions would be really appreciated. Thanks!

**Comment by lauriejim** [comment] 2019-06-10 15:20
For Google it can be caused by this issue https://github.com/strapi/strapi/issues/2660
And for Facebook, I followed the documentation few days ago and it works well.
Can you check with the `login` example app - https://github.com/strapi/strapi-examples/tree/master/login-react

**Comment by JamesHMcKay** [comment] 2019-06-11 00:10
Hi @lauriejim 

The example is great, and works really well with everything setup locally.  But try deploying somewhere and you might see these issues.

A related issue is that the box at the bottom of the providers dialog (the one that says "the redirect url to add in to your google application configurations") is wrong.  So even if you properly configure your production server address it will still point to sever:port/connect/google/callback.  Which I imagine for many is an issue, since server:port may not actually be accessible (Heroku is one example).
