### ISSUE TITLE
Migrating 3.6.0 now is not starting; downgrading 3.5.4 solves the issue

### ISSUE THREAD

**Issue by jacargentina** [strapi/strapi#10096] opened 2021-04-22 03:52 UTC
### Describe the bug

 strapi start
[2021-04-22T03:47:57.940Z] debug ⛔️ Server wasn't able to start properly.
[2021-04-22T03:47:57.941Z] error MongoError: BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'

### Steps to reproduce the behavior

1. upgrade Strapi from 3.5.4 to 3.6.0
2. strapi start
### Expected behavior

Just run

### System

- Node.js version: 12.18.2
- NPM version: 
- Strapi version: 3.6.0
- Database: mongoDB
- Operating system: Linux

**Comment by derrickmehaffy** [comment] 2021-04-22 04:19
> BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'

Are you using a custom field type or can you give the structure of this model?

**Comment by jacargentina** [comment] 2021-04-22 15:41
@derrickmehaffy  i'dont have any "update" or "updates" model, so I can't truly understand why this happens.

<img width="370" alt="Captura de Pantalla 2021-04-22 a la(s) 12 40 53" src="https://user-images.githubusercontent.com/517228/115743414-0920c180-a368-11eb-80cf-70c154f397c6.png">

**Comment by spijs** [comment] 2021-04-23 06:09
Same issue here, so definitely can reproduce. Any update yet?

**Comment by shivagouraram** [comment] 2021-04-23 18:14
I too encountered the same issue after migrating to 3.6.0. The update model does not exist on my api as well, it could be something maintained by Strapi internally or may be a new addition.

**Comment by ririen** [comment] 2021-04-23 18:22
I experienced an identical problem. The latest version started correctly only after the database was created completely from scratch. When the database was empty, it would normally connect and work.

**Comment by jacargentina** [comment] 2021-04-23 22:52
Maybe there is somehing specific to mongo (server, driver, etc....) or mongoose....

https://jira.mongodb.org/browse/NODE-2428

**Comment by spijs** [comment] 2021-04-26 07:43
Can confirm that the mongo version is the issue. I upgraded from 4.0 to 4.2.13 and issue is gone.
See --> https://stackoverflow.com/questions/56814957/mongodb-update-operation-with-aggregation-pipeline-results-in-error-code-14

**Comment by jacargentina** [comment] 2021-04-26 12:34
@spijs maybe you problem is different to this issue; I've updated to mongodb 4.4.4, and the error persists.

**Comment by fouss** [comment] 2021-04-27 07:50
same error for me (on prod env, everything is fine locally for me). Rollback to 3.5.4 solve the issue but it's not a real solution :s

**Comment by derrickmehaffy** [comment] 2021-04-27 18:30
Can anyone please give me a fresh project (either git repo or zipped project excluding node_modules, build, and .cache) reproducing the repo. Bonus points if you can take a mongodb dump of the database also.

**Comment by jacargentina** [comment] 2021-04-29 12:48
@derrickmehaffy cannot share my code, but i can help trying to search for the stack trace; any ideas on how to get to it? Can i enable some flag on strapi before start to get a full stack trace ?

**Comment by derrickmehaffy** [comment] 2021-04-29 20:36
> @derrickmehaffy cannot share my code, but i can help trying to search for the stack trace; any ideas on how to get to it? Can i enable some flag on strapi before start to get a full stack trace ?

I don't need your code, only a test project that someone can provide the exact reproduction steps.

**Comment by jacargentina** [comment] 2021-04-29 21:09
Building a test project can take some time; and you know: sometimes that test project just works.... so trying to build a test project may take much more time than simply getting the stack trace!

**Comment by derrickmehaffy** [comment] 2021-04-29 21:14
> Building a test project can take some time; and you know: sometimes that test project just works.... so trying to build a test project may take much more time than simply getting the stack trace!

I am not aware of any option to get a more detailed stack trace

**Comment by jacargentina** [comment] 2021-04-30 11:51
https://github.com/strapi/strapi/blob/a683540105e5f1f82d9882055686ef0eb291e96c/packages/strapi-admin/config/migrations/permissions-fields-to-properties.js#L94
I think this line causes the thing, I'm suspecting that mongoose 5.10.8 (strapi-connector-mongoose) is too old for supporting passing an array as the second parameter?

**Comment by rogermori** [comment] 2021-05-05 19:39
I am experiencing the same behavior reported by @jacargentina after upgrading Strapi to 3.6.0 and 3.6.1.
Strapi 3.6.X does not work connecting to a MongoDB Atlas cluster version 4.0.24; however, Strapi 3.6.X works with a similar cluster version 4.4.5

**Comment by derrickmehaffy** [comment] 2021-05-07 17:45
> https://github.com/strapi/strapi/blob/a683540105e5f1f82d9882055686ef0eb291e96c/packages/strapi-admin/config/migrations/permissions-fields-to-properties.js#L94
> 
> 
> I think this line causes the thing, I'm suspecting that mongoose 5.10.8 (strapi-connector-mongoose) is too old for supporting passing an array as the second parameter?
> How can I force my Strapi install to use a newer mongoose dependency? I'm using yarn.

https://stackoverflow.com/questions/40226639/how-do-i-override-nested-dependencies-with-yarn

However we had an automated PR to update the mongoose version and it was failing tests (likely due to breaking changes)
https://github.com/strapi/strapi/pull/10224

And thus we closed it since we don't have time to review the changes to `strapi-connector-mongoose` since we are dropping MongoDB support.

**Comment by jacargentina** [comment] 2021-05-07 17:51
@derrickmehaffy thats baaaaad news. 😔

**Comment by derrickmehaffy** [comment] 2021-05-10 13:16
Issue confirmed by an EE Customer

**Comment by alexandrebodin** [comment] 2021-05-10 15:27
Hi can anyone confirm the fix we just did fixes the issue for you ?

**Comment by derrickmehaffy** [comment] 2021-05-10 20:46
Tested upgrade from 3.5.4 to 3.6.1 on MongoDB 4.0.24 (Docker). Fix works

**Closed** 2021-05-11 07:04 UTC
Labels: meta: EE Customer, severity: high, source: connector:mongoose, status: confirmed, type: bug

**Comment by hkovacs** [comment] 2021-09-17 14:30
> Tested upgrade from 3.5.4 to 3.6.1 on MongoDB 4.0.24 (Docker). Fix works

Hi Derrick,

It would be extremely help to have a notification on the [update page](https://strapi.io/documentation/developer-docs/latest/update-migration-guides/update-version.html#upgrade-your-dependencies) to skip v3.6.0 for mongoose users.

for those of us who arent so active in the strapi world, it helps win the hearts and minds if a version is known to be bad and the strapi team actively informs of it in the right places.

All the best

**Comment by hkovacs** [comment] 2021-09-17 15:02
helpful hint. this issue is only fixed in v3.6.2

so just skip v3.6.0 and 3.6.1 completely.
