### ISSUE TITLE
Unable to have access to component data in lifecycle(beforeUpdate)

### ISSUE THREAD

**Issue by AntoninWD** [strapi/strapi#18047] opened 2023-09-12 18:11 UTC
- Node.js version: v18.17.1
- NPM version: 8.19.2
- Strapi version: 4.12.6
- Database: mysql
- Operating system: Window
- Is your project Javascript or Typescript: Javascript

### Describe the bug

I am currently implementing activity logs in my application. To achieve this, I'm utilizing content type lifecycles to track user activities such as creation, update, and deletion. For creation and deletion, the process is straightforward. However, I'm encountering a challenge with updates.

Specifically, when updating a dealer with an address component, I retrieve the data with all its relations using a "populate" request both before and after the update. Unfortunately, in the beforeUpdate event, the address data is null, whereas in the afterUpdate event, it contains the updated address information.

Upon inspecting the source code, it appears that Strapi is updating the components before the beforeUpdate event, which I believe should ideally occur between the beforeUpdate and afterUpdate events.

I'm curious about why, during the beforeUpdate event, I'm able to access the users relation but not the address component. My assumption is that the Strapi entity service is updating the address component, causing it to be unavailable in the beforeUpdate event.

Feel free to ask for more details.

### Screenshots
![image](https://github.com/strapi/strapi/assets/73403958/6c657484-5c5f-412b-a0ee-52f8170dcc43)
![image](https://github.com/strapi/strapi/assets/73403958/19a8982b-af71-4d8f-b92d-2723074f9da6)
![image](https://github.com/strapi/strapi/assets/73403958/2444faa6-bd6e-4f86-8f66-4082b8d3562f)
![image](https://github.com/strapi/strapi/assets/73403958/8a2e0db9-5ba7-4de1-841d-e653c56d5804)

**Comment by derrickmehaffy** [comment] 2023-09-12 18:14
Closing as not a bug

Duplicate of https://feedback.strapi.io/feature-requests/p/lifecycle-hooks-for-components

**Closed by derrickmehaffy** 2023-09-12 18:14 UTC
