### ISSUE TITLE
Images uploaded in Media Library are blank

### ISSUE THREAD

**Issue by mastoltejr** [strapi/strapi#13858] opened 2022-07-27 04:14 UTC
### Required System information
- Node.js version: node:14
- NPM version: node:14
- Strapi version: 4.2.3
- Database: PostgresSQL
- Operating system: Docker node:14 

### Describe the bug

Hello, I've been using strapi for a few days, however now when I go upload a new image to my media library the image is blank / not there. The filename comes through when I add a new asset but not the image.

I've seen this (post on the forum)[https://forum.strapi.io/t/images-uploaded-in-media-library-automatically-corrupts-after-few-days/2916/4] but I'd prefer to keep using the file system provider rather than an off-site provider.

What makes me scratch my head is the files I've previously uploaded still work fine, show up in the UI, and are available to query using the rest api.

### Steps to reproduce the behavior

Unsure how to reproduce, since it was working fine until it wasn't

### Expected behavior

The image thumbnail should appear in the UI after the image is uploaded and the image should come through the rest api.

### Screenshots

![image](https://user-images.githubusercontent.com/31829871/181159828-51c968f0-5d66-42d6-acb1-262b7aec4166.png)

### Additional context

I've only been using Strapi for a few days, so by no means very knowledgeable. However I think its weird it was working, still is working for old photos, but isn't for new photos.

I've tried restarting my docker container and logging in and out of the admin panel, but to no avail.

**Comment by kasonde** [comment] 2022-07-27 12:51
Duplicate of #11422
HEIC is not an image file format supported by some browsers.

**Closed by kasonde** 2022-07-27 12:51 UTC
