### ISSUE TITLE
zsh: command not found: strapi (plugin development)

### ISSUE THREAD

**Issue by blaasvaer** [strapi/strapi#8889] opened 2020-12-14 15:13 UTC
### Describe the bug

When I try to develop a new plug-in in an already existing (and running) development project, by running:
```
strapi generate:plugin my-plugin
```

I get:
```
zsh: command not found: strapi
```
### Steps to reproduce the behavior

1. Create new project
2. Make a Collection Type or what ever
3. Just make sure the project is up and running (see strapi docs on how to do that)
4. cd into project and run:
```
strapi generate:plugin my-plugin
```
### Expected behavior

I'm not sure what to expect to be happening, but maybe some files would be created in the plugins folder for me to work with (I don't know)?

### Screenshots

This would be a screenshot of the terminal with the error ... wouldn't make much sense.

### Code snippets
```
strapi generate:plugin my-plugin
```
### System

- Node.js version: v14.15.0
- NPM version: 6.14.9
- Strapi version: 3.3.4 Community Edition
- Database: SQLLite
- Operating system: Mac OS X Catalina 10.15.6 (19G73)

**Comment by laurenskling** [comment] 2020-12-15 13:08
when strapi is not installed globally, this is expected behaviour. Try `npm strapi generate:plugin my-plugin` or `yarn strapi generate:plugin my-plugin`.

**Comment by derrickmehaffy** [comment] 2020-12-22 21:06
@laurenskling is correct, marking as closed as this is intended.

**Closed by derrickmehaffy** 2020-12-22 21:06 UTC
