### ISSUE TITLE
cannot finds any plugins to implement WhatsApp and Telegram to send messages from backend.

### ISSUE THREAD

**Issue by MohammedTayibulla** [strapi/strapi#13924] opened 2022-08-01 09:29 UTC
### Required System information

- Node.js version: v16.14.0
- Strapi version: v3.5.0
- Database: MongoDB
- Operating system: windows 10 pro

### Describe the bug

-[] Cannot find plugins to integrate WhatsAapp and Telegram , to send messages from backend using strapi  .

**Comment by RedrumIzBak** [comment] 2022-08-03 14:13
I don't believe this is a worthy of a bug but you may be interested in the following article: https://strapi.io/blog/webhooks

**Comment by bolg55** [comment] 2022-08-09 17:01
Not a bug, closing. @RedrumIzBak suggestion of article should be sufficient

**Closed by bolg55** 2022-08-09 17:01 UTC
