### ISSUE TITLE
Server wasn't able to start properly. - Error: ER_DUP_ENTRY: Duplicate entry for key 'admin_permissions_role_links_unique'

### ISSUE THREAD

**Issue by PaRoxUs** [strapi/strapi#15681] opened 2023-02-02 09:08 UTC
### Required System information

- Node.js version: v18.13.0
- NPM version: 6.14.18
- Strapi version: 4.5.6 and 4.6.0
- Database: MySQL
- Operating system: macOS 13.1 (22C65)

### Describe the bug

After creating a new Content Type in the Builder the server fails to restart.

In the terminal I get this message:

```
[2023-02-02 09:53:24.981] debug: ⛔️ Server wasn't able to start properly.
[2023-02-02 09:53:24.984] error: insert into `admin_permissions_role_links` (`permission_id`, `permission_order`, `role_id`) values (186, 16, 1) - ER_DUP_ENTRY: Duplicate entry '186-1' for key 'admin_permissions_role_links_unique'
Error: ER_DUP_ENTRY: Duplicate entry '186-1' for key 'admin_permissions_role_links_unique'
    at Sequence._packetToError (/path/to/strapi/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/path/to/strapi/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/path/to/strapi/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/path/to/strapi/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/path/to/strapi/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/path/to/strapi/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/path/to/strapi/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/path/to/strapi/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    --------------------
    at Protocol._enqueue (/path/to/strapi/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/path/to/strapi/node_modules/mysql/lib/Connection.js:198:25)
    at /path/to/strapi/node_modules/knex/lib/dialects/mysql/index.js:132:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/path/to/strapi/node_modules/knex/lib/dialects/mysql/index.js:126:12)
    at executeQuery (/path/to/strapi/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/path/to/strapi/node_modules/knex/lib/client.js:146:12)
    at /path/to/strapi/node_modules/knex/lib/execution/transaction.js:363:24
    at new Promise (<anonymous>)
    at trxClient.query (/path/to/strapi/node_modules/knex/lib/execution/transaction.js:358:12)
```
### Steps to reproduce the behavior

1. Create a new content type
2. See the error

### Expected behavior

The server should restart without failing and displaying the new content type.

### Code snippets

If applicable, add code samples to help explain your problem.

### Additional context

I have successfully created content types before! I think this issue started to happen after the update to 4.4.5

If I remove the added schema.json and `npm run develop` the service works again.

**Comment by derrickmehaffy** [comment] 2023-02-02 21:07
duplicate of: https://github.com/strapi/strapi/issues/14978

**Closed by derrickmehaffy** 2023-02-02 21:07 UTC
Labels: status: duplicate
