### ISSUE TITLE
idsToOmit is wrong when opening a relationship select in ContentManager in Strapi 3.4.5

### ISSUE THREAD

**Issue by dappiu** [strapi/strapi#9294] opened 2021-02-02 13:33 UTC
## Bug report

After upgrade from 3.4.4 to 3.4.5, everywhere I have a Content-type that has some simple "x has y" relationship (many-to-many and one-to-many relationship seem to be non affected), when I pull down the select to change the value, I see that the three dots loading indicator is always there and the list of selectable values never loads. Looking at the Strapi output I see that the POST that is made to get the list of values returned a 500 error that says:

`error error: invalid input syntax for type integer: "{ ...full object representation here... }"`

And indeed opening the browser network inspector I see that the request has been made passing the full object repr to the field `idsToOmit`, instead of passing just the numerical ID.

This doesn't happen when the select is multiple (i.e. plural relationship types).
This happens both on develop and production build.

### Steps to reproduce the behavior

Create a content type, add a Relationship field selecting the first kind of relationship (x has y). 
Now insert a record for this content type and select a linked object in the relationship. The first time you should succeed as `idsToOmit` is empty. 
Save, then come back editing the object. Try to change the linked object by opening the relationship select. You should see the error in the browser's network inspector and on Strapi console, and other values are not shown.

### System

- Node.js version: 12.20.0
- NPM version: 6.14.10
- Strapi version: 3.4.5
- Database: PostgreSQL
- Operating system: Linux

**Comment by alexandrebodin** [comment] 2021-02-02 13:41
Hi @dappiu you need to rebuild your admin bundle :) `yarn build --clean`

**Comment by dappiu** [comment] 2021-02-02 13:50
Yes, I always do a clean build on upgrade, but I just checked again to be sure. Also cleaned browser cache. Now I also tried with `yarn develop --watch-admin` and accessing the admin from there, but the problem persists.

**Comment by dappiu** [comment] 2021-02-02 14:32
@alexandrebodin I tried removing everything in extensions/ and admin/ but the problem persists.

Downgrading to Strapi 3.4.4 solves the issue, but I see that the request is made on page load, instead of postponing to when the select box is clicked, the request is a GET instead of POST, and no `idsToOmit` parameter is present.

**Comment by alexandrebodin** [comment] 2021-02-02 15:07
we moved from a simpel get that didn't filter to a post with omit ids so we could remove the already selected items. @petersg83  can you ahve a look at this regression?

**Comment by dappiu** [comment] 2021-02-02 15:19
Tonight I will try to set-up a reproduction repo. 
In the meantime I could say that one could see this behaviour just using the User and Role models, as provided by the users-permissions plugin: Register a new user that will get the Authenticated role by default. Now edit the user with the content-manager and try to change the Role by clicking the select field. The server should return a 500 error on `POST /content-manager/relations/plugins::users-permissions.user/role?_limit=20`

**Comment by petersg83** [comment] 2021-02-02 18:15
Hi :)
I could reproduce the issue with what you wrote just above.
It looks like a front issue where "idsToOmit" is filled with objects instead of ids (string or integer)
![Capture d’écran 2021-02-02 à 19 13 32](https://user-images.githubusercontent.com/11708220/106644019-d5b17080-658a-11eb-82f9-59e890a52275.png)

**Comment by dappiu** [comment] 2021-02-03 10:23
@petersg83 I have the same problem also in my other ContentTypes that are unrelated with the users-permissions plugin. Hope this helps. Thanks for your time!

**Comment by alexandrebodin** [comment] 2021-02-03 13:36
Hi, the fix will be released in v3.4.6

**Closed** 2021-02-03 13:35 UTC
Labels: severity: medium, status: confirmed, type: bug

**Comment by vlad4ernyshov** [comment] 2021-02-07 06:55
Still not working in 3.4.6.

select distinct `categories`.* from `categories` where `categories`.`id` not in (`Chain` = '[object Object]', '[object Object]', `created_at` = '2021-02-07T06:24:45.000Z', `created_by` = NULL, `CustomChain` = , `status` = 'enabled', `updated_at` = '2021-02-07T06:24:45.000Z', `title` = 'Category name', `link` = 'https://www.site.com/catalogue', `id` = 1, `updated_by` = NULL) limit 20
