### ISSUE TITLE
Please upgrade your dependencies and support latest node version.

### ISSUE THREAD

**Issue by raflymln** [strapi/strapi#13631] opened 2022-06-24 11:40 UTC
### Required System information

- Node.js version: 16.15.1
- NPM version: 8.11.0
- Strapi version: v4
- Database: mysql
- Operating system: Ubuntu 18.04

### Describe the bug

When you tried to install strapi through `create-strapi-app@latest my-project`, it's always falling through an error every time i tried to install the dependencies. Most of it was `Unexpected end of JSON input while parsing empty string in {dependencies path}`

Also Node version should support v17 and upper since there's a lot of new features in the latest version.

**Comment by bolg55** [comment] 2022-06-24 15:15
Duplicate of #13627

**Closed by bolg55** 2022-06-24 15:15 UTC
