### ISSUE TITLE
Removing port in server.json 

### ISSUE THREAD

**Issue by leonidax** [strapi/strapi#4789] opened 2019-12-21 13:47 UTC
I'm using nginx as a reverse proxy.

If I upload a file in my production enviroment it works but it displays the link wrong, I found out that this was because the server.json host variable was still in localhost. I changed it and worked properly but I also need to remove the port from the link, thus I left the port string empty and the port has not been removed from the link.

1. Deploy a strapi website with the server prdocution default configuration
2. Change the host name to the one used for the DNS
3. Replace the port variable with an empty string
4. Upload a file and notice that the port is still appended to the image url when copied or by clicking in the file "eye" icon.

![image](https://user-images.githubusercontent.com/1274112/71308759-9a90c400-2400-11ea-865b-b02ce774db4a.png)

`{
  "host": "foo.com",
  "port": "",
  "production": true,
  "proxy": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false
  }
}`

**Expected behavior**
The url should not have the port.

**Screenshots**

**Code snippets**
If applicable, add code samples to help explain your problem.

**System**
- Node.js version: v10.17.0
- NPM version: 6.11.13
- Strapi version: v3.0.0-beta.17.8
- Database: Postgres
- Operating system: Ubuntu 18.04

**Comment by derrickmehaffy** [comment] 2019-12-21 21:04
https://strapi.io/documentation/3.0.0-beta.x/concepts/configurations.html#server

You need to use the proxy option, which was specifically designed to do this (note your normal host and port should remain localhost and whatever internal port you are using)

Marking as closed as this is not a bug but a configuration problem

**Closed by derrickmehaffy** 2019-12-21 21:04 UTC

**Comment by leonidax** [comment] 2019-12-22 21:49
By adding the proxy information I achieved right what I wanted.

Thanks for pointing me out to the right direction.

**Comment by derrickmehaffy** [comment] 2019-12-23 02:43
Glad I could help :smiley:

**Comment by AhmNasr** [comment] 2020-10-12 20:14
Excuse me I use the proxy but its not work, please check this:

{
  "host": "0.0.0.0",
  "port": "${process.env.PORT || 2337}",
  "proxy": {
    "enabled": true,
    "ssl": true,
    "host": "test123.com",
    "port": "1234"
  },
  "autoReload": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false
  }
}

I try to open https://test123.com:1234/
but its work

also I try to remove port from proxy section to be like that:

{
  "host": "0.0.0.0",
  "port": "${process.env.PORT || 2337}",
  "proxy": {
    "enabled": true,
    "ssl": true,
    "host": "test123.com"
  },
  "autoReload": {
    "enabled": false
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false
  }
}
and host:
https://test123.com/


But also not work

please please help

**Comment by derrickmehaffy** [comment] 2020-10-12 23:34
Hello!

Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.

Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.

Thank you and have a good day.

**Comment by AhmNasr** [comment] 2020-10-13 03:46
> Hello!
> 
> Can you please create a new GitHub issue by using the GitHub issue template, providing all required information.
> 
> Your issue looks related to that topic but it's an old one. Using another thread (GitHub issue) will be able to manage your case.
> 
> Thank you and have a good day.

Thanks for your response, but my problem its I dont know how to config the server.json, just thats it
Also the Strapi version is Beta and Alpha and you dont support it but please please helping brother

If that not worked in versions Beta and Alpha tell me "that bug and we will not support it" and I will not sad
but if you can do anything please please help I very very need it in my work for my job

and very very sorry if I bother you but I swear I need any help for my work, if no problem about my old versions to create new issue I will create otherwise please please any help as helping humane

**Comment by derrickmehaffy** [comment] 2020-10-13 17:48
@AhmNasr Sorry but as you stated we no longer support the Beta or Alpha versions, per our security policy: https://github.com/strapi/strapi/security/policy

Any usage of a version before v3.0.0-stable is "at your own risk" and no support will provided, you will need to update your application to the stable version.
