### ISSUE TITLE
Unable to access Content Manager as Super Admin local and production after switching between two single types multiple times

### ISSUE THREAD

**Issue by esraasaadyassir** [strapi/strapi#17517] opened 2023-07-31 14:06 UTC
## Bug report

Unable to access Content Manager as Super Admin local and production after switching between two single types multiple times

### Required System information

- Node.js version: v16.19.0
- NPM version: 8.19.3
- Strapi version: 4.11.7
- Database: PostgreSQL
- Operating system: Mac
- Is your project Javascript or Typescript: Typescript

### Describe the bug

Trying to switch between two single types collection quickly for an average of 4- 8 times then I got this warning
Warning: You're not allowed to see this document

### Steps to reproduce the Behavior

1. Go to Content-type builder and create 2 single collection type
2. Click on content manager and try to switch between the two single collection types quickly and for average of 4-8 times
3. See warning that "Warning: You're not allowed to see this document"

### Expected Behavior

I should be able to switch between them quickly with no issues

**Comment by gu-stav** [comment] 2023-07-31 14:07
Closing as duplicate of https://github.com/strapi/strapi/issues/17254

**Closed by gu-stav** 2023-07-31 14:07 UTC
