### ISSUE TITLE
Can't install Strapi: "Error while installing dependencies"

### ISSUE THREAD

**Issue by adrianthedev** [strapi/strapi#12179] opened 2022-01-11 20:04 UTC
## Bug report

Can't install strapi with `npx create-strapi-app@latest strapi-test`.

### Describe the bug

The installer fails to fin package `@fortawesome/fontawesome-free`

### Steps to reproduce the behavior

1. Run `npx create-strapi-app@latest strapi-test`

### Expected behavior

It should install strapi.

### System

- Node.js version: v14.18.1
- Yarn version: 1.22.10
- Strapi version: v4
- Database: default
- Operating system: macos monterey

<details>
<summary>Full output</summary>

```
npx create-strapi-app@latest strapi-test
npx: installed 104 in 19.183s
? Choose your installation type Quickstart (recommended)
Creating a quickstart project.
Creating a new Strapi application at /Users/adrian/work/misc/strapi-test.
Creating files.
Error while installing dependencies:
warning @strapi/strapi > koa-ip > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning @strapi/strapi > @strapi/generate-new > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @strapi/strapi > koa-session > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning @strapi/strapi > koa-body > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
warning @strapi/strapi > @strapi/admin > node-polyfill-webpack-plugin > url > querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @strapi/strapi > @strapi/plugin-email > @strapi/provider-email-sendmail > sendmail > mailcomposer@3.12.0: This project is unmaintained
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning @strapi/strapi > @strapi/plugin-email > @strapi/provider-email-sendmail > sendmail > mailcomposer > buildmail@3.10.0: This project is unmaintained
error Couldn't find package "@fortawesome/fontawesome-free@^5.15.3" required by "@strapi/admin@4.0.4" on the "npm" registry.
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @strapi/strapi > @strapi/generators > plop > liftoff > findup-sync > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
Error: Couldn't find package "@fortawesome/react-fontawesome@^0.1.14" required by "@strapi/admin@4.0.4" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@fortawesome/free-solid-svg-icons@^5.15.3" required by "@strapi/admin@4.0.4" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@fortawesome/free-brands-svg-icons@^5.15.3" required by "@strapi/admin@4.0.4" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@fortawesome/fontawesome-svg-core@^1.2.35" required by "@strapi/admin@4.0.4" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@fortawesome/fontawesome-svg-core@^1.2.35" required by "@strapi/helper-plugin@4.0.4" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@fortawesome/free-brands-svg-icons@^5.15.2" required by "@strapi/helper-plugin@4.0.4" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@fortawesome/free-solid-svg-icons@^5.15.3" required by "@strapi/helper-plugin@4.0.4" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@fortawesome/react-fontawesome@^0.1.14" required by "@strapi/helper-plugin@4.0.4" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Couldn't find package "@fortawesome/fontawesome-free@^5.15.2" required by "@strapi/helper-plugin@4.0.4" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:721:66)
    at new MessageError (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:310:30)
    at /usr/local/Cellar/yarn/1.22.10/libexec/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

 Keep trying!

Oh, it seems that you encountered errors while installing dependencies in your project.
Don't give up, your project was created correctly.
Fix the issues mentioned in the installation errors and try to run the following command:

cd /Users/adrian/work/misc/strapi-test && yarn install
```

</details>

![image](https://user-images.githubusercontent.com/1334409/149012726-bd77f229-9d78-447a-87d1-8882809ff766.png)

**Comment by kasonde** [comment] 2022-01-11 21:46
Currently can't reproduce this nor do I know of any reason this wouldn't work in the latest version of Strapi.

**Comment by derrickmehaffy** [comment] 2022-01-11 22:25
This looks like the user isn't using the normal npm registry as that package certainly exists. Closing until the user can provide more information.

**Closed by derrickmehaffy** 2022-01-11 22:25 UTC
Labels: status: can't reproduce

**Comment by adrianthedev** [comment] 2022-01-12 08:41
I have a Font Awesome license and setting that up requires a custom `@fortawesome:registry` entry.

The fix was `npm config delete @fortawesome:registry`. Now strapi is installing.

Thank you for the support.

**Comment by 13milliseconds** [comment] 2022-01-27 20:52
In my case it was happening on Heroku and cause by the yarn.lock file that was committed.

**Comment by bmikaili** [comment] 2022-11-17 20:22
I am getting this on a regular M1 Pro macbook. No special setup. Using default npm/yarn registry. Unfortunately makes strapi completely unusable for us.
