### ISSUE TITLE
403 on a `GET` request to `users-permissions/init`

### ISSUE THREAD

**Issue by lorenries** [strapi/strapi#4286] opened 2019-10-18 14:02 UTC
**The bug**
Running my Strapi project locally with `npm run develop` works perfectly. Once I deployed to production (a Docker container running in AWS Fargate connected to a MySQL database in AWS Aurora, I'm unable to register a superuser. I've seen previous issues reporting this bug (#4267, #4279, #3284), but [the patch](https://github.com/strapi/strapi/pull/4246) in `17.1` did not fix the issue.

I was able to fix this issue by connecting to the production database and changing a value in the `user-permissions_permissions` table.

The value of `role` was set to `1` in the production database:

<img width="707" alt="Screen Shot 2019-10-18 at 9 55 28 AM" src="https://user-images.githubusercontent.com/17712866/67100368-87a60d00-f18d-11e9-81bf-04888847b957.png">

Changing the value of `role` to `2` resolved the `403`.

**Steps to reproduce the behavior**
1. Deploy a new strapi project to AWS Fargate with a MySQL database in Aurora
2. Go to `/admin`
3. See a spinner that doesn't go away
4. Open the console and see a `403` on a request to `/users-permissions/init`

**Expected behavior**
I expect to see the super user registration screen.

**System**
- Node.js version: `10.15.0`
- Strapi version: `^3.0.0-beta.17.1`
- Database: `mysql`
- Operating system: `Docker`

**Comment by derrickmehaffy** [comment] 2019-10-18 14:21
do ensure that your package.json doesn't actually have `^3.0.0-beta.17.1` it needs to be `3.0.0-beta.17.1`

Most likely if you check your lock files with the carrot `^` you are actually installing a @next tag and not an @beta tag.

However I am closing this as it is a duplicate of: https://github.com/strapi/strapi/issues/4267

Please do check the open issues before creating a new one. Thank you

**Closed by derrickmehaffy** 2019-10-18 14:21 UTC

**Comment by pravosleva** [comment] 2019-11-23 00:07
Same problem in `3.0.0-beta.17.4`
