### ISSUE TITLE
Review Workflows : sticky header hides SubNav but not stages

### ISSUE THREAD

**Issue by MarionLemaire** [strapi/strapi#20211] opened 2024-04-25 14:21 UTC
### Required System information

- Node.js version: 20.9.0
- NPM version: 10.1.0
- Strapi version: 0.0.0-experimental.04d28a073af6fa6a173e2212fa8593a4df25efbf  (v5)
- Operating system: Windows

### Describe the bug

In Settings section, 
In Review Workflow section,
When creating a new Review workflow, there's a wrong blank header displayed when you scroll down to reach last stages : 
![image](https://github.com/strapi/strapi/assets/97893822/b479a240-9e6b-4970-9a1f-a781e4656dbd)

It's also the case when you read an existing workflow with deployed stage sections. Sticky header hides SubNav but not the stages.

![image](https://github.com/strapi/strapi/assets/97893822/c6ab149f-c678-473f-b5b2-e43ca15bb711)

### Steps to reproduce the behavior

https://www.loom.com/share/dfbc1a02738c400f8457a00e07a5e170?sid=eed6ef02-b1fe-4aa1-841c-d7768d513843

1. Go to Settings
2. Click on Review Workflows
3. Edit a workflow or create a new one
4. Deploy the stages sections
5. Scroll down and check the header

### Expected behavior

This blank header shouldn't be displayed

**Comment by yurimutti** [comment] 2024-04-25 20:02
Hello, can assign to me ?

**Comment by derrickmehaffy** [comment] 2024-04-25 20:28
> Hello, can assign to me ?

We don't assign issues, if you want to do a fix just open a pull request

**Comment by yurimutti** [comment] 2024-04-30 09:46
Hello @derrickmehaffy, we have a development user or another approach to see all features? 
<img width="1303" alt="image" src="https://github.com/strapi/strapi/assets/66539821/e2a4f0bc-d9ff-4880-b818-fc44ef35c621">

**Comment by alexandrebodin** [comment] 2024-06-06 10:01
I can't reproduce this on beta-9 on mac.

**Comment by remidej** [comment] 2024-06-25 15:39
fixed by #28563

**Closed by remidej** 2024-06-25 15:39 UTC
Labels: issue: bug, severity: medium, status: confirmed, source: core:review-workflows, version: 5
